### ISSUE TITLE
TLT Examples

### ISSUE THREAD

**Issue by turowicz** [triton-inference-server/server#1854]
Can we get an official information how to use Nvidia Transfer Learning Toolkit in Triton?

Example network:
https://ngc.nvidia.com/catalog/models/nvidia:tlt_pretrained_object_detection

I believe that because both TRTIS and TLT  are coming from Nvidia, they should be able to play nice together. Unfortunately I haven't been able to host any TLT models in TRTIS so far.

**Comment by efrats** [comment]
The workflow for taking TLT model into Triton is through tlt-converter. Download the appropriate tlt-converter based on platform/CUDA version from TLT Getting started page or from below, convert the TLT model to TensorRT engine and then provide TensorRT engine to Triton.
 
For deployment with NVIDIA Jetson, download the tlt-converter file to convert the model from UFF to TensorRT engine
JetPack4.4 TensorRT 7.1
JetPack4.2.2 TensorRT 5.1
JetPack4.3 TensorRT 6.0
For deployment on x86 with NVIDIA GPU, download the tlt-converter file for the appropriate CUDA/TensorRT version to convert the model from UFF to TensorRT engine
CUDA11 TensorRT 7.1
CUDA10.2 TensorRT 7.0

**Comment by deadeyegoodwin** [comment]
@efrats  Thanks for the information.

**Comment by turowicz** [comment]
@efrats amazing thanks!
