### ISSUE TITLE
Perf Client Failed while inferencing request on the loaded bert model !!

### ISSUE THREAD

**Issue by VJAYSLN** [triton-inference-server/server#1899]
**Description** 

I have used pretrained BertForSequenceClassfication Model to load into triton server. Here, for initial setup, i am only running on my System CPU. 
I started the server with the following command,

`docker run -it --rm --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 -p8000:8000 -p8001:8001 -p8002:8002 -v ./triton-inference-server/docs/examples/model_repository:/models nvcr.io/nvidia/tritonserver:20.06-py3 tritonserver --model-repository=/models --log-verbose=2
`
 
### Server Side Log 

=============================
== Triton Inference Server ==
=============================

NVIDIA Release 20.06 (build 13333626)

Copyright (c) 2018-2020, NVIDIA CORPORATION.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.
NVIDIA modifications are covered by the license terms that apply to the underlying
project or file.

WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use 'nvidia-docker run' to start this container; see
   https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker .

2020-08-12 05:45:01.186032: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
I0812 05:45:01.325936 1 server.cc:120] Initializing Triton Inference Server
E0812 05:45:01.326063 1 pinned_memory_manager.cc:192] failed to allocate pinned system memory: CUDA driver version is insufficient for CUDA runtime version
I0812 05:45:01.326134 1 graphdef_backend_factory.cc:48] Create GraphDefBackendFactory
I0812 05:45:01.326145 1 savedmodel_backend_factory.cc:48] Create SavedModelBackendFactory
I0812 05:45:01.326154 1 netdef_backend_factory.cc:46] Create NetDefBackendFactory
I0812 05:45:01.326159 1 plan_backend_factory.cc:48] Create PlanBackendFactory
I0812 05:45:01.326170 1 plan_backend_factory.cc:55] Registering TensorRT Plugins
I0812 05:45:01.326215 1 logging.cc:52] Registered plugin creator - ::GridAnchor_TRT version 1
I0812 05:45:01.326231 1 logging.cc:52] Registered plugin creator - ::NMS_TRT version 1
I0812 05:45:01.326243 1 logging.cc:52] Registered plugin creator - ::Reorg_TRT version 1
I0812 05:45:01.326256 1 logging.cc:52] Registered plugin creator - ::Region_TRT version 1
I0812 05:45:01.326279 1 logging.cc:52] Registered plugin creator - ::Clip_TRT version 1
I0812 05:45:01.326293 1 logging.cc:52] Registered plugin creator - ::LReLU_TRT version 1
I0812 05:45:01.326312 1 logging.cc:52] Registered plugin creator - ::PriorBox_TRT version 1
I0812 05:45:01.326324 1 logging.cc:52] Registered plugin creator - ::Normalize_TRT version 1
I0812 05:45:01.326334 1 logging.cc:52] Registered plugin creator - ::RPROI_TRT version 1
I0812 05:45:01.326343 1 logging.cc:52] Registered plugin creator - ::BatchedNMS_TRT version 1
I0812 05:45:01.326355 1 logging.cc:52] Registered plugin creator - ::FlattenConcat_TRT version 1
I0812 05:45:01.326366 1 logging.cc:52] Registered plugin creator - ::CropAndResize version 1
I0812 05:45:01.326377 1 logging.cc:52] Registered plugin creator - ::DetectionLayer_TRT version 1
I0812 05:45:01.326392 1 logging.cc:52] Registered plugin creator - ::Proposal version 1
I0812 05:45:01.326405 1 logging.cc:52] Registered plugin creator - ::ProposalLayer_TRT version 1
I0812 05:45:01.326419 1 logging.cc:52] Registered plugin creator - ::PyramidROIAlign_TRT version 1
I0812 05:45:01.326433 1 logging.cc:52] Registered plugin creator - ::ResizeNearest_TRT version 1
I0812 05:45:01.326446 1 logging.cc:52] Registered plugin creator - ::Split version 1
I0812 05:45:01.326457 1 logging.cc:52] Registered plugin creator - ::SpecialSlice_TRT version 1
I0812 05:45:01.326468 1 logging.cc:52] Registered plugin creator - ::InstanceNormalization_TRT version 1
I0812 05:45:01.326482 1 onnx_backend_factory.cc:53] Create OnnxBackendFactory
I0812 05:45:01.331247 1 libtorch_backend_factory.cc:46] Create LibTorchBackendFactory
I0812 05:45:01.331263 1 custom_backend_factory.cc:46] Create CustomBackendFactory
I0812 05:45:01.331271 1 ensemble_backend_factory.cc:47] Create EnsembleBackendFactory
I0812 05:45:01.331836 1 model_repository_manager.cc:667] AsyncLoad() 'bert'
I0812 05:45:01.331851 1 model_repository_manager.cc:729] TriggerNextAction() 'bert' version 1: 1
I0812 05:45:01.331884 1 model_repository_manager.cc:767] Load() 'bert' version 1
I0812 05:45:01.331889 1 model_repository_manager.cc:786] loading: bert:1
I0812 05:45:01.332012 1 model_repository_manager.cc:839] CreateInferenceBackend() 'bert' version 1
I0812 05:45:01.752939 1 libtorch_backend.cc:217] Creating instance bert_0_cpu on CPU using model.pt
I0812 05:45:02.337176 1 dynamic_batch_scheduler.cc:216] Starting dynamic-batch scheduler thread 0 at nice 5...
I0812 05:45:02.359768 1 model_repository_manager.cc:967] successfully loaded 'bert' version 1
I0812 05:45:02.359830 1 model_repository_manager.cc:729] TriggerNextAction() 'bert' version 1: 0
I0812 05:45:02.359854 1 model_repository_manager.cc:744] no next action, trigger OnComplete()
I0812 05:45:02.359995 1 model_repository_manager.cc:564] VersionStates() 'bert'
I0812 05:45:02.363198 1 grpc_server.cc:549] Ready for RPC 'ServerLive', 0
I0812 05:45:02.363220 1 grpc_server.cc:549] Ready for RPC 'ServerReady', 0
I0812 05:45:02.363227 1 grpc_server.cc:549] Ready for RPC 'ModelReady', 0
I0812 05:45:02.363235 1 grpc_server.cc:549] Ready for RPC 'ServerMetadata', 0
I0812 05:45:02.363243 1 grpc_server.cc:549] Ready for RPC 'ModelMetadata', 0
I0812 05:45:02.363260 1 grpc_server.cc:549] Ready for RPC 'ModelConfig', 0
I0812 05:45:02.363274 1 grpc_server.cc:549] Ready for RPC 'ModelStatistics', 0
I0812 05:45:02.363286 1 grpc_server.cc:549] Ready for RPC 'SystemSharedMemoryStatus', 0
I0812 05:45:02.363302 1 grpc_server.cc:549] Ready for RPC 'SystemSharedMemoryRegister', 0
I0812 05:45:02.363319 1 grpc_server.cc:549] Ready for RPC 'SystemSharedMemoryUnregister', 0
I0812 05:45:02.363333 1 grpc_server.cc:549] Ready for RPC 'CudaSharedMemoryStatus', 0
I0812 05:45:02.363345 1 grpc_server.cc:549] Ready for RPC 'CudaSharedMemoryRegister', 0
I0812 05:45:02.363356 1 grpc_server.cc:549] Ready for RPC 'CudaSharedMemoryUnregister', 0
I0812 05:45:02.363368 1 grpc_server.cc:549] Ready for RPC 'RepositoryIndex', 0
I0812 05:45:02.363383 1 grpc_server.cc:549] Ready for RPC 'RepositoryModelLoad', 0
I0812 05:45:02.363396 1 grpc_server.cc:549] Ready for RPC 'RepositoryModelUnload', 0
I0812 05:45:02.363433 1 grpc_server.cc:680] Thread started for CommonHandler
I0812 05:45:02.363614 1 grpc_server.cc:2623] New request handler for ModelInferHandler, 1
I0812 05:45:02.363651 1 grpc_server.cc:517] Thread started for ModelInferHandler
I0812 05:45:02.365107 1 grpc_server.cc:2860] New request handler for ModelStreamInferHandler, 3
I0812 05:45:02.365135 1 grpc_server.cc:517] Thread started for ModelStreamInferHandler
I0812 05:45:02.365152 1 grpc_server.cc:3199] Started GRPCInferenceService at 0.0.0.0:8001
I0812 05:45:02.366743 1 http_server.cc:2546] Started HTTPService at 0.0.0.0:8000
I0812 05:45:02.409279 1 http_server.cc:2565] Started Metrics Service at 0.0.0.0:8002

**I try to run triton client with the following command,**

`docker run -it --rm --net=host nvcr.io/nvidia/tritonserver:20.06-py3-clientsdk`

**Then i am using perf_client for making inference,**

/workspace# perf_client -m bert --shape INPUT__0:4

*** Measurement Settings ***
  Batch size: 1
  Measurement window: 5000 msec
  Using synchronous calls for inference
  Stabilizing using average latency

Request concurrency: 1
**Failed to maintain requested inference load. Worker thread(s) failed to generate concurrent requests.
Thread [0] had error: failed to run model 'bert_0_cpu**

**Meantime my serverside log is,**

I0812 05:45:02.365152 1 grpc_server.cc:3199] Started GRPCInferenceService at 0.0.0.0:8001
I0812 05:45:02.366743 1 http_server.cc:2546] Started HTTPService at 0.0.0.0:8000
I0812 05:45:02.409279 1 http_server.cc:2565] Started Metrics Service at 0.0.0.0:8002
I0812 05:47:59.083256 1 http_server.cc:1185] HTTP request: 0 /v2/models/bert
I0812 05:47:59.083327 1 model_repository_manager.cc:608] GetInferenceBackend() 'bert' version -1
I0812 05:47:59.083363 1 model_repository_manager.cc:564] VersionStates() 'bert'
I0812 05:47:59.084391 1 http_server.cc:1185] HTTP request: 0 /v2/models/bert/config
I0812 05:47:59.084444 1 model_repository_manager.cc:608] GetInferenceBackend() 'bert' version -1
I0812 05:48:15.671811 1 http_server.cc:1185] HTTP request: 0 /v2/models/bert
I0812 05:48:15.671850 1 model_repository_manager.cc:608] GetInferenceBackend() 'bert' version -1
I0812 05:48:15.671864 1 model_repository_manager.cc:564] VersionStates() 'bert'
I0812 05:48:15.672311 1 http_server.cc:1185] HTTP request: 0 /v2/models/bert/config
I0812 05:48:15.672330 1 model_repository_manager.cc:608] GetInferenceBackend() 'bert' version -1
I0812 05:48:15.673012 1 http_server.cc:1185] HTTP request: 0 /v2/models/bert/stats
I0812 05:48:15.673032 1 model_repository_manager.cc:564] VersionStates() 'bert'
I0812 05:48:15.673043 1 model_repository_manager.cc:608] GetInferenceBackend() 'bert' version 1
I0812 05:48:15.673109 1 http_server.cc:1185] HTTP request: 2 /v2/models/bert/infer
I0812 05:48:15.673125 1 model_repository_manager.cc:608] GetInferenceBackend() 'bert' version -1
I0812 05:48:15.673153 1 infer_request.cc:347] add original input: [0x0x7f0fd80071e0] request id: , model: bert, requested version: -1, actual version: 1, flags: 0x0, correlation id: 0, batch size: 0, priority: 0, timeout (us): 0
original inputs:
[0x0x7f0fd800dc68] input: INPUT__0, type: INT32, original shape: [1,4], shape: []
override inputs:
inputs:
original requested outputs:
requested outputs:

I0812 05:48:15.673189 1 infer_request.cc:480] prepared: [0x0x7f0fd80071e0] request id: , model: bert, requested version: -1, actual version: 1, flags: 0x0, correlation id: 0, batch size: 1, priority: 0, timeout (us): 0
original inputs:
[0x0x7f0fd800dc68] input: INPUT__0, type: INT32, original shape: [1,4], shape: [4]
override inputs:
inputs:
[0x0x7f0fd800dc68] input: INPUT__0, type: INT32, original shape: [1,4], shape: [4]
original requested outputs:
OUTPUT__0
requested outputs:
OUTPUT__0

I0812 05:48:15.673240 1 libtorch_backend.cc:550] Running bert_0_cpu with 1 requests
W0812 05:48:15.673264 1 pinned_memory_manager.cc:103] failed to allocate pinned system memory: no pinned memory pool, falling back to non-pinned system memory
I0812 05:48:15.673273 1 pinned_memory_manager.cc:130] non-pinned memory allocation: size 16, addr 0x7f10180016f0
I0812 05:48:15.947926 1 libtorch_backend.cc:772] The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__.py", line 7, in forward
  def forward(self: __torch__.WrappedModel,
    input_ids: Tensor) -> Tuple[Tensor]:
    _0 = ((self.model).forward(input_ids, ),)
           ~~~~~~~~~~~~~~~~~~~ <--- HERE
    return _0
  File "code/__torch__/transformers/modeling_bert.py", line 10, in forward
    input_ids: Tensor) -> Tensor:
    _0 = self.classifier
    _1 = (self.dropout).forward((self.bert).forward(input_ids, ), )
                                 ~~~~~~~~~~~~~~~~~~ <--- HERE
    return (_0).forward(_1, )
class BertModel(Module):
  File "code/__torch__/transformers/modeling_bert.py", line 35, in forward
    _12 = torch.to(extended_attention_mask, 6, False, False, None)
    attention_mask0 = torch.mul(torch.rsub(_12, 1., 1), CONSTANTS.c0)
    _13 = (_3).forward((_4).forward(input_ids, input, ), attention_mask0, )
                        ~~~~~~~~~~~ <--- HERE
    return (_2).forward(_13, )
class BertEmbeddings(Module):
  File "code/__torch__/transformers/modeling_bert.py", line 59, in forward
    position_ids = torch.arange(annotate(number, seq_length), dtype=4, layout=0, device=torch.device("cpu"), pin_memory=False)
    input0 = torch.expand(torch.unsqueeze(position_ids, 0), [_20, _21], implicit=False)
    _22 = (_18).forward(input_ids, )
           ~~~~~~~~~~~~ <--- HERE
    _23 = (_17).forward(input0, )
    _24 = (_16).forward(input, )
  File "code/__torch__/torch/nn/modules/sparse.py", line 7, in forward
  def forward(self: __torch__.torch.nn.modules.sparse.Embedding,
    input_ids: Tensor) -> Tensor:
    inputs_embeds = torch.embedding(self.weight, input_ids, 0, False, False)
                    ~~~~~~~~~~~~~~~ <--- HERE
    return inputs_embeds

lib/python3.7/site-packages/torch/jit/__init__.py(875): trace
saved_pytorch_model.py(13): <module>

**RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got CPUIntType instead (while checking arguments for embedding)**

I0812 05:48:15.948065 1 pinned_memory_manager.cc:157] non-pinned memory deallocation: addr 0x7f10180016f0
I0812 05:48:21.675463 1 http_server.cc:1185] HTTP request: 0 /v2/models/bert/stats
I0812 05:48:21.675595 1 model_repository_manager.cc:564] VersionStates() 'bert'
I0812 05:48:21.675669 1 model_repository_manager.cc:608] GetInferenceBackend() 'bert' version 1


**Triton Information**

What version of Triton are you using?
20.06

Are you using the Triton container or did you build it yourself?
Triton container - nvcr.io/nvidia/tritonserver:20.06-py3

**To Reproduce**

Model Name: BertForSequenceClassfication Model

I pulled the suggested PyTorch image:
docker pull nvcr.io/nvidia/pytorch:20.06-py3

I installed transformers
My transformers version is 3.0.2 while the PyTorch version is 1.5.1

I ran the following script to export the torchscript model:

```
import torch
from transformers import *

class WrappedModel(torch.nn.Module):
    def __init__(self):
        super(WrappedModel, self).__init__()
        self.model = BertForSequenceClassification.from_pretrained('bert-base-uncased')
    def forward(self, data):
        return self.model(data)

example = torch.zeros((4,128), dtype=torch.long) # bsz , seqlen
pt_model = WrappedModel().eval()
traced_script_module = torch.jit.trace(pt_model, example)
traced_script_module.save("model.pt")
```

Then I ran the following script to test if the torchscript model can do inference as expected:
```
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
pt_example_inputs = tokenizer.encode_plus("This is a sample input", return_tensors="pt")
example_inputs = {}
example_inputs['input_ids'] = pt_example_inputs['input_ids']
print(example_inputs)

import torch
model = torch.jit.load('model.pt')
example_outputs = model(example_inputs['input_ids'])

print(example_outputs[0].shape)
```
Output:
```
{'input_ids': tensor([[ 101, 2023, 2003, 1037, 7099, 7953,  102]])}
torch.Size([1, 2])
```

config.pbtxt
```

name: "bert"
platform: "pytorch_libtorch"
max_batch_size: 256
input {
  name: "INPUT__0"
  data_type: TYPE_FP32
  dims: [-1]
}
output {
  name: "OUTPUT__0"
  data_type: TYPE_FP32
  dims: [2]
}
dynamic_batching {
  preferred_batch_size: [1,2,4,8,16,32,64,128,256]
  max_queue_delay_microseconds: 10000
}
version_policy: {
  all {}
}
```
And then pulled triton server image and ran the container:
`docker pull nvcr.io/nvidia/tritonserver:20.06-py3`
And then I started server with the following command,

`docker run -it --rm --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 -p8000:8000 -p8001:8001 -p8002:8002 -v ./triton-inference-server/docs/examples/model_repository:/models nvcr.io/nvidia/tritonserver:20.06-py3 tritonserver --model-repository=/models --log-verbose=2
`

And then i pulled the triton client image as well,
```
docker pull nvcr.io/nvidia/tritonserver:20.06-py3-clientsdk
`docker run -it --rm --net=host nvcr.io/nvidia/tritonserver:20.06-py3-clientsdk`
```

For initial check inside container  i ran this,
`perf_client -m bert --shape INPUT__0:4 -v -v `

I got the following log,

*   Trying 127.0.0.1:8000...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /v2/models/bert HTTP/1.1
Host: localhost:8000
User-Agent: libcurl-agent/1.0
Accept: */*

* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/json
< Content-Length: 194
< 
* Connection #0 to host localhost left intact
{"name":"bert","versions":["1"],"platform":"pytorch_libtorch","inputs":[{"name":"INPUT__0","datatype":"INT32","shape":[-1,-1]}],"outputs":[{"name":"OUTPUT__0","datatype":"FP32","shape":[-1,2]}]}
*   Trying 127.0.0.1:8000...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /v2/models/bert/config HTTP/1.1
Host: localhost:8000
User-Agent: libcurl-agent/1.0
Accept: */*

* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/json
< Content-Length: 535
< 
* Connection #0 to host localhost left intact
{"name":"bert","platform":"pytorch_libtorch","version_policy":{"all":{}},"max_batch_size":256,"input":[{"name":"INPUT__0","data_type":"TYPE_INT32","dims":["-1"]}],"output":[{"name":"OUTPUT__0","data_type":"TYPE_FP32","dims":["2"]}],"instance_group":[{"name":"bert","count":1,"kind":"KIND_CPU"}],"default_model_filename":"model.pt","dynamic_batching":{"preferred_batch_size":[1,2,4,8,16,32,64,128,256],"max_queue_delay_microseconds":"10000"},"optimization":{"input_pinned_memory":{"enable":true},"output_pinned_memory":{"enable":true}}}
*** Measurement Settings ***
  Batch size: 1
  Measurement window: 5000 msec
  Using synchronous calls for inference
  Stabilizing using average latency

Request concurrency: 1
inference request: {"id":"","inputs":[{"name":"INPUT__0","datatype":"INT32","shape":[1,4],"parameters":{"binary_data_size":16}}],"outputs":[{"name":"OUTPUT__0","parameters":{"binary_data":true}}]}
*   Trying 127.0.0.1:8000...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
> POST /v2/models/bert/infer HTTP/1.1
Host: localhost:8000
User-Agent: libcurl-agent/1.0
Accept: */*
Inference-Header-Content-Length: 177
Content-Type: application/octet-stream
Content-Length: 193

* We are completely uploaded and fine
*   Trying 127.0.0.1:8000...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /v2/models/bert/stats HTTP/1.1
Host: localhost:8000
User-Agent: libcurl-agent/1.0
Accept: */*

* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/json
< Content-Length: 339
< 
* Connection #0 to host localhost left intact
{"model_stats":[{"name":"bert","version":"1","last_inference":0,"inference_count":0,"execution_count":0,"inference_stats":{"success":{"count":0,"ns":0},"fail":{"count":2,"ns":189531825},"queue":{"count":0,"ns":0},"compute_input":{"count":0,"ns":0},"compute_infer":{"count":0,"ns":0},"compute_output":{"count":0,"ns":0}},"batch_stats":[]}]}
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Content-Type: application/json
< Content-Length: 43
< 
* Connection #0 to host localhost left intact
inference response: {"error":"failed to run model 'bert_0_cpu"}
*   Trying 127.0.0.1:8000...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /v2/models/bert/stats HTTP/1.1
Host: localhost:8000
User-Agent: libcurl-agent/1.0
Accept: */*

* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/json
< Content-Length: 339
< 
* Connection #0 to host localhost left intact
{"model_stats":[{"name":"bert","version":"1","last_inference":0,"inference_count":0,"execution_count":0,"inference_stats":{"success":{"count":0,"ns":0},"fail":{"count":3,"ns":203056216},"queue":{"count":0,"ns":0},"compute_input":{"count":0,"ns":0},"compute_infer":{"count":0,"ns":0},"compute_output":{"count":0,"ns":0}},"batch_stats":[]}]}
  Pass [1] Error: No valid requests recorded within time interval. Please use a larger time window.
Failed to maintain requested inference load. Worker thread(s) failed to generate concurrent requests.
Thread [0] had error: failed to run model 'bert_0_cpu


**Some Notes**
Perf_client can able to make inference on other models which is already in the triton repository, (like resnet50_netdef, simple ..)
Here, I am only starting server and making inference on my local system CPU.
**Questions:**
1) What do you think would cause this problem?
Thanks in Advance :)

**Comment by deadeyegoodwin** [comment]
By default, perf_client sends random data in the input tensors. BERT models have been known to have trouble with random data so that could be the issue. You can ask perf_client to sends just zeros for the input data and see if that resolves the issue.

**Comment by VJAYSLN** [comment]
Yeah, I tried that too, But sadly that not helps.There is no change in the output log.. 

`perf_client -m bert --shape INPUT__0:4 --input-data zero -v -v`

*   Trying 127.0.0.1:8000...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /v2/models/bert HTTP/1.1
Host: localhost:8000
User-Agent: libcurl-agent/1.0
Accept: */*

* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/json
< Content-Length: 194
< 
* Connection #0 to host localhost left intact
{"name":"bert","versions":["1"],"platform":"pytorch_libtorch","inputs":[{"name":"INPUT__0","datatype":"INT32","shape":[-1,-1]}],"outputs":[{"name":"OUTPUT__0","datatype":"FP32","shape":[-1,2]}]}
*   Trying 127.0.0.1:8000...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /v2/models/bert/config HTTP/1.1
Host: localhost:8000
User-Agent: libcurl-agent/1.0
Accept: */*

* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/json
< Content-Length: 535
< 
* Connection #0 to host localhost left intact
{"name":"bert","platform":"pytorch_libtorch","version_policy":{"all":{}},"max_batch_size":256,"input":[{"name":"INPUT__0","data_type":"TYPE_INT32","dims":["-1"]}],"output":[{"name":"OUTPUT__0","data_type":"TYPE_FP32","dims":["2"]}],"instance_group":[{"name":"bert","count":1,"kind":"KIND_CPU"}],"default_model_filename":"model.pt","dynamic_batching":{"preferred_batch_size":[1,2,4,8,16,32,64,128,256],"max_queue_delay_microseconds":"10000"},"optimization":{"input_pinned_memory":{"enable":true},"output_pinned_memory":{"enable":true}}}
*** Measurement Settings ***
  Batch size: 1
  Measurement window: 5000 msec
  Using synchronous calls for inference
  Stabilizing using average latency

Request concurrency: 1
inference request: {"id":"","inputs":[{"name":"INPUT__0","datatype":"INT32","shape":[1,4],"parameters":{"binary_data_size":16}}],"outputs":[{"name":"OUTPUT__0","parameters":{"binary_data":true}}]}
*   Trying 127.0.0.1:8000...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /v2/models/bert/stats HTTP/1.1
Host: localhost:8000
User-Agent: libcurl-agent/1.0
Accept: */*

*   Trying 127.0.0.1:8000...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
> POST /v2/models/bert/infer HTTP/1.1
Host: localhost:8000
User-Agent: libcurl-agent/1.0
Accept: */*
Inference-Header-Content-Length: 177
Content-Type: application/octet-stream
Content-Length: 193

* We are completely uploaded and fine
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/json
< Content-Length: 339
< 
* Connection #0 to host localhost left intact
{"model_stats":[{"name":"bert","version":"1","last_inference":0,"inference_count":0,"execution_count":0,"inference_stats":{"success":{"count":0,"ns":0},"fail":{"count":3,"ns":187081060},"queue":{"count":0,"ns":0},"compute_input":{"count":0,"ns":0},"compute_infer":{"count":0,"ns":0},"compute_output":{"count":0,"ns":0}},"batch_stats":[]}]}
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Content-Type: application/json
< Content-Length: 43
< 
* Connection #0 to host localhost left intact
inference response: {"error":"failed to run model 'bert_0_cpu"}
*   Trying 127.0.0.1:8000...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /v2/models/bert/stats HTTP/1.1
Host: localhost:8000
User-Agent: libcurl-agent/1.0
Accept: */*

* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/json
< Content-Length: 339
< 
* Connection #0 to host localhost left intact
{"model_stats":[{"name":"bert","version":"1","last_inference":0,"inference_count":0,"execution_count":0,"inference_stats":{"success":{"count":0,"ns":0},"fail":{"count":4,"ns":203684333},"queue":{"count":0,"ns":0},"compute_input":{"count":0,"ns":0},"compute_infer":{"count":0,"ns":0},"compute_output":{"count":0,"ns":0}},"batch_stats":[]}]}
  Pass [1] Error: No valid requests recorded within time interval. Please use a larger time window.
Failed to maintain requested inference load. Worker thread(s) failed to generate concurrent requests.
Thread [0] had error: failed to run model 'bert_0_cpu
 

And same time the server side log also same,

**Comment by CoderHam** [comment]
Were you able to successfully run the torchscript model using the C++ API? The issue here is not with the perf_client but with the improper trace produced by the model. A specific op in the model **expected scalar type Long; but got CPUIntType** 

Instead of using `torch.jit.trace` please use `script = torch.jit.script(model)` and repeat the same experiment. Just because the models runs fine using the python API (should but) does not guarantee that the traced model will work using the C++ API.

**Comment by VJAYSLN** [comment]
While using torch.jit.script i got the following error,
```
RuntimeError: 
Expected a default value of type Tensor (inferred) on parameter "input_ids". Because "input_ids" was not annotated with an explicit type it is assumed to be type 'Tensor'.:
    def forward(self, input_ids=None, token_type_ids=None, position_ids=None, inputs_embeds=None):
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~...  <--- HERE
        # print(input_ids)

```
I ran the following script:
```
import torch
from transformers import *

class WrappedModel(torch.nn.Module):
    def __init__(self):
        super(WrappedModel, self).__init__()
        self.model = BertForSequenceClassification.from_pretrained('bert-base-uncased')
    def forward(self, input_ids):
        return self.model(input_ids)
example = torch.zeros((4,128), dtype=torch.long) # bsz , seqlen
pt_model = WrappedModel().eval()
traced_script_module = torch.jit.script(pt_model, example)
traced_script_module.save("model.pt")
```

**Comment by deadeyegoodwin** [comment]
@VJAYSLN  Is this issue resolved? If not please reopen.
