### ISSUE TITLE
document empty error while running image client example

### ISSUE THREAD

**Issue by DEEP2907** [triton-inference-server/server#1907]
hi ,
Im trying to run the image client example using below command
 image_client -m /path/examples/model_repository/resnet50_netdef/1 -s INCEPTION /path/triton-inference-server-master/qa/images/mug.jpg

Im getting below error:
error: failed to get model metadata: failed to parse the request JSON buffer: The document is empty. at 0
error: failed to parse model metadata: failed to parse JSON at0: The document is empty.
error: failed to get model config: failed to parse the request JSON buffer: The document is empty. at 0
error: failed to parse model config: failed to parse JSON at0: The document is empty.
image_client: /usr/include/rapidjson/document.h:1154: rapidjson::GenericValue<Encoding, Allocator>::MemberIterator rapidjson::GenericValue<Encoding, Allocator>::FindMember(const rapidjson::GenericValue<Encoding, SourceAllocator>&) [with SourceAllocator = rapidjson::MemoryPoolAllocator<>; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; rapidjson::GenericValue<Encoding, Allocator>::MemberIterator = rapidjson::GenericMemberIterator<false, rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<> >]: Assertion `IsObject()' failed.
Aborted (core dumped)

can you please help me with this?

**Comment by tanmayv25** [comment]
Which version of Triton Server and Client are you using? Looks like the server failed to return the correct json response. We did improve our server error reporting in the later releases. I would recommend using the latest 20.07 release for server and client, if not already doing so.

For debugging this, can you share the server side logs where the server is invoked using "--log-verbose=1" flag?

**Comment by DEEP2907** [comment]
Hi  @tanmayv25 ,
I m using latest 20.07 release for both server and client.

server side logs:
 docker run --rm -p8000:8000 -p8001:8001 -p8002:8002 -v /home/ubuntu/Deepthi/triton-inference-server-master/docs/examples/model_repository/resnet50_netdef/1:/models nvcr.io/nvidia/tritonserver:20.07-py3 tritonserver --model-repository=/models --log-verbose=1

=============================
== Triton Inference Server ==
=============================

NVIDIA Release 20.07 (build 14649927)

Copyright (c) 2018-2020, NVIDIA CORPORATION.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.
NVIDIA modifications are covered by the license terms that apply to the underlying
project or file.

WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use 'nvidia-docker run' to start this container; see
   https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker .

NOTE: The SHMEM allocation limit is set to the default of 64MB.  This may be
   insufficient for the inference server.  NVIDIA recommends the use of the following flags:
   nvidia-docker run --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 ...

2020-08-19 05:41:13.835900: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
I0819 05:41:13.876911 1 server.cc:120] Initializing Triton Inference Server
E0819 05:41:13.877215 1 pinned_memory_manager.cc:192] failed to allocate pinned system memory: CUDA driver version is insufficient for CUDA runtime version
I0819 05:41:13.877282 1 graphdef_backend_factory.cc:48] Create GraphDefBackendFactory
I0819 05:41:13.877292 1 savedmodel_backend_factory.cc:48] Create SavedModelBackendFactory
I0819 05:41:13.877302 1 netdef_backend_factory.cc:46] Create NetDefBackendFactory
I0819 05:41:13.877311 1 plan_backend_factory.cc:48] Create PlanBackendFactory
I0819 05:41:13.877320 1 plan_backend_factory.cc:55] Registering TensorRT Plugins
I0819 05:41:13.877374 1 logging.cc:52] Registered plugin creator - ::GridAnchor_TRT version 1
I0819 05:41:13.877406 1 logging.cc:52] Registered plugin creator - ::NMS_TRT version 1
I0819 05:41:13.877428 1 logging.cc:52] Registered plugin creator - ::Reorg_TRT version 1
I0819 05:41:13.877438 1 logging.cc:52] Registered plugin creator - ::Region_TRT version 1
I0819 05:41:13.877448 1 logging.cc:52] Registered plugin creator - ::Clip_TRT version 1
I0819 05:41:13.877458 1 logging.cc:52] Registered plugin creator - ::LReLU_TRT version 1
I0819 05:41:13.877484 1 logging.cc:52] Registered plugin creator - ::PriorBox_TRT version 1
I0819 05:41:13.877494 1 logging.cc:52] Registered plugin creator - ::Normalize_TRT version 1
I0819 05:41:13.877506 1 logging.cc:52] Registered plugin creator - ::RPROI_TRT version 1
I0819 05:41:13.877516 1 logging.cc:52] Registered plugin creator - ::BatchedNMS_TRT version 1
I0819 05:41:13.877527 1 logging.cc:52] Registered plugin creator - ::FlattenConcat_TRT version 1
I0819 05:41:13.877538 1 logging.cc:52] Registered plugin creator - ::CropAndResize version 1
I0819 05:41:13.877562 1 logging.cc:52] Registered plugin creator - ::DetectionLayer_TRT version 1
I0819 05:41:13.877570 1 logging.cc:52] Registered plugin creator - ::Proposal version 1
I0819 05:41:13.877576 1 logging.cc:52] Registered plugin creator - ::ProposalLayer_TRT version 1
I0819 05:41:13.877584 1 logging.cc:52] Registered plugin creator - ::PyramidROIAlign_TRT version 1
I0819 05:41:13.877618 1 logging.cc:52] Registered plugin creator - ::ResizeNearest_TRT version 1
I0819 05:41:13.877628 1 logging.cc:52] Registered plugin creator - ::Split version 1
I0819 05:41:13.877638 1 logging.cc:52] Registered plugin creator - ::SpecialSlice_TRT version 1
I0819 05:41:13.877647 1 logging.cc:52] Registered plugin creator - ::InstanceNormalization_TRT version 1
I0819 05:41:13.877666 1 onnx_backend_factory.cc:53] Create OnnxBackendFactory
I0819 05:41:13.886204 1 libtorch_backend_factory.cc:53] Create LibTorchBackendFactory
I0819 05:41:13.886250 1 custom_backend_factory.cc:46] Create CustomBackendFactory
I0819 05:41:13.886255 1 backend_factory.h:46] Create TritonBackendFactory
I0819 05:41:13.886266 1 ensemble_backend_factory.cc:47] Create EnsembleBackendFactory
I0819 05:41:13.887238 1 grpc_server.cc:221] Ready for RPC 'ServerLive', 0
I0819 05:41:13.887260 1 grpc_server.cc:221] Ready for RPC 'ServerReady', 0
I0819 05:41:13.887266 1 grpc_server.cc:221] Ready for RPC 'ModelReady', 0
I0819 05:41:13.887273 1 grpc_server.cc:221] Ready for RPC 'ServerMetadata', 0
I0819 05:41:13.887278 1 grpc_server.cc:221] Ready for RPC 'ModelMetadata', 0
I0819 05:41:13.887286 1 grpc_server.cc:221] Ready for RPC 'ModelConfig', 0
I0819 05:41:13.887293 1 grpc_server.cc:221] Ready for RPC 'ModelStatistics', 0
I0819 05:41:13.887299 1 grpc_server.cc:221] Ready for RPC 'SystemSharedMemoryStatus', 0
I0819 05:41:13.887307 1 grpc_server.cc:221] Ready for RPC 'SystemSharedMemoryRegister', 0
I0819 05:41:13.887314 1 grpc_server.cc:221] Ready for RPC 'SystemSharedMemoryUnregister', 0
I0819 05:41:13.887320 1 grpc_server.cc:221] Ready for RPC 'CudaSharedMemoryStatus', 0
I0819 05:41:13.887327 1 grpc_server.cc:221] Ready for RPC 'CudaSharedMemoryRegister', 0
I0819 05:41:13.887333 1 grpc_server.cc:221] Ready for RPC 'CudaSharedMemoryUnregister', 0
I0819 05:41:13.887340 1 grpc_server.cc:221] Ready for RPC 'RepositoryIndex', 0
I0819 05:41:13.887347 1 grpc_server.cc:221] Ready for RPC 'RepositoryModelLoad', 0
I0819 05:41:13.887353 1 grpc_server.cc:221] Ready for RPC 'RepositoryModelUnload', 0
I0819 05:41:13.887369 1 grpc_server.cc:354] Thread started for CommonHandler
I0819 05:41:13.887480 1 grpc_server.cc:2831] New request handler for ModelInferHandler, 1
I0819 05:41:13.887661 1 grpc_server.cc:1937] Thread started for ModelInferHandler
I0819 05:41:13.887831 1 grpc_server.cc:3173] New request handler for ModelStreamInferHandler, 3
I0819 05:41:13.887938 1 grpc_server.cc:1937] Thread started for ModelStreamInferHandler
I0819 05:41:13.887985 1 grpc_server.cc:3693] Started GRPCInferenceService at 0.0.0.0:8001
I0819 05:41:13.888387 1 http_server.cc:2645] Started HTTPService at 0.0.0.0:8000
I0819 05:41:13.930250 1 http_server.cc:2664] Started Metrics Service at 0.0.0.0:8002

**Comment by tanmayv25** [comment]
Sorry for the delay in the response.. There are are a couple of issues with understanding. The `image_client` binary expects the name of the model not the complete path to it. The forward slash is actually breaking the URI the client will use to access the server(We will add a check and produce comprehensible logging for this case).

So, a correct invocation should be something like:

> /workspace/install/bin# image_client -m resnet50_netdef -s INCEPTION ../../images/mug.jpg
> Request 0, batch size 1
> Image '../../images/mug.jpg':
 >   0.723991 (504) = COFFEE MUG

Additonaly, while running the server you must mount the complete `model_repository` directory instead of just the `version_directory`.  Please look at https://github.com/triton-inference-server/server/blob/r20.07/docs/quickstart.rst

The correct server invocation would be:

>  nvidia-docker run -it --rm -p8000:8000 -p8001:8001 -p8002:8002 -v /home/tanmay/github/reading/docs/examples/model_repository:/models nvcr.io/nvidia/tritonserver:20.07-py3 tritonserver --model-repository=/models --log-verbose=1

You must be able to see the following message on the server logs:
> I0831 20:47:38.013811 1 model_repository_manager.cc:1004] successfully loaded 'resnet50_netdef' version 1
