### ISSUE TITLE
jetson can not use gpu now? 

### ISSUE THREAD

**Issue by ctxqlxs** [triton-inference-server/server#1925]
tritonserver2.0.0-jetpack4.4ga.tgz
error:
cuda_memory_manager.cc:65 failed to finalize CUDA memory manager CNMEM_STATUS_NOT_INITIALIZED

**Comment by CoderHam** [comment]
Jetson can use GPU. Can you share the script you use and the model config?

**Comment by ctxqlxs** [comment]
name: "Seg"
platform: "tensorflow_savedmodel"
version_policy {
latest {
num_versions: 1
}
}
input {
name: "images"
data_type: TYPE_FP32
dims: -1
dims: 832
dims: 832
dims: 3
}
output {
name: "predict_label"
data_type: TYPE_FP32
dims: 416
dims: 416
dims: 1
}
instance_group {
name: "Seg"
count: 1
kind: KIND_GPU
}
default_model_filename: "model.savedmodel"

optimization { execution_accelerators {
  gpu_execution_accelerator : [ {
    name : "tensorrt"
    }]
}}

**Comment by ctxqlxs** [comment]
> Jetson can use GPU. Can you share the script you use and the model config?

name: "Seg"
platform: "tensorflow_savedmodel"
version_policy {
latest {
num_versions: 1
}
}
input {
name: "images"
data_type: TYPE_FP32
dims: -1
dims: 832
dims: 832
dims: 3
}
output {
name: "predict_label"
data_type: TYPE_FP32
dims: 416
dims: 416
dims: 1
}
instance_group {
name: "Seg"
count: 1
kind: KIND_GPU
}
default_model_filename: "model.savedmodel"

optimization { execution_accelerators {
  gpu_execution_accelerator : [ {
    name : "tensorrt"
    }]
}}

**Comment by ctxqlxs** [comment]
Thank you for your reply！ @ GuanLuo @CoderHam 
**fixed by** 
`--min-supported-compute-capability=5.3`
