### ISSUE TITLE
client request error

### ISSUE THREAD

**Issue by Waxyoung** [triton-inference-server/server#1939]
**Description**
in server shell , i Successfully loaded resnet50_netdef, but when i  use "python src/clients/python/image_client.py -m resnet50_netdef -s INCEPTION qa/images/mug.jpg" server shell occur something error.

![image](https://user-images.githubusercontent.com/26435611/91546222-b0be2f00-e954-11ea-8796-f828d8eac530.png)

![image](https://user-images.githubusercontent.com/26435611/91546246-bb78c400-e954-11ea-9e0a-9f09f442bb68.png)

**Triton Information**
What version of Triton are you using?

Are you using the Triton container or did you build it yourself?

**To Reproduce**
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**

**Comment by deadeyegoodwin** [comment]
What version of the client and server (container) are you using?

**Comment by Waxyoung** [comment]
server：19.02  client：0.11.0.dev

**Comment by Waxyoung** [comment]
@deadeyegoodwin

**Comment by deadeyegoodwin** [comment]
That is a very old, beta version of Triton. Can you try with an up-to-date version. 20.08 was just released.
