### ISSUE TITLE
Tritonbackend.h or Custom.h, unclear ensemble model 

### ISSUE THREAD

**Issue by Ken-LiuL** [triton-inference-server/server#1947]
Hi , currently I am working on the custom backends to implement an ensemble model, but I have several puzzlements
1. The difference between tritonbackend.h, which is said will be the replacement of custom.h, and the custom.h is not very clear, which one will be the best practice?
2. I noticed there is TRITON_ENABLE_GPU option in the old one, but no this option in the new one, what does this imply? If I use custom.h, will it run on GPU or CPU?
3. For typical model pipeline like  preprocess-->model-->postprocess, since most of the cases the model will be processed in GPU, should we use  opencv-cuda version so that  unnecessary cpu-gpu data copy can be avoided? Furthermore,  how triton handle data flow in ensemble model, will it use cuda shared memory?

sorry for so many questions, but these things are not stated very well  from the documentation, thanks in advance.

**Comment by deadeyegoodwin** [comment]
You should use trtitonbackend.h for all new Triton backends. There is documentation that points to several examples: https://github.com/triton-inference-server/server/blob/master/docs/backend.rst
We are in a transition right now so it is a little confusing but we will improve the documentation and source-code layout over the next couple of releases.

tritonbackend.h provides an interface for you to implement you custom backend. It is up to you if  you want to provide GPU support in that backend.

For data passed between models in an ensemble, Triton will attempt to keep data in GPU memory when possible. There is an example in the documentation showing a image pre-processing backend feeding an image classification model: https://docs.nvidia.com/deeplearning/triton-inference-server/master-user-guide/docs/client_example.html#ensemble-image-classification-example-application

**Comment by Ken-LiuL** [comment]
Is there any build instructions, like how and what to include for compile,  for the tritonbackend.h? There are detailed instructions for how to build custom backend using custom.h, but none for the tritonbackend.h.

**Comment by deadeyegoodwin** [comment]
For now look at the examples and corresponding CMake file. You can build your backend shared library any way you like but you should use an ldscript to hide the symbols as shown in the examples. We will be improving the documentation and the organization of the new backend API over the next couple of releases. https://github.com/triton-inference-server/server/blob/master/src/backends/backend/examples/CMakeLists.txt#L48
