### ISSUE TITLE
Please add max_queue_delay_microseconds and possibly preferred_batch_size to StrategyDirect

### ISSUE THREAD

**Issue by raimondasl** [triton-inference-server/server#1950]
I am using sequence batching with Direct strategy for stateful models. Unlike regular batching and StrategyOldest, StrategyDirect does not support max_queue_delay_microseconds and preferred_batch_size. At least max_queue_delay_microseconds is quite necessary for getting more requests batched into a single batch. Please add this to StrategyDirect. If possible, also add preferred_batch_size support although this is lower priority.

**Comment by GuanLuo** [comment]
@raimondasl Can you elaborate more on your use case and why `max_queue_delay_microseconds` and `preferred_batch_size` might help?

**Comment by raimondasl** [comment]
@GuanLuo : I think I described the need clearly enough. Without max_queue_delay_microseconds, we cannot control batching and therefore cannot get more requests packed into a single batch. This results in high queuing time since requests that did not make into the batch have to wait for batch to finish. I think the use cases are similar to the use cases for non-stateful models where max_queue_delay_microseconds and preferred_batch_size are supported. In non-stateful models setting max_queue_delay_microseconds to zero - which is what Direct strategy does, since it does not support max_queue_delay_microseconds - results in clearly suboptimal inference latency. 

If you still need exact details of the models we run, please talk to @deadeyegoodwin who knows the use cases and details. And we can talk further through company channels if needed.

Thank you.

**Comment by GuanLuo** [comment]
@raimondasl The requested features are added via #2139 , note that the field `minimum_slot_utilization` is used instead of `preferred_batch_size` as it fits better in the case of direct sequence batcher.
