### ISSUE TITLE
Custom Backend load custom model files

### ISSUE THREAD

**Issue by Giangblackk** [triton-inference-server/server#1959]
**Is your feature request related to a problem? Please describe.**
I'm trying to implement a custom backend for OpenCV DNN models, such as face landmark detection in Triton Inference Server.

The problem is these OpenCV DNN models need to load the actual model's weights from external XML files.

Generally, It seems that all the custom backend samples included are self-contained in a single compiled shared library file, which doesn't present my case where a custom backend needs to load external information from another file in the same model repository's folder (locally or remotely).

**Describe the solution you'd like**
I request a custom backend sample that demonstrates loading the external file in the same model repository's folder as the shared library file.

**Describe alternatives you've considered**
If this is a limitation of the current Triton Inference Server custom backend design, I request to change it to solve this problem in the release.

**Additional context**
Nothing.

**Comment by deadeyegoodwin** [comment]
First, be sure you are using the new backend APIs documented here: https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/backend.html

In the backend API, when your backend is initialized you will be able to access the path to the model repository subdirectory containing the model. So you can have other files in the model repository that you can then load. You can see this API being used in the identity.cc example: https://github.com/triton-inference-server/server/blob/master/src/backends/backend/examples/identity.cc#L407
