### ISSUE TITLE
docker install error

### ISSUE THREAD

**Issue by Waxyoung** [triton-inference-server/server#1961]
**Description**
i use 20.03 tritonserver ，when i use curl -v localhost:8000/v2/health/ready  ，error is occured。
![image](https://user-images.githubusercontent.com/26435611/91838748-92bc3b80-ec80-11ea-80fe-5a92b606d242.png)
![image](https://user-images.githubusercontent.com/26435611/91838772-9a7be000-ec80-11ea-9ec8-b118bc23776e.png)

I  want ask  “Starting HTTPService at 0.0.0.0:8000” is correct ？
Readme show “Started HTTPService at 0.0.0.0:8000”

**Triton Information**
What version of Triton are you using?

Are you using the Triton container or did you build it yourself?

**To Reproduce**
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**

**Comment by deadeyegoodwin** [comment]
20.03 release is V1 Triton. If you use the 20.03 clients and/or follow the 20.03 documentation you will see that V1 health endpoint is /api/health/live. https://docs.nvidia.com/deeplearning/triton-inference-server/archives/triton_inference_server_1130/user-guide/docs/http_grpc_api.html#health

V1 is deprecated. You should use the V2 version of triton (as in the just released 20.08 version). https://github.com/triton-inference-server/server/releases/tag/v2.2.0
