### ISSUE TITLE
REST API is too slow when using python request API

### ISSUE THREAD

**Issue by lvniqi** [triton-inference-server/server#1963]
**Description**
When I use "python requests" to inference an empty model with a large input shape, the throughput is much lower than the throughput when I use trition-client HTTP API (for example, perf_client) to inference the same model.

**Triton Information**
Triton v2.0, build by docker.

**To Reproduce**

use perf_client
perf_client -m 'pad' --concurrency-range 1:4 --shape X:1,2000000

result
Concurrency: 1, throughput: 25.2 infer/sec, latency 39608 usec
Concurrency: 2, throughput: 40.2 infer/sec, latency 49598 usec
Concurrency: 3, throughput: 59 infer/sec, latency 50977 usec
Concurrency: 4, throughput: 82 infer/sec, latency 48694 usec

use python (10 threads)
./test.sh

result ( less than 7 infer/sec in total with batchsize=1)
0.6811387938614323
0.6294492620602494
0.6260700185126562
0.6040191551496238
0.6000532168854754
0.5881483873001464
0.5871716465871505
0.5661041460573488
0.5283027242889046
0.516776275710051

the model is an empty model (just have an identity op) with input shape = (1,2000000)
[the test scripts and model is here!](https://github.com/triton-inference-server/server/files/5159824/test_pad.zip)

**Expected behavior**
the performance when using "python requests" is as same as using triton-client.

**Comment by CoderHam** [comment]
The comparison is unfair. You should compare performance with binary data extension vs perf client since that is what it uses. Uses JSON is always going to be slower due to the overhead of parsing. Additionally I do not see the requests being concurrent in the case of python.  
Please have a look at what the python httpclient library does. Is there a reason why you do not use it? 
PS: We use geventhttp instead of requests.

**Comment by deadeyegoodwin** [comment]
Short answer: python is slow, sending large data using json is slow.
perf_client is a C++ application that sends data in a "raw" binary format, and so is faster in both regards.
As @CoderHam mentioned you should try using the Triton Python HTTP library and that should improve your performance.

**Comment by bezero** [comment]
@CoderHam @deadeyegoodwin I am having a similar problem although I use `tritonhttpclient` as you suggested. Using `tritonhttpclient` has much higher `Overhead time` as explained below.

**Triton Information**
`20.08-py3` & `20.08-py3-clientsdk`

I am using the Triton container from NGC

**To Reproduce**

1. Deployed my model on triton server with tracing on
2. Run tests with`perf_client` with no concurrency
```bash
$ perf_client -m my_model

File: trace.json
Summary for my_model (20200902): trace count = 76
HTTP infer request (avg): 302446.76839473686us
	Receive (avg): 70712.17698684211us
	Send (avg): 24.12967105263158us
	Overhead (avg): 56.43784210526316us

	Handler (avg): 231654.02389473683us
		Overhead (avg): 67.62230263157895us
		Queue (avg): 76.87453947368421us
		Compute (avg): 231509.52705263157us
			Input (avg): 13115.562065789474us
			Infer (avg): 216613.97242105263us
			Output (avg): 1779.9925657894737us
```
3. Run a simple test with tritonhttpclient
```python
from tritonhttpclient import InferenceServerClient, InferInput
import numpy as np

triton_client = InferenceServerClient("localhost:8000")
config = triton_client.get_model_config("my_model")

img = np.random.rand(1,3,2048,2048).astype(np.float32)
inp = InferInput(config['input'][0]['name'], img.shape, 'FP32')
inp.set_data_from_numpy(img)

for i in range(11):
  response = triton_client.infer(model_name="my_model", inputs=[inp])
```
the trace result:
```
ummary for my_model (20200902): trace count = 11
HTTP infer request (avg): 1540241.7597272727us
	Receive (avg): 94662.99663636363us
	Send (avg): 27.28909090909091us
	Overhead (avg): 96.79036363636364us

	Handler (avg): 1445454.6836363636us
		Overhead (avg): 1049656.0788181818us
		Queue (avg): 81.63045454545454us
		Compute (avg): 395716.97436363634us
			Input (avg): 13268.454545454546us
			Infer (avg): 379332.68863636366us
			Output (avg): 3115.831181818182us
```

**Expected behavior**
Since I am using `v2.2.0.clients` I was expecting to have equivalent performance

**Comment by deadeyegoodwin** [comment]
What is the model configuration? Are you sure you are sending the same size data in each case? The server side should behave the same no matter what the client is.

**Comment by dselivanov** [comment]
@deadeyegoodwin 

> The server side should behave the same no matter what the client is.

This is what leaves us perplexed!

> What is the model configuration? Are you sure you are sending the same size data in each case? 

```name: "5806553b-fc1a-491a-971c-275e4ee9b753"
platform: "onnxruntime_onnx"
max_batch_size: 1
input [
	{
		name: "input"
		data_type: TYPE_FP32
		format: FORMAT_NCHW
		dims: [3, 2048, 2048]
	}
]
output [
	{
		name: "output"
		data_type: TYPE_FP32
		dims: [-1, 7]
	}
]
}

```

The most confusing part with python http client is following:
```
Handler (avg): 1445454.6836363636us
	Overhead (avg): 1049656.0788181818us
```
which shows that handler overhead is about 73% of the time spend on handler.

**Comment by dselivanov** [comment]
@deadeyegoodwin should we open a separate issue?

**Comment by deadeyegoodwin** [comment]
Yes, please open a new issue with all the details and we will have someone look into it.

**Comment by dselivanov** [comment]
see #1989
