### ISSUE TITLE
simplest way to use tensorflow 1.12.0 in triton server 20.07

### ISSUE THREAD

**Issue by luvpine** [triton-inference-server/server#1964]
model info : tensorflow model (tf version 1.12.0)
triton server : v20.07 (tf version 1.15.3 included)

The specific floating point values are different in tf1.2.0 and tf.1.15.3.
so I want to change tensorflow version only from triton server 20.07 version.
I attempt to build Triton with Docker or build Triton with Cmake.
Is It possible?

Please recommend the simplest way to do it.

**Comment by deadeyegoodwin** [comment]
There is no easy way to build your own TF for Triton for such an old version of TF. You have to go back to the 19.01 release to get support for 1.12.0. The easiest way is to use the 19.01 version of Triton, but that is very old.

**Comment by deadeyegoodwin** [comment]
The reason why it is not easy to use any TF version if that the TF C/C++ API is not sufficient for Triton's needs and so we needed to patch TF. TF is working on improving their C/C++ API and that will potentially allow Triton to no longer need to patch and therefore make it easier to "drop in" any version of TF. But we are not there yet.
