### ISSUE TITLE
trion on kfserving performance

### ISSUE THREAD

**Issue by zerocurve** [triton-inference-server/server#1968]
**Description**
I see the following document describe the performance work on kfserving and it shows 90% throughput downgrads
I want to understand if there was any followup on this work. If it is practical to run triton on kfserving
https://docs.google.com/document/d/1ss7M3cx1qD1PVpTaKTu_Y3C80JJz4nvMZlIyuZutZoE/edit#

**Comment by deadeyegoodwin** [comment]
That document seems more to measure the slowdown introduced by KNative. Triton should not have any additional overhead on KFServing than any other service. Triton team is on the KFServing working group and is generally supportive of and cooperating with KFServings development and goals. To get specific information about the current status on those perf issues you should ask on the KFserving issues: https://github.com/kubeflow/kfserving/issues
