### ISSUE TITLE
is there pre-build docker images for jetson?

### ISSUE THREAD

**Issue by ctxqlxs** [triton-inference-server/server#1972]
when **run** this:

`sudo docker run --gpus all --rm --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 -p8000:8000 -p8001:8001 -p8002:8002 -v$(pwd)/triton-deploy/models:/models  -v$(pwd)/triton-deploy/plugins:/plugins --env LD_PRELOAD=/plugins/liblayerplugin.so nvcr.io/nvidia/tritonserver:20.07-py3 tritonserver --model-repository=/models --strict-model-config=false --grpc-infer-allocation-pool-size=16 --log-verbose 1`

**get error**:

`standard_init_linux.go:211: exec user process caused "exec format error"`

and when i use the **[tritonserver:20.06]**

`./tritonserver200/bin/tritonserver`

i get another problem, how to set the plugins?

 `tritonserver200/bin/tritonserver: unrecognized option '--env'`

**Comment by brianegge** [comment]
What was the resolution?
