### ISSUE TITLE
the metric with ensemble_scheduling.

### ISSUE THREAD

**Issue by XuekuanWang** [triton-inference-server/server#1982]
Hi,
I want to test the metric with ensemble_scheduling. 
There's some trouble.

root@dell-Precision-7820-Tower:/workspace# perf_client -m page_det_pipeline urrency-range 1:4

The error is :

Request concurrency: 1
Failed to update context stat: [ 0] INTERNAL - Timer not set correctly.
[ 0] INTERNAL - Failed to maintain requested inference load. Worker thread(s) failed to generate concurrent requests.
Thread [0] had error: [inference:0 20] INTERNAL - payload error for 'image_preprocess_rgb_0_gpu0': (18) unable to preprocess image

Thanks.

**Comment by deadeyegoodwin** [comment]
You don't give us any information about the models in the ensemble but it looks like you have image preprocessing in there. By default perf_client just sends random data to the model. It is likely that the random data is not a valid image (jpeg, png, etc.). You could try using image_client just to confirm that the ensemble works correctly. For perf_client you will need to send real data as described here: https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/optimization.html#real-input-data
