### ISSUE TITLE
Whats the equivalent of /api/status?format=json in v2?

### ISSUE THREAD

**Issue by whillas** [triton-inference-server/server#1990]
**Is your feature request related to a problem? Please describe.**

In version 1 there was a way to get a description of all the models on the TRTIS via
`localhost:8000/api/status?format=json`
We have been using this to automatically configure our client and also to do model routing as we have multiple Triton servers running.

**Describe the solution you'd like**

An endpoint that returns a list of models running on the server and their specs with enough information to build an inference request.

**Describe alternatives you've considered**

We are upgrading from 1.11 to 2.2 as we need the fast GCP bucket loading. We're also moving to K3S for deployment and need the ready and liveliness endpoints

**Comment by bezero** [comment]
You can request your model config as follow:
```bash
curl -v localhost:8000/v2/models/<your_model>
```
Or if you want full config:
```bash
curl -v localhost:8000/v2/models/<your_model>/config
```

**Comment by whillas** [comment]
Found it so one has to do a POST (why not a get?!) to:
```
curl -X POST localhost:7000/v2/repository/index
```
_And then_ for each of those do a 
```
curl localhost:7000/v2/models/$MODEL_NAME/config
```
_per model_ which is going to slow things down.

**Comment by deadeyegoodwin** [comment]
All the protocol docs are here: https://github.com/triton-inference-server/server/tree/master/docs/protocol

**Comment by loveppdog** [comment]
> Found it so one has to do a POST (why not a get?!) to:
> curl -X POST localhost:7000/v2/repository/index
> 
> And then for each of those do a
> curl localhost:7000/v2/models/$MODEL_NAME/config
> 
> per model which is going to slow things down.

I thikn 8000/v2/models/stats should be OK.
