### ISSUE TITLE
oom happens in GTX1080Ti(11GB) but not in RTX2080Ti(11GB)

### ISSUE THREAD

**Issue by loveppdog** [triton-inference-server/server#2003]
Our pipeline includes many models (tf and pytorch)
Using trtion server 20.03. 
I see GTX1080Ti and RTX2080Ti have the same GPU capacity:11GB.

Inference on RTX2080Ti can work OK and GPU:10576MiB / 11178MiB
Inference on GTX1080Ti maybe OOM and it happens sometimes. 

How to explain the difference on RTX2080Ti/GTX1080Ti. Does triton have different gpu optimazation for them?

**Comment by deadeyegoodwin** [comment]
Triton itself doesn't treat those GPUs differently, however the underlying framework and CUDA libraries that Triton uses will likely have differences. Those GPUs have different compute capabilities and so the low-level GPU code running on them is different, even if that code is performing the same function. So, it would be that the execution of the model requires more memory on one GPU vs the other.
