### ISSUE TITLE
Triton Inference Server on Azure

### ISSUE THREAD

**Issue by chiehpower** [triton-inference-server/server#2004]
Hi all, 

Thanks for providing this really awesome tool. 
So far, I already successfully used Triton Inference Server and also did a lot of different experiments on various devices and systems. 

I wonder does Triton inference server support the Azure productions? For example, we use the Azure to do inference or deploy the model on Azure? 

Is  there any information about these? 
Thanks you so much!!!

BR,
Chieh

**Comment by tom-r-o** [comment]
I'd also be glad to know about Azure support.

**Comment by chiehpower** [comment]
> I'd also be glad to know about Azure support.

@tom-r-o 
As far as I know, Azure provides the VM service, so if you can choose a size of GPU which corresponds to the cuda compute capability of the TRTIS requesting, I think that there is possible to use the TRTIS on Azure. (BTW The thing is GPU options quite expensive for me. Therefore, I haven't tested it yet.)

**Comment by deadeyegoodwin** [comment]
Azure has just announced some Triton integration:
https://docs.microsoft.com/en-us/azure/machine-learning/how-to-deploy-with-triton?tabs=python
https://techcommunity.microsoft.com/t5/azure-ai/real-time-inference-on-nvidia-gpus-in-azure-machine-learning/ba-p/1737522
