### ISSUE TITLE
can't  parse path with    --model-repository=s3://host:port/demobucket/path

### ISSUE THREAD

**Issue by wbzqe** [triton-inference-server/server#2008]
**Description**
can't  Parse Path with    --model-repository=s3://host:port/demobucket/path

**Triton Information**
use container tritonserver:20.08-py3

**To Reproduce**
tritonserver --model-repository=s3://host:port/demobucket/path
I0911 09:42:39.332119 546 metrics.cc:184] found 2 GPUs supporting NVML metrics
I0911 09:42:39.337724 546 metrics.cc:193]   GPU 0: xxxx
I0911 09:42:39.343526 546 metrics.cc:193]   GPU 1: xxxx
I0911 09:42:39.343726 546 server.cc:119] Initializing Triton Inference Server
W0911 09:42:39.726070 546 server.cc:160] failed to enable peer access for some device pairs
error: creating server: Invalid argument - repository path is not a valid directory

**Comment by deadeyegoodwin** [comment]
Did you literally use --model-repository=s3://host:port/demobucket/path in the command line? That form of the option is for when you are running your own local S3 server (e.g. minio) and host:port indicate the local system where it is running. So something like localhost:1234.

**Comment by wbzqe** [comment]
> Did you literally use --model-repository=s3://host:port/demobucket/path in the command line? That form of the option is for when you are running your own local S3 server (e.g. minio) and host:port indicate the local system where it is running. So something like localhost:1234.

😂Actually I want to use a compatible with aws s3 API remote object storage services, but triton unable to set the endpoint url, so I try to set model repo path s3: / / host: port/bucket/path in this format

**Comment by deadeyegoodwin** [comment]
If you are using amazon s3 the don't include the host:port part. See https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/model_repository.html#s3

**Comment by wbzqe** [comment]
> If you are using amazon s3 the don't include the host:port part. See https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/model_repository.html#s3

**Comment by wbzqe** [comment]
> If you are using amazon s3 the don't include the host:port part. See https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/model_repository.html#s3

I use qiniu oss，and endpoint url should  be s3-cn-east-1.qiniucs.com
