### ISSUE TITLE
Ensemble model stuck perf test

### ISSUE THREAD

**Issue by Ken-LiuL** [triton-inference-server/server#2014]
**Description**
The issue is like this, when I run perf test on the ensemble model multiple times, after a while, it will suddenly stuck, but during the stuck period, if I just run perf test on each component, like preprocess part, of the ensemble model, it will perform well, and if I restart the triton server, then I could run perf test again, then it will stuck after a while.
**Triton Information**
What version of Triton are you using?
20.07

Are you using the Triton container or did you build it yourself?
use  Triton container
 
**Log** 
I0914 03:26:28.663013 1 grpc_server.cc:3007] Process for ModelInferHandler, rpc_ok=1, 4001 step START
I0914 03:26:28.663105 1 grpc_server.cc:3000] New request handler for ModelInferHandler, 4002
I0914 03:26:28.663130 1 model_repository_manager.cc:559] GetInferenceBackend() 'detect_ensemble' version 1
I0914 03:26:28.663186 1 model_repository_manager.cc:559] GetInferenceBackend() 'detect_ensemble' version 1
I0914 03:26:28.663209 1 infer_request.cc:362] add original input: [0x0x7f583012f5e0] request id: , model: detect_ensemble, requested version: 1, actual version: 1, flags: 0x0, correlation id: 0, batch size: 0, priority: 0, timeout (us): 0
original inputs:
[0x0x7f583012f868] input: INPUT, type: BYTES, original shape: [1,1], shape: []
override inputs:
inputs:
original requested outputs:
requested outputs:

I0914 03:26:28.663286 1 infer_request.cc:503] prepared: [0x0x7f583012f5e0] request id: , model: detect_ensemble, requested version: 1, actual version: 1, flags: 0x0, correlation id: 0, batch size: 1, priority: 0, timeout (us): 0
original inputs:
[0x0x7f583012f868] input: INPUT, type: BYTES, original shape: [1,1], shape: [1]
override inputs:
inputs:
[0x0x7f583012f868] input: INPUT, type: BYTES, original shape: [1,1], shape: [1]
original requested outputs:
bbox
requested outputs:
bbox

I0914 03:26:28.663331 1 model_repository_manager.cc:559] GetInferenceBackend() 'detect_preprocess' version -1
I0914 03:26:28.663361 1 model_repository_manager.cc:559] GetInferenceBackend() 'detect_model' version -1
I0914 03:26:28.663389 1 model_repository_manager.cc:559] GetInferenceBackend() 'detect_postprocess' version -1
I0914 03:26:28.663496 1 infer_request.cc:362] add original input: [0x0x7f5830132e60] request id: , model: detect_preprocess, requested version: -1, actual version: 1, flags: 0x0, correlation id: 0, batch size: 0, priority: 0, timeout (us): 0
original inputs:
[0x0x7f5830133108] input: INPUT, type: BYTES, original shape: [1,1], shape: []
override inputs:
inputs:
original requested outputs:
requested outputs:

I0914 03:26:28.663529 1 infer_request.cc:503] prepared: [0x0x7f5830132e60] request id: , model: detect_preprocess, requested version: -1, actual version: 1, flags: 0x0, correlation id: 0, batch size: 1, priority: 0, timeout (us): 0
original inputs:
[0x0x7f5830133108] input: INPUT, type: BYTES, original shape: [1,1], shape: [1]
override inputs:
inputs:
[0x0x7f5830133108] input: INPUT, type: BYTES, original shape: [1,1], shape: [1]
original requested outputs:
format_img
img_size
requested outputs:
format_img
img_size

I0914 03:26:28.663636 1 custom_backend.cc:335] Running detect_preprocess_0_gpu0 with 1 requests
I0914 03:26:28.663774 1 infer_response.cc:139] add response output: output: img_size, type: UINT32, shape: [1,2]
I0914 03:26:28.663838 1 pinned_memory_manager.cc:130] pinned memory allocation: size 8, addr 0x7f59066b8e10
I0914 03:26:28.663854 1 ensemble_scheduler.cc:509] Internal response allocation: img_size, size 8, addr 0x7f59066b8e10, memory type 1, type id 0
I0914 03:26:28.663879 1 infer_response.cc:139] add response output: output: format_img, type: FP32, shape: [1,3,460,640]
I0914 03:26:28.663920 1 pinned_memory_manager.cc:130] pinned memory allocation: size 3532800, addr 0x7f59060000f0
I0914 03:26:28.663936 1 ensemble_scheduler.cc:509] Internal response allocation: format_img, size 3532800, addr 0x7f59060000f0, memory type 1, type id 0
I0914 03:26:28.671048 1 ensemble_scheduler.cc:524] Internal response release: size 8, addr 0x7f59066b8e10
I0914 03:26:28.671080 1 ensemble_scheduler.cc:524] Internal response release: size 3532800, addr 0x7f59060000f0
I0914 03:26:28.671125 1 infer_request.cc:362] add original input: [0x0x7f583012b4b0] request id: , model: detect_model, requested version: -1, actual version: 1, flags: 0x0, correlation id: 0, batch size: 0, priority: 0, timeout (us): 0
original inputs:
[0x0x7f583012b758] input: input, type: FP32, original shape: [1,3,460,640], shape: []
override inputs:
inputs:
original requested outputs:
requested outputs:

I0914 03:26:28.671163 1 infer_request.cc:503] prepared: [0x0x7f583012b4b0] request id: , model: detect_model, requested version: -1, actual version: 1, flags: 0x0, correlation id: 0, batch size: 1, priority: 0, timeout (us): 0
original inputs:
[0x0x7f583012b758] input: input, type: FP32, original shape: [1,3,460,640], shape: [3,460,640]
override inputs:
inputs:
[0x0x7f583012b758] input: input, type: FP32, original shape: [1,3,460,640], shape: [3,460,640]
original requested outputs:
confs
landmss
locs
requested outputs:
confs
landmss
locs

I0914 03:26:28.671291 1 onnx_backend.cc:573] Running detect_model_0_gpu0 with 1 request requests
I0914 03:26:28.671354 1 pinned_memory_manager.cc:130] pinned memory allocation: size 3532800, addr 0x7f590677bb10
I0914 03:26:28.722138 1 infer_response.cc:139] add response output: output: landmss, type: FP32, shape: [1,12200,10]
I0914 03:26:28.722187 1 pinned_memory_manager.cc:130] pinned memory allocation: size 488000, addr 0x7f590848b280
I0914 03:26:28.722203 1 ensemble_scheduler.cc:509] Internal response allocation: landmss, size 488000, addr 0x7f590848b280, memory type 1, type id 0
I0914 03:26:28.722383 1 infer_response.cc:139] add response output: output: locs, type: FP32, shape: [1,12200,4]
I0914 03:26:28.722411 1 pinned_memory_manager.cc:130] pinned memory allocation: size 195200, addr 0x7f59085024d0
I0914 03:26:28.722442 1 ensemble_scheduler.cc:509] Internal response allocation: locs, size 195200, addr 0x7f59085024d0, memory type 1, type id 0
I0914 03:26:28.722573 1 infer_response.cc:139] add response output: output: confs, type: FP32, shape: [1,12200,2]
I0914 03:26:28.722607 1 pinned_memory_manager.cc:130] pinned memory allocation: size 97600, addr 0x7f5908531f60
I0914 03:26:28.722622 1 ensemble_scheduler.cc:509] Internal response allocation: confs, size 97600, addr 0x7f5908531f60, memory type 1, type id 0
I0914 03:26:28.722694 1 ensemble_scheduler.cc:524] Internal response release: size 488000, addr 0x7f590848b280
I0914 03:26:28.722714 1 ensemble_scheduler.cc:524] Internal response release: size 195200, addr 0x7f59085024d0
I0914 03:26:28.722728 1 ensemble_scheduler.cc:524] Internal response release: size 97600, addr 0x7f5908531f60
I0914 03:26:28.722780 1 infer_request.cc:362] add original input: [0x0x7f5830123b50] request id: , model: detect_postprocess, requested version: -1, actual version: 1, flags: 0x0, correlation id: 0, batch size: 0, priority: 0, timeout (us): 0
original inputs:
[0x0x7f5830123df8] input: landmss, type: FP32, original shape: [1,12200,10], shape: []
override inputs:
inputs:
original requested outputs:
requested outputs:

I0914 03:26:28.722814 1 infer_request.cc:362] add original input: [0x0x7f5830123b50] request id: , model: detect_postprocess, requested version: -1, actual version: 1, flags: 0x0, correlation id: 0, batch size: 0, priority: 0, timeout (us): 0
original inputs:
[0x0x7f56d37dcf88] input: img_size, type: UINT32, original shape: [1,2], shape: []
[0x0x7f5830123df8] input: landmss, type: FP32, original shape: [1,12200,10], shape: []
override inputs:
inputs:
original requested outputs:
requested outputs:

I0914 03:26:28.722860 1 infer_request.cc:362] add original input: [0x0x7f5830123b50] request id: , model: detect_postprocess, requested version: -1, actual version: 1, flags: 0x0, correlation id: 0, batch size: 0, priority: 0, timeout (us): 0
original inputs:
[0x0x7f5830123df8] input: landmss, type: FP32, original shape: [1,12200,10], shape: []
[0x0x7f56d37dd048] input: confs, type: FP32, original shape: [1,12200,2], shape: []
[0x0x7f56d37dcf88] input: img_size, type: UINT32, original shape: [1,2], shape: []
override inputs:
inputs:
original requested outputs:
requested outputs:

I0914 03:26:28.722892 1 infer_request.cc:362] add original input: [0x0x7f5830123b50] request id: , model: detect_postprocess, requested version: -1, actual version: 1, flags: 0x0, correlation id: 0, batch size: 0, priority: 0, timeout (us): 0
original inputs:
[0x0x7f5830123df8] input: landmss, type: FP32, original shape: [1,12200,10], shape: []
[0x0x7f56d37dd148] input: locs, type: FP32, original shape: [1,12200,4], shape: []
[0x0x7f56d37dd048] input: confs, type: FP32, original shape: [1,12200,2], shape: []
[0x0x7f56d37dcf88] input: img_size, type: UINT32, original shape: [1,2], shape: []
override inputs:
inputs:
original requested outputs:
requested outputs:

I0914 03:26:28.722957 1 infer_request.cc:503] prepared: [0x0x7f5830123b50] request id: , model: detect_postprocess, requested version: -1, actual version: 1, flags: 0x0, correlation id: 0, batch size: 1, priority: 0, timeout (us): 0
original inputs:
[0x0x7f5830123df8] input: landmss, type: FP32, original shape: [1,12200,10], shape: [12200,10]
[0x0x7f56d37dd148] input: locs, type: FP32, original shape: [1,12200,4], shape: [12200,4]
[0x0x7f56d37dd048] input: confs, type: FP32, original shape: [1,12200,2], shape: [12200,2]
[0x0x7f56d37dcf88] input: img_size, type: UINT32, original shape: [1,2], shape: [2]
override inputs:
inputs:
[0x0x7f5830123df8] input: landmss, type: FP32, original shape: [1,12200,10], shape: [12200,10]
[0x0x7f56d37dcf88] input: img_size, type: UINT32, original shape: [1,2], shape: [2]
[0x0x7f56d37dd048] input: confs, type: FP32, original shape: [1,12200,2], shape: [12200,2]
[0x0x7f56d37dd148] input: locs, type: FP32, original shape: [1,12200,4], shape: [12200,4]
original requested outputs:
bbox
requested outputs:
bbox

I0914 03:26:28.723049 1 pinned_memory_manager.cc:157] pinned memory deallocation: addr 0x7f59060000f0
I0914 03:26:28.723065 1 pinned_memory_manager.cc:157] pinned memory deallocation: addr 0x7f590677bb10

**Comment by GuanLuo** [comment]
Can you use a newer version of Triton (20.08 as for now) and check if the issue remains. And can you provide a minimum repro for the issue?

**Comment by Ken-LiuL** [comment]
I tried 20.08, it is the same. How could I debug this, so that I could dig out some useful information? Minimum repo? Would a ensemble config.pbtxt useful?

**Comment by GuanLuo** [comment]
It will be a step-by-step instructions of how to setup the model repository you used and how to run the server / perf test to reproduce the issue. If you can't share some confidential information, you can try to replace it with some simple components which can still capture the issue.

Otherwise, you can provide more detail on when the stuck happens, with server log we may be able to narrow down the issue.

**Comment by Ken-LiuL** [comment]
Thx for your reply, it turns out to be a bug in my custom backend, that could cause endless loop. Maybe a warning log from triton could be useful in the future
