### ISSUE TITLE
unload model not release mem

### ISSUE THREAD

**Issue by inkinworld** [triton-inference-server/server#2023]
**Description**
i need `load`/`unload` dynamically , when `unload` model, the mem not release, after multi-times, omm will hapen.

**Triton Information**
20.08-py3

**To Reproduce**
### start command:

```
 tritonserver \
   --model-store=/models/model_repo \
   --strict-model-config=false \
   --log-verbose=1 \
   --model-control-mode=explicit
```

### then  use http api:
localhost:8000/v2/repository/models/model_1/load
localhost:8000/v2/repository/models/model_1/unload
localhost:8000/v2/repository/models/model_1/load
localhost:8000/v2/repository/models/model_1/unload
localhost:8000/v2/repository/models/model_1/load
localhost:8000/v2/repository/models/model_1/unload
...(multi times)

### mem usage graph:
![image](https://user-images.githubusercontent.com/12553724/93163414-afa94200-f749-11ea-95d9-c7444a60b7d4.png)

**Expected behavior**
when unload model mem will be reduced

**Comment by deadeyegoodwin** [comment]
What type of model and you loading and unloading? Can you provide a repro?

**Comment by deadeyegoodwin** [comment]
Closing, please provide additional data and  reopen.
