### ISSUE TITLE
Error when using Ceph S3 storage as a model repository

### ISSUE THREAD

**Issue by ihong321** [triton-inference-server/server#2027]
**Description**
When I use Ceph S3 storage as a triton model repository, the server cannot load model.

**Triton Information**
NGC container 20.03.1 and 20.08

**To Reproduce**
I tried using AWS, MinIO, and Ceph to use s3 storage on Triton server.

When the 'simple' model included in the triton example is stored in the storage and the server is run in poll mode, AWS and MinIO load the model normally. However, in Ceph, an error occurs.

E0909 04:08:53.234227 1 model_repository_manager.cc:1166] failed to load model 'simple': at least one version must be available under the version policy of model 'simple'
I0909 04:08:53.234341 1 model_repository_manager.cc:515] VersionStates() 'simple'
error: creating server: Internal - failed to load all models

**Expected behavior**
The server can load the model in Ceph S3 storage.

**Comment by CoderHam** [comment]
Can you provide more information of the exact model repository url you used? Did you follow the convention from [here](https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/model_repository.html#s3)?

Did AWS S3, MINIO work fine for you?
20.3.1 is very outdated now, I would recommend you to use the latest release if you can. 
Please also double-check your directory structure for the models.

**Comment by ihong321** [comment]
@CoderHam After failing the first server run with Ceph S3, I upgraded to version 20.08 and tested.

The same model was saved in AWS, MINIO, and Ceph, and the saved objects are as follows.
'simple/config.pbtxt'
'simple/1/model.graphdef'

Triton's running option of model repository.
AWS: --model-repository=s3://my-model-test
MINIO: --model-repository=s3://<my_minio_server_ip>:<minio_port>/<models_bucket>
Ceph: --model-repository=s3://<my_ceph_server_ip>:<ceph_port>/<models_bucket>

AWS and MINIO worked fine, but Ceph didn't.

**Comment by CoderHam** [comment]
We don't currently test support for Ceph. I will mark this as an enhancement for now. 
That being said, it appears to me that ceph should not be an issue. Could you check the following:

- The ceph_port you are using is correct. 
- The aws cli output of this command: 
`aws --endpoint=http://172.21.148.53 s3 ls`
[It will confirm that the aws credentials are set correctly]
- If the profile is not "default" you need to set the AWS_PROFILE environment variable

**Comment by ihong321** [comment]
It seems that the cause of the problem is not the Ceph port, credential or region. It is possible to check the list of buckets or fetch the object list of buckets using aws cli.

If those were the cause of the problem, I think the Triton error message would have been "Could not get MetaData for bucket with name" instead of "at least one version must be available under the version policy of model".

**Comment by CoderHam** [comment]
@ihong321 Thanks for getting back to me with this information. Can you confirm that the same model loads file in Tritonserver from a local filesystem?

**Comment by ihong321** [comment]
@CoderHam I've tested local filesystem, CephFS, and Ceph S3 storage using the same model. It worked well with the local filesystem and CephFS, but there was a problem with Ceph S3 storage.

**Comment by CoderHam** [comment]
We have a couple fixes (#2879 and #2880) that should solve your issue. Feel free to try a build out these patches and get back to us with your feedback. 
Closing this ticket. Please let us know if you still face the problem.
