### ISSUE TITLE
How to install tritonclient?

### ISSUE THREAD

**Issue by gr8Adakron** [triton-inference-server/server#2040]
I have install TritonClient using Docker then I did following step to get client wheel files:

```
mkdir clients
cd clients
wget https://github.com/triton-inference-server/server/releases/download/v2.2.0/v2.2.0_ubuntu1804.clients.tar.gz
tar xzf v2.2.0_*

```
then I did:

`pip install triton*.whl
`
which install triton-client:

But then I tried to run this in python terminal:

```
import tritonclient.grpc as grpcclient
import tritonclient.grpc.model_config_pb2 as mc
```
**I get error as NoModuleFound: tritonclient**

Any help, will be appreciated!

**Comment by gr8Adakron** [comment]
One thing I notice is there is no **tritonclient.whl file** in the repo and it has all this wheel file:

```
tritonshmutils-2.2.0-py3-none-manylinux1_x86_64.whl
tritonhttpclient-2.2.0-py3-none-any.whl
tritonclientutils-2.2.0-py3-none-any.whl
tritongrpcclient-2.2.0-py3-none-any.whl

```

**Comment by gr8Adakron** [comment]
@sublee @dougn @huntrax11

**Comment by deadeyegoodwin** [comment]
You need to look at the 2.2 documentation. Triton 2.3 is releasing today as a 20.09 container on NGC and in the 2.3 release we are also release a pip package to the NVIDIA index in pypi. So if you want to use tritonclient imports as you show then you can follow the install directions here: https://github.com/triton-inference-server/server/blob/master/src/clients/python/library/README.md

**Comment by sublee** [comment]
I don't understand why I am mentioned.
