### ISSUE TITLE
Same code working for one postprocess backend but not for another.

### ISSUE THREAD

**Issue by MeghaGhosh** [triton-inference-server/server#2046]
Hi. I have 2 TensorRT Mask RCNN models running together. I require the same image to be preprocessed and passed to both. Hence this is my flow:
Custom backend preprocesses image -> this is passed to both the TensorRT engines with different number of classes  (say A and B) -> A is passed to custom backend to postprocess A and B is passed to custom backend to postprocess B. 

The config files for each are fine, the ensemble config file is fine - the postprocess code for both are exactly the same except for the num of classes. Each TensorRT model outputs 2 tensors (detection and mask). The postprocess code for A is working absolutely fine, however for B it is not. There is no indication as to what the error is. It stops at !input_fn(input_context, name, &content, &content_byte_size) for the second output tensor (mask). There is nothing wrong with the dimensions/size etc - it just prints the line before this in the backend and gives a "socket closed" output in the client side and the running server container stops. There is no reason why this could happen because both the codes are the same, tensor names are the same and they are connected properly in the ensemble. What could possibly be the issue here and how can I debug it? I am using **20.03.1** containers for both server and client.

**Comment by deadeyegoodwin** [comment]
Please look at the template that is provided when you open an issue. What is the model configuration? What frameworks are you using? What is the console output? Have you tried using --log-verbose=1?

**Comment by MeghaGhosh** [comment]
Sorry, my bad. Didn't see the template and I thought mentioning TensorRT MaskRCNN was enough to provide the details such as model configuration and framework. The console output was "socket closed" and --log-verbose=1 was enabled. Anyway we did manage to solve that so you can close this issue. Turns out there was probably a segmentation fault elsewhere hence the thread running the second postprocess code was exiting abruptly. Maybe a log for segmentation fault in the backend code could be useful?

I do have a question unrelated to the topic of this issue. Great if you can answer it here. Can I enable dynamic batching for a custom backend with max_batch_size=1 in the config file (in the same way as it is to be enabled for a, say TensorRT or Tensorflow model) ?

**Comment by deadeyegoodwin** [comment]
You can enable dynamic batching for custom backends just like for other frameworks. But if your max-batch-size is 1 then the dynamic batcher can't do anything.
