### ISSUE TITLE
the model expects 0 dimensions (shape []) but 0 dimensionsid not allowed

### ISSUE THREAD

**Issue by mozheng** [triton-inference-server/server#2052]
the  net is
![企业微信截图_de5a63ad-6da0-467d-8a12-f895783d7f3b](https://user-images.githubusercontent.com/9405676/93859683-81e76e80-fcf0-11ea-9cd7-af86178ee2ad.png)

This my config.pbtxt.
``` pbtxt
name: "inprivacy"
platform: "tensorrt_plan"
version_policy: { all { } }

input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [ -1, 3, 540, 960]
  }
]
output [
  {
    name: "output_0"
    data_type: TYPE_FP32
    dims: [ -1, 21000, 4 ]
  },
  {
    name: "output_1"
    data_type: TYPE_FP32
    dims: [ -1, 21000, 2 ]
  },
  {
    name: "output_2"
    data_type: TYPE_FP32
    dims: [ -1, 21000, 10 ]
  },
  {
    name: "350"
    data_type: TYPE_INT32
    dims: [ 1 ]
  }

]
```
but the error is:
```log
 E0922 07:46:01.600328 1 model_repository_manager.cc:1007] failed to load 'inprivacy' version 2: Invalid argument: model 'inprivacy_0_gpu0', tensor '350': the model expects 0 dimensions (shape []) but the model configuration specifies 1 dimensions (shape [1])
```

Do you have other method.

**Comment by deadeyegoodwin** [comment]
Delete everything from the config except "platform" and then run triton with --strict-model-config=false. Triton will then generate the appropriate config for you. see https://docs.nvidia.com/deeplearning/triton-inference-server/master-user-guide/docs/model_configuration.html#generated-model-configuration
