### ISSUE TITLE
Send a raw image file from a client to a Triton server

### ISSUE THREAD

**Issue by Jungmo** [triton-inference-server/server#2059]
Hello

I have a question about the design principle of the Triton inference server.
As I try to use client/python/image_client.py, there are preprocessing jobs before sending input data to the Triton server.
I think this approach has some problems;
1) The size of the data to be transmitted might be increased. 
When I want to classify 224*224*3 JPG image file (15KB), I need to send 1.3MB of preprocessed data (the result of set_data_from_numpy in tritonhttpclient) to the inference server.

2) The computation burden of client devices is increased because of preprocessing what I aforementioned.
 If the client device is an embedded device or mobile device, this might be a crucial problem that will increase battery consumption because the size of transmitted data is increased. 

For example, [Torchserve ](https://github.com/pytorch/serve) allows sending raw image file to the server([link](https://github.com/pytorch/serve/blob/master/README.md#get-predictions-from-a-model)).

I wonder what is the advantage of such implementation (preprocessing before sending data).

**Comment by GuanLuo** [comment]
The image_client is mainly used as example to show case how one can send inference request to a typical image model which expects the input to be a matrix of some fixed dimensions.

For your use case, you may be interested in Triton's ensemble feature which allows you to specify a pipeline of model execution. We provides an [example](https://docs.nvidia.com/deeplearning/triton-inference-server/master-user-guide/docs/client_example.html#ensemble-image-classification-example-application) that uses Triton features to construct a pipeline that accepts JPG image as input and produces classification results.

**Comment by deadeyegoodwin** [comment]
There is also a ensemble example that uses DALI in https://github.com/triton-inference-server/dali_backend
