### ISSUE TITLE
how to create .so file for a model

### ISSUE THREAD

**Issue by rkoystart** [triton-inference-server/server#2060]
I amy planning to use a custom backend . So in the config.pbtxt file i specify the "platform": custom and now i need a  .so file for the model i want to load .

can you please tell me how to create a .so file for the model

Thanks in advance!!!!!

**Comment by deadeyegoodwin** [comment]
If you are creating a custom backend you should *not* use custom.h. That is the API for the old backend API that is now deprecated. You should use the new backend API that is described at the below link. There are also pointers to examples with build instructions, etc.  https://github.com/triton-inference-server/backend
