### ISSUE TITLE
the results are in descending order, is it right?

### ISSUE THREAD

**Issue by ctxqlxs** [triton-inference-server/server#2067]
```
std::unique_ptr<nic::InferenceServerHttpClient> client;
nic::InferenceServerHttpClient::Create(&client, url, verbose);
....
nic::InferResult* result;
client->Infer(&result, options, inputs, outputs, http_headers);
std::vector<std::string> result_data;
result->StringData("prob", &result_data);
```
**the result are in descending order,**
![image](https://user-images.githubusercontent.com/27945719/94504452-62de6480-023b-11eb-93a1-396096fb3f29.png)
![image](https://user-images.githubusercontent.com/27945719/94504487-78ec2500-023b-11eb-8620-952539ea76b2.png)

however, i need the raw results, how can i get it?

**Comment by GuanLuo** [comment]
Can you post the complete client code? It seems like you requested Triton to perform [classification postprocessing](https://github.com/triton-inference-server/server/blob/master/docs/protocol/extension_classification.md), which will be requested if you instantiate the inference output object with non-zero class_count (see [here](https://github.com/triton-inference-server/server/blob/b50564027d80e73065e2eaddf4fce682eab25954/src/clients/python/examples/image_client.py#L296)). Please provide the complete code snippet if that is not the case.
