### ISSUE TITLE
Failed to build identity_backend, square_backend and repeat_backend

### ISSUE THREAD

**Issue by t90tank** [triton-inference-server/server#2068]
**Description**
Follow instrcutions in https://github.com/triton-inference-server/square_backend, and get compile error. 

**Expected behavior**
Successfully build.

**Comment by deadeyegoodwin** [comment]
Is the build still failing for you? Can you include the compile log that shows the error.

**Comment by t90tank** [comment]
on the step "make install", I got:
error: ‘unique_ptr’ is not a member of ‘std’
       std::unique_ptr<
       ^
/root/triton-tnn/square_backend/build/_deps/repo-backend-src/src/backend_common.cc:487:33: error: expected primary-expression before ‘,’ token
           TRITONBACKEND_Response, decltype(&TRITONBACKEND_ResponseDelete)>
                                 ^
/root/triton-tnn/square_backend/build/_deps/repo-backend-src/src/backend_common.cc:487:35: error: expected primary-expression before ‘decltype’
           TRITONBACKEND_Response, decltype(&TRITONBACKEND_ResponseDelete)>
                                   ^
/root/triton-tnn/square_backend/build/_deps/repo-backend-src/src/backend_common.cc:487:35: error: expected ‘;’ before ‘decltype’
make[2]: *** [_deps/repo-backend-build/CMakeFiles/triton-backend-utils.dir/src/backend_common.cc.o] Error 1
make[1]: *** [_deps/repo-backend-build/CMakeFiles/triton-backend-utils.dir/all] Error 2
make: *** [all] Error 2


It is likely that the codes from github forgot "#include <memory>" and initialize same variables

**Comment by deadeyegoodwin** [comment]
Are you building on Ubuntu 18.04 or some other OS?
Can you go into the triton-inference-server/backend repo and follow the build instructions there and see if you get the same failure.
If you do edit src/backend_common.cc and add "#include <memory>" at the beginning of the file and see if that fixes.

**Comment by t90tank** [comment]
Thanks, I edit src/backend_common.cc and successfully build. I can also fix the problem by upgrading my gcc version.

**Comment by deadeyegoodwin** [comment]
Fixed with https://github.com/triton-inference-server/backend/pull/7
