### ISSUE TITLE
Model auto loading unuseful

### ISSUE THREAD

**Issue by whillas** [triton-inference-server/server#2076]
**Is your feature request related to a problem? Please describe.**

When new models are automatically loaded using `model-control-mode=poll` Triton first **unloads** the old model before loading the new model. This creates _down time_ for that model since the state of the old version of the models becomes `UNAVAILABLE` while the new version is `LOADING`

Also, if 2 versions of the model are loaded and then you unload one of them, the other goes into a  LOADING state, so there is **no way to avoid down time**

**Describe the solution you'd like**
Model configuration option to control the why models are loaded i.e. load the new model before unloading the old to minimise down time.

**Describe alternatives you've considered**
We have no alternatives as we're using the bucket polling option to manage our deployments. 

Our plan was to attach a sidecar to the container to poll the `/v2/repository/index` endpoint to determine if a new model is loaded and then change the version in `config.pbtxt` to avoid down time

**Additional context**
Come on man, we can't have down time in a production environment. If Triton is supposed to be a model management solution then it has to handle this usecase. Also, my other complaint about [model distribution across multiple GPUs](https://github.com/triton-inference-server/server/issues/1644) also ties into this.

**Comment by deadeyegoodwin** [comment]
We will look into the break in availability during a reload. But you should consider using the explicit model control mode to control when models are loaded, unloaded and reloaded.  The polling mode has potential race condition in that triton could poll the filesystem at the exact time that you are modifying it.

**Comment by whillas** [comment]
Sure, but it says in the documentation:
>  After startup, all model load and unload actions must be initiated explicitly by using the **Model Control API**. The response status of the model control request indicates success or failure of the load or unload action.

The Model Control API seems to be completely undocumented?

**Comment by deadeyegoodwin** [comment]
https://github.com/triton-inference-server/server/blob/master/docs/protocol/extension_model_repository.md

**Comment by whillas** [comment]
I don't see anything about model version when loading and unloading? How can we use this to load the next version before unloading the last?

**Comment by deadeyegoodwin** [comment]
When a model is unloaded all versions indicated by the model version policy are loaded and made available. You control which versions of the model are loaded and made available by setting the version policy appropriately in the model configuration. See the model configuration documentation for details. We already said we are looking into fixing the issue with gap in coverage when unloading/loading. We'll let you know when we have any update on that.

**Comment by whillas** [comment]
Just tested this and it still unloads all models when moving from
```
version_policy: { specific { versions: [1,2] } }
```
to
```
version_policy: { specific { versions: [2] } }
```
so its impossible to load in a new version without downtime.

plz don't make me open another ticket

**Comment by GuanLuo** [comment]
Are you using the current master? Can you share a minimum repo? As part of the PR, we added tests on checking the previous version is still valid for inference while a different set of versions are being load: https://github.com/triton-inference-server/server/blob/master/qa/L0_lifecycle/lifecycle_test.py#L1625-L1681

**Comment by whillas** [comment]
I'm using official container 20.10.
I'm looking at the model status which changes from READY > LOADING > READY for v2 in the above example. Perhaps its just the status that is broken?

**Comment by GuanLuo** [comment]
The change is not included in 20.10, but it will be included in 20.11 release.

**Comment by whillas** [comment]
I was told it would be updated in 20.10. So i guess I'll wait till 20.11 is released...

**Comment by statfs** [comment]
Any progress now?

**Comment by GuanLuo** [comment]
@statfs Are you still seeing the issue after 20.11 release? Please create a separate GitHub issue with minimal repo if that is the case
