### ISSUE TITLE
unable to provide 'output__0' in GPU, will use CPU

### ISSUE THREAD

**Issue by whatdhack** [triton-inference-server/server#2090]
**Description**
The above message was observed in the output log .  Wondering what is causing that and how to fix. 

**Triton Information**
What version of Triton are you using?
nvcr.io/nvidia/tritonserver:20.08-py3

Are you using the Triton container or did you build it yourself? 
container

**To Reproduce**
Not really  sure

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

Framework :  pytorch_libtorch

config.pbtxt:
```
platform: "pytorch_libtorch"
max_batch_size: 0
input [
        {
        name: "input__0"
        data_type: TYPE_FP32
        dims:   3
        dims:  -1
        dims:  -1
      }
]
output [
      {
        name: "output__0"
        data_type: TYPE_FP32
        dims: 1
        dims: 100
      },
      {
        name: "output__1"
        data_type: TYPE_FP32
        dims: 1
        dims: 100
      },
      {
        name: "output__2"
        data_type: TYPE_FP32
        dims: 1
        dims: 100
        dims:  4
      }
]
```

**Expected behavior**
Should not see reference to CPU.

**Comment by Tabrizian** [comment]
Did you use `--gpus=1` flag when running the container?

**Comment by whatdhack** [comment]
Yes, tried borh 1 and all. Same output.

**Comment by GuanLuo** [comment]
What exactly is the error message?

**Comment by whatdhack** [comment]
That is the exact message . Not much more is printed.  You can grep for that string and find it in the source. Looked into that too,  could not identify any further cause.

**Comment by CoderHam** [comment]
@whatdhack this log comes from the HTTP / gRPC server. It's not an error. Since the output is returned via HTTP/GRPC the buffer resides on CPU not GPU even though your model outputs may have been on GPU.

**Comment by whatdhack** [comment]
Makes sense thanks. However , I am getting a HTTP  400 error. Thought that was the cause.

**Comment by CoderHam** [comment]
I can help you better if you show you server / client logs. Clearly getting this logged means the server gets and runs an inference.

**Comment by whatdhack** [comment]
That is good to know. Here is the server log. 

```
I1007 02:44:07.306165 112 pinned_memory_manager.cc:130] pinned memory allocation: size 11997000, addr 0x7f8cf0000090
samples.tensors:  [1, 3, 1333, 750]
In xxxx.forward
Out of xxxx.forward
I1007 02:44:07.441136 112 infer_response.cc:139] add response output: output: output__0, type: FP32, shape: [1,100]
I1007 02:44:07.441160 112 http_server.cc:1166] HTTP: unable to provide 'output__0' in GPU, will use CPU
I1007 02:44:07.441175 112 http_server.cc:1186] HTTP using buffer for: 'output__0', size: 400, addr: 0x7f8aec3285b0
I1007 02:44:07.441208 112 pinned_memory_manager.cc:130] pinned memory allocation: size 400, addr 0x7f8cf0b70fe0
I1007 02:44:07.441249 112 pinned_memory_manager.cc:157] pinned memory deallocation: addr 0x7f8cf0b70fe0
I1007 02:44:07.441288 112 http_server.cc:1201] HTTP release: size 400, addr 0x7f8aec3285b0
I1007 02:44:07.441306 112 pinned_memory_manager.cc:157] pinned memory deallocation: addr 0x7f8cf0000090
I1007 02:45:56.944976 112 http_server.cc:1215] HTTP request: 0 /
I1007 02:45:56.945016 112 http_server.cc:1286] HTTP error: 0 / - 400

```

Here is the client log

```
  File "..../python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://.....

```

**Comment by whatdhack** [comment]
Looks like ouput type in the config.pbtxt was the problem - TYPE_INT64 vs TYPE_FP32.  Some sort of hint would have been great.

**Comment by CoderHam** [comment]
The server does report an error if the model fails or the output data type does not match the data type specified in the model config. For PyTorch the output type cannot be verified since the model does not store the data type. It is the users responsibility to verify that the model config data type is correct.

**Comment by whatdhack** [comment]
I see. So the server  knows something is wrong, but has no details on it ? Is it an exception the server encountered ?  If so, there is bound to be some traces.

**Comment by GuanLuo** [comment]
@whatdhack I agree that the error should be returned with a detailed message. Regarding the log you posted, this message, `I1007 02:45:56.945016 112 http_server.cc:1286] HTTP error: 0 / - 400`, will only be printed if the url doesn't matches any of the regexps, can you confirmed that your client is sending request to the correct endpoints?

Also it seems like your log contains information from handling different requests, can you isolate the request that behaves unexpectedly to help finding the root cause?

**Comment by whatdhack** [comment]
@GuanLuo ,  after the fix, I did not spend any time  on why 400 was sent.  Good error messages  help in quickly root causing issues.  Hence, I would strongly encourage enhancing the error message.

**Comment by deadeyegoodwin** [comment]
We will look into improving the error message.

**Comment by CoderHam** [comment]
Fixed by https://github.com/triton-inference-server/server/pull/2173

**Comment by bhupendrasalesken** [comment]
I getting the same logs, though inference is running and running correct but as it is using CPU , it's very slow.

`I0524 13:06:57.818420 1 libtorch.cc:1087] model multiqa_pr, instance multiqa_pr_0_1, executing 1 requests
I0524 13:06:57.818433 1 libtorch.cc:504] TRITONBACKEND_ModelExecute: Running multiqa_pr_0_1 with 1 requests
I0524 13:06:58.631790 1 infer_response.cc:165] add response output: output: OUTPUT__0, type: FP32, shape: [64,256,384]
I0524 13:06:58.631863 1 http_server.cc:1226] HTTP: unable to provide 'OUTPUT__0' in GPU, will use CPU
I0524 13:06:58.631896 1 http_server.cc:1246] HTTP using buffer for: 'OUTPUT__0', size: 25165824, addr: 0x7fb4f1fff040
I0524 13:06:58.861857 1 infer_response.cc:165] add response output: output: OUTPUT__1, type: FP32, shape: [64,384]
I0524 13:06:58.861898 1 http_server.cc:1226] HTTP: unable to provide 'OUTPUT__1' in GPU, will use CPU
I0524 13:06:58.861907 1 http_server.cc:1246] HTTP using buffer for: 'OUTPUT__1', size: 98304, addr: 0x7fb40e4f1b80
I0524 13:07:01.856685 1 http_server.cc:1261] HTTP release: size 25165824, addr 0x7fb4f1fff040
I0524 13:07:01.858047 1 http_server.cc:1261] HTTP release: size 98304, addr 0x7fb40e4f1b80`

can you please let me know if something is wrong.

Thanks
