### ISSUE TITLE
Failing to comsume Triton's Prometheus in Grafana

### ISSUE THREAD

**Issue by tom-r-o** [triton-inference-server/server#2091]
**Description**
Failing to comsume Triton's Prometheus in Grafana.

**Triton Information**
Triton version: 20.09

**Are you using the Triton container or did you build it yourself?**
Using the pre-built Triton container locally, on a machine without a GPU.

**To Reproduce**
Followed the quick start guide.
Then surfing to http://localhost:8002/metrics yields this [metricsOutput.txt](https://github.com/triton-inference-server/server/files/5334909/metricsOutput.txt). Not sure if that's what it is supposed to show.

Tried to create a new Prometheus source in Grafana, using the following url: http://localhost:8002/metrics
Which returned an "HTTP Error Bad Request" in Grafana.

**Expected behavior**
See Prometheus' web gui on http://localhost:8002/metrics
Be able to consume http://localhost:8002/metrics on Grafana as a Prometheus source.

**Comment by deadeyegoodwin** [comment]
The output you show is the metrics in the prometheus data format and is what is expected. It is likely that your prometheus setup is somehow incorrect.

**Comment by tom-r-o** [comment]
Thank you for replying quickly.

Do you perhaps mean that my Grafana setup is incorrect?
All I did was create a new source in Grafana and put the http://localhost:8002/metrics url in it.
Any relevant guide?

The setup:
![Grafana](https://user-images.githubusercontent.com/1384382/95228793-6d36ca80-0808-11eb-8a5f-2a591166d65f.png)

**Comment by deadeyegoodwin** [comment]
I'm not sure you can point grafana directly to Triton. You might need prometheus to scrap Triton and then grafana points to that prometheus. In any case you should be able to find prometheus / grafana documentation about how to set that up. Triton itself doesn't do anything custom or different with respect to metrics.

**Comment by vsatpathy** [comment]
I am facing the same issue, but I guess the issue for all of us is with the integration with prometheus.
As when I open the Prometheus UI it always keeps saying that http://localhost:8002/metrics is down

<img width="1676" alt="Screenshot 2021-11-02 at 10 14 32 PM" src="https://user-images.githubusercontent.com/61777986/139908717-90dc4b25-5320-40dc-a1b1-079af92372c1.png">

Although I do get response from the triton metrics end point as expected - 
<img width="908" alt="Screenshot 2021-11-02 at 10 16 12 PM" src="https://user-images.githubusercontent.com/61777986/139908972-e7d70dc4-3c37-4c5a-8a61-f27cba23c61c.png">

And hence when I try to integrate it with Grafana, the system keeps throwing an error.
Has anyone been able to resolve this issue?

**Comment by vsatpathy** [comment]
@hit-lance have you tried exporting your metrics to Prometheus and adding prometheus to your Grafana dashboard.
Apparently that's what is recommended by Nvidia
