### ISSUE TITLE
V2 API Migration

### ISSUE THREAD

**Issue by turowicz** [triton-inference-server/server#2092]
Hi

How to get started on API migration? Where are all the protos gone and how should we go about using the protocol?

**Comment by turowicz** [comment]
Bunch of things are missing such as `response.RequestStatus`

**Comment by deadeyegoodwin** [comment]
Have you looked in the clientsdk container on NGC? The protocols are described here: https://github.com/triton-inference-server/server/blob/master/docs/protocol/README.md

For GRPC the protobuf is here: https://github.com/triton-inference-server/server/blob/master/src/core/grpc_service.proto

**Comment by tanmayv25** [comment]
> How to get started on API migration? Where are all the protos gone and how should we go about using the protocol?
I would suggest spending some time going through the REST/GRPC endpoint specification here: https://github.com/kubeflow/kfserving/blob/master/docs/predict-api/v2/required_api.md

If you are using our client library, then look at:
1.  https://github.com/triton-inference-server/server/blob/master/src/clients/c%2B%2B/library/http_client.h.in 
2.  https://github.com/triton-inference-server/server/blob/master/src/clients/c%2B%2B/library/grpc_client.h.in
3. https://github.com/triton-inference-server/server/tree/master/src/clients/python/library/tritonclient

Look at the `simple_*` examples within `src/clients` to get more idea about using the new API through our client library.

**Comment by turowicz** [comment]
@deadeyegoodwin I know the `.proto` by heart by now, but it's lacking details on allowed values of params et al. Thanks anyway ;)

Thanks @tanmayv25 this is what I was looking for. 

What we are missing is actual documentation, so people don't have to read header files in examples in order to figure out what the protocol is. I'm working with C# so for me it's not as simple as using the included

**Comment by deadeyegoodwin** [comment]
Can you be more specific as to what is missing from the protocol documentation that we linked to in the above comments. We would like to improve that documentation if something is missing.

**Comment by turowicz** [comment]
@deadeyegoodwin the linked "documentation" points to a header file inside a C++ client library. While it is enough for me, I wasn't able to find it on my own, and other people using different technologies than C++ may have difficulties reading it. The information I needed, ie. specification of Parameters, is there and not in any .MD generated file.

**Comment by turowicz** [comment]
@deadeyegoodwin actually I still can't see the equivalent of `response.RequestStatus` from V1.

**Comment by deadeyegoodwin** [comment]
This link points to the specification of the HTTP/REST and GRPC protocols: https://github.com/kubeflow/kfserving/blob/master/docs/predict-api/v2/required_api.md

If you are interested in Triton-specific extensions: https://github.com/triton-inference-server/server/blob/master/docs/protocol/README.md

In the specifications is the statement "For each of these endpoints errors are indicated by the google.rpc.Status returned for the request. The OK code indicates success and other codes indicate failure."
I believe that is what you are asking.

**Comment by turowicz** [comment]
Yes it is. For some reason the official Grpc Tools don't generate those properties for me (from the .proto).

**Comment by deadeyegoodwin** [comment]
Were you able to resolve this issue?

**Comment by turowicz** [comment]
Yes @deadeyegoodwin but the work has been halted as I'm recovering from covid.

**Comment by deadeyegoodwin** [comment]
Sorry to hear that... I hope you have a quick and complete recovery.

**Comment by AlgirdasKartavicius** [comment]
Do you have plans to finish C# client example?
