### ISSUE TITLE
Triton unable to access GPU on Jetson Nano

### ISSUE THREAD

**Issue by ishantbansal** [triton-inference-server/server#2095]
installed TRTIS on nano with provided instructions but the server is unable to find GPU and throws error

**Comment by CoderHam** [comment]
We don't test on Jetson Nano (only on Xavier). Could you elaborate what the error thrown is?

**Comment by turowicz** [comment]
@ishantbansal did you use the precompiled jetson executables?

**Comment by ishantbansal** [comment]
@turowicz Yes using that ..followed instructions provided

@CoderHam failed to load 'resnet' version 1: Invalid argument: instance group resnet of model resnet must be KIND_GPU and must specify at least one GPU id
this is the error I'm getting .. 
if I put KIND_GPU in config then 
instance group resnet_0 of model resnet has kind KIND_GPU but no GPUs are available
this is error

**Comment by ishantbansal** [comment]
used these variables .. working fine now. Thanks
LD_PRELOAD=/home/ishant/Desktop/triton/lib/libtritonserver.so LD_LIBRARY_PATH=$LD_LIBRARY_PATH:lib/ ./bin/tritonserver --model-repository=/home/ishant/Desktop/models/ --min-supported-compute-capability=5.0

**Comment by turowicz** [comment]
For reference:
https://github.com/triton-inference-server/server/issues/2095
https://github.com/triton-inference-server/server/issues/1468

**Comment by ishantbansal** [comment]
also for not found plan file error .. renamed .engine file to .plan
