### ISSUE TITLE
fail to reload a model with the same name and different configurations

### ISSUE THREAD

**Issue by KEMDAK** [triton-inference-server/server#2100]
**Description**
When I load tensorflow model named **x**, then unload it and try to load a pytorch model with the same name **x**. the second model fails to load giving me this error.

```
I1008 15:15:26.444207 1 model_repository_manager.cc:753] unloading: bml-keypoint-alphapose:1
I1008 15:15:26.460247 1 model_repository_manager.cc:865] successfully unloaded 'bml-keypoint-alphapose' version 1
I1008 15:19:56.495221 1 server_status.cc:57] New status tracking for re-added model 'bml-keypoint-alphapose'
I1008 15:19:56.495285 1 model_repository_manager.cc:723] loading: bml-keypoint-alphapose:1
E1008 15:19:56.495499 1 model_repository_manager.cc:891] failed to load 'bml-keypoint-alphapose' version 1: Not found: expected model of type tensorflow_graphdef for bml-keypoint-alphapose
```

**Triton Information**
What version of Triton are you using? `1.13.0`

Are you using the Triton container or did you build it yourself? container version `20.03.1-py3`

**To Reproduce**
Steps to reproduce the behavior.
1. load the first model `bml-keypoint-alphapose`. this is the tensorflow one.
2. unload it by deleting it from the model_repository
3. load the second model `bml-keypoint-alphapose`. this is the pytorch one.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
### `bml-keypoint-alphapose` (tesorflow) 
```
.
├── bml-keypoint-alphapose
     ├── 1
     │   └── model.graphdef
     └── config.pbtxt
```
config.pbtxt
```
name: "bml-keypoint-alphapose"
platform: "tensorflow_graphdef"
max_batch_size: 0
input [
  {
    name: "input0"
    data_type: TYPE_FP32
    dims: [ -1, 3, 320, 256 ]
  }
]
output [
  {
    name: "output_0"
    data_type: TYPE_FP32
    dims: [ -1, 33, 80, 64 ]
  }
]
```
### `bml-keypoint-alphapose` (pytorch) 
```
.
└── bml-keypoint-alphapose
    ├── 1
    │   └── model.pt
    └── config.pbtxt
```
config.pbtxt
```
name: "bml-keypoint-alphapose"
platform: "pytorch_libtorch"
max_batch_size: 128
input [
  {
    name: "INPUT__0"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [3, 320, 256 ]
  }
]
output [ 
  {
    name: "OUTPUT__0"
    data_type: TYPE_FP32
    dims: [26, 80, 64 ]
  }
]
```

**Expected behavior**
I expect the first model to get unloaded and whenever I load another model with the same name, triton server will parse the config instead of using a cached version.

**Comment by GuanLuo** [comment]
Thanks for reporting the issue, the issue is due to the model platform is captured when the model is first seen and it should have been updated when new config is provided. I will push a fix to address the issue.
