### ISSUE TITLE
Triton 20.08 hangs on inference when Custom Backend (Legacy, either v1 or v2) has no output tensors specified

### ISSUE THREAD

**Issue by pdura7** [triton-inference-server/server#2104]
Hey, I have moved the Kaldi from NVIDIA DeepLearning Examples into the new triton version and I observed the following bug. Kaldi is built on Legacy custom backend r19.12 in which the client requests output tensor iff the last chunk of a sequence is passed (is_end=True). For intermediate (is_end=False) chunks infer() function takes an empty output tensor array and the model returns an empty array of results. However in 20.08 the client simply hangs.

It turns out that the engine expects that the tensor specified in the model's configuration be populated even though we don't request it in the client.

The solution was to populate the output tensor for each time step.

**Triton Information**
20.08
Pre-built container

**To Reproduce**
It's complicated

**Expected behavior**
I expected to receive a response with an empty array of results.

**Comment by deadeyegoodwin** [comment]
I'm not sure what you mean by "engine", of if you are saying that you believe there is an issue in the client, the custom backend, or in triton server. Can you explain again using consistent terminology.

**Comment by pdura7** [comment]
On the backend (in execute) I see that request count is >0 even though in the client no output is requested, so client is probably ok. It's either a normal behaviour that changed between versions, or some issue in the code that calls backend execute. I'm not familiar with terminology, probably would it call server if I had another chance.

**Comment by deadeyegoodwin** [comment]
By default, if the client doesn't explicitly request any outputs then the server will return all outputs produced by the model. That doesn't necessarily explain why the example stopped working. Thanks for the report and we will look into it.

**Comment by tanmayv25** [comment]
@pdura7 Can you share the following information?
1. The source code of your Kaldi custom backend.
2. The verbose logs on the server and client side when running some inference sequences
