### ISSUE TITLE
Prometheus output differs from nvidia-smi

### ISSUE THREAD

**Issue by szaboak** [triton-inference-server/server#2122]
So far we were using nvidia-smi/nvtop to monitor the GPU usage of our applications.
After checking Triton's Metric output on 8002 port, it looks very promising.
The only problem is, that it doesn't report the same data compared to previously used tools.

Example nvidia smi:
tritonserver                     1199MiB
Triton metric: 
nv_gpu_memory_total_bytes 1366294528.000000 ~= 1303 MiB

What version of Triton are you using?
r20.8 container version

Are you using the Triton container or did you build it yourself?

**To Reproduce**
- Install r20.8 docker as in the quick start guide.
- Check 8002 port.
-Compare with nvidia-smi output

**Expected behavior**

Maybe it's expected, but I still have some questions:
Why does the two output differ?
On which should we rely on?

**Comment by deadeyegoodwin** [comment]
I believe both tools should be using the same underlying libraries to report their GPU metrics so it is not clear why they would differ. Do you have just a single GPU on your system. Can you provide full output of both metrics endpoint and nvidia-smi.

**Comment by szaboak** [comment]
Hi @deadeyegoodwin,

I'm running tritonserver on a double-GPU system, but started the triton docker with the "-e NVIDIA_VISIBLE_DEVICES=1", as i want it to use only the second GPU.

I attached both output:
[nv_ticket_triton_metric_output.txt](https://github.com/triton-inference-server/server/files/5415491/nv_ticket_triton_metric_output.txt)
[nv_ticket_nvidia_smi_output.txt](https://github.com/triton-inference-server/server/files/5415497/nv_ticket_nvidia_smi_output.txt)

In these logs  nvidia-smi reported 1618 MiB for triton, while metric port reports 1722 MiB.

If you have a better solution to run triton only on a single GPU, and get proper metric data, let me know.

**Comment by Tabrizian** [comment]
The log that you have attached for nvidia-smi shows 1722 MiB which is the same as what Triton reports.
