### ISSUE TITLE
How to run Triton Inference Server docker container on a Jetson Nano?

### ISSUE THREAD

**Issue by RafayAK** [triton-inference-server/server#2126]
I'm having trouble just even running the Triton Inference server on a Jetson Nano. Here is my command and its resultant error:

Command:
```bash
sudo docker run --gpus=1 --rm --shm-size=1g \
--ulimit memlock=-1 --ulimit \
stack=67108864 -p 8000:8000 -p 8001:8001 \
-p 8002:8002 \
-v /home/rafay/Documents/server/docs/examples/model_repository:/models \
nvcr.io/nvidia/tritonserver:20.09-py3 tritonserver \
--model-repository=/models
```

error:
```bash
standard_init_linux.go:211: exec user process caused "exec format error"
```

Is Triton not supported on Jetson devices? Is there any other way I can run Triton in a container? 

BTW the model repo mounted is the one in https://github.com/triton-inference-server/server/docs/examples

Any help pointing me in the right direction will be greatly appreciated, first time trying to deploy a model to a Jetson device

**Comment by deadeyegoodwin** [comment]
The container released on NGC is for x86. The jetson releases we have done are delivered as tar files. See the release notes: https://github.com/triton-inference-server/server/releases/tag/v2.3.0

If you also search the issues (both open and closed) you will find some discussion on running triton on nano and other jetson platforms.
