### ISSUE TITLE
Deploying Bert TensorRT model with Triton

### ISSUE THREAD

**Issue by vilmara** [triton-inference-server/server#2133]
Hi all, 
1- What is the latest stable pre-built docker container version of triton inference server and tensorrt recommended to deploy a Bert TensorRT model?
2- What is the best way to put the files libbert_plugins.so and libcommon.so to /opt/tritonserver/ inside the docker container?, in order to avoid the error `INVALID_ARGUMENT: getPluginCreator could not find plugin CustomEmbLayerNormPluginDynamic version 1`

**Comment by CoderHam** [comment]
To be able to load and run models with custom TRT ops you must use LD_PRELOAD (as described here) while launching the server.
