### ISSUE TITLE
Different batch-size requests causes error, even the loading model supports batching

### ISSUE THREAD

**Issue by marsmiao** [triton-inference-server/server#2136]
**Description**
Hi, there. Here's the issue. When I use a max-batch-size-5 multi-layer perceptron model, I use client to perform random batch-size requests to infer. However, when I perform batch-size 10 request first and then use batch-size 2 request, and finally perform batch-size 10 request again. The later batch-size 10 request only remain 2 out of 10 (the first two) outputs correct.

**Triton Information**
What version of Triton are you using?
20. 07 and 20.09
Are you using the Triton container or did you build it yourself?
Both.

**To Reproduce**
Steps to reproduce the behavior.
Just use different batch-size request to call the same tritonserver (without restart it)

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

Any multi-layer perceptron model supports batching

**Expected behavior**

How can I fix this or is this a known bug. Thank you very much!!

**Comment by marsmiao** [comment]
@deadeyegoodwin I also read the source code to find `// All requests must have equally-sized input tensors so use any
    // request as the representative for the input tensors.
    repr_input_request = request.get();` which seems like different-size request is not supported by trt-backend

**Comment by deadeyegoodwin** [comment]
That comment refers to the batch-1 component of your tensor. For example, if your model batches along the first dimension and so accepts inputs of [ -1, 2, 2 ]. Then you can send [10, 2, 2], [2, 2, 2], etc. and they can/may be batched together depending on your dynamic batch settings and the maximum batch size allowed by your model. The comment you found is saying that if you have a model that allows [ -1, -1, -1 ] input and you send [ 10, 2, 2 ] and [ 2, 1, 3 ] then those can't be batched.

**Comment by marsmiao** [comment]
@deadeyegoodwin really appreciate your response. For my case, it is model with inputs shape like [-1, 8], and for model config I use implicit batch mode. Also for debugging, I shut off the dynamic batching option. What I found is that when I use one request with batch-size 10 it seems right and next I send request with batch-size 2 , which is also right. Finally, I use batch-size 10 requests and then it appears the last 8 batch of output is wrong answer. I print some debug information and I think it's because Triton only uses one TensorRT's context to handle all different batch-size request, and which is not supported by TensorRT.
Could you please give me some hints,'cause I don't know if this is the right phenomenon.

**Comment by deadeyegoodwin** [comment]
When you created the TensorRT model you should have set a maximum batch size and so as long as you don't exceed that you should be able to send in different size requests to the TensorRT model. You say the model is max-batch-size 5... so I don't think you should be able to send it a batch-size 10 request. Can you share the configuration file?

**Comment by marsmiao** [comment]
@deadeyegoodwin Sorry I have a typo at first, out model's max-batch-size is 2500:
`name: "mlp"
platform: "tensorrt_plan"
max_batch_size: 2500
input [
  {
    name: "input_1"
    data_type: TYPE_FP32
    dims: [884]
  },
  {
    name: "input_2"
    data_type: TYPE_FP32
    dims: [170]
  },
  {
    name: "input_3"
    data_type: TYPE_FP32
    dims: [1039]
  },
  {
    name: "input_4"
    data_type: TYPE_FP32
    dims: [25]
  },
  {
    name: "input_5"
    data_type: TYPE_FP32
    dims: [25]
  },
  {
    name: "input_6"
    data_type: TYPE_FP32
    dims: [25]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [1]
  }
]
instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [0]
  }
]`

**Comment by marsmiao** [comment]
@deadeyegoodwin I put some log in tritonserver and what I saw is when I send a batch-size 10 request first, its response seems okay, like 
![image](https://user-images.githubusercontent.com/56477651/96552861-f4933c00-12e6-11eb-91c1-ea4609d643b0.png)
, then I send a batch-size 2 request , whose response seems also okay, like
![image](https://user-images.githubusercontent.com/56477651/96553065-345a2380-12e7-11eb-84cd-50d08c45746b.png)
, then I re-send the batch-size 10 request above, the response seems not right but only the first 2 batch's result is okay, like
![image](https://user-images.githubusercontent.com/56477651/96553186-5fdd0e00-12e7-11eb-944a-613e50808e91.png)

Do you have thoughts on this? Or is tritonserver does not support this kind of requests? Thanks a lot, again.

**Comment by deadeyegoodwin** [comment]
Triton does support this kind of request. Did you make you TensorRT model from scratch or did you convert from another model format? If you converted, can you try using triton with the model in the original format and see if you get the correct behavior.

**Comment by marsmiao** [comment]
> Triton does support this kind of request. Did you make you TensorRT model from scratch or did you convert from another model format? If you converted, can you try using triton with the model in the original format and see if you get the correct behavior.

We have already found the problem, thanks a lot.

**Comment by CPFelix** [comment]
@marsmiao So, what's the problem?
