### ISSUE TITLE
Failed to connect all addresses

### ISSUE THREAD

**Issue by KingsleyLiu-NV** [triton-inference-server/server#2140]
**Description**
I am using the python backend and the model repository layout is like this:
root@c437d4b0d6fd:/server/docs/examples/python_model_repository# tree
```bash
.
|-- add_sub
|   |-- 1
|   |   |-- model.py
|   |   `-- triton_python_backend_utils.py
|   `-- config.pbtxt
`-- hugectr_tf
    |-- 1
    |   |-- 0_sparse_10000.model
    |   |-- _dense_10000.model
    |   |-- criteo_1gpu.json
    |   |-- model.py
    |   |-- sparse_embedding0.data
    |   `-- triton_python_backend_utils.py
    `-- config.pbtxt
```

Then I try to start the triton server by `tritonserver --model_repository=/server/docs/examples/python_model_repository`，and I can successfully load the `add_sub` model, but not the `hugectr_tf` model. The info is as below:

```bash
I1020 02:06:55.349644 555 model_repository_manager.cc:714] loading: hugectr_tf:1
I1020 02:06:55.349718 555 model_repository_manager.cc:714] loading: add_sub:1
2020-10-20 10:06:55.663569: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-10-20 10:06:55.663600: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
[INFO] begin to parse model json file: /server/docs/examples/python_model_repository/hugectr_tf/1/criteo_1gpu.json
[INFO] begin to parse embedding weights: sparse_embedding1
I1020 02:06:56.360641 555 model_repository_manager.cc:896] successfully loaded 'add_sub' version 1
index 1603611 is out of bounds for axis 0 with size 1603609
[INFO] begin to parse dense weights: InnerProduct
[INFO] begin to parse dense weights: InnerProduct
[INFO] begin to parse dense weights: InnerProduct
[INFO] begin to parse dense weights: InnerProduct
[INFO] all dense weights has been parsed.
E1020 02:07:00.553829 555 model_repository_manager.cc:899] failed to load 'hugectr_tf' version 1: Internal: failed to connect to all addresses
```

**Triton Information**
What version of Triton are you using?
20.09

Are you using the Triton container or did you build it yourself?
I am using the Triton container and I have built the python backend inside the container, which proved to work well with the `add_sub` model.

**To Reproduce**
Steps to reproduce the behavior.
Just as above.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
The input of `hugectr_tf` model is a 39-dim int32 vector, and the output is a float32 scalar.
The model.py, config.pbtxt, criteo_1gpu.json, dump.py, hugectr_tf.py will be shown in the below. 

**Expected behavior**
The triton server is expected to load the 'hugectr_tf' model successfully.

**Comment by Tabrizian** [comment]
Thanks for the report.

> index 1603611 is out of bounds for axis 0 with size 1603609 

It seems like the problem is with the input size.

Are you using GPUs? If yes, it seems like there is some problem with CUDA libraries.
@KingsleyLiu-NV Can you please share the content of `model.py`?

**Comment by KingsleyLiu-NV** [comment]
Hi Tabrizian, Thank you for your quick response. Here is `model.py`
`
import triton_python_backend_utils as pb_utils

from dump import DumpToTF, struct
from hugectr_layers import *

import os

model = "criteo"
json_file = "/server/docs/examples/python_model_repository/hugectr_tf/1/criteo_1gpu.json"
dataset = "/server/docs/examples/python_model_repository/hugectr_tf/1/sparse_embedding0.data"
dense_model = "/server/docs/examples/python_model_repository/hugectr_tf/1/_dense_10000.model"
sparse_models = ["/server/docs/examples/python_model_repository/hugectr_tf/1/0_sparse_10000.model"]

if model == "criteo":
    batchsize = 1
    slot_num = 1
    max_nnz_per_slot = 39

    dense_dim = 0

    model_json = json_file
    sparse_model_names = sparse_models
    dense_model_name = dense_model

    dump = DumpToTF(sparse_model_names = sparse_model_names,
                         dense_model_name = dense_model_name,
                         model_json = model_json,
                         non_training_params_json = None)

    checkpoint_path = r'./tf_checkpoint/criteo/'
    if not os.path.exists(checkpoint_path):
        os.makedirs(checkpoint_path)
    checkpoint = os.path.join(checkpoint_path, "criteo_model")
        

    #----------------- build computing graph--------------------#
    tf.reset_default_graph()

    graph = tf.Graph()
    with graph.as_default():
        # no dense input

        # sparse input = [batchsize, slot_num, max_nnz_per_slot]
        sparse_input = tf.placeholder(shape=(batchsize, slot_num, max_nnz_per_slot),
                            dtype=tf.int64, name='sparse-input')

        # dump embedding to tf
        layer_name, init_values = dump.parse_embedding().__next__()
        vocabulary_size = init_values.shape[0]
        embedding_feature = embedding_layer(sparse_input, init_values, combiner=0)
        
        # reshape1
        leading_dim = 64
        reshape1 = tf.reshape(embedding_feature, [-1, leading_dim])

        # dump fc1 to tf
        layer_type = "InnerProduct"
        num_output = 200
        layer_bytes = (reshape1.shape[1] * num_output + 1 * num_output) * 4
        weight_fc1, bias_fc1 = dump.parse_dense(layer_bytes, layer_type,
                                                in_feature=reshape1.shape[1],
                                                out_feature=num_output)
        fc1 = innerproduct_layer(reshape1, weight_fc1, bias_fc1)

        # relu
        relu1 = tf.nn.relu(fc1)

        # dump fc2 to tf
        layer_type = "InnerProduct"
        num_output = 200
        layer_bytes = (relu1.shape[1] * num_output + 1 * num_output) * 4
        weight_fc2, bias_fc2 = dump.parse_dense(layer_bytes, layer_type,
                                                in_feature=relu1.shape[1],
                                                out_feature=num_output)
        fc2 = innerproduct_layer(relu1, weight_fc2, bias_fc2)

        # relu2
        relu2 = tf.nn.relu(fc2)

        # dump fc3 to tf
        layer_type = "InnerProduct"
        num_output = 200
        layer_bytes = (relu2.shape[1] * num_output + 1 * num_output) * 4
        weight_fc3, bias_fc3 = dump.parse_dense(layer_bytes, layer_type,
                                                in_feature=relu2.shape[1],
                                                out_feature=num_output)
        fc3 = innerproduct_layer(relu2, weight_fc3, bias_fc3)

        # relu3
        relu3 = tf.nn.relu(fc3)

        # dump fc4 to tf
        layer_type = "InnerProduct"
        num_output = 1
        layer_bytes = (relu3.shape[1] * num_output + 1 * num_output) * 4
        weight_fc4, bias_fc4 = dump.parse_dense(layer_bytes, layer_type,
                                                in_feature=relu3.shape[1],
                                                out_feature=num_output)
        fc4 = innerproduct_layer(relu3, weight_fc4, bias_fc4)

        # check whether all dense weights are parsed
        dump.read_dense_complete()

        init_op = tf.group(tf.local_variables_initializer(),
                            tf.global_variables_initializer())

        saver = tf.train.Saver()


class TritonPythonModel:
    """Your Python model must use the same class name. Every Python model
    that is created must have "TritonPythonModel" as the class name.
    """

    def initialize(self, args):
        """`initialize` is called only once when the model is being loaded.
        Implementing `initialize` function is optional. This function allows
        the model to intialize any state associated with this model.

        Parameters
        ----------
        args : dict
          Both keys and values are strings. The dictionary keys and values are:
          * model_config: A JSON string containing the model configuration
          * model_instance_kind: A string containing model instance kind
          * model_instance_device_id: A string containing model instance device ID
          * model_repository: Model repository path
          * model_version: Model version
          * model_name: Model name
        """
        self.sess = tf.Session(graph=graph)
        self.sess.graph.finalize()
        self.sess.run(init_op)

        self.model_config = model_config = json.loads(args['model_config'])
        output0_config = pb_utils.get_output_config_by_name(
            model_config, "OUTPUT0")
        self.output0_dtype = pb_utils.triton_string_to_numpy(
            output0_config['data_type'])
        print('Initialized...')

    def execute(self, requests):
        """`execute` MUST be implemented in every Python model. `execute`
        function receives a list of pb_utils.InferenceRequest as the only
        argument. This function is called when an inference request is made
        for this model.

        Parameters
        ----------
        requests : list
          A list of pb_utils.InferenceRequest

        Returns
        -------
        list
          A list of pb_utils.InferenceResponse. The length of this list must
          be the same as `requests`
        """
        output0_type = self.output0_dtype
        responses = []

        # Every Python backend must iterate every request and create a
        # pb_utils.InferenceResponse for each of them.
        for request in requests:
            # Perform inference on the request and append it to responses list...
            in_0 = pb_utils.get_input_tensor_by_name(request, "INPUT0")
            keys = in_0.as_numpy()
            out_0 = sess.run(fc4, feed_dict={sparse_input:keys})
            out_tensor_0 = pb_utils.Tensor("OUTPUT0",
                                           out_0.astype(output0_dtype))
            inference_response = pb_utils.InferenceResponse(
                output_tensors=[out_tensor_0])
            responses.append(inference_response)
        # You must return a list of pb_utils.InferenceResponse. Length
        # of this list must match the length of `requests` list.
        return responses

    def finalize(self):
        """`finalize` is called only once when the model is being unloaded.
        Implementing `finalize` function is optional. This function allows
        the model to perform any necessary clean ups before exit.
        """
        self.sess.close()
        print('Cleaning up...')
`

**Comment by KingsleyLiu-NV** [comment]
> Thanks for the report.
> 
> > index 1603611 is out of bounds for axis 0 with size 1603609
> 
> It seems like the problem is with the input size.
> 
> Are you using GPUs? If yes, it seems like there is some problem with CUDA libraries.
> @KingsleyLiu-NV Can you please share the content of `model.py`?

Yes, I am using CUDA11.0, which is not supported by tf 2.3. But I think this may not be the reason why I cannot start the server.

**Comment by KingsleyLiu-NV** [comment]
Here is `config.pbtxt`
```bash

name: "hugectr_tf"
backend: "python"

input [
  {
    name: "INPUT0"
    data_type: TYPE_INT32
    dims: [ 39 ]

  }
]
output [
  {
    name: "OUTPUT0"
    data_type: TYPE_FP32
    dims: [ 1 ]
  }
]

instance_group [ { kind: KIND_CPU }]

```

**Comment by KingsleyLiu-NV** [comment]
Here is `dump.py`
```bash
import struct
import os
import numpy as np
import json


class DumpToTF(object):

    def __init__(self, sparse_model_names, dense_model_name, 
                model_json, non_training_params_json = None):

        self.sparse_model_names = sparse_model_names # list of strings
        self.dense_model_name = dense_model_name # string
        self.model_json = model_json # json file of the whole model
        self.non_training_params_json = non_training_params_json # non training params

        self.model_content = None
        self.embedding_layers = None
        self.dense_layers = None
        self.gpus = [0]
        self.key_type = 'I32' # {'I64', 'I32'}, default is 'I32'
        self.key_type_map = {"I32": ["I", 4], "I64": ["q", 8]}

        self.parse_json()

        self.offset = 0

    def parse_json(self):
        """
        parse the model json file to get the layers of the whole model.
        save in a list.
        then parse the non training params json file. to get the non-training-parameters.
        #returns:
            [embedding_layer, dense_layer0, dense_layer1, ...], 
            [non-training-params]
        """
        print("[INFO] begin to parse model json file: %s" %self.model_json)

        try:
            with open(self.model_json, 'r') as model_json:
                self.model_content = json.load(model_json)

                self.gpus = self.model_content["solver"]["gpu"]
                key_type = self.model_content["solver"].get("input_key_type")
                if key_type is not None:
                    self.key_type = key_type                
                
                layers = self.model_content["layers"]
                # embedding_layers
                self.embedding_layers = []
                for index in range(1, len(layers)):
                    if layers[index]["type"] not in ["DistributedSlotSparseEmbeddingHash",
                                                    "LocalizedSlotSparseEmbeddingHash"]:
                        break
                    else:
                        self.embedding_layers.append(layers[index])

                #dense layers
                self.dense_layers = layers[1 + len(self.embedding_layers): ]

        except BaseException as error:
            print(error)


    def parse_embedding(self):
        """
        get one embedding table at a time.
        """
        if self.model_content is None:
            self.parse_json()

        for index, layer in enumerate(self.embedding_layers):
            print("[INFO] begin to parse embedding weights: %s" %layer["name"])

            each_key_size = 0
            layer_type = layer["type"]
            embedding_vec_size = layer["sparse_embedding_hparam"]["embedding_vec_size"]
            max_vocab_size_per_gpu = layer["sparse_embedding_hparam"]["max_vocabulary_size_per_gpu"]

            vocabulary_size = max_vocab_size_per_gpu * len(self.gpus)

            if layer_type == "DistributedSlotSparseEmbeddingHash":
                # sizeof(TypeHashKey) + sizeof(float) * embedding_vec_size
                each_key_size = self.key_type_map[self.key_type][1] + 4 * embedding_vec_size

            elif layer_type == "LocalizedSlotSparseEmbeddingHash":
                # sizeof(TypeHashKey) + sizeof(size_t) + sizeof(float) * embedding_vec_size
                each_key_size = self.key_type_map[self.key_type][1] + 8 + 4 * embedding_vec_size

            embedding_table = np.zeros(shape=(vocabulary_size, embedding_vec_size), dtype=np.float32)

            with open(self.sparse_model_names[index], 'rb') as file:
                try:
                    while True:
                        buffer = file.read(each_key_size)
                        if len(buffer) == 0:
                            break
                        
                        if layer_type == "DistributedSlotSparseEmbeddingHash":
                            key = struct.unpack(self.key_type_map[self.key_type][0], buffer[0: self.key_type_map[self.key_type][1]])
                            values = struct.unpack(str(embedding_vec_size) + "f", buffer[self.key_type_map[self.key_type][1]: ])

                        elif layer_type == "LocalizedSlotSparseEmbeddingHash":
                            key = struct.unpack(self.key_type_map[self.key_type][0], buffer[0 : self.key_type_map[self.key_type][1]])[0]
                            slot_id = struct.unpack("Q", buffer[self.key_type_map[self.key_type][1] : self.key_type_map[self.key_type][1] + 8])[0]
                            values = struct.unpack(str(embedding_vec_size) + "f", buffer[self.key_type_map[self.key_type][1] + 8: ])

                        embedding_table[key] = values

                except BaseException as error:
                    print(error)

            yield layer["name"], embedding_table


    def parse_dense(self, layer_bytes, layer_type, **kwargs):
        """
        get one layer weights at a time.
        """
        if self.model_content is None:
            self.parse_json()
            self.offset = 0

        with open(self.dense_model_name, 'rb') as file:
            print("[INFO] begin to parse dense weights: %s" %layer_type)

            file.seek(self.offset, 0)

            buffer = file.read(layer_bytes)

            if layer_type == "BatchNorm":
                # TODO
                pass
            elif layer_type == "InnerProduct":
                in_feature = kwargs["in_feature"]
                out_feature = kwargs["out_feature"]

                weight = struct.unpack(str(in_feature * out_feature) + "f", buffer[ : in_feature * out_feature * 4])
                bias = struct.unpack(str(out_feature) + "f", buffer[in_feature * out_feature * 4 : ])

                weight = np.reshape(np.float32(weight), newshape=(in_feature, out_feature))
                bias = np.reshape(np.float32(bias), newshape=(1, out_feature))

                self.offset += layer_bytes
                return weight, bias


            elif layer_type == "MultiCross":
                vec_length = kwargs["vec_length"]
                num_layers = kwargs["num_layers"]

                weights = []
                biases = []

                each_layer_bytes = layer_bytes // num_layers

                for i in range(num_layers):
                    weight = struct.unpack(str(vec_length) + "f", buffer[i*each_layer_bytes : i*each_layer_bytes + vec_length * 4])
                    bias = struct.unpack(str(vec_length) + "f", buffer[i*each_layer_bytes + vec_length * 4 : (i+1)*each_layer_bytes])

                    weights.append(np.reshape(np.float32(weight), newshape=(1, len(weight))))
                    biases.append(np.reshape(np.float32(bias), newshape=(1, len(bias))))

                self.offset += layer_bytes

                return weights, biases

            elif layer_type == "Multiply":
                # TODO
                pass

    def read_dense_complete(self):
        if self.offset == os.path.getsize(self.dense_model_name):
            print("[INFO] all dense weights has been parsed.")
        else:
            print("[INFO] not all dense weights has been parsed.")

    def build_graph(self):
        """
        build computing-graph with tf according to model json file.
        """
        pass

    def save_to_checkpoint(self):
        """
        save the computing-graph with the loading weights into a tf checkpoint.
        """
        pass

    def get_key_type(self):
        return self.key_type
```

**Comment by KingsleyLiu-NV** [comment]
Here is `hugectr_layers.py`

```bash
try:
    # tensorflow 2.x
    import tensorflow.compat.v1 as tf
    tf.disable_v2_behavior()
except:
    # tensorflow 1.x
    import tensorflow as tf

import numpy as np


def embedding_layer(input_keys, init_values, combiner=0):
    """
    input_keys: [batch, slot_num, max_nnz_per_slot]
    """
    vocabulary_size, embedding_vec_size = init_values.shape

    # map -1 to zeros embedding-feature
    zeros = np.zeros(shape=(1, embedding_vec_size), dtype=np.float32)
    init_values = np.concatenate((init_values, zeros), axis=0)
    
    embedding_table = tf.get_variable(name='embedding-table', shape=init_values.shape, 
                                      dtype=tf.float32, 
                                      initializer=tf.constant_initializer(value=init_values))

    embedding_feature = tf.nn.embedding_lookup(embedding_table, input_keys)
    if combiner == 0:
        embedding_feature = tf.reduce_sum(embedding_feature, axis=-2)
    elif combiner == 1:
        embedding_feature = tf.reduce_mean(embedding_feature, axis=-2)

    return embedding_feature


def slice_layer(x, offsets, lengths):
    y = []
    for i in zip(offsets, lengths):
        y.append(tf.slice(x, [0, i[0]], [-1, i[1]]))
    return y


def multicross_layer(x, w, b, layers):
    y = []
    for i in range(layers):
        v = tf.linalg.matvec(x if i == 0 else y[i - 1], tf.Variable(w[i]))
        v = tf.transpose(v)
        m = tf.multiply(x, v)
        m = tf.add(m, x if i == 0 else y[i - 1])
        m = tf.add(m, tf.Variable(b[i]))
        y.append(m)
    return y

def innerproduct_layer(x, w, b):
    return tf.matmul(x, tf.Variable(w)) + tf.Variable(b)
```

**Comment by KingsleyLiu-NV** [comment]
> Thanks for the report.
> 
> > index 1603611 is out of bounds for axis 0 with size 1603609
> 
> It seems like the problem is with the input size.
> 
> Are you using GPUs? If yes, it seems like there is some problem with CUDA libraries.
> @KingsleyLiu-NV Can you please share the content of `model.py`?

Seems not the problem of the input size. Without triton, I can successfully load the model and make inference: 
@Tabrizian 
```bash
[INFO] running criteo...
[INFO] begin to parse model json file: criteo_1gpu.json
[INFO] begin to parse embedding weights: sparse_embedding1
index 1603611 is out of bounds for axis 0 with size 1603609
[INFO] begin to parse dense weights: InnerProduct
[INFO] begin to parse dense weights: InnerProduct
[INFO] begin to parse dense weights: InnerProduct
[INFO] begin to parse dense weights: InnerProduct
[INFO] all dense weights has been parsed.
2020-10-20 03:05:29.211324: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2020-10-20 03:05:29.306076: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties:
pciBusID: 0000:06:00.0 name: Tesla V100-SXM2-16GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 15.78GiB deviceMemoryBandwidth: 836.37GiB/s
2020-10-20 03:05:29.306193: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/openmpi/lib:/usr/local/hwloc/lib:/usr/local/ucx/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2020-10-20 03:05:29.306452: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcublas.so.10'; dlerror: libcublas.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/openmpi/lib:/usr/local/hwloc/lib:/usr/local/ucx/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2020-10-20 03:05:29.307595: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-10-20 03:05:29.307986: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-10-20 03:05:29.310576: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-10-20 03:05:29.310800: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcusparse.so.10'; dlerror: libcusparse.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/openmpi/lib:/usr/local/hwloc/lib:/usr/local/ucx/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2020-10-20 03:05:29.310957: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudnn.so.7'; dlerror: libcudnn.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/openmpi/lib:/usr/local/hwloc/lib:/usr/local/ucx/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2020-10-20 03:05:29.310970: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1753] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-10-20 03:05:29.311364: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-10-20 03:05:29.326845: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2195025000 Hz
2020-10-20 03:05:29.332066: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x46e58a0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-10-20 03:05:29.332106: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-10-20 03:05:29.333662: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-20 03:05:29.333677: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]
[INFO] Finish read a sample from %s sparse_embedding0.data
<class 'numpy.int64'> <class 'list'> <class 'numpy.ndarray'>
0
[]
[[[      2     365    5840    8106   11025  144676  150012  151981
    152540  156528  156541  156678  156873  157293  158801  159375
    430985  609983  610294  612740  622307  622941  627045  671224
    675962  946084  948795  949311  960691 1208214 1208284 1212984
   1215053 1215132 1479013 1479030 1479060 1550398 1550501]]]
[INFO] output = -1.203956
[INFO] save done.
```

**Comment by KingsleyLiu-NV** [comment]
@Tabrizian Could you help explain what is the cause of this error?
```bash
E1020 06:40:39.453334 5716 model_repository_manager.cc:899] failed to load 'hugectr_tf' version 1: Internal: Exception calling application: name 'json' is not defined
```

**Comment by Tabrizian** [comment]
@KingsleyLiu-NV Thank you for providing the details. It seems like you forgot to include JSON in `model.py`

**Comment by KingsleyLiu-NV** [comment]
> @KingsleyLiu-NV Thank you for providing the details. It seems like you forgot to import json in `model.py`

Thank you. I think this issue can be closed.
