### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by hebaishi** [triton-inference-server/server#2143]
**Is your feature request related to a problem? Please describe.**
Is it possible to build and run Triton on Windows? More specifically, can Triton provide multi-GPU inference, on Windows, using tensorflow as its backend? Has this ever been tested?

**Describe the solution you'd like**
I would simply like a clearer idea of whether Windows is a supported platform for Triton. If the questions above could be answered, that would be helpful.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by deadeyegoodwin** [comment]
Currently there is no windows port of Triton server. You can use the python client libraries on windows. You can also build the C++ client libraries on windows. We plan to eventually have a windows build of the server but we don't have an exact date when that will be available.
