### ISSUE TITLE
Non-numeric subdirectories are not ignored for version convertion 

### ISSUE THREAD

**Issue by jckhang** [triton-inference-server/server#2144]
**Description**
Hi, we have the following structure in the model directory. We noticed the `model` subfolder is never ignored by the server. That behavior doesn't match the statement in the document saying non-numeric subdirectories will be ignored.
```
<model-repository-path>/
  <model-name>/
    [config.pbtxt]
    <version>/
      <model-definition-file>
    <version>/
      <model-definition-file>
    model/
      ...
```

**Triton Information**
What version of Triton are you using?
nvcr.io/nvidia/tritonserver:20.08-py3

Are you using the Triton container or did you build it yourself?
container

**To Reproduce**
Steps to reproduce the behavior.

Create a subfolder with name 'model'. You can see the following message.
```
1 model_repository_manager.cc:1928] failed to convert version directory 'model' to integral number
1 model_repository_manager.cc:725] re-loading: foo:1
1 model_repository_manager.cc:908] successfully unloaded 'foo' version 1
1 model_repository_manager.cc:737] loading: foo:1
```

**Expected behavior**

https://github.com/triton-inference-server/server/blob/a788a3a140b6a9418040c5cb726da9e7caa93a1c/docs/model_repository.md#model-versions

Document mentions `The subdirectories that are not numerically named, or have names that start with zero (0) will be ignored.`

The expected logging should be similar to this indicating Triton is not trying to convert these subdirectories.
```
if ((subdir.length() > 1) && (subdir.front() == '0')) {
  LOG_WARNING << "ignore version directory '" << subdir
    << "' which contains leading zeros in its directory name";
  continue;
}
```

**Comment by deadeyegoodwin** [comment]
Thanks for the report, we will look into it.

**Comment by GuanLuo** [comment]
The message is logged to indicate there is a directory that is not numerically named, actually Triton will not try to load the content inside the directory and thus ignoring the directory. Are you suggesting to change the message (and the log level) to a different tone that is more like the case you mentioned?

**Comment by jckhang** [comment]
> The message is logged to indicate there is a directory that is not numerically named, actually Triton will not try to load the content inside the directory and thus ignoring the directory. Are you suggesting to change the message (and the log level) to a different tone that is more like the case you mentioned?

does the failure trigger the reloading the model even though no change has been made to the directory?

**Comment by GuanLuo** [comment]
It will not cause reload as long as there is not change in the model directory.

**Comment by jckhang** [comment]
Changing the tone of the message should work.
