### ISSUE TITLE
S3 Storage with POLL mode reloads models constantly

### ISSUE THREAD

**Issue by bezero** [triton-inference-server/server#2147]
**Description**
When I run Triton server with S3 model storage by setting `--model-control-mode=poll`, Triton constantly detects a change on the models, although there is no change, and tries to reload them.

**Triton Information**
20.09-py3

I am using a prebuild Triton container

**To Reproduce**
Put your models on S3 storage. Run Triton server with this storage and set `--model-control-mode=poll`.

I am using only ONNX models

**Expected behavior**
Triton Server should not reload models unless there is a change, as it does with running Triton from local storage

**Comment by CoderHam** [comment]
I will look into the cause of the same. In the meanwhile please use the explicit model control API.

**Comment by oscarA1994** [comment]
I have experienced the same issue with GS buckets and PyTorch models.

**Comment by CoderHam** [comment]
Please try the same with the latest release and re-open if needed. Thank you!
