### ISSUE TITLE
Where is the definition of TRITONBACKEND_ModelSetState

### ISSUE THREAD

**Issue by KingsleyLiu-NV** [triton-inference-server/server#2153]
**Description**
`identity_backend` is a good example for building a custom backend, but I find it confusing to find some API. For example, where is the definition of `TRITONBACKEND_ModelSetState` supposed to be found? It is declared in `tritonbackend.h`, but I cannot its definition inside any file inside `triton-inference-server/backend`. Right now the code layout is much too confusing.

**Triton Information**
None

Are you using the Triton container or did you build it yourself?
Triton container.

**To Reproduce**
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**

**Comment by deadeyegoodwin** [comment]
That is part of the TRITONBACKEND API. The entire API is documented in the backed repo. https://github.com/triton-inference-server/backend#triton-backend-api.

Pointers to this information are in the Documentation section of the main README: https://github.com/triton-inference-server/server#documentation
