### ISSUE TITLE
What is the difference between triton-inference-server/server/src/backends/backend and triton-inference-server/backend?

### ISSUE THREAD

**Issue by KingsleyLiu-NV** [triton-inference-server/server#2154]
**Description**
I find it confusing when trying to build my own backend.

**Triton Information**
What version of Triton are you using?

Are you using the Triton container or did you build it yourself?

**To Reproduce**
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**

**Comment by deadeyegoodwin** [comment]
If you are developing a Triton backend you do not need to look at anything in the server repo. You should look at the backend repo for instructions, examples, etc. https://github.com/triton-inference-server/backend
