### ISSUE TITLE
Do multiple instances of the same model share parameters?

### ISSUE THREAD

**Issue by KingsleyLiu-NV** [triton-inference-server/server#2155]
**Description**
Do multiple instances of the same model share parameters? For example, if we use `tensorflow backend`, and put the saved graphdef file in the model repository. When I start the tritonserver and specify this model, I create multiple instances of this model on the same GPU. Do these instances share the parameters? In other words, does each instance of the same model need its own whole set of parameters?
How about `python backend`? If I explicitly load the parameters in the `model.py` in the model repository and create multiple instances, does each instance need to load its own parameters? If we create many instances, will that be a heavy load for CPU/GPU memory?

**Triton Information**
What version of Triton are you using?

Are you using the Triton container or did you build it yourself?

**To Reproduce**
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**

**Comment by deadeyegoodwin** [comment]
Same question a #2156
