### ISSUE TITLE
Can multiple instances can use the same GPU shared memory?

### ISSUE THREAD

**Issue by KingsleyLiu-NV** [triton-inference-server/server#2156]
**Description**
We want to create multiple instances of the same model, can these instances use the same GPU memory? For example, we have 4 instances and only 1 copy of parameters on the same GPU memory address. Can they share this only one copy of the parameters?

**Triton Information**
What version of Triton are you using?

Are you using the Triton container or did you build it yourself?

**To Reproduce**
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**

**Comment by deadeyegoodwin** [comment]
It depends on the model framework. For some frameworks triton is sharing the weights across model instances but for others it has not yet done that optimization. You should be able to tell by comparing the memory usage of different numbers of model instances. When measuring memory be aware that not all the allocation happens at load time for all frameworks, so you need to measure the memory usage while model is under high load (e.g. by using perf_analyzer https://github.com/triton-inference-server/server/blob/master/docs/perf_analyzer.md

**Comment by Jackiexiao** [comment]
> For some frameworks triton is sharing the weights across model 

so which frameworks share the weights across model?

**Comment by Jackiexiao** [comment]
to enable model weight sharing in pytorch backend, change pbtxt setting which mentioned [here](https://github.com/triton-inference-server/pytorch_backend/blob/df900ce3d3c03e7f34ce1e9518c09cc2bad520a5/README.md?plain=1#L167)
