### ISSUE TITLE
"Invalid argument - repository path is not a valid directory" when running local S3 on port 80

### ISSUE THREAD

**Issue by aras7** [triton-inference-server/server#2165]
**Description**
I'm trying to pull models from a local S3 using `--model-repository=s3://cool.url.com:80/bucket_name/path/to/repo` as described [here](https://docs.nvidia.com/deeplearning/triton-inference-server/master-user-guide/docs/model_repository.html#s3) but it gives the following error:
```
error: creating server: Invalid argument - repository path is not a valid directory
```

Changing the port from 80 to anything else gives access error, which makes sense
```
error: creating server: Internal - Could not get MetaData for bucket with name <bucket_name>
```

Removing 80 and using `--model-repository=s3://cool.url.com/bucket_name/path/to/repo` makes Triton think that the url is the bucket name:
```
error: creating server: Internal - Could not get MetaData for bucket with name cool.url.com
```

**Triton Information**
What version of Triton are you using?
nvcr.io/nvidia/tritonserver:20.08-py3

Are you using the Triton container or did you build it yourself?
I pulled the image

**To Reproduce**
Steps to reproduce the behavior.
Get a local S3 running on port 80
Add your models
pull them from there following [here](https://docs.nvidia.com/deeplearning/triton-inference-server/master-user-guide/docs/model_repository.html#s3) 

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
No relevant

**Expected behavior**
I expect models to be loaded into Triton.

**Comment by CoderHam** [comment]
Thank you for bringing this to our attention. Could you repeat these steps to confirm it is not a configuration issue on your end?
1. Use S3 command line to confirm the credentials are set correctly.
2. Confirm that the path is a folder and not a file. 
3. Use Tritonserver 20.10/20.09
4. Ensure you are following the S3 bucket name conventions.

**Comment by aras7** [comment]
Sure! 
(1)(2)(4) are good, I'm going to try `20.10` and will let you know the results.

**Comment by aras7** [comment]
Pretty much same results when using 20.10:

* `--model-repository=s3://cool.url.com:80/bucket_name/...`
    `error: creating server: Internal - Could not get MetaData for bucket with name cool.url.com:80`
     This case throws `error: creating server: Invalid argument - repository path is not a valid directory` on 20.08

* `--model-repository=s3://cool.url.com/bucket_name/...`
     `error: creating server: Internal - Could not get MetaData for bucket with name cool.url.com`

**Comment by aras7** [comment]
Is there any update? I wonder if someone is looking at this?

**Comment by CoderHam** [comment]
Hi @aras7 I was occupied by some release work. Please refer to https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html for bucket naming conventions. '_' is not a valid character for S3 buckets.

In specific refer to the section that states that you should not use underscores in bucket names. We do not allow the same to conform with the S3 bucket guidelines.

**Comment by aras7** [comment]
Sorry, I did not explain correctly.

The bucket name I'm using is valid, I can't share it for privacy policies but it only contains lowercase letters and numbers. I used `bucket_name` as an example.

Same for the host, `cool.url.com` is just an example.

**Comment by aras7** [comment]
In case this helps to assess the problem: The path doesn't have underscores either, it only has lowercase letters.

**Comment by CoderHam** [comment]
I'll likely look into this next week. Can you share the directory structure at the path S3 path you are using?

**Comment by aras7** [comment]
The directory structure looks like this:
```
andresmodelrepository/
                      subs/
                           config.pbtxt
                           1/
                              model.onnx
```

**Comment by deadeyegoodwin** [comment]
Closing, please reopen if still an issue.
