### ISSUE TITLE
Bypass arguments in Ensemble Models' input and output

### ISSUE THREAD

**Issue by zldrobit** [triton-inference-server/server#2167]
**Is your feature request related to a problem? Please describe.**
For image inference with TensorRT, a postprocessing model cannot retrieve the original image size after preprocesssing (resize and crop).
Object detection needs original image size to recalculate coordinates of bouding boxes of original images in postprocessing.
Take 720p input images for example, an original image size is 1280x720 which is resized and cropped to 640x640 as input in yolov5 models.
The detection is proceeded in 640x640 resolution, and postprocessing maps bounding boxes from 640x640 back to 1280x720 resolution.

**Describe the solution you'd like**
Add a type of input to bypass arguments as-is to output.
Using this type of input, I can set the original image size as an input, and the post processing model can retrieve the original image size after TensorRT inference.

**Describe alternatives you've considered**
Change the exported TensorRT model, and manually add a size argument into the model's input which is bypassed to output directly.
This requires a reexport of TensorRT models which is inconvenient and time costing.

**Additional context**
```
Model

preprocessing :          image,     orig_image_size
                           |              | (bypass)
TensorRT:                image,     orig_image_size
                           |              | (bypass)
postprocessing:          image,     orig_image_size
```

**Comment by deadeyegoodwin** [comment]
You control the inputs and outputs to the pre and post processing, correct? Can't you just add a new output to pre that connects to a new input on post along which you can pass the original size of the image?

**Comment by zldrobit** [comment]
@deadeyegoodwin Thanks for your response.
Your solution is practical, and won't change object detection model.
I misunderstood that the ensemble model must be in sequential order.
