### ISSUE TITLE
HTTP end point doesn't support models with decoupled transaction policy

### ISSUE THREAD

**Issue by KingsleyLiu-NV** [triton-inference-server/server#2168]
**Description**
I am trying with `square` backend and I have built it successfully. The model repository layout is as below:
```bash
.
|-- identity
|   |-- 1
|   |   `-- libtriton_identity.so
|   `-- config.pbtxt
`-- square
    |-- 1
    |   `-- libtriton_square.so
    `-- config.pbtxt
```
The config.pbtxt is as below:
```bash
name: "square"
backend: "square"
max_batch_size: 0
model_transaction_policy {
  decoupled: True
}
input [
  {
    name: "IN"
    data_type: TYPE_INT32
    dims: [ 1 ]
  }
]
output [
  {
    name: "OUT"
    data_type: TYPE_INT32
    dims: [ 1 ]
  }
]
```
I can start the Triton inference server successfully. However, inside the `nvcr.io/nvidia/tritonserver:20.09-py3-clientsdk` container, I could not run the following python script `square_client.py`:
```bash
from tritonclient.utils import *
import tritonclient.grpc as grpcclient
import tritonclient.http as httpclient

import numpy as np

model_name = "square"
shape = [1]

with httpclient.InferenceServerClient("10.19.226.179:8000") as client:
    input0_data = np.random.randint(1,10,*shape).astype(np.int32)
    inputs = [
        httpclient.InferInput("IN", input0_data.shape,
                              np_to_triton_dtype(input0_data.dtype)),
    ]

    inputs[0].set_data_from_numpy(input0_data)

    outputs = [
        httpclient.InferRequestedOutput("OUT"),
    ]

    response = client.infer(model_name,
                            inputs,
                            request_id=str(1),
                            outputs=outputs)

    result = response.get_response()
    print("IN: {}".format(
        input0_data))
    print("OUT: {}".format(response.as_numpy("OUT")))
```
The error memssage is as below:
```bash
root@77834f5ab630:/client/examples# python3 square_client.py
Traceback (most recent call last):
  File "square_client.py", line 26, in <module>
    outputs=outputs)
  File "/usr/local/lib/python3.6/dist-packages/tritonclient/http/__init__.py", line 1089, in infer
    _raise_if_error(response)
  File "/usr/local/lib/python3.6/dist-packages/tritonclient/http/__init__.py", line 63, in _raise_if_error
    raise error
tritonclient.utils.InferenceServerException: HTTP end point doesn't support models with decoupled transaction policy
```
Could you please give an python client inference example which utilizes `libtriton_square.so` model?

**Triton Information**
What version of Triton are you using?
2.3
Are you using the Triton container or did you build it yourself?
Triton container

**To Reproduce**
Steps to reproduce the behavior.
As above

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
As above

**Expected behavior**
We should be able to run `python3 square_client.py`  inside the `nvcr.io/nvidia/tritonserver:20.09-py3-clientsdk` container.

**Comment by deadeyegoodwin** [comment]
The "decoupled API" allows you to send multiple (or zero) responses for a single request. Unfortunately we don't yet have much documentation on using this API outside of what is shown in tritonbackend.h and in the square and repeat examples. The HTTP protocol as used by Triton supports a single response for each request and so is not suitable for handling zero or multiple responses per request. The GRPC protocol allows multiple responses via the streaming interface. If you look in qa/L0_decoupled you will find some test examples.

**Comment by ronaldpanape** [comment]
has this functionality change to where the HTTP endpoint can be used?

**Comment by hillarysanders** [comment]
@deadeyegoodwin Do you know how to be able to use the decoupled transaction policy w/ HTTP when you are only sending one response per request?

I'm trying to enable client-side batching with a python backend, and to do that in a smart way, I need to use decoupled mode to prioritize processing smaller requests, and to make sure I'm always using a good batch size. However I'm just getting stuck on:
```
{"error":"HTTP end point doesn't support models with decoupled transaction policy"}
``` 
Errors. However it seems there is a way to get around it? e.g. the VLLM backend is based on the python backend, and it uses decoupled mode while also allowing requests via HTTP *and* GRPC.

**Comment by adityarap** [comment]
I tried payload with http:///v2/models//infer endpoint , I'm unable to get the streaming responses for the triton_model_repo with decoupled  mode enabled on HTTP.
Getting error as : {"error":"HTTP end point doesn't support models with decoupled transaction policy"}

But the same HTTP is generating stream response for generate_stream endpoint and not for infer.

Ex : curl -X POST localhost:8000/v2/models/ensemble/generate_stream -d '{"text_input": "ceo of nvidia", "max_tokens":250, "temperature":0.00001, "top_p":0.95, "top_k":1, "repetition_penalty":1.2, "stream":true, "end_id":128009, "random_seed":1}'
o/p with stream:
data: {"model_name":"ensemble","model_version":"1","sequence_end":false,"sequence_id":0,"sequence_start":false,"text_output":" deep"}
data: {"model_name":"ensemble","model_version":"1","sequence_end":false,"sequence_id":0,"sequence_start":false,"text_output":" learning"}

Ex : curl -X POST localhost:8000/v2/models/ensemble/infer -d '{
"id": "0",
"inputs": [
{"name": "text_input",
"shape": [1,1],
"datatype": "BYTES"
"data": ["What is LLM"]
},
{
"name": "max_ tokens",
"datatype": "INT32",
"shape": [1,1],
"data": [256]
}
]
}'
Error : {"error":"HTTP end point doesn't support models with decoupled transaction policy"}

I.m unable to find out any documentation that talks about this.If you could help that would be great. Thanks
