### ISSUE TITLE
Error when build TRTIS Docker Image

### ISSUE THREAD

**Issue by le8888e** [triton-inference-server/server#2186]
Hi, when I tried to build TRTIS docker image by:

cd tensorrt-inference-server && git checkout r19.05
docker build -t tensorrtserver_build --target trtserver_build .

There is error:
ERROR: Analysis of target '//src/custom/identity:libidentity.so' failed; build aborted: error loading package 'src/core': Encountered error while reading extension file 'protobuf.bzl': no such package '@com_google_protobuf//': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/protocolbuffers/protobuf/archive/v3.6.1.2.tar.gz, https://github.com/protocolbuffers/protobuf/archive/v3.6.1.2.tar.gz] to /root/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/external/com_google_protobuf/v3.6.1.2.tar.gz: Tried to reconnect at offset 2,978,083 but server didn't support it
INFO: Elapsed time: 62.160s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (19 packages loaded, 160 targets configured)
FAILED: Build did NOT complete successfully (19 packages loaded, 160 targets configured)

Any help will be appreciated.

Thank you!

**Comment by deadeyegoodwin** [comment]
19.05 is a very old version of Triton. Can you use a more up-to-date version. It looks like it failed do to an error downloading google protobuf package. It could be a transient error. Did you try more than once?
