### ISSUE TITLE
Could you provide a tritonclient in Java?

### ISSUE THREAD

**Issue by dongrixinyu** [triton-inference-server/server#2187]
**Describe the solution you'd like**
Could you provide a tritonclient in Java?
That would attract more people to this tool.
Thank you.

**Comment by deadeyegoodwin** [comment]
We have no plans to create a java client but we agree it would be a nice addition to triton. It would be a great contribution to the contrib area (https://github.com/triton-inference-server/contrib) to have a java client that followed the existing C++ client API with appropriate java conventions.
