### ISSUE TITLE
provided PTX was compiled with an unsupported toolchain?

### ISSUE THREAD

**Issue by whillas** [triton-inference-server/server#2193]
**Description**
Trying to load a model in 20.10 that was previously loading in 20.09 in and now I'm getting this error:

> E1029 03:56:30.380349 1 model_repository_manager.cc:899] failed to load 'some_model' version 6: Internal: unable to auto-complete model configuration for 'some_model', failed to load model: CUDA runtime implicit initialization on GPU:0 failed. Status: the provided PTX was compiled with an unsupported toolchain.

**Triton Information**
Official container image 20.10

**To Reproduce**
Tensorflow 1.15 Efficientnet-b5 savemodel format 

**Expected behavior**

The model should load? 

What does this mean and how to fix it?

**Comment by deadeyegoodwin** [comment]
20.10 release is based on CUDA 11.1 https://docs.nvidia.com/deeplearning/triton-inference-server/release-notes/rel_20-10.html#rel_20-10
What nvidia driver version are you using? See Driver Requirements section of that link.

**Comment by whillas** [comment]
yeah, updated the nvidia drivers to 455.23 (beta) and it works now. 
Cheers!
