### ISSUE TITLE
Python API references disappeared from documentation !  

### ISSUE THREAD

**Issue by Fizmath** [triton-inference-server/server#2194]
Hello

Alright  !  where did the  function references  from this page go: 

https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/python_api.html

!?

**Comment by deadeyegoodwin** [comment]
It looks like the API generation has been broken for a couple of releases. But note that starting in 20.10 Triton documentation is now directly in github and no longer generates API docs. See https://github.com/triton-inference-server/server/blob/master/docs/client_libraries.md#client-library-apis for pointers into the documented code headers and modules that describe the APIs.
