### ISSUE TITLE
Debian package, when?

### ISSUE THREAD

**Issue by zned45** [triton-inference-server/server#2209]
Hi,
Great project.
But I find it really awkward that I can't install the C++ libraries. I use Triton extensively with Python, but this is a nightmare to use with C++. Is there any tutorial on how to set a C++ project?

Regards.

**Comment by deadeyegoodwin** [comment]
Can you be more specific about why it is hard to use? C++ library is an *.so file and a header. There are many ways to install it as described here: https://github.com/triton-inference-server/server/blob/master/docs/client_libraries.md#getting-the-client-libraries
If you are asking specifically for a debian package that installs the client library we don't have any plans for that currently.
