### ISSUE TITLE
Support for AWS Inferentia?

### ISSUE THREAD

**Issue by thecooltechguy** [triton-inference-server/server#2222]
**Is your feature request related to a problem? Please describe.**
Will nvidia-triton server be able to run on AWS Inferentia EC2 instances?

**Describe the solution you'd like**
Support for nvidia-triton server to be able to use AWS Inferentia chips, in addition to the existing support for NVIDIA GPUs.

**Describe alternatives you've considered**
An alternative would possibly be TF Serving on Inferentia (using the AWS Neuron SDK) instead of triton, but this approach only allows for TF models, whereas NVIDIA triton server is much more flexible in the frameworks it supports.

**Comment by dzier** [comment]
This is on the Triton road map, however, we do not have a definitive ETA on when it will be released.

**Comment by tomas-gajarsky** [comment]
"Starting from 21.11 release, Triton supports [AWS Inferentia](https://aws.amazon.com/machine-learning/inferentia/) and the [Neuron Runtime](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-intro/get-started.html)." - from [a guideline in the python_backend repo](https://github.com/triton-inference-server/python_backend/tree/main/inferentia).

[AWS Inferentia](https://aws.amazon.com/machine-learning/inferentia/) is listed as one of the backends on [AWS Machine Learning Blog ](https://aws.amazon.com/blogs/machine-learning/achieve-hyperscale-performance-for-model-serving-using-nvidia-triton-inference-server-on-amazon-sagemaker/) as well.
