### ISSUE TITLE
Failed to load Tensorflow models

### ISSUE THREAD

**Issue by liyinhgqw** [triton-inference-server/server#2223]
**Description**
Triton failed to load tensorflow models with the following error log:
```
I1104 12:45:39.614393 1858 model_repository_manager.cc:579] AsyncLoad() 'simple_string'
I1104 12:45:39.614412 1858 model_repository_manager.cc:714] TriggerNextAction() 'simple_string' version 1: 1
I1104 12:45:39.614419 1858 model_repository_manager.cc:752] Load() 'simple_string' version 1
I1104 12:45:39.614425 1858 model_repository_manager.cc:771] loading: simple_string:1
I1104 12:45:39.614605 1858 model_repository_manager.cc:579] AsyncLoad() 'simple'
I1104 12:45:39.614618 1858 model_repository_manager.cc:714] TriggerNextAction() 'simple' version 1: 1
I1104 12:45:39.614624 1858 model_repository_manager.cc:752] Load() 'simple' version 1
I1104 12:45:39.614601 1858 model_repository_manager.cc:824] CreateInferenceBackend() 'simple_string' version 1
I1104 12:45:39.614630 1858 model_repository_manager.cc:771] loading: simple:1
E1104 12:45:39.614660 1858 model_repository_manager.cc:950] failed to load 'simple_string' version 1: Invalid argument: unknown platform 'tensorflow_graphdef'
I1104 12:45:39.614669 1858 model_repository_manager.cc:714] TriggerNextAction() 'simple_string' version 1: 0
I1104 12:45:39.614679 1858 model_repository_manager.cc:729] no next action, trigger OnComplete()
I1104 12:45:39.614711 1858 model_repository_manager.cc:579] AsyncLoad() 'inception_graphdef'
I1104 12:45:39.614725 1858 model_repository_manager.cc:714] TriggerNextAction() 'inception_graphdef' version 1: 1
I1104 12:45:39.614731 1858 model_repository_manager.cc:752] Load() 'inception_graphdef' version 1
I1104 12:45:39.614737 1858 model_repository_manager.cc:771] loading: inception_graphdef:1
I1104 12:45:39.614702 1858 model_repository_manager.cc:824] CreateInferenceBackend() 'simple' version 1
E1104 12:45:39.614784 1858 model_repository_manager.cc:950] failed to load 'simple' version 1: Invalid argument: unknown platform 'tensorflow_graphdef'
I1104 12:45:39.614792 1858 model_repository_manager.cc:714] TriggerNextAction() 'simple' version 1: 0
I1104 12:45:39.614801 1858 model_repository_manager.cc:729] no next action, trigger OnComplete()
I1104 12:45:39.614814 1858 model_repository_manager.cc:824] CreateInferenceBackend() 'inception_graphdef' version 1
E1104 12:45:39.614840 1858 model_repository_manager.cc:950] failed to load 'inception_graphdef' version 1: Invalid argument: unknown platform 'tensorflow_graphdef'
I1104 12:45:39.614847 1858 model_repository_manager.cc:714] TriggerNextAction() 'inception_graphdef' version 1: 0
I1104 12:45:39.614858 1858 model_repository_manager.cc:729] no next action, trigger OnComplete()
I1104 12:45:39.614899 1858 server.cc:141]
+---------+--------+------+
| Backend | Config | Path |
+---------+--------+------+
+---------+--------+------+

I1104 12:45:39.614910 1858 model_repository_manager.cc:452] BackendStates()
I1104 12:45:39.614937 1858 server.cc:184]
+--------------------+---------+-----------------------------------------------------------------------+
| Model              | Version | Status                                                                |
+--------------------+---------+-----------------------------------------------------------------------+
| inception_graphdef | 1       | UNAVAILABLE: Invalid argument: unknown platform 'tensorflow_graphdef' |
| simple             | 1       | UNAVAILABLE: Invalid argument: unknown platform 'tensorflow_graphdef' |
| simple_string      | 1       | UNAVAILABLE: Invalid argument: unknown platform 'tensorflow_graphdef' |
+--------------------+---------+-----------------------------------------------------------------------+

I1104 12:45:39.615011 1858 tritonserver.cc:1620]
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+
| Option                           | Value                                                                                                                                              |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+
| server_id                        | triton                                                                                                                                             |
| server_version                   | 2.5.0dev                                                                                                                                           |
| server_extensions                | classification sequence model_repository schedule_policy model_configuration system_shared_memory cuda_shared_memory binary_tensor_data statistics |
| model_repository_path[0]         | model_repository                                                                                                                                   |
| model_control_mode               | MODE_NONE                                                                                                                                          |
| strict_model_config              | 1                                                                                                                                                  |
| pinned_memory_pool_byte_size     | 268435456                                                                                                                                          |
| cuda_memory_pool_byte_size{0}    | 67108864                                                                                                                                           |
| cuda_memory_pool_byte_size{1}    | 67108864                                                                                                                                           |
| min_supported_compute_capability | 6.0                                                                                                                                                |
| strict_readiness                 | 1                                                                                                                                                  |
| exit_timeout                     | 30                                                                                                                                                 |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+

I1104 12:45:39.615044 1858 server.cc:280] Waiting for in-flight requests to complete.
I1104 12:45:39.615050 1858 model_repository_manager.cc:579] AsyncLoad() 'simple_string'
I1104 12:45:39.615056 1858 model_repository_manager.cc:714] TriggerNextAction() 'simple_string' version 1: 2
I1104 12:45:39.615061 1858 model_repository_manager.cc:791] Unload() 'simple_string' version 1
I1104 12:45:39.615069 1858 model_repository_manager.cc:579] AsyncLoad() 'inception_graphdef'
I1104 12:45:39.615074 1858 model_repository_manager.cc:714] TriggerNextAction() 'inception_graphdef' version 1: 2
I1104 12:45:39.615080 1858 model_repository_manager.cc:791] Unload() 'inception_graphdef' version 1
I1104 12:45:39.615088 1858 model_repository_manager.cc:579] AsyncLoad() 'simple'
I1104 12:45:39.615094 1858 model_repository_manager.cc:714] TriggerNextAction() 'simple' version 1: 2
I1104 12:45:39.615099 1858 model_repository_manager.cc:791] Unload() 'simple' version 1
I1104 12:45:39.615108 1858 model_repository_manager.cc:416] LiveBackendStates()
I1104 12:45:39.615113 1858 server.cc:295] Timeout 30: Found 0 live models and 0 in-flight non-inference requests
error: creating server: Internal - failed to load all models
```

**Triton Information**
What version of Triton are you using?
master

Are you using the Triton container or did you build it yourself?
build by myself with tensorflow backend.

**To Reproduce**
Steps to reproduce the behavior.
Build script:
` ./build.py --build-dir /workspace/out --install-dir /workspace/out/install --enable-logging --enable-stats --enable-metrics --enable-gpu-metrics --enable-tracing --enable-gpu --filesystem=gcs  --endpoint=http --endpoint=grpc --backend=tensorrt --backend=tensorflow2 --upstream-container-version=20.08 --repo-tag=core:main --repo-tag=backend:main --repo-tag=common:main`

Run:
`LD_LIBRARY_PATH=out/install/backends/tensorflow2 ./out/install/bin/tritonserver --model-repository model_repository --log-verbose 100 --log-info true --backend-directory out/install/backends --backend-config tensorflow,version=2`

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
Models coming with Triton

**Expected behavior**
Loading from tensorflow seems to be removed in this change:
https://github.com/triton-inference-server/server/commit/ec00345e07cbd359405d6f71ef06dc2f405cc482#diff-48b036da277bb4e8eb2acb8ecc63275f9a60ea76fd9effa7443b41a86f94420d

How can I load Tensorflow model (graphdef, savedmodel)? Did I miss any flags when I ran it?

**Comment by deadeyegoodwin** [comment]
The log seems to show that Triton cannot find the tensorflow2 backend. How did you install triton, please share the entire directory tree (in our container release this is the entire contents of /opt/tritonserver).

**Comment by liyinhgqw** [comment]
@deadeyegoodwin It was built from source (master).

The install directory tree is:
.
├── backends
│   └── tensorflow2
│       ├── libtensorflow_cc.so -> libtensorflow_cc.so.2
│       ├── libtensorflow_cc.so.2 -> libtensorflow_triton.so.2
│       ├── libtensorflow_framework.so -> libtensorflow_framework.so.2
│       ├── libtensorflow_framework.so.2 -> libtensorflow_triton.so.2
│       ├── libtensorflow_triton.so -> libtensorflow_triton.so.2
│       ├── libtensorflow_triton.so.2
│       ├── libtriton_tensorflow2.so
│       └── LICENSE.tensorflow
├── bin
│   ├── memory_alloc
│   ├── simple
│   └── tritonserver
├── include
│   └── triton
│       ├── backend
│       │   ├── backend_common.h
│       │   ├── backend_input_collector.h
│       │   ├── backend_memory.h
│       │   ├── backend_model.h
│       │   ├── backend_model_instance.h
│       │   └── backend_output_responder.h
│       ├── common
│       │   ├── table_printer.h
│       │   └── triton_json.h
│       └── core
│           ├── tritonbackend.h
│           └── tritonserver.h
└── lib
    ├── cmake
    │   ├── TritonBackend
    │   │   ├── TritonBackendConfig.cmake
    │   │   ├── TritonBackendTargets.cmake
    │   │   └── TritonBackendTargets-release.cmake
    │   ├── TritonCommon
    │   │   ├── TritonCommonConfig.cmake
    │   │   ├── TritonCommonTargets.cmake
    │   │   └── TritonCommonTargets-release.cmake
    │   └── TritonCore
    │       ├── TritonCoreConfig.cmake
    │       ├── TritonCoreTargets.cmake
    │       └── TritonCoreTargets-release.cmake
    ├── libtritonbackendutils.a
    ├── libtritonserver.so
    ├── libtritonserver_stub.so
    └── libtritontableprinter.a

**Comment by deadeyegoodwin** [comment]
You don't say where that tree it rooted. By default tritonserver will look in /opt/tritonserver/backends for its backends. You can use the --backend-directory flag to override. https://github.com/triton-inference-server/backend/blob/main/README.md#backend-shared-library

**Comment by liyinhgqw** [comment]
The tree is rooted /workspace/out/install which is the install dir. The following is the scripts I built and ran:

./build.py --build-dir /workspace/out --install-dir **/workspace/out/install** --enable-logging --enable-stats --enable-metrics --enable-gpu-metrics --enable-tracing --enable-gpu --filesystem=gcs --endpoint=http --endpoint=grpc --backend=tensorrt --backend=tensorflow2 --upstream-container-version=20.08 --repo-tag=core:main --repo-tag=backend:main --repo-tag=common:main

Run:
LD_LIBRARY_PATH=out/install/backends/tensorflow2 ./out/install/bin/tritonserver --model-repository model_repository --log-verbose 100 --log-info true --backend-directory out/install/backends --backend-config tensorflow,version=2

**Comment by deadeyegoodwin** [comment]
You shouldn't need LD_LIBRARY_PATH. You need the abspath for --backend-directory.

**Comment by liyinhgqw** [comment]
Thanks. I pulled the latest master and resolved this.
