### ISSUE TITLE
The README file in this repo has a bad link - [404:NotFound]

### ISSUE THREAD

**Issue by MrCull** [triton-inference-server/server#2224]
The README file in this repo has a bad link - [404:NotFound]

Status code [404:NotFound] - Link: https://github.com/triton-inference-server/server/blob/master/deploy/single_server/README.rst

I think it the file extension and should be:
https://github.com/triton-inference-server/server/blob/master/deploy/single_server/README.md

This was found by an new experimental hobby project that I have just created: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
If this has been in any way helpful then please consider giving the above Repo a Star.

**Comment by deadeyegoodwin** [comment]
Thanks for finding that. Fixed on master.
