### ISSUE TITLE
Mismatch between config.pbtxt and reported model config json

### ISSUE THREAD

**Issue by whillas** [triton-inference-server/server#2226]
So i have a SSD model which takes variable size image dims as input but when testing the model i was getting 
```
unexpected shape for input 'inputs' for model 'ssd'. Expected [-1,300,300,3], got [1,456,456,3]
```
I checked `curl localhost:8000/v2/models/ssd/config` and got 
```json
{
  "name": "ssd",
  "platform": "tensorflow_savedmodel",
  "backend": "tensorflow",
  "version_policy": {
    "latest": {
      "num_versions": 1
    }
  },
  "max_batch_size": 1,
  "input": [
    {
      "name": "inputs",
      "data_type": "TYPE_UINT8",
      "format": "FORMAT_NONE",
      "dims": [
        -1,
        -1,
        3
      ],
      "is_shape_tensor": false,
      "allow_ragged_batch": false
    }
  ],
  "output": [
    {
      "name": "detection_scores",
      "data_type": "TYPE_FP32",
      "dims": [
        100
      ],
      "label_filename": "",
      "is_shape_tensor": false
    },
    {
      "name": "detection_boxes",
      "data_type": "TYPE_FP32",
      "dims": [
        100,
        4
      ],
      "label_filename": "",
      "is_shape_tensor": false
    },
    {
      "name": "num_detections",
      "data_type": "TYPE_FP32",
      "dims": [
        1
      ],
      "reshape": {
        "shape": []
      },
      "label_filename": "",
      "is_shape_tensor": false
    },
    {
      "name": "detection_classes",
      "data_type": "TYPE_FP32",
      "dims": [
        100
      ],
      "label_filename": "",
      "is_shape_tensor": false
    }
  ],
  "batch_input": [],
  "batch_output": [],
  "optimization": {
    "priority": "PRIORITY_DEFAULT",
    "input_pinned_memory": {
      "enable": true
    },
    "output_pinned_memory": {
      "enable": true
    }
  },
  "instance_group": [
    {
      "name": "ssd_h2o_instore",
      "kind": "KIND_GPU",
      "count": 1,
      "gpus": [
        0
      ],
      "profile": []
    }
  ],
  "default_model_filename": "model.savedmodel",
  "cc_model_filenames": {},
  "metric_tags": {},
  "parameters": {},
  "model_warmup": []
}
```
So i was confused?! Then i checked the config.pbtxt which was 
```
name: "ssd"
platform: "tensorflow_savedmodel"
version_policy {
  latest {
    num_versions: 1
  }
}
max_batch_size: 1
input {
  name: "inputs"
  data_type: TYPE_UINT8
  dims: 300
  dims: 300
  dims: 3
}
output {
  name: "num_detections"
  data_type: TYPE_FP32
  dims: 1
  reshape {
  }
}
output {
  name: "detection_classes"
  data_type: TYPE_FP32
  dims: 100
}
output {
  name: "detection_multiclass_scores"
  data_type: TYPE_FP32
  dims: 100
  dims: 2
}
output {
  name: "raw_detection_scores"
  data_type: TYPE_FP32
  dims: -1
  dims: 2
}
output {
  name: "detection_scores"
  data_type: TYPE_FP32
  dims: 100
}
output {
  name: "raw_detection_boxes"
  data_type: TYPE_FP32
  dims: -1
  dims: 4
}
output {
  name: "detection_boxes"
  data_type: TYPE_FP32
  dims: 100
  dims: 4
}
instance_group {
  name: "ssd"
  count: 1
  gpus: 0
  kind: KIND_GPU
}
default_model_filename: "model.savedmodel"
```
I'm relying on the results of `curl localhost:8000/v2/models/ssd/config` to reflect what is actually being served. If this is not how the model is being severed then _how_ do i find out?

**Triton Information**
Offical Triton 20.10 container

**To Reproduce**
`config.pbtxt` that is different from the models exported output

**Expected behavior**
The results of `curl localhost:8000/v2/models/ssd/config` should match what is actually being served by Triton

**Comment by deadeyegoodwin** [comment]
So you are asking for the config of model "ssd" and triton is giving back the config for "ssd_h20_instore". That is very strange. Are those the only 2 models in your model repository. If you use the metadata endpoint (v2/models/ssd) so you see similar mis-behavior?

**Comment by whillas** [comment]
opps, sorry, they should be the same model

**Comment by whillas** [comment]
But the problem is still valid infact that is what i mean

**Comment by deadeyegoodwin** [comment]
What do you see with the metadata endpoint? Can you share your model repository?

**Comment by whillas** [comment]
yes, i posted the output from the metadata endpoint above.
here is the model https://console.cloud.google.com/storage/browser/imagr-public-bucket

**Comment by deadeyegoodwin** [comment]
You posted the config endpoint output.
The metadata endpoint in this case is: v2/models/ssd

**Comment by deadeyegoodwin** [comment]
The ssd model that you posted in that public bucket doesn't even load with Triton 20.10:

E1112 21:20:33.608019 64 model_repository_manager.cc:899] failed to load 'ssd' version 1: Invalid argument: unexpected inference output 'detection_multiclass_scores', allowed outputs are: detection_boxes, detection_classes, detection_scores, num_detections

Can you fix that so I am able to repro the failure you are seeing. Please reopen when the repro is ready.
