### ISSUE TITLE
Config.pbtx for Efficientdet-D0

### ISSUE THREAD

**Issue by AkashDharani** [triton-inference-server/server#2228]
Description
I am deploying detection model Efficientdet-D0 via tensorflow savedmodel, and facing some issues while deploying the model using `nvcr.io/nvidia/tritonserver:20.10-py3`. It is about the dimension of output tensor, it is [1, -1, 7] and triton-server expects -1 in first dimension, I also tried to make it [-1, 7] as well, but it is still not working.

My config.pbtxt file

```
name: "EfficientDet"
platform: "tensorflow_savedmodel"
max_batch_size: 1
input [
   {
      name: "image_arrays:0"
      data_type: TYPE_UINT8
      format: FORMAT_NHWC
      dims: [-1, -1, 3]
   }
]
output [
   {
      name: "detections:0"
      data_type: TYPE_FP32
      dims: [1, -1, 7 ]
   }
]
```

I am using docker container nvcr.io/nvidia/tritonserver:20.10-py3

You can get saved_model from here : [https://tfhub.dev/tensorflow/efficientdet/d0/1]

I expected config.pbtxt to work with output tensor having dimensions of [1, 7].

**Comment by deadeyegoodwin** [comment]
Please read this section of the documentation carefully: https://github.com/triton-inference-server/server/blob/master/docs/model_configuration.md#inputs-and-outputs

Setting max_batch_size > 0 has a specific requirements on your model inputs and outputs. You should also consider not providing a config.pbtxt and using --strict-model-config=false and see what Triton generates for you: https://github.com/triton-inference-server/server/blob/master/docs/model_configuration.md#auto-generated-model-configuration

**Comment by whillas** [comment]
yeah, that is not going to work. See https://github.com/triton-inference-server/server/issues/2192

**Comment by AkashDharani** [comment]
"""
 [[efficientnet-b0/stem/tpu_batch_normalization/FusedBatchNormV3]]
2020-11-06 09:09:24.574236: E tensorflow/core/common_runtime/executor.cc:648] Executor failed to create kernel. Invalid argument: NodeDef mentions attr 'exponential_avg_factor' not in Op<name=FusedBatchNormV3; signature=x:T, scale:U, offset:U, mean:U, variance:U -> y:T, batch_mean:U, batch_variance:U, reserve_space_1:U, reserve_space_2:U, reserve_space_3:U; attr=T:type,allowed=[DT_HALF, DT_BFLOAT16, DT_FLOAT]; attr=U:type,allowed=[DT_FLOAT]; attr=epsilon:float,default=0.0001; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]; attr=is_training:bool,default=true>; NodeDef: {{node efficientnet-b0/stem/tpu_batch_normalization/FusedBatchNormV3}}. (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	 [[efficientnet-b0/stem/tpu_batch_normalization/FusedBatchNormV3]]
"""

**Comment by tanmayv25** [comment]
@AkashDharani It looks like the format of saved mode is TF2.0 saved model. Are you invoking the server with `--backend-config=tensorflow,version=2` ?

**Comment by AkashDharani** [comment]
Yeah, it is resolved now, Thanks

**Comment by tanmayv25** [comment]
FYI: Link to the tensorflow backend:  https://github.com/triton-inference-server/tensorflow_backend#command-line-options
