### ISSUE TITLE
sequence_batch_scheduler.cc:399 The previous sequence did not end before this sequence start

### ISSUE THREAD

**Issue by Slyne** [triton-inference-server/server#2229]
**Description**
Trying the perf_analyzer：
perf_analyzer -u "localhost:8001" --streaming --concurrency-range 500 -m kaldi_online -f perf.csv -i gRPC --input-data output.json
I got lots of warnnings like 'The previous sequence did not end before this sequence start'.

1. I want to know how to interpret this warnning 'The previous sequence did not end before this sequence start'. And how should I edit the input-data in order to test the streaming sequence model properly.
2. Is the latency for the whole sequence or just the last chunk ? 

The model kaldi_online can be found: https://github.com/NVIDIA/DeepLearningExamples/tree/master/Kaldi/SpeechRecognition
The output.json looks like:
{
  "data" :
    [
      [
        {
          "WAV_DATA" : [1.0, -1.560, .......],
          "WAV_DIM": [8160]
        },
        {
          "WAV_DATA" : [1.0, -1.560, .......],
          "WAV_DIM": [8160]
        },
        {
           "WAV_DATA" : [1.0, -1.560, .......],
          "WAV_DIM": [8160]
        },
        {
           "WAV_DATA" : [1.0, -1.560, .......],
          "WAV_DIM": [8160]
        }
      ],
     [....],
     [...],
]
}

**Triton Information**
20.10
nvcr.io/nvidia/tritonserver:20.10-py3-clientsdk

Are you using the Triton container or did you build it yourself?
Triton container

**To Reproduce**
Refer to the previous info.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
Model details can be found in https://github.com/NVIDIA/DeepLearningExamples/tree/master/Kaldi/SpeechRecognition.

**Expected behavior**
Just wanna know how to interpret the output of perf client on sequence data.

**Comment by tanmayv25** [comment]
Thanks for sharing your observation. 
The output.json looks good to me. perf_analyzer should ensure the correct sequence flags are provided while sending requests to the server hence you must not see the warning  'The previous sequence did not end before this sequence start'
1. Do you see the warning message even with a fresh run of the server?
2. The kaldi backend in DeepLearningExample, returns a response for each request in the stream. The output is populated with text only for the response of the last request, others are empty responses. Currently, perf_analyzer reports latency between each request and its corresponding response.  If you want more meaningful numbers for this use case, please use `kaldi_asr_parallel_client`  in https://github.com/NVIDIA/DeepLearningExamples/tree/master/Kaldi/SpeechRecognition/kaldi-asr-client.

`perf_analyzer` is a generic tool to obtain the triton server performance and might not cater to the specific needs. We are in the process of making it more useful for these needs.

Additionally, have a look at Triton's new Backend API that allows for decoupled requests and responses which is useful for kaldi. https://github.com/triton-inference-server/repeat_backend.

**Comment by Slyne** [comment]
Thank you!
1. Yes, I see the warning message with a fresh run.
2. I change  the kaldi backend a little bit so that it can return response for every request.  The kaldi_asr_parallel_client works fine for me . However it can only work with triton19.12 and doesn't seem to work with triton 20.09+.  That's the reason why I want to try a newer version client.

I'll take a look at the repeat_backend. 
Another thing I wanna ask is if the python version client（simple_grpc_sequence_stream_infer_client.py） can be used to test the latency ? I've tried modified this example and I find the RTF (real time factor) for audios is similar to kaldi_asr_parallel_client but the latency is greatly increased. Most of the responses seem to arrive at the client all at once.

**Comment by deadeyegoodwin** [comment]
The simple clients are not designed for performance measurement. And Python won't necessarily give you the highest perf in any context. But they can serve as a basis for you to create your own client.
Closing for now. Reopen if you have additional information of questions.
