### ISSUE TITLE
Use TRTIS optimized model instead of running optimization again on load

### ISSUE THREAD

**Issue by YanDavKMS** [triton-inference-server/server#2234]
Hey,

I'm running TRTIS with my model using auto mixed precision optimization.

```
optimization {
	execution_accelerators {
		gpu_execution_accelerator : [
			{
				name : "auto_mixed_precision"
			}
		]
	}
}
```

How can I get/use the already optimized model instead of optimizing the original model each time the TRTIS is loading?
I can't find the optimized model location.

Thanks,
Yaniv.

**Comment by deadeyegoodwin** [comment]
The optimization is applied in-memory by the TF framework. There is not any way to extract that model (at least not any way available through Triton).
