### ISSUE TITLE
Can we put image download to server side?

### ISSUE THREAD

**Issue by flyingmrwang** [triton-inference-server/server#2236]
**Is your feature request related to a problem? Please describe.**
Currently how tritonserver works is to accept image binaries. 

**Describe the solution you'd like**
If it is possible to make server accept image url rather than image binaries, and make downloading itself.

**Describe alternatives you've considered**
The reason is for an API service with multi instances of GPU servers, it is efficient to decentralize and allocate image downloading works to GPUs. Any work-around or alternatives?

**Additional context**
Any suggestion or hints would be appreciated.

**Comment by GuanLuo** [comment]
Triton itself doesn't try to interpret the input within the request, it simply passes the input data to the model and let the model process it.

One solution to your problem is to utilize ensemble and custom backend: the custom backend accepts the url as input of byte type, downloads the image and provides the image binary as "model output", and the ensemble connects the custom backend with the actual model that accepts the image binary.

**Comment by flyingmrwang** [comment]
@GuanLuo Thanks for your hints. Is utilization of ensemble compatible with dynamic_batch? And the implementation is python or c++? Will ensemble decrease the performance of whole pipeline? Forgive me for asking too many, since I am really concern about the performance.

**Comment by flyingmrwang** [comment]
@GuanLuo For the ensemble method that you mentioned. I noticed that people are trying to use this to move preprocess to server side. But the related code and example are not exist anymore. (src/custom/image_preprocess/image_preprocess.cc and docs/examples/ensemble_model_repository) Does this means this method is not suggested or stable enough?

**Comment by GuanLuo** [comment]
> Is utilization of ensemble compatible with dynamic_batch?

Yes, as long as the models that consist the ensemble support batching and have dynamic batching configured.

> And the implementation is python or c++? 

Not sure what exactly are you referring to. For the ensemble feature, it is part of Triton so it is implemented in C++. For custom backend, it is the user's choice of implementing it in C++ or Python. For C++, you will need to implement the Triton backend APIs (see [detail](https://github.com/triton-inference-server/backend#how-can-i-develop-my-own-triton-backend)). And for Python, we provide a Python backend that bridges Triton and model in Python, where you provide your model in a Python file with the following [structure](https://github.com/triton-inference-server/python_backend#usage).

> Will ensemble decrease the performance of whole pipeline?

What alternative are you comparing it to? Ensemble itself is providing instruction about connecting one model's output to the input of the other model, the data movement is minimized as the data are maintained by Triton. Of course, there will be neglectable overhead as some level of encapsulation, like constructing the request / response objects, is needed to comply with Triton's inference workflow.

**Comment by GuanLuo** [comment]
See [ensemble example](https://github.com/triton-inference-server/server/blob/master/docs/client_examples.md#ensemble-image-classification-example-application), we reorganized the example because now the image pre-processing task can be done via DALI backend. But feel free to raise issue or to create a PR if you encounter broken links.

**Comment by flyingmrwang** [comment]
@GuanLuo Thanks again for your patient reply. Actually what I want is to build a micro-service like API, which accept url, or at least un-processed image data and return predict result. 

I understand that preprocess for image normalization cost neglectable computation. I just want to make sure this part, or even image downloading, can cooperate well with batch inference. Anyway, instead of worry too much, I will have a try to implement my ensemble.

**Comment by anshulg03** [comment]
@flyingmrwang 
Hey, were you able to implement the server-side download and preprocessing?
