### ISSUE TITLE
cmake build server error r20.10

### ISSUE THREAD

**Issue by pycoco** [triton-inference-server/server#2238]
/usr/include/c++/5/bits/hashtable_policy.h:85:34: error: no match for call to ‘(const std::hash<triton::backend::BackendMemory::AllocationType>) (const triton::backend::BackendMemory::AllocationType&)’
  noexcept(declval<const _Hash&>()(declval<const _Key&>()))>

**Comment by CoderHam** [comment]
Please share the steps you followed to produce the error.

**Comment by pycoco** [comment]
1. git clone from https://github.com/triton-inference-server/server
2. git checkout r20.10
3. delete some lines from build/Cmakelist.txt
`#
# Build google-cloud-cpp
#
ExternalProject_Add(google-cloud-cpp
  PREFIX google-cloud-cpp
  GIT_REPOSITORY "https://github.com/googleapis/google-cloud-cpp.git"
  GIT_TAG "v0.10.0"
  SOURCE_DIR "${CMAKE_CURRENT_BINARY_DIR}/google-cloud-cpp/src/google-cloud-cpp"
  CMAKE_CACHE_ARGS
    -DGOOGLE_CLOUD_CPP_DEPENDENCY_PROVIDER:STRING=package
    -DBUILD_TESTING:BOOL=OFF
    -DCMAKE_PREFIX_PATH:PATH=${GCS_CMAKE_PREFIX_PATH}
    -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=ON
    -DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_CURRENT_BINARY_DIR}/google-cloud-cpp/install
  DEPENDS grpc protobuf crc32c
)

#
# Build AWS sdk for S3 support
#
ExternalProject_Add(aws-sdk-cpp
  PREFIX aws-sdk-cpp
  GIT_REPOSITORY "https://github.com/aws/aws-sdk-cpp.git"
  GIT_TAG "1.7.129"
  SOURCE_DIR "${CMAKE_CURRENT_BINARY_DIR}/aws-sdk-cpp/src/aws-sdk-cpp"
  CMAKE_CACHE_ARGS
    -DBUILD_ONLY:STRING=s3
    -DBUILD_SHARED_LIBS:BOOL=OFF
    -DMINIMIZE_SIZE:BOOL=ON
    -DENABLE_TESTING:BOOL=OFF
    -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=ON
    -DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_CURRENT_BINARY_DIR}/aws-sdk-cpp/install
)

when build server delete:

-Dstorage_client_DIR:PATH=${CMAKE_CURRENT_BINARY_DIR}/google-cloud-cpp/install/lib/cmake/storage_client
-Dgoogle_cloud_cpp_common_DIR:PATH=${CMAKE_CURRENT_BINARY_DIR}/google-cloud-cpp/install/lib/cmake/google_cloud_cpp_common
-DAWSSDK_DIR:PATH=${CMAKE_CURRENT_BINARY_DIR}/aws-sdk-cpp/install/lib/cmake/AWSSDK
    -Daws-cpp-sdk-core_DIR:PATH=${CMAKE_CURRENT_BINARY_DIR}/aws-sdk-cpp/install/lib/cmake/aws-cpp-sdk-core
    -Daws-cpp-sdk-s3_DIR:PATH=${CMAKE_CURRENT_BINARY_DIR}/aws-sdk-cpp/install/lib/cmake/aws-cpp-sdk-s3
    -Daws-c-event-stream_DIR:PATH=${CMAKE_CURRENT_BINARY_DIR}/aws-sdk-cpp/install/lib/aws-c-event-stream/cmake
    -Daws-c-common_DIR:PATH=${CMAKE_CURRENT_BINARY_DIR}/aws-sdk-cpp/install/lib/aws-c-common/cmake
    -Daws-checksums_DIR:PATH=${CMAKE_CURRENT_BINARY_DIR}/aws-sdk-cpp/install/lib/aws-checksums/cmake

`
4. then follow https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/build.html#section-building-the-server-with-cmake
`
$ cd builddir
$ cmake  ../build
`
5. `$ cd builddir
$ make -j16 server`

**Comment by deadeyegoodwin** [comment]
Build process has changed. You should follow the new build description here: https://github.com/triton-inference-server/server/blob/master/docs/build.md

**Comment by pycoco** [comment]
> https://github.com/triton-inference-server/server/blob/master/docs/build.md

when i follow the build document in https://github.com/triton-inference-server/server/blob/master/docs/build.md ,the error is same

**Comment by pycoco** [comment]
> Build process has changed. You should follow the new build description here: https://github.com/triton-inference-server/server/blob/master/docs/build.md

@deadeyegoodwin   i follow the document description in https://github.com/triton-inference-server/server/blob/master/docs/build.md .but the error is same

**Comment by GuanLuo** [comment]
You modified the CMakeLists so it is hard to tell whether the error is introduced by that, you can control the components to be built with using CMake option so please use that to disable GCS and S3 support.

**Comment by littletree123** [comment]
I did not change the CMakeLists.txt, but also have this error!

**Comment by 520jefferson** [comment]
maybe you can change the r20.10 to r20.12
