### ISSUE TITLE
cmake build server error r20.10 or master

### ISSUE THREAD

**Issue by Beam-wi** [triton-inference-server/server#2239]
**Description**
HEAD is now at c1d176528f Merge pull request #20948 from yashykt/v1.25.0-bump
Submodule 'third_party/abseil-cpp' (https://github.com/abseil/abseil-cpp) registered for path 'third_party/abseil-cpp'
Submodule 'third_party/benchmark' (https://github.com/google/benchmark) registered for path 'third_party/benchmark'
Submodule 'third_party/bloaty' (https://github.com/google/bloaty.git) registered for path 'third_party/bloaty'
Submodule 'third_party/boringssl' (https://github.com/google/boringssl.git) registered for path 'third_party/boringssl'
Submodule 'third_party/boringssl-with-bazel' (https://github.com/google/boringssl.git) registered for path 'third_party/boringssl-with-bazel'
Submodule 'third_party/cares/cares' (https://github.com/c-ares/c-ares.git) registered for path 'third_party/cares/cares'
Submodule 'third_party/envoy-api' (https://github.com/envoyproxy/data-plane-api.git) registered for path 'third_party/envoy-api'
Submodule 'third_party/gflags' (https://github.com/gflags/gflags.git) registered for path 'third_party/gflags'
Submodule 'third_party/googleapis' (https://github.com/googleapis/googleapis.git) registered for path 'third_party/googleapis'
Submodule 'third_party/googletest' (https://github.com/google/googletest.git) registered for path 'third_party/googletest'
Submodule 'third_party/protobuf' (https://github.com/google/protobuf.git) registered for path 'third_party/protobuf'
Submodule 'third_party/protoc-gen-validate' (https://github.com/envoyproxy/protoc-gen-validate.git) registered for path 'third_party/protoc-gen-validate'
Submodule 'third_party/udpa' (https://github.com/cncf/udpa.git) registered for path 'third_party/udpa'
Submodule 'third_party/zlib' (https://github.com/madler/zlib) registered for path 'third_party/zlib'
Cloning into '/home/biwi/APP/server/builddir/grpc-repo/src/grpc/third_party/abseil-cpp'...
Cloning into '/home/biwi/APP/server/builddir/grpc-repo/src/grpc/third_party/benchmark'...
Cloning into '/home/biwi/APP/server/builddir/grpc-repo/src/grpc/third_party/bloaty'...
Cloning into '/home/biwi/APP/server/builddir/grpc-repo/src/grpc/third_party/boringssl'...
Cloning into '/home/biwi/APP/server/builddir/grpc-repo/src/grpc/third_party/boringssl-with-bazel'...
Cloning into '/home/biwi/APP/server/builddir/grpc-repo/src/grpc/third_party/cares/cares'...
Cloning into '/home/biwi/APP/server/builddir/grpc-repo/src/grpc/third_party/envoy-api'...
Cloning into '/home/biwi/APP/server/builddir/grpc-repo/src/grpc/third_party/gflags'...
Cloning into '/home/biwi/APP/server/builddir/grpc-repo/src/grpc/third_party/googleapis'...
Cloning into '/home/biwi/APP/server/builddir/grpc-repo/src/grpc/third_party/googletest'...
Cloning into '/home/biwi/APP/server/builddir/grpc-repo/src/grpc/third_party/protobuf'...
Cloning into '/home/biwi/APP/server/builddir/grpc-repo/src/grpc/third_party/protoc-gen-validate'...
Cloning into '/home/biwi/APP/server/builddir/grpc-repo/src/grpc/third_party/udpa'...
Cloning into '/home/biwi/APP/server/builddir/grpc-repo/src/grpc/third_party/zlib'...
Submodule path 'third_party/abseil-cpp': checked out '74d91756c11bc22f9b0108b94da9326f7f9e376f'
Submodule path 'third_party/benchmark': checked out '090faecb454fbd6e6e17a75ef8146acb037118d4'
Submodule path 'third_party/bloaty': checked out '73594cde8c9a52a102c4341c244c833aa61b9c06'
Submodule 'third_party/googletest' (https://github.com/google/googletest.git) registered for path 'third_party/bloaty/third_party/googletest'
Submodule 'third_party/libFuzzer' (https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer) registered for path 'third_party/bloaty/third_party/libFuzzer'
Submodule 'third_party/re2' (https://github.com/google/re2) registered for path 'third_party/bloaty/third_party/re2'
Cloning into '/home/biwi/APP/server/builddir/grpc-repo/src/grpc/third_party/bloaty/third_party/googletest'...
Cloning into '/home/biwi/APP/server/builddir/grpc-repo/src/grpc/third_party/bloaty/third_party/libFuzzer'...
fatal: unable to access 'https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer/': Failed to connect to chromium.googlesource.com port 443: Connection timed out
fatal: clone of 'https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer' into submodule path '/home/biwi/APP/server/builddir/grpc-repo/src/grpc/third_party/bloaty/third_party/libFuzzer' failed
Failed to clone 'third_party/libFuzzer'. Retry scheduled
Cloning into '/home/biwi/APP/server/builddir/grpc-repo/src/grpc/third_party/bloaty/third_party/re2'...
Cloning into '/home/biwi/APP/server/builddir/grpc-repo/src/grpc/third_party/bloaty/third_party/libFuzzer'...
fatal: unable to access 'https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer/': Failed to connect to chromium.googlesource.com port 443: Connection timed out
fatal: clone of 'https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer' into submodule path '/home/biwi/APP/server/builddir/grpc-repo/src/grpc/third_party/bloaty/third_party/libFuzzer' failed
Failed to clone 'third_party/libFuzzer' a second time, aborting
Submodule path 'third_party/boringssl': checked out '7f02881e96e51f1873afcf384d02f782b48967ca'
Submodule path 'third_party/boringssl-with-bazel': checked out '83da28a68f32023fd3b95a8ae94991a07b1f6c62'
Submodule path 'third_party/cares/cares': checked out 'e982924acee7f7313b4baa4ee5ec000c5e373c30'
Submodule path 'third_party/envoy-api': checked out 'c181f78882e54c0e5c63f332562ef6954ee7932f'
Submodule path 'third_party/gflags': checked out '28f50e0fed19872e0fd50dd23ce2ee8cd759338e'
Submodule 'doc' (https://github.com/gflags/gflags.git) registered for path 'third_party/gflags/doc'
Cloning into '/home/biwi/APP/server/builddir/grpc-repo/src/grpc/third_party/gflags/doc'...
Submodule path 'third_party/gflags/doc': checked out '8411df715cf522606e3b1aca386ddfc0b63d34b4'
Submodule path 'third_party/googleapis': checked out '80ed4d0bbf65d57cc267dfc63bd2584557f11f9b'
Submodule path 'third_party/googletest': checked out 'c9ccac7cb7345901884aabf5d1a786cfa6e2f397'
Submodule path 'third_party/protobuf': checked out '09745575a923640154bcf307fba8aedff47f240a'
Submodule 'third_party/benchmark' (https://github.com/google/benchmark.git) registered for path 'third_party/protobuf/third_party/benchmark'
Submodule 'third_party/googletest' (https://github.com/google/googletest.git) registered for path 'third_party/protobuf/third_party/googletest'
Cloning into '/home/biwi/APP/server/builddir/grpc-repo/src/grpc/third_party/protobuf/third_party/benchmark'...
Cloning into '/home/biwi/APP/server/builddir/grpc-repo/src/grpc/third_party/protobuf/third_party/googletest'...
Submodule path 'third_party/protobuf/third_party/benchmark': checked out '5b7683f49e1e9223cf9927b24f6fd3d6bd82e3f8'
Submodule path 'third_party/protobuf/third_party/googletest': checked out '5ec7f0c4a113e2f18ac2c6cc7df51ad6afc24081'
Submodule path 'third_party/protoc-gen-validate': checked out 'e143189bf6f37b3957fb31743df6a1bcf4a8c685'
Submodule path 'third_party/udpa': checked out '94324803a497c8f76dbc78df393ef629d3a9f3c3'
Submodule path 'third_party/zlib': checked out 'cacf7f1d4e3d44d871b605da3b647f07d718623f'
Failed to recurse into submodule path 'third_party/bloaty'
CMake Error at /home/biwi/APP/server/builddir/grpc-repo/tmp/grpc-repo-gitclone.cmake:52 (message):
  Failed to update submodules in:
  '/home/biwi/APP/server/builddir/grpc-repo/src/grpc'

CMakeFiles/grpc-repo.dir/build.make:110: recipe for target 'grpc-repo/src/grpc-repo-stamp/grpc-repo-download' failed
make[3]: *** [grpc-repo/src/grpc-repo-stamp/grpc-repo-download] Error 1
CMakeFiles/Makefile2:261: recipe for target 'CMakeFiles/grpc-repo.dir/all' failed
make[2]: *** [CMakeFiles/grpc-repo.dir/all] Error 2
CMakeFiles/Makefile2:551: recipe for target 'CMakeFiles/server.dir/rule' failed
make[1]: *** [CMakeFiles/server.dir/rule] Error 2
Makefile:332: recipe for target 'server' failed
make: *** [server] Error 2

**Triton Information**
I tried the 20.10 and master the same error is thrown.
For engineering requirement i can only  build without docker.

**To Reproduce**
git clone https://github.com/triton-inference-server/server.git

git checkout r20.10

cd server

mkdir ./builddir

cd ./builddir

cmake -DTRITON_ENABLE_TENSORRT=ON -DTRITON_ENABLE_GPU=ON -DTRITON_ENABLE_METRICS_GPU=ON \
-DTRITON_ENABLE_TRACING=ON -DTRITON_ENABLE_ENSEMBLE=ON -DTRITON_ENABLE_GCS=ON \
-DTRITON_ENABLE_S3=ON -DTRITON_EXTRA_LIB_PATHS=
"/usr/local/bin;/usr/local/include;/usr/local/lib;/usr/local/cuda;/usr/local/lib/python3.6/dist-packages" \
-DTRITON_ENABLE_GRPC=ON -DTRITON_ENABLE_HTTP=ON ../build

make -j16 server

**Expected behavior**
It seems that the libFuzzer was moved to compiler-rt in  https://reviews.llvm.org/D36908. How can i sovle this problem?

**Comment by deadeyegoodwin** [comment]
Triton build is just trying to pull the grpc repo so any problem there should be resolved by them. We are not seeing any build issues. Closing. If it continues to fail you could try to manually clone the same repo to see if it is something with your local setup.

**Comment by pycoco** [comment]
@Beam-wi do you complie triton successful now ?
