### ISSUE TITLE
Jetson support of pytorch and PTH-TRT

### ISSUE THREAD

**Issue by lorenzo-caruso** [triton-inference-server/server#2240]
Hi, I saw that in deepstream SDK 5.0 release pytorch is not supported yet. I would like to ask some questions about this argument.

1) In a future release is planned to support pytorch in deepstream-triton for jetson? And when?

2) When will PTH-TRT be released?

3) PTH-TRT will be included in deepstream-triton? 

Thanks, Lorenzo

**Comment by CoderHam** [comment]
1. We do plan to add Torch/support to jetson build but this would likely be a couple releases in the future. 
2. Torch-TRT is not currently on our radar. It may be a while till it makes it to x86 and Jetson both.

**Comment by dyastremsky** [comment]
PyTorch is [now supported in Jetson](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/jetson.md). Closing this issue.
