### ISSUE TITLE
How to build libimagepreprocess.so?

### ISSUE THREAD

**Issue by flyingmrwang** [triton-inference-server/server#2250]
I noticed that many people have the demand to make pre/post process on server side. And the ensemble demo of libimagepreprocess.so really works well. But once I want to use my own set of normalization parameters, I need to modify the code and build shared lib myself. However there are difficulty for me like: 1. there are only all-in-one build.py that I don't know how to get into build env to build the lib. 2. So I try to build within tritonserver container and it says "triton/core/tritonserver.h: No such file or directory".
It seems that you encourage people to make custom backend with "triton-inference-server/backend". But it does not looks like a code base for libimagepreprocess.so. 
So please provide demo to build real-life custom backend like preprocess. Or give me some hints.

@GuanLuo @deadeyegoodwin

**Comment by flyingmrwang** [comment]
btw, I am using r20.10

**Comment by deadeyegoodwin** [comment]
The libimagepreprocess.so demo is removed because it relied on the old, legacy custom backend support. If you are intereted in image pre/post processing you should use DALI which provides GPU accelerated preprocessing functions. See https://github.com/triton-inference-server/dali_backend
