### ISSUE TITLE
Request for unknown model: 'resnet50_netdef' is not found

### ISSUE THREAD

**Issue by PerkzZheng** [triton-inference-server/server#2254]
**Description**
under the tritonserver-clientsdk, `Request for unknown model: 'resnet50_netdef' is not found`

**Triton Information**
Following the quick-start guidance. 
https://docs.nvidia.com/deeplearning/triton-inference-server/master-user-guide/docs/quickstart.html#section-quickstart-run-triton-inference-server

Using containers for both the server and the client-sdk. [`nvcr.io/nvidia/tritonserver:20.10-py3, nvcr.io/nvidia/tritonserver:20.10-py3-clientsdk `]

**To Reproduce**
After starting the server `docker run --gpus=1 --rm --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 -p8000:8000 -p8001:8001 -p8002:8002 -v/full/path/to/example/model/repository:/models <docker image> nvcr.io/nvidia/tritonserver:20.10-py3--model-repository=/models`, I started the clientsdk by `docker run -it --rm --net=host nvcr.io/nvidia/tritonserver:20.10-py3-clientsdk`
Then running `/workspace/install/bin/image_client -m resnet50_netdef -s INCEPTION /workspace/images/mug.jpg`

```
/workspace/install/bin# image_client -m resnet50_netdef -s INCEPTION qa/images/mug.jpg
error: failed to get model metadata: Request for unknown model: 'resnet50_netdef' is not found
error: failed to get model config: Request for unknown model: 'resnet50_netdef' is not found
expecting 1 input, got 0
```

There could be some steps that I missed.

**Comment by CoderHam** [comment]
Caffe has been deprecated from Triton. Please refer to the server log (use log-verbose if necessary) to confirm which models are not loaded and what is the reason for each of the models.

**Comment by PerkzZheng** [comment]
@CoderHam. It is fixed. Thanks.
