### ISSUE TITLE
Is there any guide to deploy QuartzNet through triton inference server?

### ISSUE THREAD

**Issue by zjyuan** [triton-inference-server/server#2258]
I am looking for a guide to deploy QuartzNet through triton inference server. After googled, I got nothing. Hope the experts here can provide some help.

**Comment by CoderHam** [comment]
You can follow the instructions for deploying models [here](https://github.com/triton-inference-server/server/blob/master/docs/model_repository.md). Please also follow backend specific instructions. From my reading I understand [QuartzNet](https://github.com/quartznet/quartznet) is a Job Scheduler for the .NET Platform and not a backend (deep learning framework) or a model. If so Tritonserver does not cater to this usecase.

**Comment by zjyuan** [comment]
> You can follow the instructions for deploying models [here](https://github.com/triton-inference-server/server/blob/master/docs/model_repository.md). Please also follow backend specific instructions. From my reading I understand [QuartzNet](https://github.com/quartznet/quartznet) is a Job Scheduler for the .NET Platform and not a backend (deep learning framework) or a model. If so Tritonserver does not cater to this usecase.

Thanks for your reply. QuartzNet is another asr model, like jasper, but smaller. FYI. [https://developer.nvidia.com/blog/develop-smaller-speech-recognition-models-with-nvidias-nemo-framework/](url)

**Comment by CoderHam** [comment]
Could you follow the instructions from the docs and let us know if you have any issues.

**Comment by RAHUL-KAD** [comment]
Here is the updated link for model repository [Here](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/model_repository.md)
