### ISSUE TITLE
Issue while Serving the model using Triton Server 

### ISSUE THREAD

**Issue by Darshcg** [triton-inference-server/server#2260]
Hi Nvidia Team,

I am trying to Serve the Custom Model using Triton Server on my PC(having RTX 2060 GPU).
I am using nvcr.io/nvidia/tensorrtserver:19.10-py3 container for Serving.

![Screenshot from 2020-11-18 18-18-59](https://user-images.githubusercontent.com/48723743/99573506-330e3a80-29fc-11eb-9265-b1cf6f8ca3c4.png)
While I am serving I am getting an error(found in the attached image below).

I used nvcr.io/nvidia/tensorrt:19.10-py2 Image to convert the Model from ONNX to Tensorrt.
May I know where I am doing wrong? And how to avoid this error?

Thanks in advance

**Comment by deadeyegoodwin** [comment]
Firstly you should use an up-to-date version of triton, 19.10 is over a year old. From the error is looks like the model requires a custom layer/plugin that you may need to provide. I would first try the most recent triton release (and corresponding tensorrt) which is 20.10. If you do need to provide a custom layer to triton, that doc is here: https://github.com/triton-inference-server/server/blob/master/docs/custom_operations.md

**Comment by Darshcg** [comment]
Thank you very much @deadeyegoodwin. Now I get the clarity on the Issue.
Actually, I compiled the Tensorrt custom layer implementations to libtrtcustom.so, can you please help me loading into Triton?
I am using this command to start the serving: 
```
sudo nvidia-docker run \
    --runtime nvidia \
    --rm --shm-size=1g \
    --ulimit memlock=-1 \
    --ulimit stack=67108864 \
    -p 8000:8000 -p 8001:8001 -p 8002:8002 \
    --name trt_serving \
    -v $model_path:/models \
    nvcr.io/nvidia/tensorrtserver:19.10-py3 \
    trtserver --model-store=/models
```

Can you please me what is modifications need to be done while running this command in order to load the custom layer implementations into the triton?

Thanks in advance
