### ISSUE TITLE
onnx model inference cpu usage

### ISSUE THREAD

**Issue by leqiao-1** [triton-inference-server/server#2265]
**Description**
I use triton server for onnx model inference on a GPU machine with 6 cpu cores. I start the server without gpu enabled and without cpu and memory limit. 
When I try with no model instance group, the cpu usage of tritonserver process is about 350%. And when I try with 2 model instance groups, the cpu usage of tritonserver process is also about 350%. When I use onnxruntime python package for same model with one concurrency, there is one process with cpu usage 550%, and 2 processes with 290% for 2 concurrency.

**Expected behavior**
Is there any way to use 6 cpus cores and increase the cpu usage ?

Thanks

**Comment by leqiao-1** [comment]
I will try to increase request concurrency

**Comment by leqiao-1** [comment]
With no model instance group settings in config.pbtxt and request concurrency = 1, cpu usage is about 350%. 
With model instance group count = 2 and request concurrency = 2, cpu usage is about 270%. 
Is that expected ? Thanks.

**Comment by deadeyegoodwin** [comment]
You need to share more details. What are your model configurations? Have you read the related docs? https://github.com/triton-inference-server/server/blob/master/docs/model_configuration.md#instance-groups

**Comment by leqiao-1** [comment]
Way to reproduce:
server image: nvcr.io/nvidia/tritonserver:20.09-py3
client image: nvcr.io/nvidia/tritonserver:20.09-py3-clientsdk
triton model: densenet_onnx 

run script with python concurrency.py in client container
observe cpu usage with top.

I put model and script here: https://drive.google.com/file/d/1eQxOGg1h3CmQHldOmlBSEmYvbSKTIjPt/view?usp=sharing

**Comment by leqiao-1** [comment]
another question for this model and test. Is that normal that conpute_infer/count augments when request concurrency augments ? Thanks
