### ISSUE TITLE
Adding Custom layer to Triton

### ISSUE THREAD

**Issue by Darshcg** [triton-inference-server/server#2267]
Hi Nvidia Team,
Referring to this(https://github.com/triton-inference-server/server/blob/master/docs/custom_operations.md) I have compiled the Tensorrt custom layer implementations to libtrtcustom.so.  So, how to load libtrtcustom.so into Triton?
I am using this command to start the serving:

```
sudo nvidia-docker run \
    --runtime nvidia \
    --rm --shm-size=1g \
    --ulimit memlock=-1 \
    --ulimit stack=67108864 \
    -p 8000:8000 -p 8001:8001 -p 8002:8002 \
    --name trt_serving \
    -v $model_path:/models \
    nvcr.io/nvidia/tensorrtserver:19.10-py3 \
    trtserver --model-store=/models

```
Can you please help me what modifications need to be done while running this command in order to load the custom layer implementations into the triton?

Thanks in advance

**Comment by CoderHam** [comment]
Please refer to the instruction for TensorRT in [custom_operations.md](https://github.com/triton-inference-server/server/blob/master/docs/custom_operations.md) that asks you to LD_PRELOAD the custom op libraries. Please re-open if the following does not work for you.  
```
LD_PRELOAD=libtrtcustom.so tritonserver --model-repository=/tmp/models ...
```
