### ISSUE TITLE
[Crash] Triton Server 20.10 crashing with 'double free or corruption (out)' with TensorFlow XLA-GPU enabled

### ISSUE THREAD

**Issue by tridemax** [triton-inference-server/server#2269]
**Description**
After successfully serving the request for TensorFlow model, the server crashes on the next call with the error 'double free or corruption (out)'. I'm using Python `tritonclient[grpc]` to call the server.

**Triton Information**
Triton Server running from docker image 20.10 (latest for the moment).
Environment: AWS EC2 instance running single T4 GPU (g4dn.2xlarge).

Are you using the Triton container or did you build it yourself?
Container.

**To Reproduce**
Client: tritonclient[grpc]
Model format: TensorFlow Saved Model
Model config: https://gist.github.com/tridemax/0287d0c57cb7edb018f7507198d8eeab

Note: XLA enabled as could be seen in config (`graph { level: 1 }`). Disabling the XLA doesn't reproduce the crash anymore. I have 2 different models and server starts crashing if ANY of them is XLA-enabled, i.e. it still crashes if one model is XLA-enabled and other one is XLA-disabled.

May be I could enable any kind of logging to help locating the source of this issue?

**Comment by deadeyegoodwin** [comment]
Is this issue resolved? Closing, reopen if new information.

**Comment by soulseen** [comment]
@tridemax Is this issue resolved? I met the same problem.

**Comment by soulseen** [comment]
> > @tridemax Is this issue resolved? I met the same problem.
> 
> We just disabled XLA. Never tried it with the new releases of the Triton Server.

but I have not enabled XLA, also met the error: double free or corruption (out)' in the first inference request.

Client: python HTTP requests
Model format: TensorFlow Saved Model
here is my Model config:
```
max_batch_size: 1024
instance_group [
  {
    count: 0
    kind: KIND_GPU
    gpus:  [0]
  }
 ]
dynamic_batching{
    preferred_batch_size:[ 8 ]
    max_queue_delay_microseconds: 1000 
}
```

**Comment by tridemax** [comment]
@soulseen I would suggest just play a bit with the optimization settings and check your batch size in different configurations. Also try to use last or last-1 version.
