### ISSUE TITLE
Client side memory leak in python sdk using shared memory

### ISSUE THREAD

**Issue by philipp-schmidt** [triton-inference-server/server#2274]
**Description**
The python client SDK currently leaks memory when registering and unregistering shared memory (very often) in a single process. This is because the current implementation does not unmap the shared memory on destroy.

**Triton Information**
version: nvcr.io/nvidia/tritonserver:20.08-py3

Are you using the Triton container or did you build it yourself?
NGC

**To Reproduce**
Repeat in a single process:
triton_client.register_system_shared_memory()
shm.set_shared_memory_region()
triton_client.unregister_system_shared_memory()
shm.destroy_shared_memory_region()

**Expected behavior**
RAM usage of the process does not constantly increase.

**Additional info**
The current client implementation only does `shm_unlink`:
https://github.com/triton-inference-server/server/blob/8ea7cc316d5d5baf4f6367c7be298e93f4e9876f/src/clients/python/library/tritonclient/utils/shared_memory/shared_memory.cc#L130-L140

The server on the other hand properly unmaps the memory:
https://github.com/triton-inference-server/server/blob/12f29e1d76d4d031b630f36ad0a27429d7f5716e/src/servers/shared_memory_manager.cc#L171-L182

According to [this site](http://www3.physnet.uni-hamburg.de/physnet/Tru64-Unix/HTML/APS33DTE/DOCU_004.HTM), memory is only released if unmapped:

> The shm_unlink function unlinks the shared-memory object. Memory objects are persistent, which means the contents remain until all references have been unmapped and the shared-memory object has been unlinked with a call to the shm_unlink function.

Probable quick n dirty fix (untested and coded right here and now):

```c++
int
SharedMemoryRegionDestroy(void* shm_handle)
{
  std::string shm_key =
      reinterpret_cast<SharedMemoryHandle*>(shm_handle)->shm_key_;
  int shm_fd = shm_unlink(shm_key.c_str());
  if (shm_fd == -1) {
    return -5;
  }
  int status = munmap(reinterpret_cast<SharedMemoryHandle*>(shm_handle)->base_addr_, reinterpret_cast<SharedMemoryHandle*>(shm_handle)->byte_size_);
  if (status == -1) {
    return status;
  }
  return 0;
}
```

**Comment by CoderHam** [comment]
Fixed by: https://github.com/triton-inference-server/server/pull/2279

**Comment by philipp-schmidt** [comment]
Perfect, thanks. In which pypi package version can I expect this fix to be included? 2.4.0 won't be changed right? 2.5?

**Comment by CoderHam** [comment]
It will make it to 2.6.0 (20.12 release) We code froze for 20.11 a while ago. You can use the patch I shared to build a fixed version of the python library. In my understanding it should be backward compatible.

**Comment by philipp-schmidt** [comment]
Alright, will do. Thanks again for the fast fix as always.
