### ISSUE TITLE
anyone build triton by cmake or buil.py  success in ubuntu?

### ISSUE THREAD

**Issue by pycoco** [triton-inference-server/server#2277]

**Comment by GuanLuo** [comment]
Can you provide detail regarding your issue? Our CI uses build.py script and it can build Triton server and its components.

**Comment by pycoco** [comment]
> Can you provide detail regarding your issue? Our CI uses build.py script and it can build Triton server and its components.

https://github.com/triton-inference-server/server/issues/2238

**Comment by deadeyegoodwin** [comment]
See linked issue. Closing.
