### ISSUE TITLE
E1120 12:54:31.030207 49 model_repository_manager.cc:1007] failed to load 'yolov3-spp' version 1: Invalid argument: model 'yolov3-spp_0_gpu0', tensor '000_net': the model expects 4 dimensions (shape [1,3,608,608]) but the model configuration specifies 3 dimensions (shape [3,608,608])

### ISSUE THREAD

**Issue by Darshcg** [triton-inference-server/server#2278]
Dear Nvidia Team,

I am trying to Serve the Custom Model using Triton Server on my PC(having RTX 2060 GPU).
I am using nvcr.io/nvidia/tensorrtserver:20.07-py3 container for Serving.

While I am serving I am getting an error(found in the attached image below).
![Screenshot from 2020-11-20 18-24-36](https://user-images.githubusercontent.com/48723743/99802981-a760ef00-2b5e-11eb-9da7-301d6132af24.png)

I used nvcr.io/nvidia/tensorrt:20.07-py3 Image to convert the Model from ONNX to Tensorrt.
May I know where I am doing wrong? And how to avoid this error?

Below is the config.pbtxt file content:
```
name: "yolov3-spp"
platform: "tensorrt_plan"
max_batch_size: 1
input [
  {
    name: "000_net"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 608, 608 ]
  }
]
output [
  {
    name: "(Unnamed Layer* 253) [PluginV2IOExt]_output_0"
    data_type: TYPE_FP32
    dims: [ 36, 19, 19 ]
  },
  {
    name: "(Unnamed Layer* 254) [PluginV2IOExt]_output_0"
    data_type: TYPE_FP32
    dims: [ 36, 38, 38 ]
  },
  {
    name: "(Unnamed Layer* 255) [PluginV2IOExt]_output_0"
    data_type: TYPE_FP32
    dims: [ 36, 76, 76 ]
  }
]

```

Thanks in advance

**Comment by CoderHam** [comment]
Since you are setting max_batch_size to 1 the model expects a batch dimension. You can choose to run the model without batching by setting the max_batch_size to 0 or add the batch dimension.

**Comment by Darshcg** [comment]
Hi @CoderHam,
I have tested with setting max_batch_size:0, but its the same error(screenshot of the same is attached below):
![Screenshot from 2020-11-21 13-17-32](https://user-images.githubusercontent.com/48723743/99870839-150f2880-2bfc-11eb-9896-ab1ea3a138f1.png)

After adding the batch dimension, I get the error like: **E1121 07:52:00.685025 49 model_repository_manager.cc:1705] model input NHWC/NCHW require 3 dims for yolov3-spp**
![Screenshot from 2020-11-21 13-23-05](https://user-images.githubusercontent.com/48723743/99870933-b5654d00-2bfc-11eb-948b-a5293640498f.png)

**Comment by CoderHam** [comment]
Your model stores the fact that it has a batch dimension (in the metadata of the graph). Therefore you cannot set batch size to 0. Instead you will need to use a batch size of 1 in your client while sending requests to the server. The input tensor shape should be `(batch_size,) + tensor_shape` where `tensor_shape` was the shape of your tensor without the batch dimension.

**Comment by GuanLuo** [comment]
The error message suggest that the model is expecting input with shape [1, 3, 608, 608], so you should set `max_batch_size: 0` and use [1, 3, 608, 608] as input shape. `max_batch_size` can be set to non-zero only if the model supports dynamic batching, in other words, all I/O tensors have dynamic dimension (-1) as their first dimension, which is not the case for your model. You may need to take a look at your model generation script to see if it is generating the model with dynamic shape.

**Comment by Darshcg** [comment]
Hi @CoderHam and @GuanLuo,

After some days of Research and workaround, the config.pbtxt file format for my Custom trained YoloV3-SPP is:
```
name: "yolov3-spp"
platform: "tensorrt_plan"
max_batch_size:1
input {
  name: "000_net"
  data_type: TYPE_FP32
  dims: [1,3, 608, 608]
}
output {
  name: "(Unnamed Layer* 253) [PluginV2IOExt]_output_0"
  data_type: TYPE_FP32
  dims: 1
  dims: 7581
  dims: 1
  dims: 1
}
output {
  name: "(Unnamed Layer* 254) [PluginV2IOExt]_output_0"
  data_type: TYPE_FP32
  dims: 1
  dims: 30324
  dims: 1
  dims: 1
}
output {
  name: "(Unnamed Layer* 255) [PluginV2IOExt]_output_0"
  data_type: TYPE_FP32
  dims: 1
  dims: 121296
  dims: 1
  dims: 1
}
instance_group [
  {
    count:1
    kind: KIND_GPU
  }
]
```

But the name of the Output layers of my Model are: **089_convolutional**, **101_convolutional**, **113_convolutional**, but If I add these names in the config.pbtxt file, then I am facing the Issue while Serving. May I know the specific reason? The reason for asking this is, the dimension response(trt_outputs) I am getting after sending the request is not correct.

Thanks in advance

**Comment by deadeyegoodwin** [comment]
Closing, reopen if new information.
