### ISSUE TITLE
Error Handling in  ` model.py ` 

### ISSUE THREAD

**Issue by Fizmath** [triton-inference-server/server#2289]
Hello

Since none of my  modules could be imported in ```model.py```  https://github.com/triton-inference-server/server/issues/2268 ,  i just pasted the codes into ```model.py```  . The server loaded the model then i sent my request from the client side and got this error :    

![error](https://user-images.githubusercontent.com/40030502/100080336-c3160f00-2e56-11eb-9a10-3d3ab0c4d50e.png)

Where did this ```  'Tensor' object has no attribute 'size' ``` come from ?  what   **line number**   is causing this error ? 

it might've came from ``model.py`` or  ```triton_python_backend_utils.py``` or from their sub-modules .

Please show how to  get  **Traceback** :  **line number** in addition to error messages at all levels.

**Comment by Tabrizian** [comment]
Can you share your Python model?

**Comment by Fizmath** [comment]
To elucidate the problem let's produce simple mock error in examples  ```model.py```    :   

just simply delete one of the two  ``` .as_numpy() ```  from this line :   

https://github.com/triton-inference-server/python_backend/blob/main/examples/pytorch/model.py#L131

so 
``` out_0, out_1 = self.add_sub_model(in_0.as_numpy(), in_1.as_numpy()) ```
 becomes  
```out_0, out_1 = self.add_sub_model(in_0                     ,                in_1.as_numpy()) ```

then run the mocked example ,  there'd be no reflection in server side terminal but in client side terminal you'd see this  :  

![err](https://user-images.githubusercontent.com/40030502/100194732-4727cf80-2f07-11eb-9c83-add58777fe6b.png)


you only see the error message ``` ... unsupported operand type(s) for +: 'Tensor' and 'float' ```  but where did it come from  ?  from   which **file** and  **line number** ?  

we intentionally did this error in ``` ../examples/pytorch/model.py ```  in **line 131**   , these must be printed out in client's or server's  terminals.   Logical ,  isn't it ?

**Comment by Tabrizian** [comment]
This has been fixed. Please use the `20.11` container (nvcr.io/nvidia/tritonserver:20.11-py3). This is the traceback that I got when I use the 20.11 container:

```
Traceback (most recent call last):
  File "client.py", line 57, in <module>
    outputs=outputs)
  File "/usr/local/lib/python3.6/dist-packages/tritonclient/http/__init__.py", line 1101, in infer
    _raise_if_error(response)
  File "/usr/local/lib/python3.6/dist-packages/tritonclient/http/__init__.py", line 63, in _raise_if_error
    raise error
tritonclient.utils.InferenceServerException: GRPC Execute Failed, message: Traceback (most recent call last):
  File "/opt/tritonserver/backends/python/startup.py", line 269, in Execute
    responses = self.backend.execute(inference_requests)
  File "/workspace/qa/L0_backend_python/models/pytorch/1/model.py", line 131, in execute
    out_0, out_1 = self.add_sub_model(in_0, in_1.as_numpy())
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/workspace/qa/L0_backend_python/models/pytorch/1/model.py", line 51, in forward
    return (input0 + input1), (input0 - input1)
TypeError: unsupported operand type(s) for +: 'Tensor' and 'float'
```
