### ISSUE TITLE
Fix S3 authentication for IAM roles by including Session token in env vars

### ISSUE THREAD

**Issue by nsiddharth** [triton-inference-server/server#2291]
**Description**
Triton server does not read SESSION_TOKEN environment variable that is required when using IAM roles and temp credentials. Please see: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html for more information. S3 resources cannot be accessed by triton even though they are accessible from command line. (Docker containers are usually provisioned with IAM roles and use temporary credentials)

**Triton Information**
What version of Triton are you using?
r20.10
Are you using the Triton container or did you build it yourself?
Used the container
**To Reproduce**
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**
```tritonserver --model-repository=s3://path/to/model_repo ```
This fails with ```cannot read metadata for Bucket```
However ```aws s3 ls s3://path/to/model_repo``` works

The solution is to include AWS_SESSION_TOKEN when available and I have created a PR here for the same:
https://github.com/triton-inference-server/server/pull/2290

Please merge this if it looks good as I suspect this will resolve a lot of s3 access issues.

**Comment by CoderHam** [comment]
Closed by #2290

**Comment by Debangshu132** [comment]
it still doesnot work. have added AWS_SESSION_TOKEN env variable

**Comment by CoderHam** [comment]
Which version of Tritonserver are you using?

**Comment by Debangshu132** [comment]
Hi I am using version 20.11

**Comment by CoderHam** [comment]
It was merged into the master recently (9 days ago) and will likely be in 21.01 or the subsequent release. If required you can build Tritonserver with a patch from the above PR.

**Comment by sanjukta2706** [comment]
I am trying to setup a model repository on AWS S3 and running Triton Server via the Docker image (21.03) on an EC2 instance. I have ensured that the IAM policy is able to access S3. I still get the 'cannot read metadata for Bucket' error. Are the changes as mentioned in the issue above merged and available in the Docker image for 21.03?

**Comment by nsiddharth** [comment]
This is available in 21.03 and works as expected. The right way to figure out if there is an issue with triton or your permissions would be to run:
`aws s3 ls s3://your_path` on the docker container running triton
if this works and you are able to read the path and somehow triton is not able to when it starts up then it indicates an issue with triton. There is most likely an issue with your permissions.

**Comment by TomasGajarsky** [comment]
We are still having the same/similar issue with Triton 21.05.

Access to S3 from the machine is verified and working properly, but Triton is not able to use temporary AWS credentials provided by a service account when trying to pass remote S3 path as model repository. 
Error message:
`Could not get MetaData for bucket with name`

It is working when AWS credentials are set as environment variables, but we do not want to do that for security reasons. Can this be fixed, please?

**Comment by efog** [comment]
The issue still occurs when the EC2 instance running underneath the ECS Task instance uses metadata service v2 (IMDSv2). Thus far, the only workaround is to revert to the v1 metadata service. 

Setup:
Amazon ECS.
Task definition using Triton Inference server 21.03.
EC2 instance.

**Comment by CoderHam** [comment]
@TomasGajarsky we have noted your request to this enchancement.

@efog Can you try with a recent version of Triton Inference Server? 21.03 is nearly a year old. We [updated the version of aws-sdk-cpp](https://github.com/triton-inference-server/third_party/pull/6) used in Triton 8 months ago.

If you see the issue with the new Triton release as well please open a new ticket for the same with necessary details for us to triage the issue

**Comment by garimachhabra20** [comment]
I am seeing this issue for triton version 22.04.

**Comment by kthui** [comment]
Hi, we have added a test to check the functionality of temporary credential for AWS, and the test is passing. If you are still facing issue with session token, please take a look into the test that starts from [L345](https://github.com/triton-inference-server/server/blob/main/qa/L0_storage_S3/test.sh#L345) towards the end of the script to see if that is the same use-case as yours. If not, please file a separate GitHub issue, so we can follow-up.
