### ISSUE TITLE
TorchScript concurrent inference net execution time is substantially higher than single inference execution time

### ISSUE THREAD

**Issue by TediPapajorgji** [triton-inference-server/server#2294]
## Description
In summary, it appears that allowing triton to execute concurrently on one of our TorchScript models causes a substantial increase in execution time. We observe a slow down of up-to ~74% when executing 3 inference requests in parallel on the same model when compared to executing only 1 inference request on said model.

Executing 1 inference request on one of our torch script model takes on average 0.0956s using triton, while execution of 3 concurrent inference requests (with instance groups set to 3) takes on average 0.166s for all requests to finish.

It appears that GPU memory and processors are not being utilized 100% so we are lead to believe that a hardware bottleneck is not the problem
### Observations
Our observations can be found below, for all observations the following is true:
- Models are warmed up
- Triton is being run on the same machine from where the inference requests are coming from (to minimize network overhead)
- The same torch script model and input is used for every sample
 
#### 1 inference request
![image](https://user-images.githubusercontent.com/5790075/100279757-27a79b80-2f35-11eb-8830-79193130b4c4.png)

![image](https://user-images.githubusercontent.com/5790075/100275072-676a8500-2f2d-11eb-9fd9-f09635dc13be.png)

#### 3 concurrent inference requests
![image](https://user-images.githubusercontent.com/5790075/100279836-4312a680-2f35-11eb-865c-aaec5f38852b.png)

![image](https://user-images.githubusercontent.com/5790075/100274720-edd29700-2f2c-11eb-8f57-0a32f4db14ed.png)

## Triton Information
What version of Triton are you using?
We are using triton 2.40

Are you using the Triton container or did you build it yourself?
Yes we are using the triton container, specifically: nvcr.io/nvidia/tritonserver:20.10-py3

## To Reproduce

Here is our model configuration file:
```
platform: "pytorch_libtorch"
input [
  {
    name: "unscaledmels__0"
    data_type: TYPE_FP32
    dims: [ -1, -1, -1 ]
  },
  {
    name: "f0__1"
    data_type: TYPE_FP32
    dims: [ -1,  -1, -1 ]
  },
	{
    name: "uv__2"
    data_type: TYPE_FP32
    dims: [ -1, -1, -1 ]
  }
]
output [
  {
    name: "audiodata__0"
    data_type: TYPE_FP32
    dims: [ -1, -1 ]
  }
]
instance_group [
  {
    count: 3
    kind: KIND_GPU
    gpus: [ 0 ]
  }
]
```

Heres the quick and dirty test script I Wrote to test inference, you'll notice i spawn a thread for each request to have them run concurrently (as close as possible):

```
import numpy as np
import sys
import gevent.ssl
import tritonclient.http as httpclient
from tritonclient.utils import InferenceServerException
import time
import _thread
from datetime import datetime
import argparse

def test_infer(thread, model_name, unscaledmels_data, f0_data, headers=None):
    triton_client = httpclient.InferenceServerClient(url="localhost:8000", verbose=False)
    #start = time.time()
    inputs = []
    outputs = []
    inputs.append(httpclient.InferInput('unscaledmels__0', [unscaledmels_data.shape[0], unscaledmels_data.shape[1], unscaledmels_data.shape[2]], "FP32"))
    inputs.append(httpclient.InferInput('f0__1', [f0_data.shape[0], f0_data.shape[1], f0_data.shape[2]], "FP32"))
    inputs.append(httpclient.InferInput('uv__2', [f0_data.shape[0], f0_data.shape[1], f0_data.shape[2]], "FP32"))

    # Initialize the data
    inputs[0].set_data_from_numpy(unscaledmels_data, binary_data=False)
    inputs[1].set_data_from_numpy(f0_data, binary_data=False)
    inputs[2].set_data_from_numpy(f0_data, binary_data=False)

    outputs.append(httpclient.InferRequestedOutput('audiodata__0', binary_data=False))
    start = time.time()
    results = triton_client.infer(model_name,
                                  inputs,
                                  outputs=outputs,
                                  headers=headers)
    print(f"Thread {thread} synthesis time: {time.time() - start}", flush=True)
    now = datetime.now()
    milisecs = float(now.strftime("%f"))/1000
    current_time = now.strftime("%H:%M:%S")
    print(f"Completed at {current_time}:{milisecs}")
    print(f"------------")
    return results

parser = argparse.ArgumentParser(description='Run triton inference with specified num of threads.')
parser.add_argument('threads', metavar='N', type=int, nargs='?', default=1, help='integer specifying number of threads')
args = parser.parse_args()

NUM_THREADS = args.threads


mels = np.load('mels.npy')
f0 = np.load('f0.npy')

# Create two threads as follows

now = datetime.now()
milisecs = float(now.strftime("%f"))/1000
current_time = now.strftime("%H:%M:%S")
print(f"Starting all threads at {current_time}:{milisecs}")

for x in range(NUM_THREADS):
    try:
        _thread.start_new_thread(test_infer, ((x + 1), "hooligan", mels, f0))
    except Exception as e:
        print(e)

time.sleep(500)
print('done')
```

## Expected behavior
We expect to see a slight increase in execution time for concurrent model requests but not as significant as the amount being observed currently.

**Comment by CoderHam** [comment]
Concurrent execution of Torchscript models using the Pytorch (Libtorch) Triton Backend does not work as expected due to thread specific model caching. Please follow up with Pytorch on the bug: https://github.com/pytorch/pytorch/issues/27902 as they are investigating the same and likely working to fix the same.

**Comment by deadeyegoodwin** [comment]
The pytorch issue is still open and is the root of this slowdown. Closing.
