### ISSUE TITLE
error with shared memory with client in triton client sdk: failed to register input shared memory region

### ISSUE THREAD

**Issue by nicolasMeg** [triton-inference-server/server#2296]
I'm not able to share memory with triton server using the triton client sdk docker image.

I run the docker : 

`docker run --gpus all -it --rm --net=host nvcr.io/nvidia/tritonserver:20.09-py3-clientsdk simple_http_shm_client`

and get the response : 

`error: failed to register input shared memory region: Unable to open shared memory region: '/input_simple'`

It's pretty easy to reproduce the bug as it's a simple docker command.

Please note that the cuda shm works fine.

**Comment by CoderHam** [comment]
You will need the `--ipc=host` arg while launching the container to be able to access shared memory across different containers. Additionally use  `--shm-size` to increase the total shared memory size if the default is not large enough.
Please refer to the Docker docs for the same: https://docs.docker.com/engine/reference/run/#ipc-settings---ipc

**Comment by lfxx** [comment]
> You will need the `--ipc=host` or similar arg while launching the container to be able to access shared memory across different containers. Additionally use `--shm-size` to increase the total shared memory size if the default is not large enough. Please refer to the Docker docs for the same: [docs.docker.com/engine/reference/run/#ipc-settings---ipc](https://docs.docker.com/engine/reference/run/#ipc-settings---ipc)

with --ipc=host to start the triton server,i still can not register input shared memory region.Any suggestons?thanks!
