### ISSUE TITLE
Build from sources r2.5 does not work correctly

### ISSUE THREAD

**Issue by ViktorYastrebov** [triton-inference-server/server#2297]
**Description**
r2.5.0 Building is failed under Ubuntu 20.04 LTS

**Triton Information**
https://github.com/triton-inference-server/server/releases/latest
 v2.5.0

I just downloaded the attached sources and build by my own

**To Reproduce**
 1. Download sources by the link above.
 2. Make sure all dependencies are installed ( TensorRT,  libcurl4-openssl-dev,  rapidjson-dev  curl etc )
 3. Regarding this guide: https://docs.nvidia.com/deeplearning/triton-inference-server/master-user-guide/docs/client_library.html
    run:
    $: mkdir builddir
    $: cd builddir 
    $ cmake -DCMAKE_BUILD_TYPE=Release ../build
    $ make -j8 client
This is the part of build log:

[ 67%] Built target simple_grpc_sequence_stream_infer_client
[ 68%] Linking CXX executable ensemble_image_client
[ 69%] Built target ensemble_image_client
[ 71%] Linking CXX executable simple_grpc_shm_client
[ 73%] Built target simple_grpc_shm_client
[ 76%] Built target simple_http_cudashm_client
[ 76%] Linking CXX executable simple_grpc_custom_repeat
[ 77%] Built target simple_grpc_custom_repeat
[ 78%] Linking CXX executable perf_analyzer
[ 90%] Built target perf_analyzer
[ 92%] Generating linux_stamp.whl
...
2.5.0/builddir/client/src/clients/python/library/linux//wheel
Adding package files
cp: cannot stat 'tritonclient/utils/libcshm.so': No such file or directory
make[5]: *** [src/clients/python/library/CMakeFiles/linux-client-wheel.dir/build.make:80: src/clients/python/library/linux_stamp.whl] Error 1
make[4]: *** [CMakeFiles/Makefile2:1441: src/clients/python/library/CMakeFiles/linux-client-wheel.dir/all] Error 2
make[3]: *** [Makefile:149: all] Error 2
make[2]: *** [CMakeFiles/client.dir/build.make:134: client/src/client-stamp/client-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:375: CMakeFiles/client.dir/all] Error 2
make: *** [Makefile:103: all] Error 2

**Expected behavior**
Build is successful

Additional info:
C++ fixes: 

src/core/scheduler_utils.h: 
```
+    ~Cursor() = default;
     Cursor(PriorityQueues::iterator start_it);
-
+   
     Cursor(const Cursor& rhs)
         : curr_it_(rhs.curr_it_), queue_idx_(rhs.queue_idx_),
           at_delayed_queue_(rhs.at_delayed_queue_),
@@ -230,6 +231,9 @@ class PriorityQueue {
           pending_batch_count_(rhs.pending_batch_count_), valid_(rhs.valid_)
     {
     }
+    
+    Cursor & operator = (const Cursor& rhs) = default;
```

Scripts fixes:
src/clients/python/library/build_wheel.sh

```
-    cp ../../../core/model_config_pb2.py \
-      "${WHLDIR}/tritonclient/grpc/."
-    cp ../../../core/grpc_service_pb2.py \
-      "${WHLDIR}/tritonclient/grpc/service_pb2.py"
-    cp ../../../core/grpc_service_pb2_grpc.py \
-      "${WHLDIR}/tritonclient/grpc/service_pb2_grpc.py"
+     cp ./tritongrpcclient/model_config_pb2.py \
+       "${WHLDIR}/tritonclient/grpc/."   
+#    cp ../../../core/model_config_pb2.py \
+#      "${WHLDIR}/tritonclient/grpc/."
+     cp ./tritongrpcclient/grpc_service_pb2.py \
+       "${WHLDIR}/tritonclient/grpc/service_pb2.py"
+#    cp ../../../core/grpc_service_pb2.py \
+#      "${WHLDIR}/tritonclient/grpc/service_pb2.py"
+#    cp ../../../core/grpc_service_pb2_grpc.py \
+#      "${WHLDIR}/tritonclient/grpc/service_pb2_grpc.py"
+    cp ./tritongrpcclient/grpc_service_pb2_grpc.py \
+       "${WHLDIR}/tritonclient/grpc/service_pb2_grpc.py"

```

**Comment by ViktorYastrebov** [comment]
Please if it's not an issue could you give an workaround. Looks like make does not build libcshm.

**Comment by CoderHam** [comment]
Libcshm.so is the cuda shared library and it requires the `-DTRITON_ENABLE_GRPC=ON` flag.

**Comment by deadeyegoodwin** [comment]
FYI, Ubuntu 20.04 will be supported starting with the Triton 2.6.0 release (20.12). But I'm not sure the above failure is related to ubuntu 20.04.

**Comment by ViktorYastrebov** [comment]
Thank you for responses.
I just turned off teh python client building and that's it. I need only C++ interface library.
