### ISSUE TITLE
RTX 3000 series?

### ISSUE THREAD

**Issue by turowicz** [triton-inference-server/server#2299]
Has anyone tried using the latest RTX 3000 series with Triton?

We have just placed an order for a whole lot of them as they are way more cost effective than the previous 2000 generation.

**Comment by mfuntowicz** [comment]
I'm using Triton v20.11 over a RTX 3090 for dev purpose, works fine so far 👍

**Comment by turowicz** [comment]
I just got my 3090 and it works well too! I haven't been able to run TF trainings though.
