### ISSUE TITLE
How to load more than one custom plugin, LD_PRELOAD

### ISSUE THREAD

**Issue by chull434** [triton-inference-server/server#2301]
Does anyone know how to or if its possible to load more than one custom plugin via the LD_Preload env variable?

Have two models and two plugin files and have been unable to get the triton server to load both plugin files

Probably just have the wrong syntax or something in the variable string but haven't found any posts with an example to copy

thanks
~whiskers434

**Comment by deadeyegoodwin** [comment]
Did you try a space-separated list? https://stackoverflow.com/questions/8474363/specifying-multiple-files-with-ld-preload

**Comment by chull434** [comment]
> Did you try a space-separated list? https://stackoverflow.com/questions/8474363/specifying-multiple-files-with-ld-preload

I did yeah but it only ever wants to load the first one it finds

`--env LD_PRELOAD="/plugins/liblayerplugin.so /plugins/libyololayer.so" `
loads only _liblayerplugin.so_

`--env LD_PRELOAD="/plugins/libyololayer.so /plugins/liblayerplugin.so " `
loads only _libyololayer.so_

`--env LD_PRELOAD="/plugins/libnotaplugin.so /plugins/libyololayer.so" `
loads _libyololayer.so_ only after not being able to find the first plugin

think it might be bugged if its not loading the second plugin but maybe still just have the variable wrong somehow or its docker not passing the variable correctly or something?

**Comment by chull434** [comment]
Any ideas what the best way to confirm this is a bug with triton server and what the next steps would be to resolve this issue?

**Comment by CoderHam** [comment]
https://man7.org/linux/man-pages/man8/ld.so.8.html says it should be space or colon separated. Maybe set the environment manually instead of  as a docker arg. It's possible docker does not parse it correctly.

**Comment by chull434** [comment]
Hi, sorry only getting back to this now, still having the same issue of triton server not wanting to load more than one custom plugin.

Have tried setting the environment variable for LD_PRELOAD manually, using the latest tritionserver:20.12-py3 image, have tried both space separated and colon separated both have same effect as before. It does seem like it is reading the LD_PRELOAD path correctly as if you typo either of the plugins it logs that it can't read that plugin 'object '/plugins/notaplugin.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file):'. 

I think there might be an issue here if its not loading the second plugin, unless there's something else I am still doing wrong?

In the verbose logging, 'Registering TensorRT Plugins', only seems to log the built in plugins not the custom loaded ones, is there anywhere to see the list of custom loaded plugins? and confirm it is loading the first plugin it finds but not the second?

**Comment by chull434** [comment]
had another go at this and confirmed both space and colon separated multiple plugin loading works, issue was with the plugins still sharing names somewhere, did a full rename on both and it now works

**Comment by lzcchl** [comment]
这很基础，环境变量用:(linux)或者;(windows)分隔，而不是空格
