### ISSUE TITLE
Why is there such a big performance difference between using http and grpc?

### ISSUE THREAD

**Issue by mailyyin** [triton-inference-server/server#2306]
I use perf_analyzer to test performance. When using http protocol, it was found that increasing "concurrency" will cause the client latency to be larger (server latency does not change much). The top command shows the high cpu sy usage when using http protocol, and the perf top command shows that the time consumed is mainly __pv_queued_spin_lock_slowpath.

top shows: 
%Cpu0  : 18.7 us, 48.0 sy,  0.0 ni,  7.0 id,  0.0 wa,  0.0 hi, 26.3 si,  0.0 st
%Cpu1  : 24.3 us, 68.1 sy,  0.0 ni,  7.6 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu2  : 20.3 us, 71.0 sy,  0.0 ni,  8.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu3  : 22.6 us, 70.4 sy,  0.0 ni,  7.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st

perf top shows: 
  40.11%  [kernel]                                          [k] __pv_queued_spin_lock_slowpath                                                                       
  19.23%  [kernel]                                          [k] flush_sigqueue_mask                                                                                  
   3.01%  [kernel]                                          [k] do_sigaction

However, if I change the protocol to grpc, there is no such problem and the cpu occupancy is lower. 
http:
concurrency | latency | throughput
-- | -- | --
128 | 11.132 | 11603
256 | 15.007 | 16899.6
512 | 46.48 | 11013.4
1024 | 213.3 | 4795.4

grpc: 
concurrency | latency | throughput
-- | -- | --
128 | 11.654 | 10980.4
256 | 13.794 | 18545.6
512 | 23.732 | 21574.2
1024 | 35.963 | 28452

Why is there such a big performance difference between using http and grpc?

I'm using r20.10.

**Comment by jakepoz** [comment]
Try using the `binary=True` option in the HTTP API, you may be occupied parsing your input tensors from strings into floats.

**Comment by deadeyegoodwin** [comment]
Did the binary option resolve the issue? If not please reopen with additional data.
