### ISSUE TITLE
Serialization Error in readExternam:0 (Type mismatch)

### ISSUE THREAD

**Issue by bleedingfight** [triton-inference-server/server#2307]
*ENV*
- TensorRT-7.1.3.4
- NVIDIA driver:440.26
- GPU:Tesla T4
- CUDA 10.2 v10.2.89
- OS:centos7
- tritonversion:nvcr.io/nvidia/tritonserver-20.09-py3
When I use tritonserver to load plan model and inference,but something wrong,I don't know if it's a bug。I can use tensorrt（python version） read plan and inference with it and i can use trtexec do it.this is my trtexec command:
trtexec --loadEngine=/tmp/model.plan

outpu like this:
```
[12/01/2020-15:40:41] [I] total compute time:3.0028 s
&&&& PASSED TensorRT.trtexec # trtexec --load ENgine=/tmp/model.plan
```
when I use tritonserver do it,command : 
```
docker run --gpus=1 --rm -p9000:9000 -p9001:9001 -p9002:9002 -v/tmp/plan_model:/models bdb0cbe1c039 sh -c 'tritonserver --model-repository=/models'

```
output like this:
```
coreReadArchive.h(271) - Serialization Error in readExternal:0(Type mismatch)
E1201 07:37:35.929246 47 logging.cc:43] INVIDLID_STATE:std::exception
```

**Comment by chull434** [comment]
I would double check the versions match between the tensorrt you built the model with and the triton server you are running the model on

so if your triton server is 20.09, was the model built with the 20.09 tensorrt image?

I recently ran into something similar and just rebuilt the model with 20.11 and ran it on 20.11 and it worked fine then

**Comment by bleedingfight** [comment]
> match

Oh,I had'nt check it.I just know that tritonserver can use tensorrt backend to predict.but tritonserver has'nt tensorrt software(I hadn't find Tensorrt-_xxx directory just like my server's tensorrt).Tritonserver's cuda or tensorrt just some .so to be used to inference?Is it true that if there is no accident, the result of trtexec should be consistent with that of tritonserver?Can I use trtexec to verify that my model works in trtserver？

**Comment by bleedingfight** [comment]
Oh,I had'nt check it.I just know that tritonserver can use tensorrt backend to predict.but tritonserver has'nt tensorrt software(I hadn't find Tensorrt-_xxx directory just like my server's tensorrt).Tritonserver's cuda or tensorrt just some .so to be used to inference?Is it true that if there is no accident, the result of trtexec should be consistent with that of tritonserver?Can I use trtexec to verify that my model works in trtserver？

**Comment by bleedingfight** [comment]
@chull434  Oh,I had'nt check it.I just know that tritonserver can use tensorrt backend to predict.but tritonserver has'nt tensorrt software(I hadn't find Tensorrt-_xxx directory just like my server's tensorrt).Tritonserver's cuda or tensorrt just some .so to be used to inference?Is it true that if there is no accident, the result of trtexec should be consistent with that of tritonserver?Can I use trtexec to verify that my model works in trtserver？

**Comment by deadeyegoodwin** [comment]
TensorRT is not compatible so you have to make sure you use the same version of TensorRT to build the model as you use to run it. The versions are available in the release notes, https://docs.nvidia.com/deeplearning/triton-inference-server/release-notes/rel_20-11.html#rel_20-11. As @chull434 says, the easiest way to ensure this is to use the TensorRT and Triton containers at the same release to build and run you model.
