### ISSUE TITLE
'torch.dtype' object has no attribute 'type'

### ISSUE THREAD

**Issue by c464851257** [triton-inference-server/server#2308]
Dear all,
I tried to deploy the Pytorch model in the Inference server But I got the error when do the inference call to the server.
The error is:
File "/root/miniconda3/lib/python3.6/site-packages/tensorrtserver/api/__init__.py", line 666, in _prepare_request
    if input_value.dtype == np.object or input_value.dtype.type == np.bytes_:
AttributeError: 'torch.dtype' object has no attribute 'type'
the code is:
images = torch.from_numpy(images)
test_input = []
test_input.append(images)
result = self.ctx.run(
    { self.input_name[0] : test_input},
    { self.output_name[0] : (InferContext.ResultFormat.RAW)},1)

my torch version is 0.4.1

**Comment by CoderHam** [comment]
For starters torch 0.4.1 is very old. I'd consider updating to a newer / latest version.

**Comment by CoderHam** [comment]
@c464851257 the input 'test_input' should be a list of numpy arrays and not a list of torch tensors. 
```
images = torch.from_numpy(images)
```
The V1 API has been deprecated but the docs/examples are available in the older releases. https://github.com/triton-inference-server/server/blob/r20.05/src/clients/python/api_v1/library/__init__.py#L1525-L1532 explains that the "input" field should be a dictionary of the form. 
```
{'name': (np_array1, ...), ...}
```
