### ISSUE TITLE
Failed to finalize CUDA memory manager: CNMEM_STATUS_INVALID_ARGUMENT

### ISSUE THREAD

**Issue by speshowBUAA** [triton-inference-server/server#2311]
**Description**
We failed to run triton server on our Tesla M40. 

**Triton Information**
We use the triton container 20.03.1 and get the error log. Failed to run gpu.
E1203 05:19:54.453868 1 server.cc:163] Failed to finalize CUDA memory manager: CNMEM_STATUS_INVALID_ARGUMENT
I1203 05:19:54.472444 1 onnx_backend.cc:200] Creating instance retinaface_0_cpu on CPU using model.onnx

Here is our GPU info:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64.00    Driver Version: 440.64.00    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|   0  Tesla M40           On   | 00000000:00:08.0 Off |                  Off |
| N/A   33C    P0    62W / 250W |    109MiB / 12215MiB |      0%      Default |

**To Reproduce**
docker run --gpus all --rm -p8000:8000 -v /data/tritonserver/models:/models nvcr.io/nvidia/tritonserver:20.03.1-py3 tritonserver --model-repository=/models

**Comment by GuanLuo** [comment]
Please take a look here: https://github.com/triton-inference-server/server/issues/1246#issuecomment-606759282
