### ISSUE TITLE
Triton for JetPack does NOT support ONNX backend 

### ISSUE THREAD

**Issue by marcoBrighterAI** [triton-inference-server/server#2324]
**Is your feature request related to a problem? Please describe.**

Triton inference server for **JetPack** doesn’t support **ONNX backend** out of the box yet.

**Describe the solution you'd like**

Support ONNX inference in triton server for  **JetPack** so we can use triton to deploy ONNX model in the Jetson Xavier.

**Describe alternatives you've considered**

We've considered running ONNX models without triton. 

**Additional context**

We are already using triton for our cloud and on-premise deployments, and we would like it to keep it consistent for our edge deployments too.

**Comment by CoderHam** [comment]
@marcoBrighterAI thank you for showing interest in the ONNX Backend for the Triton JetPack build. We do plan on adding the same soon. I will update this issue when we do so.

**Comment by marcoBrighterAI** [comment]
@CoderHam Thank you for the fast reply. We look forward to having this feature.

**Comment by drcolula** [comment]
Is there a way to add manually the ONNX backend to the JetPack build, or should we wait until it is supported as a feature?

**Comment by GuanLuo** [comment]
You should be able to configure CMake to build Triton with ORT support, shouldn't be any difference in terms of build steps. But you should verify that ORT itself supports JetPack

**Comment by mfruhner** [comment]
Hello, I am very interested in running an ONNX Backend in Jetpack 4.5. Are there any news on this?

**Comment by dzier** [comment]
This issue is fixed in the 21.05 release.
