### ISSUE TITLE
Pull 20.11-py3-sdk, manifest unknown

### ISSUE THREAD

**Issue by Sn0flingan** [triton-inference-server/server#2330]
**Description**
I have followed the quick start guide and was able to run Triton successfully. However, when trying to pull the client side there was an error. 
`docker pull nvcr.io/nvidia/tritonserver:20.11-py3-sdk` 
results in:
`Error response from daemon: manifest for nvcr.io/nvidia/tritonserver:20.11-tf1-py3-sdk not found: manifest unknown: manifest unknown`

The similar command:
`docker pull nvcr.io/nvidia/tritonserver:20.11-py3`
does work.

**Triton Information**
I am using the container, r20.11. Also tested with r19.12 with same results.

**To Reproduce**
To reproduce run.
`docker pull nvcr.io/nvidia/tritonserver:20.11-py3`
I have reproduced the error on two computers, one running Ubuntu and one running Windows.

**Expected behaviour**
Expected a successful pull of the docker image.

**Comment by deadeyegoodwin** [comment]
the *-sdk container is not available until the 20.12 release. You likely read documentation from the master branch which is development documentation for upcoming release (in this case 20.12). You should look at the 20.11 documentation (https://github.com/triton-inference-server/server/tree/r20.11#documentation) where you will see that the container is called *-clientsdk in 20.11.
