### ISSUE TITLE
Add ability to choose which graph and signature_def to load on model load

### ISSUE THREAD

**Issue by raimondasl** [triton-inference-server/server#2332]
Motivation: Keras savedmodel save by default saves the training model and inference model into separate graphs. There are also other situations where single model has multiple graphs and signature definitions. 
It is useful for to indicate in Triton config file which graph and signature_def Triton should load and use.
 
This could be implemented via "tag:" and "signature_def:" keys in config.pbtxt file for model.

This issue is related to issue https://github.com/triton-inference-server/server/issues/2331 
As discussed with Triton team, issue https://github.com/triton-inference-server/server/issues/2331 may or may not supersede this issue, since this issue is simpler and may provide a simpler mechanism for Triton users that do not need runtime indication which signature_def to use.

As discussed with Triton team, this issue is somewhat high priority.

**Comment by jbkyang-nvi** [comment]
Hi @raimondasl , there exists a `tag` field in tensorflow [meta_graph.proto](https://github.com/tensorflow/tensorflow/blob/0729d162c09232daa3d5d68a7d09eb1b1e4db046/tensorflow/core/protobuf/meta_graph.proto#L56) and right now it only checks if the graph contains the tag [serve](https://github.com/tensorflow/tensorflow/blob/0729d162c09232daa3d5d68a7d09eb1b1e4db046/tensorflow/cc/saved_model/tag_constants.h#L28), by specifying the tag in the config.pbtxt, you mean to change the `tag_set` to more than just `serve`. Is this correct?

**Comment by raimondasl** [comment]
@jbkyang-nvi : From what I understand, in TensorFlow 2 mostly only tag serve is used. So the more important part of the request is to be able to choose which signature_def to use. E.g. If I run saved_model_cli on a bit anonymized but real TF2 model, I get this:

`saved_model_cli show --dir mymodel --tag_set serve
The given SavedModel MetaGraphDef contains SignatureDefs with the following keys:
SignatureDef key: "__saved_model_init_op"
SignatureDef key: "some_functionality"
SignatureDef key: "serve"
SignatureDef key: "serve_serialized"
SignatureDef key: "train"
SignatureDef key: "train_serialized"
`
We need the capability for Triton to load any one of these signature defs.
Supporting different tag_set is less important. To answer your question, if Triton can allow multiple tag_sets like you showed in the example, that would be great.
Does this answer your question?
Thanks.

**Comment by deadeyegoodwin** [comment]
Fixed by #2700. The fix will be in the 21.04 release and will be merged into main after the 21.04 release.
