### ISSUE TITLE
Support scalar input to Triton

### ISSUE THREAD

**Issue by raimondasl** [triton-inference-server/server#2333]
Scalar input to Triton has not been supported since it was possible to work around it for most cases.
In TensorFlow 2, there is a case that is not possible to work around.
TensorFlow 2 provides a save operation that can be invoked to save the model weights.
This operation does not have a default for its input. It requires a scalar string input (this input is a file name for where the weights should be saved). This operation cannot be used from Triton since Triton does not support scalar input. The operation also cannot be wrapped with single-dimension input since the operation is added automatically by TensorFlow and uses a placeholder input that cannot be assigned.

Please consider adding scalar input support to Triton.

Here are code snippets to maybe clarify the save op usage:

```
  def get_save_op_name(self, saved_model_dir):
        # the save op name has index n where n = total number of signature keys (a.k.a) exported functions
        # minus 1 for the special '__saved_model_init_op' op.

        tag_set='serve' # since TF2, other tag sets are no longer really used
        from tensorflow.python.tools import saved_model_utils
        meta_graph_def = saved_model_utils.get_meta_graph_def(saved_model_dir, tag_set)
        n = len(meta_graph_def.signature_def.keys())-1
        return f'StatefulPartitionedCall_{n}:0'

…
       self.save_op = graph.get_tensor_by_name(self.get_save_op_name(export_dir))

…
    def save(self):
        graph = self.session.graph
        saver_file_tensor = graph.get_tensor_by_name('saver_filename:0')
        self.session.run(self.save_op, feed_dict={saver_file_tensor: self.save_file_name})
        print('module saved')
        self.session.close()
```
The example is not Triton-ready but should provide info if Triton team has to look at the TensorFlow 2 models to see the op and its input.

**Comment by odivay** [comment]
For reference, the same request for scalar input was rejected not so long ago: https://github.com/triton-inference-server/server/issues/1360. 
Can you explain what led to the decision that scalar input would not be supported?

**Comment by dzier** [comment]
As with #1360, scalar inputs are still not supported in Triton, and due to SW architecture, it is not feature that can integrate without a significant effort. So at this time, there are no plans to support scalar inputs.

**Comment by pablodz** [comment]
still relevant :/
