### ISSUE TITLE
Option to not provide all inputs specified in config.pbtxt

### ISSUE THREAD

**Issue by raimondasl** [triton-inference-server/server#2334]
Motivation: Triton currently requires to provide all inputs even if there are multiple outputs specified in config.pbtxt some of which may not need all inputs. It would be more efficient for the client to be able to provide a subset of inputs needed for an output.
 
This could be implemented via parameter "strict_input" which would default to True/1 and require all inputs (as it is now), but could be set to False/0 which would disable Triton's checking that all inputs are provided.

This request may have lower priority if issue https://github.com/triton-inference-server/server/issues/2331 is implemented, since allowing multiple signature_defs during runtime would also make the input set different for each signature_def.

Overall, this is "nice to have" but lower priority request.

**Comment by dyastremsky** [comment]
Optional inputs are now supported. See [this QA model configuration](https://github.com/triton-inference-server/server/blob/main/qa/L0_optional_input/models/identity_2_float32/config.pbtxt) as an example of how to add the `optional` field.
