### ISSUE TITLE
[Kaldi] 8Khz Model " unexpected size for input tensor."

### ISSUE THREAD

**Issue by basicasicmatrix** [triton-inference-server/server#2337]
**Description**

I am trying to implement an 8Khz ASpIRE based model on Triton Kaldi backend. Audio samples appear to be in right shape, I have adjusted config.pbtxt as necessary, primarily:
  ```
  name: "WAV_DATA"
    data_type: TYPE_FP32
    dims: [ 4080 ]
 
```
Output error is " unexpected size for input tensor.", which I traced to kaldi-backend-utils.cc as "kInputSize" error, and added an additional error print to debug what the expected and actual values were, like so:

```
  if (total_content_byte_size != expected_byte_size) {
    std::cerr << "Expected: \"" << expected_byte_size
              << "\" Total: " << total_content_byte_size
              << std::endl;
    return kInputSize; 
```

This makes it clear that it is Expected: "17280" Received: "16320".

The question: has anyone successfully implemented an 8Khz model with Triton? Any further debug steps I can take?
If appropriate, I would be willing to offer a moderate bounty for a solution. 

**Triton Information**
What version of Triton are you using?
Container, 19.12

**Comment by kvishnivetsky** [comment]
@basicasicmatrix , could you be so pleasant and share a solution?
