### ISSUE TITLE
Is it possible to run Triton without starting a server?

### ISSUE THREAD

**Issue by mdable2** [triton-inference-server/server#2345]
**Is your feature request related to a problem? Please describe.**
I'm looking for a solution to run Tensorflow 2.0 models in SavedModel format in my C# application. I'm in the midst of writing a C++ program that utilizes triton-inference-server and then will call it from my C# application using the C++ dll I generate. My work needs to stay local (I cannot make external API calls) so I am hoping there is an easy way to port the functionality of triton-inference-server without needing to start a server. I'm also hoping this would make my inferencing a bit faster.

**Describe the solution you'd like**
A C++ solution that I can run inferences directly. 

Any thoughts/ideas?

**Comment by deadeyegoodwin** [comment]
Triton already has a C API, why not just call that from your C# application? https://github.com/triton-inference-server/server/blob/master/docs/inference_protocols.md#c-api

**Comment by mdable2** [comment]
I've tried looking that over and am confused on where to get started to use the C API. I've tried looking for more documentation/tutorials on using the C API and could not find any. Do you know of any additional resources?

What I am trying to accomplish is to have images loaded into memory in my C# application, call the dll, and then within the dll it would directly utilize the C API without the need for parsing command line arguments or setting up a server as the `simple.cc` example does.

**Comment by deadeyegoodwin** [comment]
If you have already found simple.cc then that shows what is provided by the API. There is no need to parse command-line options unless you want to. You can use the API to initialize Triton however you want. I don't know of any more resources. If you have a more specific question about the API please reopen.

**Comment by vigneshwaran** [comment]
How to compile and run simple.cc?
