### ISSUE TITLE
CPU memory usage details in metrics

### ISSUE THREAD

**Issue by gkumbhat** [triton-inference-server/server#2353]
**Is your feature request related to a problem? Please describe.**
Currently, triton server returns the GPU memory consumption per model. It would be really helpful if triton server can also return the amount of CPU memory consumed by the model. Since, model (specially tensorflow) can consume a large amounts of memory, it gets difficult to understand how many models can be loaded beforehand.

**Describe the solution you'd like**
Triton server returns CPU memory usage per model in `/metrics` endpoint

**Describe alternatives you've considered**
Alternatively, I have tried to explore model_analyzer etc for this purpose, but they all return GPU memory only.

**Comment by dzier** [comment]
Model Analyzer now has CPU metrics. Please revisit the model analyzer.
