### ISSUE TITLE
 docker pull failed from NGC

### ISSUE THREAD

**Issue by Johnson-yue** [triton-inference-server/server#2354]
Sorry， I can not access to NGC， so it is failed pull image from NGC

I can pull from docker hub, I pulled image is from wangshulei/tritonserver but it is 20.07 version not latest version

Would you provide a  docker hub images link ?

**Comment by deadeyegoodwin** [comment]
Triton container is only published on NGC. Why can you not access NGC?

**Comment by Johnson-yue** [comment]
@deadeyegoodwin  I do not know
