### ISSUE TITLE
Questions on building triton server

### ISSUE THREAD

**Issue by tianq01** [triton-inference-server/server#2355]
Hi Guys,
I have 2 questions on building triton server:
1)the standard docker image for building triton server.
https://github.com/triton-inference-server/server/blob/master/docs/build.md#building-triton-with-docker says 'The easiest way to build Triton is to use Docker'.  However we donot find a standard docker image(or docker file) for usage.
https://github.com/triton-inference-server/server/blob/master/Dockerfile.QA gives some hint:
_ARG BUILD_IMAGE=tritonserver_build_
but not sure where to get this image.
Could you point me where to get a standard docker image or dockerfile?

2)we like the python backend feature in 20.10, but the official docker image is based on CUDA 11 and other high version artifacts. currently we are still staying at CUDA 10.2. 
Is it OK to build 20.10 triton server based on CUDA 10.2?

thanks.

**Comment by deadeyegoodwin** [comment]
The build.py script described in the docs generates a dockerfile and uses it to build. The generated docker files can be found in --build-dir after the build. If you can update your host's CUDA version but not the NVIDIA Driver you may be able to take advantage of driver compatibility and keep using you older driver, see release notes: https://docs.nvidia.com/deeplearning/triton-inference-server/release-notes/rel_20-11.html#rel_20-11
