### ISSUE TITLE
Tensorflow Saved Model Format tensorflow-gpu==2.0.0 vs. tensorflow==2.3.0 

### ISSUE THREAD

**Issue by zerapp** [triton-inference-server/server#2356]
**Description**
I have a model that I export to the savedModel format using tensorflow==2.3.0.
Triton crashes with the following message as soon as the model is inferred. 
```
W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at partitioned_function_ops.cc:113 : Internal: Assigned device '/job:localhost/replica:0/task:0/device:GPU:1' does not have registered OpKernel support for _Arg
         [[{{node ner_char_input}}]]
```
ner_char_input is a UINT32 integer encoding that is given to an tf.keras.layers.Embedding and followed by a tf.keras.layers.Conv2D

If I export the exact same model with tensorflow-gpu==2.0.0 there is no such problem.
If I run the triton docker container without the --gpus there is no such problem even with tensorflow==2.3.0

**Triton Information**
I'm using the triton container from NGC in version 20.11 and 20.09 but the error already occurred in earlier version. 

**To Reproduce**
Create a model with tf.keras and use an tf.keras.layers.Embedding as input layer followed by a tf.keras.layers.Conv2D.
Use tensorflow>=2.1.0 to save the model to the savedModel format and deploy it to triton with gpu.

**Expected behavior**
I would except triton not to crash as it does without gpu

Thank you a lot

**Comment by deadeyegoodwin** [comment]
Are you enabling TF2 backend? https://github.com/triton-inference-server/tensorflow_backend#command-line-options

**Comment by zerapp** [comment]
@deadeyegoodwin: Very good point! I was not aware of this. I was already celebrating inside, as I thought this has to be the solution...
Unfortunately, this doesn't seem to change a lot:

Although I see it's using the tf-2 backend and also the soft-placement (I thought maybe it would shift the operation to the CPU if not working on GPU)
tensorflow | /opt/tritonserver/backends/tensorflow2/libtriton_tensorflow2.so | {"cmdline":{"allow-soft-placement":"True","version":"2"}} |

I still get:

2020-12-18 12:00:01.312780: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at partitioned_function_ops.cc:114 : Internal: Assigned device '/job:localhost/replica:0/task:0/device:GPU:0' does not have registered OpKernel support for _Arg
	 [[{{node ner_char_input}}]]


The saved_model_cli from tensorflow shows this:
The given SavedModel SignatureDef contains the following input(s):
  inputs['ner_char_input'] tensor_info:
      dtype: DT_UINT32
      shape: (-1, -1, -1)
      name: serving_default_ner_char_input:0
The given SavedModel SignatureDef contains the following output(s):
  outputs['box_output'] tensor_info:
      dtype: DT_FLOAT
      shape: (-1, -1, -1, 12, 5)
      name: StatefulPartitionedCall:0
  outputs['decoder_seg_output'] tensor_info:
      dtype: DT_FLOAT
      shape: (-1, -1, -1, 59)
      name: StatefulPartitionedCall:1
Method name is: tensorflow/serving/predict

Thanks a lot for your help!

**Comment by deadeyegoodwin** [comment]
Did you find any solution for this? Reopen if you have additional information.
