### ISSUE TITLE
TensorRT on Jetpack Triton Build

### ISSUE THREAD

**Issue by drcolula** [triton-inference-server/server#2357]
Does the Triton Jetpack release supports the TensorRT backend? In the backends directory I can only find TF 1 and 2

**Comment by deadeyegoodwin** [comment]
TensorRT is supported in jetson release. TensorRT backend has not yet been extracted from the core triton which is why it is not in the backends directory.

**Comment by drcolula** [comment]
The releases page shows this example for running Triton, does the backend-config and backend-directory parameters need to be modified to run TensorRT models? 
```
 tritonserver --model-repository=/path/to/model_repo --backend-directory=/path/to/tritonserver/backends \
         --backend-config=tensorflow,version=2
```

**Comment by CoderHam** [comment]
No you don't need to modify the backend config to run TRT models.
