### ISSUE TITLE
how to build the C++ client libraries on windows

### ISSUE THREAD

**Issue by chiyukunpeng** [triton-inference-server/server#2362]
**Description**
Hi, I have built the `triton server 20.08` on `Ubuntu18.04`.
```
I1222 01:21:56.147310 1 grpc_server.cc:357] Thread started for CommonHandler
I1222 01:21:56.147463 1 grpc_server.cc:3000] New request handler for ModelInferHandler, 1
I1222 01:21:56.147488 1 grpc_server.cc:2078] Thread started for ModelInferHandler
I1222 01:21:56.147624 1 grpc_server.cc:3345] New request handler for ModelStreamInferHandler, 3
I1222 01:21:56.147668 1 grpc_server.cc:2078] Thread started for ModelStreamInferHandler
I1222 01:21:56.147686 1 grpc_server.cc:3897] Started GRPCInferenceService at 0.0.0.0:8001
I1222 01:21:56.148193 1 http_server.cc:2679] Started HTTPService at 0.0.0.0:8000
I1222 01:21:56.190012 1 http_server.cc:2698] Started Metrics Service at 0.0.0.0:8002
```
Now, I want to build the C++ client libraries on windows. I find the docs [client_libraries.md](https://github.com/triton-inference-server/server/blob/master/docs/client_libraries.md). Can it only be built with `CMake 3.18.4`?

Also, I will infer videos with `CUDA`. Can [image_client.cc](https://github.com/triton-inference-server/server/blob/master/src/clients/c%2B%2B/examples/image_client.cc) make it?

**Comment by deadeyegoodwin** [comment]
What version of cmake do you want to use? Did the build fail with that version? Is it a problem for you to install a more recent version of cmake? kitware provides several easy ways to update cmake.
image_client.cc is an example and only handles individual images. Triton does not provide any video processing examples.
