### ISSUE TITLE
fail to use perf_client

### ISSUE THREAD

**Issue by XingBin111** [triton-inference-server/server#2365]
**Description**

I deployed an ensemble model on triton, and sending requests locally can run normally, but when I use perf_client to test performance, I get an error.

`$ perf_client -m detection --percentile=95   `

> *** Measurement Settings ***
  Batch size: 1
  Measurement window: 5000 msec
  Using synchronous calls for inference
  Stabilizing using p95 latency

> Request concurrency: 1
Failed to maintain requested inference load. Worker thread(s) failed to generate concurrent requests.
Thread [0] had error: in ensemble 'detection', 2 root error(s) found.
  (0) Invalid argument: assertion failed: [Unable to decode bytes as JPEG, PNG, GIF, or BMP]
	 [[{{node image_decoder/decode_image/cond_jpeg/cond_png/cond_gif/Assert_1/Assert}}]]
	 [[GroupCrossDeviceControlEdges_0/image_resize/resize_image_with_pad/pad_to_bounding_box/control_dependency/_144]]
  (1) Invalid argument: assertion failed: [Unable to decode bytes as JPEG, PNG, GIF, or BMP]
	 [[{{node image_decoder/decode_image/cond_jpeg/cond_png/cond_gif/Assert_1/Assert}}]]
0 successful operations.
0 derived errors ignored

Here is my config.protxt:

`name: "detection"
platform: "ensemble"
max_batch_size: 0
input [
  {
    name: "raw_image"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]
output [
  {
    name: "score"
    data_type: TYPE_FP32
    dims: [ 1, 100 ]
  },
  {
    name: "category"
    data_type: TYPE_INT32
    dims: [ 1, 100 ]
  },
  {
    name: "bbox"
    data_type: TYPE_FP32
    dims: [ 1, 100, 4 ]
  }
]
ensemble_scheduling {
  step [
    {
      model_name: "detection-preprocess"
      model_version: 1
      input_map {
        key: "raw_image"
        value: "raw_image"
      }
      output_map {
        key: "process_img"
        value: "process_img"
      }
      output_map {
        key: "affine_trans_mat"
        value: "affine_trans_mat"
      }
    },
    {
      model_name: "detection-network"
      model_version: 1
      input_map {
        key: "process_img"
        value: "process_img"
      }
      output_map {
        key: "heatmap"
        value: "heatmap"
      }
      output_map {
        key: "bbox_wh"
        value: "bbox_wh"
      }
      output_map {
        key: "center_shift"
        value: "center_shift"
      }
    },
    {
      model_name: "detection-postprocess"
      model_version: 1
      input_map {
        key: "heatmap"
        value: "heatmap"
      }
      input_map {
        key: "bbox_wh"
        value: "bbox_wh"
      }
      input_map {
        key: "center_shift"
        value: "center_shift"
      }
      input_map {
        key: "affine_trans_mat"
        value: "affine_trans_mat"
      }
      output_map {
        key: "score"
        value: "score"
      }
      output_map {
        key: "category"
        value: "category"
      }
      output_map {
        key: "bbox"
        value: "bbox"
      }
    }
  ]
}`

**Comment by deadeyegoodwin** [comment]
Does your model expect images as input? By default perf_client sends random dataand that data mail fail to decode as an image. You can try using the -z flag to send all zeros instead, or you can look in the docs for information on how to have perf_analyzer (aka perf_client) send explicit data.
