### ISSUE TITLE
Check failed: size >= 0 (-1655719932 vs. 0) 

### ISSUE THREAD

**Issue by CColten** [triton-inference-server/server#2368]
**Description**
[tensorflow/core/framework/tensor_shape.cc:324] Check failed: size >= 0 (-1655719932 vs. 0) | Elapsed Time: 0:00:00 ETA: --:--:--2020-03-19 18:16:48.267327: F tensorflow/core/framework/tensor_shape.cc:324] Check failed: size >= 0 (-1655719932 vs. 0)

**Triton Information**
in 19.10, it's OK .
in  20.07,  wrong. 

**To Reproduce**
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
tf-model.

max_batch_size: 8
input [
   {
    name: "image_tensor"
    data_tpe: TYPE_UINT8
    format: FORMAT_NHWC
    dims: [1280,1280,3]
   }
]

output [
   {
      name: "detection_scores"
      data_tpe: TYPE_FP32
      dims: [3]
   }
]

output [
   {
      name: "detection_boxes"
      data_tpe: TYPE_FP32
      dims: [3, 4]
   }
]

**Comment by deadeyegoodwin** [comment]
That error is coming from within TF. What TF model are you using? What version of TF was used to generate/train the model?

**Comment by CColten** [comment]
> That error is coming from within TF. What TF model are you using? What version of TF was used to generate/train the model?

You are right.  The error is coming from TF with different vision.

the error is solved. 
the model was trained in tf 1.15, but frozen the model in  tf  1.13.   When froze it  in  tf 1.15,  everything is ok.
