### ISSUE TITLE
NVTX error occurs when TRITON_ENABLE_CAFFE2 and TRITON_ENABLE_PYTORCH is OFF

### ISSUE THREAD

**Issue by marsmiao** [triton-inference-server/server#2375]
**Description**
NVTX error occurs when TRITON_ENABLE_CAFFE2 or TRITON_ENABLE_PYTORCH is OFF.

**Triton Information**
What version of Triton are you using?
r20.10

Are you using the Triton container or did you build it yourself?
use the official docker image

**To Reproduce**
just disable the tritonserver to link to libtorch_cuda.so, which linked to libnvToolsExt.so, and recompile the tritonserver, error like "E0103 08:58:20.908233 24636 nvtx.h:42] Unable to start NVTX range 'DynamicBatchScheduler '" will appear.

**Expected behavior**
add a general way to link to NVTX, not depend on libtorch_cuda.so

**Comment by marsmiao** [comment]
As far as I'm concerned, nvtx3 is a header-only library, while previous versions are linked with libnvToolsExt.so, so maybe there are two different versions of nvtx running at the same time when triton is linked with torch_cuda.so.

**Comment by CoderHam** [comment]
Please re-try the same with the latest release i.e. 20.12. Please note that Caffe2 is deprecated.  
Additionally run 
`find / -name libnvToolsExt.so` inside your container to confirm that the library is present and available. If the library is missing ensure you are launching the docker container with the correct arguments and that it has access to the GPU.

**Comment by marsmiao** [comment]
> Please re-try the same with the latest release i.e. 20.12. Please note that Caffe2 is deprecated.
> Additionally run
> `find / -name libnvToolsExt.so` inside your container to confirm that the library is present and available. If the library is missing ensure you are launching the docker container with the correct arguments and that it has access to the GPU.

Thanks a lot, I will try it later and give updates. By the way, if TRITON_ENABLE_PYTORCH is enabled, libtorch_cuda.so will also be linked to libnvToolsExt.so either. So maybe the problem still remains.

**Comment by deadeyegoodwin** [comment]
Closing. Please reopen with any updates.
