### ISSUE TITLE
Question: Kubernetes Deployment with stateful models

### ISSUE THREAD

**Issue by tarrencev** [triton-inference-server/server#2376]
I'm interested in running a kubernetes deployment with multiple replicas. I would like to run inference with stateful models. Is this possible with the current helm chart? Do i need a way to ensure sequential requests are routed to the same instance?

@deadeyegoodwin since you are the author :)

**Comment by deadeyegoodwin** [comment]
You will need to use the GRPC streaming API as is shown in the sequence examples. If you use a compliant load balancer then requests on the same stream should be routed the same. I believe envoy, nginx, etc. all handle this correctly.
