### ISSUE TITLE
Getting issue while load FP16 retinaface model

### ISSUE THREAD

**Issue by alphapibeta** [triton-inference-server/server#2377]
Facing issue while loading retinaface from [tensorrtx](https://github.com/wang-xinyu/tensorrtx) using FP16 precision, model was generated successfully and its working without any errors with tensorrt Inference code. But while loading into Triton-inference -server it's giving the following error: 

```E0104 10:59:53.411466 1 model_repository_manager.cc:899] failed to load 'retinaface' version 1: Invalid argument: unexpected datatype TYPE_FP32 for input 'data', expecting TYPE_FP16 for retinaface_0_0_gpu0```

**It works with FP32 model, but not FP16**

Environment :
GPU= T4,
Tritonserver 20.09 container.

**config.pbtxt**

name: "retina"
platform: "tensorrt_plan"
max_batch_size: 1
dynamic_batching {
  preferred_batch_size: [1]
  max_queue_delay_microseconds: 100
}
input [
  {
    name: "data"
    data_type: TYPE_FP16
    format: FORMAT_NCHW
    dims: [ 3, 480, 640 ]
  }
]
output [
  {
    name: "prob"
    data_type: TYPE_FP16
    dims: [189001,1,1]
    
  }
]
instance_group [
  {
    count:1
    kind: KIND_GPU
  }
]

**Comment by Burachonok** [comment]
Hi. You need use TYPE_FP32 for all inputs and outputs. Your trt engine must be convert in float16.

**Comment by alphapibeta** [comment]
Thanks, it worked.

**Comment by kla240** [comment]
@alphapibeta , can you share how you finally got retinaface from tensorrtx to work with Triton?   I am stuck with trying this... "prob" output is zeros... did you have to build a custom backend, or could you use the engine directly with decodeplugin.so in triton tensorrt backend?

**Comment by austinmw** [comment]
@Burachonok Hi, do you know if it's possible to use TYPE_FP16 as input?

**Comment by nouxf** [comment]
> To be able use `TYPE_FP16` as data type for input and output, use `--inputIOFormats` and `--outputIOFormats` when parsing the model from ONNX. For example: `trtexec --onnx=model.onnx --saveEngine=model.plan --fp16 --inputIOFormats=fp16:chw --outputIOFormats=fp16:chw`

Tks  bro! It really helped.
