### ISSUE TITLE
Onnx batchsize greater than 1

### ISSUE THREAD

**Issue by alphapibeta** [triton-inference-server/server#2387]
Hello, converted a [mxnet](https://github.com/deepinsight/insightface) model to onnx format with batchsize=16, model was generated successfully. Also, generated the model with batchsize=1, batchsize=1 works without any issue but when trying with a batch size=16 getting errors.

<h1>The config.pbtxt for batchsize=1</h1>

name: "arcface"
platform: "onnxruntime_onnx"
max_batch_size: 0
input [
  {
    name: "data"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [3, 112, 112 ]
    reshape: { shape: [1,3,112,112] }
  }
]
output [
  {
    name: "fc1"
    data_type: TYPE_FP32
    dims: [1,512]
    
  }
]
instance_group [
  {
    count:1
    kind: KIND_GPU
  }
]
<h1>The above config load fine and works</h1>

<h1>The config.pbtxt for batchsize=16</h1>

name: "arcface"
platform: "onnxruntime_onnx"
max_batch_size: 16
input [
  {
    name: "data"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [3, 112, 112 ]
    reshape: { shape: [1,3,112,112] }
  }
]
output [
  {
    name: "fc1"
    data_type: TYPE_FP32
    dims: [1,512]
    
  }
]
instance_group [
  {
    count:1
    kind: KIND_GPU
  }
]

```
failed to load 'arcface' version 1: Invalid argument: model 'arcface', tensor 'data': 
for the model to support batching the shape should have at least 1 dimension and the first dimension must be -1; but shape expected by the model is [16,3,112,112]

```

name: "arcface"
platform: "onnxruntime_onnx"
max_batch_size: 16

input [
  {
    name: "data"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [3, 112, 112 ]
    reshape: { shape: [16,3,112,112] }
  }
]
output [
  {
    name: "fc1"
    data_type: TYPE_FP32
    dims: [16,512]
    
  }
]
instance_group [
  {
    count:1
    kind: KIND_GPU
  }
]

```model input has different size for dims and reshape for arcface```

**Comment by GuanLuo** [comment]
The error message shows that the batch size 16 model you generated has shape [16, 3,112,112], the batch dimension is not -1 means the model doesn't support dynamic batch size, for example, it does not accept input of shape [4, 3, 112, 112]. So what you can do is to set `max_batch_size: 0` to indicate the model doesn't support batching and use [16, 3, 112, 112] as your input shape. Another way is to modify your generation script so that the generated model actually supports dynamic batch size.

**Comment by CPFelix** [comment]
@GuanLuo I follow your device and set densenet_onnx config.pbtxt as 
"
name: "densenet_onnx"
platform: "onnxruntime_onnx"
max_batch_size : 0
input [
  {
    name: "data_0"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 1, 3, 224, 224 ]
  }
]
output [
  {
    name: "fc6_1"
    data_type: TYPE_FP32
    dims: [ 1, 1000, 1, 1 ]
    label_filename: "densenet_labels.txt"
  }
]
"
When load the model get the error:
"
E0830 03:44:40.749103 1 model_repository_manager.cc:1916] Poll failed for model directory 'densenet_onnx': model input NHWC/NCHW require 3 dims for densenet_onnx
"
And I open the model using netron and confirm the input shape of the model is [1, 3, 224, 224].

**Comment by GuanLuo** [comment]
@CPFelix Please remove `format: FORMAT_NCHW` from the input field
