### ISSUE TITLE
Cannot run Pytorch and Tensorflow models consecutively on a single GPU

### ISSUE THREAD

**Issue by Debangshu132** [triton-inference-server/server#2388]
**Description**
Just after the server starts if tensorflow model runs first then subsequently pytorch is run, thr pytorch goes OOM, and same when pytorch model is run first then tensorflow model.

**Triton Information**
What version of Triton are you using?
I am using version 20.10

Are you using the Triton container or did you build it yourself?
Triton container

**To Reproduce**
Steps to reproduce the behavior.
Use version 20.10 and load a pytorch model and a tensorflow model 

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
Pytorch torchscript and tensorflow savedmmodel model

**Expected behavior**
Both the models should work fine.

**Comment by deadeyegoodwin** [comment]
Frameworks dynamically allocate GPU memory when requests are processed and may hold onto that memory for subsequent inference requests. GPU memory is a shared resource across all models. It is likely that your 2 models are just too big to share the GPU. You can load and run one at a time and use nvidia-smi to see how much each is using. You should also look into model analyzer to help you understand GPU memory usage: https://github.com/triton-inference-server/model_analyzer

**Comment by Debangshu132** [comment]
Hi, thanks for answering. I thought triton server somehow frees the memory from the framework just after the inference is completed. Can this be added in a future release?

**Comment by deadeyegoodwin** [comment]
Triton relies on the framework (TF, PyT, etc.) libraries to execute the models and as part of that each framework has its own way of allocating and managing memory. Triton does not provide a universal allocator that all frameworks subscribe to.
