### ISSUE TITLE
Optimal/Suggested way of handling image requests for optimizing throughput

### ISSUE THREAD

**Issue by gaborvecsei** [triton-inference-server/server#2389]
# Problem

Let's consider a Tensorflow model which can classify images. The input of the model is `[None, 512, 512, 3]`.  

As I know it is best to create the **POST inference request where we have a payload of base64 encoded image or the raw bytes. It is not optimal to send the "raw" uint8/float32 image data.**

What is the best way to serve such model if we would like to deploy it to reduce network latency and increase the overall throughput?

# What was tried

We can create a "servable optimized" model, which accepts byte inputs with:

```python
class Servable(tf.Module):
    def __init__(self, model):
        super().__init__()
        self.model = model # This is the original TF model

    @tf.function
    def __call__(self, image_bytes):
        x = tf.map_fn(tf.io.decode_image, image_bytes, fn_output_signature=tf.uint8)
        return self.model(x)
```

When this is saved as a savedmodel, we can serve it:

```python
model = Servable()
input_tensor_spec = tf.TensorSpec([None], tf.string, name='input_0')
model_call_fn = model.__call__.get_concrete_function(input_tensor_spec)
tf.saved_model.save(model, SAVE_DIR, signatures=model_call_fn)
```

We can deploy this model with TritonServing, but for the first request we will get an error like:

```
  (1) Invalid argument: 2 root error(s) found.
  (0) Invalid argument: During Variant Host->Device Copy: non-DMA-copy attempted of tensor type: string
  (1) Invalid argument: During Variant Host->Device Copy: non-DMA-copy attempted of tensor type: string
0 successful operations.
0 derived errors ignored.
        [[{{node map/TensorArrayUnstack/TensorListFromTensor}}]]
        [[StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/map/while/LoopCond/_508/_677]]
```

When we remove the `tf.map_fn(...)` and only handle the first item in the input batch with `tf.io.decode_image`, then it works. So the `map_fn()` is not supported.

From here comes the question, **how should we handle image inputs?** Which is the "fastest" way with Triton Serving? (The above showed example works with Tensorflow Serving)

**Comment by gaborvecsei** [comment]
We can "force" ✅ the jpeg decode to happen on the CPU, and it works that way without errors (I hope I can post performance numbers later). ❓ But the question still stands, what is your view, how should we deal with image inputs ❓

**Comment by deadeyegoodwin** [comment]
If you want to send the image as input and have it decoded on the server, then you can use an ensemble that pipelines an image decoder with the model. An example is given here: https://github.com/triton-inference-server/dali_backend/tree/main/docs/examples/inception_ensemble#inceptionv3-inference-using-dali

**Comment by gaborvecsei** [comment]
@deadeyegoodwin Thank your for the quick response!
