### ISSUE TITLE
PIL module not found

### ISSUE THREAD

**Issue by sourdurian** [triton-inference-server/server#2392]
Good day everyone,

I've went to stackoverflow to ask but nobody seems to know. I've been on google and stackoverflow but i cant find any answers so as a last resort i'm here. I'm actually having problems with the docs because it seems a little strange to me. 

**Triton Information**
I am server 20.08 

**Steps To Reproduce**
1. `docker pull nvcr.io/nvidia/tritonserver:20.08-py3`
2. `cd docs/examples`
3. `./fetch_models.sh`
4. `docker run --rm -p8000:8000 -p8001:8001 -p8002:8002 -v/Users/a/server/docs/examples/model_repository:/models nvcr.io/nvidia/tritonserver:20.08-py3 tritonserver --model-repository=/models`
5. `curl -v localhost:8000/v2/health/ready `

<img width="1440" alt="Screenshot 2021-01-08 at 11 30 14 AM" src="https://user-images.githubusercontent.com/57052760/103971218-ee558300-51a4-11eb-927c-718a9f2aa999.png">

Everything worked fine until here. Quoting the docs, "To use image_client (or image_client.py) you must first have a running Triton that is serving one or more image classification models. The image_client application requires that the model have a single image input and produce a single classification output." Which was what i did in step 4. Correct me if I'm wrong

Next in a separate CLI, i tried this to get inference and it returned me PIL module not found: 

`cd server/src/clients/python/examples`
`python image_client.py -m inception_graphdef -s INCEPTION qa/images/mug.jpg` 

Am i missing a step somewhere? Any help is greatly appreciated because I've tried looking everywhere but i couldnt find any answers. Thanks 

On a side note: 

I have tried a separate part of the tutorial which is: 
1. docker pull nvcr.io/nvidia/tritonserver:20.08-py3-clientsdk
2. docker run -it --rm --net=host nvcr.io/nvidia/tritonserver:20.08-py3-clientsdk
3./workspace/install/bin/image_client -m densenet_onnx -c 3 -s INCEPTION /workspace/images/mug.jpg

And it works

**Comment by deadeyegoodwin** [comment]
It looks like you are following the quickstart. In that you need to run the image_client.py from within the *-sdk container as that has the appropriate python libraries installed: https://github.com/triton-inference-server/server/blob/r20.12/docs/quickstart.md#getting-the-client-examples and https://github.com/triton-inference-server/server/blob/r20.12/docs/quickstart.md#running-the-image-classification-example.

If you want to run the examples directly from a host system, you must manually install the libraries. Options to do that are shown here: https://github.com/triton-inference-server/server/blob/r20.12/docs/client_libraries.md#getting-the-client-libraries
