### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [triton-inference-server/server#2397]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [CudaSharedMemoryReleaseBuffer](https://github.com/triton-inference-server/server/blob/b5a5541d3252a9fb235eeea9c156eb0d2f8ab883/src/clients/python/library/tritonclient/utils/cuda_shared_memory/cuda_shared_memory.cc#L180 "CudaSharedMemoryReleaseBuffer function")
- [GrpcClient](https://github.com/triton-inference-server/server/blob/c8997383e883b87f6fdb1765d23f46b54a7715dd/src/clients/c%2B%2B/perf_analyzer/client_backend/tensorflow_serving/grpc_client.cc#L685 "Destructor for GrpcClient")

**Comment by deadeyegoodwin** [comment]
Thanks for the note. Can you please submit a PR with the fixes.
