### ISSUE TITLE
Triton Server Support for Jetson Nano

### ISSUE THREAD

**Issue by Darshcg** [triton-inference-server/server#2400]
Hi Nvidia-Team,
I want to serve our custom Models(TRT) on Jetson Nano,
I have served the models using Triton Server in my Linux based Laptop(using tritonserver:20.08 container), but I want to serve the models on Jetson nano.
Whether the Triton Serving supported on Jetson Nano(using the Container)?
If yes, Can I get the reference of it? And also which version will support both Pytorch and Onnxruntime backend?

Regards,
Darshan

**Comment by deadeyegoodwin** [comment]
A jetson build is included in the release. Others have used it on Nano. Have you tried it? https://github.com/triton-inference-server/server/releases

**Comment by Darshcg** [comment]
Hi @deadeyegoodwin,
Thanks for your reply.
Does it support both pytorch and ONNXruntime backend?

Thanks
