### ISSUE TITLE
ONNX Backend Support for Jetpack

### ISSUE THREAD

**Issue by Darshcg** [triton-inference-server/server#2401]
Hi Nvidia Team,

I have a custom ONNX model, which I need to serve on Jetson Nano using Triton Serving. Does the Latest release(https://github.com/triton-inference-server/server/releases) support for ONNX Backend?

Thanks

**Comment by CoderHam** [comment]
Triton does not currently support Onnx backend on Jetson.

**Comment by Darshcg** [comment]
Thanks @CoderHam for your Quick Reply. Does the Latest Release support for Pytorch Backend on Jetson?

**Comment by CoderHam** [comment]
@Darshcg Onnx and PyTorch are the two backends that are currently not supported on Jetson. We do not have a confirmed timeline on when it will be available yet.

**Comment by Darshcg** [comment]
Hi @CoderHam,
Thank you for your reply. Will the Latest release support Tensorrt Backend on Jetson Nano?

**Comment by deadeyegoodwin** [comment]
Yes, TensorRT, TensorFlow and custom backends are supported by current and future jetson releases. Keep an on the release page and we will announce with additional backends become supported.
