### ISSUE TITLE
Startup error while loading shared libraries

### ISSUE THREAD

**Issue by belsakn** [triton-inference-server/server#2402]
**Description**
While running the latest Triton Inference Server 2.6.0  container i'm getting this error:
```
tritonserver: error while loading shared libraries: libnvrtc.so.11.1: cannot open shared object file: No such file or directory
```

**Triton Information**
Running the latest Triton Inference Server 2.6.0 

Are you using the Triton container or did you build it yourself?
Container

**To Reproduce**
Run the container, no models needed

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**
More specific error description

**Comment by CoderHam** [comment]
Do you have cuda 11.1 installed on the host machine where the docker is running? If not which version of cuda are you running? Does the docker container have access to the GPU?

**Comment by belsakn** [comment]
CUDA 11.2
Yes the container has access to the GPU.

**Comment by belsakn** [comment]
@CoderHam any suggestions?

**Comment by deadeyegoodwin** [comment]
What is your pod/container spec? How are you launching Triton? We have a simple example here: https://github.com/triton-inference-server/server/blob/master/deploy/single_server/templates/deployment.yaml#L50

**Comment by belsakn** [comment]
@deadeyegoodwin i launch it with the manifest that you provided. The sem spec that I use works with 2.5.0 container.

**Comment by CoderHam** [comment]
> @CoderHam any suggestions?
> 
> Also i'm trying to run it in Kubernetes, if I run it in docker it works.

I think the issue is because you're using cuda 11.2 and not 11.1. Tritonserver is looking for libnvrtc.so.11.1 instead of libnvrtc.so.11.2

**Comment by belsakn** [comment]
@CoderHam are there any docs on how to check the cuda version?

**Comment by deadeyegoodwin** [comment]
On your host system you can run "nvidia-smi" and it will report the CUDA version. To determine the version required for Triton you can check the release notes: https://docs.nvidia.com/deeplearning/triton-inference-server/release-notes/index.html and specifically the support matrix: https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html
