### ISSUE TITLE
A make error here that complains that 'not finding grpc_service_pb2.py'

### ISSUE THREAD

**Issue by gpudavid** [triton-inference-server/server#2408]
**Description**
A make error here that complains that 'not finding grpc_service_pb2.py'

**Triton Information**
What version of Triton are you using? r20.12

Are you using the Triton container or did you build it yourself?
build myself in a build.py built container. 

https://github.com/triton-inference-server/server/blob/2593799fa3cf510eb9b95b2d7c55ff9b534eec78/src/clients/python/library/build_wheel.sh#L73-L77

Where is the 'grpc_service_pb2.py'? I met a make error here that complains that 'not finding grpc_service_pb2.py'. I noticed that the file is in 'src/clients/python/library/tritongrpcclient'. Need here to be 'cp ./tritongrpcclient/model_config_pb2.py' ?

I made this modification and passed this error to another. 'tritonclient/utils/libcshm.so': No such file or directory'. Seems the modification was right.

**Comment by gpudavid** [comment]
I noticed that I need a manual `make` in 'python/library' to make the 'tritonclient/utils/libcshm.so' and passed the second error. So it seems a mismatch of files moving in different development phases.

**Comment by deadeyegoodwin** [comment]
You are trying to build the grpc client libraries? Are you following the build instructions? https://github.com/triton-inference-server/server/blob/master/docs/client_libraries.md#build-using-docker

**Comment by gpudavid** [comment]
I use build.py to build r20.12 and get very thing working. And then I am trying to build the source code by hand. So I start a container based on the 'tritonserver_buildbase' and in that I am trying to repeat the cmake commands that the build.py emitted to the container. By doing this, I am trying to get an backend development environment.

The steps of mine. I login to the container, git clone triton-inference-server/server and then run a build.py as following, which is is a repeat of build.py emitted to the container:
```
./build.py --verbose --build-dir=/tmp/citritonbuild2 --enable-logging --enable-stats --enable-tracing --enable-metrics --enable-gpu-metrics --enable-gpu --filesystem=gcs --filesystem=s3 --endpoint=http --endpoint=grpc --repo-tag=common:r20.12 --repo-tag=core:r20.12 --repo-tag=backend:r20.12 --backend=custom --backend=ensemble --backend=tensorrt --backend=identity:r20.12 --backend=repeat:r20.12 --backend=square:r20.12 --backend=onnxruntime:r20.12 --backend=pytorch:r20.12 --backend=tensorflow1:r20.12 --backend=python:r20.12 --backend=dali:r20.12 --no-container-build --version 2.6.0 --container-version 20.12 --upstream-container-version 20.12  --install-dir /tmp/tritonbuild2/install
```
This build was succeed.

Then I would like to add dig more to get the cmake programming env. So I do this in the build directory:

```
cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/tmp/citritonbuild2/tritonserver/install -DTRITON_COMMON_REPO_TAG:STRING=r20.12 -DTRITON_CORE_REPO_TAG:STRING=r20.12 -DTRITON_BACKEND_REPO_TAG:STRING=r20.12 -DTRITON_THIRD_PARTY_REPO_TAG:STRING=main -DTRITON_ENABLE_LOGGING:BOOL=ON -DTRITON_ENABLE_STATS:BOOL=ON -DTRITON_ENABLE_METRICS:BOOL=ON -DTRITON_ENABLE_METRICS_GPU:BOOL=ON -DTRITON_ENABLE_TRACING:BOOL=ON -DTRITON_ENABLE_GPU:BOOL=ON -DTRITON_MIN_COMPUTE_CAPABILITY=6.0 -DTRITON_ENABLE_GRPC:BOOL=ON -DTRITON_ENABLE_HTTP:BOOL=ON -DTRITON_ENABLE_GCS:BOOL=ON -DTRITON_ENABLE_S3:BOOL=ON -DTRITON_ENABLE_AZURE_STORAGE:BOOL=OFF -DTRITON_ENABLE_TENSORFLOW=ON -DTRITON_ENABLE_TENSORRT=ON -DTRITON_ENABLE_CUSTOM=ON -DTRITON_ENABLE_ENSEMBLE=ON -DTRITON_ENABLE_ONNXRUNTIME=ON -DTRITON_ENABLE_PYTHON=ON -DTRITON_ENABLE_DALI=ON -DTRITON_ENABLE_PYTORCH=ON -DTRITON_EXTRA_LIB_PATHS=/opt/tritonserver/lib /work/triton2/server/build

make
```

So in this cmake and make, it seems encounter the errors above. The `cmake` options was copied from build.py generation.

**Comment by gpudavid** [comment]
Or, direct to my requirements. What is the best way to get a working programming environment to try Triton server and backend.

**Comment by gpudavid** [comment]
I think I understand the error. I was holding a docker image for building server. I should `make server` while I was doing `make`, which invoked `make client`.
