### ISSUE TITLE
Question: Changing GRPC compression options

### ISSUE THREAD

**Issue by mortylin2019** [triton-inference-server/server#2409]
I am trying to config GRPC to use compression, but I can't find a simple code change or option that I can achieve that.
Can anyone suggest how can I do that?

Similar issue: #2021

**Comment by deadeyegoodwin** [comment]
We are still planning on exposing the GRPC compression options in the client but we have not implemented it yet. We don't have any timeline to provide right now.

**Comment by deadeyegoodwin** [comment]
Duplicate of #2021
