### ISSUE TITLE
"unexpected shape for input" Error for a Model with Dynamic Input

### ISSUE THREAD

**Issue by doruksonmez** [triton-inference-server/server#2411]
**Description**
I have specified the input layer's dims within the config.pbtxt as follows. I got he layer names and their dimensions using the ```save_model_cli show``` cli tool. It says: 

> if a model requires a 2-dimensional input tensor where the first dimension must be size 4 but the second dimension can be any size, the model configuration for that input would include dims: [ 4, -1 ]. Triton would then accept inference requests where that input tensor's second dimension was any value greater-or-equal-to 0.

However, when I feed a [320,320,3] shaped image to my network using the sample Python client, I get the following error.

`inference failed: unexpected shape for input 'input_tensor' for model 'ssd_trt'. Expected [1,-1,-1,3], got [320,320,3]
`

Here is my model config file for the Triton. The server starts without any errors or warnings. In addition, I can also use the same model with TensorFlow Serving without any problem. 

**Triton Information**
I am using the **nvcr.io/nvidia/tritonserver:20.12-py3-sdk** container from NGC.

**To Reproduce**
Steps to reproduce the behavior.

I am using Tensorflow SavedModel from Tensorflow Object Detection API 2.0.

```
  platform: "tensorflow_savedmodel"
  input [
    {
      name: "input_tensor"
      data_type: TYPE_UINT8
      dims: [ 1,-1,-1,3 ]
    }
  ]
  output [
    {
      name: "detection_boxes"
      data_type: TYPE_FP32
      dims: [ 1,-1,-1 ]
    },
    {
      name: "detection_classes"
      data_type: TYPE_FP32
      dims: [ 1,-1 ]
    },
    {
      name: "detection_scores"
      data_type: TYPE_FP32
      dims: [ 1,-1 ]
    }
  ]
```

**Expected behavior**
I think that it should have handled the different shapes for the input image since it is specified as -1 under the `dimensions`.

**Comment by deadeyegoodwin** [comment]
I think the error is clear. Your model configuration file says that "input_tensor" must have shape [ 1, -1, -1, 3 ] but you sent [ 320, 320, 3 ]. The 320's are not the problem, the problem is that 4 dimension tensor is required and you sent 3 dimensional. Try sending a tensor with shape [ 1, 320, 320, 3 ].
