### ISSUE TITLE
Linker error when torch installed in Python backend

### ISSUE THREAD

**Issue by francescoclarifai** [triton-inference-server/server#2414]
**Description**
- Installed torch in default python backend (/usr/bin/python3)
- Importing torch is causing a linker error ("undefined symbol: _THError")
- This seems to happen because the `LD_LIBRARY_PATH` includes some pytorch headers/libraries: `/opt/tritonserver/lib/pytorch/:/usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64`
- The problem disappears when resetting `LD_LIBRARY_PATH` to `/usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64`
- I would have expected this hack to cause issues for the pytorch backend, but it doesn't seem to be the case, are those libraries used at all?

**Triton Information**
What version of Triton are you using?
20.10

Are you using the Triton container or did you build it yourself?
container

**To Reproduce**
Steps to reproduce the behavior.
- run interactively 20.10 container
- `python3 -m pip install torch`
- `python3 -c "import torch"`

**Expected behavior**
Being able to use torch in the python backend without modifying the `LD_LIBRARY_PATH` in the container.

**Comment by Tabrizian** [comment]
@francescoclarifai I believe this issue is fixed in the latest version of Triton. Reopen this ticket if you still saw this error in 20.12.
