### ISSUE TITLE
How to use custom backend e.g. identity_backend

### ISSUE THREAD

**Issue by XingBin111** [triton-inference-server/server#2418]
I only saw the build backend, but did not see how to deploy and send the request to the custom backend. So, how to use official [identity_backend](https://github.com/triton-inference-server/identity_backend) and [repeat_backend](https://github.com/triton-inference-server/repeat_backend)?

**Comment by deadeyegoodwin** [comment]
You don't directly communicate with a custom backend, just like you don't directly communicate with the TensorFlow or TensorRT backend. You send an inference request for a model to Triton using the C API, HTTP/REST protocol or GRPC protocol. You use the API/protocol in the same way no matter what type of model you are requesting. If that model is implemented by the custom backend then triton will "forward" the request to the custom backend.

**Comment by XingBin111** [comment]
For example, I need to write TritonPythonModel in model.py and corresponding config.pbtxt,  if I want inference is implemented by python backend .  what do I need to do if I want to use identity_backend?

In addition,do I need to build python backend from source  if I want to use opencv or some shared library written by c++ in TritonPythonModel?

**Comment by XingBin111** [comment]
For example, I need to write TritonPythonModel in model.py and corresponding config.pbtxt,  if I want inference is implemented by python backend .  what do I need to do if I want to use identity_backend?

In addition,do I need to build python backend from source  if I want to use opencv or some shared library written by c++ in TritonPythonModel?

**Comment by Tabrizian** [comment]
For identity backend, you need to use `"backend": identity` in your config.pbtxt file. 

Regarding the Python backend, you shouldn't need to build the Python backend from source. If you are able to use opencv in a simple Python code, you should be able to use it in the Python backend too.
