### ISSUE TITLE
Unable to get "compute start" and "compute end" with ensemble model for trace command 

### ISSUE THREAD

**Issue by githublsk** [triton-inference-server/server#2428]
Hi，

When I use the trace command for my ensemble model, I can not get "compute start" and "compute end" information, please give me a hint?
My envrionment:
Triton Information
docker nvcr.io/nvidia/tritonserver:20.10-py3

My trace command:
tritonserver --model-repository=/models --log-verbose=1 --trace-file=./trace.json --trace-level=MAX --trace-rate=1

My ensemble model config file:
<img width="255" alt="企业微信截图_16109627667418" src="https://user-images.githubusercontent.com/77612906/104899270-99401b00-59b5-11eb-82d7-523116b83a3a.png">

My trace log (summarized by trace_summary.py)
![image](https://user-images.githubusercontent.com/77612906/104899402-c260ab80-59b5-11eb-9bf0-12a5715ed278.png)

**Comment by deadeyegoodwin** [comment]
The ensemble itself does not have a compute... the compute is performed by the composing models. Is there specific information you are looking for in the trace? Trace functionality is incomplete for some model types and almost all the data it presents is more easily obtained via the statistics APIs: https://github.com/triton-inference-server/server/blob/master/docs/protocol/extension_statistics.md

**Comment by githublsk** [comment]
@deadeyegoodwin Thanks for your reply, as you said, the ensemble itself does not have a compute information, but for its sub-models does have compute information,  refering to the link https://github.com/triton-inference-server/server/pull/932. For our ensemble model(including preprocess model and faster rcnn model),  the trace.json (produced by our ensemble model)  only has ensemble model information, not has sub-models information(I think it should have), the trace.json is as follows
<img width="944" alt="企业微信截图_16111363981910" src="https://user-images.githubusercontent.com/77612906/105158201-ad685180-5b48-11eb-9b71-4e857ee9b274.png">, can you tell me what cause this phenomenon？
:

**Comment by deadeyegoodwin** [comment]
It looks like there has been a regression in the trace support for ensembles. There should be entries with a "parent_id" indicating they are part of an ensemble but clearly they are not present. We will open an internal issue to track.

**Comment by GuanLuo** [comment]
@githublsk #2680 fixes the regression
