### ISSUE TITLE
python_backend cmake error

### ISSUE THREAD

**Issue by DataXujing** [triton-inference-server/server#2432]
when execute：`cmake -DCMAKE_INSTALL_PREFIX:PATH=/opt/tritonserver/install -DTRITON_ENABLE_GPU=ON ..`
```
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- RapidJSON found. Headers: /usr/local/lib/cmake/RapidJSON/../../../include
-- RapidJSON found. Headers: 
-- Found CUDAToolkit: /usr/local/cuda/include (found version "11.1.74") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE 
```

**Comment by Tabrizian** [comment]
@DataXujing Can you please elaborate on the error? I don't see any errors in the log that you have posted.

**Comment by AderonHuang** [comment]
> when execute：`cmake -DCMAKE_INSTALL_PREFIX:PATH=/opt/tritonserver/install -DTRITON_ENABLE_GPU=ON ..`
> 
> ```
> -- The C compiler identification is GNU 7.5.0
> -- The CXX compiler identification is GNU 7.5.0
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: /usr/bin/cc - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: /usr/bin/c++ - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- RapidJSON found. Headers: /usr/local/lib/cmake/RapidJSON/../../../include
> -- RapidJSON found. Headers: 
> -- Found CUDAToolkit: /usr/local/cuda/include (found version "11.1.74") 
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE 
> ```

do you solved this problem?

**Comment by Tabrizian** [comment]
It takes a bit of time for the compilation. If you wait a bit more, you should see some progress on the compilation. Feel free to reopen this issue if you didn't see any progress.
