### ISSUE TITLE
Streaming generation

### ISSUE THREAD

**Issue by alxmamaev** [triton-inference-server/server#2433]
For example I have TTS model, how I can realise realtime streaming inside triton?

**Comment by deadeyegoodwin** [comment]
I'm not sure what you mean by "realtime", triton cannot make real-time scheduling guarantees like a realtime OS.

Triton sequence API is described here: https://github.com/triton-inference-server/server/blob/master/docs/protocol/extension_sequence.md and an example is here: https://github.com/triton-inference-server/server/blob/master/docs/client_examples.md#client-api-for-stateful-models.

**Comment by Jackiexiao** [comment]
update link: https://github.com/triton-inference-server/client#client-api-for-stateful-models

**Comment by Jackiexiao** [comment]
update link: https://github.com/triton-inference-server/client#client-api-for-stateful-models
