### ISSUE TITLE
segment fault within http_server.cc about rapidjson

### ISSUE THREAD

**Issue by ald2004** [triton-inference-server/server#2434]
**Description**
segment fault when second time call http infer .

**Triton Information**
2.7.0dev
Are you using the Triton container or did you build it yourself?
build my self 
**To Reproduce**
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `tritonserver --model-repository=./model'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f0caafb6db6 in rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>::Clear (this=0x32) at /usr/include/rapidjson/allocators.h:146
146             while (chunkHead_ && chunkHead_ != userBuffer_) {
[Current thread is 1 (Thread 0x7f0c857fe700 (LWP 32346))]
(gdb) bt
#0  0x00007f0caafb6db6 in rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>::Clear (this=0x32) at /usr/include/rapidjson/allocators.h:146
#1  0x00007f0caafb334e in rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>::~MemoryPoolAllocator (this=0x32, __in_chrg=<optimized out>) at /usr/include/rapidjson/allocators.h:140

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
when call python client demo for mug.jpg.
python image_client.py -i http -u 0.0.0.0:8000 -m densenet_onnx /dev/shm/server/qa/images/mug.jpg 
**Expected behavior**
for rapidjson repos issue said document allocator will be destroyed after document is not being referenced.
may be this line in triton_json.h : allocator_ = &document_.GetAllocator();
i do not know how to do with out allocator for after use to add some json member.

**Comment by deadeyegoodwin** [comment]
Can you run using the 20.12 Triton container from NGC. We do not see this kind of failure so may be related to your build.

**Comment by deadeyegoodwin** [comment]
Closing. Reopen when additional information is provided.
