### ISSUE TITLE
Spend long time in python backend module Tensor function

### ISSUE THREAD

**Issue by githublsk** [triton-inference-server/server#2453]
Hi,
when doing reference with ensemble model, the time spent on python backend execute funtion(Tensor funtion) is very long.
My envrionment:
Triton Information
docker nvcr.io/nvidia/tritonserver:20.10-py3

My ensemble model config file:
<img width="311" alt="ensemble_config_file" src="https://user-images.githubusercontent.com/77612906/105787316-b1b5c400-5fb9-11eb-9c1f-5d1cc2c75708.png">
My preprocess model config file(python backend):
<img width="222" alt="python_backend" src="https://user-images.githubusercontent.com/77612906/105787453-baa69580-5fb9-11eb-9ad4-25be52f31377.png">
The time spent on python backend execute funtion (Tensor function)is very long, I print the time spent on the Tensor funtion in startup.py in python backend, the average time is about between 0.045 and 0.055 second, the code in startup.py is as follows, can you give me some hint?
<img width="816" alt="tensor_time" src="https://user-images.githubusercontent.com/77612906/105787674-ec1f6100-5fb9-11eb-9a9e-9a47ecde352e.png">

**Comment by Tabrizian** [comment]
Your output size is very large (4.57 MB). `Tensor` is a constructor that creates a new `raw_data`. Currently, there is no other way to pass the output to gRPC except using `tobytes` method which creates a copy of the object. For now, the only way to reduce the time spent here would be to reduce the `OUTPUT0` size.

**Comment by Tabrizian** [comment]
Closing, reopen if the issue persists.
