### ISSUE TITLE
Getting the server inference time using the client library

### ISSUE THREAD

**Issue by Jungmo** [triton-inference-server/server#2467]
I am using the 20.06 version of TRTIS server and client library.

As far as I know, the detailed timestamp of the processing inference query is recorded in RequestTimers class like the below code in [http_client.cc](https://github.com/triton-inference-server/server/blob/b5a252773bb098123248950964600bcc9f262962/src/clients/c%2B%2B/library/http_client.cc#L1091).
```c++
[sync_request->Timer().CaptureTimestamp(RequestTimers::Kind::REQUEST_END);]
```
[In RequestTimers class](https://github.com/triton-inference-server/server/blob/b5a252773bb098123248950964600bcc9f262962/src/clients/c%2B%2B/library/common.h#L502), there are six kinds of timestamps, REQUEST_START, REQUEST_END,  SEND_START, SEND_END, RECV_START, and RECV_END.

Thus, I believed that the following formula, **_my_server_time_**  will be the inference time except communication time.
```c++
my_server_time = (REQUEST_END-REQUEST_START) - (SEND_END-SEND_START) - (RECV_END-RECV_START);
```

However,I identified that **_my_server_time_**  is not correct by comparing to server-side measurement, compute_infer_duration in[ infer_stats.cc](https://github.com/triton-inference-server/server/blob/b5a252773bb098123248950964600bcc9f262962/src/core/infer_stats.cc#L81).
I conjecture that the communication time is not completely eliminated by **_my_server_time_**.
Although I forcibly increased network latency between the client and the server using Linux traffic control utility (tc), I observed that (SEND_END-SEND_START) and (RECV_END-RECV_START) are not changed but **_my_server_time_** is increased.
This means that (SEND_END-SEND_START) is not a communication time of sending input data and (RECV_END-RECV_START) is also not a communication time of receiving inference result. 

My questions are as follows.

1. Although I was not able to find the related API, I was wondering that there is already an API to get server inference time in the client library. I think the perf_client also uses the same client library and I believe that the perf_client is reporting exact server inference time. 

2. If there is no specific API to get server inference time, is **_my_server_time_** the best way to get the inference time on the server?

3. If yes, why using the current API in RequestTimers class can not assess communication latency between the server and the client? 

4. If no, could you please share the way to get the inference time on client devices?

I conjecture that this issue might be already well-known and fixed in the current version of TRITS because I used the old version of TRITS (r20.06). If so, please let me know.

**Comment by tanmayv25** [comment]
> Although I was not able to find the related API, I was wondering that there is already an API to get server inference time in the client library. I think the perf_client also uses the same client library and I believe that the perf_client is reporting exact server inference time.

Seems like you are looking for [Statistics Extension](https://github.com/triton-inference-server/server/blob/r20.06/docs/protocol/extension_statistics.md). perf_client uses the same to obtain server-side inference statistics. Specifically, you can obtain  server side duration from ` "success" : $duration_stat`. It will accumulate the duration and request counts. 

> If there is no specific API to get server inference time, is my_server_time the best way to get the inference time on the server?

Besides just my_server_time, the API supports break-up such as queue, compute input, compute infer and compute output. Look in the above link to understand more about them. 

> If yes, why using the current API in RequestTimers class can not assess communication latency between the server and the client?

The `RequestTimers` class is just meant to capture the time seen by **client** and is separated from the server side logic. All the time markers are populated by the client library. The SEND_END is captured when there is no more data left to upload within the [callback ](https://github.com/triton-inference-server/server/blob/b5a252773bb098123248950964600bcc9f262962/src/clients/c%2B%2B/library/http_client.cc#L378)provided to libcurl api. IMO SEND_END is hence an estimate of the time when upload is finished from the client side(libcurl will not be given any more data to upload for the request). Similarly, RECV_START and RECV_END are set by the callbacks within libcurl. See [here](https://github.com/triton-inference-server/server/blob/b5a252773bb098123248950964600bcc9f262962/src/clients/c%2B%2B/library/http_client.cc#L1215-L1229). 

> If yes, why using the current API in RequestTimers class can not assess communication latency between the server and the client?

As explained above, these markers are essentially the client side by design. It doesn't account for the time when the upload from client completed till the final byte was received by the server.

> If no, could you please share the way to get the inference time on client devices?

Please use the Statistics Extension.

**Comment by deadeyegoodwin** [comment]
Just to followup on what @tanmayv25 says, the C++ and python client libraries each have an API to access the statistics extension. https://github.com/triton-inference-server/server/blob/master/docs/client_libraries.md#client-library-apis

For example, for HTTP C++ client it is ModelInferenceStatistics, https://github.com/triton-inference-server/server/blob/master/src/clients/c%2B%2B/library/http_client.h.in#L216

**Comment by Jungmo** [comment]
@deadeyegoodwin @tanmayv25 


Thank you for your answer. However, I think that I already tried your solutions as below.

```c++
FAIL_IF_ERR(part2_client->ModelInferenceStatistics(&model_stat, model_name),"unable to get model statistics");
parsingSuccessful = reader.parse( model_stat, root );
inf_count = root["model_stats"][0]["inference_count"].asFloat();
last_infer_time = root["model_stats"][0]["inference_stats"]["success"]["ns"].asString();
```

As far as I understand, in order to get inference time on the server, you said that a client should 

1. get server status on time t1 above code.
2. send an inference **query (A)** and receive the result of **query (A)** on time t2
3. get server status on time t3  above code.
4. last_infer_time (t3) - last_infer_time (t1) to get the server inference time of the query sent on time t2.

This method is working when there is no other inference. If another client sends and receives a **query (B)** between t3 and t1, this **query (B)** might interference the inference time of **query (A)**. Thus, in this case, inf_count (B) - inf_count (A) is not 1.

Is my method (code) reasonable and (if reasonable) a unique way to get the inference time of the query?

I am studying the relationship between server slowdowns and the number of inference queries that are computed simultaneously.  Under my research scenario, I need a server that can return the exact inference time of the query sent by the client.

**Comment by deadeyegoodwin** [comment]
If you want to track the server-side performance of individual inference requests you need to use the trace feature: https://github.com/triton-inference-server/server/blob/master/docs/trace.md#triton-server-trace
Unfortunately, for some model types, there is currently a known issue that all trace information is not collected. But you could try it and see if it is sufficient for your needs.

**Comment by Jungmo** [comment]
@deadeyegoodwin 

Thanks. However, there is still no way to return such traced information of individual inference to clients. Trace option is logged only in server-side. Am I right?

 As a researcher who has a large interest in designing inference servers for IoT, mobile services, I think if the server returns a classification result and piggybacks detail timestamps in the result as well (optionally), it helps clients' future actions based on the time information in the server. (e.g., sending a query to another idle server or changing connectivity to mitigate network latency).

**Comment by deadeyegoodwin** [comment]
An additional enhancement could be an option on each inference request to trace the request and return that trace information in the response. This would be an enhancement to the HTTP/REST and GRPC protocols. I can see how this would be useful but I imagine most production servers would disable this option as they would not want users putting the additional trace load on their server.

**Comment by Jungmo** [comment]
@deadeyegoodwin I agree "most production servers would disable this option as they would not want users putting the additional trace load on their server.".  However, in the service development stage, I think this option might be helpful.
I really appreciate you sharing your brilliant idea.
