### ISSUE TITLE
tritonclient.utils.cuda_shared_memory.CudaSharedMemoryException: unable to set device successfully

### ISSUE THREAD

**Issue by 28utkarsh** [triton-inference-server/server#2472]
I am trying to execute **simple_grpc_cudashm_client.py** example file to figure out how to use CUDA Shared Memory. I am able to successfully load the **simple** model from the **model_repository** (on the server side) as shown below. 

![Screenshot 2021-01-30 at 00 08 17](https://user-images.githubusercontent.com/15148237/106314107-43aa1f00-628f-11eb-9251-75136926ac90.png)

As soon as I run the example python code (on the client side), I am getting the following error:

`
Traceback (most recent call last):
  File "simple_grpc_cudashm_client.py", line 88, in <module>
    "output0_data", output_byte_size, 0)
  File "/usr/local/lib/python3.6/dist-packages/tritonclient/utils/cuda_shared_memory/__init__.py", line 123, in create_shared_memory_region
    byref(cuda_shm_handle))))
  File "/usr/local/lib/python3.6/dist-packages/tritonclient/utils/cuda_shared_memory/__init__.py", line 86, in _raise_if_error
    raise ex
tritonclient.utils.cuda_shared_memory.CudaSharedMemoryException: unable to set device successfully
`

I am using the following docker images:
**Sever: nvcr.io/nvidia/tritonserver:20.11-py3**
**Client: nvcr.io/nvidia/tritonserver:20.11-py3-clientsdk**

GPU: Quadro RTX 6000
System NVIDIA Driver Version: 460.32.03
CUDA: 11.1 (Docker)

**Comment by apekshapriya** [comment]
You can try giving **--gpus** as an arg while starting the client side docker as you had given while starting the server side docker.

**Comment by 28utkarsh** [comment]
Thanks for the correction.
