### ISSUE TITLE
Trouble sending image data to Triton Server

### ISSUE THREAD

**Issue by mdable2** [triton-inference-server/server#2478]
**Description**
I am trying to send an image to my model that is hosted on Triton Server. I have tried doing this in two ways. One, sending the image like this:
```
{
    "id": "1",
    "inputs": [
        {
            "name": "input_tensor",
            "datatype": "UINT8",
            "shape": [
                1,
                1,
                1,
                3
            ],
            "data": [--image data as bytes (type is unsigned int8)--]
        }
    ]
}
```

With this, I get this error: `{"error":"attempt to access JSON non-unsigned-integer as unsigned-integer"}`.

The other way I try to send is using the `Binary Tensor Data Extension` but I've gotten a few errors, one being: `http_server.cc:2327 Infer failed: must specifiy valid 'Infer-Header-Content-Length' in request header and 'binary_data_size' when passing inputs in binary data format`.

For the `Binary Tensor Data Extension` I am confused on how to set the call up properly because it says we need to send the request a an octet-stream but also include a JSON body. How are we to accomplish both of this in one call?

**Triton Information**
What version of Triton are you using?
20.13

Are you using the Triton container or did you build it yourself?
Built using Docker

**To Reproduce**
Using Tensorflow 2 Object Detection API model which returns `num_detections`, `detection_boxes`, `detection_scores`, `detection_classes`, and `image_tensor`.

**Expected behavior**
I am trying to successfully send image data to Triton server from my client project and get a response back.

**Comment by deadeyegoodwin** [comment]
Have you tried using the Python (or C++) HTTP client library to make the requests for you? Even if you don't want to use it as an ultimate solution it can still be useful to try because with the verbose option you can see what kind of HTTP requests it generates for both the pure json and binary tensor data formats. 
For your first error I imaging that you "data" array contains a negative value, but since the datatype is unsigned int8 that is not allowed.

**Comment by tanmayv25** [comment]
@mdable2  Can you share the `config.pbtxt` of your model? For using `Binary Tensor Data Extension`, you must include a header (Infer-Header-Content-Length) in your request that includes json size and not the binary data blob. You can see this implementation here for reference:
https://github.com/triton-inference-server/server/blob/master/src/clients/c%2B%2B/library/http_client.cc#L1269

**Comment by zet809** [comment]
hi, @mdable2 , here is my steps to send image data as **binary** format for your reference. But I still **not figure out** how to send image data as `"data": [--image data as bytes (type is unsigned int8)--]`

* prepend image file size 1005970(0x0f5992)
```
# printf "\x00\x0f\x59\x92" | cat - ./images/mug.jpg > stuff_mug
# ls -l stuff_mug
-rw-r--r-- 1 root root 1005974 Feb  3 01:35 stuff_mug
```

* prepare postdata json format, and append image size and image data to it:
```
# cat postdata.json
{"inputs":[{"name":"INPUT","shape":[1,1],"datatype":"BYTES","parameters":{"binary_data_size":<size of file stuff_mug, 1005974 here>}}],"outputs":[{"name":"OUTPUT","parameters":{"classification":3,"binary_data":true}}]}
# ls -l postdata.json
-rw-r--r-- 1 root root 188 Feb  3 01:35 postdata.json
# printf "\x00\x0f\x59\x92" | cat - ./images/mug.jpg >> postdata.json
# ls -l postdata.json
-rw-r--r-- 1 root root 1006161 Jan  6 05:50 postdata.json
```
* do inference
```
# curl -X POST -H "Content-Type: application/octet-stream" -H "Inference-Header-Content-Length: <sizeof original postdata.json, 188 here>" -H "Content-Length: <size of final postdata.json, 1006161 here>" -H "Accept: */*" localhost:8000/v2/models/<model_name>/infer --data-binary "@postdata.json" -vv -o /workspace/myoutput
# cat /workspace/myoutput
{"model_name":"<model_name>","model_version":"1","outputs":[{"name":"OUTPUT","datatype":"BYTES","shape":[1,3],"parameters":{"binary_data_size":72}}]}0.723992:504:COFFEE MUG0.270952:968:CUP0.001160:967:ESPRESSO#
```

**Comment by mdable2** [comment]
@deadeyegoodwin I did try using the Python HTTP client and I was able to get that to work. But my solution is written in C# so I am trying to just hit the endpoints provided by Triton Server and am handling the HTTP call as well as response myself. I am taking a bitmap and converting it to a byte array. Then trying to send that byte array along with the HTTP call.

@tanmayv25 here is my config of my model:
```
I1216 20:09:13.692264 1 tensorflow.cc:1031] model configuration:
{
    "name": "signatures",
    "platform": "tensorflow_savedmodel",
    "backend": "tensorflow",
    "version_policy": {
        "latest": {
            "num_versions": 1
        }
    },
    "max_batch_size": 0,
    "input": [
        {
            "name": "input_tensor",
            "data_type": "TYPE_UINT8",
            "dims": [
                1,
                -1,
                -1,
                3
            ]
        }
    ],
    "output": [
        {
            "name": "raw_detection_scores",
            "data_type": "TYPE_FP32",
            "dims": [
                1,
                300,
                2
            ]
        },
        {
            "name": "detection_scores",
            "data_type": "TYPE_FP32",
            "dims": [
                1,
                300
            ]
        },
        {
            "name": "raw_detection_boxes",
            "data_type": "TYPE_FP32",
            "dims": [
                1,
                300,
                4
            ]
        },
        {
            "name": "detection_boxes",
            "data_type": "TYPE_FP32",
            "dims": [
                1,
                300,
                4
            ]
        },
        {
            "name": "num_detections",
            "data_type": "TYPE_FP32",
            "dims": [
                1
            ]
        },
        {
            "name": "detection_classes",
            "data_type": "TYPE_FP32",
            "dims": [
                1,
                300
            ]
        },
        {
            "name": "detection_multiclass_scores",
            "data_type": "TYPE_FP32",
            "dims": [
                1,
                300,
                2
            ]
        },
        {
            "name": "detection_anchor_indices",
            "data_type": "TYPE_FP32",
            "dims": [
                1,
                300
            ]
        }
    ],
    "batch_input": [],
    "batch_output": [],
    "optimization": {
        "priority": "PRIORITY_DEFAULT",
        "input_pinned_memory": {
            "enable": true
        },
        "output_pinned_memory": {
            "enable": true
        }
    },
    "instance_group": [
        {
            "name": "signatures",
            "kind": "KIND_GPU",
            "count": 1,
            "gpus": [
                0
            ],
            "profile": []
        }
    ],
    "default_model_filename": "model.savedmodel",
    "cc_model_filenames": {},
    "metric_tags": {},
    "parameters": {},
    "model_warmup": [] 
}
```
I have tried adding the infer request header but was not setting it correctly then. So the idea is to send both the JSON object and byte array in the same field? I guess I'm confused on how exactly I package up the JSON object and byte array.

@zet809 so with your answer, I do have an additional question. Does that mean I will need to change my model's config.pbtxt? Right now, if you see above, I'm not sure it will still work because I do not have an OUTPUT for bytes.

Thank you all by the way, this is very helpful!

**Comment by deadeyegoodwin** [comment]
I'm not sure what you mean by "in the same field". In the body of your http request you send the json followed immediately by the data bytes, and Inference-Header-Content-Length gives the length of the json part so that Triton knows how to parse it (and also find the start of the binary data. If you use verbose output with the HTTP client you should see this. Also the protocol docs explain this and give some examples: https://github.com/triton-inference-server/server/blob/master/docs/protocol/extension_binary_data.md

**Comment by mdable2** [comment]
Got it. I will give that a try.

**Comment by mdable2** [comment]
@deadeyegoodwin Now I am getting a new error: 

`Infer failed: failed to parse the request JSON buffer: The document must not be followed by other values. at 122`

This is my json object:
```
{
"inputs":
  [
    {"name":"input_tensor",
     "datatype":"UINT8",
     "shape":
       [1,4212,2544,3],
     "parameters":
       {"binary_data_size":32145984}
     }
]}
```
Then I serialize my byte array and concatenate it to the end of my json object. Then I add this as StringContent to the HttpContent value of my post call.

I added the `Inference-Header-Content-Length` header with the value of json object length * sizeof(char).

Any ideas of what I'm doing wrong?

**Comment by mdable2** [comment]
I changed my `Inference-Header-Content-Length` to the correct value it looks like and am now getting this error:

`Infer failed: unexpected additional input data for model 'signatures'`

**Comment by tanmayv25** [comment]
@mdable2  This means you have some extraneous bytes attached to your request's binary data. 
Can you ensure the binary data that you stick after your json is exactly `32145984 bytes`?

**Comment by mdable2** [comment]
@tanmayv25 I'm pretty sure that it is that many bytes. This is what I'm doing:

I'm taking a bitmap, converting it to a byte array, and then passing the length of the byte array as the value to `binary_data_size`.

For reference, this is how I am setting up my call:

```
public async void GetInferenceSignatures(byte[] img, int height, int width)
		{

			string endpoint = url;
			JObject jsonBody = new JObject();

			JObject binaryDataSize = new JObject();
			binaryDataSize.Add("binary_data_size", img.Length);

			JObject requestInput = new JObject();
			requestInput.Add("name", "input_tensor");
			requestInput.Add("datatype", "UINT8");
			requestInput.Add("shape", new JArray(1, height, width, 3));
			requestInput.Add("parameters", binaryDataSize);
			jsonBody.Add("inputs", new JArray(requestInput));

			var jsonData= JsonConvert.SerializeObject(jsonBody);
			var imageData = JsonConvert.SerializeObject(img);
			var requestBody = jsonData + imageData;

			StringContent content = new StringContent(requestBody, Encoding.UTF8, "application/octet-stream");
			client.DefaultRequestHeaders.Add("Inference-Header-Content-Length", (jsonData.Length).ToString());
			
			var data = client.PostAsync(endpoint, content).Result;
			var responseString = await data.Content.ReadAsStringAsync();
			Console.WriteLine("Your response data is: " + responseString);
		}
```

**Comment by mdable2** [comment]
Another update, I have now been able to get the error above resolved by not converting the byte array to an object rather just appending it to the json body data. 

Now, I get this error: `{"error":"unexpected size for input 'input_tensor', expecting 32146025 bytes for model 'signatures'"}`

**Comment by mdable2** [comment]
Another update @deadeyegoodwin. I did as you suggested to see what the http request looks like via a working Python or C++ example. I was able to get that working and captured the output of the Python image example. There were a few bytes that looked like this: `\x00$` or `\x00~`.

Are we missing something here?

**Comment by mdable2** [comment]
@deadeyegoodwin I went ahead and converted my images into the hex string format that I saw from the Python image example (minus the characters mentioned above). And I am still getting an error saying that `Infer failed: unexpected additional input data for model 'signatures'`.

With that said, I am having trouble with how large the payload of the request gets. For instance, in the Python example it turns a 342 KB image into a 2.91 MB request. Then within my own implementation of how the Python client encodes the image data, I am getting similar results where a 14.3 KB images is over a MB. And then the data I actually want to use, which are larger images, turns the request into over 250 MB and it doesn't reach the server for many minutes.

Is this to be expected? If so, do you have any recommendation on how to send more efficient requests?

**Comment by deadeyegoodwin** [comment]
It seems like you have a working example using the python client library where you can see the HTTP request being generated and it is accepted by Triton. You just need to get your C# code to generate requests with the same format. I'm not familiar with C# or the HTTP library you are trying to use. It seems like you are having trouble figuring out how to but some bytes into the http request body using C#. Have you tried a simplier example where you send a request with just 4 bytes of data? Perhaps you can ask for help in a C# forum as this doesn't seem like a Triton issue.

**Comment by gioipv** [comment]
> hi, @mdable2 , here is my steps to send image data as **binary** format for your reference. But I still **not figure out** how to send image data as `"data": [--image data as bytes (type is unsigned int8)--]`
> 
> * prepend image file size 1005970(0x0f5992)
> 
> ```
> # printf "\x00\x0f\x59\x92" | cat - ./images/mug.jpg > stuff_mug
> # ls -l stuff_mug
> -rw-r--r-- 1 root root 1005974 Feb  3 01:35 stuff_mug
> ```
> 
> * prepare postdata json format, and append image size and image data to it:
> 
> ```
> # cat postdata.json
> {"inputs":[{"name":"INPUT","shape":[1,1],"datatype":"BYTES","parameters":{"binary_data_size":<size of file stuff_mug, 1005974 here>}}],"outputs":[{"name":"OUTPUT","parameters":{"classification":3,"binary_data":true}}]}
> # ls -l postdata.json
> -rw-r--r-- 1 root root 188 Feb  3 01:35 postdata.json
> # printf "\x00\x0f\x59\x92" | cat - ./images/mug.jpg >> postdata.json
> # ls -l postdata.json
> -rw-r--r-- 1 root root 1006161 Jan  6 05:50 postdata.json
> ```
> 
> * do inference
> 
> ```
> # curl -X POST -H "Content-Type: application/octet-stream" -H "Inference-Header-Content-Length: <sizeof original postdata.json, 188 here>" -H "Content-Length: <size of final postdata.json, 1006161 here>" -H "Accept: */*" localhost:8000/v2/models/<model_name>/infer --data-binary "@postdata.json" -vv -o /workspace/myoutput
> # cat /workspace/myoutput
> {"model_name":"<model_name>","model_version":"1","outputs":[{"name":"OUTPUT","datatype":"BYTES","shape":[1,3],"parameters":{"binary_data_size":72}}]}0.723992:504:COFFEE MUG0.270952:968:CUP0.001160:967:ESPRESSO#
> ```
@zet809 
thankyou for sharing. i read the [binary data extension](https://github.com/triton-inference-server/server/blob/main/docs/protocol/extension_binary_data.md) . But i dont understand that, in you comment, `1005970` is the image size in bytes ?. And the last is why do you add the image size in `hex` formated in `stuff_mug`.
Could you tell me about that, Thank you ?

**Comment by zet809** [comment]
Hi, @gioipv , sorry for misleading you.
The purpose of adding image size in `hex` into `stuff_mug` step, is just want to show you how the  "binary_data_size" is got in postdata.json.

So, `0x0f5992` is image binary data size. And then, "binary_data_size"=image_data_size(0x0f5992 or 1005970) + length of data_size( 4), then that is 1005974. 

As for why need to add `hex data_size` before `binary data` when append image data to `post json data`, may related to how binary data is processed inside HTTP server. I didn't pay much attention to this part.

**Comment by Sencc** [comment]
Have you solved this problem? Can you provide relevant C# code for my reference? Thank you！
