### ISSUE TITLE
Simplify the source building process (i.e. doc and dependencies)

### ISSUE THREAD

**Issue by nicklhy** [triton-inference-server/server#2482]
**Is your feature request related to a problem? Please describe.**
Triton usually releases a new version with a set of corresponding docker images (i.e. `nvcr.io/nvidia/tritonserver:20.12-py3`). However, it also restricts user's choices about the version of triton's dependencies (i.e. CUDA/CuDNN/TF/PyTorch/TensorRT). When trying to use triton in production scenarios, this could be a big problem if we have a lot of old models to maintain and want to migrate to the newest triton. For instance, some models only work with old cuda 10.0 + cudnn 7, some models were developed with the old custom backends APIs based on opencv 3.2 ...

I guess a better idea is to let users build triton from source in their own images. But unfortunately, the current source building process is too complicated and difficult. For instance,

* We have to do `pip install docker` even though we set `--no-container-build` when executing `python build.py`.
* The directory of `CMakeLists.txt` is fixed to `/workspace/build` in [`build.py#L267`](https://github.com/triton-inference-server/server/blob/ec3dab4bceb8162b82c85b5fe34231f145f9e2ad/build.py#L267). I do not think this is a good idea if we just want to build triton from source without docker.
* Can we ignore the complicate `build.py` (with more than 1000 lines of code) and just use cmake directly like most other C/C++ projects based on cmake ?
* It tries to download tensorflow, aws-sdk-cpp, google-cloud-cpp and a lot of other dependencies even though I set the corresponding options off. Some repos are too large to clone (i.e. grpc uses 1+ GB space) and I don't want to waste time on them in ci jobs.

**Describe the solution you'd like**

* Optimize the source building doc and the related scripts. Make it easy to customize and compile for everyone.
* If possible, I guess it would also be better to remove some redundent dependencies from triton server.

**Additional context**

From my perspective, the official images which almost turned all features on and always rely on the latest cuda/cudnn/trt/tf/pytorch is more suitable for demo, not for production.

**Comment by deadeyegoodwin** [comment]
We will fix the issue with docker being required for --no-container-build and look into the /workspace/build directory.

The build.py script exists because building Triton requires gathering and installing a lot of specific dependencies (cuda, cudnn, etc.) and the building of source from multiple repositories. But you don't have to use build.py as every part of the triton project has cmake files (in fact, after setting up dependencies, etc., build.py just invokes cmake).

How are you invoking cmake where you see the unneeded repos being cloned?

**Comment by nicklhy** [comment]
@deadeyegoodwin  Thanks for your reply. And about what you asked, I tried to compile triton as below
```
cd ${TRITON_SERVER_ROOT}
mkdir builddir
cd builddir
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=builddir/tritonserver/install -DTRITON_COMMON_REPO_TAG:STRING=main -DTRITON_CORE_REPO_TAG:STRING=main -DTRITON_BACKEND_REPO_TAG:STRING=main -DTRITON_THIRD_PARTY_REPO_TAG:STRING=main -DTRITON_ENABLE_LOGGING:BOOL=ON -DTRITON_ENABLE_STATS:BOOL=ON -DTRITON_ENABLE_METRICS:BOOL=ON -DTRITON_ENABLE_METRICS_GPU:BOOL=ON -DTRITON_ENABLE_TRACING:BOOL=ON -DTRITON_ENABLE_GPU:BOOL=ON -DTRITON_MIN_COMPUTE_CAPABILITY=6.0 -DTRITON_ENABLE_GRPC:BOOL=ON -DTRITON_ENABLE_HTTP:BOOL=ON -DTRITON_ENABLE_GCS:BOOL=OFF -DTRITON_ENABLE_S3:BOOL=OFF -DTRITON_ENABLE_AZURE_STORAGE:BOOL=OFF -DTRITON_ENABLE_TENSORFLOW=OFF -DTRITON_ENABLE_TENSORRT=OFF -DTRITON_ENABLE_CUSTOM=ON -DTRITON_ENABLE_ENSEMBLE=OFF -DTRITON_ENABLE_ONNXRUNTIME=OFF -DTRITON_ENABLE_PYTHON=OFF -DTRITON_ENABLE_DALI=OFF -DTRITON_ENABLE_PYTORCH=OFF -DTRITON_EXTRA_LIB_PATHS=/opt/tritonserver/lib ../build

make -j8
```
For instance, S3/AZURE/TENSORFLOW are disabled here, but the corresponding repos are still being download during `make`.

**Comment by deadeyegoodwin** [comment]
You did not specify a target so make is trying to build everything. Try "make -j8 server".

**Comment by nicklhy** [comment]
@deadeyegoodwin Thanks. `make server` works for me now.
