### ISSUE TITLE
Unable to set dims for output with only batch dimension

### ISSUE THREAD

**Issue by Piteryo** [triton-inference-server/server#2496]
I have an output with the shape of batch dimension, like [2, 3, 4] (when batch_size = 3), so the wanted shape is [3] in that case. I want to use dynamic batching, therefore I have an implicit batch dimension. How to set the right ```dims``` option for such output? Empty brackets or 0 are not approved by the server.

**Comment by vignesh34v** [comment]
Any updates here

**Comment by Wolfffff** [comment]
Hitting this issue as well -- hopefully there's a simple solution!

**Comment by CoderHam** [comment]
For dimensions with variable size you can use -1 to represent that dimension
