### ISSUE TITLE
Python backend doesn't support boolean outputs

### ISSUE THREAD

**Issue by dgoupil** [triton-inference-server/server#2500]
**Description**
Python backend doesn't support boolean outputs
Error received from the grpc response
{
  "error": "13 INTERNAL: GRPC Execute Failed, message: Exception calling application: <class 'numpy.bool_'>"
}

The issue is here: [https://github.com/triton-inference-server/python_backend/blob/main/src/resources/triton_python_backend_utils.py](https://github.com/triton-inference-server/python_backend/blob/main/src/resources/triton_python_backend_utils.py)

**The numpy type should be `np.bool_` instead of `np.bool`.**
Let me know if you want me to create the PR. 
Thank you

**Triton Information**
What version of Triton are you using?
I'm using Triton container version `nvcr.io/nvidia/tritonserver:20.12-py3`

Are you using the Triton container or did you build it yourself?
I'm using Triton container version `nvcr.io/nvidia/tritonserver:20.12-py3`

**To Reproduce**
Steps to reproduce the behavior.
config.pbtxt
```
backend: "python"
max_batch_size: 10
input [
  {
    name: "bool"
    data_type: TYPE_BOOL
    dims: [ 1 ]
  }
]
output [
  {
    name: "bool"
    data_type: TYPE_BOOL
    dims: [ 1 ]
  }
]
version_policy: { 
  latest { 
    num_versions: 1 
  }
}
instance_group [
  {
    count: 1
    kind: KIND_CPU
  }
]
```

model.py
```
import triton_python_backend_utils as pb_utils

import json


class TritonPythonModel:
    def initialize(self, args):
        model_config = json.loads(args['model_config'])
        self.output_dtype_bool = pb_utils.triton_string_to_numpy(pb_utils.get_output_config_by_name(model_config, 'bool')['data_type'])

    def execute(self, requests):
        responses = []

        for request in requests:
            try:
                input_bool = pb_utils.get_input_tensor_by_name(request, 'bool').as_numpy()

                output_tensors = [pb_utils.Tensor('bool', input_bool.astype(self.output_dtype_bool))]

                inference_response = pb_utils.InferenceResponse(output_tensors=output_tensors)
                responses.append(inference_response)
            except Exception as e:
                responses.append(pb_utils.InferenceResponse(
                    output_tensors=[], error=pb_utils.TritonError(f'An Error Occurred:{e}')))

        return responses

    def finalize(self):
        """`finalize` is called only once when the model is being unloaded.
        Implementing `finalize` function is OPTIONAL. This function allows
        the model to perform any necessary clean ups before exit.
        """
        print('Cleaning up...')

```

Grpc request
```
{
  "model_name": "mli-test",
  "inputs": [
    {
      "name": "bool",
      "datatype": "BOOL",
      "shape": [2, 1],
      "contents": {
        "bool_contents": [false, true]
      }
    }
  ]
}
```

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
The model takes a bool as an input, and send back the same bool as an output.

**Expected behavior**
The response is created with the proper bool type.

**Comment by Tabrizian** [comment]
Thanks for reporting this. It will be fixed in triton-inference-server/python_backend#35.

**Comment by Tabrizian** [comment]
It is fixed now.

**Comment by dgoupil** [comment]
@Tabrizian  Thank you!
