### ISSUE TITLE
Wrong formatted config file from Auto-Generated Model Configuration

### ISSUE THREAD

**Issue by oyilmaz-nvidia** [triton-inference-server/server#2502]
**Description**
Wrong formatted config file from Auto-Generated Model Configuration

**Triton Information**
20.12

Are you using the Triton container or did you build it yourself?
Yes, using Triton container

**To Reproduce**
You can use nvtabular docker container to the example.

1) Use the notebook below to generate the data first;

https://github.com/NVIDIA/NVTabular/blob/main/examples/rossmann/rossmann-store-sales-preproc.ipynb

2) Then, use feature engineering notebook below;
https://github.com/NVIDIA/NVTabular/blob/main/examples/rossmann/rossmann-store-sales-feature-engineering.ipynb

3) Lastly, use the following notebook to train a model;

https://github.com/NVIDIA/NVTabular/blob/main/examples/rossmann/rossmann-store-sales-tensorflow.ipynb

In the last cell of "/rossmann-store-sales-tensorflow.ipynb" notebook, you can run;

tf_model.save('path') to save the model.

After start serving the saved model with "--strict-model-config=false", you can get the config file with 

curl localhost:8000/v2/models/<model name>

The return config file with curl has a wrong format. For instance, it has FP32 as a type rather then TYPE_FP32.

**Comment by deadeyegoodwin** [comment]
When using the HTTP or GRPC protocol types are communicated using the names defined by those protocols: https://github.com/kubeflow/kfserving/blob/master/docs/predict-api/v2/required_api.md#tensor-data-types
This is a community developed standard (as part of KFServing) and is younger that the model configuration specification in Triton, and uses different names for datatypes. So you need to translate the datatype names.

An alternative is to use --log-verbose=1 when running triton and the console log should container the auto-completed configuration in a format that is easier to cut-paste.

**Comment by oyilmaz-nvidia** [comment]
@deadeyegoodwin Used --log-verbose=1 and copied the console log into config file and getting this error;
```
Error parsing text-format inference.ModelConfig: 1:1: Expected identifier, got: {
```

**Comment by CoderHam** [comment]
@oyilmaz-nvidia The model config.pbtxt expects a protobuf and not a json.

**Comment by oyilmaz-nvidia** [comment]
@CoderHam How can I generate the config.pbtxt automatically?

**Comment by CoderHam** [comment]
You will have to base it off the json that we log. I don't think you can log the model config that was auto-filled as a protobuf (as of now). 
@deadeyegoodwin can you confirm this is correct?

**Comment by deadeyegoodwin** [comment]
In that case you need to manually translate the json into protobuf.

**Comment by Tabrizian** [comment]
@oyilmaz-nvidia code snippet below may help with the conversion:

```py
from tritonclient.grpc import model_config_pb2
from google.protobuf import json_format, text_format

proto_message = json_format.Parse(json_config, model_config_pb2.ModelConfig())
proto_string = text_format.MessageToString(proto_message)
```

**Comment by oyilmaz-nvidia** [comment]
@Tabrizian Thanks for the code but we're getting error. Btw, json_config variable is a string, right? Not a file path?

Here is the error;

```
>>> proto_message = json_format.Parse('config.json', model_config_pb2.ModelConfig())
Traceback (most recent call last):
  File "/conda/lib/python3.8/site-packages/google/protobuf/json_format.py", line 431, in Parse
    js = json.loads(text, object_pairs_hook=_DuplicateChecker)
  File "/conda/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/conda/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/conda/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conda/lib/python3.8/site-packages/google/protobuf/json_format.py", line 433, in Parse
    raise ParseError('Failed to load JSON: {0}.'.format(str(e)))
google.protobuf.json_format.ParseError: Failed to load JSON: Expecting value: line 1 column 1 (char 0).
>>> proto_string = text_format.MessageToString(proto_message)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'proto_message' is not defined
>>> proto_message = json_format.Parse('config.json', model_config_pb2.ModelConfig())
Traceback (most recent call last):
  File "/conda/lib/python3.8/site-packages/google/protobuf/json_format.py", line 431, in Parse
    js = json.loads(text, object_pairs_hook=_DuplicateChecker)
  File "/conda/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/conda/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/conda/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conda/lib/python3.8/site-packages/google/protobuf/json_format.py", line 433, in Parse
    raise ParseError('Failed to load JSON: {0}.'.format(str(e)))
google.protobuf.json_format.ParseError: Failed to load JSON: Expecting value: line 1 column 1 (char 0).
```

**Comment by Tabrizian** [comment]
@oyilmaz-nvidia You need to first load the config into a string. The first argument of `Parse` is a string.
