### ISSUE TITLE
Reading floats from raw content

### ISSUE THREAD

**Issue by Uture** [triton-inference-server/server#2512]
I'm working on a Java client for the Triton and have two questions.

1) Am I missing something with the InferOutputTensor.get[X]Content() method, because hasContent() always returns false for me and the corresponding getters don't return any data, even though my model outputs multiple tensors of type FP32.
2) From the lack of data in the InferOutputTensor, I assumed that I should access the data through ModelInferResponse.getRawOutputContents(). But when I try to read floats from it, the amount of extracted floats is correct but the values are utter rubbish, like 4.6006E-41. This is not a valid output of my model, as its last operation is a softmax.

I would be very thankful for guidance in this topic, as we would love to use the Triton server as part of our deployment stack.

**Comment by Uture** [comment]
I just figured it out, if someone struggles with the same issue, the solution was to change the byte order of the raw content to little-endian. If this isn't documented anywhere, I think it should be.

**Comment by deadeyegoodwin** [comment]
Linked a PR that adds a little-endian reference in perf_analyzer docs.
There is an existing mention here: https://github.com/triton-inference-server/server/blob/master/docs/protocol/extension_binary_data.md#binary-tensor-data-extension
