### ISSUE TITLE
ArmNN Backend

### ISSUE THREAD

**Issue by jishminor** [triton-inference-server/server#2513]
**Is your feature request related to a problem? Please describe.**
Running Triton models on cpu for Arm64 platforms could be potentially accelerated using ArmNN as an inference backend.

**Describe the solution you'd like**
A backend for ArmNN maintained externally from Nvidia

**Additional context**
I've already written a functional ArmNN backend for Triton as an `InferenceBackend` about a year ago, but did not submit a PR. With the new improved build system for Triton backends, it is now easy to maintain the ArmNN backend in a separate repo for the community to use. I wanted to make sure this backend is not already in existence.

**Comment by deadeyegoodwin** [comment]
We don't know of any Triton backend effort for ArmNN, but we are interested in supporting you in your effort. Do you have a plan for where you would host the backend? In the ArmNN repo? In the triton-inference-server repo?

**Comment by jishminor** [comment]
It would be hosted likely somewhere in here: https://github.com/ARM-software. In a repo adjacent to the armnn project.

**Comment by jishminor** [comment]
I notice that there are some residual dependencies for building the inference backends in `server/src/backends/pytorch/`. Will I have to add this for the ArmNN backend into the main server repo via a PR?

**Comment by deadeyegoodwin** [comment]
No. That is just old cruft which we will clean up once we get all the backends moved over to the Triton Backend API (the only one remaining is the TensorRT backend). You will not be required to make any changes to server for your backend.
