### ISSUE TITLE
Decoding grpc output

### ISSUE THREAD

**Issue by mdable2** [triton-inference-server/server#2514]
I am trying to decode the `grpc` output and cannot figure out the proper way to do this. I've tried ASCII, Base64, UTF8, etc.

I construct my request according to the .proto file provided. Then I add `RawInputContents` to that request by using the `Google.Protobuf.ByteString.FromStream()` function which takes a `MemoryStream` and converts it into a `ByteString`.

I then make the request utilizing `ModelInferAsync`, it hits the server and reports a successful response has been sent back. I then look at the reply and can see what I expect to be an array of 5 `ByteStrings` in the reply's `RawOutputContents`. I iterate through these and try to print out the contents and cannot figure out what encoding I need to use to make it readable.

The output is always a jumbled mess of characters, questions marks, etc.

I am using C# for my client and have been using the `image classification examples` as reference. Everything works up until the point of figuring out how to decode the output from the `grpc` call. 

Any ideas of what I can try next?

**Comment by mdable2** [comment]
I have also tried converting how I see in `deserialize_bytes_tensor`. So I have a function that converts the byte array into hex string.

For instance, this is the hex string output but decoding this turns into a bunch of boxes and jumbled stuff.
```
00000842000035430000a242000028420000024300005f4300005943000036430000324300002f43000034430000234300002c430000264300002443000022430000254300002b430000314300002e4300002743000028430000304300002d430000294300002a4300003943000033430000a0420000704100005442000063430000534300008c420000684200004c4200004d430000654300005e43000001430000803f000072430000734300006c42000045430000074300000443000049430000ec420000504300006b430000404300006d430000854300003842000020420000f0420080874300006c430000794300001c420000fe420000a4420000b24200003d43000018420000584200003f4300005643000084430000ea420000ee420000514300004a4300009e420000e2420000b04100006843000058430000694300009a42000055430080944300007a4300001042000040400000e442000094420000664300000a430000674300808b430080954300008c43000094430000934300008d43000090430000924300808f430000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```

**Comment by mdable2** [comment]
After inspecting the `raw_output_contents` using the Python `inception_graphdef` image example, I see the output looks like this:

`raw_output_contents: "\026\000\000\0000.57645:917:WEB SITE\r"`

What do I need to do to convert the contents into something I can use?

I'm expecting something similar to how in the HTTP request example it comes back with a response I decode and can read as JSON.

**Comment by CoderHam** [comment]
You can have a look at the way we do this in the python grpc client library [here](https://github.com/triton-inference-server/server/blob/master/src/clients/python/library/tritonclient/grpc/__init__.py#L1592-L1636). We convert the raw output contents into a numpy array.
