### ISSUE TITLE
Triton GRPC client creation has memory leak

### ISSUE THREAD

**Issue by deadeyegoodwin** [triton-inference-server/server#2517]
**Description**
In the GRPC client library the InferenceServerGrpcClient::Create function appears to have a memory leak. The source of the leak seems to be a bug in gRPC: https://github.com/grpc/grpc/issues/21563 but the Triton client should find some way to avoid the leak so it does not impact uses of the client.

**Triton Information**
What version of Triton are you using?
20.11

Are you using the Triton container or did you build it yourself?
Container

**To Reproduce**
Create a large number of GRPC client objects and observe memory usage, or use valgrind.

**Expected behavior**
Triton GRPC client should not leak.

**Comment by CoderHam** [comment]
Appears to be solved by https://github.com/triton-inference-server/server/pull/2533
