### ISSUE TITLE
backend directory in jetson nano deploy

### ISSUE THREAD

**Issue by qianwangn** [triton-inference-server/server#2519]
Hello, @sublee 

**Describe the solution you'd like**
```
  tritonserver --model-repository=/path/to/model_repo --backend-directory=/path/to/tritonserver/backends \
         --backend-config=tensorflow,version=2
```
what path should I use, in --backend-directory.
I use Jetson NX, installed tensorrt7.1.3 with jetpack.

**Comment by deadeyegoodwin** [comment]
It depends on where you install the Triton tar file. If you look in the files that are untared you will see .../backends directory and that is what you should point to with --backend-directory

**Comment by qianwangn** [comment]
That means triton only support tensorflow1 and tensorflow2 as backends?
@deadeyegoodwin

**Comment by CoderHam** [comment]
@qianwangn Triton supports only Tensorflow (1 and 2) and TensorRT backends on Jetpack for now. The rest of the backends are not yet supported on Jetpack machines.

**Comment by qianwangn** [comment]
It depends on where you install the Triton tar file. If you look in the files that are untared you will see .../backends directory and that is what you should point to with --backend-directory

In this tar file. There is no Tensorrt backends.

**Comment by deadeyegoodwin** [comment]
TensorRT support has not yet migrated to the backends/ area (but it will in the future). But TensorRT support is there. Have you tried running a TensorRT model and hit a failure?

**Comment by qianwangn** [comment]
@deadeyegoodwin I didn't hit a failure. But I want to run a TensorRT model use TensorRT backends. That will support in the future?

**Comment by deadeyegoodwin** [comment]
TensorRT is supported now and it will remain supported in the future.

**Comment by qianwangn** [comment]
@deadeyegoodwin Thats my question. I can not find tensorrt backends in the jetson release package. so I want to know how to find tensorrt backends. should I compile tensorrt in jetson, or ttensorrt backends already generated with jetpack.
Thanks a lot.

**Comment by deadeyegoodwin** [comment]
Triton support is compiled into libtritonserver.so.

**Comment by qianwangn** [comment]
Thanks A lot.
