### ISSUE TITLE
Call HTTP/RestAPI with byte data in payload

### ISSUE THREAD

**Issue by gaborvecsei** [triton-inference-server/server#2520]
**Problem**

The problem is that if a model requires byte input (e.g. this operation: https://www.tensorflow.org/api_docs/python/tf/io/decode_jpeg), then we can not provide that with the rest inferface.

Possibilities:
- we use the gRPC interface
- change the model to support base64 decoding (e.g. https://www.tensorflow.org/api_docs/python/tf/io/decode_base64) and then it will do the image decoding

Or maybe I am missing something. How this is handled currently?

**Solution** 

- Server side `base64` decoding (just like in Tensorflow serving: https://www.tensorflow.org/tfx/serving/api_rest#encoding_binary_values)
- `Multipart/form-data`, where the `POST` payload is the same as before except the `data` key.

**Comment by deadeyegoodwin** [comment]
Triton already supports a binary payload in HTTP/REST by having the request body contain a json header followed by binary data. This format is used by Triton's Python and C++ client libraries. It is more efficient than base64. https://github.com/triton-inference-server/server/blob/master/docs/protocol/extension_binary_data.md

**Comment by zet809** [comment]
Hi, @deadeyegoodwin , as there is binary payload supported, does it mean the `base64` string is not supported? And if a `base64` string passed in triton, it is our model responsibility to decode it and then do predict?

**Comment by deadeyegoodwin** [comment]
Triton doesn't explicitly support base64 in any protocol. You can of course pass a base64 string as binary data and it will be delivered to your model in that way... and so your model would need to then decode the base64.
