### ISSUE TITLE
Support List of Tensors in LibTorch backend

### ISSUE THREAD

**Issue by Ursanon** [triton-inference-server/server#2521]
**Description**
I want to run inference on f-rcnn model trained with pyTorch, but it fails due to lack of support for inputs as `List[Tensor]`.

**Environment:**
Trained with `nvidia/pytorch:20.12-py3`
Inference with `nvidia/tritonserver:20.12-py3`

**Error:**
```
PyTorch execute failure: forward() Expected a value of type 'List[Tensor]' for argument 'images' but instead found type 'Tensor'
```

**Comment by deadeyegoodwin** [comment]
Triton only supports tensor inputs. You will need to change the model to take tensors instead of a list of tensors.
