### ISSUE TITLE
Pip install nvidia-pyindex not working

### ISSUE THREAD

**Issue by sourdurian** [triton-inference-server/server#2525]
**Description**
When trying to pip install nvidia-pyindex from https://github.com/triton-inference-server/server/blob/r20.12/docs/client_libraries.md#getting-the-client-libraries, I got this error below. 
```
Collecting nvidia-pyindex
  Using cached https://files.pythonhosted.org/packages/40/e6/56a6909f95409a31865399282f5f5a1692e89e7f5f5c5e7633d201e0fbd0/nvidia-pyindex-1.0.6.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/pp/djp21f2j6q9dtzp_9v5f2jy80000gn/T/pip-install-mheb2qmw/nvidia-pyindex/setup.py'"'"'; __file__='"'"'/private/var/folders/pp/djp21f2j6q9dtzp_9v5f2jy80000gn/T/pip-install-mheb2qmw/nvidia-pyindex/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /private/var/folders/pp/djp21f2j6q9dtzp_9v5f2jy80000gn/T/pip-install-mheb2qmw/nvidia-pyindex/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/pp/djp21f2j6q9dtzp_9v5f2jy80000gn/T/pip-install-mheb2qmw/nvidia-pyindex/setup.py", line 214, in <module>
        raise OSError("Your operating system is not supported by "
    OSError: Your operating system is not supported by `nvidia-pyindex`: darwin.
    Only Linux systems are supported.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
**Triton Information**
I'm using triton 20.08

To replicate: 
pip3 install nvidia-pyindex

**Comment by Ursanon** [comment]
Are you on mac ?

> Only Linux systems are supported.

This may be issue.

**Comment by sourdurian** [comment]
ah crap.. i used ubuntu but had the same issue

**Comment by CoderHam** [comment]
Please update pip: `pip install --upgrade pip` first. You might be running an old version. 
I tried the same and it works fine for me. I am running this on ubuntu 18.04 with pip version 21.0.1. I can re-open the issue if you are still facing the issue after updating pip.

**Comment by novioleo** [comment]
> Please update pip: `pip install --upgrade pip` first. You might be running an old version.
> I tried the same and it works fine for me. I am running this on ubuntu 18.04 with pip version 21.0.1. I can re-open the issue if you are still facing the issue after updating pip.


error still exist .pls help to fix @CoderHam
