### ISSUE TITLE
Cannot import torch when using Python Backend

### ISSUE THREAD

**Issue by gilevir** [triton-inference-server/server#2532]
**Description**
When loading a model using the python backend, triton can't find the pytorch python package locally.
`ModuleNotFoundError: No module named 'torch'`

**Triton Information**
What version of Triton are you using?
Triton version 2.5.0 

Are you using the Triton container or did you build it yourself?
Triton container version 20.11
Triton is deployed on GKE

**To Reproduce**
Steps to reproduce the behavior.
- Add a python model using torch in the model repository
- Load the model manually using triton httpclient `load_model` method

Logs from triton:
```
2021-02-18 14:49:02 | I0218 13:49:02.760276 1 model_repository_manager.cc:810] loading: generator_anime_python:1
-- | --
  |   | 2021-02-18 14:49:05 | I0218 13:49:05.626769 1 python.cc:696] TRITONBACKEND_ModelInstanceInitialize: generator_anime_python_0 (GPU device 0)
  |   | 2021-02-18 14:49:05 | Traceback (most recent call last):
  |   | 2021-02-18 14:49:05 | File "/opt/tritonserver/backends/python/startup.py", line 360, in <module>
  |   | 2021-02-18 14:49:05 | python_host = PythonHost(module_path=FLAGS.model_path)
  |   | 2021-02-18 14:49:05 | File "/opt/tritonserver/backends/python/startup.py", line 161, in __init__
  |   | 2021-02-18 14:49:05 | spec.loader.exec_module(module)
  |   | 2021-02-18 14:49:05 | File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  |   | 2021-02-18 14:49:05 | File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  |   | 2021-02-18 14:49:05 | File "/tmp/folderAUHVdy/1/model.py", line 2, in <module>
  |   | 2021-02-18 14:49:05 | import torch
  |   | 2021-02-18 14:49:05 | ModuleNotFoundError: No module named 'torch'
  |   | 2021-02-18 14:49:10 | E0218 13:49:10.664959 1 model_repository_manager.cc:986] failed to load 'generator_anime_python' version 1: Internal: failed to connect to all addresses
```
Model config file: 

```
name: "generator_anime_python"
backend: "python"

input [
  {
    name: "INPUT__0"
    data_type: TYPE_FP32
    dims: [ 18, 512 ]

  }
]
output [
  {
    name: "OUTPUT__0"
    data_type: TYPE_FP32
    dims: [ 3, 1024, 1024 ]
  }
]

instance_group [{ kind: KIND_GPU }]
```

**Expected behavior**
torch package should be included in Triton container and be imported from `model.py`file.
Model should load flawlessly

**Comment by Tabrizian** [comment]
@gilevir Have you installed pytorch? You need to install the pytorch using pip or conda before using it.

**Comment by gilevir** [comment]
Hi, thanks for your quick answer.
No i didn't since i thought it was already there in the container.

Is it possible then to extend directly the container with the torch pip installation (using a dockerfile) ?

**Comment by remib-proovstation** [comment]
> Hi, thanks for your quick answer.
> No i didn't since i thought it was already there in the container.
> 
> Is it possible then to extend directly the container with the torch pip installation (using a dockerfile) ?

Hey, did you manage to extend the image via a dockerfile ?

**Comment by gilevir** [comment]
Hello,

Yes, basically you can create a new dockerfile as follow:

```
FROM nvcr.io/nvidia/tritonserver:20.12-py3

RUN pip3 install --upgrade --no-cache-dir torch
```

**Comment by hongdayu** [comment]
> 
> 
> Hello,
> 
> Yes, basically you can create a new dockerfile as follow:
> 
> ```
> FROM nvcr.io/nvidia/tritonserver:20.12-py3
> 
> RUN pip3 install --upgrade --no-cache-dir torch
> ```

Are you stuck with model loading?
