### ISSUE TITLE
Is there any difference between tensorflow model and TensorRT engine?

### ISSUE THREAD

**Issue by pogevip** [triton-inference-server/server#2536]
Is there any difference between tensorflow torch and torch?

inference speed or others etc

**Comment by deadeyegoodwin** [comment]
You mention Tensorflow and TensorRT in the title and then tensorflow and torch in the body so I'm not sure what you are asking. By "torch" I assume you mean PyTorch. Tensorflow, TensorRT and PyTorch (torchscript) models are all supported by Triton so you can experiment with different model frameworks to compare performance (see https://github.com/triton-inference-server/server/blob/master/docs/perf_analyzer.md). In general TensorRT model will have higher throughput and lower latency than TF or PyT.

**Comment by upendra8793** [comment]
TensorRT is library or model?????
