### ISSUE TITLE
Decoding binary data

### ISSUE THREAD

**Issue by ajaichemmanam** [triton-inference-server/server#2539]
I successfully ran the triton inference server and got the following results.

Request 1, batch size 1
[[b'3.951172:8397' b'3.443359:8396' b'3.271484:8269' ...
  b'-107.000000:499' b'-112.562500:628' b'-115.500000:627']]

[[b'125.500000:24186' b'125.437500:24586' b'125.375000:24316' ...
  b'-0.440430:16385' b'-0.531250:256' b'-0.685547:128']]

[[b'52.593750:542737' b'52.406250:542738' b'52.062500:509454' ...
  b'-63.656250:151692' b'-63.656250:151821' b'-63.968750:151693']]

[[b'0.862793:383' b'0.847656:510' b'0.841797:382' ... b'0.119873:16505'
  b'0.111084:16507' b'0.097656:16506']]

[[b'3.539062:170686' b'3.449219:170558' b'3.351562:239818' ...
  b'-33.625000:180851' b'-33.656250:49779' b'-35.187500:49651']]

[[b'0.805664:1151' b'0.804199:4934' b'0.800781:22845' ...
  b'0.014648:10968' b'0.007812:16388' b'0.005127:16387']]

These are 6 output tensors as expected. However, I am unable to decode them into np.float32 format.
Any help is appreciated. 
I tried using struck.unpack, got error as a buffer of size 4 is needed.

**Comment by deadeyegoodwin** [comment]
Those look like classification responses with the value and the index. If that correct? You can just use standard python functions to split the string. image_client does it like this: https://github.com/triton-inference-server/server/blob/master/src/clients/python/examples/image_client.py#L257
