### ISSUE TITLE
MyelinGraphError

### ISSUE THREAD

**Issue by ajaichemmanam** [triton-inference-server/server#2540]
I am trying to run a tensorrt model through triton.
The trt model is running perfectly with tensorrt but on triton it throws an error on loading.

plan_backend.cc:333] Creating instance ctmodel_0_gpu0 on GPU 0 (8.6) using ctmodel.trt
E0222 17:45:39.613183 1 logging.cc:43] myelin/myelinGraphContext.h (26) - Myelin Error in MyelinGraphContext: 66 (myelinBinaryVersionMismatch : myelinGraphDeserializeBinary called with a buffer that's not a Myelin binary (invalid version)
)
terminate called after throwing an instance of 'nvinfer1::MyelinError'
  what():  std::exception

Any hint about the error?

It's a pytorch model converted to onnx and then to tensorrt engine.
GPU: RTX3090
triton version: latest

**Comment by deadeyegoodwin** [comment]
Did you generate the model with the exact version of TensorRT that is being used by Triton (you can find that version in the Triton release notes: https://docs.nvidia.com/deeplearning/triton-inference-server/release-notes/index.html

**Comment by ajaichemmanam** [comment]
Yes. Tensorrt 7.2.2

**Comment by qianwangn** [comment]
same problem with RTX3090, RNN model.

**Comment by mozheng** [comment]
> same problem with RTX3090, RNN model.
> @deadeyegoodwin

+1

**Comment by qianwangn** [comment]
That bug seem fixed in recently release: 21.02.
Thanks.
