### ISSUE TITLE
build docker with build.py bug

### ISSUE THREAD

**Issue by dongrixinyu** [triton-inference-server/server#2542]
**Description**
docker-py version could have an impact on the final result.

**Triton Information**
master branch

build it myself.

**To Reproduce**
```
docker-py         1.10.6
docker-pycreds    0.4.0
```

yield several error :

1、line 911： timeout is an unexpected argument
2、line 914：AttributeError: 'function' object has no attribute 'get'

**Expected behavior**
the right docker -py interface version is ?

**Comment by CoderHam** [comment]
@dongrixinyu  Which version of python are you running? The build runs fine for me when I use these versions of `docker-py` and `docker-pycreds`?
Also could you share the command/args you are using to run build.py ?

**Comment by dongrixinyu** [comment]
python3.8 and the  docker-py version is above.
the args is 
```
./build.py --build-dir=/tmp/citritonbuild --enable-logging --enable-stats --enable-tracing --enable-metrics --enable-gpu-metrics --enable-gpu --filesystem=gcs --filesystem=azure_storage --filesystem=s3 --endpoint=http --endpoint=grpc --repo-tag=common:r20.12 --repo-tag=core:r20.12 --repo-tag=backend:r20.12 --backend=python:r20.12
```
i delete the cmake-dir arg because it cause a bug ```cmake-dir arg does not exist```

**Comment by CoderHam** [comment]
@dongrixinyu Can you confirm which release version of Triton you are running and the system OS (and any other information that can help reproduce this) you are running the build.py on?

**Comment by dongrixinyu** [comment]
- os: linux 18.04
- python: 3.8 anaconda
- git status: On branch v2.6.0.release
- docker version: Docker version 20.10.3
- nvidia: 460
- cuda: 11.2

**Comment by CoderHam** [comment]
Please try again with the latest release and let us know if you face the same issue.
