### ISSUE TITLE
Configuration documentation typo 

### ISSUE THREAD

**Issue by kjdrew** [triton-inference-server/server#2549]
**Description**
The documentation has an example for max batch size and dimensions of input/output tensors. The example doesn't not show the distinction the documentation is trying to make. 

Page: https://github.com/triton-inference-server/server/blob/r20.12/docs/model_configuration.md

Under Inputs and Outputs section, the two examples describe what a configuration file should look like for the case where _max_batch_size_ > 0 and where _max_batch_size_ == 0. However, both code examples are identical. This makes the example useless as reference. 

Text containing error: 

For example, for the following configuration the shape of "input0" is [ -1, 16 ] and the shape of "output0" is [ -1, 4 ].
```
  platform: "tensorrt_plan"
  max_batch_size: 8
  input [
    {
      name: "input0"
      data_type: TYPE_FP32
      dims: [ 16 ]
    }
  ]
  output [
    {
      name: "output0"
      data_type: TYPE_FP32
      dims: [ 4 ]
    }
  ]
```
For a configuration that is identical except that max_batch_size equal to 0, the shape of "input0" is [ 16 ] and the shape of "output0" is [ 4 ].

```
  platform: "tensorrt_plan"
  max_batch_size: 0
  input [
    {
      name: "input0"
      data_type: TYPE_FP32
      dims: [ 16 ]
    }
  ]
  output [
    {
      name: "output0"
      data_type: TYPE_FP32
      dims: [ 4 ]
    }
  ]
```

**Comment by deadeyegoodwin** [comment]
The examples are not identical. One has max_batch_size == 8 and as described this means that the shape required by the model input is [ -1, 16 ], even though the model configuration itself shows the shape as just [ 16 ]. The other example is max_batch_size == 0 and in that case the shape required by the model matches the shape shown in the configuration. Then intent is to show exactly what is explained in the text... that based on max_batch_size the dims specified in the config must be interpreted differently.

**Comment by kjdrew** [comment]
In this case, you'd not need to specify the `-1` in a configuration file. Is that correct?

**Comment by deadeyegoodwin** [comment]
In which case?

**Comment by kjdrew** [comment]
In the case of `max_batch_size=8`

**Comment by deadeyegoodwin** [comment]
Correct, and that is what the example is showing and the preceding text is explaining. In hindsight it is unnecessarily confusing and I would design it differently if I could. But at this point we can't break backwards compat.

**Comment by kjdrew** [comment]
OK thanks for clarifying!
