### ISSUE TITLE
Problem with commiting changes to the prebuilt docker container

### ISSUE THREAD

**Issue by Mike20001** [triton-inference-server/server#2553]
I added a pip3 package to the: nvcr.io/nvidia/tritonserver:20.11-py3 docker container and commited the changes and now I keep getting the following warning when I try to run with the following command:

sudo docker run --gpus=1 --rm -p8000:8000 -p8001:8001 -p8002:8002 -v/model_repository:/models  tritonserver --model-repository=/models

WARNING:

You should always run with libnvidia-ml.so that is installed with your
NVIDIA Display Driver. By default it's installed in /usr/lib and /usr/lib64.
libnvidia-ml.so in GDK package is a stub library that is attached only for
build purposes (e.g. machine that you build your application doesn't have
to have Display Driver installed).

Should I be changing the docker image in a different way?

**Comment by deadeyegoodwin** [comment]
What pip package did you add?

**Comment by Mike20001** [comment]
I tried using the base image nvcr.io/nvidia/tritonserver:20.11-py3 and commiting a new image without adding any pip package and I still get the same warning.

**Comment by deadeyegoodwin** [comment]
I'm not sure what you mean by "committing a new image". Not exactly what you are trying to do but there is some instructions for manipulating the triton container here: https://github.com/triton-inference-server/server/blob/master/docs/compose.md

**Comment by Mike20001** [comment]
What I mean by "commiting a new image" is using the command: "docker commit {CONTAINER_ID} {IMAGE_NAME} "
to create an image with the changes that I have made.

**Comment by deadeyegoodwin** [comment]
Are you still just trying to add a pip package? If so why are you not just using "docker build..."?

FROM ...
RUN pip3 install ...

**Comment by Tabrizian** [comment]
I think the issue is that `nvidia_entrypoint.sh` is not being used as the ENTRYPOINT for the new docker image.

**Comment by Mike20001** [comment]
> I think the issue is that `nvidia_entrypoint.sh` is not being used as the ENTRYPOINT for the new docker image.

This solved my problem thank you very much.
