### ISSUE TITLE
Deploy model trained with TLT

### ISSUE THREAD

**Issue by Ursanon** [triton-inference-server/server#2572]
Hello,

I’m trying to run inference on Triton Inference Server with faster rcnn model trained with TLT, converted to TensorRT.

In docs I can see:
> Note that the models can also be deployed outside of DeepStream using TensorRT but users will need to do image pre-processing and post-process the output Tensor after inference.

What kind of pre-process and post-process should I use for FasterRCNN and other available object detection models?
Currently I have OpenCV’s Mat (8UC3)-> 32FC3 → channel-wise array (3, width, height) (RRRGGGBBB) → pack data into bytestring and send request.

Then I parse output, but NMS_1 always equals zero.

Triton generated config:
```
{"name":"frcnn_fp16","versions":["1"],"platform":"tensorrt_plan","inputs":[{"name":"input_image","datatype":"FP32","shape":[-1,3,384,1248]}],"outputs":[{"name":"NMS","datatype":"FP32","shape":[-1,1,100,7]},{"name":"NMS_1","datatype":"FP32","shape":[-1,1,1,1]}]}
```
Post on forum: https://forums.developer.nvidia.com/t/triton-deployment-and-inference/169726

**Comment by justmert** [comment]
Same issue here...

**Comment by tanmayv25** [comment]
Closing the issue. Please check the response on the developer forum.
