### ISSUE TITLE
CMake error in building from source (no container)

### ISSUE THREAD

**Issue by fhaque** [triton-inference-server/server#2575]
**Description**
Since there's no Debian package for Triton, I would like to create one since we don't use Docker. As a start, I wanted to see if I could build from source.

I executed a no container and no GPU build from source on MacOS and got this error:

The output and error is:
```
backend "custom" at tag/branch "main"
backend "ensemble" at tag/branch "main"
backend "tensorrt" at tag/branch "main"
backend "identity" at tag/branch "r20.12"
backend "repeat" at tag/branch "r20.12"
backend "square" at tag/branch "r20.12"
backend "onnxruntime" at tag/branch "r20.12"
backend "pytorch" at tag/branch "r20.12"
backend "tensorflow1" at tag/branch "r20.12"
backend "tensorflow2" at tag/branch "r20.12"
backend "python" at tag/branch "r20.12"
backend "dali" at tag/branch "r20.12"
Building Triton Inference Server
component "common" at tag/branch "r20.12"
component "core" at tag/branch "r20.12"
component "backend" at tag/branch "r20.12"
component "thirdparty" at tag/branch "main"
CMake Error: The source directory "/workspace/build" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
error: cmake failed
```

**Triton Information**
What version of Triton are you using?
r20.12

Are you using the Triton container or did you build it yourself?
Trying to build myself.

**To Reproduce**
On MacOS 10.15.6:

Using `build.py` as specified in [build doc](https://github.com/triton-inference-server/server/blob/r20.12/docs/build.md#building-triton-with-docker), I executed a no container and no GPU build from source. Branch is `r20.12`:
```
./build.py --build-dir=/tmp/citritonbuild --enable-logging --enable-stats --enable-tracing --enable-metrics --filesystem=gcs --filesystem=s3 --endpoint=http --endpoint=grpc --repo-tag=common:r20.12 --repo-tag=core:r20.12 --repo-tag=backend:r20.12 --backend=custom --backend=ensemble --backend=tensorrt --backend=identity:r20.12 --backend=repeat:r20.12 --backend=square:r20.12 --backend=onnxruntime:r20.12 --backend=pytorch:r20.12 --backend=tensorflow1:r20.12 --backend=tensorflow2:r20.12 --backend=python:r20.12 --backend=dali:r20.12 --no-container-build
```

**Expected behavior**
It would create the directory `/workspace/build` or at least generate the right files in `build-dir` so cmake doesn't complain and build completes with a working tritonserver.

**Comment by deadeyegoodwin** [comment]
There was some hardcoded paths in build.py that are fixed in master branch. The specific error you are hitting can be fixed by using the --cmake-dir flag to point to your triton-inference-server/server/build directory. We also removed the "import docker" if you are building without docker.
