### ISSUE TITLE
model reload should be performed in backgroud but it does not

### ISSUE THREAD

**Issue by yushcs** [triton-inference-server/server#2578]
**Description**
When model is already in being served, and then config.txt is modified with version dir remain same. The model repository manager will first unload the model and then load.
But in the notes in method ModelRepositoryManager::BackendLifeCycle::AsyncLoad(in model_repository_manager.cc), it says "If the version backend is being served, the re-load of the version should be performed in background to avoid version down-time".
May be there should be a change from 
 ```
 // If the version backend is being served, the re-load of the version
      // should be performed in background to avoid version down-time
      if (serving_backend->state_ == ModelReadyState::READY) {
        if (res.first->second.second != nullptr) {
          res.first->second.second.reset(new BackendInfo(
              repository_path, ModelReadyState::UNKNOWN, ActionType::NO_ACTION,
              model_config));
        }
      }
 ```
to
```
// If the version backend is being served, the re-load of the version
      // should be performed in background to avoid version down-time
      if (serving_backend->state_ == ModelReadyState::READY) {
        if (res.first->second.second == nullptr) {
          res.first->second.second.reset(new BackendInfo(
              repository_path, ModelReadyState::UNKNOWN, ActionType::NO_ACTION,
              model_config));
        }
      }
```

**Triton Information**
What version of Triton are you using?
20.12

Are you using the Triton container or did you build it yourself?
Triton container

**To Reproduce**
Steps to reproduce the behavior.
1、start server in POLL mode
2、modified the config.txt

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**
The model being served should performed the re-load in the backgroud and avoid version down-time.

**Comment by deadeyegoodwin** [comment]
@GuanLuo  is that comment still accurate. I believe we fixed the downtime issue?

**Comment by GuanLuo** [comment]
The comment is still accurate, I just took a look at the existing test and it only tested the reload of the model with different version and missed the case of reloading the same version. Will fix it.
