### ISSUE TITLE
How to fork a request to multiple model instances?

### ISSUE THREAD

**Issue by gpudavid** [triton-inference-server/server#2583]
**Is your feature request related to a problem? Please describe.**
There are some usage cases that a Triton client sent a request and execute the request on several model instances. For example:
1. A giant model is divided into several sub-model and loaded as several model instances, and all the instances need to receive the request and get part of the request data and be triggered to run.
2. A same request may need to be handled by different DL models for different purposes, such different accuracy.

**Describe the solution you'd like**
I see there is ensemble models concept, which is related. https://github.com/triton-inference-server/server/blob/master/docs/architecture.md#ensemble-models. Can the `input` be assigned to a key and value? If so, it seems that one can reuse the `input` key for different model or model instances.

**Describe alternatives you've considered**
Ever one can write an `ensemble` model. It is more desired that the client can choose the request destination dynamically. When a client put a request:
1. it can select a model list and receive a list of response.
2. it can select a list of instances of a same model, and receive a response. This is for the case that when a giant model is divided into several sub-model and is loaded as several sub-model instances. All or part of the instances need to receive the request.

**Comment by GuanLuo** [comment]
Yes, your use case can be satisfied with ensemble, you can configure it in a way that the input tensors are sent to a set of models and collect the outputs of the models as the ensemble's response (2.). And of course you can also connect the I/O of the models to compute the result as if the giant model is run.

For your alternative, currently it is not supported as a request corresponds to one model, but you can achieve that with an ensemble that includes all the destinations and each destination corresponds to one ensemble output, then you can select the destinations by only requesting the corresponding outputs.

**Comment by gpudavid** [comment]
I will try to use ensemble model or related C++ functions/APIs to solve this. 

In the giant model case, it is a little complicated that, Triton recognized the sub-model-instances as identical instances to one model, even they are substantial different parts of the giant model. There is no multiple models to be assembled.
