### ISSUE TITLE
TensorRT model uses Perf_Client to test the performance and finds that compute input takes too long and infer takes too short.

### ISSUE THREAD

**Issue by zhaohb** [triton-inference-server/server#2591]
**Description**
we have a tensorrt model, several custom OPs were implemented for the model and compiled into a library，and deploy this model with triton, It can run normally.
But the performance is not satisfactory：
```shell
./perf_client -a -b 1500 -u localhost:8001 -i gRPC -m trt-0224 --concurrency-range 1
```
output:
```shell
*** Measurement Settings ***
  Batch size: 1500
  Measurement window: 5000 msec
  Using asynchronous calls for inference
  Stabilizing using average latency

Request concurrency: 1
  Client: 
    Request count: 150
    Throughput: 45000 infer/sec
    Avg latency: 33358 usec (standard deviation 2758 usec)
    p50 latency: 31450 usec
    p90 latency: 37247 usec
    p95 latency: 37413 usec
    p99 latency: 37568 usec
    Avg gRPC time: 33532 usec ((un)marshal request/response 3250 usec + response wait 30282 usec)
  Server: 
    Inference count: 267000
    Execution count: 178
    Successful request count: 178
    Avg request latency: 26965 usec (overhead 3 usec + queue 158 usec + compute input 23862 usec + compute infer 2925 usec + compute output 17 usec)

Inferences/Second vs. Client Average Batch Latency
Concurrency: 1, throughput: 45000 infer/sec, latency 33358 usec

```

**Triton Information**
we use triton 2.6.0,and we use Triton container

**To Reproduce**
this model has 173 inputs and 8 outputs, The input data volume of a BatchSize is about 0.4 KB.

**Expected behavior**
Why is compute input taking so long and how can I optimize it？does it have anything to do with my custom op？

**Comment by tanmayv25** [comment]
The `compute_input`, `compute_infer` and `compute_output` times are not accurate for TensorRT backend. What is accurate is the total (`compute_input + compute_infer + compute_output`). We are working on a solution that can provide an accurate breakdown without hurting the performance.

**Comment by zhaohb** [comment]
So the performance bottleneck right now is not necessarily in compute input, right?

**Comment by zhaohb** [comment]
this is great, and when will this feature be available？

**Comment by tanmayv25** [comment]
@GuanLuo ^^^

**Comment by zhaohb** [comment]
Now if I want to know the execution time of each phase, is there any other way？

**Comment by deadeyegoodwin** [comment]
Not right now... we hope to have a fix for this in the 21.04 release (late April). It is too late now for the March release.

**Comment by zhaohb** [comment]
I wonder if I could test it first，because now I'm analyzing the performance of the model, I can't get the running time exactly.

**Comment by zhaohb** [comment]
@deadeyegoodwin

**Comment by deadeyegoodwin** [comment]
We don't have anything to test yet because we don't have a solution yet. The TensorRT backend is async using cuda streams and we need to determine how we can measure these times without reducing performance. If you watch the PR and the release notes you will be able to see when we are working on it and when we have a potential solution.

**Comment by zhaohb** [comment]
ok, thank you very much, I'll keep an eye on it.

**Comment by GuanLuo** [comment]
Can you try to build with this change and see if it addresses the issue? #2602

**Comment by zhaohb** [comment]
of course, I will build and test as soon as possible
