### ISSUE TITLE
In model configuration support defining list of tensors as input

### ISSUE THREAD

**Issue by arunsu** [triton-inference-server/server#2593]
**Is your feature request related to a problem? Please describe.**
Some of the models take a list of images to inference. In the model configuration file "config.pbtxt" the tensor [datatypes supported](https://github.com/triton-inference-server/server/blob/master/docs/model_configuration.md#datatypes) by Triton doesn't have a list. Is there a plan to support list or is there a work around to pass a list of tensors to model.

Example:
Retinanet model takes list of images
import torch
import torchvision.models as models
retina50 = models.detection.retinanet_resnet50_fpn(pretrained=True)  
retina50.eval()
dummy_input = [torch.rand(3, 300, 400), torch.rand(3, 500, 400)]
output = retina50(dummy_input)

**Describe the solution you'd like**
Support List of tensors or alternative to provide the list.

**Describe alternatives you've considered**
In the config.pbtxt have the following input which doesn't work with the model.
input [
  {
    name: "input__0"
    data_type: TYPE_FP32
    dims: [3, 480, 640]
  }
]

**Additional context**

**Comment by GuanLuo** [comment]
So your model can accepts variable number of inputs? Or what you are showing here is batching the images into one input? Usually the image models accepts a batch of images as input to process a group of images in the same inference, and Triton can serve such model and you will need to change the `max_batch_size` in your model config to comply with the max batch size of your model.

**Comment by CoderHam** [comment]
While libtorch does support passing lists of tensors, Tritonserver does not. You can build a simple wrapper model that coverts a tensor into a list of tensors and passes it on to your model. Once you have this wrapper model, simply trace the same and you should be able to use this model inside Triton.

**Comment by CoderHam** [comment]
Closing this since Triton does not intend on adding support for handling list of tensors as inputs. Please use the work around shared above.
