### ISSUE TITLE
Docker image does not run under arbitrary non-root user

### ISSUE THREAD

**Issue by cliveseldon** [triton-inference-server/server#2600]
**Description**
Under Openshift an arbitrary non-root user will be enforced for running containers. the image `nvcr.io/nvidia/tritonserver:20.08-py3` at present assumes a user 1000 for triton-server. If you try to run as another non-root user you get a failure in the logs:
```
ln: failed to create symbolic link '/opt/tritonserver/lib/libnvidia-ml.so.1': Permission denied
```

**Triton Information**
What version of Triton are you using?
nvcr.io/nvidia/tritonserver:20.08-py3

Are you using the Triton container or did you build it yourself?
container

**To Reproduce**
Steps to reproduce the behavior.
```
docker run -it --rm --user 8888 nvcr.io/nvidia/tritonserver:20.08-py3
```

You should see
```
=============================
== Triton Inference Server ==
=============================

NVIDIA Release 20.08 (build 15533555)

Copyright (c) 2018-2020, NVIDIA CORPORATION.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.
NVIDIA modifications are covered by the license terms that apply to the underlying
project or file.
find: '/usr/lib/ssl/private': Permission denied

WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use 'nvidia-docker run' to start this container; see
   https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker .
find: '/etc/ssl/private': Permission denied
find: '/proc/tty/driver': Permission denied
find: '/root': Permission denied
ln: failed to create symbolic link '/opt/tritonserver/lib/libnvidia-ml.so.1': Permission denied
```

**Expected behavior**

The Docker image will run with an arbitrary non-root user.

**Comment by CoderHam** [comment]
The docker container needs permission to access libnvidia-ml.so
You will need to give it appropriate permissions.

**Comment by cliveseldon** [comment]
I think what I am suggesting is the created Docker image for the project is made in a way that allows it to be run with a non-root manner which is the norm for Kubernetes distributions such as Openshift.

**Comment by deadeyegoodwin** [comment]
We are moving triton to use libdcgm instead of nvml and that may allow us to remove the need to create this libnviida-ml-so link. If so, that should resolve this issue. I believe we should be able to attempt in 21.05 or 21.06 release.

**Comment by taomanwai** [comment]
I am using v21.06 and latest v21.12 but getting find: '/usr/lib/ssl/private': Permission denied.

Any solutions?
