### ISSUE TITLE
triton client C++

### ISSUE THREAD

**Issue by michaelwithu** [triton-inference-server/server#2603]
Download client sdk from NGC. and i try to cmake the samples "simple_http_health_metadata.cc".and "image_client" by my own CMakeLists.txt. When to cmake the sample "simple_http_health_metadata.cc" ,i use the CMakeLists.txt.
`cmake_minimum_required(VERSION 3.0)
project(simple_http_health_metadata)
set(CMAKE_BUILD_TYPE "Release")

set(CMAKE_CXX_FLAGS "-std=c++11 -g -O2 -pthread")
set(MAIN_EXE simple_http_health_metadata.cc)

include_directories(${CMAKE_SOURCE_DIR}/include)
include_directories("/workspace/")
include_directories("/workspace/install/include")
link_directories("/workspace/install/lib")

# about RapidJSON 
find_package(RapidJSON CONFIG REQUIRED)
add_library(
      json-utils-library EXCLUDE_FROM_ALL OBJECT
      json_utils.h json_utils.cc
      )
target_include_directories(
    json-utils-library
    PUBLIC ${RapidJSON_INCLUDE_DIRS}
    )

# about OpencCV
find_package(OpenCV REQUIRED)

add_executable(
  simple_http_health_metadata
  simple_http_health_metadata.cc
  $<TARGET_OBJECTS:json-utils-library>
  )
target_link_libraries(
  simple_http_health_metadata
  PRIVATE httpclient_static
  )
`

and 
mkdir build
cd build
cmake ..
make
then i get error 

`[ 33%] Built target json-utils-library
Scanning dependencies of target simple_http_health_metadata
[ 66%] Building CXX object CMakeFiles/simple_http_health_metadata.dir/simple_http_health_metadata.cc.o
[100%] Linking CXX executable simple_http_health_metadata
/workspace/install/lib/libhttpclient_static.a(http_client.cc.o): In function `nvidia::inferenceserver::client::(anonymous namespace)::CurlGlobal::~CurlGlobal()':
http_client.cc:(.text+0x9): undefined reference to `curl_global_cleanup'
/workspace/install/lib/libhttpclient_static.a(http_client.cc.o): In function `nvidia::inferenceserver::client::HttpInferRequest::~HttpInferRequest()':
http_client.cc:(.text+0x3ef): undefined reference to `curl_slist_free_all'
/workspace/install/lib/libhttpclient_static.a(http_client.cc.o): In function `nvidia::inferenceserver::client::InferenceServerHttpClient::InferenceServerHttpClient(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)':
http_client.cc:(.text+0x1138): undefined reference to `curl_easy_init'
http_client.cc:(.text+0x1144): undefined reference to `curl_multi_init'
/workspace/install/lib/libhttpclient_static.a(http_client.cc.o): In function `nvidia::inferenceserver::client::InferenceServerHttpClient::~InferenceServerHttpClient()':
http_client.cc:(.text+0x32ef): undefined reference to `curl_easy_cleanup'
http_client.cc:(.text+0x3320): undefined reference to `curl_multi_remove_handle'
http_client.cc:(.text+0x3328): undefined reference to `curl_easy_cleanup'
http_client.cc:(.text+0x3344): undefined reference to `curl_multi_cleanup'
/workspace/install/lib/libhttpclient_static.a(http_client.cc.o): In function `nvidia::inferenceserver::client::InferenceServerHttpClient::PreRunProcessing(void*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, nvidia::inferenceserver::client::InferOptions const&, std::vector<nvidia::inferenceserver::client::InferInput*, std::allocator<nvidia::inferenceserver::client::InferInput*> > const&, std::vector<nvidia::inferenceserver::client::InferRequestedOutput const*, std::allocator<nvidia::inferenceserver::client::InferRequestedOutput const*> > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, std::shared_ptr<nvidia::inferenceserver::client::HttpInferRequest>&)':
http_client.cc:(.text+0x4af1): undefined reference to `curl_easy_setopt'
http_client.cc:(.text+0x4b07): undefined reference to `curl_easy_setopt'
http_client.cc:(.text+0x4b1b): undefined reference to `curl_easy_setopt'
http_client.cc:(.text+0x4b2f): undefined reference to `curl_easy_setopt'
http_client.cc:(.text+0x4b69): undefined reference to `curl_easy_setopt'
/workspace/install/lib/libhttpclient_static.a(http_client.cc.o):http_client.cc:(.text+0x4b82): more undefined references to `curl_easy_setopt' follow
/workspace/install/lib/libhttpclient_static.a(http_client.cc.o): In function `nvidia::inferenceserver::client::InferenceServerHttpClient::PreRunProcessing(void*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, nvidia::inferenceserver::client::InferOptions const&, std::vector<nvidia::inferenceserver::client::InferInput*, std::allocator<nvidia::inferenceserver::client::InferInput*> > const&, std::vector<nvidia::inferenceserver::client::InferRequestedOutput const*, std::allocator<nvidia::inferenceserver::client::InferRequestedOutput const*> > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, std::shared_ptr<nvidia::inferenceserver::client::HttpInferRequest>&)':
http_client.cc:(.text+0x4cda): undefined reference to `curl_slist_append'
http_client.cc:(.text+0x4ce9): undefined reference to `curl_slist_append'
http_client.cc:(.text+0x4cf8): undefined reference to `curl_slist_append'
http_client.cc:(.text+0x4d65): undefined reference to `curl_slist_append'
http_client.cc:(.text+0x4da9): undefined reference to `curl_easy_setopt'
http_client.cc:(.text+0x4eb2): undefined reference to `curl_easy_setopt'
http_client.cc:(.text+0x4f82): undefined reference to `curl_easy_setopt'
/workspace/install/lib/libhttpclient_static.a(http_client.cc.o): In function `nvidia::inferenceserver::client::InferenceServerHttpClient::AsyncInfer(std::function<void (nvidia::inferenceserver::client::InferResult*)>, nvidia::inferenceserver::client::InferOptions const&, std::vector<nvidia::inferenceserver::client::InferInput*, std::allocator<nvidia::inferenceserver::client::InferInput*> > const&, std::vector<nvidia::inferenceserver::client::InferRequestedOutput const*, std::allocator<nvidia::inferenceserver::client::InferRequestedOutput const*> > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)':
http_client.cc:(.text+0x53a1): undefined reference to `curl_easy_init'
http_client.cc:(.text+0x5402): undefined reference to `curl_easy_cleanup'
http_client.cc:(.text+0x551b): undefined reference to `curl_easy_cleanup'
http_client.cc:(.text+0x5630): undefined reference to `curl_multi_add_handle'
/workspace/install/lib/libhttpclient_static.a(http_client.cc.o): In function `nvidia::inferenceserver::client::InferenceServerHttpClient::Infer(nvidia::inferenceserver::client::InferResult**, nvidia::inferenceserver::client::InferOptions const&, std::vector<nvidia::inferenceserver::client::InferInput*, std::allocator<nvidia::inferenceserver::client::InferInput*> > const&, std::vector<nvidia::inferenceserver::client::InferRequestedOutput const*, std::allocator<nvidia::inferenceserver::client::InferRequestedOutput const*> > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)':
http_client.cc:(.text+0x6ede): undefined reference to `curl_easy_perform'
http_client.cc:(.text+0x70f3): undefined reference to `curl_easy_getinfo'
/workspace/install/lib/libhttpclient_static.a(http_client.cc.o): In function `nvidia::inferenceserver::client::InferenceServerHttpClient::AsyncTransfer()':
http_client.cc:(.text+0x7330): undefined reference to `curl_multi_perform'
http_client.cc:(.text+0x7361): undefined reference to `curl_multi_info_read'
http_client.cc:(.text+0x7424): undefined reference to `curl_multi_remove_handle'
http_client.cc:(.text+0x742d): undefined reference to `curl_easy_cleanup'
http_client.cc:(.text+0x7500): undefined reference to `curl_multi_remove_handle'
http_client.cc:(.text+0x7509): undefined reference to `curl_easy_cleanup'
http_client.cc:(.text+0x766f): undefined reference to `curl_easy_getinfo'
/workspace/install/lib/libhttpclient_static.a(http_client.cc.o): In function `nvidia::inferenceserver::client::InferenceServerHttpClient::Get(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, long*)':
http_client.cc:(.text+0x7f2e): undefined reference to `curl_easy_init'
http_client.cc:(.text+0x7f4c): undefined reference to `curl_easy_setopt'
http_client.cc:(.text+0x7f62): undefined reference to `curl_easy_setopt'
http_client.cc:(.text+0x7f76): undefined reference to `curl_easy_setopt'
http_client.cc:(.text+0x7fbb): undefined reference to `curl_easy_setopt'
http_client.cc:(.text+0x7fcd): undefined reference to `curl_easy_setopt'
http_client.cc:(.text+0x803f): undefined reference to `curl_slist_append'
http_client.cc:(.text+0x8083): undefined reference to `curl_easy_setopt'
http_client.cc:(.text+0x808b): undefined reference to `curl_easy_perform'
http_client.cc:(.text+0x80a2): undefined reference to `curl_slist_free_all'
http_client.cc:(.text+0x80aa): undefined reference to `curl_easy_cleanup'
http_client.cc:(.text+0x80b1): undefined reference to `curl_easy_strerror'
http_client.cc:(.text+0x8280): undefined reference to `curl_easy_getinfo'
http_client.cc:(.text+0x8288): undefined reference to `curl_slist_free_all'
http_client.cc:(.text+0x8290): undefined reference to `curl_easy_cleanup'
http_client.cc:(.text+0x8330): undefined reference to `curl_easy_setopt'
/workspace/install/lib/libhttpclient_static.a(http_client.cc.o): In function `nvidia::inferenceserver::client::InferenceServerHttpClient::Post(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)':
http_client.cc:(.text+0x939d): undefined reference to `curl_easy_init'
http_client.cc:(.text+0x93bc): undefined reference to `curl_easy_setopt'
http_client.cc:(.text+0x93d2): undefined reference to `curl_easy_setopt'
http_client.cc:(.text+0x93e6): undefined reference to `curl_easy_setopt'
http_client.cc:(.text+0x93f9): undefined reference to `curl_easy_setopt'
http_client.cc:(.text+0x940b): undefined reference to `curl_easy_setopt'
/workspace/install/lib/libhttpclient_static.a(http_client.cc.o):http_client.cc:(.text+0x9453): more undefined references to `curl_easy_setopt' follow
/workspace/install/lib/libhttpclient_static.a(http_client.cc.o): In function `nvidia::inferenceserver::client::InferenceServerHttpClient::Post(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)':
http_client.cc:(.text+0x94d4): undefined reference to `curl_slist_append'
http_client.cc:(.text+0x9517): undefined reference to `curl_easy_setopt'
http_client.cc:(.text+0x951f): undefined reference to `curl_easy_perform'
http_client.cc:(.text+0x9536): undefined reference to `curl_slist_free_all'
http_client.cc:(.text+0x953e): undefined reference to `curl_easy_cleanup'
http_client.cc:(.text+0x9545): undefined reference to `curl_easy_strerror'
http_client.cc:(.text+0x9700): undefined reference to `curl_easy_getinfo'
http_client.cc:(.text+0x9708): undefined reference to `curl_slist_free_all'
http_client.cc:(.text+0x9710): undefined reference to `curl_easy_cleanup'
http_client.cc:(.text+0x9790): undefined reference to `curl_easy_setopt'
/workspace/install/lib/libhttpclient_static.a(http_client.cc.o): In function `_GLOBAL__sub_I_http_client.cc':
http_client.cc:(.text.startup+0x6d): undefined reference to `curl_global_init'
collect2: error: ld returned 1 exit status
CMakeFiles/simple_http_health_metadata.dir/build.make:96: recipe for target 'simple_http_health_metadata' failed
make[2]: *** [simple_http_health_metadata] Error 1
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/simple_http_health_metadata.dir/all' failed
make[1]: *** [CMakeFiles/simple_http_health_metadata.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by zl-zhuangli** [comment]
I also encountered the same problem. How do you solve it?
