### ISSUE TITLE
Building Pytorch backend

### ISSUE THREAD

**Issue by gilevir** [triton-inference-server/server#2604]
**Description**
The documentation for building the Pytorch backend is not precise enough.
I want to build the Pytorch backend into the main Triton image (from ngc container version 20.11) ie. extend the main triton image with the pytorch backend which is not present in the 20.11 image (no `pytorch` folder under `/opt/tritonserver/backends`)

The documentation says `Copy over the LibTorch and Torchvision headers and libraries from the PyTorch NGC container into local directories.`

But does not say exactly which headers and librairies neither in which precise local directories.

**Triton Information**
2.5 from container 20.11

**Comment by gilevir** [comment]
Thanks for your answer.
I thought the pytorch backend was not in the 20.11 container because when running interactively the 20.11 docker image, there was no `pytorch` folder under `/opt/tritonserver/backends` 

My main issue is actually to load custom torch ops following [this doc](https://github.com/triton-inference-server/server/blob/master/docs/custom_operations.md#pytorch).
And got an error while loading `libtorch_python.so` (cf my previous issue #2596 )
I am not sure how the the update of `LD_LIBRARY_PATH` can be effective if the mentioned folder does not exists.

**Comment by deadeyegoodwin** [comment]
You need to use the version of the doc that corresponds to your release: https://github.com/triton-inference-server/server/blob/r20.11/docs/custom_operations.md
