### ISSUE TITLE
Model status API should report per-model-instance memory usage

### ISSUE THREAD

**Issue by mrjackbo** [triton-inference-server/server#261]
Would it be possible for the status api also to provide the amount of GPU memory taken by each instance of a model?

**Comment by deadeyegoodwin** [comment]
It will depend on what the backend supports (TF, TRT, etc.). It would be nice but for the most part I don't think the backends are capable of providing that information. I will mark as enhancement.

**Comment by dyastremsky** [comment]
While a per-instance memory usage wouldn't be possible across backends (the approach and feasibility will be framework-dependent), we [recently added per-model memory usage metrics](https://github.com/triton-inference-server/server/pull/5642). You also have more control over metrics now with the [custom metrics feature](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/metrics.md#custom-metrics).
