### ISSUE TITLE
ONNX TensorRT optimization parameters

### ISSUE THREAD

**Issue by Mike20001** [triton-inference-server/server#2613]
I have a model that I converted from onnx to tensorrt using the tensorrt docker image, and I compared it with the onnx model converted using the following configuration in the tritonserver pbtxt:
optimization { execution_accelerators {
gpu_execution_accelerator : [ { name : "tensorrt" } ]
}}

The model converted in tritonserver finishes the conversion faster than the model converted on the tensorrt docker image, but it's inference speed is lower.

Are there any options I can add in the pbtxt to specify workspace size or optimal size of input for tensorrt conversion? Or at the very least I want to know where the onnx-tensorrt conversion is executed in tritonserver so that I can modify it.

**Comment by GuanLuo** [comment]
For ONNX Runtime, the accelerator function is calling ORT's API to invoke its TRT execution provider ([detail](https://github.com/triton-inference-server/onnxruntime_backend/blob/main/src/onnxruntime.cc#L242-L244)). I am not aware that the conversion parameters can be set via ORT APIs.

**Comment by deadeyegoodwin** [comment]
This is tracked by https://github.com/triton-inference-server/onnxruntime_backend/issues/20
