### ISSUE TITLE
[Ask for help & discussion] Understanding shared memory.

### ISSUE THREAD

**Issue by qiuxiafei** [triton-inference-server/server#2617]
As described [here](https://github.com/triton-inference-server/server/blob/master/docs/protocol/extension_shared_memory.md), both system and CUDA shared memory could help to communicate to Triton Server in efficient way. According to my understanding, this works only when client and server locate on the same host. Is is right ?
But I see shared memory API are exposed to HTTP and gRPC layer. Will that help? Taking [this](https://github.com/triton-inference-server/server/blob/master/src/clients/c%2B%2B/examples/simple_http_cudashm_client.cc) as example, `client` calls `RegisterCudaSharedMemory` twice (making 2 RPC call underlying) before calling `Infer`. So may I say, in this case, shared memory improves performance at the cost of 2 extra RPC call? I think RPC calls are much more expensive.

This confuses me a lot, do you have any idea about it ?

Thanks!

**Comment by CoderHam** [comment]
Using shared memory the input (and output) data/tensors are communicated to and from Triton server. However the request to the server still requires an HTTP/GRPC request and response.  
You need not create a new shared memory region for each request. Create a large one, register it in Triton and reuse different sections of it for the I/O of data with Triton server. 
In essence the performance improvement shared memory allows is to send large input data and receive large output data from Triton without them adding network overhead. 
@qiuxiafei I hope this helps answer your questions.

**Comment by qiuxiafei** [comment]
Thanks for your quick reply, @CoderHam !

I think I've got your idea. For large input/output tensor, data transfer dominates network time, the cost of the RPC round-trip become relatively trivial. And the larger the input/output tensor is, the more shared memory gains.

So may I conclude that large input/output tensors benefit from shared memory where small tensors not?
Thanks.

**Comment by tdeng521** [comment]
> Using shared memory the input (and output) data/tensors are communicated to and from Triton server. However the request to the server still requires an HTTP/GRPC request and response.
> You need not create a new shared memory region for each request. Create a large one, register it in Triton and reuse different sections of it for the I/O of data with Triton server.
> In essence the performance improvement shared memory allows is to send large input data and receive large output data from Triton without them adding network overhead.
> @qiuxiafei I hope this helps answer your questions.

Shared memory is generally used in multi process communication, but from the code, httpserver and backend are in the same process. What is the reason for using shared memory in this place? My understanding is that shared memory takes up physical memory, which is more efficient than virtual memory. Is that right?
Thanks

**Comment by deadeyegoodwin** [comment]
The shard memory discussed above is used between a client application and the triton server running on the same system, but they are separate processes. Shared memory is virtual memory, the OS just allows multiple processes to access it...
