### ISSUE TITLE
Triton server crashes with a model converted using tf-trt

### ISSUE THREAD

**Issue by tmorgansl** [triton-inference-server/server#2625]
**Description**
I'm having a problem with triton where sending an inference request to a model converted using tf-trt immediately crashes the server. There are no logs outputted even when I set `--log-verbose=1`. The model I'm trying to convert is a tensorflow 1.x savedmodel file and I followed the steps in your documentation to convert it:

https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html

**Triton Information**
2012

Are you using the Triton container or did you build it yourself? Container

**To Reproduce**
1. Given a tensorflow 1.x savedmodel file, convert it using tf-trt using the following commends

```
from tensorflow.python.compiler.tensorrt import trt_convert as trt
converter = trt.TrtGraphConverter(input_saved_model_dir=input_saved_model_dir)
converter.convert()
converter.save(output_saved_model_dir)
```
2. Add the model files and a new config.pbtxt to the model repository:-
```
max_batch_size : 1
name: "customer_service_tft"
platform: "tensorflow_savedmodel"
```
3. Run the server:-
`docker run --rm -p8000:8000 -p8001:8001 -p8002:8002 -v/mounted/path:/models nvcr.io/nvidia/tritonserver:20.12-py3 tritonserver --model-repository=/models --strict-model-config=false --log-verbose=1`

4. Send a single request, either via GRPC or REST. The logs of the server end with:-
```
I0315 08:19:42.296461 1 infer_request.cc:502] prepared: [0x0x7f39cc003560] request id: , model: customer_service_tft, requested version: 1, actual version: 1, flags: 0x0, correlation id: 0, batch size: 1, priority: 0, timeout (us): 0
original inputs:
[0x0x7f39cc0037e8] input: examples, type: BYTES, original shape: [1,1], batch + shape: [1], shape: []
override inputs:
inputs:
[0x0x7f39cc0037e8] input: examples, type: BYTES, original shape: [1,1], batch + shape: [1], shape: []
original requested outputs:
probabilities
requested outputs:
probabilities

I0315 08:19:42.298726 1 tensorflow.cc:2097] model customer_service_tft, instance customer_service_tft, executing 1 requests
I0315 08:19:42.298766 1 tensorflow.cc:1386] TRITONBACKEND_ModelExecute: Running customer_service_tft with 1 requests
I0315 08:19:42.300285 1 tensorflow.cc:1614] TRITONBACKEND_ModelExecute: input 'examples' is GPU tensor: false
```

This is a demo with using the CPU inference, however the behavior is the same with a T4 cuda setup running in GCP. It's also worth noting that the same model prior to conversion works fine in triton.

**Expected behavior**
The inference request is completed successfully

I suspect I'm missing something really basic, but I can't find anything in the documentation. Any help would be greatly appreciated.

**Comment by CoderHam** [comment]
When you say the model crashes do you mean it segfaults? Can you share the trace?
The tensorflow backend has a optimization, specifically the gpu_execution_accelerator which can be specified as **tensorrt** through which Triton converts a TF model to TF-TRT prior to deploying it. 

This needs to be added to the model configuration for Tritonserver to perform the necessary optimization during model deployment. 
A sample of the same is available below.
```
optimization { execution_accelerators {
  gpu_execution_accelerator : [ {
    name : "tensorrt"
    parameters { key: "precision_mode" value: "FP16" }}]
}}
```

From my understanding the TF backend does not support loading TF-TRT model directly.

**Comment by tmorgansl** [comment]
The server just abruptly ends, there are no error logs or segfault I can see. I turned on `--log-verbose=1` but if you have suggestions for other flags we can try to get more detailed information then I can try that.

I'll try adding that optimization section to my config and let you know how it goes, thanks!

**Comment by tanmayv25** [comment]
@CoderHam  I think we can still use TF-TRT model with TF backend. This definitely looks like a bug.
@tmorgansl  Are you able to run your TFTRT model outside Triton successfully?

**Comment by tmorgansl** [comment]
Apologies for the delay in replying, I think the problem was that it was using all of the ram on the machine. It seems like with and without the tensorrt optimisation @CoderHam suggested, the triton server is using more than 8gb of ram to handle the request when running with a GPU. Is this expected behaviour for a typical BERT model? Before conversion, it would use roughly half of this.

If this is expected I'll close this issue.

@tanmayv25 I tested the converted model in tensorflow and it works fine with no issues

```
req = '...'

graph = tf.Graph()
with graph.as_default():
    with tf.Session() as sess:
        tf.saved_model.loader.load(
            sess,
            [tag_constants.SERVING],
            '/path/to/model')
        
        prediction = graph.get_tensor_by_name('input_tensor:0')
        output = graph.get_tensor_by_name('loss/Softmax:0')
        
        result = sess.run(output, feed_dict={prediction: [req]})
        print(result)
```

**Comment by Ofek-ishay-axon** [comment]
Hey, I also encountered this issue where it seg faults, although mine crashes before the models even loads
Also a tf-trt int8 model  - a classifier so a memory issue would seem quite unlikely.

I would love your help - thanks in advance!

**Comment by dyastremsky** [comment]
Closing this issue due to its age and inactivity. Triton has changed a lot in the last two years.

For any new issues (such as Ofek's) existing in Triton's recent release, please open a new issue following the bug template. We need clear steps to reproduce your issue, including models and filed needed. If you cannot share your model, feel free to use a sample model which reproduces the same issue.

**Comment by anantzoid** [comment]
hi @Ofek-ishay-axon  and @tmorgansl , were you able to resolve this?
