### ISSUE TITLE
TF-TRT Model can't be loaded

### ISSUE THREAD

**Issue by zerapp** [triton-inference-server/server#2627]
**Description**
I trained a model using tensorflow 2.3 and exported it in saved model format. The saved model is loaded by triton and works like a charm even with the automatic mixed precision optimization. Now I wanted to see how much I could improve the performance of the model and thus I tried to convert it with TF-TRT:
```
import copy

import tensorflow as tf
from tensorflow.python.compiler.tensorrt import trt_convert as trt

import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = "3"

def convert():
    """Loads a saved model using a TF-TRT converter, and returns the converter"""
    params = copy.deepcopy(trt.DEFAULT_TRT_CONVERSION_PARAMS)
    params = params._replace(
        precision_mode=trt.TrtPrecisionMode.FP16,
        max_batch_size=8,
        max_workspace_size_bytes=2 << 32,  # 8,589,934,592 bytes
        maximum_cached_engines=100,
        minimum_segment_size=3,
        allow_build_at_runtime=True
    )
    converter = trt.TrtGraphConverterV2(
        input_saved_model_dir="/models/cnn/1/model.savedmodel",
        conversion_params=params,
    )
    converter.convert()
    converter.save("/models/cnn_converted_fp16")

convert()

```
After conversion, with and without a config.pbtxt I get the following error 
`Invalid argument: model output cannot have empty reshape for non-batching model for cnn_converted_fp16`

**Triton Information**
I'm using the container from NGC in version 20.11 and 20.12

**To Reproduce**
___________________
- Export a CNN with tensorflow-2.3 to the saved model format with _input_shape_ _(None, None, 3)_
- Convert it with the code above.
- Place it in the triton models folder **without** a config.pbtxt (I also tried with)
- Triton says model output cannot have empty reshape for non-batching model for cnn_converted_fp16
___________________
- Export a CNN with tensorflow-2.3 to the saved model format and explicitly define _batch_size_ _1_ and _input_shape_ _(2624, 1856, 3)_
- Convert it with the code above.
- Place it in the triton models folder **without** a config.pbtxt (I also tried with)
- Triton loads the models
- perf_analyzer says 
```
Failed to maintain requested inference load. Worker thread(s) failed to generate concurrent requests.
Thread [0] had error: NodeDef mentions attr 'max_batch_size' not in Op<name=TRTEngineOp; signature=in_tensor: -> out_tensor:; attr=serialized_segment:string; attr=segment_func:func,default=[]; attr=InT:list(type),min=1,allowed=[DT_INT8, DT_HALF, DT_FLOAT, DT_INT32]; attr=OutT:list(type),min=1,allowed=[DT_INT8, DT_HALF, DT_FLOAT, DT_INT32]; attr=input_shapes:list(shape),default=[]; attr=max_cached_engines_count:int,default=1; attr=workspace_size_bytes:int; attr=precision_mode:string,allowed=["FP32", "FP16", "INT8"]; attr=calibration_data:string,default=""; attr=use_calibration:bool,default=true; attr=segment_funcdef_name:string,default=""; attr=cached_engine_batches:list(int),default=[],min=0; attr=fixed_input_size:bool,default=true; attr=output_shapes:list(shape),default=[]; attr=static_engine:bool,default=true>; NodeDef: {{node StatefulPartitionedCall/functional_3/conv2d_17/TRTEngineOp_0_9}}. (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	 [[PartitionedCall/PartitionedCall/StatefulPartitionedCall/functional_3/conv2d_17/TRTEngineOp_0_9]]
```

**Expected behavior**
I would expect triton to load the model an to answer the inference requests with better performance.

Thanks a lot for your effort

**Comment by hwaxxer** [comment]
Have the exact same problem and I suspect it's because after TF-TRT conversion, the output signature of the model looks like this (output from `saved_model_cli`):

```
  The given SavedModel SignatureDef contains the following output(s):
    outputs['output'] tensor_info:
        dtype: DT_FLOAT
        shape: unknown_rank
        name: PartitionedCall:0
  Method name is: tensorflow/serving/predict 
```

**Comment by farzanehnakhaee70** [comment]
Is there any suggestion how we can solve this issue?

**Comment by dyastremsky** [comment]
Closing this issue due to its age and inactivity. Triton has changed a lot in the last two years.

For any new issues (such as Ofek's) existing in Triton's recent release, please open a new issue following the bug template. We need clear steps to reproduce your issue, including models and filed needed. If you cannot share your model, feel free to use a sample model which reproduces the same issue.
