### ISSUE TITLE
Error when load model with http api

### ISSUE THREAD

**Issue by a396198172** [triton-inference-server/server#2633]
When POST v2/repository/models/${MODEL_NAME}/load
I got "error": "explicit model load / unload is not allowed if polling is enabled", how can I solve this?
Thx.

**Comment by bezero** [comment]
When starting triton server set `--model-control-mode=explicit`, that should fix your problem. This means, you will manually need to call `v2/repository/models/${MODEL_NAME}/load` and `v2/repository/models/${MODEL_NAME}/unload ` for your models.

**Comment by a396198172** [comment]
> When starting triton server set `--model-control-mode=explicit`, that should fix your problem. This means, you will manually need to call `v2/repository/models/${MODEL_NAME}/load` and `v2/repository/models/${MODEL_NAME}/unload ` for your models.

That works for me, thx! :)

**Comment by gioipv** [comment]
thank @bezero it work for me. I start triton server with not load model to start triton server faster, after that, I load model with command manually
