### ISSUE TITLE
Question of starting serving inside docker

### ISSUE THREAD

**Issue by zyxstudycs** [triton-inference-server/server#2634]
I just started learning Triton and hope someone would answer my question.
In quick start document, I should start docker by "docker run --gpus=1 --rm -p8000:8000 -p8001:8001 -p8002:8002 -v/full/path/to/docs/examples/model_repository:/models nvcr.io/nvidia/tritonserver:20.12-py3 tritonserver --model-repository=/models".
However, as my environment constraint, after pull the image, I can't set "--model-repository=/models" when docker run.
Can I first start docker by "docker run --gpus=1 --rm -p8000:8000 -p8001:8001 -p8002:8002 nvcr.io/nvidia/tritonserver:20.12-py3 tritonserver", and then start server insider docker container later? and how？

**Comment by tanmayv25** [comment]
You can definitely start docker using `docker run --gpus=1 --rm -p8000:8000 -p8001:8001 -p8002:8002 nvcr.io/nvidia/tritonserver:20.12-py3` and then run server  `tritonserver --model-repository=/models`
I am not sure how does this address your constrained environment problem though.
