### ISSUE TITLE
Can't set max batch size when using strict-model-config = false #1466

### ISSUE THREAD

**Issue by daganida88** [triton-inference-server/server#2635]
**Is your feature request related to a problem? Please describe.**
I need to manage hundreds of models and I want triton to create a config file for me each time I deploy a new model.
The problem that it is always set the max_batch_size property to 1, which then causes inference calls to fail because I am trying to make an inference call with a batch size that is greater than one.
Do I have a way to tell Triton what is the desired max batch size?
Or I have to get the config file from the triton server, edit it with the desirable max batch size (which is a lot of headache because it is not a json, it is a protobuf), and push it again so triton will have the updated version?
**Describe the solution you'd like**
Some way to tell triton what is the desirable max batch size when it created the config file for me.

**Describe alternatives you've considered**

**Additional context**

**Comment by tanmayv25** [comment]
Can you share what triton backend you are using?
Try setting just the `max_batch_size:<N>` in the config.pbtxt and let triton's autofiller generate rest of the config for you. The feasibility does depend on the backend being used.

**Comment by daganida88** [comment]
How can i set the max batch size in the config file if I am not the one who creates it?

**Comment by CoderHam** [comment]
I  think what @tanmayv25 is recommending is that you can use the log-verbose=1 flag and to log the model config and manually edit the logged model config to create one with a `max_batch_size: N`. It looks like the autofilled model config does not set the max batch size to 1. 
That being said if the model does store batching information, Triton should be able to autofill the same. What kind of model is it (framework)?

**Comment by daganida88** [comment]
The trition backend I am using is tensorflow, savedmodel file.
"manually edit the logged model config to create one with a max_batch_size: N" : I can't do things like that manually, I have hundreds of models. Is there any way I can send the max batch size to triton somehow instead of manually creating it over and over again?

**Comment by tanmayv25** [comment]
> The trition backend I am using is tensorflow, savedmodel file.

Great.. Then my suggestion above should work.. You don't have to manually edit anything. Provide incomplete config.pbtxt with just `max_batch_size: 8` and triton will use that as max_batch_size filling in the missing infomation like inputs and outputs.

The contents of config.pbtxt:
```
max_batch_size: 8
```

Replace 8 with any max batch size you would like to support..

**Comment by whillas** [comment]
In the documentation it says:

> If the model's batch dimension is the first dimension, and all inputs and outputs to the model have this batch dimension, then Triton can use its dynamic batcher or sequence batcher to automatically use batching with the model. In this case max_batch_size should be set to a value greater-or-equal-to 1 that indicates the maximum batch size that Triton should use with the model.

What does "model's batch dimension is the first dimension" mean? That the first dim of the model has to be -1? None of the examples seem to show this?

**Comment by deadeyegoodwin** [comment]
When max_batch_size is set > 0 Triton assumes the model supports batching and that there is an implicit -1 batch dimension that you do not list in the config.pbtxt. See https://github.com/triton-inference-server/server/issues/2643.

What is the configuration generated by Triton if you don't provide any config.pbtxt at all?

**Comment by daganida88** [comment]
> > The trition backend I am using is tensorflow, savedmodel file.
> 
> Great.. Then my suggestion above should work.. You don't have to manually edit anything. Provide incomplete config.pbtxt with just `max_batch_size: 8` and triton will use that as max_batch_size, automatically filling in the missing information like inputs and outputs.
> 
> The contents of config.pbtxt:
> 
> ```
> max_batch_size: 8
> ```
> 
> Replace 8 with any max batch size you would like to support.. You can easily embed this in a script while setting up model-repository directory.

If this works you managed to solve my problem my friend.. i will check and let you know.

**Comment by whillas** [comment]
Right, thanks @deadeyegoodwin i'll give that a go. Perhaps the documentation should be updated to make this explicit?

**Comment by deadeyegoodwin** [comment]
The following section of the doc talks about this at some length. Let us know if you have specific ways that it can be improved: https://github.com/triton-inference-server/server/blob/master/docs/model_configuration.md#inputs-and-outputs
