### ISSUE TITLE
Label mismatch: value and index in reverse order

### ISSUE THREAD

**Issue by andrea-garritano** [triton-inference-server/server#2636]
**Description**
I am trying to use the _faster_rcnn_inception_v2_ model, downloaded from TensorFlow Model Zoo. (downloaded from: http://download.tensorflow.org/models/object_detection/faster_rcnn_inception_v2_coco_2018_01_28.tar.gz) 

I followed the first part of the guide provided by NVidia (this: https://developer.nvidia.com/blog/deploying-models-from-tensorflow-model-zoo-using-deepstream-and-triton-inference-server/) and followed steps 1 and 2.

This is my _config.pbtxt_ file:

```
name: "faster_rcnn_inception_v2"
platform: "tensorflow_graphdef"
max_batch_size: 9
input [
  {
    name: "image_tensor"
    data_type: TYPE_UINT8
    format: FORMAT_NHWC
    dims: [ 600, 1024, 3 ]
  }
]
output [
  {
    name: "detection_boxes"
    data_type: TYPE_FP32
    dims: [ 100, 4]
    reshape { shape: [100,4] }
  },
  {
    name: "detection_classes"
    data_type: TYPE_FP32
    dims: [ 100 ]
    label_filename: "faster_labels.txt"
  },
  {
    name: "detection_scores"
    data_type: TYPE_FP32
    dims: [ 100 ]
  },
  {
    name: "num_detections"
    data_type: TYPE_FP32
    dims: [ 1 ]
    reshape { shape: [] }
  }
]
# Specify GPU instance.
instance_group {
  kind: KIND_GPU
  count: 1
  gpus: 0
}
```
In the same directory of my _config.pbtxt_ file, I created a _faster_labels.txt_ with the label.

I created an application in C++ using the Nvidia Triton client libraries.
When I try to do the classification, using the _StringData_ function on the _InferResult_ object of output _detection_classes_, I get an incorrect string back.

The documentation says this:

> The format of the returned string will be "**value:index[:label]**", where **index** is the index of the class in the model output tensor, **value** is the value associated with that index in the model output, and the **label** associated with that index is optional.

In my case `value` and `index` are reversed, so the associated labels are wrong.
This seems to be a bug.

**Triton Information**
Triton server version: 2.6.0 (Docker version: nvcr.io/nvidia/tritonserver:20.12-py3)

**Comment by CoderHam** [comment]
Can you share your C++ client or a minimal repro of the issue?

**Comment by deadeyegoodwin** [comment]
Closing. Reopen with additional information if issue is not resolved.
