### ISSUE TITLE
Failed to get device count

### ISSUE THREAD

**Issue by zyxstudycs** [triton-inference-server/server#2640]
Hi, I pulled docker image of 20.12.
Inside docker container, I tried to do: tritonserver --model-repository=/models, as quickStart tell me. But I went throuth several problems:
1. I can't find tritonserver. I fixed it by add "/opt/tritonserver/bin" into my PATH.
2. I got error "unable to load custom library: libcusolver.so.11, no such file..". I fixed it by add "/usr/local/cuda/bin" into my PATH.
3. However, I still get error now: "failed to get device count, GPU metrics will not be available: initialization error". And now I am confused and don't know how to fix it.

I am wondering where the real problem is, It seems that if I pull and run the container right, I should not even encounter problem 1 and 2. Can someone help me?

**Comment by CoderHam** [comment]
This is the 20.12 NGC container correct?
- What docker version are you using?
- Can you run `nvidia-smi` and share the output?

**Comment by zyxstudycs** [comment]
> This is the 20.12 NGC container correct?
> 
> * What docker version are you using?
> * Can you run `nvidia-smi` and share the output?

Thanks for your reply. I pull the image as： docker pull nvcr.io/nvidia/tritonserver:20.12-py3。
This is result from nvidia-smi:
![image](https://user-images.githubusercontent.com/27251199/111580254-3242b500-87f2-11eb-8da4-507dbe2a31a5.png)
This is result from nvcc --version:
![image](https://user-images.githubusercontent.com/27251199/111580655-e04e5f00-87f2-11eb-94d5-f8a5682ba0b0.png)

It seems that cuda version of host driver and container is different. 

As my environment constraint(I am using server environment in the company and I can't adjust my host  driver), It seems I should download previous version of tritonserver. However, when I tried to download it by "docker pull nvcr.io/nvidia/tritonserver:19.12-py3" for example, it shows "manifest for nvcr.io/nvidia/tritonserver:19.12-py3 not found". What should I do now?

**Comment by CoderHam** [comment]
The cuda driver you are using and the cuda version are both outdated. Please look at the Driver Requirements section of the 20.12 release notes here: https://docs.nvidia.com/deeplearning/triton-inference-server/release-notes/rel_20-12.html#rel_20-12

> Release 20.12 is based on NVIDIA CUDA 11.1.1, which requires NVIDIA Driver release 455 or later.  

Please re-open if needed.
