### ISSUE TITLE
Unable to execute model simultaneously on a multi gpu instance.

### ISSUE THREAD

**Issue by daganida88** [triton-inference-server/server#2652]
**Description**
I have a model repository containing 20 models. Since 1 GPU with 16GB can't hold all of them, I expected that if I will use a 4GPU instance (64GB), it will know how to use the GPU's memory to allocate all models and inference those models at the same time.

**Triton Information**
21.02
Are you using the Triton container or did you build it yourself?

I am running on KFServing 0.5 with triton runtime.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
All the models are savedmodel (tensorflow), each one with a config.pbtxt file containing 1 instance and KIND = GPU.

**Expected behavior**
I was expecting to see 4 GPUS, each one loads a different model and so I can make inference requests simultaneously to all models.
Also, you in the docs it says:
"By default, a single execution instance of the model is created for each GPU available in the system."What does it mean When you say a  single execution instance of the model is created for each GPU available in the system?if I have model X and 4 gpus, does it load the model to all GPU's memory? If this is the case it is a big waste, no? 

In case I understand it correct, this is might be a feature request:
it says "In a multi-GPU server, it automatically creates an instance of each model on each GPU. All these increase GPU utilization without any extra coding from the user." . why not creating an instance based on the free GPU memory? that was I can harness the memory of all GPUs. if not I am limited to the number of models I can load to only 1GPU.

**Comment by tanmayv25** [comment]
TensorFlow consumes more dynamic memory when running inference which is not released till the model is unloaded. As, we don't have a way to get this number before hand `creating an instance based on the free GPU memory` is not very advantageous.
However, it looks like you are missing our "gpus" specification from our instance_group. https://github.com/triton-inference-server/server/blob/master/src/core/model_config.proto#L214-L221
This let's you specify on which GPUs you want your model to load. This can be used to distribute the models on your four GPUs. 
We are working on another tool([Model Analyzer](https://github.com/triton-inference-server/model_analyzer)) that can prove beneficial for understanding how to distribute your models.. Unfortunately, the actual model configuration must still be provided by the user.
