### ISSUE TITLE
config.pbtxt for openvino model

### ISSUE THREAD

**Issue by AIengineer** [triton-inference-server/server#2653]
Actually, I spend much time finding document for making config.pbtxt for openvino model successfully. So far, i cannot make it. I have done in onnxruntime_onnx but i stuck at openvino model format. Could anybody complete it before. Could you give a example for this backend ?

**Comment by AIengineer** [comment]
@tanmayv25, Could you help me for this issue, thank you so much

**Comment by tanmayv25** [comment]
It mostly follows as our other backends. Just the parameters provided are little different. Please go through the [README.md](https://github.com/triton-inference-server/openvino_backend) for more info.  Below is the config.pbtxt for resnet50 model:

```
name: "resnet50_int8"
backend: "openvino"
max_batch_size: 4
input [
  {
    format: FORMAT_NCHW
    name: "input_tensor"
    data_type: TYPE_FP32
    dims: [ 3, 224, 224 ]
  }
]
output [
  {
    name: "softmax_tensor"
    data_type: TYPE_FP32
    dims: [ 1001 ]
  }
]

instance_group {
  kind: KIND_CPU
}

parameters: {
key: "SKIP_OV_DYNAMIC_BATCHSIZE"
value: {
string_value:"YES"
}
}
```
