### ISSUE TITLE
What do you support for Multi Tenancy?

### ISSUE THREAD

**Issue by chandrameenamohan** [triton-inference-server/server#2658]
**Description**
I read in your document that there is support for multi tenancy. https://docs.nvidia.com/deeplearning/triton-inference-server/release-notes/rel_18.04.html . I did not see any example or description on how you do this.

**Triton Information**
What version of Triton are you using?
21.02

Are you using the Triton container or did you build it yourself?
I am using triton container

**To Reproduce**
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**

We have multiple customer. They want to use our infrastructure for inferencing their model. We are onboarding triton in our serving layer. I do not find much details on multi-tenancy support. I would like to understand what kind of isolation triton provides for multiple tenant. Can you please explain on following points? 
1. How do you support multi-tenancy? 
2. How do you isolate data when inferencing for the request from multiple tenants?

**Comment by CoderHam** [comment]
From my understanding we do not support multi-tenancy natively in Triton. One workaround (not the best) could be to create N versions of the model exposing one to each tenant and ensure the inferences are sent with corresponding versions.

**Comment by deadeyegoodwin** [comment]
You are looking at very old release notes. Here is the latest version: https://docs.nvidia.com/deeplearning/triton-inference-server/release-notes/rel_21-03.html#rel_21-03

Triton is "just" a CUDA application and can not provide any isolation of the type you describe beyond what CUDA provides. A single CUDA application (like Triton) does not have any isolation between the different tasks it performs on a GPU, so running multiple models from different tenants simultaneously on a single Triton does not provide any isolation between the models. 

I suggest you look into MIG (https://blogs.nvidia.com/blog/2020/05/14/multi-instance-gpus/), GPU virtualization, and perhaps MPS.
