### ISSUE TITLE
Option (flag) to disable `optimized_execution` in pytorch backend

### ISSUE THREAD

**Issue by ioangatop** [triton-inference-server/server#2661]
Option to execute `torch.jit` with the `optimized_execution` set to false, in order to avoid the warm-up and optimisation.

Python counterpart:
```
with torch.jit.optimized_execution(False):
    y = model(x)
```

**Comment by CoderHam** [comment]
@ioangatop can you elaborate what kind of benefits this would bring? We could technically add a model config parameter for disabling optimized execution but I want to know what the motivation for the same is.

**Comment by ioangatop** [comment]
@CoderHam the `optimized_execution` equal number of forward pass to the number of available GPUs to optimise the execution of the model. However, each one of these forward passes can take up to x600% more time, with negligible (if any) gain in speed performance. Thus, it will be nice to have the option to deploy a scripted model without this option.

Example: https://stackoverflow.com/questions/60232846/too-slow-first-run-torchscript-model-and-its-implementation-in-flask

**Comment by 0wu** [comment]
A possible workaround is setup the warmup in triton config, so the slow first run is done during warmup and thus not visible to the real clients.

**Comment by ioangatop** [comment]
Goop point @0wu! However, even though I already have implement a warmup function, because the model expects an input of [0, 255] and the default options are zeros or random, the inference is not carried out till the end (Faster RCNN model), and thus it does not warped up properly. Although I could potentially add a custom file for model inference, I do not prefer it as its an additional overhead during an model export to TorchScript and auto deployment. @CoderHam probably an also good extra feature will be to support more default options for model warmup (int in certain range, str, etc)?

There is also an issue here that states that _traced model with optimization shows no performance improvement_ (https://github.com/pytorch/pytorch/issues/19978).

Thus I believe it will be a useful feature to have, in order to be able to execute the model it a more custom desired way.

**Comment by CoderHam** [comment]
@ioangatop from my reading it appears there is no C++ counterpart for optimized_execution() since the same must be called during the tracing of the pytorch python model to produce the TorchScript model.
```
with torch.jit.optimized_execution(False):
  model = torch.jit.trace(model, inputs)
```
Hence Triton will not be able to disable the optimized execution itself. Could you try the above and see if it solved your problem?

**Comment by CoderHam** [comment]
@ioangatop can you try to build and test the changes from this PR: triton-inference-server/pytorch_backend#24?

**Comment by ioangatop** [comment]
Hi @CoderHam! Will do, I'll let you know. Thanks!

**Comment by tanmayv25** [comment]
Closing the issue as [#24](https://github.com/triton-inference-server/pytorch_backend/pull/24) got merged.
