### ISSUE TITLE
Python gRPC and http clients throw warning when using Python 3.8

### ISSUE THREAD

**Issue by fpertl** [triton-inference-server/server#2668]
**Description**
Python gRPC and http clients throw warning in Python 3.8 
```
/usr/local/lib/python3.8/site-packages/tritonclient/grpc/__init__.py:791: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if name is not "":
/usr/local/lib/python3.8/site-packages/tritonclient/grpc/__init__.py:940: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if name is not "":
/usr/local/lib/python3.8/site-packages/tritonclient/grpc/__init__.py:1186: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if request_id is not "":
```
**Triton Information**
This happens in version 2.7 (r21.02) and master

I build the client libs myself for CentOS7

**To Reproduce**
To reproduce the behavior, run the clients using Python3.8
The error message suggest a fix

**Expected behavior**
No warning is thrown.

**Comment by CoderHam** [comment]
This is a new warning added in Python 3.8 as mentioned inthe [release notes](https://docs.python.org/3.8/whatsnew/3.8.html#changes-in-python-behavior). We can fix this shortly but you can ignore the warning for now.
