### ISSUE TITLE
QuickStart example without the --gpus flag fails for tritonserver:v20.12-py3 and later.

### ISSUE THREAD

**Issue by msjelly** [triton-inference-server/server#2674]
**Description**
QuickStart example without --gpus flag, described [here](https://github.com/triton-inference-server/server/blob/master/docs/quickstart.md#run-on-cpu-only-system), fails as follows for tritonserver:v21.02-py3 and tritonserver:v20.12-py3 with following message "error: creating server: Internal - failed to load all models".

**Triton Information**
What version of Triton are you using?  tritonserver:v21.02-py3

Are you using the Triton container or did you build it yourself?
Triton container  nvcr.io/nvidia/tritonserver:20.10-py3
**To Reproduce**
Steps to reproduce the behavior.
QuickStart example without the --gpus flag, described [here](https://github.com/triton-inference-server/server/blob/master/docs/quickstart.md#run-on-cpu-only-system).
Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
See QuickStart.
**Expected behavior**
TritonServer startup succeeds without --gpus flag and subsequent scoring call as described in QuickStart succeeds.

**Comment by msjelly** [comment]
$ docker run --name test-triton  --rm -p9000:8000 -p9001:8001 -p9002:8002 -v $(pwd)/model_repository:/models nvcr.io/nvidia/tritonserver:21.02-py3 tritonserver --model-repository=/models

=============================
== Triton Inference Server ==
=============================

NVIDIA Release 21.02 (build 20174689)

Copyright (c) 2018-2021, NVIDIA CORPORATION.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use Docker with NVIDIA Container Toolkit to start this container; see
   https://github.com/NVIDIA/nvidia-docker.

I0327 01:23:02.966714 1 libtorch.cc:940] TRITONBACKEND_Initialize: pytorch
I0327 01:23:02.966804 1 libtorch.cc:950] Triton TRITONBACKEND API version: 1.0
I0327 01:23:02.966809 1 libtorch.cc:956] 'pytorch' TRITONBACKEND API version: 1.0
2021-03-27 01:23:03.130571: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
I0327 01:23:03.167470 1 tensorflow.cc:1877] TRITONBACKEND_Initialize: tensorflow
I0327 01:23:03.167520 1 tensorflow.cc:1887] Triton TRITONBACKEND API version: 1.0
I0327 01:23:03.167525 1 tensorflow.cc:1893] 'tensorflow' TRITONBACKEND API version: 1.0
I0327 01:23:03.167529 1 tensorflow.cc:1917] backend configuration:
{}
I0327 01:23:03.169128 1 onnxruntime.cc:1728] TRITONBACKEND_Initialize: onnxruntime
I0327 01:23:03.169152 1 onnxruntime.cc:1738] Triton TRITONBACKEND API version: 1.0
I0327 01:23:03.169156 1 onnxruntime.cc:1744] 'onnxruntime' TRITONBACKEND API version: 1.0
E0327 01:23:03.175862 1 pinned_memory_manager.cc:202] failed to allocate pinned system memory: CUDA driver version is insufficient for CUDA runtime version
E0327 01:23:03.176953 1 model_repository_manager.cc:1682] unexpected platform type caffe2_netdef for resnet50_netdef
I0327 01:23:03.177132 1 model_repository_manager.cc:787] loading: simple:1
I0327 01:23:03.277385 1 model_repository_manager.cc:787] loading: densenet_onnx:1
I0327 01:23:03.277451 1 tensorflow.cc:1977] TRITONBACKEND_ModelInitialize: simple (version 1)
I0327 01:23:03.278443 1 tensorflow.cc:2026] TRITONBACKEND_ModelInstanceInitialize: simple (CPU device 0)
2021-03-27 01:23:03.284674: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2021-03-27 01:23:03.284724: E tensorflow/stream_executor/cuda/cuda_driver.cc:339] failed call to cuInit: UNKNOWN ERROR (303)
2021-03-27 01:23:03.284752: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] no NVIDIA GPU device is present: /dev/nvidia0 does not exist
2021-03-27 01:23:03.304725: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2445415000 Hz
2021-03-27 01:23:03.310294: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7efe2007d360 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-03-27 01:23:03.310370: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
I0327 01:23:03.316391 1 model_repository_manager.cc:960] successfully loaded 'simple' version 1
I0327 01:23:03.377892 1 onnxruntime.cc:1787] TRITONBACKEND_ModelInitialize: densenet_onnx (version 1)
I0327 01:23:03.377953 1 model_repository_manager.cc:787] loading: inception_graphdef:1
I0327 01:23:03.378288 1 onnxruntime.cc:1830] TRITONBACKEND_ModelInstanceInitialize: densenet_onnx (CPU device 0)
WARNING: Since openmp is enabled in this build, this API cannot be used to configure intra op num threads. Please use the openmp environment variables to control the number of threads.
I0327 01:23:03.478182 1 model_repository_manager.cc:787] loading: simple_string:1
I0327 01:23:03.478472 1 tensorflow.cc:1977] TRITONBACKEND_ModelInitialize: inception_graphdef (version 1)
I0327 01:23:03.478985 1 tensorflow.cc:2026] TRITONBACKEND_ModelInstanceInitialize: inception_graphdef (CPU device 0)
I0327 01:23:03.540668 1 model_repository_manager.cc:960] successfully loaded 'inception_graphdef' version 1
I0327 01:23:03.559106 1 model_repository_manager.cc:960] successfully loaded 'densenet_onnx' version 1
I0327 01:23:03.578462 1 tensorflow.cc:1977] TRITONBACKEND_ModelInitialize: simple_string (version 1)
I0327 01:23:03.578928 1 tensorflow.cc:2026] TRITONBACKEND_ModelInstanceInitialize: simple_string (CPU device 0)
I0327 01:23:03.584513 1 model_repository_manager.cc:960] successfully loaded 'simple_string' version 1
I0327 01:23:03.584609 1 server.cc:495]
+-------------+-----------------------------------------------------------------+------+
| Backend     | Config                                                          | Path |
+-------------+-----------------------------------------------------------------+------+
| pytorch     | /opt/tritonserver/backends/pytorch/libtriton_pytorch.so         | {}   |
| tensorflow  | /opt/tritonserver/backends/tensorflow1/libtriton_tensorflow1.so | {}   |
| onnxruntime | /opt/tritonserver/backends/onnxruntime/libtriton_onnxruntime.so | {}   |
+-------------+-----------------------------------------------------------------+------+

I0327 01:23:03.584657 1 server.cc:538]
+--------------------+---------+--------+
| Model              | Version | Status |
+--------------------+---------+--------+
| densenet_onnx      | 1       | READY  |
| inception_graphdef | 1       | READY  |
| simple             | 1       | READY  |
| simple_string      | 1       | READY  |
+--------------------+---------+--------+

I0327 01:23:03.584735 1 tritonserver.cc:1642]
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+
| Option                           | Value                                                                                                                                              |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+
| server_id                        | triton                                                                                                                                             |
| server_version                   | 2.7.0                                                                                                                                              |
| server_extensions                | classification sequence model_repository schedule_policy model_configuration system_shared_memory cuda_shared_memory binary_tensor_data statistics |
| model_repository_path[0]         | /models                                                                                                                                            |
| model_control_mode               | MODE_NONE                                                                                                                                          |
| strict_model_config              | 1                                                                                                                                                  |
| pinned_memory_pool_byte_size     | 268435456                                                                                                                                          |
| min_supported_compute_capability | 6.0                                                                                                                                                |
| strict_readiness                 | 1                                                                                                                                                  |
| exit_timeout                     | 30                                                                                                                                                 |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+

I0327 01:23:03.584746 1 server.cc:220] Waiting for in-flight requests to complete.
I0327 01:23:03.584750 1 model_repository_manager.cc:820] unloading: simple_string:1
I0327 01:23:03.584787 1 model_repository_manager.cc:820] unloading: simple:1
I0327 01:23:03.584832 1 model_repository_manager.cc:820] unloading: inception_graphdef:1
I0327 01:23:03.584867 1 model_repository_manager.cc:820] unloading: densenet_onnx:1
I0327 01:23:03.584874 1 tensorflow.cc:2064] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0327 01:23:03.584905 1 server.cc:235] Timeout 30: Found 4 live models and 0 in-flight non-inference requests
I0327 01:23:03.585087 1 tensorflow.cc:2064] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0327 01:23:03.585079 1 tensorflow.cc:2064] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0327 01:23:03.585079 1 onnxruntime.cc:1864] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0327 01:23:03.585120 1 tensorflow.cc:2003] TRITONBACKEND_ModelFinalize: delete model state
I0327 01:23:03.585183 1 model_repository_manager.cc:943] successfully unloaded 'simple_string' version 1
I0327 01:23:03.585327 1 tensorflow.cc:2003] TRITONBACKEND_ModelFinalize: delete model state
I0327 01:23:03.585445 1 model_repository_manager.cc:943] successfully unloaded 'simple' version 1
I0327 01:23:03.591133 1 onnxruntime.cc:1810] TRITONBACKEND_ModelFinalize: delete model state
I0327 01:23:03.591298 1 model_repository_manager.cc:943] successfully unloaded 'densenet_onnx' version 1
I0327 01:23:03.592059 1 tensorflow.cc:2003] TRITONBACKEND_ModelFinalize: delete model state
I0327 01:23:03.592180 1 model_repository_manager.cc:943] successfully unloaded 'inception_graphdef' version 1
I0327 01:23:04.584994 1 server.cc:235] Timeout 29: Found 0 live models and 0 in-flight non-inference requests
error: creating server: Internal - failed to load all models
E0327 01:23:04.609725 1 cuda_memory_manager.cc:66] Failed to finalize CUDA memory manager: [3] CNMEM_STATUS_NOT_INITIALIZED

**Comment by msjelly** [comment]
Tests were run on Testla T4 with following GPU driver and CUDA version.
$nvidia-smi
Fri Mar 26 21:37:01 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.32.00    Driver Version: 455.32.00    CUDA Version: 11.1     |

**Comment by deadeyegoodwin** [comment]
These are the lines of interest:

E0327 01:23:03.175862 1 pinned_memory_manager.cc:202] failed to allocate pinned system memory: CUDA driver version is insufficient for CUDA runtime version
E0327 01:23:03.176953 1 model_repository_manager.cc:1682] unexpected platform type caffe2_netdef for resnet50_netdef

The first is actually a warning and so should not appear as an error (fixed in the upcoming 21.04 release).
The second line is the actual error. You are trying to load a Caffe2 model but caffe2 is no longer supported. You must be using the example model repository from an old release. If you use the example models from 21.02 you should not hit an error.
