### ISSUE TITLE
How can I run identity_backend on trition

### ISSUE THREAD

**Issue by somelaoda** [triton-inference-server/server#2681]
I clone identity_backend from github and run

"""
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/install ..
make install
"""

to product libtriton_identity.so

then I copy  libtriton_identity.so to /opt/tritonserver/backends/identity/，
change my config.pbtxt to 'backend: "identity"'
just like
“”“
name: "identity"
backend: "identity"
max_batch_size: 1
input {
  name: "input"
  data_type: TYPE_FP32
  dims: 28
}
output {
  name: "output"
  data_type: TYPE_FP32
  dims: 28
}
instance_group {
  count: 1
  kind: KIND_CPU
}
”“”

But Trition didn't find out  identity backend

“”“
I0331 08:02:31.756994 1 custom_backend_factory.cc:46] Create CustomBackendFactory
I0331 08:02:31.756999 1 ensemble_backend_factory.cc:47] Create EnsembleBackendFactory
I0331 08:02:31.757406 1 autofill.cc:138] TensorFlow SavedModel autofill: Internal: unable to autofill for 'identity' due to no version directories
I0331 08:02:31.757418 1 autofill.cc:151] TensorFlow GraphDef autofill: Internal: unable to autofill for 'identity' due to no version directories
I0331 08:02:31.757427 1 autofill.cc:164] PyTorch autofill: Internal: unable to autofill for 'identity' due to no version directories
I0331 08:02:31.757440 1 autofill.cc:196] ONNX autofill: Internal: unable to autofill for 'identity' due to no version directories
I0331 08:02:31.757450 1 autofill.cc:209] TensorRT autofill: Internal: unable to autofill for 'identity' due to no version directories
W0331 08:02:31.757455 1 autofill.cc:248] Proceeding with simple config for now
I0331 08:02:31.757460 1 model_config_utils.cc:637] autofilled config: name: "identity"

E0331 08:02:31.758045 1 model_repository_manager.cc:1937] Poll failed for model directory 'identity': unexpected platform type  for identity
”“”

I really hope someone can help me，our company has tried Torch, TensorFlow, ONNX, Python bckend，all worked very well

**Comment by tanmayv25** [comment]
Which version of Triton are you using? Do you have version directory alongside config.pbtxt?

**Comment by deadeyegoodwin** [comment]
Also, include the entire log output.

**Comment by somelaoda** [comment]
The problem has been solved, identity backend needs to create a version folder with empty inside. It is running smoothly and has the return value.
Thank you very much to the community.

+-------------+-----------------------------------------------------------------+--------+
| Backend     | Path                                                            | Config |
+-------------+-----------------------------------------------------------------+--------+
| pytorch     | /opt/tritonserver/backends/pytorch/libtriton_pytorch.so         | {}     |
| identity    | /opt/tritonserver/backends/identity/libtriton_identity.so       | {}     |
| tensorflow  | /opt/tritonserver/backends/tensorflow1/libtriton_tensorflow1.so | {}     |
| onnxruntime | /opt/tritonserver/backends/onnxruntime/libtriton_onnxruntime.so | {}     |
| openvino    | /opt/tritonserver/backends/openvino/libtriton_openvino.so       | {}     |
+-------------+-----------------------------------------------------------------+--------+

I0401 02:00:54.212003 1 Model_Repository_Manager. Cc :588] BackendStates()
I0401 02:00:54. 212036 1 server. Cc: 570]
+----------+---------+--------+
| Model    | Version | Status |
+----------+---------+--------+
| identity | 1       | READY  |
+----------+---------+--------+

**Comment by somelaoda** [comment]
The problem has been solved, Identity Backend needs to create a version folder with empty inside. It is running smoothly and has the return value.
Thank you very much to the community.

+-------------+-----------------------------------------------------------------+--------+
| Backend     | Path                                                            | Config |
+-------------+-----------------------------------------------------------------+--------+
| pytorch     | /opt/tritonserver/backends/pytorch/libtriton_pytorch.so         | {}     |
| identity    | /opt/tritonserver/backends/identity/libtriton_identity.so       | {}     |
| tensorflow  | /opt/tritonserver/backends/tensorflow1/libtriton_tensorflow1.so | {}     |
| onnxruntime | /opt/tritonserver/backends/onnxruntime/libtriton_onnxruntime.so | {}     |
| openvino    | /opt/tritonserver/backends/openvino/libtriton_openvino.so       | {}     |
+-------------+-----------------------------------------------------------------+--------+

I0401 02:00:54.212003 1 Model_Repository_Manager. Cc :588] BackendStates()
I0401 02:00:54. 212036 1 server. Cc: 570]
+----------+---------+--------+
| Model    | Version | Status |
+----------+---------+--------+
| identity | 1       | READY  |
+----------+---------+--------+

**Comment by woodyexcellent** [comment]
> where to get the modle file for identity?

or it dont need a modle file?

**Comment by tanmayv25** [comment]
@woodyexcellent  you can find identity model from here: https://github.com/triton-inference-server/identity_backend

**Comment by CoderHam** [comment]
One you build the backend into a shared library i.e. `libtriton_identity.so` you can add it to `/opt/tritonserver/backends/identity/.` the and have empty version directories.
