### ISSUE TITLE
How can I get percentile latency metrics (say p99) for online inferencing?

### ISSUE THREAD

**Issue by Bole0331** [triton-inference-server/server#2685]
Hi, we are considering using Triton as model server for online inferencing service. It seems although Triton exposes prometheus metrics, all latency related metrics are cumulative numbers. Is there a way for us to get server side percentile latency metrics in Triton, which is important for online service monitoring.

**Comment by tanmayv25** [comment]
You can use trace as described [here ](https://github.com/triton-inference-server/server/blob/master/docs/trace.md)
to get timestamps for individual request.

**Comment by deadeyegoodwin** [comment]
As @tanmayv25  notes, the only way to get individual request statistics is via the trace interface, which is likely too expense for production use cases. Triton could possibly implement some kind of sliding window over the last 'n' requests and publish percentiles from that... but currently it doesn't have that capability.
