### ISSUE TITLE
Trinton Errror during the initialization of the modell

### ISSUE THREAD

**Issue by romeolandry** [triton-inference-server/server#2688]
I am trying to use [SSD ResNet50 V1 FPN 640x640 (RetinaNet50)](http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_resnet50_v1_fpn_640x640_coco17_tpu-8.tar.gz) whith DeepStream SDK and i can't load tensorflow savedModel the model with Triton. 
**My config.pbtx**
name: "my_ssd"
platform: "tensorflow_savedmodel"
#default_model_filename: "model.savedmodel"
max_batch_size: 0
input [
  {
    name: "input_tensor"
    data_type: TYPE_UINT8
    format: FORMAT_NHWC
    dims: [1,-1,-1 3 ]
  }
]
output [
  {
    name: "detection_boxes"
    data_type: TYPE_FP32
    dims:  [1,100,4]
  },
  {
    name: "detection_classes"
    data_type: TYPE_FP32
    dims: [1,100]
  },
  {
    name: "detection_scores"
    data_type: TYPE_FP32
    dims: [1,100]
  },
  {
    name: "num_detections"
    data_type: TYPE_FP32
    dims:  [1]
  }
]

and savedModel description is:

2021-04-01 10:06:51.864130: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
The given SavedModel SignatureDef contains the following input(s):
  inputs['input_tensor'] tensor_info:
      dtype: DT_UINT8
      shape: (1, -1, -1, 3)
      name: serving_default_input_tensor:0
The given SavedModel SignatureDef contains the following output(s):
  outputs['detection_anchor_indices'] tensor_info:
      dtype: DT_FLOAT
      shape: (1, 100)
      name: StatefulPartitionedCall:0
  outputs['detection_boxes'] tensor_info:
      dtype: DT_FLOAT
      shape: (1, 100, 4)
      name: StatefulPartitionedCall:1
  outputs['detection_classes'] tensor_info:
      dtype: DT_FLOAT
      shape: (1, 100)
      name: StatefulPartitionedCall:2
  outputs['detection_multiclass_scores'] tensor_info:
      dtype: DT_FLOAT
      shape: (1, 100, 91)
      name: StatefulPartitionedCall:3
  outputs['detection_scores'] tensor_info:
      dtype: DT_FLOAT
      shape: (1, 100)
      name: StatefulPartitionedCall:4
  outputs['num_detections'] tensor_info:
      dtype: DT_FLOAT
      shape: (1)
      name: StatefulPartitionedCall:5
  outputs['raw_detection_boxes'] tensor_info:
      dtype: DT_FLOAT
      shape: (1, 51150, 4)
      name: StatefulPartitionedCall:6
  outputs['raw_detection_scores'] tensor_info:
      dtype: DT_FLOAT
      shape: (1, 51150, 91)
      name: StatefulPartitionedCall:7
Method name is: tensorflow/serving/predict

**The error:**
[libprotobuf ERROR /home/gitlab-runner/triton/server/builddir/grpc-repo/src/grpc/third_party/protobuf/src/google/protobuf/text_format.cc:317] Error parsing text-format inference.ModelConfig: 32:20: Expected ",", found "3".
E0401 10:24:03.874703 12870 model_repository_manager.cc:1705] failed to read text proto from /opt/nvidia/deepstream/deepstream-5.1/samples/trtis_model_repo/my_ssd/config.pbtxt
ERROR: Triton: failed to load model my_ssd, triton_err_str:Internal, err_msg:failed to load 'my_ssd', no version is available
ERROR: failed to load model: my_ssd, nvinfer error:NVDSINFER_TRTIS_ERROR
ERROR: failed to initialize backend while ensuring model:my_ssd ready, nvinfer error:NVDSINFER_TRTIS_ERROR
0:00:01.525811355 12870     0x2a842cf0 ERROR          nvinferserver gstnvinferserver.cpp:362:gst_nvinfer_server_logger:<primary-inference> nvinferserver[UID 5]: Error in createNNBackend() <infer_trtis_context.cpp:246> [UID = 5]: failed to initialize trtis backend for model:my_ssd, nvinfer error:NVDSINFER_TRTIS_ERROR
I0401 10:24:03.875000 12870 server.cc:280] Waiting for in-flight requests to complete.
I0401 10:24:03.875036 12870 server.cc:295] Timeout 30: Found 0 live models and 0 in-flight non-inference requests
0:00:01.525947972 12870     0x2a842cf0 ERROR          nvinferserver gstnvinferserver.cpp:362:gst_nvinfer_server_logger:<primary-inference> nvinferserver[UID 5]: Error in initialize() <infer_base_context.cpp:81> [UID = 5]: create nn-backend failed, check config file settings, nvinfer error:NVDSINFER_TRTIS_ERROR
0:00:01.525977139 12870     0x2a842cf0 WARN           nvinferserver gstnvinferserver_impl.cpp:439:start:<primary-inference> error: Failed to initialize InferTrtIsContext
0:00:01.525996670 12870     0x2a842cf0 WARN           nvinferserver gstnvinferserver_impl.cpp:439:start:<primary-inference> error: Config file path: dstest_ssd_nopostprocess.txt
0:00:01.526422354 12870     0x2a842cf0 WARN           nvinferserver gstnvinferserver.cpp:460:gst_nvinfer_server_start:<primary-inference> error: gstnvinferserver_impl start failed
Error: gst-resource-error-quark: Failed to initialize InferTrtIsContext (1): /dvs/git/dirty/git-master_linux/deepstream/sdk/src/gst-plugins/gst-nvinferserver/gstnvinferserver_impl.cpp(439): start (): /GstPipeline:pipeline0/GstNvInferServer:primary-inference:
Config file path: dstest_ssd_nopostprocess.txt

**Comment by GuanLuo** [comment]
```
[libprotobuf ERROR /home/gitlab-runner/triton/server/builddir/grpc-repo/src/grpc/third_party/protobuf/src/google/protobuf/text_format.cc:317] Error parsing text-format inference.ModelConfig: 32:20: Expected ",", found "3
```
This error indicates that your config.pbtxt is not correct, please take a look at the `dims` field of `input_tensor`
