### ISSUE TITLE
[Question] Infer from multiple models simultaneously on a single GPU without lower fps

### ISSUE THREAD

**Issue by poornimajd** [triton-inference-server/server#2698]
**Description**
Sorry to raise it as an issue.This is more of a question
I have two models,one is a TensorRT model and the other is a pytorch model.The tensorRT model requires 2gb of gpu memory (runs at 35 fps) and pytorch needs 0.7 gb of memory(runs at 68 fps).I have a 6gb vram gpu.I tried running the two models simultaneously,by loading it in two different terminals at the same time.The gpu utilization is close to 100%.Memory utilization is around 3gb and the fps of both the models reduces to half of the original value. In this case can triton help me to load these models simultaneously without decrease in the fps? 
I read the docs about triton very briefly,but not sure about the fps decrease.
Any suggestion is greatly appreciated.

**Triton Information**
What version of Triton are you using?
N/A
Are you using the Triton container or did you build it yourself?
N/A

Thank you in advance.

**Comment by deadeyegoodwin** [comment]
You can certainly use triton to load both models onto the same GPU and then serve those models. You may be able to use the dynamic batching or multi-model-instance capabilities of triton to get some performance improvement... but given that you are already at 100% gpu utilization there may not be that much more perf available.
It is no surprising that running 2 models at the same time gives you only half performance for each model when run alone. I would guess that when run alone each model is able to get high gpu utilization.

**Comment by poornimajd** [comment]
Thanks for the reply!!

> It is no surprising that running 2 models at the same time gives you only half performance for each model when run alone. I would guess that when run alone each model is able to get high gpu utilization.

Yeah,one of the model uses gpu 93% of the time and the other model uses gpu for about 60% of the time.I think this is the reason I get a decrease in fps right,because the gpu is trying to allocate the resources to both and hence there is a decrease in fps eventually.Is this correct?

In this situation would you suggest anything so that the models can be run in parallel?I tried tensorRT optimization,but does not address this issue.

Thanks a lot.

**Comment by aman-cc** [comment]
> Thanks for the reply!!
> 
> > It is no surprising that running 2 models at the same time gives you only half performance for each model when run alone. I would guess that when run alone each model is able to get high gpu utilization.
> 
> Yeah,one of the model uses gpu 93% of the time and the other model uses gpu for about 60% of the time.I think this is the reason I get a decrease in fps right,because the gpu is trying to allocate the resources to both and hence there is a decrease in fps eventually.Is this correct?
> 
> In this situation would you suggest anything so that the models can be run in parallel?I tried tensorRT optimization,but does not address this issue.
> 
> Thanks a lot.

Hi @poornimajd, I have the exact situation and trying to run both models in parallel but not working. Did you find a way to make two models work in parallel?

**Comment by poornimajd** [comment]
No I was not able to solve the issue.
