### ISSUE TITLE
c# .net5

### ISSUE THREAD

**Issue by botao1995** [triton-inference-server/server#2699]
I've recently migrated from pytorch tensorrt engine Serving to NVIDIA Triton as it's much faster and suits my purposes better.

All my applications are in C# .NET Core.
Can we provide relevant use cases for this?

**Comment by sunhailin-Leo** [comment]
@botao1995 
* I think you can use HTTP to request 的 Triton Server

**Comment by botao1995** [comment]
> @botao1995
> 
> * I think you can use HTTP to request Triton Server

Is there a delay in using HTTP or grpc?

**Comment by sunhailin-Leo** [comment]
@botao1995 
* After my testing, HTTP and GRPC are almost similar.
* If you want to use GRPC，i think you can refer the Golang use cases.

**Comment by botao1995** [comment]
> @botao1995
> 
> * After my testing, HTTP and GRPC are almost similar.
> * If you want to use GRPC，i think you can refer the Golang use cases.



> @botao1995
> 
> * After my testing, HTTP and GRPC are almost similar.
> * If you want to use GRPC，i think you can refer the Golang use cases.
Is HTTP or grpc call slower than native？

**Comment by sunhailin-Leo** [comment]
@botao1995 
* Native you means what？

**Comment by botao1995** [comment]
> @botao1995
> 
> * Native you means what？
我的意思是，tensorrt triton服务器部署，使用http或者grpc响应能否和 使用tensorrt部署延迟一致？

**Comment by deadeyegoodwin** [comment]
If you are not using Python or C++, the easiest route to create a client is to generate one using the grpc tools. There are examples of how to do this for both golang and java/scala and based on that you can do something similar for C#
