### ISSUE TITLE
set_data_from_numpy hangs with image data

### ISSUE THREAD

**Issue by gvashishtha** [triton-inference-server/server#2702]
**Description**
I'm trying to send an image as a BYTES array to a Python model. Unfortunately my client never seems to finish the `set_data_from_numpy` step.

**Triton Information**
What version of Triton are you using?
Client: 2.1.0, container 20.11
Are you using the Triton container or did you build it yourself?
Triton Container
**To Reproduce**
Steps to reproduce the behavior.

import numpy as np
import requests
import io
from PIL import Image

import tritonclient.http as tritonhttpclient

headers = {"Content-Type": "application/octet-stream"}
```
test_sample = requests.get("https://aka.ms/peacock-pic", allow_redirects=True).content
img = Image.open(io.BytesIO(test_sample))
test=np.array(img, dtype=np.object_)
input = tritonhttpclient.InferInput('img_in_bytes', test.shape, 'BYTES')
input.set_data_from_numpy(test, binary_data=True)
inputs = [input]
client = tritonhttpclient.InferenceServerClient("localhost:8000")
outputs = [tritonhttpclient.InferRequestedOutput('date_0')]
client.infer(model_name='densenet_preprocess', inputs=inputs, request_id='1', outputs=outputs)
```

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

Config file:

```
name: "densenet_preprocess"
backend: "python"

input [
  {
    name: "img_in_bytes"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]
output [
  {
    name: "data_0"
    data_type: TYPE_FP32
    dims: [ 1, 3, 224, 224 ]
  }
]

instance_group [{ kind: KIND_CPU }]
```
Dockerfile:
```
FROM nvcr.io/nvidia/tritonserver:20.11-py3

RUN pip install Pillow
CMD tritonserver --model-repository=/models --strict-model-config=false --log-verbose=1
```
**Expected behavior**
When I try running the client code above, I expect it to finish executing promptly.

**Comment by CoderHam** [comment]
@gvashishtha can you repeat these test with the latest Triton release?

**Comment by gvashishtha** [comment]
Sure I can give this a shot. Ended up just doing binary_data=False and it worked somehow so this issue is not as urgent. Closing for now.
