### ISSUE TITLE
new C++ client file

### ISSUE THREAD

**Issue by hanyanLWD** [triton-inference-server/server#2719]
**Description**
I want to add a new file to c++ client,but i can not compile it
**Triton Information**
docker : nvcr.io/nvidia/tritonserver :20.03-py3-clientsdk
code:r20.03

Are you using the Triton container or did you build it yourself?

**To Reproduce**
1. first. like "server-r20.03/src/clients/c++/examples/image_client.cc", i add a file name "my_classifier.cc" in "server-r20.03/src/clients/c++/examples/"
2. second.modify "/home/hanyan/hy/jicheng/trion/server-r20.03/src/clients/c++/examples/CMakeLists.txt" add 
#
# hy_classify
#
find_package(OpenCV REQUIRED)
add_executable(hy_classify hy_classify.cc)
target_include_directories(hy_classify PRIVATE ${OpenCV_INCLUDE_DIRS})
target_link_libraries(
  hy_classify
  PRIVATE TRTIS::request_static
  PRIVATE ${OpenCV_LIBS}
)
install(
  TARGETS hy_classify
  RUNTIME DESTINATION bin
)

3. cd "/home/hanyan/hy/jicheng/trion/server-r20.03/src/clients/c++"
    mkdir build
    cd  build
    cmake ..
i got error:
No VERSION specified for WRITE_BASIC_CONFIG_VERSION_FILE()
Objects of target "grpc-library" referenced but no such target exists.
 Objects of target "grpc-library" referenced but no such target exists.

**Expected behavior**
if i want compile c++ client, how to do????

**Comment by tanmayv25** [comment]
In order to build client examples, you have to build them along with client libraries. Please follow the instructions here: https://github.com/triton-inference-server/server/blob/r20.03/docs/client.rst#build-using-cmake
