### ISSUE TITLE
is_server_live results in connection reset

### ISSUE THREAD

**Issue by gvashishtha** [triton-inference-server/server#2725]
**Description**
I have an https endpoint serving Triton that I can get 200 responses from with curl, i.e.:
```
curl -v https://gopalv-custom-container2.westus2-main.inference.ml.azure.com/v2/health/live -H "Authorization: Bearer <token here>"
```
But when I try accessing it from the Python client, i.e.
```
client = tritonhttpclient.InferenceServerClient("gopalv-custom-container2.westus2-main.inference.ml.azure.com", ssl=True)
headers = {'Authorization': 'Bearer <token here>'}
client.is_server_live(headers=headers)
```

I get 

```
Traceback (most recent call last):  File "/home/gopalv/miniconda3/envs/azureml/lib/python3.7/site-packages/geventhttpclient/connectionpool.py", line 163, in get_socket    return self._socket_queue.get(block=False)  File "src/gevent/queue.py", line 334, in gevent._gevent_cqueue.Queue.get  File "src/gevent/queue.py", line 349, in gevent._gevent_cqueue.Queue.get  File "src/gevent/queue.py", line 318, in gevent._gevent_cqueue.Queue._Queue__get_or_peek
    
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gopalv/miniconda3/envs/azureml/lib/python3.7/site-packages/tritonclient/http/__init__.py", line 335, in is_server_live
    query_params=query_params)
  File "/home/gopalv/miniconda3/envs/azureml/lib/python3.7/site-packages/tritonclient/http/__init__.py", line 256, in _get
    response = self._client_stub.get(request_uri, headers=headers)
  File "/home/gopalv/miniconda3/envs/azureml/lib/python3.7/site-packages/geventhttpclient/client.py", line 266, in get
    return self.request(METHOD_GET, request_uri, headers=headers)
  File "/home/gopalv/miniconda3/envs/azureml/lib/python3.7/site-packages/geventhttpclient/client.py", line 226, in request
    sock = self._connection_pool.get_socket()
  File "/home/gopalv/miniconda3/envs/azureml/lib/python3.7/site-packages/geventhttpclient/connectionpool.py", line 166, in get_socket
    return self._create_socket()
  File "/home/gopalv/miniconda3/envs/azureml/lib/python3.7/site-packages/geventhttpclient/connectionpool.py", line 127, in _create_socket
    raise first_error
  File "/home/gopalv/miniconda3/envs/azureml/lib/python3.7/site-packages/geventhttpclient/connectionpool.py", line 114, in _create_socket
    sock = self._connect_socket(sock, sock_info[-1])
  File "/home/gopalv/miniconda3/envs/azureml/lib/python3.7/site-packages/geventhttpclient/connectionpool.py", line 248, in _connect_socket
    return gevent.ssl.wrap_socket(sock, **ssl_options)
  File "/home/gopalv/miniconda3/envs/azureml/lib/python3.7/site-packages/gevent/_ssl3.py", line 798, in wrap_socket
    ciphers=ciphers)
  File "/home/gopalv/miniconda3/envs/azureml/lib/python3.7/site-packages/gevent/_ssl3.py", line 311, in __init__
    raise x
  File "/home/gopalv/miniconda3/envs/azureml/lib/python3.7/site-packages/gevent/_ssl3.py", line 307, in __init__
    self.do_handshake()
  File "/home/gopalv/miniconda3/envs/azureml/lib/python3.7/site-packages/gevent/_ssl3.py", line 663, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer
```
**Triton Information**
tritonclient==2.8.0
triton version = 20.11

Using the NVIDIA Triton container.

**To Reproduce**
Steps to reproduce the behavior.

Not including config file since this behavior is not model-specific.

**Expected behavior**
is_server_live() should return True

**Comment by deadeyegoodwin** [comment]
Can you turn on verbose mode in the tritonhttpclient to see what additional output is generated.

**Comment by gvashishtha** [comment]
All it prints out is:

GET /v2/health/live, headers {'Authorization': 'Bearer <token>'}

and then I get the same stack trace. Will send the token to Mahan via email if you want to try some debugging on your side

**Comment by tanmayv25** [comment]
@gvashishtha  If you can provide a minimal repro instructions then I can take look into what's failing.

**Comment by tanmayv25** [comment]
So, I was able to reproduce the issue and collect ssldumps.
- [tritionclient_ssldump.txt](https://github.com/triton-inference-server/server/files/6328250/tritionclient_ssldump.txt)
- [curl_ssldump.txt](https://github.com/triton-inference-server/server/files/6328251/curl_ssldump.txt)
The difference can be seen below:
![ssldump](https://user-images.githubusercontent.com/10909321/115093681-c65e8400-9f38-11eb-92f7-c746c823ef95.JPG)

tritonclient uses geventhttpclientlib library. I added server_hostname keyword in the wrap_socket in the file `gevent/_ssl3.py`  and was able to interact with the server. This change allowed me to add server_name extension in the ClientHello.

I got the following response which means authorization was failed: 
```
<HTTPSocketPoolResponse status=401 headers={'azureml-model-deployment': 'triton3', 'content-length': '14', 'content-type': 'text/plain', 'date': 'Fri, 16 Apr 2021 23:27:16 GMT', 'server': 'azureml-frontdoor'}>
```

When compared to curl we are still missing the following two extensions:
- next_protocol_negotiation
- application_layer_protocol_negotiation

Evidently, the gevent python library appears to not support such cases. Otherwise, they would have wrapped server_hostname to  the socket. I will open a issue with geventhttpclient project after some research.

**Comment by tanmayv25** [comment]
I looked into gevent library and found a solution that should work.

```
import tritonclient.http as tritonhttpclient
import gevent.ssl

headers = {"Authorization": "Bearer  <access_token>"}
client = tritonhttpclient.InferenceServerClient("gopalv-custom-container2.westus2-main.inference.ml.azure.com", ssl=True, ssl_context_factory=gevent.ssl._create_default_https_context, verbose=True)
client.is_server_live(headers=headers)

```

Note the additional `ssl_context_factory` option. I am seeing 401 error on both python and curl calls:

**Python:**
`<HTTPSocketPoolResponse status=401 headers={'azureml-model-deployment': 'triton3', 'content-length': '14', 'content-type': 'text/plain', 'date': 'Mon, 19 Apr 2021 10:00:29 GMT', 'server': 'azureml-frontdoor'}>`

**CURL**
```
* old SSL session ID is stale, removing
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< azureml-model-deployment: triton3
< content-length: 14
< content-type: text/plain
< date: Mon, 19 Apr 2021 10:07:24 GMT
< server: azureml-frontdoor
```
The JWT of the token seems to be expired. Can you try the above solution and let me know if this works for you?

**Comment by gvashishtha** [comment]
It works! Thank you very much, @tanmayv25 !

**Comment by 1994sugar** [comment]
> **Description** I have an https endpoint serving Triton that I can get 200 responses from with curl, i.e.:
> 
> ```
> curl -v https://gopalv-custom-container2.westus2-main.inference.ml.azure.com/v2/health/live -H "Authorization: Bearer <token here>"
> ```
> 
> But when I try accessing it from the Python client, i.e.
> 
> ```
> client = tritonhttpclient.InferenceServerClient("gopalv-custom-container2.westus2-main.inference.ml.azure.com", ssl=True)
> headers = {'Authorization': 'Bearer <token here>'}
> client.is_server_live(headers=headers)
> ```
> 
> I get
> 
> ```
> Traceback (most recent call last):  File "/home/gopalv/miniconda3/envs/azureml/lib/python3.7/site-packages/geventhttpclient/connectionpool.py", line 163, in get_socket    return self._socket_queue.get(block=False)  File "src/gevent/queue.py", line 334, in gevent._gevent_cqueue.Queue.get  File "src/gevent/queue.py", line 349, in gevent._gevent_cqueue.Queue.get  File "src/gevent/queue.py", line 318, in gevent._gevent_cqueue.Queue._Queue__get_or_peek
>     
> _queue.Empty
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/gopalv/miniconda3/envs/azureml/lib/python3.7/site-packages/tritonclient/http/__init__.py", line 335, in is_server_live
>     query_params=query_params)
>   File "/home/gopalv/miniconda3/envs/azureml/lib/python3.7/site-packages/tritonclient/http/__init__.py", line 256, in _get
>     response = self._client_stub.get(request_uri, headers=headers)
>   File "/home/gopalv/miniconda3/envs/azureml/lib/python3.7/site-packages/geventhttpclient/client.py", line 266, in get
>     return self.request(METHOD_GET, request_uri, headers=headers)
>   File "/home/gopalv/miniconda3/envs/azureml/lib/python3.7/site-packages/geventhttpclient/client.py", line 226, in request
>     sock = self._connection_pool.get_socket()
>   File "/home/gopalv/miniconda3/envs/azureml/lib/python3.7/site-packages/geventhttpclient/connectionpool.py", line 166, in get_socket
>     return self._create_socket()
>   File "/home/gopalv/miniconda3/envs/azureml/lib/python3.7/site-packages/geventhttpclient/connectionpool.py", line 127, in _create_socket
>     raise first_error
>   File "/home/gopalv/miniconda3/envs/azureml/lib/python3.7/site-packages/geventhttpclient/connectionpool.py", line 114, in _create_socket
>     sock = self._connect_socket(sock, sock_info[-1])
>   File "/home/gopalv/miniconda3/envs/azureml/lib/python3.7/site-packages/geventhttpclient/connectionpool.py", line 248, in _connect_socket
>     return gevent.ssl.wrap_socket(sock, **ssl_options)
>   File "/home/gopalv/miniconda3/envs/azureml/lib/python3.7/site-packages/gevent/_ssl3.py", line 798, in wrap_socket
>     ciphers=ciphers)
>   File "/home/gopalv/miniconda3/envs/azureml/lib/python3.7/site-packages/gevent/_ssl3.py", line 311, in __init__
>     raise x
>   File "/home/gopalv/miniconda3/envs/azureml/lib/python3.7/site-packages/gevent/_ssl3.py", line 307, in __init__
>     self.do_handshake()
>   File "/home/gopalv/miniconda3/envs/azureml/lib/python3.7/site-packages/gevent/_ssl3.py", line 663, in do_handshake
>     self._sslobj.do_handshake()
> ConnectionResetError: [Errno 104] Connection reset by peer
> ```
> 
> **Triton Information** tritonclient==2.8.0 triton version = 20.11
> 
> Using the NVIDIA Triton container.
> 
> **To Reproduce** Steps to reproduce the behavior.
> 
> Not including config file since this behavior is not model-specific.
> 
> **Expected behavior** is_server_live() should return True

grpc client meet the same question...

**Comment by tanmayv25** [comment]
@1994sugar Can you create a new github issue with all the details?
