### ISSUE TITLE
Question about the relationship between multiple instances and GPU usage

### ISSUE THREAD

**Issue by chanwook19** [triton-inference-server/server#2727]
In the document, I understood that when multiple instances are used, the copies of model are copied to the GPU memory. However when I use the model analyzer, the GPU memory being used is the same. I am curious about what happens to GPU usage when using multiple instances, and how it affects GPU memory and utilization.

**Comment by Tabrizian** [comment]
If you have multiple instances and there are multiple requests coming into your model, GPU utilization and memory usage should be higher compared to the single model instance case. Can you share the configuration that you are using with model analyzer?

**Comment by chanwook19** [comment]
Here is the configuration.
`name: "SE-DKT+"
platform: "tensorflow_savedmodel"
max_batch_size: 32

input [
  {
    name: "inputs"
    data_type: TYPE_INT32
    dims: [ 10 , 2]
  },
  {
    name: "input_c_state"
    data_type: TYPE_FP32
    dims: [ 200]
  },
  {
    name: "input_h_state"
    data_type: TYPE_FP32
    dims: [ 200]
  }
]
output [
  {
    name: "preds"
    data_type: TYPE_FP32
    dims: [ 544 ]
  },
  {
    name: "output_c_state"
    data_type: TYPE_FP32
    dims: [ 200 ]
  },
  {
    name: "output_h_state"
    data_type: TYPE_FP32
    dims: [ 200 ]
  }
]
instance_group [
  {
    count: 4
    kind: KIND_GPU
    gpus: [ 0 ]
  }
]
dynamic_batching {
  preferred_batch_size: [ 4 ]
}`

And also, I have another question.

There is a problem with the GPU memory usage when using the model analyzer.
When I fixed the input batch size to 1 and change the concurrency, the memory usage was about 1000MB in the concurrency 256.
However, when I gave the batch size to 1, 2, 4, 8, 16, 32, the memory usage was 5000MB in the concurrency 256 and batch size 1.
Is this because Triton server set the GPU usage with batch size 32 and ran batch size 1? Does GPU usage mean the memory currently being used, including other programs?

![image](https://user-images.githubusercontent.com/80809874/114843223-91591100-9e14-11eb-9f67-be5c0c79377e.png)
![image](https://user-images.githubusercontent.com/80809874/114843309-a5047780-9e14-11eb-8e8c-7023ea08b3a3.png)

**Comment by Tabrizian** [comment]
This is a known issue in Model Anaylzer. The problem is that some frameworks do not release GPU memory even if the GPU memory is not being used. Because Model Analyzer does not restart the triton server when trying a single model configuration, if the framework does not release the GPU memory it will be accumulated for all the concurrency and batch size values for that model configuration. For now, you can try running a single batch size value for the sweep but I agree that it is not ideal.
