### ISSUE TITLE
Add trtorch backend

### ISSUE THREAD

**Issue by seed93** [triton-inference-server/server#2735]
Is there any plan to add a [TRTorch](https://github.com/NVIDIA/TRTorch) backend?

**Comment by deadeyegoodwin** [comment]
Triton supports TorchScript models. Have you tried running a TorchScript model that was produced with trtorch?

**Comment by seed93** [comment]
No we can't. According to [TRTorch](https://nvidia.github.io/TRTorch/tutorials/runtime.html), we have to import or link trtorch in python/c++, and this is the only thing we need to do.

**Comment by seed93** [comment]
Additionally, currently pytorch_backend doesn't support fp16 datatype, which is the main datatype for trtorch. Could we add trtorch and fp16 based upon pytorch_backend?

**Comment by MatthieuTPHR** [comment]
Adding TRTorch would be amazing

**Comment by tanmayv25** [comment]
The enhancement is being tracked here: https://github.com/triton-inference-server/pytorch_backend/pull/44
