### ISSUE TITLE
grpc java client 

### ISSUE THREAD

**Issue by zhoujiang2013** [triton-inference-server/server#2739]
when i use grpc java client follow the doc: https://github.com/triton-inference-server/client/tree/main/src/java
i got the errors:

1)inference/GrpcService.java

line:           if (parameters_ == null) {
            return com.google.protobuf.MapField.emptyMapField(
                ParametersDefaultEntryHolder.defaultEntry);
          }
          return parameters_;
        }

error: 
Reference to 'ParametersDefaultEntryHolder' is ambiguous, both 'inference.GrpcService.ModelInferRequest.InferInputTensor.ParametersDefaultEntryHolder' and 'inference.GrpcService.ModelInferRequest.ParametersDefaultEntryHolder' match

2) inference/ModelConfigOuterClass.java

line:
            internalGetInput() {
              if (input_ == null) {
                return com.google.protobuf.MapField.emptyMapField(
                    InputDefaultEntryHolder.defaultEntry);
              }
              return input_;
            }

error:

Reference to 'InputDefaultEntryHolder' is ambiguous, both 'inference.ModelConfigOuterClass.ModelOptimizationPolicy.Cuda.GraphSpec.LowerBound.InputDefaultEntryHolder' and 'inference.ModelConfigOuterClass.ModelOptimizationPolicy.Cuda.GraphSpec.InputDefaultEntryHolder' match

How can i solve the problems, look forward for your help

**Comment by deadeyegoodwin** [comment]
We test the java client here: https://github.com/triton-inference-server/server/blob/master/qa/L0_client_java/test.sh
Note that the clients have recently moved to the client repo: https://github.com/triton-inference-server/client
Can you try running that test and/or compare it to what you are doing and see if you can determine what is happening. Note that if you want to run the test locally you will need to follow these steps: https://github.com/triton-inference-server/server/blob/master/docs/test.md
