### ISSUE TITLE
[Question] Flask integration with Python HTTP Client

### ISSUE THREAD

**Issue by gilevir** [triton-inference-server/server#2744]
Hello,

I wanted to have more insights on the the client development side of Triton.
In our specific use case, we decided to build a flask server acting as a relay for incoming requests to Triton, meaning we have integrated the Triton Python HTTP client inside a Flask app.

The main reasons why we have choose this design is :
- We need to expose dedicated endpoint to some other clients (possibly thousands of them)
- We need some python processing of incoming request before sending them to Triton
- We need connexion to an external storage (GCS) in between receiving & sending requests to Triton

The flask app contains multiple endpoints, each sending an inference request to Triton for a different model.
The first question we had to tackle is how do we integrate the InferenceServerClient into the flask app.

Since the doc explicitely say :
```
An InferenceServerClient object is used to perform any kind of communication 
with the InferenceServer using http protocol. None of the methods are thread safe. 
The object is intended to be used by a single thread and simultaneously calling 
different methods with different threads is not supported and will cause undefined behavior.
```
...and since Flask is creating a new thread for each incoming request, we decided to initialize a new `InferenceServerClient` object into each endpoint. Thus, how can we leverage then the `concurrency` parameter of the triton client ? It seems that going from concurrency 1 to 2 doesn't make any differences on several metrics.

As we want to optimize the whole architecture there are still questions regarding this choice.
- Is it generally a good practice to integrate the Triton Python HTTP client into a Flask Server ?
- Is there any other options (frameworks, design) to meet our need in this case ?

Thanks a lot for your insights 

**Triton Information**
v2.5.0 from  r20.11

**Comment by deadeyegoodwin** [comment]
@tanmayv25  Do you have any additional feedback?

**Comment by tanmayv25** [comment]
I completely agree with @deadeyegoodwin. Using `[async_infer](https://github.com/triton-inference-server/client/blob/main/src/python/library/tritonclient/http/__init__.py#L1157)` will allow utilizing `concurrency` parameter. Using grpc client will allow to share the InferenceServerClient object.

**Comment by gilevir** [comment]
Hi, thanks for your feedbacks.

On our API design, we are creating a new `InferenceServerClient` for each request so I understand that there is no need to increase the `concurrency` parameter.

But, would it change something to call `async_infer` instead of `infer` on the servers point of view ? Even if for each new client creating we send only one inference request ?

We are using the HTTP client. Is GRPC more suitable when dealing with high concurrency ?

Thanks

**Comment by deadeyegoodwin** [comment]
If you are only sending a single request with the InferenceServerClient object then sync_infer vs. async_infer should not have any different behavior on the server side. For your case I would not expect GRPC to be significantly better but it should be easy to experiment and see.

You can use the perf_analyzer with Triton to get some indication of the maximum throughput and minimum latency you can expect.
