### ISSUE TITLE
use python backend to add Huggingface Transformers example?

### ISSUE THREAD

**Issue by gyin-ai** [triton-inference-server/server#2747]
Can we add an example for python backend to serve Huggingface Transformers text generation model where generation utils can't be exported to torchscript or tf saved model yet? Similar to torch serve and ray serve examples.

**Comment by gyin-ai** [comment]
https://github.com/pytorch/serve/blob/master/examples/Huggingface_Transformers/README.md

**Comment by gyin-ai** [comment]
@Tabrizian wondering whether we have measured the overhead using python backend instead of tensorflow backend or pytorch backend directly. How many extra time would it take?

**Comment by Tabrizian** [comment]
@gyin-ai We have not measured this for models but we have measured the input/output overhead. Recently, we have significantly improved the performance of Python backend and now it almost has the same performance as other backends. These changes will be included in 21.04 release but you can build the backend yourself too.

Were you able to run Hugging Face examples in Python backend? If so, can you share a PR?

**Comment by gyin-ai** [comment]
Yes. Huggingface examples can work. Can I ask when we would expect the 21.04 docker image would be released? When I build it by myself, I saw the following message even if the tag version is set to be r21.04.

```
backend "ensemble" at tag/branch "main"
backend "tensorrt" at tag/branch "main"
```

**Comment by philschmid** [comment]
@gyin-ai did you manage to deploy a `transformers` using the `python_backend`? If yes would mind sharing the code?

**Comment by cat-ross-0401** [comment]
I have tried it with python backend for huggingface transformers. It can work. Would try to add the code example during the daytime.

**Comment by Tabrizian** [comment]
The command to build was shared in https://github.com/triton-inference-server/server/issues/2763. 21.04 will be released shortly.

**Comment by Tabrizian** [comment]
21.04 was released today.

**Comment by philschmid** [comment]
@cat-ross-0401 did you find the time to add the code example? if yes could you point me to it?
