### ISSUE TITLE
No error log for failed request.

### ISSUE THREAD

**Issue by Bole0331** [triton-inference-server/server#2748]
Hi, I use python backend and cannot see error log for failed request. I added `assert  True == False` in `model.py` and tried both `--log-verbose=true` and `--log-error=true` while starting Triton server, but there was no error message. Although we do see below error message from client side:
```
{"error":"GRPC Execute Failed, message: Traceback (most recent call last):\n  File \"/opt/tritonserver/backends/python/startup.py\", line 273, in Execute\n    responses = self.model_instance.execute(inference_requests)\n  File \"/tmp/foldermnmGuh/1/model.py\", line 59, in execute\n    assert True == False\nAssertionError\n"}
Process finished with exit code 0
```
Any thoughts and how can I see per request level error log?

**Comment by Tabrizian** [comment]
The response to the request contains the error as you have mentioned but we currently do not log the error on the Python backend side.

**Comment by Bole0331** [comment]
can you point out where can I log the error (the error msg in response) in Triton front-end code?

**Comment by Tabrizian** [comment]
https://github.com/triton-inference-server/python_backend/blob/f1a6e1100ac7a9241862e55a42ca99695a7778e0/src/python.cc#L729 This is the link to the place where we send the error back in 21.03 release.

**Comment by Bole0331** [comment]
Thanks, this is good. Then I can just use 21.03 release.

**Comment by Bole0331** [comment]
thanks, this is what I need.
