### ISSUE TITLE
metrics about Count and Latency

### ISSUE THREAD

**Issue by hanyanLWD** [triton-inference-server/server#2755]
**Description**
use curl localhost:8002/metrics,but i can not get Count and Latency

**Triton Information**
20.03

Are you using the Triton container or did you build it yourself?
 using the Triton container

I get the result:
curl localhost:8002/metrics
# HELP nv_inference_request_success Number of successful inference requests, all batch sizes
# TYPE nv_inference_request_success counter
# HELP nv_inference_request_failure Number of failed inference requests, all batch sizes
# TYPE nv_inference_request_failure counter
# HELP nv_inference_count Number of inferences performed
# TYPE nv_inference_count counter
# HELP nv_inference_exec_count Number of model executions performed
# TYPE nv_inference_exec_count counter
# HELP nv_inference_request_duration_us Cummulative inference request duration in microseconds
# TYPE nv_inference_request_duration_us counter
# HELP nv_inference_compute_duration_us Cummulative inference compute duration in microseconds
# TYPE nv_inference_compute_duration_us counter
# HELP nv_inference_queue_duration_us Cummulative inference queuing duration in microseconds
# TYPE nv_inference_queue_duration_us counter
# TYPE nv_inference_load_ratio histogram
# HELP nv_gpu_utilization GPU utilization rate [0.0 - 1.0)
# TYPE nv_gpu_utilization gauge
nv_gpu_utilization{gpu_uuid="GPU-d4d0dbb0-037e-652e-6df4-a742b597738c"} 0.120000
# HELP nv_gpu_memory_total_bytes GPU total memory, in bytes
# TYPE nv_gpu_memory_total_bytes gauge
nv_gpu_memory_total_bytes{gpu_uuid="GPU-d4d0dbb0-037e-652e-6df4-a742b597738c"} 4227465216.000000
# HELP nv_gpu_memory_used_bytes GPU used memory, in bytes
# TYPE nv_gpu_memory_used_bytes gauge
nv_gpu_memory_used_bytes{gpu_uuid="GPU-d4d0dbb0-037e-652e-6df4-a742b597738c"} 1300627456.000000
# HELP nv_gpu_power_usage GPU power usage in watts
# TYPE nv_gpu_power_usage gauge
nv_gpu_power_usage{gpu_uuid="GPU-d4d0dbb0-037e-652e-6df4-a742b597738c"} 0.000000
# HELP nv_gpu_power_limit GPU power management limit in watts
# TYPE nv_gpu_power_limit gauge
nv_gpu_power_limit{gpu_uuid="GPU-d4d0dbb0-037e-652e-6df4-a742b597738c"} 75.000000
# HELP nv_energy_consumption GPU energy consumption in joules since the trtserver started
# TYPE nv_energy_consumption counter
nv_energy_consumption{gpu_uuid="GPU-d4d0dbb0-037e-652e-6df4-a742b597738c"} 0.000000

**Comment by CoderHam** [comment]
These metrics are the metrics for the server. Count and latency are specific to the model. Please look at the [model statistics](https://github.com/triton-inference-server/server/blob/master/docs/protocol/extension_statistics.md) documenation. For per inference latency you would need to use the [trace](https://github.com/triton-inference-server/server/blob/master/docs/trace.md) functionality.

**Comment by hanyanLWD** [comment]
@CoderHam thanks
but i use postman and request is:GET v2/models/stats,but i get response:503 Service Unavailable

**Comment by hanyanLWD** [comment]
> These metrics are the metrics for the server. Count and latency are specific to the model. Please look at the [model statistics](https://github.com/triton-inference-server/server/blob/master/docs/protocol/extension_statistics.md) documenation. For per inference latency you would need to use the [trace](https://github.com/triton-inference-server/server/blob/master/docs/trace.md) functionality.

but i use postman and request is:GET v2/models/stats,but i get response:503 Service Unavailable

**Comment by offbye** [comment]
You should use the HTTP port 8000， not the metrics por 8002 to get the model stat
curl localhost:8000/v2/models/wdl/versions/1/stats
