### ISSUE TITLE
Unable to build r21.04 version

### ISSUE THREAD

**Issue by gyin-ai** [triton-inference-server/server#2763]
command:

```
container_tag="r21.04"
./build.py --cmake-dir=/tmp/serve/build --build-dir=/tmp/citritonbuild --enable-logging --enable-stats --enable-tracing --enable-metrics --enable-gpu-metrics --enable-gpu --filesystem=gcs --filesystem=azure_storage --filesystem=s3 --endpoint=http --endpoint=grpc --repo-tag=common:$container_tag --repo-tag=core:$container_tag --repo-tag=backend:$container_tag --repo-tag=thirdparty:$container_tag --backend=ensemble --backend=tensorrt --backend=identity:$container_tag --backend=repeat:$container_tag --backend=square:$container_tag --backend=onnxruntime:$container_tag --backend=pytorch:$container_tag --backend=tensorflow1:$container_tag --backend=tensorflow2:$container_tag --backend=openvino:$container_tag --backend=python:$container_tag --backend=dali:$container_tag --repoagent=checksum:$container_tag --repo-tag=$container_tag
```

error:
```
iled to solve with frontend dockerfile.v0: failed to create LLB definition: nvcr.io/nvidia/tritonserver:21.04-py3-min: not found
```

**Comment by 0wu** [comment]
The current latest release is 21.03 (See [readme](https://github.com/triton-inference-server/server/blob/master/README.md))
Maybe you want to build with "main" tag instead?

**Comment by gyin-ai** [comment]
> The current latest release is 21.03 (See [readme](https://github.com/triton-inference-server/server/blob/master/README.md))
> Maybe you want to build with "main" tag instead to get latest commits?
> See detail in [Build with docker](https://github.com/triton-inference-server/server/blob/master/docs/build.md#building-with-docker)

It is also not working.

```
Building Triton Inference Server
error: --repo-tag must specific <component-name>:<repo-tag>
error: docker run tritonserver_builder failed
```

**Comment by gyin-ai** [comment]
can we only build triton_server to a different base image instead of `nvcr.io/nvidia/tritonserver:xx.xx-py3-min`?

**Comment by deadeyegoodwin** [comment]
You can't build 21.04 until it is released (as noted in the README for that branch)
If you build on main/master you should be able to specify already released branches in repo-tag.
If you want to set a different base image you can use --image=base,<base image> but that base image must contain all the dependencies required to build triton

**Comment by 0wu** [comment]
I just tried 
```
./build.py  --cmake-dir=build --build-dir=/tmp/citritonbuild --enable-logging --enable-stats --enable-tracing \
--enable-metrics --enable-gpu-metrics --enable-gpu  --endpoint=http --endpoint=grpc \
--repo-tag=common:main --repo-tag=core:main --repo-tag=backend:main \
--repo-tag=thirdparty:main --backend=ensemble  --backend=identity:main --backend=repeat:main \
--backend=square:main  --backend=pytorch:main --backend=dali:main --backend=python:main \
--repoagent=checksum:main
```
with current repo master `8ecd15d`
And it builds fine.

**Comment by gyin-ai** [comment]
Thanks a lot.
