### ISSUE TITLE
Documentation for Windows alpha release

### ISSUE THREAD

**Issue by philipp-schmidt** [triton-inference-server/server#2767]
Can we get a brief addition to the documentation on how to run Triton under Windows using the recent alpha release?

I tried to install all dependencies using the respective Windows Installers - but I'm still getting errors regarding `nvinfer.dll` on startup. Do I need to add something to the PATH?

Trying to install Triton natively on a fresh Windows Server 2019 install.

**Comment by tanmayv25** [comment]
We have updated our build instructions for Windows 10 here: https://github.com/triton-inference-server/server/blob/main/docs/build.md#building-for-windows-10

Please re-open if you still see this issue or file a new issue if the outlined steps don't work for you.
