### ISSUE TITLE
tensorflow saved_model performance

### ISSUE THREAD

**Issue by devloper13** [triton-inference-server/server#2770]
I am running an object detection model, EfficientDet D7 (TF2 model zoo) which gives me about 1 FPS (which is a normal GPU performance).  This model doesn't support dynamic batching.
This is terribly slow for triton. Why is this happening? Also, triton boasts to deploy multiple model, does it automatically convert the model in Tensor RT? How does triton claim to make model inferencing efficient?

Also, I have to mention that when I deployed fasterrcnn-resnet101(TF1 model zoo, graphdef) in Deepstream 5 (has triton inferencing), it gave upto 8 FPS (which normally gives 3FPS). I'm at a total loss. What's going on?

System details:
1 T4 GPU core on aws g4dn

**Comment by CoderHam** [comment]
Triton does not convert the model to TRT. It does however support TRT models once you convert them. It also supports enablin the TF-TRT optimization. 
Can you quantize how much slower inference is on Triton. Is the test with and w/o Triton on the same type of GPU and are both using Tensorflow 1 or 2? 

> Also, I have to mention that when I deployed fasterrcnn-resnet101(TF1 model zoo, graphdef) in Deepstream 5 (has triton inferencing), it gave upto 8 FPS (which normally gives 3FPS). I'm at a total loss. What's going on?

Can you clarify what you mean by normally gives 3FPS? Does this mean direct execution of the model in native TF gives 3FPS?

**Comment by devloper13** [comment]
> Can you clarify what you mean by normally gives 3FPS? Does this mean direct execution of the model in native TF gives 3FPS?

Yes. 3 fps on native tf on a single gpu without any extra optimization. I had tested this with TF1 faster-rcnn-resnet-101. However this on deepstream-triton gave upto 8 fps. 

Now the model I am testing is with efficientdet d7 on trito inference server (not seepstream) which is TF2. The fps I get is 1. However this is the same performance I get on native tf. I was expecting some speedup say upto 3 fps at the very least if I compare to the speedup I mentioned above.

**Comment by CoderHam** [comment]
There are several factors that can impact performance, if the model is utilizing the GPU 100% as is, outside Triton there might not be a lot of performance gain that we can provide. You would ideally see nearly 1:1 mapping for perf in and outside Triton for a single concurrency and single instance. Can you confirm what the number of instances are in both cases?

**Comment by devloper13** [comment]
Hey, there was a slight misunderstanding from my side. This is no longer an issue. My observations were wrong.
