### ISSUE TITLE
How to use Triton server “ensemble model” with 1:N input/output to create patches from large image?

### ISSUE THREAD

**Issue by hubtub2** [triton-inference-server/server#2777]
I am trying to feed a very large image into a Triton server. I need to divide the input image into patches and feed the patches one by one into a tensorflow model. The image has a variable size, so the number of patches N is variable for each call.

I think a Triton ensemble model that calls the following steps would do the job:

1. A python model (pre-process) to draw the patches
2. The segmentation model
3. Finally another python model (post-process) to merge the output patches into a big output mask

However, for this I would have to write a config.pbtxt file with 1:N and N:1 relation between the models, meaning the ensemble scheduler needs to call the 2nd step multiple times and the 3rd one with the aggregated output-array.

Is this possible, or is there some other technique for patch based inference with Triton server?
Simply doing this in a tensorflow dataset isn't feasible  for us (there is a lot of code using various libs behind drawing the right patches).

I tried to read the manual, but there is no complete reference for the  "config.pbtxt"

**Comment by deadeyegoodwin** [comment]
See this document on Business Logic Scripting: https://docs.google.com/document/d/1_5PCQvWNxb32-T97E7P5aZxbCnFmuNKc0bPOoFqxtzo

**Comment by zakajd** [comment]
Hi @hubtub2
Did you managed to implement patch processing in Triton?
I'm facing almost the same issue now, try to inference variable-sized images that are too big to fit in memory and think about crop-process-merge pipeline. 

Thanks in advance!
