### ISSUE TITLE
[Jetson] triton client health calls via grpc on jetson very slow/hangs

### ISSUE THREAD

**Issue by chull434** [triton-inference-server/server#2779]
**Description**
When calling health check calls from python grpc client on jetson such as `triton_client.is_server_live()` call is very slow to get a response and hangs. Basically what [this example](https://github.com/triton-inference-server/client/blob/main/src/python/examples/simple_grpc_health_metadata.py) does. However calls via the http client are fine. 

Both client and server logs with verbose only show the calls as you would expect with nothing else to hint at what the issue might be.

Rest of the triton stuff works fine once the response comes back, only noticed it was an issue when my client containers where taking ages to complete start up, traced it to the above issue. 

**Triton Information**
_What version of Triton are you using?_ 
Same effect on both 2.9.0 and 2.8.0

_Are you using the Triton container or did you build it yourself?_ 
Custom container,  base image `nvcr.io/nvidia/l4t-ml:r32.5.0-py3` then install as per instructions in jetson jetpack support release section

**To Reproduce**
Running [this example](https://github.com/triton-inference-server/client/blob/main/src/python/examples/simple_grpc_health_metadata.py) on jetson should reproduce it

_Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well)._ 
Model and frameworks seemed to have little effect on the issue, had tried a few different models of different types etc.

**Expected behavior**
health check calls from python grpc client on jetson shouldn't take an overly long to respond or do we just need to use http client only for these calls?

**Comment by CoderHam** [comment]
Thanks for this bug. We will try to repro and zero in on the error.

**Comment by CoderHam** [comment]
@chull434 I am unable to reproduce this in our latest release. Can you share a script/s for the reproduction of the issue?

**Comment by CoderHam** [comment]
Closing this ticket due to inactivity. Please re-open when you can share a detailed reproduction guide.
