### ISSUE TITLE
Questions about Model Loading on GPU memory

### ISSUE THREAD

**Issue by qpakzk** [triton-inference-server/server#2780]
Hello.
I have some questions about model loading on GPU memory.

I understood that Triton loads model graphs for each GPU memory when it is booting.
Then it loads weights when a client first requests an inference.

**I ask whether Triton switches weights when GPU memory is fulled.**
For example, model A weights and model B weights full GPU memory. 
If a client requests an inference for model C, then does Triton switch weights?

**I asked whether Triton has an option to upload some weights in advance.**
When a client first requests an inference, the execution is very slow because Triton is loading weights.
Is it possible to load some weights before the first request?

**Comment by 0wu** [comment]
(1) I don't think triton (or any reasonably designed serving) has the ability to decide whether a model can be unloaded or not as it does not have the ability to predict when next query will arrive. However, one can explicitly control the load/unload of models using the APIs https://github.com/triton-inference-server/server/blob/master/docs/protocol/extension_model_repository.md

(2) You can use initialize a model by warmup
https://github.com/triton-inference-server/server/blob/2af3ab977c31e152881e39127906447700ad1a2b/docs/model_configuration.md#model-warmup

**Comment by qpakzk** [comment]
@0wu Thanks for your answer.

In (1), I thought it is necessary for Triton to load and unload model weights automatically
because a client application which requires numerous models can exist. 
But when I tested this situation, the Triton process was dead.
So I suspected whether I tested it wrongly or Triton doesn't manage loading on the GPU memory.

I thought Triton should serve regardless of GPU memory size.
So I expected Triton will unload existing weights and load new weights that a new inference request requires when there is no free space in the GPU memory.

Suppose that my GPU memory is fulled when model A and model B weights are loaded on my GPU memory.
To run my service, my client application, which uses Triton to execute inferences, needs model A, B and C.
When I boot Triton Inference Server, three model graphs are loaded on my GPU memory.
And while I'm running my service, model A and B weights are already loaded because previous inference requests require model A and B.
In this situation, if a new inference request requires model C, my service will be stopped because the Triton process will be dead.

How do you think about it?

**Comment by deadeyegoodwin** [comment]
Triton does not automatically load and unloaded model instances, you must control that explicitly. https://github.com/triton-inference-server/server/blob/main/docs/model_management.md
