### ISSUE TITLE
Unusual HTTP send/recv latency with perf_analyzer

### ISSUE THREAD

**Issue by gilevir** [triton-inference-server/server#2783]
**Description**
I am trying to optimize my models loaded on Triton with `perf_analyzer` and observe throughput vs latency.
One of them, whose output is fairly big data (images of shape 3, 1024, 1024), shows really high HTTP send/recv times
For instance, the output of perf_analyzer for concurrency 6 :
```
Request concurrency: 6
  Client:
    Request count: 56
    Throughput: 0.933333 infer/sec
    Avg latency: 6450700 usec (standard deviation 2150478 usec)
    p50 latency: 6571193 usec
    p90 latency: 8036464 usec
    p95 latency: 8438160 usec
    p99 latency: 8755278 usec
    Avg HTTP time: 6391027 usec (send/recv 6172206 usec + response wait 218821 usec)
  Server:
    Inference count: 33
    Execution count: 33
    Successful request count: 33
    Avg request latency: 136472 usec (overhead 4 usec + queue 179 usec + compute input 4017 usec + compute infer 9553 usec + compute output 122719 usec)
```

On the client side the latency is around 6,4 sec (!) and the HTTP send/recv part is 6,17 sec !
This is really a huge bottleneck. 

Is this due to the HTTP transfer of the results of the model, which are quite big data ? 
Can this be optimized ?

**Triton Information**
What version of Triton are you using?
Triton 2.5 from container 20.11

Triton is deployed on GKE 1.18.16-gke.502. `perf_analyzer` is run on a different machine which is not on the same network than Triton

**To Reproduce**

Load a torchscript generative model which output is a 1024x1024 image in triton
Run perf_analyzer on this model

model config file: 

```
name: "generator"
platform: "pytorch_libtorch"
max_batch_size: 2
dynamic_batching {
    max_queue_delay_microseconds: 100
}
input [
    {
      name: "INPUT__0"
      data_type: TYPE_FP32
      dims: [ 18, 512 ]
    }
]
output [
    {
      name: "OUTPUT__0"
      data_type: TYPE_FP32
      dims: [ 3, 1024, 1024 ]
    }
]
instance_group [
    {
      count: 2
      kind: KIND_GPU
      gpus: [ 1 ]
    }
]
```

**Expected behavior**
No latency bottleneck on the HTTP send/recv time

**Comment by gilevir** [comment]
Some additional inputs / questions : 

- On the HTTP client side, we use the `binary=True` option in the HTTP API for each input. But, we do not set any outputs when calling `infer` (ie. we do not set any InferRequestedOutput). How can this change the behaviour of the HTTP send/recv time ?
- We do not use `request_compression_algorithm` nor `response_compression_algorithm`, cant it help for data as large as (3, 1024, 1024) 

Thanks

**Comment by 0wu** [comment]
(1) What's your actual model inference/second w/o Triton? Is it much faster than 1 inf/s?
(2) How about construct an identity model taking the same input

**Comment by gilevir** [comment]
Hi, thanks for answering.

(1) On a slightly better GPU than the T4 I use for Triton, I can achieve 20 inferences/second with python and same torchscript model
(2) I did load in Triton a dummy model with same input and output shapes. `perf_analyzer`on this dummy model is showing same high HTTP send/recv times (between 4 to 7 seconds depending on the concurrency)

**Comment by deadeyegoodwin** [comment]
Are you running perf_analyzer on the same system as Triton?
Run perf_analyzer with grpc? How do the results compare with http?

There was a bug fixed where non-binary mode would be used for all outputs if you didn't explicitly use InferRequestedOutput for them. This bug is fixed in recent Tritons. You should try a more recent triton (21.04) if possible.

**Comment by tanmayv25** [comment]
Closing the issue because of inactivity for now. If you are still seeing this behavior then please re-open the issue with response to above questions.
