### ISSUE TITLE
When use command line to launch triton, it raise: attempt to access JSON non-number as double

### ISSUE THREAD

**Issue by XZHUNZHUN** [triton-inference-server/server#2790]
- I followed the https://github.com/triton-inference-server/tensorflow_backend#command-line-options 
to add gpu-memory-fraction to launch triton
        
        nvidia-docker run -it --name=tritonserver --gpus=1 --rm \
          --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 \
          -p8000:8000 -p8001:8001 -p8002:8002 \
          -v triton-inference-server/server/docs/examples/model_repository:/models \
          nvcr.io/nvidia/tritonserver:20.08-py3 tritonserver --model-repository=/models \
          --backend-config=tensorflow,version=1 --backend-config=tensorflow,gpu-memory-fraction='0.4'
        
- But get some error:

      I0430 02:33:53.194747 1 tensorflow.cc:2075] TRITONBACKEND_Initialize: tensorflow
      I0430 02:33:53.194774 1 tensorflow.cc:2088] Triton TRITONBACKEND API version: 0.2
      I0430 02:33:53.194779 1 tensorflow.cc:2094] 'tensorflow' TRITONBACKEND API version: 0.2
      I0430 02:33:53.194787 1 tensorflow.cc:2115] backend configuration:
      {"cmdline":{"version":"1","gpu-memory-fraction":"0.4"}}
      E0430 02:33:53.195008 1 model_repository_manager.cc:928] failed to load 'east' version 1: Internal: attempt to access JSON non-number as double
      error: creating server: Internal - failed to load all models
    
- So i found the TensorFlow.cc source code https://github.com/triton-inference-server/tensorflow_backend/blob/main/src/tensorflow.cc

       if (backend_config.Find("cmdline", &cmdline)) {
        triton::common::TritonJson::Value value;
        std::string value_str;
        if (cmdline.Find("allow-soft-placement", &value)) {
          RETURN_IF_ERROR(value.AsString(&value_str));
          RETURN_IF_ERROR(
              ParseBoolValue(value_str, &lconfig->allow_soft_placement_));
        }
        if (cmdline.Find("gpu-memory-fraction", &value)) {
          RETURN_IF_ERROR(value.AsString(&value_str));
          double lvalue;
          RETURN_IF_ERROR(ParseDoubleValue(value_str, &lvalue));
          lconfig->per_process_gpu_memory_fraction_ = lvalue;
          lconfig->allow_gpu_memory_growth_ = (lvalue == 0.0);
        }
      }
    
- The error seems to be in  __ParseDoubleValue__, but I don't think there is any problem with this code. May I ask if I made a mistake in the command line? If I remove the __gpu-memory-fraction__ in command, the triton will start up normally.

**Comment by shelltalk** [comment]
I met the same situation, also need a solution.

**Comment by CoderHam** [comment]
Have you tried passing it as a float instead of a string? i.e. --backend-config=tensorflow,gpu-memory-fraction=0.4 instead of gpu-memory-fraction='0.4'
We mention in [this doc](https://github.com/triton-inference-server/server/blob/master/docs/v1_to_v2.md) as well that the gpu-memory-fraction must be passed as a float.

**Comment by GuanLuo** [comment]
What Triton version are you using? I think the current version will print out a different error message if it fails to parse the value.

**Comment by XZHUNZHUN** [comment]
> What Triton version are you using? I think the current version will print out a different error message if it fails to parse the value.

Yes I am using the latest version, do you have any recommended versions

**Comment by XZHUNZHUN** [comment]
> Have you tried passing it as a float instead of a string? i.e. --backend-config=tensorflow,gpu-memory-fraction=0.4 instead of gpu-memory-fraction='0.4'
> We mention in [this doc](https://github.com/triton-inference-server/server/blob/master/docs/v1_to_v2.md) as well that the gpu-memory-fraction must be passed as a float.

I have tried every form 0.4,'0.4', and "0.4" but nothing worked

**Comment by XZHUNZHUN** [comment]
> What Triton version are you using? I think the current version will print out a different error message if it fails to parse the value.

version 20.08, I will tried the current version

**Comment by XZHUNZHUN** [comment]
> What Triton version are you using? I think the current version will print out a different error message if it fails to parse the value.

Release 20.08

**Comment by CoderHam** [comment]
@XZHUNZHUN 20.08 is over 6 months old now. Please try with the latest (21.03/4) release

**Comment by XZHUNZHUN** [comment]
> @XZHUNZHUN 20.08 is over 6 months old now. Please try with the latest (21.03/4) release

Have finished, thanks

**Comment by XZHUNZHUN** [comment]
> @XZHUNZHUN 20.08 is over 6 months old now. Please try with the latest (21.03/4) release

The problem has been solved. Thanks
