### ISSUE TITLE
can not load onnx model 

### ISSUE THREAD

**Issue by ffffwyy** [triton-inference-server/server#2793]
**Description**!
i convert  a "detr_resnet50" model to an onnx with dynamic batch as below shown , and it seems to be OK.

the converting code is as follows:
output_onnx = 'det.onnx'
    print("==> Exporting model to ONNX format at '{}'".format(output_onnx))
    input_names = ["input"]
    output_names = ["scores", "boxes"]
    dynamic_dic = {'input': {0: 'batch_size'}, 'scores': {0: 'batch_size'}, 'boxes': {0: 'batch_size'}}

    inputs = torch.randn(1, 3, 800, 800).to('cpu')
    torch_out = torch.onnx.export(net, inputs, output_onnx, export_params=True, verbose=False,
                                   input_names=input_names, output_names=output_names, opset_version=11, dynamic_axes=dynamic_dic)

    onnx_model = onnx.load('det.onnx')

![1](https://user-images.githubusercontent.com/42471198/116655812-44ea0580-a9be-11eb-86d8-65b4123df3f1.png)

but when i started server , i got erro log like this .
=============================
== Triton Inference Server ==
=============================

NVIDIA Release 21.03 (build 20851776)

Copyright (c) 2018-2021, NVIDIA CORPORATION.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

I0430 05:42:27.016903 1 metrics.cc:221] Collecting metrics for GPU 0: Tesla T4
I0430 05:42:27.023470 1 metrics.cc:221] Collecting metrics for GPU 1: Tesla T4
I0430 05:42:27.029899 1 metrics.cc:221] Collecting metrics for GPU 2: Tesla T4
I0430 05:42:27.036465 1 metrics.cc:221] Collecting metrics for GPU 3: Tesla T4
I0430 05:42:27.426365 1 libtorch.cc:940] TRITONBACKEND_Initialize: pytorch
I0430 05:42:27.426402 1 libtorch.cc:950] Triton TRITONBACKEND API version: 1.0
I0430 05:42:27.426411 1 libtorch.cc:956] 'pytorch' TRITONBACKEND API version: 1.0
2021-04-30 05:42:27.670530: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
I0430 05:42:27.721528 1 tensorflow.cc:1880] TRITONBACKEND_Initialize: tensorflow
I0430 05:42:27.721563 1 tensorflow.cc:1890] Triton TRITONBACKEND API version: 1.0
I0430 05:42:27.721576 1 tensorflow.cc:1896] 'tensorflow' TRITONBACKEND API version: 1.0
I0430 05:42:27.721587 1 tensorflow.cc:1920] backend configuration:
{}
I0430 05:42:27.723942 1 onnxruntime.cc:1728] TRITONBACKEND_Initialize: onnxruntime
I0430 05:42:27.723971 1 onnxruntime.cc:1738] Triton TRITONBACKEND API version: 1.0
I0430 05:42:27.723993 1 onnxruntime.cc:1744] 'onnxruntime' TRITONBACKEND API version: 1.0
I0430 05:42:27.756317 1 openvino.cc:1166] TRITONBACKEND_Initialize: openvino
I0430 05:42:27.756342 1 openvino.cc:1176] Triton TRITONBACKEND API version: 1.0
I0430 05:42:27.756350 1 openvino.cc:1182] 'openvino' TRITONBACKEND API version: 1.0
I0430 05:42:28.013108 1 pinned_memory_manager.cc:205] Pinned memory pool is created at '0x7fc080000000' with size 268435456
I0430 05:42:28.017340 1 cuda_memory_manager.cc:103] CUDA memory pool is created on device 0 with size 67108864
I0430 05:42:28.017355 1 cuda_memory_manager.cc:103] CUDA memory pool is created on device 1 with size 67108864
I0430 05:42:28.017362 1 cuda_memory_manager.cc:103] CUDA memory pool is created on device 2 with size 67108864
I0430 05:42:28.017368 1 cuda_memory_manager.cc:103] CUDA memory pool is created on device 3 with size 67108864
W0430 05:42:28.581784 1 server.cc:188] failed to enable peer access for some device pairs
I0430 05:42:28.591548 1 model_repository_manager.cc:1065] loading: truck_det:1
I0430 05:42:28.693887 1 onnxruntime.cc:1787] TRITONBACKEND_ModelInitialize: truck_det (version 1)
WARNING: Since openmp is enabled in this build, this API cannot be used to configure intra op num threads. Please use the openmp environment variables to control the number of threads.
I0430 05:42:28.695379 1 onnxruntime.cc:1830] TRITONBACKEND_ModelInstanceInitialize: truck_det_0_0 (GPU device 1)
I0430 05:42:34.380839 1 onnxruntime.cc:1864] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0430 05:42:34.380903 1 onnxruntime.cc:1810] TRITONBACKEND_ModelFinalize: delete model state
E0430 05:42:34.380991 1 model_repository_manager.cc:1242] failed to load 'truck_det' version 1: Invalid argument: model 'truck_det', tensor 'boxes': for the model to support batching the shape should have at least 1 dimension and the first dimension must be -1; but shape expected by the model is [1,100,4]
I0430 05:42:34.381143 1 server.cc:500] 

**Triton Information**!
21.03

Are you using the Triton container or did you build it yourself?
container

**To Reproduce**
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

my config is as follows:

name: "det"
platform: "onnxruntime_onnx"
max_batch_size: 32
input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [ 3, 800, 800  ]

  }

]

output [
  {
    name: "boxes"
    data_type: TYPE_FP32
    dims: [ 100, 4 ]

  },
  {
    name: "scores"
    data_type: TYPE_FP32
    dims: [ 100, 3 ]

  }
]

instance_group [
    {
      count: 3
      kind: KIND_GPU
      gpus: [ 1, 2, 3 ]
    }
]

dynamic_batching {
    preferred_batch_size: [ 8, 32 ]
    max_queue_delay_microseconds: 100000
}

**Expected behavior**

**Comment by GuanLuo** [comment]
Can you share the model as well so we can try to reproduce the issue?

**Comment by geometrikal** [comment]
Try this:

```
name: "det"
platform: "onnxruntime_onnx"
max_batch_size: 32
input [
{
name: "input"
data_type: TYPE_FP32
dims: [ -1, 3, 800, 800 ]

}

]

output [
{
name: "boxes"
data_type: TYPE_FP32
dims: [ -1, 100, 4 ]

},
{
name: "scores"
data_type: TYPE_FP32
dims: [ -1, 100, 3 ]

}
]

instance_group [
{
count: 3
kind: KIND_GPU
gpus: [ 1, 2, 3 ]
}
]

dynamic_batching {
preferred_batch_size: [ 8, 32 ]
max_queue_delay_microseconds: 100000
}
```

**Comment by ffffwyy** [comment]
> Can you share the model as well so we can try to reproduce the issue?

i use https://github.com/facebookresearch/detr.git to get the model.
just use script below to convert onnx model 

from __future__ import print_function
import os
import argparse
import torch
import onnx


def load_model():
    from hubconf import detr_resnet50
    model = detr_resnet50(pretrained=False, num_classes=2)

    return model

if __name__ == '__main__':
    torch.set_grad_enabled(False)

    # load weight
    net = load_model()

    print('Finished loading model!')


    # print(net)

    # ##################export###############
    output_onnx = 'det.onnx'
    print("==> Exporting model to ONNX format at '{}'".format(output_onnx))
    input_names = ["input"]
    output_names = ["scores", "boxes"]
    dynamic_dic = {'input': {0: 'batch_size'}, 'scores': {0: 'batch_size'}, 'boxes': {0: 'batch_size'}}

    inputs = torch.randn(1, 3, 800, 800).to('cpu')
    torch_out = torch.onnx.export(net, inputs, output_onnx, export_params=True, verbose=False,
                                   input_names=input_names, output_names=output_names, opset_version=11, dynamic_axes=dynamic_dic)

    onnx_model = onnx.load('det.onnx')
    print(onnx_model.graph.input[0])
    # ##################end###############

**Comment by ffffwyy** [comment]
> Try this:
> 
> ```
> name: "det"
> platform: "onnxruntime_onnx"
> max_batch_size: 32
> input [
> {
> name: "input"
> data_type: TYPE_FP32
> dims: [ -1, 3, 800, 800 ]
> 
> }
> 
> ]
> 
> output [
> {
> name: "boxes"
> data_type: TYPE_FP32
> dims: [ -1, 100, 4 ]
> 
> },
> {
> name: "scores"
> data_type: TYPE_FP32
> dims: [ -1, 100, 3 ]
> 
> }
> ]
> 
> instance_group [
> {
> count: 3
> kind: KIND_GPU
> gpus: [ 1, 2, 3 ]
> }
> ]
> 
> dynamic_batching {
> preferred_batch_size: [ 8, 32 ]
> max_queue_delay_microseconds: 100000
> }
> ```

i've tried and faild. i think it is no need adding "-1" explicitly to "dims" in cases of dynamic batch

**Comment by geometrikal** [comment]
Try the Python script again with an input batch size of greater than 1. Maybe the model is actually only working for batch size 1.

**Comment by ffffwyy** [comment]
> Can you share the model as well so we can try to reproduce the issue?

https://drive.google.com/file/d/12v98uC0jxfktdRc3aJnpuwhT0k2Yj7P7/view?usp=sharing

this is the model.

**Comment by deadeyegoodwin** [comment]
From the error message it is saying that the "boxes" output produced by the model has shape [ 1, 100, 4 ]. To support dynamic batching in Triton it must have shape [ -1, 100, 4 ]. You need to fix you model conversion to produce an output with the first dimension being variable size (-1). I'm not sure how this is done with the pytorch -> onnx converter. @CoderHam  do you know?

**Comment by ffffwyy** [comment]
> From the error message it is saying that the "boxes" output produced by the model has shape [ 1, 100, 4 ]. To support dynamic batching in Triton it must have shape [ -1, 100, 4 ]. You need to fix you model conversion to produce an output with the first dimension being variable size (-1). I'm not sure how this is done with the pytorch -> onnx converter. @CoderHam do you know?

I think this "dynamic_dic = {'input': {0: 'batch_size'}, 'scores': {0: 'batch_size'}, 'boxes': {0: 'batch_size'}}" is to fix first dimension being "-1".
I converted other pytorch models to onnx with the same method, and they worked well.
Maybe the cause is "opset_version=11"? When I converted this model ,pytorch error message suggested me to use this version.

**Comment by deadeyegoodwin** [comment]
Perhaps pytorch community can help you with the issue? You can't enable dynamic batching in Triton until that output is fixed to have the batch dimension.
