### ISSUE TITLE
Windows support for C API sample

### ISSUE THREAD

**Issue by gvashishtha** [triton-inference-server/server#2803]
**Is your feature request related to a problem? Please describe.**
Today [simple.cc](https://github.com/triton-inference-server/server/blob/master/src/servers/simple.cc) is not included in Windows build because it uses some libraries and functions not supported on Windows, including unistd.h, getopt,  optarg, usleep.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by CoderHam** [comment]
Can you help us understand the motivation to have a simple.cc for Windows? It was meant to serve as an example.
This would help us prioritize expanding the simple.cc to be supported on Windows.

**Comment by gvashishtha** [comment]
Our devs want to see if they can successfully use Triton on Windows. Having a known-good Windows example would help them move faster (rather than having to come up with something themselves)
