### ISSUE TITLE
Out of memory error on second inference

### ISSUE THREAD

**Issue by geometrikal** [triton-inference-server/server#2810]
**Description**
Out of memory error on second inference

**Triton Information**
21.04

Are you using the Triton container or did you build it yourself?
Using the container

**To Reproduce**

Converted a TF2 obj det model (Faster RCNN) to ONNX using op version 13

Use model config file:

```
name: "Faster_RCNN_2048_v1"
platform: "onnxruntime_onnx"
max_batch_size : 0
input [
  {
    name: "input_tensor:0"
    data_type: TYPE_UINT8
    dims: [ 1, -1, -1, 3 ]
  }
]
output [
  {
    name: "detection_boxes"
    data_type: TYPE_FP32
    dims: [ 1, 300, 4  ]
  },
  {
    name: "detection_classes"
    data_type: TYPE_FP32
    dims: [ 1, 300 ]        
  },
  {
    name: "detection_scores"
    data_type: TYPE_FP32
    dims: [ 1, 300 ]        
  },
  {
    name: "num_detections"
    data_type: TYPE_FP32
    dims: [ 1 ]        
  }
]
instance_group [
    {
      count: 1
      kind: KIND_GPU
      gpus: [ 0 ]
    }
  ]
```

Inference code to test:

```
import tritonclient.grpc as grpcclient
from tritonclient.utils import InferenceServerException
import numpy as np


triton_client = grpcclient.InferenceServerClient('localhost:8001', False)
model_metadata = triton_client.get_model_metadata("Faster_RCNN_2048_v1")

# Infer
inputs = []
outputs = []
inputs.append(grpcclient.InferInput(model_metadata.inputs[0].name, [1, 2048, 2448, 3], model_metadata.inputs[0].datatype))
input0_data = np.random.randint(0, 255, (1, 2048, 2448, 3)).astype(np.uint8)
inputs[0].set_data_from_numpy(input0_data)

outputs.append(grpcclient.InferRequestedOutput(model_metadata.outputs[0].name))

results = triton_client.infer(
    model_name="Faster_RCNN_2048_v1",
    inputs=inputs,
    outputs=outputs,
    client_timeout=30,
    headers={'test': '1'})

statistics = triton_client.get_inference_statistics(model_name="Faster_RCNN_2048_v1")
print(statistics)
if len(statistics.model_stats) != 1:
    print("FAILED: Inference Statistics")
```

First inference runs fine. Re-running the script it fails:

2021-05-05 03:58:22.081200604 [E:onnxruntime:, sequential_executor.cc:339 Execute] Non-zero status code returned while running NonMaxSuppression node. Name:'NonMaxSuppression__1623' Status Message: /workspace/onnxruntime/onnxruntime/core/framework/bfc_arena.cc:305 void* onnxruntime::BFCArena::AllocateRawInternal(size_t, bool) Failed to allocate memory for requested buffer of size 4831838208

Can share .onnx file if needed to debug

**Comment by CoderHam** [comment]
What are the memory specifications of the system you are running this on?
Are you able to run the model in native ORT without an OOM error?

**Comment by geometrikal** [comment]
Same error just using onnxruntime, closing issue, but will comment with any solutions I find.
