### ISSUE TITLE
Verifying dynamic batching is working

### ISSUE THREAD

**Issue by okyspace** [triton-inference-server/server#2811]
**Is your feature request related to a problem? Please describe.**
I have added configuration for dynamic batching and look through the metrics provided through port 8002 but I cannot find any means to verify that it is working correctly. 

**Describe the solution you'd like**
Provide log of merged last 10 requests vs its inference call for verification purpose. 

**Describe alternatives you've considered**
Tried playing with delay and max batch size to find any difference between total inference time and queue time. But this is inferring from these available data but may not mean the dynamic batching configuration is done correctly.

**Comment by GuanLuo** [comment]
Triton doesn't provide such logs so you may need to add your own logging to the source code to achieve exactly what you want.

However, to just understand the difference when dynamic batching is used, you can run perf_analyzer with a fixed concurrency (> 1) so the server will receive enough load. And then, assuming your model support batching, you can compare the infer / sec between when dynamic batching is enabled and when it is not.

**Comment by okyspace** [comment]
@GuanLuo Thanks. I only managed to find these references to proceed with what you suggested:
1. Description of perf_analyzer features and some performance results: [](https://github.com/triton-inference-server/server/blob/master/docs/perf_analyzer.md)
2. Installing perf_analyzer: https://github.com/triton-inference-server/client#getting-the-client-libraries-and-examples

I have looked through the client examples but cannot find perf_analyzer related ones. Could you help to point me to the page that help me to start running perf_analyzer? Appreciate your help.

**Comment by tanmayv25** [comment]
@okyspace  `perf_analyzer -h` will print the options and their usage.. 
Detailed documentation can be found here: https://github.com/triton-inference-server/client/blob/main/src/c%2B%2B/perf_analyzer/main.cc#L58
