### ISSUE TITLE
Triton crashes while running TensorFlow model with reshape commands for outputs in config.pbtxt

### ISSUE THREAD

**Issue by raimondasl** [triton-inference-server/server#2818]
We encountered the issue while using 21.04 Triton via Nvidia container: `sudo docker run -it --entrypoint=/bin/bash --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 -p8000:8000 -p8001:8001 -p8002:8002 nvcr.io/nvidia/tritonserver:21.04-py3`

Triton loads the model fine, but crashes during inference with a config file that contains reshape for outputs:

output [
{
name: "text"
data_type: TYPE_STRING
dims: [ 1 ]
reshape: { shape: [ ] }
},
{
name: "times"
data_type: TYPE_INT32
dims: [ 1 ]
reshape: { shape: [ ] }
},
{
name: "row_splits"
data_type: TYPE_INT32
dims: [ 1 ]
reshape: { shape: [ ] }
}
]

The inference works fine if we remove batching.
I have attached full config.pbtxt files: the problematic one and the non-batching one. I had to name them .txt for attachment to work.

Here is the log from the server:

Here is the end of the log before crash:

I0504 21:06:05.092885 1 model_repository_manager.cc:659] GetInferenceBackend() 'serving_default' version -1
I0504 21:06:05.092938 1 infer_request.cc:497] prepared: [0x0x7f0f58011390] request id: , model: serving_default, requested version: -1, actual version: 1, flags: 0x0, correlation id: 0, batch size: 1, priority: 0, timeout (us): 0
original inputs:
[0x0x7f0f580117d8] input: len_audio, type: INT32, original shape: [1,1], batch + shape: [1], shape: []
[0x0x7f0f580116d8] input: audio, type: FP32, original shape: [1,10240,1], batch + shape: [1,10240,1], shape: [10240,1]
[0x0x7f0f58011618] input: chunk_number, type: FP32, original shape: [1,1], batch + shape: [1], shape: []
override inputs:
inputs:
[0x0x7f0f58011618] input: chunk_number, type: FP32, original shape: [1,1], batch + shape: [1], shape: []
[0x0x7f0f580116d8] input: audio, type: FP32, original shape: [1,10240,1], batch + shape: [1,10240,1], shape: [10240,1]
[0x0x7f0f580117d8] input: len_audio, type: INT32, original shape: [1,1], batch + shape: [1], shape: []
original requested outputs:
requested outputs:
row_splits
text
times

I0504 21:06:05.093162 1 tensorflow.cc:2385] model serving_default, instance serving_default_0, executing 1 requests
I0504 21:06:05.093201 1 tensorflow.cc:1562] TRITONBACKEND_ModelExecute: Running serving_default_0 with 1 requests
I0504 21:06:05.093441 1 tensorflow.cc:1811] TRITONBACKEND_ModelExecute: input 'chunk_number' is GPU tensor: false
I0504 21:06:05.093505 1 tensorflow.cc:1811] TRITONBACKEND_ModelExecute: input 'audio' is GPU tensor: false
I0504 21:06:05.093514 1 tensorflow.cc:1811] TRITONBACKEND_ModelExecute: input 'len_audio' is GPU tensor: false
I0504 21:06:07.936527 1 http_server.cc:1229] HTTP request: 0 /v2/health/ready
I0504 21:06:07.936607 1 model_repository_manager.cc:591] BackendStates()
I0504 21:06:08.934501 1 http_server.cc:1229] HTTP request: 0 /v2/health/live
I0504 21:06:17.936650 1 http_server.cc:1229] HTTP request: 0 /v2/health/ready
I0504 21:06:17.936699 1 model_repository_manager.cc:591] BackendStates()
I0504 21:06:18.934268 1 http_server.cc:1229] HTTP request: 0 /v2/health/live
I0504 21:06:27.936281 1 http_server.cc:1229] HTTP request: 0 /v2/health/ready
I0504 21:06:27.936347 1 model_repository_manager.cc:591] BackendStates()
I0504 21:06:28.934229 1 http_server.cc:1229] HTTP request: 0 /v2/health/live
I0504 21:06:37.936776 1 http_server.cc:1229] HTTP request: 0 /v2/health/ready
I0504 21:06:37.936841 1 model_repository_manager.cc:591] BackendStates()
I0504 21:06:38.934325 1 http_server.cc:1229] HTTP request: 0 /v2/health/live
I0504 21:06:40.500346 1 infer_response.cc:165] add response output: output: row_splits, type: INT32, shape: [1]
I0504 21:06:40.500534 1 grpc_server.cc:2260] GRPC: using buffer for 'row_splits', size: 4, addr: 0x7f0f68001c00
I0504 21:06:40.500577 1 tensorflow.cc:2085] TRITONBACKEND_ModelExecute: output 'row_splits' is GPU tensor: false
I0504 21:06:40.500584 1 infer_response.cc:165] add response output: output: text, type: BYTES, shape: [1]

Please let me know if we can provide any additional info.

[config.nobatching.pbtxt.txt](https://github.com/triton-inference-server/server/files/6430569/config.nobatching.pbtxt.txt)
[config.problematic.pbtxt.txt](https://github.com/triton-inference-server/server/files/6430570/config.problematic.pbtxt.txt)

**Comment by CoderHam** [comment]
Can you remove the STRING output i.e. 'text' and see if the model executes successfully? There might be an issue in the handling of string type tensors. 
It would also be helpful if you could share the model with us, so we can repro and triage the bug.

**Comment by rabbh** [comment]
Removed the STRING output from the .pbtxt and still got a crash:

```I0507 15:28:52.747193 1 infer_response.cc:165] add response output: output: row_splits, type: INT32, shape: [1]
I0507 15:28:52.747261 1 grpc_server.cc:2260] GRPC: using buffer for 'row_splits', size: 4, addr: 0x7f6b6cf5c430
I0507 15:28:52.747279 1 tensorflow.cc:2085] TRITONBACKEND_ModelExecute: output 'row_splits' is GPU tensor: false
I0507 15:28:52.747286 1 infer_response.cc:165] add response output: output: times, type: INT32, shape: [1]
I0507 15:28:52.747294 1 grpc_server.cc:2260] GRPC: using buffer for 'times', size: 4, addr: 0x7f6b7aa1c5a0
```

Not sure if we can share the model yet; will get back to you.

**Comment by raimondasl** [comment]
It is possible that our model is to blame. 

I tried to reproduce by generating trivial models with float and string input/output and running tests via perf_analyzer: `perf_analyzer -m test -i gRPC --sync --max-threads 5 --request-rate-range 1000 -u myip:8001`
Triton works fine.

I think we can close this with "_can't reproduce_" for now. If we get a crash on a model that we can share with you, we'll reopen.

Trivial model:
[adder.py.txt](https://github.com/triton-inference-server/server/files/6444695/adder.py.txt)
Config.pbtxt for it:
[config.pbtxt.txt](https://github.com/triton-inference-server/server/files/6444699/config.pbtxt.txt)
