### ISSUE TITLE
Question: How to call another model in a model.(like emsemble, speech recognition application)

### ISSUE THREAD

**Issue by jeon30c** [triton-inference-server/server#2827]
Model A: split signals into small chunks and send the chunks to many instances of model B. After getting the results, model A post-processes the outputs from model B.
Model B: several instances of model B process the chunks simultaneously. Sending results back to model A.

It is not correct for model A to send requests to model Bs via grpc or http, as the two models reside on the same server.

Questions:
Best way to send "asynchronous" requests among the models in one server.

**Comment by jeon30c** [comment]
Thank you for the reply. @dzier 

Splitting model "A" is fine but I am still confused about sending the preprocessing's outputs to multiple instances of model "B".

Model "A"(preprocessing) splits the input signal into BxTxC where B is variable based on the signal length. Model "B" consumes only one TxC (eg. fixed size spectrogram) because it depends on a beam search algorithm. So model "A" has to send variable B requests to model "B".  And variable B outputs from model "B" are asynchronously sent to model "C". "C" does not know how may inputs are gathered from model "B".

Is it possible to configure this structure in configpb.txt?

**Comment by dzier** [comment]
In your use case, you are correct, an ensemble will not work. However, we working on a solution internally that will handle this exact use case. I will ping this issue when we are ready to release new feature and corresponding documentation.

**Comment by dzier** [comment]
@jeon30c We now have a public document that describes how to implement your use case with Business Logic Scripting: 

https://docs.google.com/document/d/1_5PCQvWNxb32-T97E7P5aZxbCnFmuNKc0bPOoFqxtzo/edit#heading=h.mxzsxt3ihlf0

I will close this issue for now. Please re-open or file a new issue if you have additional questions.
