### ISSUE TITLE
how to change the package name in java client

### ISSUE THREAD

**Issue by Damcy** [triton-inference-server/server#2828]
The package name for those generated files in the java client is `package inference`, how can I change the package name, for example, `com.newname.inference`. I want to place these files into `com/newname/inference` dir. I've tried to replace the code `package inference;` in the *.proto file to `package com.newname.inference;` but it seems not working (compile okay).

**Comment by dzier** [comment]
This issues appears to be a JAVA build issue and not related to the Triton Server. If you have an issue related to directly to Triton Server, please file a new issue. Please re-open this issue if you feel this is in error.

For additional reference on use a JAVA Client with Triton, please refer to the [Java client example](https://github.com/triton-inference-server/client/tree/main/src/java)
