### ISSUE TITLE
How to inference with tuple input in pytorch_backend?

### ISSUE THREAD

**Issue by seed93** [triton-inference-server/server#2831]
I use tuple as input in pytorch_backend. It seems that triton only supports tensor as inputs but not tuple.
`Error processing InferRequest: rpc error: code = Internal desc = PyTorch execute failure: forward() Expected a value of type '__torch__.P' for argument 'x' but instead found type 'Tensor'.`
I will get this error info in my client request. How can I feed tuple to a pytorch model?

**Comment by CoderHam** [comment]
@seed93 Triton does not support passing inputs as tuples. You can follow an approach similar to [here](https://github.com/triton-inference-server/server/issues/2025#issuecomment-697961419) to unblock yourself.

**Comment by seed93** [comment]
Thanks. Let's consider this case. We have a python model as the preprocess model, which takes one tensor as input and output nearly 100 tensors to the next pytorch model. Then we have to set 200 tensors in a ensemble config.pbtxt. If tuple could be supported, it would be much simpler.

**Comment by dzier** [comment]
Triton uses only tensors transfer data between backends and the server. This is an architectural limitation of Triton. @seed93, did the work around that @CoderHam provided unblock you on this issue?

**Comment by seed93** [comment]
> Triton uses only tensors transfer data between backends and the server. This is an architectural limitation of Triton. @seed93, did the work around that @CoderHam provided unblock you on this issue?

I wrote a script to handle this, thks.
