### ISSUE TITLE
Windows docker build error, Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by YongHuangSJTU** [triton-inference-server/server#2833]
**Description**
I get this error when I run docker build Dockerfile.win10.min:

Exception calling "DownloadString" with "1" argument(s): "The request was aborted: Could not create SSL/TLS secure
channel."
At line:1 char:1
+ iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

Which is thrown by this line:
_RUN powershell.exe -ExecutionPolicy RemoteSigned iex (new-object net.webclient).downloadstring('https://get.scoop.sh')_

**Triton Information**
What version of Triton are you using?
I'm using master branch with commit 7fbb232baf8d316f8f01b2129979eee677cab026 of May 7th.

**To Reproduce**
Run command   _docker build -t win10-py3-min -f Dockerfile.win10.min ._

**Comment by deadeyegoodwin** [comment]
Can you download https://get.scoop.sh outside of docker?

**Comment by YongHuangSJTU** [comment]
> Can you download https://get.scoop.sh outside of docker?

Yes I can run the command and download it outside docker

**Comment by legarconjoure** [comment]
Calling `docker build` with an additional arg `--network nat` helped me around the network issue inside the container as I was facing a similar situation that my host machine can access get.scoop.sh but not inside the container. (in China)

**Comment by YongHuangSJTU** [comment]
thanks @legarconjoure. I tried it and I got the same error :(

**Comment by deadeyegoodwin** [comment]
Are you following these instrutions carefully? https://github.com/triton-inference-server/server/blob/master/docs/build.md#windows-and-docker
Did you use the --network="Default Switch" flag?

**Comment by tanmayv25** [comment]
Closing the issue because of inactivity for now. If you are still seeing this behavior then please re-open the issue with response to above questions.
