### ISSUE TITLE
Running Triton Without GPU

### ISSUE THREAD

**Issue by svetlana41** [triton-inference-server/server#2838]
**Triton Information**
What version of Triton are you using?
`nvcr.io/nvidia/tritonserver            20.03-py3`

Are you using the Triton container or did you build it yourself?
Helm chart

Hi Everyone,

I do not know if this is an issue, or I am doing something wrong in my configuration. Is there a way to prevent the Triton server from utilizing a GPU? I am using one server, on which I need to use the GPU for something else (training). However, when I start the Triton server it always acquires a GPU whether I specify no resources or not...See logs below:

```
2021-05-10 17:08:10.943697: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-05-10 17:08:10.946880: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Found device 0 with properties: 
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
```
nvidia-smi:

![image](https://user-images.githubusercontent.com/71891134/117699225-9189c980-b192-11eb-8cf8-5616a3b7a2f6.png)

How can I configure it so that it utilizes no GPU? Is that even possible?

Thank you

Svetlana

**Comment by dzier** [comment]
I also note that your version of Triton is over 14 months old. You may also want to consider updating to the latest release, `21.04-py3`. https://ngc.nvidia.com/catalog/containers/nvidia:tritonserver

**Comment by svetlana41** [comment]
> You can specify the KIND in the instance_group to be KIND_CPU in the model configuration. This will allow you to execute a model on a CPU even if there is a GPU available. https://github.com/triton-inference-server/server/blob/master/docs/model_configuration.md#instance-groups.

Hi,

Thank you for your response. 
From what I understood the models are still loaded in the memory of the GPU, and the KIND_CPU just specifies what to use for inference...? So basically there is no way to tell the Triton server not to use a GPU at all? Since the resource I specify in the yaml file does not matter.

We are planning to upgrade it, we held it off since from what I understand client libraries have changed since that release.

Regards

Svetlana

**Comment by svetlana41** [comment]
> You can launch the container without `--gpus` flag. This will make a CPU only instance of the server.
> 
> https://github.com/triton-inference-server/server/blob/master/docs/quickstart.md#run-on-cpu-only-system

I tried that, but maybe I will try again by removing all deployment and re-installing charts from fresh. Thank you for your help.

**Comment by dzier** [comment]
Can you post the model config as well?

**Comment by svetlana41** [comment]
> Can you post the model config as well?

The model config is as follows:

```
name: "1"
platform: "tensorflow_savedmodel"
max_batch_size: 64 
input [
  {
    name: "input_2"
    data_type: TYPE_FP32
    format: FORMAT_NHWC
    dims: [ 256, 256, 3]
  },
  {
    name: "input_3"
    data_type: TYPE_FP32
    format: FORMAT_NHWC
    dims: [ 256, 256, 3]
  }
]
output [
  {
    name: "label_prob"
    data_type: TYPE_FP32
    dims: [ 1 ]
  }
]
instance_group [
    {
      count: 1
      kind: KIND_CPU
    }
]
```

**Comment by dzier** [comment]
If KIND_CPU is specified for a model instances then we ask the framework to load the model onto the CPU,  **not** the GPU. It looks like you are setting the kind correctly for your model.

By default, Triton does allocate a cuda memory pool. This may be the GPU memory usage your are seeing. The memory pool can be disabled by setting `cuda-memory-pool-byte-size` to 0.

**Comment by dzier** [comment]
You are welcome. Closing the issue. Please re-open if you have more questions.
