### ISSUE TITLE
so many server's handler caused server not work

### ISSUE THREAD

**Issue by CColten** [triton-inference-server/server#2843]
**Description**
the tensorrt server when run in a long time, it didn't handle any request 。
we started our services in some GPUs, the trtserver had so many handles when found one TensorRT didn't work, but others are OK;
from the handles' info , we found "protocol:UNIX ", "protocol:TCP", "pipe", "eventpoll" are the mainly causes.

in our client, only using curl in "server\src\clients\c++\api_v1\library\request_http.cc" to request with a curl clean after.
searching about the "pipe", "eventpoll" , found that mainly caused by not shutdown the sock or other connetions.

is any other had met the same question? why the server used so many handlers?

**Triton Information**
What version of Triton are you using?
TensorRT Version: 19.10
NVIDIA GPU: V100
NVIDIA Driver Version: 410.79
CUDA Version: 10.0

Are you using the Triton container or did you build it yourself?
using the Triton container （19.10 and 20.07）

**To Reproduce**
Steps to reproduce the behavior.
running a long time when the handlers' num increasing

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
we put many models together and used,  long time later , one of the servers  hang.

**Expected behavior**

**Comment by kommons** [comment]
@CColten Are you able to upgrade to the current version or is there a reason to stay on that combination?
