### ISSUE TITLE
identity_backend of input_buffer_count

### ISSUE THREAD

**Issue by hanyanLWD** [triton-inference-server/server#2845]
**Description**
identity_backend

**Triton Information**
21.03

question:
In https://github.com/triton-inference-server/identity_backend/tree/r21.03. at src/identity.cc, line 819, for (uint32_t b = 0; b < input_buffer_count; ++b). I want to know why a input tensor such as "INPUT0" has the propertity of "input_buffer_count".
 in function "TRITONBACKEND_InputProperties(input, nullptr /* input_name */, &input_datatype, &input_shape,  &input_dims_count, &input_byte_size, &input_buffer_count))". 
a input tensor has a buffer not multiple????

**Comment by CoderHam** [comment]
The input tensors could be stored in non-contiguous buffers. The number of buffers is what is captured in the input_buffer_count parameter.
If in your case you do not have inputs that are stored in multiple non-contiguous buffers then this will work for that one buffer only.
