### ISSUE TITLE
the preprocess VGG mean-substraction in image_client.cc 

### ISSUE THREAD

**Issue by zoidburg** [triton-inference-server/server#2848]
https://github.com/triton-inference-server/server/blob/b4d6cc227acf5dfe985d7982592764014fbcf047/src/clients/c%2B%2B/examples/image_client.cc#L139

The image has been converted to RGB order before, so maybe the mean value should be (123, 117, 104), just like in the python implementation
https://github.com/triton-inference-server/server/blob/b4d6cc227acf5dfe985d7982592764014fbcf047/src/clients/python/examples/image_client.py#L168

**Comment by dzier** [comment]
Thank you for the feedback. We will investigate and make changes to the example if needed.

**Comment by CoderHam** [comment]
Fixed by https://github.com/triton-inference-server/client/pull/19
