### ISSUE TITLE
Python client support for variable size dimensions

### ISSUE THREAD

**Issue by allenc97** [triton-inference-server/server#2849]
**Is your feature request related to a problem? Please describe.**
One of the features that TRT supports is models with variable size dimensions. A classical use case for variable dimensions is unit detection. (One commonly resizes to the long end of an image while preserving aspect ratios) Currently, using the client library, one has to call `set_data_from_numpy`, which does not check for variable size dimensions. 

**Describe the solution you'd like**
Support variable size dimensions by checking for -1. I recall older client code in TRT 1.0 having checks. 

**Describe alternatives you've considered**
Right now, it seems that users have to either stick with fixed dimensions using the triton grpc client library, or implement their own version of a library by wrapping/calling the native service protobuf and rewrite the size checks.  The latter is fine if that is the direction the project prefers to head in, otherwise it would be greatly preferred to just improve the current library for greater public usage. By extension, one potential missing function is really being able to constructing a bare infer request from a remote model configuration. (I.e converting model_pb2 into corresponding InferInputs and InferOutptus)

If the former is preferred and bandwidth is limited, I can chip in by implementing and submitting a PR.

**Additional context**

**Comment by dzier** [comment]
Triton fully supports variable-sized tensor dimension: https://github.com/triton-inference-server/server/blob/master/docs/model_configuration.md#inputs-and-outputs. This is also supported in the TensorRT Backend. Can you post the full use case or code snippet from where you are not able to set the dimension to -1?

**Comment by allenc97** [comment]
@dzier I think you misunderstood the question. What I am referring to is the client, not the server.

Referring to https://github.com/triton-inference-server/client/blob/main/src/python/examples/simple_grpc_infer_client.py, I am specifically referring to the use of `InferenceServerClient` and `InferInput`. For example,
```
>>> import tritonclient.grpc as grpcclient
>>> import numpy as np
>>> input = grpcclient.InferInput('SAMPLE', [-1, -1, 3], "INT32")
>>> input_data = np.ones((800, 450, 3), dtype="int32")
>>> input.set_data_from_numpy(input_data)
...
tritonclient.utils.InferenceServerException: got unexpected numpy array shape [800, 450, 3], expected [-1, -1, 3]
```

**Comment by tanmayv25** [comment]
For variable shaped tensors, the user must also provide the shape with [set_shape()](https://github.com/triton-inference-server/client/blob/main/src/python/library/tritonclient/grpc/__init__.py#L1439) API. 
You can argue we can extract shape from numpy array but this is done for consistency between `set_data_from_numpy` and `set_shared_memory`. Also, it makes our C++ API where data is provided just as a buffer, consistent with Python as well. 
Even for variable shaped tensors at client. A user must provide fixed shape when providing data. 

```
>>> import tritonclient.grpc as grpcclient
>>> import numpy as np
>>> input = grpcclient.InferInput('SAMPLE', [-1, -1, 3], "INT32")
>>> input_data = np.ones((800, 450, 3), dtype="int32")
>>> input.set_shape(input_data.shape)
>>> input.set_data_from_numpy(input_data)
```

We can improve the error message to indicate use of set_shape call.

**Comment by dzier** [comment]
@allenc97 did this answer resolve your issue?

**Comment by allenc97** [comment]
Yes. I was unaware of the set_shape function call, it solves my problems. Thanks a ton!
