### ISSUE TITLE
 TRITONBACKEND_InputProperties

### ISSUE THREAD

**Issue by hanyanLWD** [triton-inference-server/server#2850]
**Triton Information**
21.03

(1)TRITONBACKEND_InputProperties() can get Properties of input. how to get Properties of output?
(2)In addition, When can you give imgpreprocess backend like r20.03

**Comment by dzier** [comment]
For (1), in the Triton backend, the output properties should be retrieved from the framework, since the framework produces the output. 

For (2), can you expand on your question? Are you looking for Triton to provide a specific example or are you asking about a specific use-case?

**Comment by hanyanLWD** [comment]
I am  looking for Triton to provide a specific example of imgpreprocess backkend like  r20.03 in src/custom/image_preprocess.

**Comment by dzier** [comment]
There is an example of image_preprocessing in the ensembling documentation: https://github.com/triton-inference-server/server/blob/master/docs/architecture.md#ensemble-models

**Comment by dzier** [comment]
Closing the issue for now. If you have more questions, please re-open the issue, or file a new issue.
