### ISSUE TITLE
How to reduce the time consumption of tensor transfer among models in a ensemble model?

### ISSUE THREAD

**Issue by seed93** [triton-inference-server/server#2851]
If I want to ensemble a python model and a pytorch model, how to reduce the communication time? The intermediate tensors are extremely huge and I want it to keep in memory, but not transferred through network.

**Comment by CoderHam** [comment]
Did you try to use shared memory? Triton supports the both system and cuda shared memory.
Additionally ensembles in Triton do not use network to copy across tensors. The I/O between models in ensembled occurs in memory.

**Comment by dzier** [comment]
For information on setting up model ensembles, please refer to  https://github.com/triton-inference-server/server/blob/master/docs/architecture.md#ensemble-models. For information on shared memory, please refer to https://github.com/triton-inference-server/server/blob/master/docs/protocol/extension_shared_memory.md

**Comment by dzier** [comment]
Closing issue for now. Please re-open issue if you have more questions about shared memory.
