### ISSUE TITLE
How to accelerate the Triton when loading TensorRT plan.

### ISSUE THREAD

**Issue by sunhailin-Leo** [triton-inference-server/server#2852]
Questions: 
*  I have a Bert model with TensorRT. When I using Triton to load the model, it takes a long time to load it.
*  I noticed that Triton is using both memory and GPU memory when loading the model, why is that?

**Comment by dzier** [comment]
Can you provide the model and server configurations you are using?

**Comment by sunhailin-Leo** [comment]
@dzier 
* Model is too large, but we use the bert-base to fine-tune.
* Config is here
```
platform: "tensorrt_plan"
max_batch_size: 4

optimization {
  cuda { 
    output_copy_stream: true
    busy_wait_events: true 
  }
}

input [
    {
        name: "segment_ids"
        data_type: TYPE_INT32
        dims: 32
    },
    {
        name: "input_ids"
        data_type: TYPE_INT32
        dims: 32
    },
    {
        name: "input_mask"
        data_type: TYPE_INT32
        dims: 32
    }
    ]

output [
    {
        name: "embedding"
        data_type: TYPE_FP32
        dims: [ 768, 1, 1 ]
    },
    {
        name: "probability"
        data_type: TYPE_FP32
        dims: [ 1, 1, 1 ]
    },
    {
        name: "index"
        data_type: TYPE_INT32
        dims: [ 1, 1, 1 ]
    }
]

dynamic_batching {
    preferred_batch_size: [ 1, 2, 4 ]
    max_queue_delay_microseconds: 100
  }

instance_group [
    {
        gpus: [ 2, 3 ]
        count: 1
        kind: KIND_GPU
        profile: "0"
        profile: "1"
        profile: "2"
    }
]
```

**Comment by sunhailin-Leo** [comment]
@dzier 
* Model Size：600 MB
* Model Storage: Local File
* Logs & Load: In the verbose log, it run the QKV function when loading the model, because the Bert model will load TensorRT fast-transformer class. 

Question: How can I pin memory to the stage when loading the model?

**Comment by sunhailin-Leo** [comment]
@dzier 
About the model: We use TensorFlow to fine-tune the Bert-base, after the training task, we use TensorRT convert the `savemodel` to `tensorrt plan`. [Converter scripts like here](https://github.com/NVIDIA/TensorRT/blob/master/demo/BERT/builder.py)

**Comment by tanmayv25** [comment]
> I have a Bert model with TensorRT. When I using Triton to load the model, it takes a long time to load it.

In the verbose mode(--log-verbose=1), TensorRT itself should print the time taken to deserialize the plan file. Can you share verbose logs from the server? It will help us understand where the majority of the time is being spent and overhead from Triton. If most of the time is spent in deserializing plan file then this question needs to be forwarded to our TensorRT team.

That being said: 

>         profile: "0"
>         profile: "1"
>         profile: "2"

I see that you are using 3 optimization profiles. The dynamic shape being handled seems to be the batch dimension. You can reduce the model load time by using lesser optimization profiles. Triton initializes buffers for each optimization profile separately. So, this might help reducing the load time. 

> I noticed that Triton is using both memory and GPU memory when loading the model, why is that?
Triton allocates buffer on GPU during the load time. The data transfer from pinned CPU memory to GPU is faster than normal CPU memory to GPU. Hence, Triton uses a CPU pinned memory pool as well.
