### ISSUE TITLE
Triton does not load the latest available model in explicit mode.

### ISSUE THREAD

**Issue by nsiddharth** [triton-inference-server/server#2853]
**Description**
using model control mode as explicit, it is expected that Triton will load the latest available model when a new model version is added and load_model is called. However, this does not happen and load_model returns only the already loaded model. This can be tested by adding a new version directory for the simple model provided in the examples. Note that a new version directory is added after Triton has started up. However, this works when unload_model is called followed by load model
**Triton Information**
What version of Triton are you using?
2.8.0
Are you using the Triton container or did you build it yourself?
Using the container
**To Reproduce**
Steps to reproduce the behavior.
Use a simple script like so to test this behavior:
```
import tritonclient.grpc as grpcclient
from tritonclient.utils import InferenceServerException

MODEL_NAME = "simple"

URL = "localhost:8001"
triton_client = grpcclient.InferenceServerClient(url=URL, verbose=True)

triton_client.is_server_live()
print(triton_client.is_model_ready(MODEL_NAME))
triton_client.get_model_repository_index().models

"""
model loading and unloading 
This should pickup the latest available model
without having to call:
triton_client.unload_model(MODEL_NAME)
"""
triton_client.load_model(MODEL_NAME)
"""This should show that the latest model is available"""
triton_client.get_model_repository_index().models

```
Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
The model used to test this was the simple model provided in the examples
**Expected behavior**
when a new version is added to the model repo like so:
`aws s3 cp --recursive 2 s3://<Model_repo>/simple/2`
and load_model is called, the latest model should be loaded and made available. This does not happen. 
However, this takes effect if unload_model is called before calling load_model again. We do not want this behavior in production where you need to unload the model causing downtime before you are able to load a new one.

**Comment by dzier** [comment]
Your expectation for explicit mode is incorrect. What you are describing is the POLL mode. In EXPLICIT mode, you need to explicitly unload the model before you can load the model again with the new changes. In your example code, it appears you are commenting out the `triton_client.unload_model(MODEL_NAME)`. 

Additional information can be found here: https://github.com/triton-inference-server/server/blob/master/docs/model_management.md#modifying-the-model-repository

**Comment by nsiddharth** [comment]
It seems like POLL model should not be used in production according to the docs. However, if we need the ability to upload a new version and have triton pick up the latest version we need to first unload and then call load? will this not also result in downtime? How can we avoid downtime in production when we need to upload retrained daily models and have triton pick up the latest version? Am I missing something or is this use-case not supported?

**Comment by nsiddharth** [comment]
Some clarification on how to do this in production would be welcome.

**Comment by dzier** [comment]
I am soliciting some feedback from my team. In general, a model has to be unloaded to remove it from GPU memory before a new version of the model can be loaded. What I am trying to determine is the impact of the downtime, if any and get some suggestions on how to mitigate the downtime.

We are developing a new tool, [Model Navigator](https://github.com/triton-inference-server/model_navigator), which helps managing and deploying models in Triton. Feel free to investigate and see if it will work for your use case.

**Comment by nsiddharth** [comment]
Please let me know what you find. I think this is a common enough use-case that needs to be addressed by triton if it is to be used in production environments.

**Comment by GuanLuo** [comment]
Can you attach the server log in the case when you try to reload the model with new version?

**Comment by dzier** [comment]
@nsiddharth it appears this may be a bug. You should be able to load the model again to get the newer version without downtime. We will attempt to reproduce and debug the issue. In the meantime, can you attach the server log as @GuanLuo requested?

**Comment by nsiddharth** [comment]
To be clear you want me to attach the server log when I call `load_model()` without first calling unload model, right? Should triton be started in a verbose mode? can you tell me what flag to use or a normal startup is ok?

**Comment by nsiddharth** [comment]
`=============================
== Triton Inference Server ==
=============================

NVIDIA Release 21.03 (build 20851776)

Copyright (c) 2018-2021, NVIDIA CORPORATION.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use Docker with NVIDIA Container Toolkit to start this container; see
   https://github.com/NVIDIA/nvidia-docker.

I0513 20:28:05.357503 1 libtorch.cc:940] TRITONBACKEND_Initialize: pytorch
I0513 20:28:05.358362 1 libtorch.cc:950] Triton TRITONBACKEND API version: 1.0
I0513 20:28:05.358378 1 libtorch.cc:956] 'pytorch' TRITONBACKEND API version: 1.0
2021-05-13 20:28:05.946710: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
I0513 20:28:06.015671 1 tensorflow.cc:1880] TRITONBACKEND_Initialize: tensorflow
I0513 20:28:06.015756 1 tensorflow.cc:1890] Triton TRITONBACKEND API version: 1.0
I0513 20:28:06.015763 1 tensorflow.cc:1896] 'tensorflow' TRITONBACKEND API version: 1.0
I0513 20:28:06.015772 1 tensorflow.cc:1920] backend configuration:
{}
I0513 20:28:06.025344 1 onnxruntime.cc:1728] TRITONBACKEND_Initialize: onnxruntime
I0513 20:28:06.025412 1 onnxruntime.cc:1738] Triton TRITONBACKEND API version: 1.0
I0513 20:28:06.025424 1 onnxruntime.cc:1744] 'onnxruntime' TRITONBACKEND API version: 1.0
I0513 20:28:06.107854 1 openvino.cc:1166] TRITONBACKEND_Initialize: openvino
I0513 20:28:06.107954 1 openvino.cc:1176] Triton TRITONBACKEND API version: 1.0
I0513 20:28:06.107967 1 openvino.cc:1182] 'openvino' TRITONBACKEND API version: 1.0
E0513 20:28:06.108825 1 pinned_memory_manager.cc:202] failed to allocate pinned system memory: CUDA driver version is insufficient for CUDA runtime version
I0513 20:28:12.683858 1 model_repository_manager.cc:1065] loading: simple:4
I0513 20:28:16.037740 1 tensorflow.cc:1980] TRITONBACKEND_ModelInitialize: simple (version 4)
I0513 20:28:16.051406 1 tensorflow.cc:2029] TRITONBACKEND_ModelInstanceInitialize: simple (CPU device 0)
2021-05-13 20:28:16.055994: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2021-05-13 20:28:16.056046: E tensorflow/stream_executor/cuda/cuda_driver.cc:339] failed call to cuInit: UNKNOWN ERROR (303)
2021-05-13 20:28:16.056073: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (661198f1ea9e): /proc/driver/nvidia/version does not exist
2021-05-13 20:28:16.092966: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2304000000 Hz
2021-05-13 20:28:16.094675: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f3bbc133a70 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-05-13 20:28:16.094730: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
I0513 20:28:16.114088 1 model_repository_manager.cc:1239] successfully loaded 'simple' version 4
I0513 20:28:16.116818 1 server.cc:500]
+------------------+------+
| Repository Agent | Path |
+------------------+------+
+------------------+------+

I0513 20:28:16.117177 1 server.cc:527]
+-------------+-----------------------------------------------------------------+--------+
| Backend     | Path                                                            | Config |
+-------------+-----------------------------------------------------------------+--------+
| pytorch     | /opt/tritonserver/backends/pytorch/libtriton_pytorch.so         | {}     |
| tensorflow  | /opt/tritonserver/backends/tensorflow1/libtriton_tensorflow1.so | {}     |
| onnxruntime | /opt/tritonserver/backends/onnxruntime/libtriton_onnxruntime.so | {}     |
| openvino    | /opt/tritonserver/backends/openvino/libtriton_openvino.so       | {}     |
+-------------+-----------------------------------------------------------------+--------+

I0513 20:28:16.117312 1 server.cc:570]
+--------+---------+--------+
| Model  | Version | Status |
+--------+---------+--------+
| simple | 4       | READY  |
+--------+---------+--------+

I0513 20:28:16.118692 1 tritonserver.cc:1658]
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+
| Option                           | Value                                                                                                                                              |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+
| server_id                        | triton                                                                                                                                             |
| server_version                   | 2.8.0                                                                                                                                              |
| server_extensions                | classification sequence model_repository schedule_policy model_configuration system_shared_memory cuda_shared_memory binary_tensor_data statistics |
| model_repository_path[0]         | s3://<model_repo>/                                                                              |
| model_control_mode               | MODE_EXPLICIT                                                                                                                                      |
| startup_models_0                 | simple                                                                                                                                             |
| strict_model_config              | 1                                                                                                                                                  |
| pinned_memory_pool_byte_size     | 268435456                                                                                                                                          |
| min_supported_compute_capability | 6.0                                                                                                                                                |
| strict_readiness                 | 1                                                                                                                                                  |
| exit_timeout                     | 30                                                                                                                                                 |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+

I0513 20:28:16.152361 1 grpc_server.cc:3983] Started GRPCInferenceService at 0.0.0.0:8001
I0513 20:28:16.153924 1 http_server.cc:2717] Started HTTPService at 0.0.0.0:8000
I0513 20:28:16.206411 1 http_server.cc:2736] Started Metrics Service at 0.0.0.0:8002`

**Comment by nsiddharth** [comment]
calling load_model from the script shown above does not produce any additional logs and index shows that the same version is still loaded in memory. so like 
` aws s3 ls s3://<model_repository>/simple/
                           PRE 1/
                           PRE 2/
                           PRE 3/
                           PRE 4/
2020-11-21 20:42:19        370 config.pbtxt`

the index call returns the correct model in this case like this:
`models {
  name: "simple"
  version: "4"
  state: "READY"
}`

after adding a new version model repo is updated like so with version 5:
`aws s3 ls s3://<model_repository>/simple/
                           PRE 1/
                           PRE 2/
                           PRE 3/
                           PRE 4/
                           PRE 5/
2020-11-21 20:42:19        370 config.pbtxt`

but load_model is not loading this as can be seen by the index call:
`models {
  name: "simple"
  version: "4"
  state: "READY"
}`
which returns version 4 even though 5 is now available in the repo

**Comment by GuanLuo** [comment]
>To be clear you want me to attach the server log when I call load_model() without first calling unload model, right?

Yes. Does the log you posted cover the `load_model()` part? If so, it seems like the change in cloud storage is not detected and thus Triton assumes nothing needs to be done for a previously loaded model, which is a bug.

**Comment by nsiddharth** [comment]
yes, the log I posted covers the `load_model()` part. nothing is registered in the logs when that call is made as opposed to unloading and then loading. those calls get registered in the server logs

**Comment by CoderHam** [comment]
I tested the model control explicit mode. Works fine with a local repo. Testing with an S3 repo to see if the error lies there.
PS: You can launch the server with `--log-verbose=1`  that should allow you to see loading/unloading logs from the model_repository_manager.

1. Load model: `curl -X POST localhost:8000/v2/repository/models/resnet50_libtorch/load`
2. List models: `curl -X POST localhost:8000/v2/repository/index`
```
[{"name":"resnet50_libtorch","version":"2","state":"READY"}]
```
3. Create new version of model: `(cd repo/resnet50_libtorch && cp -r 1 2)`
4. Load the same model: `curl -X POST localhost:8000/v2/repository/models/resnet50_libtorch/load`
5. List models: `curl -X POST localhost:8000/v2/repository/index`
```
[{"name":"resnet50_libtorch","version":"1","state":"UNAVAILABLE","reason":"unloaded"},{"name":"resnet50_libtorch","version":"2","state":"READY"}]
```

Repo structure
```
repo
`-- resnet50_libtorch
    |-- 1
    |   `-- model.pt
    |-- config.pbtxt
    `-- resnet50_labels.txt
```

**Comment by CoderHam** [comment]
I ran my tests on the latest master was able to confirm that using an S3 model repo for the above steps works as expected as well. @nsiddharth can you try to re-run your experiments with the latest (21.05) release?

**Comment by nsiddharth** [comment]
Do I need to build from source to test this?

**Comment by CoderHam** [comment]
You can use NGC container for 21.05.
If you want to work with master you will need to build from source yes.

**Comment by nsiddharth** [comment]
I tested this with 21.05 and it does not work. The server logs do not show unloading and loading of the model. I suppose I must try building it from source and test? Did this work on your end with 21.05?

**Comment by nsiddharth** [comment]
@CoderHam, In the example you have posted it shows that `version 2` is in the ready state before you do the copy. Should it not be `version 1`?
I ask because I tried building from source on the main branch and I still cannot get it to work. Unloading and loading works or restarting triton picks up the latest model which suggests that the format and versioning of the repo is fine. Posting the server logs here. It does not seem to load the latest version. 
```
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Option                           | Value                                                                                                                                                                                  |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| server_id                        | triton                                                                                                                                                                                 |
| server_version                   | 2.11.0dev                                                                                                                                                                              |
| server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_policy model_configuration system_shared_memory cuda_shared_memory binary_tensor_data statistics |
| model_repository_path[0]         | s3://medium-production-models-us-east-1/triton_test/model_repository/                                                                                                                  |
| model_control_mode               | MODE_EXPLICIT                                                                                                                                                                          |
| startup_models_0                 | simple                                                                                                                                                                                 |
| strict_model_config              | 1                                                                                                                                                                                      |
| pinned_memory_pool_byte_size     | 268435456                                                                                                                                                                              |
| min_supported_compute_capability | 6.0                                                                                                                                                                                    |
| strict_readiness                 | 1                                                                                                                                                                                      |
| exit_timeout                     | 30                                                                                                                                                                                     |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

I0524 04:44:19.193163 1 grpc_server.cc:225] Ready for RPC 'ServerLive', 0
I0524 04:44:19.193246 1 grpc_server.cc:225] Ready for RPC 'ServerReady', 0
I0524 04:44:19.193272 1 grpc_server.cc:225] Ready for RPC 'ModelReady', 0
I0524 04:44:19.193294 1 grpc_server.cc:225] Ready for RPC 'ServerMetadata', 0
I0524 04:44:19.193330 1 grpc_server.cc:225] Ready for RPC 'ModelMetadata', 0
I0524 04:44:19.193906 1 grpc_server.cc:225] Ready for RPC 'ModelConfig', 0
I0524 04:44:19.194137 1 grpc_server.cc:225] Ready for RPC 'ModelStatistics', 0
I0524 04:44:19.194695 1 grpc_server.cc:225] Ready for RPC 'SystemSharedMemoryStatus', 0
I0524 04:44:19.194756 1 grpc_server.cc:225] Ready for RPC 'SystemSharedMemoryRegister', 0
I0524 04:44:19.194783 1 grpc_server.cc:225] Ready for RPC 'SystemSharedMemoryUnregister', 0
I0524 04:44:19.194807 1 grpc_server.cc:225] Ready for RPC 'CudaSharedMemoryStatus', 0
I0524 04:44:19.195909 1 grpc_server.cc:225] Ready for RPC 'CudaSharedMemoryRegister', 0
I0524 04:44:19.196563 1 grpc_server.cc:225] Ready for RPC 'CudaSharedMemoryUnregister', 0
I0524 04:44:19.196623 1 grpc_server.cc:225] Ready for RPC 'RepositoryIndex', 0
I0524 04:44:19.197217 1 grpc_server.cc:225] Ready for RPC 'RepositoryModelLoad', 0
I0524 04:44:19.197265 1 grpc_server.cc:225] Ready for RPC 'RepositoryModelUnload', 0
I0524 04:44:19.197339 1 grpc_server.cc:416] Thread started for CommonHandler
I0524 04:44:19.198739 1 grpc_server.cc:3144] New request handler for ModelInferHandler, 1
I0524 04:44:19.198825 1 grpc_server.cc:2202] Thread started for ModelInferHandler
I0524 04:44:19.199590 1 grpc_server.cc:3497] New request handler for ModelStreamInferHandler, 3
I0524 04:44:19.199676 1 grpc_server.cc:2202] Thread started for ModelStreamInferHandler
I0524 04:44:19.199686 1 grpc_server.cc:4062] Started GRPCInferenceService at 0.0.0.0:8001
I0524 04:44:19.201244 1 http_server.cc:2744] Started HTTPService at 0.0.0.0:8000
I0524 04:44:19.252649 1 http_server.cc:162] Started Metrics Service at 0.0.0.0:8002



I0524 04:47:57.225451 1 grpc_server.cc:270] Process for RepositoryIndex, rpc_ok=1, 0 step START
I0524 04:47:57.226046 1 grpc_server.cc:225] Ready for RPC 'RepositoryIndex', 1
I0524 04:48:00.368685 1 model_repository_manager.cc:568] BackendStates()
I0524 04:48:00.371471 1 grpc_server.cc:270] Process for RepositoryIndex, rpc_ok=1, 0 step COMPLETE
I0524 04:48:00.371679 1 grpc_server.cc:408] Done for RepositoryIndex, 0

I0524 04:49:21.049047 1 grpc_server.cc:270] Process for RepositoryModelLoad, rpc_ok=1, 0 step START
I0524 04:49:21.049119 1 grpc_server.cc:225] Ready for RPC 'RepositoryModelLoad', 1
I0524 04:49:29.384910 1 model_repository_manager.cc:592] VersionStates() 'simple'
I0524 04:49:29.386734 1 grpc_server.cc:270] Process for RepositoryModelLoad, rpc_ok=1, 0 step WRITEREADY
I0524 04:49:29.388904 1 grpc_server.cc:270] Process for RepositoryModelLoad, rpc_ok=1, 0 step COMPLETE
I0524 04:49:29.388962 1 grpc_server.cc:408] Done for RepositoryModelLoad, 0
```
I ran an aws s3 cp like so : 
`ok aws s3 cp --recursive 2 s3://<repo>/triton_test/model_repository/simple/8`
I caleed LoadModel and expected version 8 to be picked
As you can see, the load model call does not unload the previous version in the server logs.. The only difference is that I am making a grpcurl call to load like so:
`grpcurl -proto proto/triton/grpcService.proto -plaintext  -d '{"model_name":"simple"}' localhost:8001  inference.GRPCInferenceService.RepositoryModelLoad`

calling Index shows the previous version as is.
```
    {
      "name": "simple",
      "version": "7",
      "state": "READY"
    },
```
Am i missing something?

**Comment by nsiddharth** [comment]
@CoderHam After going through the code in detail, I was able to find the issue. I cannot imagine how this could've worked with an s3 repo because it is comparing Milliseconds to Nanoseconds. I have created a PR for this. Please merge if it looks ok.

PS: It took me a lot of time to go through the code meticulously and find the bug which may have been a lot faster on Triton devs end. If triton is to be considered seriously for prod envs, please do not be in a haste to close issues which the community is raising. Also, I am not sure how the tests with s3 could have succeeded with this bug in place. I request you to update your tests if they were not able to catch this.

**Comment by nsiddharth** [comment]
@CoderHam yes, I tested the fix and it seems to resolve my issue of loading the latest model correctly. I did start triton in explicit mode as can be seen from the server logs here:
```
I0528 20:10:38.900626 1 tritonserver.cc:1659]
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Option                           | Value                                                                                                                                                                                  |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| server_id                        | triton                                                                                                                                                                                 |
| server_version                   | 2.11.0dev                                                                                                                                                                              |
| server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_policy model_configuration system_shared_memory cuda_shared_memory binary_tensor_data statistics |
| model_repository_path[0]         | s3://medium-production-models-us-east-1/triton_test/model_repository/                                                                                                                  |
| model_control_mode               | MODE_EXPLICIT                                                                                                                                                                          |
| startup_models_0                 | simple                                                                                                                                                                                 |
| strict_model_config              | 1                                                                                                                                                                                      |
| pinned_memory_pool_byte_size     | 268435456                                                                                                                                                                              |
| min_supported_compute_capability | 6.0                                                                                                                                                                                    |
| strict_readiness                 | 1                                                                                                                                                                                      |
| exit_timeout                     | 30                                                                                                                                                                                     |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

That being said, you know the code base better so if it should not be affectting `explicit mode` function then it maybe some other bug but in my case it was calling Poll and not getting the proper modified time. I had some print statements in the code and I am pasting them here if it helps you debug. 

```
I0528 20:14:17.039786 1 grpc_server.cc:270] Process for RepositoryModelLoad, rpc_ok=1, 0 step START
I0528 20:14:17.039936 1 grpc_server.cc:225] Ready for RPC 'RepositoryModelLoad', 1
I0528 20:14:17.042384 1 server.cc:465]  action type from server.cc 1
I0528 20:14:17.042507 1 server.cc:466]  action type from server.cc 1
I0528 20:14:17.042548 1 model_repository_manager.cc:1528] Inside LoadUnloadModels : model_repo_manager.cc
I0528 20:14:17.042564 1 model_repository_manager.cc:1529] Inside LoadUnloadModels : model_repo_manager.cc
I0528 20:14:17.042579 1 model_repository_manager.cc:1540] Should Reach here in LoadUnloadModels()
I0528 20:14:17.042604 1 model_repository_manager.cc:1746] Inside Poll  : model_repo_manager.cc :
I0528 20:14:17.042618 1 model_repository_manager.cc:1776] Inside else: Should reach here for Load : in Poll()
I0528 20:14:17.042639 1 model_repository_manager.cc:1782] Inside else: full path to model : in  Poll() s3://medium-production-models-us-east-1/triton_test/model_repository/simple
I0528 20:14:17.633703 1 model_repository_manager.cc:1790] Inside else: found model in repo : in Poll()
I0528 20:14:17.633771 1 model_repository_manager.cc:1792] Model exists : Poll()
I0528 20:14:17.633778 1 model_repository_manager.cc:1824] child : simple repo: 's3://<model_repo>/triton_test/model_repository/'
I0528 20:14:17.633790 1 model_repository_manager.cc:1827] Full path : in Poll() s3://<model_repo>/triton_test/model_repository/simple
I0528 20:14:17.633838 1 model_repository_manager.cc:1831] Check if new version present : Poll()
I0528 20:14:17.633869 1 model_repository_manager.cc:1842] STATE MODIFIED: Passing mtime in model config to compare in IsModified() : Poll() 1622215328000000 State: 2
```
Thanks for looking into it.

**Comment by CoderHam** [comment]
Closed by https://github.com/triton-inference-server/server/pull/2957
