### ISSUE TITLE
smaller size docker image with specific functions

### ISSUE THREAD

**Issue by yjegssl** [triton-inference-server/server#2856]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when pulling such a big triton server image (more than 10G), most features in which I never use.
**Describe the solution you'd like**
method and clear instruction on building custom triton image, e.g : only support cv tasks with torch script model with a smaller size docker image : maybe about 3 G

**Additional context**

**Comment by seed93** [comment]
Maybe you want to minimal backends? Pls refer to [here](https://github.com/triton-inference-server/server/blob/master/docs/compose.md#triton-with-unsupported-and-custom-backends).

**Comment by dzier** [comment]
@seed93 is correct. You will want to start with the Triton minimum container as a base container and add in the just the additional backends you require.  Closing the issue for now, if you have more questions, please re-open the issue.
