### ISSUE TITLE
failed to load all models

### ISSUE THREAD

**Issue by Amanda-Barbara** [triton-inference-server/server#2858]
I failed to load all models when I execute the local tritonserver I built from the Building without Docker tutorial,  the local model path I checked is correct. This is my execution process:
/tmp/citritonbuild/tritonserver/install/bin$ ./tritonserver --model-repository=/models
error: creating server: Internal - failed to load all models
my model path is:
ls /models/
densenet_onnx  inception_graphdef  simple  simple_dyna_sequence  simple_identity  simple_int8  simple_sequence  simple_string
how to solve it ? thanks.

**Comment by tanmayv25** [comment]
You must take a look on the complete logs to see more exact error of what models failed and why..

**Comment by KevenLee** [comment]
> You must take a look on the complete logs to see more exact error of what models failed and why..
I got the same error: 
https://github.com/isarsoft/yolov4-triton-tensorrt/issues/32

**Comment by deadeyegoodwin** [comment]
Run with --log-verbose=1 and look at entries beginning with 'E' (for error) and also the tables printed near the end of the output. Please share that log.

**Comment by tanmayv25** [comment]
Closed due to inactivity. Please re-open if still facing this issue.
