### ISSUE TITLE
How to stop ensemble pipeline

### ISSUE THREAD

**Issue by gouravvemula0** [triton-inference-server/server#2865]
How to stop the ensemble pipeline. The use-case is to not call other models in the pipeline if first model returns a specific value. ?

**Comment by GuanLuo** [comment]
Currently the ensemble doesn't provide functionality to evaluate a intermediate tensor value and stop the pipeline early. However, we working on a solution internally that may address this use case

**Comment by deadeyegoodwin** [comment]
@GuanLuo  Is referring to "Business Logic Scripting". You can read about how you can try it with the current Triton and what improvements we are working on. https://docs.google.com/document/d/1_5PCQvWNxb32-T97E7P5aZxbCnFmuNKc0bPOoFqxtzo
