### ISSUE TITLE
Yolov5 - preprocess in infer config file

### ISSUE THREAD

**Issue by htran170642** [triton-inference-server/server#2868]
Can anyone help me to write my preprocess? I didnt get any bounding box after running deepstream app. Thank you so much
![image](https://user-images.githubusercontent.com/70887055/118452992-eabca480-b720-11eb-86da-4daf346fb59d.png)

![image](https://user-images.githubusercontent.com/70887055/118452503-6bc76c00-b720-11eb-8c2f-809e3442dd50.png)

![image](https://user-images.githubusercontent.com/70887055/118452553-797cf180-b720-11eb-8564-1dc225c113af.png)

**Comment by deadeyegoodwin** [comment]
You should ask in the DeepStream forum: https://forums.developer.nvidia.com/c/accelerated-computing/intelligent-video-analytics/deepstream-sdk/15
