### ISSUE TITLE
Reshape did not work for python backend

### ISSUE THREAD

**Issue by okyspace** [triton-inference-server/server#2870]
I have a model.py with config.pbtxt which will accept >=1 image tensor of variable shape but 3 channels. 
But I would need the output to be (3, 384, 128) shape so that I can input to next model. 
However I always get (294912,) as the output which is 2 x 3 x 384 x 128 (NCHW), even with the defined output shape + reshape. 
I couldn't find much documentation or examples on reshape and output dimension. Would appreciate your help. 

```
name: "preprocess"
backend: "python"
max_batch_size: 16
input [
  {
    name: "INPUT"
    data_type: TYPE_FP32
    format: FORMAT_NHWC
    dims: [ -1, -1, 3 ]
    
  }
]

output [
  {
    name: "OUTPUT"
    data_type: TYPE_FP32
    dims: [ 3, 384, 128 ]
    reshape: { shape: [ 3, 384, 128 ] }
  }
]


instance_group [{ kind: KIND_CPU }]`
```

**Triton Information**
20.12-py3

This is my TritonPythonClass:

```
class TritonPythonModel:
    def initialize(self, args):
        self.model_config = model_config = json.loads(args['model_config'])
        output_config = pb_utils.get_output_config_by_name(
            model_config, OUTPUT_NAME)

        self.output_dtype = pb_utils.triton_string_to_numpy(
            output_config['data_type'])
        self.output_dims = output_config['dims']

    def execute(self, requests):
        responses = []

        # Every Python backend must iterate over everyone of the requests
        # and create a pb_utils.InferenceResponse for each of them.
        for x, request in enumerate(requests):
            # Get INPUT and convert to numpy
            i = pb_utils.get_input_tensor_by_name(request, INPUT_NAME).as_numpy()

            # Get batch size
            batch_size = i.shape[0]
            input_shape = self.output_dims
            input_shape = np.insert(input_shape, 0, batch_size)

            # Resize input to a desired output shape
            out = np.resize(i, input_shape)
            out_tensor = pb_utils.Tensor(OUTPUT_NAME, out.astype(self.output_dtype))

            # Create InferenceResponse. 
            inference_response = pb_utils.InferenceResponse(
                output_tensors=[out_tensor])
            responses.append(inference_response)

        return responses

```

**Comment by deadeyegoodwin** [comment]
Your python code is creating the shape of the output to match OUTPUT dims, are you not seeing that shape in the response?
Your reshape doesn't do anything for 2 reasons:
1. it is the same as dims
2. I don't believe the python backend is handling it correctly. FYI, @Tabrizian 

reshape on an output should change the shape of the output produced by your python code [ 3, 384, 128 ] in this case, to some other shape that is returned in the response (but of course has same number of elements).

**Comment by okyspace** [comment]
@deadeyegoodwin , i did get the shape in the response but the data is a 1-D list instead of the shape. Although i can reshape it to get back what I want but I cannot be sure if this works if I chain up in model pipelines. Is this supposed to be the correct behavior?

**Comment by Tabrizian** [comment]
Python backend is likely not handling reshaping properly. I filed a bug to investigate it.

**Comment by deadeyegoodwin** [comment]
@okyspace can you share your client code where you are reading the response. I'm not sure how you are getting the correct response shape but then having the actual data be a different shape.

**Comment by okyspace** [comment]
@deadeyegoodwin , this is the client code I have used. Basically I have a main function to call this infer function. 
This infer function does a REST call to triton server. 

```
def infer(img_paths, batch_size, model_name, model_ver, input_name, input_datatype, input_shape, output_name, output_datatype, output_shape):
    # /v2/models/{MODEL_NAME}/versions/{VERSION}/infer
    url = 'http://' + TRITON_IP + ':' + TRITON_HTTP_PORT + '/v2/models/' + model_name + '/versions/' + model_ver + '/infer'
    
    # read img and get tensor
    input_data = []
    for i in range(batch_size):
        img_path = img_paths[i]
        img = cv2.imread(img_path)
        input_data.append(img)

    input_data = np.array(input_data)
    print("input_data: ", input_data.shape)

    # construct inference request body
    infer_req = {
        "id": "optional-use-if-need-to-check-against-http-return",
        "inputs": [
            {
                "name": input_name,
                "shape": input_data.shape,
                "datatype": input_datatype,
                "data": input_data.tolist()
            }
        ],
        "outputs": [
            {
                "name": output_name,
            }
        ]
    }

    headers = {'Content-type': 'application/json'}
    resp = requests.post(url, data=json.dumps(infer_req), headers=headers)
    if resp.status_code == 200:
        print(".... inference SUCCESS ....")
            r = response.json()
            # this is where I got the shape and this shape is correct.
            output_shape = r['outputs'][0]['shape']
            # this is where I got the data but is a 1-D list. 
            embeds = r['outputs'][0]['data']
            embeds = np.array(embeds)
            print("embeds: ", embeds.shape)
            # I could reshape the 1-D array based on the shape gotten but was expecting the data from triton to be of correct shape
            embeds = np.reshape(embeds, output_shape)
           print("embeds: ", embeds.shape)

```

**Comment by deadeyegoodwin** [comment]
I there a reason you are not using the Triton Python client module? https://github.com/triton-inference-server/client
It would handle the reshape for you.

But if you are writing your own then you do need to do the reshape. The Triton protocol does all the server to return the output tensors as a flattened 1-D vector and that is what Triton does: https://github.com/kubeflow/kfserving/blob/master/docs/predict-api/v2/required_api.md#tensor-data

**Comment by okyspace** [comment]
@deadeyegoodwin , thanks for the clarification. I am using own implementation as I may have environment that do not allow install of triton client library. 

I have read the link you shared, it was not clear to me that Triton server will always return a flattened 1-D vector. I had this impression that it may return the nature multi-dimension vectors if we defined the output dims or include reshape configuration in config.pbtxt. 

Can I confirm that regardless, Triton will only return 1-D flattened vector? 

Also on related note, I am intending to pipeline this model 1 with another model 2. 
If triton provides 1-D flattened vector as model 1 output, but my model 2 input requires a certain shape, adding the reshape config will help?

Appreciate your help.

**Comment by deadeyegoodwin** [comment]
The protocol allows the server to return a json tensor as either a 1-D vector or as a multi-D array matching the shape. Triton will always return as a 1-D vector.

You will need to reshape the output tensor if you want the numpy to reflect the actual shape of the tensor. numpy reshape should be a very efficient operation as it doesn't need to change the data.

BTW, if you are using the pure json http format (*not* using binary data format) and you have large input and/or output tensors, then your network communication is likely going to be a bottleneck because json is inefficient in representing large tensors.
