### ISSUE TITLE
Questions related to shared memory

### ISSUE THREAD

**Issue by kpedro88** [triton-inference-server/server#2872]
Context: I have been implementing an interface that swaps between gRPC, CPU shared memory, or GPU shared memory at runtime, handling all the complexity to simplify the implementation of actual inference requests. The goal is to pick the best option as automatically as possible.

With that in mind, I have several questions about Triton's shared memory support specifically, and some related questions about Triton server features.

1. Why does registering a shared memory region require both a name and a key? I understand the optimization to avoid re-opening a region that is already known, but I don't see a reason to have two distinct fields to keep track of this. https://github.com/triton-inference-server/server/blob/v2.9.0/src/servers/shared_memory_manager.cc#L218-L243
2. Is there a way to check if a given server is local and able to read shared memory from the CPU where the client is running? (I could imagine sending a dummy inference request, e.g. with an identity model, through the shared memory mode to see if it works, but it would be nicer if this were a bit more automated/simplified.)
3. Is there a way to ask the server if it is running on CPU or running on GPU?
4. Is there a way to check the GPU device number(s) for the GPU(s) being used by the server?

**Comment by deadeyegoodwin** [comment]
1. The name is in triton "namespace" and key is in OS/system namespace. The name is also used for cuda shm when their is not a named key so I assume we did it for consistency. @CoderHam do you have any other comment?
2. You would need to know if two processes were running on the same server. Not sure if there is a general way to do that. Client is access the server by a URL so perhaps from that you can get a hostname and do something with that? Triton doesn't provide anything specific for determining this.
3. Are you asking for a way to know, for a given model, if any/all/some of the model instances are using GPU? You can use the model configuration endpoint to set the instance-group information that tells you this: https://github.com/triton-inference-server/server/blob/main/docs/protocol/extension_model_configuration.md. Note that is a model instance is on GPU it could still be using CPU for some of it's layers/operations.
4. I believe the only way right now is to use the metrics endpoint (https://github.com/triton-inference-server/server/blob/main/docs/metrics.md) which will contain entry for each GPU with an identifying UUID.

**Comment by kpedro88** [comment]
Thanks for the very quick response! A few followups:

2. I was considering the possibility of adding a built-in accessor to the client that would carry out these otherwise manual steps: set up a shared memory region (could just be 1 byte), assign an arbitrary value, make a request to the server, see if the server returns the same value, remove shared memory region. Is this generically useful enough to be worth implementing?
3. I was thinking of a different case: if I start the server on a machine with no GPU (or as a container that does not have access to the GPU), it will fall back to running the inference on CPU. It would be nice to be able to detect that case in the client. (The point about a GPU model using CPU for some layers is a good one, and probably too difficult for automatic, reliable detection.)
4. Can the client get the metrics information? (I ask because https://github.com/triton-inference-server/server/blob/v2.3.0/src/clients/c%2B%2B/examples/simple_grpc_cudashm_client.cc#L106-L115 requires the device number.)

**Comment by deadeyegoodwin** [comment]
2. That seems like a reasonable solution. We haven't received any other requests for this kind of thing. Typically the deployment is set up in a known configuration as far as having the client being on the same server as Triton or not, so it is not something that needs to be discovered.

For 3 and 4 I think you likely want something like a "device" endpoint that returns information about the different devices that are visible and available to Triton. For GPU would need to return the device ID as triton sees it but also the GPU UUID, because the device IDs that the client sees may differ if CUDA_VISIBLE_DEVICES or related docker --gpus settings are used.

**Comment by tanmayv25** [comment]
Closed due to inactivity. Please re-open or open a new issue in case you have any other questions.
