### ISSUE TITLE
triton load yensorrt error

### ISSUE THREAD

**Issue by lx-rookie** [triton-inference-server/server#2873]
**Description**

**Triton Information**
What version of Triton are you using?

Are you using the Triton container or did you build it yourself?

**To Reproduce**
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**
![image](https://user-images.githubusercontent.com/54061448/118576648-800c7700-b7bb-11eb-9e41-d746778835b0.png)

when I user triton20.09 load tensorrt models, The following error occurred.
E0518 01:21:26.791899 1 logging.cc:43] Reshape_554: reshaping failed for tensor: (Unnamed Layer* 832) [Constant]_output
E0518 01:21:26.791942 1 logging.cc:43] shapeMachine.cpp (160) - Shape Error in executeReshape: reshape would change volume
E0518 01:21:26.791978 1 logging.cc:43] Instruction: RESHAPE_ZERO_IS_PLACEHOLDER{1 1 3 1 1 2} {8 3 1 1 2}

but when I user python package tensorrt load models, It works just fine
![image](https://user-images.githubusercontent.com/54061448/118576671-90245680-b7bb-11eb-83f1-4189dc0c3459.png)

tensorrt == 7.1.3.4 is like triton server tensorrt

**Comment by deadeyegoodwin** [comment]
Did you generate the TensorRT model with the same version of TensorRT as is used by Triton? https://docs.nvidia.com/deeplearning/triton-inference-server/release-notes/rel_20-09.html#rel_20-09
Looks like TensorRT 7.1.3 is the correct version. If you generate the plan with the 20.09 TensorRT docker image you can be certain you are using the same version as in Triton 20.09.

**Comment by tanmayv25** [comment]
Closed due to inactivity.
