### ISSUE TITLE
Python backend is not using python3 available in PATH

### ISSUE THREAD

**Issue by schibrikov** [triton-inference-server/server#2874]
**Description**
I need to use triton's python backend with TensorFlow 1, which only supports python 3.7 (version in the image is 3.8.5), so I tried to install python 3.7 to the container, so that `python3` points to it. Despite it seems to work correctly, Triton is trying to run the model with python 3.8.5 which obviously doesn't work.

**Triton Information**
I'm using the latest container release - 21.04.

**To Reproduce**
1. Run `bash` in the container, I'm using Kubernetes, so the exactly my command is `kubectl run -i -t nvidia-triton --image=nvcr.io/nvidia/tritonserver:21.04-py3 --restart=Never -- bash`
2. Take the example model from https://github.com/triton-inference-server/python_backend/tree/main/examples/add_sub and add the following snippet which simply checks the python interpreter version to `initialize` method:
```python
major = sys.version_info.major
minor = sys.version_info.minor

if major != 3 or minor != 7:
    raise Exception('Expected version 3.7 of python')
```
3. Install python 3.7 in the container 
```bash
apt update
apt install software-properties-common
add-apt-repository ppa:deadsnakes/ppa
apt install python3.7
```
4. Make sure python3.7 is available as `python3`
```bash
rm /usr/bin/python3
ln -s /usr/bin/python3.7 /usr/bin/python3
python3 --version # 3.7.x
```
5. Run Triton `tritonserver --model-repository=/repo`
6. Check model is not loaded because of our exception
<img width="738" alt="image" src="https://user-images.githubusercontent.com/5585758/118620855-52d1c000-b7df-11eb-8bbd-d5b8244e3874.png">

**Expected behavior**
I expect triton python backend to take `python3` available in the environment while running like it's mentioned in the docs (https://github.com/triton-inference-server/python_backend#python-environment), so it should be using python 3.7.10 and pass the check in my case.

**Comment by Tabrizian** [comment]
@schibrikov Thanks for filing the detailed report. The information on the doc link that you shared is a bit out dated. I created a PR to update this. You need to rebuild Python backend from source in the new Python environment if you want to use a different Python version.

**Comment by schibrikov** [comment]
@Tabrizian thanks! I'll try that
