### ISSUE TITLE
Cmake error

### ISSUE THREAD

**Issue by Amanda-Barbara** [triton-inference-server/server#2875]
-- Using google-cloud-cpp 1.22.0
-- Found AWS SDK for C++, Version: 1.7.129, Install Root:/tmp/citritonmainbuild/tritonserver/build/aws-sdk-cpp/install, Platform Prefix:, Platform Dependent Libraries: pthread;crypto;ssl;z;curl
-- Components specified for AWSSDK: s3
-- Try finding aws-cpp-sdk-core
-- Found aws-cpp-sdk-core
-- Try finding aws-cpp-sdk-s3
-- Found aws-cpp-sdk-s3
-- Using aws-cpp-sdk-s3 1.7.129
-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
NVINFER_LIBRARY
    linked by target "tritonserver" in directory ~/project/ai-platform/triton_inference_server/server/src/servers
NVINFER_PLUGIN_LIBRARY
    linked by target "tritonserver" in directory ~/project/ai-platform/triton_inference_server/server/src/servers

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
make[3]: *** [CMakeFiles/server.dir/build.make:100：server/src/server-stamp/server-configure] 错误 1
make[3]: 离开目录“/tmp/citritonmainbuild/tritonserver/build”
make[2]: *** [CMakeFiles/Makefile2:128：CMakeFiles/server.dir/all] 错误 2
make[2]: 离开目录“/tmp/citritonmainbuild/tritonserver/build”
make[1]: *** [CMakeFiles/Makefile2:135：CMakeFiles/server.dir/rule] 错误 2
make[1]: 离开目录“/tmp/citritonmainbuild/tritonserver/build”
make: *** [Makefile:124：server] 错误 2
error: make server failed

python3 ./build.py --no-container-build --cmake-dir=~/project/triton_inference_server/server/build --build-dir=/tmp/citritonmainbuild --enable-logging --enable-stats --enable-tracing --enable-metrics --enable-gpu-metrics --enable-gpu --endpoint=http --endpoint=grpc --repo-tag=common:main --repo-tag=core:main --repo-tag=backend:main --repo-tag=thirdparty:main --backend=ensemble --backend=tensorrt --backend=identity:main --backend=repeat:main --backend=square:main --backend=onnxruntime:main --backend=pytorch:main --backend=tensorflow1:main --backend=tensorflow2:main --backend=openvino:main --backend=python:main --backend=dali:main --repoagent=checksum:main --filesystem=gcs --filesystem=s3

this is my build parameter, How should I modify it ? thanks.

**Comment by CoderHam** [comment]
Looks like you have not set up the dependencies for the non-docker build correctly. You and find the relevant information [here](https://github.com/triton-inference-server/server/blob/main/docs/build.md#building-without-docker).
