### ISSUE TITLE
tritonserver: error while loading shared libraries: libnvidia-ml.so.1 on Jetson NX

### ISSUE THREAD

**Issue by snowuyl** [triton-inference-server/server#2882]
**Description**
Can't run tritonserver since loading libnvidia-ml.so.1 failed on Jetson NX.

**Triton Information**
r21.05
I build it myself on Jetson NX with Jetpack 4.4.

**To Reproduce**
cd ~/server/build/build/server/install/bin
./tritonserver
./tritonserver: error while loading shared libraries: libnvidia-ml.so.1: cannot open shared object file: No such file or directory

**Expected behavior**
Can run tritonserver on Jetson NX successfully.

**Comment by deadeyegoodwin** [comment]
Perhaps you built with gpu metrics support enabled? That is not currently supported. We have an open issue to improve the documentation around jetson builds. Are you able to you the pre-built jetson release available on the release page? https://github.com/triton-inference-server/server/releases/tag/v2.9.0

**Comment by snowuyl** [comment]
Thanks for your reply. I can run tritonserver if I disabled GPU metrics support. I also can run v2.9.0 pre-built Jetson release.
