### ISSUE TITLE
ensemble  model, inference input data-type is 'BYTES', model expects 'FP32' 

### ISSUE THREAD

**Issue by hanyanLWD** [triton-inference-server/server#2885]
**Description**
r21.03
I use ensemble model in my work. I get an error:error: unable to run model: in ensemble 'ensemble_vapd_cam', inference input data-type is 'BYTES', model expects 'FP32' for 'Efficientb0_first'

in my config file:
|- imgpreprocess
|- efficientnet
|- ensemble model

(1)imgpreprecess:
name: "image_preprocess"
backend:"imgpreprocess"
max_batch_size: 1
input [
  {
    name: "INPUT0"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]
output [
  {
    name: "OUTPUT0"
    data_type: TYPE_FP32
    dims: [ 3, 448, 448 ]
  }
]

(2) efficientnet
name: "Efficientb0_second"
platform: "onnxruntime_onnx"
max_batch_size : 0
input [
  {
    name: "input"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 448,448 ]
        reshape { shape: [ 1, 3, 448,448 ] }
  }
]
output [
  {
    name: "classes"
    data_type: TYPE_FP32
    dims: [ 2 ]
        #reshape { shape: [ 1, 2, 1, 1 ] }
    label_filename: "Efficientb0_second.txt"
  }
]

(3)ensemble 
name: "ensemble_vapd_cam"
platform: "ensemble"
max_batch_size: 1
input [
  {
    name: "INPUT0"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]
output [
  {
    name: "OUTPUT"
    data_type: TYPE_FP32
    dims: [ 4 ]
    #reshape { shape: [ 1, 4, 1, 1 ] }
  }
]
ensemble_scheduling {
  step [
    {
      model_name: "image_preprocess"
      model_version: 1
      input_map {
        key: "INPUT0"
        value: "INPUT0"
      }
      output_map {
        key: "OUTPUT0"
        value: "preprocessed_img"
      }
    },
    {
      model_name: "Efficientb0_first"
      model_version: 1
      input_map {
        key: "input_0"
        value: "preprocessed_img"
      }
      output_map {
        key: "classes"
        value: "OUTPUT"
      }
    }
  ]
}

in my impreprocess config,the output is FP32. use it as  efiicientnet model input, and efiicientnet model input Datatype is FP32.

 why I have a error "unable to run model: in ensemble 'ensemble_vapd_cam', inference input data-type is 'BYTES', model expects 'FP32' for 'Efficientb0_first'"

**Comment by deadeyegoodwin** [comment]
I don't see Efficientb0_first defined in your config file.

**Comment by CoderHam** [comment]
Looks like "Efficientb0_first" is the name of the model. Can you share the config for the model?
My understanding is that the data passed to 'Efficientb0_first' for its input is of TYPE_STRING or BYTES but the model expects FP32.

**Comment by hanyanLWD** [comment]
sorry, i make a error,here is Efficientb0_first:

name: "Efficientb0_first"
platform: "onnxruntime_onnx"
max_batch_size : 0
input [
  {
    name: "input_0"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 448, 448 ]
        reshape { shape: [ 1, 3, 448, 448 ] }
  }
]
output [
  {
    name: "classes"
    data_type: TYPE_FP32
    dims: [ 4 ]
        #reshape { shape: [ 1, 4, 1, 1 ] }
    label_filename: "Efficientb0_first.txt"
  }
]

**Comment by hanyanLWD** [comment]
I  solve the question and get true result in ensemble model
