### ISSUE TITLE
Backend version mismatch when building from sources

### ISSUE THREAD

**Issue by schibrikov** [triton-inference-server/server#2886]
Related issue: https://github.com/triton-inference-server/server/issues/2874

**Description**
I'm trying to use custom Python backend rebuilt from sources to replace python3.8 with python3.7.
When I then running tritonserver I'm getting an error about version mismatch despite using a single release tag `r21.04` for everything:
```
I0519 11:08:11.821198 1975 shared_library.cc:44] OpenLibraryHandle: /opt/tritonserver/backends/python/libtriton_python.so
I0519 11:08:11.821840 1975 python.cc:993] 'python' TRITONBACKEND API version: 1.2
I0519 11:08:11.821859 1975 triton_backend_manager.cc:92] unloading backend 'python'
``` 
And in model status: `UNAVAILABLE: Unsupported: Triton backend API version does not support this backend`

**Triton Information**
I'm using the latest available container r21.04 and rebuilding backend from r21.04 sources inside it.

**To Reproduce**
I created a repo for the simplicity https://github.com/schibrikov/triton-issue-reproduction

I'm trying to build an image and run `tritonserver --model-store=/repo` inside a container.

**Expected behavior**
I expect Triton to load the backend and run my model successfully

**Comment by tanmayv25** [comment]
Refer to this: https://github.com/triton-inference-server/server/issues/2876#issuecomment-844004388. Re-open if still an issue.
