### ISSUE TITLE
Can not load densenet model

### ISSUE THREAD

**Issue by Amanda-Barbara** [triton-inference-server/server#2892]
I enter the command from self-built tritonserver with source like this
./tritonserver --model-repository=/models

I0520 03:11:41.420200 1720574 metrics.cc:228] Collecting metrics for GPU 0: NVIDIA GeForce GTX 1660 SUPER
2021-05-20 11:11:41.566399: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
I0520 03:11:41.593761 1720574 tensorflow.cc:2165] TRITONBACKEND_Initialize: tensorflow
I0520 03:11:41.593801 1720574 tensorflow.cc:2175] Triton TRITONBACKEND API version: 1.2
I0520 03:11:41.593820 1720574 tensorflow.cc:2181] 'tensorflow' TRITONBACKEND API version: 1.0
I0520 03:11:41.593822 1720574 tensorflow.cc:2205] backend configuration:
{}
I0520 03:11:41.595859 1720574 onnxruntime.cc:1722] TRITONBACKEND_Initialize: onnxruntime
I0520 03:11:41.595888 1720574 onnxruntime.cc:1732] Triton TRITONBACKEND API version: 1.2
I0520 03:11:41.595892 1720574 onnxruntime.cc:1738] 'onnxruntime' TRITONBACKEND API version: 1.0
I0520 03:11:41.608284 1720574 openvino.cc:1168] TRITONBACKEND_Initialize: openvino
I0520 03:11:41.608299 1720574 openvino.cc:1178] Triton TRITONBACKEND API version: 1.2
I0520 03:11:41.608302 1720574 openvino.cc:1184] 'openvino' TRITONBACKEND API version: 1.0
I0520 03:11:41.720605 1720574 pinned_memory_manager.cc:206] Pinned memory pool is created at '0x7f2060000000' with size 268435456
I0520 03:11:41.720880 1720574 cuda_memory_manager.cc:103] CUDA memory pool is created on device 0 with size 67108864
E0520 03:11:41.722097 1720574 model_repository_manager.cc:1916] Poll failed for model directory 'inception_graphdef': unexpected platform type tensorflow_graphdef for inception_graphdef
E0520 03:11:41.722145 1720574 model_repository_manager.cc:1916] Poll failed for model directory 'simple': unexpected platform type tensorflow_graphdef for simple
E0520 03:11:41.722245 1720574 model_repository_manager.cc:1916] Poll failed for model directory 'simple_dyna_sequence': unexpected platform type tensorflow_graphdef for simple_dyna_sequence
E0520 03:11:41.722290 1720574 model_repository_manager.cc:1916] Poll failed for model directory 'simple_identity': unexpected platform type tensorflow_savedmodel for simple_identity
E0520 03:11:41.722331 1720574 model_repository_manager.cc:1916] Poll failed for model directory 'simple_int8': unexpected platform type tensorflow_graphdef for simple_int8
E0520 03:11:41.722383 1720574 model_repository_manager.cc:1916] Poll failed for model directory 'simple_sequence': unexpected platform type tensorflow_graphdef for simple_sequence
E0520 03:11:41.722424 1720574 model_repository_manager.cc:1916] Poll failed for model directory 'simple_string': unexpected platform type tensorflow_graphdef for simple_string
I0520 03:11:41.722455 1720574 model_repository_manager.cc:1043] loading: densenet_onnx:1
I0520 03:11:41.822853 1720574 onnxruntime.cc:1781] TRITONBACKEND_ModelInitialize: densenet_onnx (version 1)
WARNING: Since openmp is enabled in this build, this API cannot be used to configure intra op num threads. Please use the openmp environment variables to control the number of threads.
I0520 03:11:41.823513 1720574 onnxruntime.cc:1824] TRITONBACKEND_ModelInstanceInitialize: densenet_onnx (GPU device 0)
I0520 03:11:42.834382 1720574 model_repository_manager.cc:1210] successfully loaded 'densenet_onnx' version 1
I0520 03:11:42.834485 1720574 server.cc:504] 
+------------------+------+
| Repository Agent | Path |
+------------------+------+
+------------------+------+

I0520 03:11:42.834544 1720574 server.cc:543] 
+-------------+-----------------------------------------------------------------+--------+
| Backend     | Path                                                            | Config |
+-------------+-----------------------------------------------------------------+--------+
| tensorrt    | <built-in>                                                      | {}     |
| tensorflow  | /opt/tritonserver/backends/tensorflow1/libtriton_tensorflow1.so | {}     |
| onnxruntime | /opt/tritonserver/backends/onnxruntime/libtriton_onnxruntime.so | {}     |
| openvino    | /opt/tritonserver/backends/openvino/libtriton_openvino.so       | {}     |
+-------------+-----------------------------------------------------------------+--------+

I0520 03:11:42.834576 1720574 server.cc:586] 
+---------------+---------+--------+
| Model         | Version | Status |
+---------------+---------+--------+
| densenet_onnx | 1       | READY  |
+---------------+---------+--------+

I0520 03:11:42.834627 1720574 tritonserver.cc:1659] 
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+
| Option                           | Value                                                                                                                                  |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+
| server_id                        | triton                                                                                                                                 |
| server_version                   | 2.11.0dev                                                                                                                              |
| server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_policy model_configuration system_shared_memory  |
|                                  | cuda_shared_memory binary_tensor_data statistics                                                                                       |
| model_repository_path[0]         | /models                                                                                                                                |
| model_control_mode               | MODE_NONE                                                                                                                              |
| strict_model_config              | 1                                                                                                                                      |
| pinned_memory_pool_byte_size     | 268435456                                                                                                                              |
| cuda_memory_pool_byte_size{0}    | 67108864                                                                                                                               |
| min_supported_compute_capability | 6.0                                                                                                                                    |
| strict_readiness                 | 1                                                                                                                                      |
| exit_timeout                     | 30                                                                                                                                     |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+

I0520 03:11:42.834643 1720574 server.cc:234] Waiting for in-flight requests to complete.
I0520 03:11:42.834646 1720574 model_repository_manager.cc:1076] unloading: densenet_onnx:1
I0520 03:11:42.834692 1720574 server.cc:249] Timeout 30: Found 1 live models and 0 in-flight non-inference requests
I0520 03:11:42.834845 1720574 onnxruntime.cc:1858] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0520 03:11:42.837628 1720574 onnxruntime.cc:1804] TRITONBACKEND_ModelFinalize: delete model state
I0520 03:11:42.837747 1720574 model_repository_manager.cc:1193] successfully unloaded 'densenet_onnx' version 1
I0520 03:11:43.834781 1720574 server.cc:249] Timeout 29: Found 0 live models and 0 in-flight non-inference requests
error: creating server: Internal - failed to load all models

the model failed to load finally. what is the reason and how to solve it ? thanks.

**Comment by CoderHam** [comment]
You are pointing to a repo that contains models with backends/platforms that you have not enabled support for i.e. unexpected platform type tensorflow_graphdef 
You should remove these models from the model repo or use `--exit-on-error=false`

**Comment by CoderHam** [comment]
Closing since densenet model itself was loaded corectly. As seen by the log.
```
+---------------+---------+--------+
| Model | Version | Status |
+---------------+---------+--------+
| densenet_onnx | 1 | READY |
+---------------+---------+--------+
```

**Comment by Amanda-Barbara** [comment]
@CoderHam thanks so much.
