### ISSUE TITLE
Unable to compile Triton/client on CentOS 7.9

### ISSUE THREAD

**Issue by Kiran-r** [triton-inference-server/server#2895]
**Description**
Compiling Triton/client on centOS leads to `undefined reference to symbol 'deflate'`

**Triton Information**
What version of Triton are you using?
Master branch

Are you using the Triton container or did you build it yourself?
Yes.

**To Reproduce**
CentOS 7.9
GCC 9.3
CUDA 10
$ cmake path/to/repo
$ make cc-clients

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**
```[  9%] Linking CXX executable simple_http_async_infer_client
/usr/bin/ld: ../library/libhttpclient_static.a(http_client.cc.o): undefined reference to symbol 'deflate'
$HOME/bin/lib/libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[6]: *** [examples/simple_http_async_infer_client] Error 1
make[5]: *** [examples/CMakeFiles/simple_http_async_infer_client.dir/all] Error 2
make[4]: *** [all] Error 2
make[3]: *** [cc-clients/src/cc-clients-stamp/cc-clients-build] Error 2
make[2]: *** [CMakeFiles/cc-clients.dir/all] Error 2
make[1]: *** [CMakeFiles/cc-clients.dir/rule] Error 2
make: *** [cc-clients] Error 2```

**Comment by deadeyegoodwin** [comment]
We do not officially support CentOS 7.9 so changes may be required to the build scripts. Can you post your entire cmake/make command as well as the entire output.

**Comment by Kiran-r** [comment]
Was able to resolve this by updating system packages using `$ yum update`.

**Comment by vivienfanghuagood** [comment]
> **Description** Compiling Triton/client on centOS leads to `undefined reference to symbol 'deflate'`
> 
> **Triton Information** What version of Triton are you using? Master branch
> 
> Are you using the Triton container or did you build it yourself? Yes.
> 
> **To Reproduce** CentOS 7.9 GCC 9.3 CUDA 10 $ cmake path/to/repo $ make cc-clients
> 
> Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
> 
> **Expected behavior**
> 
> ```
> /usr/bin/ld: ../library/libhttpclient_static.a(http_client.cc.o): undefined reference to symbol 'deflate'
> $HOME/bin/lib/libz.so.1: error adding symbols: DSO missing from command line
> collect2: error: ld returned 1 exit status
> make[6]: *** [examples/simple_http_async_infer_client] Error 1
> make[5]: *** [examples/CMakeFiles/simple_http_async_infer_client.dir/all] Error 2
> make[4]: *** [all] Error 2
> make[3]: *** [cc-clients/src/cc-clients-stamp/cc-clients-build] Error 2
> make[2]: *** [CMakeFiles/cc-clients.dir/all] Error 2
> make[1]: *** [CMakeFiles/cc-clients.dir/rule] Error 2
> make: *** [cc-clients] Error 2```
> ```

Probobaly you should try something like:
target_link_libraries(
    image_client
    PRIVATE -lz
  )
to avoid this problem.
