### ISSUE TITLE
Running image_client.py causes core dump on Jetson NX

### ISSUE THREAD

**Issue by snowuyl** [triton-inference-server/server#2899]
Description
Running image_client.py causes core dump

Triton Information
r21.05
I build it myself on Jetson NX with Jetpack 4.4.

To Reproduce
python3 image_client.py -m inception_graphdef -s INCEPTION /home/alpha/Downloads/tritonserver-2.9.0/qa/images/mug.jpg 

Expected behavior
Can run image_client.py on Jetson NX successfully.
Steps to reproduce the behavior.

**Comment by CoderHam** [comment]
The 2.9.0 release was built for jetpack 4.5. You might have to rebuild the client libraries for 4.4

**Comment by deadeyegoodwin** [comment]
Or you can try using an older version of Triton that was compiled for Jetpack 4.4. Such as https://github.com/triton-inference-server/server/releases/tag/v2.5.0.
