### ISSUE TITLE
Can't generating  linux_stamp.whl successfully on Intel i5

### ISSUE THREAD

**Issue by snowuyl** [triton-inference-server/server#2900]
Description
Can't generating  linux_stamp.whl successfully

Triton Information
r21.05
I build it myself on Intel i5 NB with Ubuntu 18.04

Expected behavior
Can't generating  linux_stamp.whl successfully

Steps to reproduce the behavior
1. Enabling Python HTTP client libraries in CMakeLitsts.txt.
option(TRITON_ENABLE_PYTHON_HTTP "Enable Python HTTP client libraries" ON)
2. mkdir build
3. cd build
4. cmake ..
.....
Scanning dependencies of target linux-client-wheel
[ 92%] Generating linux_stamp.whl
 === Using builddir: /home/snowuyl/inference-client/build/python-clients/library/linux//wheel
Adding package files
~/inference-client/build/python-clients/library/linux/wheel ~/inference-client/build/python-clients/library
=== Building wheel
Traceback (most recent call last):
  File "setup.py", line 128, in <module>
    data_files=data_files,
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 134, in setup
    ok = dist.parse_command_line()
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 499, in parse_command_line
    result = _Distribution.parse_command_line(self)
  File "/usr/lib/python3.6/distutils/dist.py", line 472, in parse_command_line
    args = self._parse_command_opts(parser, args)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 814, in _parse_command_opts
    nargs = _Distribution._parse_command_opts(self, parser, args)
  File "/usr/lib/python3.6/distutils/dist.py", line 534, in _parse_command_opts
    if not issubclass(cmd_class, Command):
TypeError: issubclass() arg 1 must be a class
library/CMakeFiles/linux-client-wheel.dir/build.make:84: recipe for target 'library/linux_stamp.whl' failed
make[5]: *** [library/linux_stamp.whl] Error 1
CMakeFiles/Makefile2:282: recipe for target 'library/CMakeFiles/linux-client-wheel.dir/all' failed
make[4]: *** [library/CMakeFiles/linux-client-wheel.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/python-clients.dir/build.make:130: recipe for target 'python-clients/src/python-clients-stamp/python-clients-build' failed
make[2]: *** [python-clients/src/python-clients-stamp/python-clients-build] Error 2
CMakeFiles/Makefile2:151: recipe for target 'CMakeFiles/python-clients.dir/all' failed
make[1]: *** [CMakeFiles/python-clients.dir/all] Error 2
Makefile:102: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by deadeyegoodwin** [comment]
Are you building using build.py? Are you doing a Docker build? If not you must make sure that all dependencies are installed on your host. It could be that you are missing "pip install wheel" or "pip install setuptools". Note that we do not regularly build on Ubuntu 18.04.

**Comment by snowuyl** [comment]
Thanks for your reply. I can build linux_stamp.whl successfully on Intel i5 by installing wheel Python package.
