### ISSUE TITLE
unexpected platform type caffe2_netdef for Triton 2.7.0 ?

### ISSUE THREAD

**Issue by chunyulin** [triton-inference-server/server#2901]
Hi, recently we have a new Triton v2.7.0 installed (NGC 21.02-py3 container) and the server starts successfully with loading all tensorflow models in the example repo. However, in trying to load the 'resnet50_netdef' (with platform "caffe2_netdef" ), it shows the following error:
```
E0516 06:19:37.834718 12806 model_repository_manager.cc:1682] unexpected platform type caffe2_netdef for resnet50_netdef
I0516 06:19:37.834819 12806 server.cc:495]
```
Using TensorRT server v1 has no such the problem. 
Is it the error from model side or server side ?       Thanks.

The resetnet50 model and config files are D/L from http://download.caffe2.ai.s3.amazonaws.com/models/resnet50/predict_net.pb  http://download.caffe2.ai.s3.amazonaws.com/models/resnet50/init_net.pb
https://github.com/triton-inference-server/server/tree/v2.3.0/docs/examples/model_repository/resnet50_netdef

**Comment by deadeyegoodwin** [comment]
The Caffe2 backend was removed in the 2.5.0 release: https://github.com/triton-inference-server/server/releases/tag/v2.5.0. You will need to use an older release than that if you want Caffe2 support.
