### ISSUE TITLE
 GRPC Execute Failed, message: failed to connect to all addresses

### ISSUE THREAD

**Issue by DataXujing** [triton-inference-server/server#2902]
When I use Python backend to ensemble model, 

After the Triton service runs for a period of time, the ensemble model will report the following error:

```
inference failed: in ensemble 'model_name', GRPC Execute Failed, message: failed to connect to all addresses
```

**Comment by Tabrizian** [comment]
@DataXujing Are you able to perform any inference requests before you see this error? If yes, it could be that your model code has some issues that leads that causes the Python process to exit. For example, if your model causes Out of Memory exception you will see the error above that you posted.

**Comment by deadeyegoodwin** [comment]
Also, I believe you are likely using an older version of Triton. If you use a recent version, like 21.05, you should not see this error.
