### ISSUE TITLE
error: failed to get model metadata: Request for unknown model: 'inception_graphdef' is not found

### ISSUE THREAD

**Issue by snowuyl** [triton-inference-server/server#2911]
**Description**
error: failed to get model metadata: Request for unknown model: 'inception_graphdef' is not found

**Triton Information**
r21.05
I build it myself on Jetson NX with Jetpack 4.5.

**To Reproduce**
./tritonserver --model-repository ~/inference-server/docs/examples/model_repository/inception_graphdef/1/

./image_client -m inception_graphdef -s INCEPTION /home/alpha/inference-server/qa/images/mug.jpg 
error: failed to get model metadata: Request for unknown model: 'inception_graphdef' is not found
error: failed to get model config: Request for unknown model: 'inception_graphdef' is not found
expecting 1 input, got 0

**Expected behavior**
Can run image_client succefully on Jetson NX successfully.

**Comment by GuanLuo** [comment]
`--model-repository` should be set to the directory that contains the models, so you should set --model-repository ~/inference-server/docs/examples/model_repository

**Comment by snowuyl** [comment]
Thanks for your reply. I change command as follows. 
./tritonserver --model-repository ~/inference-server/docs/examples/model_repository

But tritonserver shows the following error message.
failed to load 'simple' version 1: Invalid argument: unable to find 'libtriton_tensorflow1.so' for model 'simple', searched: /home/alpha/inference-server/docs/examples/model_repository/simple/1, /home/alpha/inference-server/docs/examples/model_repository/simple, /opt/tritonserver/backends/tensorflow1

**Comment by CoderHam** [comment]
If you built your image from scratch you will need to build the libtriton_tensorflow1.so backend library. You can also pick up these and other TF backend dependencies from the Jetson tar file in the release notes.

Please note these files were built on Jetson Xavier. You can always follow the instructions from the TF backend repo to build it from scratch.

**Comment by snowuyl** [comment]
Thanks for your reply. I try to build server from scratch by using the following command.
python3 build.py --no-container-build --target-platform jetpack --build-dir /tmp/inference-server --cmake-dir ~/inference-server/build --backend tensorflow2 --filesystem azure_storage

But the following error occurred.
CMake Error at CMakeLists.txt:52 (message):
  Using the Tensorflow docker based build requires
  TRITON_TENSORFLOW_DOCKER_IMAGE

I have specified --no-container-build option, but why build.py using the TensorFlow docker based build. How can I build libtriton_tensorflow1.so without TensorFlow docker?

**Comment by CoderHam** [comment]
You need to specify the  `--library-paths=tensorflow1:<path_to_tf1_libraries>/backends/tensorflow1` flag so that Triton knows to not use the NGC Tensorflow container for the build.
Have a look at the tensorflow repo cmakelist: https://github.com/triton-inference-server/tensorflow_backend/blob/main/CMakeLists.txt#L50. 
As mentioned earlier I'd recommend just using the [tar file](https://github.com/triton-inference-server/server/releases/download/v2.10.0/tritonserver2.10.0-jetpack4.5.tgz) from the 2.10.0 release since it would be way easier.

**Comment by CoderHam** [comment]
I am closing this issue since it is a user error. If you encounter a problem please open a separate issue.
