### ISSUE TITLE
ensemble model load failed

### ISSUE THREAD

**Issue by woodyexcellent** [triton-inference-server/server#2917]
E0526 05:31:25.666963 395040 model_repository_manager.cc:1916] Poll failed for model directory 'ensemble': unexpected platform type ensemble for ensemble

I have checked the struct of my model-repository. It's no problem.
model-repository-path/
    ensemble/
      [config.pbtxt]
      1/
    identity/
      [config.pbtxt]
      1/

here is the content of config.pbtxt:
name: "ensemble"
platform: "ensemble"
input [
    {
    name: "INPUT0"
    data_type: TYPE_INT32
    dims: 16
    },
    {
    name: "INPUT1"
    data_type: TYPE_INT32
    dims: 16
    }
]
output [
    {
    name: "OUTPUT0"
    data_type: TYPE_INT32
    dims: 16
    },
    {
    name: "OUTPUT1"
    data_type: TYPE_INT32
    dims: 16
    }
]
ensemble_scheduling {
  step [
    {
      model_name: "identity"
      model_version: 1
      input_map {
        key: "INPUT0"
        value: "INPUT0"
      }
      input_map {
        key: "INPUT1"
        value: "INPUT1"
      }
      output_map {
        key: "OUTPUT0"
        value: "OUTPUT0"
      }
      output_map {
        key: "OUTPUT1"
        value: "OUTPUT1"
      }
    }
  ]
}

what's wrong?

**Comment by woodyexcellent** [comment]
my server has let the TRITON_ENABLE_ENSEMBLE=ON

**Comment by GuanLuo** [comment]
The model config looks okay to me. Can you check if the model can be loaded with with the 21.05 container? I suppose you are building from source, that can check whether it is just a misconfiguration during the build

**Comment by woodyexcellent** [comment]
> The model config looks okay to me. Can you check if the model can be loaded with with the 21.05 container? I suppose you are building from source, that can check whether it is just a misconfiguration during the build

I have found my error in building process. In fact, I made a wrong modification in the cmakelists.txt. Now it’s ok to run the server.

**Comment by woodyexcellent** [comment]
I have found my error in building process. In fact, I made a wrong modification in the cmakelists.txt. Now it’s ok to run the server.
