### ISSUE TITLE
ensemble_image_client client example giving error

### ISSUE THREAD

**Issue by akash2826** [triton-inference-server/server#2922]
**Description**
Hi Team,
I am Trying to execute "ensemble_image_client" c++ binary from tritonserver:21.04-py3-sdk container  but it giving below error

[..]
$:/workspace/install/bin# ./ensemble_image_client /workspace/images/
error: failed to get model config: Request for unknown model: 'preprocess_inception_ensemble' is not found
The number of images exceeds maximum batch size, only the first 0 images, sorted by name alphabetically, will be processed
error: unable to run model: Request for unknown model: 'preprocess_inception_ensemble' is not found
[..]

It is saying 'preprocess_inception_ensemble' model not found I build  dali backend in triton-sever hoping this model will be present but it is not avilable there.

please suggest how to run "ensemble_image_client" example successfully and where to search for 'preprocess_inception_ensemble' model.

**Triton Information**
Triton version is 21.04

Are you using the Triton container or did you build it yourself?
Triton container
**To Reproduce**
docker run -it --rm --gpus=1 --net=host nvcr.io/nvidia/tritonserver:21.04-py3-sdk
$:/workspace/install/bin# ./ensemble_image_client /workspace/images/

**Expected behavior**
Successful execution of example.

**Comment by GuanLuo** [comment]
The ensemble example is transferred from the server repo to the [DALI repo](https://github.com/triton-inference-server/dali_backend/tree/main/docs/examples/inception_ensemble) as now DALI backend is a suggested way to handle the data preprocessing part, please take a look at the attach link for obtaining the models.
