### ISSUE TITLE
Cuda version for Jetpack 2.10.0

### ISSUE THREAD

**Issue by htran170642** [triton-inference-server/server#2925]
My cuda version in jetson is 10.2. Should I need to upgrade to cuda 11.1 for triton2.10 -jetpack4.5?
I got problems when running deepstream with triton server on Jetson.
![image](https://user-images.githubusercontent.com/70887055/119782915-eb122800-bef6-11eb-8fe1-16a402170247.png)

**Comment by GuanLuo** [comment]
@CoderHam

**Comment by CoderHam** [comment]
@htran170642 which version of deepstream are you using? Jetson 4.5 is built with CUDA 10.2 and not 11.1 and so is the Triton 2.10 for JP 4.5.
Can you also share your model config? The error message seems to indicate and is with the model config.

**Comment by htran170642** [comment]
I used deepstream 5.1 (this image: deepstream-l4t:5.1-21.02-samples)
I tried to run deepstream app with those model samples and all of them return the same error - input or output layers are empty.

when I used triton 2.5, everything just worked fine but this 2.5 triton did not have onnxruntime. Any idea to resolve it? Thank you so much.

Model sample for
*********************************************************
name: "ssd_inception_v2_coco_2018_01_28"
platform: "tensorflow_graphdef"
default_model_filename: "model.graphdef"
max_batch_size: 128
input [
  {
    name: "image_tensor"
    data_type: TYPE_UINT8
    format: FORMAT_NHWC
    dims: [ 300, 300, 3 ]
  }
]
output [
  {
    name: "detection_boxes"
    data_type: TYPE_FP32
    dims: [ 100, 4]
    reshape { shape: [100,4] }
  },
  {
    name: "detection_classes"
    data_type: TYPE_FP32
    dims: [ 100 ]
  },
  {
    name: "detection_scores"
    data_type: TYPE_FP32
    dims: [ 100 ]
  },
  {
    name: "num_detections"
    data_type: TYPE_FP32
    dims: [ 1 ]
    reshape { shape: [] }
  }
]

# Switch to CPU instance for Nano since memory might not be enough for
# certain Models.

# Specify CPU instance.
#instance_group {
#  count: 1
#  kind: KIND_CPU
#}

# Specify GPU instance.
instance_group {
  kind: KIND_GPU
  count: 1
  gpus: 0
}
***********************************************************

**Comment by htran170642** [comment]
@CoderHam
