### ISSUE TITLE
Get label with REST http client

### ISSUE THREAD

**Issue by okyspace** [triton-inference-server/server#2926]
I using own REST implementation for inference. And also included label file, but I don't seems to be able to get label from response output. I read that it is possible using triton client but I also cannot find code example of it. 

Able to point me to it if it exists?

**Comment by CoderHam** [comment]
@okyspace Can you refer to the http client library [here](https://github.com/triton-inference-server/client/blob/main/src/python/library/tritonhttpclient/__init__.py) and the example for classification using http [here](https://github.com/triton-inference-server/client/blob/main/src/python/examples/image_client.py). 

Also refer to the API docs [here](https://github.com/triton-inference-server/server/blob/main/docs/protocol/extension_classification.md) for classification. This is likely what you are looking for.

**Comment by tanmayv25** [comment]
Closing the issue. Please re-open or file a new issue if you have anymore questions.
