### ISSUE TITLE
Extending Triton to support more open source libraries

### ISSUE THREAD

**Issue by okyspace** [triton-inference-server/server#2927]
I have a python backend model that uses external library like yaml, torch, cv2, scipy, etc to perform process like non_max_suppression, reading classes/idx from yaml file and conversion of class label to idx.
However, when I run this model, error arised as these libraries are not present. 
May I know how we can add on our external libraries in this case, and is it recommended as it seems to make future upgrade of Triton version more difficult as it coupled with them?

More generally, this arises because I am using open source model like ScaledYOLOv4. The codes are structured to use these libraries either in preprocess, model, postprocess. I think to some extent some refactoring can be done to try to avoid usage of the external libraries which may not be 100% doable. But this will also defeat the purpose of using open source to some extent as significant effort is required to redesign and refractor the codes. 
However, to utilise Triton features, it is still desire to try to deploy on Triton. Any advice?

**Comment by Tabrizian** [comment]
@okyspace  

> However, when I run this model, error arised as these libraries are not present.

Can you please share your model and code? Python backend should work with all the libraries that you install. What is the error that you are seeing? If you only have a single environment and all the dependencies are installed in that environment, your code should work. However, if the version of the Python environment is different from the version of the Python available inside the container (which is 3.8) your code will not work. We are working on improving the support for Python environments but if the Python versions match your code should be able to work.

**Comment by okyspace** [comment]
@Tabrizian, I understand. 
Here's the sample of the open source that I am looking at. Trying to deploy this but from my understanding, I may need to refactor significantly to deploy this using pipelines. However, even with model pipelines, I would need to install the 3rd party libraries for the model to work. In such cases, what's the better way to deploy this?
[](https://github.com/WongKinYiu/ScaledYOLOv4)

**Comment by Tabrizian** [comment]
We recently added support for Python Execution Environment in Python backend. https://github.com/triton-inference-server/python_backend#using-custom-python-execution-environments It is going to be released in 21.06. Hopefully this feature should help you with the dependencies.

**Comment by Tabrizian** [comment]
Feel free to re-open this ticket if you have additional questions.
