### ISSUE TITLE
How to serve a PyTorch model in Triton python_backend on multiple GPUs? 

### ISSUE THREAD

**Issue by ukemamaster** [triton-inference-server/server#2928]
I want to serve my pytorch model in the python_backend triton server **on multiple GPUs**. When i load my model in the `model.py`, it utilizes only GPU:0 (though the job is assigned to all the GPUs). No matter how many counts i specify in the config file, all instances are created on GPU:0. How can i make it utilize all GPUs, with multiple counts. 

Here is my nvidia-smi output: 

![Screenshot from 2021-05-27 16-18-53](https://user-images.githubusercontent.com/59258087/119842998-6f6ca700-bf07-11eb-8faa-bd7dda96a48f.png)

One way is to use the `torch.DistributedDataParallel` class to wrap my pytorch model in. I tried it but it requires to run the python script with `python -m torch.distributed.launch --nproc_per_node=6 my_script.py`. 

How can i execute the `model.py` in this way? Where is the execution call of `model.py`?

**Comment by Tabrizian** [comment]
@ukemamaster Your model is responsible for transferring the PyTorch model to the appropriate GPU. You can do so using the:

```python
def initialize(self, args):
    self.model_instance_kind = args['model_instance_kind']
    self.model_instance_device_id  = args['model_instance_device_id']
```

These two parameters indicate whether the model should be placed on GPU/CPU and if it should be placed on GPU which GPU device it should be placed on. You can use these parameters to place your model on the appropriate device.

**Comment by ukemamaster** [comment]
@Tabrizian Thanks for your reply. The following changes solved my problem:

`self.model_instance_device_id  = args['model_instance_device_id']`
`device = torch.device('cuda:'+ self.model_instance_device_id)`
`my_model.to(device)`

With this i have multiple instances on different GPUs, as expected. 

However, with this i faced another problem. When i send client request using the `client.py`, i get the following Exception:

`    File "client.py", line 41, in <module>`
`          response = client.infer(model_name, inputs, request_id=str(1), outputs=outputs)` 
`     File "/tertiary/umairkhan/torch_1_8/lib/python3.6/site-packages/tritonclient/grpc/__init__.py", line 1086, in infer
          raise_error_grpc(rpc_error)`
`     File "/tertiary/umairkhan/torch_1_8/lib/python3.6/site-packages/tritonclient/grpc/__init__.py", line 61, in raise_error_grpc
          raise get_error_grpc(rpc_error) from None`
`tritonclient.utils.InferenceServerException: [StatusCode.INTERNAL] GRPC Execute Failed, message: Exception calling application: can only concatenate str (not "int") to str`

It only happens when there are instances on different GPUs. When all instances are on the same GPU, all requests are responded correctly. Do you have any idea about this?

**Comment by ukemamaster** [comment]
@Tabrizian I came to know that the problem arises from the fact that in PyTorch it is necessary to have all Tensors on the same device. I got the following error: 

`RuntimeError: All input tensors must be on the same device. Received cuda:0 and cuda:1`

How can i have all Tensors on the same device if there are multiple instances of the model on different devices?

**Comment by ukemamaster** [comment]
I solved my little problem. For those who may get help from it. 

Somewhere in a froward pass of my model i am concatenating two tensors `x` and `y`. The default code was: 
```
if x.is_cuda:
   y = y.to('cuda')
z = torch.cat((x, y), dim=1)
```
Which puts tensor `y` on `cuda:0`, if `x` is on `cuda`. In case of Triton server, when there are multiple instances on different devices, `x` is on device according to `args['model_instance_device_id']`, which may not always be `cuda:0`. So the following little change puts `y` on the current device of `x`, and not always on `cuda:0`. 
```
if x.is_cuda:
   y = y.to(x.get_device())
z = torch.cat((x, y), dim=1)
```

**Comment by Tabrizian** [comment]
Great, thanks for sharing the response.
