### ISSUE TITLE
Triton (docker 21.05-py3) fails to load a model repository with two python backends

### ISSUE THREAD

**Issue by ioangatop** [triton-inference-server/server#2932]
With the latest `nvcr.io/nvidia/tritonserver:21.05-py3`, triton fails to load a model repository that contains two models with **python** backend.

The server loads and works as expected with `nvcr.io/nvidia/tritonserver:21.03-py3` and `nvcr.io/nvidia/tritonserver:21.04-py3`. Using the flags `--model-control-mode "explicit" --load-model "model1"` the server starts as expected, but of course it load only one. It still manages to load a repo with various backends (e.i. dali, onnx etc) but when I include two models with python backend, it seems that it loads one and then fails.

The model repository looks as follows;
```
repo
`-- model1
    |-- 1
    |   `-- model.py
    `-- config.pbtxt
`-- model2
    |-- 1
    |   `-- model.py
    `-- config.pbtxt
```

The error message is the following;
```
I0528 16:58:06.837506 1 model_repository_manager.cc:1043] loading: model2:1
I0528 16:58:06.937788 1 model_repository_manager.cc:1043] loading: model1:1
I0528 16:58:06.940346 1 python.cc:1223] TRITONBACKEND_ModelInstanceInitialize: model2_0 (CPU device 0)
I0528 16:58:07.042691 1 python.cc:1223] TRITONBACKEND_ModelInstanceInitialize: model1_0 (CPU device 0)
terminate called after throwing an instance of 'triton::backend::python::PythonBackendException
```

**Comment by Tabrizian** [comment]
You need to increase the shared memory size if you are running inside docker:

Make sure that you have `--shm-size=5g` in your docker run command.
