### ISSUE TITLE
Client build on Windows fails:  cl : command line error D8021: invalid numeric argument '/Wno-implicit-fallthrough'

### ISSUE THREAD

**Issue by olibartfast** [triton-inference-server/server#2938]
Hi, I'm posting here because can't open my Issue  on triton client repo
**Description**
[Triton Client](https://github.com/triton-inference-server/client/tree/r21.05)  build on Windows fails with error
` cl : command line error D8021: invalid numeric argument '/Wno-implicit-fallthrough'`
`/Wno-implicit-fallthrough` is included inside file [C++ library Cmakelists, line 276](https://github.com/triton-inference-server/client/blob/r21.05/src/c%2B%2B/library/CMakeLists.txt) 
You get the error when you set on Cmake `-DTRITON_ENABLE_CC_HTTP=ON`  
  
**Windows Information** 
* msbuild version 16.10.0+4242f381a  
* Windows SDK version 10.0.19042  
* CXX compiler is MSVC 19.27.29112

**Triton Information**
What version of Triton are you using?
r21.05  

**To Reproduce**
Steps to reproduce the behavior.
`mkdir build`
`cd build`
`cmake.exe -DVCPKG_TARGET_TRIPLET=x64-windows -DCMAKE_TOOLCHAIN_FILE='path/to/vcpkg.cmake' -DCMAKE_INSTALL_PREFIX=install -DTRITON_ENABLE_CC_HTTP=ON -DTRITON_ENABLE_CC_GRPC=ON -DTRITON_ENABLE_PERF_ANALYZER=ON -DTRITON_ENABLE_PYTHON_HTTP=ON -DTRITON_ENABLE_PYTHON_GRPC=ON -DTRITON_ENABLE_GPU=ON -DTRITON_ENABLE_EXAMPLES=ON -DTRITON_ENABLE_TESTS=ON ..`
`msbuild.exe cc-clients.vcxproj -p:Configuration=Release -clp:ErrorsOnly`

**Expected behavior**
Client correctly built  on Windows.

**Comment by olibartfast** [comment]
Ok it looks like this /Wno-implicit-fallthrough argument is available only for GCC compiler, however avoiding to use it during Windows build all the process complete successfully without errors

**Comment by CoderHam** [comment]
@olibartfast Currently our Windows build does not include REST/HTTP support. If you are able to get a build of both server and client with HTTP support we would like to hear about any issues you faced with the same. Thanks!

**Comment by olibartfast** [comment]
Currently I only need windows client and not the server, so I only built the first one. However using client in Windows I'm not currently having any issues
