### ISSUE TITLE
tritonserver2.10.0-jetpack4.5.tgz - deepstream 5.1- jetson xavier NX

### ISSUE THREAD

**Issue by htran170642** [triton-inference-server/server#2940]
Docker image: nvcr.io/nvidia/deepstream-l4t:5.1-21.02-samples

input or output layers are empty, check trtis model config settings
ERROR: failed to initialize backend while setup model:ssd_inception_v2_coco_2018_01_28 layer info, nvinfer error:NVDSINFER_TRTIS_ERROR

![image](https://user-images.githubusercontent.com/70887055/120141397-99bfac80-c206-11eb-9a94-7febd2815311.png)
![image](https://user-images.githubusercontent.com/70887055/120141421-a93ef580-c206-11eb-8065-dd0ebc290828.png)

config.pbtxt file:
name: "ssd_inception_v2_coco_2018_01_28"
platform: "tensorflow_graphdef"
default_model_filename: "model.graphdef"
max_batch_size: 128
input [
  {
    name: "image_tensor"
    data_type: TYPE_UINT8
    format: FORMAT_NHWC
    dims: [ 300, 300, 3 ]
  }
]
output [
  {
    name: "detection_boxes"
    data_type: TYPE_FP32
    dims: [ 100, 4]
    reshape { shape: [100,4] }
  },
  {
    name: "detection_classes"
    data_type: TYPE_FP32
    dims: [ 100 ]
  },
  {
    name: "detection_scores"
    data_type: TYPE_FP32
    dims: [ 100 ]
  },
  {
    name: "num_detections"
    data_type: TYPE_FP32
    dims: [ 1 ]
    reshape { shape: [] }
  }
]

The docker image starts with triton 2.5, it works fine with all models.
But after I download tritonserver2.10.0-jetpack4.5.tgz and extract it to reinstall triton servers, when I run deepstream-app, all deepstream file config returned same error "input or output layers are empty". 
Any idea to fix it? Please help. Thank you so much

**Comment by CoderHam** [comment]
@htran170642  The logs you shared indicate that there was an error loading a model but not the exact error. I will ask someone from the deepstream to look deeper but for now can you try using a verbose logging for deepstream to see if you can find the exact error?

**Comment by windyuan** [comment]
The error is expected in DS5.1. There are some legacy issue for forward compatibility support in deepstream-triton.  it's better to use the same triton version as ds-triton build. For more questions about deepstream or deepstream-triton specific, @htran170642 you can also try ask https://forums.developer.nvidia.com/c/accelerated-computing/intelligent-video-analytics/deepstream-sdk/15

**Comment by CoderHam** [comment]
Thanks @windyuan. Closing this issue. @htran170642 let me know if you face issues with the same version of triton as the deepstream-triton build and I can re-open as needed.
