### ISSUE TITLE
triton C API How to build example

### ISSUE THREAD

**Issue by akash2826** [triton-inference-server/server#2944]
**Description**
Hi Team,

I want to build and understanding triton C API for accessing the input data directly into triton server and use shared memory for optimal performance. For this I am exploring triton C API and simple.cc program I wanted to know or any example which will help me for building triton server with C API. I did not find any such example for building or container.

Please help me on this.

**Comment by Tabrizian** [comment]
@akash2826 This the section of the CMake file related to the `simple.cc` program. https://github.com/triton-inference-server/server/blob/main/src/servers/CMakeLists.txt#L266-L310. I believe if you build triton from source, it will compile the `simple.cc` and install it in `/opt/tritonserver/bin`.

**Comment by akash2826** [comment]
@Tabrizian what about the nvcr.io/nvidia/tritonserver:21.04-py3 container does this container should also have binary for the simple.cc in /opt/tritonserver/bin ? 
As I have checked from doing /bin/bash in container simple.cc binary is not present.

**Comment by CoderHam** [comment]
@akash2826 simple is an example server and not shipped in the nvcr.io/nvidia/tritonserver:21.04-py3 container. You can build the simple.cc and other example servers using build.py. Refer to our [build docs](https://github.com/triton-inference-server/server/blob/main/docs/build.md#building-with-docker).

**Comment by gcarr1020** [comment]
Both links to the `CMakeLists.txt` are dead. Could you provide updated links and line numbers please?

**Comment by joihn** [comment]
despite building triton myelf (with docker), the `simple` binary can't be found anywhere.
Any idea ?
