### ISSUE TITLE
Cannot find -ltensorflow_triton when building tensorflow_backend

### ISSUE THREAD

**Issue by snowuyl** [triton-inference-server/server#2951]
**Description**
Cannot find -ltensorflow_triton when building tensorflow_backend

**Triton Information**
r21.05
I build it myself on Jetson NX with Jetpack 4.5.

**To Reproduce**
git clone https://github.com/triton-inference-server/tensorflow_backend
cd tensorflow_backend/
changing CMakeLitsts.txt as follows
set(TRITON_TENSORFLOW_VERSION "2" CACHE STRING "TensorFlow version, must be '1' or '2'.")
set(TRITON_TENSORFLOW_LIB_PATHS "/usr/local/lib" CACHE PATH "Paths to TensorFlow libraries. Multiple paths may be specified by separating them with a semicolon.")
set(TRITON_TENSORFLOW_DOCKER_BUILD OFF)

mkdir build
cd build
cmake ..
make

[ 78%] Linking CXX shared library libtriton_tensorflow2.so
/usr/bin/ld: cannot find -ltensorflow_triton
collect2: error: ld returned 1 exit status
CMakeFiles/triton-tensorflow-backend.dir/build.make:121: recipe for target 'libtriton_tensorflow2.so' failed
make[2]: *** [libtriton_tensorflow2.so] Error 1
CMakeFiles/Makefile2:162: recipe for target 'CMakeFiles/triton-tensorflow-backend.dir/all' failed
make[1]: *** [CMakeFiles/triton-tensorflow-backend.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2

**Expected behavior**
Can building tensorflow_backend succefully on Jetson NX successfully.

**Comment by CoderHam** [comment]
tensorflow_triton is a patched version of Tensorflow with some additional functions needed to use the TF backend in Tensorflow. @deadeyegoodwin what path do you suggest. I don't think we document how to build this binary on GitHub.

**Comment by deadeyegoodwin** [comment]
TF C API is missing some features required by Triton so we must patch TF. See the appropriate bullet point here: https://github.com/triton-inference-server/server/blob/main/docs/build.md#building-on-unsupported-platforms
More specific instructions for how to build are here: https://github.com/triton-inference-server/tensorflow_backend#build-the-tensorflow-backend-with-custom-tensorflow
