### ISSUE TITLE
The question of interrupting streams 

### ISSUE THREAD

**Issue by guskovd** [triton-inference-server/server#2952]
Hello.

We are using tritonserver to get inference from the GPU using a stream via GRPC.

It so happens that our application may restart.
At such moments, it seems that the tritonserver cannot accept new requests for inference and is somehow trying to process incomplete requests.

Is this normal behavior from your point of view?
And is it possible to somehow control this behavior using the config / command line arguments? (Ideally, we would like the tritonserver to terminate all streams for dropped clients)

--

Triton server/client (protobuf files version) version: 20.06
GPU: Tesla T4

**Comment by CoderHam** [comment]
Once requests are queued up in Triton, we cannot know which requested are from dropped clients. I guess one feature would be to clear the request queue. @guskovd Would this be an acceptable solution?
cc @deadeyegoodwin correct me if I am wrong here.

**Comment by guskovd** [comment]
> Once requests are queued up in Triton, we cannot know which requested are from dropped clients. I guess one feature would be to clear the request queue. @guskovd Would this be an acceptable solution?

It would be great for us to just learn how to get information about the server load, that is, to find out the number of pending requests for inference. I found `ModelStatisticsRequest`, but I still don't understand how to get what I need from it.

**Comment by guskovd** [comment]
Even the simplest config does not work for me:
```
(require 'exwm)
(require 'exwm-config)
(exwm-config-default)
```

**Comment by deadeyegoodwin** [comment]
Final question is covered by #3038, closing.
