### ISSUE TITLE
Service Shutdown while multiple python backend to be loaded.

### ISSUE THREAD

**Issue by SraRod** [triton-inference-server/server#2953]
**Description**
Triton Server shutdown while multiple python backend model to be loaded in triton 21.05.

**Triton Information**
official ngc docker image
`nvcr.io/nvidia/tritonserver:21.05-py3`

**To Reproduce**
1. Deploy triton 21.05 via docker run
2. deploy model from POST
```bash
curl -X POST localhost:8000/v2/repository/models/simple_int8/load
curl -X POST localhost:8000/v2/repository/models/pytorch/load
curl -X POST localhost:8000/v2/repository/models/simple_sequence/load
curl -X POST localhost:8000/v2/repository/models/add_sub/load
```
`simple_int8` and `simple_sequence` are the [default models in the triton repository](https://github.com/triton-inference-server/server/tree/main/docs/examples/model_repository).
`pytorch` and `add_sub`  is clone from [examples of python_backend](https://github.com/triton-inference-server/python_backend/tree/main/examples), and just add a version layer folder to fulfill triton model format.

3.  service shutdown logs
```bash
I0603 10:39:31.778689 1 tensorflow.cc:2265] TRITONBACKEND_ModelInitialize: simple_int8 (version 1)
I0603 10:39:31.779107 1 tensorflow.cc:2314] TRITONBACKEND_ModelInstanceInitialize: simple_int8 (CPU device 0)
I0603 10:39:31.779566 1 model_repository_manager.cc:1210] successfully loaded 'simple_int8' version 1
I0603 10:39:51.298084 1 model_repository_manager.cc:1043] loading: pytorch:1
I0603 10:39:51.399342 1 python.cc:1223] TRITONBACKEND_ModelInstanceInitialize: pytorch_0 (CPU device 0)
I0603 10:39:55.348521 1 model_repository_manager.cc:1210] successfully loaded 'pytorch' version 1
I0603 10:40:07.137537 1 model_repository_manager.cc:1043] loading: simple_sequence:1
I0603 10:40:07.237848 1 tensorflow.cc:2265] TRITONBACKEND_ModelInitialize: simple_sequence (version 1)
I0603 10:40:07.238243 1 tensorflow.cc:2314] TRITONBACKEND_ModelInstanceInitialize: simple_sequence_0 (CPU device 0)
W0603 10:40:07.238821 1 pinned_memory_manager.cc:104] failed to allocate pinned system memory: no pinned memory pool, falling back to non-pinned system memory
I0603 10:40:07.239184 1 model_repository_manager.cc:1210] successfully loaded 'simple_sequence' version 1
I0603 10:40:23.924136 1 model_repository_manager.cc:1043] loading: add_sub:1
I0603 10:40:24.024758 1 python.cc:1223] TRITONBACKEND_ModelInstanceInitialize: add_sub_0 (CPU device 0)
terminate called after throwing an instance of 'triton::backend::python::PythonBackendException
```
**Expected behavior**
It's this a bug? or these python models are belong to **legacy custom backed**?
I also notice the release documentation in 21.05 announce new triton release remove the support to legacy custom backend.
But I cannot find out any more information about legacy custom backend.
BTW, I test these on 21.03 and 21.04, but all **success**.

**Comment by Tabrizian** [comment]
@SraRod See this ticket: https://github.com/triton-inference-server/server/issues/2932 Python backend is not part of legacy custom backend.
