### ISSUE TITLE
build with --no-container-build flag fails while building onnxruntime inside a container

### ISSUE THREAD

**Issue by GowthamKudupudi** [triton-inference-server/server#2967]
**Description**
I'm trying to build Triton server(no container build) on a VM with Ubuntu 20.04 and T4 GPU. When executing the command
`./build.py --no-container-build --target-platform ubuntu --cmake-dir=$(pwd)/build --build-dir=/tmp/citritonbuild --enable-logging --enable-stats --enable-tracing --enable-metrics --enable-gpu-metrics --enable-gpu --filesystem=gcs --filesystem=azure_storage --filesystem=s3 --endpoint=http --endpoint=grpc --repo-tag=common:r21.05 --repo-tag=core:r21.05 --repo-tag=backend:r21.05 --repo-tag=thirdparty:r21.05 --backend=ensemble --backend=tensorrt --backend=identity:r21.05 --backend=repeat:r21.05 --backend=square:r21.05 --backend=onnxruntime:r21.05 --backend=pytorch:r21.05 --backend=tensorflow1 --backend=tensorflow2 --backend=openvino:r21.05 --backend=python:r21.05 --backend=dali:r21.05 --repoagent=checksum`
the build fails with the following error.
```
Step 26/37 : RUN ./build.sh ${COMMON_BUILD_ARGS} --update --build --use_cuda --cuda_home "/usr/local/cuda" --use_tensorrt --tensorrt_home "/usr/src/tensorrt" --use_openvino CPU_FP32
 ---> Running in a603dfe1d8d8
2021-06-07 04:55:25,623 tools_python_utils [INFO] - flatbuffers module is not installed. parse_config will not be available
2021-06-07 04:55:25,634 build [ERROR] - cuda_home and cudnn_home paths must be specified and valid.
cuda_home='/usr/local/cuda' valid=True. cudnn_home='None' valid=False
The command '/bin/sh -c ./build.sh ${COMMON_BUILD_ARGS} --update --build --use_cuda --cuda_home "/usr/local/cuda" --use_tensorrt --tensorrt_home "/usr/src/tensorrt" --use_openvino CPU_FP32' returned a non-zero code: 1
make[2]: *** [CMakeFiles/ort_target.dir/build.make:74: onnxruntime/lib/libonnxruntime.so.1.7.1] Error 1
make[2]: Leaving directory '/tmp/citritonbuild/onnxruntime/build'
make[1]: *** [CMakeFiles/Makefile2:173: CMakeFiles/ort_target.dir/all] Error 2
make[1]: Leaving directory '/tmp/citritonbuild/onnxruntime/build'
make: *** [Makefile:136: all] Error 2
error: make install failed
```
I don't know why `onnxruntime` is built inside a container when the ` --no-container-build` flag is used.

**Triton Information**
v2.10.0

Are you using the Triton container or did you build it yourself?
I'm building my self.

**To Reproduce**
Install all the dependencies in an Ubuntu server and run the above `build.py` script.

**Expected behavior**
the above error should not be encountered while building with `--no-container-build` flag.

**Comment by GowthamKudupudi** [comment]
It got fixed after installing `cuDNN`. But now I get the following error
```
2021-06-06 17:09:22,159 tools_python_utils [INFO] - flatbuffers module is not installed. parse_config will not be available
2021-06-06 17:09:22,170 build [ERROR] - cuda_home and cudnn_home paths must be specified and valid.
cuda_home='/usr/local/cuda' valid=True. cudnn_home='None' valid=False
```
but i already did `pip install flatbuffers`, `export CUDA_PATH=/usr/local/cuda-11.3`, `export cuDNN_PATH=/usr/lib/x86_64-linux-gnu` and `PATH=$PATH:~/cmake-3.20.3-linux-x86_64/bin:/usr/local/cuda-11.3/bin`

**Comment by tanmayv25** [comment]
Duplicate. Please follow: https://github.com/triton-inference-server/onnxruntime_backend/issues/33#issue-834671129
