### ISSUE TITLE
input segment_ids[0] expected type int32 != int64

### ISSUE THREAD

**Issue by somelaoda** [triton-inference-server/server#2970]
When I use tf.feature_column.embedding_column for my tensorflow model

Trition server 2.6.0 raise this error for me:

```python
2021-06-07 09:45:30.286771: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at partitioned_function_ops.cc:113 : Invalid argument: input segment_ids[0] expected type int32 != int64, the type of model/DenseFeatures_191/191_embedding/191_embedding_weights/embedding_lookup_sparse/strided_slice:output:0[0]
```

I checked out tensorflow community related issues（https://github.com/tensorflow/tensorflow/issues/43628）,they fixed this bug in the end of last year.

Now when I use tensorflow==2.4.0(official release),my model can be inferenced correctly,
but when I use trition server for inference, trition raise this error.
I think trition‘s tensorflow backend maybe needs to be upgrade to fix it.

**Comment by tanmayv25** [comment]
**Tritonserver 2.6.0** supports **TensorFlow 2.3.1**. 

As described in your issue the problem might be solved by moving to **TensorFlow 2.4.0**. I would advice moving to latest **Tritonserver 2.10.0**.  Note: **TensorFlow 2.4.0** support was added with **Tritonserver 2.7.0**

Source: https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html

Re-open if you have any other questions.

**Comment by zhaohb** [comment]
@tanmayv25  I am sorry, I using triton 2.7.0 but I had the same problem, so I do not think moving to 2.7.0 or later will solve the problem. I also test 2.10.0 ,the same error.

**Comment by tanmayv25** [comment]
Are you using --backend-config to make triton use TF 2.4.0? Otherwise by default triton will use TF 1.x.
https://github.com/triton-inference-server/tensorflow_backend#--backend-configtensorflowversionint

If not, then try using `--backend-config=tensorflow,version=2` with the server's CLI invocation.

**Comment by somelaoda** [comment]
@tanmayv25 
thanks very much！
can I set this config in my config.pbtxt? 
both tf1 model and tf2 model in my model library,I want them to go their own way

**Comment by tanmayv25** [comment]
> can I set this config in my config.pbtxt?
Unfortunately, no. Triton can support either TF2 or TF1 backend at a time.

>  If I add the command and make a version using TensorFlow 2.x, will the TensorFlow 1.x model load properly? Will there be other problems？
AFAIK, most of the TF1 savedmodels should be compatible with TF2. I might be mistaken. It's better to search on TF forums.
