### ISSUE TITLE
Python backend returning wrong results converting from NHWC to NCHW

### ISSUE THREAD

**Issue by sorny92** [triton-inference-server/server#2971]
**Description**
I've created a model with python backend doing simple preprocessing (substract and transpose)

Model.pbtxt looks like this:
```python
name: "face_detector_preprocess"
backend: "python"

input [
  {
    name: "image"
    data_type: TYPE_UINT8
    dims: [ -1, 320, 320, 3]
  }
]
output [
  {
    name: "preprocessed_image"
    data_type: TYPE_FP32
    dims: [ -1, 3, 320, 320 ]
  }
]
instance_group [{
    count: 1
    kind: KIND_CPU }]
```
The execute method in the model.py looks like this:
```python
    def execute(self, requests):
        output_dtype = self.output_dtype
        responses = []
        for request in requests:
            input_ = pb_utils.get_input_tensor_by_name(request, "image")
            in_img = torch.from_numpy(input_.as_numpy())
            in_img = torch.sub(in_img, torch.Tensor([104, 117, 123]))
            in_img = in_img.permute(0,3,1,2)
            out = in_img.numpy().astype(dtype=np.float32)
            output = pb_utils.Tensor("preprocessed_image", out.astype(output_dtype))
            inference_response = pb_utils.InferenceResponse(output_tensors=[output])
            responses.append(inference_response)
        return responses
```
Running over an example image I get a result that looks like this:
![image](https://user-images.githubusercontent.com/8601395/121043875-4ffe3580-c7b5-11eb-9747-9d0baf555bb1.png)

Doing this same step outside of Triton gives me a result as expected:
![image](https://user-images.githubusercontent.com/8601395/121046962-6953b180-c7b6-11eb-9920-d9ab7fa6b762.png)

The problem I find is in the permute step I send my image as NWHC and I want to return them as NCHW so then I can just chain this as an ensemble model (the next model uses NCHW). 
If I comment:
```            in_img = in_img.permute(0,3,1,2)```
The image is OK but in NWHC order so I don't understand what could be happening because doing the same without triton server works fine.

**Triton Information**
21.04

I'm using a Triton container which only adds numpy and torch:
```Dockerfile
FROM nvcr.io/nvidia/tritonserver:21.04-py3

RUN pip install numpy torch
```

**Comment by Tabrizian** [comment]
@sorny92 Can you please share your client file as well?  https://github.com/triton-inference-server/common/blob/249232758855cc764c78a12964c2a5c09c388d87/protobuf/model_config.proto#L344 Have you tried setting NWHC/NCHW settings in the model config?

**Comment by ajaichemmanam** [comment]
Similar issue for me. 
![NCHW](https://user-images.githubusercontent.com/10387750/121849455-f774ee00-cd08-11eb-9e17-26ea8da923b4.jpg)
![NHWC](https://user-images.githubusercontent.com/10387750/121849464-fa6fde80-cd08-11eb-8821-616e6066c136.jpg)

model config
`name: "pre_process"
backend: "python"
input[
 { 
    name: "PREPROCESS_INPUT0"
    data_type: TYPE_UINT8
    format: FORMAT_NHWC
    dims: [-1, -1, 3]
 }
]
output [
  { 
    name: "PREPROCESS_OUTPUT0"
    data_type: TYPE_FP32
    dims: [-1, 3, 512, 512]
  }
]
output [
  { 
    name: "PREPROCESS_OUTPUT1"
    data_type: TYPE_UINT8
    dims: [-1, -1, -1, 3]
  }
]
instance_group [{ kind: KIND_CPU }]`
I used numpy for processing the image

`for request in requests:
            img = pb_utils.get_input_tensor_by_name(request, "PREPROCESS_INPUT0").as_numpy()

            img_x = cv2.resize(img, (512,512))
            nchw = img_x.transpose(2, 0, 1).reshape(1, 3, 512, 512).astype(np.float32)
            nhwc = np.expand_dims(img, 0)
            
           
            out_tensor_0 = pb_utils.Tensor("PREPROCESS_OUTPUT0", nchw)
            out_tensor_1 = pb_utils.Tensor("PREPROCESS_OUTPUT1", nhwc)
            inference_response = pb_utils.InferenceResponse(output_tensors=[out_tensor_0, out_tensor_1])
            responses.append(inference_response)`

and on Client side

`NCHW_image = results.as_numpy('PREPROCESS_OUTPUT0').reshape(1,3,512,512) #-1, 3, 512, 512
        CHW = np.squeeze(NCHW_image)
        print(CHW.shape)
        CHW = CHW.transpose(1, 2, 0).astype(np.uint8)

        cv2.imwrite('./NCHW.jpg', CHW)

        NHWC_image = results.as_numpy('PREPROCESS_OUTPUT1') #-1, -1, -1, 3
        HWC = np.squeeze(NHWC_image)
        cv2.imwrite('./NHWC.jpg', HWC)`

**Comment by vspavl99** [comment]
I have the same problem. As I notice, if you reshape output image from python backend into (H,W,C) shape and plot it, the image will be correct. Also, using triton server 20.12 version fully resolved problem

**Comment by Tabrizian** [comment]
@ajaichemmanam Thanks for filing a detailed bug report. We will investigate this.

**Comment by sorny92** [comment]
> @sorny92 Can you please share your client file as well? https://github.com/triton-inference-server/common/blob/249232758855cc764c78a12964c2a5c09c388d87/protobuf/model_config.proto#L344 Have you tried setting NWHC/NCHW settings in the model config?

Hello! I tried NWHC/NCHW but doesn't change the result. As I understand that only sets how the data is ordered in memory so it should not affect the result but the performance.

**Comment by Tabrizian** [comment]
@sorny92 I can confirm that this is a bug on our side. We'll investigate and let you know when the fix is available.

**Comment by Tabrizian** [comment]
I created a PR to fix this. Meanwhile, you can use `np.ascontiguousarray` before creating the `Tensor` object.

**Comment by sorny92** [comment]
> I created a PR to fix this. Meanwhile, you can use `np.ascontiguousarray` before creating the `Tensor` object to avoid this issue.

Do you mean before creating the output Tensor?
