### ISSUE TITLE
Can't set ‘backend’ to run my tensorRT model

### ISSUE THREAD

**Issue by somelaoda** [triton-inference-server/server#2975]
https://github.com/triton-inference-server/backend

from this doc I knows that:

```python
Backends: 

For TensorRT, 'backend' must be set to tensorrt or 'platform' must be set to tensorrt_plan.
```

but when I set backend: 'tensorrt' to my conifg.pbtxt, TensorRT model can not be loaded.
only  'platform' can run  effect.

I hope the community can support 'tensorrt'   in backend，
Because I want to take TensorRT model  in my "ensemble" platform.
Thanks very much.

**Comment by CoderHam** [comment]
cc @tanmayv25 feel free to correct me if I am wrong. It looks like the docs might need to be updated.
The specification of `backend: "tensorrt"` will be available once we port TensorRT to our new Backend API and move it to its own repository. In the meanwhile please use `platform: "tensorrt_plan"`

**Comment by somelaoda** [comment]
In my understanding, 
'platform' specifies the mode of entire workflow, 
'backend' specifies which .so file  will be used in a single point of the workflow

What I didn't understand is after  my 'platform' field set to tensorrt_plan, I can still use ensemble platform which is without being declared... 

So what is dirrfeent between  'platform'  and 'backend'  ... 
Maybe I do need another document == 

Thank you for your suggestion，now my models works well

**Comment by tanmayv25** [comment]
Your understanding is correct. But we don't have a separate .so file for tensorrt backend. The tensorrt is currently in-built with triton. We are working on the TensorRT backend to get the backend out into its own .so. 

Closing the issue as your question is resolved. Please open a new issue if you have any more questions.
