### ISSUE TITLE
Failed to 

### ISSUE THREAD

**Issue by quic-nmorillo** [triton-inference-server/server#2976]
Ubuntu:  18.04
pytorch: nvcr.io/nvidia/pytorch:20.11-py3
Triton Server:  nvcr.io/nvidia/tritonserver:20.11-py3-clientsdk

I'm trying to follow this blog to convert a huggingface bert model to pytorch script and then try to run it with triton server, but I'm running into errors.  

Link to blog:  https://blog.einstein.ai/benchmarking-tensorrt-inference-server/

I was able to get a bert-base-model.pt from this script:  https://gist.github.com/keskarnitish/1061cbd101ab186e2d80c7877517e7ee#file-saved_pytorch_model-py

When I used the bash ./triton/export_model.sh with the checkpoint generated from above, I got this error:  

For bert_config and vocab file, I did a git clone from Huggingface git repo and modified the ./triton/export_model.sh script to have the correct bert_config.json  & vocab file
https://huggingface.co/bert-base-uncased/tree/main

>> DeepLearningExamples/PyTorch/LanguageModeling/BERT# bash ./triton/export_model.sh

_=============
== PyTorch ==
=============

NVIDIA Release 20.11 (build 17345815)
PyTorch Version 1.8.0a0+17f8c32

Container image Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.

Copyright (c) 2014-2020 Facebook Inc.
Copyright (c) 2011-2014 Idiap Research Institute (Ronan Collobert)
Copyright (c) 2012-2014 Deepmind Technologies    (Koray Kavukcuoglu)
Copyright (c) 2011-2012 NEC Laboratories America (Koray Kavukcuoglu)
Copyright (c) 2011-2013 NYU                      (Clement Farabet)
Copyright (c) 2006-2010 NEC Laboratories America (Ronan Collobert, Leon Bottou, Iain Melvin, Jason Weston)
Copyright (c) 2006      Idiap Research Institute (Samy Bengio)
Copyright (c) 2001-2004 Idiap Research Institute (Ronan Collobert, Samy Bengio, Johnny Mariethoz)
Copyright (c) 2015      Google Inc.
Copyright (c) 2015      Yangqing Jia
Copyright (c) 2013-2016 The Caffe contributors
All rights reserved.

NVIDIA Deep Learning Profiler (dlprof) Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.
NVIDIA modifications are covered by the license terms that apply to the underlying project or file.

NOTE: MOFED driver for multi-node communication was not detected.
      Multi-node communication performance may be reduced.

/opt/conda/lib/python3.6/site-packages/torch/serialization.py:589: UserWarning: 'torch.load' received a zip file that looks like a TorchScript archive dispatching to 'torch.jit.load' (call 'torch.jit.load' directly to silence this warning)
  " silence this warning)", UserWarning)
Traceback (most recent call last):
  File "triton/deployer.py", line 148, in <module>
    model = initialize_model(model_args)
  File "triton/deployer.py", line 89, in initialize_model
    state_dict = torch.load(args.checkpoint, map_location='cpu')["model"]
  File "/opt/conda/lib/python3.6/site-packages/torch/jit/_script.py", line 618, in __getitem__
    return self.forward_magic_method("__getitem__", idx)
  File "/opt/conda/lib/python3.6/site-packages/torch/jit/_script.py", line 611, in forward_magic_method
    raise NotImplementedError()
NotImplementedError_

**Comment by CoderHam** [comment]
This looks like a pytorch issue and not specific to Triton server. Your log indicates that you are trying to run the model using pytorch python API and not Triton. Please open an issue against PyTorch instead.
