### ISSUE TITLE
yolov5 to onnx model image client throws 'expecting model output to be a vector' error 

### ISSUE THREAD

**Issue by WillsonAmalrajA** [triton-inference-server/server#2977]
**Description**
I converted a yolov5 model to onnx model and deployed the model using onnx_runtime.

**Triton Information**
I am using tritionserver 21.04 (docker image : nvcr.io/nvidia/tritonserver:21.04-py3)

Are you using the Triton container or did you build it yourself?
I am using the official docker containers for server as well as client.

**To Reproduce**

I converted a custom trained yolov5 model to onnx model. following is the structure of the model.
![model onnx](https://user-images.githubusercontent.com/9077340/121124867-35c96380-c858-11eb-9376-626078a693de.png)

my config.pbtxt is as follows

name: "yolov5"
platform: "onnxruntime_onnx"
version_policy {
    specific: {
        versions: [ 1 ]
    }
}
max_batch_size : 0
input [
    {
        name: "images"
        data_type: TYPE_FP32
        dims: [ 3, 640, 640 ]
        reshape {shape :[1, 3, 640, 640]}
    }
]
output [
    {
        name: "output"
        data_type: TYPE_FP32
        dims: [-1, 3, 80, 80, 43]
        reshape {shape : [1, 3, 80,  80, 43] }
        label_filename: "yolov5_labels.txt"
    }
]
instance_group [
    {
        kind: KIND_GPU
        count: 1
        gpus: [ 0 ]
    }
]
default_model_filename: "model.onnx"
cc_model_filenames [
    {
        key: "6.1"
        value: "model.onnx"
    }
]

Steps to reproduce the behavior.

when I try to get an inference using image_client from triton image client using

./install/bin/image_client -m yolov5 /workspace/images/mug.jpg

I always get this error 'expecting model output to be a vector'

How do I solve this?

**Comment by tanmayv25** [comment]
Going by the model configuration:

> reshape {shape : [1, 3, 80, 80, 43] }

The error is correct. You would have to write your own image client that parses the results correctly in accordance with the model. The current image client is designed to handle resnet-like models that outputs the class probabilities as a single 1D vector per image.
