### ISSUE TITLE
Use real image data with perf_analyzer - Triton Inference Server

### ISSUE THREAD

**Issue by AkSino** [triton-inference-server/server#2978]
I'm currently trying use perf_analyzer of Nvidia Triton Inference Server with Deep Learning model which take as input a numpy array (which is an image).*

I followed the steps to use real data from the documentation but my input are rejected by the perf_analyzer : "error: unsupported input data provided perf_analyzer".

This is my input config:

```
"input": [
        {
            "name": "input_1:0",
            "data_type": "TYPE_FP32",
            "format": "FORMAT_NONE",
            "dims": [
                -1,
                -1,
                3
            ],
            "is_shape_tensor": false,
            "allow_ragged_batch": false
        }
    ],
```
And an example of JSON which I want to load in my perf_analyzer :
```
{
    "data": [
        {
            "input_1:0": {
                "content": [
                    [
                        [
                            [
                                1.8207893371582031,
                                2.0784313678741455,
                                2.4482789039611816
                            ],...,

  [
                                -2.1179039478302,
                                -2.0357143878936768,
                                -1.804444432258606
                            ]
                        ]
                    ]
                ],
                "shape": [
                    1024,
                    1024,
                    3
                ]
            }
        }
    ]
}
```
Do you have any idea how to pass images in my type_FP32 through JSON?

Thanks

**Comment by tanmayv25** [comment]
The content field in json does not support nested tensors. The data elements need to flattened in row-major format. The shape is provided separately.

From the [doc](https://github.com/triton-inference-server/server/blob/main/docs/perf_analyzer.md#real-input-data):
> Note that the [4, 4] tensor has been flattened in a row-major format for the inputs.

**Comment by tanmayv25** [comment]
Closing for now. Please re-open if the issue persists.
