### ISSUE TITLE
Triton (+ model.pt) silently exits

### ISSUE THREAD

**Issue by scamianbas** [triton-inference-server/server#2985]
**Description**
I modified fasterrcnn_resnet50_fpn in order to make it accept a single image (and not a list of images) and make it return a single tensor (and not a dict of boxes, scores, labels, ....) which is actually the label of the category detected with the best score. Then I built a model.pt TorchScript model out of that works fine on my workstation but fails on Triton.

**Triton Information**
21.05, Triton container

**To Reproduce**
mkdir server/docs/examples/model_repository/fasterrcnn_resnet50_fpn_pytorch/
mkdir server/docs/examples/model_repository/fasterrcnn_resnet50_fpn_pytorch/1

put model.pt (cannot attach, too big but I can put it on some filesharing site if needed) under fasterrcnn_resnet50_fpn_pytorch/1/
put config.pbtxt (see below) under fasterrcnn_resnet50_fpn_pytorch/
name: "fasterrcnn_resnet50_fpn_pytorch"
backend: "pytorch"
max_batch_size : 0
input [
  {
    name: "input__0"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 224, 224 ]
  }
]
output [
  {
    name: "output__0"
    data_type: TYPE_FP32
    dims: [ 1 ]
    label_filename: "coco_labels.txt"
  }
]

put coco_labels.txt (see file attached) under fasterrcnn_resnet50_fpn_pytorch/

then

docker run --gpus=1 --rm -p8000:8000 -p8001:8001 -p8002:8002 -v /home/mirko/server/docs/examples/model_repository:/models nvcr.io/nvidia/tritonserver:21.05-py3 tritonserver --model-repository=/models

docker run -it --rm --net=host nvcr.io/nvidia/tritonserver:21.05-py3-sdk
(then inside this container)
wget https://github.com/bytedance/triton-inference-server/raw/master/qa/images/car.jpg
/workspace/install/python/image_client.py -m fasterrcnn_resnet50_fpn_pytorch -c 1 -s INCEPTION car.jpg
/workspace# /workspace/install/python/image_client.py -m fasterrcnn_resnet50_fpn_pytorch -c 1 -s INCEPTION car.jpg
Traceback (most recent call last):
  File "/workspace/install/python/image_client.py", line 437, in <module>
    triton_client.infer(FLAGS.model_name,
  File "/usr/local/lib/python3.8/dist-packages/tritonclient/http/__init__.py", line 1149, in infer
    response = self._post(request_uri=request_uri,
  File "/usr/local/lib/python3.8/dist-packages/tritonclient/http/__init__.py", line 304, in _post
    response = self._client_stub.post(request_uri=request_uri,
  File "/usr/local/lib/python3.8/dist-packages/geventhttpclient/client.py", line 272, in post
    return self.request(METHOD_POST, request_uri, body=body, headers=headers)
  File "/usr/local/lib/python3.8/dist-packages/geventhttpclient/client.py", line 250, in request
    raise e
  File "/usr/local/lib/python3.8/dist-packages/geventhttpclient/client.py", line 231, in request
    sock.sendall(_request + body)
  File "/usr/local/lib/python3.8/dist-packages/gevent/_socketcommon.py", line 699, in sendall
    return _sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.8/dist-packages/gevent/_socketcommon.py", line 409, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.8/dist-packages/gevent/_socketcommon.py", line 349, in __send_chunk
    data_sent += socket.send(chunk, flags, timeout=timeleft)
  File "/usr/local/lib/python3.8/dist-packages/gevent/_socketcommon.py", line 722, in send
    return self._sock.send(data, flags)
BrokenPipeError: [Errno 32] Broken pipe

at the same time triton server container silently exited:
I0609 04:10:51.442854 1 grpc_server.cc:4062] Started GRPCInferenceService at 0.0.0.0:8001
I0609 04:10:51.454597 1 http_server.cc:2887] Started HTTPService at 0.0.0.0:8000
I0609 04:10:51.500880 1 http_server.cc:2906] Started Metrics Service at 0.0.0.0:8002
$ 

**Expected behavior**
Triton server container should not silently exit and inference should at least return the tensor (3, category number)
Here's how model.pt works on my workstation:

import torch
import torchvision
from PIL import Image
im = Image.open("car.jpg")
imt = torchvision.transforms.ToTensor()(im)
m = torch.jit.load('model.pt')
m = m.eval()
x = m(imt)
print(x)
tensor(3.)

[coco_labels.txt](https://github.com/triton-inference-server/server/files/6621048/coco_labels.txt)

**Comment by tanmayv25** [comment]
Can you share verbose server logs? Just invoke the tritonserver using `--log-verbose=1` option. 

Also share a gdb stack trace for the server when it crashes.

**Comment by scamianbas** [comment]
> Can you share verbose server logs? Just invoke the tritonserver using `--log-verbose=1` option.
> 
> Also share a gdb stack trace for the server when it crashes.

Server logs:
I0609 07:59:36.743041 1 http_server.cc:1275] HTTP request: 0 /v2/models/fasterrcnn_resnet50_fpn_pytorch
I0609 07:59:36.743085 1 model_repository_manager.cc:636] GetInferenceBackend() 'fasterrcnn_resnet50_fpn_pytorch' version -1
I0609 07:59:36.743097 1 model_repository_manager.cc:592] VersionStates() 'fasterrcnn_resnet50_fpn_pytorch'
I0609 07:59:36.743444 1 http_server.cc:1275] HTTP request: 0 /v2/models/fasterrcnn_resnet50_fpn_pytorch/config
I0609 07:59:36.743464 1 model_repository_manager.cc:636] GetInferenceBackend() 'fasterrcnn_resnet50_fpn_pytorch' version -1
I0609 07:59:36.756050 1 http_server.cc:1275] HTTP request: 2 /v2/models/fasterrcnn_resnet50_fpn_pytorch/infer
I0609 07:59:36.756073 1 model_repository_manager.cc:636] GetInferenceBackend() 'fasterrcnn_resnet50_fpn_pytorch' version -1
I0609 07:59:36.756081 1 model_repository_manager.cc:636] GetInferenceBackend() 'fasterrcnn_resnet50_fpn_pytorch' version -1
I0609 07:59:36.756126 1 infer_request.cc:497] prepared: [0x0x7f7b2c008c20] request id: 1, model: fasterrcnn_resnet50_fpn_pytorch, requested version: -1, actual version: 2, flags: 0x0, correlation id: 0, batch size: 0, priority: 0, timeout (us): 0
original inputs:
[0x0x7f7b2c004538] input: input__0, type: FP32, original shape: [3,224,224], batch + shape: [3,224,224], shape: [3,224,224]
override inputs:
inputs:
[0x0x7f7b2c004538] input: input__0, type: FP32, original shape: [3,224,224], batch + shape: [3,224,224], shape: [3,224,224]
original requested outputs:
output__0
requested outputs:
output__0

I0609 07:59:36.756431 1 libtorch.cc:1087] model fasterrcnn_resnet50_fpn_pytorch, instance fasterrcnn_resnet50_fpn_pytorch, executing 1 requests
I0609 07:59:36.756455 1 libtorch.cc:504] TRITONBACKEND_ModelExecute: Running fasterrcnn_resnet50_fpn_pytorch with 1 requests
I0609 07:59:37.556327 1 infer_response.cc:165] add response output: output: output__0, type: FP32, shape: []
I0609 07:59:37.556414 1 model_repository_manager.cc:636] GetInferenceBackend() 'fasterrcnn_resnet50_fpn_pytorch' version 2


how do I do a gdb stack trace ?

**Comment by tanmayv25** [comment]
> I have no core dump, the server container simply exits.

So, the server exits normally?

> I0609 07:59:37.556327 1 infer_response.cc:165] add response output: output: output__0, type: FP32, shape: []

It looks like the shape of the output tensor is an empty. That being said, the server should not exit without an error. I have filed a bug with our dev team to look further into the issue.

**Comment by scamianbas** [comment]
> @scamianbas could you share the model with us so we can repro the issue?
Here's a link on wetransfer where you can get model.pt : https://we.tl/t-4xNot3kLxq


Here's an example about how to use it on your workstation:

import torch
import torchvision
from PIL import Image
im = Image.open("car.jpg")
imt = torchvision.transforms.ToTensor()(im)
m = torch.jit.load('model.pt')
m = m.eval()
x = m(imt)
print(x)


And here's the image used:
![car](https://user-images.githubusercontent.com/3215795/121460497-4c350380-c9ad-11eb-8cc2-c82bb0f19959.jpg)

**Comment by CoderHam** [comment]
@scamianbas Triton server does segfault when the output is a scalar in the PyTorch Backend. Please note that Triton does not support scalars I/O. 

You will need to wrap your fasterrcnn_resnet50_fpn pytorch model in a wrapper that converts the output from scalar to a vector of dims [1] before you trace the model to create the TorchScript model. 

That being said, Triton should detect the output is a scalar and ensure an error is reported instead of segfaulting. I will have a fix up shortly. Thank you for your repro and bringing this to our attention.

**Comment by scamianbas** [comment]
> @scamianbas Triton server does segfault when the output is a scalar in the PyTorch Backend. Please note that Triton does not support scalars I/O.
> 
> You will need to wrap your fasterrcnn_resnet50_fpn pytorch model in a wrapper that converts the output from scalar to a vector of dims [1] before you trace the model to create the TorchScript model.
> 
> That being said, Triton should detect the output is a scalar and ensure an error is reported instead of segfaulting. I will have a fix up shortly. Thank you for your repro and bringing this to our attention.

@CoderHam Thank you very much it works now, here's the output:

/workspace/install/python/image_client.py -m fasterrcnn_resnet50_fpn_pytorch -c 1 -s INCEPTION car.jpg
Request 1, batch size 1
    3.000000 (0) = __background__
PASS

I followed your advice and transformed my scalar x to a one dim vector with x.reshape(1)

Thank you very much again :)

**Comment by rxdcxdrnine** [comment]
@scamianbas
How did you modified fasterrcnn__resnet50_fpn with wrapper model?
I tried it with `nvcr.io/nvidia/pytorch:20-07-py3`container like below.

```
import torch
import torchvision

class FasterRCNNWrapper(torch.nn.Module):

    def __init__(self):
        super().__init__()
        self.model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=True)

    def forward(self, x):
        losses, detections = self.model([x])
        return detections[0]['boxes'], detections[0]['labels'], detections[0]['scores']

if __name__ == "__main__":
    model = FasterRCNNWrapper()
    script = torch.jit.script(model)
    script.save('model.pt')
```

But there was error like below.
```
E0629 09:25:17.227953 1 model_repository_manager.cc:1213] failed to load 'fasterRCNN' version 1: Internal: failed to load model 'fasterRCNN': 
Unknown builtin op: torchvision::_new_empty_tensor_op.
Could not find any similar ops to torchvision::_new_empty_tensor_op. This op may not exist or may not be currently supported in TorchScript.
```

**Comment by scamianbas** [comment]
> @scamianbas
> How did you modified fasterrcnn__resnet50_fpn with wrapper model?
> I tried it with `nvcr.io/nvidia/pytorch:20-07-py3`container like below.
> 
> ```
> import torch
> import torchvision
> 
> class FasterRCNNWrapper(torch.nn.Module):
> 
>     def __init__(self):
>         super().__init__()
>         self.model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=True)
> 
>     def forward(self, x):
>         losses, detections = self.model([x])
>         return detections[0]['boxes'], detections[0]['labels'], detections[0]['scores']
> 
> if __name__ == "__main__":
>     model = FasterRCNNWrapper()
>     script = torch.jit.script(model)
>     script.save('model.pt')
> ```
> 
> But there was error like below.
> 
> ```
> E0629 09:25:17.227953 1 model_repository_manager.cc:1213] failed to load 'fasterRCNN' version 1: Internal: failed to load model 'fasterRCNN': 
> Unknown builtin op: torchvision::_new_empty_tensor_op.
> Could not find any similar ops to torchvision::_new_empty_tensor_op. This op may not exist or may not be currently supported in TorchScript.
> ```

@rxdcxdrnine In main you need to run your model with an image before saving it to TorchScript, look at my posts above.

**Comment by rxdcxdrnine** [comment]
@scamianbas 
Thank you for your quick reply.
Since I could run model with image in `nvcr.io/nvidia/pytorch:20.07-py3` container, there's always torchvision error when I run tritonserver with `nvcr.io/nvidia/tritonserver:21.05-py3`container. And the error is below.
How did you solve within torchvision error?

```
Unknown builtin op: torchvision::_new_empty_tensor_op.
Could not find any similar ops to torchvision::_new_empty_tensor_op. This op may not exist or may not be currently supported in TorchScript.
:
  File "/opt/conda/lib/python3.6/site-packages/torchvision/ops/new_empty_tensor.py", line 16
        output (Tensor)
    """
    return torch.ops.torchvision._new_empty_tensor_op(x, shape)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
Serialized   File "code/__torch__/torchvision/ops/new_empty_tensor.py", line 3
def _new_empty_tensor(x: Tensor,
    shape: List[int]) -> Tensor:
  _0 = ops.torchvision._new_empty_tensor_op(x, shape)
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
  return _0
'_new_empty_tensor' is being compiled since it was called from 'interpolate'
Serialized   File "code/__torch__/torchvision/ops/misc.py", line 28
  _2 = __torch__.torch.nn.functional.___torch_mangle_5.interpolate
  _3 = __torch__.torchvision.ops.misc._output_size
  _4 = __torch__.torchvision.ops.new_empty_tensor._new_empty_tensor
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
  if torch.gt(torch.numel(input), 0):
    _6 = _2(input, size, scale_factor, mode, align_corners, None, )
'interpolate' is being compiled since it was called from '_resize_image_and_masks'
Serialized   File "code/__torch__/torchvision/models/detection/transform.py", line 212
    target: Optional[Dict[str, Tensor]]) -> Tuple[Tensor, Optional[Dict[str, Tensor]]]:
  _71 = __torch__.torch.nn.functional.___torch_mangle_4.interpolate
  _72 = __torch__.torchvision.ops.misc.interpolate
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
  _73 = torch.slice(torch.size(image), -2, 9223372036854775807, 1)
  im_shape = torch.tensor(_73, dtype=None, device=None, requires_grad=False)
'_resize_image_and_masks' is being compiled since it was called from 'GeneralizedRCNNTransform.resize'
Serialized   File "code/__torch__/torchvision/models/detection/transform.py", line 80
    target: Optional[Dict[str, Tensor]]) -> Tuple[Tensor, Optional[Dict[str, Tensor]]]:
    _19 = "This Python function is annotated to be ignored and cannot be run"
    _20 = __torch__.torchvision.models.detection.transform._resize_image_and_masks
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    _21 = __torch__.torchvision.models.detection.transform.resize_boxes
    _22 = __torch__.torchvision.models.detection.transform.resize_keypoints
'GeneralizedRCNNTransform.resize' is being compiled since it was called from 'GeneralizedRCNNTransform.forward'
  File "/opt/conda/lib/python3.6/site-packages/torchvision/models/detection/transform.py", line 93
                                 "of shape [C, H, W], got {}".format(image.shape))
            image = self.normalize(image)
            image, target_index = self.resize(image, target_index)
                                  ~~~~~~~~~~~ <--- HERE
            images[i] = image
            if targets is not None and target_index is not None:
Serialized   File "code/__torch__/torchvision/models/detection/transform.py", line 29
        pass
      image0 = (self).normalize(image, )
      _2 = (self).resize(image0, target_index, )
                                 ~~~~~~~~~~~~ <--- HERE
      image1, target_index0, = _2
      _3 = torch._set_item(images0, i, image1)
```
