### ISSUE TITLE
how to set cuda version when build?

### ISSUE THREAD

**Issue by HaoLiuHust** [triton-inference-server/server#2987]
when build the project with main branch, it use cuda 11.3. But with my test, I can not use cuda 11.3 with 1080Ti, so I have to use cuda 11.1 instead,  how can I change the cuda version when building?

**Comment by tanmayv25** [comment]
Triton and other framework containers are built with the specific cuda version. You can try Triton 20.12  which is built using cuda 11.1.1 or Triton 20.11 which is built using cuda 11.1.0.

If you want to try to build the main branch with cuda11.1.x note that the build configuration is not tested and you may run into some issues. See the following links to get more information about how to build triton with custom cuda:
https://github.com/triton-inference-server/server/blob/main/docs/build.md#cuda-cublas-cudnn
https://github.com/triton-inference-server/server/blob/main/docs/build.md#building-without-docker
