### ISSUE TITLE
How to load python backend model without restart server

### ISSUE THREAD

**Issue by HaoLiuHust** [triton-inference-server/server#2989]
**Description**
start up server without python model in model repo, then python backend will not start up, and when put a python model into mode repo, the model will not be servered. Restart the server, the python backend will start up and the model will be served. I wonder is there a way to server python model without restart?

**Triton Information**
What version of Triton are you using?

r21.03

**Comment by tanmayv25** [comment]
You are looking for:
https://github.com/triton-inference-server/server/blob/main/docs/model_management.md#model-control-mode-explicit

Start the server in explicit mode and then use [model_control_api](https://github.com/triton-inference-server/server/blob/main/docs/protocol/extension_model_repository.md) to load the python model to begin serving.
