### ISSUE TITLE
Do we need to explicitly load/unload sub-models in an ensemble model.

### ISSUE THREAD

**Issue by Taiga648** [triton-inference-server/server#2993]
In explicit mode: to load an ensemble model, do we need to explicitly load the underlying models first, or the load of the ensemble model will take care of it? The same question for the unload ensemble model.

Thank you

**Comment by tanmayv25** [comment]
I believe you would need to explicitly load all the composing models to triton. @GuanLuo  Can you confirm?

For unloading, triton has an option to unload all the composing models alongwith the ensembe. Look at the `unload_dependents` in [here](https://github.com/triton-inference-server/server/blob/main/docs/protocol/extension_model_repository.md#unload). This allows you to unload all the composing models of the ensemble.

**Comment by GuanLuo** [comment]
As Tanmay stated, The unloading can be controlled with `unload_dependents`. For loading, the load of the ensemble itself will trigger polling and loading the composing models.

**Comment by Taiga648** [comment]
Thank you GuanLuo and Tanmayv25 for the prompt response. 

We are currently using version 1.13, do you believe this behavior is supported in 1.13 and through the GRPC client? We are under the impression that the 1.13 does not seem to support it. If not in what version the described behavior was introduced?

A follow-up question to the unload with unload_dependents  what would be the behavior if I had 2 ensemble models EM1, and EM2, and both ensembles have a common model CM, and I unload EM2 with unload_dependents? Will it unload everything but CM because it is still being used by EM1, or it will do something else?

Thanks again for all your help

**Comment by tanmayv25** [comment]
The feature was added with 2.9.0 See [here](https://github.com/triton-inference-server/server/releases/tag/v2.9.0). 

> A follow-up question to the unload with unload_dependents what would be the behavior if I had 2 ensemble models EM1, and EM2, and both ensembles have a common model CM, and I unload EM2 with unload_dependents? Will it unload everything but CM because it is still being used by EM1, or it will do something else?

Triton maintains a dependency graph and should unload the model only when the last holding EM2 is unloaded. Please file a bug if you notice otherwise.

**Comment by Taiga648** [comment]
Thank you for all your help.

**Comment by tanmayv25** [comment]
Closing the issue. Please file a new issue if you have any questions.
