### ISSUE TITLE
How to minimize the docker image for deployment?

### ISSUE THREAD

**Issue by Edwardmark** [triton-inference-server/server#2999]
Hi, the tritonserver is as large as 11G, how to minimize the docker image size so that the deploy can be more convenient.
Thanks.

**Comment by tanmayv25** [comment]
Please see the instructions here: https://github.com/triton-inference-server/server/blob/main/docs/compose.md#minimum-triton

See the similar issue [here](https://github.com/triton-inference-server/server/issues/2856#issue-891557471).

**Comment by tanmayv25** [comment]
Closing the issue for now. Please re-open if you have any more questions.

**Comment by Edwardmark** [comment]
@tanmayv25 Hi, could you tell me how large a minimal deploy docker image is which contains tensorRT/python/dali backend with necessary dependancy? I try to use triton-server-minimal to build the docker image, but it is still as large as 10G.

**Comment by Edwardmark** [comment]
@tanmayv25 can I change the base image from UBUNTU to other minimal linux operating system?

**Comment by tanmayv25** [comment]
@Edwardmark  The base container with cuda/cudnn/tensorrt dependency is itself ~6GB. I believe 10GB is expected. 
If you want CPU only containers then probably you can get smaller container sizes.

> @tanmayv25 can I change the base image from UBUNTU to other minimal linux operating system?

I don't think the issue size is with ubuntu base container but the cuda library. All the dependencies are installed assuming ubuntu in our scripts. This will definitely be a lot more involved exercise.

On a side note, we are working on compose utility which will allow you to directly build containers with different requirements similar to our `build.py`. Do keep an eye for it.

**Comment by Edwardmark** [comment]
@tanmayv25 Thank you very much.
