### ISSUE TITLE
Model Load request to a kubernetes cluster reaches only one pod (when replicationCount > 1)

### ISSUE THREAD

**Issue by nsiddharth** [triton-inference-server/server#3001]
**Description**
We are using a kubernetes setup for the triton service and I was curious about the model load behavior. A model load request to triton in a kubernetes deployment is routed to only one pod (replicationCount > 1), is this expected behavior? It will result in an inconsistent state during inferencing. I wonder if triton has logic to send the model load request to all pods in the cluster? Has this behavior been tested and is it known to work as expected? Any details will be helpful in figuring out if there is an issue on our end or if this is a bug in triton.
**Triton Information**
2.11.0dev

Are you using the Triton container or did you build it yourself?
built from main branch
**To Reproduce**
Steps to reproduce the behavior.
setup a kubernetes cluster with multiple pods and send a model load request in explicit mode. We should have all pods receive this request and load the newer model.
Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**
All pods in the cluster should load the new model and not just one or part of the cluster. 

It may be the case that this is somehow specific to our deployment but I wanted to confirm that this is how triton is supposed to work and the model load request should indeed be sent to all the pods. If not, should it be considered a bug because it will result in an inconsistent state for model inferencing?

**Comment by nsiddharth** [comment]
The requests get routed to a specific pod at random and this is fine for inferencing but the model load request should reach all pods to avoid inconsistencies. I don't know that there is a good way to do this currently in a distributed environment without triton supporting it natively. we may have to write additional logic to achieve this to make is usable in production.

**Comment by deadeyegoodwin** [comment]
This is beyond the scope of Triton. If you want to load a model onto all servers in a cluster then you need some agent operating within the cluster that can communicate directly with the individual nodes in the cluster. Triton has no knowledge of the cluster or of the other nodes. This sounds like a specific problem within the more general problem of "model orchestration". You could look at KFS MMS as one open-source project trying to address it:  https://github.com/kubeflow/kfserving
