### ISSUE TITLE
A suggestion: allowing the different batch size of inputs  for "ensemble mode".

### ISSUE THREAD

**Issue by michael0218** [triton-inference-server/server#3007]
I have two inputs, one is batched images and the other is a 2D tensor (not batched) that contains predicting bounding boxes from the previous model.

I'm always frustrated when the second model be triggered the error message shows.
**in ensemble 'ensemble_model', 'input' 'input01' batch size does not match other inputs for 'cnn_model'**

The walkaround is to replicate 2D tensor and concatenate as a _batch_.

I would like to know there any efficient or more correct way to handle those mismatch inputs.
Thank you.

**Comment by GuanLuo** [comment]
Confusion will be raised if inputs of different batch size is allowed, for example, when multiple requests are batched and sent to the model, which of the batch sizes is the correct one to scatter the output?

In your case the 'cnn_model' model is not really a batchable model from Triton's perspective, you should set `max_batch_size` to 0 and specify the full shape for the inputs in your model config
