### ISSUE TITLE
Deployment Strategies

### ISSUE THREAD

**Issue by jax79sg** [triton-inference-server/server#3008]
**Is your feature request related to a problem? Please describe.**
There are times when I want to deploy new models with a certain strategy. For example, I would sometimes want to deploy in shadow mode. Meaning my last version is still serving the users but my latest version is also running the inference. 

**Describe the solution you'd like**
Does it make sense to incorporate Deployment Strategies in Triton? Or should we write another layer of software to do this prior to Triton?

**Describe alternatives you've considered**

**Additional context**

**Comment by deadeyegoodwin** [comment]
Deployment strategies like canary, incremental rollout, etc. should be performed by a cluster / container management layer like kubernetes. Triton provides endpoints and metrics to integrate seemlessly in these envionments but does not provide the deployment strtegies itself.
