### ISSUE TITLE
Error cannot find -ltorch and ltorchvision in building PyTorch Backend along with Triton Server in Oracle Linux 7.9

### ISSUE THREAD

**Issue by chandrameenamohan** [triton-inference-server/server#3010]
**Description**
I am trying to build Triton Server with pytorch backend I am getting this error:

```
[100%] Linking CXX shared library libtriton_pytorch.so
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/triton-pytorch-backend.dir/link.txt --verbose=0
/usr/bin/ld: cannot find -ltorch
/usr/bin/ld: cannot find -ltorchvision
collect2: error: ld returned 1 exit status
make[2]: *** [libtriton_pytorch.so] Error 1
make[2]: Leaving directory `/tmp/citritonbuild/pytorch/build'
make[1]: *** [CMakeFiles/triton-pytorch-backend.dir/all] Error 2
make[1]: Leaving directory `/tmp/citritonbuild/pytorch/build'
make: *** [all] Error 2
error: make install failed
```
I am using this command:

`./build.py --cmake-dir=/home/git/server/build --build-dir=/tmp/citritonbuild --no-container-build --endpoint=http --endpoint=grpc --repo-tag=common:r21.04 --repo-tag=core:r21.04 --repo-tag=backend:r21.04 --repo-tag=thirdparty:r21.04 --backend=pytorch:r21.04 --enable-logging --enable-stats --enable-tracing`

**Triton Information**
What version of Triton are you using?

Are you using the Triton container or did you build it yourself?
Yes. I am building it myself. I am using r21.04 release

**To Reproduce**
Steps to reproduce the behavior.
Use oracle linux 7.9 or centos 7.9 for build.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**

**Comment by GuanLuo** [comment]
If not building with docker container, then you need to provide the library path via [`--library-paths`](https://github.com/triton-inference-server/server/blob/main/build.py#L1073-L1080)

**Comment by chandrameenamohan** [comment]
Can you please provide me the example of library paths?
I found that torch and torchvision is this directory path:` /tmp/citritonbuild/pytorch/build/include`

**Comment by CoderHam** [comment]
You will need to specify both TRITON_PYTORCH_LIB_PATHS and TRITON_PYTORCH_INCLUDE_PATHS for a non NGC docker build.

For TRITON_PYTORCH_INCLUDE_PATHS you can refer to the pytorch_backend ReadMe and look at the pytorch_backend CMakeLists.txt: https://github.com/triton-inference-server/pytorch_backend/blob/main/CMakeLists.txt#L220-L222
```
      ${CMAKE_CURRENT_BINARY_DIR}/include/torch
      ${CMAKE_CURRENT_BINARY_DIR}/include/torch/torch/csrc/api/include
      ${CMAKE_CURRENT_BINARY_DIR}/include/torchvision
```

TRITON_PYTORCH_LIB_PATHS should be the path to the pytorch and torchvision libs and dependencies. This would vary based on how you built the version of pytorch you wish to use.

**Comment by CoderHam** [comment]
I just noticed that the build.py does not contain the option to pass these library flags for the pytorch backend. I will follow up on a fix for this. In the meantime please build the pytorch backend with the instructions in the pytorch_backend [ReadMe](https://github.com/triton-inference-server/pytorch_backend#readme).

**Comment by hit-lance** [comment]
> Can you please provide me the example of library paths?
> I found that torch and torchvision is this directory path:` /tmp/citritonbuild/pytorch/build/include`

hey, do you solve the problem now?

**Comment by chandrameenamohan** [comment]
I was able to solve this problem.

Go to this directory:
`/tmp/citritonbuild/pytorch/build/CMakeFiles/triton-pytorch-backend.dir`
Open this file:
`vim link.txt`
My file looks like this:
`/usr/local/bin/c++ -fPIC -O3 -DNDEBUG -Wl,--no-as-needed,--version-script libtriton_pytorch.ldscript -shared -Wl,-soname,libtriton_pytorch.so -o libtriton_pytorch.so CMakeFiles/triton-pytorch-backend.dir/src/libtorch.cc.o CMakeFiles/triton-pytorch-backend.dir/src/libtorch_utils.cc.o  -Wl,-rpath,"\${ORIGIN}" _deps/repo-core-build/libtritonserver_stub.so _deps/repo-backend-build/libtritonbackendutils.a -L/tmp/citritonbuild/pytorch/build -ltorch -ltorchvision`
Why I am adding path of library `-L/path-of-library`? - https://stackoverflow.com/questions/16710047/usr-bin-ld-cannot-find-lnameofthelibrary
Come back to build directory:
`cd /tmp/citritonbuild/pytorch/build`
Run
`make install`

**Comment by hit-lance** [comment]
> I was able to solve this problem.
> 
> Go to this directory:
> `/tmp/citritonbuild/pytorch/build/CMakeFiles/triton-pytorch-backend.dir`
> Open this file:
> `vim link.txt`
> My file looks like this:
> `/usr/local/bin/c++ -fPIC -O3 -DNDEBUG -Wl,--no-as-needed,--version-script libtriton_pytorch.ldscript -shared -Wl,-soname,libtriton_pytorch.so -o libtriton_pytorch.so CMakeFiles/triton-pytorch-backend.dir/src/libtorch.cc.o CMakeFiles/triton-pytorch-backend.dir/src/libtorch_utils.cc.o -Wl,-rpath,"\${ORIGIN}" _deps/repo-core-build/libtritonserver_stub.so _deps/repo-backend-build/libtritonbackendutils.a -L/tmp/citritonbuild/pytorch/build -ltorch -ltorchvision`
> Why I am adding path of library `-L/path-of-library`? - https://stackoverflow.com/questions/16710047/usr-bin-ld-cannot-find-lnameofthelibrary
> Come back to build directory:
> `cd /tmp/citritonbuild/pytorch/build`
> Run
> `make install`

Thank you so much! I build pytorch backend successfully by using your method. However when I run tritonsever I still got error: `UNAVAILABLE: Invalid argument: unable to find 'libtriton_pytorch.so' for model 'resnet50_torch', searched: /models/resnet50_torch/1, /models/resnet50_torch, /opt/tritonserver/backends/pytorch you so much! I build pytorch backend successfully by using your method. However when I run tritonsever I still got error: ""`
<img width="1410" alt="截屏2021-07-02 下午4 59 46" src="https://user-images.githubusercontent.com/57555256/124251440-7ca93100-db58-11eb-8656-4222184485ea.png">
Have you encountered this problem? I want to ask how to solve it

**Comment by chandrameenamohan** [comment]
Error says - tritonserver is not able to find the libtrititon_pytorch library. 
Copy the install binaries of pytorch to tritonserver directory
go to directory:
`cd /tmp/citritonbuild/pytorch/install`
Then copy backends, lib and lib64 to /opt/tritonserver
```
cp -r backends /opt/tritonserver/backends
cp -r include /opt/tritonserver/include
cp -r lib64 /opt/tritonserver/lib64
```

**Comment by hit-lance** [comment]
> I was able to solve this problem.
> 
> Go to this directory:
> `/tmp/citritonbuild/pytorch/build/CMakeFiles/triton-pytorch-backend.dir`
> Open this file:
> `vim link.txt`
> My file looks like this:
> `/usr/local/bin/c++ -fPIC -O3 -DNDEBUG -Wl,--no-as-needed,--version-script libtriton_pytorch.ldscript -shared -Wl,-soname,libtriton_pytorch.so -o libtriton_pytorch.so CMakeFiles/triton-pytorch-backend.dir/src/libtorch.cc.o CMakeFiles/triton-pytorch-backend.dir/src/libtorch_utils.cc.o -Wl,-rpath,"\${ORIGIN}" _deps/repo-core-build/libtritonserver_stub.so _deps/repo-backend-build/libtritonbackendutils.a -L/tmp/citritonbuild/pytorch/build -ltorch -ltorchvision`
> Why I am adding path of library `-L/path-of-library`? - https://stackoverflow.com/questions/16710047/usr-bin-ld-cannot-find-lnameofthelibrary
> Come back to build directory:
> `cd /tmp/citritonbuild/pytorch/build`
> Run
> `make install`

I found a more elegant solution. Just modify [CMakeLists.txt line 276-279](https://github.com/triton-inference-server/pytorch_backend/blob/137bdfb6dae1e52d573373ba77641b66658ae18c/CMakeLists.txt#L276) to set(TRITON_PYTORCH_LDFLAGS "-L${CMAKE_CURRENT_BINARY_DIR}") will solve the problem.
