### ISSUE TITLE
Trouble understanding REST outputs from Python TritonClient 

### ISSUE THREAD

**Issue by PeterSenyszyn** [triton-inference-server/server#3011]
Hello,

I've successfully loaded my YOLOv5l model that I converted to ONNX into Triton Inference Server. Inference is being run with the TensorRT backend. I'm having a hard time understanding the response I'm getting from the server. My code:
```
url = "localhost:1234"
model_name = "level"

triton_client = httpclient.InferenceServerClient(url=url, verbose=False)
model_metadata = AttrDict(triton_client.get_model_metadata(model_name))
model_config = AttrDict(triton_client.get_model_config(model_name))

input_name, output_name, format, dtype = parse_model(model_metadata, model_config)

rgb_img = Image.open("img.png").convert('RGB')
rgb_img = rgb_img.resize((1920, 1920), Image.BILINEAR)
image = np.asarray(rgb_img, dtype=np.float32)
image /= 255.0  # Normalize
image = np.transpose(image, (2, 0, 1))  # change order to c w h
image = np.asarray([image])  # stack array

responses = []
for input, output in request_generator(image, input_name, output_name, dtype):
    responses.append(triton_client.infer("level", input, request_id="asd", outputs=output))

for response in responses:
    post_process(response, output_name)
```

```
def parse_model(metadata, config):
    input_metadata = metadata.inputs[0]
    input_config = config.input[0]
    output_metadata = metadata.outputs[1]
    return input_metadata.name, output_metadata.name, input_config.format, input_metadata.datatype


def request_generator(image_data, input_name, output_name, dtype):
    input = [httpclient.InferInput(input_name, image_data.shape, dtype)]
    input[0].set_data_from_numpy(image_data)
    output = [httpclient.InferRequestedOutput(output_name, class_count=2)]
    yield input, output


def post_process(resp, output_name):
    output_array = resp.as_numpy(output_name)
    print(str(output_array))
    for results in output_array:
        print(results)
```

The response: `[b'1917.162231:1209593' b'1916.938843:806393']`

From https://github.com/triton-inference-server/server/blob/main/docs/protocol/extension_classification.md I read that each element represents a "<value>:<index>" where <index> is the index of the class in the model output tensor, and <value> is the value associated with that index in the model output. From this how do we get bounding boxes to perform NMS on, along with their class ids? 

 My config.pbtxt looks like this:

```
name: "level",
platform: "onnxruntime_onnx",
backend: "onnxruntime",
version_policy: {
    latest: {
        num_versions: 1
    }   
},
max_batch_size: 0,
input [
    {   
        name: "images",
        data_type: TYPE_FP32,
        dims: [1, 3, 1920, 1920]
    }   
],
output [
    {   
        name: "712",
        data_type: TYPE_FP32,
        dims: [1, 3, 120, 120, 7]
    },  
    {   
        name: "output",
        data_type: TYPE_FP32,
        dims: [1, 226800, 7]
    },  
    {   
        name: "773",
        data_type: TYPE_FP32,
        dims: [1, 3, 60, 60, 7]
    },  
    {   
        name: "651",
        data_type: TYPE_FP32,
        dims: [1, 3, 240, 240, 7]
    }   
],

optimization {
    execution_accelerators {
        gpu_execution_accelerator : [ { name : "tensorrt" } ] 
    }   
},
default_model_filename: "model.onnx",
instance_group [ { count: 1 } ],
model_warmup: []
```
My understanding is that I just need to get outputs from the detect layer, i.e "output" with 226800 predictions and 7 representing "x y w h objectness conf_cls1 conf_cls2". Is this correct? It's not clear to me how to translate my outputs to a bounding box and class id. If anyone could help me out that would be great. Thank you!

**Comment by PeterSenyszyn** [comment]
Here's the detect layer of my model in Netron:
![Screenshot from 2021-06-14 19-12-23](https://user-images.githubusercontent.com/2731293/121974561-4476b580-cd45-11eb-8a24-e0dff3074548.png)

**Comment by GuanLuo** [comment]
Not sure why you want to use classification extension for your case, it is used when the output is a vector representing the probabilities of different classes (i.e. resnet output), which I don't think that the output of your model aligns with the use case. You should remove the `class_count` setting in your `request_generator` function which will return the output as it is, and you can postprocess it appropriately
