### ISSUE TITLE
faild build requires deletion of `/tmp/citritonbuild/<backend>` git repo folders

### ISSUE THREAD

**Issue by GowthamKudupudi** [triton-inference-server/server#3013]
**Description**
If the Triton server build fails due to any reason, I have to delete the `/tmp/citritonbuild/<backend>` folders to prevent the next rebuild from throwing `git repo already exists` error.

**Triton Information**
r21.05

I am building the Triton server myself.

**To Reproduce**
uninstall one of the dependency needed by a backend.
run `build.py` with all the backends enabled.
let the build fail after building some of the backends.
now install the dependency that was uninstalled before.
run the `build.py`
now the build fails with `git repo already exists` error.

**Expected behavior**
the build should succeed without any errors

**Comment by dyastremsky** [comment]
I don't believe this issue exists any longer. If you find this is still true on the main branch, please let us know and we can reopen the issue.
