### ISSUE TITLE
When 21.06 Will be available to launch triton in unprivileged (non-root user) ?

### ISSUE THREAD

**Issue by MaxGdr** [triton-inference-server/server#3021]
**Description**
Cannot deploy as unprivileged the triton inference server.

**Triton Information**
Latest (21.05)

Are you using the Triton container or did you build it yourself?

**To Reproduce**
Deploy to Openshift for example, or run as non-root user

----
I know that this problem is due to symbolic linking for libs, and the problem has been already identified and it will be fixed in the Release 21.06, but I'm wondering when this release will be available ? Thanks for your answer and have a great day !

**Comment by Tabrizian** [comment]
21.06 will be released by the end of month.

**Comment by MaxGdr** [comment]
Thank you Tabrizian !
