### ISSUE TITLE
Example to Test TensorFlow2 Backend in TritonServer Built Without Docker

### ISSUE THREAD

**Issue by chandrameenamohan** [triton-inference-server/server#3023]
**Is your feature request related to a problem? Please describe.**
I have built my tritonserver for TensorFlow1 and TensorFlow2 on RHEL7. I checked the examples in https://github.com/triton-inference-server/server/tree/main/docs/examples/model_repository . But all these examples use TensorFlow1 backend. I am looking for example which I can use to test TensorFlow2 backend as well.

**Describe the solution you'd like**
I am looking for example model for sanity test of my TensorFlow2 backend.

**Describe alternatives you've considered**

**Additional context**

**Comment by Tabrizian** [comment]
Instead of finding a TF2 only model, you can try loading the triton with "--backend-config=tensorflow,version=2" to make sure that the TF2 is compiled and works properly.

**Comment by Tabrizian** [comment]
Closing the issue, feel free to re-open if you have follow up questions.
