### ISSUE TITLE
from tritonclient.grpc import model_config_pb2

### ISSUE THREAD

**Issue by Edwardmark** [triton-inference-server/server#3025]
I can import tritonclient without error, but when I try to import grpc, the error shows:

![image](https://user-images.githubusercontent.com/15247551/122498284-6b710800-d021-11eb-85a3-05b35769a7df.png)

why is that, and how to solve that? Thanks.

**Comment by GuanLuo** [comment]
I couldn't reproduce it, can you try to use the latest container if you are not using it? And please provide repro steps if it still not working for you.
```
/opt/tritonserver# python
Python 3.8.5 (default, May 27 2021, 13:30:53) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tritonclient
>>> import tritonclient.grpc
>>> 
```
