### ISSUE TITLE
Error message while installing triton for jetpack

### ISSUE THREAD

**Issue by francescokoh** [triton-inference-server/server#3030]
Trying to install triton for jetpack on my NVidia jetson agx xavier. 

I followed process mentioned in latest github release page of triton server.

Before the last process, there is no problem. But in last process, I got an error message like follows:
error while loading shared libraries: libnvinfer.so.7: cannot open shared object file: No such file or directory

What is the reason of this message and how to fix this?

I used Nvidia jetson agx xavier.
And jetpack 4.5.1 is installed in my device.

**Comment by CoderHam** [comment]
If Jetpack 4.5.1 is installed you should have TRT 7 installed as well. Can you confirm if the same is true and which version of TRT you have installed?
Refer to: https://developer.nvidia.com/jetpack-sdk-45-archive
Please note that the [release](https://github.com/triton-inference-server/server/releases/tag/v2.10.0) tar file was built on and for JP 4.5.

**Comment by francescokoh** [comment]
> If Jetpack 4.5.1 is installed you should have TRT 7 installed as well. Can you confirm if the same is true and which version of TRT you have installed?
> 
> Refer to: https://developer.nvidia.com/jetpack-sdk-45-archive
> 
> Please note that the [release](https://github.com/triton-inference-server/server/releases/tag/v2.10.0) tar file was built on and for JP 4.5.
> 
> 

As you said, I missed install tensorrt in flashing jetpack os.
Sp, I tried to install tensorrt singly but I can't find the way to install it in arm arm architecture.
So, I reinstall jetpack os.
And everything is working well.
