### ISSUE TITLE
Constant URL for RESTAPI

### ISSUE THREAD

**Issue by okyspace** [triton-inference-server/server#3031]
**Is your feature request related to a problem? Please describe.**
My use case requires to use latest version of the model deployed. However, the URL is changed whenever we have a new version. e.g. v2/models/<model_name>/versions/1/infer. Thus, this requires a change in our proxy server or client side which can be tedious if we roll out new versions quite regularly and frequently. 

**Describe the solution you'd like**
Provide an option to indicate that latest / specific version of the model to be used with a constant URL. 
e.g. v2/models/<model_name>/versions/<user_defined>/infer.

**Comment by CoderHam** [comment]
If you do not specify a version or specify -1 as the version and that should use the latest version. 
You might also want to consider using the version policy in the model config to ensure the older versions of the model are unloaded.

**Comment by okyspace** [comment]
@CoderHam, I tried your recommendation. 
i.e. Using APi v2/models/mnist/versions/-1 to retrieve the metadata. 
I got error getting the model metadata. Similarly for v2/models/mnist/versions.
Not sure if I understood you correctly. Can share example of what you mean?

I have tried versions_policy. say using latest {num_versions: 1}. Although only latest model will be loaded, the API will still change according to the version number.

**Comment by CoderHam** [comment]
What happens when you do not specify the version?
You will not need to change the API based on version number since it will use the latest loaded version.

**Comment by okyspace** [comment]
@CoderHam, Thanks. I think I got it. It works if we do not specify the version but failed if we uses -1 as the version. 

########## Here's the details ##########
**What happens when you do not specify the version?**
If you are referring to APi `v2/models/mnist`, I will get the model meta data with all the versions number that are configured to be available. 

**You will not need to change the API based on version number since it will use the latest loaded version.**
I tried API `v2/models/{MODEL_NAME}/versions/-1/infer` ==> failed. http400
I tried API `v2/models/{MODEL_NAME}/infer` ==> OK. triton uses latest version. I verified using the actual version: 3 printed in the server. Is this correct?
