### ISSUE TITLE
Python Backend does not load due to shared memory issue

### ISSUE THREAD

**Issue by nsiddharth** [triton-inference-server/server#3036]
**Description**
Triton is unable to load the add_sub example shown [here](https://github.com/triton-inference-server/python_backend/tree/main/examples/add_sub) . It fails with the following error:
```
I0622 21:02:46.540096 1 python.cc:1549] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0622 21:02:46.540137 1 python.cc:1468] TRITONBACKEND_ModelFinalize: delete model state
I0622 21:02:46.540155 1 triton_backend_manager.cc:101] unloading backend 'python'
I0622 21:02:46.540162 1 python.cc:1425] TRITONBACKEND_Finalize: Start
I0622 21:02:46.540263 1 python.cc:1430] TRITONBACKEND_Finalize: End
E0622 21:02:46.541164 1 model_repository_manager.cc:1215] failed to load 'add_sub' version 1: Internal: Unable to initialize shared memory key '/add_sub_0_CPU_0' to requested size (67108864 bytes). If you are running Triton inside docker, use '--shm-size' flag to control the shared memory region size. Each Python backend model instance requires at least 64MBs of shared memory. Flag '--shm-size=5G' should be sufficient for common usecases. Error: File exists
I0622 21:02:46.541176 1 model_repository_manager.cc:988] TriggerNextAction() 'add_sub' version 1: 0
```
Not quite sure what `Error: File exists` means here. This error was not happening on a previous version of triton (2.8.0)

**Triton Information**
What version of Triton are you using?
2.11.0dev

Are you using the Triton container or did you build it yourself?
built container from main
**To Reproduce**
Start Triton with the add_sub model in the repository

**Expected behavior**
Triton should startup without any errors

Has anything changed in recent versions to cause this behavior?

**Comment by Tabrizian** [comment]
Starting from 21.04 release Python backend uses shared memory for faster communication between Python code and Triton core. Did you try the suggestion in the error message?

**Comment by nsiddharth** [comment]
We currently do not have a way to set this in our kubernetes deployment. Can we be certain that this is indeed caused by the shared memory change?

**Comment by Tabrizian** [comment]
I tried it locally and verified that this is indeed the issue. You need to have enough shared memory when starting the Python backend beginning from 21.04 release onward.

**Comment by Tabrizian** [comment]
Closing the issue. Feel free to re-open if you are still facing this problem.

**Comment by nsiddharth** [comment]
This is fine to close but when I tried building with a python version earlier than 21.04 the build fails with very terse error message. I can confirm that this works when building with main so something has changed in how it is supposed to be built? 
```
[ 49%] Linking CXX static library libprotoc.a
cd /tmp/tritonbuild/python/build/_deps/grpc-build/third_party/protobuf && /usr/bin/cmake -P CMakeFiles/libprotoc.dir/cmake_clean_target.cmake
cd /tmp/tritonbuild/python/build/_deps/grpc-build/third_party/protobuf && /usr/bin/cmake -E cmake_link_script CMakeFiles/libprotoc.dir/link.txt --verbose=0
make[2]: Leaving directory '/tmp/tritonbuild/python/build'
[ 49%] Built target libprotoc
make[1]: Leaving directory '/tmp/tritonbuild/python/build'
make: *** [Makefile:149: all] Error 2
```
Can you provide any guidance on how to build it with an older version for the python backend. I am currently running it like so:
```
/build.py --build-dir=/tmp/citritonbuild --enable-logging --enable-stats --enable-tracing --enable-metrics --enable-gpu-metrics --enable-gpu --filesystem=gcs --filesystem=azure_storage --filesystem=s3 --endpoint=http --endpoint=grpc --repo-tag=common:main --repo-tag=core:main --repo-tag=backend:main  --backend=ensemble --backend=tensorrt --backend=identity --backend=repeat --backend=square --backend=python:r21.03 --backend=onnxruntime:r21.04 --backend=pytorch --backend=tensorflow1 --backend=tensorflow2  --repoagent=checksum
```
from the error message it is clear that the error is being thrown when building the python backend but it is not clear what exactly is the problem. if the tag is changed to main, it works fine and builds successfully.

**Comment by Tabrizian** [comment]
Can you try building Python backend from the 21.03 branch independent of other backends using the instructions provided [here](https://github.com/triton-inference-server/python_backend/tree/r21.03#building-from-source)? Are you using the 21.03 build.py?

**Comment by nsiddharth** [comment]
I don't think I am using the 21.03 build.py. I thought you could use the latest build.py(from main) and have it build older versions by providing the version to build like I had pasted in the earlier comment. Ideally, I want to build the entire image with all backends so I can push it to our repository. If I build the python backend independently, can I have it be part of the final tritonserver image? if so, how would I do this? Will try buliding it independently like you suggest but I think it would be useful to build different versions using the latest build.py which seems to be the purpose of having that ability.

**Comment by Tabrizian** [comment]
If there is not a dependency change between the version of the backend that you want to compile and the version of build.py that you are using, you should be fine. However, for your specific situation there were some dependency changes and that is likely the reason why you are seeing that error. An alternative approach would be to compile the Python backend separately using the instructions I posted above and copy the `/opt/tritonserver/backends/python` folder into your container.

**Comment by nsiddharth** [comment]
I have tried a variety of things and none of them have worked. I'll mention the most important one here. 
We tried increasing the shared memory by adding this config to our kubernetes setup mentioned on [StackOverflow](https://stackoverflow.com/questions/43373463/how-to-increase-shm-size-of-a-kubernetes-container-shm-size-equivalent-of-doc/47921100#47921100).
This however, does not help as the python model that was loading fine in earlier versions(20.11), does not seem to load. It also does not throw any helpful error message describing what the issue might be. Here are verbose logs from triton.
```
I0628 16:09:16.580354 1 python.cc:1489] TRITONBACKEND_ModelInstanceInitialize: tokenize_0 (CPU device 0)
I0628 16:09:16.580369 1 backend_model_instance.cc:68] Creating instance tokenize_0 on CPU using artifact ''
I0628 16:09:16.581432 1 model_repository_manager.cc:1105] CreateInferenceBackend() 'add_sub' version 1
I0628 16:09:16.586164 25 python.cc:918] Starting Python backend stub: exec /opt/tritonserver/backends/python/triton_python_backend_stub /tmp/foldernvoPPf/1/model.py /tokenize_0_CPU_0 67108864 67108864 1 /opt/tritonserver/backends/python
2021-06-28 16:09:17.300643: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
I0628 16:09:17.601293 1 python.cc:1549] TRITONBACKEND_ModelInstanceFinalize: delete instance state
```
It seems like that the model files are being created fine locally but triton never proceeds from here to start the liveness and readiness probes..
```
 kctl a -n triton-staging exec -it nsiddharth-playground-20210628-154843-9a0e5cc493-4wl8h -c triton -- ls -la /dev/shm/
total 131072
drwxrwsrwt 2 root 1337       80 Jun 28 16:22 .
drwxr-xr-x 5 root root      360 Jun 28 16:22 ..
-rw-r--r-- 1 root 1337 67108864 Jun 28 16:22 add_sub_0_CPU_0
-rw-r--r-- 1 root 1337 67108864 Jun 28 16:22 tokenize_0_CPU_0
```
It is also not clear why it is allocating only 64MB when a lot more shared memory is available. Triton seems to be stuck starting the python backend stub in and endless loop. A more helpful error message would be nice. Triton should probably error out instead of just gettin stuck in this state. Any advice?

**Comment by Tabrizian** [comment]
@nsiddharth

> It is also not clear why it is allocating only 64MB when a lot more shared memory is available. Triton seems to be stuck starting the python backend stub in and endless loop.

Are you running multiple instances of Triton server on the same node? You can configure the amount of shared memory used by default using the backend config fields: https://github.com/triton-inference-server/python_backend#managing-shared-memory

But you shouldn't need to worry about that as long as you have enough shared memory available.

> any helpful error message describing what the issue might be.

I have a fix inflight to fix the error message printing but in this case it looks like you still have some shared memory issues. Can you try running only a single model? Does that work properly?
