### ISSUE TITLE
How to find out the number of unprocessed requests for an inference?

### ISSUE THREAD

**Issue by guskovd** [triton-inference-server/server#3038]
I am interested in the ability to receive information about the length of the queue for the inference, so that the client can imagine how long it will take for him to wait until the request is processed.

I was able to find the `ModelStatisticsRequest` method.
But it seems that it only gives information about completed inferences.

**Comment by Tabrizian** [comment]
> so that the client can imagine how long it will take for him to wait until the request is processed.

It is not possible to get the estimate on how long your request will take while the inference is being made. However, you can use [perf_analyzer](https://github.com/triton-inference-server/server/blob/r21.05/docs/perf_analyzer.md) to find the average queuing time of your request offline. Perf analyzer includes the breakdown of your latency including the queuing time for the request.

**Comment by guskovd** [comment]
> It is not possible to get the estimate on how long your request will take while the inference is being made. However, you can use [perf_analyzer](https://github.com/triton-inference-server/server/blob/r21.05/docs/perf_analyzer.md) to find the average queuing time of your request offline. Perf analyzer includes the breakdown of your latency including the queuing time for the request.
I understand it. But is there any way to find out how many inferences are in the queue at the current time?

**Comment by Tabrizian** [comment]
You can get the cumulative queue waiting time of your requests using [Triton Metrics API](https://github.com/triton-inference-server/server/blob/main/docs/metrics.md). You can use this API to find the average amount of time your requests spend in the queue. However, I don't think it is possible to get the current number of requests that are currently in the queue. 

@deadeyegoodwin / @CoderHam Feel free to correct me if I'm wrong here.

**Comment by CoderHam** [comment]
You are right @Tabrizian, we will need to enhance the API to expose the number of queued (unprocessed) requests for an inference.

**Comment by CoderHam** [comment]
@guskovd one workaround could be to utilize the number of executions performed (exposed by model metrics) and keep track of the number of requests sent for inference (on your client side) to be able to get the number of unprocessed requests.

**Comment by guskovd** [comment]
> @guskovd one workaround could be to utilize the number of executions performed (exposed by model metrics) and keep track of the number of requests sent for inference (on your client side) to be able to get the number of unprocessed requests.

Thank you. Yes, I decided to stay on this option for now.

But for many reasons this is not a very correct approach ... I would very much like the `tritonserver` to be able to count the number of received, but unprocessed requests for inference

**Comment by cooperlab** [comment]
I ran into this issue as well. It's fundamental information that should be available to clients.

> @guskovd one workaround could be to utilize the number of executions performed (exposed by model metrics) and keep track of the number of requests sent for inference (on your client side) to be able to get the number of unprocessed requests.

There could be other processes submitting requests to the same model which your process can't track. We have a scenario where we need to re-load a model but want to check first that this model doesn't have pending requests.

**Comment by dyastremsky** [comment]
This is now available via the metrics endpoint: https://github.com/triton-inference-server/server/blob/main/docs/user_guide/metrics.md#inference-request-metrics. You can see the PR for more information as well: https://github.com/triton-inference-server/core/pull/246.
