### ISSUE TITLE
.proto files deleted in src/core/ directory

### ISSUE THREAD

**Issue by rxdcxdrnine** [triton-inference-server/server#3043]
**Description**

I have plan to use gRPC client in java and take steps with README.md in <https://github.com/triton-inference-server/client/tree/main/src/java>

However there were no .proto files in src/core/ in master branch.
Only branches past r20.12 have .proto files in src/core.
Is there a reason for deleting files?

**Triton Information**
What version of Triton are you using?
r21.05

Are you using the Triton container or did you build it yourself?
triton container

**To Reproduce**
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**

**Comment by Tabrizian** [comment]
The protobuf files have been moved to the common repo. https://github.com/triton-inference-server/common/tree/r21.05/protobuf

I have created a PR to update this on the Java client guide.

**Comment by Tabrizian** [comment]
Feel free to re-open the ticket if you are facing any additional issues.
