### ISSUE TITLE
pytorch_backend build fails with `cannot find -ltorch`

### ISSUE THREAD

**Issue by GowthamKudupudi** [triton-inference-server/server#3058]
**Description**
I'm building the Triton server with
`./build.py --no-container-build --target-platform ubuntu --cmake-dir=$(pwd)/build --build-dir=`pwd`/citritonbuild --enable-logging --enable-stats --enable-tracing --enable-metrics --enable-gpu-metrics --enable-gpu --filesystem=gcs --filesystem=azure_storage --filesystem=s3 --endpoint=http --endpoint=grpc --repo-tag=common:r21.05 --repo-tag=core:r21.05 --repo-tag=backend:r21.05 --repo-tag=thirdparty:r21.05 --backend=ensemble --backend=tensorrt --backend=python --backend=tensorflow1 --backend=tensorflow2 --backend=pytorch --repoagent=checksum --image tensorflow1,nvcr.io/nvidia/tensorflow:21.05-tf1-py3 --image tensorflow2,nvcr.io/nvidia/tensorflow:21.05-tf2-py3 --image pytorch,nvcr.io/nvidia/pytorch:21.05-py3
`

### it fails with
```
[  9%] Built target kernel-library-new
[ 13%] Built target ptlib_target
[ 27%] Built target triton-common-async-work-queue
[ 36%] Built target triton-core-serverstub
[ 68%] Built target triton-backend-utils
[ 72%] Linking CXX shared library libtriton_pytorch.so
/usr/bin/ld: cannot find -ltorch
/usr/bin/ld: cannot find -ltorchvision
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/triton-pytorch-backend.dir/build.make:121: libtriton_pytorch.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:173: CMakeFiles/triton-pytorch-backend.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```
I notice the `libtorch.so` and `libtorchvision.so` present in the build folder.

**Triton Information**
What version of Triton are you using?
r21.05

Are you using the Triton container or did you build it yourself?
I'm building it myself

**Comment by CoderHam** [comment]
pytorch backend picks up libtorch.so, libtorchvision.so and other deps from the pytorch NGC container. Which build folder are you referring to?
Can you confirm that the build logs 
"Extracting pytorch and torchvision libraries and includes from <pytorch docker image>"
And that it pulls the docker image as well?

**Comment by GowthamKudupudi** [comment]
I'm referring to the build folder `citritonbuild/pytorch/build`. I don't see the `Extracting pytorch and torchvision libraries and includes from ` in the build log. Below is the complete build log:
```
gowtham@t-trt-ubuntu:~/server/citritonbuild/pytorch/build$ make clean
gowtham@t-trt-ubuntu:~/server/citritonbuild/pytorch/build$ make
[  4%] Building NVCC (Device) object _deps/repo-backend-build/CMakeFiles/kernel-library-new.dir/src/kernel-library-new_generated_kernel.cu.o
[  9%] Linking CXX static library libkernel-library-new.a
[  9%] Built target kernel-library-new
[ 13%] Extracting pytorch and torchvision libraries and includes from nvcr.io/nvidia/pytorch:21.05-py3
21.05-py3: Pulling from nvidia/pytorch
Digest: sha256:a5986639e4cf01eb35c0c0a9ca9fb9c6f905cc1b546966b78de4f69d15b894cf
Status: Image is up to date for nvcr.io/nvidia/pytorch:21.05-py3
nvcr.io/nvidia/pytorch:21.05-py3
Error: No such container: pytorch_backend_ptlib
error ignored...
bcf92ea4bbbd76853d665e06a3c401dc8319a04ae2db5ebb356aa0862629edec
pytorch_backend_ptlib
[ 13%] Built target ptlib_target
[ 18%] Building CXX object _deps/repo-common-build/CMakeFiles/triton-common-async-work-queue.dir/src/async_work_queue.cc.o
[ 22%] Building CXX object _deps/repo-common-build/CMakeFiles/triton-common-async-work-queue.dir/src/error.cc.o
[ 27%] Linking CXX static library libtritonasyncworkqueue.a
[ 27%] Built target triton-common-async-work-queue
[ 31%] Building CXX object _deps/repo-core-build/CMakeFiles/triton-core-serverstub.dir/src/tritonserver_stub.cc.o
[ 36%] Linking CXX shared library libtritonserver_stub.so
[ 36%] Built target triton-core-serverstub
[ 40%] Building CXX object _deps/repo-backend-build/CMakeFiles/triton-backend-utils.dir/src/backend_common.cc.o
[ 45%] Building CXX object _deps/repo-backend-build/CMakeFiles/triton-backend-utils.dir/src/backend_input_collector.cc.o
[ 50%] Building CXX object _deps/repo-backend-build/CMakeFiles/triton-backend-utils.dir/src/backend_memory.cc.o
[ 54%] Building CXX object _deps/repo-backend-build/CMakeFiles/triton-backend-utils.dir/src/backend_model_instance.cc.o
[ 59%] Building CXX object _deps/repo-backend-build/CMakeFiles/triton-backend-utils.dir/src/backend_model.cc.o
[ 63%] Building CXX object _deps/repo-backend-build/CMakeFiles/triton-backend-utils.dir/src/backend_output_responder.cc.o
[ 68%] Linking CXX static library libtritonbackendutils.a
[ 68%] Built target triton-backend-utils
[ 72%] Building CXX object CMakeFiles/triton-pytorch-backend.dir/src/libtorch.cc.o
In file included from /home/gowtham/server/citritonbuild/pytorch/src/libtorch.cc:43:
/home/gowtham/server/citritonbuild/pytorch/build/include/torchvision/torchvision/vision.h:10:40: warning: ‘_register_ops’ initialized and declared ‘extern’
   10 | extern "C" VISION_INLINE_VARIABLE auto _register_ops = &cuda_version;
      |                                        ^~~~~~~~~~~~~
[ 77%] Building CXX object CMakeFiles/triton-pytorch-backend.dir/src/libtorch_utils.cc.o
[ 81%] Linking CXX shared library libtriton_pytorch.so
/usr/bin/ld: cannot find -ltorch
/usr/bin/ld: cannot find -ltorchvision
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/triton-pytorch-backend.dir/build.make:121: libtriton_pytorch.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:173: CMakeFiles/triton-pytorch-backend.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by hit-lance** [comment]
> I'm referring to the build folder `citritonbuild/pytorch/build`. I don't see the `Extracting pytorch and torchvision libraries and includes from ` in the build log. Below is the complete build log:
> 
> ```
> gowtham@t-trt-ubuntu:~/server/citritonbuild/pytorch/build$ make clean
> gowtham@t-trt-ubuntu:~/server/citritonbuild/pytorch/build$ make
> [  4%] Building NVCC (Device) object _deps/repo-backend-build/CMakeFiles/kernel-library-new.dir/src/kernel-library-new_generated_kernel.cu.o
> [  9%] Linking CXX static library libkernel-library-new.a
> [  9%] Built target kernel-library-new
> [ 13%] Extracting pytorch and torchvision libraries and includes from nvcr.io/nvidia/pytorch:21.05-py3
> 21.05-py3: Pulling from nvidia/pytorch
> Digest: sha256:a5986639e4cf01eb35c0c0a9ca9fb9c6f905cc1b546966b78de4f69d15b894cf
> Status: Image is up to date for nvcr.io/nvidia/pytorch:21.05-py3
> nvcr.io/nvidia/pytorch:21.05-py3
> Error: No such container: pytorch_backend_ptlib
> error ignored...
> bcf92ea4bbbd76853d665e06a3c401dc8319a04ae2db5ebb356aa0862629edec
> pytorch_backend_ptlib
> [ 13%] Built target ptlib_target
> [ 18%] Building CXX object _deps/repo-common-build/CMakeFiles/triton-common-async-work-queue.dir/src/async_work_queue.cc.o
> [ 22%] Building CXX object _deps/repo-common-build/CMakeFiles/triton-common-async-work-queue.dir/src/error.cc.o
> [ 27%] Linking CXX static library libtritonasyncworkqueue.a
> [ 27%] Built target triton-common-async-work-queue
> [ 31%] Building CXX object _deps/repo-core-build/CMakeFiles/triton-core-serverstub.dir/src/tritonserver_stub.cc.o
> [ 36%] Linking CXX shared library libtritonserver_stub.so
> [ 36%] Built target triton-core-serverstub
> [ 40%] Building CXX object _deps/repo-backend-build/CMakeFiles/triton-backend-utils.dir/src/backend_common.cc.o
> [ 45%] Building CXX object _deps/repo-backend-build/CMakeFiles/triton-backend-utils.dir/src/backend_input_collector.cc.o
> [ 50%] Building CXX object _deps/repo-backend-build/CMakeFiles/triton-backend-utils.dir/src/backend_memory.cc.o
> [ 54%] Building CXX object _deps/repo-backend-build/CMakeFiles/triton-backend-utils.dir/src/backend_model_instance.cc.o
> [ 59%] Building CXX object _deps/repo-backend-build/CMakeFiles/triton-backend-utils.dir/src/backend_model.cc.o
> [ 63%] Building CXX object _deps/repo-backend-build/CMakeFiles/triton-backend-utils.dir/src/backend_output_responder.cc.o
> [ 68%] Linking CXX static library libtritonbackendutils.a
> [ 68%] Built target triton-backend-utils
> [ 72%] Building CXX object CMakeFiles/triton-pytorch-backend.dir/src/libtorch.cc.o
> In file included from /home/gowtham/server/citritonbuild/pytorch/src/libtorch.cc:43:
> /home/gowtham/server/citritonbuild/pytorch/build/include/torchvision/torchvision/vision.h:10:40: warning: ‘_register_ops’ initialized and declared ‘extern’
>    10 | extern "C" VISION_INLINE_VARIABLE auto _register_ops = &cuda_version;
>       |                                        ^~~~~~~~~~~~~
> [ 77%] Building CXX object CMakeFiles/triton-pytorch-backend.dir/src/libtorch_utils.cc.o
> [ 81%] Linking CXX shared library libtriton_pytorch.so
> /usr/bin/ld: cannot find -ltorch
> /usr/bin/ld: cannot find -ltorchvision
> collect2: error: ld returned 1 exit status
> make[2]: *** [CMakeFiles/triton-pytorch-backend.dir/build.make:121: libtriton_pytorch.so] Error 1
> make[1]: *** [CMakeFiles/Makefile2:173: CMakeFiles/triton-pytorch-backend.dir/all] Error 2
> make: *** [Makefile:136: all] Error 2
> ```

I encountered the same problem..

**Comment by CoderHam** [comment]
@GowthamKudupudi @hit-lance which version of Torchvision / PyTorch are you using for this custom build?

**Comment by GowthamKudupudi** [comment]
@CoderHam I'm sorry, I didn't notice the `Extracting pytorch and torchvision libraries and includes from ` right in the build log. I have update my comment above.

**Comment by GowthamKudupudi** [comment]
I fixed the issue by replacing `-ltorch` and `-ltorchvision` with `${CMAKE_CURRENT_BINARY_DIR}/libtorch.so` and `${CMAKE_CURRENT_BINARY_DIR}/libtorchvision.so` in `CMakeLists.txt`
