### ISSUE TITLE
Client library / triton server / config.pbtxt data_type naming convention missmatch

### ISSUE THREAD

**Issue by casperroo** [triton-inference-server/server#3061]
I am using the newest client libraries (C++) from main branch (https://github.com/triton-inference-server/client.git)
I am using the triton server as docker container (nvcr.io/nvidia/tritonserver:21.05-py3)
I have a working model (MobileNet) with the input defined in the config.pbtxt as follows:
```
input [
  {
    name: "keras_layer_input"
    data_type: TYPE_FP32
    format: FORMAT_NHWC
    dims: [ 224, 224, 3 ]
  }
]
```
In my client app I query the model using GRPC:
```
triton::client::Error err;
inference::ModelConfigResponse model;
err = m_ctx->ModelConfig(&model, modelName());
...
```
and store the input type (as enum and as string):
```
const auto& input = model.config().input(0);
m_inputFormat = input.format();
m_inputName = input.name();
m_inputDataType = input.data_type();
m_inputDataTypeName = inference::DataType_Name(m_inputDataType);
```
The ```m_inputDataType``` is correctly read as ```DataType::TYPE_FP32```
and the ```std::string``` variable ``` m_inputDataTypeName``` holds ```"TYPE_FP32"```  (as expected).

Unfortunately when I create an input like this (the ```m_inputShape``` initialization is omitted here as it is irrelevant):
```
triton::client::Error err;
triton::client::InferInput *input;
err = triton::client::InferInput::Create(&input, m_inputName, m_inputShape, m_inputDataTypeName);
```
I get an error response from the triton inference server saying:
```inference input data-type is '<invalid>', model expects 'FP32' for '<my model name>'```

Initializing the input with fixed "FP32":
```err = triton::client::InferInput::Create(&input, m_inputName, m_inputShape, "FP32");```
works as expected.

So it looks like the inference::DataType enum names are consistent with inference::DataType_Name (obviously) and this is also consistent withe the pbtxt file (this is all part of a protobuf). Unfortunately it seems that the inference server itself has some other text<->data_type parser/converter on the grpc part (on the config part it seems working well: it reads the config.pbtxt and understands the "TYPE_FP32").

The client API lacks the ```triton::client::InferInput::Create``` overload that takes the ```inference::DataType``` enum as an argument. It looks like the only way around it is to make some assumes function that drops the "TYPE_" prefix from the said enum names. But is it actually correct for all the types available?

Or is there some other method that does exactly that but I have simply missed it?

**Comment by jbkyang-nvi** [comment]
Hi! Thanks for the question and apologies for the late response.
Is there a reason you are using the `ModelConfig` and not `ModelMetadata`? You can find the metadata [here](https://github.com/triton-inference-server/client/blob/main/src/c%2B%2B/library/grpc_client.h). The metadata will contain the correct protocol you need for for creating infer inputs.

**Comment by casperroo** [comment]
Hi. Thanks for the feedback. I have used the ModelConfig as I was porting from the old client library which was created based on old examples (by old I mean before the project's name was changed into tritonserver). I can see now in the examples that both model's config and metatdata are used to parse the model over GRPC. Sorry for bothering you.

**Comment by jbkyang-nvi** [comment]
@casperroo no bother at all. Glad that fixed it!
