### ISSUE TITLE
Increasing number of instances of the model does not increase performance

### ISSUE THREAD

**Issue by dhirajpatnaik16297** [triton-inference-server/server#3066]
Hi 
I have an onnx model (single batch) of yolov5(medium) and i am trying to use it to serve multiple clients. I have tried to increase number of instances in the config file but it does not help much. My perf_analyzer throughput does not improve. 
I am wondering where i am going wrong.
I also have certain questions like : 
Can a single model handle lets say 30 clients without compromising on the FPS and accuracy? 
If so what changes should i do with the current model?
Thanks

**Comment by jbkyang-nvi** [comment]
Hi, what concurrency are you running at with the perf_analyzer?

**Comment by dhirajpatnaik16297** [comment]
Following are the outputs of the perf_analyzer::
Here yolov5 and yolov5_1 are 2 separate folders having the same medium model model.

####  Running yolov5 and yolov5_1 individually:::

** perf_analyzer -m yolov5 --percentile=95 --concurrency-range 1:4
*** Measurement Settings ***
  Batch size: 1
  Measurement window: 5000 msec
  Latency limit: 0 msec
  Concurrency limit: 4 concurrent requests
  Using synchronous calls for inference
  Stabilizing using p95 latency
....
....
Inferences/Second vs. Client p95 Batch Latency
Concurrency: 1, throughput: 43.6 infer/sec, latency 24359 usec
Concurrency: 2, throughput: 62.6 infer/sec, latency 33098 usec
Concurrency: 3, throughput: 62 infer/sec, latency 49435 usec
Concurrency: 4, throughput: 63.8 infer/sec, latency 63873 usec

------------------------------------------------------------------------
** perf_analyzer -m yolov5_1 --percentile=95 --concurrency-range 1:4
*** Measurement Settings ***
  Batch size: 1
  Measurement window: 5000 msec
  Latency limit: 0 msec
  Concurrency limit: 4 concurrent requests
  Using synchronous calls for inference
  Stabilizing using p95 latency
...
...
Inferences/Second vs. Client p95 Batch Latency
Concurrency: 1, throughput: 43 infer/sec, latency 25009 usec
Concurrency: 2, throughput: 62.8 infer/sec, latency 32599 usec
Concurrency: 3, throughput: 62.8 infer/sec, latency 48877 usec
Concurrency: 4, throughput: 62.2 infer/sec, latency 65342 usec

------------------------------------------------------------------------

#### running yolov5 and yolov5_1 almost simultaneously (ran yolov5_1 first and then yolov5 after 2-3 seconds)::

perf_analyzer -m yolov5_1 --percentile=95 --concurrency-range 1:4
*** Measurement Settings ***
  Batch size: 1
  Measurement window: 5000 msec
  Latency limit: 0 msec
  Concurrency limit: 4 concurrent requests
  Using synchronous calls for inference
  Stabilizing using p95 latency
...
...
Inferences/Second vs. Client p95 Batch Latency
Concurrency: 1, throughput: 20.6 infer/sec, latency 71422 usec
Concurrency: 2, throughput: 28.8 infer/sec, latency 91769 usec
Concurrency: 3, throughput: 30.2 infer/sec, latency 135551 usec
Concurrency: 4, throughput: 61.8 infer/sec, latency 65801 usec
-------------------------------------------------------------------------
perf_analyzer -m yolov5 --percentile=95 --concurrency-range 1:4
*** Measurement Settings ***
  Batch size: 1
  Measurement window: 5000 msec
  Latency limit: 0 msec
  Concurrency limit: 4 concurrent requests
  Using synchronous calls for inference
  Stabilizing using p95 latency
...
...
Inferences/Second vs. Client p95 Batch Latency
Concurrency: 1, throughput: 33.2 infer/sec, latency 31199 usec
Concurrency: 2, throughput: 44.4 infer/sec, latency 59752 usec
Concurrency: 3, throughput: 37 infer/sec, latency 105378 usec
Concurrency: 4, throughput: 36.8 infer/sec, latency 140257 usec


I have gone through a forum blog where millions of requests are processed by a BERT model which is way more complex than this model.  Please let me know how to achieve that kind of throughput with accuracy and fps intact.

**Comment by CoderHam** [comment]
@dhirajpatnaik16297 you are running 2 models instead of one model with 2 instances. You can do this using count: 2 in the instance_group in the model config.pbtxt

Running 2 instances of perf_analyzer is not stable since there will be interference that effects the stabilization. Hence the numbers will be incorrectly reported.

**Comment by dhirajpatnaik16297** [comment]
## instance count =1 
perf_analyzer -m yolov5 --concurrency-range 1:4 
*** Measurement Settings ***
  Batch size: 1
  Measurement window: 5000 msec
  Latency limit: 0 msec
  Concurrency limit: 4 concurrent requests
  Using synchronous calls for inference
  Stabilizing using average latency
...
...
Inferences/Second vs. Client Average Batch Latency
Concurrency: 1, throughput: 45.2 infer/sec, latency 22052 usec
Concurrency: 2, throughput: 64.4 infer/sec, latency 31044 usec
Concurrency: 3, throughput: 63.8 infer/sec, latency 46948 usec
Concurrency: 4, throughput: 63.2 infer/sec, latency 63170 usec
 

## instance count =2
perf_analyzer -m yolov5 --concurrency-range 1:4 
*** Measurement Settings ***
  Batch size: 1
  Measurement window: 5000 msec
  Latency limit: 0 msec
  Concurrency limit: 4 concurrent requests
  Using synchronous calls for inference
  Stabilizing using average latency
...
...
Inferences/Second vs. Client Average Batch Latency
Concurrency: 1, throughput: 44.6 infer/sec, latency 22412 usec
Concurrency: 2, throughput: 66.2 infer/sec, latency 30242 usec
Concurrency: 3, throughput: 67.2 infer/sec, latency 44708 usec
Concurrency: 4, throughput: 67.2 infer/sec, latency 59509 usec

## instance count =3
 perf_analyzer -m yolov5 --concurrency-range 1:4 
*** Measurement Settings ***
  Batch size: 1
  Measurement window: 5000 msec
  Latency limit: 0 msec
  Concurrency limit: 4 concurrent requests
  Using synchronous calls for inference
  Stabilizing using average latency
...
...
Inferences/Second vs. Client Average Batch Latency
Concurrency: 1, throughput: 45.2 infer/sec, latency 22154 usec
Concurrency: 2, throughput: 67 infer/sec, latency 29863 usec
Concurrency: 3, throughput: 66 infer/sec, latency 45531 usec
Concurrency: 4, throughput: 66.8 infer/sec, latency 59906 usec

## instance count =4
 perf_analyzer -m yolov5 --concurrency-range 1:4 
*** Measurement Settings ***
  Batch size: 1
  Measurement window: 5000 msec
  Latency limit: 0 msec
  Concurrency limit: 4 concurrent requests
  Using synchronous calls for inference
  Stabilizing using average latency
...
...
Inferences/Second vs. Client Average Batch Latency
Concurrency: 1, throughput: 45.2 infer/sec, latency 22075 usec
Concurrency: 2, throughput: 65 infer/sec, latency 30780 usec
Concurrency: 3, throughput: 64.6 infer/sec, latency 46578 usec
Concurrency: 4, throughput: 64.4 infer/sec, latency 62555 usec


Even by increasing instance counts the performance remains almost the same.

**Comment by dhirajpatnaik16297** [comment]
## Update::
I have tried out the same with the available models  densenet_onnx and inception_graphdef. I cannot see very significant performance improvement upon increasing the instance number here too contradicting to what i have seen in docs.

** for densenet_onnx
 instance count=1
 perf_analyzer -m densenet_onnx --concurrency-range 1:4     

Inferences/Second vs. Client Average Batch Latency
Concurrency: 1, throughput: 121.2 infer/sec, latency 8257 usec
Concurrency: 2, throughput: 127.6 infer/sec, latency 15673 usec
Concurrency: 3, throughput: 129.4 infer/sec, latency 23204 usec
Concurrency: 4, throughput: 129.6 infer/sec, latency 30836 usec

 instance count=2
 perf_analyzer -m densenet_onnx --concurrency-range 1:4 

Inferences/Second vs. Client Average Batch Latency
Concurrency: 1, throughput: 118.6 infer/sec, latency 8428 usec
Concurrency: 2, throughput: 151.8 infer/sec, latency 13175 usec
Concurrency: 3, throughput: 152.4 infer/sec, latency 19688 usec
Concurrency: 4, throughput: 149.6 infer/sec, latency 26753 usec

 instance count=3
perf_analyzer -m densenet_onnx --concurrency-range 1:4 

Inferences/Second vs. Client Average Batch Latency
Concurrency: 1, throughput: 121.6 infer/sec, latency 8227 usec
Concurrency: 2, throughput: 154.6 infer/sec, latency 12941 usec
Concurrency: 3, throughput: 165 infer/sec, latency 18175 usec
Concurrency: 4, throughput: 156.4 infer/sec, latency 25588 usec

 instance count=4
perf_analyzer -m densenet_onnx --concurrency-range 1:4 

Inferences/Second vs. Client Average Batch Latency
Concurrency: 1, throughput: 121.6 infer/sec, latency 8224 usec
Concurrency: 2, throughput: 149.4 infer/sec, latency 13386 usec
Concurrency: 3, throughput: 165 infer/sec, latency 18178 usec
Concurrency: 4, throughput: 156.6 infer/sec, latency 25519 usec


** for inception_graphdef
instance count=1
 perf_analyzer -m inception_graphdef --concurrency-range 1:8
Inferences/Second vs. Client Average Batch Latency
Concurrency: 1, throughput: 90.8 infer/sec, latency 11011 usec
Concurrency: 2, throughput: 103.8 infer/sec, latency 19228 usec
Concurrency: 3, throughput: 101.4 infer/sec, latency 29601 usec
Concurrency: 4, throughput: 119.6 infer/sec, latency 33419 usec
Concurrency: 5, throughput: 131 infer/sec, latency 38276 usec
Concurrency: 6, throughput: 140.2 infer/sec, latency 42681 usec
Concurrency: 7, throughput: 153.4 infer/sec, latency 45655 usec
Concurrency: 8, throughput: 159.2 infer/sec, latency 50297 usec

instance count=2
perf_analyzer -m inception_graphdef --concurrency-range 1:8
Inferences/Second vs. Client Average Batch Latency
Concurrency: 1, throughput: 91 infer/sec, latency 10994 usec
Concurrency: 2, throughput: 99.8 infer/sec, latency 20031 usec
Concurrency: 3, throughput: 127.2 infer/sec, latency 23551 usec
Concurrency: 4, throughput: 148 infer/sec, latency 27007 usec
Concurrency: 5, throughput: 161.6 infer/sec, latency 30958 usec
Concurrency: 6, throughput: 171 infer/sec, latency 34988 usec
Concurrency: 7, throughput: 180 infer/sec, latency 38778 usec
Concurrency: 8, throughput: 188 infer/sec, latency 42481 usec

instance count=3
perf_analyzer -m inception_graphdef --concurrency-range 1:8 
Inferences/Second vs. Client Average Batch Latency
Concurrency: 1, throughput: 90.8 infer/sec, latency 11005 usec
Concurrency: 2, throughput: 103.6 infer/sec, latency 19302 usec
Concurrency: 3, throughput: 101 infer/sec, latency 29766 usec
Concurrency: 4, throughput: 101 infer/sec, latency 39310 usec
Concurrency: 5, throughput: 103 infer/sec, latency 48588 usec
Concurrency: 6, throughput: 112.6 infer/sec, latency 53392 usec
Concurrency: 7, throughput: 120.8 infer/sec, latency 58056 usec
Concurrency: 8, throughput: 127.8 infer/sec, latency 62585 usec

**Comment by tanmayv25** [comment]
perf analyzer should report the detailed breakdown of the latency. Can you run PA with `-f <filename>.csv` and share them for instance counts 1,2 and 3 for any one of the models such as `inception_graphdef`?

**Comment by dyastremsky** [comment]
Closed due to inactivity. Please let us know if you need this issue reopened.

**Comment by simon5u** [comment]
Hi, i am facing the same issue where the yolo5s is very slow in triton even with multiple instances.
I downloaded the model from this link, https://github.com/ultralytics/yolov5/blob/master/export.py
Then, the model was converted from onnx to model.plan, input size is batchsize,3,640,640.
I am using this docker nvcr.io/nvidia/deepstream:5.1-21.02-triton with a 2080Ti GPU.
If I increased the batch to 4 or more than 4, the latency becomes very large, more than 100ms.
Is it a normal situation or something wrong with my config.pbtxt settings?

===
name: "yolo5"
platform: "tensorrt_plan"

max_batch_size: 16
dynamic_batching {
    preferred_batch_size: [ 1, 2, 4, 8, 10, 16 ]
    #max_queue_delay_microseconds: 10
}

instance_group [
  {
    count: 2
    kind: KIND_GPU
  }
]

input [
  {
    name: "input1"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 640, 640 ]
    reshape { shape: [ 3, 640, 640 ] }
  }
]
output [
  {
    name: "output1"
    data_type: TYPE_FP32
    dims: [ 25200, 85 ]
  },
  {
    name: "output2"
    data_type: TYPE_FP32
    dims: [ 3,80,80,85 ]

  },
  {
    name: "output3"
    data_type: TYPE_FP32
    dims: [ 3,40,40,85 ]
  },
  {
    name: "output4"
    data_type: TYPE_FP32
    dims: [ 3,20,20,85 ]
  }
]

=== using 1 instance ===
**perf_analyzer -m yolo5 --concurrency-range 1:4 -b 1 -f yolo5a.csv**
Concurrency: 1, throughput: 58 infer/sec, latency 17314 usec
Concurrency: 2, throughput: 90.2 infer/sec, latency 22177 usec
Concurrency: 3, throughput: 89.2 infer/sec, latency 33790 usec
Concurrency: 4, throughput: 94.6 infer/sec, latency 42339 usec
**perf_analyzer -m yolo5 --concurrency-range 1:4 -b 16 -f yolo5a16.csv**
Concurrency: 1, throughput: 57.6 infer/sec, latency 266690 usec
Concurrency: 2, throughput: 105.6 infer/sec, latency 301117 usec
Concurrency: 3, throughput: 115.2 infer/sec, latency 412961 usec
Concurrency: 4, throughput: 121.6 infer/sec, latency 521678 usec

=== using 2 instances ===
**perf_analyzer -m yolo5 --concurrency-range 1:4 -b 1 -f yolo5b.csv**
Concurrency: 1, throughput: 56.8 infer/sec, latency 17560 usec
Concurrency: 2, throughput: 80 infer/sec, latency 25016 usec
Concurrency: 3, throughput: 123.6 infer/sec, latency 24348 usec
Concurrency: 4, throughput: 130 infer/sec, latency 30830 usec

**perf_analyzer -m yolo5 --concurrency-range 1:4 -b 1 -f yolo5b16.csv**
Concurrency: 1, throughput: 60.8 infer/sec, latency 270396 usec
Concurrency: 2, throughput: 76.8 infer/sec, latency 424688 usec
Concurrency: 3, throughput: 80 infer/sec, latency 592924 usec
Concurrency: 4, throughput: 80 infer/sec, latency 760824 usec

Please advise on how to make the inference faster.

[yolo5a.csv](https://github.com/triton-inference-server/server/files/7084297/yolo5a.csv)
[yolo5a16.csv](https://github.com/triton-inference-server/server/files/7084298/yolo5a16.csv)
[yolo5b.csv](https://github.com/triton-inference-server/server/files/7084299/yolo5b.csv)
[yolo5b16.csv](https://github.com/triton-inference-server/server/files/7084300/yolo5b16.csv)

**Comment by simon5u** [comment]
> Closed due to inactivity. Please let us know if you need this issue reopened.



> Closed due to inactivity. Please let us know if you need this issue reopened.

Please reopen this issue. Thanks.

**Comment by GuanLuo** [comment]
@dhirajpatnaik16297 Please provide additional information in respect to @tanmayv25 's earlier comment, and then feel free to reopen the issue:
> perf analyzer should report the detailed breakdown of the latency. Can you run PA with -f <filename>.csv and share them for instance counts 1,2 and 3 for any one of the models such as inception_graphdef?

@simon5u Can you create a separate issue regarding your use case? It is hard to keep track of multiple scenarios in one issue.

**Comment by langong347** [comment]
Hi @GuanLuo  @tanmayv25  I am having a similar issue with YOLOv8 model where using 2 model instances only marginally improves throughput. Since the triton perf analyzer is not available to me, I am using `hey` to measure the latency/throughput before/after increasing the model instances and reading my resource utilization from a Graphana Dashboard.

- Two replicas, each contains a single T4 GPU
- Triton runtime version: runtimeVersion: 23.12
- config.pbtxt:
```
platform: "onnxruntime_onnx"
max_batch_size: 8
input [
  {
    name: "images"
    data_type: TYPE_FP32
    dims: [ 3, -1, -1 ]
  }
]
output [
  {
    name: "output0"
    data_type: TYPE_FP32
    dims: [ -1, -1 ]
  }
]
 dynamic_batching {
 	max_queue_delay_microseconds: 20000
 }
 instance_group [
   {
     count: 2
     kind: KIND_GPU
   }
 ]
```

1000 requests are sent at concurrency level  `c=1, 2, 5, 10, 20, 50`:

Model instance = 1
```
# c = 1
   Total:        11.3171 secs
   Slowest:      0.1655 secs
   Fastest:      0.1011 secs
   Average:      0.1132 secs
   Requests/sec: 8.8362

# c = 2
Total:        10.0818 secs
   Slowest:      0.2255 secs
   Fastest:      0.0830 secs
   Average:      0.1001 secs
   Requests/sec: 19.8377

# c = 5
 Total:        12.3119 secs
   Slowest:      0.2220 secs
   Fastest:      0.0810 secs
   Average:      0.1200 secs
   Requests/sec: 40.6112

# c = 10
 Total:        16.6449 secs
   Slowest:      0.3462 secs
   Fastest:      0.0844 secs
   Average:      0.1636 secs
   Requests/sec: 60.0786

# c = 20
 Total:        14.9312 secs
   Slowest:      0.5636 secs
   Fastest:      0.0869 secs
   Average:      0.2920 secs
   Requests/sec: 66.9737

# c = 50
 Total:        14.8280 secs
   Slowest:      1.1955 secs
   Fastest:      0.0930 secs
   Average:      0.7206 secs
   Requests/sec: 67.4398
```

Model instances = 2
```
c = 1
Total:        11.0247 secs
   Slowest:      0.1277 secs
   Fastest:      0.0989 secs
   Average:      0.1102 secs
   Requests/sec: 9.0705

c = 2
 Total:        10.8996 secs
   Slowest:      0.1914 secs
   Fastest:      0.0859 secs
   Average:      0.1087 secs
   Requests/sec: 18.3493

c = 5
 Total:        13.2817 secs
   Slowest:      0.2476 secs
   Fastest:      0.0814 secs
   Average:      0.1279 secs
   Requests/sec: 37.6459

c = 10
Total:        19.4423 secs
   Slowest:      0.5300 secs
   Fastest:      0.0837 secs
   Average:      0.1882 secs
   Requests/sec: 51.4342

c = 20
   Total:        15.9425 secs
   Slowest:      0.5783 secs
   Fastest:      0.0847 secs
   Average:      0.3078 secs
   Requests/sec: 62.7255

c = 50
   Total:        14.2107 secs
   Slowest:      1.1725 secs
   Fastest:      0.1462 secs
   Average:      0.6919 secs
   Requests/sec: 70.3695
```

I noticed that at higher concurrency levels my GPU core utilization could reach anywhere between 90 - 100%, which might have halved the performance of each model instance. I suspect enabling dynamic batching was sufficient to saturate GPU utilization making multi-instance execution unnecessary.....

Also, we may rule out issues due to GPU memory as running two instances only took 5 GB out of 16GB total for my GPU.

I want to know if my understanding is correct, and whether you have further insights into the proper usage of multi-instance execution.

Thank you.
