### ISSUE TITLE
How to add resnet50 model for qa tests

### ISSUE THREAD

**Issue by ottercute** [triton-inference-server/server#3069]
Hello, I am trying to run a test **L0_trt_dla** from r21.06 of triton server.
it is not clear how to get `trt_dla_model_store/resnet50_plan` in `/data/inferenceserver/21.06/` filepath.
I have followed steps in [this](https://github.com/triton-inference-server/server/blob/r21.06/docs/test.md#generate-qa-model-repositories) docs, but all generated model repositories names started with qa_*.

Also i found mention of resnet50 in **L0_perf_resnet** but in another folder named perf_model_store/ in REPODIR. I think this is the same model.

Could you please give more information about generation this resnet50_plan model?

**Comment by dzier** [comment]
After generating the models, you have to run the container and link in the files as indicated in the `-v` option used in the command line here: https://github.com/triton-inference-server/server/blob/main/docs/quickstart.md#run-on-system-with-gpus

If you run that command line correctly, you will see the generated models in the running docker container.

Closing issue, please re-open if you are still having issues.
