### ISSUE TITLE
backend build fails 

### ISSUE THREAD

**Issue by jimobuwu** [triton-inference-server/server#3070]
**Description**
I'm building the backend with

> $ mkdir build
$ cd build
$ cmake -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/install ..
$ make install
 
it fails with
> /usr/include/c++/5/bits/hashtable_policy.h:85:34: error: no match for call to ‘(const std::hash<triton::backend::BackendMemory::AllocationType>) (const triton::backend::BackendMemory::AllocationType&)’
  noexcept(declval<const _Hash&>()(declval<const _Key&>()))>
                                  ^
In file included from /usr/include/c++/5/bits/move.h:57:0,
                 from /usr/include/c++/5/bits/stl_pair.h:59,
                 from /usr/include/c++/5/bits/stl_algobase.h:64,
                 from /usr/include/c++/5/bits/char_traits.h:39,
                 from /usr/include/c++/5/string:40,
                 from /data/from_home/lilei/triton/backend/include/triton/backend/backend_memory.h:28,
                 from /data/from_home/lilei/triton/backend/src/backend_memory.cc:27:
/usr/include/c++/5/type_traits: In instantiation of ‘struct std::__not_<std::__and_<std::__is_fast_hash<std::hash<triton::backend::BackendMemory::AllocationType> >, std::__detail::__is_noexcept_hash<triton::backend::BackendMemory::AllocationType, std::hash<triton::backend::BackendMemory::AllocationType> > > >’:
/usr/include/c++/5/bits/unordered_map.h:100:66:   required from ‘class std::unordered_map<triton::backend::BackendMemory::AllocationType, TRITONSERVER_Error*>’
/data/from_home/lilei/triton/backend/src/backend_memory.cc:117:59:   required from here
/usr/include/c++/5/type_traits:148:38: error: ‘value’ is not a member of ‘std::__and_<std::__is_fast_hash<std::hash<triton::backend::BackendMemory::AllocationType> >, std::__detail::__is_noexcept_hash<triton::backend::BackendMemory::AllocationType, std::hash<triton::backend::BackendMemory::AllocationType> > >’
     : public integral_constant<bool, !_Pp::value>`

I comment the code below，It shows build success
`std::unordered_map<AllocationType, TRITONSERVER_Error*> errors;`

**Comment by jbkyang-nvi** [comment]
Hi @jimobuwu. Can you specify: which backend you are building and branch you are using? Better, can you specify your problem by following this bug report template? https://github.com/triton-inference-server/server/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by jimobuwu** [comment]
Hi @jbkyang-nvi 
I‘m building the example backend: identity_backend，using the latest code pulled from the main branch of the repository 
https://github.com/triton-inference-server/identity_backend

**Comment by jbkyang-nvi** [comment]
@jimobuwu I can build it locally no problem with my linux machine (new clone of current `main`  [here](https://github.com/triton-inference-server/identity_backend/commit/5ec0b1865024b8dc4e54b3ac105f1f6561e6c947)). Can you specify:
1. What OS are you using (windows/linux/?)
2. Specific hash you are using (btw, are you using the branch `main` or something else? It might be better to use a release branch (eg. [r21.06](https://github.com/triton-inference-server/identity_backend/tree/r21.06)).

**Comment by paulxjin** [comment]
AllocationType is a Nested class.  And it has been used in STL?
