### ISSUE TITLE
segfault at ... error 6 in libc-2.27.so

### ISSUE THREAD

**Issue by vBLFTePebWNi6c** [triton-inference-server/server#3073]
**Description**
Docker container crashes with segfault. 

**Triton Information**
I'm using Triton container `nvcr.io/nvidia/tritonserver:20.09-py3`

**To Reproduce**
Start Triton server with model with following configuration:
```
        name: 'Model'
        platform: 'tensorflow_savedmodel'
        input [
          {
            name: 'input_layer'
            data_type: TYPE_UINT8
            dims: [ -1, -1, -1, 3 ]
          }
        ]
        output [
          {
            name: 'tf_op_layer_Cast_1'
            data_type: TYPE_UINT8
            dims: [ -1, -1, -1, 3 ]
          }
        ]

        instance_group {
              kind: KIND_GPU
              count: 1
           }
```

Run two or more tasks constantly requesting inference using Triton client with cuda shared memory. One task may succeed, but another will cause segfault. 

**Expected behavior**
All tasks works correctly.

**Comment by jbkyang-nvi** [comment]
Hello! Is there a reason why you are using `20.09`?

**Comment by CoderHam** [comment]
@vBLFTePebWNi6c can you share the backtrace for the segfault?
Are you destroying a cuda shared memory region that is being used for inference?
We'd appreciate a detailed repro for the same so we can correctly identify the issue you are facing.

**Comment by vBLFTePebWNi6c** [comment]
@jbkyang-nvi 
I'll give a try `21.06` and come back later.
@CoderHam
[Here's](https://github.com/triton-inference-server/server/files/6752984/triton_8000.log) Triton Server log. 
Running tasks creates cuda shared memory regions and reuse them between inference requests, at the end script destroys created regions. Unfortunately I can't provide code and models to reproduce this bug due to NDA.

**Comment by tanmayv25** [comment]
@vBLFTePebWNi6c  Did 21.06 container resolve the issue?

**Comment by vBLFTePebWNi6c** [comment]
@tanmayv25 I didn't try 21.06 container. I solved this issue with changing type of shared memory from cuda to system and explicitly loading all my models from largest to smallest before the script. I can assume that problem was in memory allocation for models or shared memory regions because total GPU memory that each model takes when loaded separately is larger than all available GPU memory, but if I load them from largest to smallest there is not such problem and all models utilizes GPU memory well.

**Comment by tanmayv25** [comment]
Glad it worked for you. If you see similar issues with our recent releases or have general suggestions on how to handle such cases better in triton, feel free to open another GitHub issue.
