### ISSUE TITLE
Question about tensorflow backend (savedmodel)

### ISSUE THREAD

**Issue by scamianbas** [triton-inference-server/server#3080]
Hello there,
does the tensorflow backend (savedmodel) support Generic Dicts ?
I'm asking because savedmodel returns only dictionaries ... AFAIK
Thanks.

**Comment by dzier** [comment]
I don't think I have enough context to understand your use case. Tirton uses wrapped tensorflow::Tensor to send data to TF session. That's the only way to communicate with the session.

Triton uses tensorflow::LoadSavedModel to load it into tensorflow::SavedModelBundle,  Then extract session out of it, For more details like the options exposed, please refer to this function https://github.com/triton-inference-server/tensorflow_backend/blob/main/src/tensorflow_backend_tf.cc#L902

**Comment by tanmayv25** [comment]
Closing because of the inactivity. Please feel free to open a new issue if you have any more questions.
