### ISSUE TITLE
Versioning of other repositories

### ISSUE THREAD

**Issue by kpedro88** [triton-inference-server/server#3083]
**Is your feature request related to a problem? Please describe.**
Now that the main `server` repository has been refactored into others (`client`, `backend`, etc.), a new release of Triton should encompass all repositories, not just `server`. For example, there are currently no tags in `client` corresponding to https://github.com/triton-inference-server/server/releases/tag/v2.11.0. There is a branch https://github.com/triton-inference-server/client/tree/r21.06, but this is not equivalent to a frozen tag.

**Describe the solution you'd like**
All repositories should have tags corresponding to each release.

**Describe alternatives you've considered**
The commit hash from the HEAD of the relevant branch can be used directly, but a tag is preferable.

**Additional context**
![triton_client_no_tag](https://user-images.githubusercontent.com/4672808/124305178-5a98ba00-db2a-11eb-91e0-7f9ac1e57412.png)

**Comment by jbkyang-nvi** [comment]
Hi @kpedro88. Right now, we branch for releases. For a release branch the head of the branch is the fixed/ final state of that release. We could put a tag there as well but they are equivalent and it is extra work for us so we don't have any plans to do it. 
Is there a specific reason why you want to use `tags`?

**Comment by kpedro88** [comment]
The HEAD of a branch could change at any time. For production-ready code, the best practice is assigning a frozen tag.

Also, it introduces a discrepancy between how the `server` code and the other repos' code should be obtained. For `server`, the Triton version can be used (e.g. `v2.11.0`), while for the other repos, the branch name corresponds to the NGC container version.

**Comment by dzier** [comment]
The build scripts in Server pull directly from branches, not tags or commit hashes. Tagging the individual repos will not provide any additional protection for build. The release branches are protected and there should not be any unforseen changes. While this may be a best practice, it would require a significant change to our build and test infrastructure. We have filed this as a potential improvement and will evaluate the process internally.
