### ISSUE TITLE
custom build tensorflow backend

### ISSUE THREAD

**Issue by zhaohb** [triton-inference-server/server#3085]
now, I build tensorflow backend, this step [https://github.com/triton-inference-server/tensorflow_backend#build-the-tensorflow-backend-with-custom-tensorflow](https://github.com/triton-inference-server/tensorflow_backend#build-the-tensorflow-backend-with-custom-tensorflow) I had finish, but [https://github.com/triton-inference-server/tensorflow_backend#build-the-tensorflow-backend](https://github.com/triton-inference-server/tensorflow_backend#build-the-tensorflow-backend) I have some doubts：
![image](https://user-images.githubusercontent.com/5791375/124354605-6d50e300-dc3f-11eb-8f7c-3c4b13b88852.png)
which environment should I perform this step? the NGC link is not open right now.

**Comment by CoderHam** [comment]
Thanks for pointing this out. It is a typo in the documentation: 
The link to NGC is https://ngc.nvidia.com/catalog
We will have a fix up shortly.

**Comment by CoderHam** [comment]
Fixed by https://github.com/triton-inference-server/tensorflow_backend/pull/27

**Comment by CoderHam** [comment]
@zhaohb you will need to run the same in the main repo dir post cloning. The build involves pulling and copying contents out of the NGC TF container.
