### ISSUE TITLE
Multiple instances of same model-additional memory for weights?

### ISSUE THREAD

**Issue by wabbitml** [triton-inference-server/server#3096]
If I have a model X and I create multiple instances of the same model X on GPU, will every additional instance end up consuming additional memory for the full set of weights in X or will all instances share the same memory?

**Comment by CoderHam** [comment]
@wabbitml TensorRT tried to re-use weights whenever possible between instances on the same GPU. In my understanding the other backends do not.

**Comment by dzier** [comment]
@wabbitml , Did this answer your question?

**Comment by dzier** [comment]
Closing issue, please re-open if have followup questions.

**Comment by wabbitml** [comment]
> @wabbitml TensorRT tried to re-use weights whenever possible between instances on the same GPU. In my understanding the other backends do not.

I couldn't find this in the Tensorrt documentation. Do you have a link to the doc/code comments where this is specified?
