### ISSUE TITLE
Usage of packaged conda environments stored in s3 with python backend

### ISSUE THREAD

**Issue by tavanduy** [triton-inference-server/server#3097]
Hello, 
I am trying to use Custom Python Execution Environments. Specifically, I struggle with specifiying the "EXECUTION_ENV_PATH" in config.pbtxt file when using custom packaged conda environment. 

The example provided in the documentation is using an absolute path to the packaged conda environment.  
`name: "model_a"
backend: "python"

...

parameters: {
  key: "EXECUTION_ENV_PATH",
  value: {string_value: "/home/iman/miniconda3/envs/python-3-6/python3.6.tar.gz"}
}`

However, I struggle with specifying the path in case of storing the packaged environment in S3. The Triton Server reads the contents of the s3 bucket using https protocol and it creates some temporary folder on a local machine that is running the server that contains the models from S3 e.g /tmp/some_numbers/models/model_subfolder which makes me unable to use relative path to the packaged conda environment since I don't know what is the adress of the temporary folder in the time of specifying the config.pbtxt file. Is there any way how to use the packaged conda environment stored in S3?

Triton version is 21.06
To reproduce just try to use custom packaged environment stored in S3 using any model.

**Comment by Tabrizian** [comment]
@tavanduy Storing Python backend execution environments inside S3 is not supported yet.
