### ISSUE TITLE
Support for Sequence IDs as strings

### ISSUE THREAD

**Issue by rabbh** [triton-inference-server/server#3099]
**Is your feature request related to a problem? Please describe.**

Sequence IDs for sequence batching are currently set via the gRPC API as 64-bit integers.
When using Triton with many clients per host (> 1000), particularly in a k8s environment where pods are free to come and go as they please, this makes it difficult to avoid potential collisions and reuse of sequence IDs on the same Triton host.

**Describe the solution you'd like**
Allowing sequence IDs to be strings would allow us to use v4 UUIDs and greatly reduce the chance of collisions, and would simplify the need for any safeguards across all client pods. The bonus is that it would allow us to directly tie sequence IDs to request IDs, which are often UUIDs in cloud-native environments (e.g. when using Envoy as an API gateway, the request IDs are UUIDs).

**Describe alternatives you've considered**
Triton could also generate a sequence ID itself and return it via gRPC trailing metadata of the first inference response, or whatever other field is available for metadata. So you'd send your first request with sequence ID -1 or 0 to defer the generation to Triton, and it would return an ID when replying to that RPC. This would prevent any collisions on Triton itself without changing the data type.

**Comment by dzier** [comment]
Filed an Enhancement request with the team.

**Comment by dzier** [comment]
Feature was added to the [21.10 release](https://github.com/triton-inference-server/server/releases/tag/v2.15.0)
