### ISSUE TITLE
No ModelWarmup examples 

### ISSUE THREAD

**Issue by rabbh** [triton-inference-server/server#3100]
**Description**
We're interested in warming up our models before allowing them to serve traffic. This documentation briefly introduces a 'ModelWarmup' functionality: https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md

But I cannot find any examples or additional documentation. I did find this test configpb.txt:
https://github.com/triton-inference-server/server/blob/main/qa/L0_model_config/autofill_noplatform/ensemble/model_warm_up_set/config.pbtxt

With a "model_warmup [{}]" property but I'm guessing it's missing some additional properties. I tried adding that to our config just in case but it did not have any effect.

Please note this would be for sequence batching specifically.

**Triton Information**
21.05

Are you using the Triton container or did you build it yourself?
Triton container

**Comment by tanmayv25** [comment]
Please take a look at the documentation in the proto file:
https://github.com/triton-inference-server/common/blob/main/protobuf/model_config.proto#L1438
https://github.com/triton-inference-server/common/blob/main/protobuf/model_config.proto#L1762


> Please note this would be for sequence batching specifically.
In that case, one must ensure the "series of inference requests" specified in the model config must reset the model state at the end.
