### ISSUE TITLE
Multiple copies of perf_analyzer cannot be run in parallel with sequence batching due to sequence id collisions

### ISSUE THREAD

**Issue by raimondasl** [triton-inference-server/server#3103]
I tried to run two perf_analyzer copies from different machines to test the load on a sequence batching model.
Unfortunately, it seems that perf_analyzer does not randomize sequence ids well and there are sequence id collisions.
On server:
.....
W0709 18:15:26.215562 584 sequence_batch_scheduler.cc:401] sequence 406 for model 'asr' has a conflict. The previous sequence did not end before this sequence start. Previous sequence will be terminated early.
W0709 18:15:26.216838 584 sequence_batch_scheduler.cc:401] sequence 407 for model 'asr' has a conflict. The previous sequence did not end before this sequence start. Previous sequence will be terminated early.
W0709 18:15:26.218117 584 sequence_batch_scheduler.cc:401] sequence 408 for model 'asr' has a conflict. The previous sequence did not end before this sequence start. Previous sequence will be terminated early.
.....

Ultimately clients also terminate with:
....
Thread [246] had error: inference request for sequence 1901 to model 'asr' must specify the START flag on the first request of the sequence
Thread [248] had error: inference request for sequence 1998 to model 'asr' must specify the START flag on the first request of the sequence
Thread [249] had error: inference request for sequence 1858 to model 'asr' must specify the START flag on the first request of the sequence
.....

Can the perf_analyzer sequence ids be randomized with a random seed to prevent sequence id collisions from multiple perf_analyzer copies running at the same time? Alternatively, could the perf_analyzer take the seed as an input.

**Comment by dzier** [comment]
It's possible. I will file an enhancement/bug request with the team.

**Comment by tanmayv25** [comment]
@raimondasl [This](https://github.com/triton-inference-server/client/pull/44/files) PR introduced an option to provide sequence id range to perf_analyzer cli. This should allow you to run multiple PA in parallel without sequence id collision.

Please re-open if you face any other issues.
