### ISSUE TITLE
How to set the cpu affinity of the model instance?

### ISSUE THREAD

**Issue by zouyxdut** [triton-inference-server/server#3106]
My CPU TorchScript model has very high latency in concurrent scenarios, which is about 2 times of single concurrency. I tried setting CPU affinity in my local PyTorch environment, and the performance improved significantly. But how to do the same thing in triton?

**Comment by deadeyegoodwin** [comment]
Recent versions of Triton have some numa controls for the threads created by triton: https://github.com/triton-inference-server/server/blob/main/docs/optimization.md#numa-optimization

But those controls will not influence how pytorch itself is managing its internal threads. What are you doing to control affinity in pytorch?

**Comment by tanmayv25** [comment]
Closing because of the inactivity. Please re-open if still an issue.
