### ISSUE TITLE
Question about max_batch_size, dynamic_batching in python_backend

### ISSUE THREAD

**Issue by donggrame** [triton-inference-server/server#3107]
Consider following `config.pbtxt` for example.
```
backend: "python"

input [
  {
    name: "INPUT0"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]

output [
  {
    name: "OUTPUT0"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]

max_batch_size: 32
dynamic_batching {
  preferred_batch_size: [ 8,16,32 ]
  max_queue_delay_microseconds: 30000
}
```

I thought triton takes care of batch concatenation from multiple requests and batch split to each request but it is not.

1. The client must add batch dimension even though it has a single string to request. That is
```python
# This complains about size of input
input0_data = np.array(["This is input for model"], dtype=object)
httpclient.InferInput("INPUT0", input0_data.shape, np_to_triton_dtype(input0_data.dtype))

# This works
input0_data = np.array([["This is input for model"]], dtype=object)
httpclient.InferInput("INPUT0", input0_data.shape, np_to_triton_dtype(input0_data.dtype))
```

2. If the client sends 8 requests within 3000microseconds with a single string instance, the length of `requests` passed through  `def execute(self, requests)` is 8, not the length of `requests` is 1 with 8 data inside of it. The client must handle multiple requests by making them into a batch manually to get improved performance. Then split them into 8 responses.

I guessed that the `batch` in `max_batch_size` and `dynamic_batching` are completely different things.
The `batch` in `max_batch_size` means the maximum batch size per request and the `batch` in `dynamic_batching` means the maximum requests passed to `execute(self, requests)`.
To batching requests by hand, I changed `config.pbtxt` to this but it complains like `dynamic batching preferred size must be <= max batch size for mode`.
```
max_batch_size: 1
dynamic_batching {
  preferred_batch_size: [ 1,2,4,8,16,32 ]
  max_queue_delay_microseconds: 30000
}
```

I'm confused a bit about what is `max_batch_size` and what is `dynamic_batching`.
Could you elaborate more about this batch thing and give the best practice?

**Comment by Tabrizian** [comment]
> The client must add batch dimension even though it has a single string to request.

When `max_batch_size > 0` you need to add another dimension in your inputs for batching. You can read more about it in the link below:

https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#inputs-and-outputs

> the batch in dynamic_batching means the maximum requests passed to execute(self, requests)

This is incorrect. The `preferred_batch_size` in dynamic batching means your preferred size of created batches. The `max_batch_size` indicates the maximum size of the batch (or requests array in case of Python backend).

https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#preferred-batch-sizes
