### ISSUE TITLE
Not able to connect to Dell EMC ECS

### ISSUE THREAD

**Issue by okyspace** [triton-inference-server/server#3110]
**Description**
Got this error when running Triton on kubernetes to connect to Dell ECS.
`error: creating server: Internal - Could not get MetaData for bucket with name x.x.x.x due to exception: error message: Unable to connect to endpoint`
It can work if I connect triton to a standalone Minio though.
I can also access the ECS bucket through S3 browser with the same URL, port number and credentials.

**Triton Information**
What version of Triton are you using?
21.06

Are you using the Triton container or did you build it yourself?
Container

**To Reproduce**
Steps to reproduce the behavior.
Run triton with the below command: 
`docker run --rm -p 8000:8000 -p 8001:8001 -p 8002:8002 --env <envfileContainAccessKeyAndPassword> nvidia/tritonserver:21.06-py3 tritonserver --model-repository=s3://https://x.x.x.x:443/bucketname --log-verbose=1`

**Comment by deadeyegoodwin** [comment]
@CoderHam It seems like the host field is being interpreted as the bucketname?

**Comment by CoderHam** [comment]
@deadeyegoodwin I tried launching the server with that path and the error I got was different (expected since I left the S3 creds blank): 
`error: creating server: Internal - Could not get MetaData for bucket with name bucketname due to exception: , error message: Unable to connect to endpoint`
The same holds true for both 21.06 and master.
@okyspace could you confirm the version of tritonserver you were using in 21.06 and not an older image?

**Comment by okyspace** [comment]
@deadeyegoodwin @CoderHam , yes, confirmed. I just downloaded 21.06-py3 on Mon for deployment.

**Comment by CoderHam** [comment]
@okyspace I am unable to reproduce the error you shared with the 21.06-py3 image

**Comment by okyspace** [comment]
@CoderHam Thanks! could I ask if there is any way to turn on more specific logs so that we can troubleshoot further.

**Comment by CoderHam** [comment]
@okyspace unfortunately that the verbose error we received from the aws sdk. What I can suggest is using the same credentials inside the Triton docker and use the aws cli to confirm it is working correctly.

**Comment by okyspace** [comment]
@CoderHam, can I understand how to deploy a SSL cert to establish the HTTPS connection from Triton to ECS. We suspect the issue is due to cert. I search through triton documentation but cannot find something relevant. Able to advise?

**Comment by okyspace** [comment]
Resolved by including a cert. due to https. Thanks for the help.
