### ISSUE TITLE
How to read image file from HTTP requests for python backend?

### ISSUE THREAD

**Issue by ernestlwt** [triton-inference-server/server#3115]
Instead of using a client.py file to send inference requests, I am trying to send an image file via a HTTP request but I am not sure how to modify the model.py so that I can read the image in from the InferenceRequest object. Is this possible or what are the alternatives to do so?

**Comment by Tabrizian** [comment]
Your input tensors are available in the InferenceRequest object. You have access to the input tensors using a NumPy array.

```
in_0 = pb_utils.get_input_tensor_by_name(request, "INPUT0")

# Get the numpy array
in_0.as_numpy()
```

We have some examples in the Python backend repository:

https://github.com/triton-inference-server/python_backend#examples

**Comment by Tabrizian** [comment]
Closing the ticket. Feel free to re-open if you have additional questions.
