### ISSUE TITLE
Wrong preferred_batch_size selected

### ISSUE THREAD

**Issue by AnthonyBarbier** [triton-inference-server/server#3116]
I've got a very similar set up (Except I'm using a custom backend): I've got a client which sends loads of size 256 requests and I've got a model I'm trying to get to process multiples of 256:

```
name: "my_model"
backend: "my_backend"
max_batch_size: 51200
dynamic_batching {
  preferred_batch_size: [256, 25600, 51200]
  max_queue_delay_microseconds: 100000
}
input [
  {
    name: "testinfeed.0"
    data_type: TYPE_FP32
    dims: [ 48, 48, 1 ]
  }
]
output [
  {
    name: "testoutfeed.0"
    data_type: TYPE_FP32
    dims: [ 3 ]
  },
  {
    name: "testoutfeed.1"
    data_type: TYPE_FP32
    dims: [ 1 ]
  }
]

instance_group [{ kind: KIND_CPU }]
```

With that model config I receive 18k requests
if I remove 256 from the preferred_batch_size, then the batching kicks in (i.e the backend receives 180 requests) but always to the lowest batch size (i.e not 51200), and if I remove 25600 it finally gets to the full size.
The documentation says the server will try to batch using the largest possible batch but in practice it seems to always pick the smallest one.

**Comment by GuanLuo** [comment]
The preferred batch size is selected based on the number of requests waiting in the model's queue. What may happened is that when the model is idle and asks for requests from the queue, the number of requests is in range [256, 25600), so the scheduler sees that the largest possible preferred batch can be formed at the moment is 256, so the model will proceed to execute batch of 256. If your client doesn't generate load faster than the model consumes, then it is expected that the queue won't contains pending batch > 25600.

And when you removed 256 from preferred batch, in the scenario above, the scheduler will let the model remain idle as no preferred batch can be formed from the queue, until the client sends more requests and number of pending requests reaches 25600.

**Comment by AnthonyBarbier** [comment]
Ok, so I've added more batch sizes and increased the timeout to 1 second.
When the server starts I see the following in the console:
```
  "dynamic_batching": {
        "preferred_batch_size": [
            256,
            512,
            1024,
            2048,
            4096,
            8192,
            16384,
            25600,
            51200
        ],
        "max_queue_delay_microseconds": 1000000,
        "preserve_ordering": false,
        "priority_levels": 0,
        "default_priority_level": 0,
        "priority_queue_policy": {}
    },
```
I'm using a python grpc client to send loads of 256 requests, and on the server I print how many requests I receive and the batch size of each of them:
```
I0715 11:51:02.733180 4977 requests_handler.cc:27] DBG received 1 requests
I0715 11:51:02.733203 4977 requests_handler.cc:80] DBG Processing request 0 (batch size = 256)
I0715 11:51:02.735936 4977 requests_handler.cc:27] DBG received 2 requests
I0715 11:51:02.735996 4977 requests_handler.cc:80] DBG Processing request 0 (batch size = 256)
I0715 11:51:02.736058 4977 requests_handler.cc:80] DBG Processing request 1 (batch size = 256)
I0715 11:51:02.740042 4977 requests_handler.cc:27] DBG received 1 requests
I0715 11:51:02.740067 4977 requests_handler.cc:80] DBG Processing request 0 (batch size = 256)
I0715 11:51:02.742460 4977 requests_handler.cc:27] DBG received 1 requests
I0715 11:51:02.742486 4977 requests_handler.cc:80] DBG Processing request 0 (batch size = 256)
I0715 11:51:02.745182 4977 requests_handler.cc:27] DBG received 2 requests
I0715 11:51:02.745234 4977 requests_handler.cc:80] DBG Processing request 0 (batch size = 256)
I0715 11:51:02.745299 4977 requests_handler.cc:80] DBG Processing request 1 (batch size = 256)
I0715 11:51:02.748951 4977 requests_handler.cc:27] DBG received 1 requests
I0715 11:51:02.748973 4977 requests_handler.cc:80] DBG Processing request 0 (batch size = 256)
I0715 11:51:02.751619 4977 requests_handler.cc:27] DBG received 1 requests
I0715 11:51:02.751655 4977 requests_handler.cc:80] DBG Processing request 0 (batch size = 256)
I0715 11:51:02.763041 4977 requests_handler.cc:27] DBG received 1 requests
I0715 11:51:02.763088 4977 requests_handler.cc:80] DBG Processing request 0 (batch size = 256)
I0715 11:51:02.768983 4977 requests_handler.cc:27] DBG received 1 requests
I0715 11:51:02.769042 4977 requests_handler.cc:80] DBG Processing request 0 (batch size = 256)
```
1) Looking at the timestamps: the backend gets called many times within 1 second
2) The very few times where the requests are actually regrouped they still have a batch size of 256.

**Comment by GuanLuo** [comment]
1. The timeout is the maximum time to wait when "no preferred batch can be formed from the queue", if you send each request with batch 255 then you can see it being used. In your scenario when there is request in the queue, it can always form a preferred batch (256).
2. As you mentioned, the scheduler doesn't modify the requests, it groups them together and send them to the backend (because it won't know how a batch should be formulated for individual backend). You can see that your backend received a execution of 2 requests from time to time, then you backend can process them in one execution by preparing them to the form that your backend needs for execution.

**Comment by AnthonyBarbier** [comment]
Oh, I see, thanks a lot for the explanation, makes more sense now.

Is there a way to configure the server to make it cope better with small requests?

I've got a client which sends 7000 requests of size 256, and no matter how I tweak the `preferred_batch_size` and `max_queue_delay_microseconds` it still takes ~30 seconds to run, and only 6-8 seconds is spent in my backend.

Is it just the overhead of grpc / network configuration, or am I missing some settings on the server / model side which could help?

**Comment by GuanLuo** [comment]
You can use `perf_analyzer` to profile the time spent on different parts of the inference cycle. It provides various options that you can use to simulate your workload.

And it would be good to create a new Github issue for the performance subject, as it differs from the original subject of this issue.

**Comment by AnthonyBarbier** [comment]
Sure, will close this issue now.
Thanks again for your help.
