### ISSUE TITLE
failed to load torch script model, unexpected no host policy

### ISSUE THREAD

**Issue by aixi** [triton-inference-server/server#3117]
**Description**
E0714 13:21:46.350558 5163 model_repository_manager.cc:1215] failed to load 'xiaomi-nose-type' version 1: Internal: unexpected no host policy for my_model
**Triton Information**
What version of Triton are you using?
trtion server-v2.11.0
Are you using the Triton container or did you build it yourself?
build from source
**To Reproduce**
Steps to reproduce the behavior.
./simple -r <model repo path>
Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
name: "my_model"
platform: "pytorch_libtorch"
max_batch_size: 0
input [
  {
    name: "INPUT__0"
    data_type: TYPE_FP32
    dims: [ 3, 224, 224 ]
  },
  {
    name: "INPUT__1"
    data_type: TYPE_FP32
    dims: [ 1, 224, 224 ]
  }
]
output [
  {
    name: "OUTPUT__0"
    data_type: TYPE_FP32
    dims: [ 3 ]
  }
]
instance_group [
  {
    count: 1
    kind: KIND_GPU
    host_policy: "gpu_0"
  }
]
**Expected behavior**
load model success

looks likes file backend>src>backed_model_instance.cc:146 throw a exception

**Comment by GuanLuo** [comment]
Are you building the source from a release version or from master? Are you building with `build.py` script? It appears that you are building the backend / server from misaligned source

**Comment by aixi** [comment]
Thank for you reply.
No, I am not using build.py. I use CMakeLists to build, I found the the reason, server backend pytroch_backend tag are not match. I solve this problem by using same tag r21.06
