### ISSUE TITLE
Triton server crashes silently with invalid input data

### ISSUE THREAD

**Issue by NonStatic2014** [triton-inference-server/server#3119]
**Description**
Sending an invalid input json to the REST API interface can cause triton server crashes silently

**Triton Information**
21.05-py3 container pulled from nvidia, on a CPU-only machine

**To Reproduce**
1. Follow instruction [here](https://www.tensorflow.org/tfx/tutorials/serving/rest_simple) to train the mnist_fashion model
2. create a folder for the trained model and make sure layout is correct
3. Run triton: `docker run --rm -p8000:8000 -p8001:8001 -p8002:8002 -v$(pwd)/model:/model nvcr.io/nvidia/tritonserver:21.05-py3 tritonserver --model-repository=/model --log-verbose=1 --strict-model-config=false`
4. Command to send request: `curl -d @"<filename>.json" http://localhost:8000/v2/models/fashion/versions/1/infer -v`

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
* Trained Model: https://ufile.io/dde0s62m
* Good input json: https://ufile.io/inpve8py
* Bad input json (causing crash): https://ufile.io/0kfmjc2p

**Expected behavior**
Error message when receive invalid input.

**Comment by deadeyegoodwin** [comment]
Thanks for the bug report and repo instructions. We will look into the issue.
