### ISSUE TITLE
Can Triton server be installed on Drive PX2?

### ISSUE THREAD

**Issue by yidiwang21** [triton-inference-server/server#3120]
Hello, 

I am trying to install Triton server on Drive PX2 with cmake. So far I have tried r18.12, r19.08, r20.01, and r21.06 but none of them can be successfully built. So my question is, can Triton be installed on PX2? If the answer is yes, which version is suggested to use?

Should I use jetson version for Arm support?

Any help would be appreciated, thanks!

**Comment by deadeyegoodwin** [comment]
We don't test on Drive PX2 so I can't say for sure what is required for that platform. We do provide the jetson Jetpack-based release... I suggest that you try using that release and see if it works on PX2.
