### ISSUE TITLE
GRPC: unable to provide 'output_3' in GPU, will use CPU

### ISSUE THREAD

**Issue by xuyufeng1995** [triton-inference-server/server#3121]
**Description**
When I use triton for model inference service, the client request can be returned correctly, but I checked the log and found a problem，”I0715 05:07:05.505314 1 grpc_server.cc:2275] GRPC: unable to provide 'output_3' in GPU, will use CPU“.
  whether the model inference is running on GPU or CPU, how to understand this problem.Does the model inference run on Gpu as I expected。

I0715 05:07:05.501241 1 plan_backend.cc:2513] Running rider_0_0_gpu3 with 1 requests
I0715 05:07:05.501304 1 plan_backend.cc:3431] Optimization profile default [0] is selected for rider_0_0_gpu3
I0715 05:07:05.501338 1 pinned_memory_manager.cc:161] pinned memory allocation: size 393216, addr 0x7f43c4000090
I0715 05:07:05.501538 1 plan_backend.cc:2936] Context with profile default [0] is being executed for rider_0_0_gpu3
I0715 05:07:05.505281 1 infer_response.cc:139] add response output: output: output_3, type: FP32, shape: [1,93]
I0715 05:07:05.505314 1 grpc_server.cc:2275] GRPC: unable to provide 'output_3' in GPU, will use CPU
I0715 05:07:05.505322 1 grpc_server.cc:2286] GRPC: using buffer for 'output_3', size: 372, addr: 0x7f3f7f58c170
I0715 05:07:05.505332 1 pinned_memory_manager.cc:161] pinned memory allocation: size 372, addr 0x7f43c40600a0
I0715 05:07:05.505360 1 infer_response.cc:139] add response output: output: output_0, type: FP32, shape: [1,93]
I0715 05:07:05.505368 1 grpc_server.cc:2275] GRPC: unable to provide 'output_0' in GPU, will use CPU
I0715 05:07:05.505374 1 grpc_server.cc:2286] GRPC: using buffer for 'output_0', size: 372, addr: 0x7f3f7fc15d50
I0715 05:07:05.505379 1 pinned_memory_manager.cc:161] pinned memory allocation: size 372, addr 0x7f43c4060220
I0715 05:07:05.505394 1 infer_response.cc:139] add response output: output: output_1, type: FP32, shape: [1,93]
I0715 05:07:05.505401 1 grpc_server.cc:2275] GRPC: unable to provide 'output_1' in GPU, will use CPU
I0715 05:07:05.505406 1 grpc_server.cc:2286] GRPC: using buffer for 'output_1', size: 372, addr: 0x7f3f7f8a11d0
I0715 05:07:05.505414 1 pinned_memory_manager.cc:161] pinned memory allocation: size 372, addr 0x7f43c40603a0
I0715 05:07:05.505427 1 infer_response.cc:139] add response output: output: output_2, type: FP32, shape: [1,93]
I0715 05:07:05.505435 1 grpc_server.cc:2275] GRPC: unable to provide 'output_2' in GPU, will use CPU
I0715 05:07:05.505440 1 grpc_server.cc:2286] GRPC: using buffer for 'output_2', size: 372, addr: 0x7f3f7f8a1720
I0715 05:07:05.505447 1 pinned_memory_manager.cc:161] pinned memory allocation: size 372, addr 0x7f43c4060520
I0715 05:07:05.511160 1 pinned_memory_manager.cc:190] pinned memory deallocation: addr 0x7f43c40600a0
I0715 05:07:05.511186 1 pinned_memory_manager.cc:190] pinned memory deallocation: addr 0x7f43c4060220
I0715 05:07:05.511192 1 pinned_memory_manager.cc:190] pinned memory deallocation: addr 0x7f43c40603a0
I0715 05:07:05.511196 1 pinned_memory_manager.cc:190] pinned memory deallocation: addr 0x7f43c4060520
I0715 05:07:05.511211 1 grpc_server.cc:3304] ModelInferHandler::InferResponseComplete, 9788 step ISSUED
I0715 05:07:05.511233 1 grpc_server.cc:2321] GRPC free: size 372, addr 0x7f3f7f58c170
I0715 05:07:05.511239 1 grpc_server.cc:2321] GRPC free: size 372, addr 0x7f3f7fc15d50
I0715 05:07:05.511244 1 grpc_server.cc:2321] GRPC free: size 372, addr 0x7f3f7f8a11d0
I0715 05:07:05.511248 1 grpc_server.cc:2321] GRPC free: size 372, addr 0x7f3f7f8a1720
I0715 05:07:05.511347 1 grpc_server.cc:2873] ModelInferHandler::InferRequestComplete
I0715 05:07:05.511357 1 grpc_server.cc:3151] Process for ModelInferHandler, rpc_ok=1, 9788 step COMPLETE
I0715 05:07:05.511372 1 grpc_server.cc:2195] Done for ModelInferHandler, 9788
I0715 05:07:05.511360 1 pinned_memory_manager.cc:190] pinned memory deallocation: addr 0x7f43c4000090

**Comment by deadeyegoodwin** [comment]
That is just an informational message (notice that the log line starts with 'I'). You will only see this message is you turn on verbose logging.  It means that the model has produced / will produce the model output into GPU memory, so it is requesting from the grpc endpoint for a GPU buffer into which it will write the output. The GRPC endpoint is saying that is can't provide a GPU buffer so it is providing a CPU buffer instead.

FYI, the message is generated here: https://github.com/triton-inference-server/server/blob/main/src/servers/grpc_server.cc#L2275
