### ISSUE TITLE
openvino custom op

### ISSUE THREAD

**Issue by zhaohb** [triton-inference-server/server#3129]
now I am using openvino, but custom operators are implemented as required. I wonder how to support custom operators on the OpenVino backend.

who can help me ? thanks

**Comment by tanmayv25** [comment]
OpenVINO backend is still in beta quality with a limited testing.  You can try using `CPU_EXTENSION_PATH` parameter in the model config:  https://github.com/triton-inference-server/openvino_backend#parameters

For other instructions please follow: https://docs.openvinotoolkit.org/latest/openvino_docs_HOWTO_Custom_Layers_Guide.html

**Comment by zhaohb** [comment]
ok, thank you very much, I got it.

**Comment by zhaohb** [comment]
another question, when will there be an official version？

**Comment by tanmayv25** [comment]
There are some fixes available in OV 2021.4. We are waiting for ONNXRuntime to move to 2021.4 to enable our testing and officially support OV backend.

**Comment by zhaohb** [comment]
which version OV in triton 21.06?

**Comment by tanmayv25** [comment]
2021.2 See here: https://github.com/triton-inference-server/server/blob/r21.06/build.py#L73

**Comment by zhaohb** [comment]
ok, thank you very much , I know windows is 2021.2, but do not know linux is also 2021.2
