### ISSUE TITLE
Support for HTTP endpoint on windows

### ISSUE THREAD

**Issue by 9cvele3** [triton-inference-server/server#3130]
**Describe the solution you'd like**
Is it possible for Windows version of Triton to have HTTP server, like the Linux version does? Currently, only GRPC endpoint is supported. 

**Additional context**
Triton uses libevhtp in HTTP server implementation, and vcpkg seems to lack libevhtp for Windows. 
Is that the only blocker for having HTTP endpoint on Windows version of Triton ? Would it help if MinGW based vcpkg was created (it seems that libevhtp can't be build with MSVC, only MinGW on Windows) ?

**Comment by deadeyegoodwin** [comment]
Triton likely needs a windows-native port of libevhtp. We suspect that it is just a matter of using the appropriate socket API for windows. Other than libevhtp there is no other blocker for getting HTTP support on windows. At this time we don't have a schedule for when we will be working on windows HTTP.
