### ISSUE TITLE
Secure https endpoint

### ISSUE THREAD

**Issue by okyspace** [triton-inference-server/server#3138]
**Is your feature request related to a problem? Please describe.**
A secure http endpoint, i.e. https. Similar to https://github.com/triton-inference-server/server/blob/main/qa/L0_secure_grpc/test.sh

**Describe the solution you'd like**
Allow us to deploy own SSL cert to triton server to enable https endpoint.

**Comment by GuanLuo** [comment]
The support for secure HTTPS endpoint is on our backlog but not yet prioritize for future release. Will keep this issue updated once we are working on this feature.

**Comment by CoderHam** [comment]
@okyspace support for SSL was added to both the HTTP Server endpoint and the Client sdk: https://github.com/triton-inference-server/server/pull/3862
