### ISSUE TITLE
Can we build with Caffe2 without MKL?

### ISSUE THREAD

**Issue by yidiwang21** [triton-inference-server/server#3148]
When I build from the source with `-DTRTIS_ENABLE_CAFFE2=ON`, I got the error: 
```
/usr/bin/ld: cannot find -lmkl_core
/usr/bin/ld: cannot find -lmkl_gnu_thread
/usr/bin/ld: cannot find -lmkl_avx2
/usr/bin/ld: cannot find -lmkl_def
/usr/bin/ld: cannot find -lmkl_intel_lp64
/usr/bin/ld: cannot find -lmkl_rt
/usr/bin/ld: cannot find -lmkl_vml_def
```
However, I am on an ARM platform. Here is the system information:
Platform: Drive PX2
OS: Ubuntu 16.04
CUDNN: 7
CUDA: 9.2
Triton version: r20.01
Caffe2 version: 1.0.1 (1.4.0 is used according to the dockerfile, but it cannot be installed on this platform)

**Comment by CoderHam** [comment]
Triton no longer supports Caffe2. However I encourage you to patch the release (20.01 is quite old) to disable MKL support in the build and use your custom Caffe2 build

**Comment by yidiwang21** [comment]
@CoderHam Can you make it more detailed on how to do that?
