### ISSUE TITLE
Can Triton support MIG?

### ISSUE THREAD

**Issue by chiehpower** [triton-inference-server/server#3151]
Dear all,

Can Triton server support MIG? I have tested that I allocate multi complete GPU instance (did not partition), it can work. 
However, if I allocate multi mig instances, it cannot work. (It will only allocate one mig)

My GPUs are five A100.

Thank you in advance.

BR,
Chieh

**Comment by CoderHam** [comment]
Can you clarify what you mean by it allocates only 1 partition/MIG? Triton does support MIG. You might be setting your instance groups in the config.pbtxt incorrectly.

**Comment by tanmayv25** [comment]
> The new Multi-Instance GPU (MIG) feature allows GPUs based on the NVIDIA Ampere architecture (such as NVIDIA A100) to be securely partitioned into up to seven separate GPU Instances for CUDA applications, providing multiple users with separate GPU resources for optimal GPU utilization. This feature is particularly beneficial for workloads that do not fully saturate the GPU’s compute capacity and therefore users may want to run different workloads in parallel to maximize utilization.

[Source](https://docs.nvidia.com/datacenter/tesla/mig-user-guide/index.html)


Triton being a CUDA application can not span across the MIG partition. Hence, the visibility of Triton is limited to the MIG partition. You can try running a Triton process per MIG to get complete GPU utilization.

**Comment by chiehpower** [comment]
> Can you clarify what you mean by it allocates only 1 partition/MIG? Triton does support MIG. You might be setting your instance groups in the config.pbtxt incorrectly.

Dear @CoderHam , 
You are right! Thanks for your reminder! 
I will try it again after I amend the setting in the `config.pbtxt` file.
Thank you!!

> [Source](https://docs.nvidia.com/datacenter/tesla/mig-user-guide/index.html)
> 
> Triton being a CUDA application can not span across the MIG partition. Hence, the visibility of Triton is limited to the MIG partition. You can try running a Triton process per MIG to get complete GPU utilization.

Dear @tanmayv25 , 

Thanks for your information! 
Is your meaning one Triton one MIG partition? 
Suppose that one A100 (40G) partitions 2 MIG (20G GPU memory per MIG), do you suggest that I launch two Triton services with one MIG respectively rather than one Triton service with 2 MIG?
Thank you!!

Best regards,
Chieh

**Comment by tanmayv25** [comment]
> Suppose that one A100 (40G) partitions 2 MIG (20G GPU memory per MIG), do you suggest that I launch two Triton services with one MIG respectively rather than one Triton service with 2 MIG?

Yes.. That is what my understanding is.

**Comment by chiehpower** [comment]
> > Suppose that one A100 (40G) partitions 2 MIG (20G GPU memory per MIG), do you suggest that I launch two Triton services with one MIG respectively rather than one Triton service with 2 MIG?
> 
> Yes.. That is what my understanding is.

Dear @tanmayv25 ,

Got it! 
I am interested in this way that could you elaborate more detail about it? According to the previous discussion, starting 2 triton servers represents 2 containers. In other words, it will use the two different ports. For example, if I use the http protocol, the default port is 8000. In your concept of starting 2 triton servers, is it possible to manage 2 servers (or connect both servers) with one port that clients can always send the request to the same ip and port; in addition, triton can handle this dynamic adjusting? 

Thank you so much!

BR,
Chieh

**Comment by chiehpower** [comment]
Thanks for your reply!

I will close it because I already got the answer to my question of title.
Thanks.

**Comment by tanmayv25** [comment]
I am not the best person to advice you on how to setup your system as I have limited exposure to MIG. But you can take a look at [load balancing]( https://www.nginx.com/resources/glossary/load-balancing/
). 
A system can be designed as a load balancer routing requests to underlying instances of Triton server processes. This way client only has to issue request to load balancer and all the triton servers running on separate MIGs will be engaged.

**Comment by chiehpower** [comment]
Hi @tanmayv25 ,

I got it! Thanks for your reply and for sharing the information!
I will take a look and try it.
Thank you!
