### ISSUE TITLE
py3-min Dockerfile

### ISSUE THREAD

**Issue by MrAta** [triton-inference-server/server#3154]
I would like to build an in-house version of the server image from scratch, however, I couldn't find the Docker file for the py3-min image for Ubuntu. I can see the windows version is there. Where can I find the Dockerfile for the Ubuntu py3-min image?

**Comment by CoderHam** [comment]
We no longer have a permanent Dockerfile.min, you can however use the build.py to create this min container, follow the instructions in docs/build.md

**Comment by jbkyang-nvi** [comment]
Hi @MrAta please follow instructions https://github.com/triton-inference-server/server/blob/main/docs/compose.md if you want to customize the backends. Since we have not officially released this script yet, you should be able to clone the most recent server and do something like `python3 compose.py --work-dir . --repoagent checksum --enable-gpu ... --container-version 21.07`

**Comment by MrAta** [comment]
Thanks @jbkyang-nvi, that's helpful. However, I wanted to use my own base image instead of the py3-min image. While it's not documented in docs/build.md, I could figure out that I can do that using the `--image=base,<image>` flag. Furthermore, it is not well document what exact libs and dependencies are required for such base image.

**Comment by jbkyang-nvi** [comment]
> Thanks @jbkyang-nvi, that's helpful. However, I wanted to use my own base image instead of the py3-min image. While it's not documented in docs/build.md, I could figure out that I can do that using the `--image=base,<image>` flag. Furthermore, it is not well documented what exact libs and dependencies are required for such base image.
> I think maintaining a Dockerfile for the min image would be pretty helpful.

@MrAta Thanks for your feedback. Will create a ticket for the team to prioritize. In the meantime, you can grep for `apt-get` and `pip3` for dependencies in `build.py` as indicated in https://github.com/triton-inference-server/server/blob/main/docs/build.md

**Comment by MrAta** [comment]
@jbkyang-nvi the build.py is building [on the base image](https://github.com/triton-inference-server/server/blob/main/build.py#L531) which itself has some other dependencies installed that are not documented.

Using `ubuntu:20.04` as the base image, so far, I had to install the following packages and counting:

```bash
cuda
cudnn
dirmngr 
gpg-agent 
gnupg gnupg1 gnupg2
python3-libnvinfer-dev 
numactl 
libnuma-dev
```
I wish there was a way to reporduce the -py3-min image.

**Comment by jbkyang-nvi** [comment]
@MrAta Can you try https://github.com/triton-inference-server/server/blob/main/docs/build.md#building-without-docker for additional dependencies? Alternatively you can use `apt list --installed` from the existing min container to check for all the dependencies and use those to build your container. We currently do not have a Dockerfile we can publish right now.

**Comment by MrAta** [comment]
Thanks @jbkyang-nvi that would give a ton of packages and wouldn't be much informative. Anyway, after reading all the build files (server and the backends) and CMakeList files, I could find out all the (undocumented) required packages and configs required to use the `ubuntu:20.04` as the base image. 

For those who might face the issue in the future, I have created this gist containing the Dockerfile based on `ubuntu:20.04` that can be used as the base image. Note that this is only tested on `r21.04` triton release (though should work for other versions too):  https://gist.github.com/MrAta/f37c0306508e453628b9bc58f80d9e77

@jbkyang-nvi if you think this Dockerfile is worth adding to the main repository, I can open a PR. Also feel free to close this issue.
