### ISSUE TITLE
Framework support matrix has wrong version of onnxruntime for 21.06

### ISSUE THREAD

**Issue by holzman** [triton-inference-server/server#3157]
The Framework Support Matrix 

https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html

lists onnx runtime 1.7.1, but release 21.06 includes 1.8.0 (as of commit 9ec38519206a2fe9311ea798c0b388ba1513856e)

**Comment by CoderHam** [comment]
@holzman thanks for catching this. @dzier and @msalehiNV could you help coordinate the fix to the support matrix?

**Comment by CoderHam** [comment]
Fixed
