### ISSUE TITLE
Build and run Triton direclty in my machine instead of using docker

### ISSUE THREAD

**Issue by rkoystart** [triton-inference-server/server#3169]
Hi, i am new Triton Inference Server. The doubt i have is , i know we can run the Triton inference server with the help of the predefined docker provided which has the required things  installed for the triton inference server ro run/deploy models in gpus.. I want to know how can i build the triton Inference Server which can run direclty in my GPU machine  instead of the it running through the Docker. 
So instead of mounting my models in the triton inference server image , i want to run it direclty in my gpu machine like using some command like tritonserver --model-repository /path/to/the/model/repository
Thanks in advance !!!!!!!!!!

**Comment by CoderHam** [comment]
@rkoystart have you tried to do the same by following the docs in [build.md#building-without-docker](https://github.com/triton-inference-server/server/blob/main/docs/build.md#building-without-docker)?

**Comment by rkoystart** [comment]
Thanks for the docs @CoderHam .
When i run the following command(hope it is right),
```
sudo CUDA_VISIBLE_DEVICES=4 ./build.py --cmake-dir=build --build-dir=citritonbuild --enable-logging --enable-stats --enable-tracing --enable-metrics --enab
le-gpu-metrics --enable-gpu --filesystem=gcs --filesystem=azure_storage --filesystem=s3 --endpoint=http --endpoint=grpc --repo-tag=common:r20.07 --repo-tag=core:r20.07 --repo-tag=backend:r20.07 --repo-ta
g=thirdparty:r20.07 --backend=ensemble --backend=identity:r20.07 --backend=repeat:r20.07 --backend=square:r20.07 --backend=onnxruntime:r20.07 --backend=pytorch:r20.07 --backend=tensorflow1:r20.07 --backe
nd=tensorflow2:r20.07 --backend=openvino:r20.07 --backend=python:r20.07 --backend=dali:r20.07 --backend=fil:r20.07 --repoagent=checksum:r20.07
```
I am gettting this error 
```version 2.12.0
default repo-tag: r21.07
container version 21.07
upstream container version 21.07
backend "ensemble" at tag/branch "r21.07"
backend "identity" at tag/branch "r20.07"
backend "repeat" at tag/branch "r20.07"
backend "square" at tag/branch "r20.07"
backend "onnxruntime" at tag/branch "r20.07"
backend "pytorch" at tag/branch "r20.07"
backend "tensorflow1" at tag/branch "r20.07"
backend "tensorflow2" at tag/branch "r20.07"
backend "openvino" at tag/branch "r20.07"
backend "python" at tag/branch "r20.07"
backend "dali" at tag/branch "r20.07"
backend "fil" at tag/branch "r20.07"
repoagent "checksum" at tag/branch "r20.07"
Sending build context to Docker daemon  15.45MB
Step 1/20 : ARG TRITON_VERSION=2.12.0
Step 2/20 : ARG TRITON_CONTAINER_VERSION=21.07
Step 3/20 : ARG BASE_IMAGE=nvcr.io/nvidia/tritonserver:21.07-py3-min
Step 4/20 : FROM ${BASE_IMAGE}
Get https://nvcr.io/v2/: proxyconnect tcp: dial tcp: lookup proxy.example.com on 192.168.100.11:53: no such host
error: docker build tritonserver_buildbase failed
```
Can i know what went wrong ?

**Comment by CoderHam** [comment]
You need to docker login with your ngc credentials to be able to fetch the NGC containers. 
 As you can see you are trying to pull nvcr.io/nvidia/tritonserver:21.07-py3-min without docker logging in.

**Comment by rkoystart** [comment]
Is there any documentaion for creating the ngc credentials @CoderHam

**Comment by tanmayv25** [comment]
@rkoystart  May be sign up from [here](https://ngc.nvidia.com/signin).

**Comment by dyastremsky** [comment]
Closed due to inactivity. Please let us know if you need this issue reopened.
