### ISSUE TITLE
CUDA illegal memory error when calling bool() in torch script

### ISSUE THREAD

**Issue by lidh15** [triton-inference-server/server#3175]
**Description**

CUDA error an illegal memory access was encountered at
 bool(torch.any(encoder_padding_mask))

**Triton Information**

Triton server container sdk image 21.04 
Triton server version 2.7.0
Triton client installed via pip wheel
Triton client version 2.11.0

**To Reproduce**

the model is Facebook fairseq model and is transfered into torch script

set instance_group including gpus different from 0 (it didn't happen when gpus = [0])

call http inference for several times (it never happened at the first call)

**Expected behavior**

CUDA error an illegal memory access was encountered at
 bool(torch.any(encoder_padding_mask)) in torch script

**Comment by CoderHam** [comment]
@lidh15 did you try running the model in torchscript outside Triton? It is possible the model requires the input data on GPU0.

**Comment by lidh15** [comment]
> @lidh15 did you try running the model in torchscript outside Triton? It is possible the model requires the input data on GPU0.

yes I tried, everything was fine when I set the model and the input tensor both on GPU 1,
it only happened in triton where we won't determine the device during inference.

**Comment by lidh15** [comment]
And the memory bug disappeared when I use another machine. But I cannot figure out how the differences in the setup caused this. The bug happened where I used docker 20.10.7, nvidia driver 440.118.02, libnvidia-container 1.1.1.1 and nvidia-docker2 2.3.0, nvidia-container-toolkit 1.1.2, nvidia-container-runtime 3.2.0

**Comment by lidh15** [comment]
okay, this is the bug fixed in triton server 2.9 which is corresponding to container sdk image 21.04, my partner falsely told me that triton server 2.7 is binding to container 21.04 and failed my work.
