### ISSUE TITLE
[Docs] Clarify when backends need to release requests

### ISSUE THREAD

**Issue by wphicks** [triton-inference-server/server#3176]
**Description**
In the [documentation for backend development](https://github.com/triton-inference-server/backend#tritonbackend_request), it says that the backend takes ownership of requests and "must release" each request it receives. If `TRITONBACKEND_ModelInstanceExecute` returns non-null, it appears that the server takes back ownership of the requests and releases them as indicated by the comment on [this line](https://github.com/triton-inference-server/server/blob/main/src/backends/backend/triton_model.cc#L219). It would be helpful to clarify the documentation to give better guidance on when it is necessary for the backend to release the request.

**Triton Information**
Build of latest main

Are you using the Triton container or did you build it yourself? Tried both

**To Reproduce**
In any backend, release requests and then return a non-null error value from `TRITONBACKEND_ModelInstanceExecute`. Observe double free.

**Expected behavior**
If a backend "must release" requests, doing so should not lead to a double free unless the backend itself releases the requests multiple times. Alternatively, the docs should be updated to clarify when the backend must release its requests.

**Comment by tanmayv25** [comment]
We do have a complete documentation of this behavior [here](https://github.com/triton-inference-server/core/blob/main/include/triton/core/tritonbackend.h#L1122-L1140). 

If it looks good, we can include the same in our markdowns or at the least point to the tritonbackend.h file.

**Comment by wphicks** [comment]
Yeah, that looks great! If we could just get a reference or copy of that in the markdown, that would be ideal.
