### ISSUE TITLE
[INTERNAL] Attempting to access response which is not yet allocated

### ISSUE THREAD

**Issue by Yonghao-Yu** [triton-inference-server/server#3177]
**Description**

E0730 14:55:35.346636 167 grpc_server.cc:1613] [INTERNAL] Attempting to access response which is not yet allocated
E0730 14:55:35.347336 167 grpc_server.cc:3175] expected allocator to have created a response object

**Triton Information**
What version of Triton are you using?
2.3.0

Are you using the Triton container or did you build it yourself?
yes

**To Reproduce**
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

i am trying to deploy Pytorch official fasterrcnn model ，and my model configuration is as follow：

platform: "pytorch_libtorch"
max_batch_size: 1
input [
  {
    name: "INPUT__0"
    format: FORMAT_NCHW
    data_type: TYPE_FP32
    dims: [ 3, -1, -1 ]
  }
]
output [
  {
    name: "OUTPUT__0"
    data_type: TYPE_FP32
    dims: [ 2 ]
  }
]

**Expected behavior**

**Comment by CoderHam** [comment]
@Yonghao-Yu can you share the complete log? It looks like the response object is destroyed before it reaches the InferResponseComplete function.

**Comment by Yonghao-Yu** [comment]
> @Yonghao-Yu can you share the complete log? It looks like the response object is destroyed before it reaches the InferResponseComplete function.

When I run “image_client.py” once, the server updates these two log, and there are no other log

**Comment by Yonghao-Yu** [comment]
> > When I run “image_client.py” once, the server updates these two log, and there are no other log
> > You should run the server with --log-verbose=1 and share the entire server log.
> 
> > stderr repeat “checker_process.cpp:1334] TCP health check for task 'jarvis-robot.qrn-qcc-jarvis-cn-bj-yuyonghao-endpoint-fr-model.gpu-bjdxt04.59589a60-f3ae-11eb-8aa9-0242e1520065' returned: 1”
> > Are you certain this originates from inside Triton?

I0803 02:48:42.820678 7237 libtorch_backend.cc:776] The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/torchvision/models/detection/faster_rcnn.py", line 20, in forward
      _2 = False
    if _2:
      ops.prim.RaiseException("Exception")
      ~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    else:
      pass

Traceback of TorchScript, original code (most recent call last):
  File "C:\Users\yuyonghao\Anaconda3\envs\fasterrcnn\lib\site-packages\torchvision\models\detection\generalized_rcnn.py", line 59, in forward
        """
        if self.training and targets is None:
            raise ValueError("In training mode, targets should be passed")
            ~~~~~~~~~~~~~~~~~~ <--- HERE
        if self.training:
            assert targets is not None
RuntimeError: Exception

it seems like triton not support some ops

**Comment by CoderHam** [comment]
@Yonghao-Yu Triton should support the basic torchvision ops. The issue is with the torchscript model preparation. As you can see the issue is caused by this set of checks:
>if self.training and targets is None:
raise ValueError("In training mode, targets should be passed")
if self.training:
assert targets is not None

You should try to run the torchscript model in native pytorch to confirm that the issue is not specific to the model itself.

**Comment by Yonghao-Yu** [comment]
> @Yonghao-Yu Triton should support the basic torchvision ops. The issue is with the torchscript model preparation. As you can see the issue is caused by this set of checks:
> 
> > if self.training and targets is None:
> > raise ValueError("In training mode, targets should be passed")
> > if self.training:
> > assert targets is not None
> 
> You should try to run the torchscript model in native pytorch to confirm that the issue is not specific to the model itself.

OK，thank you
