### ISSUE TITLE
SageMaker HTTPService automatically starts in r21.07/r21.06

### ISSUE THREAD

**Issue by philschmid** [triton-inference-server/server#3178]
**Description**

Triton is starting SageMake HTTP Service by default.
```Bash
I0730 15:43:10.303199 118 grpc_server.cc:4072] Started GRPCInferenceService at 0.0.0.0:8001
I0730 15:43:10.303403 118 http_server.cc:2795] Started HTTPService at 0.0.0.0:8000
I0730 15:43:10.350331 118 sagemaker_server.cc:134] Started Sagemaker HTTPService at 0.0.0.0:8080
I0730 15:43:10.399905 118 http_server.cc:162] Started Metrics Service at 0.0.0.0:8002
```
even the flag is 
https://github.com/triton-inference-server/server/blob/6733c3f35317f74f6b49ea2e8c5a1f29c847e94b/build/CMakeLists.txt#L49

**Triton Information**
What version of Triton are you using?
`nvcr.io/nvidia/tritonserver:21.07-py3`
Are you using the Triton container or did you build it yourself?
Using Triton container

**To Reproduce**
Run Triton Server with an ONNX model. 

**Expected behavior**
SageMaker HTTPService not to start.

**Comment by philschmid** [comment]
Additionally when using even with `--allow-sagemaker=false`
it seems not to start any more
```Bash
I0730 16:05:17.289085 538 grpc_server.cc:4072] Started GRPCInferenceService at 0.0.0.0:8001
I0730 16:05:17.289292 538 http_server.cc:2795] Started HTTPService at 0.0.0.0:8000
I0730 16:05:17.339985 538 http_server.cc:162] Started Metrics Service at 0.0.0.0:8002
```
but i still get `Error: Address already in use (os error 98)` when trying to run something on port 8080

**Comment by philschmid** [comment]
Further investigation on my side:
Tested with `r21.06` 

command to run the container:
```bash
 docker run -t -i \
                        -v $(pwd)/endpoint/repository:/repository \
                        nvcr.io/nvidia/tritonserver:21.06-py3 tritonserver --log-verbose=2 --strict-model-config=false --model-repository=/repository
```
SageMaker Service started
```bash
I0730 16:43:24.079733 1 grpc_server.cc:3144] New request handler for ModelInferHandler, 1
I0730 16:43:24.079755 1 grpc_server.cc:2202] Thread started for ModelInferHandler
I0730 16:43:24.079871 1 grpc_server.cc:3497] New request handler for ModelStreamInferHandler, 3
I0730 16:43:24.079901 1 grpc_server.cc:2202] Thread started for ModelStreamInferHandler
I0730 16:43:24.079913 1 grpc_server.cc:4062] Started GRPCInferenceService at 0.0.0.0:8001
I0730 16:43:24.080600 1 http_server.cc:2795] Started HTTPService at 0.0.0.0:8000
I0730 16:43:24.125107 1 sagemaker_server.cc:134] Started Sagemaker HTTPService at 0.0.0.0:8080
I0730 16:43:24.168152 1 http_server.cc:162] Started Metrics Service at 0.0.0.0:8002
```

Tested with `r21.07` 

command to run the container:
```bash
 docker run -t -i \
                        -v $(pwd)/endpoint/repository:/repository \
                        nvcr.io/nvidia/tritonserver:21.07-py3 tritonserver --log-verbose=2 --strict-model-config=false --model-repository=/repository
```
SageMaker Service started
```bash
I0730 16:43:24.079733 1 grpc_server.cc:3144] New request handler for ModelInferHandler, 1
I0730 16:43:24.079755 1 grpc_server.cc:2202] Thread started for ModelInferHandler
I0730 16:43:24.079871 1 grpc_server.cc:3497] New request handler for ModelStreamInferHandler, 3
I0730 16:43:24.079901 1 grpc_server.cc:2202] Thread started for ModelStreamInferHandler
I0730 16:43:24.079913 1 grpc_server.cc:4062] Started GRPCInferenceService at 0.0.0.0:8001
I0730 16:43:24.080600 1 http_server.cc:2795] Started HTTPService at 0.0.0.0:8000
I0730 16:43:24.125107 1 sagemaker_server.cc:134] Started Sagemaker HTTPService at 0.0.0.0:8080
I0730 16:43:24.168152 1 http_server.cc:162] Started Metrics Service at 0.0.0.0:8002
```

**Comment by CoderHam** [comment]
@philschmid the NGC container has the Sagemaker endpoint enabled by default. You can disable it by using the flag `--allow-sagemaker=false`
@deadeyegoodwin should we change the default value of the cmake flag to match the NGC container ?

**Comment by CoderHam** [comment]
Investigating the cause of this issue below
> I still get Error: Address already in use (os error 98) when trying to run something on port 8080

**Comment by philschmid** [comment]
Hey @CoderHam,

thank you for the quick response. I thought SageMaker endpoints are disabled by default. Referring to this flag
https://github.com/triton-inference-server/server/blob/6733c3f35317f74f6b49ea2e8c5a1f29c847e94b/build/CMakeLists.txt#L49 and discussed in this PR 
https://github.com/triton-inference-server/server/pull/2820#discussion_r630397754

Shouldn`t ` option(TRITON_ENABLE_SAGEMAKER "Include AWS SageMaker API in server" OFF)` excluded SageMaker endpoints?

**Comment by GuanLuo** [comment]
The Triton build overrides the default setting in CMakeLists.txt as it has all feature-wise setting enabled. So the release Docker image will have SageMaker enabled and you should use `--allow-sagemaker` flag to disable it at runtime.

>  I still get Error: Address already in use (os error 98) when trying to run something on port 8080


Can you confirm that the port is used by Triton even if SageMaker is disabled? I ran 21.07 container with SageMaker disabled and I didn't see port 8080 is used by Triton:
```
docker run --network=host -t -i -v $HOME/data/empty_dir:/repository nvcr.io/nvidia/tritonserver:21.07-py3 tritonserver --log-verbose=2 --strict-model-config=false --model-repository=/repository --allow-sagemaker=false

sudo lsof -i -P -n | grep triton
tritonser 30435            root    5u  IPv6 93001599      0t0  TCP *:8001 (LISTEN)
tritonser 30435            root    6u  IPv6 93001603      0t0  TCP *:8001 (LISTEN)
tritonser 30435            root    7u  IPv6 93001604      0t0  TCP *:8001 (LISTEN)
tritonser 30435            root   57u  IPv4 93001627      0t0  TCP *:8000 (LISTEN)
tritonser 30435            root   68u  IPv4 93001633      0t0  TCP *:8002 (LISTEN)
```

**Comment by GuanLuo** [comment]
However, Triton should not start with SageMaker by default as 8080 is a common port for other uses, we will push a fix to turn off SageMaker by default on running Triton.

**Comment by philschmid** [comment]
> Can you confirm that the port is used by Triton even if SageMaker is disabled? I ran 21.07 container with SageMaker disabled and I didn't see port 8080 is used by Triton:

I must have done something wrong. After setting up again and adding `--allow-sagemaker` maybe it was still running or something else. ✅

Could reference the issue when the fix is applied?

**Comment by GuanLuo** [comment]
@philschmid The fix is merged into main
