### ISSUE TITLE
how can I control the cuda memory for models?

### ISSUE THREAD

**Issue by LLsmile** [triton-inference-server/server#3195]
what does gpu-memory-fraction mean? How can I control cuda memory for models? It seems the cuda memory doesn't change after model change.

**Comment by tanmayv25** [comment]
It is a TensorFlow option exposed by Triton. See here for more details: https://github.com/triton-inference-server/tensorflow_backend#--backend-configtensorflowgpu-memory-fractionfloat

It does nothing but sets the [per_process_gpu_memory_fraction](https://github.com/tensorflow/tensorflow/blob/v2.5.0/tensorflow/core/protobuf/config.proto#L19)  to the specified value and [allow_growth ] to true if gpu-memory-fraction is non-zero. See these links for detailed description from TensorFlow. You can do some reading on tensorflow stackoverlow and TF documentation to understand more.

> It seems the cuda memory doesn't change after model change.

Can you elaborate more?

**Comment by LLsmile** [comment]
@tanmayv25 Thanks for your help. I start the triton server with tensorflow,gpu-memory-fraction=0.1and explicit mode, then run different models (such as resnet, mobilenet and so on) with different input size (such as  480*480, 320*320, even 64*64). The cuda memory never change for so many difference. 
Besides, I'm running different models in different versions on the same time, such as ONNX Models and TensorFlow Models. How can I control the cuda memory for these models in triton? Is _--backend-config=onnx,gpu-memory-fraction=0.1_ useful?

**Comment by tanmayv25** [comment]
The frameworks(TF, ONNXRuntime, pyTorch-libtorch) do not expose hooks to exactly control memory usage. Triton will itself go OOM if you exceed GPU memory by keep loading the models.

In our experience with TF we have observed TF does not release the memory it has once allocated. This may be an optimization from their side as TF would not have to re-allocate the memory again for future larger sized input. This is something currently Triton can not provide unless frameworks support these hooks,


> How can I control the cuda memory for these models in triton? Is --backend-config=onnx,gpu-memory-fraction=0.1 useful?

There is no such option for ONNX runtime. You can try using `max_workspace_size_bytes` with [TensorRT optimization](https://github.com/triton-inference-server/onnxruntime_backend#onnx-runtime-with-tensorrt-optimization). This might help preserving the memory footprint.

**Comment by LLsmile** [comment]
@tanmayv25 I keep tensorflow,gpu-memory-fraction=0.0 and restart the triton server and run models with different input size. But the cuda memory keeps the same regardless of the input size.

**Comment by tanmayv25** [comment]
We only have limited hooks to control gpu memory usage by the framework (TF in this case). Try executing inference on TensorFlow Session directly outside Triton with these GPU options. If you still see the same behavior then you should file an issue with TensorFlow project. 

If you are able to control the memory usage of TF models outside Triton, then file a new issue and we will enhance/fix our TF backend.
