### ISSUE TITLE
Include triton backend license files in tritonserver container image.

### ISSUE THREAD

**Issue by msjelly** [triton-inference-server/server#3197]
**Is your feature request related to a problem? Please describe.**
We publish docker images based on nvidia's tritonserver images.  As OSS best practice, container images should include the LICENSE files for runtime OSS dependencies.  I could not locate a copy of the LICENSE files for tritonserver backends in the containter image - e.g. 
https://raw.githubusercontent.com/triton-inference-server/tensorflow_backend/r21.06/LICENSE
https://raw.githubusercontent.com/triton-inference-server/tensorrt_backend/main/LICENSE
https://raw.githubusercontent.com/triton-inference-server/dali_backend/r21.06/LICENSE.md

**Describe the solution you'd like**
For triton backend dependencies, include corresponding license in the released triton inference server container image 
e.g. nvcr.io/nvidia/tritonserver:21.0x-py3

Ideally, for tritonserver backends that share the same LICENSE,  link (soft or hard) to a single copy of the LICENSE.

**Describe alternatives you've considered**
For given release version (/opt/tritonserver/TRITON_VERSION),  attempt to programmatically discover included backends (under /opt/tritonserver/backends) and  then pull a remote copy of the license from github.    Saw following with this approach: 1. tensorrt was not found under /opt/tritonserver/backend 2.  license file names may or may not have .md suffix and r21.06 branch did not exist for [tensorrt backend](https://github.com/triton-inference-server/tensorrt_backend/branches).

**Additional context**

**Comment by tanmayv25** [comment]
We have an ongoing effort of including licenses for 1st order dependencies in the Triton container image. Opening an issue with team to take your considerations into account.

**Comment by tanmayv25** [comment]
TensorRT backend is currently built-in into tritonserver so you don't see it under `/opt/tritonserver/backends`

**Comment by deadeyegoodwin** [comment]
The top-level LICENSE file at /opt/tritonserver covers all of the Triton components. There are additional licenses in the individual backends to cover the software used by that backend (for example, the tensorflow_backend directory contains license for the Google TensorFlow framework).
