### ISSUE TITLE
Clarification of error message: Poll failed for model directory 'x': output 'output.0' for ensemble 'x' is not written

### ISSUE THREAD

**Issue by c-woods-gm** [triton-inference-server/server#3198]
I am getting the error message: "Poll failed for model directory 'x': output 'output.0' for ensemble 'x' is not written", while trying to load an ensemble. Could it be clarified under what conditions this error occurs as I cannot find any documentation describing the error

**Comment by tanmayv25** [comment]
There is no model writing to the `output.0` in your ensemble.  Most probably the ensemble chain is broken and data flow is not reaching the `output.0` tensor.

We have a test for this in our CI. Please take a look at an ensemble that can throw this error.  https://github.com/triton-inference-server/server/blob/main/qa/L0_model_config/autofill_noplatform/ensemble/unreachable_output_2/config.pbtxt

In the example note `prob_2` is only defined as input and output of the model 'fp32_dim1_batch4' and no model connects it to the input `data`.
