### ISSUE TITLE
Error in Build of Triton server using --no-container-build

### ISSUE THREAD

**Issue by SriHarsha-Paladugula** [triton-inference-server/server#3213]
**Description**

While I am trying to build the triton server without docker as mentioned in the build.md facing error as mentioned below

Cloning into 'repo-third-party-src'...
fatal: invalid reference: r20.11
CMake Error at repo-third-party-subbuild/repo-third-party-populate-prefix/tmp/repo-third-party-populate-gitclone.cmake:40 (message):
  Failed to checkout tag: 'r20.11'

**Triton Information**
What version of Triton are you using?
r20.11

Are you using the Triton container or did you build it yourself?
building using without docker following the steps mentioned on build.md

**To Reproduce**
Steps to reproduce the behavior.

clone the latest server github repo of Triton Inference
install the necessary packages mentioned in 
create_dockerfile_buildbase() function of build.py.

command used to run:
./build.py --cmake-dir=<local-
![MicrosoftTeams-image](https://user-images.githubusercontent.com/38833597/128714732-0c69653a-0e3c-4462-b917-73609ba35963.png)
path-to-server>/build --build-dir=citritonbuild  --no-container-build --enable-logging --enable-stats --enable-tracing --enable-metrics --enable-gpu-metrics --enable-gpu --filesystem=gcs --filesystem=azure_storage --filesystem=s3 --endpoint=http --endpoint=grpc --repo-tag=common:r20.11 --repo-tag=core:r20.11 --repo-tag=backend:r20.11 --repo-tag=thirdparty:r20.11 --backend=ensemble --backend=tensorrt --backend=identity:r20.11 --backend=repeat:r20.11 --backend=square:r20.11 --backend=onnxruntime:r20.11 --backend=pytorch:r20.11 --backend=tensorflow1:r20.11 --backend=tensorflow2:r20.11 --backend=openvino:r20.11 --backend=python:r20.11 --backend=dali:r20.11 --backend=fil:r20.11 --repoagent=checksum:r20.11

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
Ubuntu version : 18.04
Cuda Version : 11.1
Tensorrt Version: 7.2.3
Graphics card: Nvidia Geforce  MX130
**Expected behavior**

should be able to build triton server without any hiccups

**Comment by CoderHam** [comment]
@SriHarsha-Paladugula branch tags for releases for the third_party repo were added from 20.12 onwards. Is there a reason you cannot use 20.12?

**Comment by SriHarsha-Paladugula** [comment]
@CoderHam Thanks for the quick update.
Two main reasons to go with this version
1. I have Nvidia Geforece MX130 Gpu (Maxwell Architecture) on my laptop and none of the dockers were supporting this GPU so checking if non container build may support.
2. I have Ubuntu 18.04, Cuda 11.1 and Tensort 7.2.3 already installed on my system and closest release to these matches with 20.11 hence gone with this version

**Comment by CoderHam** [comment]
@SriHarsha-Paladugula you should be using the build.py and source code from r20.11 and not master / 21.07

**Comment by dyastremsky** [comment]
Closed due to inactivity.
