### ISSUE TITLE
Triton Ensemble Model - seems to be executing each model multiple times.

### ISSUE THREAD

**Issue by prateek-ponnuru** [triton-inference-server/server#3215]
**Description**
I am trying to deploy a triton Ensemble consisting of a pre.py - model - post.py pipeline. I have some debugging statements in the pre and post scripts that should ideally be printed so -

pre-started
pre-ended
post-started
post-ended

However, this is the actual output -

preprocess started
preprocess finished
W0809 15:02:10.547689 7445 pinned_memory_manager.cc:133] failed to allocate pinned system memory: no pinned memory pool, falling back to non-pinned system memory
preprocess started
postprocess started
preprocess finished
preprocess started
preprocess finished
preprocess started
postprocess finished
postprocess started

Building a reproducible code by removing all the sensitive information is a big effort, so before I do that, I just wanted to confirm the way I designed my pipeline is not the reason for the issue. Here is the ensemble config -

```
platform: "ensemble"
max_batch_size: 0
input [
    {
        name: "IMAGE_NAME"
        data_type: TYPE_STRING
        dims: [ 1 ]
    }
]
output [
    {
        name: "IMAGES_4SEGMENTATION"
        data_type: TYPE_FP32
        dims: [ 224, 224, 3 ]
    }
]
ensemble_scheduling {
    step [
        {
            model_name: "preproc-yolo"
            model_version: -1
            input_map {
                key: "INPUT_PRE"
                value: "IMAGE_NAME"
            }
            output_map [
                {
                    key: "RESIZED"
                    value: "IMAGE_RESIZED"
                },
                {
                    key: "ORIGINAL"
                    value: "IMAGE_ORIGINAL"
                },
                {
                    key: "NAME"
                    value: "IMAGE_NAME"
                }
            ]

        },
        {
            model_name: "YOLO-tf2"
            model_version: -1
            input_map {
                key: "input_1"
                value: "IMAGE_RESIZED"
            }
            output_map [
                {
                    key: "conv2d_9"
                    value: "yolo_out13x13"
                },
                {   key: "conv2d_12"
                    value: "yolo_out26x26"
                }
            ]
        },
        {
            model_name: "postproc-yolo"
            model_version: -1
            input_map [
                {
                    key: "BOXES1"
                    value: "yolo_out13x13"
                },
                {
                    key: "BOXES2"
                    value: "yolo_out26x26"
                },
                {
                    key: "ORIGINAL_IMAGE"
                    value: "IMAGE_ORIGINAL"
                },
                {
                    key: "NAME"
                    value: "IMAGE_NAME"
                }
            ]
            output_map [
                {
                    key: "OUTPUT4UNET"
                    value: "IMAGES_4SEGMENTATION"
                }
            ]
        }
    ]
}
```

**Triton Information**
21.06

Are you using the Triton container or did you build it yourself?
I have customized the container to build the python environment as I am using custom libraries

I want to understand that this kind of input and output map is acceptable or not. If yes, then there could be some issue and I shall work on providing reproducible code.

Thanks,
Prateek

**Comment by Tabrizian** [comment]
In Python backend it could be that the print statements are not flushed out and are printed once the buffer is full. Can you try again with `print('Your Print statement', flush=True)` to see whether you still the same issue?

**Comment by prateek-ponnuru** [comment]
Thanks for the response @Tabrizian. However, that was not the issue. 

```
step [
        {
            model_name: "preproc-yolo"
            model_version: -1
            input_map {
                key: "INPUT_PRE"
                value: "IMAGE_NAME"
            }
            output_map [
                {
                    key: "RESIZED"
                    value: "IMAGE_RESIZED"
                },
                {
                    key: "ORIGINAL"
                    value: "IMAGE_ORIGINAL"
                },
                {
                    key: "NAME"
                    value: "IMAGE_NAME"
                }
            ]

        },

``` 

The Tensor 'IMAGE_NAME' was used both as an input and output, which resulted in a loop.
