### ISSUE TITLE
 Is dynamic batch  trt model file required when using dynamic_batching

### ISSUE THREAD

**Issue by FreshZZ** [triton-inference-server/server#3218]
Is dynamic batch  trt model file required when using dynamic_batching?
If I have to convert a trt model with dynamic batch when using dynamic_batching to improve throughput

**Comment by aramesh7** [comment]
Dynamic batching is a property of the triton inference server, and not any specific model. It can be turned on by modifying the model config file https://github.com/triton-inference-server/server/blob/main/docs/optimization.md#dynamic-batcher. 

As long as the model supports batching, it should be possible to use the dynamic batcher to improve your throughput.

**Comment by dyastremsky** [comment]
Closed due to inactivity.
