### ISSUE TITLE
sending an output with wrong datatype (e.g. integers > 256 as datatype uint8) should fail

### ISSUE THREAD

**Issue by moritzhambach** [triton-inference-server/server#3219]
**Description**
accidentally declared the wrong datatype (TYPE_UINT8) for integers above 256 as output of the triton server (python backend). Instead of raising an error, it sends the values modulo 256. makes it hard to debug...

**Triton Information**
What version of Triton are you using?
nvcr.io/nvidia/tritonserver:21.06-py3

Are you using the Triton container or did you build it yourself?
new one with just some python packages on top 

**To Reproduce**
send integer 257 as uint8 output

**Expected behavior**
raise error when declared datatype of input / output does not match input / output

**Comment by Tabrizian** [comment]
Thanks for reporting this issue. We have a bug already filed to fix this issue in Python backend.

**Comment by Tabrizian** [comment]
I looked into this. Python backend relies on NumPy for CPU tensors. It looks like this is a NumPy problem more than Python backend. Also, Python backend will not check the datatypes and shapes for output tensors because of possible performance degradation.

```
>>> import numpy as np
>>> x = np.asarray(257, dtype=np.uint8)
>>> x
array(1, dtype=uint8)
```
