### ISSUE TITLE
Install Triton Server From Source Code On Jetson Nano

### ISSUE THREAD

**Issue by sarperkilic** [triton-inference-server/server#3224]
**Description**

Hello, 

I follow the latest release for jetson jetpack 4.6 support (https://github.com/triton-inference-server/server/releases/tag/v2.12.0). 

I download the Source code (tar.gz) file and tritonserver2.12.0-jetpack4.6.tgz file.

I understand that, ı have to run build.py script in Source code (tar.gz) file  to compile Triton Server,

Am I right?

And, when I run following build.py script, I got path error. Could you help me how can I compile it? What should I change?

sudo ./build.py --cmake-dir=./build/ --build-dir=./build/ --no-container-build --enable-logging --enable-stats --enable-tracing --enable-metrics --enable-gpu-metrics --enable-gpu --filesystem=gcs --filesystem=azure_storage --filesystem=s3 --endpoint=http --endpoint=grpc --repo-tag=common:main --repo-tag=core:main --repo-tag=backend:main --repo-tag=thirdparty:main --backend=ensemble --backend=tensorrt --backend=identity:main --backend=repeat:main --backend=square:main --backend=onnxruntime:main --backend=pytorch:main --backend=tensorflow1:main --backend=tensorflow2:main --backend=openvino:main --backend=python:main --backend=dali:main --backend=fil:main --repoagent=checksum:main

CMake Error: The source directory "/home/inovako/Downloads/server-2.12.0/build/tritonserver/build/build" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
error: cmake failed

And what is the difference between Source code (tar.gz) file and tritonserver2.12.0-jetpack4.6.tgz file. 
 

**Triton Information**
What version of Triton are you using?

Are you using the Triton container or did you build it yourself?
I built myself

**To Reproduce**

sudo ./build.py --cmake-dir=./build/ --build-dir=./build/ --no-container-build --enable-logging --enable-stats --enable-tracing --enable-metrics --enable-gpu-metrics --enable-gpu --filesystem=gcs --filesystem=azure_storage --filesystem=s3 --endpoint=http --endpoint=grpc --repo-tag=common:main --repo-tag=core:main --repo-tag=backend:main --repo-tag=thirdparty:main --backend=ensemble --backend=tensorrt --backend=identity:main --backend=repeat:main --backend=square:main --backend=onnxruntime:main --backend=pytorch:main --backend=tensorflow1:main --backend=tensorflow2:main --backend=openvino:main --backend=python:main --backend=dali:main --backend=fil:main --repoagent=checksum:main

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**

Compiled triton inference server

**Comment by CoderHam** [comment]
@sarperkilic as the release notes indicate you do not need to build Triton server /client libraries and can use the same out of the box from the tar file. You must however install the necessary dependencies listed in the release notes.
