### ISSUE TITLE
Can we fine tune a model with triton server?

### ISSUE THREAD

**Issue by nischal-sanil** [triton-inference-server/server#3225]
Hello,

I am working on a project where given the input data, I have to finetune the model during inference. 

is it feasible to use triton server for such a scenario?

Thanks in advance.

**Comment by aramesh7** [comment]
What type of parameters do you need to finetune?

**Comment by aramesh7** [comment]
Triton is an inference server only, and does not facilitate backpropagation/training of that kind. You may be able to use Triton as the inference engine part of a larger system to do that. @GuanLuo Is there is anything in Triton that can make @nischal-sanil 's task easier?

**Comment by Tabrizian** [comment]
@nischal-sanil It is possible to use Python backend to implement any custom logic on your model.

 https://github.com/triton-inference-server/python_backend

**Comment by nischal-sanil** [comment]
Thank you @aramesh7 and @Tabrizian , for taking the time to reply.
