### ISSUE TITLE
Load triton_python_backend_stub from S3 model repository

### ISSUE THREAD

**Issue by c-woods-gm** [triton-inference-server/server#3227]
I am trying to load a python model from a model repository based in an S3 bucket. The triton_python_backend_stub is located in the model directory within the repository. When I try to load the model I am getting the following error:

```
I0812 14:50:59.211734 25 python.cc:918] Starting Python backend stub: export LD_LIBRARY_PATH=/tmp/python_env_pkhKPf/0/lib:$LD_LIBRARY_PATH; source /tmp/python_env_pkhKPf/0/bin/activate && exec /tmp/folderyPJDZi/triton_python_backend_stub /tmp/folderyPJDZi/1/model.py /interpreter_CPU_0 67108864 67108864 1 /opt/tritonserver/backends/python
bash: /tmp/folderyPJDZi/triton_python_backend_stub: Permission denied
bash: line 0: exec: /tmp/folderyPJDZi/triton_python_backend_stub: cannot execute: Permission denied
```
It looks as though the triton_python_backend_stub has not got executable permissions after being downloaded from the S3 bucket. Is this a bug or something that is not supported?

**Comment by Tabrizian** [comment]
@c-woods-gm Using [Custom Execution Environments](https://github.com/triton-inference-server/python_backend#using-custom-python-execution-environments) with S3 is not supported yet. We have a ticket to fix this for S3 but we have not been able to get to it yet.

**Comment by Tabrizian** [comment]
1.
