### ISSUE TITLE
tritonserver:<version>py3-min Dockerfile

### ISSUE THREAD

**Issue by mgiessing** [triton-inference-server/server#3234]
Hello,

I'm trying to build the triton inference server on ppc64le architecture, but I'm wondering where I can get the source Dockerfile for the mentioned container?

I was able to recreate the triton infernence server using the nvidia/cuda-ppc64le:11.2.2-devel image as the base, but when starting the container I get the error that `/usr/local/bin/checkSMVER.sh` is not found as well as the command `deviceQuery`.

When I inspect the docker pull nvcr.io/nvidia/tritonserver:21.07-py3-min image on x86 I can see that those binaries are found there...but now I'm wondering where I can see how this source image was basically built...?

Thanks!

**Comment by Tabrizian** [comment]
@mgiessing The build process is explained in [build.md](https://github.com/triton-inference-server/server/blob/main/docs/build.md). Let us know if the documentation is not clear and you need additional information.

**Comment by mgiessing** [comment]
Hi @Tabrizian !

Yes, I followed the build along on an x86 system and also had a look into the `build.py` script.
Three images are built in total (tritonserver_builder_image, tritonserver_build and finally tritonserver)

However if I check the "first" image going to be built in the [create_dockerfile_buildbase](https://github.com/triton-inference-server/server/blob/main/build.py#L527) function there is another base image referenced (it comes from [argmap['BASE_IMAGE']](https://github.com/triton-inference-server/server/blob/main/build.py#L533))

That variable is referenced by [dockerfileargmap](https://github.com/triton-inference-server/server/blob/main/build.py#L919)

dockerfileargmap is referenced by [this](https://github.com/triton-inference-server/server/blob/main/build.py#L896) variable

And here we go! That is the root of all images to my understanding:
--> https://github.com/triton-inference-server/server/blob/main/build.py#L883
```
[...]
    if 'base' in images:
        base_image = images['base']
    elif target_platform() == 'windows':
        base_image = 'mcr.microsoft.com/dotnet/framework/sdk:4.8'
    else:
        base_image = 'nvcr.io/nvidia/tritonserver:{}-py3-min'.format(
            FLAGS.upstream_container_version)
[...]
```

How do I know how nvcr.io/nvidia/tritonserver:{}-py3-min is being built? I don't see any further reference?

For x86 systems it is no problem at all, becuase the image will just get pulled from nvcr.io to build the others, but for different architectures (such as ppc64le or aarch64) I'd like to know how to build that.

If I miss something there I'm happy to hear :-) 
Thanks!

**Comment by Tabrizian** [comment]
@mgiessing Unfortunately, the Dockerfile for the min container is not available. You can try modifying the `entrypoint.sh` to not use the `deviceQuery` and `/usr/local/bin/checkSMVER.sh` to see whether it fixes your issue.

**Comment by mgiessing** [comment]
@Tabrizian 
I just build `deviceQuery` using the [cuda-samples](https://github.com/NVIDIA/cuda-samples/) repo and got the `checkSMVER.sh` script from the x86 container, but I always face new challenges without this min-Dockerfile when progressing :/



> @mgiessing Unfortunately, the Dockerfile for the min container is not publicly available. You can try modifying the `entrypoint.sh` to not use the `deviceQuery` and `/usr/local/bin/checkSMVER.sh` to see whether it fixes your issue.


Does this mean the min - Dockerfile/Container image is NVIDIA proprietary or it is - for some reason - just not publicly shared?
If it is not proprietary: Is there a possibility to get the Dockerfile somehow or do you know if it is possible to reverse engineer it ?

Otherwise it is extreme difficult to port/develop for other CPU architectures.

Thanks!

**Comment by Tabrizian** [comment]
Using the min container is not the recommended way for building Triton on unsupported platforms. Please follow the documentation and let us know if it is not clear or needs improvment:

 https://github.com/triton-inference-server/server/blob/main/docs/build.md#building-on-unsupported-platforms

Currently, it is not possible to get the Dockerfile for min container.

**Comment by mgiessing** [comment]
Thanks for clarification!
