### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/folder31uWBi/1/model.py'

### ISSUE THREAD

**Issue by CPFelix** [triton-inference-server/server#3237]
**Description**
When I use the Python Backend, becasue there are preprocess.py and postprocess.py, I need to rename the python model name.But after I definit "default_model_filename", I get the error:
"
I0817 02:55:35.150648 1 python.cc:604] TRITONBACKEND_ModelInstanceInitialize: post_detection_0 (CPU device 0)
Traceback (most recent call last):
  File "/opt/tritonserver/backends/python/startup.py", line 382, in <module>
    python_host = PythonHost(module_path=FLAGS.model_path)
  File "/opt/tritonserver/backends/python/startup.py", line 172, in __init__
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 915, in get_code
  File "<frozen importlib._bootstrap_external>", line 972, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/folder31uWBi/1/model.py'
I0817 02:55:35.595524 1 onnxruntime.cc:1787] TRITONBACKEND_ModelInitialize: densenet_onnx (version 1)
I0817 02:55:35.596162 1 onnxruntime.cc:1830] TRITONBACKEND_ModelInstanceInitialize: densenet_onnx (GPU device 0)
WARNING: Since openmp is enabled in this build, this API cannot be used to configure intra op num threads. Please use the openmp environment variables to control the number of threads.
I0817 02:55:41.053828 1 model_repository_manager.cc:1239] successfully loaded 'densenet_onnx' version 1
E0817 02:55:45.171304 1 model_repository_manager.cc:1242] failed to load 'post_detection' version 1: Internal: failed to connect to all addresses
"
It seems the "default_model_filename" doesn't work?
**Triton Information**
21.03

Are you using the Triton container or did you build it yourself?
Triton container
**To Reproduce**
None

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
config.pbtxt:
"
name: "post_detection"
backend: "python"

input [
  {
    name: "INPUT"
    data_type: TYPE_FP32
    dims: [ 1,7001,1,1]
  }
]

output [
  {
    name: "OUTPUT"
    data_type: TYPE_FP32
    dims: [-1, 6]
  }
]
instance_group [ { kind: KIND_CPU }]
default_model_filename:"post_detection.py"
"
**Expected behavior**
Triton can load python model whose name is not "model.py".

**Comment by CPFelix** [comment]
I also try rename "densenet_onnx" model and it can be load successfully.It seems only the python model's name can't modify.

**Comment by Tabrizian** [comment]
@CPFelix Thanks for bringing this to our attention. I have filed a bug to fix this.
