### ISSUE TITLE
Dockerfile in building triton

### ISSUE THREAD

**Issue by gioipv** [triton-inference-server/server#3244]
* Problem
Hello
I am using triton inference server. And when i using docker image 21.07. I have to install a package to fix issues about related to libGL.so.1. 
This is link issues: https://github.com/conda-forge/pygridgen-feedstock/issues/10#issuecomment-365914605
I rebuild a triton image with docker. Refer to : https://github.com/triton-inference-server/server/blob/r21.07/docs/build.md#building-with-docker
* Solution
Before build triton with `./build.py` command.
I add a line into `build.py` file at `line 706` in a create dockerfile function
```
RUN apt-get -yqq update && apt -yqq install libgl1-mesa-glx
```
I think this is a common problem. So, should we add the line above into `build.py` file of the [repo](https://github.com/triton-inference-server/server).

**Comment by Tabrizian** [comment]
@gioipv Can you please elaborate on where you see that import error? Do you see this when trying to use the Python client?

**Comment by gioipv** [comment]
Yup. When I am using triton images version 21.07.
Using python backend, I also build [python backend stub and conda-pack](https://github.com/triton-inference-server/python_backend#using-custom-python-execution-environments) for my conda envs.
In the file `model.py` of my model of [model repository](https://github.com/triton-inference-server/server/blob/r21.07/docs/model_repository.md#python-models) , I import cv2 by the line `import cv2` 
When run triton by docker run:

`docker run \
--gpus=1 \
--rm \
-it \
-p8000:8000 -p8001:8001 -p8002:8002 \
-v /home/gioipv/workspaces/triton_template/server/model_repos:/models \
nvcr.io/nvidia/tritonserver:21.07-py3 \
tritonserver --model-repository=/models
`
It will raise an error when load the model.
`
I0820 15:36:16.317719 57 model_config_utils.cc:1523] 	ModelConfig::sequence_batching::max_sequence_idle_microseconds
I0820 15:36:16.317734 57 model_config_utils.cc:1523] 	ModelConfig::sequence_batching::oldest::max_queue_delay_microseconds
I0820 15:36:16.317753 57 model_config_utils.cc:1523] 	ModelConfig::version_policy::specific::versions
I0820 15:36:16.318444 57 python.cc:1275] Using Python execution env /models/glasses.tar.gz
I0820 15:36:16.322143 57 python.cc:1497] TRITONBACKEND_ModelInstanceInitialize: glasses_model_0 (GPU device 0)
I0820 15:36:16.324814 57 backend_model_instance.cc:105] Creating instance glasses_model_0 on GPU 0 (7.5) using artifact ''
I0820 15:37:39.109068 94 python.cc:918] Starting Python backend stub: export LD_LIBRARY_PATH=/tmp/python_env_HsfIYt/0/lib:$LD_LIBRARY_PATH; source /tmp/python_env_HsfIYt/0/bin/activate && exec /models/glasses_model/triton_python_backend_stub /models/glasses_model/1/model.py /glasses_model_0_GPU_0 67108864 67108864 57 /opt/tritonserver/backends/python
0820 15:37:42.850268 94 pb_stub.cc:639] ImportError: libGL.so.1: cannot open shared object file: No such file or directory

At:
  /tmp/python_env_HsfIYt/0/lib/python3.7/site-packages/cv2/__init__.py(5): <module>
  <frozen importlib._bootstrap>(219): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(728): exec_module
  <frozen importlib._bootstrap>(677): _load_unlocked
  <frozen importlib._bootstrap>(967): _find_and_load_unlocked
  <frozen importlib._bootstrap>(983): _find_and_load
  /models/glasses_model/1/model.py(8): <module>
  <frozen importlib._bootstrap>(219): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(728): exec_module
  <frozen importlib._bootstrap>(677): _load_unlocked
  <frozen importlib._bootstrap>(967): _find_and_load_unlocked
  <frozen importlib._bootstrap>(983): _find_and_load
`
I see that, It is
`
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
`
So i fix issues by install packages above in the container before run triton server by 
`tritonserver \
--model-control-mode=explicit \
--model-repository=/models --log-verbose 20
`
So I think it is a common problem.

**Comment by Tabrizian** [comment]
It looks like it is more a problem with the way conda packages the dependencies. We can't change Triton container to include dependencies for Python packages. I think the only work around for now would be to create another Docker container that contains the dependencies required for your Python environment.

**Comment by gioipv** [comment]
yup, 
I think, for now, triton only support with conda .and I also add the line above into creating dockerfile function with `using python backend` in the file `build.py`
anyway, this is simply my opinion. Thanks you for your support.

**Comment by csvance** [comment]
@gioipv If you install opencv through pip, you can install opencv-python-headless in order to avoid the dependency. conda-pack works just fine with pip packages as well.

Conda OpenCV also uses OpenMP for multi threading which doesn't play nicely with many computing paradigms without a ton of extra configuration and debugging. The pip packaging of OpenCV uses vanilla pthreads, which are much easier to work with and play nicer with other things.
