### ISSUE TITLE
Triton Ensemble model: Unable to get multiple output

### ISSUE THREAD

**Issue by letstryy** [triton-inference-server/server#3246]
Hi,

I was using triton ensemble model with two models: model_1_0 and model_1_0 with same input and want output from each of these models.
I referred to the ensemble model for image classification and segmentation with model configuration mentioned in the architecture: https://github.com/triton-inference-server/server/blob/r21.07/docs/architecture.md 

ensemble:
config.pbtxt
name: "ensemble"
platform: "ensemble"
max_batch_size: 1
input [{
    name: "feature_input"
    data_type: TYPE_FP32
    dims: [1,34]
  }]
output [{
    name: "variable"
    data_type: TYPE_FP32
    dims: [1,1]
  },
{
    name: "variable1"
    data_type: TYPE_FP32
    dims: [1,1]
  } ]
ensemble_scheduling {
  step [
    {
      model_name: "model_1_0"
      model_version: -1
      input_map {
        key: "feature_input"
        value: "feature_input"
      }
      output_map {
        key: "variable"
        value: "variable"
      }},
    {
      model_name: "model_1_1"
      model_version: -1
      input_map {
        key: "feature_input"
        value: "feature_input"
      }
      output_map {
        key: "variable_model"
        value: "variable1"
      } } ]}
It gives me error: model_1_1,UNAVAILABLE: Invalid argument: unexpected inference output 'variable_model', allowed outputs are: variable.
I am unable to get multiple output. Need help here, maybe i am missing something here!

**Comment by Tabrizian** [comment]
@letstryy The "key" parameter in the output map must exist in the list of outputs in the model config of the model in each stage. The reason that you are seeing this error is because "variable_model" is not in the list of outputs of "model_1_1".

**Comment by letstryy** [comment]
@Tabrizian Sharing the config.pbtxt for model_1_1
name: "model_1_1"
platform: "onnxruntime_onnx"
backend: "onnxruntime"
max_batch_size: 0
input [
    {
        name: "feature_input"
        data_type: TYPE_FP32
        dims: [1,34]
        }
]
output: [
    {
        name: "variable_model"
        data_type: TYPE_FP32
        dims: [1,1]
        }
]
instance_group: [
    {
        name: "model_1_1"
        kind: KIND_CPU
        count: 1
        }
]

**Comment by GuanLuo** [comment]
The model config only describes the properties of model and it seems like the model itself doesn't have a output called  `variable_model`. Can you double check if  `model_1_1` model generates `variable_model` output? (i.e. use Netron to visualize the ONNX model)
