### ISSUE TITLE
Build python backend error using docker

### ISSUE THREAD

**Issue by azraelkuan** [triton-inference-server/server#3253]
**Description**
build python backend from r21.07 failed

**Triton Information**
What version of Triton are you using?
r21.07

Are you using the Triton container or did you build it yourself?
i build the latest python backend using r21.07 docker.

**To Reproduce**
```cmake -DTRITON_ENABLE_GPU=ON -DTRITON_BACKEND_REPO_TAG=r21.07 -DTRITON_COMMON_REPO_TAG=r21.07 -DTRITON_CORE_REPO_TAG=r21.07 -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/install ..```

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**
```
-- RapidJSON found. Headers: /usr/include
-- RapidJSON found. Headers: /usr/include
-- Using CUDA 11.4
-- pybind11 v2.6.2 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Configuring done
CMake Error in CMakeLists.txt:
  Imported target "pybind11::embed" includes non-existent path

    "/usr/include/python3.8"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

**Comment by azraelkuan** [comment]
one more question: how to print log in the backend, it seems print do not work with python backend.

**Comment by gioipv** [comment]
Hello,
I think python backend is availble on triton docker images ver 21.07. Have you custom python backend for your purpose ?

I have tried building python backend from [source](https://github.com/triton-inference-server/python_backend#building-from-source)
I clone the [repos](https://github.com/triton-inference-server/python_backend#building-from-source) abd I am using conda and activate my envs. and using `cmake` command. I builded python backend without the problem that you met.
my cmake is cmake version 3.21.1
I think maybe you try set python path and try. could you please talk to me if you build completely without error

**Comment by Tabrizian** [comment]
@azraelkuan Do you have `python3-dev` installed on your system? Are you trying the build inside the Triton container?

**Comment by azraelkuan** [comment]
sloved by me. thanks
