### ISSUE TITLE
Missing package configuration: prometheus-cpp

### ISSUE THREAD

**Issue by mgiessing** [triton-inference-server/server#3256]
Hi, did anyone else tried to build triton based on centos8 and encountered this error when enabling metrics?

```
CMake Error at CMakeLists.txt:240 (find_package):
  Could not find a package configuration file provided by "prometheus-cpp"
  with any of the following names:

    prometheus-cppConfig.cmake
    prometheus-cpp-config.cmake

  Add the installation prefix of "prometheus-cpp" to CMAKE_PREFIX_PATH or set
  "prometheus-cpp_DIR" to a directory containing one of the above files.  If
  "prometheus-cpp" provides a separate development package or SDK, be sure it
  has been installed.
```

I can see in the logs that prometheus-cpp-v0.7.0 is downloaded and installed, but somehow the linking seem not to work in centos compared to Ubuntu?

**Comment by mgiessing** [comment]
If someone else face this problem:
You need to compile & install prometheus manually in the `build.py` to overcome this issue:
For r21.07 it needs prometheus-cpp v0.7.0 (maybe for x86 there is an RPM out there - for Power I haven't found any)

Build instruction from the github page:

```
RUN git clone https://github.com/jupp0r/prometheus-cpp.git && cd prometheus-cpp && git checkout v0.7.0 && \
        git submodule init && git submodule update && mkdir _build && cd _build && \
        cmake .. -DBUILD_SHARED_LIBS=ON && make -j 4 && make install
```

**Comment by Tabrizian** [comment]
Thanks for sharing the solution to this.
