### ISSUE TITLE
Build modified triton from source in Jetson

### ISSUE THREAD

**Issue by Levocetirizine** [triton-inference-server/server#3262]
**Is your feature request related to a problem? Please describe.**
I am trying to add some new features to triton server by modifying its source code. I have noticed that there are no guides for building triton in Jetson for now, and it's recommended to use the pre-compiled binary release. 

I tried to run build.py on my Jetson Xavier and it failed to compile.

**Describe the solution you'd like**
A build.py for Jetson will be great.

**Describe alternatives you've considered**
Actually, what I am thinking of is to make ensemble model more dynamic. Currently the topological shape of the ensemble graph is fixed (only with some prunes), I wish triton can send the output tensor to different step according to the output tensor of previous step in runtime.  (maybe by some pre-defined control outputs)

**Comment by Tabrizian** [comment]
cc @CoderHam

**Comment by CoderHam** [comment]
@Levocetirizine I would need a little more information on the failure you saw to be able to help you. 
What you are suggesting is a ensemble pipeline with custom user logic and for this you would likely need to build a custom backend which will perform the necessary actions.

**Comment by Levocetirizine** [comment]
@CoderHam  Thank you for your reply, the error occurs when the onnx backend is being built. However I found it's okay, I just ignored the error and used the onnx backend in the official binary release as a workaround. 

About the ensemble model, do you suggest that I should write a brand-new backend rather than modifying the current code? I am not sure if it's possible since ensemble model also relies on the ensemble scheduler, which is one of the core codes. I have went through ensemble_scheduler.cc and I think adding features based on current scheduler code is also possible...

**Comment by CoderHam** [comment]
For the onnxruntime backend build, we use a docker based approach on x86 but for jetson you must build the onnxruntime library on Jetson yourself and  point to the path of the library using the respective args from build.py
```
--library-paths=onnxruntime:$PATH_TO_ONNXRUNTIME
```

**Comment by CoderHam** [comment]
PS: refer to onnxruntime docs for instructions to build on jetson. One useful resource would be https://onnxruntime.ai/docs/how-to/build/inferencing.html#native-compiling-on-linux-arm-device

**Comment by Levocetirizine** [comment]
Thank you for your information, my problem has been solved.
