### ISSUE TITLE
How to Add Custom Models with  different framework in Triton inference server and have to serve the model and utilize the api

### ISSUE THREAD

**Issue by manish0079** [triton-inference-server/server#3263]
Hiii

I have followed this [https://github.com/triton-inference-server/server/blob/main/docs/quickstart.md#install-triton-docker-image](url) and setup up the basic flow of inference server, I could be able to do for the dense net model and see the inference image, but I have deeplab model custom trained, I want to integrate triton inference for that, Not only deepab, I have many deep learning models with a different framework, Plz help me to know what is the easiest or optimal way to do it, I know we have to change in ONNX Format but I m not getting what to do exactly how to add custom trained models and all

Hoping for ur reply

Thank u

**Comment by Tabrizian** [comment]
Triton is able to work with many different frameworks. There is detailed information about this and how you should setup your model repository in the link below:

 https://github.com/triton-inference-server/server#user-documentation

**Comment by manish0079** [comment]
Can i get the conversion script for ONNX Format?

**Comment by GuanLuo** [comment]
We don't have the conversion script between different model formats, you should consult with the framework maintainers for conversion guidance. ONNX format is a common format so I think many popular frameworks do support exporting models to ONNX.

And as @Tabrizian mentioned, Triton supports multiple frameworks so if some of your models are already in supported framework, you can use Triton to serve them directly without converting to ONNX format.

**Comment by manish0079** [comment]
Hii 

I have been able to load the yolov5s model, but I am getting the model output as bytes,Is there any way to convert bytes into tensors or pass the bytes directly?
