### ISSUE TITLE
Sagemaker and KFServing port clash

### ISSUE THREAD

**Issue by swapkh91** [triton-inference-server/server#3264]
I'm tring to deploy KFServing inference using Triton, but it gives the following error 
`The server cannot listen to SageMaker requests and HTTP requests at the same port`

KFServing uses port `8080`, same as Sagemaker

I'm using triton image `21.07-py3`

Is there some way to change the port for Sagemaker?

Earlier I was using image `20.10-py3`, so it worked fine. But now I have to use FIL backend for XGBoost models.

**Comment by Tabrizian** [comment]
You can start triton with ` --allow-sagemaker false` flag to disable Sagemaker.

**Comment by swapkh91** [comment]
@Tabrizian thanks for the reply, its working now.
