### ISSUE TITLE
Triton repository agent checksum - readme broken link

### ISSUE THREAD

**Issue by vignif** [triton-inference-server/server#3282]
**Description**
In the [readme](https://github.com/triton-inference-server/checksum_repository_agent) under the section `Using the Checksum Repository Agent` a link is pointing to `https://github.com/triton-inference-server/server/blob/master/src/core/model_config.proto`, which returns a 404 page.

Where is that file stored now?

**Comment by dyastremsky** [comment]
Link fixed. Closing out the issue.
