### ISSUE TITLE
Build error withou docker

### ISSUE THREAD

**Issue by ToTheMonn** [triton-inference-server/server#3288]
**Description**
Re-run cmake no build system arguments
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- RapidJSON found. Headers: /usr/include
-- RapidJSON found. Headers: /usr/include
-- Using protobuf 3.8.0.0
-- Found CUDAToolkit: /usr/local/cuda/include (found version "11.2.67") 
-- Using CUDA 11.2
-- Using CUDA 11.2
-- Using Boost 1.77.0
-- Using libevent 2.1.8
-- Using protobuf 3.8.0.0
-- Using prometheus-cpp 
-- Using libevhtp 1.2.18
-- Using tracing 
-- Using prometheus-cpp 
-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
RE2_LIBRARY
            linked by target "main" in directory /home/server/src/servers

**Triton Information**
r21.02

**Comment by KrisChou** [comment]
I pulled your official docker image and tried to compile the source code in the created container . But it doesn't work.

**Comment by GuanLuo** [comment]
If you want to build with docker, then you just need to remove `--no-container-build` when you `run build.py`
