### ISSUE TITLE
Can NMT models can be deployed with triton inference server ?

### ISSUE THREAD

**Issue by aj7tesh** [triton-inference-server/server#3300]
Can NMT models (Transformer large) trained using fairseq (pytorch) be deployed using triton's inference server? if so, how do i go about it and model conversions etc.

**Comment by dyastremsky** [comment]
Looking at #376, NMT models do not seem to be supported. If you can convert the model to a supported framework on your end, then you could run it.

(Tagging @deadeyegoodwin for visibility.)

**Comment by aj7tesh** [comment]
> Looking at #376, NMT models do not seem to be supported. If you can convert the model to a supported framework on your end, then you could run it.
> 
> (Tagging @deadeyegoodwin for visibility.)

supported framework as in? its pytorch and fairseq wrapper on top of it.

**Comment by dyastremsky** [comment]
Understood. @deadeyegoodwin, do you know whether NMT models are now supported?

**Comment by deadeyegoodwin** [comment]
Triton supports touchscript models but you must export your pytorch to torchscript... there is a lot of documentation on this. I don't know about fairseq and how that impacts the generation of torchscript.

You can also run your pytorch script as is by capturing all dependencies, etc. with miniconda and the using the Python backend, as described here: https://github.com/triton-inference-server/python_backend#using-custom-python-execution-environments

You may also find some helpful information at https://github.com/NVIDIA/DeepLearningExamples
