### ISSUE TITLE
http client for a model with multiple outputs

### ISSUE THREAD

**Issue by sourabh-burnwal** [triton-inference-server/server#3303]
Hello,
Working on a model (pytorch converted to onnx) with multiple outputs. I'm providing the config.pbtxt

name: "model_xyz"
platform: "onnxruntime_onnx"
backend: "onnxruntime"
max_batch_size: 0
input [
	{
		name: "input"
		data_type: TYPE_UINT8
		dims: [-1,3,-1,-1]
	}
]
output [
	{
		name: "887"
		data_type: TYPE_FP32
		dims: [1,2,128,128]
	},
	{
		name: "818"
		data_type: TYPE_FP32
		dims: [1,8,128,128]
	},
	{
		name: "882"
		data_type: TYPE_FP32
		dims: [1,2,128,128]
	},
	{
		name: "877"
		data_type: TYPE_FP32
		dims: [1,2,64,64]
	},
	{
		name: "686"
		data_type: TYPE_FP32
		dims: [1,8,64,64]
	},
	{
		name: "872"
		data_type: TYPE_FP32
		dims: [1,2,64,64]
	},
	{
		name: "554"
		data_type: TYPE_FP32
		dims: [1,8,32,32]
	},
	{
		name: "867"
		data_type: TYPE_FP32
		dims: [1,2,32,32]
	},
	{
		name: "output"
		data_type: TYPE_FP32
		dims: [-1,2,32,32]
	}
]

How to specify the 'outputs' object in requestGenerator function?

If I do it it like this:
output_name = ['887', '818', '882', '877', '686', '872', '554', '867', 'output']
outputs = [
        client.InferRequestedOutput(output_name, class_count=9)
    ]

I'm getting this error: Unable to parse 'name': attempt to access JSON non-string as string

If I'm not specifying the 'outputs' field, I'm getting None as the inference server's output.

**Comment by GuanLuo** [comment]
You need to specify each of the requested output in a separate `InferRequestedOutput` object, so something like:
```
outputs = [
client.InferRequestedOutput("output", class_count=9)
]
```

**Comment by sourabh-burnwal** [comment]
Thanks for replying.
I did this, and now the outputs finally is a list of inferOutput objects like it's supposed to be. However, I'm still getting None as model output. Sharing the code snippet:

`inputs, outputs = requestGenerator(image_data, input_name, output_name, dtype)
response = triton_client.infer(model_name,
                                inputs,
                                request_id=str(sent_count),
                                model_version=model_version,
                                outputs=outputs)
inferenceOutputs = response.as_numpy(output_name)
print("OUTPUT FROM MODEL: {}".format(inferenceOutputs))`

Output==> OUTPUT FROM MODEL: None

**Comment by sourabh-burnwal** [comment]
Closing this as this has been solved. Thanks again.

**Comment by aneeshmb02** [comment]
I have specified the outputs field correctly yet I am getting the error " [400] Unable to parse 'name': attempt to access JSON non-string as string"
