### ISSUE TITLE
Why the Yolov5s speed is very slow neither using dynamic batch size or multiple instances?

### ISSUE THREAD

**Issue by simon5u** [triton-inference-server/server#3312]
Hi, i am facing the an issue where the yolo5s is very slow in triton even with multiple instances.
I downloaded the model from this link, https://github.com/ultralytics/yolov5/blob/master/export.py
Then, the model was converted from onnx to model.plan, input size is batchsize,3,640,640.
I am using this docker nvcr.io/nvidia/deepstream:5.1-21.02-triton with a 2080Ti GPU.
If I increased the batch size more than 1, the latency becomes very large, more than 100ms.
We compared the speed by using Pytorch or ONNX model, both are faster than using Triton server with similar batch size.
Is it a normal situation or something wrong with my config.pbtxt settings?

===
name: "yolo5"
platform: "tensorrt_plan"

max_batch_size: 16
dynamic_batching {
    preferred_batch_size: [ 1, 2, 4, 8, 10, 16 ]
    #max_queue_delay_microseconds: 10
}

instance_group [
  {
    count: 2
    kind: KIND_GPU
  }
]

input [
  {
    name: "input1"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 640, 640 ]
    reshape { shape: [ 3, 640, 640 ] }
  }
]
output [
  {
    name: "output1"
    data_type: TYPE_FP32
    dims: [ 25200, 85 ]
  },
  {
    name: "output2"
    data_type: TYPE_FP32
    dims: [ 3,80,80,85 ]

  },
  {
    name: "output3"
    data_type: TYPE_FP32
    dims: [ 3,40,40,85 ]
  },
  {
    name: "output4"
    data_type: TYPE_FP32
    dims: [ 3,20,20,85 ]
  }
]

=== using 1 instance ===
**perf_analyzer -m yolo5 --concurrency-range 1:4 -b 1 -f yolo5a.csv**
Concurrency: 1, throughput: 58 infer/sec, latency 17314 usec
Concurrency: 2, throughput: 90.2 infer/sec, latency 22177 usec
Concurrency: 3, throughput: 89.2 infer/sec, latency 33790 usec
Concurrency: 4, throughput: 94.6 infer/sec, latency 42339 usec
**perf_analyzer -m yolo5 --concurrency-range 1:4 -b 16 -f yolo5a16.csv**
Concurrency: 1, throughput: 57.6 infer/sec, latency 266690 usec
Concurrency: 2, throughput: 105.6 infer/sec, latency 301117 usec
Concurrency: 3, throughput: 115.2 infer/sec, latency 412961 usec
Concurrency: 4, throughput: 121.6 infer/sec, latency 521678 usec

=== using 2 instances ===
**perf_analyzer -m yolo5 --concurrency-range 1:4 -b 1 -f yolo5b.csv**
Concurrency: 1, throughput: 56.8 infer/sec, latency 17560 usec
Concurrency: 2, throughput: 80 infer/sec, latency 25016 usec
Concurrency: 3, throughput: 123.6 infer/sec, latency 24348 usec
Concurrency: 4, throughput: 130 infer/sec, latency 30830 usec

**perf_analyzer -m yolo5 --concurrency-range 1:4 -b 1 -f yolo5b16.csv**
Concurrency: 1, throughput: 60.8 infer/sec, latency 270396 usec
Concurrency: 2, throughput: 76.8 infer/sec, latency 424688 usec
Concurrency: 3, throughput: 80 infer/sec, latency 592924 usec
Concurrency: 4, throughput: 80 infer/sec, latency 760824 usec

===
**Speed using a pytorch model with a batch size of 16, around 38ms to 52ms only.**
Model Summary: 224 layers, 7266973 parameters, 0 gradients
image 1/2 yolov5/data/images/bus.jpg: img.shape:  torch.Size([16, 3, 640, 480])
640x480 4 persons, 1 bus, 1 fire hydrant, Done. (0.052s)
640x480 4 persons, 1 bus, 1 fire hydrant, Done. (0.052s)
640x480 4 persons, 1 bus, 1 fire hydrant, Done. (0.052s)
640x480 4 persons, 1 bus, 1 fire hydrant, Done. (0.052s)
640x480 4 persons, 1 bus, 1 fire hydrant, Done. (0.052s)
640x480 4 persons, 1 bus, 1 fire hydrant, Done. (0.052s)
640x480 4 persons, 1 bus, 1 fire hydrant, Done. (0.052s)
640x480 4 persons, 1 bus, 1 fire hydrant, Done. (0.052s)
640x480 4 persons, 1 bus, 1 fire hydrant, Done. (0.052s)
640x480 4 persons, 1 bus, 1 fire hydrant, Done. (0.052s)
640x480 4 persons, 1 bus, 1 fire hydrant, Done. (0.052s)
640x480 4 persons, 1 bus, 1 fire hydrant, Done. (0.052s)
640x480 4 persons, 1 bus, 1 fire hydrant, Done. (0.052s)
640x480 4 persons, 1 bus, 1 fire hydrant, Done. (0.052s)
640x480 4 persons, 1 bus, 1 fire hydrant, Done. (0.052s)
640x480 4 persons, 1 bus, 1 fire hydrant, Done. (0.052s)
image 2/2 yolov5/data/images/zidane.jpg: img.shape:  torch.Size([16, 3, 384, 640])
384x640 2 persons, 2 ties, Done. (0.038s)
384x640 2 persons, 2 ties, Done. (0.038s)
384x640 2 persons, 2 ties, Done. (0.038s)
384x640 2 persons, 2 ties, Done. (0.038s)
384x640 2 persons, 2 ties, Done. (0.038s)
384x640 2 persons, 2 ties, Done. (0.038s)
384x640 2 persons, 2 ties, Done. (0.038s)
384x640 2 persons, 2 ties, Done. (0.038s)
384x640 2 persons, 2 ties, Done. (0.038s)
384x640 2 persons, 2 ties, Done. (0.038s)
384x640 2 persons, 2 ties, Done. (0.038s)
384x640 2 persons, 2 ties, Done. (0.038s)
384x640 2 persons, 2 ties, Done. (0.038s)
384x640 2 persons, 2 ties, Done. (0.038s)
384x640 2 persons, 2 ties, Done. (0.038s)
384x640 2 persons, 2 ties, Done. (0.038s)
Results saved to runs/detect/exp12
Done. (0.566s)

Please advise on how to make the inference faster.

[yolo5a.csv](https://github.com/triton-inference-server/server/files/7084297/yolo5a.csv)
[yolo5a16.csv](https://github.com/triton-inference-server/server/files/7084298/yolo5a16.csv)
[yolo5b.csv](https://github.com/triton-inference-server/server/files/7084299/yolo5b.csv)
[yolo5b16.csv](https://github.com/triton-inference-server/server/files/7084300/yolo5b16.csv)

**Comment by tanmayv25** [comment]
The attached files show that Server Compute Infer is 32ms for single concurrency. The additional overhead is coming from the network transactions.  You can use the shared memory as described in the ticket linked by @CPFelix  or you may also use the perf analyzer in C API mode. See [here ](https://github.com/triton-inference-server/server/blob/main/docs/perf_analyzer.md#benchmarking-triton-directly-via-c-api) for more information.

**Comment by simon5u** [comment]
@tanmayv25 Thanks for the advice. You are right, using shared-memory improved both inference speed and latency significantly.

**root@luke:/sharefolder# perf_analyzer -m yolo5 --concurrency-range 1:4 -b 16 --shared-memory=cuda** 
*** Measurement Settings ***
  Batch size: 16
  Using "time_windows" mode for stabilization
  Measurement window: 5000 msec
  Latency limit: 0 msec
  Concurrency limit: 4 concurrent requests
  Using synchronous calls for inference
  Stabilizing using average latency

Request concurrency: 1
  Client: 
    Request count: 318
    Throughput: 1017.6 infer/sec
    Avg latency: 15723 usec (standard deviation 727 usec)
    p50 latency: 15751 usec
    p90 latency: 15827 usec
    p95 latency: 15863 usec
    p99 latency: 15936 usec
    Avg HTTP time: 15723 usec (send/recv 134 usec + response wait 15589 usec)
  Server: 
    Inference count: 6096
    Execution count: 381
    Successful request count: 381
    Avg request latency: 14839 usec (overhead 2 usec + queue 68 usec + compute input 611 usec + compute infer 13127 usec + compute output 1031 usec)

Request concurrency: 2
  Client: 
    Request count: 360
    Throughput: 1152 infer/sec
    Avg latency: 27669 usec (standard deviation 631 usec)
    p50 latency: 27545 usec
    p90 latency: 28066 usec
    p95 latency: 28359 usec
    p99 latency: 30787 usec
    Avg HTTP time: 27646 usec (send/recv 141 usec + response wait 27505 usec)
  Server: 
    Inference count: 6944
    Execution count: 434
    Successful request count: 434
    Avg request latency: 26698 usec (overhead 2 usec + queue 351 usec + compute input 744 usec + compute infer 24355 usec + compute output 1246 usec)

Request concurrency: 3
  Client: 
    Request count: 325
    Throughput: 1040 infer/sec
    Avg latency: 46047 usec (standard deviation 585 usec)
    p50 latency: 46064 usec
    p90 latency: 46673 usec
    p95 latency: 46928 usec
    p99 latency: 47628 usec
    Avg HTTP time: 46041 usec (send/recv 26 usec + response wait 46015 usec)
  Server: 
    Inference count: 6272
    Execution count: 392
    Successful request count: 392
    Avg request latency: 45767 usec (overhead 3 usec + queue 30 usec + compute input 675 usec + compute infer 43020 usec + compute output 2039 usec)

Request concurrency: 4
  Client: 
    Request count: 362
    Throughput: 1158.4 infer/sec
    Avg latency: 55142 usec (standard deviation 946 usec)
    p50 latency: 55095 usec
    p90 latency: 56364 usec
    p95 latency: 56861 usec
    p99 latency: 57568 usec
    Avg HTTP time: 55128 usec (send/recv 147 usec + response wait 54981 usec)
  Server: 
    Inference count: 6960
    Execution count: 435
    Successful request count: 435
    Avg request latency: 54167 usec (overhead 2 usec + queue 199 usec + compute input 979 usec + compute infer 50636 usec + compute output 2351 usec)

Inferences/Second vs. Client Average Batch Latency
Concurrency: 1, throughput: 1017.6 infer/sec, latency 15723 usec
Concurrency: 2, throughput: 1152 infer/sec, latency 27669 usec
Concurrency: 3, throughput: 1040 infer/sec, latency 46047 usec
Concurrency: 4, throughput: 1158.4 infer/sec, latency 55142 usec

**Comment by Stephenfang51** [comment]
@simon5u  @CPFelix 

Here is my performace of yolov5s deployed using tritonserver on GPU 2080Ti
and did not use share memory method 

`perf_analyzer -u xxx.xxx.xxx.xxx:8001 -m yolov5s_coco -i gRPC -b 16 --concurrency-range 1:4 -f yolov5s_coco_fp32.csv`

```
Inferences/Second vs. Client Average Batch Latency
Concurrency: 1, throughput: 128 infer/sec, latency 249800 usec
Concurrency: 2, throughput: 243.2 infer/sec, latency 264826 usec
Concurrency: 3, throughput: 320 infer/sec, latency 300467 usec
Concurrency: 4, throughput: 364.8 infer/sec, latency 348505 usec
```
my client and tritonserver are on the same machine, same url.
How's you guys ? Are you all run on same machine or different between client and server side ?
