### ISSUE TITLE
Allow selected models in the model repository not to be loaded

### ISSUE THREAD

**Issue by mustafakasap** [triton-inference-server/server#3316]
**Is your feature request related to a problem? Please describe.**
`Yes. Some models in my model repository runs just on CPU and some others just GPU. If launching the server without GPU support, it fails because backends&models with GPU support fails to load. Would like to be able to exclude some models being loaded in case not launching triton with GPU support. 
`
**Describe the solution you'd like**
1) Maybe naming the model folders with a prefix of "_". So all model folder names in a repo starting with "_" character will be omitted to be loaded.
2) It will skip loading failed models and without crashing, continue with successful models.

**Describe alternatives you've considered**
Currently, if I want to test CPU only models, I move GPU models to temporary folder.

**Comment by dyastremsky** [comment]
Have you tried the explicit model control mode? I'm not sure what specifically is bringing your server down _(models that cannot be loaded are typically just unavailable)_, but this mode should accomplish your goals. It allows you to specify when to load/unload models.

Documentation here: https://github.com/triton-inference-server/server/blob/main/docs/model_management.md

**Comment by mustafakasap** [comment]
Running the container by pointing to a model repo that has GPU only models will fail:

`docker run --rm -p8000:8000 -p8001:8001 -p8002:8002 -v/full/path/to/docs/examples/model_repository:/models nvcr.io/nvidia/tritonserver:<xx.yy>-py3 tritonserver --model-repository=/models`

see above command without **--gpus=all** parameter. And put a CPU only model under "/full/path/to/docs/examples/model_repository"

**Comment by dyastremsky** [comment]
Understood, that makes sense if it tries to access a GPU. Did you try this with --model-control-mode=explicit? This provide you full control over which models are loaded.

(Tagging @CoderHam for visibility.)

**Comment by mustafakasap** [comment]
Thanks @dyastremsky sure it works like: 

`docker run --rm -p8000:8000 -p8001:8001 -p8002:8002 -v/full/path/to/docs/examples/model_repository:/models nvcr.io/nvidia/tritonserver:<xx.yy>-py3 tritonserver --model-repository=/models --model-control-mode=explicit --load-model simple --load-model densenet_onnx`

But imagine you have a repo of 20 models in the repo, in a K8s setup, some of the nodes (without GPU) will serve CPU only models, and other nodes with GPU will server all... all K8s nodes accessing same model repository (single point readonly storage area)

In such case 
`--model-control-mode=explicit --load-model simple --load-model densenet_onnx   ......... `
sure will work but for 20 different models, you need to specify one by one in the commandline...

If it was skippling the unloaded models without container is terminating, than that would be much more efficient.

**Comment by dyastremsky** [comment]
There should be ways to implement the sort of logic you're describing programmatically (e.g. via a script that you use to start up Triton that scans model names and loads those matching a specific pattern).

However, I understand you're asking about additional failure recovery functionality. I'll defer to @dzier.

**Comment by tanmayv25** [comment]
@mustafakasap  You can try out ` --exit-on-error=false` when launching server.  See here for more details: https://github.com/triton-inference-server/server/blob/main/src/servers/main.cc#L310

**Comment by mustafakasap** [comment]
``
