### ISSUE TITLE
Shape problem when using SavedModel

### ISSUE THREAD

**Issue by audrey-siqueira** [triton-inference-server/server#3318]
**Description**
I am trying to use my SavedModel to make inferences using Triton 20.10.
 
Knowing that SavedModel doesn't necessarily need a config.pbtxt, I ran it using **--strict-model-config=false**, the model was loaded successfully.

However when I try to make an inference using the image_client.py script (https://github.com/triton-inference-server/client/blob/main/src/python/examples/image_client.py) , then I get some errors detailed below.

**First bug:**

When I try to make the inference, the following error is returned:

**"Exception: unexpected input format FORMAT_NONE, expecting FORMAT_NCHW or FORMAT_NHWC"**

So, I decided to run the container again with the parameter **--log-verbose=1** , to find out which automatic configuration is generating for config.pbtxt, the returned configuration follows below:

{
    "name": "clasificacion_categorica",
    "platform": "tensorflow_savedmodel",
    "backend": "tensorflow",
    "version_policy": {"latest": {"num_versions": 1}
    },
    "max_batch_size": 1,
    "input": [
        {
            "name": "input_1",
            "data_type": "TYPE_FP32",
            "dims": [
                256,
                256,
                3
            ]
        }
    ],
    "output": [
        {
            "name": "dense",
            "data_type": "TYPE_FP32",
            "dims": [
                11
            ]
        }
    ],
    "batch_input": [],
    "batch_output": [],
    "optimization": {
        "priority": "PRIORITY_DEFAULT",
        "input_pinned_memory": {
            "enable": true
        },
        "output_pinned_memory": {
            "enable": true
        }
    },
    "instance_group": [
        {
            "name": "clasificacion_categorica",
            "kind": "KIND_GPU",
            "count": 1,
            "gpus": [
                0
            ],
            "profile": []
        }
    ],
    "default_model_filename": "model.savedmodel",
    "cc_model_filenames": {},
    "metric_tags": {},
    "parameters": {},
    "model_warmup": []
}

So I added the format parameter for **NHWC** as shown below and then the problem was fixed, but I got a second bug back.

name: "clasificacion_categorica"
platform: "tensorflow_savedmodel"
backend: "tensorflow"
max_batch_size: 1

input [
        {
            name: "input_1"
            data_type: TYPE_FP32
            format: FORMAT_NCHW
            dims: [256,256,3]
        }
]

output [
        {
            name: "dense"
            data_type: TYPE_FP32
            dims: [11]
        }
]

**Second Bug:**

When I try again to make the inference with the previous problem fixed , it returns the following :

**inference failed: unexpected shape for input 'input_1' for model 'classificacion_categorica'. Expected [-1,256.256,3], got [1,3,256.3]**

Could someone help me how to solve this problem? I don't know if I should edit something in config.pbtxt or edit something in the image_cliente.py client script.

Please , help me.

**Triton Information**
What version of Triton are you using?  **20.10**

Are you using the Triton container or did you build it yourself? **Container**

**To Reproduce**
Described above

- Triton 20.10 container
- SavedModel  (.pb)
- Cuda 11.1

**Expected behavior**
Solve the shape format problem to finish the inference  .

**Comment by dyastremsky** [comment]
The image client relies on the format attribute to know how to preprocess an image, which is why you got the first error. So you do need to do what you're doing exactly: adding the config.pbtxt file (e.g. taking the auto-generated one and setting the appropriate format).

Your specified dimensions don't match your image ones. If that's the exact error message you're getting, it looks like you specify 256 channels in your image but only have 3. You may need to play around with it to find the correct configuration for your model with the NCHW format you specified.

**Comment by audrey-siqueira** [comment]
The model was trained in (256,256,3) , in addition the command --log-verbose=1 also returned me that the correct one would be (256,256.3).

Even though I change the setting to (3,256,3) , matching the image  output, I get the new error:

**UNAVAILABLE: Invalid argument: model 'clasificacion_categorica', tensor 'input_1': the model expects 4 dimensions (shape [-1,256,256,3]) but the model configuration specifies 4 dimensions (an initial batch dimension because max_batch_size > 0 followed by the explicit tensor shape, making complete shape [-1,3,256,3]**

It seems  that in the link someone had a similar problem:

https://github.com/triton-inference-server/server/issues/1299

As explained in the link, I also tried to configure a config.pbtxt file with only the parameter max_batch_size: 0 and after that, generate the automatic configuration with --log-verbose=1 --strict-model-config=false. 

But unlike the person in this topic, I didn't notice any change in the new generated configuration, even though I set max_batch_size: 0 in config.pbtxt , it returns an automatic configuration with max_batch_size: 1

**Comment by dyastremsky** [comment]
So one set of dimensions results in the model not loading, the other set of dimensions results in the model loading but inference failing? Interesting. Thanks for the additional information.

Tagging @deadeyegoodwin, who might be able to catch what's going on.

**Comment by audrey-siqueira** [comment]
You are right, hope  @deadeyegoodwin can help me , I really need to solve this quickly for my job. Thanks

**Comment by GuanLuo** [comment]
> So I added the format parameter for NHWC as shown below and then the problem was fixed, but I got a second bug back.

You said that you use NHWC which looks to be the correct format for your model, while the model config you posted use `FORMAT_NCHW`, can you double check?
```
name: "clasificacion_categorica"
platform: "tensorflow_savedmodel"
backend: "tensorflow"
max_batch_size: 1

input [
{
name: "input_1"
data_type: TYPE_FP32
format: FORMAT_NCHW
dims: [256,256,3]
}
```

**Comment by audrey-siqueira** [comment]
Hi GuanLuo, thank you for your answer, you were right, but even using NHWC , I am getting an error yet :

Traceback (most recent call last):
  File "image_client.py", line 441, in <module>
    outputs=outputs))
  File "/home/audrey_siqueira/anaconda3/lib/python3.6/site-packages/tritonclient/http/__init__.py", line 1255, in infer
    query_params=query_params)
  File "/home/audrey_siqueira/anaconda3/lib/python3.6/site-packages/tritonclient/http/__init__.py", line 306, in _post
    headers=headers)
  File "/home/audrey_siqueira/anaconda3/lib/python3.6/site-packages/geventhttpclient/client.py", line 272, in post
    return self.request(METHOD_POST, request_uri, body=body, headers=headers)
  File "/home/audrey_siqueira/anaconda3/lib/python3.6/site-packages/geventhttpclient/client.py", line 254, in request
    block_size=self.block_size, method=method.upper(), headers_type=self.headers_type)
  File "/home/audrey_siqueira/anaconda3/lib/python3.6/site-packages/geventhttpclient/response.py", line 298, in __init__
    super(HTTPSocketPoolResponse, self).__init__(sock, **kw)
  File "/home/audrey_siqueira/anaconda3/lib/python3.6/site-packages/geventhttpclient/response.py", line 170, in __init__
    self._read_headers()
  File "/home/audrey_siqueira/anaconda3/lib/python3.6/site-packages/geventhttpclient/response.py", line 190, in _read_headers
    data = self._sock.recv(self.block_size)
  File "/home/audrey_siqueira/anaconda3/lib/python3.6/site-packages/gevent/_socketcommon.py", line 663, in recv
    self._wait(self._read_event)
  File "src/gevent/_hub_primitives.py", line 317, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 322, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 313, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 314, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 55, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_waiter.py", line 154, in gevent._gevent_c_waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
socket.timeout: timed out



I don't know if it looks like a library error, do you have any ideas?

While using NCHW there was the error mentioned above:

inference failed: unexpected shape for input 'input_1' for model 'clasificacion_categorica'. Expected [-1,256,256,3], got [1,3,256,3]

**Comment by audrey-siqueira** [comment]
It looks like this person had the same problem: https://github.com/triton-inference-server/server/issues/3260

All my ports have been configured correctly and when I try to make the inference to a model in the example, I successfully get:

python image_client.py -m densenet_onnx -c 1 -s INCEPTION images/1/tsuru.jpg
Request 1, batch size 1
     12.493561 (654) = MINIBUS
PASS

But when I try to use my model, I get the error mentioned above.

Can anyone help me?

**Comment by tanmayv25** [comment]
Can you try using `-i grpc -u localhost:8001` with image_client.py? 
This will use the python grpc client and grpc endpoint to the server.

**Comment by audrey-siqueira** [comment]
Hi tanmayv25 , thanks for your anwser . Now I changed my Triton container version to 21.08 and also my client container to 21.08 , this way I think I won't have any more dependency errors.

With this new version I dont have problems with the ports anymore, but it returned a new error when I'm making the inference:

**failed sending synchronous infer request: [_Derived_]{{function_node __inference_signature_wrapper_234816}} {{function_node __inference_signature_wrapper_234816}} cuDNN launch failure : input shape([1,48,64,64]) filter shape([3,3,48,192])
         [[{{node StatefulPartitionedCall/sequential/keras_layer/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/blocks_3/StatefulPartitionedCall/conv2d/Conv2D}}]]
         [[StatefulPartitionedCall]]**

For the example modelsI can make the inference without problem but specifically for my SAVED MODEL (.pb)  I'm getting this error above.

Do you have any idea how to solve it?

**Comment by audrey-siqueira** [comment]
Any updates?

**Comment by dyastremsky** [comment]
Thank you for the update! Will close this issue.
