### ISSUE TITLE
make: *** No rule to make target 'triton-python-backend-stub'.

### ISSUE THREAD

**Issue by souvik3333** [triton-inference-server/server#3322]
I was following the instructions [here](https://github.com/triton-inference-server/python_backend#1-building-custom-python-backend-stub). While executing `make triton-python-backend-stub` it gave the mentioned error (`make: *** No rule to make target 'triton-python-backend-stub'.  Stop.`). Any possible solutions would be much appreciated.

**Comment by Tabrizian** [comment]
Did you run `cmake` before running make? Are you in the `build` folder?

**Comment by souvik3333** [comment]
Yes, I did and I tried from the build folder. Actually, a quick search of the Makefile with `triton-python-backend-stub` does not result in any match. I was using the `r20.12` branch. There are rules for `triton-python-backend` which creates a `libtriton_python.so` file. Should I use it instead of `triton-python-backend-stub`?

**Comment by Tabrizian** [comment]
That documentation does not apply to 20.12 branch. You need to update to 21.07+ version to use the Python execution environments.

**Comment by dzier** [comment]
Closing ticket for now. Please try building with 21.07 or later. Feel free to re-open issue if you have more questions.
