### ISSUE TITLE
Scaling multiple GPUs

### ISSUE THREAD

**Issue by vignesh34v** [triton-inference-server/server#3326]
I have a CPU server, connected with 8 GPUs. Tried to deploy my model across all GPUs. 
Issue: The server is not scalable for a large number of GPUs. 

X - Inference requests/per second on single GPU
On 2 GPU - 1.8 X
      4 GPU - 3.3 X
      8 GPU - 4.5 X

Configuration :
          Intel(R) Xeon(R) Gold 5218R CPU
          8 Quadro RTX 5000

**Comment by dzier** [comment]
Can you provide the server config, models, and repo commands?

**Comment by vignesh34v** [comment]
Model config:
```bash
name: "roberta"
platform: "onnxruntime_onnx"
max_batch_size: 64
input [
  {
    name: "input_ids"
    data_type: TYPE_INT64
    dims: [ -1 ]
  },
  {
    name: "attention_mask"
    data_type: TYPE_INT64
    dims: [ -1 ]
  }
]
output
[
  {
    name: "argmax"
    data_type: TYPE_INT64
    dims: [ -1 ]
  },
  {
    name: "logits"
    data_type: TYPE_FP32
    dims: [ -1 ]
  }
]
dynamic_batching {
  preferred_batch_size: [ 8,16,32 ]
  max_queue_delay_microseconds: 1000
}
version_policy: { latest { num_versions : 1 }}
optimization {
  graph { level: 1 }
}
instance_group [
  {
    count: 1
  }
]
```

Tested using perf_analyzer

**Comment by GuanLuo** [comment]
What is the command you use to run `perf_analyzer`? And what is the GPU usage when you are running your experiments? I wonder if `perf_analyzer` is sending enough load to occupy all GPU devices.

**Comment by vignesh34v** [comment]
I just followed perf_analyzer documentation.
```bash
perf_analyzer -m roberta --concurrency-range 1:4 -f perf.csv -p 10000
```

I got similar performance when I test against locust. Memory utilization is same on all GPU. Can I get any other info on GPU?

**Comment by GuanLuo** [comment]
The perf analyzer command you use is not sending a large load to server, I believe if you look at the perf analyzer log, it only maintained 4 concurrency where each request is with batch size 1 at most. What you can try is to configure perf analyzer to send request with max batch size so each request will fully occupy one model instance and you should see the gain of deploying model across GPUs better.
