### ISSUE TITLE
How to pass different input sizes to different models in an ensemble?

### ISSUE THREAD

**Issue by sourabh-burnwal** [triton-inference-server/server#3328]
I have two models say Model A, and Model B. I'm sharing the config files below.
```
name: "Model_A"
platform: "onnxruntime_onnx"
backend: "onnxruntime"
max_batch_size: 0
input [
	{
		name: "input"
		data_type: TYPE_UINT8
		dims: [-1,3,-1,-1]
	}
]
output [
	{
		name: "867"
		data_type: TYPE_FP32
		dims: [1,2,32,32]
	},
	{
		name: "output"
		data_type: TYPE_FP32
		dims: [-1,2,32,32]
	}
]
```

```
name: "Model_B"
platform: "onnxruntime_onnx"
backend: "onnxruntime"
max_batch_size: 5
input [
	{
		name: "input"
		data_type: TYPE_FP32
		format: FORMAT_NCHW
		dims: [3,112,112]
	}
]
output [
	{
		name: "output"
		data_type: TYPE_FP32
		dims: [512]
	}
]
```

I want to ensemble these two in such a way, I provide one input, and both the models can use this. Is there any workaround for this? How can I pass an input which is accepted by both models?

**Comment by dzier** [comment]
What is the dimension and shape of your single input? You may need a third model that can take in the single input convert to the correct outputs for these two models, then you can have the third model feed the input of both Model_A and Model_B.

**Comment by sourabh-burnwal** [comment]
Thanks for replying. Added another python backend model for preprocessing of the input. I have another error now. In my model.py of that newly added model, I've imported tritonclient python library. But, the triton server can't be started since it doesn't have this library installed. So, how can I do install a couple of new pip modules in the triton server?

**Comment by sourabh-burnwal** [comment]
Thanks for replying. I have added another model for preprocessing of the input before feeding to that model.
