### ISSUE TITLE
AttributeError: module 'triton_python_backend_utils' has no attribute 'InferenceRequest'

### ISSUE THREAD

**Issue by sourabh-burnwal** [triton-inference-server/server#3332]
I want to use a python backend model in the Triton server. My model.py looks something like this (can't provide the whole code due to confidentiality)
```
import numpy as np
from tritonclient.utils import *
import tritonclient.http as httpclient
import triton_python_backend_utils as pb_utils

class TritonPythonModel:
    def initialize(self, args):
        self.inputImage_shape = (450, 600)
        self.input_names = ['output', '554', '867', '872', '686', '877', '882', '818', '887']
        
    def execute(self, requests):
        responses = []
        result = {
            'has_mask': [],
            'has_no_mask': []
        }

        for request in requests:
            inferenceOutputs = pb_utils.get_input_tensor_by_name(request, self.input_names)
            faceOutputs = self._postprocess(inferenceOutputs, self.inputImage_shape, 1)
```

I copied the triton_python_backend_utils.py file from [here](https://github.com/triton-inference-server/python_backend/blob/main/src/resources/triton_python_backend_utils.py) into the model directory inside version dir. When I run the Triton server docker container, I get this error and it doesn't start.
```
| mask_detect_postprocess | 1       | UNAVAILABLE: Internal: AttributeError: module 'triton_python_backend_utils' has no attribute 'InferenceRequest' |
```

What am I doing wrong?
Thanks in advance

**Comment by Tabrizian** [comment]
You shouldn't copy the `triton_python_backend_utils.py` file. It is automatically available in every Python model served by Triton.

**Comment by sourabh-burnwal** [comment]
Thanks a lot. I was confused and made the mistake of using that file exclusively.
