### ISSUE TITLE
Defining multiple key-value pairs in ensemble model config.pbtxt

### ISSUE THREAD

**Issue by sourabh-burnwal** [triton-inference-server/server#3333]
I have an onnx model and a post-process python model. The output of the onnx model has 9 different tensors. I want my python model to take these tensors as inputs and post-process them. I wrote an ensemble model config for this, which looks like this:
```
name: "ensemble_a"
platform: "ensemble"
max_batch_size: 0
input [
	{
		name: "input"
		data_type: TYPE_UINT8
		dims: [-1,3,-1,-1]
	}
]
output [
	{
		name: "MASK"
		data_type: TYPE_UINT8
		dims: [-1,-1,-1,-1]
	},
	{
		name: "NO_MASK"
		data_type: TYPE_UINT8
		dims: [-1,-1,-1,-1]
	}
]
ensemble_scheduling {
	step [
		{
			model_name: "mask_detection"
			model_version: -1
			input_map {
				key: "input"
				value: "input"
			}
			output_map {
				key: "887"
				value: "887",
				key: "818"
				value: "818",
				key: "882"
				value: "882",
				key: "877"
				value: "877",
				key: "686"
				value: "686",
				key: "872"
				value: "872",
				key: "554"
				value: "554",
				key: "867"
				value: "867",
				key: "output"
				value: "output",
			}
		},
		{
			model_name: "mask_detect_postprocess"
			model_version: -1
			input_map {
				key: "887"
				value: "887",
				key: "818"
				value: "818",
				key: "882"
				value: "882",
				key: "877"
				value: "877",
				key: "686"
				value: "686",
				key: "872"
				value: "872",
				key: "554"
				value: "554",
				key: "867"
				value: "867",
				key: "output"
				value: "output",
			}
			output_map {
				key: "MASK"
				value: "MASK",
				key: "NO_MASK"
				value: "NO_MASK"
			}
		}
	]
}
```

The config.pbtxt of postprocess model looks like this:
```name: "mask_detect_postprocess"
backend: "python"

input [
	{
		name: "887"
		data_type: TYPE_FP32
		dims: [1,2,128,128]
	},
	{
		name: "818"
		data_type: TYPE_FP32
		dims: [1,8,128,128]
	},
	{
		name: "882"
		data_type: TYPE_FP32
		dims: [1,2,128,128]
	},
	{
		name: "877"
		data_type: TYPE_FP32
		dims: [1,2,64,64]
	},
	{
		name: "686"
		data_type: TYPE_FP32
		dims: [1,8,64,64]
	},
	{
		name: "872"
		data_type: TYPE_FP32
		dims: [1,2,64,64]
	},
	{
		name: "554"
		data_type: TYPE_FP32
		dims: [1,8,32,32]
	},
	{
		name: "867"
		data_type: TYPE_FP32
		dims: [1,2,32,32]
	},
	{
		name: "output"
		data_type: TYPE_FP32
		dims: [-1,2,32,32]
	}
]

output [
	{
		name: "MASK"
		data_type: TYPE_UINT8
		dims: [-1,-1,-1,-1]
	},
	{
		name: "NO_MASK"
		data_type: TYPE_UINT8
		dims: [-1,-1,-1,-1]
	}
]
```

I'm getting this error when I run the Triton server:
```
Error parsing text-format inference.ModelConfig: 35:36: Non-repeated field "key" is specified multiple times.
```

So, what will be the correct way to define multiple outputs in ensemble model config.pbtxt file
Thanks !!

**Comment by GuanLuo** [comment]
For protobuf's map field, if you have multiple entries, you must specify each entry separately (see [example](https://github.com/triton-inference-server/server/blob/main/qa/ensemble_models/batch_to_nobatch_float32_float32_float32/config.pbtxt#L60-L75))

**Comment by sarperkilic** [comment]
> For protobuf's map field, if you have multiple entries, you must specify each entry separately (see [example](https://github.com/triton-inference-server/server/blob/main/qa/ensemble_models/batch_to_nobatch_float32_float32_float32/config.pbtxt#L60-L75))

Hi,

I need an python client script for ensamble model which has multiple input(2) and multiple output(3). Could you share example python client script please? For example, model like you shared the config file with above

**Comment by sourabh-burnwal** [comment]
Model client will depend on your use case. But for multiple input, while making the InferInput objects, you'll have to do it separately for all the input names. Same goes with the outputs. What I did was making a list with all the input names:
```
input_names = ['a', 'b']
inputs = [client.InferInput(input_name, your_data.shape, dtype) for input_name in input_names]
```
Worked for me.
