### ISSUE TITLE
How can I improve the inference speed?

### ISSUE THREAD

**Issue by perldeniel** [triton-inference-server/server#3335]
**Description**
I am using a pre-trained model from [InsightFace](https://github.com/deepinsight/insightface/tree/master/python-package) and managed to get it up and running with Triton server. 

If my understanding on Triton is correct, Triton utilises multiple instance groups and batching to high concurrent inference possible. If the pre-trained model is trained with batch size of 1, does it mean it can at most accepting 1 request at a time?

I create the `config.pbtxt` files myself by navigating through the hints every time I run the docker container. Apparently, the dimensions are fixed and batch size is set to 1.

Currently, the Triton server is giving equivalent query per seconds (10 QPS) as if I'm running it raw on my Python Flask server. Wondering if there is any enhancement possible given the config files below. 

Thanks!

**Triton Information**
21.03

Are you using the Triton container or did you build it yourself? - Docker Container

**Expected behavior**
Higher request / query per second (QPS).

Download model [here](https://mega.nz/file/NRNHQYxa#dTwEN4fdyErXjszwI_2eQvxV1pL3AhpItq0W3HW5bck)

**Config files**

SCRFD Model

```
name: "scrfd"
platform: "onnxruntime_onnx"
max_batch_size : 0
input [
  {
    name: "input.1"
    data_type: TYPE_FP32
    dims: [ 1, 3, 640, 640 ]
  }
]
output [
  {
    name: "448"
    data_type: TYPE_FP32
    dims: [ 12800, 1 ]
  },
  {
    name: "451"
    data_type: TYPE_FP32
    dims: [ 12800, 4 ]
  },
  {
    name: "454"
    data_type: TYPE_FP32
    dims: [ 12800, 10 ]
  },
  {
    name: "471"
    data_type: TYPE_FP32
    dims: [ 3200, 1 ]
  },
  {
    name: "474"
    data_type: TYPE_FP32
    dims: [ 3200, 4 ]
  },
  {
    name: "477"
    data_type: TYPE_FP32
    dims: [ 3200, 10 ]
  },
  {
    name: "494"
    data_type: TYPE_FP32
    dims: [ 800, 1 ]
  },
  {
    name: "497"
    data_type: TYPE_FP32
    dims: [ 800, 4 ]
  },
  {
    name: "500"
    data_type: TYPE_FP32
    dims: [ 800, 10 ]
  }
]
instance_group {
  count: 2
  kind: KIND_GPU
}
```

ArcFace Model
```
name: "arcface"
platform: "onnxruntime_onnx"
max_batch_size : 0
input [
  {
    name: "input.1"
    data_type: TYPE_FP32
    dims: [ -1, 3, 112, 112 ]
  }
]
output [
  {
    name: "1333"
    data_type: TYPE_FP32
    dims: [ 1, 512 ]
  }
]
instance_group {
  count: 2
  kind: KIND_GPU
}
```

**Comment by dzier** [comment]
Based on the config file, your max_batch_size is 0. This means that your model doesn't support batching, at least not in the first dimension, which is the only kind of batching that Triton understands.  So dynamic batching cannot be used with this model.

However, you can still use multiple model instances to get some improved performance: https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#instance-groups

**Comment by perldeniel** [comment]
@dzier Thanks for your explanation. It's much clearer now. I will close this issue.
