### ISSUE TITLE
Pass different input size in a batch

### ISSUE THREAD

**Issue by JadenLy** [triton-inference-server/server#3343]
For image classification, I want to build an ensemble module. I have a preprocessing script, which I will make it a `TritonPythonModel`, and a classification model. And I want to send raw images with different sizes in a batch to the ensemble module, where the preprocessing module resizes and transforms each image before sending to the model. e.g. I have two images, one with 100x80 and the other is 120x100. I want to send raw images and the preprocessing module would convert them to 299x299 for the classification model. I tried to create numerous inputs in the config for the ensemble and preprocessing module, which eventually works. But I wonder if there is an easier way on the Triton end to accommodate such feature without writing multiple inputs in the config file? Also the number of images sent in a batch might be dynamic but is definitely lower than the batch size. Thanks in advance.

**Comment by dzier** [comment]
It sounds like what you want is a variable size input. This can be specified by using `-1` in the dimensions. For example,

```
  input [
    {
      name: "input0"
      data_type: TYPE_FP32
      dims: [ -1, -1 ]
    }
  ]
```

See https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#inputs-and-outputs for more information on variable dimensions.

**Comment by tanmayv25** [comment]
For ragged batches, you can send the input tensors as TYPE_BYTES with [-1] dimension. The image data for the batch can be encoded and sent as:
[\<c of first image\>\<h of first image\>\<w of first image\>\<raw data for first image\>,
\<c of second image\>\<h of second image\>\<w of second image\>\<raw data for second image\>,
.
.
.
\<c of last image\>\<h of last image\>\<w of last image\>\<raw data for last image\>]

On your preprocessing module you can parse the encoded images.

See how to send/receive BYTES tensors with this example: https://github.com/triton-inference-server/client/blob/main/src/python/examples/simple_http_string_infer_client.py#L56
