### ISSUE TITLE
An option to automatically re-assign device for CPU only ops in tensorflow SavedModel

### ISSUE THREAD

**Issue by BorisPolonsky** [triton-inference-server/server#3344]
**Is your feature request related to a problem? Please describe.**

I have lots of classification model in `tensorflow SavedModel` format that runs perfectly on GPU version of `tensorflow/serving`. Some of the them fails to run on triton model server if I define label look up op in its graph. I assume that `tensorflow/serving` automatically move these ops to CPU devices. I would like to expect an option to make things run on GPU and fall back to CPU if a certain op is not supported by GPU.

Here's the logs from `triton-model-server` with `--strict-model-config=true` set
```
2021-09-09 17:03:23.005937: W tensorflow/core/common_runtime/colocation_graph.cc:983] Failed to place the graph without changing the devices of some resources. Some of the operations (that had to be colocated with resource generating operations) are not supported on the resources' devices. Current candidate devices are [
  /job:localhost/replica:0/task:0/device:CPU:0].
See below for details of this colocation group:
Colocation Debug Info:
Colocation group had the following types and supported devices: 
Root Member(assigned_device_name_index_=-1 requested_device_name_='/device:GPU:0' assigned_device_name_='' resource_device_name_='/device:GPU:0' supported_device_types_=[CPU] possible_devices_=[]
LookupTableFindV2: CPU 
LookupTableImportV2: CPU 
HashTableV2: CPU 

Colocation members, user-requested devices, and framework assigned devices, if any:
  index_to_string (HashTableV2) /gpu:0
  index_to_string/table_init (LookupTableImportV2) /gpu:0
  index_to_string_Lookup (LookupTableFindV2) /gpu:0


.......


I0909 09:03:24.433899 1 server.cc:249] Timeout 29: Found 0 live models and 0 in-flight non-inference requests
error: creating server: Internal - failed to load all models
```
Here's an example of my `config.pbtxt`
```
platform: "tensorflow_savedmodel"
backend: "tensorflow"
max_batch_size: 2
input: [
  {
  name: "input_ids"
  data_type: TYPE_INT64
  dims: [ 512 ]
  allow_ragged_batch: false
  },
  {
  name: "input_mask"
  data_type: TYPE_INT64
  dims: [ 512 ]
  reshape: { shape: [ ] }
  },
  {
  name: "segment_ids"
  data_type: TYPE_INT64
  dims: [ 512 ]
  reshape: { shape: [ ] }
  }
]
output [
  {
  name: "cls_embedding"
  data_type: TYPE_FP32
  dims: [ 768 ]
  }
]

batch_input []
batch_output []
instance_group: [
  {
  kind: KIND_MODEL
  }
]
```
**Describe the solution you'd like**
The model got successfully loaded on GPU, with those CPU only ops automatically re-assigned on CPU.

**Describe alternatives you've considered**

**Additional context**

**Comment by ankur-sarda** [comment]
+1 I can confirm this behavior is on 21.09 and not on 21.08.

**Comment by BorisPolonsky** [comment]
> +1 I can confirm this behavior is on 21.09 and not on 21.08.

I tested on `nvcr.io/nvidia/tritonserver:21.08-py3`. I'll try the newer image later.

**Comment by dzier** [comment]
21.09 has not been released yet. `nvcr.io/nvidia/tritonserver:21.08-py3` is the latest release.

**Comment by ankur-sarda** [comment]
> +1 I can confirm this behavior is on 21.09 and not on 21.08.

Oops, my bad.  
Correction - I can confirm this behavior is on ~~21.09~~ 21.08 and not on ~~21.08~~ 21.07.

**Comment by dzier** [comment]
For the original request, the Tensorflow backend does expose the allow-soft-placement option already: https://github.com/triton-inference-server/tensorflow_backend#--backend-configtensorflowallow-soft-placementboolean

Please make sure this option is set to true in launching Triton.

**Comment by BorisPolonsky** [comment]
> For the original request, the Tensorflow backend does expose the allow-soft-placement option already: https://github.com/triton-inference-server/tensorflow_backend#--backend-configtensorflowallow-soft-placementboolean
> 
> Please make sure this option is set to true in launching Triton.

I added this configuration and the problem still exists

```
Colocation members, user-requested devices, and framework assigned devices, if any:
  index_to_string (HashTableV2) /gpu:0
  index_to_string/table_init (LookupTableImportV2) /gpu:0
  index_to_string_Lookup (LookupTableFindV2) /gpu:0

2021-09-11 10:10:13.222359: I tensorflow/cc/saved_model/loader.cc:251] Restoring SavedModel bundle.
2021-09-11 10:10:13.648803: I tensorflow/cc/saved_model/loader.cc:200] Running initialization op on SavedModel bundle at path: /home/model-repo/ner/1/model.savedmodel
2021-09-11 10:10:13.670924: I tensorflow/cc/saved_model/loader.cc:379] SavedModel load for tags { serve }; Status: success. Took 5883326 microseconds.
2021-09-11 10:10:13.670965: W triton/tensorflow_backend_tf.cc:986] unable to find serving signature 'serving_default
2021-09-11 10:10:13.670990: W triton/tensorflow_backend_tf.cc:988] using signature 'predict'
I0911 02:10:13.671343 1 model_repository_manager.cc:1212] successfully loaded 'ner' version 1
I0911 02:10:13.671496 1 server.cc:504] 
+------------------+------+
| Repository Agent | Path |
+------------------+------+
+------------------+------+

I0911 02:10:13.671663 1 server.cc:543] 
+-------------+-----------------------------------------------------------------+---------------------------------------------+
| Backend     | Path                                                            | Config                                      |
+-------------+-----------------------------------------------------------------+---------------------------------------------+
| tensorrt    | <built-in>                                                      | {}                                          |
| pytorch     | /opt/tritonserver/backends/pytorch/libtriton_pytorch.so         | {}                                          |
| tensorflow  | /opt/tritonserver/backends/tensorflow1/libtriton_tensorflow1.so | {"cmdline":{"allow-soft-placement":"true"}} |
| onnxruntime | /opt/tritonserver/backends/onnxruntime/libtriton_onnxruntime.so | {}                                          |
| openvino    | /opt/tritonserver/backends/openvino/libtriton_openvino.so       | {}                                          |
+-------------+-----------------------------------------------------------------+---------------------------------------------+
```

So this is indeed supported but not worked as expected. May be I should file a bug report instead?

**Comment by ankur-sarda** [comment]
The problem still exists for me as well.

**Comment by tanmayv25** [comment]
Are you using the same version of tensorflow in Triton? In triton you are using TF 1. To use TF 2, users must add the following flag when launching the server:

`--backend-config=tensorflow,version=<int>`
https://github.com/triton-inference-server/tensorflow_backend#--backend-configtensorflowversionint

Triton doesn't do anything different than TFS when it comes to loading the model. So, can you confirm that versions of TF is same in TFS and Triton?

**Comment by tanmayv25** [comment]
>  tensorflow  | /opt/tritonserver/backends/tensorflow1/libtriton_tensorflow1.so | {"cmdline":{"allow-soft-placement":"true"}} |

@BorisPolonsky 's logs showed TF1 was being used. 
@ankur-sarda  Please open a github issue with simple repro steps for the regression?

**Comment by BorisPolonsky** [comment]
> Are you using the same version of tensorflow in Triton? In triton you are using TF 1. To use TF 2, users must add the following flag when launching the server:
> 
> `--backend-config=tensorflow,version=2`
> https://github.com/triton-inference-server/tensorflow_backend#--backend-configtensorflowversionint
> 
> Triton doesn't do anything different than TFS when it comes to loading the model. So, can you confirm that versions of TF is same in TFS and Triton?

I tried adding `--backend-config=tensorflow,version=2` option, the problem still exist. The original `SavedModel` works in both of TFS1 and TFS2.
