### ISSUE TITLE
Is it possible to use tensorflow with GPU on custom python backend?

### ISSUE THREAD

**Issue by ankur-sarda** [triton-inference-server/server#3347]
**Is your feature request related to a problem? Please describe.**
We have tried to use tensorflow with CPU on custom python backend. But it is not clear if it possible to use it with GPU. 
Also, Custom python backend was introduced in version 21.06 of triton and is built against CUDA 11.3, whereas latest tensorflow supports up to CUDA 11.2. I have tried to run tensorflow 2.6 with CUDA 11.4 and it does not seem to work.

**Describe the solution you'd like**
NA

**Describe alternatives you've considered**
Using tensorflow savedmodel

**Comment by dzier** [comment]
Yes, the custom python backend can use the GPU. We improved this usage with 21.08, so I would recommend using the latest release. However, why are you running a tensorflow model on a custom Python backend? Have your tried using the Tensorflow backend directly?

**Comment by Tabrizian** [comment]
You can install any Python package and use them in Python backend models.

**Comment by ankur-sarda** [comment]
@dzier Sure, I will try with 21.08. However, how do I run tensorflow (2.6 - latest) on CUDA 11.4 which is shipped with triton 21.08? The latest cuda version supported by tf 2.6 is 11.2, and building triton with 11.2 is not officially supported?

**Comment by dzier** [comment]
Please checkout the support matrix: https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html. You should use the 21.08 Tensorflow supplied by NGC. That version does use CUDA 11.4.1. The 21.08 Triton version is builds the Tensorflow backend from that TF NGC container.

**Comment by ankur-sarda** [comment]
Great, I will check it out. Is there plans to release version with tensorflow 2.6 ?

**Comment by deadeyegoodwin** [comment]
TF 2.6 will be released in 21.09 images later this month.
