### ISSUE TITLE
Allow http server to bind to specific address/interface

### ISSUE THREAD

**Issue by damonmaria** [triton-inference-server/server#3360]
**Describe the solution you'd like**
It would be useful to have the ability to specify the address the http server binds to. Currently this is [hard coded to "0.0.0.0"](https://github.com/triton-inference-server/server/blob/main/src/servers/http_server.cc#L69). 

I have the situation where Triton is a 'sidecar' container within a k8s pod to enable fast data passing between Triton and our container. The pod itself has to be `hostNetwork: true` for our container to communicate with the cameras we're pulling images from. Unfortunately this means Triton is exposed with open ports on the host, and since it's bound to 0.0.0.0, open to the network. I would like to bind Triton to 127.0.0.1 so it's not exposed on the network. 

**Describe alternatives you've considered**
The alternative would be to run Triton in it's own pod but we run multiple of these containers, each with their own distinct set of models. It makes sense to co-locate them on the same host.

**Comment by deadeyegoodwin** [comment]
This would be a fairly straight-forward enhancement to http and grpc servers. Can you push a PR?

**Comment by damonmaria** [comment]
If this was a Python or Typescript project I'd be happy to, but very little experience with C++ sorry.
