### ISSUE TITLE
Loading CPU/GPU dyncamically

### ISSUE THREAD

**Issue by ajaichemmanam** [triton-inference-server/server#3361]
When using explicit model control, We are able to load the model and unload the model through the client.
But the hardware acceleration and number of instances are taken from the model config.pbtxt itself.

Can we specify whether to load a model on CPU/GPU and the number of instances/count of it through the same API interface?

**Comment by deadeyegoodwin** [comment]
No, that configuration is part of the model itself. You can change the config.pbtxt and then (re)load a model to change those properties.
