### ISSUE TITLE
Does tensorflow-backend support multi-stream on a single GPU?

### ISSUE THREAD

**Issue by AsherXian903** [triton-inference-server/server#3370]
Hi all,
    I'm facing the problem that when I do tensorflow multiple references with multi-thread on a single GPU, it occures to me that the requests are processed sequentially. Can tensorflow-backend help me to resolve this?

Thanks,
Asher

**Comment by deadeyegoodwin** [comment]
It is not clear what you are asking. Triton itself can simultaneously handle multiple inference requests. If multiple requests are for the same model, triton may or may not be able to handle them simultaneously depending on how you have configured the dynamic batcher and model instances. See https://github.com/triton-inference-server/server/blob/main/docs/architecture.md
