### ISSUE TITLE
Can i use new version client api to reques older version triton-server

### ISSUE THREAD

**Issue by Weizhongjin** [triton-inference-server/server#3374]
Can i use r21.08 client api to send request to r20.03 server. Because of some reason my model can only be deployed on r20.03 triton server docker. But i find some difficult on compile 20.03 client c++ library, so i want to use 21.08 client c++ library

**Comment by deadeyegoodwin** [comment]
The 20.03 version of Triton is V1 Triton.r21.08 is V2 Triton. That means the client protocols are not compatible. Note that V1 is no longer supported. The 20.03.1 version of Triton does have experimental support for V2 but that is unlikely to work in all cases with a full V2 client (like those from r21.08).

V1 was deprecated and then removed in the 20.08 release. V2 clients are compatible with older servers (and vice-versa) so you can use a newer client with any 20.08 or later server.
