### ISSUE TITLE
Release triton server image 21.09+

### ISSUE THREAD

**Issue by oeway** [triton-inference-server/server#3380]
**Is your feature request related to a problem? Please describe.**
I would like to use the `$$TRITON_MODEL_DIRECTORY` option for loading custom conda env pack from S3 model repo for the python backend, but it is not available yet in `nvcr.io/nvidia/tritonserver:21.08-py3` (the latest image).

**Describe the solution you'd like**
Could you please publish a newer server image (i.e. 21.09+)?

**Describe alternatives you've considered**
Not sure how we can load custom conda env from S3 model repo if we need a hardcoded path.

**Comment by GuanLuo** [comment]
We release the container monthly and 21.09 should be released at the end of the month
