### ISSUE TITLE
`perf_analyzer` error while loading shared libraries: `libcudart.so.11.0`

### ISSUE THREAD

**Issue by fabito** [triton-inference-server/server#3391]
**Description**
Cannot run `perf_analyzer`, after installing tritonclient in a fresh virtual environment.
The following error is raised:

```bash
perf_analyzer: error while loading shared libraries: libcudart.so.11.0: cannot open shared object file: No such file or directory
```

**tritonclient Information**
tritonclient 2.13.0

```
$ python3 -V
Python 3.8.5

$ pip freeze
Brotli==1.0.9
certifi==2021.5.30
gevent==21.8.0
geventhttpclient==1.5.1
greenlet==1.1.1
grpcio==1.40.0
numpy==1.21.2
protobuf==3.18.0
python-rapidjson==1.4
six==1.16.0
tritonclient==2.13.0
zope.event==4.5.0
zope.interface==5.4.0
```

**To Reproduce**
- creata a new python virtual environment
- install tritonclient
- run perf_analyzer

```bash
python3 -m venv venv
source venv/bin/activate
pip install tritonclient[all]==2.13.0
chmod +x venv/bin/perf_analyzer

perf_analyzer -h
``` 

**Expected behavior**
`perf_analyzer` help printed on screen

**Comment by fabito** [comment]
Downgrading to `2.09.0`, seems to solve the issue.

```bash
pip install tritonclient[all]==2.09.0
```

**Comment by CoderHam** [comment]
I think the reason is likely a mismatch in the cuda version you have on your system vs the one being used to build the tritonclient package. As you can see the cuda version is 11.0 for the package. Can you confirm the cuda version used in your environment?
@tanmayv25 for viz

**Comment by tanmayv25** [comment]
@fabito Please use the [support matrix](https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html) for verifying the supported versions.

v2.9.0 is built with cuda **11.3.0**, whereas v2.13.0 is built with cuda **11.4.1**.

**Comment by fabito** [comment]
I am using the docker image now and I can use the latest version
