### ISSUE TITLE
Asynchronous Operation for Request/Response for Python Backed

### ISSUE THREAD

**Issue by andywag** [triton-inference-server/server#3394]
The python backend works well with synchronous requests/responses and has some asynchronous support internally but doesn't support asynchronous requests/responses. This limitation leads to a couple performance issues for certain models. 

- Pipelined models or models with delay aren't supported
- Hiding data pre-processing during device run times isn't possible

Breaking the dependence between the request and response would alleviate this issue. I believe simply breaking the dependence between the request and response would solve this issue. There are quite a few ways this could work from the model side but one approach is to add 2 new methods. The control will in general stay with the "model" code to avoid issues with GIL.

- get_data : Gets a request from the server if one is available
- put_response : Puts a response to the server when it is ready. 

The request/response is pretty tightly tied together internally in the code but I had some success separating them out.

**Comment by Tabrizian** [comment]
> Breaking the dependence between the request and response would alleviate this issue.

This is on our roadmap but we have not been able to get to it yet.

> get_data : Gets a request from the server if one is available

Can you elaborate more on this? Currently, your Python model's `execute` function is called whenever there are new requests available. So, I think `get_data` is similar to what we have already.

Is it possible to elaborate more on the usecases? Is this about the [BLS ](https://github.com/triton-inference-server/python_backend#business-logic-scripting-beta) feature or the way Python backend handles requests in general?

**Comment by Tabrizian** [comment]
I see, decoupling inference response and request in Python backend is on our roadmap.

**Comment by Tabrizian** [comment]
Python backend now supports the decoupled API. You can read more about it here: https://github.com/triton-inference-server/python_backend#decoupled-mode

Closing this issue.
