### ISSUE TITLE
Misleading gRPC status codes returned for some error cases

### ISSUE THREAD

**Issue by njhill** [triton-inference-server/server#3399]
If a gRPC `InferRequest` is made for a model name or version that doesn't exist or a model which isn't yet ready, the returned status code in all cases is `UNAVAILABLE`. A more appropriate code for the first two cases would be `NOT_FOUND`.

It looks like this might have been an oversight [here](https://github.com/triton-inference-server/server/blob/eaa5755e807b2ff4dec53a5cd61c7b02ac8de2ce/src/core/model_repository_manager.cc#L1676-L1681), where a non-success status is not preserved/translated and instead always set to `UNAVAILABLE`.

The [unit tests](https://github.com/triton-inference-server/server/blob/8d02c9e8f1075baf525614120514ec2e12d3e842/qa/L0_lifecycle/lifecycle_test.py#L752) only check the error message, not the code.

**Comment by GuanLuo** [comment]
Thanks for reporting, we will look into improving the error reporting.

**Comment by GuanLuo** [comment]
Thank for the follow-up, unfortunately we have other prioritized items to work on so I haven't have the chance to take a look at this. This issue is being tracked, but feel free to create a PR with the fix if you don't mind taking a stab at it.

**Comment by krishung5** [comment]
Hi @njhill, thanks for raising this issue. Closing this issue as the misleading status code problem has been addressed in this PR:https://github.com/triton-inference-server/core/pull/95.
