### ISSUE TITLE
Why client expriment v2 api in r20.03 can not request 20.03 server 

### ISSUE THREAD

**Issue by Weizhongjin** [triton-inference-server/server#3400]
`  File "grpc_v2_image_client.py", line 284, in <module>
    metadata_response = grpc_stub.ModelMetadata(metadata_request)
  File "/usr/local/lib/python3.6/dist-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.6/dist-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNIMPLEMENTED
        details = ""
        debug_error_string = "{"created":"@1632450363.555499733","description":"Error received from peer ipv4:172.17.0.1:8001","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"","grpc_status":12}"
`

**Comment by GuanLuo** [comment]
The Triton version that you are using is old, is there a reason for not using the later version?

I think that is during the transaction and there is a server argument to select the protocol version when you start the server, have you set that? If so, please provide a detail repro step.

**Comment by Weizhongjin** [comment]
You are correct! I didn't set the api-version when i start a server. Thanks so much
