### ISSUE TITLE
Problem with sending float tensors to the server

### ISSUE THREAD

**Issue by mhs-achyut** [triton-inference-server/server#3407]
**Description**
I am trying to deploy an instance segmentation model using the triton inference server. Specifically, my model takes in an input image, fp32 detection box [-1X4] tensor as another input and predicts fp32 (-1X32X32) segmentation masks. My queries randomly produce errors and randomly the query succeeds. Whenever there is an error, I am getting the following debug output from the server:

```
failed sending synchronous infer request: 2 root error(s) found.
  (0) Invalid argument: assertion failed: [[[2.02321691e+11 0 0...]]...]
         [[{{node Assert/AssertGuard/Assert}}]]
         [[cluster_14_1/merge_oidx_0/_3205]]
  (1) Invalid argument: assertion failed: [[[2.02321691e+11 0 0...]]...]
         [[{{node Assert/AssertGuard/Assert}}]]
0 successful operations.
0 derived errors ignored.
```

I don't understand why this is happening. Please help me. I can provide code and model to reproduce this error on request privately.

**Triton Information**
What version of Triton are you using?
21.07-py3
nvcr.io/nvidia/tritonserver:21.07-py3

Are you using the Triton container or did you build it yourself?
Container

**To Reproduce**
Steps to reproduce the behavior.
Tensorflow Deepmac instance segmentation model served with saved_model format

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

```
name: "mhsdeepmac_savedmodel"
platform: "tensorflow_savedmodel"
max_batch_size: 0
input [
  {
    name: "input_tensor"
    data_type: TYPE_UINT8
    format: FORMAT_NHWC
    dims: [1024, 1024, 3 ]
    reshape: { shape: [1,1024,1024,3] }
  },
  {
    name: "boxes"
    data_type: TYPE_FP32
    dims: [-1, 4 ]
    reshape: { shape: [1, -1, 4] }
  }
]
output [
  {
    name: "detection_masks"
    data_type: TYPE_FP32
    dims: [-1, 32, 32 ]
    reshape: { shape: [1, -1, 32, 32] }
  }
]
instance_group [
  {
      kind: KIND_GPU
      count: 1
      gpus: [
          1
      ]
  }
]
optimization {graph { level: 2 }}

```

**Expected behavior**

I want the root errors to go away and expect a reliable inference call every time.

Thanks

**Comment by mhs-achyut** [comment]
@deadeyegoodwin

**Comment by CoderHam** [comment]
@mhs-achyut please share the code + model you used to produce this error.

**Comment by mhs-achyut** [comment]
@CoderHam I could not find a single example sending a float tensor as input to the server. There is not even an AppendRaw function that supports this input. Please let me know if this is a feature supported by the server and the client libs at the moment?
The only AppendRaw functions I have seen from the docs are only supporting uint8 as following. Please let me know how to pass float tensors as input with a small example.
Error AppendRaw(const std::vector<uint8_t>& input);

**Comment by CoderHam** [comment]
@mhs-achyut did you have a look at the python/C++ [image client](https://github.com/triton-inference-server/client/blob/main/src/python/examples/image_client.py)? You can find all these examples at: https://github.com/triton-inference-server/client/tree/main/src/python/examples.

You can find the datatypes support in the respective backends [here](https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#datatypes).

**Comment by achbogga** [comment]
Never mind, the server only takes raw bytes as input. If anyone facing the same issue, convert your float tensor to bytes and use AppendRaw(std::vector<uint8_t>& input_bytes_tensor).

**Comment by achbogga** [comment]
@CoderHam you can close the issue.
