### ISSUE TITLE
Clear documentation on GRPC health endpoint

### ISSUE THREAD

**Issue by slizb** [triton-inference-server/server#3410]
**Is your feature request related to a problem? Please describe.**
I've run into trouble configuring a GRPC health check for my Triton application. This repository doesn't seem to have any clear documentation on the appropriate endpoint to use for checking GRPC server health. The closest I could find was in server/docs/architecture.md, which references "Readiness and liveness health endpoints," but does not suggest what they are. In server/docs/protocol, there is a reference to the KFServing project, which uses the following endpoints, but there is no indication if any of these is appropriate for checking Triton GRPC health:

```
// Inference Server GRPC endpoints.
service GRPCInferenceService
{
  // The ServerLive API indicates if the inference server is able to receive 
  // and respond to metadata and inference requests.
  rpc ServerLive(ServerLiveRequest) returns (ServerLiveResponse) {}

  // The ServerReady API indicates if the server is ready for inferencing.
  rpc ServerReady(ServerReadyRequest) returns (ServerReadyResponse) {}

  // The ModelReady API indicates if a specific model is ready for inferencing.
  rpc ModelReady(ModelReadyRequest) returns (ModelReadyResponse) {}

  // The ServerMetadata API provides information about the server. Errors are 
  // indicated by the google.rpc.Status returned for the request. The OK code 
  // indicates success and other codes indicate failure.
  rpc ServerMetadata(ServerMetadataRequest) returns (ServerMetadataResponse) {}

  // The per-model metadata API provides information about a model. Errors are 
  // indicated by the google.rpc.Status returned for the request. The OK code 
  // indicates success and other codes indicate failure.
  rpc ModelMetadata(ModelMetadataRequest) returns (ModelMetadataResponse) {}

  // The ModelInfer API performs inference using the specified model. Errors are
  // indicated by the google.rpc.Status returned for the request. The OK code 
  // indicates success and other codes indicate failure.
  rpc ModelInfer(ModelInferRequest) returns (ModelInferResponse) {}
}
```

**Describe the solution you'd like**
I would like to know the appropriate GRPC endpoint(s) for checking triton server health, and would like for this to be better documented in the triton repository.

**Comment by CoderHam** [comment]
We have examples that demonstrate how to send requests the GRPC health endpoint i.e. [simple_grpc_health_metadata.py](https://github.com/triton-inference-server/client/blob/main/src/python/examples/simple_grpc_health_metadata.py#L58-L61). If you are not using the triton client library and wish to write your own you can refer to the [source code](https://github.com/triton-inference-server/client/blob/main/src/python/library/tritonclient/grpc/__init__.py#L256) for these functions. 

ServerLive indicates if the server is running and can respond to metadata/inference requests. 
ServerReady indicates if the server is ready to run inferences and so on. These endpoints are clearly described in the grpc endpoint protobuf that you shared above. Can you help us understand how better to document the same?

**Comment by slizb** [comment]
Thank you for the quick response! Then would the appropriate health endpoint path for ServerLive be /inference.GRPCInferenceService/ServerLive? 

An equivalent to the above snippet from the KFServing project written in markdown documentation would be very useful, to keep users from having to dig through the source code.

**Comment by mdable2** [comment]
I also am wondering if `/inference.GRPCInferenceService/ServerLive` is the right way to reference the gRPC health endpoint?

**Comment by CoderHam** [comment]
@slizb @mdable2 yes that is correct. [grpc_service.proto](https://github.com/triton-inference-server/common/blob/main/protobuf/grpc_service.proto#L42-L47) details the same as well
