### ISSUE TITLE
python-backend r21.09-py3 manifest unknown

### ISSUE THREAD

**Issue by mlizhardy** [triton-inference-server/server#3414]
**Description**
I need to use r21.09 for the ability to return gpu tensors.  However, when I run:
`docker pull nvcr.io/nvidia/tritonserver:21.09-py3`

I get the following error: 
`Error response from daemon: manifest for nvcr.io/nvidia/tritonserver:21.09-py3 not found: manifest unknown: manifest unknown`

**To Reproduce**
Steps to reproduce the behavior.
`docker pull nvcr.io/nvidia/tritonserver:21.09-py3`

**Expected behavior**

I expect to build the container.

**Comment by CoderHam** [comment]
The 21.09 NGC release is not out yet. You should try with 21.08 or wait till 21.09 is out.

**Comment by mlizhardy** [comment]
thanks - looks like dlpack works with 21.08 as well anyway
