### ISSUE TITLE
Ability to have optional inputs

### ISSUE THREAD

**Issue by ankur-sarda** [triton-inference-server/server#3419]
**Is your feature request related to a problem? Please describe.**
Triton now supports business logic scripting, where we can introduce business logic based on the input. Just like any API, not all inputs to an API are necessary as some default behavior can be expected in business logic. 

**Describe the solution you'd like**
Propose to have optional field for each input variable. 

```
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [ 1 ]
    optional: true
  }
```

**Additional context**
I can contribute for implementation, if the proposal is accepted.

**Comment by oeway** [comment]
This will be very useful for Python backends. The output tensors can be selectively requested and I think it would make a lot of sense to support optional inputs.

**Comment by Tabrizian** [comment]
Support for optional inputs has been added in https://github.com/triton-inference-server/server/pull/3680 and will be available in 22.01 release. For an example, you can refer to https://github.com/triton-inference-server/server/blob/main/qa/L0_optional_input/models/identity_2_float32/config.pbtxt

**Comment by oeway** [comment]
This is awesome! Thanks a lot! @Tabrizian

**Comment by oeway** [comment]
A quick question, if we call "pb_utils.get_input_tensor_by_name" in the python backend and the optional input is not available, will it return None? @Tabrizian

**Comment by Tabrizian** [comment]
Correct. If an input doesn't exist, Python backend will return None. https://github.com/triton-inference-server/python_backend/blob/29cb0f2570dcf411f4c457ea026676e020901460/src/resources/triton_python_backend_utils.py#L122
