### ISSUE TITLE
Triton Server Shared Memory - Free Unused Memory from Multiple Processes in C++

### ISSUE THREAD

**Issue by simon5u** [triton-inference-server/server#3428]
Description

I have 2 processes (P1 and P2) calling the same tritonserver model (yolov5s)

Both P1 and P2 have these few lines of code in the constructor to free unused memory before initialising a new shared memory buffer for inference:

{
FAIL_IF_ERR(nic::InferenceServerGrpcClient::Create(&client, "localhost:8001", false),
"unable to create triton client yolov5");

FAIL_IF_ERR(client->UnregisterSystemSharedMemory(),
  "unable to unregister all system shared memory regions");

FAIL_IF_ERR(client->UnregisterCudaSharedMemory(),
  "unable to unregister all cuda shared memory regions");

}

However, doing so causes a problem where P2 will free the shared memory allocated to P1 as well (or vice versa depending which process running last).

Is there any way for the process to free only as certain part of shared memory instead of freeing all?

Thank you.

Triton Information
What version of Triton are you using?
nvcr.io/nvidia/tritonserver:21.02-py3

Are you using the Triton container or did you build it yourself?
triton container nvcr.io/nvidia/tritonserver:21.02-py3

**Comment by CoderHam** [comment]
@simon5u you cannot free a specific section of the shared memory region and must free the entire region or mmap blocks of it at a time to begin with. 
Why not unregister specific shared memory regions in each process instead of unregistering all of them in both?
Do you need common shared memory regions between P1 and P2?

**Comment by simon5u** [comment]
> @simon5u you cannot free a specific section of the shared memory region and must free the entire region or mmap blocks of it at a time to begin with. Why not unregister specific shared memory regions in each process instead of unregistering all of them in both? Do you need common shared memory regions between P1 and P2?

Your suggestion is right, we made a mistake and we should free specific shared memory region, no need to share between P1 and P2. Thanks for the suggestion.
