### ISSUE TITLE
Change Documentation of Instance Groups to prevent Misunderstandings

### ISSUE THREAD

**Issue by SetZero** [triton-inference-server/server#3443]
**Edit:** I just found the sentence `By default, a single execution instance of the model is created for each GPU available in the system` [\[1\]](https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#instance-groups). Maybe you should change [the other sentence](https://github.com/triton-inference-server/server/blob/main/docs/architecture.md#concurrent-model-execution) I found to prevent this misunderstanding.

I'm currently trying to figure out if Triton needs an instance group on a system with multiple GPUs.
My Workstation has 2 GPUs but when I try to apply an instance group of size 2 the latency will increase, while the throughput stays the same, even if there is only one model executed.

As far as I understand the documentation Triton should only have one instance of a model running (`By default, Triton gives each model a single instance`), which should bring an increase in performance if I set it to the amount of GPUs, but it doesn't

```
name: "image_label"
platform: "tensorflow_savedmodel"
max_batch_size: 64

[...]

dynamic_batching {
    max_queue_delay_microseconds: 100
}
instance_group [
    {
      count: 2
      kind: KIND_GPU
    }
  ]
```

Command:
```
perf_analyzer --percentile=95 --concurrency-range 1:100 
```

Output:
![image](https://user-images.githubusercontent.com/6242238/136535154-a9ec13ba-6a93-4ab6-b3a1-8b4753afc15d.png)

The output leads me to the conclusion that Triton is actually starting an instance of a model per GPU. Is that correct?

**Comment by Tabrizian** [comment]
>The output leads me to the conclusion that Triton is actually starting an instance of a model per GPU. Is that correct?

Correct. If you don't specify device in the instance group section of model configuration, there will be 'count' instances of the model created on each GPU. I have filed a ticket to improve the documentation. Thanks for bringing this to our attention.

**Comment by CoderHam** [comment]
Fixed by https://github.com/triton-inference-server/server/pull/3517
