### ISSUE TITLE
Triton backend API version does not support this backend

### ISSUE THREAD

**Issue by JaydonChion** [triton-inference-server/server#3450]
Hi,

I am trying to run tritonserver on jetson agx. 
I downloaded tritonserver2.14.0-jetpack4.6.tgz to my pc, follow by git clone the python backend according to the instruction in (https://github.com/triton-inference-server/python_backend) to tritonserver/backends

Next, I did the cmake installation with -DCMAKE_INSTALL_PREFIX set to tritonserver/bin , which is the folder my tritonserver executable file located. 

lastly, i run :
tritonserver/bin/tritonserver --model-repository=/home/xxx/Documents/model_repository --backend-directory=/home/xxx/Documents/tritonserver/bin/backends

However, i encounter the error (**Unsupported: Triton backend API version does not support this backend**) as listed below:

`
  I1011 05:52:38.046743 19577 onnxruntime.cc:1999] TRITONBACKEND_Initialize: onnxruntime
  I1011 05:52:38.046850 19577 onnxruntime.cc:2012] Triton TRITONBACKEND API version: 1.5
  I1011 05:52:38.046885 19577 onnxruntime.cc:2018] 'onnxruntime' TRITONBACKEND API version: 1.5
  I1011 05:52:38.255083 19577 pinned_memory_manager.cc:240] Pinned memory pool is created at '0x2037ca000' with size 268435456
  I1011 05:52:38.255601 19577 cuda_memory_manager.cc:105] CUDA memory pool is created on device 0 with size 67108864
  I1011 05:52:38.271628 19577 model_repository_manager.cc:1022] loading: kps_post:1
  I1011 05:52:38.372437 19577 model_repository_manager.cc:1022] loading: kps_prep:1
  E1011 05:52:38.380999 19577 model_repository_manager.cc:1186] failed to load 'kps_post' version 1: Unsupported: Triton backend API version does not support this backend
  I1011 05:52:38.473293 19577 model_repository_manager.cc:1022] loading: lpd_prep:1
  E1011 05:52:38.479918 19577 model_repository_manager.cc:1186] failed to load 'kps_prep' version 1: Unsupported: Triton backend API version does not support this backend
  I1011 05:52:38.574248 19577 model_repository_manager.cc:1022] loading: lpd_post:1
  E1011 05:52:38.581159 19577 model_repository_manager.cc:1186] failed to load 'lpd_prep' version 1: Unsupported: Triton backend API version does not support this backend
  I1011 05:52:38.675649 19577 model_repository_manager.cc:1022] loading: lpd:2
  E1011 05:52:38.682231 19577 model_repository_manager.cc:1186] failed to load 'lpd_post' version 1: Unsupported: Triton backend API version does not support this backend
  I1011 05:52:38.776348 19577 model_repository_manager.cc:1022] loading: kps:2
  I1011 05:52:38.874338 19577 tensorrt.cc:4905] TRITONBACKEND_Initialize: tensorrt
  I1011 05:52:38.874528 19577 tensorrt.cc:4918] Triton TRITONBACKEND API version: 1.5
  I1011 05:52:38.874575 19577 tensorrt.cc:4924] 'tensorrt' TRITONBACKEND API version: 1.5
  I1011 05:52:38.875693 19577 tensorrt.cc:4981] TRITONBACKEND_ModelInitialize: lpd (version 2)
  I1011 05:52:38.877180 19577 model_repository_manager.cc:1022] loading: lpr:2
  I1011 05:52:38.882239 19577 tensorrt.cc:4981] TRITONBACKEND_ModelInitialize: kps (version 2)
`

Any idea what's went wrong? Thank you

**Comment by Tabrizian** [comment]
Since you are using the 21.09 version of Triton server, you need to specify the same repo tag when compiling the backend. You need to use `r21.09` instead of TRITON_BACKEND_REPO_TAG in the building from source instructions.
https://github.com/triton-inference-server/python_backend#building-from-source
