### ISSUE TITLE
Can we provide pure cmake builds without mixing python scripts and cmake files and download steps?

### ISSUE THREAD

**Issue by YuxiangJohn** [triton-inference-server/server#3455]
Although the build process controlled by python script is easy to know the build options, the build process will crash such as  the network condition is not good. Why not list out all the dependencies and make a traditional cmake build? The build process is a nightmare for me.... I would love to build step by step following the instruction instead of doing everything in one python script. All in one is cool but not always meet all the requirements.

**Comment by CoderHam** [comment]
You can use the build.py to generate the dockerfiles. These will elaborate the cmake commands that need to be run.

**Comment by YuxiangJohn** [comment]
> You can use the build.py to generate the dockerfiles. These will elaborate the cmake commands that need to be run.

Thanks for your suggestion, I will try.

**Comment by dyastremsky** [comment]
Closed due to inactivity. Please let us know if you need this issue reopened.
