### ISSUE TITLE
Condition checking in ensemble

### ISSUE THREAD

**Issue by kashishvjain** [triton-inference-server/server#3459]
I have two models which I am joining. The output of the first goes as input of the second. I want the ensemble to exit when the first model returns a not found value. Currently, even if the output of the first is null it has to go through the second model wasting time and resources.

Condition check in the ensemble would be great as it would allow me to exit the ensemble after the first model. Some sort of check that can make the model exit would be great.

**Comment by allen-ash** [comment]
Also have this wondering, hope for quick reply.

**Comment by allen-ash** [comment]
@kashishvjain You can check [https://github.com/triton-inference-server/python_backend#business-logic-scripting-beta](https://github.com/triton-inference-server/python_backend#business-logic-scripting-beta). 

> Triton's ensemble feature supports many use cases where multiple models are composed into a pipeline (or more generally a DAG, directed acyclic graph). However, there are many other use cases that are not supported because as part of the model pipeline they require loops, conditionals (if-then-else), data-dependent control-flow and other custom logic to be intermixed with model execution. We call this combination of custom logic and model executions Business Logic Scripting (BLS).

**Comment by Levocetirizine** [comment]
@kashishvjain @allen-ash 
I also need similar feature (https://github.com/triton-inference-server/server/issues/3262), although using business logic or even writing a custom backend could be a possible solution, I still wish some of the basic flow controls (eg. branch, shortcut...) can be integrated in ensemble backend.

I forked the project and customized the ensemble scheduler code to support the feature, might be a reference for you.
(https://github.com/Levocetirizine/server/tree/r21.06-mod) 
(https://github.com/Levocetirizine/server/blob/r21.06-mod/docs/enhanced_ensemble_model.md)
But an officially supported version will be better...

**Comment by dzier** [comment]
The [business logic scripting](https://github.com/triton-inference-server/python_backend#business-logic-scripting) feature is the official method for controlling the flow of your ensemble. It is now out of beta and fully featured.
