### ISSUE TITLE
GPU metrics are not matching with nvidia-smi output

### ISSUE THREAD

**Issue by SaratM34** [triton-inference-server/server#3460]
**Description**
The GPU metrics provided by the metrics endpoint are not matching the actual numbers provided by nvidia-smi command. I am currently using an Tesla T4 GPU with 16GB memory. The **nv_gpu_memory_total_bytes** from metrics endpoint shows 2958032896.000000 bytes ~  2.9GB and the **nv_gpu_memory_used_bytes** shows 534773760.000000 bytes ~ 0.53GB where as actual usage by Triton from nvidia-smi is 8.6GB

**Triton Information**
What version of Triton are you using?
r21.08

Are you using the Triton container or did you build it yourself?
using Triton container
**To Reproduce**
The issue can be reproduced by starting the Triton server and accessing metrics endpoint

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**

**Comment by CoderHam** [comment]
@jbkyang-nvi can you have a look if this is DCGM related?

**Comment by jbkyang-nvi** [comment]
I think this is related to the DCGM update and also our bug fix https://github.com/triton-inference-server/server/pull/3319. Are you seeing this with 21.09 or 21.10?

**Comment by SaratM34** [comment]
@jbkyang-nvi I tried with 21.09. I don't see this issue.
