### ISSUE TITLE
I saved a tensorflow model as the saved_model format of the serialized input of tf.Example, how to deploy the triton service and infer

### ISSUE THREAD

**Issue by lyx564** [triton-inference-server/server#3464]
**Description**

I transformed a tensorflow model as the saved_model format of the serialized input of tf.Example as follows:
![image](https://user-images.githubusercontent.com/52693012/137084665-da964c18-a55f-45a1-809d-742789296cee.png)

The input and output of config.pbtxt are as follows, so I can deploy the triton-server successfully, but I don't know how to build the correct inputs for the triton_client.infer 

input [
  {
    name: "input"  
    data_type: TYPE_STRING
    dims: [ -1 ] 
  }
]
output [
  {
    name: "output" 
    data_type: TYPE_FP32 
    dims: [-1, 2]
  }
]

**Comment by lyx564** [comment]
> Hello have you followed the guide to [quickstart](https://github.com/triton-inference-server/server/blob/main/docs/quickstart.md) to understand how to run infer with server and client and looked at our examples of running with the tensorflow backend? What version of Triton are you using?

I have followed the guide to quickstart and started the triton server successfully and I used the Triton 21.08. 
But I did not find a similar python example in the client example because my inputs is the serialized input of tf.Example

**Comment by ConverJens** [comment]
@lyx564 @jbkyang-nvi 
We have alos tried this but with no luck.

First of all, one needs to send the tf.Example in b64 format:
`base64.b64encode(tf_example_serialized).decode('utf-8')`
which is similar in how you do it if you query tf Serving with http.

We can get it working with tf Serving using both http and grpc but not with Triton. We tried to use the kfserving_v2 protocol to communicate with the Triton server.

**Comment by jbkyang-nvi** [comment]
Hi @ConverJens Triton does handle raw bytes (input doesn't have to be np.arrays).  TFServing handles TF.examples as raw bytes too. 
@lyx564  you're seeing error because the response is not correctly utf-8 encoded. This can be because of TF.example. I'll make a ticket to address this issue and add more examples related to tf.example

**Comment by ConverJens** [comment]
> Hi @ConverJens Triton does handle raw bytes (input doesn't have to be np.arrays). TFServing handles TF.examples as raw bytes too. 

@jbkyang-nvi  I know, i tried to query Triton with a bytes payload setting the length of the bytes payload etc but I didn't get it to work.

> @lyx564 you're seeing error because the response is not correctly utf-8 encoded. This can be because of TF.example. I'll make a ticket to address this issue and add more examples related to tf.example

If you can provide a working example of performing inference with a serialized tf.Example that would be great.

**Comment by lyx564** [comment]
> > Hi @ConverJens Triton does handle raw bytes (input doesn't have to be np.arrays). TFServing handles TF.examples as raw bytes too.
> 
> @jbkyang-nvi I know, i tried to query Triton with a bytes payload setting the length of the bytes payload etc but I didn't get it to work.
> 
> > @lyx564 you're seeing error because the response is not correctly utf-8 encoded. This can be because of TF.example. I'll make a ticket to address this issue and add more examples related to tf.example
> 
> If you can provide a working example of performing inference with a serialized tf.Example that would be great.

In my way, sometimes it works, and sometimes the above error is reported.  So weird....

**Comment by oandreeva-nv** [comment]
Closing due to the lack of activity on this thread. Feel free to follow up with a comment and we will re-open this issue
