### ISSUE TITLE
jimeter test, tps is not stable

### ISSUE THREAD

**Issue by franktz** [triton-inference-server/server#3469]
**Description**
i use triton in my project. I use libhv as my http framework and jimeter to test the project. 
first, libhv is uesd to get the request and download image
second, the image is uesd to as input for triton client
third, inference the input and get output
end,the output is response by libhv.
i use onnxruntime backend.
when i use jimeter test the project, i find tps is not stable,and it will be  decrease. like the picture

![3dda5b8f939f03d721669a53b0c69b6c](https://user-images.githubusercontent.com/6367123/137317857-b08a849f-cba9-4fae-9025-8197f4fbec02.jpg)

What version of Triton are you using?
21.03

Are you using the Triton container or did you build it yourself?
Triton container

**Comment by CoderHam** [comment]
@franktz I would also suggest using a newer version of Triton since 21.03 is over 6 months old

**Comment by dyastremsky** [comment]
Closed due to inactivity. Please let us know if you need this issue reopened.
