### ISSUE TITLE
Triton Explicit Model control mode cloud serving advice

### ISSUE THREAD

**Issue by Deseram** [triton-inference-server/server#3471]
Hi guys,

I need a little advice with deploying Triton inference server with explicit model control. From the looks of it, this mode is the one that gives the user the most control of which model goes live, etc. But the problem I’m not able to solve is how to load models in case the server goes in production and then a new instance spawns up.

The only solution I can think of is to have a service poll the server at regular time intervals, constantly check if my live models are actually live and if not, then load them. All honesty, i’m not a big fan of this solution.

How have you guys gone about solving this problem? Would really appreciate some ideas.

Thanks in advance

**Comment by dzier** [comment]
We do not have good solution for this use case. Our only supported model control modes are listed [here](https://github.com/triton-inference-server/server/blob/main/docs/model_management.md). Is sound like you may want to use Explicit mode, and then create a layer on top of Triton that will intercept the request to find out what model needs to load and explicitly load it. Note this will also require managing the models are are loaded, since models are not automatically unloaded.

**Comment by dzier** [comment]
I am going to mark this as a feature request.

**Comment by rmccorm4** [comment]
Hi @Deseram ,

Just wanted to follow up on this. A few questions:

1. Are you still having issues with this, or have you found some solution or workaround in the meantime?
2. If you want to use EXPLICIT mode but also have a known set of models you always want to load when a new server instance starts up, you can use the `tritonserver ... --load-model <model1> --load-model <model2>` to load some or `tritonserver ... --load-model *` to load all models in the model repositories. Maybe this can help depending on the use case.
3. If you always want to explicitly load models, but make sure new server instances are in-sync with the models loaded in other server instances -- or for example are talking to Tritonserver instances through a load balancer, then I'm not sure we plan to support such behavior yet. I have a more detailed response in this use case here: https://github.com/triton-inference-server/server/issues/3935#issuecomment-1040883270

Let me know your thoughts on this.

**Comment by rmccorm4** [comment]
Closing due to lack of response, will re-open as needed based on response.
