### ISSUE TITLE
looser throw specifier for ‘virtual const char* google::protobuf::FatalException::what() const’

### ISSUE THREAD

**Issue by JaydonChion** [triton-inference-server/server#3478]
Hi,
I am trying to run a cpp triton client on jetson Agx with jetpack 4.6 installed. 
I encountered this error while trying to cmake and make my program : 

`/home/jaydon/Documents/tritonserver/clients/include/google/protobuf/stubs/common.h:199:23: error: looser throw specifier for ‘virtual const char* google::protobuf::FatalException::what() const’
   virtual const char* what() const throw();`

The cmake was built using Cxx 17

I tried building the client repo and run the cpp example, i can run most of the example except those with cuda shm. 
i will have this error 
`CUDA exception (line 113): cudaErrorNotSupported (operation not supported)
`
when i run the cuda shm code

Any idea what causes this to happen? Thank you.

**Comment by tanmayv25** [comment]
@JaydonChion  Were you able to resolve the issue?

**Comment by JaydonChion** [comment]
@tanmayv25 , no I didn't solve the issue. But I managed to found a work around which is to build the code in a DeepStream docker
