### ISSUE TITLE
Is python backend going to support asyncio?

### ISSUE THREAD

**Issue by ZhuYuJin** [triton-inference-server/server#3482]
**Is your feature request related to a problem? Please describe.**
Is python backend going to support asyncio?

**Describe the solution you'd like**
Coroutine has better performance than concurrency in the situation of network IO.

**Describe alternatives you've considered**
Referring to grpc-python, we can start a python thread to run asyncio loop. We also start a c++ thread to sniffer and forward packages.  Python thread and c++ thread communicate with queue.

**Additional context**
Our business has strong reliance on asyncio. We can assign a manpower for the job.

**Comment by ZhuYuJin** [comment]
https://github.com/triton-inference-server/python_backend/blob/main/src/pb_stub.cc#L482

![image](https://user-images.githubusercontent.com/5879410/138087294-9878b31f-6561-4f2c-a86c-6679df237e4e.png)

In current python backend implementation, the coroutine is called synchronously with `asyncio.run`.  It should has bad performance in real workspace.

**Comment by Tabrizian** [comment]
I see.. I am wondering if you do not want to block when the `execute` function returns then when do you need the results from your RPC/HTTP requests and how are you going to use them? Is it something that you want to run in the background regardless of the requests that are being executed on your model?

**Comment by Tabrizian** [comment]
If your requests are batched, you can use async in with the current version of Python backend to create a coroutine for each request to download the images asynchronously. You can also create 10 model instances of your Python model so that each request will be executed independently and the image download happens asynchronously. https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#instance-groups

**Comment by ZhuYuJin** [comment]
Let me explain more explicitly.
[Background] Each request is a user request. Ensemble backend can push all requests to the queue of python backend. By now, python backend receives a request from the queue, executes the request, and sends back the response. Each request is executed synchronously.
[Problem] So, my problem is python backend cannot process multiple requests concurrently in a instance. Asyncio should enable concurrent processing with coroutine. However, python backend use `asyncio.run` to execute async function, which will cause each request is executed synchronously.
[Solution] Merge multiple requests into a batch request should solve the problem in some cases. However, if only one request arrives in the first window, we can only process the first request. And the following requests should wait until the first request is done. If our python function is to download a video, we will achieve a bad performance in the situation.
[Suggestion] My suggestion is to start a new repo `async python backend`. We can start a python thread to run asyncio loop. C++ thread will get data from triton queue, send it to python thread, and wait for the response of python thread.(This is the architecture of grpc-python) I'm wondering whether you are interested in the suggestion.

**Comment by CoderHam** [comment]
@ZhuYuJin we have made a note of your request for adding such a feature.

**Comment by manhtd98** [comment]
did we start this feature?

**Comment by Tabrizian** [comment]
@manhtd98 We have implemented decoupled API support which partially addresses the feature requested here: https://github.com/triton-inference-server/python_backend#decoupled-mode

Having said that we have a feature on the road map to support full async API in python backend but it has not been scheduled.

**Comment by manhtd98** [comment]
I have error with asyncio and memory not auto clean after predict.

**Comment by charlesmelby** [comment]
@Tabrizian Any updates on this?

**Comment by charlesmelby** [comment]
@Tabrizian 
We have a similar use case (although in our case we're waiting on BLS-type triton server requests not downloads).
The decoupled model is a viable alternative but only if it can be called from an ensemble.
Is calling decoupled models from ensembles supported right now?

**Comment by lvmnn** [comment]
Any updates on this? I have the same problem, serial processing of requests cause insufficient performance

**Comment by lvmnn** [comment]
@ZhuYuJin Is there any progress?

**Comment by Tabrizian** [comment]
Sorry for the delayed response. This is on our roadmap but it has not been scheduled yet. We'll let you know as soon as there is an updated.
