### ISSUE TITLE
Version policy `specific` doesn’t work as expected. It doesn’t respect the model_version parameter during inference.

### ISSUE THREAD

**Issue by dugarsumit** [triton-inference-server/server#3485]
**Description**
Version policy specific doesn’t work as expected. It doesn’t respect the model_version parameter during inference.

**Triton Information**
TRITON_VERSION=2.14.0

Are you using the Triton container or did you build it yourself?
TRITON_CONTAINER_VERSION=21.09

**To Reproduce**
1. Use `specific` version policy with python backend models having two versions. In each model file you can add some print lines to indicate which model is being used during the inference.
2. Start the triton server
3. Infer the model using the client by passing the model_version.
4. Repeat step 3 multiple times. You will see randomly being served by one of the model versions irrespective of what model_version was passed in the client.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**
Request should be served by the same model version that was passed in the client.

**Comment by GuanLuo** [comment]
This issue should be fixed by https://github.com/triton-inference-server/python_backend/pull/99 . @dugarsumit can you verify the fix on your side?

**Comment by s402621342** [comment]
I have the same problem is TRITON_VERSION =2.16.0 and got solved in 2.17.0
