### ISSUE TITLE
Clear documentation about all parameters in config.pbtxt meaning?

### ISSUE THREAD

**Issue by allen-ash** [triton-inference-server/server#3489]
**Is your feature request related to a problem? Please describe.** I wonder is there clear explanation about all parameters in config.pbtxt?  Or is there complete documentation like  an library reference?

**Comment by sam-writer** [comment]
I looked through that, and everywhere in the docs but couldn't find an answer to a seemingly simple question: what if an onnx model outputs a Python list of numpy arrays? something like

```
output [
    {
        name: "OUTPUT__0"
        data_type: TYPE_FP32
        dims: [-1, 1, 384]
    },
    {
        name: "OUTPUT__1"
        data_type: TYPE_FP32
        dims: [-1, 12, -1, 64]
    },
    ...
]
?
```
