### ISSUE TITLE
Is it possible to redirect a gRPC request from the Triton client?

### ISSUE THREAD

**Issue by PauloFavero** [triton-inference-server/server#3490]
I have an application that is divided into multiple services. The Triton client would act as an inference middleware. 

In this setup, I have a camera that is capturing images and sending them through gRPC to the Triton client that will submit the image to an inference pipeline. 

At the end of the pipeline, I want to send the result to a server/dashboard using gRPC. I don't want the camera to handle the reply from the client. 
Is this possible somehow? Any ideas on how to do it?
All my services are running inside a docker container. I want to avoid putting the camera and the server/dashboard together with the Triton client. 

**Triton Information**

What version of Triton are you using? 
Server: nvcr.io/nvidia/tritonserver:21.03-py3 
Client: nvcr.io/nvidia/tritonserver:21.03-py3-sdk

**Comment by PauloFavero** [comment]
Hi @jbkyang-nvi,

Thanks for your reply. 

Yes, I can use shared memory to output the results but, in that case I would still need to give back a dummy response to the camera like an "ok", right? If so, that's no problem.

In another way, instead of sharing the result in the shared memory, could I transfer the classification output through gRPC to the dashboard service? It means that I would trigger a gRPC request inside a previous one.

**Comment by jbkyang-nvi** [comment]
Triton client does not do redirections. You probably would need to set up a middleman service that handles the sending and the recieving
