### ISSUE TITLE
Unable to use shm using simple_http_shm_client

### ISSUE THREAD

**Issue by kalyangande96** [triton-inference-server/server#3494]
**Description**
I want to use shm for inference. I have followed quickstart.md from docs but I'm not able to use shm.

**Triton Information**
I'm using tritonserver:21.08-py3 server and tritonserver:21.08-py3-sdk images.

Are you using the Triton container or did you build it yourself?

I'm using Triton container.

**To Reproduce**

1. I have downloaded model repository and used below command to run the triton.

`docker run --rm -p 8000:8000 -p 8001:8001 -p 8002:8002 -v /home/hadoop/kalyan_workspace/triton_quickstart/server/docs/examples/model_repository:/models nvcr.io/nvidia/tritonserver:21.08-py3 tritonserver  --model-repository=/models --log-verbose=true`

2. I have used this command below to run sdk container.
`docker run -it --rm --net=host nvcr.io/nvidia/tritonserver:21.08-py3-sdk`

3. In sdk container, `/workspace/install/bin/simple_http_shm_client` I have used previous command.
4.  Got an error -  {"error":"Unable to open shared memory region: '/input_simple'"}
error: failed to register input shared memory region: Unable to open shared memory region: '/input_simple'

Please find the server log below.

I1025 12:43:23.622638 1 http_server.cc:2715] HTTP request: 2 /v2/systemsharedmemory/unregister
I1025 12:43:23.623131 1 http_server.cc:2715] HTTP request: 2 /v2/cudasharedmemory/unregister
I1025 12:43:23.623737 1 http_server.cc:2715] HTTP request: 2 /v2/systemsharedmemory/region/input_data/register
**I1025 12:43:23.623806 1 shared_memory_manager.cc:127] shm_open failed, errno: 2**

**Comment by z1521183003** [comment]
Description
I want to use shm for inference. I have followed quickstart.md from docs but I'm not able to use shm.

Triton Information
I'm using tritonserver:24.11-py3 server and tritonserver:24.11-py3-sdk images.

Are you using the Triton container or did you build it yourself?

I'm using Triton container.

To Reproduce

I have downloaded model repository and used below command to run the triton.
docker run --gpus=1 --rm --ipc=host --net=host --shm-size 8G -v ${PWD}/model_repository:/models nvidia/tritonserver:24.11-py3 tritonserver --log-verbose=1 --model-repository=/models


I have used this command below to run sdk container.
docker run -it --rm --net=host nvidia/tritonserver:24.11-py3-sdk bash

In sdk container, /workspace/install/bin/simple_http_shm_client I have used previous command.
![image](https://github.com/user-attachments/assets/c5811259-35b9-459f-a612-dd539c5b2e95)


Got an error - {"error":"Unable to open shared memory region: '/input_simple'"}
Creating new channel with url:localhost:8001
Unregistered all system shared memory regions
Unregistered all system shared memory regions
error: failed to register input shared memory region: Unable to open shared memory region: '/input_simple'



Please find the server log below.

I1217 01:54:57.149670 1 grpc_server.cc:152] "Process for SystemSharedMemoryUnregister, rpc_ok=1, 2 step START"
I1217 01:54:57.149690 1 grpc_server.cc:102] "Ready for RPC 'SystemSharedMemoryUnregister', 3"
I1217 01:54:57.149756 1 grpc_server.cc:152] "Process for SystemSharedMemoryUnregister, rpc_ok=1, 2 step COMPLETE"
I1217 01:54:57.149767 1 grpc_server.cc:358] "Done for SystemSharedMemoryUnregister, 2"
I1217 01:54:57.149900 1 grpc_server.cc:152] "Process for CudaSharedMemoryUnregister, rpc_ok=1, 2 step START"
I1217 01:54:57.149912 1 grpc_server.cc:102] "Ready for RPC 'CudaSharedMemoryUnregister', 3"
I1217 01:54:57.149944 1 grpc_server.cc:152] "Process for CudaSharedMemoryUnregister, rpc_ok=1, 2 step COMPLETE"
I1217 01:54:57.149953 1 grpc_server.cc:358] "Done for CudaSharedMemoryUnregister, 2"
I1217 01:54:57.150148 1 grpc_server.cc:152] "Process for SystemSharedMemoryRegister, rpc_ok=1, 2 step START"
I1217 01:54:57.150161 1 grpc_server.cc:102] "Ready for RPC 'SystemSharedMemoryRegister', 3"
I1217 01:54:57.150183 1 shared_memory_manager.cc:141] "shm_open failed, errno: 2"
I1217 01:54:57.150227 1 grpc_server.cc:152] "Process for SystemSharedMemoryRegister, rpc_ok=1, 2 step COMPLETE"
I1217 01:54:57.150234 1 grpc_server.cc:358] "Done for SystemSharedMemoryRegister, 2"

![image](https://github.com/user-attachments/assets/4178ef1c-08af-4798-b8eb-d064ee284513)
