### ISSUE TITLE
Unable to build CPU only image

### ISSUE THREAD

**Issue by neozhangthe1** [triton-inference-server/server#3498]
**Description**
By running the following command
python3 compose.py --backend python --backend onnx --backend torch --repoagent checksum

We get:

version 2.16.0dev
using container version 21.09
pulling container:nvcr.io/nvidia/tritonserver:21.09-cpu-only-py3
Error response from daemon: manifest for nvcr.io/nvidia/tritonserver:21.09-cpu-only-py3 not found: manifest unknown: manifest unknown
error: docker pull container nvcr.io/nvidia/tritonserver:21.09-cpu-only-py3 failed, None

**Triton Information**
What version of Triton are you using?
21.09

Are you using the Triton container or did you build it yourself?
Using the Triton container

**To Reproduce**
python3 compose.py --backend python --backend onnx --backend torch --repoagent checksum

**Comment by jbkyang-nvi** [comment]
Hi @neozhangthe1 sorry for the late update. We are actually not releasing the CPU-only container composition tool yet. However, customers today can use our build.py script to generate a CPU only build: https://github.com/triton-inference-server/server/blob/main/docs/build.md. Only the following backends are available for a non-GPU / CPU-only build: identity, repeat, square, onnxruntime, openvino, and python.
