### ISSUE TITLE
Save files in server

### ISSUE THREAD

**Issue by sofiaele** [triton-inference-server/server#3499]
Hello, 
I am running triton server via docker. I am using a python client to infer via http requests. What I want to achieve is to save the input audio files of client in server side (probably in a specified folder) for logging reasons. For instance, I would like to save a <date_time_timestamp>.wav file. I have not found anything related to this so far. 

Is there any way to achieve such a functionality? 
Thanks in advance!

**Comment by CoderHam** [comment]
> I must have created a model that uses that specific backend, that is, that takes the tensor signal as input (and does not produce any output?
 
 Yes. You can refer to the [identity](https://github.com/triton-inference-server/identity_backend) backend for reference/examples of how to create a custom backend.
 
 > I need to have mounted a volume, so that the folder where the custom backend has stored the files corresponds to a local folder. 
 
That is right.
