### ISSUE TITLE
Error while deploying nvidia triton inference on AWS EKS

### ISSUE THREAD

**Issue by venkateshp-kore** [triton-inference-server/server#3504]
**Description**
Deploying triton inference on AWS EKS. Pod crashes with error that the shm-size limit error

NOTE: The SHMEM allocation limit is set to the default of 64MB.  This may be
   insufficient for the inference server.  NVIDIA recommends the use of the following flags:
   nvidia-docker run --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 ...

**Triton Information**
What version of Triton are you using?
21.08
Are you using the Triton container or did you build it yourself?
Triton container as documented for AWS EKS deployment using nvidia helm chart
**To Reproduce**
Steps to reproduce the behavior.
Deploy the latest nvidia triton inference over AWS EKS 

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**
Inference server pod to be started properly

**Comment by CoderHam** [comment]
@venkateshp-kore you would need to talk to some AWS EKS folks. I'd recommend reaching out to them on their respective forum . Closing this issue since it is a limitation on EKS side.
