### ISSUE TITLE
"Failed to allocate CUDA memory with byte size" WARNNING

### ISSUE THREAD

**Issue by LightToYang** [triton-inference-server/server#3511]
DALI backend and TensorRT are used with NGC Tritonserver:2108.
What's the meaning of the following warnning ?

![image](https://user-images.githubusercontent.com/17929130/139394033-0775b57b-6b60-4882-a6b4-13c358f3b047.png)

**Comment by dyastremsky** [comment]
There is not enough GPU memory available for your model, so it is falling back to using pinned system memory.

**Comment by Vozf** [comment]
It's also possible that the amount of pinned memory isn't enough, that could be increased from default 64mb to 512mb for instance via
```
--cuda-memory-pool-byte-size 0:536870912
```
