### ISSUE TITLE
`cudaCheck` fails when provided `_CUDA_COMPAT_REALLIB`

### ISSUE THREAD

**Issue by sunhs** [triton-inference-server/server#3518]
# Description

In the environment variables I got
```
_CUDA_COMPAT_STATUS=No CUDA-capable device is detected (CUDA_ERROR_NO_DEVICE) cuInit()=100
```

According to `/etc/shinit_v2`, this env variable is set by calling `/usr/local/bin/cudaCheck` provided `LD_LIBRARY_PATH="${_CUDA_COMPAT_REALLIB}"`. But when I manually run `cudaCheck` in the container, it says "CUDA Driver OK". I suspect something goes wrong when `${_CUDA_COMPAT_REALLIB}` is provided.

# Triton Information

I tried:
- `nvcr.io/nvidia/tritonserver:21.09-py3[-min]`
- `nvcr.io/nvidia/tritonserver:21.10-py3[-min]`
- a built container using `build.py` based on `nvcr.io/nvidia/tritonserver:21.10-py3-min`

and all of them behaves the same

# System Information

- Ubuntu 16.04
- nvidia driver 455.45.01
- GPU: GeForce RTX 2080 Ti

# To Reproduce

### 1. start the container

```
sudo docker run -it --rm --gpus=all nvcr.io/nvidia/tritonserver:21.10-py3 bash
```

then something prompts:

```
WARNING: CUDA Minor Version Compatibility mode ENABLED.
  Using driver version 455.45.01 which has support for CUDA 11.1.  This container
  was built with CUDA 11.4 and will be run in Minor Version Compatibility mode.
  CUDA Forward Compatibility is preferred over Minor Version Compatibility for use
  with this container but was unavailable:
  [[No CUDA-capable device is detected (CUDA_ERROR_NO_DEVICE) cuInit()=100]]
  See https://docs.nvidia.com/deploy/cuda-compatibility/ for details.
```

IMO, the `CUDA Forward Compatibility` should be on since I'm using the 455.45.01 driver.

### 2. run cudaCheck

It's OK. `CUDA Driver OK` is shown. This seems to prove my point that `CUDA Forward Compatibility` should be on.

### 3. Some inspects

In `/usr/local/cuda/compat/lib.real/` which is also `$_CUDA_COMPAT_REALLIB` there are:
- libcuda.so.470.57.02
- libnvidia-ptxjitcompiler.so.470.57.02

By `ldconfig -p` I found that, in `/usr/lib/x86_64-linux-gnu/` there are:
- libcuda.so.455.45.01
- libnvidia-ptxjitcompiler.so.455.45.01

### 4. start triton server

```
sudo docker run --gpus=1 --rm -p8000:8000 -p8001:8001 -p8002:8002 -v /full/path/to/docs/examples/model_repository:/models nvcr.io/nvidia/tritonserver:21.10-py3 tritonserver --model-repository=/models
```

It fails to start, and the following line occupies most of the log:

```
Internal: CUDA runtime implicit initialization on GPU:0 failed. Status: the provided PTX was compiled with an unsupported toolchain.
```

At this point `LD_LIBRARY_PATH=/usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64`, where `/usr/local/cuda/compat/lib` doesn't exist, because in `/etc/shinit_v2`, `cudaCheck` failed and the symlink to `/usr/local/cuda/compat/lib.real/` is not created.

### 5. manually start triton server

Start a bash in the container and run:

```
LD_LIBRARY_PATH=/usr/local/cuda/compat/lib.real:$LD_LIBRARY_PATH tritonserver --model-repository /models/
```

This time the server succeeds to start.

# Questions

Seems that `libcuda.so.470.57.02` and `libnvidia-ptxjitcompiler.so.470.57.02` should be used to start the server. But `libcuda.so.455.45.01` and `libnvidia-ptxjitcompiler.so.455.45.01` can make `cudaCheck` pass. So what's the difference between them and which should be used?

**Comment by dyastremsky** [comment]
Forward compatibility is applicable for certain GPUs and toolkits. More information is available here: https://docs.nvidia.com/deploy/cuda-compatibility/#forward-compatibility-title

The error seems to result from the way the CUDA toolkit and runtime was installed. There are many reasons the PTX error could result, likely from a mismatch between the driver and compilation toolchain.

Those are two different versions. It seems like your system has two versions of CUDA drivers and compilers installed (470.57.52 and 455.45.01), so you may want to go through and ensure the installations are valid and not conflicting. It seems like your 455.45.01 driver and compilers are correctly configured, which is why the cudaCheck passes for them.

**Comment by sunhs** [comment]
@dyastremsky By saying `It seems like your system has two versions of CUDA drivers and compilers installed`, do you mean in the container or on the host system?

In the container, by `nvcc -V` I got:

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Aug_15_21:14:11_PDT_2021
Cuda compilation tools, release 11.4, V11.4.120
Build cuda_11.4.r11.4/compiler.30300941_0
```

With `LD_LIBRARY_PATH` unset, `nvidia-smi` gives:

```
NVIDIA-SMI 455.45.01    Driver Version: 455.45.01    CUDA Version: 11.1
```

With `LD_LIBRARY_PATH=/usr/local/cuda/compat/lib.real`, `nvidia-smi` gives:

```
 NVIDIA-SMI 455.45.01    Driver Version: 455.45.01    CUDA Version: 11.4
```

I believe `libcuda.so.455.45.01` and `libnvidia-ptxjitcompiler.so.455.45.01` are mounted from the host system.

Could you give me some hints on how to find out conflicting installations ? For example, by looking into `dpkg -l` or `ldconfig -p`? Or by looking into what packages ?

Thanks.

**Comment by sunhs** [comment]
@dyastremsky OK, I'm sorry. Seems that the GeForce RTX 2080 Ti does not support forward compatibility. This can explain why the `470.57.02` libs don't work as expected while the `455.45.01` ones do. I've tested on the machine with Tesla V100 and the forward compatibility mode was on.

Thanks anyway !
