### ISSUE TITLE
Custom backend (C++ or python) Whats the difference ?

### ISSUE THREAD

**Issue by yichong96** [triton-inference-server/server#3523]
I want to be able to use triton to implement a person REID task. Most probably I think I would have to create a custom backend as it involves more logic than just model inference. 

I am wondering if there is any difference between a c++ or python backend implementation. I know c++ runs faster than python. I would need some advice on which language to proceed with. I am generally more comfortable writing code in python. 

Thank you !

**Comment by dyastremsky** [comment]
Either one should work. Note that many of our supported and example backends are written in C++, so you'd have more reference code. Both C++ and Python are supported, so it's ultimately a personal choice.

**Comment by yichong96** [comment]
hmm I see thank you. Now that I think of it, Titron backend should only be used to perform model inference. The person REID tasks needs model inference results as well as access to a database of images. I should think it is better for titron to just return the inference results and let the client handle database operations. Would you think so ?

**Comment by dyastremsky** [comment]
Sure. Triton is meant for model inference. Other parts of your system would not be in the backend.

**Comment by yichong96** [comment]
All right thank you for your help ! will close this issue.
