### ISSUE TITLE
Prometheus not working with Triton

### ISSUE THREAD

**Issue by vsatpathy** [triton-inference-server/server#3525]
I am facing the same issue, but I guess the issue for all of us is with the integration with prometheus.
As when I open the Prometheus UI it always keeps saying that http://localhost:8002/metrics is down

<img width="1676" alt="Screenshot 2021-11-02 at 10 14 32 PM" src="https://user-images.githubusercontent.com/61777986/139908717-90dc4b25-5320-40dc-a1b1-079af92372c1.png">

Although I do get response from the triton metrics end point as expected - 
<img width="908" alt="Screenshot 2021-11-02 at 10 16 12 PM" src="https://user-images.githubusercontent.com/61777986/139908972-e7d70dc4-3c37-4c5a-8a61-f27cba23c61c.png">

And hence when I try to integrate it with Grafana, the system keeps throwing an error.
Has anyone been able to resolve this issue?

_Originally posted by @vsatpathy in https://github.com/triton-inference-server/server/issues/2091#issuecomment-957935491_

**Comment by dyastremsky** [comment]
As @deadeyegoodwin mentioned in #2091, it may not be possible to point Grafana directly at Triton. Perhaps someone else can provide more guidance on how to do so, so we can leave this issue open for a bit.

**Comment by vsatpathy** [comment]
So I didn't connect Triton directly to Grafana. I re-directed prometheus exported metrics to grafana. But still to no avail.

**Comment by deadeyegoodwin** [comment]
Did you try our deployment examples in the deploy/ directory? Grafana project should have documentation on how to integrate with prometheus database. Closing. Reopen if you have additional information.

**Comment by khazamaa** [comment]
hello all,
can anyone help me in setting up promethues in a single node system.

**Comment by dyastremsky** [comment]
Hi Khazamaa, if you have a specific question related to setup, please open a new issue with your detailed question. There is some information located [in the metrics documentation](https://github.com/triton-inference-server/server/blob/main/docs/metrics.md) and you may be able to find external documentation written by Triton's users to help get you started. This issue is related to connecting to Grafana and has been closed.
