### ISSUE TITLE
max_batch_size in config.pbtxt refer to model batch size or request batch size ?

### ISSUE THREAD

**Issue by yichong96** [triton-inference-server/server#3527]
From what I understand, the [docs](https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md) on `max_batch_size` seem to indicate that the batching refers to batching of `request` objects. 

Reading the backend code for onnx run time seems to confirm this as well 

Code snippet in `onnxruntime.cc => ModelInstanceState::ProcessRequests`
```
  const int max_batch_size = model_state_->MaxBatchSize();

  // For each request collect the total batch size for this inference
  // execution. The batch-size, number of inputs, and size of each
  // input has already been checked so don't need to do that here.
  size_t total_batch_size = 0;
  for (size_t i = 0; i < request_count; i++) {
    // If we get a nullptr request then something is badly wrong. Fail
    // and release all requests.
    if (requests[i] == nullptr) {
      RequestsRespondWithError(
          requests, request_count,
          TRITONSERVER_ErrorNew(
              TRITONSERVER_ERROR_INTERNAL,
              std::string(
                  "null request given to ONNX Runtime backend for '" + Name() +
                  "'")
                  .c_str()));
      return;
    }

    if (max_batch_size > 0) {
      // Retrieve the batch size from one of the inputs, if the model
      // supports batching, the first dimension size is batch size
      TRITONBACKEND_Input* input;
      TRITONSERVER_Error* err =
          TRITONBACKEND_RequestInputByIndex(requests[i], 0 /* index */, &input);
      if (err == nullptr) {
        const int64_t* shape;
        err = TRITONBACKEND_InputProperties(
            input, nullptr, nullptr, &shape, nullptr, nullptr, nullptr);
        total_batch_size += shape[0];
      }
      if (err != nullptr) {
        RequestsRespondWithError(requests, request_count, err);
        return;
      }
    } else {
      total_batch_size += 1;
    }
  }

  // If there are no valid payloads then no need to run the inference.
  if (total_batch_size == 0) {
    return;
  }
```
However, the docs also mention this paragraph below, and it seems to me that `max_batch_size` refers to the batch size of the input tensors that is being fed into the model rather than the `request` batch size ?

> Input and output shapes are specified by a combination of max_batch_size and the dimensions specified by the input or output dims property. For models with max_batch_size greater-than 0, the full shape is formed as [ -1 ] + dims. For models with max_batch_size equal to 0, the full shape is formed as dims. For example, for the following configuration the shape of "input0" is [ -1, 16 ] and the shape of "output0" is [ -1, 4 ].

Hope I am able to clarify my understanding.

**Comment by yichong96** [comment]
What if each request sends more than one tensor ? Eg. each request contains a batch of 8 tensors. What should the max batch size be ?

**Comment by dyastremsky** [comment]
The use of the word batch in your reply is a little ambiguous for me. If you are manually batching, you can make the first dimension in the shape -1 to allow for your model to handle it.

You are still sending one tensor per input/output, just with an extra dimension (to combine all the tensors into one tensor).  In the case you are manually batching and do not want Triton to do so, you can set the max_batch_size to 1 if your model supports batching, otherwise 0.

If you mean something else, I am not sure how you plan to send multiple tensors in one request. Your model would expect your requests to follow the format specified in config.pbtxt.

**Comment by yichong96** [comment]
@dyastremsky In the image client python file, each request sends a batch of images to the server as in the code snippet below.

```
for idx in range(FLAGS.batch_size):
        input_filenames.append(filenames[image_idx])
        repeated_image_data.append(image_data[image_idx])
        image_idx = (image_idx + 1) % len(image_data)
        if image_idx == 0:
            last_request = True

        if max_batch_size > 0:
            batched_image_data = np.stack(repeated_image_data, axis=0)
        else:
            batched_image_data = repeated_image_data[0]
        # Send request
        try:
            for inputs, outputs, model_name, model_version in requestGenerator(
                    batched_image_data, input_name, output_name, dtype, FLAGS):
                sent_count += 1
                if FLAGS.streaming:
                    triton_client.async_stream_infer(
                        FLAGS.model_name,
                        inputs,
                        request_id=str(sent_count),
                        model_version=FLAGS.model_version,
                        outputs=outputs)
```

This means that the model on the server should have the 1st dim  == `Flags.batch_size` specified on the client side?

**Comment by dyastremsky** [comment]
@tanmayv25 Any chance you can clarify if the above is right?

My understanding is that the batching was performed by the server, but the above code sample seems to indicate that you can also perform batching on the client side. In which case the first dimension of each input would be the batch size sent (-1 in the config file). Is that correct?

**Comment by tanmayv25** [comment]
The `max_batch_size` in the model config is a property of model. It indicates what's the max possible shape value for the first dimension that the model can support. 

In triton client, batch size is just treated as any other variable dimension. The user can send requests with any supported shape. 

To better explain the relation, let's assume the max_batch_size is set to 10,  and onnx model supports shape [-1, 256, 256]
The client can send 4 images in first request, 2 in second request and 4 in third request.
Assuming the three requests were sent in quick succession such that max_queue_delay time for dynamic batcher was not elapsed, Triton will form a batch of these three requests(the `request_count` in backend code above will be 3).
The tensor data from the three requests will be merged and model will execute with input tensor shaped [10, 256, 256].

Client can also send a request with 10 images. The backend will only get one request in this case as max_batch_size is already reached. In third case, client can send requests with single images. The backend may get upto 10 requests in this case.

Triton dynamic batcher can only grow batches and not split them. Choosing efficient `max_batch_size` really depends upon your model. But at the very least it should be atleast as large as the size client is expected to send in a single request. You can see [model_analyzer](https://github.com/triton-inference-server/model_analyzer) for tuning these parameters.

**Comment by yichong96** [comment]
@tanmayv25 Thank you for the detailed explanation ! it clarifies alot. I guess it would be detrimental if the onnx model supports only a fixed batch size input. Eg. [10, 3, 224,224] because if the only request that comes in has batch size < 10, then the model would fail to provide an output because the 1st dim shape it is expecting is not 10 ? 

Is my understanding on this correct ?

**Comment by tanmayv25** [comment]
Yes. For dynamic batching, the first dimension must be variable in model.
Triton can run inference on model with shape [x, 256, 256], where x can be from 1 to 10.

 For a fixed shape model, the client can send only request with that shape. [10, 256, 256] in above case. The max batch size in the config should be set 0 too.

**Comment by yichong96** [comment]
Thank you very much. Managed to run model inference with batching with both your help ! @dyastremsky @tanmayv25

**Comment by Lennon-cheng** [comment]
> 



> The `max_batch_size` in the model config is a property of model. It indicates what's the max possible shape value for the first dimension that the model can support.
> 
> In triton client, batch size is just treated as any other variable dimension. The user can send requests with any supported shape.
> 
> To better explain the relation, let's assume the max_batch_size is set to 10, and onnx model supports shape [-1, 256, 256] The client can send 4 images in first request, 2 in second request and 4 in third request. Assuming the three requests were sent in quick succession such that max_queue_delay time for dynamic batcher was not elapsed, Triton will form a batch of these three requests(the `request_count` in backend code above will be 3). The tensor data from the three requests will be merged and model will execute with input tensor shaped [10, 256, 256].
> 
> Client can also send a request with 10 images. The backend will only get one request in this case as max_batch_size is already reached. In third case, client can send requests with single image. The backend may get upto 10 requests in this case.
> 
> Triton dynamic batcher can only grow batches and not split them. Choosing efficient `max_batch_size` really depends upon your model. But at the very least it should be atleast as large as the size client is expected to send in a single request. You can see [model_analyzer](https://github.com/triton-inference-server/model_analyzer) for tuning these parameters.

The reply said that “Triton dynamic batcher can only grow batches and not split them.”
I understand that this doesn't work, when I set max_batch_size to 8, but client send 10 batch in request.
My test results have been verified：
config.pbtxt:
<img width="356" alt="image" src="https://user-images.githubusercontent.com/33142144/219256620-f620687d-1bf6-41b5-83ec-935fac806d06.png">

client request error:
<img width="977" alt="image" src="https://user-images.githubusercontent.com/33142144/219257313-5f18696e-5bc3-4a2f-939a-0f1042b0c5b0.png">


Are my tests normal？   
Looking forward to your reply! @tanmayv25

**Comment by dyastremsky** [comment]
Yes, that is expected behavior. You set the max_batch_size to 8 and tried to send a batch size of 10. Error checking code is [here](https://github.com/triton-inference-server/core/blob/066f63aa57c05240da179a4ea4679c761383cf3e/src/infer_request.cc#L905-L913).

Please open a new issue if you have further questions.
