### ISSUE TITLE
TensorRT Backend Installation Error

### ISSUE THREAD

**Issue by sarperkilic** [triton-inference-server/server#3529]
**Description**

Hello,

I am trying to install tensorRT backend. 
First, I clone this repo https://github.com/triton-inference-server/tensorrt_backend
Then follow the steps.

cmake -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/install -DTRITON_BACKEND_REPO_TAG=r21.07 -DTRITON_CORE_REPO_TAG=r21.07 -DTRITON_COMMON_REPO_TAG=r21.07 ..

when I run  $make install command, I got an error like this:

[ 60%] Building CXX object CMakeFiles/triton-tensorrt-backend.dir/src/tensorrt.cc.o
/home/user/Downloads/tritonserver2.12.0-jetpack4.6/backends/tensorrt_backend/src/tensorrt.cc:36:10: fatal error: triton/common/nvtx.h: No such file or directory
 #include "triton/common/nvtx.h"
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/triton-tensorrt-backend.dir/build.make:81: recipe for target 'CMakeFiles/triton-tensorrt-backend.dir/src/tensorrt.cc.o' failed
make[2]: *** [CMakeFiles/triton-tensorrt-backend.dir/src/tensorrt.cc.o] Error 1
CMakeFiles/Makefile2:165: recipe for target 'CMakeFiles/triton-tensorrt-backend.dir/all' failed
make[1]: *** [CMakeFiles/triton-tensorrt-backend.dir/all] Error 2
Makefile:148: recipe for target 'all' failed

What should I do?

I think, I have to give the tensorRT path to the cmake command but I couldnt find the TensorRT path.
I am using Jetpack 4.6 and TensorRT 8.0.1.6 is installed on my Jetson.

Where can I find the TensorRT path ?
And what else should I do to install tensorRT backend.

Thanks

**Triton Information**
What version of Triton are you using?
r21.07
Are you using the Triton container or did you build it yourself?
Build myself
**To Reproduce**
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**

**Comment by CoderHam** [comment]
@sarperkilic can you try with NVTX disabled? Add the `-DTRITON_ENABLE_NVTX:BOOL=OFF` flag?

**Comment by sarperkilic** [comment]
@CoderHam Hello, yes I try 

I got the same error when I run make install command

[ 60%] Building CXX object CMakeFiles/triton-tensorrt-backend.dir/src/tensorrt.cc.o
/home/inovako/Downloads/tritonserver2.12.0-jetpack4.6/backends/tensorrt_backend/src/tensorrt.cc:36:10: fatal error: triton/common/nvtx.h: No such file or directory
 #include "triton/common/nvtx.h"
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/triton-tensorrt-backend.dir/build.make:81: recipe for target 'CMakeFiles/triton-tensorrt-backend.dir/src/tensorrt.cc.o' failed
make[2]: *** [CMakeFiles/triton-tensorrt-backend.dir/src/tensorrt.cc.o] Error 1
CMakeFiles/Makefile2:165: recipe for target 'CMakeFiles/triton-tensorrt-backend.dir/all' failed
make[1]: *** [CMakeFiles/triton-tensorrt-backend.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2


Also, I am sharing the cmake code output

-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- RapidJSON found. Headers: /usr/include
-- RapidJSON found. Headers: /usr/include
-- Found CUDAToolkit: /usr/local/cuda/include (found version "10.2.300") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "10.2") 
-- Using CUDA 10.2
-- Using CUDA 10.2
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/Downloads/tritonserver2.12.0-jetpack4.6/backends/tensorrt_backend/build

**Comment by sarperkilic** [comment]
Any help please? @CoderHam

**Comment by CoderHam** [comment]
@sarperkilic which branch of TensorRT are you using for your build?

**Comment by zhenxingsh** [comment]
I think your tensorrt_backend is not in r21.07 branch，you should keep branch consistent with common\backend\core.

**Comment by CoderHam** [comment]
@zhenxingsh is right. @sarperkilic please fix the branch names to be consistent with the version you are building for
