### ISSUE TITLE
CondaPackError: Cannot pack an environment with editable packages

### ISSUE THREAD

**Issue by gioipv** [triton-inference-server/server#3546]
**Cannot pack an environment with editable packages**
I am using `python backend` in triton. In my model, I am using an custom build package. It is: [DCNv2](https://github.com/MatthewHowe/DCNv2). It will raise an error when run `conda-pack`
**Reproduce**
Firstly, creating an env with conda, and activate it
+ Pip install the packages
+ For build [DCNv2](https://github.com/MatthewHowe/DCNv2), just clone the source code and then run `sh make.sh`, in envs with torch 1.5.1 and torchvision 0.6.1, cuda 10.2
==> When [packing conda envs](https://github.com/triton-inference-server/python_backend/tree/r21.07#2-packaging-the-conda-environment) using `conda-pack`. Then it raise an error:
```
Collecting packages...
CondaPackError: Cannot pack an environment with editable packages
installed (e.g. from `python setup.py develop` or
 `pip install -e`). Editable packages found:
-CenterNet/models/networks/DCNv2
```
I think this might be a feature in future ??? ^^ 
Or not, could you share with me an idea for solution for this ^^ Thank you very much

**Comment by dzier** [comment]
This looks like a file permissions issue. The error is stating that `CenterNet/models/networks/DCNv2` is editable and CondaPack cannot pack an environment with an editable package. Try removing write permissions on the file.

In general, this is an issue with your file structure, and not related to Triton or the Python Backend,

**Comment by gioipv** [comment]
Hello @dzier  thank you for reply
I can not remove DCNv2 package because It used in my model. `python backend` use `conda-pack` for packing environment, but run `conda-pack` just work with the packages: numpy,torch,cv2.... (installed with pip). And, when we use a editable package such as `DCNv2` (above). 'conda-pack' will not work, and will raise an error.

**Comment by gioipv** [comment]
Halo, after some day, i find a solution, 
I build an docker image from triton image, in `Dockerfile`, build [DCNv2] package , and copy .so file (the lib file) of DCNv2 to `WORKDIR`
```
# from base image
FROM nvcr.io/nvidia/tritonserver:21.07-py3
... 
# install python, the requirement of DCNv2
RUN apt-get -y install python3  && apt-get -y install python3-pip
...
# install the DCNv2 package
RUN cd /.../DCNv2 && python3 setup.py build develop && cp *.so /opt/tritonserver
...
# set WORKDIR
WORKDIR /opt/tritonserver
...
```
It worked for me
