### ISSUE TITLE
How to measure performance (throughput, latency) when running two different models run concurrently?

### ISSUE THREAD

**Issue by Michelvl92** [triton-inference-server/server#3553]
The title shows directly my question:

How to measure performance (throughput, latency) when running two different models run concurrently?

To be more specific, I want to perform a test with `perf_analyzer` what the (throughput, latency) is when two do inferences and compare that when only running one of those models.

**Comment by dzier** [comment]
Multi-model model analysis is currently a feature that is not supported in perf_analyzer or Model Analyzer. However, this is a feature that is heavily requested and we are actively working on.  

Right now, you can do an experiment, but it is not very accurate. For example, you can have single Triton instance loaded with both models and then have two perf_analyzers, one for each model. They are not coordinated though and could starve the requests from one another.
