### ISSUE TITLE
python backend model instances as threads instead of separate processes?

### ISSUE THREAD

**Issue by user473** [triton-inference-server/server#3560]
Hello, our current issue is that when we are serving a model for python backend that contains some gpu processing such as pytorch code, each model instance initializes a huge cuda context(about 1.4Gib). Since this happens for each model instance, it makes it near impossible for us to serve several python models. 
We noticed that this happens because each python model instance is created in their own separate process. 
If we make the python backend to have a single process and its model instances as sub-threads, wouldn't this make all model instances share a single cuda context and save huge amounts of gpu ram and potentially increase performance?(due to less cuda context switching)
Since there could be GIL concern for non-gpu use cases, I believe maybe an argument to toggle would best serve all use cases.
We know that ideally we should use other backends for a gpu model, but our hands are tied due to difficulties in scripting a complicated sequence generator with many logics. 
Thanks!

**Comment by dzier** [comment]
Each python model instance runs as its process to ensure that GIL is handled correctly. GIL has nothing to do with GPU and CPU being used. A CUDA context itself should not take 1.2 GB. Is your python model allocating CUDA memory? This is the likely cause of the memory usage and that would not change even if using a single process.

**Comment by dzier** [comment]
It also possible to use MPS to share a single CUDA context across all CUDA processes on the system. https://docs.nvidia.com/deploy/pdf/CUDA_Multi_Process_Service_Overview.pdf

**Comment by user473** [comment]
> It also possible to use MPS to share a single CUDA context across all CUDA processes on the system. https://docs.nvidia.com/deploy/pdf/CUDA_Multi_Process_Service_Overview.pdf

I could be mistaken somehow, but isn’t sharing cuda context memory no longer viable if using volta or newer, due to newly introduced mps memory isolation? We confirmed this with testing where we saw almost no reduction in gpu memory usage even with mps running

**Comment by dzier** [comment]
MPS should allow you share context with the Kepler Hyper-Q. From the documentation: 

> The MPS runtime architecture
is designed to transparently enable co-operative multi-process CUDA applications,
typically MPI jobs, to utilize Hyper-Q capabilities on the latest NVIDIA (Kepler-based)
GPUs. 

I am not sure if this addresses your issue though.

Is there a reason you are not using the PyTorch Backend to load the PyTorch model? If you need the additional logic from Python, you could use Business Logic Scripting (https://github.com/triton-inference-server/python_backend#business-logic-scripting-beta) in an ensemble with the PyTorch model running on a PyTorch backend.

**Comment by user473** [comment]
We'll look into that, thank you!
