### ISSUE TITLE
How to send batch with different sizes in inference client request

### ISSUE THREAD

**Issue by mshmnv** [triton-inference-server/server#3564]
I want to send several images to model in one inference request. Now I know how to do this with the same length in every image. Here is this request on golang:

```
	inferReq := &triton.ModelInferRequest {
		ModelName:    modelName,
		ModelVersion: modelVersion,
		Inputs: []*triton.ModelInferRequest_InferInputTensor {
			{
				Name:     "INPUT",
				Datatype: "UINT8",
				Shape:    []int64{nImages, imgSize},
			},
		},
		Outputs: []*triton.ModelInferRequest_InferRequestedOutputTensor {
			{
				Name: "OUTPUT",
			},
		},
		RawInputContents: [][]byte{imgBatch},
	}
```

So if *imgSize* is the same in every image it works and I can get results for every image. But I want to send images with different sizes

Here is config for model
```
name: "model"
platform: "ensemble"
max_batch_size: 8
input [
  {
    name: "INPUT"
    data_type: TYPE_UINT8
    dims: [-1]
  }
]
output [
  {
    name: "OUTPUT"
    data_type: TYPE_FP32
    dims: [ 1 ]
  }
]

ensemble_scheduling {
  step [
    {
      model_name: "dali_model"
      model_version: -1
      input_map {
        key: "DALI_INPUT_0"
        value: "INPUT"
      }
      output_map {
        key: "DALI_OUTPUT_0"
        value: "preprocessed_image"
      }

    },
    {
      model_name: "trt_model"
      model_version: -1
      input_map {
        key: "input"
        value: "preprocessed_image"
      }
      output_map {
        key: "output"
        value: "OUTPUT"
      }
    }
  ]
}
```
So how can I send images with different sizes in one request?

**Comment by dzier** [comment]
You need to set _imgSize_ as a variable dimension. https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#inputs-and-outputs

You input dimensions may need to be `[-1, -1]`

**Comment by mshmnv** [comment]
it's already [-1,-1]
I will try to explain better.

1. What I can send now?
For example `image = []byte{1,2,3}`
And I can send several of such images with this request:

```
	inferReq := &triton.ModelInferRequest {
		ModelName:    modelName,
		ModelVersion: modelVersion,
		Inputs: []*triton.ModelInferRequest_InferInputTensor {
			{
				Name:     "INPUT",
				Datatype: "UINT8",
				Shape:    []int64{5, 3},
			},
		},
		Outputs: []*triton.ModelInferRequest_InferRequestedOutputTensor {
			{
				Name: "OUTPUT",
			},
		},
		RawInputContents: [][]byte{ {1,2,3,1,2,3,1,2,3,1,2,3,1,2,3} },
	}
```
And I will get 5 answers for all this 5 copies of image. In `Shape` I write number of images(5) and size of every image(3).

2. What I want to send?
`image1 = {1,2,3}`
`image2 = {17,19,19,19,1,6,3,6,8,3}`

These images have different sizes and previous request will not work with it.

How can I send several images with different sizes in one request?

**Comment by mshmnv** [comment]
@dzier  please help. About the comment above

**Comment by tanmayv25** [comment]
What you are asking for is the support for ragged batches on client side. At present, Triton does not supports ragged batches on client side. 
You can use dynamic batching for server-side ragged batch support. https://github.com/triton-inference-server/server/blob/main/docs/ragged_batching.md
Note: it is only supported for limited backends. The client will still send the images of different sizes in different requests but server will batch them together before executing it on model. 

As the ragged batches are not supported on client side, and you really need to send these images batched together from client side, you may encode these image as follows in TYPE_BYTES.
<1st_image_byte_size><1st_image_bytes><2nd_image_byte_size><2image_bytes>.. and so on.
