### ISSUE TITLE
Can Give a Centos version Model_analyzer build.py. Now this build script just for window or ubantu, I have to make my own Dockerfile, But there many bug report.

### ISSUE THREAD

**Issue by GuoGuiRong** [triton-inference-server/server#3566]
I try to make the docker file for Centos, but failed, and the ubantu build.py always report some inRelease bug

**Comment by dzier** [comment]
We do not support Centos at this time. A docker build will fail, since the base container and all the components are based on Ubuntu. You would need to build Triton and perf_analyzer with a local cmake in Centos and then install the model analyzer script.

**Comment by GuoGuiRong** [comment]
> We do not support Centos at this time. A docker build will fail, since the base container and all the components are based on Ubuntu. You would need to build Triton and perf_analyzer with a local cmake in Centos and then install the model analyzer script.

can give me a step detail? this not in doc, I don't know how to do it?
