### ISSUE TITLE
CMake Error In Centos

### ISSUE THREAD

**Issue by GuoGuiRong** [triton-inference-server/server#3570]
my command:
```
python3 ./build.py --cmake-dir=/root/server/build --build-dir=/root/server/build  --no-container-build --enable-logging --enable-stats --enable-tracing --enable-metrics --enable-gpu-metrics --enable-gpu --endpoint=http --endpoint=grpc --repo-tag=common:r21.09  --repo-tag=core:r21.09  --repo-tag=backend:r21.09  --repo-tag=thirdparty:r21.09  --backend=ensemble --backend=tensorrt:r21.09  --backend=identity:r21.09  --backend=repeat:r21.09  --backend=square:r21.09  --backend=onnxruntime:r21.09  --backend=pytorch:r21.09  --backend=tensorflow2:r21.09  --backend=openvino:r21.09  --backend=python:r21.09  --backend=dali:r21.09  --backend=fil:r21.09  --repoagent=checksum:r21.09 

```
I have look the build.md many times, don't know what's my problem!
...
...
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
NVINFER_LIBRARY
    linked by target "tritonserver" in directory /root/server/src/servers
NVINFER_PLUGIN_LIBRARY
    linked by target "tritonserver" in directory /root/server/src/servers
RE2_LIBRARY
    linked by target "main" in directory /root/server/src/servers

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
make[3]: *** [server/src/server-stamp/server-configure] Error 1
make[3]: Leaving directory `/root/server/build/tritonserver/build'
make[2]: *** [CMakeFiles/server.dir/all] Error 2
make[2]: Leaving directory `/root/server/build/tritonserver/build'
make[1]: *** [CMakeFiles/server.dir/rule] Error 2
make[1]: Leaving directory `/root/server/build/tritonserver/build'
make: *** [server] Error 2
error: make server failed

**Comment by GuoGuiRong** [comment]
I use build.py on Centos but failed, And my company's system are all Centos. So the docker build case is not suit to me.

**Comment by GuoGuiRong** [comment]
Can official can give a docker image for centOS, and embbed moddel_analyzer. My GPU is Telsa but my system is CentOs, So the dockfile is always build failed when I want to get image with model analyzer and inference server. I just want to use a software out of the box.

**Comment by CoderHam** [comment]
@GuoGuiRong Triton does not officially support Centos. The errors including NVINFER_LIBRARY, NVINFER_PLUGIN_LIBRARY and RE2_LIBRARY indicate that TensorRT and re2 libraries are not installed / located during the build.

**Comment by iron-js** [comment]
@CoderHam Is there a plan to support centos without docker containers?
