### ISSUE TITLE
 How does the client call HTTP request to send an image file (such as a.jpg) to the server? 

### ISSUE THREAD

**Issue by yangbohust** [triton-inference-server/server#3571]
**Description**

How does the client call HTTP request to send an image (such as a.jpg) to the server?
The backend needs to get the data of the original image file, and the image decoding and model inference are completed in the backend.

I have a model. The input is the original image file (for example, a.jpg), and the output is the inference result (a json string). How do I write the configuration file of the model?

thinks~

**Triton Information**
What version of Triton are you using?
r21.10
Are you using the Triton container or did you build it yourself?
container 
**To Reproduce**
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**

**Comment by CoderHam** [comment]
@yangbohust refer to our examples in the client repo https://github.com/triton-inference-server/client/blob/main/src/python/examples/image_client.py and https://github.com/triton-inference-server/client/blob/main/src/c%2B%2B/examples/image_client.cc that demonstrate how to load and send inference requests starting from an image file.
