### ISSUE TITLE
 Unable to find the implementation of the pure virtual function Run() function of the BackendContext structure

### ISSUE THREAD

**Issue by yangbohust** [triton-inference-server/server#3576]
**Description**

Where is the implementation of the pure virtual function [Run()](https://github.com/triton-inference-server/server/blob/main/src/core/backend_context.h) of the BackendContext structure.
``` cpp
 virtual void Run(
      InferenceBackend* base,
      std::vector<std::unique_ptr<InferenceRequest>>&& requests) = 0;
```
in [backend_context.h](https://github.com/triton-inference-server/server/blob/main/src/core/backend_context.h),Line 88

When I tracked how the request was passed from the http server to the inference server, and then to the backend and scheduler, I found that I couldn’t find the place where the request was actually processed.

**Triton Information**
What version of Triton are you using?
r21.10
Are you using the Triton container or did you build it yourself?
container 
**To Reproduce**
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**

Can you provide a hint to help me sort out how Trion completes the request transmission between the inference server, scheduling, and backend? Including the delivery of the response also requires prompts. 

I really want to know how Triton implements asynchronous inference? Hope you can give me some tips.

Thank you very much~!

**Comment by tanmayv25** [comment]
`backend_context.h` is a remnant from older design and currently marked to be removed. 

The HTTP or GRPC frontend calls to [TRITONSERVER_ServerInferAsync](https://github.com/triton-inference-server/server/blob/main/src/servers/http_server.cc#L2265) implemented in Triton server core. The implementation calls [InferenceServer::InferAsync](https://github.com/triton-inference-server/server/blob/main/src/core/tritonserver.cc#L2472). This   calls [InferenceRequest::Run](https://github.com/triton-inference-server/server/blob/main/src/core/server.cc#L470) in return.  The `InferenceRequest::Run` enqueues the request on `InferenceBackend` by calling[ InferenceBackend::Enqueue.](https://github.com/triton-inference-server/server/blob/main/src/core/infer_request.cc#L116). This in turn calls [Scheduler::Enqueue](https://github.com/triton-inference-server/server/blob/main/src/core/backend.h#L134). The scheduler (for sake of the example we assume no batching) forms a [Payload object with the requests and enqueues the payload to rate limiter](https://github.com/triton-inference-server/server/blob/main/src/core/dynamic_batch_scheduler.cc#L187-L191). The thread at this point returns. The [TritonModelBackendThread takes the payload from the RateLimiter queue and calls Payload::Execute](https://github.com/triton-inference-server/server/blob/main/src/backends/backend/triton_model_instance.cc#L662-L692).. 
The Payload::Execute calls [TritonModelInstance::Schedule](https://github.com/triton-inference-server/server/blob/main/src/core/payload.cc#L170). This calls[ TritonModelInstance::Schedule](https://github.com/triton-inference-server/server/blob/main/src/backends/backend/triton_model_instance.cc#L501).

The TritonModelInstance::Execute function calls [inst_exec_fn](https://github.com/triton-inference-server/server/blob/main/src/backends/backend/triton_model_instance.cc#L574) which is an entrypoint to `.so` via TRITONBACKEND_ModelInstanceExecute.

**Comment by yangbohust** [comment]
Great, thank you very much！
