### ISSUE TITLE
Triton Server return sequence flags errors in each 6 batch processing

### ISSUE THREAD

**Issue by konstantin-sancom** [triton-inference-server/server#3577]
**Description**
We use a test "batch" of 850 elements ~300 seconds long each. Every 6 run in average server return GRCP error:
`ORR_ID: [100]   PARTIAL_TEXT: []`
`error_message: "inference request for sequence 543 to model \'kaldi_online\' must specify the START flag on the first request of the sequence"`
`infer_response {`
`}`

`error: inference request failed: inference request for sequence 543 to model 'kaldi_online' must specify the START flag on the first request of the sequence`

In server log we also see:
`I1116 12:34:34.412698 198621 grpc_server.cc:3504] Process for ModelStreamInferHandler, rpc_ok=1, context 111114, 146090 step WRITEREADY`

We run `Triton Server r.21.05` under `Ubuntu 20.04` in `openVZ` container with `128Gb RAM` + `Tesla T4 GPU`. `Triton Server`, `Kaldi` and all needed dependencied were extracted from original Docker container. Also we belt original `Kaldi backend` and `C++ client` in `Docker` container and extracted them also.

**Triton Information**
https://github.com/triton-inference-server/server/tree/r21.05
https://github.com/NVIDIA/DeepLearningExamples/tree/master/Kaldi/SpeechRecognition `r21.08`

Are you using the Triton container or did you build it yourself?
Triton from orignal Docker Container

**To Reproduce**
Run batch of 850 5min items iterately.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
Kaldi Model

**Expected behavior**
Normal batch proceeding.

**Comment by tanmayv25** [comment]
Looks like the sequence 543 is idling out. Triton would evict a sequence if it does not see any further requests within the specified time. After the sequence is evicted, the request that comes with that sequence id is expected to have START flag.

In your case it looks like the max idle time is 5sec. 
https://github.com/NVIDIA/DeepLearningExamples/blob/master/Kaldi/SpeechRecognition/model-repo/kaldi_online/config.pbtxt#L100

Can you try setting it to a larger value and then retrying?

**Comment by konstantin-sancom** [comment]
> 
> 
> Looks like the sequence 543 is idling out. Triton would evict a sequence if it does not see any further requests within the specified time. After the sequence is evicted, the request that comes with that sequence id is expected to have START flag.
> 
> In your case it looks like the max idle time is 5sec. https://github.com/NVIDIA/DeepLearningExamples/blob/master/Kaldi/SpeechRecognition/model-repo/kaldi_online/config.pbtxt#L100
> 
> Can you try setting it to a larger value and then retrying?

Thank you for help. We increased `max_sequence_idle_microseconds` from `5000000` to `10000000` and situation goes better.
But there is a question: what actually this parameter means? Is it a time-out between two sequentul chunks or is it overall timeout from START to END (time, allocated for client to send entire SEQUENCE from START to END chunk)?

**Comment by konstantin-sancom** [comment]
And could somebody tell something about this message in server log:
`I1118 09:07:58.363941 215906 grpc_server.cc:3504] Process for ModelStreamInferHandler, rpc_ok=1, context 147682, 199171 step WRITEREADY`

It's appear when batch proceeding is "freezed" for some reason.

**Comment by tanmayv25** [comment]
You can learn about the `max_sequence_idle_microseconds` from here: https://github.com/triton-inference-server/common/blob/main/protobuf/model_config.proto#L1392-L1402.

To learn more about sequence batching in general you can learn it from here: https://github.com/triton-inference-server/server/blob/main/docs/architecture.md#stateful-models

> I1118 09:07:58.363941 215906 grpc_server.cc:3504] Process for ModelStreamInferHandler, rpc_ok=1, context 147682, 199171 step WRITEREADY

The message means that server is ready for writing the response to the grpc stream such that client can receive it. The message comes from grpc server implementation that uses grpc async API to communicate with bidirectional streaming. To delve into deeper levels, it means that when the state object is encountered again via grpc completion queue, the response will be written to the stream. See here for implementation of `Process` function: https://github.com/triton-inference-server/server/blob/main/src/servers/grpc_server.cc#L3508.
