### ISSUE TITLE
Stateful model example for the python backend

### ISSUE THREAD

**Issue by oeway** [triton-inference-server/server#3580]
**Is your feature request related to a problem? Please describe.**
I am trying to make a stateful model in Python backend, but I couldn't find any example to do that.

**Describe the solution you'd like**
It would be great if someone can provide an example with a simple python backend, and ideally with the client code to start with.

More specifically, I wonder how we can access the `sequence_id, sequence_start, sequence_end` and other control signal information from the request object.

**Comment by zzk0** [comment]
As a triton user, I think stateful model is not a good name and it causes some confusion. **stateful backend** is better. You have to develop your own backend if you want to make use of sequence batching. Maybe the developers should consider to add sequence batching support in python backend. In the C++ backend you can access `sequence_id, sequence_start, sequence_end` by the API listed below.

```
  TRITONBACKEND_RequestCorrelationId
  TRITONBACKEND_RequestCorrelationIdString
  TRITONBACKEND_RequestId
  TRITONBACKEND_RequestInput  // control_input name set in the config.pbtxt
```

**Comment by oeway** [comment]
> As a triton user, I think stateful model is not a good name and it causes some confusion. stateful backend is better. 

Not sure if I understand what you suggest, but you also mentioned the C++ backend also support sequence batching. Isn't that suggesting the opposite? 

Are you about the python backend does not support stateful models? I would assuming all the backend supports stateless and stateful models.

> In the C++ backend you can access sequence_id, sequence_start, sequence_end by the API listed below.

Do you have an example on how we can use the python client to interact with the stateful model with C++ backend?

**Comment by zzk0** [comment]
> Are you sure about the python backend does not support stateful models?

Not very sure. You can find all the methods you can use in python backend in the following files. The files don't contain any methods to get sequence id.

https://github.com/triton-inference-server/python_backend/blob/main/src/resources/triton_python_backend_utils.py

https://github.com/triton-inference-server/python_backend/blob/main/src/pb_stub.cc#L642

> I can actually get the control signal with something like `start = pb_utils.get_input_tensor_by_name(request, "START")` in a python backend.

yes. It is similar to the C++ API `TRITONBACKEND_RequestInput`. But you still cannot get sequence id.

> Do you have an example on how we can use the python client to interact with the stateful model with C++ backend?

To interact with stateful model, what you need to do is set `sequence_id`, `sequence_start`, `sequence_end` in the [parameters](https://github.com/triton-inference-server/client/blob/main/src/python/library/tritonclient/grpc/__init__.py#L1030).

Here is an example: https://github.com/triton-inference-server/client/blob/main/src/python/examples/simple_http_sequence_sync_infer_client.py#L62


> > As a triton user, I think stateful model is not a good name and it causes some confusion. stateful backend is better.
>
> Not sure if I understand what you suggest

Hope my word didn't confuse you. 😄  I think you understand the stateful model.

**Comment by zzk0** [comment]
I was wrong. sorry 😢 

I found it! You can get `sequence_id` and `correlation_id`

https://github.com/triton-inference-server/python_backend/blob/main/src/pb_stub.cc#L661

**Comment by oeway** [comment]
Hi, I confirm that the python backend supports sequences. Would still be nice to add some documentation for accessing sequence related information.

In the config.pbtxt I added:
```protobuf
sequence_batching {
  max_sequence_idle_microseconds: 30000000
  direct {}
  control_input [
    {
      name: "START"
      control [
        {
          kind: CONTROL_SEQUENCE_START
          fp32_false_true: [ 0, 1 ]
        }
      ]
    },
    {
      name: "END"
      control [
        {
          kind: CONTROL_SEQUENCE_END
          fp32_false_true: [ 0, 1 ]
        }
      ]
    }
  ]
}
```

And in the python model, I can access them by:
```python
sequence_id = request.correlation_id()
start_flag = pb_utils.get_input_tensor_by_name(request, "START").as_numpy()[0]
end_flag = pb_utils.get_input_tensor_by_name(request, "END").as_numpy()[0]
```

Will close this issue for now.
