### ISSUE TITLE
Is there any way to check if the client is disconnected? Or a way to force close the model?

### ISSUE THREAD

**Issue by phamtrongthang123** [triton-inference-server/server#3581]
Hi everyone, I want to ask if there is any way to force close or unload or kill the model process when it's inferencing. In a situation where the model inference time takes lots of time and the client disconnect, this may cause the server to hang for other users. I thought Triton has it but after a while, I look through the documents but did not find any instruction on how to do that. Hope that someone could suggest me a way to solve this problem. 
Thank you very much!

**Comment by GuanLuo** [comment]
Once the request is passed to the backend, Triton doesn't have a way to stop the execution as completing the requests received by the server is the first priority. But it shouldn't cause the server to hang as concurrent model executions is one feature of Triton, can you elaborate on "his may cause the server to hang for other users"

**Comment by phamtrongthang123** [comment]
Hi @GuanLuo. Thanks for the reply. 
> Once the request is passed to the backend, Triton doesn't have a way to stop the execution as completing the requests received by the server is the first priority

I see. So backend should be the one in total control and Triton's features should be used as a way to reduce the backend's burden. 

> But it shouldn't cause the server to hang as concurrent model executions is one feature of Triton, can you elaborate on "his may cause the server to hang for other users"

Sorry the word "hang" was not a good word choice, what I mean was wasting time and computation. I was thinking of using only 1 instance per machine so concurrent execution was not used in this case. This way every pending requests will be put into waiting queue. Sometimes the client just disconnect suddenly but Triton will keep inferencing until it's done. That's why I thought it would be great if we can stop the execution halfway to avoid wasting computation. So far I have been using backend to manage waiting queue and handle requests list instead of delegating all request to Triton, but doing this manually is just a waste of all the great features from Triton.

**Comment by GuanLuo** [comment]
Correct, Triton will not instruct the model to stop its execution. For your use case, you may want to use `instance_group` in model config to create multiple instances of the same model so the request only occupies one instance when disconnection happens. Having a disconnected client while the request is being executed seems to be a rare case so it may be acceptable to spend extra compute on those requests

**Comment by tricky61** [comment]
> Correct, Triton will not instruct the model to stop its execution. For your use case, you may want to use `instance_group` in model config to create multiple instances of the same model so the request only occupies one instance when disconnection happens. Having a disconnected client while the request is being executed seems to be a rare case so it may be acceptable to spend extra compute on those requests

when the client disconnected while the request is being executed, after the request finished, will the request output free on the server side? will the server hang?
