### ISSUE TITLE
Generate config.pbtxt 

### ISSUE THREAD

**Issue by mgiessing** [triton-inference-server/server#3584]
Hello I got a tf keras model which is converted to onnx and was wondering if it is possible to generate the `config.pbtxt` before running the triton server (maybe with onnx or tf2onnx?) and then manually add parameters such as `label_filename` and `format`.

I understand that I can see many information once the model is deployed with `--strict-model-config=false` and then use the `tritonclient.get_model_config()` method, but ideally I got the relevant information before doing that.

I consulted the [model configuration](https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md) doc and [model proto](https://github.com/triton-inference-server/common/blob/main/protobuf/model_config.proto) file, but didn't find any better information.

Not sure if that is a question which I better ask at onnx/tf2onnx, but maybe you got some hints as well :-)

Thanks in advance!

**Comment by GuanLuo** [comment]
There is no utility to generate `config.pbtxt` without running Triton, you will need to examine the model yourself and create the `config.pbtxt` file manually. You may consult onnx/tf2onnx for whether they have tools for examining the model properties.

**Comment by mgiessing** [comment]
Thanks!
