### ISSUE TITLE
no model loaded by triton

### ISSUE THREAD

**Issue by ggslayer** [triton-inference-server/server#3595]
**Description**
Hi, I'm newer for triton, I run the triton docker image by document: "bulid with docker", and it started succeed.
compile command:
./build.py --cmake-dir=./build --build-dir=/tmp/citritonbuild --enable-logging --enable-stats --enable-tracing --enable-metrics --enable-gpu-metrics --enable-gpu  --endpoint=http --endpoint=grpc --repo-tag=common:r21.10 --repo-tag=core:r21.10 --repo-tag=backend:r21.10 --repo-tag=thirdparty:r21.10 --backend=tensorrt:r21.10 --backend=onnxruntime:r21.10

And run the result docker image with:
docker run --gpus=all --rm -p8000:8000 -p8001:8001 -p8002:8002 -v /data/models/:/models  tritonserver  tritonserver --model-repository=/models

But in the output of terminal, there is no model loaded, I think, maybe my oxxn model have some problem, So I copy the docs/examples/densenet_onnx folder to /data/models, But also have no model loaded.

I want to know:
1. is my build parameter or docker run parameter have some problems?
2. where can i see the error log, include the model load process log...

**Triton Information**
version: r21.10

Are you using the Triton container or did you build it yourself?
I built it follow "build with docker"

**Comment by GuanLuo** [comment]
Have you download the actual model following the [fetch model script](https://github.com/triton-inference-server/server/blob/main/docs/examples/fetch_models.sh)?

Can you share what the layout of `/data/models`?

**Comment by ggslayer** [comment]
in model folder, tree it:
`-- densenet_onnx
    |-- 1
    |   `-- model.onnx
    |-- config.pbtxt
    `-- densenet_labels.txt

this is same like docs/examples/model foloder,  is there any log about model load?

**Comment by ggslayer** [comment]
I Got it!, given a wrong dir in docker in docker situation ... thank you
