### ISSUE TITLE
Ensemble models with multiple inputs or outputs

### ISSUE THREAD

**Issue by grapefruitL** [triton-inference-server/server#3602]
**Is your feature request related to a problem? Please describe.**
I was ensembling two models,the first one has two inputs, the other has two outputs, how shoud I write the config.pbtxt of the ensemble model?

**Describe the solution you'd like**
now my config.pbtxt is like this:
```
name: "ensemble"
platform: "ensemble"
max_batch_size: 8
input [
  {
    name: "INPUT_0"
    data_type: TYPE_UINT8
    dims: [ -1 ]
  },
  {
    name: "INPUT_SIZE_0"
    data_type: TYPE_FP32
    dims: [ -1 ]
  }
]
output [
  {
    name: "OUTPUT_0"
    data_type: TYPE_FP32
    dims: [ -1 ]
  },
  {
    name: "OUTPUT_1"
    data_type: TYPE_FP32
    dims: [ -1 ]
  }
]
ensemble_scheduling {
  step [
    {
      model_name: "dali_cls"
      model_version: 1
      input_map {
        key: "DALI_INPUT_0"
        value: "INPUT_0"
        key: "DALI_INPUT_SIZE_0"
        value: "INPUT_SIZE_0"
      }
      output_map{
        key: "DALI_OUTPUT_0"
        value: "preprocessed_image"
      }
    },
    {
      model_name: "cls"
      model_version: -1
      input_map {
        key: "INPUT__0"
        value: "preprocessed_image"
      }
      output_map {
        key: "OUTPUT_0"
        value: "OUTPUT"
        key: "OUTPUT_1"
        value: "OUTPUT"
      }
    }
  ]
}
```

**Describe alternatives you've considered**
Can this be achieved? I think this demand is very common

**Comment by zzk0** [comment]
In the model\_config.proto, you can find the `input_map`, `output_map` is a map type. model\_config.proto is a protobuf file, maybe you should learn a little bit about [protocol buffer](https://developers.google.com/protocol-buffers/docs/cpptutorial).

https://github.com/triton-inference-server/common/blob/main/protobuf/model_config.proto#L1462

you can write your input map like this:

```
input_map {
    key: "DALI_INPUT_0"
    value: "INPUT_0"
}
input_map {
  key: "DALI_INPUT_SIZE_0"
  value: "INPUT_SIZE_0"
}
```

**Comment by GuanLuo** [comment]
@zzk0 Thanks for the reply. @grapefruitL as zzk0 mentioned, you can specify the connectivity of the tensors via the map key-value mapping, here is an [multi-I/O ensemble example](https://github.com/triton-inference-server/server/blob/v2.16.0/qa/ensemble_models/mix_ensemble_int32_float32_float32/config.pbtxt) that we use for testing
