### ISSUE TITLE
Pip install tritonclient[all] not working in ubuntu 20.04

### ISSUE THREAD

**Issue by danielbasso** [triton-inference-server/server#3603]
**Description**

Related to #3544. O opened here because the other issue is here as well.

`pip install tritonclient` works:

```shell
❯ pip install tritonclient
Requirement already satisfied: tritonclient in ./venv/lib/python3.8/site-packages (2.16.0)
Requirement already satisfied: numpy>=1.19.1 in ./venv/lib/python3.8/site-packages (from tritonclient) (1.21.4)
Requirement already satisfied: python-rapidjson>=0.9.1 in ./venv/lib/python3.8/site-packages (from tritonclient) (1.5)
```
When I try to load the package:

```python
In [2]: import tritonclient.http as triton_http
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
~/Workspaces/triton-workspace/python-request/venv/lib/python3.8/site-packages/tritonclient/http/__init__.py in <module>
     27 try:
---> 28     from geventhttpclient import HTTPClient
     29     from geventhttpclient.url import URL

ModuleNotFoundError: No module named 'geventhttpclient'

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
<ipython-input-2-7394082b7260> in <module>
----> 1 import tritonclient.http as triton_http

~/Workspaces/triton-workspace/python-request/venv/lib/python3.8/site-packages/tritonclient/http/__init__.py in <module>
     36     import gzip, zlib
     37 except ModuleNotFoundError as error:
---> 38     raise RuntimeError(
     39         'The installation does not include http support. Specify \'http\' or \'all\' while installing the tritonclient package to include the support'
     40     ) from error

RuntimeError: The installation does not include http support. Specify 'http' or 'all' while installing the tritonclient package to include the support

```

So I tried `pip install tritonclient[all]` and the result is:

```shell
❯ pip install tritonclient[all]
zsh: no matches found: tritonclient[all]
```

**System information**
Kubuntu 20.04
Python 3.8.10

**Comment by CoderHam** [comment]
@danielbasso can you try `pip3 install tritonclient[all]`

**Comment by danielbasso** [comment]
Hi @CoderHam!

This is happening inside an python3 venv, so pip is already 3. But just to make sure and double check, I've tried it:

![image](https://user-images.githubusercontent.com/20959177/143129978-2ffceeac-9054-4857-97a6-2276bf475d3e.png)

**Comment by danielbasso** [comment]
Huh, found the culprit. Of course it had to do with the "[" symbol:

```shell
pip install tritonclient\[all\]                                                                                                                                                      ─╯
Requirement already satisfied: tritonclient[all] in ./venv/lib/python3.8/site-packages (2.16.0)
Requirement already satisfied: numpy>=1.19.1 in ./venv/lib/python3.8/site-packages (from tritonclient[all]) (1.21.4)
Requirement already satisfied: python-rapidjson>=0.9.1 in ./venv/lib/python3.8/site-packages (from tritonclient[all]) (1.5)
Collecting geventhttpclient>=1.4.4; extra == "all"
  Using cached geventhttpclient-1.5.3-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (77 kB)
Collecting grpcio>=1.31.0; extra == "all"
  Using cached grpcio-1.42.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.0 MB)
Collecting protobuf>=3.5.0; extra == "all"
  Using cached protobuf-3.19.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
Collecting six
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting gevent>=0.13
  Using cached gevent-21.8.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (6.5 MB)
Collecting brotli
  Using cached Brotli-1.0.9-cp38-cp38-manylinux1_x86_64.whl (357 kB)
Collecting certifi
  Downloading certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
     |████████████████████████████████| 149 kB 4.9 MB/s 
Collecting greenlet<2.0,>=1.1.0; platform_python_implementation == "CPython"
  Using cached greenlet-1.1.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (156 kB)
Collecting zope.event
  Using cached zope.event-4.5.0-py2.py3-none-any.whl (6.8 kB)
Collecting zope.interface
  Using cached zope.interface-5.4.0-cp38-cp38-manylinux2010_x86_64.whl (259 kB)
Requirement already satisfied: setuptools in ./venv/lib/python3.8/site-packages (from gevent>=0.13->geventhttpclient>=1.4.4; extra == "all"->tritonclient[all]) (44.0.0)
Installing collected packages: six, greenlet, zope.event, zope.interface, gevent, brotli, certifi, geventhttpclient, grpcio, protobuf
Successfully installed brotli-1.0.9 certifi-2021.10.8 gevent-21.8.0 geventhttpclient-1.5.3 greenlet-1.1.2 grpcio-1.42.0 protobuf-3.19.1 six-1.16.0 zope.event-4.5.0 zope.interface-5.4.0
```
Then:

```python
❯ python
Python 3.8.10 (default, Sep 28 2021, 16:10:42) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tritonclient.http as triton_http
>>> 
```

Suggestions:

1) Write about it in the docs ("you could try `tritonclient\[all\]`  `if tritonclient[all]` doesn't work ");
2) Wouldn't be easier if the vanilla `tritonclient` was the 'all' version?

**Comment by CoderHam** [comment]
> Write about it in the docs ("you could try tritonclient\[all\] if tritonclient[all] doesn't work ");

@danielbasso which version of pip are you using? I have not seen this error before.

> Wouldn't be easier if the vanilla tritonclient was the 'all' version?

@tanmayv25 what do you think about this?

**Comment by danielbasso** [comment]
@CoderHam  pip version is 20.0.2. But I think the "problem" was related to the Zhs terminal I'm using.

Can I make a pull request to update the `README.md` file?

**Comment by CoderHam** [comment]
@danielbasso looks like the right solution is to turn off globbing for pip
https://stackoverflow.com/questions/30539798/zsh-no-matches-found-requestssecurity/30539963#30539963
Since this is a feature of zsh that is breaking the syntax I would rather we do not confuse the user by adding details about a WAR needed in a custom shell.

**Comment by danielbasso** [comment]
I don't think that adding that you might need to escape brackets would be that confusing and could be a "day saver" for some with the problem. But I understand your point.

**Comment by tanmayv25** [comment]
> @tanmayv25 what do you think about this?

I believe pip optional dependencies don't work that way. We can not install all optional dependencies by default and rely on all. I would be interested in a way it is possible and doesn't involve complicated logic. As far as I read back then most packages followed same convention with [<modules>].

**Comment by Hezhexi2002** [comment]
> Huh, found the culprit. Of course it had to do with the "[" symbol:
> 
> ```shell
> pip install tritonclient\[all\]                                                                                                                                                      ─╯
> Requirement already satisfied: tritonclient[all] in ./venv/lib/python3.8/site-packages (2.16.0)
> Requirement already satisfied: numpy>=1.19.1 in ./venv/lib/python3.8/site-packages (from tritonclient[all]) (1.21.4)
> Requirement already satisfied: python-rapidjson>=0.9.1 in ./venv/lib/python3.8/site-packages (from tritonclient[all]) (1.5)
> Collecting geventhttpclient>=1.4.4; extra == "all"
>   Using cached geventhttpclient-1.5.3-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (77 kB)
> Collecting grpcio>=1.31.0; extra == "all"
>   Using cached grpcio-1.42.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.0 MB)
> Collecting protobuf>=3.5.0; extra == "all"
>   Using cached protobuf-3.19.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
> Collecting six
>   Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
> Collecting gevent>=0.13
>   Using cached gevent-21.8.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (6.5 MB)
> Collecting brotli
>   Using cached Brotli-1.0.9-cp38-cp38-manylinux1_x86_64.whl (357 kB)
> Collecting certifi
>   Downloading certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
>      |████████████████████████████████| 149 kB 4.9 MB/s 
> Collecting greenlet<2.0,>=1.1.0; platform_python_implementation == "CPython"
>   Using cached greenlet-1.1.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (156 kB)
> Collecting zope.event
>   Using cached zope.event-4.5.0-py2.py3-none-any.whl (6.8 kB)
> Collecting zope.interface
>   Using cached zope.interface-5.4.0-cp38-cp38-manylinux2010_x86_64.whl (259 kB)
> Requirement already satisfied: setuptools in ./venv/lib/python3.8/site-packages (from gevent>=0.13->geventhttpclient>=1.4.4; extra == "all"->tritonclient[all]) (44.0.0)
> Installing collected packages: six, greenlet, zope.event, zope.interface, gevent, brotli, certifi, geventhttpclient, grpcio, protobuf
> Successfully installed brotli-1.0.9 certifi-2021.10.8 gevent-21.8.0 geventhttpclient-1.5.3 greenlet-1.1.2 grpcio-1.42.0 protobuf-3.19.1 six-1.16.0 zope.event-4.5.0 zope.interface-5.4.0
> ```
> 
> Then:
> 
> ```python
> ❯ python
> Python 3.8.10 (default, Sep 28 2021, 16:10:42) 
> [GCC 9.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import tritonclient.http as triton_http
> >>> 
> ```
> 
> Suggestions:
> 
> 1. Write about it in the docs ("you could try `tritonclient\[all\]`  if `tritonclient[all]` doesn't work ");
> 2. Wouldn't be easier if the vanilla `tritonclient` was the 'all' version?

Thanks for your solution,it works on my wsl2 ubuntu20.04 distro with zsh too!
