### ISSUE TITLE
undefined symbol: TRITONBACKEND_StateBuffer

### ISSUE THREAD

**Issue by zhenxingsh** [triton-inference-server/server#3607]
**Description**
first, I pull triton-server docker r21.10, and the run command as:
`docker run --gpus all -itd --name triton_server_21.10 -p8000:8000 -p8001:8001 -p8002:8002 --shm-size=1g --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 -v$(pwd)/triton_deploy/models:/models -v$(pwd)/triton_deploy/plugins:/plugins -v {pwd}/triton_project:/triton_project nvcr.io/nvidia/tritonserver:21.10-py3
`
second, I pull tensorrt_backend source and compile it from source,the command as:
`
cd tensorrt_backend
git reset --hard 61925b324bead1178147f4a9335d935b3b47b717   [切换到分支origin/r21.10]
mkdir build && cd build
cmake -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/install ..
make install
`

last , replace the origin /opt/tritonserver/backend/tensorrt/libtriton_tensorrt.so using the generated libtriton_tensorrt.so, and run tritonserver:
`
tritonserver --model-repository=/models --log-verbose 1 --strict-model-config=false
`
the result as bellow, any one can help me to check this error?
| Model  | Version | Status                                                            |
+--------+---------+-------------------------------------------------------------------+
| resnet | 1       | UNAVAILABLE: Not found: unable to load backend library: /opt/trit |
|        |         | onserver/backends/tensorrt/libtriton_tensorrt.so: undefined symbo |
|        |         | l: TRITONBACKEND_StateBuffer   

  Thanks.

**Triton Information**
What version of Triton are you using?
r21.10
Are you using the Triton container or did you build it yourself?
tensorrt_backend build by myself
**To Reproduce**
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
platform: "tensorrt_plan"
input {
  name: "input"
  data_type: TYPE_FP32
  dims: -1
  dims: 3
  dims: -1
  dims: -1
}
output {
  name: "probs"
  data_type: TYPE_FP32
  dims: -1
  dims: 1000
}
backend: "tensorrt"

#################################
this is the full log:
>/opt/tritonserver# tritonserver --model-repository=/models --log-verbose 1 --strict-model-config=false
I1124 02:44:34.884955 740585 metrics.cc:298] Collecting metrics for GPU 0: NVIDIA GeForce RTX 2080 Ti
I1124 02:44:34.885202 740585 shared_library.cc:108] OpenLibraryHandle: /opt/tritonserver/backends/pytorch/libtriton_pytorch.so
I1124 02:44:35.050344 740585 libtorch.cc:1092] TRITONBACKEND_Initialize: pytorch
I1124 02:44:35.050364 740585 libtorch.cc:1102] Triton TRITONBACKEND API version: 1.6
I1124 02:44:35.050369 740585 libtorch.cc:1108] 'pytorch' TRITONBACKEND API version: 1.6
I1124 02:44:35.050394 740585 shared_library.cc:108] OpenLibraryHandle: /opt/tritonserver/backends/tensorflow1/libtriton_tensorflow1.so
2021-11-24 02:44:35.235300: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
I1124 02:44:35.261311 740585 tensorflow.cc:2170] TRITONBACKEND_Initialize: tensorflow
I1124 02:44:35.261333 740585 tensorflow.cc:2180] Triton TRITONBACKEND API version: 1.6
I1124 02:44:35.261336 740585 tensorflow.cc:2186] 'tensorflow' TRITONBACKEND API version: 1.6
I1124 02:44:35.261338 740585 tensorflow.cc:2210] backend configuration:
{}
I1124 02:44:35.261357 740585 shared_library.cc:108] OpenLibraryHandle: /opt/tritonserver/backends/onnxruntime/libtriton_onnxruntime.so
I1124 02:44:35.280408 740585 onnxruntime.cc:1999] TRITONBACKEND_Initialize: onnxruntime
I1124 02:44:35.280425 740585 onnxruntime.cc:2009] Triton TRITONBACKEND API version: 1.6
I1124 02:44:35.280429 740585 onnxruntime.cc:2015] 'onnxruntime' TRITONBACKEND API version: 1.6
I1124 02:44:35.287542 740585 shared_library.cc:108] OpenLibraryHandle: /opt/tritonserver/backends/openvino/libtriton_openvino.so
I1124 02:44:35.293397 740585 openvino.cc:1193] TRITONBACKEND_Initialize: openvino
I1124 02:44:35.293407 740585 openvino.cc:1203] Triton TRITONBACKEND API version: 1.6
I1124 02:44:35.293409 740585 openvino.cc:1209] 'openvino' TRITONBACKEND API version: 1.6
I1124 02:44:35.425410 740585 pinned_memory_manager.cc:240] Pinned memory pool is created at '0x7f54ca000000' with size 268435456
I1124 02:44:35.425660 740585 cuda_memory_manager.cc:105] CUDA memory pool is created on device 0 with size 67108864
I1124 02:44:35.426010 740585 backend_factory.h:45] Create TritonBackendFactory
I1124 02:44:35.426021 740585 ensemble_backend_factory.cc:47] Create EnsembleBackendFactory
I1124 02:44:35.426659 740585 autofill.cc:209] TensorRT autofill: OK: 
I1124 02:44:35.426667 740585 model_config_utils.cc:666] autofilled config: name: "resnet"
platform: "tensorrt_plan"
input {
  name: "input"
  data_type: TYPE_FP32
  dims: -1
  dims: 3
  dims: -1
  dims: -1
}
output {
  name: "probs"
  data_type: TYPE_FP32
  dims: -1
  dims: 1000
}
backend: "tensorrt"

I1124 02:44:35.426884 740585 model_repository_manager.cc:726] AsyncLoad() 'resnet'
I1124 02:44:35.426908 740585 model_repository_manager.cc:965] TriggerNextAction() 'resnet' version 1: 1
I1124 02:44:35.426913 740585 model_repository_manager.cc:1003] Load() 'resnet' version 1
I1124 02:44:35.426915 740585 model_repository_manager.cc:1022] loading: resnet:1
I1124 02:44:35.527347 740585 model_repository_manager.cc:1082] CreateInferenceBackend() 'resnet' version 1
I1124 02:44:35.527544 740585 shared_library.cc:108] OpenLibraryHandle: /opt/tritonserver/backends/tensorrt/libtriton_tensorrt.so
I1124 02:44:35.538658 740585 triton_backend_manager.cc:101] unloading backend 'tensorrt'
E1124 02:44:35.538706 740585 model_repository_manager.cc:1186] failed to load 'resnet' version 1: Not found: unable to load backend library: /opt/tritonserver/backends/tensorrt/libtriton_tensorrt.so: undefined symbol: TRITONBACKEND_StateBuffer
I1124 02:44:35.538725 740585 model_repository_manager.cc:965] TriggerNextAction() 'resnet' version 1: 0
I1124 02:44:35.538740 740585 model_repository_manager.cc:980] no next action, trigger OnComplete()
I1124 02:44:35.538831 740585 model_repository_manager.cc:571] VersionStates() 'resnet'
I1124 02:44:35.538916 740585 model_repository_manager.cc:571] VersionStates() 'resnet'
I1124 02:44:35.539008 740585 server.cc:522] 
+------------------+------+
| Repository Agent | Path |
+------------------+------+
+------------------+------+

I1124 02:44:35.539201 740585 server.cc:549] 
+-------------+-----------------------------------------------------------------+--------+
| Backend     | Path                                                            | Config |
+-------------+-----------------------------------------------------------------+--------+
| pytorch     | /opt/tritonserver/backends/pytorch/libtriton_pytorch.so         | {}     |
| tensorflow  | /opt/tritonserver/backends/tensorflow1/libtriton_tensorflow1.so | {}     |
| onnxruntime | /opt/tritonserver/backends/onnxruntime/libtriton_onnxruntime.so | {}     |
| openvino    | /opt/tritonserver/backends/openvino/libtriton_openvino.so       | {}     |
+-------------+-----------------------------------------------------------------+--------+

I1124 02:44:35.539268 740585 model_repository_manager.cc:547] BackendStates()
I1124 02:44:35.539423 740585 server.cc:592] 
+--------+---------+----------------------------------------------------------------------------------------+
| Model  | Version | Status                                                                                 |
+--------+---------+----------------------------------------------------------------------------------------+
| resnet | 1       | UNAVAILABLE: Not found: unable to load backend library: /opt/tritonserver/backends/ten |
|        |         | sorrt/libtriton_tensorrt.so: undefined symbol: TRITONBACKEND_StateBuffer               |
+--------+---------+----------------------------------------------------------------------------------------+

I1124 02:44:35.539784 740585 tritonserver.cc:1920] 
+----------------------------------+--------------------------------------------------------------------------+
| Option                           | Value                                                                    |
+----------------------------------+--------------------------------------------------------------------------+
| server_id                        | triton                                                                   |
| server_version                   | 2.15.0                                                                   |
| server_extensions                | classification sequence model_repository model_repository(unload_depende |
|                                  | nts) schedule_policy model_configuration system_shared_memory cuda_share |
|                                  | d_memory binary_tensor_data statistics                                   |
| model_repository_path[0]         | /models                                                                  |
| model_control_mode               | MODE_NONE                                                                |
| strict_model_config              | 0                                                                        |
| rate_limit                       | OFF                                                                      |
| pinned_memory_pool_byte_size     | 268435456                                                                |
| cuda_memory_pool_byte_size{0}    | 67108864                                                                 |
| response_cache_byte_size         | 0                                                                        |
| min_supported_compute_capability | 6.0                                                                      |
| strict_readiness                 | 1                                                                        |
| exit_timeout                     | 30                                                                       |
+----------------------------------+--------------------------------------------------------------------------+

I1124 02:44:35.539844 740585 server.cc:252] Waiting for in-flight requests to complete.
I1124 02:44:35.539856 740585 model_repository_manager.cc:671] AsyncUnload() 'resnet'
I1124 02:44:35.539867 740585 model_repository_manager.cc:965] TriggerNextAction() 'resnet' version 1: 2
I1124 02:44:35.539886 740585 model_repository_manager.cc:1048] Unload() 'resnet' version 1
I1124 02:44:35.539915 740585 model_repository_manager.cc:511] LiveBackendStates()
I1124 02:44:35.539940 740585 server.cc:267] Timeout 30: Found 0 live models and 0 in-flight non-inference requests
I1124 02:44:35.539965 740585 triton_backend_manager.cc:101] unloading backend 'pytorch'
I1124 02:44:35.539986 740585 triton_backend_manager.cc:101] unloading backend 'tensorflow'
I1124 02:44:35.540010 740585 triton_backend_manager.cc:101] unloading backend 'onnxruntime'
I1124 02:44:35.540039 740585 triton_backend_manager.cc:101] unloading backend 'openvino'
error: creating server: Internal - failed to load all models

**Comment by Tabrizian** [comment]
You are compiling the latest version of tensorrt backend instead of r21.10 branch. Also, make sure to use the correct branch tag for `common`, `core`, and `backend` repo tags. You can look at the [Building From Source](https://github.com/triton-inference-server/python_backend#building-from-source) section of Python backend and use the same instructions (with minor modifications) to compile tensorrt backend.

**Comment by zhenxingsh** [comment]
> You are compiling the latest version of tensorrt backend instead of r21.10 branch. Also, make sure to use the correct branch tag for `common`, `core`, and `backend` repo tags. You can look at the [Building From Source](https://github.com/triton-inference-server/python_backend#building-from-source) section of Python backend and use the same instructions (with minor modifications) to compile tensorrt backend.



thanks，have solved it using specify common core backend repo tags
