### ISSUE TITLE
The model deployed with TensorRT could not be load

### ISSUE THREAD

**Issue by lincong8722** [triton-inference-server/server#3609]
When I used tensorrt to deploy my Triton, the following error occurred when loading the model. I converted the tensorrt model in the same container, but it still didn't work. What step did I make a mistake?
`root@huangzetao-dashan-chief-0:/# tritonserver --model-repository=/lanmu1
I1124 08:46:37.702350 3510 metrics.cc:290] Collecting metrics for GPU 0: NVIDIA GeForce RTX 2080 Ti
I1124 08:46:38.104128 3510 libtorch.cc:1029] TRITONBACKEND_Initialize: pytorch
I1124 08:46:38.104164 3510 libtorch.cc:1039] Triton TRITONBACKEND API version: 1.4
I1124 08:46:38.104179 3510 libtorch.cc:1045] 'pytorch' TRITONBACKEND API version: 1.4
2021-11-24 16:46:38.306469: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
I1124 08:46:38.360362 3510 tensorflow.cc:2169] TRITONBACKEND_Initialize: tensorflow
I1124 08:46:38.360399 3510 tensorflow.cc:2179] Triton TRITONBACKEND API version: 1.4
I1124 08:46:38.360410 3510 tensorflow.cc:2185] 'tensorflow' TRITONBACKEND API version: 1.4
I1124 08:46:38.360417 3510 tensorflow.cc:2209] backend configuration:
{}
I1124 08:46:38.374465 3510 onnxruntime.cc:1970] TRITONBACKEND_Initialize: onnxruntime
I1124 08:46:38.374490 3510 onnxruntime.cc:1980] Triton TRITONBACKEND API version: 1.4
I1124 08:46:38.374500 3510 onnxruntime.cc:1986] 'onnxruntime' TRITONBACKEND API version: 1.4
I1124 08:46:38.415934 3510 openvino.cc:1193] TRITONBACKEND_Initialize: openvino
I1124 08:46:38.415964 3510 openvino.cc:1203] Triton TRITONBACKEND API version: 1.4
I1124 08:46:38.415973 3510 openvino.cc:1209] 'openvino' TRITONBACKEND API version: 1.4
I1124 08:46:38.716599 3510 pinned_memory_manager.cc:240] Pinned memory pool is created at '0x7f3b80000000' with size 268435456
I1124 08:46:38.718275 3510 cuda_memory_manager.cc:105] CUDA memory pool is created on device 0 with size 67108864
I1124 08:46:38.726557 3510 model_repository_manager.cc:1045] loading: pl_lanmu_ml:1
I1124 08:46:38.826877 3510 model_repository_manager.cc:1045] loading: pl_lanmu_prep:1
I1124 08:46:38.927231 3510 model_repository_manager.cc:1045] loading: pl_lanmu_postp:1
I1124 08:46:38.936697 3510 python.cc:1714] TRITONBACKEND_ModelInstanceInitialize: pl_lanmu_prep (GPU device 0)
I1124 08:46:40.450422 3510 logging.cc:49] [MemUsageChange] Init CUDA: CPU +797, GPU +0, now: CPU 1028, GPU 590 (MiB)
I1124 08:46:40.451587 3510 logging.cc:49] Loaded engine size: 80 MiB
E1124 08:46:40.455603 3510 logging.cc:43] 1: [stdArchiveReader.cpp::StdArchiveReader::35] **Error Code 1: Serialization (Serialization assertion safeVersionRead == safeSerializationVersion failed.Version tag does not match. Note: Current Version: 0, Serialized Engine Version: 96)**
E1124 08:46:40.455638 3510 logging.cc:43] 4: [runtime.cpp::deserializeCudaEngine::50] Error Code 4: Internal Error (Engine deserialization failed.)
E1124 08:46:40.461154 3510 model_repository_manager.cc:1215] failed to load 'pl_lanmu_ml' version 1: Internal: unable to create TensorRT engine
I1124 08:46:45.815909 3510 model_repository_manager.cc:1212] successfully loaded 'pl_lanmu_prep' version 1
I1124 08:46:45.820568 3510 python.cc:1714] TRITONBACKEND_ModelInstanceInitialize: pl_lanmu_postp (GPU device 0)
I1124 08:46:46.871717 3510 model_repository_manager.cc:1212] successfully loaded 'pl_lanmu_postp' version 1
E1124 08:46:46.871841 3510 model_repository_manager.cc:1404] Invalid argument: ensemble 'pl_lanmu' depends on 'pl_lanmu_ml' which has no loaded version
I1124 08:46:46.871944 3510 server.cc:504]
+------------------+------+
| Repository Agent | Path |
+------------------+------+
+------------------+------+

I1124 08:46:46.872040 3510 server.cc:543]
+-------------+-----------------------------------------------------------------+--------+
| Backend     | Path                                                            | Config |
+-------------+-----------------------------------------------------------------+--------+
| tensorrt    | <built-in>                                                      | {}     |
| pytorch     | /opt/tritonserver/backends/pytorch/libtriton_pytorch.so         | {}     |
| onnxruntime | /opt/tritonserver/backends/onnxruntime/libtriton_onnxruntime.so | {}     |
| openvino    | /opt/tritonserver/backends/openvino/libtriton_openvino.so       | {}     |
| tensorflow  | /opt/tritonserver/backends/tensorflow1/libtriton_tensorflow1.so | {}     |
| python      | /opt/tritonserver/backends/python/libtriton_python.so           | {}     |
+-------------+-----------------------------------------------------------------+--------+

I1124 08:46:46.872120 3510 server.cc:586]
+----------------+---------+---------------------------------------------------------+
| Model          | Version | Status                                                  |
+----------------+---------+---------------------------------------------------------+
| pl_lanmu_ml    | 1       | UNAVAILABLE: Internal: unable to create TensorRT engine |
| pl_lanmu_postp | 1       | READY                                                   |
| pl_lanmu_prep  | 1       | READY                                                   |
+----------------+---------+---------------------------------------------------------+

I1124 08:46:46.872280 3510 tritonserver.cc:1718]
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Option                           | Value                                                                                                                                                                                  |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| server_id                        | triton                                                                                                                                                                                 |
| server_version                   | 2.13.0                                                                                                                                                                                 |
| server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_policy model_configuration system_shared_memory cuda_shared_memory binary_tensor_data statistics |
| model_repository_path[0]         | /lanmu1                                                                                                                                                                                |
| model_control_mode               | MODE_NONE                                                                                                                                                                              |
| strict_model_config              | 1                                                                                                                                                                                      |
| pinned_memory_pool_byte_size     | 268435456                                                                                                                                                                              |
| cuda_memory_pool_byte_size{0}    | 67108864                                                                                                                                                                               |
| min_supported_compute_capability | 6.0                                                                                                                                                                                    |
| strict_readiness                 | 1                                                                                                                                                                                      |
| exit_timeout                     | 30                                                                                                                                                                                     |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

I1124 08:46:46.872332 3510 server.cc:234] Waiting for in-flight requests to complete.
I1124 08:46:46.872345 3510 model_repository_manager.cc:1078] unloading: pl_lanmu_prep:1
I1124 08:46:46.872442 3510 model_repository_manager.cc:1078] unloading: pl_lanmu_postp:1
I1124 08:46:46.872554 3510 server.cc:249] Timeout 30: Found 2 live models and 0 in-flight non-inference requests
I1124 08:46:47.872654 3510 server.cc:249] Timeout 29: Found 2 live models and 0 in-flight non-inference requests
I1124 08:46:47.902923 3510 model_repository_manager.cc:1195] successfully unloaded 'pl_lanmu_prep' version 1
I1124 08:46:47.997291 3510 model_repository_manager.cc:1195] successfully unloaded 'pl_lanmu_postp' version 1
I1124 08:46:48.872777 3510 server.cc:249] Timeout 28: Found 0 live models and 0 in-flight non-inference requests
error: creating server: Internal - failed to load all models`

**Comment by CoderHam** [comment]
@lincong8722 which version of TRT did you use to produce the model? The version of TRT in Triton needs to match the TRT version used to produce the model.

**Comment by lincong8722** [comment]
> @lincong8722您使用哪个版本的TRT来制作模型？Triton 中的 TRT 版本需要与用于生成模型的 TRT 版本相匹配。

Hello, I installed version 8.2.1 of tensorrt, but when turning the model, I was prompted with attributeerror: **'tensorrt. Tensorrt. Builder' object has no attribute 'max_ workspace_ Size '**, so I executed the **install NVIDIA tensorrt = = 7.2. *** operation to convert the model. The above error is displayed on Triton. What is the TRT version in Triton?
I just changed the platform: to **"tensorrt_plan"** in config, and then converted the **.pth** model to**. plan**, without adding any other code in it. Am I missing that step? I want to ask you for advice

**Comment by lincong8722** [comment]
@CoderHam Hello, I installed version 8.2.1 of tensorrt, but when turning the model, I was prompted with attributeerror: 'tensorrt. Tensorrt. Builder' object has no attribute 'max_ workspace_ Size ', so I executed the **install NVIDIA tensorrt = = 7.2. *** operation to convert the model. The above error is displayed on Triton. What is the TRT version in Triton?
image
image
Is the conversion unsuccessful because the two versions are inconsistent? If I put the following tensorrt._ V_ Converting to 8. X will fail. What should I do?
I just changed the platform: to "tensorrt_plan" in config, and then converted the .pth model to. plan, without adding any other code in it. Am I missing that step? I want to ask you for advice

**Comment by lincong8722** [comment]
@CoderHam Hello, I installed version 8.2.1 of tensorrt, but when turning the model, I was prompted with attributeerror: 'tensorrt. Tensorrt. Builder' object has no attribute 'max_ workspace_ Size ', so I executed the **install NVIDIA tensorrt = = 7.2. *** operation to convert the model. The above error is displayed on Triton. What is the TRT version in Triton?
![image](https://user-images.githubusercontent.com/57218642/143582299-375541a6-258c-4585-babc-80abdbf96f06.png)
![image](https://user-images.githubusercontent.com/57218642/143582321-48da7498-b6ed-494f-81bb-f87e37fa9f10.png)
Is the conversion unsuccessful because the two versions are inconsistent? If I put the following tensorrt._ V_ Converting to 8. X will fail. What should I do?
I just changed the platform: to "tensorrt_plan" in config, and then converted the .pth model to. plan, without adding any other code in it. Am I missing that step? I want to ask you for advice

**Comment by CoderHam** [comment]
Please use the **exact same version** of TRT for your model preparation. You might need to update the build docs accordingly for the new TRT 8 convention for model generation. Feel free to refer to the model gen scripts for trt models that are used by Triton: https://github.com/triton-inference-server/server/blob/main/qa/common/gen_qa_models.py#L787

**Comment by Tabrizian** [comment]
Closing due to in-activity. Feel free to re-open if the issue persists.

**Comment by phamkhactu** [comment]
Hi @Tabrizian 
I have encountered with same problem, but I think I have installed same version tensorrt and triton server
Here Is my step

1. I pull tensorrt image: ``` nvcr.io/nvidia/tensorrt       23.02-py3 ```
2. I convert onnx to tensorrt sucessfully
```
import tensorrt as trt
from onnx import ModelProto
import os 
os.environ["CUDA_VISIBLE_DEVICES"]="1"




TRT_LOGGER = trt.Logger(trt.Logger.INFO)
a=(int)(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
EXPLICIT_BATCH = 1 << (int)(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)

def GiB(val):
    return val * 1 << 30

def build_detec_engine(onnx_path,using_int4=False, using_int8= False, using_half=False, dynamic_input=True, workspace_size=2, name_input="x",
                min_shape=(1,3,100,100), opt_shape=(1,3,960,960), max_shape=(1,3,1280,1280)):
    trt.init_libnvinfer_plugins(None, '')
    with trt.Builder(TRT_LOGGER) as builder, builder.create_network(EXPLICIT_BATCH) as network, trt.OnnxParser(network, TRT_LOGGER) as parser:
        builder.max_batch_size = 1 # always 1 for explicit batch
        config = builder.create_builder_config()
        config.max_workspace_size = GiB(int(workspace_size))
        if using_half:
            config.set_flag(trt.BuilderFlag.FP16)
        if using_int8:
            config.set_flag(trt.BuilderFlag.INT8)
        if using_int4:
            config.set_flag(trt.BuilderFlag.INT4)
        # Load the Onnx model and parse it in order to populate the TensorRT network.
        with open(onnx_path, 'rb') as model:
            if not parser.parse(model.read()):
                print ('ERROR: Failed to parse the ONNX file.')
                for error in range(parser.num_errors):
                    print (parser.get_error(error))
                return None
        
        if dynamic_input:
            profile = builder.create_optimization_profile();
            profile.set_shape(name_input, min_shape, opt_shape, max_shape) 
            config.add_optimization_profile(profile)
        print("hihihihi")
        return builder.build_serialized_network(network, config) 


def save_engine(serialized_engine, file_name):
    # buf = serialized_engine.serialize()
    with open(file_name, 'wb') as f:
       f.write(serialized_engine)
    


def load_engine(trt_runtime, plan_path):
   with open(plan_path, 'rb') as f:
       engine_data = f.read()
   engine = trt_runtime.deserialize_cuda_engine(engine_data)
   return engine


def convert_to_rt():

    engine_name = "trt_weights_8.5.3.1/qat_enn_space_not_fintune_86_triton_int8.plan"
    onnx_path = "onnx_weights/qat_enn_space_not_fintune_86.onnx" 
    batch_size = 1
    
    model = ModelProto()
    with open(onnx_path, "rb") as f:
        model.ParseFromString(f.read())

    d0 = model.graph.input[0].type.tensor_type.shape.dim[1].dim_value
    d1 = model.graph.input[0].type.tensor_type.shape.dim[2].dim_value
    d2 = model.graph.input[0].type.tensor_type.shape.dim[3].dim_value
    shape = [batch_size , d0, d1 ,d2]
    print("shape input model:", shape) #[1, 3, -1, -1]
    engine = build_detec_engine(onnx_path=onnx_path, name_input="input",
                                min_shape=(1,3,32,128),
                                opt_shape=(1,3,32,128),
                                max_shape=(1,3,32,128), using_int8=True)
    
    save_engine(engine, engine_name) 

if __name__ == '__main__':
    convert_to_rt()
```
3. I start build my tensorrt model in ```triton server:  nvcr.io/nvidia/tritonserver   23.02-py3 ```
I get error:
```
W0526 16:43:07.342114 1 pinned_memory_manager.cc:236] Unable to allocate pinned system memory, pinned memory pool will not be available: CUDA driver version is insufficient for CUDA runtime version
I0526 16:43:07.342161 1 cuda_memory_manager.cc:115] CUDA memory pool disabled
I0526 16:43:07.343499 1 model_lifecycle.cc:459] loading: db:1
I0526 16:43:07.343524 1 model_lifecycle.cc:459] loading: ocr:1
I0526 16:43:07.344221 1 onnxruntime.cc:2459] TRITONBACKEND_Initialize: onnxruntime
I0526 16:43:07.344233 1 onnxruntime.cc:2469] Triton TRITONBACKEND API version: 1.11
I0526 16:43:07.344236 1 onnxruntime.cc:2475] 'onnxruntime' TRITONBACKEND API version: 1.11
I0526 16:43:07.344239 1 onnxruntime.cc:2505] backend configuration:
{"cmdline":{"auto-complete-config":"true","min-compute-capability":"6.000000","backend-directory":"/opt/tritonserver/backends","default-max-batch-size":"4"}}
I0526 16:43:07.352038 1 onnxruntime.cc:2563] TRITONBACKEND_ModelInitialize: db (version 1)
I0526 16:43:07.352348 1 onnxruntime.cc:666] skipping model configuration auto-complete for 'db': inputs and outputs already specified
I0526 16:43:07.378001 1 tensorrt.cc:64] TRITONBACKEND_Initialize: tensorrt
I0526 16:43:07.378016 1 tensorrt.cc:74] Triton TRITONBACKEND API version: 1.11
I0526 16:43:07.378021 1 tensorrt.cc:80] 'tensorrt' TRITONBACKEND API version: 1.11
I0526 16:43:07.378048 1 tensorrt.cc:104] backend configuration:
{"cmdline":{"auto-complete-config":"true","min-compute-capability":"6.000000","backend-directory":"/opt/tritonserver/backends","default-max-batch-size":"4"}}
I0526 16:43:07.378214 1 onnxruntime.cc:2606] TRITONBACKEND_ModelInstanceInitialize: db_0 (CPU device 0)
I0526 16:43:07.419323 1 tensorrt.cc:211] TRITONBACKEND_ModelInitialize: ocr (version 1)
I0526 16:43:07.419769 1 tensorrt.cc:260] TRITONBACKEND_ModelInstanceInitialize: ocr (CPU device 0)
I0526 16:43:07.419843 1 tensorrt.cc:298] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0526 16:43:07.419852 1 tensorrt.cc:237] TRITONBACKEND_ModelFinalize: delete model state
E0526 16:43:07.419860 1 model_lifecycle.cc:597] failed to load 'ocr' version 1: Invalid argument: unable to load model 'ocr', TensorRT backend supports only GPU device
I0526 16:43:07.419893 1 onnxruntime.cc:2606] TRITONBACKEND_ModelInstanceInitialize: db_1 (CPU device 0)
I0526 16:43:07.458225 1 model_lifecycle.cc:694] successfully loaded 'db' version 1
I0526 16:43:07.458268 1 server.cc:563] 
+------------------+------+
| Repository Agent | Path |
+------------------+------+
+------------------+------+

I0526 16:43:07.458305 1 server.cc:590] 
+-------------+--------------------------------------------------+--------------------------------------------------+
| Backend     | Path                                             | Config                                           |
+-------------+--------------------------------------------------+--------------------------------------------------+
| onnxruntime | /opt/tritonserver/backends/onnxruntime/libtriton | {"cmdline":{"auto-complete-config":"true","min-c |
|             | _onnxruntime.so                                  | ompute-capability":"6.000000","backend-directory |
|             |                                                  | ":"/opt/tritonserver/backends","default-max-batc |
|             |                                                  | h-size":"4"}}                                    |
|             |                                                  |                                                  |
| tensorrt    | /opt/tritonserver/backends/tensorrt/libtriton_te | {"cmdline":{"auto-complete-config":"true","min-c |
|             | nsorrt.so                                        | ompute-capability":"6.000000","backend-directory |
|             |                                                  | ":"/opt/tritonserver/backends","default-max-batc |
|             |                                                  | h-size":"4"}}                                    |
|             |                                                  |                                                  |
+-------------+--------------------------------------------------+--------------------------------------------------+

I0526 16:43:07.458342 1 server.cc:633] 
+-------+---------+--------------------------------------------------------------------------------------------------+
| Model | Version | Status                                                                                           |
+-------+---------+--------------------------------------------------------------------------------------------------+
| db    | 1       | READY                                                                                            |
| ocr   | 1       | UNAVAILABLE: Invalid argument: unable to load model 'ocr', TensorRT backend supports only GPU de |
|       |         | vice                                                                                             |
+-------+---------+--------------------------------------------------------------------------------------------------+

W0526 16:43:07.479257 1 metrics.cc:848] Cannot get CUDA device count, GPU metrics will not be available
I0526 16:43:07.479382 1 metrics.cc:757] Collecting CPU metrics
I0526 16:43:07.479458 1 tritonserver.cc:2264] 
+----------------------------------+----------------------------------------------------------------------------------+
| Option                           | Value                                                                            |
+----------------------------------+----------------------------------------------------------------------------------+
| server_id                        | triton                                                                           |
| server_version                   | 2.31.0                                                                           |
| server_extensions                | classification sequence model_repository model_repository(unload_dependents) sch |
|                                  | edule_policy model_configuration system_shared_memory cuda_shared_memory binary_ |
|                                  | tensor_data statistics trace logging                                             |
| model_repository_path[0]         | /models                                                                          |
| model_control_mode               | MODE_POLL                                                                        |
| strict_model_config              | 0                                                                                |
| rate_limit                       | OFF                                                                              |
| pinned_memory_pool_byte_size     | 268435456                                                                        |
| response_cache_byte_size         | 0                                                                                |
| min_supported_compute_capability | 6.0                                                                              |
| strict_readiness                 | 1                                                                                |
| exit_timeout                     | 30                                                                               |
+----------------------------------+----------------------------------------------------------------------------------+

E0526 16:43:07.479480 1 tritonserver.cc:2273] Internal: failed to load all models
I0526 16:43:07.480312 1 grpc_server.cc:4868] Started GRPCInferenceService at 0.0.0.0:8001
I0526 16:43:07.480454 1 http_server.cc:3477] Started HTTPService at 0.0.0.0:8000
I0526 16:43:07.521347 1 http_server.cc:184] Started Metrics Service at 0.0.0.0:8002
I0526 16:43:07.526622 1 model_lifecycle.cc:459] loading: ocr:1
I0526 16:43:07.526697 1 tensorrt.cc:211] TRITONBACKEND_ModelInitialize: ocr (version 1)
I0526 16:43:07.526957 1 tensorrt.cc:260] TRITONBACKEND_ModelInstanceInitialize: ocr (CPU device 0)
I0526 16:43:07.526987 1 tensorrt.cc:298] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0526 16:43:07.526998 1 tensorrt.cc:237] TRITONBACKEND_ModelFinalize: delete model state
E0526 16:43:07.527005 1 model_lifecycle.cc:597] failed to load 'ocr' version 1: Invalid argument: unable to load model 'ocr', TensorRT backend supports only GPU device
```
Thanks in advance!!
