### ISSUE TITLE
Triton Inference Server binary distribution for Ubuntu x64

### ISSUE THREAD

**Issue by konstantin-sancom** [triton-inference-server/server#3610]
**Is your feature request related to a problem? Please describe.**
There is no binary distribution to run under openVZ containers.

**Describe the solution you'd like**
I want to have binary Release distribution(in DEBs) to run under Ubuntu LTS in openVZ container

**Describe alternatives you've considered**
I want to have binary Release distribution(in TARball) to run under Ubuntu LTS in openVZ container

**Additional context**

**Comment by CoderHam** [comment]
@konstantin-sancom can you exact the binaries and libraries from the x86 container and package them yourself?
You could also use build.py to build your own Triton container that is compatible to run on openVZ if the above is not sufficient.

**Comment by konstantin-sancom** [comment]
> @konstantin-sancom can you exact the binaries and libraries from the x86 container and package them yourself? You could also use build.py to build your own Triton container that is compatible to run on openVZ if the above is not sufficient.

Hi, @CoderHam , We do so - extracted binaries from Docker container, but we not shure, that we did in the right way(dependent libraries versions an so on), cause there are some troubles in runtime, that I described in other issues.
So, tested by veendor binary distribution would be something that insures us, that probkem is not in the way we performed extraction.

**Comment by CoderHam** [comment]
@konstantin-sancom what are the errors are seeing during runtime? Triton does not plan on shipping binaries separately.

**Comment by konstantin-sancom** [comment]
> @konstantin-sancom what are the errors are seeing during runtime? Triton does not plan on shipping binaries separately.

Hi, @CoderHam . I'm talking about this issue: https://github.com/triton-inference-server/server/issues/3694

**Comment by dyastremsky** [comment]
As we have no current plans to ship separate binaries (with exceptions, such as Jetson), I am going to close this issue.
