### ISSUE TITLE
Allow different input types for different inputs in perf_analyzer

### ISSUE THREAD

**Issue by kpedro88** [triton-inference-server/server#3612]
**Is your feature request related to a problem? Please describe.**
To test some models, it may be desirable to have e.g. zeroes for one input, but random data for another input. This currently is not supported by perf_analyzer.

**Describe the solution you'd like**
It would be useful if the argument `--input-data` supported a syntax similar to the argument `--shape`, i.e. `name:shape`.

**Describe alternatives you've considered**
Sometimes models can be modified to treat some inputs as zeros internally, but this is manual and error-prone.

**Comment by CoderHam** [comment]
cc @tanmayv25

**Comment by tanmayv25** [comment]
@kpedro88  Have you looked at [providing data as json](https://github.com/triton-inference-server/server/blob/main/docs/perf_analyzer.md#real-input-data) to perf_analyzer?  For models that are sensitive to data we recommend providing data explicitly for each input in json. 

You can generate the custom json file with your data(some inputs 0, some inputs random etc.) and use it to benchmark your model.

**Comment by kpedro88** [comment]
Yes, I've used the json feature as well. It just seemed that since perf_analyzer can already 1. generate random data on the fly and 2. specify some information per-input, these two features could be combined to simplify such a case.

**Comment by tanmayv25** [comment]
Sure that it can be considered as an enhancement, but it does not add much value as there is already an alternative.
The way random data is generated in perf_analyzer is that we create a buffer of largest input tensor size and populate it with random data. All the inputs in all the requests then use the same buffer with their respective size. 
So, essentially the feature can be easily emulated by having below json with **a single entry**:
```
 {
    "data" :
     [
        {
          "INPUT0" : [0,0,0,0,0,0,0],
          "INPUT1" : [<random bytes>],
          "INPUT2" : [<random bytes>]
        }
      ]
  }
```

What's more using input json method, you can provide different random bytes to INPUT1 and INPUT2. With the feature you are requesting the random bytes for INPUT1 and INPUT2 will be identical to the byte size of INPUT1 and INPUT2. 
Specifying as json is more customizable, but also what a user might expect. The requested feature may lead to confusion and add complicate the current logic.

**Comment by tanmayv25** [comment]
There are similar requests like having random data within a range etc. We would not like to add these features in perf_analyzer and let user decide the data they want to use for their models.

**Comment by dzier** [comment]
Closing due due to lack of activity
