### ISSUE TITLE
Segmentation fault in libtriton_pytorch.so with invalid inputs

### ISSUE THREAD

**Issue by jamt9000** [triton-inference-server/server#3613]
**Description**

Original behaviour observed:
Triton occasionally segfaults. Right now it seems to happen after about 5 minutes under load.

(see below for updated cause)

**Triton Information**

nvcr.io/nvidia/tritonserver:21.10-py3

**To Reproduce**
~Not sure, it seems quite random. Running a mix of pytorch and onnx models. GPU and CPU memory use both seem ok before it dies.~

Update: So it seems to happen with the NVIDIA Jasper TritonClient when the audio_signal is an empty array,
meaning that `input_batch = array([], shape=(1, 0), dtype=float16)`

https://github.com/NVIDIA/DeepLearningExamples/blob/a8c42a142ceb67513892a303b48185d9c52864c0/PyTorch/SpeechRecognition/Jasper/triton/speech_utils.py#L257

So this is certainly a nonsensical input, but it would be great if it didn't bring down the whole triton server and if it gave a more informative error.

**Expected behavior**
Not segfaulting.

```
0# 0x0000564B4B89F8A9 in tritonserver
1# 0x00007F631496D210 in /usr/lib/x86_64-linux-gnu/libc.so.6
2# abort in /usr/lib/x86_64-linux-gnu/libc.so.6
3# 0x00007F6314D23911 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
4# 0x00007F6314D2F38C in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
5# 0x00007F6314D2F3F7 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
6# 0x00007F6314D2F6A9 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
7# 0x00007F62CEB89AB6 in /opt/tritonserver/backends/pytorch/libtorch_cpu.so
8# 0x00007F6310563BA4 in /opt/tritonserver/backends/pytorch/libtriton_pytorch.so
9# 0x00007F6310567176 in /opt/tritonserver/backends/pytorch/libtriton_pytorch.so
10# TRITONBACKEND_ModelInstanceExecute in /opt/tritonserver/backends/pytorch/libtriton_pytorch.so
11# 0x00007F63154F983A in /opt/tritonserver/bin/../lib/libtritonserver.so
12# 0x00007F63154FA04D in /opt/tritonserver/bin/../lib/libtritonserver.so
13# 0x00007F63153AE801 in /opt/tritonserver/bin/../lib/libtritonserver.so
14# 0x00007F63154F3DC7 in /opt/tritonserver/bin/../lib/libtritonserver.so
15# 0x00007F6314D5BDE4 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
16# 0x00007F63151D9609 in /usr/lib/x86_64-linux-gnu/libpthread.so.0
17# clone in /usr/lib/x86_64-Linux-gnu/libc.so.6

triton_1 exited with code 139
```

**Comment by CoderHam** [comment]
Triton does have handling to catch errors from the frameworks but we are unable to prevent a segfault from occurring since it happens inside the framework.

**Comment by leemengwei** [comment]
@CoderHam  
Help, similar concern here with loading backends model with _explicit-control_: In our case models are given by different people across a platform, somehow managers will try to load these newly published models. When some of these models were generated by mismatch version of TensorRT then if tried loaded by `ip:port/v2/repository/models/[some_model_name]/load` the whole Triton backend CRASH, impacting dozens of models serving on the background....
