### ISSUE TITLE
floating point exception using self built python backend and triton, centos

### ISSUE THREAD

**Issue by azraelkuan** [triton-inference-server/server#3614]
**Description**
when use tritonserver, it will raise floating point exception

**Triton Information**
build from r21.07 on centos

**To Reproduce**
![image](https://user-images.githubusercontent.com/23380152/143429572-aaa7bae0-fb54-4e13-8dc8-44be570812fc.png)
![image](https://user-images.githubusercontent.com/23380152/143429661-37246304-dbb6-453e-adee-ceee2ba8d8c6.png)

![image](https://user-images.githubusercontent.com/23380152/143429699-9b161e77-79cb-4e14-8185-4f170ffe6e64.png)

any one has some suggestion on this?

**Comment by azraelkuan** [comment]
@Tabrizian

**Comment by Tabrizian** [comment]
@azraelkuan Are you able to reproduce the same error in the Triton NGC container with your model repository?

**Comment by azraelkuan** [comment]
@Tabrizian hi，i have tried the triton ngc docker, there is no problem.
how can i show u the back trace of the segfault?

**Comment by Tabrizian** [comment]
If you have access to the core dump, you can use `gdb` to find the backtrace.

```
gdb  /opt/tritonserver/bin/tritonserver /<route_to_core_dump>/

(gdb) bt
```

https://sourceware.org/gdb/current/onlinedocs/gdb/Backtrace.html

**Comment by azraelkuan** [comment]
solved
