### ISSUE TITLE
Error in using S3-Compatible Storage [Oracle Cloud Infrastructure (OCI) Object Storage] 

### ISSUE THREAD

**Issue by Abh1navKumar** [triton-inference-server/server#3615]
**Description**
I am trying to use Oracle OCI Object storage. It is a S3-Compatible: https://docs.oracle.com/en-us/iaas/Content/Object/Tasks/s3compatibleapi.htm. 

**Triton Information**
nvcr.io/nvidia/tensorrtserver:21.10-py3

Are you using the Triton container or did you build it yourself?
I am using the Triton container

**To Reproduce**

Note : 
1. aws credentials are already provided as aws config inside the docker container under root/.aws folder.
2. Was able to load the same model from AWS S3 bucket with the same approach.

Behaviours - 

1. Running triton server with hostname having https
docker run -d --rm -p8000:8000 -p8001:8001 -p8002:8002 -v/Users/kabhinak/DevSource/triton-inference-server/models:/models nvcr.io/nvidia/tritonserver:21.10-py3 tritonserver --model-repository=s3://https://namespace.compat.objectstorage.us-ashburn-1.oraclecloud.com:443/TritonModelBucket

Getting this error:
error: creating server: Internal - Could not get MetaData for bucket with name https: due to exception: , error message: curlCode: 6, Couldn't resolve host name

2.  Running triton server with hostname not having https
docker run -d --rm -p8000:8000 -p8001:8001 -p8002:8002 -v/Users/kabhinak/DevSource/triton-inference-server/models:/models nvcr.io/nvidia/tritonserver:21.10-py3 tritonserver --model-repository=s3://namespace.compat.objectstorage.us-ashburn-1.oraclecloud.com:443/TritonModelBucket

 Getting this error:
error: creating server: Internal - Could not get MetaData for bucket with name namespace.compat.objectstorage.us-ashburn-1.oraclecloud.com:443 due to exception: , error message: curlCode: 6, Couldn't resolve host name

3.  Running triton server with hostname not having port
docker run -d --rm -p8000:8000 -p8001:8001 -p8002:8002 -v/Users/kabhinak/DevSource/triton-inference-server/models:/models nvcr.io/nvidia/tritonserver:21.10-py3 tritonserver --model-repository=s3://namespace .compat.objectstorage.us-ashburn-1.oraclecloud.com/TritonModelBucket

Getting this error:
error: creating server: Internal - Could not get MetaData for bucket with name namespace.compat.objectstorage.us-ashburn-1.oraclecloud.com due to exception: , error message: curlCode: 6, Couldn't resolve host name

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well) : Using model Simple from examples.

**Expected behavior**
Model shall be loaded from OCI object storage bucket.

I am able to get data from OCI bucket using boto S3 api. You can find this example here:https://docs.oracle.com/en-us/iaas/Content/Object/Tasks/s3compatibleapi.htm

import boto3

s3 = boto3.resource(
    service_name='s3',
    region_name='us-ashburn-1',
    aws_access_key_id='74236c7628a7e17c83d4ead8f0b7050534a362j3',
    aws_secret_access_key='bt2asO8GeCFaYk5RTjmbgHRNU6I0TPRlOmXsO3x9wWY=',
    endpoint_url = 'https://ociodscdev.compat.objectstorage.us-ashburn-1.oraclecloud.com'
)

bucketname = "TritonModelBucket"
   
print(bucketname)

for obj in s3.Bucket(bucketname).objects.all():
    print(obj)

**Comment by KshitizLohia** [comment]
@CoderHam Can we get your eyes on this issue? I think there was already an issue filed earlier on integration of OCI Object store : https://github.com/triton-inference-server/server/issues/2493

**Comment by CoderHam** [comment]
@KshitizLohia @KshitizLohia The issue you are facing is due to the fact that your bucket has capital letters in it.
Based on the rules for bucket naming: https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html
-> Bucket names can consist only of lowercase letters, numbers, dots (.), and hyphens (-).

Please re-try with the appropriate lowercase bucket name

**Comment by KshitizLohia** [comment]
@CoderHam Yes. Changing bucket name fixed the issue. Thanks.

**Comment by Abh1navKumar** [comment]
Yeah, we are able to load model from OCI object Storage successfully. Closing this issue.
