### ISSUE TITLE
Getting (unsorted) value of all classes as output

### ISSUE THREAD

**Issue by umerjamil16** [triton-inference-server/server#3616]
I'm running image_client.py Classification example as demonstrated in Quick Start [https://github.com/triton-inference-server/server/blob/main/docs/quickstart.md#run-triton](url) and getting top k classification results. 

My question is how do I get (unsorted) value of all classes on the output? Lets say there are 1000 classes so the output array size will be [1, 1000]. Right now, I'm getting top-k results based in -c flag. 

What I have found is that I have to edit the classification.cc file [https://github.com/triton-inference-server/server/blob/8d02c9e8f1075baf525614120514ec2e12d3e842/src/servers/classification.cc#L39](url) and build the triton server. 

Please let me know if there is any other way to do this.

**Comment by zzk0** [comment]
You can edit the image\_client.py like this:

```
outputs.append(httpclient.InferRequestedOutput('OUTPUT__0', binary_data=False, class_count=3))  # topN classes
outputs.append(httpclient.InferRequestedOutput('OUTPUT__0', binary_data=False))  # Get the prob of every classes, that is [1, 1000]
```

**Comment by umerjamil16** [comment]
Got it. Thanks :)
