### ISSUE TITLE
Failed to build r21.05 in Docker container

### ISSUE THREAD

**Issue by konstantin-sancom** [triton-inference-server/server#3617]
**Description**
I failed to build in Docker with this instructions https://github.com/triton-inference-server/server/blob/r21.05/docs/build.md

Build process failed with:
`[ 32%] Completed 'grpc-repo'`
`/usr/bin/cmake -E make_directory /tmp/tritonbuild/tritonserver/build/CMakeFiles`
`/usr/bin/cmake -E touch /tmp/tritonbuild/tritonserver/build/CMakeFiles/grpc-repo-complete`
`/usr/bin/cmake -E touch /tmp/tritonbuild/tritonserver/build/grpc-repo/src/grpc-repo-stamp/grpc-repo-done`
`make[3]: Leaving directory '/tmp/tritonbuild/tritonserver/build'`
`[ 32%] Built target grpc-repo`
`make[2]: Leaving directory '/tmp/tritonbuild/tritonserver/build'`
`make[1]: Leaving directory '/tmp/tritonbuild/tritonserver/build'`
`make[1]: *** [CMakeFiles/Makefile2:145: CMakeFiles/server.dir/rule] Error 2`
`make: *** [Makefile:137: server] Error 2`
`version 2.10.0`
`backend "ensemble" at tag/branch "main"`
`Building Triton Inference Server`
`component "common" at tag/branch "latest"`
`component "core" at tag/branch "latest"`
`component "backend" at tag/branch "latest"`
`component "thirdparty" at tag/branch "latest"`
`error: make server failed`
`error: docker run tritonserver_builder failed`

**Triton Information**
r21.05 (for Kaldi backend support)

Tried build it myself.

**To Reproduce**
Follow the sterps in instruction:
https://github.com/triton-inference-server/server/blob/r21.05/docs/build.md
`./build.py --cmake-dir=/root/_distr --build-dir=/tmp/citritonbuild --enable-logging --enable-stats --enable-tracing --enable-metrics --enable-gpu-metrics --enable-gpu --endpoint=http --endpoint=grpc --repo-tag=common:latest --repo-tag=core:latest --repo-tag=backend:latest --repo-tag=thirdparty:latest --backend=ensemble`

**Expected behavior**
Build success.

**Comment by zzk0** [comment]
From the document, you can find this line:

>  For example, if you are building on the r21.05 branch you should set <container tag> to be "r21.05".

If you want to build a specified version, you should set the <container tag> to that version. 

You can replace the "latest" with "r21.05".

```
./build.py --cmake-dir=/root/_distr --build-dir=/tmp/citritonbuild --enable-logging --enable-stats --enable-tracing --enable-metrics --enable-gpu-metrics --enable-gpu --endpoint=http --endpoint=grpc --repo-tag=common:latest --repo-tag=core:latest --repo-tag=backend:latest --repo-tag=thirdparty:latest --backend=ensemble
```

**Comment by konstantin-sancom** [comment]
> From the document, you can find this line:
> 
> > For example, if you are building on the r21.05 branch you should set `<container tag>` to be "r21.05".
> 
> If you want to build a specified version, you should set the `<container tag>` to that version.
> 
> You can replace the "latest" with "r21.05".
> 
> ```
> ./build.py --cmake-dir=/root/_distr --build-dir=/tmp/citritonbuild --enable-logging --enable-stats --enable-tracing --enable-metrics --enable-gpu-metrics --enable-gpu --endpoint=http --endpoint=grpc --repo-tag=common:r21.05 --repo-tag=core:r21.05 --repo-tag=backend:r21.05 --repo-tag=thirdparty:r21.05 --backend=ensemble
> ```

Thank you for help. Now it works!
