### ISSUE TITLE
Failed to build triton server with docker at branch r20.12

### ISSUE THREAD

**Issue by nxty2011** [triton-inference-server/server#3620]
**Description**
Fail to build trition server at branch r20.12 via build.py following the build instructons in 

https://github.com/triton-inference-server/server/blob/r20.12/docs/build.md

with command in terminal at root directory:
"sudo ./build.py --build-dir=/tmp/citritonbuild --enable-logging --enable-stats --enable-tracing --enable-metrics --enable-gpu-metrics --enable-gpu --filesystem=gcs --filesystem=s3 --endpoint=http --endpoint=grpc --repo-tag=common:r20.12 --repo-tag=core:r20.12 --repo-tag=backend:r20.12 --backend=custom --backend=ensemble --backend=tensorrt --backend=identity:r20.12 --backend=repeat:r20.12 --backend=square:r20.12 --backend=onnxruntime:r20.12 --backend=pytorch:r20.12 --backend=tensorflow1:r20.12 --backend=tensorflow2:r20.12 --backend=python:r20.12 --backend=dali:r20.12"

Finally I got the error message like.
error: tritonserver_builder failed: {'Error': None, 'StatusCode': 1}

**Triton Information**
What version of Triton are you using?
r20.12

Are you using the Triton container or did you build it yourself?
Using the Triton container(build.py would pull the related containers)

**To Reproduce**
Steps to reproduce the behavior.
1. git clone triton-inference-server/server repo;
2. git fetch 
3. git checkout r20.12
4. sudo ./build.py --build-dir=/tmp/citritonbuild --enable-logging --enable-stats --enable-tracing --enable-metrics --enable-gpu-metrics --enable-gpu --filesystem=gcs --filesystem=s3 --endpoint=http --endpoint=grpc --repo-tag=common:r20.12 --repo-tag=core:r20.12 --repo-tag=backend:r20.12 --backend=custom --backend=ensemble --backend=tensorrt --backend=identity:r20.12 --backend=repeat:r20.12 --backend=square:r20.12 --backend=onnxruntime:r20.12 --backend=pytorch:r20.12 --backend=tensorflow1:r20.12 --backend=tensorflow2:r20.12 --backend=python:r20.12 --backend=dali:r20.12

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
Null

**Expected behavior**
From the doc, I would expect "The result of the build will be a Docker image called tritonserver that will contain the tritonserver executable in /opt/tritonserver/bin and the required shared libraries in /opt/tritonserver/lib. The backends built for Triton will be in /opt/tritonserver/backends".

Extra info may help:
1.I have already run the triton-server and client sucessfully via docer images on the machine.
2. From the build.py script, it fails in the function "contain_build(backends, images)"

**Comment by CoderHam** [comment]
@nxty2011 20.12 is nearly a year old. Is there a reason you are using the specific version?
Can you share a more details log for the error you are seeing during the build?

**Comment by nxty2011** [comment]
@CoderHam thanks for your time.

**20.12 is nearly a year old. Is there a reason you are using the specific version?**
It's because the nvidia-driver of target machine is 455.45. The most updated support version is r20.12 from framework support matrix.

**Can you share a more details log for the error you are seeing during the build?**
1. with no verbose, it would print messages like:
...
Step 68/70 : ENTRYPOINT []
 ---> Running in 5e59007bc425
Removing intermediate container 5e59007bc425
 ---> faab361c2919
Step 69/70 : ENV TRITON_SERVER_VERSION ${TRITON_VERSION}
 ---> Running in f1852f2e7490
Removing intermediate container f1852f2e7490
 ---> 4ef71196a89b
Step 70/70 : ENV NVIDIA_TRITON_SERVER_VERSION ${TRITON_CONTAINER_VERSION}
 ---> Running in 72b400322aba
Removing intermediate container 72b400322aba
 ---> f491e917ea0b
Successfully built f491e917ea0b
Successfully tagged tritonserver_buildbase:latest
error: tritonserver_builder failed: {'Error': None, 'StatusCode': 1}

2. with "build.py -v ... ", the **first line of error** is

 "/workspace/src/servers/http_server.cc:2270:34: error: \xe2\x80\x98evhtp_request_t\xe2\x80\x99 {aka \xe2\x80\x98struct evhtp_request\xe2\x80\x99} has no member named \xe2\x80\x98recv_start_ts\xe2\x80\x99; did you mean \xe2\x80\x98recv_start_ns\xe2\x80\x99?\n'
b' 2270 |           TIMESPEC_TO_NANOS(req->recv_start_ts));\n'
b'      |                                  ^~~~~~~~~~~~~\n' "

which results into the failure build of http_server.

b"make[6]: Leaving directory '/tmp/tritonbuild/tritonserver/build/server'\n"
b'make[6]: *** [src/servers/CMakeFiles/http-endpoint-library.dir/build.make:82: src/servers/CMakeFiles/http-endpoint-library.dir/http_server.cc.o] Error 1\n'
b'make[5]: *** [CMakeFiles/Makefile2:821: src/servers/CMakeFiles/http-endpoint-library.dir/all] Error 2\n'
b'make[5]: *** Waiting for unfinished jobs....\n'
b"make[6]: Leaving directory '/tmp/tritonbuild/tritonserver/build/server'\n"
b'[ 82%] Built target ensemble-backend-library\n'
b"make[6]: Leaving directory '/tmp/tritonbuild/tritonserver/build/server'\n"
b'[ 82%] Built target triton-backend-library\n'
b"make[6]: Leaving directory '/tmp/tritonbuild/tritonserver/build/server'\n"
b'[ 82%] Built target custom-backend-library\n'
b"make[6]: Leaving directory '/tmp/tritonbuild/tritonserver/build/server'\n"
b'[ 82%] Built target server-library\n'
b"make[6]: Leaving directory '/tmp/tritonbuild/tritonserver/build/server'\n"
b'[ 82%] Built target tensorrt-backend-library\n'
b"make[6]: Leaving directory '/tmp/tritonbuild/tritonserver/build/server'\n"
b'[ 82%] Built target grpc-library\n'
b"make[5]: Leaving directory '/tmp/tritonbuild/tritonserver/build/server'\n"
b'make[4]: *** [Makefile:149: all] Error 2\n'
b"make[4]: Leaving directory '/tmp/tritonbuild/tritonserver/build/server'\n"
b"make[3]: Leaving directory '/tmp/tritonbuild/tritonserver/build'\n"
b"make[2]: Leaving directory '/tmp/tritonbuild/tritonserver/build'\n"
b"make[1]: Leaving directory '/tmp/tritonbuild/tritonserver/build'\n"
b'make[3]: *** [CMakeFiles/server.dir/build.make:139: server/src/server-stamp/server-build] Error 2\n'
b'make[2]: *** [CMakeFiles/Makefile2:136: CMakeFiles/server.dir/all] Error 2\n'
b'make[1]: *** [CMakeFiles/Makefile2:143: CMakeFiles/server.dir/rule] Error 2\n'
b'make: *** [Makefile:137: server] Error 2\n'
b'backend "custom" at tag/branch "main"\n'
b'backend "ensemble" at tag/branch "main"\n'
b'backend "tensorrt" at tag/branch "main"\n'
b'backend "identity" at tag/branch "r20.12"\n'
b'backend "repeat" at tag/branch "r20.12"\n'
b'backend "square" at tag/branch "r20.12"\n'
b'backend "onnxruntime" at tag/branch "r20.12"\n'
b'backend "pytorch" at tag/branch "r20.12"\n'
b'backend "tensorflow1" at tag/branch "r20.12"\n'
b'backend "tensorflow2" at tag/branch "r20.12"\n'
b'backend "python" at tag/branch "r20.12"\n'
b'backend "dali" at tag/branch "r20.12"\n'
b'Building Triton Inference Server\n'
b'component "common" at tag/branch "r20.12"\n'
b'component "core" at tag/branch "r20.12"\n'
b'component "backend" at tag/branch "r20.12"\n'
b'component "thirdparty" at tag/branch "main"\n'
b'mkdir: /tmp/tritonbuild/tritonserver/build\n'
b"cmake ['-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX:PATH=/tmp/tritonbuild/tritonserver/install', '-DTRITON_COMMON_REPO_TAG:STRING=r20.12', '-DTRITON_CORE_REPO_TAG:STRING=r20.12', '-DTRITON_BACKEND_REPO_TAG:STRING=r20.12', '-DTRITON_THIRD_PARTY_REPO_TAG:STRING=main', '-DTRITON_ENABLE_LOGGING:BOOL=ON', '-DTR
ITON_ENABLE_STATS:BOOL=ON', '-DTRITON_ENABLE_METRICS:BOOL=ON', '-DTRITON_ENABLE_METRICS_GPU:BOOL=ON', '-DTRITON_ENABLE_TRACING:BOOL=ON', '-DTRITON_ENABLE_GPU:BOOL=ON', '-DTRITON_MIN_COMPUTE_CAPABILITY=6.0', '-DTRITON_ENABLE_GRPC:BOOL=ON', '-DTRITON_ENABLE_HTTP:BOOL=ON', '-DTRITON_ENABLE_GCS:BOOL=ON', '-DTRITON_ENABLE
_S3:BOOL=ON', '-DTRITON_ENABLE_AZURE_STORAGE:BOOL=OFF', '-DTRITON_ENABLE_TENSORFLOW=ON', '-DTRITON_ENABLE_TENSORRT=ON', '-DTRITON_ENABLE_CUSTOM=ON', '-DTRITON_ENABLE_ENSEMBLE=ON', '-DTRITON_ENABLE_ONNXRUNTIME=ON', '-DTRITON_ENABLE_PYTHON=ON', '-DTRITON_ENABLE_DALI=ON', '-DTRITON_ENABLE_PYTORCH=ON', '-DTRITON_EXTRA_LI
B_PATHS=/opt/tritonserver/lib', '/workspace/build']\n"
b'make server\n'
b'error: make server failed\n'
error: tritonserver_builder failed: {'Error': None, 'StatusCode': 1}

3. in src code,

void
HTTPAPIServer::HandleInfer(
    evhtp_request_t* req, const std::string& model_name,
    const std::string& model_version_str)
{
  if (req->method != htp_method_POST) {
    evhtp_send_reply(req, EVHTP_RES_METHNALLOWED);
    return;
  }

  evhtp_headers_add_header(
      req->headers_out,
      evhtp_header_new("Content-Type", "application/json", 1, 1));

  bool connection_paused = false;

  int64_t requested_model_version;
  auto err = GetModelVersionFromString(
      model_version_str.c_str(), &requested_model_version);

  if (err == nullptr) {
    uint32_t txn_flags;
    err = TRITONSERVER_ServerModelTransactionProperties(
        server_.get(), model_name.c_str(), requested_model_version, &txn_flags,
        nullptr /* voidp */);
    if ((err == nullptr) && (txn_flags & TRITONSERVER_TXN_DECOUPLED) != 0) {
      err = TRITONSERVER_ErrorNew(
          TRITONSERVER_ERROR_UNSUPPORTED,
          "HTTP end point doesn't support models with decoupled "
          "transaction policy");
    }
  }

  // If tracing is enabled see if this request should be traced.
  TRITONSERVER_InferenceTrace* trace = nullptr;
#ifdef TRITON_ENABLE_TRACING
  uint64_t trace_id = 0;
  if ((err == nullptr) && (trace_manager_ != nullptr)) {
    trace = trace_manager_->SampleTrace();
    if (trace != nullptr) {
      TRITONSERVER_InferenceTraceId(trace, &trace_id);

      // Timestamps from evhtp are capture in 'req'. We record here
      // since this is the first place where we have access to trace
      // manager.
      trace_manager_->CaptureTimestamp(
          trace_id, TRITONSERVER_TRACE_LEVEL_MIN, "HTTP_RECV_START",
          TIMESPEC_TO_NANOS(req->recv_start_ts));

It seems that "evhtp_request_t* req" has referenced a illegel member.
