### ISSUE TITLE
failed to load model :at least one version must be available under the version policy of model 

### ISSUE THREAD

**Issue by lincong8722** [triton-inference-server/server#3623]
I made such an error when starting the model：
![image](https://user-images.githubusercontent.com/57218642/143586134-b2cddaf1-24a7-4f67-90fa-d5826d1141c2.png)
I defined platform: "ensemble" in pl_video_tag，I don't know where's wrong

**Comment by user473** [comment]
I think if you just create an empty folder '1' in the pl_video_tag folder, it should work

**Comment by lincong8722** [comment]
@user473  oh yeah!Thank u bro!
