### ISSUE TITLE
When I run tritonserver.exe on windows, I encountered the following problems

### ISSUE THREAD

**Issue by 213120632** [triton-inference-server/server#3626]
**Description**
platform: Windows10
NVIDIA Driver 472
CUDA 11.4.2
cuDNN 8.2.4.15
TensorRT 8.0.3.4

**Triton Information**
version: Release 2.16.0 corresponding to NGC container 21.11

Are you using the Triton container or did you build it yourself?
unzip tritonserver2.16.0-win.zip and run bin/tritonserver.exe, no container build

**To Reproduce**
download and unzip tritonserver2.16.0-win.zip, double click bin/tritonserver.exe

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**

error message:
cannot find file: b64.dll, zlib1.dll, re2.dll, pthreadVC3.dll

![image](https://user-images.githubusercontent.com/39933573/143664680-614a4f80-d37f-447f-a186-4efa14b4e9b3.png)
![image](https://user-images.githubusercontent.com/39933573/143664709-48257316-7998-4aaa-9fc2-2eed8cc7fd6b.png)
![image](https://user-images.githubusercontent.com/39933573/143664717-b53572d8-f17a-4c6c-ac4f-424fc26a6f9f.png)
![image](https://user-images.githubusercontent.com/39933573/143664726-37f32146-44ca-4986-b99e-448d9ebbe07c.png)

Thank you

**Comment by GuanLuo** [comment]
Triton depends on a set of external libraries and you need to make sure the libraries are installed on your host machine. See the [Dockerfile](https://github.com/triton-inference-server/server/blob/main/Dockerfile.win10.min#L60-L70) for the dependencies

**Comment by Tabrizian** [comment]
Closing due to in-activity. Feel free to re-open if the issue persists.

**Comment by gp01pw** [comment]
When trying to run tritonserver.exe getting below error.
![image](https://user-images.githubusercontent.com/121614135/211756543-eac1ce98-9ba5-448b-98b4-1324ad1c86b6.png)
