### ISSUE TITLE
Update model

### ISSUE THREAD

**Issue by sunlinlin-aragon** [triton-inference-server/server#3628]
If I have multiple models running at the same time and just want to stop updating and restart one model, what should I do if I don't understand others?

**Comment by CoderHam** [comment]
@sunlinlin-aragon you should use the model control API as described here: https://github.com/triton-inference-server/server/blob/main/docs/model_management.md

**Comment by Sysa** [comment]
document was moved, updated link: https://github.com/triton-inference-server/server/blob/main/docs/user_guide/model_management.md
