### ISSUE TITLE
Will the triton server schedule requests in the queue to GPUs with low memory usage?

### ISSUE THREAD

**Issue by ccnankai** [triton-inference-server/server#3629]
Will the triton server schedule requests in the queue to GPUs with low memory usage? I can't find any instructions.

Which file in the src directory implements this function? I did not find the relevant function module in the file dynamic_batch_scheduler.cc

**Comment by CoderHam** [comment]
@tanmayv25 can you share your guidance here? In my understanding Triton does not balance load based on memory usage, rather balances the load based on availability of model instance on each GPU / distributes the requests evenly across all model instances of a specific model.

**Comment by tanmayv25** [comment]
Yes.. Triton by default distribute to the GPU whichever is available in a greedy fashion. The scheduling logic is available in `dynamic_batch_scheduler.cc` and `rate_limiter.cc`. 

@ccnankai Can you elaborate what you mean by GPU with low memory usage means? Triton doesn't keep track of memory consumption by model on GPUs. We do have a rate limiter implementation to manually attach numbers with named resources to models for cross-model prioritization. https://github.com/triton-inference-server/server/blob/main/docs/rate_limiter.md

**Comment by ccnankai** [comment]
@tanmayv25 
In the rate_limiter configuration, what does the "name" field specifically refer to? Does it refer to a real resource? For example, memory. Or the value of name is set to "R1", "R2" is just a fake resource set, and it is just a randomly named identifier, which is used for scheduling.

**Comment by tanmayv25** [comment]
> @tanmayv25 In the rate_limiter configuration, what does the "name" field specifically refer to? Does it refer to a real resource? For example, memory,cpu,etc. Or the value of name is set to "R1", "R2" is just a fake resource set, and it is just a randomly named identifier, which is used for scheduling.

It is the latter.. That is a fake resource set used just for scheduling purpose. The meaning to name and count is entirely user-given to control the scheduling.

**Comment by ccnankai** [comment]
Now that I understand, I will read the documentation carefully. Thank you very much.
