### ISSUE TITLE
triton with onnx model error when load

### ISSUE THREAD

**Issue by ggslayer** [triton-inference-server/server#3631]
Hi, I'm running triton server 2.15 with my own onnx model on ubuntu20.04, 

I use the command line to auto generate config file: 
docker run  --gpus=all --rm -p8000:8000 -p8001:8001 -p8002:8002 -v /mnt/data/projects/models:/models  tritonserver  tritonserver --model-repository=/models --strict-model-config=false

than server start failed with error:
UNAVAILABLE: Invalid argument: model input cannot have empty reshape for non-batching model for <mymodel name>

I don't know how to reslove this, please give me some explain about the error and help me to run my model succeed.

Thank You!

**Comment by CoderHam** [comment]
@ggslayer can you share your model config for the specific model you are seeing the error for?

**Comment by Tabrizian** [comment]
Closing due to in-activity. Feel free to re-open if the issue persists.
