### ISSUE TITLE
can I specify the log file with auto rolling with file size option when run triton?

### ISSUE THREAD

**Issue by ggslayer** [triton-inference-server/server#3643]
Hi, I'm record triton's log like this:
docker run ....  --log-error=true > ./triton.log & 2>&1

Is there some better way to log to file with auto rolling with file size or time? 
Thank you!

**Comment by dyastremsky** [comment]
That's a good approach. We also have a [logging endpoint](https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/protocol/extension_logging.html), some other command-line options for customizing logging (try checking `tritonserver --help`), [trace logging](https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/user_guide/trace.html), and [Prometheus metrics](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/metrics.md).
