### ISSUE TITLE
error: failed to register input shared memory region: failed to register CUDA shared memory region 'input_data1'

### ISSUE THREAD

**Issue by simon5u** [triton-inference-server/server#3647]
**Description**
Our PC has two GPUs and we use tritonserver 21.02 to host the yolo5 models with cuda shared memory on these two GPUs. 
We run the tritonserver, eveything is working fine and the GPU memory consumption is around 5GB each. Then, we start to run our client code using two processes because we need to support 20 cameras, each process will handle 10 cameras with hardware decoding. We set the CUDA_VISIBLE_DEVICES=0 for the first process, and 1 for the second process. 
We are having the problem "error: failed to register input shared memory region: failed to register CUDA shared memory region 'input_data1'" when we run the second process. We dont have any problem on running the first process. We think that the problem was caused by the cuda shared memory. Any advice on this issue?

**Triton Information**
nvcr.io/nvidia/deepstream:5.1-21.02-triton

Are you using the Triton container or did you build it yourself?
We pull the original docker.

**To Reproduce**
Run the tritonserver to host the yolo5 model with cuda shared memory and using two GPUs.
Then, we run two client processes with CUDA_VISIBLE_DEVICES=0 or 1.
First process is running well with bbox output from yolo5.
Second process will crash and show a log "error: failed to register input shared memory region: failed to register CUDA shared memory region 'input_data1'"

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
Model is yolo5 from https://github.com/ultralytics/yolov5/releases. Input is a 2D image and output is an object bbox.

**Expected behavior**
We are expecting a way to direct the client process to the triton model hosted in a particular gpu.

**Comment by CoderHam** [comment]
@simon5u the issue here might be cause by the usage of CUDA_VISIBLE DEVICES. We will investigate this further but you should not set CUDA_VISIBLE_DEVICES differently for clients and server. 
In this case your client creates the cuda shared memory on GPU1 but tries to register/open it on GPU0 in the server. Instead please set the device id field correctly for create_shared_memory_region
https://github.com/triton-inference-server/client/blob/r21.12/src/python/library/tritonclient/utils/cuda_shared_memory/__init__.py#L97

**Comment by simon5u** [comment]
> In this case your client creates the cuda shared memory on GPU1 but tries to register/open it on GPU0 in the server. Instead please set the device id field correctly for create_shared_memory_region

This is a good suggestion, we will try it and let you know the result soon.

**Comment by CoderHam** [comment]
@simon5u closing the issue since the error was due to incorrect usage of CUDA_VISIBLE_DEVICES
