### ISSUE TITLE
Pose estimation models

### ISSUE THREAD

**Issue by younes-h** [triton-inference-server/server#3648]
**Description**
I have converted openpose from pt to onnx format then it is not being loaded with the load api

**Triton Information**
no version available

Are you using the Triton container

**To Reproduce**
- download openpose model
- add openpose to model repository as required
- run triton server with no model
- load the openpose model

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**
expect normal load of openpose model

**Comment by CoderHam** [comment]
@younes-h we would need a more detailed report including the server logs that show the error and more elaborate repro steps to be able to help you.

**Comment by younes-h** [comment]
@CoderHam  it is ok now
