### ISSUE TITLE
pytorch models not being loaded

### ISSUE THREAD

**Issue by younes-h** [triton-inference-server/server#3649]
**Description**
I am currently working with Pytorch framework and the exported models with the file format .pt or .pth are not being loaded
maybe it is from the pytorch backend ??

**Triton Information**
Triton version is 21.09

I am using the prebuilt Triton container

**To Reproduce**
- put a Pytorch model in the model repository 
- run Triton without models
- load the model 

**Expected behavior**
the model being loaded and we verify that with the index api to get loaded models !!

**Comment by CoderHam** [comment]
@younes-h the model must be a Torchscript model (refer to the docs). Can you share the server log detailing the error?
