### ISSUE TITLE
unexpected platform type python for <model_name>

### ISSUE THREAD

**Issue by vishalsrao** [triton-inference-server/server#3650]
**Description**
I get an error saying:
`Poll failed for model directory 'dummy_ensemble_model': unexpected platform type python for dummy_ensemble_model`
when I try to build an ensemble similar to the async one at https://github.com/triton-inference-server/python_backend/tree/main/examples/bls

Is any special configuration/setup needed for enabling Python backend on Triton Docker containers?

**Triton Information**
Prebuilt Triton docker image with tag 21.11-py3 (nvcr.io/nvidia/tritonserver:21.11-py3)

**Comment by Tabrizian** [comment]
@vishalsrao Can you share your model configuration?

You need to use 'backend: "python"' in your model.

**Comment by vishalsrao** [comment]
Thanks, @Tabrizian. I had used platform instead of backend.
