### ISSUE TITLE
[QUESTION] grpc_server.cpp ModelInferHandler::Process the same Request instance for different correlation_id

### ISSUE THREAD

**Issue by konstantin-sancom** [triton-inference-server/server#3652]
Hi!

In file `grpc_server.cpp` at method `ModelInferHandler::Process`

there is code near `} else if (state->step_ == Steps::READ) {` 

I added debug output:

`    TRITONSERVER_Error* err = nullptr;`
`    const inference::ModelInferRequest& request = state->request_;`
`    LOG_VERBOSE(1) << "Process READ for " << Name() << ", state_id "`
`                 << state->unique_id_ << ", request_addr " << std::addressof(state->request_) << ", request " << request.id();`

and I see in out such strings:

`Dec 03 13:42:58 ub2004.private tritonserver[300604]: I1203 13:42:58.092498 300604 grpc_server.cc:3532] New request handler for ModelStreamInferHandler, state_id 3, request_addr 0x7fcd14001920`
`Dec 03 13:42:58 ub2004.private tritonserver[300604]: I1203 13:42:58.102018 300604 grpc_server.cc:3538] Process READ for ModelStreamInferHandler, state_id 3, request_addr 0x7fcd14001920, request 1_0_1_0`
`Dec 03 13:42:58 ub2004.private tritonserver[300604]: I1203 13:42:58.217927 300604 grpc_server.cc:3855] Process for ModelStreamInferHandler, rpc_ok=1, context 2, 3 step WRITEREADY is NOT complete. , request_addr 0x7fcd14001920, request 1_0_1_0`
`Dec 03 13:42:58 ub2004.private tritonserver[300604]: I1203 13:42:58.217935 300604 grpc_server.cc:3866] Process for ModelStreamInferHandler, rpc_ok=1, context 2, 3 step WRITEREADY set state to outgoing write. , request_addr 0x7fcd14001920, request 1_0_1_0`
`Dec 03 13:42:58 ub2004.private tritonserver[300604]: I1203 13:42:58.596181 300604 grpc_server.cc:3538] Process READ for ModelStreamInferHandler, state_id 385, request_addr 0x7fcd14001920, request 172_1671_0_0`

Explanaition:

`1_0_1_0` means corr_id=1, request_sequtial_id(autoincrement)=0,  START=1, END=0
`172_1671_0_0` means corr_id=172, request_sequtial_id(autoincrement)=167,  START=1, END=0

`request_addr ` is `std::addressof(state->request_)`

So, how is it possible, that for different utterances in one batch there is one `state->request_`, that is used?

**Comment by tanmayv25** [comment]
This is a part of the optimization coming from protobuf message memory reuse. The `request_` is part of `InferHandlerState` and the state objects are kept in a bucket. See [here](https://github.com/triton-inference-server/server/blob/main/src/servers/grpc_server.cc#L2093-L2115) for the logic how during StateNew, the previously created state objects are reused instead of creating new object.

**Comment by konstantin-sancom** [comment]
> This is a part of the optimization coming from protobuf message memory reuse. The `request_` is part of `InferHandlerState` and the state objects are kept in a bucket. See [here](https://github.com/triton-inference-server/server/blob/main/src/servers/grpc_server.cc#L2093-L2115) for the logic how during StateNew, the previously created state objects are reused instead of creating new object.

Hi, @tanmayv25 , thenk you for explanation.

Could you tell me. Is there a way to enusure, that all "chunk", sent by the CLIENT are accepted and PROCEEDED by SERVER?
We supose, thet it is not working as expected in `r21.05`.(We use `r21.05` as a lates version, that supports `Kaldi Backend`)

**Comment by tanmayv25** [comment]
This appears to be a bug in triton then. All requests forwarded from client should be received by Triton. @GuanLuo Is this similar to what you were working on last week?

**Comment by tanmayv25** [comment]
@konstantin-sancom  I would suggest using grpc logging to understand the state of requests that were not received in `cq->Next()`. See [here ](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for more information.

**Comment by konstantin-sancom** [comment]
We also see in our logs following lines for "frezed" sequences(items in batch, client have sent):
`I1208 13:46:31.280812 724 sequence_batch_scheduler.cc:603] Reaper: corr_id 91: max sequence idle exceeded`
`I1208 13:46:31.280854 724 sequence_batch_scheduler.cc:630] Reaper: ignoring stale idle corr_id 91`

**Comment by konstantin-sancom** [comment]
Full example of such behaviour:

`// Here we deliver response (but client does not receive it)`
`I1208 15:16:57.332778 1412 triton-kaldi-backend.cc:998] ModelInstanceState::DeliverResponse:  (corr_id 277)`

`// Here a timeout triggers a sequence in stale status`
`I1208 15:33:19.087420 1412 sequence_batch_scheduler.cc:603] Reaper: corr_id 277: max sequence idle exceeded`
`I1208 15:33:19.087522 1412 sequence_batch_scheduler.cc:630] Reaper: ignoring stale idle corr_id 277`

**Comment by tanmayv25** [comment]
Were there any other responses being sent to client at the same time? The [DecoupledWriteResponse ](https://github.com/triton-inference-server/server/blob/main/src/servers/grpc_server.cc#L1839) is invoked that writes the response back to the stream.

>We also see in our logs following lines for "frezed" sequences(items in batch, client have sent):
Did you mark the last request in the sequence 91 with END flag? Was that request received by the server?

**Comment by konstantin-sancom** [comment]
> > // Here we deliver response (but client does not receive it)
> 
> Were there any other responses being sent to client at the same time? The [DecoupledWriteResponse ](https://github.com/triton-inference-server/server/blob/main/src/servers/grpc_server.cc#L1839) is invoked that writes the response back to the stream. But being asynchronous the response will be written once at a time.. Was the server being loaded with lots of requests? Do you see the same issue when running requests for single sequence at a time.

There are multiple requests. At the client side we use following alorithm to send a "batch" of WAV files:
1. We set a `corr_id` for each WAV file.
2. We split each WAV file into `chunks`. The first `chunk` are marked with `flags` as: `START: 1`, `END: 0`. Middle `chunks` are marked as: `SATRT: 0`, `END: 0`. The last `chunk` is marked as: `START: 0`, `END: 1`.
3. `Chunks` from all `WAV` files are sent in loops: all first `chunks` are sent, then all second `chunks`(if present) are sent and so on...
4. For debug purposes request IDs(strings) are composed from: `corr_id`, global incremental `sequence id` and `START/END flags `. For example: `2_300_1_0` corr_id=1, global_sequence=300, start=1, end=0

> 
> > We also see in our logs following lines for "frezed" sequences(items in batch, client have sent):
> 
> Did you mark the last request in the sequence 91 with END flag? Was that request received by the server?

Yes. We set `END` mark and I see in logs, that server received this chunk.

**Comment by konstantin-sancom** [comment]
### Additional information.

We turned ON a GRPC DEBUG and traces, in some moment we see last SERVER SEND log records and then thre is no any GRPC network ativity present.

`I1209 07:40:32.820191738   10525 call.cc:1964]               grpc_call_start_batch(call=0x7f06e6f615a0, ops=0x7f1ed37f4f20, nops=2, tag=0x7f03ea57c138, reserved=(nil))`
`E1209 07:40:32.820210239   10525 cpu_linux.cc:75]            Cannot handle hot-plugged CPUs`
`I1209 07:40:32.820226049   10525 call.cc:1566]               ops[0]: SEND_INITIAL_METADATA(nil)`
`I1209 07:40:32.820241920   10525 call.cc:1566]               ops[1]: SEND_MESSAGE ptr=0x7f03c83bcc60`
`I1209 07:40:32.820297671   10525 tcp_posix.cc:1062]          WRITE 0x7f1ec8431540 (peer=ipv4:192.168.0.167:41970)`
`D1209 07:40:32.820327552   10525 tcp_posix.cc:1066]          DATA: 00 00 04 08 00 00 00 02 1f 00 00 00 05 '.............'`
`I1209 07:40:32.820345412   10525 tcp_posix.cc:1062]          WRITE 0x7f1ec8431540 (peer=ipv4:192.168.0.167:41970)`
`D1209 07:40:32.820362683   10525 tcp_posix.cc:1066]          DATA: 00 00 04 01 04 00 00 02 57 88 c0 bf be 00 00 04 08 00 00 00 00 00 00 '........W..............'`
`I1209 07:40:32.820378093   10525 tcp_posix.cc:1062]          WRITE 0x7f1ec8431540 (peer=ipv4:192.168.0.167:41970)`
`D1209 07:40:32.820393814   10525 tcp_posix.cc:1066]          DATA: 00 00 05 '...'`
`I1209 07:40:32.820473685   10525 tcp_posix.cc:1100]          write: "No Error"`
`I1209 07:40:32.820494086   10525 completion_queue.cc:952]    grpc_completion_queue_next(cq=0x55b20291a570, deadline=gpr_timespec { tv_sec: 9223372036854775807, tv_nsec: 0, clock_type: 1 }, reserved
=(nil))`
`I1209 07:40:32.820526417   10525 completion_queue.cc:1061]   RETURN_EVENT[0x55b20291a570]: OP_COMPLETE: tag:0x7f06e6737fe0 OK`

**Comment by konstantin-sancom** [comment]
Should `correlation_id` be totally unique during TritonServer process lifetime or could we reuse it if sequence was already finished?
In other words: how much `unique` should `correlation_id` value be?

**Comment by tanmayv25** [comment]
>Should correlation_id be totally unique during TritonServer process lifetime or could we reuse it if sequence was already finished?

The correlation_id can be reused once the sequence using it earlier is already finished.

**Comment by konstantin-sancom** [comment]
### UPDATE

We tested on releases from `r20.12` to `r21.05` - the same behaviuor is present: Triton freeze on 3rd batch with 300 utterances.
`Freezing` means that Triton does not send Final Responses(with lattice) to client.

**Comment by konstantin-sancom** [comment]
> > // Here we deliver response (but client does not receive it)
> 
> Were there any other responses being sent to client at the same time? The [DecoupledWriteResponse ](https://github.com/triton-inference-server/server/blob/main/src/servers/grpc_server.cc#L1839) is invoked that writes the response back to the stream. But being asynchronous the response will be written once at a time.. Was the server being loaded with lots of requests? Do you see the same issue when running requests for single sequence at a time.
> 
> > We also see in our logs following lines for "frezed" sequences(items in batch, client have sent):
> 
> Did you mark the last request in the sequence 91 with END flag? Was that request received by the server?

> Do you see the same issue when running requests for single sequence at a time.

We have single `session` if we are taking about GRPC client to server connection(TCP connection).
Inside of this single connection there are multiple request for 300 diffrent utterances(corr_ids)

**Comment by tanmayv25** [comment]
@konstantin-sancom  Can you please open a GH issue with the instructions to reproduce the bug? We will investigate furhter. 
There hasn't been any major modification in gRPC server/client implementation for a while so I don't think any of the older versions you tried should fix the problem.

**Comment by konstantin-sancom** [comment]
> @konstantin-sancom Can you please open a GH issue with the instructions to reproduce the bug? We will investigate furhter. There hasn't been any major modification in gRPC server/client implementation for a while so I don't think any of the older versions you tried should fix the problem.

New issue(`BUG`) opened:
https://github.com/triton-inference-server/server/issues/3694

**Comment by AlbertZheng** [comment]
> > // Here we deliver response (but client does not receive it)
> 
> Were there any other responses being sent to client at the same time? The [DecoupledWriteResponse ](https://github.com/triton-inference-server/server/blob/main/src/servers/grpc_server.cc#L1839) is invoked that writes the response back to the stream. But being asynchronous the response will be written once at a time.. Was the server being loaded with lots of requests? Do you see the same issue when running requests for single sequence at a time.
> 
> > We also see in our logs following lines for "frezed" sequences(items in batch, client have sent):
> 
> Did you mark the last request in the sequence 91 with END flag? Was that request received by the server?

> // Here a timeout triggers a sequence in stale status
> I1208 15:33:19.087420 1412 sequence_batch_scheduler.cc:603] Reaper: corr_id 277: max sequence idle exceeded
> I1208 15:33:19.087522 1412 sequence_batch_scheduler.cc:630] Reaper: ignoring stale idle corr_id 277

@tanmayv25 One more question: if a idle timeout triggered a sequence in stale status, will the tritonserver automatically send a END flag to the corresponding backend? if not, how can the backend know when it will need to release its session resource for this idle sequence? As you know, if the user CTRL+C or kills the client, the tritonserver & the backend will never receive END flag from client and the corresponding sequence will become be resource leaking after the max sequence idle exceeded.

**Comment by tanmayv25** [comment]
@AlbertZheng  Triton does not send a request with END flag upon idle timeout. The solution can be to have your own reaping thread in the backend that releases the resources for sequences that have timed out. The backend would not see the requests for these sequence.

**Comment by AlbertZheng** [comment]
> @AlbertZheng Triton does not send a request with END flag upon idle timeout. The solution can be to have your own reaping thread in the backend that releases the resources for sequences that have timed out (not active). The backend would not see the requests for these sequence. Something similar to what we do in our sequence_batch_scheduler.cc.

@tanmayv25 Thanks for reply. Since the sequence_batch_scheduler has implemented the detection of idle timeout, is it possible to add an enhancement design and mechanism  in sequence_batch_scheduler to notify the backend when the timeout is detected? so that the idle timeout control and related timeout config parameters in the backend can be synchronized with the sequence_batch_scheduler.

**Comment by tanmayv25** [comment]
I think we can add an API which backend can optionally implement. The function will then be invoked by the server when it times out a sequence.

@AlbertZheng  Can you open a new GH issue and describe your use-case. We will prioritize the enhancement.
