### ISSUE TITLE
How to get requests headers in the backend

### ISSUE THREAD

**Issue by lbhli** [triton-inference-server/server#3658]
I created my own triton backend, and it works well. And I'd like to send infer requests with some information through headers,  and my question is how to get these header in my own backend, I didn't find any api can do that.

Such as the header will be send as the following code snippet in example [grpc_client.py](https://github.com/triton-inference-server/client/blob/main/src/python/examples/grpc_client.py)
`   # Test with outputs`
`   results = triton_client.infer(`  
`          model_name=model_name,`  
`          inputs=inputs,`  
`          outputs=outputs,`  
`          client_timeout=FLAGS.client_timeout,`  
`          headers={'test':** '1'},`  
`          compression_algorithm=FLAGS.grpc_compression_algorithm)`  

In this example, this infer send a header "{'test': '1'}",

**Comment by tanmayv25** [comment]
Triton does not support sending headers to the backend.  When triton is running under a cloud deployment framework like kubeflow, certain headers are required for correctly passing the tokens and routing the request packets. We only support attaching headers with request for that purposes. Triton doesn't parse or consume these headers.

Why do you need to pass information to your backend as headers? Why not add an input to your model instead?

**Comment by lbhli** [comment]
> Triton does not support sending headers to the backend. When triton is running under a cloud deployment framework like kubeflow, certain headers may be required for correctly passing the tokens and routing the request packets. We only support attaching headers with request for that purposes. Triton doesn't parse or consume these headers.
> 
> Why do you need to pass information to your backend as headers? Why not add an input to your model/backend instead?

Thank you for your reply.
Yes, I can add an other input to pass some values. I just want to know whether there has any other method that can pass some extra values.  Those values are not needed by the model but related to the logic.

**Comment by tanmayv25** [comment]
We don't have any other way currently to provide data to backends. If these values need to be provided just at the load time then you can use model parameters field in config.pbtxt. See here for more information: https://github.com/triton-inference-server/common/blob/main/protobuf/model_config.proto#L1836

If you want to provide values in real time you would need to add that as an input and pass only the subset to model and treat others for your logic.

**Comment by lbhli** [comment]
OK. Thanks. 
I will close this issue.
