### ISSUE TITLE
About the Model Warmup part of the document

### ISSUE THREAD

**Issue by zijin520** [triton-inference-server/server#3681]
**Description**
In the Model Warmup part, it is said that `For some backends, some or all of this initialization is deferred until the model receives its first inference request (or first few inference requests). `. Could you please tell me which backends? In addition, it is better to give the some warmup configuration examples there. Thanks.

**Triton Information**
r21.09
Triton container

**To Reproduce**

**Expected behavior**

**Comment by tanmayv25** [comment]
@zijin520 Some optimizations like [onnx-trt](https://github.com/triton-inference-server/server/blob/main/docs/optimization.md#onnx-with-tensorrt-optimization) and [tf-trt](https://github.com/triton-inference-server/server/blob/main/docs/optimization.md#tensorflow-with-tensorrt-optimization) defers the actual conversion of graph to optimized graph with TensorRTEngineOps till it receives the first inference requests. You can probably see some logs on the server when that happens. These are only few examples. Depending upon the framework, first few inference runs can be slower hence we have model warmups. 

Please see the detailed documentation of ModelWarmup configuration options here: https://github.com/triton-inference-server/common/blob/main/protobuf/model_config.proto#L1504

This test.sh file gives examples of various warmup settings that we support: https://github.com/triton-inference-server/server/blob/main/qa/L0_warmup/test.sh#L73
