### ISSUE TITLE
JetPack 4.6 do not support pytorch?

### ISSUE THREAD

**Issue by zhangkom** [triton-inference-server/server#3683]
Hello, does the Jetpack support pytorch? I read the doc of the git, as following:

Jetson Jetpack Support
A release of Triton for JetPack 4.6 (https://developer.nvidia.com/embedded/jetpack) is provided in the attached tar file: tritonserver2.16.0-jetpack4.6.tgz.

This release supports the TensorFlow 2.6.0, TensorFlow 1.15.5, TensorRT 8.0.1.6, OnnxRuntime 1.8.1 and as well as ensembles.

**Comment by tanmayv25** [comment]
Support for pytorch is not available in 2.16.0 release. It should be available in 2.18.0 release.
