### ISSUE TITLE
docker: Command not found in build server with backend

### ISSUE THREAD

**Issue by zhangkom** [triton-inference-server/server#3685]
root@docker-desktop:/code/server# pip install docker
Requirement already satisfied: docker in /usr/local/lib/python3.8/dist-packages (5.0.3)
Requirement already satisfied: websocket-client>=0.32.0 in /usr/local/lib/python3.8/dist-packages (from docker) (1.2.3)
Requirement already satisfied: requests!=2.18.0,>=2.14.2 in /usr/lib/python3/dist-packages (from docker) (2.22.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

./build.py --cmake-dir=/code/server/build --build-dir=/tmp/citritonbuild --enable-logging --enable-stats --enable-tracing --enable-metrics --enable-gpu-metrics --enable-gpu --endpoint=http --endpoint=grpc --repo-tag=common:r21.11 --repo-tag=core:r21.11 --repo-tag=backend:r21.11 --repo-tag=thirdparty:r21.11 --backend=onnxruntime:r21.11 --backend=pytorch:r21.11 --backend=tensorflow1:r21.11 --backend=tensorflow2:r21.11   --no-container-build --build-type=Debug

[ 93%] Completed 'server'
/code/cmake-3.21.4-linux-x86_64/bin/cmake -E make_directory /tmp/citritonbuild/tritonserver/build/CMakeFiles
/code/cmake-3.21.4-linux-x86_64/bin/cmake -E touch /tmp/citritonbuild/tritonserver/build/CMakeFiles/server-complete
/code/cmake-3.21.4-linux-x86_64/bin/cmake -E touch /tmp/citritonbuild/tritonserver/build/server/src/server-stamp/server-done
make[3]: Leaving directory '/tmp/citritonbuild/tritonserver/build'
[100%] Built target server
make[2]: Leaving directory '/tmp/citritonbuild/tritonserver/build'
/code/cmake-3.21.4-linux-x86_64/bin/cmake -E cmake_progress_start /tmp/citritonbuild/tritonserver/build/CMakeFiles 0
make[1]: Leaving directory '/tmp/citritonbuild/tritonserver/build'
Cloning into 'onnxruntime'...
[ 52%] Linking CXX static library libkernel-library-new.a
cd /tmp/citritonbuild/onnxruntime/build/_deps/repo-backend-build && /code/cmake-3.21.4-linux-x86_64/bin/cmake -P CMakeFiles/kernel-library-new.dir/cmake_clean_target.cmake
cd /tmp/citritonbuild/onnxruntime/build/_deps/repo-backend-build && /code/cmake-3.21.4-linux-x86_64/bin/cmake -E cmake_link_script CMakeFiles/kernel-library-new.dir/link.txt --verbose=0
make[2]: Leaving directory '/tmp/citritonbuild/onnxruntime/build'

[  8%] Building ONNX Runtime

common-error.dir/src/error.cc.o -c /tmp/citritonbuild/onnxruntime/build/_deps/repo-common-src/src/error.cc
docker build --cache-from=tritonserver_onnxruntime --cache-from=tritonserver_onnxruntime_cache0 --cache-from=tritonserver_onnxruntime_cache1 -t tritonserver_onnxruntime -f ./Dockerfile.ort /tmp/citritonbuild/onnxruntime
make[2]: docker: Command not found
make[2]: *** [CMakeFiles/ort_target.dir/build.make:74: onnxruntime/lib/libonnxruntime.so.1.9.0] Error 127
make[2]: Leaving directory '/tmp/citritonbuild/onnxruntime/build'
make[1]: *** [CMakeFiles/Makefile2:173: CMakeFiles/ort_target.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 34%] Linking CXX shared library libtritonserver_stub.so
cd /tmp/citritonbuild/onnxruntime/build/_deps/repo-core-build && /code/cmake-3.21.4-linux-x86_64/bin/cmake -E cmake_link_script CMakeFiles/triton-core-serverstub.dir/link.txt --verbose=0
make[2]: Leaving directory '/tmp/citritonbuild/onnxruntime/build'

**Comment by tanmayv25** [comment]
@CoderHam We do use `--no-container-build`. Do you have any insight why the user is seeing this error?

**Comment by GuanLuo** [comment]
Note that the ORT backend actually use `docker` to fulfill its ORT dependency unless you [specify where to find ORT](https://github.com/triton-inference-server/onnxruntime_backend/blob/main/CMakeLists.txt#L124-L127).

This is mentioned in the [build without docker doc](https://github.com/triton-inference-server/server/blob/main/docs/build.md#building-without-docker):
> Fetch each requested backend and build it using the CMake file from the corresponding backend repo. For example, the ONNX Runtime backend is built using triton-inference-server/onnxruntime_backend/CMakeLists.txt. Some of the backends may use Docker as part of their build (for example ONNX Runtime and OpenVINO). If you don't want to use Docker in those cases you must consult the build process for those backends.

**Comment by GuanLuo** [comment]
I noticed that you installed `docker` via `pip`, however, the `build.py` and other CMake build in other backends invoke `docker` directly, and I don't think installing docker via pip actually fulfills this dependency. Are you able to run `docker` in a terminal directly?

**Comment by CoderHam** [comment]
> @CoderHam We do use `--no-container-build` on jetson. Do you have any insight why the user is seeing this error?

Yes that is correct. But the --no-container-build on jetson differs in the sense that we do not even use dockers to build the backends. When the user uses no container build we do not build inside a docker container but we do use containers for the build.

Failure as @GuanLuo mentioned is to due to missing docker deps that has not yet been installed.

**Comment by zhangkom** [comment]
@GuanLuo @CoderHam  Thank you for the answer. 
    And when I run "docker", it will show "bash: docker: command not found" in the container of "nvcr.io/nvidia/tritonserver:21.11-py3". How can I do, I have apt install docker as following:

root@docker-desktop:/code/server# apt install docker
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  wmdocker
The following NEW packages will be installed:
  docker wmdocker
0 upgraded, 2 newly installed, 0 to remove and 61 not upgraded.
Need to get 13.0 kB/14.3 kB of archives.
After this operation, 58.4 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://archive.ubuntu.com/ubuntu focal/universe amd64 wmdocker amd64 1.5-2 [13.0 kB]
Fetched 13.0 kB in 1s (23.3 kB/s)   
Selecting previously unselected package wmdocker.
(Reading database ... 43574 files and directories currently installed.)
Preparing to unpack .../wmdocker_1.5-2_amd64.deb ...
Unpacking wmdocker (1.5-2) ...
Selecting previously unselected package docker.
Preparing to unpack .../archives/docker_1.5-2_all.deb ...
Unpacking docker (1.5-2) ...
Setting up wmdocker (1.5-2) ...
Setting up docker (1.5-2) ...
root@docker-desktop:/code/server# docker
bash: docker: command not found

**Comment by zhangkom** [comment]
I have install docker successfully by apt-get install docker.io, and when I run build.py, there are errors come:

./build.py --cmake-dir=/code/server/build --build-dir=/tmp/citritonbuild --enable-logging --enable-stats --enable-tracing --enable-metrics --enable-gpu-metrics --enable-gpu --endpoint=http --endpoint=grpc --repo-tag=common:r21.11 --repo-tag=core:r21.11 --repo-tag=backend:r21.11 --repo-tag=thirdparty:r21.11 --backend=onnxruntime:r21.11 --backend=pytorch:r21.11 --backend=tensorflow1:r21.11 --backend=tensorflow2:r21.11 --no-container-build --build-type=Debug


cd /tmp/citritonbuild/tritonserver/build/server && /code/cmake-3.21.4-linux-x86_64/bin/cmake -E touch /tmp/citritonbuild/tritonserver/build/server/src/server-stamp/server-install
[ 93%] Completed 'server'
/code/cmake-3.21.4-linux-x86_64/bin/cmake -E make_directory /tmp/citritonbuild/tritonserver/build/CMakeFiles
/code/cmake-3.21.4-linux-x86_64/bin/cmake -E touch /tmp/citritonbuild/tritonserver/build/CMakeFiles/server-complete
/code/cmake-3.21.4-linux-x86_64/bin/cmake -E touch /tmp/citritonbuild/tritonserver/build/server/src/server-stamp/server-done
make[3]: Leaving directory '/tmp/citritonbuild/tritonserver/build'
[100%] Built target server
make[2]: Leaving directory '/tmp/citritonbuild/tritonserver/build'
/code/cmake-3.21.4-linux-x86_64/bin/cmake -E cmake_progress_start /tmp/citritonbuild/tritonserver/build/CMakeFiles 0
make[1]: Leaving directory '/tmp/citritonbuild/tritonserver/build'
Cloning into 'onnxruntime'...
remote: Enumerating objects: 25, done.
remote: Counting objects: 100% (25/25), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 25 (delta 5), reused 15 (delta 0), pack-reused 0
Unpacking objects: 100% (25/25), 47.57 KiB | 705.00 KiB/s, done.
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using Onnxruntime docker: ON
-- RapidJSON found. Headers: /usr/include
-- RapidJSON found. Headers: /usr/include
-- Found CUDAToolkit: /usr/local/cuda/include (found version "11.5.50") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "11.5") 
-- Using CUDA 11.5
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/citritonbuild/onnxruntime/build
/code/cmake-3.21.4-linux-x86_64/bin/cmake -S/tmp/citritonbuild/onnxruntime -B/tmp/citritonbuild/onnxruntime/build --check-build-system CMakeFiles/Makefile.cmake 0
/code/cmake-3.21.4-linux-x86_64/bin/cmake -E cmake_progress_start /tmp/citritonbuild/onnxruntime/build/CMakeFiles /tmp/citritonbuild/onnxruntime/build//CMakeFiles/progress.marks
make  -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/tmp/citritonbuild/onnxruntime/build'
make  -f _deps/repo-backend-build/CMakeFiles/kernel-library-new.dir/build.make _deps/repo-backend-build/CMakeFiles/kernel-library-new.dir/depend
make  -f CMakeFiles/ort_target.dir/build.make CMakeFiles/ort_target.dir/depend
make  -f _deps/repo-common-build/CMakeFiles/triton-common-async-work-queue.dir/build.make _deps/repo-common-build/CMakeFiles/triton-common-async-work-queue.dir/depend
make[2]: Entering directory '/tmp/citritonbuild/onnxruntime/build'
make  -f _deps/repo-core-build/CMakeFiles/triton-core-serverstub.dir/build.make _deps/repo-core-build/CMakeFiles/triton-core-serverstub.dir/depend
make[2]: Entering directory '/tmp/citritonbuild/onnxruntime/build'
cd /tmp/citritonbuild/onnxruntime/build && /code/cmake-3.21.4-linux-x86_64/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/citritonbuild/onnxruntime /tmp/citritonbuild/onnxruntime /tmp/citritonbuild/onnxruntime/build /tmp/citritonbuild/onnxruntime/build /tmp/citritonbuild/onnxruntime/build/CMakeFiles/ort_target.dir/DependInfo.cmake --color=
make[2]: Entering directory '/tmp/citritonbuild/onnxruntime/build'
cd /tmp/citritonbuild/onnxruntime/build && /code/cmake-3.21.4-linux-x86_64/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/citritonbuild/onnxruntime /tmp/citritonbuild/onnxruntime/build/_deps/repo-common-src /tmp/citritonbuild/onnxruntime/build /tmp/citritonbuild/onnxruntime/build/_deps/repo-common-build /tmp/citritonbuild/onnxruntime/build/_deps/repo-common-build/CMakeFiles/triton-common-async-work-queue.dir/DependInfo.cmake --color=
make  -f _deps/repo-common-build/CMakeFiles/triton-common-error.dir/build.make _deps/repo-common-build/CMakeFiles/triton-common-error.dir/depend
make  -f _deps/repo-common-build/CMakeFiles/triton-common-table-printer.dir/build.make _deps/repo-common-build/CMakeFiles/triton-common-table-printer.dir/depend
make[2]: Entering directory '/tmp/citritonbuild/onnxruntime/build'
cd /tmp/citritonbuild/onnxruntime/build && /code/cmake-3.21.4-linux-x86_64/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/citritonbuild/onnxruntime /tmp/citritonbuild/onnxruntime/build/_deps/repo-core-src /tmp/citritonbuild/onnxruntime/build /tmp/citritonbuild/onnxruntime/build/_deps/repo-core-build /tmp/citritonbuild/onnxruntime/build/_deps/repo-core-build/CMakeFiles/triton-core-serverstub.dir/DependInfo.cmake --color=
make[2]: Entering directory '/tmp/citritonbuild/onnxruntime/build'
cd /tmp/citritonbuild/onnxruntime/build && /code/cmake-3.21.4-linux-x86_64/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/citritonbuild/onnxruntime /tmp/citritonbuild/onnxruntime/build/_deps/repo-common-src /tmp/citritonbuild/onnxruntime/build /tmp/citritonbuild/onnxruntime/build/_deps/repo-common-build /tmp/citritonbuild/onnxruntime/build/_deps/repo-common-build/CMakeFiles/triton-common-error.dir/DependInfo.cmake --color=
make[2]: Entering directory '/tmp/citritonbuild/onnxruntime/build'
cd /tmp/citritonbuild/onnxruntime/build && /code/cmake-3.21.4-linux-x86_64/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/citritonbuild/onnxruntime /tmp/citritonbuild/onnxruntime/build/_deps/repo-common-src /tmp/citritonbuild/onnxruntime/build /tmp/citritonbuild/onnxruntime/build/_deps/repo-common-build /tmp/citritonbuild/onnxruntime/build/_deps/repo-common-build/CMakeFiles/triton-common-table-printer.dir/DependInfo.cmake --color=
[  4%] Building NVCC (Device) object _deps/repo-backend-build/CMakeFiles/kernel-library-new.dir/src/kernel-library-new_generated_kernel.cu.o
cd /tmp/citritonbuild/onnxruntime/build/_deps/repo-backend-build/CMakeFiles/kernel-library-new.dir/src && /code/cmake-3.21.4-linux-x86_64/bin/cmake -E make_directory /tmp/citritonbuild/onnxruntime/build/_deps/repo-backend-build/CMakeFiles/kernel-library-new.dir/src/.
make[2]: Leaving directory '/tmp/citritonbuild/onnxruntime/build'
make  -f _deps/repo-core-build/CMakeFiles/triton-core-serverstub.dir/build.make _deps/repo-core-build/CMakeFiles/triton-core-serverstub.dir/build
make[2]: Leaving directory '/tmp/citritonbuild/onnxruntime/build'
make  -f CMakeFiles/ort_target.dir/build.make CMakeFiles/ort_target.dir/build
make[2]: Leaving directory '/tmp/citritonbuild/onnxruntime/build'
make[2]: Entering directory '/tmp/citritonbuild/onnxruntime/build'
make  -f _deps/repo-common-build/CMakeFiles/triton-common-async-work-queue.dir/build.make _deps/repo-common-build/CMakeFiles/triton-common-async-work-queue.dir/build
make[2]: Leaving directory '/tmp/citritonbuild/onnxruntime/build'
make[2]: Entering directory '/tmp/citritonbuild/onnxruntime/build'
make  -f _deps/repo-common-build/CMakeFiles/triton-common-error.dir/build.make _deps/repo-common-build/CMakeFiles/triton-common-error.dir/build
make[2]: Entering directory '/tmp/citritonbuild/onnxruntime/build'
make[2]: Leaving directory '/tmp/citritonbuild/onnxruntime/build'
make  -f _deps/repo-common-build/CMakeFiles/triton-common-table-printer.dir/build.make _deps/repo-common-build/CMakeFiles/triton-common-table-printer.dir/build
make[2]: Entering directory '/tmp/citritonbuild/onnxruntime/build'
make[2]: Entering directory '/tmp/citritonbuild/onnxruntime/build'
cd /tmp/citritonbuild/onnxruntime/build/_deps/repo-backend-build/CMakeFiles/kernel-library-new.dir/src && /code/cmake-3.21.4-linux-x86_64/bin/cmake -D verbose:BOOL=0 -D build_configuration:STRING=Debug -D generated_file:STRING=/tmp/citritonbuild/onnxruntime/build/_deps/repo-backend-build/CMakeFiles/kernel-library-new.dir/src/./kernel-library-new_generated_kernel.cu.o -D generated_cubin_file:STRING=/tmp/citritonbuild/onnxruntime/build/_deps/repo-backend-build/CMakeFiles/kernel-library-new.dir/src/./kernel-library-new_generated_kernel.cu.o.cubin.txt -P /tmp/citritonbuild/onnxruntime/build/_deps/repo-backend-build/CMakeFiles/kernel-library-new.dir/src/kernel-library-new_generated_kernel.cu.o.Debug.cmake
[  8%] Building CXX object _deps/repo-core-build/CMakeFiles/triton-core-serverstub.dir/src/tritonserver_stub.cc.o
cd /tmp/citritonbuild/onnxruntime/build/_deps/repo-core-build && /usr/bin/c++ -Dtriton_core_serverstub_EXPORTS  -g -fPIC -Wall -Wextra -Wno-unused-parameter -Werror -MD -MT _deps/repo-core-build/CMakeFiles/triton-core-serverstub.dir/src/tritonserver_stub.cc.o -MF CMakeFiles/triton-core-serverstub.dir/src/tritonserver_stub.cc.o.d -o CMakeFiles/triton-core-serverstub.dir/src/tritonserver_stub.cc.o -c /tmp/citritonbuild/onnxruntime/build/_deps/repo-core-src/src/tritonserver_stub.cc
[ 13%] Building ONNX Runtime

**Comment by zhangkom** [comment]
@CoderHam @GuanLuo @tanmayv25 Whould you please help me to resolve this?
I want compile own server on my macbook, the server will run on the nvidia GPU. So I use following instrics to build:

git clone https://github.com/triton-inference-server/server
git checkout r21.11
docker pull nvcr.io/nvidia/tritonserver:21.11-py3
docker run --gpus=all --network=host --shm-size=2g -v/triton_server:/code  -it nvcr.io/nvidia/tritonserver:21.11-py3
pip install docker
apt update
apt install libssl-dev libonig-dev zlib1g-dev libboost-all-dev libre2-dev libb64-dev rapidjson-dev -y

export PATH=/code/cmake-3.21.4-linux-x86_64/bin/:$PATH
./build.py --cmake-dir=/code/server/build --build-dir=/tmp/citritonbuild --enable-logging --enable-stats --enable-tracing --enable-metrics --enable-gpu-metrics --enable-gpu --endpoint=http --endpoint=grpc --repo-tag=common:r21.11 --repo-tag=core:r21.11 --repo-tag=backend:r21.11 --repo-tag=thirdparty:r21.11 --backend=onnxruntime:r21.11 --backend=pytorch:r21.11 --backend=tensorflow1:r21.11 --backend=tensorflow2:r21.11   --no-container-build --build-type=Debug

and I receive the error above, how can I do?

**Comment by Tabrizian** [comment]
I think you need to mount the docker socket inside container.

docker run --gpus=all --network=host --shm-size=2g -v /var/run/docker.sock:/var/run/docker.sock -v/triton_server:/code -it nvcr.io/nvidia/tritonserver:21.11-py

**Comment by zhangkom** [comment]
@Tabrizian thanks a lot, the error is resolved, and triton-onnxruntime-backend was built successfully, but another error come as following: 

./build.py --cmake-dir=/code/server/build --build-dir=/tmp/citritonbuild --enable-logging --enable-stats --enable-tracing --enable-metrics --enable-gpu-metrics --enable-gpu --endpoint=http --endpoint=grpc --repo-tag=common:r21.11 --repo-tag=core:r21.11 --repo-tag=backend:r21.11 --repo-tag=thirdparty:r21.11 --backend=onnxruntime:r21.11 --backend=pytorch:r21.11 --backend=tensorflow1:r21.11 --backend=tensorflow2:r21.11 --no-container-build --build-type=Debug

Cloning into 'pytorch'...
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 14 (delta 4), reused 5 (delta 0), pack-reused 0
Unpacking objects: 100% (14/14), 22.77 KiB | 777.00 KiB/s, done.
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using PyTorch docker: nvcr.io/nvidia/pytorch:None-py3
-- Found Python3: /usr/include/python3.8 (found version "3.8.10") found components: Development Development.Module Development.Embed 
-- RapidJSON found. Headers: /usr/include
-- RapidJSON found. Headers: /usr/include
-- Found CUDAToolkit: /usr/local/cuda/include (found version "11.5.50") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "11.5") 
-- Using CUDA 11.5
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/citritonbuild/pytorch/build

.Debug.cmake
[  9%] Building CXX object _deps/repo-core-build/CMakeFiles/triton-core-serverstub.dir/src/tritonserver_stub.cc.o
cd /tmp/citritonbuild/pytorch/build/_deps/repo-core-build && /usr/bin/c++ -Dtriton_core_serverstub_EXPORTS  -g -fPIC -Wall -Wextra -Wno-unused-parameter -Werror -MD -MT _deps/repo-core-build/CMakeFiles/triton-core-serverstub.dir/src/tritonserver_stub.cc.o -MF CMakeFiles/triton-core-serverstub.dir/src/tritonserver_stub.cc.o.d -o CMakeFiles/triton-core-serverstub.dir/src/tritonserver_stub.cc.o -c /tmp/citritonbuild/pytorch/build/_deps/repo-core-src/src/tritonserver_stub.cc
[ 13%] Extracting pytorch and torchvision libraries and includes from nvcr.io/nvidia/pytorch:None-py3

[ 86%] Linking CXX static library libtritonbackendutils.a
cd /tmp/citritonbuild/pytorch/build/_deps/repo-backend-build && /code/cmake-3.21.4-linux-x86_64/bin/cmake -P CMakeFiles/triton-backend-utils.dir/cmake_clean_target.cmake
cd /tmp/citritonbuild/pytorch/build/_deps/repo-backend-build && /code/cmake-3.21.4-linux-x86_64/bin/cmake -E cmake_link_script CMakeFiles/triton-backend-utils.dir/link.txt --verbose=0
make[2]: Leaving directory '/tmp/citritonbuild/pytorch/build'
[ 86%] Built target triton-backend-utils
Error response from daemon: manifest for nvcr.io/nvidia/pytorch:None-py3 not found: manifest unknown: manifest unknown
make[2]: *** [CMakeFiles/ptlib_target.dir/build.make:97: libmkl_core.so] Error 1
make[2]: Leaving directory '/tmp/citritonbuild/pytorch/build'
make[1]: *** [CMakeFiles/Makefile2:143: CMakeFiles/ptlib_target.dir/all] Error 2
make[1]: Leaving directory '/tmp/citritonbuild/pytorch/build'
make: *** [Makefile:136: all] Error 2
error: make install failed

**Comment by Tabrizian** [comment]
Looks like it is missing the `--upstream-container-version r21.11` flag.

**Comment by zhangkom** [comment]
@Tabrizian Thank you for the answer. Would you please tell me where I insert the option "--upstream-container-version 21.11" ?

Should I insert the option into following shell, thanks a lot.
./build.py --cmake-dir=/code/server/build --build-dir=/tmp/citritonbuild --enable-logging --enable-stats --enable-tracing --enable-metrics --enable-gpu-metrics --enable-gpu --endpoint=http --endpoint=grpc --repo-tag=common:r21.11 --repo-tag=core:r21.11 --repo-tag=backend:r21.11 --repo-tag=thirdparty:r21.11 --backend=onnxruntime:r21.11 --backend=pytorch:r21.11 --backend=tensorflow1:r21.11 --backend=tensorflow2:r21.11 --no-container-build --build-type=Debug

**Comment by deadeyegoodwin** [comment]
Yes, that is an argument to build.py. Sorry for the slow response. Closing. Reopen if you are still having an issue.
