### ISSUE TITLE
Cannot start Triton servers following default instructions

### ISSUE THREAD

**Issue by YanLu-nyu** [triton-inference-server/server#3688]
**Description**
I start Triton via docker run xxx following instructions from [QuickStart](https://github.com/triton-inference-server/server/blob/main/docs/quickstart.md). Although I get no error in loading model, the server closes and print "error: creating server: Internal - failed to load all models" in the end.

**Triton Information**
nvcr.io/nvidia/tritonserver:21.10-py3

I am using Triton container directly through command "docker run --gpus all --rm -p8000:8000 -p8001:8001 -p8002:8002 --name triton_server -v /home/featurize/work/adaptive_det/server/docs/examples/model_repository:/models nvcr.io/nvidia/tritonserver:21.10-py3 tritonserver --model-repository=/models --strict-model-config=false"

**To Reproduce**
Steps to reproduce the behavior.

I am using default models (densenet_onnx and inception_graphdef) as same as [QuickStart](https://github.com/triton-inference-server/server/blob/main/docs/quickstart.md). 

**Expected behavior**
No errors and Triton server starts.
![image](https://user-images.githubusercontent.com/10672549/145620680-4e2ffe55-b000-404d-8911-ef61035eb6a0.png)
![image](https://user-images.githubusercontent.com/10672549/145620717-235e3c04-d158-45fe-8846-8266721ff2bf.png)
![image](https://user-images.githubusercontent.com/10672549/145620746-f7fd3628-cb50-4f3c-9694-cfbfebbb5789.png)
![image](https://user-images.githubusercontent.com/10672549/145620774-e34b2cc6-e135-46d0-a6b9-dee846ba94d3.png)

**Comment by YanLu-nyu** [comment]
@sublee @dougn @benfred @kimdwkimdw

**Comment by tanmayv25** [comment]
You seem to have a file .ipynb_checkpoints in your model repository that is throwing some errors. Look for the messages starting with "E1210". Try removing it then run the server.

**Comment by YanLu-nyu** [comment]
@tanmayv25 Thanks for your advice. I start the server successfully after removing .ipynb_checkpoint.
