### ISSUE TITLE
How to understand the priority in rate_limiter?

### ISSUE THREAD

**Issue by Jianbing-D** [triton-inference-server/server#3705]
Document says ["An instance with priority 2 will be given 1/2 the number of scheduling chances as an instance with priority 1"](https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#priority).  It sounds like higher priority value equals to low priority behavior.

If there exists two model instances: Inst_A and Inst_B. And priority for Inst_A is 1, while that is 2 for Inst_B. Does that mean Inst_A will be scheduled for execution more often than that of Inst_B? For example, Inst_A is scheduled for 10 times execution, while Inst_B only be scheduled for 5 times.

If that is the case, how does it happen? 
When I dived into the source codes, I found that a [customized comparator](https://github.com/triton-inference-server/server/blob/main/src/core/rate_limiter.h#L178-L184) is used to build a `priority_queue` to stage the available instance.  And if an instance has bigger `ScaledPriority`, it should be pop out and used first. And [here](https://github.com/triton-inference-server/server/blob/main/src/core/rate_limiter.cc#L672-L681) is the logic of `ScaledPriority`.
```cpp
double
RateLimiter::ModelInstanceContext::ScaledPriority()
{
  // TODO: Different schemes for the prioritization of
  // model instance can be added here.
  // The priority of instance is 1 by default. If specified
  // as 0, the priority is still treated as 1.
  auto priority = std::max(rate_limiter_config_.priority(), 1u);
  return (exec_count_ * priority);
}
```
From the logic of `ScaledPriority()`, I am expecting that the model instance with higher priority value will get higher `ScaledPriority`, then should be pop out and used first from that `priority_queue`. 

Back to my previous example, that means  Inst_B should be scheduled and used before Inst_A, because Inst_B has higher priority, which is 2, than that of Inst_A. And **this is not consistent with the documents**.  And that is the exact point where I am confused.

And another question is:
Can the `priority` be set to arbitrary value?

**Comment by Tabrizian** [comment]
cc @tanmayv25

**Comment by tanmayv25** [comment]
>Document says "An instance with priority 2 will be given 1/2 the number of scheduling chances as an instance with priority 1". It sounds like higher priority value equals to low priority behavior.

Yes, see [here](https://softwareengineering.stackexchange.com/questions/77365/priority-value-meaning) for more details.

>If there exists two model instances: Inst_A and Inst_B. And priority for Inst_A is 1, while that is 2 for Inst_B. Does that mean Inst_A will be scheduled for execution more often than that of Inst_B? For example, Inst_A is scheduled for 10 times execution, while Inst_B only be scheduled for 5 times.

That's correct.

>If that is the case, how does it happen?

We multiply the priority value with the number of times the model Inst is executed that gives it a higher priority value. (higher scaled priority value means lower actual priority as per the convention)


>Back to my previous example, that means Inst_B should be scheduled and used before Inst_A, because Inst_B has higher priority, which is 2, than that of Inst_A. And this is not consistent with the documents. And that is the exact point where I am confused.

The customized comparator stores the elements as a min heap on the basis of scaled priority level. So, the first instance that comes out would have least priority. See [here](https://stackoverflow.com/questions/2439283/how-can-i-create-min-stl-priority-queue) for more details about how it works. 

All of it becomes consistent if you look from the right direction😃

 
>And another question is:
>Can the priority be set to arbitrary value?
You can set it to any value you want but you should be aware of the impact. These values come only into play when there are always requests queued up for instA and instB on the server. Assuming this to be true, you might see much less response rate from whatever instance you have decided to give a higher priority value. It depends upon you as a user if you would like to really make one model faster at expense of the other.

**Comment by Jianbing-D** [comment]
That is very clear now. Thanks!
