### ISSUE TITLE
Windows Tensorflow and Pytorch support

### ISSUE THREAD

**Issue by umutozturk95** [triton-inference-server/server#3715]
Hi,
 I am trying to  compile triton server in Windows 10 Pro (Docker support) platform . But As far as I can see from the build process there is no tensorflow and pytorch support. I created C++ application using vs 2015 . I want to produce a model result from c++ app  using tensorflow or pythorc over triton server. I want to use triton server to switch between these deep learning libraries easily.So the triton server should be in the local system, not in the cloud environment. That's why I'm thinking of embedding the triton server into the software using C api. Do you think this process can be done? Do i need to pay attention?
Thanks.

**Comment by umutozturk95** [comment]
I also get an error when compiling buil.py with Dockerfile.win10.min.  win10-py3-min image is created by using docker -t command successfully. 
  I am sending the error tracs in the error_list.txt file. How can i solve the problem ?
Thanks.


[error_list.txt](https://github.com/triton-inference-server/server/files/7738958/error_list.txt)
.

**Comment by CoderHam** [comment]
@umutozturk95 if you are building a specific release branch you need to use the appropriate repo branch tags for that release. You should use r21.xx for core, common, backend, client and tf/pytorch and other respective repos if you are using the r21.xx branch of the server repo

**Comment by umutozturk95** [comment]
Thanks. I solved this build problem. When I successfully completed the build process, I saw that there were no tensorflow and pythorch folders for the backend in Windows 10 platform.But there are only build files of onnx ,openvivo and tensorrt.Does triton provide tensorflow and pytorch support on windows platform?

**Comment by dzier** [comment]
At this time, windows support is an alpha release and very limited. It does not currently support Tensorflow or Pytorch. The windows release only currently supports ONNX RT, OpenVino, and TensorRT. You can try to use something like [Model Navigator](https://github.com/triton-inference-server/model_navigator) to convert your Tensorflow or Pytorch model to TensorRT and then run it on Windows.

Closing issue for now, please re-open if you have more questions or issues.
