### ISSUE TITLE
Starting a Triton Inference Server using Terraform on AWS throwing stub error

### ISSUE THREAD

**Issue by sourabh-burnwal** [triton-inference-server/server#3716]
I am trying to automate the deployment of the Triton Inference Server on AWS using Terraform. I have an ami configured and am using a g4 instance type. Every step gets executed perfectly. But while running the triton docker image, a few python backend models get failed to load. The error I get is:
```
E1216 13:03:22.621255 1 model_repository_manager.cc:1215] failed to load 'ageGender_preprocess' version 1: Internal: Failed to initialize stub, stub process exited unexpectedly: ageGender_preprocess error: creating server: Internal - failed to load all models
```
When I ssh to the deployed ec2 instance and run the same 'docker run' command, it throws no error. Also, this error while deploying the Triton Server using Terraform comes up 6/10 times. And every time, it's some python backend model.

Can someone help me understand the issue here? What might be the actual reason for this error, since it doesn't appear when running the same docker run command manually.

**Comment by Tabrizian** [comment]
Can you share the arguments that you pass through the docker run command when automating the process? Are you trying to deploy multiple instances of Triton or this is the only instance?

**Comment by Tabrizian** [comment]
There is a bug in `--model-control-mode=poll/explicit` for Python models that we are aware of. If you use `--model-control-mode=none`, do you still see this issue?

**Comment by sourabh-burnwal** [comment]
But, I need the ```--model-control-model==poll``` so that new changes in the model directory can be reflected in the Triton server. Else, I'll need to restart the server manually, right?
Is there any alternative to this? My use-case included Triton Server getting restarted automatically when there is any change in the model repository.

**Comment by Tabrizian** [comment]
Can you please try Triton 21.12? We have fixed a bug related to this so this issue could've been resolved.

**Comment by sourabh-burnwal** [comment]
Tried with 21.12
It's working. Thank you for the response @Tabrizian
