### ISSUE TITLE
Unable to load Openvino shufflenet model (Input 'axes' should be Constant.)

### ISSUE THREAD

**Issue by TannedCung** [triton-inference-server/server#3718]
Hi,

I've just tried to load yolov5 (yolov5n which uses shufflenetv2 as backbone) into tritonserver. However, i got this bug:
```
E1220 07:01:27.321578 1 model_repository_manager.cc:1243] failed to load 'yolov5_face' version 1: Internal: openvino error in reading network : Check 'axes_node' failed at ngraph/core/src/op/interpolate.cpp:165:
While validating node 'v4::Interpolate Resize_251 (Mul_249[0]:f32{1,128,14,14}, Resize_251/sizes_ss[0]:i64{2}, Resize_251/scales_ss/Output_0/Data__const[0]:f32{2}, Resize_251/axes[0]:i64{?}) -> ()' with friendly_name 'Resize_251':
Input 'axes' should be Constant.
```
OpenVINO model is converted from ONNX and works fine using `openvino.inference_engine`. 

**Triton Information**
Tritonserver: 21.04, 21.11
OpenVINO: 2021.03

Are you using the Triton container or did you build it yourself?
Tritonserver is downloaded from dockerhub

**To Reproduce**
Here are the model files:
[1.zip](https://github.com/triton-inference-server/server/files/7743415/1.zip)

and the `config.pbtxt`:
```
name: "yolov5_face"
backend: "openvino"
max_batch_size: 1

input [
  {
    format: FORMAT_NCHW
    name: "data"
    data_type: TYPE_FP32
    dims: [ 3, 640, 640 ]
  }
]

output [
  {
    name: "stride_8"
    data_type: TYPE_FP32
    dims: [ 51, 56, 56 ]
  },
  {
    name: "stride_16"
    data_type: TYPE_FP32
    dims: [ 50, 28, 28 ]
  },
  {
    name: "stride_32"
    data_type: TYPE_FP32
    dims: [ 50, 14, 14 ]
  }
]
```

Thank you for your help !!!

**Comment by dzier** [comment]
It looks like you are missing a definition for input "axes" in the Input list. You only have "data" defined.

**Comment by TannedCung** [comment]
Turn out i used wrong openvino version to convert from onnx. Tritonserver docker use 2021.02 and i used version > 2021.03 to convert model. After switching to 2021.02, things work fine now.
