### ISSUE TITLE
[question] What is the server actions when got new requests immediately after the exiting

### ISSUE THREAD

**Issue by zijin520** [triton-inference-server/server#3719]
If I cancel the server running by "Ctrl+c", i.e. the server state has been set be "ready_state_ = ServerReadyState::SERVER_EXITING", but the live_models.size() is greater than zero. At that moment if the server got new inference requests, what are the server's actions for this? Does the new requests will be added into queue and be scheduled? Thanks.

**Comment by dzier** [comment]
The server will send back an error response indicating the server is unavailable. For example, see https://github.com/triton-inference-server/server/blob/main/src/core/server.cc#L457. If there are requests already in the queue or being processed before CTRL-C is pressed, the server will complete and return the requests. The server will wait for a configurable amount of time for the requests complete before shutting down. I think the default is 30 seconds, but you can run with `--help` to get the CLI option set the timeout period.
