### ISSUE TITLE
[developing custom triton backend] Segmentation fault when return error in TRITONBACKEND_ModelInstanceInitialize

### ISSUE THREAD

**Issue by zzk0** [triton-inference-server/server#3728]
**Description**
Segmentation fault when return error in TRITONBACKEND_ModelInstanceInitialize

**Triton Information**
r21.10

Are you using the Triton container or did you build it yourself?
Triton container

**To Reproduce**

I write the code below.

![image](https://user-images.githubusercontent.com/30856589/147029448-cc8bfdaf-e322-48f9-8ee7-4e653a53750a.png)

**Expected behavior**
It should not segmentation fault

**Comment by dzier** [comment]
In order to assist, we will need more information on how to reproduce, including source code, build commands, and the exact console commands you used to generate the segmentation fault.  The code you provided looks correct but will produce a segmentation fault if instance is not pointing to a correct model instance or is NULL. Until we know how model instance is invoked, there is not much help we can provide.

**Comment by zzk0** [comment]
>  The code you provided looks correct but will produce a segmentation fault if instance is not pointing to a correct model instance or is NULL. 

Thanks! This is excatly why segmentation fault happened.


Here is my code:

```
// Implementing TRITONBACKEND_ModelInstanceInitialize is optional. The
// backend should initialize any state that is required for a model
// instance.
TRITONBACKEND_ISPEC TRITONSERVER_Error*
TRITONBACKEND_ModelInstanceInitialize(TRITONBACKEND_ModelInstance* instance)
{
  const char* cname;
  RETURN_IF_ERROR(TRITONBACKEND_ModelInstanceName(instance, &cname));
  std::string name(cname);

  // if (true) {
  //   return TRITONSERVER_ErrorNew(TRITONSERVER_ERROR_INTERNAL, "Segmentation fault if throw error here");
  // }

  int32_t device_id;
  RETURN_IF_ERROR(TRITONBACKEND_ModelInstanceDeviceId(instance, &device_id));
  TRITONSERVER_InstanceGroupKind kind;
  RETURN_IF_ERROR(TRITONBACKEND_ModelInstanceKind(instance, &kind));

  LOG_MESSAGE(
      TRITONSERVER_LOG_INFO,
      (std::string("TRITONBACKEND_ModelInstanceInitialize: ") + name + " (" +
       TRITONSERVER_InstanceGroupKindString(kind) + " device " +
       std::to_string(device_id) + ")")
          .c_str());

  std::string device_tag = "cpu";
  SetDevice(kind, device_id);
  if (kind == TRITONSERVER_INSTANCEGROUPKIND_GPU) {
    device_tag = "cuda";
  }
  oneflow_api::Device device(device_tag, device_id);

  // The instance can access the corresponding model as well... here
  // we get the model and from that get the model's state.
  TRITONBACKEND_Model* model;
  RETURN_IF_ERROR(TRITONBACKEND_ModelInstanceModel(instance, &model));

  void* vmodelstate;
  RETURN_IF_ERROR(TRITONBACKEND_ModelState(model, &vmodelstate));
  ModelState* model_state = reinterpret_cast<ModelState*>(vmodelstate);

  // With each instance we create a ModelInstanceState object and
  // associate it with the TRITONBACKEND_ModelInstance.
  ModelInstanceState* instance_state;
  // An error will be thrown before SetState in some cases, this causes segmentation fault
  RETURN_IF_ERROR(ModelInstanceState::Create(
      model_state, instance, &instance_state, device));
  RETURN_IF_ERROR(TRITONBACKEND_ModelInstanceSetState(
      instance, reinterpret_cast<void*>(instance_state)));

  if (true) {
    return TRITONSERVER_ErrorNew(TRITONSERVER_ERROR_INTERNAL, "Segmentation fault will not happen if throw error here");
  }

  return nullptr;  // success
}
```

**Comment by dzier** [comment]
So the segfault is only occurring when you build with `-DTRITON_ENABLE_GPU=ON`? Are you sure have the correct build dependencies, including the correct CUDA versions.

However, the TRITONSERVER_ERROR_INVALID_ARG is an error thrown when an invalid argument is passed to Triton on the command line. What is the exact command line you are using to start the Triton server?

**Comment by zzk0** [comment]
> Are you sure have the correct build dependencies, including the correct CUDA versions.

Not sure. Is that means triton server r21.10 should only build with NVIDIA CUDA 11.1.0?  I know the corresponding version between triton server and CUDA from [this document](https://docs.nvidia.com/deeplearning/triton-inference-server/release-notes/rel_21-09.html), but I didn't know triton server relys on a specific cuda version 🤣  I will try to build with corresponding version and test. 

> However, the TRITONSERVER_ERROR_INVALID_ARG is an error thrown when an invalid argument is passed to Triton on the command line.

Are you sure about this? I find [this line](https://github.com/triton-inference-server/identity_backend/blob/main/src/identity.cc#L192) in the source code of identity backend. TRITONSERVER_ERROR_INVALID_ARG is thrown when config.pbtxt contains invalid arguments.


Thanks for your help😁.

**Comment by deadeyegoodwin** [comment]
Triton core calls TRITONBACKEND_ModelInstanceInitialize and it should never pass in an invalid or nullptr "instance". I'm closing this as you seem to have fixed the issue. But if you are seeing a case where "instance" is invalid or nullptr in this call then please reopen and provide everything we need to reproduce.
See https://github.com/triton-inference-server/backend#backend-lifecycles
