### ISSUE TITLE
How to implement custom pre/post processing in Triton inference server?

### ISSUE THREAD

**Issue by PythonImageDeveloper** [triton-inference-server/server#3729]
Hello there,
**Q1-** I read the Triton documents and the implement pre/pst processing steps is done in the client-side, right? why? Is it possible to do custom pre/post processing steps in the server-side?
**Q2-** How I can implement the custom pre/post processing steps in the server-side?

**Comment by Tabrizian** [comment]
Q1: No,  you don't have to do the pre/processing steps the client side. You can use [ensemble](https://github.com/triton-inference-server/server/blob/main/docs/architecture.md#ensemble-models) and Python backend to do the pre/post processing in Python.

Q2: There is an example on how to do pre processing steps in the sever side using Python backend. https://github.com/triton-inference-server/python_backend#preprocessing
