### ISSUE TITLE
Failed to allocate memory for requested buffer of size 13565952

### ISSUE THREAD

**Issue by sourabh-burnwal** [triton-inference-server/server#3730]
I have 20 onnx models, 40 python backend models, and 7 ensemble models, totaling up to 67 models on Triton. onnx model size ranges from 10mb to 40mb, and a couple of ensembles are ensembles of more than 3 onnx models. The ec2 instance where I've deployed this is of g4dn.2xlarge type. Specifications are 32gb RAM and 16gb VRAM (Tesla T4 GPU). 

I'm passing 14G as shm size while running the triton container. When I hit different models in the model server. Sometimes I get this error and triton crashes:
`
2021-12-22 11:21:32.471790726 [E:onnxruntime:, sequential_executor.cc:339 Execute] Non-zero status code returned while running Sigmoid node. Name:'Sigmoid_1' Status Message: /workspace/onnxruntime/onnxruntime/core/framework/bfc_arena.cc:330 void* onnxruntime::BFCArena::AllocateRawInternal(size_t, bool) Failed to allocate memory for requested buffer of size 13565952
`

I have two questions:
- What is the significance of --shm-size argument while running the triton container, and how to know what amount of shm size one should assign?
- How many models and requests this instance of mine can handle, and how to decide the specifications of the base system for triton server?

**Comment by dzier** [comment]
I believe the `--shm-size` indicates the size of the shared memory that is available to the container. If you want to hold all of your models in shared memory, it should be large enough to hold all your models.

For your second questions, I would recommend using [Model Analyzer](https://github.com/triton-inference-server/model_analyzer) to profile your model(s). Model Analyzer can be used to find the best configuration for the models and the memory footprint based on concurrent input requests size. However, it cannot handle the ensembled models at this time, but should get you the information you need for the models. It will even provide the optimal Model configuration file for each model based on any constraints you specify.
