### ISSUE TITLE
Why does TRITONSERVER_Server used like this?

### ISSUE THREAD

**Issue by spxcds** [triton-inference-server/server#3736]
```
struct TRITONSERVER_Server;

TRITONSERVER_Server* p = nullptr;
ni::InferenceServer* lserver = new ni::InferenceServer();
p = reinterpret_cast<TRITONSERVER_Server*>(lserver);
```

There's no any definition about  `TRITONSERVER_Server`. All the information are transacted by `TRITONSERVER_Server*`.

And other classes such as `TRITONSERVER_Error`,`TRITONSERVER_InferenceRequest`also used like this, does anyone knows the reason why using this method?

**Comment by dzier** [comment]
These Structs and handles are the fundamental components for the C-API that enables the modular aspect of Triton. For more information, please refer to the [Triton Architecture](https://github.com/triton-inference-server/server/blob/main/docs/architecture.md) documentation. The structs are defined in the [tritonserver.h](https://github.com/triton-inference-server/core/blob/main/include/triton/core/tritonserver.h) file.

**Comment by rec-syser** [comment]
I have the same question when i learn trinton's source code

**Comment by rec-syser** [comment]
> ```
> struct TRITONSERVER_Server;
> 
> TRITONSERVER_Server* p = nullptr;
> ni::InferenceServer* lserver = new ni::InferenceServer();
> p = reinterpret_cast<TRITONSERVER_Server*>(lserver);
> ```
> 
> There's no any definition about `TRITONSERVER_Server`. All the information are transacted by `TRITONSERVER_Server*`.
> 
> And other classes such as `TRITONSERVER_Error`,`TRITONSERVER_InferenceRequest`also used like this, does anyone knows the reason why using this method?

Can I ask how you solved this confusion?
