### ISSUE TITLE
change the request input shape will make triton server hang up？

### ISSUE THREAD

**Issue by zhugailin** [triton-inference-server/server#3743]
I am using  custom http client to access the triton service, but when I change the request input of the client, the triton server will hang up. I have to repeatedly start the triton service during the test code.
Is there any way to avoid it？

**Description**
serve :
`corrupted size vs. prev_size`

client:
```
raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
```

**Triton Information**
Triton versions :20.12
server_version  :2.6.0

**Comment by dzier** [comment]
The Triton version you are using is now over a year old. Does the problem exist in the latest version?

Also, you are using  custom HTTP client. Without seeing how that was implemented, it would be hard to debug. Can you provide additional information about the client? How we Triton built and ran?

**Comment by zhugailin** [comment]
Thanks for your reply.  The  20.12 version of triton I used before is the official docker image，I found this problem while using the codes as follows:
```
    infer_data = {
    "name": model_name,
    "versions": [version],
    "platform": "tensorrt_plan",
    "inputs": [{"name": "image", "datatype": "FP32","shape": [1,640,640,3],"data": img}],
    "outputs": [
            {"name": "detection_boxes","datatype": "FP32", "shape": [1,100,4]},
            {"name": "detection_classes","datatype": "FP32", "shape": [1,100]},
            {"name": "detection_scores","datatype": "FP32", "shape": [1,100]},
            {"name": "num_detections","datatype": "INT32", "shape": [1,1]}
            ]
    }
 infer_data = json.dumps(infer_data)
    headers = {
        "Content-Type": "application/json",
            }
    resp = requests.post(url,data=infer_data, headers=headers)
```


I tried to use 21.11 version of triton and there is no such problem, maybe this is a bug of the old version？

**Comment by dzier** [comment]
Yes, the latest version for 21.12 was released a few weeks ago. I would also try that one. We tend to fix bugs in older versions and apply them to newer versions.
