### ISSUE TITLE
got error when output is zero rank in BLS

### ISSUE THREAD

**Issue by Channingss** [triton-inference-server/server#3745]
**Description** 
I  call model to inference in a  BLS logic, when output of this model is zero rank(happened in detection task), i got a core dump in this line:

```
inference_response = inference_request.exec()
``` 

error logged by triton server

```
 2# 0x00007F6EADD6E1F9 in /opt/tritonserver/backends/python/libtriton_python.so
 3# 0x00007F6EADD51CDE in /opt/tritonserver/backends/python/libtriton_python.so
 4# 0x00007F6EADD5249F in /opt/tritonserver/backends/python/libtriton_python.so
 5# 0x00007F6EADD5F36D in /opt/tritonserver/backends/python/libtriton_python.so
 6# 0x00007F6EE343047F in /usr/lib/x86_64-linux-gnu/libpthread.so.0
 7# 0x00007F6EADD4E505 in /opt/tritonserver/backends/python/libtriton_python.so
 8# 0x00007F6EE2FA9DE4 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 9# 0x00007F6EE3427609 in /usr/lib/x86_64-linux-gnu/libpthread.so.0
10# clone in /usr/lib/x86_64-linux-gnu/libc.so.6
```

**Triton Information**
21.11

Are you using the Triton container or did you build it yourself?
yes

**To Reproduce**
Steps to reproduce the behavior.

project download link: https://1drv.ms/u/s!AlYyqSo4c3BygxWTJnkzR4BuWm-I?e=LD75I4

run client_bls1.py  get error.
run client_bls2.py  run successfully.

**Expected behavior**
run client_bls1.py should run successfully.

**Comment by Channingss** [comment]
>

**Comment by Tabrizian** [comment]
Thanks for sharing a repro. We have take a note of this and we will look into it.

**Comment by farzanehnakhaee70** [comment]
Hi,
Is there any update on this issue?
I have the same problem

**Comment by Channingss** [comment]
> Thanks for sharing a repro. We have take a note of this and we will look into it.

https://github.com/Channingss/bls/tree/master

**Comment by Tabrizian** [comment]
Fixed by triton-inference-server/python_backend#109
