### ISSUE TITLE
ERROR: infer_trtis_server.cpp:261 Triton: TritonServer response error received., triton_err_str:Internal, err_msg:PyTorch execute failure: Expected Tensor but got GenericDict

### ISSUE THREAD

**Issue by mfoglio** [triton-inference-server/server#3746]
I am trying to integrate a Torchscript classifier with Deepstream 6.0. 
The classifier outputs a dictionary:
```
{'output_1': tensor([[ 3.2155, -3.0554, -0.4579,  0.7352, -4.2501,  2.6455,  0.3411]],
        grad_fn=<MmBackward>),
 'output_2': tensor([[  3.8159,   6.6151, -10.7066,  -0.4239,  -1.1774,  -5.4879,  -2.1760]],
        grad_fn=<MmBackward>)}
```
I tried to integrate it with Triton Server but it seems that Triton doesn't like the dictionary. Is there a way make it work either by retrieving the dictionary or any intermediate layer?
For instance, it would be great if I could retrieve the layers upon which the dictionary is computed. Then, I could recompute the final the dictionary again "by myself".

**Comment by dzier** [comment]
Triton currently does not support the dictionary datatype. A work around is to use a UINT9 [-1] tensor to pass an arbitrary binary data blob. This can be a json or other serialization of a dictionary object. The model would then need to be modified to interpret that data. You could use an ensemble or [BLS](https://github.com/triton-inference-server/python_backend#business-logic-scripting) to deserialize the the data tensor into a dictionary and convert the tensors used by the model. Or you will need to modify the model accept the data blob tensor and deserialize the data.

**Comment by mfoglio** [comment]
Thank you @dzier . I was thinking that maybe it could be easier to wrap the model in order to return a triton-compatible output? For instance, I could convert the dictionary into a tuple. Would that work?
Since I am working with Deepstream I am not sure how if the UINT9 workaround would be applicable.

**Comment by dzier** [comment]
I don't think you should be having this issue with Deepstream. Deepstream has native support for Triton and should be able to already pass data in the correct format. Here is some documentation on the Triton Extension for Deepstream (https://docs.nvidia.com/metropolis/deepstream/dev-guide/graphtools-docs/docs/text/ExtensionsManual/NvDsTritonExt.html). I will see if I can find some examples.

**Comment by mfoglio** [comment]
I am using the Deepstream plugin nvinferserver https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_plugin_gst-nvinferserver.html . I am not exactly sure how it relates to the NvDsTritonExt you mentioned.

**Comment by dzier** [comment]
Even with the nvinferserver, Deepstream should work with Triton, meaning that it should output Tensor Data that Triton can use. I am not sure where the dictionary datatype comes from in Deepstream. Perhaps you should ask in the Deepstream forums, since the Triton team here are not very familiar with how Deepstream works.

**Comment by mfoglio** [comment]
Thank you @dzier . I am trying to wrap the model since this seems to me the easiest option:
```
class ModelWrapper(torch.nn.Module):

    def __init__(self, path):
        super(ModelWrapper, self).__init__()
        self.model = torch.jit.load(path, "cuda")

    def forward(self, x):
        output = self.model
        return output["output_color"], output["output_type"]
```
What options do I have in terms of the output of the `forward` function? Must it return only a single tensor or can it return a tuple or list?
