### ISSUE TITLE
Sporadic streaming gRPC error "2 UNKNOWN: TRTIS response timeout"

### ISSUE THREAD

**Issue by piraka9011** [triton-inference-server/server#3747]
**Description**

I have a Triton server deployed using v1.7.0b0 of the [Nvidia Riva](https://docs.nvidia.com/deeplearning/riva/user-guide/docs/index.html) service.
I am successfully able to perform streaming STT requests using gRPC with Node.js v16.
However, 3-4 times every 2-3 hours, I get the following error from gRPC: `2 UNKNOWN: TRTIS response timeout`.
I cannot handle this specific error using `grpc-js` because it seems to be caused after a client has shutdown/closed, however, I am able to handle other errors.

I can see when this happens that the Triton server is definitely not under load based on the Prometheus metrics.
An example of when this happened we had only: 3-4 active sessions, ~1800 requests, ~60ms response time, and 12.5% GPU utilization.

**Triton Information**

What version of Triton are you using? `2.13.0 `
Are you using the Triton container or did you build it yourself? Triton container (`nvcr.io/nvidia/riva/riva-speech:1.7.0-beta-server`)

**To Reproduce**

Start a Triton server:

```sh
tritonserver --log-verbose=0 --strict-model-config=true --model-repository /data/models --cuda-memory-pool-byte-size=0:1000000000
```

Keep running streaming sessions and intermittently get these errors after close.
Sample gRPC configuration (assuming [protos](https://docs.nvidia.com/deeplearning/riva/user-guide/docs/development-grpc.html#generating-bindings) were generated using `protoc`):

```js
import { RivaSpeechRecognitionClient } from './lib/riva_asr_grpc_pb';
import {
  RecognitionConfig,
  SpeechRecognitionAlternative,
  StreamingRecognitionConfig,
  StreamingRecognitionResult,
  StreamingRecognizeRequest,
  StreamingRecognizeResponse,
} from './lib/riva_asr_pb';
import { AudioEncoding } from './lib/riva_audio_pb';

// Setup
const recognitionConfig = new RecognitionConfig();
recognitionConfig.setEncoding(AudioEncoding.LINEAR_PCM);
recognitionConfig.setSampleRateHertz(SUPPORTED_SAMPLE_RATE);
recognitionConfig.setAudioChannelCount(SUPPORTED_CHANNELS);
recognitionConfig.setMaxAlternatives(1);
recognitionConfig.setEnableWordTimeOffsets(true);
recognitionConfig.setLanguageCode('ar-BH');
recognitionConfig.setModel(MODEL_NAME);

const streamingRecognitionConfig = new StreamingRecognitionConfig();
streamingRecognitionConfig.setConfig(recognitionConfig);
streamingRecognitionConfig.setInterimResults(true);

SttClientImpl = new RivaSpeechRecognitionClient(SERVER_URL, credentials.createInsecure()); SttClientImpl.waitForReady(getDeadline(SERVER_READY_TIMEOUT), (e) => {
  if (e) {
    onError(e);
    return;  
  }

  stream = SttClientImpl.streamingRecognize();
  stream.on('data', onData);
  stream.on('error', onError);
  const streamingRecognitionRequest = new StreamingRecognizeRequest(); 
  streamingRecognitionRequest.setStreamingConfig(streamingRecognitionConfig);
  // The first call to the client must be the request with the config
  stream.write(streamingRecognitionRequest);
});
...
// Some callback after we get audio data
const streamingRequest = new StreamingRecognizeRequest();
streamingRequest.setAudioContent(data);  // data is of type Buffer
stream.write(streamingRequest);
```

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

The ensemble model configuration was generated using [`riva-build` and `riva-deploy`](https://docs.nvidia.com/deeplearning/riva/user-guide/docs/custom-model-deployment.html).

<details>
<summary>Top level model configuration</summary>
<br>
<pre>
name: "CnLg-SpeUni256-EATL900-v2-streaming"
platform: "ensemble"
max_batch_size: 64
input {
  name: "AUDIO_SIGNAL"
  data_type: TYPE_FP32
  dims: [-1]
}
input {
  name: "SAMPLE_RATE"
  data_type: TYPE_UINT32
  dims: [1]
}
input {
  name: "END_FLAG"
  data_type: TYPE_UINT32
  dims: [1]
}
input {
  name: "CUSTOM_CONFIGURATION"
  data_type: TYPE_STRING
  dims: [-1, 2]
}
output {
  name: "FINAL_TRANSCRIPTS"
  data_type: TYPE_STRING
  dims: [-1]
}
output {
  name: "FINAL_TRANSCRIPTS_SCORE"
  data_type: TYPE_FP32
  dims: [-1]
}
output {
  name: "FINAL_WORDS_START_END"
  data_type: TYPE_INT32
  dims: [-1, 2]
}
output {
  name: "PARTIAL_TRANSCRIPTS"
  data_type: TYPE_STRING
  dims: [-1]
}
output {
  name: "PARTIAL_TRANSCRIPTS_STABILITY"
  data_type: TYPE_FP32
  dims: [-1]
}
output {
  name: "PARTIAL_WORDS_START_END"
  data_type: TYPE_INT32
  dims: [-1, 2]
}
output {
  name: "AUDIO_PROCESSED"
  data_type: TYPE_FP32
  dims: [1]
}
parameters {
  key: "chunk_size"
  value {
    string_value: "1.0"
  }
}
parameters {
  key: "compute_timestamps"
  value {
    string_value: "True"
  }
}
parameters {
  key: "decoder_type"
  value {
    string_value: "greedy"
  }
}
parameters {
  key: "language_code"
  value {
    string_value: "ar-BH"
  }
}
parameters {
  key: "lattice_beam"
  value {
    string_value: "5"
  }
}
parameters {
  key: "left_padding_size"
  value {
    string_value: "2.4"
  }
}
parameters {
  key: "max_supported_transcripts"
  value {
    string_value: "1"
  }
}
parameters {
  key: "model_family"
  value {
    string_value: "riva"
  }
}
parameters {
  key: "ms_per_timestep"
  value {
    string_value: "80"
  }
}
parameters {
  key: "offline"
  value {
    string_value: "False"
  }
}
parameters {
  key: "right_padding_size"
  value {
    string_value: "2.4"
  }
}
parameters {
  key: "sample_rate"
  value {
    string_value: "16000"
  }
}
parameters {
  key: "streaming"
  value {
    string_value: "True"
  }
}
parameters {
  key: "type"
  value {
    string_value: "online"
  }
}
parameters {
  key: "vad"
  value {
    string_value: "True"
  }
}
ensemble_scheduling {
  step {
    model_name: "CnLg-SpeUni256-EATL900-v2-streaming-feature-extractor-streaming"
    model_version: 1
    input_map {
      key: "AUDIO_SIGNAL"
      value: "AUDIO_SIGNAL"
    }
    input_map {
      key: "SAMPLE_RATE"
      value: "SAMPLE_RATE"
    }
    output_map {
      key: "AUDIO_FEATURES"
      value: "AUDIO_FEATURES"
    }
    output_map {
      key: "AUDIO_PROCESSED"
      value: "AUDIO_PROCESSED"
    }
  }
  step {
    model_name: "riva-trt-CnLg-SpeUni256-EATL900-v2-streaming-am-streaming"
    model_version: 1
    input_map {
      key: "audio_signal"
      value: "AUDIO_FEATURES"
    }
    output_map {
      key: "logprobs"
      value: "CHARACTER_PROBABILITIES"
    }
  }
  step {
    model_name: "CnLg-SpeUni256-EATL900-v2-streaming-voice-activity-detector-ctc-streaming"
    model_version: 1
    input_map {
      key: "CLASS_LOGITS"
      value: "CHARACTER_PROBABILITIES"
    }
    output_map {
      key: "SEGMENTS_START_END"
      value: "SEGMENTS_START_END"
    }
  }
  step {
    model_name: "CnLg-SpeUni256-EATL900-v2-streaming-ctc-decoder-cpu-streaming"
    model_version: 1
    input_map {
      key: "CLASS_LOGITS"
      value: "CHARACTER_PROBABILITIES"
    }
    input_map {
      key: "CUSTOM_CONFIGURATION"
      value: "CUSTOM_CONFIGURATION"
    }
    input_map {
      key: "END_FLAG"
      value: "END_FLAG"
    }
    input_map {
      key: "SEGMENTS_START_END"
      value: "SEGMENTS_START_END"
    }
    output_map {
      key: "FINAL_TRANSCRIPTS"
      value: "FINAL_TRANSCRIPTS"
    }
    output_map {
      key: "FINAL_TRANSCRIPTS_SCORE"
      value: "FINAL_TRANSCRIPTS_SCORE"
    }
    output_map {
      key: "FINAL_WORDS_START_END"
      value: "FINAL_WORDS_START_END"
    }
    output_map {
      key: "PARTIAL_TRANSCRIPTS"
      value: "PARTIAL_TRANSCRIPTS"
    }
    output_map {
      key: "PARTIAL_TRANSCRIPTS_STABILITY"
      value: "PARTIAL_TRANSCRIPTS_STABILITY"
    }
    output_map {
      key: "PARTIAL_WORDS_START_END"
      value: "PARTIAL_WORDS_START_END"
    }
  }
}
</pre>
</details>

**Expected behavior**

There should not be any streaming errors.

**Comment by dzier** [comment]
Can you provide a detailed Triton log that captures timeout? This may be an issue with RIVA and not Triton, but we cannot debug further without the log. Also, please provide the exact command lines you are using to reproduce.

**Comment by piraka9011** [comment]
I just updated the original post with the CLI ran to repro.
The logs don't show any errors and usually look something like this:

```
I1230 00:07:44.696545 18877 grpc_riva_asr.cc:590] Send silence buffer for EOS
I1230 00:07:44.710273 18807 grpc_riva_asr.cc:975] ASRService.StreamingRecognize returning OK
I1230 00:07:50.597883 19049 grpc_riva_asr.cc:590] Send silence buffer for EOS
I1230 00:07:50.610366 19019 grpc_riva_asr.cc:975] ASRService.StreamingRecognize returning OK
I1230 00:07:54.411506 18805 grpc_riva_asr.cc:590] Send silence buffer for EOS
I1230 00:07:54.427407 18790 grpc_riva_asr.cc:975] ASRService.StreamingRecognize returning OK
I1230 00:08:04.062316 19058 grpc_riva_asr.cc:799] ASRService.StreamingRecognize called.
I1230 00:08:04.062345 19058 grpc_riva_asr.cc:833] ASRService.StreamingRecognize performing streaming recognition with sequence id: 1304549395
I1230 00:08:04.062372 19058 grpc_riva_asr.cc:870] Using model CnLg-SpeUni256-EATL900-streaming for inference
I1230 00:08:04.062435 19058 grpc_riva_asr.cc:886] Model sample rate= 16000 for inference
I1230 00:08:04.472923 19058 riva_asr_stream.cc:219] Detected format: encoding = 1 RAW numchannels = 1 samplerate = 16000 bitspersample = 16
I1230 00:08:08.557456 19125 grpc_riva_asr.cc:799] ASRService.StreamingRecognize called.
I1230 00:08:08.557485 19125 grpc_riva_asr.cc:833] ASRService.StreamingRecognize performing streaming recognition with sequence id: 1715172346
I1230 00:08:08.557512 19125 grpc_riva_asr.cc:870] Using model CnLg-SpeUni256-EATL900-streaming for inference
I1230 00:08:08.557570 19125 grpc_riva_asr.cc:886] Model sample rate= 16000 for inference
I1230 00:08:08.871186 19125 riva_asr_stream.cc:219] Detected format: encoding = 1 RAW numchannels = 1 samplerate = 16000 bitspersample = 16
I1230 00:08:20.895381 19127 grpc_riva_asr.cc:590] Send silence buffer for EOS
I1230 00:08:20.908399 19125 grpc_riva_asr.cc:975] ASRService.StreamingRecognize returning OK
I1230 00:08:25.981110 18794 grpc_riva_asr.cc:590] Send silence buffer for EOS
I1230 00:08:25.998153 18774 grpc_riva_asr.cc:975] ASRService.StreamingRecognize returning OK
I1230 00:08:26.268473 19021 grpc_riva_asr.cc:590] Send silence buffer for EOS
I1230 00:08:26.280959 18803 grpc_riva_asr.cc:975] ASRService.StreamingRecognize returning OK
I1230 00:08:26.648864 19136 grpc_riva_asr.cc:799] ASRService.StreamingRecognize called.
I1230 00:08:26.648891 19136 grpc_riva_asr.cc:833] ASRService.StreamingRecognize performing streaming recognition with sequence id: 1647523235
I1230 00:08:26.648918 19136 grpc_riva_asr.cc:870] Using model CnLg-SpeUni256-EATL900-streaming for inference
I1230 00:08:26.648978 19136 grpc_riva_asr.cc:886] Model sample rate= 16000 for inference
I1230 00:08:26.929754 19136 riva_asr_stream.cc:219] Detected format: encoding = 1 RAW numchannels = 1 samplerate = 16000 bitspersample = 16
I1230 00:08:28.828382 19040 grpc_riva_asr.cc:799] ASRService.StreamingRecognize called.
I1230 00:08:28.828413 19040 grpc_riva_asr.cc:833] ASRService.StreamingRecognize performing streaming recognition with sequence id: 1801780327
I1230 00:08:28.828447 19040 grpc_riva_asr.cc:870] Using model CnLg-SpeUni256-EATL900-streaming for inference
I1230 00:08:28.828505 19040 grpc_riva_asr.cc:886] Model sample rate= 16000 for inference
I1230 00:08:29.269603 19040 riva_asr_stream.cc:219] Detected format: encoding = 1 RAW numchannels = 1 samplerate = 16000 bitspersample = 16
```

**Comment by piraka9011** [comment]
I just found some logs with an error, see lines 2 and 3:

```
I1230 23:48:48.946724  4856 grpc_riva_asr.cc:975] ASRService.StreamingRecognize returning OK
W1230 23:49:00.939409  4772 grpc_riva_asr.cc:671] Response timeout. requests sent: 79 received: 78
E1230 23:49:00.939572  4761 grpc_riva_asr.cc:971] ASRService.StreamingRecognize returning failure
I1230 23:49:01.120965  5175 grpc_riva_asr.cc:590] Send silence buffer for EOS
I1230 23:49:01.120968  5097 grpc_riva_asr.cc:590] Send silence buffer for EOS
I1230 23:49:01.121009  4931 grpc_riva_asr.cc:590] Send silence buffer for EOS
I1230 23:49:01.121205  4194 grpc_riva_asr.cc:590] Send silence buffer for EOS
```

This is after updating the Triton server command to:

```
tritonserver --log-verbose=0 --log-info=true --log-warning=true --log-error=true --strict-model-config=true --model-repository /data/models --cuda-memory-pool-byte-size=0:1000000000
```

**Comment by rmccorm4** [comment]
Hi @piraka9011,

Thanks for sharing the info so far. Before moving forward, I see that RIVA v1.8.0-beta is out. Can you reproduce this with the latest RIVA version: `1.8.0-beta-server` ?

**Comment by piraka9011** [comment]
We wanted to use 1.8.0 but can't since there seems to be another bug related to inverse text normalization (ITN) causing transcripts to appear connected and/or disjoined. 

However, I will create a script to continuously run inference for a long time and see if it happens on v1.7.0 or 1.8.0 locally.

Do you have any insight at least into potentially why this might happening or what's causing the timeout?

**Comment by piraka9011** [comment]
I just tested 1.8.0 vs. 1.7.0 locally and there doesn't seem to be a difference.
I wasn't able to reproduce the error either.

However, after updating to Riva 1.8.0, I now get the following error:

```
2 UNKNOWN: in ensemble <MODEL_NAME>, inference request for sequence 324231651 to model '<MODEL_NAME>-feature-extractor-streaming' must specify the START flag on the first request of the sequence
```

we have hundreds of succesful requests, so I'm not sure why this would be happening intermittently.

**Comment by rmccorm4** [comment]
Hi @piraka9011 ,

I filed a ticket with the RIVA team to help take a look at this as it doesn't seem like a Triton-specific issue at the moment.

I'm going to go ahead and close this issue on Triton side, let's move the conversation to the RIVA dev forum for now: https://forums.developer.nvidia.com/t/sporadic-streaming-grpc-error-2-unknown-trtis-response-timeout/199288

**Comment by piraka9011** [comment]
Makes sense, also, I think I might have found the issue.
It is related to the way the `end` and `status` events are sent by the server and handled by the client.
I will post our solution (?) in the forums.
