### ISSUE TITLE
What is the generation method of the first four bytes of bytestring? 

### ISSUE THREAD

**Issue by SuoSiFire** [triton-inference-server/server#3748]
[ISSUE](https://github.com/triton-inference-server/server/issues/999)

"A string element in a tensor must be encoded as 4-byte string length followed by the actual string bytes." was mentioned in this link.

What is the generation method of the first 4-byte? Are there any encoding and decoding codes? thanks.

**Comment by dzier** [comment]
Can you please point me to the documentation you are referring to?

**Comment by dzier** [comment]
There is no encoding or decoding. According to [extension_binary_data.md](https://github.com/triton-inference-server/server/blob/main/docs/protocol/extension_binary_data.md)

> Tensor data represented as binary data is organized in little-endian byte order, row major, without stride or padding between elements.

The first 4-bytes are just the length of the string in total number of bytes. This is just a `uint32` encoded as 4 bytes in little-endian format, followed by the string bytes.
