### ISSUE TITLE
Benchmark/Measure switching time between models

### ISSUE THREAD

**Issue by Michelvl92** [triton-inference-server/server#3749]
Is there an option to measure the switching time between models, when they should be loaded/unloaded or when they are both online?

The goal is to measure e.g. if there is a performance penalty when having> 1 model in the triton client and want alternately request from those models, or when both models are online and nee concurrent requests.

**Comment by dzier** [comment]
You should be able to set up some experiments of this nature using [Model Analyzer](https://github.com/triton-inference-server/model_analyzer). This tool will run several experiments to find the best configuration (batch size, number of instances, etc) for your model that maximizes the throughput for a given latency constraint. We are also working on a feature to perform multi-model analysis which will do exactly what you need.  Unfortunately, it is not ready at this time.

If you would like to create your own experiments, all of the Performance runs and metrics that Model Analyzer uses are generated by [Perf Analyzer](https://github.com/triton-inference-server/server/blob/main/docs/perf_analyzer.md). Experimenting with Perf Analyzer will be you best option, next to Model Analyzer.

Also keep in mind, that when running multiple separate models, you will want to take advantage of the [rate limiter](https://github.com/triton-inference-server/server/blob/main/docs/rate_limiter.md) feature, which will prevent one model from starving another model.
