### ISSUE TITLE
pinned buffer: failed to perform CUDA copy: invalid argument

### ISSUE THREAD

**Issue by dumbPy** [triton-inference-server/server#3750]
**Description**
I am trying to implement [class aware NMS for yolox in torchscript](https://github.com/Megvii-BaseDetection/YOLOX/blob/d669fd38d9ac672a9e5a7eab5aa61d3be6b3959a/yolox/utils/demo_utils.py#L56)

But the model when infered with random array of 3x7 or (any valid shape) throws the error `tritonclient.utils.InferenceServerException: pinned buffer: failed to perform CUDA copy: invalid argument`

I tried the suggestions in #2641 as it looks related, by trying to build the torchscript model inside the ngc container from same 21.10 tag, but even that didn't work.

**Triton Information**
using nvcr.io/nvidia/tritonserver:21.09-py3

Are you using the Triton container or did you build it yourself?
container

**To Reproduce**
build.py
```python
import torch
import torchvision
import numpy as np

class YoloPostProcessor(torch.nn.Module):
    def __init__(self, score_thresh, nms_thresh):
        super().__init__()
        self.score_thresh = score_thresh
        self.nms_thresh = nms_thresh


    def forward(self, predictions):
        boxes = predictions[:, :4]
        scores = predictions[:, 4:]
        mask = (scores>self.score_thresh) # dets to use for class aware nms
        class_idxs = torch.arange(0,mask.shape[1], pin_memory=True).repeat((mask.shape[0],1))
        bbox_idxs = torch.arange(0,mask.shape[0], pin_memory=True).reshape((-1,1)).repeat((1,mask.shape[1]))
        bbox_idxs = bbox_idxs.reshape(-1)[mask.reshape(-1)]
        boxes = boxes[bbox_idxs,:]
        classes = class_idxs.reshape(-1)[mask.reshape(-1)]
        scores = scores.reshape(-1)[mask.reshape(-1)]
        keep = torchvision.ops.batched_nms(boxes=boxes,
                                        scores=scores,
                                        idxs=classes.clone(),
                                        iou_threshold=self.nms_thresh
                                        )
        boxes = boxes[keep,:]
        scores = scores[keep]
        classes = classes[keep]
        return boxes, scores, classes
    
if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("output_path")
    parser.add_argument('--score_thresh', default=0.7, type=float)
    parser.add_argument('--nms_thresh', default=0.45, type=float)
    args = parser.parse_args()
    model = YoloPostProcessor(args.score_thresh, args.nms_thresh).eval().to('cuda')
    model = torch.jit.trace(model, torch.rand((4,7), device='cuda'), strict=False)
    model.save(args.output_path)
    print(model.code)
```
I then tried to build it inside the container with 
```sh
docker run --rm -it \
	-v $PWD:/data \
	--name torchscript-yolo-nms-builder nvcr.io/nvidia/pytorch:21.10-py3 \
	bash -c "cd /data && python3 build.py  model.pt"
```
and then when I load the model and try to infer on it, it with the below client.py, it throws the above mentioned error.

I also tried loading the model.pt in pytorch and pass random 4x7 tensor and it works as expected ,but fails in triton.

```py
import numpy as np
import tritonclient.grpc
import tritonclient.http
import cv2

input_name = "INPUT__0"
# output_names = ["boxes__0", "scores__1", "labels__2"]
output_names = ["OUTPUT__0", "OUTPUT__1", "OUTPUT__2"]
model_name = "yolo_ensemble_post"


if __name__ == "__main__":
    input_shape = [4,7]
    print(f"Taking input shape {input_shape}")
    print(f"This corresponds to 5 bboxes with 7-4=3 classes")

    client = tritonclient.http.InferenceServerClient('localhost:8000')
    client.load_model(model_name)

    input_data = np.random.rand(*input_shape).astype(np.float32)
    inputs = [tritonclient.http.InferInput(input_name, input_data.shape, 'FP32')]
    inputs[0].set_data_from_numpy(input_data)
    # outputs = [tritonclient.grpc.InferRequestedOutput(output_name) for output_name in output_names]
    response = client.infer(model_name, inputs=inputs)
    boxes,scores,classes = [response.as_numpy(output_name) for output_name in output_names]
    print(f"Received outputs:\n")
    print(f"boxes: {boxes.shape}")
    print(f"scores: {scores.shape}")
    print(f"classes: {classes.shape}")
```

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

```pb
# platform: "pytorch_libtorch"    
input [                
  {                    
    name: "INPUT__0"    
    data_type: TYPE_FP32    
    dims: [ -1, -1 ]    
  }                    
]                      
output [               
  {                    
    name: "OUTPUT__0" #bboxes    
    data_type: TYPE_FP32    
    dims: [ -1 , 4  ]    
  },                   
  {                    
    name: "OUTPUT__1" # scores    
    data_type: TYPE_FP32    
    dims: [ -1 ]       
  },                   
  {                    
    name: "OUTPUT__2" # class indices    
    data_type: TYPE_INT64    
    dims: [ -1 ]       
  }                    
]
```

**Comment by dzier** [comment]
It looks like you are running a model built on 21.10 PyTorch container on a 21.09 release of Triton. The 21.10 PyTorch container has a new version of PyTorch than the 21.09 Triton release.  Can you run the model on the 21.10 release of Triton or newer?

**Comment by dumbPy** [comment]
Tried building in 21.09 and that didn't help. still getting the same error. In fact, was building the model.pt earlier on local installation which is even older than what's in 21.09 and it wasn't working, which is why I tried building inside the ngc docker as mentioned [here](https://github.com/triton-inference-server/server/issues/2641#issuecomment-811222644). neither helped.

**Comment by dumbPy** [comment]
I worked around this issue for now, by loading the torchscript model inside python backend and inferring on the requests. would be great if it works without this hack though.

**Comment by CoderHam** [comment]
@dumbPy can you provide the model and reproduction steps so we can triage this issue and work on a fix? Additionally did you face this error when running the torchscript model outside Triton?

**Comment by ddukek22** [comment]
I mentioned in https://github.com/triton-inference-server/server/issues/2641, but I think likely what is happening is that you have a mismatch between what memory triton is allocating your model / expects outputs to be in and where your outputs are. I would try a test being explicit in both the config.pbtxt and with the values that you are returning. My guess would be in your case that `classes` is in host memory and everything else is in memory on the  gpu.
