### ISSUE TITLE
[Question] How to serve sklearn preprocessing pipeline with triton

### ISSUE THREAD

**Issue by heya-na** [triton-inference-server/server#3752]
Hello, our project uses [sklearn pipeline](https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html) to preprocess data and get estimation. The pipeline has two steps: the 1st step is build with [ColumnTransformer](https://scikit-learn.org/stable/modules/generated/sklearn.compose.ColumnTransformer.html), which is an encoder for preprocessing input data. The 2nd step is a LGBMClassifier model for estimation. 
I'm able to extract the 2nd step, save it as LGBMClassifier model and serve with triton using fil backend. The inferencing works fine. But I'm not sure what would be the proper way to deploy the 1st step. For now it is serialized as an object and saved somewhere, to be downloaded when the application starts. But in the near future we might have an increasing number of pipelines, all with their own preprocessing and estimation steps. Is there a better way to handle the preprocessing part of the pipeline? Thank you.

**Comment by dzier** [comment]
You will want to read up on [ensemble models](https://github.com/triton-inference-server/server/blob/main/docs/architecture.md#ensemble-models), as this was designed specifically to create a pipeline of models and should be able to handle all your preprocessing needs. If you need more logical control of your pipeline, you can use our new [Business Logic Scripting](https://github.com/triton-inference-server/python_backend#business-logic-scripting) feature in your ensemble.
