### ISSUE TITLE
use docker  pull  triton   on  jetson    

### ISSUE THREAD

**Issue by woshituobaye** [triton-inference-server/server#3753]
after I use docker  pull  triton   on  jetson    .  it  report  an error.

sudo docker run --gpus=all -it   cbbabafbf004

=============================
== Triton Inference Server ==
=============================

NVIDIA Release 21.12 (build 30441440)

Copyright (c) 2018-2021, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license
find: File system loop detected; '/usr/local/cuda-11.5/compat/lib.real/lib.real' is part of the same file system loop as '/usr/local/cuda-11.5/compat/lib.real'.
find: File system loop detected; '/usr/local/cuda-11.5/compat/lib/lib.real' is part of the same file system loop as '/usr/local/cuda-11.5/compat/lib'.
find: File system loop detected; '/usr/local/cuda-11/compat/lib.real/lib.real' is part of the same file system loop as '/usr/local/cuda-11/compat/lib.real'.
find: File system loop detected; '/usr/local/cuda-11/compat/lib/lib.real' is part of the same file system loop as '/usr/local/cuda-11/compat/lib'.
find: File system loop detected; '/usr/local/cuda/compat/lib.real/lib.real' is part of the same file system loop as '/usr/local/cuda/compat/lib.real'.
find: File system loop detected; '/usr/local/cuda/compat/lib/lib.real' is part of the same file system loop as '/usr/local/cuda/compat/lib'.

WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use Docker with NVIDIA Container Toolkit to start this container; see
   https://github.com/NVIDIA/nvidia-docker.

How can I solve this problem？

**Comment by dzier** [comment]
The machine you are running the Triton docker image on must have CUDA 11.5 and a CUDA 11.5 enabled driver installed. What is the output when you enter the command `nvidia-smi`?

**Comment by woshituobaye** [comment]
-bash: nvidia-smi: command not found

Can Triton be pre-installed on the Jetson platform？

**Comment by woshituobaye** [comment]
> The machine you are running the Triton docker image on must have CUDA 11.5 and a CUDA 11.5 enabled driver installed. What is the output when you enter the command `nvidia-smi`?

-bash: nvidia-smi: command not found

Could Triton be pre-installed on the Jetson platform？

**Comment by woshituobaye** [comment]
we have  1000+ jetson machine

**Comment by CoderHam** [comment]
@woshituobaye Triton does not have a docker image for jetson. If you refer to the release notes we share a tar file containing the Triton server and client builds.

Additionally nvidia-smi is not supported on Tegra devices. 
PS: Jetson devices run on CUDA 10.2 so you cannot use the SBSA docker image on Jetson.
