### ISSUE TITLE
/bin/bash: error while loading shared libraries: libnvinfer.so.8: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by zhongqingyang** [triton-inference-server/server#3754]
Ubuntu18. 04 error occurred while loading yolov5 model: "libnvinfer. So. 8: cannot open shared object file".

My startup command: sudo docker run -- GPUs = 1 -- RM - p8000:8000 - p8001:8001 - p8002:8002 - V / home / test / Triton_ deploy/models:/models -v/home/test/triton_ deploy/plugins:/plugins --env LD_ PRELOAD=/plugins/libmyplugins. so nvcr. io/nvidia/tritonserver:20.09-py3 tritonserver --model-repository=/models。

What should I do

**Comment by dzier** [comment]
You have a space between `libmyplugins.` and `so`. Try the following command:
```
sudo docker run -- GPUs = 1 -- RM - p8000:8000 - p8001:8001 - p8002:8002 - V / home / test / Triton_ deploy/models:/models -v/home/test/triton_ deploy/plugins:/plugins --env LD_ PRELOAD=/plugins/libmyplugins.so nvcr. io/nvidia/tritonserver:20.09-py3 tritonserver --model-repository=/models
```
