### ISSUE TITLE
[question][performance] Triton ensemble scheduling in parallel

### ISSUE THREAD

**Issue by aman-cc** [triton-inference-server/server#3755]
Hi, I'm trying to run an ensemble of 5 models with same input with the following ensemble config. But the throughput obtained for the ensemble has become 1/5th for the single model throughput (analyzed by `perf_analyzer`). The ensemble model execution is probably sequential. Is there a way to execute all the models in parallel?

```
name: "ensemble_model"
platform: "ensemble"
max_batch_size: 64
input [
  {
    name: "INPUT"
    data_type: TYPE_FP32
    format: FORMAT_NHWC
    dims: [ 320, 480, 3 ]
  }
]
output [
  {
    name: "out_1"
    data_type: TYPE_INT64
    dims: [ 160, 240 ]
  },
  {
    name: "out_2"
    data_type: TYPE_INT64
    dims: [ 160, 240 ]
  },
  {
    name: "out_3"
    data_type: TYPE_INT64
    dims: [ 160, 240 ]
  },
  {
    name: "out_4"
    data_type: TYPE_INT64
    dims: [ 160, 240 ]
  },
  {
    name: "out_5"
    data_type: TYPE_INT64
    dims: [ 160, 240 ]
  }
]
ensemble_scheduling {
  step [
    {
      model_name: "inf_model-A1"
      model_version: -1
      input_map {
        key: "image"
        value: "INPUT"
      }
      output_map {
        key: "postprocess_layer"
        value: "out_1"
      }
    },
    {
      model_name: "inf_model-A2"
      model_version: -1
      input_map {
        key: "image"
        value: "INPUT"
      }
      output_map {
        key: "postprocess_layer"
        value: "out_2"
      }
    },
    {
      model_name: "inf_model-A5"
      model_version: -1
      input_map {
        key: "image"
        value: "INPUT"
      }
      output_map {
        key: "postprocess_layer"
        value: "out_3"
      }
    },
    {
      model_name: "inf_model-A6"
      model_version: -1
      input_map {
        key: "image"
        value: "INPUT"
      }
      output_map {
        key: "postprocess_layer"
        value: "out_4"
      }
    },
    {
      model_name: "inf_model-A8"
      model_version: -1
      input_map {
        key: "image"
        value: "INPUT"
      }
      output_map {
        key: "postprocess_layer"
        value: "out_5"
      }
    }
  ]
}
```

**Comment by dzier** [comment]
This would require multiple GPUs. You would need to use instance groups to have one model run on 1 GPU and the other model run on the other GPU. Then then ensemble can send the output of one model to the input of both of these models to be ran in parallel.

**Comment by dzier** [comment]
Also, only one model can be loaded onto a GPU partition at time. The performance gain you get from GPUs is not from parallelizing the models, but from parallelizing the workload. Try increasing the concurrent batch size to improve the throughput.

**Comment by aman-cc** [comment]
> This would require multiple GPUs. You would need to use instance groups to have one model run on 1 GPU and the other model run on the other GPU. Then then ensemble can send the output of one model to the input of both of these models to be ran in parallel.

Thanks @dzier. Would there be anyway I can run all the models on the same GPU in parallel? Perhaps with BLS or custom backend?

**Comment by billaram** [comment]
Hi, I have same question 

* Does BLS ensure concurrency and improve overall latency? 
* What is concurrent batch size and how to set it?
* How can I reduce the latency while increasing throughput?
