### ISSUE TITLE
[Question] - Artifacts with Python backend

### ISSUE THREAD

**Issue by JulesBelveze** [triton-inference-server/server#3757]
Hi all,

I am using the Triton server with a Python backend and I'm trying to load the weights of a fine-tuned model. 
I have tried to include the `.bin` file within the `model/1/` folder, similarly to the ONNX backend and where my `model.py` is, but I'm hitting a `FileNotFoundError`.

Is there any recommended way to load artifacts when using a Python backend? Or do I have to build a custom Docker image and then copy them there?

Thanks for your help 😃 
Cheers!

**Comment by Tabrizian** [comment]
You can load your own artifacts for Python backend. If you are using relative paths, the path will be relative with respect to the directory that you have started Triton Server. You need to either make your path absolute or use `model/1/<your-file.bin>`.
