### ISSUE TITLE
The set_data_from_numpy function of class InferInput returns a list of **Nonetypes**

### ISSUE THREAD

**Issue by ThiruRJST** [triton-inference-server/server#3762]
**Description**
The **set_data_from_numpy** function of class **InferInput** returns a list of nonetypes when it has to return a list of tensors

**Triton Information**
I'm using the Triton Docker Image from NVIDIA NGC: 21.12-py3

Are you using the Triton container or did you build it yourself?
I'm using the triton container from NVIDIA NGC

**To Reproduce**
Steps to reproduce the behavior.
I'm using peoplenet TAO model which I converted into *model.plan* using TAO converter
Then I set the input using InferInput class defining the input name,input shape and input dtype

When I used **set_data_from_numpy** function to convert the image array to tensor and send a inference request, It raised an error stating
```
Nonetype has no attribute __get__tensor

```
After this printed the Inputs list which was a list of None. I checked the image array which wasn't NoneType. Why this function returns a list of None

**Expected behavior**
The function has to return a list of tensors that are going to be the inputs for the model.

**Comment by jbkyang-nvi** [comment]
Can you print the whole trace and the slice of code you use to call `set_dat_from_numpy` and the input you gave it?

**Comment by ThiruRJST** [comment]
[None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
Traceback (most recent call last):
  File "infer.py", line 224, in <module>
    inf.Pipeline(client=client)
  File "infer.py", line 115, in Pipeline
    det_res = client.infer(
  File "/home/tensorthug/.local/lib/python3.8/site-packages/tritonclient/grpc/__init__.py", line 1132, in infer
    request = _get_inference_request(model_name=model_name,
  File "/home/tensorthug/.local/lib/python3.8/site-packages/tritonclient/grpc/__init__.py", line 74, in _get_inference_request
    request.inputs.extend([infer_input._get_tensor()])
AttributeError: 'NoneType' object has no attribute '_get_tensor'

**Comment by ThiruRJST** [comment]
```
def Pipeline(self,client):
        #Preprocess and store images for each detectors present
        """
        The preprocessed images are stored in the format: {
            "detector_n": [list of all preprocessed images]
        }
        The images are stored in a global variable in PIL format
        
        """
        self.detector_preprocess(self.img_paths)
        print("Preprocessing Completed")

        #Detector Ins and Outs
        for dets in range(len(self.detectors)):
            inputs = []
            outputs = []
            inp_name = self.detectors[dets]['input_name']
            inp_shape = self.detectors[dets]['input_shape']
            out_name = self.detectors[dets]['output_name']
            #print(self.det_imgs['detector_0'])
            for tensors in self.det_imgs[f'detector_{dets}']:
                print(tensors.shape)
                inp_ten = grpcclient.InferInput(inp_name[0],inp_shape[0],"FP32")
                print(type(inp_ten))
                inputs.append(inp_ten.set_data_from_numpy(tensors))

            for outs in range(len(out_name)):
                outputs.append(grpcclient.InferRequestedOutput(out_name[outs]))
        
        print(inputs)
        #detector Inference
        det_res = client.infer(
            model_name='detector',
            inputs = inputs,
            outputs = outputs,
            headers={"test":"1"}
        )
        out_0 = det_res.as_numpy("output_bbox/BiasAdd")
        out_1 = det_res.as_numpy("output_cov/Sigmoid")

        print(out_0)
```

**Comment by ThiruRJST** [comment]
@jbkyang-nvi The scenario is we have multiple detector and classifier models, For each detectors, the inputs are created and appended into the **Inputs** list, when I printed this list, it shows a list of None.

**Comment by jbkyang-nvi** [comment]
Can you print the whole logs, including all your prints? 
```
...
            inp_name = self.detectors[dets]['input_name']
            inp_shape = self.detectors[dets]['input_shape']
            out_name = self.detectors[dets]['output_name']
            print("input name {}".format(inp_name[0]))
            print("inp_shape:")
            print(inp_shape[0])
            for tensors in self.det_imgs[f'detector_{dets}']:
                print("tensor shape")
                print(tensors.shape)
                inp_ten = grpcclient.InferInput(inp_name[0],inp_shape[0],"FP32")
                print(type(inp_ten))
                inputs.append(inp_ten.set_data_from_numpy(tensors))
                print("inp_ten type:")
                print(type(inp_ten))
            print(inputs)
```

**Comment by ThiruRJST** [comment]
Here I'm providing the link for the screemshot

https://drive.google.com/file/d/1G_R4l7wMNnv1KSAywMWAh7btX8gE5CTu/view?usp=sharing

**Comment by deadeyegoodwin** [comment]
set_data_from_numpy always returns None. It adds the data to the InferInput but doesn't return anything. If you want to collect the inputs use inputs.append(inp_ten)
