### ISSUE TITLE
How to protect  python model in triton server?

### ISSUE THREAD

**Issue by RobbertOnly** [triton-inference-server/server#3769]
**Is your feature request related to a problem? Please describe.**
How to proctect python model code  include preprocess and postprocess in ensemble model?

**Comment by Tabrizian** [comment]
Could you please elaborate more on what you mean by "protection"?

**Comment by RobbertOnly** [comment]
> 

When the  ensemble models are deployed in the public cloud or other production environment, 
the TritonPythonModel source codes are visible. How can i protect the implement details for those codes?

**Comment by deadeyegoodwin** [comment]
Triton itself doesn't provide any mechanism for this. You can create whatever conda env you want to run your python code so perhaps you can do something with that to protect your code.

**Comment by lchunleo** [comment]
> Triton itself doesn't provide any mechanism for this. You can create whatever conda env you want to run your python code so perhaps you can do something with that to protect your code.

If the python code is obsfuncated , can Triton inference server read it ?

**Comment by lchunleo** [comment]
> > 
> 
> When the ensemble models are deployed in the public cloud or other production environment, the TritonPythonModel source codes are visible. How can i protect the implement details for those codes?

Can share any idea to do so ? Thanks
