### ISSUE TITLE
No CUDA-capable device is detected (CUDA_ERROR_NO_DEVICE) cuInit()=100

### ISSUE THREAD

**Issue by zzk0** [triton-inference-server/server#3773]
**Description**
When run the tritonserver:21.10-py3-sdk, you can see this message in the WARNING.

![image](https://user-images.githubusercontent.com/30856589/148482619-fd1eecbf-5887-4fcf-aa95-0a8d40d8274d.png)

**Triton Information**
What version of Triton are you using?
nvcr.io/nvidia/tritonserver:21.10-py3-sdk

Are you using the Triton container or did you build it yourself?
Triton container

**To Reproduce**
docker run -it --rm  --runtime=nvidia -v $(pwd):$(pwd) -w $(pwd) nvcr.io/nvidia/tritonserver:21.10-py3-sdk bash

**Machine Environment**

Driver Version: 455.45.01
Docker version 18.09.3, build 774a1f4

![image](https://user-images.githubusercontent.com/30856589/148482841-c0326061-8398-48d7-bec0-9fcf64af933e.png)

![image](https://user-images.githubusercontent.com/30856589/148483149-071b2e1f-d073-47c0-b1ac-9e8fe7871d4f.png)

**Comment by jbkyang-nvi** [comment]
If you look at the [support matrix](https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html) for our containers, there's a line requiring you to update your driver.
```
Release 21.10 is based on NVIDIA CUDA 11.4.2 with cuBLAS 11.6.5.2, which requires NVIDIA Driver release 470 or later. However, if you are running on Data Center GPUs (formerly Tesla), for example, T4, you may use NVIDIA driver release 418.40 (or later R418), 440.33 (or later R440), 450.51 (or later R450), or 460.27 (or later R460).
The CUDA driver's compatibility package only supports particular drivers
```
Can you update your driver to be > 470 and see if this resolves the issue.

**Comment by zzk0** [comment]
> Can you update your driver to be > 470 and see if this resolves the issue.

Update driver to be 470 solves my problem. Thanks.
