### ISSUE TITLE
`is_server_live()` python GRPC client got no response intermittently, while c++ is OK

### ISSUE THREAD

**Issue by chunyulin** [triton-inference-server/server#3800]
**Description**
For GRPC clients, `is_server_live()` python API got no response intermittently **for some client mainchines** while c++ `IsServerLive()` is OK. No problem for HTTP clients at all. I wonder is python's `is_server_live()` implemented differently with c++'s such that they behaved differently in certain networking condition?

**Triton Information**
- Server: 21.08-py3 container with only `simple*` example models loaded. Although the issue doesn't depend on models.
- Client: Tested in 21.08-py3-sdk container and built c++ client with  `cmake` and only `TRITON_ENABLE_CC_GRPC` on and `make cc-clients`. The pip-installed python client without container is also checked and behaved the same.

**To Reproduce**
- For python grpc client on some machines, there is a high probability the following script halt when checking server aliveness: 
  ```
  for i in {0..10}; do python check_triton.py; done
  ```
- C++ clients were built by `g++ check_triton.cc -lgrpcclient` and it always return true immediately. 
- Here are [check_triton.py](https://gist.github.com/chunyulin/83bf74e703a77b84f3e79fbbd15ea0a0) and [check_triton.cc](https://gist.github.com/chunyulin/1ddcec32bf70465f44ce15aafe0a5c6a) in which the hard-coded server address should be accessible now. 

**Expected behavior**
The python client code should return immediately as c++ `IsServerLive()` does.

**Comment by dyastremsky** [comment]
Thank you for sharing this and providing a detailed report. Would you be able to test this again in 21.12 to see if you find the same issue?

**Comment by chunyulin** [comment]
Sadly I got the same result.
This issue happened intermittently for only some clients machine connecting to our server at `203.145.219.187`, eg., a client on LIGO cluster at CA and most on the research network in Taiwan, while the tests are OK for a client in Nvidia Taipei and one in CERN. So I am really curious why C++ api works but python got no response sometimes in this simple case. 

- Server building script
  ```
  VER="r21.12"
  ./build.py --cmake-dir=build --build-dir=citritonbuild --enable-logging --endpoint=grpc --endpoint=http \
    --repo-tag=common:${VER} --repo-tag=core:${VER} --repo-tag=backend:${VER} --repo-tag=thirdparty:${VER} \
    --backend=tensorflow2:${VER} --backend=onnxruntime:${VER}
  ```
- All client api are built and tested in:
  ```
  docker run --rm -v $PWD:$PWD --net host -it nvcr.io/nvidia/tritonserver:21.21-py3-sdk
  ```
  with the script:
  ```
  cmake -DCMAKE_INSTALL_PREFIX=`pwd`/install \
        -DTRITON_ENABLE_CC_HTTP=OFF        -DTRITON_ENABLE_CC_GRPC=ON \
        -DTRITON_ENABLE_PERF_ANALYZER=ON   -DTRITON_ENABLE_PYTHON_HTTP=OFF \
        -DTRITON_ENABLE_PYTHON_GRPC=ON     -DTRITON_ENABLE_GPU=OFF \
        -DTRITON_ENABLE_EXAMPLES=OFF       -DTRITON_ENABLE_TESTS=OFF ..
  
  make -j16 cc-clients python-clients
  pip remove tritonclient       ##  or just use the pre-installed python api
  pip install `pwd`/install/python/tritonclient-0.0.0-py3-none-manylinux1_x86_64.whl
  ```

**Comment by dyastremsky** [comment]
Thank you for testing and providing the full commands, Chun-Yu. We will investigate.

**Comment by jbkyang-nvi** [comment]
@chunyulin are you still facing this issue? I'm running your example with 23.02 and this issue doesn't exist anymore

**Comment by chunyulin** [comment]
@jbkyang-nvi furthur studies indicate it might be interwined with local network issues. So I close the issue. Thanks.
