### ISSUE TITLE
Model load call is throwing error only on the first call `POST /v2/repository/models/{MODEL}/load`

### ISSUE THREAD

**Issue by KshitizLohia** [triton-inference-server/server#3802]
**Description**
Model load should always throw error if there is an issue in loading the model

**Triton Information**
What version of Triton are you using?
`nvcr.io/nvidia/tritonserver:21.10-py3`

Are you using the Triton container or did you build it yourself?

**To Reproduce**
Steps to reproduce the behavior.
1. Bring up the triton server with model https://github.com/guyroyse/redisai-iris/blob/main/iris.onnx
```
tritonserver --strict-model-config=false  --model-repository=/models --model-control-mode=explicit
```
2. Run the model load command twice. We will get a 200 status call on the second call and error on the first call.
```
curl --location --request POST 'localhost:8000/v2/repository/models/{MODEL}/load'
curl --location --request POST 'localhost:8000/v2/repository/models/{MODEL}/load'
```
First Try:
<img width="1042" alt="firsttry" src="https://user-images.githubusercontent.com/11562259/149273868-a0f73df1-36e7-4719-b1ac-df93ff9c5826.png">
Second Try:
<img width="1058" alt="secondtry" src="https://user-images.githubusercontent.com/11562259/149273881-7260ebe4-1243-439f-b60b-8375e6175607.png">

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
1. https://github.com/guyroyse/redisai-iris/blob/main/iris.onnx
2. No config.pbtxt is required as config will be auto generated.

**Expected behavior**
`POST /v2/repository/models/{MODEL}/load` should always throw error in case of unsuccessful load. Else, the user will be under the impression that model has loaded on the second try.

**Comment by dyastremsky** [comment]
Thank you for bringing this to our attention. We will investigate.

**Comment by deadeyegoodwin** [comment]
@GuanLuo It is curious that we don't fail both calls in the same way.

**Comment by GuanLuo** [comment]
I haven't look into this issue, but my guess is that the first load sets timestamp of the model, then during the second attempt the model manager gets the same timestamp from polling the model directory and decides "reload" is not needed for this model

**Comment by deadeyegoodwin** [comment]
I suppose we should reset that timestamp if the model load fails?

**Comment by GuanLuo** [comment]
I think we could in the explicit mode. In polling mode, we may want to update the timestamp as otherwise model manager will poll, try to load the model again and fail to load even though there is no changes in the model directory

**Comment by KshitizLohia** [comment]
@deadeyegoodwin Is there a doc on how model manager load/unloads model and set timestamp according to last updated model? This will help us understand it better.

**Comment by deadeyegoodwin** [comment]
@GuanLuo  But if the model isn't loaded at all, then it is strange to report with the second load attempt that the model loaded ok. I think  it is ok if we just keep attempting to load the model and it keeps failing at each poll attempt. That would mean that we don't want to reset the timestamps unless the model loads successfully. Can you file a ticket (bug) to track this fix.

**Comment by GuanLuo** [comment]
We do have a ticket to track this issue, added some description to that ticket
