### ISSUE TITLE
Failed to fetch anonymous token when trying to pull Triton Docker image in CI

### ISSUE THREAD

**Issue by bryanmcgrane** [triton-inference-server/server#3805]
**Description**
Every few CI runs I see this exact error when I try to pull the Triton Docker image. It causes my CI to fail, which is really frustrating!

```
#5 [internal] load metadata for nvcr.io/nvidia/tritonserver:21.09-py3
#5 sha256:427d8fa572bc82e08f6dcef7f8d657525a6eca13d4e4fe03fea3258a157c0558
#5 ERROR: failed to authorize: rpc error: code = Unknown desc = failed to fetch anonymous token: unexpected status: 401 Unauthorized
#3 [internal] load metadata for nvcr.io/nvidia/tritonserver:21.09-py3-min
#3 sha256:ab4baa3f48727d25fa6024bc84cf599d16c85f5a907845f4bb3b82991ea5d04b
#3 ERROR: failed to authorize: rpc error: code = Unknown desc = failed to fetch anonymous token: unexpected status: 401 Unauthorized
```

**Triton Information**
21.09

Are you using the Triton container or did you build it yourself?

I am trying to build Triton myself, which usually works well up until a few weeks ago when I started seeing this issue.

**To Reproduce**
Try to pull the docker image a few times in a row. My CI runs every 10 minutes or so.

**Expected behavior**
The docker image pull does not give me a 401.

**Comment by dyastremsky** [comment]
@dzier Do you know what this might be? Is there some kind of rate limiter on our side?

**Comment by deadeyegoodwin** [comment]
This is a problem with NGC, not with Triton. I've filed an issue with NGC referring to this issue.

**Comment by mattdibi** [comment]
Any update on this? I'm having the same issue while building locally with Docker.

```
#1 [internal] load build definition from Dockerfile
#1 sha256:903741c3d11eaa42596196898b4c439fa35df96d5e184cbef79273cdf713d95d
#1 transferring dockerfile: 3.43kB done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 sha256:f44d8a4831d856cd6119d80f473da935c07af1032648b9c9c7e2ce3b8f57d7df
#2 transferring context: 103B done
#2 DONE 0.0s

#3 [internal] load metadata for nvcr.io/nvidia/tritonserver:21.12-py3
#3 sha256:775ad3373fdaaaf160dca050597919008aec39667c13f611de897ebecf31b551
#3 ERROR: failed to authorize: rpc error: code = Unknown desc = failed to fetch anonymous token: unexpected status: 401 Unauthorized
------
 > [internal] load metadata for nvcr.io/nvidia/tritonserver:21.12-py3:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to authorize: rpc error: code = Unknown desc = failed to fetch anonymous token: unexpected status: 401 Unauthorized
```

**Comment by chajath** [comment]
Any update on this? I'm also seeing the same issue. Is there a bug tracker on NGC side?

**Comment by dyastremsky** [comment]
@deadeyegoodwin

**Comment by hirenp4** [comment]
Wanted to check if issue is still happening ? Was there any retry during authentication failure? 
Possible to add debug  around the failure and see if the connection is leaving their network and reaching NGC

**Comment by bryanmcgrane** [comment]
Yes the issue is still happening. I had it happen this week.

**Comment by hirenp4** [comment]
Introduce this command for your build process. This might help us to troubleshot

Pls turn on debug and collect detailed logs, Would help to have timestamp in log messages if possible

curl 'https://api.ipify.org?format=json'

for i in {1..10}; do echo -n `date` " "; curl -w "dns_resolution: %{time_namelookup}, tcp_established: %{time_connect}, ssl_handshake_done: %{time_appconnect}, TTFB: %{time_starttransfer}\n" -o /dev/null -s "https://nvcr.io/v2/users/login"; sleep 2; done

**Comment by bryanmcgrane** [comment]
Just to follow up. I have resolved the issue for my team. We now back up Triton in our own private container registry. When we build, we pull from our registry.

**Comment by dyastremsky** [comment]
Thank you for the update, Bryan! Appreciate that you were able to find a workaround.

I'll leave this ticket open to work on until Hiren closes it, as this NGC issue is still impacting users.

**Comment by Vozf** [comment]
Happening to me now

**Comment by Vozf** [comment]
https://stackoverflow.com/questions/70970424/docker-build-docker-compose-up-error-unknown-desc-failed-to-fetch-anonymous/75757516#75757516

**Comment by sakar-12id** [comment]
Happening to me now as well!!! Even restarting docker (solution mentioned in the above-mentioned stackoverflow link) doesn't work.

**Comment by dyastremsky** [comment]
For Hiren's help debugging, please follow the steps provided to produce logs for the NGC team to investigate.

CC: @hirenp4 @Christina-Young-NVIDIA

**Comment by Jacobsolawetz** [comment]
Happening to me

**Comment by dyastremsky** [comment]
Thank you for the information, Jacob.

Closing this ticket. This is a generic NGC issue outside of Triton. This ticket is quite old. Hiren from the NGC team was willing to help and provided steps for generating logs, but no one provided them yet and it's been a year. There are also many reasons this failure could pop up.

If anyone wants to continue to discuss this issue and get help from NGC folks, please consider submitting a question on the NVIDIA forum. I see some guidance [here](https://forums.developer.nvidia.com/t/sdk-v0-2-docker-build-errors-in-using-a-development-container/218679) on the forum, feel free to open another issue there if that doesn't resolve the issue for you.

**Comment by Jacobsolawetz** [comment]
Thanks @dyastremsky!
