### ISSUE TITLE
How to run tests after building tritonserver

### ISSUE THREAD

**Issue by zzk0** [triton-inference-server/server#3816]
From the document, 

```
For a given version of Triton you can attempt to build with non-supported versions of the libraries but you may have build or execution issues since non-supported versions are not tested.
```

Therefore, I want to test tritonserver after I built it.

**Comment by dyastremsky** [comment]
There are tests in the qa folder. You should be able to run some of them. Others may require non-public models, so you can use them as a starting point for writing and running your own tests.

**Comment by deadeyegoodwin** [comment]
https://github.com/triton-inference-server/server/blob/main/docs/test.md
