### ISSUE TITLE
How to understand queue_batch_size payload_batch_size pending_batch_size  batch_size next_preferred_batch_size_ in dynamic_batch_scheduler.cc

### ISSUE THREAD

**Issue by zhaohb** [triton-inference-server/server#3818]
Now I am looking at the code of triton, the logic of dynamic batchsize in dynamic_batch_scheduler.cc, but some variables cannot be understood.
![image](https://user-images.githubusercontent.com/5791375/149952089-10cd0a12-fed1-4d48-b132-8e59d5e30405.png)
who can help me?

**Comment by deadeyegoodwin** [comment]
We typically can't provide a written explanation of the source code beyond the source code and the corresponding comments. Do you have a particular issue you are seeing, or some feature that you are trying to add to the batcher? Reopen with that kind of question and we can try to help.
