### ISSUE TITLE
[Question] Is ensemble model sequential in all cases?

### ISSUE THREAD

**Issue by gggaugau** [triton-inference-server/server#3822]
Hello guys. I have an ensemble model containing 3 sub models, each taking the same input. Particularly:

```
ensemble model: input, output1, output2, output3

ensemble_scheduling:
model A: input, output1,
model B: input, output2,
model C: input, output3
```
In case there is an inference request, which case does my ensemble model execute the request?
1. trigger model A,B and C at the same time
2. trigger model A -> B -> C sequentially

**Comment by GuanLuo** [comment]
Case 1 will be the expected behavior as the required inputs for all steps in the pipeline have been satisfied.
