### ISSUE TITLE
server's NGC container has no source code and build tools like cmake.

### ISSUE THREAD

**Issue by dongfangduoshou123** [triton-inference-server/server#3824]
I pull the latest triton-server's docker image and then create one container and enter into the container;
and I find that the container dose not has the server's source code and build tools like cmake;
I hope you can maintain a server's docker images with tags like devel(this devel image should contains the server's
source code and build tools like cmake; and users could directly use this devel image to do their futher development.

thank you!

**Comment by dongfangduoshou123** [comment]
why the build program can so complex？
I hope the build program is like below:
mkdir build_dir
cd build_dir
cmake ..
make

thank you!

**Comment by dyastremsky** [comment]
Our build targets many platforms and options (Windows, Linux, Jetson, etc.). Feel free to read through the build files to get a sense of why the logic is there. Most users use the pre-built Docker container, which is the easiest way to start. Instructions for different build options are here: https://github.com/triton-inference-server/server/blob/main/docs/build.md

We don't want to bloat the pre-built Triton server container, as it's already large and it's meant to be used for running the server. If you want to develop, you can clone the repository, add build tools, and run tests from our qa repository in your Docker container. Keep in mind that the qa tests may rely on models that aren't public and the like, so depending which tests you want to run, you may need to modify a few.
