### ISSUE TITLE
[Question]: Fairseq model to Triton server

### ISSUE THREAD

**Issue by eyalhir74** [triton-inference-server/server#3830]
Hi,
  I have a Fairseq model which I'd like to load into Triton. Is it possible? Any tutorial/explaination exists on how to do so?

thanks
Eyal

**Comment by GuanLuo** [comment]
We have [doc](https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md) and [example](https://github.com/triton-inference-server/server/tree/main/docs/examples/model_repository) for deploying different kinds of models, the general procedures should also apply to your particular model. Please provide more detail if you encounter specific issues while following the examples.

**Comment by deadeyegoodwin** [comment]
This site has many model examples, some of which give instructions for triton. Check there to see if there is any information for fairseq. https://github.com/NVIDIA/DeepLearningExamples
