### ISSUE TITLE
[question] model loading

### ISSUE THREAD

**Issue by zijin520** [triton-inference-server/server#3832]
Hi, Could you please help me to get the answers. Thanks. 
1. When overwriting the original model file with a new model file, how does the model roll back to the previous model if an error occurs when trying to load the new file?  Did you make a copy of the original file beforehand?  
2. Is the offline model file loaded into memory every time it is loaded?  If so, will it take up a lot of memory? And is it means that triton server is not suitable for deployment on the mobile end, only suitable for deployment on the computer end?
3. Could you please provide some mode examples for tensorrt_backend,  preferably including both stateless and stateful models.

Thank you very much.

**Comment by GuanLuo** [comment]
1. Triton only unload the previous model if the new model is successfully loaded, so in the case of failure, the previous model will still be served even though the files have been replaced.
2. In Triton, when a model is loaded, it is ready to perform any inference so yes the model is loaded into memory. The memory usage depends on both the model itself and the framework, there are small models that can fit in mobile devices and thus Triton deployment on those devices are also possible.
3. Triton is agnostic to the backends so the examples we have can be easily applied to specific backends (i.e. tensorrt_backend), please check our client repo for [client examples](https://github.com/triton-inference-server/client#triton-client-libraries-and-examples) and the server doc on [providing configuration for different types of models](https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#scheduling-and-batching)

**Comment by deadeyegoodwin** [comment]
The backend repo has a lot of information about backends in general, including a tutorial on writing them: https://github.com/triton-inference-server/backend

This example website has many model examples: https://github.com/NVIDIA/DeepLearningExamples
