### ISSUE TITLE
Differing batch_size between input and output

### ISSUE THREAD

**Issue by philnguyenresson** [triton-inference-server/server#3833]
I have a tensorRT model (generated by trtexec) which has a different input batch_size  and output batch_size. This is due to a part of the model which performs an operation similar to tensorflow's [extract_patches](https://www.tensorflow.org/api_docs/python/tf/image/extract_patches), except instead of inserting the patches into a new dimension, I concatenate them along the first (batch) dimension.
So if an input image creates 30 patches, then the output_batch_size = input_batch_size*30.

The model runs fine just using the TensorRT python api, since I'm able to specify the size of the input and output buffers. However, it seems that the triton-server only cares about the input_batch_size. So it only returns an output batch the size of the input_batch_size, I assume the excess output is cut off.

Is there a way to handle this in triton-server?

One possibility on my end is to modify the model itself such that it re-reshapes the output tensors so that the input and output batch sizes match.

**Comment by deadeyegoodwin** [comment]
If you don't use the dynamic batcher then I suspect that you will get the behavior you want. You can create a batch on the client, send it to triton in a single request, and the response should be the shape you expect. With the dynamic batcher triton must "scatter" each output tensors so that a portion of it goes to the appropriate request. This is where it assumes output batch size equals input batch size. Your suggestion would work and is a good way to fix for you model.

**Comment by philnguyenresson** [comment]
I don't think I have dynamic batching enabled, here is the auto generated config json for the model:

> {
>   "name": "effdet_d1_mbc_crop384",
>   "platform": "tensorrt_plan",
>   "backend": "tensorrt",
>   "version_policy": {
>     "latest": {
>       "num_versions": 1
>     }
>   },
>   "max_batch_size": 1,
>   "input": [
>     {
>       "name": "input_tensor:0",
>       "data_type": "TYPE_FP32",
>       "format": "FORMAT_NONE",
>       "dims": [
>         2048,
>         2432,
>         3
>       ],
>       "is_shape_tensor": false,
>       "allow_ragged_batch": false
>     }
>   ],
>   "output": [
>     {
>       "name": "num_detections",
>       "data_type": "TYPE_INT32",
>       "dims": [
>         1
>       ],
>       "label_filename": "",
>       "is_shape_tensor": false
>     },
>     {
>       "name": "detection_boxes",
>       "data_type": "TYPE_FP32",
>       "dims": [
>         100,
>         4
>       ],
>       "label_filename": "",
>       "is_shape_tensor": false
>     },
>     {
>       "name": "detection_scores",
>       "data_type": "TYPE_FP32",
>       "dims": [
>         100
>       ],
>       "label_filename": "",
>       "is_shape_tensor": false
>     },
>     {
>       "name": "detection_classes",
>       "data_type": "TYPE_INT32",
>       "dims": [
>         100
>       ],
>       "label_filename": "",
>       "is_shape_tensor": false
>     }
>   ],
>   "batch_input": [],
>   "batch_output": [],
>   "optimization": {
>     "priority": "PRIORITY_DEFAULT",
>     "input_pinned_memory": {
>       "enable": true
>     },
>     "output_pinned_memory": {
>       "enable": true
>     },
>     "gather_kernel_buffer_threshold": 0,
>     "eager_batching": false
>   },
>   "instance_group": [
>     {
>       "name": "effdet_d1_mbc_crop384",
>       "kind": "KIND_GPU",
>       "count": 1,
>       "gpus": [
>         0
>       ],
>       "secondary_devices": [],
>       "profile": [],
>       "passive": false,
>       "host_policy": ""
>     }
>   ],
>   "default_model_filename": "model.plan",
>   "cc_model_filenames": {},
>   "metric_tags": {},
>   "parameters": {},
>   "model_warmup": []
> }
> 

I will try modifying my model as mentioned above to see if that works
