### ISSUE TITLE
[Question] Error when loading models with python backend

### ISSUE THREAD

**Issue by SaratM34** [triton-inference-server/server#3834]
**Description**

**Triton Information**
r21.09

Are you using the Triton container or did you build it yourself?
Built myself

Question
I am getting the below errors when loading the models from NFS mount. All the models use python backend with custom conda environments. Just wanted to understand what could be the reason for these errors. I was able to load models successfully from local directory.

![Screen Shot 2022-01-19 at 4 29 40 PM](https://user-images.githubusercontent.com/1553258/150405257-f1e26a57-4f5c-4adb-8247-276d90c0f6a6.png)

**Comment by deadeyegoodwin** [comment]
Python backend must unpack any conda environment you have associated with the model. Are the listed directories writable by the triton process?

**Comment by SaratM34** [comment]
@deadeyegoodwin Thanks for your reply. **/tmp** directory is writable because using the same Triton Image I was able to load the model repository from local a directory. Also since /tmp is within Triton Container it should be writable even when loading models from NFS mount right?

**Comment by Tabrizian** [comment]
I looked up the first error in the `libarchive.h` and it looks like it happens when some underlying system call such as `fseek` or `read` fails. The second errors seems to be coming from a simple `mkdir` syscall https://github.com/triton-inference-server/python_backend/blob/92881cf95d826eacfeb58f3e90d5cb45a9d2115a/src/pb_env.cc#L123. Can you try the code below when the NFS is being used in your container to see whether you see any errors:

```
#include <sys/types.h>
#include <sys/stat.h>

int status;
status = mkdir("/tmp/my_test_dir", S_IRWXU | S_IRWXG | S_IROTH | S_IXOTH);
```

**Comment by SaratM34** [comment]
@Tabrizian Thanks for your response. I tried running the code above when NFS is being used by the container. The directory is getting created within /tmp folder. I also see that `ExtractTarFile` is called after directory is created. Could it be any error when extracting tar file?

**Comment by SaratM34** [comment]
@Tabrizian The issue got fixed. The model files got corrupted in the mount. This issue can be **closed**. Thanks for looking into this.
