### ISSUE TITLE
[Question] Is there data populating when request batch_size is less than tensorrt offline model batch_size

### ISSUE THREAD

**Issue by zijin520** [triton-inference-server/server#3837]
For tensorrt_backend, If the batch_size of the tensorrt offline model is 8 and the batch_size of the request is 7, can Tensorrt handle such a request, and if so, does it populate the input data?  Who fills it? Is it Runtime or Triton or ternsorrt_backend.
For the handling of this situation, can you give the code position. Thanks

**Comment by deadeyegoodwin** [comment]
Triton and tensorrt can handle a batch size that is less than the maximum batch size used when building the tensorrt model. Did you try it? No additional input data is generated, it is just left uninitialized. The TensorRT backend is here: https://github.com/triton-inference-server/tensorrt_backend/
