### ISSUE TITLE
The problem of low cpu usage

### ISSUE THREAD

**Issue by SilverBach805** [triton-inference-server/server#3838]
**Description**

**Triton Information**
What version of Triton are you using?
21.08 to 21.12
Are you using the Triton container or did you build it yourself?
Triton container released by nvidia.

**To Reproduce**
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**

The problem of low cpu usage. Specifically, a 6-core 12-thread cpu on version 21.08 shows a top command of 600% usage, which doesn't seem to be using hyperthreading. All versions after 21.09 show that the usage rate is only 100%, that is, only a single core is used. What is the reason, I look forward to your answer, thank you

**Comment by deadeyegoodwin** [comment]
It depends on what you are trying to do. What models are you running? Are you using GPU(s)? Does your throughput go down by 6x when you use a 21.09 or later triton?

**Comment by SilverBach805** [comment]
> It depends on what you are trying to do. What models are you running? Are you using GPU(s)? Does your throughput go down by 6x when you use a 21.09 or later triton?

i'm running with paddle OCR model which i transform to onnx. when i using GPU, it's same speed with direct running.
i have used 21.08-21.12. on version 21.08 it shows 600% usage with the top common and on 21.09 to 21.12, only 100%

i also try another model, it's the same

**Comment by tanmayv25** [comment]
Hi @SilverBach805, 
We removed the SetntraOpNumThreadCount and reverted to using default settings when moving from 21.08 to 21.09 in our onnxruntime_backend. https://github.com/triton-inference-server/onnxruntime_backend/commit/258da929d3ea6d2a594873ed6825d671659c4fa1
 
See here for more details about how it impacts the CPU usage: https://github.com/microsoft/onnxruntime/issues/2741
