### ISSUE TITLE
allow_ragged_batch

### ISSUE THREAD

**Issue by SilverBach805** [triton-inference-server/server#3839]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

how to use allow_ragged_batch? do i need to modify my model?

**Comment by deadeyegoodwin** [comment]
Yes, you will need to modify your model. https://github.com/triton-inference-server/server/blob/main/docs/ragged_batching.md

**Comment by SilverBach805** [comment]
can you give mee a demo for how to modify model?

**Comment by GuanLuo** [comment]
The [example section](https://github.com/triton-inference-server/server/blob/main/docs/ragged_batching.md#example-on-ragged-input-and-batch-input) of the linked documentation should give an idea on how the model should be implemented (paragraph 2 to be specific). Please let us know if you think the documentation is unclear and how we may improve it.

**Comment by mgxjq** [comment]
> The [example section](https://github.com/triton-inference-server/server/blob/main/docs/ragged_batching.md#example-on-ragged-input-and-batch-input) of the linked documentation should give an idea on how the model should be implemented (paragraph 2 to be specific). Please let us know if you think the documentation is unclear and how we may improve it.

i see the docs, it shows that a normal model use batch like this
        max_batch_size: 16
        input [
          {
            name: "INPUT"
            data_type: TYPE_FP32
            dims: [ -1 ]
          }
        ]
and use ragged_batch like this
max_batch_size: 16
      input [
        {
          name: "INPUT"
          data_type: TYPE_FP32
          dims: [ -1 ]
          allow_ragged_batch: true
        }
      ]
      batch_input [
        {
          kind: BATCH_ACCUMULATED_ELEMENT_COUNT
          target_name: "INDEX"
          data_type: TYPE_FP32
          source_input: "INPUT"
        }
      ]


i want to know how show i use the target_name: "INDEX" in my model? in my eyes, triton only give a longer tensor and a position array, how should i use and return in my model? for example torch?

**Comment by GuanLuo** [comment]
You should substitute "INDEX" with the tensor name that your model expects for the "position array". Yes, in short "Triton only give a longer tensor and a position array", which is what you should modify your model to accept those as its inputs. Your model should know how to delimit and process the batch from the inputs, and return the outputs for the batch.

Let's take the above input config and assume the model simply return the sum of the elements for each request in the batch: it accepts two inputs "INPUT" with shape [-1] and "INDEX" with shape [-1] and produce one output [-1 (batch dimension), 1]. And the model config will be:
```
max_batch_size: 16
input [
{
name: "INPUT"
data_type: TYPE_FP32
dims: [ -1 ]
allow_ragged_batch: true
}
]
batch_input [
{
kind: BATCH_ACCUMULATED_ELEMENT_COUNT
target_name: "INDEX"
data_type: TYPE_FP32
source_input: "INPUT"
}
]
output [
{
name: "OUTPUT"
data_type: TYPE_FP32
dims: [ 1 ]
}
]
```
If you send two request: the first one has "INPUT" = [1, 2, 3] and the second has "INPUT" = [7, 8]. Triton will send the (ragged batched) inputs "INPUT" = [1, 2, 3, 7, 8] and "INDEX" = [3, 5]. The model will use it to know where is the end of each request and compute the output for them, so it returns "OUTPUT" = [ [6], [15] ] and Triton will respond to each request with the proper part of the output

**Comment by SilverBach805** [comment]
> 

what about we have three or more inputs like bert? how should i modify my config.pbtxt? all three inputs need to concat. do i need three batch_input? but i only have one output.
Thanks a lot for your reply!

**Comment by mgxjq** [comment]
You mean that each input should have a corresponding index, even if my three input dimensions are the same, so that the Triton can be spliced automatically. Then I get three inputs and three indexes during model inference. I should directly infer the spliced inputs in the model. If it is a combination of five requests, you need to split the output according to the index, and then return an array with a length of five. triton will return these results to each request. Is my understanding right??

**Comment by mgxjq** [comment]
another question for batch, if  inputs of three requests are batched and i use  ragged batch, need i config reshape in config.pbtxt to reshape input with batch? or how triton concat inputs with batch of 3 and batch of 2?

**Comment by GuanLuo** [comment]
> You mean that each input should have a corresponding index, even if my three input dimensions are the same, so that the Triton can be spliced automatically. Then I get three inputs and three indexes during model inference. I should directly infer the spliced inputs in the model. If it is a combination of five requests, you need to split the output according to the index, and then return an array with a length of five. triton will return these results to each request. Is my understanding right??

Triton doesn't do the slicing for inputs, it batches them and provide index information (batch input) to the model and the model should know how to "slice" the batched input. For output, the model will just return the batch output and Triton will split it (based on model config) as responses to the requests.

> You mean that each input should have a corresponding index, even if my three input dimensions are the same

It's up to your model implementation, if each input of the same request has the same shape and they all need ragged batching, your model can just use one index information for all. And if that is how your model is set up, it only need one "batch input" then you can describe that in model config to have only one batch input which Triton will generate from one of the inputs.

> another question for batch, if inputs of three requests are batched and i use ragged batch, need i config reshape in config.pbtxt to reshape input with batch? or how triton concat inputs with batch of 3 and batch of 2?

You shouldn't need to add reshape, Triton will just concat the inputs.
