### ISSUE TITLE
python model get stuck on instance initialization step

### ISSUE THREAD

**Issue by Alexejklim** [triton-inference-server/server#3840]
I use pytorch model with triton container 21.11 and Kserve 0.7 Inferenceservice. Came across a problem, that model deployment got stuck on step "Starting Python backend stub" without any error message in logs. 

I0118 14:09:47.387210 18 python.cc:1608] Using Python execution env ...
I0118 14:09:47.387333 18 python.cc:1875] TRITONBACKEND_ModelInstanceInitialize: ...
I0118 14:09:47.387343 18 backend_model_instance.cc:68] Creating instance ...
I0118 14:10:18.258314 22 python.cc:1200] Starting Python backend stub: source /tmp/python_env_GZeDnz/0/bin/activate && exec env LD_LIBRARY_PATH=
/tmp/python_env_GZeDnz/0/lib:$LD_LIBRARY_PATH /opt/tritonserver/backends/python/triton_python_backend_stub ...
... 67108864 67108864 18 /opt/tritonserver/backends/python 56 ...

As it turned out, it was necessary to define more resourses (CPU and Memory). Assume, python process was killed each time just to free some resourses. 
Will nice if such case will handled in future releases or atleast better covered with error logs.

**Comment by Tabrizian** [comment]
Thanks for doing a complete analysis of this issue. The CPU usage problem has been fixed in this https://github.com/triton-inference-server/python_backend/commit/e9379464298de8ca9273910fecd07a57202d0789.

**Comment by deadeyegoodwin** [comment]
Closing. Reopen if you still see an issue after upgrading to the mention fix (will be available in the 22.01 release.

**Comment by hegc** [comment]
How can I set more resourses (CPU and Memory)?

**Comment by Alexejklim** [comment]
> How can I set more resourses (CPU and Memory)? I use 22.02-py3.
In my case was necessary to have at least 2 CPU in requests:  
```
        resources:
          limits:
            cpu: 6
            memory: 8Gi
            nvidia.com/gpu: 1
          requests:
            **cpu: 2**
            memory: 2Gi
```
