### ISSUE TITLE
Pytorch backend forJetson Nano 

### ISSUE THREAD

**Issue by L-A-Sandhu** [triton-inference-server/server#3841]
I am trying to build pytorch backend for my jetson device. I have used " cmake -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/install -DTRITON_PYTORCH_DOCKER_IMAGE="nvcr.io/nvidia/pytorch:21.12-py3" .." to get the pytorch docker 21.12-py3. 
while building it exits with the following error 

[  9%] Built target kernel-library-new
[ 22%] Built target triton-common-async-work-queue
[ 54%] Built target triton-backend-utils
[ 59%] Built target ptlib_target
[ 68%] Built target triton-core-serverstub
[ 72%] Linking CXX shared library libtriton_pytorch.so
/usr/bin/ld: cannot find -ltorch
/usr/bin/ld: cannot find -ltorchvision
collect2: error: ld returned 1 exit status
CMakeFiles/triton-pytorch-backend.dir/build.make:120: recipe for target 'libtriton_pytorch.so' failed
make[2]: *** [libtriton_pytorch.so] Error 1
CMakeFiles/Makefile2:146: recipe for target 'CMakeFiles/triton-pytorch-backend.dir/all' failed
make[1]: *** [CMakeFiles/triton-pytorch-backend.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2

Is there any solution to solve this problem.

**Comment by deadeyegoodwin** [comment]
Python backend works with jetson. We will be including it by default in an upcoming release. @CoderHam  can you provide details and help with the above.

**Comment by deadeyegoodwin** [comment]
Pytorch backend is not currently supported for jetson. You would first need to build pytorch itself for jetson. The pytorch on NGC is for ubuntu/x86, it does not work for jetson. 
But we are adding PyTorch backend to our jetson release as part of the 22.01 release, which should be out in 1-2 weeks.

**Comment by CoderHam** [comment]
@L-A-Sandhu you will need to first install both torch and torchvision (and their dependencies) to build / run the pytorch backend.
