### ISSUE TITLE
Prometheus always shows one GPU in Triton on Kubernetes

### ISSUE THREAD

**Issue by sourabh-burnwal** [triton-inference-server/server#3842]
I deployed a Kubernetes Cluster of Triton nodes. Everything seems working like it's supposed to. But the Prometheus metrics the server is exporting are confusing. So for the query: nv_gpu_utilization, I am getting one GPU only whereas two pods are running currently, meaning there should be two GPUs since I have configured node affinity as 1. So, only one pod will be running/started on one node. How to interpret the GPU utilization results I'm getting from my Kubernetes cluster?

When I saw the Triton Inference server demo on [YouTube](https://www.youtube.com/watch?v=1DUqD3zMwB4&t=71s), it shows individual GPU and model metrics. How can I do that? I'm not able to find any resources.

**Comment by deadeyegoodwin** [comment]
How are you getting the metrics? If you are using the http://metrics endpoint on a node then you are only going to see the metrics that are collected by that node, which will be only for the 1 GPU on that node. If you want a metric view across your entire cluster you need to add a prometheus database into your cluster that scrapes the metrics from all nodes and then you can query the database. See the deploy examples: https://github.com/triton-inference-server/server/tree/main/deploy

Also: https://github.com/triton-inference-server/server/blob/main/docs/metrics.md
