### ISSUE TITLE
Why Triton's allow_ragged_batch feature doesn't works?

### ISSUE THREAD

**Issue by PythonImageDeveloper** [triton-inference-server/server#3851]
**Triton Information**
What version of Triton are you using? 20.x

Are you using the Triton container or did you build it yourself? No

GPU: RTX 3060 - 12 GB
Model : wave2vec2 with 3 inputs

Hi all,
I Successfully converted the ASR model from onnx to TRT-7.x with the below shapes :
**min_shape : 1x8000
opt_shape: 1x64000
max_shape: 1x512000**

I used Triton 20.x for server and client, the every things is good for single request, but I want to expand this app to multi request support at the same time.

I have to some question:
**Q1-** Is the Triton automatically support multi request processing (multi-batch) in the Triton-server side at the same time?
**Q2-** When I change **allow_ragged_batch** in the config.pbtxt to True, I service throw out this error:
 

`asr   | 1       | UNAVAILABLE: Invalid argument: model 'asr_0_gpu0', tensor 'input': for the model to support ragged input, the engine shape is: [1,-1] while the model config shape is: [1,-1] `

I also convert the the model from onnx to TRT with the below shapes:
**min_shape : 1x8000
opt_shape: 5x64000
max_shape: 10x512000**

I have to set the input shape to [-1,-1] in the config.pbtxt, but I get the same error. why?

> name:"asr"
> platform:"tensorrt_plan"
> backend:""
>    version_policy {
>       latest {
>          num_versions:1
>       }
>    }
>    max_batch_size:10
>    input [
>       {
>          name:"input"
>          data_type:TYPE_FP32
>          format:FORMAT_NONE
>          dims: [ -1 ]
>          is_shape_tensor:false
>          allow_ragged_batch:true
>       }
>    ]
>    output [
>       {
>          name:"output"
>          data_type:TYPE_FP32
>          dims: [
>             -1,
>             32
>          ]
>          label_filename:""
>          is_shape_tensor:false
>       }
>    ]
>    batch_input [
>          {
>             kind: BATCH_ACCUMULATED_ELEMENT_COUNT
>             target_name: "INDEX"
>             data_type: TYPE_FP32
>             source_input: "INPUT"
>          }
>    ]
>    batch_output [
>       
>    ]
>    optimization {
>       priority :PRIORITY_DEFAULT
>       input_pinned_memory {
>          enable:true
>       }
>       output_pinned_memory {
>          enable:true
>       }
>    }
>    instance_group [
>       {
>          name:"asr"
>          kind:KIND_GPU
>          count:1
>          gpus: [
>             0
>          ]
>          profile: [
>             
>          ]
>       }
>    ]
>    default_model_filename:"asr_fp32.trt"
>    cc_model_filenames {
>       
>    }
>    metric_tags {
>       
>    }
>    parameters {
>       
>    }
>    model_warmup [
>       
>    ]

**Comment by GuanLuo** [comment]
Q1: Triton is able to prepare multiple batches, note that whether there will be parallel executions depends on your [instance group setting](https://github.com/triton-inference-server/server/blob/main/docs/optimization.md#model-instances).

Q2: The error message is not accurate regarding what the actual issue is. For the ragged batching implementation in TensorRT backend, your model should be accepting the input with shape [-1] (more [detail](https://github.com/triton-inference-server/server/blob/main/docs/ragged_batching.md)) whereas your model currently accepts shape [1, -1].
