### ISSUE TITLE
modification of the dimension check in EvaluateTensorRTContext

### ISSUE THREAD

**Issue by ziyuanjiang** [triton-inference-server/server#3852]
I am using the tensorRT backend for my model. 
My model has multiple inputs whose first dimensions are dynamic and should all be the batch size.
When I create the tensorRT model plan. Somehow, I encountered errors when setting the first dimension of the inputs in one profile with different min, opt, max values. （The same min, opt, max value for all inputs. Just the values for min, opt, max are different.）
I am still trying to understand that. But I managed to create a model plan with several profiles, with each of the profiles set all the min, opt, max to a same batch size. So each of the profiles corresponds to a batch size ranging from 1 to the max batch size.

Then I loaded the model plan to triton server, and noticed that the backend always selects the first profile even though the first profile cannot handle a batch size larger than one.

After a short study of the backend, I found that this dimension validation check blocks the backend from choosing the right profile.

https://github.com/triton-inference-server/tensorrt_backend/blob/5b5ede3bb0e60fd1872d6992d3017c0d9e578ae5/src/tensorrt.cc#L2869

This is a problem for me because when getting the input_shape_vec from TRITONBACKEND_InputProperties,
the first dimension is one, neglecting the actual batch size. 
And even though the manhattan distance of the corresponding profile should be much smaller in the afterward calculation, in my case only the first profile can pass this validation. And then the first profile failed to handle the actual batch size while inferencing.

I wonder whether you can only check the non-batch dimensions there or you mean that all profiles should be able to handle all the batch sizes and I abuse the ability of profiles.

**Comment by CoderHam** [comment]
@ziyuanjiang in your case is the first dimension not the batch dimension? If not that batching model might not be supported by Triton.
cc @GuanLuo

**Comment by GuanLuo** [comment]
Seems like the `input_shape_vec` generated doesn't get set to reflect the shape of the batch, but only the shape of the request. @tanmayv25 although it looks like a trivial fix, can you file a ticket for that?

**Comment by tanmayv25** [comment]
Sure! This is a bug. Backend must sweep across all profiles to capture what are supported for the shape then use manhattan to resolve which one to select.
