### ISSUE TITLE
Single model scaling

### ISSUE THREAD

**Issue by andreapairon** [triton-inference-server/server#3856]
I wonder if it's possible to scale out the Triton server loading only the model that is currently under heavy load.

Example:
I have a Triton server with `model-1` and `model-2`; the `model-2` is under heavy load and I would like to provide a new Triton server that includes only the `model-2`, without loading the `model-1` as well.

So, the final scenario would be:
first Triton server with `model-1` and `model-2`
second Triton server with `model-2`

Thanks in advance.

**Comment by GuanLuo** [comment]
There are different [model management mode](https://github.com/triton-inference-server/server/blob/main/docs/model_management.md) that you can specify for your need

**Comment by manhtd98** [comment]
seem like i have same problem. did you fix that?
