### ISSUE TITLE
Windows Dockerfile reference new cuDNN folder structure

### ISSUE THREAD

**Issue by hamaney** [triton-inference-server/server#3864]
**Description**
The Windows Docker Image references a directory that does not exist.   
When the Dockerfile builds, it runs the line `"RUN unzip %CUDNN_ZIP%"` which was copied from the host. 
After this line, the Dockerfile then tries to copy some cuDNN dlls and other files to the `%CUDA_INSTALL_ROOT_WP%`.
The issue is that the zip file copied from the host to the container has different folder names than what is mentioned in the Dockerfile.
The cuDNN zip file I downloaded from the Nvidia website is `cudnn-windows-x86_64-8.3.2.44_cuda11.5-archive.zip` and it has this folder naming after unzipping

- cudnn-windows-x86_64-8.3.2.44_cuda11.5-archive
    - \cudnn-windows-x86_64-8.3.2.44_cuda11.5-archive\
        - bin\
            - cudnn_adv_infer64_8.dll
            - ......
        - include\
            - ......
        - lib\
            - ..... 

The folder structure expected in the dockerfile is:
- libcudnn\
    - bin\
        - cudnn*.dll
- libcudnn_dev\
    - lib\
       - x64\
           - ...... 
- libcudnn_dev\
    - include\
       - ...... 

I see that some of this change happen in this PR https://github.com/triton-inference-server/server/pull/3766

**Triton Information**
master branch commit 071eb2c6c9a8f1bba380c0e69592f50a857c5c42

Are you using the Triton container or did you build it yourself?
still trying to build it in a container

**To Reproduce**
download these zip files form nvidia:

- cudnn-windows-x86_64-8.3.2.44_cuda11.5-archive.zip
- TensorRT-8.2.3.0.Windows10.x86_64.cuda-11.4.cudnn8.2.zip
- in Powershell run `docker build -t win10-py3-min -f Dockerfile.win10.min --build-arg TENSORRT_VERSION=8.2.3.0 .`

**Expected behavior**
should build the docker image.

**Comment by AbdulAbCellera** [comment]
fixed in https://github.com/triton-inference-server/server/pull/3861
