### ISSUE TITLE
Why the third party of grpc-new not appear to contain CMakeLists.txt

### ISSUE THREAD

**Issue by SimonLliu** [triton-inference-server/server#3866]
**Description**
Thanks for your good work! When i want to build triton-server with docker (https://github.com/triton-inference-server/server/blob/main/docs/build.md#ubuntu-docker), i run the default command. And i find abseil, cares, protobuf have the errors (does not appear to contain CMakeLists.txt).

**Triton Information**
What version of Triton are you using?
I use the main branch of the triton-server.
Are you using the Triton container or did you build it yourself?
I want to build it myself.
**To Reproduce**
Steps to reproduce the behavior.
I run the command.
`./build.py --cmake-dir=/home/XXX/triton-exp/server/build --build-dir=/tmp/citritonbuild --enable-logging --enable-stats --enable-tracing --enable-metrics --enable-gpu-metrics --enable-gpu --filesystem=gcs --filesystem=azure_storage --filesystem=s3 --endpoint=http --endpoint=grpc --repo-tag=common:main --repo-tag=core:main --repo-tag=backend:main --repo-tag=thirdparty:main --backend=ensemble --backend=identity:main --backend=repeat:main --backend=square:main --backend=onnxruntime:main --backend=pytorch:main --repoagent=checksum:main`

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Bug information**
There are too many logs so i just list some of them.
`...
[ 52%] Performing configure step for 'absl'
cd /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/absl/src/absl-build && /usr/bin/cmake "-GUnix Makefiles" -C/tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/absl/tmp/absl-cache-Release.cmake /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo-new/src/grpc/third_party/abseil-cpp
-- Performing Test OPT-Wdouble-promotion - Success
-- Performing Test OPT-Wno-system-headers
loading initial cache file /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/absl/tmp/absl-cache-Release.cmake
Re-run cmake no build system arguments
CMake Error: The source directory "/tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo-new/src/grpc/third_party/abseil-cpp" **does not appear to contain CMakeLists.txt.**
Specify --help for usage, or press the help button on the CMake GUI.
make[3]: *** [_deps/repo-third-party-build/CMakeFiles/absl.dir/build.make:94: _deps/repo-third-party-build/absl/src/absl-stamp/absl-configure] Error 1
make[3]: Leaving directory '/tmp/tritonbuild/tritonserver/build'
make[2]: *** [CMakeFiles/Makefile2:379: _deps/repo-third-party-build/CMakeFiles/absl.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
[ 53%] No patch step for 'c-ares'
cd /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build && /usr/bin/cmake -E echo_append
make[6]: Leaving directory '/tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/prometheus-cpp/src/prometheus-cpp-build'
[ 53%] No patch step for 'protobuf'
cd /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build && /usr/bin/cmake -E echo_append
cd /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build && /usr/bin/cmake -E touch /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/c-ares/src/c-ares-stamp/c-ares-patch
[100%] Built target core
make[5]: Leaving directory '/tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/prometheus-cpp/src/prometheus-cpp-build'
/usr/bin/cmake -E cmake_progress_start /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/prometheus-cpp/src/prometheus-cpp-build/CMakeFiles 0
make[4]: Leaving directory '/tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/prometheus-cpp/src/prometheus-cpp-build'
cd /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/prometheus-cpp/src/prometheus-cpp-build && /usr/bin/cmake -E touch /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/prometheus-cpp/src/prometheus-cpp-stamp/prometheus-cpp-build
cd /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build && /usr/bin/cmake -E touch /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/protobuf/src/protobuf-stamp/protobuf-patch
-- Looking for sys/timerfd.h - found
-- Looking for errno.h
[ 55%] Performing configure step for 'c-ares'
cd /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/c-ares/src/c-ares-build && /usr/bin/cmake "-GUnix Makefiles" -C/tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/c-ares/tmp/c-ares-cache-Release.cmake /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo/src/grpc/third_party/cares/cares
[ 56%] Performing install step for 'prometheus-cpp'
cd /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/prometheus-cpp/src/prometheus-cpp-build && make install
[ 57%] Performing configure step for 'protobuf'
cd /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/protobuf/src/protobuf-build && /usr/bin/cmake "-GUnix Makefiles" -C/tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/protobuf/tmp/protobuf-cache-Release.cmake /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo/src/grpc/third_party/protobuf/cmake
loading initial cache file /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/c-ares/tmp/c-ares-cache-Release.cmake
Re-run cmake no build system arguments
CMake Error: The source directory "/tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo/src/grpc/third_party/cares/cares" **does not appear to contain CMakeLists.txt.**
Specify --help for usage, or press the help button on the CMake GUI.
make[3]: *** [_deps/repo-third-party-build/CMakeFiles/c-ares.dir/build.make:94: _deps/repo-third-party-build/c-ares/src/c-ares-stamp/c-ares-configure] Error 1
make[3]: Leaving directory '/tmp/tritonbuild/tritonserver/build'
make[2]: *** [CMakeFiles/Makefile2:516: _deps/repo-third-party-build/CMakeFiles/c-ares.dir/all] Error 2
make[4]: Entering directory '/tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/prometheus-cpp/src/prometheus-cpp-build'
/usr/bin/cmake -S/tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/prometheus-cpp/src/prometheus-cpp -B/tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/prometheus-cpp/src/prometheus-cpp-build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/prometheus-cpp/src/prometheus-cpp-build/CMakeFiles /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/prometheus-cpp/src/prometheus-cpp-build//CMakeFiles/progress.marks
loading initial cache file /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/protobuf/tmp/protobuf-cache-Release.cmake
Re-run cmake no build system arguments
CMake Error: The source directory "/tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo/src/grpc/third_party/protobuf/cmake" **does not appear to contain CMakeLists.txt.**
Specify --help for usage, or press the help button on the CMake GUI.
make[3]: *** [_deps/repo-third-party-build/CMakeFiles/protobuf.dir/build.make:94: _deps/repo-third-party-build/protobuf/src/protobuf-stamp/protobuf-configure] Error 1
make[3]: Leaving directory '/tmp/tritonbuild/tritonserver/build'
make[2]: *** [CMakeFiles/Makefile2:353: _deps/repo-third-party-build/CMakeFiles/protobuf.dir/all] Error 2
make  -f CMakeFiles/Makefile2 all
make[5]: Entering directory '/tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/prometheus-cpp/src/prometheus-cpp-build'
make  -f core/CMakeFiles/core.dir/build.make core/CMakeFiles/core.dir/depend
-- Performing Test OPT-Wno-system-headers - Success
-- Performing Test OPT-Wno-pedantic-ms-format
...
begin
platform linux
machine x86_64
version 2.19.0dev
default repo-tag: main
container version 22.02dev
upstream container version 21.12
backend "ensemble" at tag/branch "main"
backend "identity" at tag/branch "main"
backend "repeat" at tag/branch "main"
backend "square" at tag/branch "main"
backend "onnxruntime" at tag/branch "main"
backend "pytorch" at tag/branch "main"
repoagent "checksum" at tag/branch "main"
error: docker run tritonserver_builder failed
begin
`
**Expected behavior**

Thanks!

**Comment by GuanLuo** [comment]
Just to confirm, are you running the `build.py` script from main branch as well?

**Comment by SimonLliu** [comment]
> Just to confirm, are you running the `build.py` script from main branch as well?

Yes. I ran the build.py script from main branch

**Comment by CoderHam** [comment]
@SimonLliu can you try building without the --cmake-dir argument if you are using the docker based build? The directory refers to the path inside the docker and not the local filesystem. We will need to fix the docs to clarify the same.

**Comment by SimonLliu** [comment]
> @SimonLliu can you try building without the --cmake-dir argument if you are using the docker based build? The directory refers to the path inside the docker and not the local filesystem. We will need to fix the docs to clarify the same.

I try it. Yet there are no some changes in the logs and these errors exist. Maybe the problem is not from --cmake-dir.

**Comment by CoderHam** [comment]
@SimonLliu I am unable to reproduce this error.
