### ISSUE TITLE
UNAVAILABLE: Internal: unable to create stream: the provided PTX was compiled with an unsupported toolchain

### ISSUE THREAD

**Issue by oeway** [triton-inference-server/server#3877]
**Description**
I upgraded the triton server with the ngc container `22.01-py3` and all my models becomes unavailable.

This [previous issue](https://github.com/triton-inference-server/server/issues/2193) suggests that the nvidia driver is outdated, so I did an upgrade and now I got: `Driver Version: 495.46, CUDA Version: 11.5` on my host (ubuntu 20.04). But still doesn't work.

**Triton Information**
What version of Triton are you using?
The one in docker image `nvcr.io/nvidia/tritonserver:22.01-py3`.

**To Reproduce**

```
docker run nvcr.io/nvidia/tritonserver:22.01-py3
```

**Expected behavior**
It should not fail.

**Comment by CoderHam** [comment]
@oeway This issue occurs due to a mismatch between the driver and compilation toolchain. I believe the driver version used for 22.01 is 510. Can you try using the Nvidia driver version 510.39?

I believe Framework Support Matrix docs need to be fixed to reflect the same.

**Comment by CoderHam** [comment]
@oeway I confirmed that the Nvidia Driver should be release 510. Can you try the same and confirm it solves your problem?

**Comment by oeway** [comment]
Hi, thanks for your quick response. 

I have RTX3090 cards, according to the drivers page, https://www.nvidia.com/Download/driverResults.aspx/184248/en-us  the latest driver I can get is 495.46 on the new feature branch. How can I get 510?

**Comment by CoderHam** [comment]
Refer to https://developer.nvidia.com/cuda-downloads

**Comment by oeway** [comment]
@CoderHam Thanks for the pointers, I will give it a try for my local test environment. However, we would like to deploy to a K8s cluster, and according to the [GPU Operator Component Matrix](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/platform-support.html#operator-component-matrix), the latest we can get is `470.82.01`. Do you by chance know a workaround for this?

**Comment by CoderHam** [comment]
@oeway can you try to enable cuda compability? (If it is currently disabled)

**Comment by 739982423** [comment]
> @CoderHam Thanks for the pointers, I will give it a try for my local test environment. However, we would like to deploy to a K8s cluster, and according to the [GPU Operator Component Matrix](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/platform-support.html#operator-component-matrix), the latest we can get is `470.82.01`. Do you by chance know a workaround for this?

2022.2.14:
Version 510.54 for RTX3090 is available for download at https://www.nvidia.com/Download/driverResults.aspx/186996/en-us

**Comment by TaylorHere** [comment]
I meet this issue when deploying tritonserver in kubernetes with A100 Card
containerd://1.5.4
Driver Version: 470.82.01
CUDA Version: 11.6
nvcr tag: 22.03-py3

I was use tensorRT to build a model.plan, then run it with tritonserver,  with the same nvcr container version tag but it says:

```
UNAVAILABLE: Internal: unable to create stream: the provided PTX was compiled with an unsupported toolchain
```

but I finally figure it out.

it can work with
```
command:
  - bash
args:
  - -c
  - tritonserver
  - --model-store=/models/
```
can't work with
```
command:
  - tritonserver
args:
  - --model-store=/models/
```
I have no idea why this happened.

![图片](https://user-images.githubusercontent.com/12156543/165743516-979541d6-f9f1-4685-a62b-bf12d0ae9bfe.png)

**Comment by RobMin** [comment]
Can confirm that this issue still exists for
`nvcr.io/nvidia/tritonserver:22.12-py3`
`gke 1.24`
`nvidia driver version 470`
`cuda 11.8`
and is solvable with
```
command:
  - bash
args:
  - -c
  - tritonserver --model-store=/models/
```
as mentioned above by @TaylorHere

**Comment by eddyerach** [comment]
@RobMin Is this the line? It didnt work for me:

bash -c tritonserver --model-store=/models/
