### ISSUE TITLE
Batch Inference

### ISSUE THREAD

**Issue by sarperkilic** [triton-inference-server/server#3880]
**Description**

Hello, 

I am trying to load my TensorRT model for batch size>1 inference. Below, I am sharing my config file.

name: "segmentation_model"
platform: "tensorrt_plan"
max_batch_size: 16
input [
  {
    name: "input_1"
    data_type: TYPE_FP32
    dims: [ -1,3, 512, 864 ]
  }
]
output [
  {
    name: "softmax_1"
    data_type: TYPE_FP32
    dims: [ -1,512,864,3] 
  }
]

When I try to load model with this config file, I am getting that error:
Invalid argument: model 'segmentation_model_0_gpu0', tensor 'input_1': the model expects 4 dimensions (shape [-1,3,512,864])  but the model configuration specifies 5 dimensions (an initial batch dimension because max_batch_size > 0 followed by the explicit tesor shape, making complete shape [-1,-1,3,512,864])  

How can I send an inference request with batch size>1? Like 2 batch size or 4.

**Triton Information**
What version of Triton are you using?
2.13.0

Are you using the Triton container or did you build it yourself?
Container

**Comment by dyastremsky** [comment]
Remove the -1 as your first dimension in the input and output. They are implicit when you use max_batch_size.

See this documentation for more information: https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#maximum-batch-size
