### ISSUE TITLE
Pass outputs of one model to inputs of another in BLS

### ISSUE THREAD

**Issue by TsykunovDmitriy** [triton-inference-server/server#3891]
**Description**
In my pipeline, several models are called sequentially. How can I pass output of one model to input of another in BLS? 

**Triton Information**
r22.01
docker image

**To Reproduce**
The code below raise last exception.
```
class TritonPythonModel:
    ...
    def execute(self, requests):
            ...
            preproc_request = pb_utils.InferenceRequest(
                model_name="preproc,
                requested_output_names=["OUTPUT0", "OUTPUT1"],
                inputs=[pb_utils.get_input_tensor_by_name(request, "INPUT0")]
            )
            preproc_response = preproc_request.exec()
            if preproc_response.has_error():
                raise pb_utils.TritonModelException(
                    preproc_response.error().message())

            inference_request = pb_utils.InferenceRequest(
                model_name="model",
                requested_output_names=["OUTPUT0", "OUTPUT1", "OUTPUT2"],
                inputs=[
                    pb_utils.get_output_tensor_by_name(preproc_response, "OUTPUT0"),
                    pb_utils.get_output_tensor_by_name(preproc_response, "OUTPUT1"),
                ]
            )
            inference_response = inference_request.exec()
            if inference_response.has_error():
                raise pb_utils.TritonModelException(
                    inference_response.error().message())
            ...
```
log output
```
0204 20:47:38.058890 82 pb_stub.cc:419] Failed to process the request(s) for model 'bls_model', message: TritonModelException: unexpected inference input 'OUTPUT0' for model 'model'
```

**Expected behavior**
Unfortunately, I could not find in examples or docs method how to change the name of tensor. The only solution I've found so far is to use `pb_utils.Tensor.from_dlpack("INPUT0", pb_utils.get_output_tensor_by_name(preproc_response, "OUTPUT0").to_dlpack())`. But I'm not sure that this solution does not cause unnecessary data copying. It would be cool to have an explicit implementation of passing tensors between models.

**Comment by CoderHam** [comment]
@TsykunovDmitriy please refer to https://github.com/triton-inference-server/server/blob/main/docs/architecture.md#ensemble-models on how to use ensembles in Triton. 

"n ensemble model represents a pipeline of one or more models and the connection of input and output tensors between those models." 

It contains an example on how to configure ensemble models in Triton.

**Comment by Tabrizian** [comment]
@TsykunovDmitriy Currently, there is not a way to change the tensor name but there is a ticket for it. Creating a new tensor from the existing tensor, as you mentioned in the issue, is the current approach for changing the tensor name. Note that this will not copy the underlying tensor and both of the tensors refer to the same underlying data.

**Comment by TsykunovDmitriy** [comment]
@Tabrizian Thanks a lot. 
Close issue.

**Comment by candlewill** [comment]
I also need the tensor rename feature.
