### ISSUE TITLE
Conditional model inference

### ISSUE THREAD

**Issue by averkij** [triton-inference-server/server#3896]
🖐 Hello, engineers.

I'm using Triton inference server and I have some pipeline of different models grouped in the single ensemble model (_platform_: ensemble). Now I need to implement some API flags that lead to adding two additional models in the pipeline.

So, the question is — do I need to **implement another three ensemble pipelines for every flags combination** or there are other options? And what if there would be more combinations. What is the best practice around this case?

**Comment by Tabrizian** [comment]
The [business logic scripting](https://github.com/triton-inference-server/python_backend#business-logic-scripting) feature is the official method for having full control over the ensemble execution. Conditional execution is not supported in the Triton ensemble.
