### ISSUE TITLE
DCGM_FI_DEV_GPU_UTIL for HPA is showing error "no metrics returned from custom metrics API"

### ISSUE THREAD

**Issue by MeghaVarshney21** [triton-inference-server/server#3897]
Hi,

I have deployed triton on the top of Kubernetes (EKS). I've installed everything and is working well and I have created a HPA  as well for the triton deployment on the basis of GPU Utilization (DCGM_FI_DEV_GPU_UTIL).

The yaml file for HPA looks like this:-

```
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: triton
  namespace: prometheus
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: triton
  minReplicas: 2
  maxReplicas: 3
  metrics:
  - type: Pods
    pods:
      metricName: DCGM_FI_DEV_GPU_UTIL # Average GPU usage of the pod.
      targetAverageValue: 90

```

But, I have realized that it is not working.  It is showing me the error that "unable to get metric DCGM_FI_DEV_GPU_UTIL: no metrics returned from custom metrics API".

```
**kubectl describe hpa -n prometheus**

Name:                              triton
Namespace:                         prometheus
Labels:                            <none>
Annotations:                       <none>
CreationTimestamp:                 Sat, 05 Feb 2022 20:48:07 +0530
Reference:                         Deployment/triton
Metrics:                           ( current / target )
  "DCGM_FI_DEV_GPU_UTIL" on pods:  <unknown> / 90
Min replicas:                      1
Max replicas:                      3
Deployment pods:                   2 current / 2 desired
Conditions:
  Type           Status  Reason               Message
  ----           ------  ------               -------
  AbleToScale    True    SucceededGetScale    the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetPodsMetric  the HPA was unable to compute the replica count: unable to get metric DCGM_FI_DEV_GPU_UTIL: no metrics returned from custom metrics API
Events:
  Type     Reason               Age                     From                       Message
  ----     ------               ----                    ----                       -------
  Warning  FailedGetPodsMetric  4m33s (x9421 over 39h)  horizontal-pod-autoscaler  unable to get metric DCGM_FI_DEV_GPU_UTIL: no metrics returned from custom metrics API
```

I want to autoscale Triton pods based on average GPU utilization (targetAverageValue) because when I am using autoscaling based on targetValue it is just summing all GPUs which is not my usecase.

**Comment by tanmayv25** [comment]
@jbkyang-nvi can you take a look at this issue?

**Comment by jbkyang-nvi** [comment]
Hi @MeghaVarshney21 can you clarify a few things:
1. Does

> I have created a HPA as well for the triton deployment on the basis of GPU Utilization (DCGM_FI_DEV_GPU_UTIL).

mean you started a separate instance of DCGM on your machine?  

2. Does the Triton metrics not work for you? We do use `DCGM_FI_DEV_GPU_UTIL` to monitor the GPUs that are exposed to Triton as `nv_gpu_utilization`.  Details [here](https://github.com/triton-inference-server/server/blob/main/docs/metrics.md)

**Comment by MeghaVarshney21** [comment]
Hi @jbkyang-nvi ,


I have created a separate pod for dcgm-exporter. I am getting metrics **(DCGM_FI_DEV_GPU_UTIL)** from Prometheus, but I am not able to use it for the autoscaling of Triton pods. 

``` **kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1/namespaces/default/pods/*/DCGM_FI_DEV_GPU_UTIL |  jq**

{
  "kind": "MetricValueList",
  "apiVersion": "custom.metrics.k8s.io/v1beta1",
  "metadata": {
    "selfLink": "/apis/custom.metrics.k8s.io/v1beta1/namespaces/default/pods/%2A/DCGM_FI_DEV_GPU_UTIL"
  },
  "items": [
    {
      "describedObject": {
        "kind": "Pod",
        "namespace": "default",
        "name": "dcgm-exporter-2cp2b",
        "apiVersion": "/v1"
      },
      "metricName": "DCGM_FI_DEV_GPU_UTIL",
      "timestamp": "2022-02-10T07:39:45Z",
      "value": "0",
      "selector": null
    },
    {
      "describedObject": {
        "kind": "Pod",
        "namespace": "default",
        "name": "dcgm-exporter-pw8m4",
        "apiVersion": "/v1"
      },
      "metricName": "DCGM_FI_DEV_GPU_UTIL",
      "timestamp": "2022-02-10T07:39:45Z",
      "value": "0",
      "selector": null
    }
  ]
}
```

**Comment by jbkyang-nvi** [comment]
@MeghaVarshney21 Triton uses the library version of DCGM which is not allowed to co-exist with the container version of DCGM which might explain the behavior you are seeing. To disable Triton's usage of the DCGM library you will need to compile Tritonserver yourself with [build.py](https://github.com/triton-inference-server/server/blob/main/docs/build.md#building-for-ubuntu-2004) without `--enable-metrics --enable-gpu-metrics` flags.

**Comment by MeghaVarshney21** [comment]
Autoscaling is one of the key features in Kubernetes cluster. It is a feature in which the cluster is capable of increasing the number of nodes as the demand for service response increases and decrease the number of nodes as the requirement decreases.

**
So, I am using HPA for autoscaling the  triton pods on the basis of gpu utilization(DCGM_FI_DEV_GPU_UTIL).**

**Comment by MeghaVarshney21** [comment]
> Hi @MeghaVarshney21 can you clarify a few things:
> 
> 1. Does
> 
> > I have created a HPA as well for the triton deployment on the basis of GPU Utilization (DCGM_FI_DEV_GPU_UTIL).
> 
> mean you started a separate instance of DCGM on your machine?
> 
> 2. Does the Triton metrics not work for you? We do use `DCGM_FI_DEV_GPU_UTIL` to monitor the GPUs that are exposed to Triton as `nv_gpu_utilization`.  Details [here](https://github.com/triton-inference-server/server/blob/main/docs/metrics.md)


Thanks @jbkyang-nvi

But when I check prometheus metrics for my cluster with more than one pod (meaning multiple GPUs), nv_gpu_utilisation shows single gpu always. **Why is it so and what does it mean?**
![Screenshot from 2022-02-15 15-53-45](https://user-images.githubusercontent.com/95682577/154042706-df768160-c791-4532-8c9e-0eb6ab681fb8.png)

**Also, how to use this metric (nv_gpu_utilisation) in HPA in kubernetes?**

**Comment by jbkyang-nvi** [comment]
> 



> > Hi @MeghaVarshney21 can you clarify a few things:
> > 
> > 1. Does
> > 
> > > I have created a HPA as well for the triton deployment on the basis of GPU Utilization (DCGM_FI_DEV_GPU_UTIL).
> > 
> > 
> > mean you started a separate instance of DCGM on your machine?
> > 
> > 2. Does the Triton metrics not work for you? We do use `DCGM_FI_DEV_GPU_UTIL` to monitor the GPUs that are exposed to Triton as `nv_gpu_utilization`.  Details [here](https://github.com/triton-inference-server/server/blob/main/docs/metrics.md)
> 
> Thanks @jbkyang-nvi
> 
> But when I check prometheus metrics for my cluster with more than one pod (meaning multiple GPUs), nv_gpu_utilisation shows single gpu always. **Why is it so and what does it mean?** ![Screenshot from 2022-02-15 15-53-45](https://user-images.githubusercontent.com/95682577/154042706-df768160-c791-4532-8c9e-0eb6ab681fb8.png)
> 
What did you run the Triton container with? Is it run with `--gpus='"device=0:0"'` or similar? Otherwise it should have a field of `nv_gpu_utilization` for each GPU label. 

> **Also, how to use this metric (nv_gpu_utilisation) in HPA in kubernetes?**
One of the ways it seems like is to rebuild triton using build.py that does not use GPU metrics as commented here: https://github.com/triton-inference-server/server/issues/3897#issuecomment-1035414009 and start your own DCGM monitoring service. Would that work for you?

**Comment by MeghaVarshney21** [comment]
I am using AWS EKS. I am using GPU instance type. It has all the pre-installed binaries required for kubernetes nodes. I cannot pass the --gpu " " argument because it is a docker argument not triton argument. And when I am trying to pass --gpu argument in deploy.yaml file it is giving me an error that tritonserver has no such argument.
But without passing this --gpu argument, I am able to access the GPU, since I have a few dali-backend models which strictly requires a GPU to load, and they are running without any error. The problem is when I am trying to view the nv_gpu_util metrics on Grafana Dashboard, it is showing me Single GPU . Also, it can be seen in the screenshot above, it's showing LoadBalancer IP instead of instance (node/pod) IP.

**This is how I'm passing the arguments in the deployment file of kubernetes**.

```
 containers:
       - image: *********************/tritonserver:v5
         imagePullPolicy: Always
         name: tritonserver
         args: ["tritonserver", "--model-repository=s3://test-triton", "--model-control-mode=poll", "--repository-poll-secs=60"]
```

**Comment by jbkyang-nvi** [comment]
Can you try running triton with `--allow-gpu-metrics=false` and have standalone DCGM and see if that works?

**Comment by rmccorm4** [comment]
Closing since no response in > 2 weeks.
