### ISSUE TITLE
Client side ratio perf_ Analyzer requests are much slower

### ISSUE THREAD

**Issue by Vulcan-YJX** [triton-inference-server/server#3898]
Hi, I have deployed tritonServer on Nx , perf_ Analyzer show that Peoplenet is 150infer/s . But It is just 60infer/s when i use python script in [tao-toolkit-triton-apps](https://github.com/NVIDIA-AI-IOT/tao-toolkit-triton-apps).  Once request maybe need 0.016 sec.How can we reach the theoretical value？

`
  Inferences/Second vs. Client Average Batch Latency
  Concurrency: 1, throughput: 119.8 infer/sec, latency 8339 usec
  Concurrency: 2, throughput: 152 infer/sec, latency 13152 usec
  Concurrency: 3, throughput: 154.6 infer/sec, latency 19401 usec
  Concurrency: 4, throughput: 154.4 infer/sec, latency 25877 usec
  Concurrency: 5, throughput: 154.8 infer/sec, latency 32298 usec
  Concurrency: 6, throughput: 154.6 infer/sec, latency 38786 usec
`

**Comment by tanmayv25** [comment]
Perf_analyzer is a C++ client application and uses our C++ client library. The C++ library is much more performant and handles data more efficiently than python. 
This large difference could be attributed to large data handling cost on python. perf_analyzer uses data from a single buffer to repeatedly send the requests one after the other. You can try increasing the request concurrencies in python client to mask the data handling cost. Or write client application using C++ client library.

**Comment by Vulcan-YJX** [comment]
Thanks for your help, It works!
