### ISSUE TITLE
Directing requests to correct triton deployment on kubernetes

### ISSUE THREAD

**Issue by v1nc3nt27** [triton-inference-server/server#3903]
Hello all,

I was wondering if there is any best-practice solution for the following case:

We want to run triton on kubernetes and AWS with nodes that have a single T4 each. Mostly, we deploy each model twice (on separate nodes). Sometimes, however, we run a model only once (e.g. for testing), sometimes we need to run it more than twice. Hence, not each triton sever deployment will have each model deployed. If we'd only create one service for all triton server deployments, we will eventually connect to a triton server that doesn't host the requested model. 

We could run several different triton server deployments that all host consistently the same models, but I don't want to have that overhead. Another option, I guess, would be to create a different kubernetes service for each model and only link to the triton pods that host the given model.

I was wondering if there is a built-in solution for that case or if someone has a better idea than the above suggestions. Thanks a lot!

**Comment by tanmayv25** [comment]
I am not aware of how this can be achieved in kubernetes. @rmccorm4  Any suggestions?

**Comment by the40thieves** [comment]
Hi this is a model orchestration problem, current Triton can explicitly load and unload the model, but it may make more sense to set up separated services for hosting and testing ... etc

**Comment by mengdong** [comment]
Hello, this is a model orchestration problem, Triton supports explicitly load and unload models across the same deployment, it also make sense to set up separated services for hosing and testing of different models.

**Comment by v1nc3nt27** [comment]
I see, thanks a lot for the explanation. I'll use different services then and also have a look into dynamic loading and undloading of models!
