### ISSUE TITLE
Unclear TensorRT version match

### ISSUE THREAD

**Issue by Michelvl92** [triton-inference-server/server#3904]
**Description**
I use the docker containers to export an ONNX model to TenosrRT to use with the triton server. Each release of https://github.com/onnx/  always expects a specific version of TensorRT, but this version does not exactly match the version of the Triton server. So it is unclear to me which release of onnx-tensorrt I should match with which release of triton-infernce-server?

**Comment by tanmayv25** [comment]
You can use our `trtexec` from Nvidia's TensorRT container release to convert onnx to trt model. The generated model would be compatible with corresponding release of Triton. For instance, model generated with 22.01 TRT container will work with 22.01 Triton container.
https://catalog.ngc.nvidia.com/orgs/nvidia/containers/tensorrt

**Comment by tanmayv25** [comment]
You can find more about the difference here: https://github.com/onnx/onnx-tensorrt/issues/500
Closing the issue now. Please re-open if you have any other questions.
