### ISSUE TITLE
Experiencing Bottlenecking at Scale - is it related to having a single gRPC connection?

### ISSUE THREAD

**Issue by bryanmcgrane** [triton-inference-server/server#3905]
**Description**
Hello. My team leverages communicating with Triton over gRPC from our server written in Go. We followed the simple example [here](https://github.com/triton-inference-server/client/blob/main/src/grpc_generated/go/grpc_simple_client.go), but we are now experiencing what we believe is a bottleneck due to only establishing a single client on our Go server via this call.

```
client := triton.NewGRPCInferenceServiceClient(conn)
```

We did some digging in the [perf_analyzer](https://github.com/triton-inference-server/client/blob/8125d057fb590f9e9acc202a647130a9dfc686c2/src/c%2B%2B/perf_analyzer/concurrency_manager.h) code and we noticed that in order to implement concurrency, a new Triton client is established per thread.

This has us believing that the correct way to implement high-volume communication to Triton is to have a connection pool between our Go server and Triton. However, none of the examples or documentation points to this, so we figured it would be best to ask the experts here.

**Triton Information**
What version of Triton are you using?
21.09-py3

Are you using the Triton container or did you build it yourself?
Triton container and self-built experience the same issue.

**To Reproduce**
Steps to reproduce the behavior.

We have verified this via the following:
1. Create an application that sends 1000 inference requests as quickly as possible to Triton and make note of the request / second
2. Create three instances of the same application running on separate threads, and note a ~3x throughput

We feel very confident that the bottleneck is not within the application itself, and we believe we have isolated the bottleneck to the client connection.

Our model is a simple resnet18 model.

**Expected behavior**
Documentation to describe the best practice for high-volume communication with Triton

**Comment by tanmayv25** [comment]
Please note the performance best practices as described by grpc team here: https://grpc.io/docs/guides/performance/
Though it does not have many pointers about Go application, you would find the points under General head quite illuminating. 

> (Special topic) Each gRPC channel uses 0 or more HTTP/2 connections and each connection usually has a limit on the number of concurrent streams. When the number of active RPCs on the connection reaches this limit, additional RPCs are queued in the client and must wait for active RPCs to finish before they are sent. Applications with high load or long-lived streaming RPCs might see performance issues because of this queueing.

Specifically in this case may be you are hitting the concurrency limit on the channel?

Triton server is a grpc implementation and any general optimization on client side for any typical gRPC application must benefit client of Triton as well. 

Using multiple clients in perf_analyzer was just for handling the thread-safety issues in the functions of client objects. Internally, they re-use same channels and stubs. We recently found about the concurrency limit over the channel and have added support of channel pool in our client library.

**Comment by bryanmcgrane** [comment]
Thank you for the quick response. I was aware of this gRPC limitation, and I think this is exactly what we're seeing. 

On this comment:
> We recently found about the concurrency limit over the channel and have added support of channel pool in our client library.

Can you point me to where in your client library you added this support? This is very encouraging.

**Comment by bryanmcgrane** [comment]
Actually I think I found the PR here: https://github.com/triton-inference-server/client/pull/55

**Comment by tanmayv25** [comment]
Yes. That's the change I was talking about.

**Comment by bryanmcgrane** [comment]
We are seeing the same result between our server and Triton. Thanks for the help!
