### ISSUE TITLE
Triton tries to use the `tensorflow1` backend for `22.01-tf2-python-py3` image

### ISSUE THREAD

**Issue by narolski** [triton-inference-server/server#3906]
**Description**
When I want to use the image `22.01-tf2-python-py3` instead of ``22.01-py3`, I get:
```
triton_1            | | craft | 1       | UNAVAILABLE: Invalid argument: unable to find 'libtriton_tensorflow1.so' for model 'craft', searched: /model_repository/craft/1, /model_repository/craft, /opt/tritonserver/backends/tensorflow1 |
```
For a `tensorflow_savedmodel` saved with TensorFlow 2.6+.

**Triton Information**
`22.01-tf2-python-py3` and `22.01-py3`

Using the provided containers from NVCR.

**To Reproduce**

Config file:
```
name: "XXX"
platform: "tensorflow_savedmodel"
max_batch_size: 8
input [
  {
    name: "input_2"
    data_type: TYPE_FP32
    dims: [-1, -1, -1, 3]
  }
]
output [
  {
    name: "conv_cls.8"
    data_type: TYPE_FP32
    dims: [-1, -1, -1, 2]
  }
]
instance_group {
  kind: KIND_CPU
  count: 1
}
model_warmup {                                                                        
    name: "CRAFT Warmup"
    batch_size: 1                                                                     
    inputs: {                                                                         
        key: "input_2"                                                                  
        value: {                                                                      
            data_type: TYPE_FP32                                                      
            dims: [1024, 1024, 3]                                                                 
            zero_data: false
        }                                                                             
    }                                                                                 
}  
```

Use the containers from NVCR.

**Expected behavior**

The server should run fine and should not infer that I want to use tensorflow 1 backend. How do I force the usage of tensorflow 2 backend?

**Comment by tanmayv25** [comment]
Did you launch the server with `--backend-config=tensorflow,version=2` ?
https://github.com/triton-inference-server/tensorflow_backend#--backend-configtensorflowversionint

**Comment by narolski** [comment]
@tanmayv25 After adding the flag it did work, thank you! 🎉  Wish this was documented in the main repository 👌

**Comment by fighterhit** [comment]
Hi @tanmayv25 , I noticed that tf1 is not supported since 23.04, but I also get this error when using `tritonserver:23.03-tf2-python-py3 ` with `--backend-config=tensorflow,version=1`, and I found that there is no `/opt/tritonserver/backends/tensorflow1` path.
