### ISSUE TITLE
TorchScript GELU error

### ISSUE THREAD

**Issue by shmahe** [triton-inference-server/server#3909]
**Description**
Loading the model.pt fails with the following error when loading. I've added the steps we took to load the model, is there an issue with that?

I0208 23:28:55.112867 1 server.cc:589]
+------------+---------+-----------------------------------------------------------------------------------------------------+
| Model      | Version | Status                                                                                              |
+------------+---------+-----------------------------------------------------------------------------------------------------+
| bart_model| 1       | UNAVAILABLE: Internal: failed to load model 'bart_model':                                           |
|            |         | Arguments for call are not valid.                                                                   |
|            |         | The following variants are available:                                                               |
|            |         |                                                                                                     |
|            |         |   aten::gelu(Tensor self, bool approximate) -> (Tensor):                                            |
|            |         |   Argument approximate not provided.                                                                |
|            |         |                                                                                                     |
|            |         |   aten::gelu.out(Tensor self, bool approximate, *, Tensor(a!) out) -> (Tensor(a!)):                 |
|            |         |   Argument approximate not provided.                                                                |
|            |         |                                                                                                     |
|            |         | The original call is:                                                                               |
|            |         | /opt/miniconda/lib/python3.7/site-packages/torch/nn/functional.py(1556): gelu                       |
|            |         | /opt/miniconda/lib/python3.7/site-packages/transformers/models/bart/modeling_bart.py(318): forward  |
|            |         | /opt/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py(1090): _slow_forward          |
|            |         | /opt/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py(1102): _call_impl             |
|            |         | /opt/miniconda/lib/python3.7/site-packages/transformers/models/bart/modeling_bart.py(828): forward  |
|            |         | /opt/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py(1090): _slow_forward          |
|            |         | /opt/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py(1102): _call_impl             |
|            |         | /opt/miniconda/lib/python3.7/site-packages/transformers/models/bart/modeling_bart.py(1205): forward |
|            |         | /opt/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py(1090): _slow_forward          |
|            |         | /opt/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py(1102): _call_impl             |
|            |         | /opt/miniconda/lib/python3.7/site-packages/transformers/models/bart/modeling_bart.py(1341): forward |
|            |         | /opt/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py(1090): _slow_forward          |
|            |         | /opt/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py(1102): _call_impl             |
|            |         | /opt/miniconda/lib/python3.7/site-packages/torch/jit/_trace.py(965): trace_module                   |
|            |         | /opt/miniconda/lib/python3.7/site-packages/torch/jit/_trace.py(750): trace                          |
|            |         | <stdin>(1): <module>                                                                                |
|            |         | Serialized   File "code/__torch__/transformers/models/bart/modeling_bart.py", line 137              |
|            |         |     input = torch.add(hidden_states, hidden_states0)                                                |
|            |         |     _75 = (self_attn_layer_norm).forward(input, )                                                   |
|            |         |     input1 = torch.gelu((fc1).forward(_75, ))                                                       |
|            |         |              ~~~~~~~~~~ <--- HERE                                                                   |
|            |         |     input2 = torch.dropout(input1, 0.10000000000000001, False)                                      |
|            |         |     hidden_states1 = torch.dropout((fc2).forward(input2, ), 0.10000000000000001, False)             |
+------------+---------+-----------------------------------------------------------------------------------------------------+

**Triton Information**
21.12

Are you using the Triton container or did you build it yourself?
We are using the Triton container.

**To Reproduce**
1. run docker container for Triton 21.12
2. install transformers, torch
3. load model using BartForConditionalGeneration.from_pretrained(), config file: [triton_issue_config.txt](https://github.com/triton-inference-server/server/files/8035360/triton_issue_config.txt)
4. trace the model using torch.jit.trace(model.pt)
5. save the traced model using torch.jit.save()

**Expected behavior**
Expect the model to load without failure.

**Comment by CoderHam** [comment]
@shmahe the issue looks similar to https://github.com/triton-inference-server/server/issues/3385

Which version of torch are using to produce the model?

**Comment by naor2013** [comment]
If you convert your model to TorchScript in nvcr.io/Nvidia/pytorch:21.12-py3 this issue will be solved.
It's because Nvidia's Pytorch version (used both in Triton and in the Pytorch image I referenced above) is not compatible with "regular" pytorch.
Nvidia did fix it pretty recently so it would probably be solved in Triton 22.02 (if not, maybe 22.03) but instead of waiting, just doing what I said above should fix it for you.

**Comment by shmahe** [comment]
@CoderHam The torch version is torch-1.10.2-cp37

@naor2013 Thanks, will try this!

**Comment by shmahe** [comment]
@naor2013 's suggestion worked, thanks for the help!
