### ISSUE TITLE
UNAVAILABLE: Internal: trt failed to set binding dimension to [8,10,128] for input 'input_id' for paraRecognition

### ISSUE THREAD

**Issue by expresschen** [triton-inference-server/server#3919]
**Description**

**Triton Information**
What version of Triton are you using?

Are you using the Triton container or did you build it yourself?

**To Reproduce**
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**

**Comment by tanmayv25** [comment]
The error means that the trt plan does not support the shape [8,10,128].
You can try polygraphy to view what dimensions are supported. 

Provide the details in the issue template if you need further assistance.
