### ISSUE TITLE
Build image "tritonserver_qa" failed  due to “Dockerfile.QA” references to a non-existing folder

### ISSUE THREAD

**Issue by yaoyunda** [triton-inference-server/server#3924]
**Description**
After build of image "tritonserver", follow all steps of [instructions](urlhttps://github.com/triton-inference-server/server/blob/main/docs/test.md#:~:text=Blame-,Testing%20Triton,-Currently%20there%20is) to build image" tritonserver_qa".
Build failed with error:
cp: cannot stat 'qa/L0_tf_image_models/.': No such file or directory
Exame the qa folder, there is no folder "L0_tf_image_models"

View the file "Dockerfile.QA", it has two lines:
    mkdir -p qa/L0_tf_image_models_tf2 && \
    cp -r qa/L0_tf_image_models/. qa/L0_tf_image_models_tf2 && \
Modify this file to remove above two lines, the image is successfully build.

**Triton Information**
What version of Triton are you using?
r21.12

Are you using the Triton container or did you build it yourself?
build the image by myself

**To Reproduce**
Steps to reproduce the behavior.

cd /data/triton/server
sudo git clone --single-branch --depth=1 -b r21.12 https://github.com/triton-inference-server/client.git clientrepo

sudo chmod -R 777 /data/triton/server/qa
cd /data/triton/server/qa/common
sudo chmod -R 777 /data/tmp
./gen_qa_model_repository
sudo chmod -R 777 /data/tmp
./gen_qa_custom_ops

cd /data/triton/server
sudo docker build -t tritonserver_sdk -f Dockerfile.sdk .
sudo docker build -t tritonserver_qa -f Dockerfile.QA .

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**

Provide the folder "qa/L0_tf_image_models_tf2" if it is needed
or
Remove the two lines in the file "Dockerfile.QA"

**Comment by CoderHam** [comment]
The issue was introduced by https://github.com/triton-inference-server/server/commit/fe917fa5b1d17c2bc2e36c92affd1ef254d3e2ce

We should not be copying the L0_tf_image_models for when it does not exist (It does not exist

**Comment by CoderHam** [comment]
@yaoyunda closed with the aforementioned [fix](https://github.com/triton-inference-server/server/commit/523e20da696266e0b112b21c5a32ec9066905c90). You can cherry-pick the same onto your older branch to resolve your issue

**Comment by yaoyunda** [comment]
Thanks @CoderHam , question: I use git to clone the code from baranch r21.12, is the file Dockerfile.QA still the same with these 2 extra lines? basically I am using the code directly from github to build, does not fork it.

**Comment by CoderHam** [comment]
No the Dockerfile in r21,12 is not the same as main. You will need to apply the patch after cloning.
