### ISSUE TITLE
Test “L0_trt_dla” failed in branch r21.12 due to missing model “resnet50_plan”

### ISSUE THREAD

**Issue by yaoyunda** [triton-inference-server/server#3927]
**Description**
Follow the instructions:
go to folder "qa/L0_trt_dla" and run test as:
bash -x test.sh
test failed with error: Request for unknown model 'resnet50_plan' is not found

The file "~/server/qa/L0_trt_dla/dla_test.py" contains a line :
model_name = "resnet50_plan"

The file ~/server/qa/L0_trt_dla/test.sh contains a line :
cp -r $DATADIR/trt_dla_model_store/resnet50_plan models/.

**Triton Information**
What version of Triton are you using?
R21.12
Are you using the Triton container or did you build it yourself?
Build by myself
**To Reproduce**
Steps to reproduce the behavior.
Build the images tritonserver and tritonserver_qa, 
start the container: docker run --gpus=all -it --rm -v /data/tmp:/inferenceserver tritonserver_qa 
go to folder "qa/L0_trt_dla" and run test as:
bash -x test.sh

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**
The test is passed without error.

**Comment by Tabrizian** [comment]
The models required for some of the tests are not publicly available. @CoderHam Are you aware of any method to generate this specific model?

**Comment by CoderHam** [comment]
@yaoyunda the TRT DLA model cannot be published publicly at the moment. Are you trying to test dla support?

**Comment by yaoyunda** [comment]
@CoderHam ,
I tried to build and run all the tests available. is there any doc to specify the scope of tests.  currently about 50+ CI test failed from all these 100+ tests.

**Comment by CoderHam** [comment]
@yaoyunda as a general thumb rule you can skip all the tests that do not use the generated models. I am closing this ticket for now since the L0_trt_dla test model will not be available publicly for now.
