### ISSUE TITLE
The error means that the trt plan does not support the shape [16,128].

### ISSUE THREAD

**Issue by expresschen** [triton-inference-server/server#3928]
The error means that the trt plan does not support the shape [8,10,128].
You can try polygraphy(https://github.com/NVIDIA/TensorRT/tree/main/tools/Polygraphy/examples/cli/inspect/01_inspecting_a_tensorrt_network) to view what dimensions are supported. 

Provide the details in the issue template if you need further assistance.

_Originally posted by @tanmayv25 in https://github.com/triton-inference-server/server/issues/3919#issuecomment-1036429833_

**Comment by expresschen** [comment]
GPU:P40
Tensorrt version:8.2.18
cuda:10.2
triton-inference-server:[21](http://nvcr.io/nvidia/tritonserver:21.12-py3)
polygraphy:
 ==== TensorRT Network ====
    Name: Unnamed Network 0 | Explicit Batch Network
    
    ---- 3 Network Input(s) ----
    {input_id [dtype=int32, shape=(-1, 128)],
     attention_mask [dtype=int32, shape=(-1, 128)],
     token_type_ids [dtype=int32, shape=(-1, 128)]}
    
    ---- 1 Network Output(s) ----
    {output [dtype=float32, shape=(-1, 128, 384)]}
step reproduce:
from transformers import AutoTokenizer,AutoModel,AutoConfig                         
import onnx                                                                         
import torch                                                                        
import torch.nn as nn                                                                                                                                          
class simpleBert(nn.Module):                                                        
    def __init__(self):                                                             
        super(simpleBert, self).__init__()                                          
        config = AutoConfig.from_pretrained("./chinese_roberta_L-6_H-384_A-12_K-128"
        self._petrained_language_model = AutoModel.from_config(config)              
    def forward(self,input_id,attention_mask,token_type_ids):                       
        out = self._petrained_language_model(input_ids=input_id, attention_mask=atte
        return out                                                                  
                                                                                                                              
model = simpleBert()                                                                                                                              
model.to("cuda")                                                                    
a = [[101, 100, 782, 3152, 3221, 5125, 2506, 4638, 117, 4906, 2110,                 
       3221, 1438, 3352, 4638, 100, 4638, 2692, 2590, 3221, 782, 5102,              
       4638, 5632, 712, 1158, 3173, 2590, 5335, 3221, 5125, 2506, 4638,             
       117, 5445, 4906, 2110, 3221, 782, 5102, 3255, 1213, 2768, 3362,              
       4638, 772, 4289, 8024, 1071, 3221, 3302, 1218, 754, 782, 5102,               
       4638, 117, 2400, 679, 833, 2519, 3302, 782, 5102, 511, 1728,                 
       3634, 117, 2769, 812, 6206, 3297, 7361, 2428, 1355, 2916, 782,               
       3152, 4415, 6389, 117, 4415, 6237, 4906, 2825, 8024, 1355, 2245,             
       1962, 4906, 2825, 8024, 6602, 750, 4906, 2110, 2697, 2658, 511,              
       102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,                                           
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,                                             
       0, 0, 0, 0, 0, 0, 0],[101, 2769, 812, 833, 6371, 711, 2825, 3318, 2190, 4495,
       3221, 671, 4905, 2904, 2773, 117, 2154, 2586, 3300, 671, 1921,               
       2769, 812, 833, 6158, 4906, 2110, 2519, 3302, 117, 852, 752,                 
       2141, 677, 4906, 2825, 738, 3221, 671, 4905, 4495, 1462, 117,                
       2769, 812, 6206, 6602, 750, 4906, 2825, 2658, 2697, 511, 2825,               
       3318, 2190, 2126, 2136, 2190, 4495, 1462, 6963, 3300, 4916, 3353,            
       4638, 2692, 721, 511, 671, 3175, 7481, 117, 4906, 2825, 5314,                
       2769, 812, 4638, 4495, 3833, 2372, 3341, 749, 2342, 1920, 4638,              
       912, 1164, 2595, 117, 2990, 7770, 782, 5102, 3833, 1220, 4638,               
       3126, 4372, 117, 1369, 671, 3175, 7481, 117, 4906, 2825, 3221,               
       1392, 1744, 5341, 1394, 1744, 1213, 4993, 751, 4638, 7028, 6206,             
       6598, 3975, 1469, 1213, 7030, 511, 102],                                     
     [101, 100, 782, 3152, 3221, 5125, 2506, 4638, 117, 4906, 2110,                 
       3221, 1438, 3352, 4638, 100, 4638, 2692, 2590, 3221, 782, 5102,              
       4638, 5632, 712, 1158, 3173, 2590, 5335, 3221, 5125, 2506, 4638,             
       117, 5445, 4906, 2110, 3221, 782, 5102, 3255, 1213, 2768, 3362,              
       4638, 772, 4289, 8024, 1071, 3221, 3302, 1218, 754, 782, 5102,               
       4638, 117, 2400, 679, 833, 2519, 3302, 782, 5102, 511, 1728,                 
       3634, 117, 2769, 812, 6206, 3297, 7361, 2428, 1355, 2916, 782,               
       3152, 4415, 6389, 117, 4415, 6237, 4906, 2825, 8024, 1355, 2245,             
       1962, 4906, 2825, 8024, 6602, 750, 4906, 2110, 2697, 2658, 511,              
       102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,                                           
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,                                             
       0, 0, 0, 0, 0, 0, 0],[101, 2769, 812, 833, 6371, 711, 2825, 3318, 2190, 4495,
       3221, 671, 4905, 2904, 2773, 117, 2154, 2586, 3300, 671, 1921,               
       2769, 812, 833, 6158, 4906, 2110, 2519, 3302, 117, 852, 752,                 
       2141, 677, 4906, 2825, 738, 3221, 671, 4905, 4495, 1462, 117,                
       2769, 812, 6206, 6602, 750, 4906, 2825, 2658, 2697, 511, 2825,               
       3318, 2190, 2126, 2136, 2190, 4495, 1462, 6963, 3300, 4916, 3353,            
       4638, 2692, 721, 511, 671, 3175, 7481, 117, 4906, 2825, 5314,                
       2769, 812, 4638, 4495, 3833, 2372, 3341, 749, 2342, 1920, 4638,              
       912, 1164, 2595, 117, 2990, 7770, 782, 5102, 3833, 1220, 4638,               
       3126, 4372, 117, 1369, 671, 3175, 7481, 117, 4906, 2825, 3221,               
       1392, 1744, 5341, 1394, 1744, 1213, 4993, 751, 4638, 7028, 6206,             
       6598, 3975, 1469, 1213, 7030, 511, 102]                                      
     ]                                                                              
b = [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,          
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,         
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,         
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,         
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,         
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],                                      
      [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,         
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,         
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,         
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,         
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,         
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,         
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,         
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,         
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,         
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],                                      
      [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,         
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,         
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,         
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,         
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,         
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]                                       
     ]                                                                              
c = [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,          
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,         
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,         
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,         
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,         
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],                                      
      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,         
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,         
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,         
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,         
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,         
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],                                      
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,          
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,         
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,         
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,         
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,         
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],                                      
      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,         
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,         
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,         
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,         
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,         
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]                                      
input_id = torch.LongTensor(a).cuda()                                               
attention_mask = torch.LongTensor(b).cuda()                                         
token_type_ids = torch.LongTensor(c).cuda()                                         
torch.onnx.export(model, (input_id, attention_mask, token_type_ids), "test.onnx",                             
                  input_names=['input_id', 'attention_mask', 'token_type_ids'],                               
                  output_names=['output'], opset_version=11,                                                  
                  dynamic_axes={'input_id': [0], 'attention_mask': [0], 'token_type_ids': [0], 'output': [0]})
import tensorrt as trt                                                              
print(trt.__file__)                                                                 
TRT_LOGGER = trt.Logger(trt.Logger.VERBOSE)                                         
import os                                                                           
def get_engine(max_batch_size=16, onnx_file_path="./test.onnx", engine_file_path="",
               save_engine=True):                                                   
    """Attempts to load a serialized engine if available, otherwise builds a new Ten
    explicit_batch = 1 << (int)(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)  #
                                                                                    
    def build_engine(max_batch_size, save_engine):                                  
        """Takes an ONNX file and creates a TensorRT engine to run inference with"""
        builder = trt.Builder(TRT_LOGGER)                                           
        network = builder.create_network(explicit_batch)                            
        parser = trt.OnnxParser(network, TRT_LOGGER)                                
        runtime = trt.Runtime(TRT_LOGGER)                                           
        # Parse model file                                                          
        if not os.path.exists(onnx_file_path):                                      
            quit('ONNX file {} not found'.format(onnx_file_path))                   
                                                                                    
        print('Loading ONNX file from path {}...'.format(onnx_file_path))           
        model = open(onnx_file_path,'rb')                                           
        print('Beginning ONNX file parsing')                                        
        if not parser.parse(model.read()):                                          
            for error in range(parser.num_errors):                                  
                print(parser.get_error(error))                                      
        print('Completed parsing of ONNX file')                                     
        assert network.num_layers > 0, 'Failed to parse ONNX model. Please check if 
        profile = builder.create_optimization_profile()                             
        profile.set_shape("input_id", (1, 128), (4,128), (16,128))                  
        profile.set_shape("attention_mask", (1, 128), (4,128), (16,128))            
        profile.set_shape("token_type_ids", (1, 128), (4,128), (16,128))            
        # profile.set_shape("output", (1, 4, 4), (4, 5, 4), (16, 10, 4))            
        config = builder.create_builder_config()                                    
        config.max_workspace_size = (1 << 20)*8*1024  # 256MiB                      
        builder.max_batch_size = max_batch_size                                     
        if fp16_mode:                                                               
            config.set_flag(trt.BuilderFlag.FP16)                                   
        elif int8_mode:                                                             
            config.set_flag(trt.BuilderFlag.INT8)                                   
        else:                                                                       
            config.set_flag(trt.BuilderFlag.REFIT)                                  
        config.add_optimization_profile(profile)                                    
                                                                                    
        flag = builder.is_network_supported(network, config)                        
        print('flag', flag)                                                         
                                                                                    
        print('Building an engine from file {}; this may take a while...'.format(onn
        plan = builder.build_serialized_network(network, config)                    
        engine = runtime.deserialize_cuda_engine(plan)                              
        print("Completed creating Engine")                                          
        if save_engine:                                                             
            with open(engine_file_path, "wb") as f:                                 
                f.write(plan)                                                       
        return engine                                                               
    if os.path.exists(engine_file_path):                                            
        # If a serialized engine exists, load it instead of building a new one.     
        print("Reading engine from file {}".format(engine_file_path))               
        with open(engine_file_path, "rb") as f, trt.Runtime(TRT_LOGGER) as runtime: 
            return runtime.deserialize_cuda_engine(f.read())                        
    else:                                                                           
        return build_engine(max_batch_size, save_engine)                                                         
get_engine(engine_file_path="test.trt")

**Comment by expresschen** [comment]
In the output log, I found this error message again
E0214 10:55:10.085525 1 logging.cc:43] 1: [graphContext.h::MyelinGraphContext::24] Error Code 1: Myelin (Compiled against cuBLAS 10.2.2.0 but running against cuBLAS 11.7.3.0.)
I0214 10:55:10.085570 1 logging.cc:49] Could not set default profile 0 for execution context. Profile index must be set explicitly.
I0214 10:55:10.085593 1 logging.cc:49] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +104, now: CPU 0, GPU 1341 (MiB)
E0214 10:55:10.085632 1 logging.cc:43] 3: [executionContext.cpp::setBindingDimensions::924] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setBindingDimensions::924, condition: mOptimizationProfile >= 0 && mOptimizationProfile < mEngine.getNbOptimizationProfiles()
)
@tanmayv25

**Comment by tanmayv25** [comment]
> E0214 10:55:10.085525 1 logging.cc:43] 1: [graphContext.h::MyelinGraphContext::24] Error Code 1: Myelin (Compiled against cuBLAS 10.2.2.0 but running against cuBLAS 11.7.3.0.)

Looks like there is a discrepancy in the CUDA stack for the build and runtime systems. Did you run the above model generation script on corresponding tensorrt container from NGC? It should be tensorrt:21.12-py3 in your case.

**Comment by expresschen** [comment]
The container version I use is 21.12-py3, so the version of tensorrt used locally is the same as the version used by the container. But I use cuda10.2 locally, but cuda11.5 used in the container, is this the reason. But cuda11.5 does not have a GPU version corresponding to pytorch.

**Comment by tanmayv25** [comment]
Sorry for the delayed response.

> But I use cuda10.2 locally, but cuda11.5 used in the container, is this the reason.

From the error message it does appear that is the case. Is it not possible to generate the TRT engine within `tensorrt:21.12-py3` container?

**Comment by expresschen** [comment]
Yes，i solved it by reinstall cuda11.5
