### ISSUE TITLE
Same output for every batches when using shared memory

### ISSUE THREAD

**Issue by remib-proovstation** [triton-inference-server/server#3929]
**Description**
When using shared memory in python client with a object detection model in onnx backend, when extracting the results from the inference output on the shared memory, I obtain number_batches times the same result (the one from the last request). ​

**Triton Information**
Triton 21.10 from docker
Python client from `pip install tritonclient[all]`

_Are you using the Triton container or did you build it yourself?_
Using Triton from a custom container from base triton.

**To Reproduce**

The client/server interaction works fine when I don’t use shared memory (using simple http protocol), and I’m able to send 15 batches of images to the server, and then collect 15 different results from the server.

The problem arises when I try to switch to shared memory : the model receives correctly the 15 different batches, but when I collect the inference responses, with:
```
for response in responses:
    infer_outputs = []
    # for each output of the model
    for output in model_outputs:
        result = response.get_output(output_name)
        
        # this will always return the same result, the one from the last request
        output_data = shm.get_contents_as_numpy(
            output_triton_shm_handle,
            result.datatype,
            result.shape)
```
 I have 15 times the same result, the one from the last request processed by the model.

Simplified version of my client code:

```import tritonclient.utils.shared_memory as shm

# for each input, and each output,  create and register a shared memory region using :

shm_handle = shm.create_shared_memory_region(
        triton_shm_name,
        triton_shm_key,
        byte_size
    )

client.register_system_shared_memory(
        triton_shm_name,
        triton_shm_key,
        byte_size,
    )
# we then store the handles for each inputs/outputs

...

async_requests = []
# iterate on the image batches from a pytorch dataloader
for batch in dataloader:
    # do some preprocessing

    ...

    # convert torch Tensor to numpy
    np_batch = batch.numpy()

    # Put input data values into shared memory
    shm.set_shared_memory_region(input_triton_shm_handle, [np_batch])

    # definition of this function is below
    inputs, outputs = request_generator(np_batch)
    # send the request(s) asynchronously, 
    async_requests.append(
            client.async_infer(
                model_name=model_name,
                inputs=inputs,
                request_id=str(sent_count),
                model_version=model_version,
                outputs=outputs,
            )
    )

# wait for the server to complete request, then get inference responses
responses = []
for async_request in async_requests:
    responses.append(async_request.get_result(timeout=20))

for response in responses:
    infer_outputs = []
    # for each output of the model
    for output in model_outputs:
        result = response.get_output(output_name)
        
        # this will always return the same result, the one from the last request
        output_data = shm.get_contents_as_numpy(
            output_triton_shm_handle,
            result.datatype,
            result.shape)
            
        
        infer_outputs.append(output_data)
        

def request_generator(self, batched_image_data):
    # Creates infer requested output object for each input using :
    inputs.append(httpclient.InferInput(input_name, batched_image_data.shape, input_datatype))
    inputs[-1].set_shared_memory(
        triton_shm_name,
        byte_size,
    )
    # Creates infer requested output object for each output using :
    outputs.append(httpclient.InferRequestedOutput(output_name, binary_data=True))
    outputs[-1].set_shared_memory(
        triton_shm_name,
        byte_size,
    )
    return inputs, outputs
```
The configuration of the model:

```name: "standarddamages_ps"
  backend: "onnxruntime"
  max_batch_size: 16
  input [
    {
      name: "image_tensor"
      data_type: TYPE_FP32
      format: FORMAT_NCHW
      dims: [ 1, 512, 512]
    }
  ]
  output [
    {
      name: "boxes"
      data_type: TYPE_FP32
      dims: [ 1000, 4 ]
    }
  ]
  output [
    {
      name: "classes"
      data_type: TYPE_FP32
      dims: [ 1000 ]
    }
  ]
  output [
      {
        name: "scores"
        data_type: TYPE_FP32
        dims: [ 1000 ]
      }
    ]
```

**Expected behavior**

I should obtain a different result for each batch, as it is the case when not using shared memory

**Comment by matthewkotila** [comment]
Hi @remib-proovstation, sorry you're running into this issue. Thanks for the detailed information. We are looking into the issue 👍.

**Comment by CoderHam** [comment]
@remib-proovstation You are reusing the same shared memory region and sending async requests without a timeout between requests. If you want to use the same shared memory region you must ensure there is a single request in flight that uses the specific region.

**Comment by remib-proovstation** [comment]
@CoderHam thank you for your answer. I was indeed getting the feeling that a single shm region for async output could not work. I have then three questions:
1)  why does this not seems to happen for my inputs, since I'm sending async request on the shm region for my input too ?
2)  I implemented my pipeline based on the example from triton client, where we all waiting for all the responses from the server, then we extract the content. Do you have a implementation or pseudo code explainging how one could implement async inference request with one or several memory region ? I don't understand how to "ensure there is a single request in flight that uses the specific region"
3) Should I use one shm region for each batch ? I didn't think of it because I didn't need it with the inputs, and it wasn't shown in the examples. I sounds simpler that the "single request in flight" method, but maybe there problems with this method I don't yet understand.

Thank you in advance for your precious help on the matter.

**Comment by CoderHam** [comment]
@remib-proovstation if you see this problem with sync inference requests (please shared the repro code) it might be a bug. I can file a ticket to look into this. 

> 1. why does this not seems to happen for my inputs, since I'm sending async request on the shm region for my input too ?

It should occur for inputs as well. 

> 2. I implemented my pipeline based on the example from triton client, where we all waiting for all the responses from the server, then we extract the content. Do you have a implementation or pseudo code explainging how one could implement async inference request with one or several memory region ? I don't understand how to "ensure there is a single request in flight that uses the specific region"

* Do not use the exact same shared memory region, rather use a small section of a large shared memory region. It is the users responsibility to maintain the lifecycle of these regions and use them correctly. Clearly reusing the same shared memory region entirely between multiple requests will lead to issues. 

* Async inference is tricky with shared memory because you need to read o/p before re-using that shared memory region. I would recommend implementing a callback or a utility to do the same.

> Should I use one shm region for each batch ? I didn't think of it because I didn't need it with the inputs, and it wasn't shown in the examples. I sounds simpler that the "single request in flight" method, but maybe there problems with this method I don't yet understand.


You CAN create a single large shared memory region and use sections of this region for I/O. These sections should not overlap and the same sections of these regions. Refer to this example where 1 shared memory region hold multiple inputs and later another shared memory region holds multiple outputs.

**Comment by remib-proovstation** [comment]
Using a shared memory region of size number_of_batch_in_dataloader * size_of_batch, and navigating in this shm region with offset works well (but need the PR mentionned above to be merged).

Alternatively, using a specific shm region of the size of a batch for each batch works well. I keep the handles in a dictionary along with the bacth id. I didn't see any overhead from the creation and registration of all those small shm regions. It doesn't need the PR mentionned above.

I'm closing this issue since those two solutions works well in async mode.

The python client example of multiple image batch with shared memory might need a rework though.

Thanks for your time and help @CoderHam !
