### ISSUE TITLE
torchscripted model fails to load on triton server

### ISSUE THREAD

**Issue by vladimir-sverdlov** [triton-inference-server/server#3937]
**Description**
When creating a torchscripted model and exporting to triton backend, when it tries to load it it fails due to a None attribute.

```
UNAVAILABLE: Internal: failed to load model 'model_for_triton':  |                                                                                            │
│ kfserving-container |                             |         | Unknown type name 'NoneType':                                               |                                                                                            │
│ kfserving-container |                             |         | Serialized   File "code/__torch__/torch/nn/modules/conv.py", line 7         |                                                                                            │
│ kfserving-container |                             |         |   bias : Optional[Tensor]                                                   |                                                                                            │
│ kfserving-container |                             |         |   training : bool                                                           |                                                                                            │
│ kfserving-container |                             |         |   _is_full_backward_hook : NoneType                                         |                                                                                            │
│ kfserving-container |                             |         |                            ~~~~~~~~ <--- HERE                               |                                                                                            │
│ kfserving-container |                             |         |   transposed : bool                                                         |                                                                                            │
│ kfserving-container |                             |         |   _reversed_padding_repeated_twice : List[int]
```

**Triton Information**
What version of Triton are you using? 21.02-py3

Are you using the Triton container or did you build it yourself? nvcr.io/nvidia/tritonserver

**To Reproduce**
Steps to reproduce the behavior.
create a torch model, ours is based on torch.nn.modules.module.Module
script it, save and then export to triton:

```
import torch
from torch.jit import script
model = create_model(block=DEFAULT_RESNET_BLOCK,
                                                           layers=DEFAULT_NETWORK_LAYERS_LIST,
                                                           num_classes=num_classes)

model_scripted = script(model)
torch.jit.save(model_scripted, "/Users/my_user_name/model.pt")
```
the exported model is saved by this layout:

```
TorchScript Models
An TorchScript model is a single file that by default must be named model.pt. This default name can be overridden using the default_model_filename property in the model configuration. It is possible that some models traced with different versions of PyTorch may not be supported by Triton due to changes in the underlying opset.

A minimal model repository for a TorchScript model is:

  <model-repository-path>/
    <model-name>/
      config.pbtxt
      1/
        model.pt
```
configuration file:
```

platform: "pytorch_libtorch"
max_batch_size: 1
input [
  {
    name: "INPUT__0"
    data_type: TYPE_FP32
    dims: [3,224,224]
  }
]
output [
  {
    name: "OUTPUT__0"
    data_type: TYPE_FP32
    dims: [4519]
  }
]
instance_group [
    {
        count: 1
        kind: KIND_CPU
    }
]
```
Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
torch version==1.9.1
torchvision==0.10.1

**Expected behavior**
Export and load should work with torch version 1.6.0
being able to load a torchscripted model with version > 1.6 using triton server.

**Comment by CoderHam** [comment]
@vladimir-sverdlov can you share the pytorch code for the model or a repro?

Additionally try tracing the model in with the NGC 22.02 PyTorch container (has Pytorch v1.11.0) and try that model?

**Comment by CoderHam** [comment]
@vladimir-sverdlov you should first try to run the torchscript model outside Triton (in native PyTorch) and see if you can reproduce the error. If so, the issue may be from the way the model was traced/scripted. (Occurs outside of Triton)

Sometimes the issue occurs because the model was traced with an old version of PyTorch. I recommend you to produce the torchscript model inside the NGC 22.02 PyTorch container (nvcr.io/nvidia/pytorch) and verify if that resolves your issue.

**Comment by vladimir-sverdlov** [comment]
@CoderHam thanks for your suggestions, we were able to load the torchscript model when using torch version 1.6.0
a new issue we encounter now, is that the same model(the one that was created with the 1.6.0 torch version) produces different results when ran on a cpu&gpu machines vs the triton run, we get different results with a much lower confidence.
any idea to what may be causing this?
as mentioned before, we are using the triton inference server v21.02-py3 for our need for multiple models.

**Comment by CoderHam** [comment]
@vladimir-sverdlov the issue you described appears to be inside PyTorch. The model should not have different results between CPU / GPU. You should raise an issue with [PyTorch](https://github.com/pytorch/pytorch).

Since the issue is not inside Triton, can I close this issue?

**Comment by vladimir-sverdlov** [comment]
I think I didn't phrase myself correctly.
I get the same results when I run on cpu or GPU machines. When I run on triton GPU, I get different results

**Comment by CoderHam** [comment]
> I get the same results when I run on cpu or GPU machines.

Is this with the C++ API or the python API for PyTorch? If you are using the python API then I recommend using the C API so that comparison is apples to apples. 

> When I run on triton GPU, I get different results

Are you running a single instance or multiple instances of the model? How different (MSE or some quantifiable error rate) is the results?

Do you see the difference even running on Triton with device as CPU ?

**Comment by vladimir-sverdlov** [comment]
hey @CoderHam. thanks for being responsive and very helpful. 
closing this issue as we were able to resolve it, it came down to the model being scripted which gave us inconsistent results.
