### ISSUE TITLE
Docs for building custom TF backend are obsolete

### ISSUE THREAD

**Issue by lminer** [triton-inference-server/server#3940]
If I run `nvcr.io/nvidia/tensorflow:22.01-tf2-py3`

And then run the following command

```
./nvbuild.sh --triton
```

I get:

```
UNKNOWN OPTION --triton
Run ./nvbuild.sh -h for help
```

**Comment by Tabrizian** [comment]
You are correct. Looks like the option no longer exist in 22.01. I have filed a ticket to fix this.

**Comment by lminer** [comment]
Do you know when it was removed? Even in 21.10 I'm getting this issue.

**Comment by rmccorm4** [comment]
Docs have been updated in this PR: https://github.com/triton-inference-server/tensorflow_backend/pull/47. Closing
