### ISSUE TITLE
[Question] Details examples for how to use the rate limiter?

### ISSUE THREAD

**Issue by luvwinnie** [triton-inference-server/server#3942]
Hello, I'm using the triton inference server for deploying the models, I have about 11 models to deploy and I need to control the request since I'm using the ONNX model which dynamically allocate the memories, I don't understand about the "number" assign on R1,R2,R3 and etc, so called "resource" in this [page](https://github.com/triton-inference-server/server/blob/main/docs/rate_limiter.md#:~:text=Rate%20limiter%20manages%20the%20rate,to%20allow%20cross%2Dmodel%20prioritization.) Is that mean for example, R1: 4 mean the model will handle 4 requests async at once?

Can anyone provide a detail example let say simple resnet18 model and how should I calculate correctly with the GPU memories with respective config files for each of my 11 models? I search a lot on google no one write about the rate limiter therefore I asked at here.

**Comment by Tabrizian** [comment]
> on R1,R2,R3 and etc, so called "resource" in this [page](https://github.com/triton-inference-server/server/blob/main/docs/rate_limiter.md#:~:text=Rate%20limiter%20manages%20the%20rate,to%20allow%20cross%2Dmodel%20prioritization.) Is that mean for example, R1: 4 mean the model will handle 4 requests async at once?

No, this means that from the pool of all the resources (global or per-device) this model requires 4 R1 resources. For example, if you have 10 R1 resources for a device in total, and you have 3 instances of model A, and each instance execution requires 4 of R1 resources, it means that at the same time only two of the instances of model A will be executed at the same time. 

> Can anyone provide a detail example let say simple resnet18 model and how should I calculate correctly with the GPU memories with respective config files for each of my 11 models? I search a lot on google no one write about the rate limiter therefore I asked at here.

For making sure that you do not exceed the GPU memory usage, I think you can follow the procedure below:

1. Calculate the total memory of your GPU 
2. Calculate the memory usage of each of the models when only loaded to the Triton (not serving any inference request)
3. Subtract the load-only GPU memory usage of all the models from the total GPU memory (let's call this value _m_).
4. Now for obtaining the numbers for R1, you need to find out the maximum memory usage of each of the model instances.
5. Set the R1 values for each model instance based on the numbers obtained in step 4.
6. Set the total per device R1 value to _m_. 

Model Analyzer can also help with some of the memory profiling steps required for this:
https://github.com/triton-inference-server/model_analyzer

(@tanmayv25 feel free to correct me if I'm wrong here).

**Comment by tanmayv25** [comment]
Iman has described the use case accurately. Triton does not monitor memory as such while scheduling. Setting the resource counts as Iman described, a user can imitate the R1 as system memory. It's upon user to attach meaning to a named resource.

**Comment by Tabrizian** [comment]
Closing the ticket as the question has been answered.

**Comment by luvwinnie** [comment]
@Tabrizian Thank you for answering! Just want to clarify the step 3 which is the remains memory after loaded models, this value "m" does it have any units for it for example GB/MB and etc?

**Comment by Tabrizian** [comment]
It can be in either MB/Bytes you just need to be consistent and use the same unit for all the steps.

**Comment by leloykun** [comment]
What do R1, R2, R3, R4 mean? Are these unique to the device?
