### ISSUE TITLE
[client c++] build script uses system libcurl instead of own third-party/curl

### ISSUE THREAD

**Issue by HarHarLinks** [triton-inference-server/server#3948]
**Description**
build script uses system libcurl instead of own third-party/curl
the former is too old, leading to this error:
```
src/c++/library/http_client.cc:1514:26: error: ‘CURLOPT_UPLOAD_BUFFERSIZE’ was not declared in this scope; did you mean ‘CURLOPT_BUFFERSIZE’?
 1514 |   curl_easy_setopt(curl, CURLOPT_UPLOAD_BUFFERSIZE, buffer_byte_size);
```

`third-party/curl/lib64/libcurl.a` and alongside it headers with the referenced `CURLOPT_UPLOAD_BUFFERSIZE` are present, but not used.

related: #3922

**Triton Information**
clients r22.01

**To Reproduce**
Platform: CentOS 7.9.2009, cmake 3.21.1, GNU Make 3.82, icc (ICC) 2021.5.0 20211109

```
git clone -b r22.01 https://github.com/triton-inference-server/client

mkdir -p client/build && cd client/build

cmake -DCMAKE_INSTALL_PREFIX=`pwd`/install -DTRITON_ENABLE_CC_HTTP=ON -DTRITON_ENABLE_CC_GRPC=ON -DTRITON_ENABLE_PERF_ANALYZER=ON -DTRITON_ENABLE_GPU=ON -DTRITON_ENABLE_EXAMPLES=ON -DTRITON_ENABLE_TESTS=ON -DTRITON_COMMON_REPO_TAG=r22.01 -DTRITON_THIRD_PARTY_REPO_TAG=r22.01 -DTRITON_CORE_REPO_TAG=r22.01 -DTRITON_BACKEND_REPO_TAG=r22.01 ..

make cc-clients
```

It will pull and build lots of third party libraries, including curl. Then when it starts to build the triton clients `Found CURL: /usr/lib64/libcurl.so (found version "7.29.0")` which is the (outdated in terms of triton requirements) system curl.

**Expected behavior**
It builds

**Comment by HarHarLinks** [comment]
I think you need to require a minimum curl version in the build script https://github.com/triton-inference-server/client/blob/f0f2b89b3b8418a0a79a8dd60329a8b99489268b/src/c%2B%2B/CMakeLists.txt#L86

CURLOPT_UPLOAD_BUFFERSIZE was added in 7.62.0 https://curl.se/libcurl/c/CURLOPT_UPLOAD_BUFFERSIZE.html

**Comment by tanmayv25** [comment]
We must use third-party curl. This looks like a bug. https://github.com/triton-inference-server/client/blob/main/CMakeLists.txt#L119

**Comment by Tabrizian** [comment]
Filed a ticket for this.

**Comment by CoderHam** [comment]
@HarHarLinks are you facing this issue when you are building on your machine directly instead of inside a docker using the Dockerfile.sdk?

**Comment by HarHarLinks** [comment]
Yes, I am building the client library outside the container to integrate it with an existing application.

I am working on a High-Performance Computing Cluster which runs on Centos 7 as described; thus I have no root access (nor `apt`) to install dependencies system-wide. I assume libcurl is preinstalled by the distro or my admins due to being a common dependency.

Your make system does try to ship its own libcurl as i mentioned, however there appears to be a defect where it finds the system libcurl first and prefers that.

Please let me know if I can provide any more info.

**Comment by CoderHam** [comment]
@HarHarLinks can you try building with this change: https://github.com/triton-inference-server/client/pull/75
It should skip the system paths and use the third-party curl path for the Triton client build

**Comment by CoderHam** [comment]
@HarHarLinks did you try to use the patch to fix your issue?

**Comment by CoderHam** [comment]
Closed with the aforementioned [PR](https://github.com/triton-inference-server/client/pull/75)

**Comment by HarHarLinks** [comment]
> @HarHarLinks did you try to use the patch to fix your issue?

Tomorrow is the earliest I can try this.

**Comment by HarHarLinks** [comment]
appears to be working now.

**Comment by prm-james-hill** [comment]
(Sorry for the necromancy)
Is the reason for "We must use third-party curl" explained anywhere? I'm trying to use my own version of libcurl to avoid linkage complexity. I don't see any patch files for curl in the third-party repo so I'm hoping maybe it's just pinning a minimum version.
