### ISSUE TITLE
inference queue time high

### ISSUE THREAD

**Issue by llustc** [triton-inference-server/server#3953]
We are using triton to deploy gpu service, the queue waiting time suddenly becomes very long，But the infer time is very stable（batchsize=1） ，The gpu usage and cpu usage of the gpu machine are normal，and qps did not rise. Is there any direction to investigate this issue? thanks

The monitoring information is as follows，
![image](https://user-images.githubusercontent.com/97878310/154491873-a4bfda0d-e53b-42d5-a9a8-202df65856ae.png)
![image](https://user-images.githubusercontent.com/97878310/154491885-3d3a37b2-8a25-4a9f-8215-e133124190cc.png)

**Comment by llustc** [comment]
![5F92E787-64EE-4FFD-AED9-F8740B6407F9](https://user-images.githubusercontent.com/97878310/154494153-7dae624e-023e-4fe5-a191-fad52bb4bf80.png)
![61F5A340-FA63-4FFE-99C3-738D820579A7](https://user-images.githubusercontent.com/97878310/154494176-b938ea44-7d24-45d7-b3b2-6defd002427d.png)

**Comment by llustc** [comment]
> If there are many requests inflight but there are not many model instances available to serve those requests, it can lead to an increase in the request queue time. You can trying increasing the number of instances for the model to decrease the queue time. https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#multiple-model-instances

Thanks for your reply, i will have a try.

**Comment by josephykwang** [comment]
even when increasing the instance count to be # of cores, we see long queue time for a single request.

**Comment by feihugis** [comment]
> ![5F92E787-64EE-4FFD-AED9-F8740B6407F9](https://user-images.githubusercontent.com/97878310/154494153-7dae624e-023e-4fe5-a191-fad52bb4bf80.png) ![61F5A340-FA63-4FFE-99C3-738D820579A7](https://user-images.githubusercontent.com/97878310/154494176-b938ea44-7d24-45d7-b3b2-6defd002427d.png)

@llustc May I ask how you generated these monitoring figures?

**Comment by llustc** [comment]
> > ![5F92E787-64EE-4FFD-AED9-F8740B6407F9](https://user-images.githubusercontent.com/97878310/154494153-7dae624e-023e-4fe5-a191-fad52bb4bf80.png) ![61F5A340-FA63-4FFE-99C3-738D820579A7](https://user-images.githubusercontent.com/97878310/154494176-b938ea44-7d24-45d7-b3b2-6defd002427d.png)
> 
> @llustc May I ask how you generated these monitoring figures?

Maybe you can see this: https://github.com/triton-inference-server/server/blob/main/docs/user_guide/metrics.md，
then use prometheus collecting data

**Comment by troycheng** [comment]
> > If there are many requests inflight but there are not many model instances available to serve those requests, it can lead to an increase in the request queue time. You can trying increasing the number of instances for the model to decrease the queue time. https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#multiple-model-instances
> 
> Thanks for your reply, i will have a try.

We met the same problem and do not know why, did you find the reason at last ?

**Comment by SunnyGhj** [comment]
> > > If there are many requests inflight but there are not many model instances available to serve those requests, it can lead to an increase in the request queue time. You can trying increasing the number of instances for the model to decrease the queue time. https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#multiple-model-instances
> > 
> > 
> > Thanks for your reply, i will have a try.
> 
> We met the same problem and do not know why, did you find the reason at last ?

I have the same problem.  Is there any progress?
