### ISSUE TITLE
Triton server - required NVIDIA driver version vs CUDA minor version compatibility

### ISSUE THREAD

**Issue by kgksl** [triton-inference-server/server#3955]
I am able to run [Triton-server 21.12](https://docs.nvidia.com/deeplearning/triton-inference-server/release-notes/rel_21-12.html#rel_21-12) (server version 2.17) docker image with TensorRT backend on a GPU that has NVIDIA driver version 470 installed. However I noticed that Triton-server 21.12 requires NVIDIA driver version 495 or later on the release notes to support CUDA 11.5.

I am wondering if I am not getting any issues and able to successfully run the docker image with an older driver because of CUDA [minor version compatibility](https://docs.nvidia.com/deploy/cuda-compatibility/index.html#minor-version-compatibility). The logs do not have any warnings or information that it uses minor version compatibility though ( I came across [some instances](https://github.com/triton-inference-server/server/issues/3518) among the issues posted here, where the logs print this as an error or a warning about [minor version compatibility](https://docs.nvidia.com/deploy/cuda-compatibility/index.html#minor-version-compatibility)/ driver version).

I want to know if I am able to use Driver 470 because of CUDA minor version compatibility or due to some other reason. 

And if it is safe to rely on minor version compatibility even with future triton-server releases, where the required NVIDIA driver version given on release notes is higher, but the installed NVIDIA driver version is equal or greater than the minimum required driver, for the version of CUDA toolkit being used by Triton-server.

**Comment by rmccorm4** [comment]
Hi @kgksl, what GPU are you using? As noted in the release notes, for Tesla GPUs (T4, V100, A100, etc.) cuda compatibility mode will support certain earlier driver versions:

> However, if you are running on a Data Center GPU (for example, T4 or any other Tesla board), you may use NVIDIA driver release 418.40 (or later R418), 440.33 (or later R440), 450.51 (or later R450), 460.27 (or later R460), or 470.57 (or later R470). The CUDA driver's compatibility package only supports particular drivers. For a complete list of supported drivers, see the [CUDA Application Compatibility](https://docs.nvidia.com/deploy/cuda-compatibility/index.html#cuda-application-compatibility) topic. For more information, see [CUDA Compatibility and Upgrades](https://docs.nvidia.com/cuda/cuda-c-best-practices-guide/index.html#cuda-compatibility-and-upgrades) and [NVIDIA CUDA and Drivers Support](https://docs.nvidia.com/datacenter/tesla/cuda-drivers-support/index.html#introduction).

**Comment by kgksl** [comment]
@rmccorm4 thanks for the reply. I am not using a Tesla GPU. I am using a RTX2070 at the moment and all the GPUs I am planning to use are Turing/ Pascal.

**Comment by rmccorm4** [comment]
Hi @kgksl , can you share the output banner printed when you start the Triton 21.12 container on that machine?

**Comment by kgksl** [comment]
Hi @rmccorm4 thanks alot for the instructions.

I built a custom triton-server docker image by using `nvcr.io/nvidia/tritonserver:21.12-py3-min` as the base image and TensorRT as backend. And I was using this custom docker image as the base image for my final triton-server docker image.
And I didn't see any warning related when running this docker image, and the server was working fine with running inferences.

And with your instructions, I ran the `nvcr.io/nvidia/tritonserver:21.12-py3-min` docker image and I can see the following warning which says it uses CUDA [minor version compatibility](https://docs.nvidia.com/deploy/cuda-compatibility/index.html#minor-version-compatibility)

1.the full output banner printed when you start the Triton 21.12 container
`docker run -it --rm --gpus=all  --runtime nvidia nvcr.io/nvidia/tritonserver:21.12-py3-min`

```
==========
== CUDA ==
==========

NVIDIA Release  (build )
CUDA Version 11.5.0.029

Container image Copyright (c) 2021, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

WARNING: CUDA Minor Version Compatibility mode ENABLED.
  Using driver version 470.57.02 which has support for CUDA 11.4.  This container
  was built with CUDA 11.5 and will be run in Minor Version Compatibility mode.
  CUDA Forward Compatibility is preferred over Minor Version Compatibility for use
  with this container but was unavailable:
  [[Forward compatibility was attempted on non supported HW (CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE) cuInit()=804]]
  See https://docs.nvidia.com/deploy/cuda-compatibility/ for details.

NOTE: MOFED driver for multi-node communication was not detected.
      Multi-node communication performance may be reduced.

NOTE: The SHMEM allocation limit is set to the default of 64MB.  This may be
   insufficient for CUDA.  NVIDIA recommends the use of the following flags:
   docker run --gpus all --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 ...
 ```
 2. echo $_CUDA_COMPAT_STATUS inside the Triton 21.12 container
 ```
 Forward compatibility was attempted on non supported HW (CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE) cuInit()=804
 ```

**Comment by rmccorm4** [comment]
Hi @kgksl, so as you suspected, you're getting CUDA Minor Version compatibility with your setup.

If you're not seeing this warning/banner in your custom image, are you overwriting the ENTRYPOINT in your Dockerfile?

**Comment by kgksl** [comment]
thanks a-lot for your help.

Final question: the given [application considerations]( https://docs.nvidia.com/deploy/cuda-compatibility/#application-considerations) talk about limitations on applications using `PTX`  and I can see there are issues related `PTX` on this repo, which means triton-server might be using it in some (or all) instances. Do you know about this?

**Comment by rmccorm4** [comment]
@GuanLuo @deadeyegoodwin any thoughts on this?

**Comment by GuanLuo** [comment]
In the backend utilities provided, there is a [copy kernel](https://github.com/triton-inference-server/backend/blob/main/src/kernel.h) that backend implementer can use for gather / scatter tensors in some use cases, which is compiled with PTX for portability reason. Besides that the backend / framework itself may utilize PTX as well. That being said, PTX usage is specific to backend and Triton core itself doesn't use it.

**Comment by kgksl** [comment]
thanks a lot for your answers. I am using TensorRT as the backend with Triton server. I am not familiar with TensorRT core and if it uses PTX. Do you have an idea about that? thanks
