### ISSUE TITLE
Build trtion server image with container failed

### ISSUE THREAD

**Issue by SuoSiFire** [triton-inference-server/server#3962]
**Description**

Build trtion server image with container failed ,error msg : 

docker run -it -d --name tensorflow_backend_deps gitlab-master.nvidia.com:5005/dl/dgx/tensorflow:master-py3-base
Unable to find image 'gitlab-master.nvidia.com:5005/dl/dgx/tensorflow:master-py3-base' locally
docker: Error response from daemon: Get https://gitlab-master.nvidia.com:5005/v2/: dial tcp: lookup gitlab-master.nvidia.com: no such host

Guess  gitlab-master.nvidia.com is an intranet address 

**Triton Information**
What version of Triton are you using?

release 2.18.0

Are you using the Triton container or did you build it yourself?

build it myself.

**To Reproduce**
Steps to reproduce the behavior.

./build.py --cmake-dir=./build --build-dir=/tmp/citritonbuild --enable-logging --enable-stats --enable-tracing --enable-metrics --endpoint=http --endpoint=grpc --repo-tag=common:r22.01 --repo-tag=core:r22.01 --repo-tag=backend:r22.01 --repo-tag=thirdparty:r22.01 --backend=ensemble  --backend=onnxruntime:r22.01 --backend=tensorflow2:r22.01 --backend=openvino:r22.01 --backend=python:r22.01 --repoagent=checksum:r22.01

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**

build success.

**Comment by lminer** [comment]
I'm having the same issue

**Comment by CoderHam** [comment]
@SuoSiFire and @lminer that you for raising this issue. We will work on a fix for the same.
