### ISSUE TITLE
Auto generated model configuration for custom backend

### ISSUE THREAD

**Issue by zzk0** [triton-inference-server/server#3971]
From [this document](https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#auto-generated-model-configuration) we can learn that some models do not require to provide a model configuration file. Is it possible for a custom backend? 

> Specifically, TensorRT, TensorFlow saved-model, and ONNX models do not require a model configuration file because Triton can derive all the required settings automatically.

**Comment by dyastremsky** [comment]
Sure. A good starting point would be referencing how other backends do it, such as ONNX: https://github.com/triton-inference-server/onnxruntime_backend/blob/main/src/onnxruntime.cc#L119-L134

**Comment by GuanLuo** [comment]
Another reference is the API itself https://github.com/triton-inference-server/core/blob/main/include/triton/core/tritonbackend.h#L916-L946

**Comment by zzk0** [comment]
Thank you for your prompt response! 

It seems that autofill for custom backends only works in newer versions of triton and not in older versions such as [r21.10](https://github.com/triton-inference-server/server/blob/r21.10/src/core/autofill.cc)

**Comment by zzk0** [comment]
@dyastremsky @GuanLuo  I found the following code snippet, which seems to imply that if the model file is not one of these, it will not be recognized. 🤔

https://github.com/triton-inference-server/server/blob/main/src/core/model_config_utils.cc#L646-L658

**Comment by dyastremsky** [comment]
> @dyastremsky @GuanLuo I found the following code snippet, which seems to imply that if the model file is not one of these, it will not be recognized. 🤔
> 
> https://github.com/triton-inference-server/server/blob/main/src/core/model_config_utils.cc#L646-L658

This code snippet is unrelated. It has to do with auto-completing the backend and default model filename fields based on the platform. That's done for backward compatibility. You'll need to specify the backend in the model config: https://github.com/triton-inference-server/backend/blob/main/README.md#backends

**Comment by dyastremsky** [comment]
> Thank you for your prompt response!
> 
> It seems that autofill for custom backends only works in newer versions of triton and not in older versions such as [r21.10](https://github.com/triton-inference-server/server/blob/r21.10/src/core/autofill.cc)

I don't understand the relevance of the link. Could you link the specific lines you're looking at?

I'm not sure which version autocomplete was added in. If you're using an older version of Triton, I can look into that. I see the auto-complete API code that Guan linked still present in 21.10 here: https://github.com/triton-inference-server/core/blob/r21.10/include/triton/core/tritonbackend.h#L808-L838

**Comment by zzk0** [comment]
I will try to describe the scenario more clearly first. **There is a model directory, but no model configuration file, that is config.pbtxt.** Can autofill works for custom backends in such a scenario?

For triton r21.10, autofill only works for specific backends such as TensorFlow, PyTorch, ONNX. For example, we can start tritonserver with the following command, tritonserver will autofill the missing model configuration.

```
docker run --rm --runtime=nvidia --network=host -v$(pwd)/model_repo1:/models nvcr.io/nvidia/tritonserver:21.10-py3 /opt/tritonserver/bin/tritonserver --model-store /models --strict-model-config false --log-verbose 1
```

We can see the output like this:

![image](https://user-images.githubusercontent.com/30856589/155674896-084add4f-6139-4c94-95ac-d68605bd1bc8.png)

However, autofill will not work  for a custom backend when missing the configuration file.

![image](https://user-images.githubusercontent.com/30856589/155671899-6f9ce2d1-ab4e-4326-bad9-0ed65d327a29.png)

-----

>  I see the auto-complete API code that Guan linked still present in 21.10 here: https://github.com/triton-inference-server/core/blob/r21.10/include/triton/core/tritonbackend.h#L808-L838

In the case of missing fields, autofill does help. In the absence of config.pbtxt, tritonserver will try to autofill based on the model name. For example, a model file named model.onnx will use ONNX Runtime. However, model file name maybe anything for a custom backend, so tritonserver cannot autofill if there is no config.pbtxt to figure out what backend it uses.

Maybe tritonserver can provide API like this: `TRITONBACKEND_RegisterModelFileName`. 😄

**Comment by dyastremsky** [comment]
Thanks for providing additional information!

@tanmayv25, do you know if there is a way for custom backends to specify the model name for autofill (when there is no config file at all) or would this be an enhancement?

**Comment by GuanLuo** [comment]
No, at the minimal there must be a `config.pbtxt` file that has `backend` field specified, otherwise Triton will not know what backend library it should interact with, not to mention the autofill is now part of the backend functionality. And your suggestion for `TRITONBACKEND_RegisterModelFileName()` will have the same issue, Triton needs to know which backend library to be loaded before calling `TRITONBACKEND_RegisterModelFileName()` provided by the backend library, which is a self dependency here.

You may make changes in Triton core so it can use other hint (i.e. model file name) to recognize if your custom backend should be used, but again, as @dyastremsky mentioned this kind of Triton autofill is mainly for backward compatibility reason, and with the current backend decoupling approach, Triton core should be agnostic to the backends until the model config introduce the backend name to it.
