### ISSUE TITLE
Way to capture headers in model.py when using python backend

### ISSUE THREAD

**Issue by SaratM34** [triton-inference-server/server#3972]
**Description**
Hi,

I am using HTTP/REST protocol to call the Triton directly for inferencing. I have a requirement where I need to capture a specific header from the request in the model.py when using python backend. Just wanted to check if there is a way to capture the header information in the model.py.
 
**Triton Information**
r21.09
Are you using the Triton container or did you build it yourself?
Triton Container
**To Reproduce**
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**
Able to capture header information in model.py when using python backend

**Comment by Tabrizian** [comment]
Currently, there is no way to access the HTTP request headers in Python backend.

**Comment by ukemamaster** [comment]
@Tabrizian In [this](https://github.com/triton-inference-server/client/blob/main/src/python/examples/simple_grpc_infer_client.py) example (line 131) they pass a python dict in the headers arg of  `triton_client.infer()` call. 
Is there a way to get this dict in the `model.py `while using python_backend ?

**Comment by camify** [comment]
I too would like this feature

**Comment by XiaoxueWang1** [comment]
Any update here?

**Comment by Tabrizian** [comment]
It is actually supported now. Please see this test:

https://github.com/triton-inference-server/server/blob/main/qa/L0_parameters/test.sh
