### ISSUE TITLE
Edge compute using Transform4rec models with ONNX runtime 

### ISSUE THREAD

**Issue by fire** [triton-inference-server/server#3976]
**Is your feature request related to a problem? Please describe.**

I want to execute transform4rec models on edge compute to solve recommendation problems.

**Describe the solution you'd like**

On the edge compute, execute onnx model using onnxruntime with gpu acceleration and with a cpu fallback.

I am looking for a quick start example that takes tabular data, executes the model and gets a result in something from a zip deployment archive.

Targeting NVIDIA edge compute devices, Windows 10 and linux desktop oses.

Can try to develop a quick start, but unclear what is required.

**Describe alternatives you've considered**

* REJECTED use pytorch and transform4rec directly due to the difficult of assembling all the dependencies
* REJECTED ship a docker / kubernetes cluster to process models

**Additional context**

See https://github.com/NVIDIA-Merlin/Transformers4Rec/issues/369

**Comment by tanmayv25** [comment]
It is not clear from your description what you are asking of Triton. 

> executes the model
Triton can help you running models. We have a quickstart [here](https://github.com/triton-inference-server/server/blob/main/docs/quickstart.md). 
The model repositoy has an onnx model: https://github.com/triton-inference-server/server/tree/main/docs/examples/model_repository/densenet_onnx
For directly calling inference from your application without going through http and grpc endpoints we have a simple server example here: https://github.com/triton-inference-server/server/blob/main/src/simple.cc
See here for all the APIs supported by tritonserver: https://github.com/triton-inference-server/core/blob/main/include/triton/core/tritonserver.h

**Comment by fire** [comment]
I am closing. Thanks for the help.
