### ISSUE TITLE
How to download dependency in advance?

### ISSUE THREAD

**Issue by lhy2749** [triton-inference-server/server#3985]
**Description**
Now I have an embarrassing problem. There is something wrong with my network agent, which always reports git errors when compiling in the container, like 
```
fatal: unable to access 'https://github.com/triton-inference-server/third_party.git/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.
```
I want to know if I can  download the dependencies on GitHub into my container before use `python build.py`, so that I don't need to download them from GitHub for cmake?

**Triton Information**
What version of Triton are you using?
r22.01

Are you using the Triton container or did you build it yourself?
I want to build cpu-only image.
```
docker run --name tritonserver_builder -w /workspace -v /var/run/docker.sock:/var/run/docker.sock tritonserver_buildbase python3 ./build.py --enable-logging --enable-stats --enable-tracing --enable-metrics --filesystem=gcs --filesystem=azure_storage --filesystem=s3 --endpoint=http --endpoint=grpc --repo-tag=common:r22.01 --repo-tag=core:r22.01 --repo-tag=backend:r22.01 --repo-tag=thirdparty:r22.01 --backend=ensemble --backend=square:r22.01 --backend=onnxruntime:r22.01 --backend=pytorch:r22.01 --backend=tensorflow1:r22.01 --backend=openvino:r22.01 --backend=python:r22.01 --repoagent=checksum:r22.01 --no-container-build --version 2.18.0 --container-version 22.01 --upstream-container-version 22.01 --cmake-dir /workspace/build --build-dir /tmp/tritonbuild --install-dir /tmp/tritonbuild/install
```

**To Reproduce**
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**

**Comment by dyastremsky** [comment]
You could probably clone the repos locally, mount them via a volume, then update the build.py script for your case. If cloning works locally, perhaps try something like --net=host on the container to see if that resolves your network issues.

**Comment by CoderHam** [comment]
In addition to the steps @dyastremsky mentioned, you will also need to modify the FetchContent defined in the cmakelists.txt to point to local copies of the repos instead of git. This would be a non-trivial amount of changes.

**Comment by lhy2749** [comment]
> In addition to the steps @dyastremsky mentioned, you will also need to modify the FetchContent defined in the cmakelists.txt to point to local copies of the repos instead of git. This would be a non-trivial amount of changes.

I found that the changes were really big, so I decided to wait for the cpu-only version.
