### ISSUE TITLE
Set_shared_memory of the class InferInput in python client doesn't support offset !=0

### ISSUE THREAD

**Issue by remib-proovstation** [triton-inference-server/server#3986]
**Description**
When using the function `set_shared_memory` of the class `InferInput` of the python http and grpc client with option `offset`, 
`KeyError: 'shared_memory_offset'` is raised

**Triton Information**
I'm using the last client version (from `pip install tritonclient[all]`)

Are you using the Triton container or did you build it yourself?
I'm using the triton container, but this issue is client side

**To Reproduce**
Call the set_shared_memory on a InferInput with offset != 0

I don't know if I'm missing something, but since the `self._input.parameters` dict is initialized at `{}`, and then we have in the function  `set_shared_memory` :

```
if offset != 0:
       self._input.parameters['shared_memory_offset'].int64_param = offset
```

The exception seems logical. What is this `int64_param` ?

**Expected behavior**
When using the function `set_shared_memory` of the class `InferInput` of the python http and grpc client with option `offset`, no exception should be raised.

**Possible fix**
```
if offset != 0:
       # enforce offset of type int
       if not isinstance(offset, int)
            raise_error(f"got unexpected type {type(offset)} for offset, expected int")
       self._input.parameters['shared_memory_offset'] = offset
```

**Comment by remib-proovstation** [comment]
I've proposed changes in this PR
https://github.com/triton-inference-server/client/pull/74

**Comment by dyastremsky** [comment]
Thank you for submitting a PR.

**Comment by dyastremsky** [comment]
PR was merged. Closing this issue.
