### ISSUE TITLE
Ask about the meaning of output.

### ISSUE THREAD

**Issue by cyLi-Tiger** [triton-inference-server/server#3990]
I only have a simple question, I ran the image classification client example, I wonder what does the numbers in the red block mean? Are they inference time? If not, how can I know how much time does a inference take?

I want to know the above question because I wan't to test whether my model can be inference faster after depression.
Looking forward to your reply! Thanks!
![image](https://user-images.githubusercontent.com/37681002/156006662-1d075584-2c8b-47e0-b468-03b9a31a6607.png)

**Comment by cyLi-Tiger** [comment]
In the mean time, what framework do you suggest to make this inference result better, for example, can we use nginx?

**Comment by GuanLuo** [comment]
That is the probability of the result to be in the category, so there is ~75% confidence that the item is coffee mug. Please checkout [perf analyzer](https://github.com/triton-inference-server/server/blob/main/docs/perf_analyzer.md) for performance profiling.

**Comment by cyLi-Tiger** [comment]
> So how can I get the time each inference cost?
