### ISSUE TITLE
How to get the time each inference cost?

### ISSUE THREAD

**Issue by cyLi-Tiger** [triton-inference-server/server#3994]
I wonder how can I know the time each inference cost, for example, how can I get the inference time in the image classification client example that you provide?
![image](https://user-images.githubusercontent.com/37681002/156089868-18e8b4e0-3ef0-4d60-97d8-5caa5a5d6595.png)

**Comment by dyastremsky** [comment]
You can use Triton's [Model Analyzer](https://github.com/triton-inference-server/model_analyzer) if you're trying to profile the models.

If you're looking to do it for individual requests, you'll need to do it on the client side. The [GRPC client](https://github.com/triton-inference-server/client/blob/main/src/python/library/tritonclient/grpc/__init__.py#L685) and [HTTP client](https://github.com/triton-inference-server/client/blob/main/src/python/library/tritonclient/http/__init__.py#L679) have get_inference_statistics functions that provide that information, so those could be a good starting point for getting them for an image classification example.

If you don't need much detail, you may also want to explore using a time/clock function that starts when you send the request and stops after you receive it.

**Comment by cyLi-Tiger** [comment]
> 

much thanks

**Comment by tengerye** [comment]
Hi @dyastremsky How could we get the processing time of the server (transmitting time exclusively) for each request?
