### ISSUE TITLE
Tensorflow2 backend UNAVAILABLE: Not found: unable to load shared library: libnccl.so.2

### ISSUE THREAD

**Issue by mattdibi** [triton-inference-server/server#3996]
**Description**
After a custom CPU-only ARM64 Docker build I cannot run a Tensorflow model because:

```
| tf_autoencoder_fp32 | 1       | UNAVAILABLE: Not found: unable to load shared library: libnccl.so.2: cannot open shared object file: No such file or directory |
```

Complete log: [log.txt](https://github.com/triton-inference-server/server/files/8159729/log.txt)

**Triton Information**
_What version of Triton are you using?_ **r22.02**

_Are you using the Triton container or did you build it yourself?_ **I'm building a Triton container**

**To Reproduce**
_Steps to reproduce the behavior._

Build a CPU-only ARM64 container using the following options while on branch r22.02

```
./build.py --cmake-dir=build --build-dir=/tmp/citritonbuild --enable-logging --enable-stats --enable-tracing --enable-metrics --endpoint=http --endpoint=grpc --backend=ensemble --backend=identity --backend=repeat --backend=square --backend=onnxruntime  --backend=tensorflow2 --backend=python --extra-backend-cmake-arg=tensorflow2:TRITON_TENSORFLOW_INSTALL_EXTRA_DEPS=ON
```

Once the build completes I export the Docker image in `.tar.gz` format and then load it on the Raspberry Pi using the following commands:

```
docker save tritonserver:latest | gzip > tritonserver_arm64_cpu_22_02.tar.gz
```

```
docker load < tritonserver_arm64_cpu_22_02.tar.gz
```

The Docker image builds fine and can correctly load Python models on a Raspberry Pi with 64bit OS but not the Tensorflow one.

_Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well)._

You can find all models configurations [here](https://github.com/mattdibi/sense-hat-demo/tree/master/models).

**Expected behavior**
_A clear and concise description of what you expected to happen._

I expected it to behave the same way the official container works. These model configurations are working fine for nvcr.io/nvidia/tritonserver:22.01-py3 on x86.

**Comment by dyastremsky** [comment]
Sure, thanks for pointing out the NCCL issue. It's been fixed for the main branch and next release.

That's correct. You should also be able to directly move the .so file produced into the server container (I believe /opt/tritonserver/backends/<backend_name>).
