### ISSUE TITLE
Question: Is it possible to access request body 'parameters' in the python backend?

### ISSUE THREAD

**Issue by gnovack** [triton-inference-server/server#3998]
**Description**
The KServe API specification mentions that the Inference API should accept a _parameters_ field which contains zero or more name-value pairs: https://github.com/kserve/kserve/blob/master/docs/predict-api/v2/required_api.md#parameters

I was curious if it is possible to access these parameters in the python backed, or do all client inputs to the python backend have to be passed as input tensors?

**Comment by dyastremsky** [comment]
@Tabrizian Do you know if the Python backend can take parameters or only tensors?

**Comment by Tabrizian** [comment]
It can only take tensors in the execute function. This will be a separate feature request. cc @msalehiNV

**Comment by dyastremsky** [comment]
Thanks for clarifying, Iman! I created an enhancement ticket to track this issue.

**Comment by Tabrizian** [comment]
This has been addressed in https://github.com/triton-inference-server/python_backend/pull/213. Closing this ticket.
