### ISSUE TITLE
How to use Triton Inference Server with Docker Swarm

### ISSUE THREAD

**Issue by sourabh-burnwal** [triton-inference-server/server#4015]
Has anyone here tried to create a docker swarm of triton inference servers?
I have a use case, where I want to use a lightweight container orchestration tool. I tried to use docker swarm since it has load-balancing, fault-tolerance, rolling updates, and other features. I followed answers on StackOverflow on how to use GPU in docker swarm. Referring to that, my `/etc/docker/daemon.json` looks like this:
```
{
    "runtimes": {
        "nvidia": {
            "path": "nvidia-container-runtime",
            "runtimeArgs": []
        }
    },
    "default-runtime":"nvidia",
    "node-generic-resources": [
	    "NVIDIA-GPU=GPU-4b0429cc-5ffe-148e-9d58-61e35be291de"
    ]

}
```

And, `/etc/nvidia-container-runtime/config.toml` like this:
```
disable-require = false
swarm-resource = "DOCKER_RESOURCE_GPU"
#accept-nvidia-visible-devices-envvar-when-unprivileged = true
#accept-nvidia-visible-devices-as-volume-mounts = false

[nvidia-container-cli]
#root = "/run/nvidia/driver"
#path = "/usr/bin/nvidia-container-cli"
environment = []
#debug = "/var/log/nvidia-container-toolkit.log"
#ldcache = "/etc/ld.so.cache"
load-kmods = true
#no-cgroups = false
#user = "root:video"
ldconfig = "@/sbin/ldconfig.real"

[nvidia-container-runtime]
#debug = "/var/log/nvidia-container-runtime.log"
```

I created a service using this command (after initialising a swarm):
```
sudo docker service create --name triton-svc --mount type=bind,source=/home/ericedge/Desktop/workspace/models,destination=/models --generic-resource "NVIDIA-GPU=0" -p 8000:8000 -p 8001:8001 -p 8002:8002 --env model-repository=/models tritonserver:fordev_v5
```

I am getting this as output:
```
overall progress: 0 out of 1 tasks 
1/1: assigned  
verify: Detected task failure 
```
It keeps creating and failing. I checked the logs, and their logs end here:
```
=============================
triton-svc.1.lldgevgyvtwh@raven    | == Triton Inference Server ==
triton-svc.1.lldgevgyvtwh@raven    | =============================
triton-svc.1.lldgevgyvtwh@raven    | 
triton-svc.1.lldgevgyvtwh@raven    | NVIDIA Release 21.07 (build 24810355)
triton-svc.1.lldgevgyvtwh@raven    | 
triton-svc.1.lldgevgyvtwh@raven    | Copyright (c) 2018-2021, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
triton-svc.1.lldgevgyvtwh@raven    | 
triton-svc.1.lldgevgyvtwh@raven    | Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.
triton-svc.1.lldgevgyvtwh@raven    | 
triton-svc.1.lldgevgyvtwh@raven    | This container image and its contents are governed by the NVIDIA Deep Learning Container License.
triton-svc.1.lldgevgyvtwh@raven    | By pulling and using the container, you accept the terms and conditions of this license:
triton-svc.1.lldgevgyvtwh@raven    | https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license
triton-svc.1.lldgevgyvtwh@raven    | find: File system loop detected; '/usr/bin/X11' is part of the same file system loop as '/usr/bin'.
triton-svc.1.lldgevgyvtwh@raven    | 
``` 

I am not able to find a solution, not to say even find the issue here. Can anyone point me in the right direction? Is it even possible to use triton inference server in docker swarm?

**Comment by rmccorm4** [comment]
Hi @sourabh-burnwal, we do not have any explicit support for Docker Swarm currently so I may not be of much help.

After a [quick search](https://stackoverflow.com/questions/53222530/getting-detected-task-failure-for-some-images-while-creating-docker-service) of your issue, it may be that the service container you're starting is not doing anything (simply printing the text banner above and exiting). You may want to try setting the [COMMAND](https://docs.docker.com/engine/reference/commandline/service_create/) for the container to do something like `tritonserver --model-repository /models` in order to actually start the triton server in the container.

Perhaps this modified version of your command may help to learn more:
```
# Call tritonserver executable on container start
sudo docker service create --name triton-svc --mount type=bind,source=/home/ericedge/Desktop/workspace/models,destination=/models --generic-resource "NVIDIA-GPU=0" -p 8000:8000 -p 8001:8001 -p 8002:8002 tritonserver:fordev_v5 tritonserver --model-repository=/models
```

**Comment by sourabh-burnwal** [comment]
@rmccorm4 Thanks for replying. It was my bad, I forgot to add that. Now it's converging.
I have another doubt though. Since I am running a number of models, which requires me to pass --shm-size atleast 5G. How to pass shm size in docker swarm? I have followed this: https://gist.github.com/tomlankhorst/33da3c4b9edbde5c83fc1244f010815c to use gpu. But it doesn't seem to be working.
Could you help me with this?

**Comment by sourabh-burnwal** [comment]
UPDATE: I added `--mount type=tmpfs,target=/dev/shm` in the command, and it executed perfectly. Thanks again for you help.
Closing the issue.
