### ISSUE TITLE
How to build server source code in a container?

### ISSUE THREAD

**Issue by MAhaitao999** [triton-inference-server/server#4027]
Hi all:
    I want to add some features (like model encrypt, decrypt...) in the server source code. If I build with docker, it is very very slow. So  Can I docker run a container, and only build the server source code in the container?

**Comment by rmccorm4** [comment]
Hi @MAhaitao999 ,

Our officially supported path is to make use of `build.py` as described in [docs/build.md](https://github.com/triton-inference-server/server/blob/main/docs/build.md), so we encourage you to do so. 

You can use can use `build.py` with `--no-container-build` flag and it will build by just invoking cmake. It is your responsibility to make sure the host system or docker container has all the required dependencies installed. The [Building Without Docker](https://github.com/triton-inference-server/server/blob/main/docs/build.md#building-without-docker) section covers this.

As for model encryption/decryption, you may be interested in using the existing repo agent API documented here: https://github.com/triton-inference-server/server/blob/main/docs/repository_agents.md. There is an example of verifying checksums here: https://github.com/triton-inference-server/checksum_repository_agent.

**Comment by MAhaitao999** [comment]
Ok，thank u@rmccorm4, follow you `--no-container-build` guide, I have build it successful!
