### ISSUE TITLE
Can we load TensorRT model within the self.initialize method of the TritonPythonModel?

### ISSUE THREAD

**Issue by thuyngch** [triton-inference-server/server#4028]
Following this example, I create a TritonPythonModel: https://github.com/triton-inference-server/python_backend/blob/main/examples/pytorch/model.py#L50

But I want to load a TensorRT model within the self.initialize method.
Is it possible?

Thanks,
Thuy

**Comment by Tabrizian** [comment]
Are you talking about loading a TRT engine using the Python API in python backend? If yes, that is possible.

**Comment by thuyngch** [comment]
> Are you talking about loading a TRT engine using the Python API in python backend? If yes, that is possible.

@Tabrizian Yes, it is exactly what I need.
Could you please give me a link to instruction or example?
Thanks!

**Comment by Tabrizian** [comment]
The guide below might be helpful: https://docs.nvidia.com/deeplearning/tensorrt/quick-start-guide/index.html

(@rmccorm4 feel free to share additional resources)

**Comment by thuyngch** [comment]
I got it, thank you so much!
