### ISSUE TITLE
Expose gRPC channel options

### ISSUE THREAD

**Issue by wurthel** [triton-inference-server/server#4036]
Hello! 

I see, you had thoughts about exposing gRPC options in `InferenceServerClient`:
https://github.com/triton-inference-server/client/blob/main/src/python/library/tritonclient/grpc/__init__.py#L213

Do you have any updates on it? Plans to start exposing them?

**Why it's worth exposing (my personal use case)**
We use gRPC protocol to communicate with Triton. We have more than 1 replica of Triton in our Kubernetes cluster. Since gRPC load balancing is not handled by default in Kubernetes, I enabled the load balancing on client side by modifying the gRPC load balancing policy. I just inherited from `InferenceServerClient` and overwrote the `__init__`:
```
class RoundRobinInferenceServerClient(InferenceServerClient):

    def __init__(self, url):
        keepalive_options = triton_grpc.KeepAliveOptions()
        channel_opt = [
            ("grpc.max_send_message_length", triton_grpc.MAX_GRPC_MESSAGE_SIZE),
            ("grpc.max_receive_message_length", triton_grpc.MAX_GRPC_MESSAGE_SIZE),
            ("grpc.keepalive_time_ms", keepalive_options.keepalive_time_ms),
            ("grpc.keepalive_timeout_ms", keepalive_options.keepalive_timeout_ms),
            (
                "grpc.keepalive_permit_without_calls",
                keepalive_options.keepalive_permit_without_calls,
            ),
            ("grpc.http2.max_pings_without_data", keepalive_options.http2_max_pings_without_data),
            ("grpc.lb_policy_name", "round_robin"),  # Enable load balancing on client side
        ]
        self._channel = grpc.insecure_channel(url, options=channel_opt)
        self._client_stub = triton_grpc.service_pb2_grpc.GRPCInferenceServiceStub(self._channel)
        self._verbose = False
        self._stream = None
```

It would be very nice if you could allow to modify the gRPC options in `InferenceServerClient` directly.

**Comment by rmccorm4** [comment]
Hi @wurthel, thanks for submitting this request.

@tanmayv25 thoughts on exposing `grpc.lb_policy_name` specifically or more options generally?

**Comment by tanmayv25** [comment]
I think we can expose channel_opt in the API for advanced users. The options provided in the dictionary can supercede other options in the API signature.

The idea of not exposing dict was to have some kind of feature documentation in our library.

**Comment by rmccorm4** [comment]
Hi @wurthel, we have a ticket now to track this enhancement request, thanks for filing this.

**Comment by rmccorm4** [comment]
Hi @wurthel, I recently exposed generic ChannelArgs params to the GRPC client library so advanced users can pass any channel arg that they would like: https://github.com/triton-inference-server/client/pull/104. 

See this new `channel_args` param in the python client library for your use case: https://github.com/triton-inference-server/client/blob/c6296f2b853517ecfc949edc6e0bb7a85ea1d22c/src/python/library/tritonclient/grpc/__init__.py#L193-L200

Other links:
- [C++ client library ChannelArgs param](https://github.com/triton-inference-server/client/blob/3ca04153909edbfe2f36462a44c8e63b203a5121/src/c%2B%2B/library/grpc_client.h#L127-L151)
- [C++ example](https://github.com/triton-inference-server/client/blob/main/src/c++/examples/simple_grpc_custom_args_client.cc)
- [Python example](https://github.com/triton-inference-server/client/blob/main/src/python/examples/simple_grpc_custom_args_client.py)

**Comment by Vincouux** [comment]
May I ask what extra mechanism did you configure to correctly balance the load between replication of Triton? I've copied the channel args (especially the round robin one) to my client instantiation, provided the name alias of my service as URL (`triton:6001` for example) but still cannot see any load balancing. I feel like I'm missing something.

![Capture d’écran du 2024-01-14 03-11-46](https://github.com/triton-inference-server/server/assets/17098417/c9850556-3b5f-486f-a2df-7f1edc5cf1b0)
