### ISSUE TITLE
How to set dynamic batching for tensorrt model?

### ISSUE THREAD

**Issue by ZJU-lishuang** [triton-inference-server/server#4038]
the tensorrt model has set max_batch_size big than 1.
```
import tensorrt as trt
logger = trt.Logger(trt.Logger.INFO)

builder = trt.Builder(logger)
builder.max_batch_size = 128
```
Also enable dynamic batching config.pbtxt.
Meet following error.
`Error details: model expected the shape of dimension 0 to be between 1 and 1 but received 39`

Should I set [dynamic shapes](https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#work_dynamic_shapes) in tensorrt like following?
```
profile = builder.create_optimization_profile();
profile.set_shape("foo", (3, 100, 200), (3, 150, 250), (3, 200, 300)) 
config.add_optimization_profile(profile)
```

**Comment by rmccorm4** [comment]
Hi @ZJU-lishuang , yes the `builder.max_batch_size` you referenced from the TensorRT API is from the older "implicit" batch style. I believe implicit batch should still work as long as you don't specify the `NetworkDefinitionCreationFlag.EXPLICIT_BATCH` flag when building your TRT engine.

However, "explicit" batch is preferred with optimization profiles for dynamic shape dimensions as you mention, so I recommend you move towards using explicit batch.

**Comment by henbucuoshanghai** [comment]
profile.set_shape("foo", (3, 100, 200), (3, 150, 250), (3, 200, 300)) 

foo is？
 (3, 100, 200), (3, 150, 250), (3, 200, 300)？is what？
