### ISSUE TITLE
Python Backend can not be loaded!!

### ISSUE THREAD

**Issue by MAhaitao999** [triton-inference-server/server#4043]
Hi all:
I built the triton server docker image using the offical build.py like the following cmd:
`#!/bin/bash

python3 ./build.py --cmake-dir=./build --build-dir=/mnt/disk/tmp/citritonbuild --enable-logging --enable-stats --enable-tracing --enable-metrics --enable-gpu-metrics --enable-gpu --filesystem=gcs --endpoint=http --endpoint=grpc --repo-tag=common:r21.07 --repo-tag=core:r21.07 --repo-tag=backend:r21.07 --repo-tag=thirdparty:r21.07 --backend=ensemble --backend=tensorrt:r21.07 --backend=identity:r21.07 --backend=repeat:r21.07 --backend=square:r21.07 --backend=pytorch:r21.07 --backend=tensorflow1:r21.07 --backend=tensorflow2:r21.07 --backend=openvino:r21.07 --backend=python:r21.07 --backend=fil:r21.07 --repoagent=checksum:r21.07`

When I docker run the image, and run the cmd:
`/opt/tritonserver/bin/tritonserver --model-repository=/models`
It shows that:
![image](https://user-images.githubusercontent.com/8710394/157907688-de5c6082-d315-438c-b98a-334631da6563.png)
It means that the python backend does not be load success!!!
and python model does not load success!!!
![image](https://user-images.githubusercontent.com/8710394/157907905-c77aad57-8a98-4bd0-9304-9c1e648529f0.png)

My Branch is r21.07!!!
Can anyone tell me the reason?

**Comment by Tabrizian** [comment]
Looks like there are some unexpected characters in the `triton_python_backend_utils`. Are you building this on a different platform? The stackoverflow question below might be related: https://stackoverflow.com/questions/31233777/python-source-code-string-cannot-contain-null-bytes

**Comment by MAhaitao999** [comment]
> 

I build it in Ubuntu18.04.

**Comment by Tabrizian** [comment]
Did you try the solution in the stackoverflow link?

**Comment by MAhaitao999** [comment]
> Did you try the solution in the stackoverflow link?

Yes，I tried it, but it does not work.

**Comment by Tabrizian** [comment]
Strange.. From the error it looks like there are some unexpected characters in the `triton_python_backend_utils`. Can you share the output of the command below:

```
cat -vET /opt/tritonserver/backends/python/triton_python_backend_utils.py
```

**Comment by MAhaitao999** [comment]
> Strange.. From the error it looks like there are some unexpected characters in the `triton_python_backend_utils`. Can you share the output of the command below:
> 
> ```
> cat -vET /opt/tritonserver/backends/python/triton_python_backend_utils.py
> ```

I know the reason. Because the encryption software in my computer encrypts the python file. Thank you!
