### ISSUE TITLE
Question on Concurrent Execution on the same GPU device

### ISSUE THREAD

**Issue by xliado** [triton-inference-server/server#4044]
**Description**
Hi team, we are trying to run multiple instances of the same model on the same GPU device. But it seems that the requests are executed in a sequential manner inside the same Triton server. However if we deploy the model across multiple Triton server, we found that the requests were executed in parallel. Could you pls take a look at our settings and I just want to make sure that we are not missing anything.
We have converted our PyTorch model to Torchscript, ONNX and tensorrt. And we have been trying to use PyTorch backend, ONNX backend and TensorRT backend. Looks like PyTorch backend has this issue: https://github.com/triton-inference-server/server/issues/2294. But what about ONNX and tensorrt backends? Any suggestion is much appreciated!

![workflow](https://user-images.githubusercontent.com/101420505/157916343-d978028e-d102-401b-bb6d-5a375e8a5577.png)

**Triton Information**
22.02

Are you using the Triton container or did you build it yourself?
We are using the Triton container.

**To Reproduce**
Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

Increasing number of instance_group has the same performance as using single instance. 
```
instance_group [
  {
    kind: KIND_GPU
    count: 4
  }
]
```

**Comment by GuanLuo** [comment]
ORT backend and TRT backend should not have the issue as in Torch backend, can you share the whole model config (and repro steps) so we can have a closer look?

Also when you deploy the model across multiple Triton servers, do the servers share the same GPU like multi-instance-single-server case does?
