### ISSUE TITLE
[Question]Can TRITON POLL MODE hot-update the ensemble model?

### ISSUE THREAD

**Issue by zbh0323** [triton-inference-server/server#4051]
In POLL MODE, when I updated the subfolder corresponding to ensemble, the following error was reported:
<img width="957" alt="image" src="https://user-images.githubusercontent.com/41530068/158097243-369dee67-2e67-4b75-9414-ef0dfac325b3.png">

Another scenario, in POLL MODE, when I update the corresponding subfolder of a submodel in the orchestration model, the following error is reported:
<img width="958" alt="image" src="https://user-images.githubusercontent.com/41530068/158097446-980b24f7-2d7e-4ef7-82c1-a4ccb7d4d98d.png">

**Comment by GuanLuo** [comment]
I think this is similar to #2607, it is being tracked but we haven't have a chance to look into it.

**Comment by zbh0323** [comment]
> I think this is similar to #2607, it is being tracked but we haven't have a chance to look into it.

Do you have any plans to fix this problem? Or is there a relatively good scheme for hot update of ensemble model?

**Comment by GuanLuo** [comment]
> Do you have any plans to fix this problem?

Unfortunately we haven't have the development cycle to look into the issue.
>  Or is there a relatively good scheme for hot update of ensemble model?

The way that you were trying is the scheme for hot updating ensemble, this is a bug that we will need to fix

**Comment by issamemari** [comment]
Was this bug fixed eventually?
