### ISSUE TITLE
Build openvino backend fail in container

### ISSUE THREAD

**Issue by MrRace** [triton-inference-server/server#4057]
**Description**
I try to build openvino backend in my container which have installed triton、tensorrt 、tensorrt backend、onnxruntime backend and so on, I follow the guides in https://github.com/triton-inference-server/openvino_backend
However it fails and comes some errror:
```
[root@67f0b2a328ae build]# make install -j 10
[  5%] Building CXX object _deps/repo-common-build/CMakeFiles/triton-common-error.dir/src/error.cc.o
[ 10%] Building CXX object _deps/repo-core-build/CMakeFiles/triton-core-serverstub.dir/src/tritonserver_stub.cc.o
[ 20%] Building CXX object _deps/repo-common-build/CMakeFiles/triton-common-async-work-queue.dir/src/async_work_queue.cc.o
[ 20%] Building OpenVino
make[2]: docker: Command not found
make[2]: *** [CMakeFiles/ov_target.dir/build.make:81: openvino/lib/inference_engine.so] Error 127
make[1]: *** [CMakeFiles/Makefile2:192: CMakeFiles/ov_target.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 25%] Building CXX object _deps/repo-common-build/CMakeFiles/triton-common-async-work-queue.dir/src/error.cc.o
[ 30%] Linking CXX shared library libtritonserver_stub.so
[ 35%] Linking CXX static library libtritoncommonerror.a
[ 35%] Built target triton-core-serverstub
[ 35%] Built target triton-common-error
[ 40%] Linking CXX static library libtritonasyncworkqueue.a
[ 40%] Built target triton-common-async-work-queue
make: *** [Makefile:149: all] Error 2
```

**Triton Information**
The version of Triton is from branch r21.10, and I build it myself

**Comment by dyastremsky** [comment]
The error states that Docker is not found. If you're building in a Docker container, you need to have Docker accessible in it. There are resources available online for how to run Docker in Docker. One way is to run Docker with the default Unix socket docker.sock as a volume.

For example, when running your Docker container, include "-v /var/run/docker.sock:/var/run/docker.sock".

**Comment by MrRace** [comment]
@dyastremsky Thanks a lot for your prompt reply~And it can work when running my Docker container with  `-v /var/run/docker.sock:/var/run/docker.sock -v /usr/bin/docker:/usr/bin/docker`. By the way, if i want to  build openvino backend from  my  Dockerfile, How should I do to append  both  parameters `-v /var/run/docker.sock:/var/run/docker.sock -v /usr/bin/docker:/usr/bin/docker` in my Dockerfile or `docker build` command? With Best Regards~

**Comment by dyastremsky** [comment]
Any time, glad it worked for you! For Docker questions, please check out [Docker's documentation](https://docs.docker.com/) or check with their support team.
