### ISSUE TITLE
Please add option to specify `grpc.default_authority` when creating python InferenceServerClient

### ISSUE THREAD

**Issue by chajath** [triton-inference-server/server#4062]
**Is your feature request related to a problem? Please describe.**
Sometimes `:authority` pseudo header is used to route gRPC calls. Once it's set when creating channel, it's tricky to override in each calls.

**Describe the solution you'd like**
An additional parameter to specify `grpc.default_authority` channel option when creating InferenceServerClient

**Describe alternatives you've considered**
Trying to hack _channel etc, just make things overly complicated.

**Additional context**
`:authority` pseudo header is used to route gRPC traffic

**Comment by dzier** [comment]
We are currently implementing support to expose custom GRPC channel settings. I will reference this issue in that ticket to see if the engineers can expose `:authority` as part of that effort.
