### ISSUE TITLE
Perf_Analyzer requires libcudart

### ISSUE THREAD

**Issue by KarelvdVrie** [triton-inference-server/server#4066]
**Description**
I would like to use the `perf_analyzer` with the client from the pip package in a CPU-only client. 
I install the Python library in a standalone Docker image. This enables me to run the client on CPU-only systems while communicating with a GPU instance of the TRITON server. While trying to use the analyzer in this image the following error occurs: `perf_analyzer: error while loading shared libraries: libcudart.so.11.0: cannot open shared object file: No such file or directory`. This is logical because the container does not have any access to a GPU nor the CUDA libraries. 
Is it the case that the `perf_analyzer` requires access to a GPU / the GPU running the model? If so where can I find this in the documentation? If not is it possible to use the analyzer on CPU-only systems?
Additionally, if the analyzer requires access to a / the GPU does this mean that it cannot be used for CPU-only servers?

**Triton Information**
_What version of Triton are you using?_
The server uses the following image: `nvcr.io/nvidia/tritonserver:22.01-py3`. 
The client uses the following Dockerfile:
```
FROM python:3.10-bullseye

RUN apt update && apt install -y --no-install-recommends \
        curl \
        make \
        automake \
        gcc \
        g++ \
        subversion \
        pkg-config \
        wget \
        libb64-dev

WORKDIR /Workdir/Install

RUN python3 -m pip install --upgrade wheel setuptools cython addict attrdict munch joblib numpy Pillow future

ARG TRITON_VERSION="2.18.0"

RUN wget https://github.com/triton-inference-server/server/releases/download/v${TRITON_VERSION}/v${TRITON_VERSION}_ubuntu2004.clients.tar.gz && \
    mkdir -p client_src && \
    tar -xf v${TRITON_VERSION}_ubuntu2004.clients.tar.gz -C client_src && \
    pip install /Workdir/Install/client_src/python/tritonclient-${TRITON_VERSION}-py3-none-manylinux1_x86_64.whl[all] && \
    rm -r * 

RUN rm -r /Workdir/Install
WORKDIR /Workdir/
```

**To Reproduce**
_Steps to reproduce the behavior._
After building the client run the command `perf_analyzer -h` which fails with the error mentioned above.

**Expected behavior**
_A clear and concise description of what you expected to happen._
I expect to be able to use the performance analyzer on CPU-only systems, only when using shared memory options would the CUDA library be required. If it is required for the analyzer to be run with access to a or the server GPU could this be added to the documentation somewhere?

**Comment by Tabrizian** [comment]
It is not required to have a GPU but perf analyzer expects the CUDA libraries to be present even in the CPU only mode. If you don't want to install the CUDA libraries, you would need to compile the perf analyzer by yourself and set the `-DTRITON_ENABLE_GPU=OFF` in [this section](https://github.com/triton-inference-server/client#build-using-cmake).

**Comment by GuanLuo** [comment]
Currently the `tfs` and `torchserve` parts of `perf_analyzer` can not be disabled, however, we do have plan to add option to disable them. Before that, you will have to remove the related code to exclude them from the build
