### ISSUE TITLE
build the server in a container

### ISSUE THREAD

**Issue by MAhaitao999** [triton-inference-server/server#4067]
Hi all:
I docker run a container with the following command:
`docker run --gpus all -it --network=host \
           --privileged --shm-size=32g \
           -v /var/run/docker.sock:/var/run/docker.sock \
           --name=trtis_dms_workflow nvcr.io/nvidia/tritonserver:21.07-py3 bash`

in the container, I build the server with:
`./build.py --cmake-dir=/workspace/server/build --build-dir=/tmp/citritonbuild --enable-logging --enable-stats --enable-tracing --enable-metrics --enable-gpu-metrics --enable-gpu --endpoint=http --endpoint=grpc --repo-tag=common:r21.07 --repo-tag=core:r21.07 --repo-tag=backend:r21.07 --repo-tag=thirdparty:r21.07 --backend=tensorrt:r21.07 --backend=identity:r21.07 --backend=repeat:r21.07 --backend=square:r21.07 --backend=pytorch:r21.07 --backend=tensorflow1:r21.07 --backend=tensorflow2:r21.07 --backend=openvino:r21.07 --backend=python:r21.07 --backend=fil:r21.07 --repoagent=checksum:r21.07 --backend=ensemble:r21.07 --no-container-build --upstream-container-version=21.07`

But the tensorrt backend is not loaded successfully! Can anybody tell me what is wrong in the script?

**Comment by MAhaitao999** [comment]
![image](https://user-images.githubusercontent.com/8710394/158775154-cc691c35-5755-4033-861c-0067f1a39f67.png)

**Comment by MAhaitao999** [comment]
I am very sure my model det is ok!

**Comment by dzier** [comment]
How are you launching Triton in the container? That error means it could not find the model directory `det`. I noticed that you virtual link or mount to an local drive in the docker run command.

**Comment by MAhaitao999** [comment]
> How are you launching Triton in the container? That error means it could not find the model directory `det`. I noticed that you virtual link or mount to an local drive in the docker run command.

`/tmp/citritonbuild/opt/tritonserver/bin/tritonserver --model-repository=/models`
![image](https://user-images.githubusercontent.com/8710394/158924417-7c80e013-3015-46d2-b9a5-daeec23997f6.png)

**Comment by deadeyegoodwin** [comment]
Are you running build.py from the 21,07 branch of the "server" repo? Can you post the entire console log.

**Comment by tanmayv25** [comment]
Closing the issue because of inactivity. Please re-open if you are still running into issues.
