### ISSUE TITLE
POSTing Base64 image to Triton running YOLOV4/TensorRT model

### ISSUE THREAD

**Issue by dominusLabs** [triton-inference-server/server#4078]
Hello! 

I'm still getting used to Triton and figuring it out, since I only heard about Triton ~3 days ago. We're looking to use it to deploy our YoloV4 model, optimized with TensorRT using Triton. 

Currently, we're running a very basic Flask server. We use a NodeJS script to send an image as base64 and POST it to our Flask API. The API then takes the base64 data and saves it to a file, which is then used by YoloV4 to detect and returns the detections in a JSON format. 

So we're hoping to do something similar with Triton, ideally by using only HTTP requests (and not having to use any of the client libraries). We've already converted our YoloV4 to ONNX and then to TensorRT, and are running it with Triton with the following configuration:

```
name: "yolov4"
platform: "tensorrt_plan"
max_batch_size: 0
input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [ 3, 416, 416 ]
  }
]
output [
  {
    name: "boxes"
    data_type: TYPE_FP32
    dims: [ 22743, 1, 4 ]
  },
  {
    name: "confs"
    data_type: TYPE_FP32
    dims: [ 122743, 80 ]
  }
]
```

So I understand that with this config, we're essentially telling Triton that it should expect FP32 tensor data. But is there a way to get Triton to accept base64 and then convert it to FP32 on the server that is running Triton? Or maybe sending the image as binary data? 

We're trying to avoid using the client libraries and only use HTTP requests for everything, since the rest of our API/system is already configured to work in such a way.

**Comment by dominusLabs** [comment]
Closing as the tensorflow-js library seems to be able to do what we need it to. Will open again in case that doesn't work out.

**Comment by leemengwei** [comment]
@dominusLabs Hi  can you be more specific? I'm trying to post base64 with pure postman to a yolo trt server
thanks in advance
