### ISSUE TITLE
object class 'GstNvInferServer' has no property named 'input-tensor-meta'

### ISSUE THREAD

**Issue by sandeepy1** [triton-inference-server/server#4081]
I am trying to run faster rcnn from [here](https://github.com/NVIDIA-AI-IOT/deepstream_triton_model_deploy/tree/master/faster_rcnn_inception_v2) 

But getting this error:
```
deepstream-app -c source1_primary_faster_rcnn_inception_v2.txt 

(deepstream-app:69): GLib-GObject-WARNING **: 16:30:49.275: g_object_set_is_valid_property: object class 'GstNvInferServer' has no property named 'input-tensor-meta'
** ERROR: <main:707>: Failed to set pipeline to PAUSED
Quitting
App run failed

```

**Comment by dyastremsky** [comment]
That error is not from Triton. It looks to be an error from the Gst-nvinferserver plugin. Opening an issue in the source repo you linked or perhaps DeepStream is your best bet.
