### ISSUE TITLE
Request to cherry-pick fixes in tensorrt-backend for 22.03

### ISSUE THREAD

**Issue by naor2013** [triton-inference-server/server#4088]
If it's not too late, can you cherry pick the fixes in tensorrt-backend to 22.03?
Specifically the one that is important to me is https://github.com/triton-inference-server/tensorrt_backend/pull/26

I tried to build the tensorrt-backend by myself and while it seems that Triton found that backend and didn't fail to load it, the bug still remained so I probably did something wrong.
So it would be great if I could get this fix sooner rather than later, thanks!

**Comment by deadeyegoodwin** [comment]
22.03 release is already past code freeze so no additional changes will be added. The TensorRT backend fixes will be in 22.04.
