### ISSUE TITLE
Some confusions about MessageQueue in python backend.

### ISSUE THREAD

**Issue by spxcds** [triton-inference-server/server#4094]
**Description**

In python backend, there's a class named MessageQueue. When I performing a push operation, [(*index_)++](https://github.com/triton-inference-server/python_backend/blob/main/src/message_queue.cc#L120), and [(*index_)--](https://github.com/triton-inference-server/python_backend/blob/main/src/message_queue.cc#L148) will be executed when there is a pop operation.

Therefore I consider it is a `MessageStack` more than a `MessageQueue`. In some circumstance, elements in this stack may never be visited. So, @Tabrizian could you share you thoughts about this class to solve my confuison?

Thanks!

**Comment by Tabrizian** [comment]
You're correct. This is a message stack. Having said that, it has been converted to a message queue in an upcoming PR. https://github.com/triton-inference-server/python_backend/pull/128

> elements in this stack may never be visited. So, @Tabrizian could you share you thoughts about this class to solve my confuison?

Can you elaborate on this? I don't think there is a case where the messages will not be visited.

**Comment by spxcds** [comment]
> Can you elaborate on this? I don't think there is a case where the messages will not be visited.

I read other codes in python backend, `MessageQueue` works fine in actually.

Thanks for your patience.
