### ISSUE TITLE
Failed to load model - Unknown Builtin Op Torch Sparse

### ISSUE THREAD

**Issue by mprithiv** [triton-inference-server/server#4101]
**Description**
Failed to load a GNN model
failed to load 'gat' version 1: Internal: failed to load model 'gat': 
Unknown builtin op: torch_sparse::ptr2ind.
Could not find any similar ops to torch_sparse::ptr2ind. This op may not exist or may not be currently supported in TorchScript.
**Triton Information**
What version of Triton are you using?
22.02-py3
Are you using the Triton container or did you build it yourself?
Triton
**To Reproduce**
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
GATConv, PyG
**Expected behavior**

**Comment by CoderHam** [comment]
@mprithiv torch_sparse is not part of the vanilla pytorch library is it? Triton does not include the miscellaneous extension libraries for pytorch.

**Comment by mprithiv** [comment]
No it is not a part of vanilla pytorch but it is a required package for PyG model I am using. Is there any way to include packages like torch_scatter, torch_sparse with the deployment?

**Comment by deadeyegoodwin** [comment]
Here is documentation on adding custom pytorch operations: https://github.com/triton-inference-server/server/blob/main/docs/custom_operations.md#pytorch
