### ISSUE TITLE
No response after a long period

### ISSUE THREAD

**Issue by zachluo** [triton-inference-server/server#4103]
**Description**
When exporting a PyTorch model by torch script, the server will not respond to any requests after running near one month normally. Does anyone meet the same issue?

**Triton Information**
What version of Triton are you using?
21.03

Are you using the Triton container or did you build it yourself?
Triton container

**To Reproduce**
Steps to reproduce the behavior.
N/A

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
Yolov5

**Expected behavior**
It is expected to be normal forever.

**Comment by CoderHam** [comment]
@zachluo we would need some more information to be able to triage this. In terms of resolution I would recommend trying to record memory usage to see if there is a trailing memory leak that causes the machine your server is being run on to hit an OOM state.

We do stress test Triton but not for as long as a month. If you could provide us repro steps to reproduce this in a smaller interval like a single day that would be great.

**Comment by tanmayv25** [comment]
Closing the issue because of inactivity. Please share the requested additional information for us to be able to better assist you.
