### ISSUE TITLE
how should i run the fastertransformer(FT) custom op with TIS?

### ISSUE THREAD

**Issue by 520jefferson** [triton-inference-server/server#4111]
The model size increase , then i have to use the FT to do some optimization before online serving. 

The FT support the  related TIS support the gpt https://github.com/triton-inference-server/fastertransformer_backend, but not T5.

If i want to use TIS to support T5(after FT optimmization)？ i just find the t5 triton_backend file https://github.com/NVIDIA/FasterTransformer/tree/dev/v5.0_beta/src/fastertransformer/triton_backend/t5，but it seems not a custom C++ operations of torchscript (https://github.com/triton-inference-server/server/blob/main/docs/custom_operations.md pytorch . what shoud i do to support FT T5 model's inference with TIS?

**Comment by byshiue** [comment]
FT has supported the T5 in Triton, you can refer the guide in https://github.com/triton-inference-server/fastertransformer_backend/tree/dev/v1.1_beta#prepare-triton-t5-model-store-in-the-docker.

**Comment by 520jefferson** [comment]
i met this error when building docker image.
Error response from daemon: No such image: triton_with_ft:21.07
