### ISSUE TITLE
[Feature Request] Allow ensemble model's sub-models to be inside the model dir

### ISSUE THREAD

**Issue by dumbPy** [triton-inference-server/server#4118]
**Is your feature request related to a problem? Please describe.**

Consider an ensemble model `M1` being an ensemble of `M11, M12, M13`. When we call load model api for M1, it would implicitly load M11, M12, M13 which is great...  
But, These need to live in the same folder as `M1`, and hence are always independent models, that need to be put in place individually.
```
models
├── M1
├── M11
├── M12
└── M13
```
Since triton doesn't cater to model placement, it needs to be handled either by the user's sidecar service, or in kserve by [modelmesh-runtime-adapter](https://github.com/kserve/modelmesh-runtime-adapter/tree/main/model-mesh-triton-adapter) that takes care of pulling the required models from model store.

Since they are at the same level, any service catering to this model placement would have to deduce which all model folders it needs to grab by parsing the `config.ptbxt`, to know which all models to grab when trying to grab model `M1`.

It would be far less complicated if a single dir `models/M1` can always be associated to the model `M1`.

**Describe the solution you'd like**

A simple solution would be to support loading sub-models in ensemble from within the model dir.
```
models
└── M1
    ├── M11
    ├── M12
    └── M13
```
inside `M1/config.pbtxt`, these can be loaded as `M1/M11`, `M1/M12`, `M1/M13`, or just `M1`,`M2` and `M3` for that matter, by searching for them in `M1` dir.

This would inherently make ensemble model work in kserve as well.

**Describe alternatives you've considered**

I tried using BLS where, while loading `M1`, I make symlinks `M11 -> M1/M11`, `M12 -> M1/M12` but need to also load M11, M12 individually (any model starting with `M1`) and using model.py to call M11 and M12 from within M1. 
This becomes messy, and slower that using ensemble model.

**Additional context**

I haven't tried ensemble models in kserve, and don't know if it attempts to cater to ensemble models by doing anything like such, but the source code doesn't seem to handle pulling `M11`, `M12` separately.

**Comment by GuanLuo** [comment]
This flatten structure is to allow the individual model to be used for different ensemble model, i.e. you may have a model for pre-processing which can be the first step in different ensembles.

For your use case, since you have provided the sidecar service, the sidecar may check if you are uploading a collection of models (i.e. directory that does not contain config.pbtxt) instead of uploading one model and it will place each model within the collection to the model repository.
