### ISSUE TITLE
Grpc compression increases the latency quite a lot?

### ISSUE THREAD

**Issue by tuotuoshao** [triton-inference-server/server#4131]
Here are two experiments with compare:
1
![hWIZhw1TII](https://user-images.githubusercontent.com/51219602/160833685-68b22ba3-a1fd-46b7-85bd-4676a03a57ee.png)
2
![woxG9CJHQl](https://user-images.githubusercontent.com/51219602/160833790-a18d6858-54b4-48d1-843b-e0bca6c4c971.png)

what' the wrong?

**Comment by GuanLuo** [comment]
The (de-)compression itself has some overhead, so there can be negative impact until the data to be transferred is sufficiently large

**Comment by tuotuoshao** [comment]
@GuanLuo  I've tried large input data just like 1x5000x10000x3 but it still generated greater latency than no compression. Could you tell me when should i use the compression and it is eactly more efficient than no compression？

**Comment by GuanLuo** [comment]
@tanmayv25 do you have some insights to share? I don't think we have done in-depth compression benchmarking.

**Comment by tanmayv25** [comment]
As Guan suggested compression is always going to add an overhead(time spent in compression and de-compression). But just large data does not guarantees you will see a perf benefit of compression.
It only helps when you have identified that bottleneck is in your network connection. The bandwidth is a limited resource and can support only certain bytes/sec of data transfer. compression/decompression can help you transfer your request data more quickly between client and server. 
**It looks like you are running the server as a localhost which I believe can support large bandwidth.** 
> Could you tell me when should i use the compression and it is eactly more efficient than no compression？

Running the server in a remote machine with limited bandwidth where it is serving requests from multiple clients (which might lead to network congestion), may be a useful case for using compression.

**Comment by tuotuoshao** [comment]
@tanmayv25  Thank you for your clarification, now I have a clear concept of it. I'll measure the practical latency of compression and de-compression in a remote enviroment as my input shape likes 1x720x1280x3 or 1x1080x1920x3  at future.

**Comment by tanmayv25** [comment]
Closing the issue for now. Please open a new issue if you find something wrong with the gRPC compression in Triton.
