### ISSUE TITLE
python backend always loading!

### ISSUE THREAD

**Issue by hegc** [triton-inference-server/server#4132]
**Description**
I make a custom python stub and conda env files, when load model using python platfom, the starting process get stucked.

**Triton Information**
What version of Triton are you using?
docker run --gpus=1 --shm-size=50G --rm -p8000:8000 -p8001:8001 -p8002:8002 -v/path/to/model_repository:/models nvcr.io/nvidia/tritonserver:22.02-py3 tritonserver --model-repository=/models --model-control-mode=explicit --exit-on-error=true --log-verbose=true

Are you using the Triton container or did you build it yourself?
nvcr.io/nvidia/tritonserver:22.02-py3

**To Reproduce**
Steps to reproduce the behavior.
make python stub:
`cmake -DTRITON_ENABLE_GPU=ON -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/install ..`
`apt-get -y install libgl1`
`apt-get install -y rapidjson-dev libarchive-dev`
`make triton-python-backend-stub`

the config.pbtxt:
parameters: {
  key: "EXECUTION_ENV_PATH",
  value: {string_value: "$$TRITON_MODEL_DIRECTORY/python3.8.10.tar.gz"}
}

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**
I0330 12:54:21.202837 1 http_server.cc:3075] Started HTTPService at 0.0.0.0:8000
I0330 12:54:21.244809 1 http_server.cc:178] Started Metrics Service at 0.0.0.0:8002

I0330 12:54:36.125292 1 http_server.cc:2976] HTTP request: 2 /v2/repository/index
I0330 12:54:36.125469 1 model_repository_manager.cc:522] ModelStates()
I0330 12:54:44.776590 1 http_server.cc:2976] HTTP request: 2 /v2/repository/models/retinaface_end2end/load
I0330 12:54:44.778163 1 model_config_utils.cc:667] Server side auto-completed config: name: "retinaface_end2end"
input {
  name: "MODEL_NAME"
  data_type: TYPE_STRING
  dims: 1
}
input {
  name: "INPUT0"
  data_type: TYPE_STRING
  dims: 1
}
output {
  name: "OUTPUT0"
  data_type: TYPE_FP32
  dims: 4
}
output {
  name: "OUTPUT1"
  data_type: TYPE_FP32
  dims: 5
  dims: 2
}
output {
  name: "OUTPUT2"
  data_type: TYPE_FP32
  dims: 1
}
parameters {
  key: "EXECUTION_ENV_PATH"
  value {
    string_value: "$$TRITON_MODEL_DIRECTORY/python3.8.10.tar.gz"
  }
}
backend: "python"

I0330 12:54:44.779881 1 model_repository_manager.cc:700] AsyncLoad() 'retinaface_end2end'
I0330 12:54:44.779955 1 model_repository_manager.cc:939] TriggerNextAction() 'retinaface_end2end' version 1: 1
I0330 12:54:44.779972 1 model_repository_manager.cc:975] Load() 'retinaface_end2end' version 1
I0330 12:54:44.779979 1 model_repository_manager.cc:994] loading: retinaface_end2end:1
I0330 12:54:44.880179 1 model_repository_manager.cc:1052] CreateModel() 'retinaface_end2end' version 1
I0330 12:54:44.880321 1 shared_library.cc:108] OpenLibraryHandle: /opt/tritonserver/backends/python/libtriton_python.so
I0330 12:54:44.882759 1 python.cc:1679] 'python' TRITONBACKEND API version: 1.8
I0330 12:54:44.882777 1 python.cc:1701] backend configuration:
{}
I0330 12:54:44.882795 1 python.cc:1811] Shared memory configuration is shm-default-byte-size=67108864,shm-growth-byte-size=67108864,stub-timeout-seconds=30
I0330 12:54:44.882943 1 python.cc:1859] TRITONBACKEND_ModelInitialize: retinaface_end2end (version 1)
I0330 12:54:44.884530 1 model_config_utils.cc:1616] ModelConfig 64-bit fields:
I0330 12:54:44.884546 1 model_config_utils.cc:1618] 	ModelConfig::dynamic_batching::default_queue_policy::default_timeout_microseconds
I0330 12:54:44.884553 1 model_config_utils.cc:1618] 	ModelConfig::dynamic_batching::max_queue_delay_microseconds
I0330 12:54:44.884559 1 model_config_utils.cc:1618] 	ModelConfig::dynamic_batching::priority_queue_policy::value::default_timeout_microseconds
I0330 12:54:44.884568 1 model_config_utils.cc:1618] 	ModelConfig::ensemble_scheduling::step::model_version
I0330 12:54:44.884574 1 model_config_utils.cc:1618] 	ModelConfig::input::dims
I0330 12:54:44.884584 1 model_config_utils.cc:1618] 	ModelConfig::input::reshape::shape
I0330 12:54:44.884590 1 model_config_utils.cc:1618] 	ModelConfig::instance_group::secondary_devices::device_id
I0330 12:54:44.884596 1 model_config_utils.cc:1618] 	ModelConfig::model_warmup::inputs::value::dims
I0330 12:54:44.884604 1 model_config_utils.cc:1618] 	ModelConfig::optimization::cuda::graph_spec::graph_lower_bound::input::value::dim
I0330 12:54:44.884611 1 model_config_utils.cc:1618] 	ModelConfig::optimization::cuda::graph_spec::input::value::dim
I0330 12:54:44.884617 1 model_config_utils.cc:1618] 	ModelConfig::output::dims
I0330 12:54:44.884625 1 model_config_utils.cc:1618] 	ModelConfig::output::reshape::shape
I0330 12:54:44.884631 1 model_config_utils.cc:1618] 	ModelConfig::sequence_batching::direct::max_queue_delay_microseconds
I0330 12:54:44.884636 1 model_config_utils.cc:1618] 	ModelConfig::sequence_batching::max_sequence_idle_microseconds
I0330 12:54:44.884642 1 model_config_utils.cc:1618] 	ModelConfig::sequence_batching::oldest::max_queue_delay_microseconds
I0330 12:54:44.884647 1 model_config_utils.cc:1618] 	ModelConfig::sequence_batching::state::dims
I0330 12:54:44.884653 1 model_config_utils.cc:1618] 	ModelConfig::sequence_batching::state::initial_state::dims
I0330 12:54:44.884658 1 model_config_utils.cc:1618] 	ModelConfig::version_policy::specific::versions
I0330 12:54:44.884859 1 python.cc:1618] Using Python execution env /models/retinaface_end2end/python3.8.10.tar.gz
I0330 12:54:44.889722 1 python.cc:1903] TRITONBACKEND_ModelInstanceInitialize: retinaface_end2end (GPU device 0)
I0330 12:54:44.890565 1 backend_model_instance.cc:105] Creating instance retinaface_end2end on GPU 0 (6.1) using artifact ''
I0330 12:54:56.458038 73 python.cc:1206] Starting Python backend stub: source /tmp/python_env_A4FJ5e/0/bin/activate && exec env LD_LIBRARY_PATH=/tmp/python_env_A4FJ5e/0/lib:$LD_LIBRARY_PATH /models/retinaface_end2end/triton_python_backend_stub /models/retinaface_end2end/1/model.py triton_python_backend_shm_region_1 67108864 67108864 1 /opt/tritonserver/backends/python 56 retinaface_end2end

And then, stucked here...

**Comment by hegc** [comment]
drwxrwxr-x 3 supdev supdev      4096 3月  30 20:54 1
-rw-r--r-- 1 supdev supdev       571 3月  30 19:58 config.pbtxt
-rw------- 1 supdev supdev 408425936 3月  30 16:16 python3.8.10.tar.gz
-rwxr-xr-x 1 supdev supdev    690440 3月  30 18:32 triton_python_backend_stub

**Comment by Tabrizian** [comment]
@hegc Did you compile the stub on the 22.02 branch? The Github branch that the stub uses must match the Triton version.

**Comment by hegc** [comment]
Great! It works. Thank you.

**Comment by Tabrizian** [comment]
Closing, the ticket as the issue has been solved.
