### ISSUE TITLE
Q. Is BLS and model excution run with pipeline parallelism

### ISSUE THREAD

**Issue by codertimo** [triton-inference-server/server#4137]
**Description**

I want to know that BLS(python backend ex: Preprocess) and model execution run with pipeline parallelism.

![IMG_0288](https://user-images.githubusercontent.com/9063575/160999754-a0d8a7c4-1f51-40ba-ae29-58b0bc470d72.jpg)

**Comment by hegc** [comment]
If there are only one BLS instance, the requests is not parallel processed.

**Comment by Tabrizian** [comment]
Closing the ticket, due to in-activity.

**Comment by Jackiexiao** [comment]
if python backend using BLS, there would be a lot of time waiting for other model to exec request. so could we support parallelism with one python backend instance (instead of creating multiple instances) @Tabrizian

**Comment by Jackiexiao** [comment]
there is a async mode, but
> Currently, async BLS requests are not supported in decoupled mode.

**Comment by Jackiexiao** [comment]
ps: in document python decoupled

> The request data and InferenceResponseSender object can be passed to a separate thread in the model. This means main caller thread can exit from execute function and the model can still continue generating responses as long as it holds InferenceResponseSender object.
