### ISSUE TITLE
[Question] memory consumption of model loading for different instance_group count 

### ISSUE THREAD

**Issue by zijin520** [triton-inference-server/server#4138]
We know that when a model is loaded the model is loaded into memory for inference in any time.
If the instance count is set to be 2, does it take twice as much memory as the count 1? If so, why cannot we use the same model loaded memory for the two instances to reduce memory consumption because they are indeed created from the same model. Thanks.
instance_group [
 {
     count: 2
 }
]

**Comment by GuanLuo** [comment]
> If the instance count is set to be 2, does it take twice as much memory as the count 1? 

Yes in general, but some backends (i.e. TRT backend, TF backend) will try to share model weight across instances as much as possible.

Note that for some cases you must have separate model copy for each instance to avoid unintended interference, for example, NLP models may need to maintain internal state for a sequence of requests which won't work properly if the model is shared.
