### ISSUE TITLE
Request custom model metadata

### ISSUE THREAD

**Issue by gandharv-kapoor** [triton-inference-server/server#4139]
This is in line with following feature request but probably addresses a broader problem PR https://github.com/triton-inference-server/server/issues/3484
As mentioned in the PR keeping model metadata and client always in sync is hard in a distributed environment specially where client hardly changes but models are regularly updated. Therefore it would be great if GET Model Metadata had some extension field to allow setting and retrieval of custom model metadata fields not just a label. Labels are certainly one thing I should be able to retrieve but there can be custom keys and value parameters which are needed by client to further better process and understand model output.

**Describe the solution you'd like**
Have a parameter/extension key/value field in model metadata which can be supplied in config.pbtx and later can be retrieved as part of GET model metadata request. This will also be able to support label use case requested in the [Feature Request 3484](https://github.com/triton-inference-server/server/issues/3484)

**Comment by GuanLuo** [comment]
I think your request can be addressed by [model config protocol](https://github.com/triton-inference-server/server/blob/main/docs/protocol/extension_model_configuration.md) which is the endpoint to retrieve model configuration. And the user-specified parameter can be added to model config's [parameters](https://github.com/triton-inference-server/common/blob/main/protobuf/model_config.proto#L1922) field

**Comment by Tabrizian** [comment]
Closing due to in-activity.
