### ISSUE TITLE
How should I request a model whose input is a dictionary？

### ISSUE THREAD

**Issue by stringbue** [triton-inference-server/server#4144]
**Description**
I'm deploying a model via docker and its input is a dictionary in a format like {"key": tensor}.
By querying the readme, I found that Triton supports Dictionary of Tensors as Input, but what makes me wonder is, how should I write the input of the config file?
And how should I pass the image data into the model via tritonclient.http? How does set_data_from_numpy handle a dictionary data?

**Triton Information**
Triton version 2.11.0

Are you using the Triton container or did you build it yourself?
Yes, I am using  the Triton container，version is 21.06。

**To Reproduce**
Due to work reasons, I can't provide the complete network, sorry I can only provide the forward function and config.pbtxt。
The forward：
```
   def forward(self, x: Dict):
        view_pool = []
        for k, f in x.items():
            f = self.backbone(f)
            bs = f.shape[0]
            feat_num = f.shape[1]
            f = f.view(bs, feat_num)
            view_pool.append(f)
        view_pool, _ = torch.max(torch.stack(view_pool), 0)

```

The config:
```
name: ""
platform: "pytorch_libtorch"
max_batch_size: 128
input [
  {
    name: "INPUT__0"
    data_type: TYPE_FP32
    dims: [ 3, 448, 224 ]
  }
]
output [
  {
    name: "OUTPUT__0"
    data_type: TYPE_FP32
    dims: [ -1 ]
  }
]

dynamic_batching {
    preferred_batch_size: [1, 2, 4]
    max_queue_delay_microseconds: 100
  }

```
**Expected behavior**
If I infer this model, when I want to input a dictionary of tensors, such as {"key": tensor}, there are two problems:
1. How should I modify the input in my config file and change "INPUT__0" in "name" to "key"?
2. If I want to pass an image to the model in docker through tritonclient.http, how should I modify the following request? "img" should be a numpy, how should I put it into a dictionary?
     ```
        triton_client = httpclient.InferenceServerClient(url='127.0.0.1:8000')
        inputs = []
        inputs.append(httpclient.InferInput('INPUT__0', img.shape, "FP32"))
        inputs[0].set_data_from_numpy(img, binary_data=False)
        outputs = []
        outputs.append(httpclient.InferRequestedOutput('OUTPUT__0', binary_data=False))
      
        results = triton_client.infer(infer_name, inputs=inputs, outputs=outputs)

    ```

**Comment by dzier** [comment]
Perhaps the documentation is not clear, but it does say how to specify a dictionary input in https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#special-conventions-for-pytorch-backend. 

According the docs, the answer to 1. is to just use "key" and specify the shape and datatype associated with that "key". You do not use the "<name>_<index>" naming scheme.

> ... the input fields in the configuration do not need to follow the "<name>__<index>" convention. Instead, the names of the inputs in this case must map to the string value 'key' for that specific tensor.

For your second answer, nothing special is needed to use tritonclient.http other than correctly setting up the model config file.

**Comment by stringbue** [comment]
> Perhaps the documentation is not clear, but it does say how to specify a dictionary input in https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#special-conventions-for-pytorch-backend.
> 
> According the docs, the answer to 1. is to just use "key" and specify the shape and datatype associated with that "key". You do not use the "_" naming scheme.
> 
> > ... the input fields in the configuration do not need to follow the "__" convention. Instead, the names of the inputs in this case must map to the string value 'key' for that specific tensor.
> 
> For your second answer, nothing special is needed to use tritonclient.http other than correctly setting up the model config file.

First of all, thank you very much for your answer. 
Maybe my description of the problem is not clear enough. What I currently want to input is a single map dictionary, such as {"A":tensor}, B does not exist inside, and when I modify the input in config to name (my key name), I get an error:
  ```
UNAVAILABLE: Internal: input 'name' does not follow naming convention i.e. <name>__<index>.
```
It's not clear to me is it because my data is a dictionary of single mappings or for some other reason? 
Maybe I should upgrade the version of docker, I found that Triton supports the feature in 2.19, so should I pull 2.19 or 2.20, I'm a bit unsure if the feature is stable?

There is the second problem, my description is confusing. I mean the normal request is to convert the image data to numpy and use set_data_from_nump to convert it to tensor, but my input is a dictionary, do I need to take out the values in the dictionary separately and convert it to tensor? If I take out the values individually, can httpclient.InferInput also rebuild it back into a dictionary?

If there is a problem with my understanding, could you please show me how to input a dictionary in triton_client.infer, or give me an official example.

Thank you again。

**Comment by CoderHam** [comment]
@stringbue we should probably add an example to clear the description better. The issue here is you have not changed the input tensor names to be keys to . For example if the input to the model forward function is:

```
Model input: {'A': input0_data, 'B': input1_data}
```
Instead, the names of the inputs in this case must map to the string value 'key' for that specific tensor. In this case the inputs would be "A" and "B" instead of INPUT__0 and INPUT__1

Therefore you need to fix the input name in your model config i.e. `name: "INPUT__0"` to be the 'key' for the input dictionary. As you can see each key value pair requires a different input tensor in the model config. The names of the inputs would be 
`name: "key0"`, `name: "key1"` and so on. Hopefully this helps you understand how to pass dictionary of tensors to the PyTorch backend.

**Comment by stringbue** [comment]
> 

Thanks a lot for your answer, I finally solved the problem.
First, you need to upgrade docker to 22.03, and then follow your suggestion, change the input name to name: "dictionary key name", and then the model can be loaded and reasoned correctly.

**Comment by niqbal996** [comment]
Hi @CoderHam and @stringbue ,
I am facing a similar problem. I have a model with this config file 
```json
name: "pointpillar"
platform: "onnxruntime_onnx"
max_batch_size : 0
input [
  {
    name: "voxels"
    data_type: TYPE_FP32
    dims: [-1, 32, 4]
  },
  {
    name: "coors"
    data_type: TYPE_INT32
    dims: [-1, 4]
  },
  {
    name: "num_points"
    data_type: TYPE_INT32
    dims: [1]
  }
]
output [
  {
    name: "bbox_preds"
    data_type: TYPE_FP32
    dims: [1, 42, 248, 216]
  },
  {
    name: "dir_scores"
    data_type: TYPE_FP32
    dims: [1, 12, 248, 216]
  },
  {
    name: "scores"
    data_type: TYPE_FP32
    dims: [1, 18, 248, 216]
  }
]
```
As you see, my input to the model is also a dict(). The model is loaded correctly. Now I am writing the client function for gRPC endpoint based on image_client.py example. 
On the client side, I do something like: 
```python
self.input0 = service_pb2.ModelInferRequest().InferInputTensor()
self.input0.name = 'voxels'
self.input0.datatype = self.input_types[0]
self.input1 = service_pb2.ModelInferRequest().InferInputTensor() 
self.input1.name = 'coors'
self.input1.datatype = self.input_types[1]
self.input2 = service_pb2.ModelInferRequest().InferInputTensor() 
self.input2.name = 'num_points'
self.input2.datatype = self.input_types[2]

self.channel.request.inputs.extend([self.input0,
                                    self.input1,
                                    self.input2])
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Here is the problem
self.channel.request.raw_input_contents.extend([self.pointcloud['voxels'].tobytes(),
                                                                               np.array(self.pointcloud['voxel_coords'], dtype=np.int32).tobytes(),
                                                                               np.array([self.pc['voxel_num_points'].size], dtype=np.int32).tobytes()
                                                                              ])
```
When I send the gRPC inference request, I get the following error: 
```
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.INVALID_ARGUMENT
        details = "unexpected shape for input 'num_points' for model 'pointpillar'. Expected [1], got []"
        debug_error_string = "{"created":"@1658162360.678715249","description":"Error received from peer ipv6:[::1]:8001","file":"src/core/lib/surface/call.cc","file_line":1069,"grpc_message":"unexpected shape for input 'num_points' for model 'pointpillar'. Expected [1], got []","grpc_status":3}"
```
I tried different combinations. I am struggling with the `request.raw_input_contents` part. How should I send my dict() data to the inference server so that it can match the different keys and data types.

**Comment by whalefa1I** [comment]
> @stringbue we should probably add an example to clear the description better. The issue here is you have not changed the input tensor names to be keys to . For example if the input to the model forward function is:
> 
> ```
> Model input: {'A': input0_data, 'B': input1_data}
> ```
> 
> Instead, the names of the inputs in this case must map to the string value 'key' for that specific tensor. In this case the inputs would be "A" and "B" instead of INPUT__0 and INPUT__1
> 
> Therefore you need to fix the input name in your model config i.e. `name: "INPUT__0"` to be the 'key' for the input dictionary. As you can see each key value pair requires a different input tensor in the model config. The names of the inputs would be `name: "key0"`, `name: "key1"` and so on. Hopefully this helps you understand how to pass dictionary of tensors to the PyTorch backend.
> 

My input dict contains two keys
```
input_tensor_decoder = {
    'logits__0':
        torch.tensor(bert_result['logits']),
    'label_mask__1':
        torch.tensor(bert_result['label_mask'])
}
```
and my config.pbtxt  :
```
name: "ner_crf"
platform: "pytorch_libtorch"

max_batch_size: 128
input [
  {
    name: "logits__0"
    data_type: TYPE_FP32
    dims: [  -1, 33]
  },
{
    name: "label_mask__1"
    data_type: TYPE_BOOL
    dims: [ -1 ]
  }
]
output [
  {
    name: "predicts__0"
    data_type: TYPE_INT64
    dims: [-1]
  }
]

instance_group [
    {
      count: 1
      kind: KIND_CPU
    }
]
```
and the model is loaded correctly
but when I ussing this code to get a result from triron serve:
```
model_name = "ner_crf"
inputs = []
outputs = []

inputs.append(httpclient.InferInput('logits__0', [1, 187, 33], "FP32"))
inputs[0].set_data_from_numpy(input_ids_1, binary_data=False)

inputs.append(httpclient.InferInput('label_mask__1', [1, 187], "BOOL"))
inputs[1].set_data_from_numpy(label_mask_1, binary_data=False)
outputs.append(httpclient.InferRequestedOutput('predicts__0'))

input_dict = {
    "logits": httpclient.InferInput('logits__0', [1, 187, 33], "FP32"),
    "label_mask": httpclient.InferInput('label_mask__1', [1, 187], "BOOL"),
}
results = triton_client.infer(model_name, inputs=inputs, outputs=outputs)
```
I got an error like this 
```
tritonclient.utils.InferenceServerException: PyTorch execute failure: Expected at most 2 argument(s) for operator 'forward', but received 3 argument(s). Declaration: forward(__torch__.Decoder self, Dict(str, Tensor) inputs) -> (Tensor)
```

Should I convert the model inputs from Dict to array ?Or just modify my config file ,Thanks
