### ISSUE TITLE
python backend stuck in Starting Python backend stub when launching multiple servers simultaneously

### ISSUE THREAD

**Issue by yongbinfeng** [triton-inference-server/server#4145]
**Description**
When trying to launch two Triton servers simultaneously inside one docker container, for example, with
```
#!/bin/bash

tritonserver --model-repository=/models --log-verbose=1 --log-error=1 --log-warning=1 --log-info=1 --http-port=8050 --grpc-port=8051 --metrics-port=8052 >& runlog1.log &
tritonserver --model-repository=/models --log-verbose=1 --log-error=1 --log-warning=1 --log-info=1 --http-port=8060 --grpc-port=8061 --metrics-port=8062 >& runlog2.log &
```
One server launches successfully; but the other way **gets stuck** in
```
I0401 16:44:36.759603 111 python.cc:1859] TRITONBACKEND_ModelInitialize: add_sub (version 1)
I0401 16:44:36.761866 111 model_config_utils.cc:1608] ModelConfig 64-bit fields:
I0401 16:44:36.761896 111 model_config_utils.cc:1610]   ModelConfig::dynamic_batching::default_queue_policy::default_timeout_microseconds
I0401 16:44:36.761913 111 model_config_utils.cc:1610]   ModelConfig::dynamic_batching::max_queue_delay_microseconds
I0401 16:44:36.761927 111 model_config_utils.cc:1610]   ModelConfig::dynamic_batching::priority_queue_policy::value::default_timeout_microseconds
I0401 16:44:36.761942 111 model_config_utils.cc:1610]   ModelConfig::ensemble_scheduling::step::model_version
I0401 16:44:36.761969 111 model_config_utils.cc:1610]   ModelConfig::input::dims
I0401 16:44:36.761984 111 model_config_utils.cc:1610]   ModelConfig::input::reshape::shape
I0401 16:44:36.762000 111 model_config_utils.cc:1610]   ModelConfig::instance_group::secondary_devices::device_id
I0401 16:44:36.762015 111 model_config_utils.cc:1610]   ModelConfig::model_warmup::inputs::value::dims
I0401 16:44:36.762029 111 model_config_utils.cc:1610]   ModelConfig::optimization::cuda::graph_spec::graph_lower_bound::input::value::dim
I0401 16:44:36.762045 111 model_config_utils.cc:1610]   ModelConfig::optimization::cuda::graph_spec::input::value::dim
I0401 16:44:36.762059 111 model_config_utils.cc:1610]   ModelConfig::output::dims
I0401 16:44:36.762074 111 model_config_utils.cc:1610]   ModelConfig::output::reshape::shape
I0401 16:44:36.762090 111 model_config_utils.cc:1610]   ModelConfig::sequence_batching::direct::max_queue_delay_microseconds
I0401 16:44:36.762104 111 model_config_utils.cc:1610]   ModelConfig::sequence_batching::max_sequence_idle_microseconds
I0401 16:44:36.762120 111 model_config_utils.cc:1610]   ModelConfig::sequence_batching::oldest::max_queue_delay_microseconds
I0401 16:44:36.762135 111 model_config_utils.cc:1610]   ModelConfig::sequence_batching::state::dims
I0401 16:44:36.762148 111 model_config_utils.cc:1610]   ModelConfig::sequence_batching::state::initial_state::dims
I0401 16:44:36.762164 111 model_config_utils.cc:1610]   ModelConfig::version_policy::specific::versions
I0401 16:44:36.763176 111 python.cc:1903] TRITONBACKEND_ModelInstanceInitialize: add_sub_0 (CPU device 0)
I0401 16:44:36.763216 111 backend_model_instance.cc:68] Creating instance add_sub_0 on CPU using artifact ''
I0401 16:44:36.789789 131 python.cc:1206] Starting Python backend stub:  exec /opt/tritonserver/backends/python/triton_python_backend_stub /models/add_sub/1/model.py triton_python_backend_shm_region_1 67108864 67108864 111 /opt/tritonserver/backends/python 56 add_sub_0
```
forever and never moves on.

Not sure if it is related to the issue https://github.com/triton-inference-server/server/issues/4113 - the setup is quite different but they both get stuck in the same place.

**Triton Information**
We are using official Triton container 22.03-py3 but we think the error is persistent with all different servers we have tested so far.

**To Reproduce**
We are testing with the `add_sub` model in the python backend repo: https://github.com/triton-inference-server/python_backend/blob/main/examples/add_sub/model.py.

Start the docker container interactively including the `add_sub` model directory:
```
nvidia-docker run -it --rm -v${PWD}/models:/models nvcr.io/nvidia/tritonserver:22.03-py3
```
Then run the above script to launch two servers simultaneously - one of them will get stuck.

Sometimes the first time everything runs fine. Then stop the two servers and run again - the problem will occur and one of the servers gets stuck in Starting Python backend stub.

**Expected behavior**
Expected both servers to launch successfully, instead of one getting stuck.

**Comment by Tabrizian** [comment]
When running multiple tritonserver instances on the same machine, you need to change the `shm_region` prefix in Python backend. You can control the prefix name using the `shm-region-prefix-name` backend config flag.

```
tritonserver --model-repository `pwd`/models --backend-config=python,shm-region-prefix-name=prefix1_
tritonserver --model-repository `pwd`/models --backend-config=python,shm-region-prefix-name=prefix2_
```

**Comment by yongbinfeng** [comment]
Thanks a lot - this fixes our issue!

(Could the document be updated accordingly? Didn't see this was discussed anywhere in the document.)

**Comment by tanmayv25** [comment]
@yongbinfeng  You are correct, we are missing documentation of `shm-region-prefix-name`. Thanks for bringing it up to our notice. We have opened a ticket with the team to document these configs and their respective use-cases. 
As your problem is solved, I will be closing this issue.

**Comment by npuichigo** [comment]
> When running multiple tritonserver instances on the same machine, you need to change the `shm_region` prefix in Python backend. You can control the prefix name using the `shm-region-prefix-name` backend config flag.
> 
> ```
> tritonserver --model-repository `pwd`/models --backend-config=python,shm-region-prefix-name=prefix1_
> tritonserver --model-repository `pwd`/models --backend-config=python,shm-region-prefix-name=prefix2_
> ```
> 
> For example, the commands above will use two different shared memory region prefixes.

If run in docker, is `shm-region-prefix-name` still needed or it's isolated by docker?

**Comment by sboudouk** [comment]
> If run in two dockers, is `shm-region-prefix-name` still needed or it's isolated by docker?

I'd also like to know please :)
