### ISSUE TITLE
Can't find  tritonclient.utils.shared_memory on WIN10

### ISSUE THREAD

**Issue by wanghaohw** [triton-inference-server/server#4149]
I want to use tritonclient.utils.shared_memory with WIN10 client,but I can't import it in Pycharm.
I install tritonclient by ```pip install tritonclient[all]```  and import it by ```import tritonclient.utils.shared_memory as shm```.

**Comment by Tabrizian** [comment]
Triton on Windows does not support shared memory.

**Comment by tanmayv25** [comment]
`shared_memory` and `cuda_shared_memory` are only supported on linux systems. 
See here for more documentation:
https://github.com/triton-inference-server/client#download-using-python-package-installer-pip
