### ISSUE TITLE
sometimes slower response time with smaller batch size

### ISSUE THREAD

**Issue by zhanghaoie** [triton-inference-server/server#4170]
**Description**

**Triton Information**
What version of Triton are you using?
nvcr.io/nvidia/tritonserver:20.12-py3

Are you using the Triton container or did you build it yourself?
use container

**To Reproduce**
Steps to reproduce the behavior.

I have used the torch script to save model, the model is bert with 12 transformer layers.
I have requested the server with dynamic batch_size (16-30).
In the most time, the model responses with time below 20ms, but some responses are very slow, exceed 380ms. The request is sequential and the gpu is V100

**Expected behavior**
The response time should more stable.

below is the config file:
name: "nsp_pairmatching"
platform: "pytorch_libtorch"
#backend: "pytorch_libtorch"
max_batch_size: 32
dynamic_batching{
  preferred_batch_size: [16,32]
  max_queue_delay_microseconds: 10
}
input [
 {    name: "input__0"
 data_type: TYPE_INT32
   dims: [128]  }
 ,
{    name: "input__1"
data_type: TYPE_INT32
 dims: [128]  }
,
{    name: "input__2"
 data_type: TYPE_INT32
 dims: [128]  }
,
{    name: "input__3"
  data_type: TYPE_INT32
dims: [128]  }]
output [
{    name: "output__0"
 data_type: TYPE_FP16
 dims: [1]  }
]

**Comment by zhanghaoie** [comment]
> I0406 13:55:35.556104 125 http_server.cc:1229] HTTP request: 2 /v2/models/nsp_pairmatching/infer I0406 13:55:35.556143 125 model_repository_manager.cc:496] GetInferenceBackend() 'nsp_pairmatching' version -1 I0406 13:55:35.556155 125 model_repository_manager.cc:496] GetInferenceBackend() 'nsp_pairmatching' version -1 I0406 13:55:35.556199 125 infer_request.cc:502] prepared: [0x0x7fcd7c005120] request id: , model: nsp_pairmatching, requested version: -1, actual version: 1, flags: 0x0, correlation id: 0, batch size: 25, priority: 0, timeout (us): 0 original inputs: [0x0x7fcd7c002ad8] input: input__3, type: INT32, original shape: [25,128], batch + shape: [25,128], shape: [128] [0x0x7fcd7c002fc8] input: input__2, type: INT32, original shape: [25,128], batch + shape: [25,128], shape: [128] [0x0x7fcd7c0037f8] input: input__1, type: INT32, original shape: [25,128], batch + shape: [25,128], shape: [128] [0x0x7fcd7c004658] input: input__0, type: INT32, original shape: [25,128], batch + shape: [25,128], shape: [128] override inputs: inputs: [0x0x7fcd7c004658] input: input__0, type: INT32, original shape: [25,128], batch + shape: [25,128], shape: [128] [0x0x7fcd7c0037f8] input: input__1, type: INT32, original shape: [25,128], batch + shape: [25,128], shape: [128] [0x0x7fcd7c002fc8] input: input__2, type: INT32, original shape: [25,128], batch + shape: [25,128], shape: [128] [0x0x7fcd7c002ad8] input: input__3, type: INT32, original shape: [25,128], batch + shape: [25,128], shape: [128] original requested outputs: output__0 requested outputs: output__0
> 
> I0406 13:55:35.556279 125 libtorch.cc:1100] model nsp_pairmatching, instance nsp_pairmatching, executing 1 requests I0406 13:55:35.556307 125 libtorch.cc:510] TRITONBACKEND_ModelExecute: Running nsp_pairmatching with 1 requests I0406 13:55:35.562061 125 infer_response.cc:165] add response output: output: output__0, type: FP16, shape: [25,1] I0406 13:55:35.562235 125 http_server.cc:1180] HTTP: unable to provide 'output__0' in GPU, will use CPU I0406 13:55:35.562283 125 http_server.cc:1200] HTTP using buffer for: 'output__0', size: 50, addr: 0x7fcdc12530b0 I0406 13:55:35.581752 125 http_server.cc:1215] HTTP release: size 50, addr 0x7fcdc12530b0 I0406 13:55:36.961335 125 http_server.cc:1229] HTTP request: 2 /v2/models/nsp_pairmatching/infer I0406 13:55:36.961372 125 model_repository_manager.cc:496] GetInferenceBackend() 'nsp_pairmatching' version -1 I0406 13:55:36.961383 125 model_repository_manager.cc:496] GetInferenceBackend() 'nsp_pairmatching' version -1 I0406 13:55:36.961433 125 infer_request.cc:502] prepared: [0x0x7fcd7c005120] request id: , model: nsp_pairmatching, requested version: -1, actual version: 1, flags: 0x0, correlation id: 0, batch size: 23, priority: 0, timeout (us): 0 original inputs: [0x0x7fcd7c002fc8] input: input__3, type: INT32, original shape: [23,128], batch + shape: [23,128], shape: [128] [0x0x7fcd7c0037f8] input: input__2, type: INT32, original shape: [23,128], batch + shape: [23,128], shape: [128] [0x0x7fcd7c0053c8] input: input__1, type: INT32, original shape: [23,128], batch + shape: [23,128], shape: [128] [0x0x7fcd7c003308] input: input__0, type: INT32, original shape: [23,128], batch + shape: [23,128], shape: [128] override inputs: inputs: [0x0x7fcd7c003308] input: input__0, type: INT32, original shape: [23,128], batch + shape: [23,128], shape: [128] [0x0x7fcd7c0053c8] input: input__1, type: INT32, original shape: [23,128], batch + shape: [23,128], shape: [128] [0x0x7fcd7c0037f8] input: input__2, type: INT32, original shape: [23,128], batch + shape: [23,128], shape: [128] [0x0x7fcd7c002fc8] input: input__3, type: INT32, original shape: [23,128], batch + shape: [23,128], shape: [128] original requested outputs: output__0 requested outputs: output__0
> 
> I0406 13:55:36.961521 125 libtorch.cc:1100] model nsp_pairmatching, instance nsp_pairmatching, executing 1 requests I0406 13:55:36.961549 125 libtorch.cc:510] TRITONBACKEND_ModelExecute: Running nsp_pairmatching with 1 requests I0406 13:55:37.336897 125 infer_response.cc:165] add response output: output: output__0, type: FP16, shape: [23,1] I0406 13:55:37.336966 125 http_server.cc:1180] HTTP: unable to provide 'output__0' in GPU, will use CPU I0406 13:55:37.337410 125 http_server.cc:1200] HTTP using buffer for: 'output__0', size: 46, addr: 0x7fcdc138ea50 I0406 13:55:37.337524 125 http_server.cc:1215] HTTP release: size 46, addr 0x7fcdc138ea50

this is an example, the upper with batch size 25, but response time is about 29.88ms.
the other with batch size 23, but response time is above 300ms

**Comment by zhanghaoie** [comment]
I0406 13:55:35.556104 125 http_server.cc:1229] HTTP request: 2 /v2/models/nsp_pairmatching/infer
I0406 13:55:35.556143 125 model_repository_manager.cc:496] GetInferenceBackend() 'nsp_pairmatching' version -1
I0406 13:55:35.556155 125 model_repository_manager.cc:496] GetInferenceBackend() 'nsp_pairmatching' version -1
I0406 13:55:35.556199 125 infer_request.cc:502] prepared: [0x0x7fcd7c005120] request id: , model: nsp_pairmatching, requested version: -1, actual version: 1, flags: 0x0, correlation id: 0, batch size: 25, priority: 0, timeout (us): 0
original inputs:
[0x0x7fcd7c002ad8] input: input__3, type: INT32, original shape: [25,128], batch + shape: [25,128], shape: [128]
[0x0x7fcd7c002fc8] input: input__2, type: INT32, original shape: [25,128], batch + shape: [25,128], shape: [128]
[0x0x7fcd7c0037f8] input: input__1, type: INT32, original shape: [25,128], batch + shape: [25,128], shape: [128]
[0x0x7fcd7c004658] input: input__0, type: INT32, original shape: [25,128], batch + shape: [25,128], shape: [128]
override inputs:
inputs:
[0x0x7fcd7c004658] input: input__0, type: INT32, original shape: [25,128], batch + shape: [25,128], shape: [128]
[0x0x7fcd7c0037f8] input: input__1, type: INT32, original shape: [25,128], batch + shape: [25,128], shape: [128]
[0x0x7fcd7c002fc8] input: input__2, type: INT32, original shape: [25,128], batch + shape: [25,128], shape: [128]
[0x0x7fcd7c002ad8] input: input__3, type: INT32, original shape: [25,128], batch + shape: [25,128], shape: [128]
original requested outputs:
output__0
requested outputs:
output__0

I0406 13:55:35.556279 125 libtorch.cc:1100] model nsp_pairmatching, instance nsp_pairmatching, executing 1 requests
I0406 13:55:35.556307 125 libtorch.cc:510] TRITONBACKEND_ModelExecute: Running nsp_pairmatching with 1 requests
I0406 13:55:35.562061 125 infer_response.cc:165] add response output: output: output__0, type: FP16, shape: [25,1]
I0406 13:55:35.562235 125 http_server.cc:1180] HTTP: unable to provide 'output__0' in GPU, will use CPU
I0406 13:55:35.562283 125 http_server.cc:1200] HTTP using buffer for: 'output__0', size: 50, addr: 0x7fcdc12530b0
I0406 13:55:35.581752 125 http_server.cc:1215] HTTP release: size 50, addr 0x7fcdc12530b0
I0406 13:55:36.961335 125 http_server.cc:1229] HTTP request: 2 /v2/models/nsp_pairmatching/infer
I0406 13:55:36.961372 125 model_repository_manager.cc:496] GetInferenceBackend() 'nsp_pairmatching' version -1
I0406 13:55:36.961383 125 model_repository_manager.cc:496] GetInferenceBackend() 'nsp_pairmatching' version -1
I0406 13:55:36.961433 125 infer_request.cc:502] prepared: [0x0x7fcd7c005120] request id: , model: nsp_pairmatching, requested version: -1, actual version: 1, flags: 0x0, correlation id: 0, batch size: 23, priority: 0, timeout (us): 0
original inputs:
[0x0x7fcd7c002fc8] input: input__3, type: INT32, original shape: [23,128], batch + shape: [23,128], shape: [128]
[0x0x7fcd7c0037f8] input: input__2, type: INT32, original shape: [23,128], batch + shape: [23,128], shape: [128]
[0x0x7fcd7c0053c8] input: input__1, type: INT32, original shape: [23,128], batch + shape: [23,128], shape: [128]
[0x0x7fcd7c003308] input: input__0, type: INT32, original shape: [23,128], batch + shape: [23,128], shape: [128]
override inputs:
inputs:
[0x0x7fcd7c003308] input: input__0, type: INT32, original shape: [23,128], batch + shape: [23,128], shape: [128]
[0x0x7fcd7c0053c8] input: input__1, type: INT32, original shape: [23,128], batch + shape: [23,128], shape: [128]
[0x0x7fcd7c0037f8] input: input__2, type: INT32, original shape: [23,128], batch + shape: [23,128], shape: [128]
[0x0x7fcd7c002fc8] input: input__3, type: INT32, original shape: [23,128], batch + shape: [23,128], shape: [128]
original requested outputs:
output__0
requested outputs:
output__0

I0406 13:55:36.961521 125 libtorch.cc:1100] model nsp_pairmatching, instance nsp_pairmatching, executing 1 requests
I0406 13:55:36.961549 125 libtorch.cc:510] TRITONBACKEND_ModelExecute: Running nsp_pairmatching with 1 requests
I0406 13:55:37.336897 125 infer_response.cc:165] add response output: output: output__0, type: FP16, shape: [23,1]
I0406 13:55:37.336966 125 http_server.cc:1180] HTTP: unable to provide 'output__0' in GPU, will use CPU
I0406 13:55:37.337410 125 http_server.cc:1200] HTTP using buffer for: 'output__0', size: 46, addr: 0x7fcdc138ea50
I0406 13:55:37.337524 125 http_server.cc:1215] HTTP release: size 46, addr 0x7fcdc138ea50



the upper one batch size 25 , response time 28.99ms
the below batch size 23, response time above 300ms

**Comment by CoderHam** [comment]
@zhanghaoie can you use the perf_analyzer to provide the breakdown between total inference time.  

Follow up questions/suggestions:
- nvcr.io/nvidia/tritonserver:20.12-py3 is over a year old. Can you test with a newer release of Triton?
- Have you confirmed that this slowdown is not reproducible in PyTorch directly i.e. outside Triton?

**Comment by zhanghaoie** [comment]
> @zhanghaoie can you use the perf_analyzer to provide the breakdown between total inference time.
> 
> Follow up questions/suggestions:
> 
> * nvcr.io/nvidia/tritonserver:20.12-py3 is over a year old. Can you test with a newer release of Triton?
> * Have you confirmed that this slowdown is not reproducible in PyTorch directly i.e. outside Triton?

Ok, I will use perf analyzer to see the time cost. I have tried docker 21.07, also doen't work.

**Comment by zhanghaoie** [comment]
Request concurrency: 1
  Client: 
    Request count: 1022
    Throughput: 2452.8 infer/sec
    p50 latency: 9688 usec
    p90 latency: 9749 usec
    p95 latency: 9768 usec
    p99 latency: 9838 usec
    Avg HTTP time: 9681 usec (send/recv 47 usec + response wait 9634 usec)
  Server: 
    Inference count: 29472
    Execution count: 1228
    Successful request count: 1228
    Avg request latency: 9458 usec (overhead 17 usec + queue 12 usec + compute input 59 usec + compute infer 1896 usec + compute output 7474 usec)

Request concurrency: 2
  Client: 
    Request count: 1054
    Throughput: 2529.6 infer/sec
    p50 latency: 18859 usec
    p90 latency: 18974 usec
    p95 latency: 19018 usec
    p99 latency: 19263 usec
    Avg HTTP time: 18866 usec (send/recv 40 usec + response wait 18826 usec)
  Server: 
    Inference count: 30360
    Execution count: 1265
    Successful request count: 1265
    Avg request latency: 18658 usec (overhead 17 usec + queue 11 usec + compute input 936 usec + compute infer 10056 usec + compute output 7638 usec)

Request concurrency: 3
  Client: 
    Request count: 1061
    Throughput: 2546.4 infer/sec
    p50 latency: 28178 usec
    p90 latency: 28344 usec
    p95 latency: 28999 usec
    p99 latency: 33713 usec
    Avg HTTP time: 28189 usec (send/recv 39 usec + response wait 28150 usec)
  Server: 
    Inference count: 30552
    Execution count: 1273
    Successful request count: 1273
    Avg request latency: 27979 usec (overhead 17 usec + queue 9149 usec + compute input 134 usec + compute infer 11030 usec + compute output 7649 usec)

Request concurrency: 4
  Client: 
    Request count: 1059
    Throughput: 2541.6 infer/sec
    p50 latency: 37629 usec
    p90 latency: 37949 usec
    p95 latency: 38577 usec
    p99 latency: 45874 usec
    Avg HTTP time: 37649 usec (send/recv 42 usec + response wait 37607 usec)
  Server: 
    Inference count: 30504
    Execution count: 1271
    Successful request count: 1271
    Avg request latency: 37427 usec (overhead 16 usec + queue 18574 usec + compute input 133 usec + compute infer 9533 usec + compute output 9171 usec)



use the perf count, the time seems reasonable. But the compute output takes longer than infer, is it reasonable?

**Comment by zhanghaoie** [comment]
I doubt if my client code has some problems when requesting batch data. below is the client code.

    def test_infer(self,
                   input0_data,
                   input1_data,
                   input2_data,
                   input3_data,
                   model_name):
        inputs = []
        outputs = []
        batch_size = input0_data.shape[0]
        inputs.append(httpclient.InferInput('input__0', [batch_size, 128], "INT32"))
        inputs.append(httpclient.InferInput('input__1', [batch_size, 128], "INT32"))
        inputs.append(httpclient.InferInput('input__2', [batch_size, 128], "INT32"))
        inputs.append(httpclient.InferInput('input__3', [batch_size, 128], "INT32"))

        # Initialize the data
        inputs[0].set_data_from_numpy(input0_data, binary_data=True)
        inputs[1].set_data_from_numpy(input1_data, binary_data=True)
        inputs[2].set_data_from_numpy(input2_data, binary_data=True)
        inputs[3].set_data_from_numpy(input3_data, binary_data=True)

        outputs.append(httpclient.InferRequestedOutput('output__0', binary_data=True))

        # query_params = {'test_1': 1, 'test_2': 2}
        results = self.triton_client.infer(
            model_name,
            inputs,
            outputs=outputs)

        return results

**Comment by zhanghaoie** [comment]
I have used the python backend instead of pytorch, it seems no problem!
