### ISSUE TITLE
Jetson PyTorch wheel broken link

### ISSUE THREAD

**Issue by 1-800-BAD-CODE** [triton-inference-server/server#4172]
**Description**

Following the Jetson [documentation](https://github.com/triton-inference-server/server/blob/r22.02/docs/jetson.md) for 2.19.0, attempting to install the PyTorch wheel leads to a broken link.

**Triton Information**
2.19.0

**To Reproduce**

Link for 2.19 (broken):
```
wget https://developer.download.nvidia.com/compute/redist/jp/v461/pytorch/torch-1.11.0a0+17540c5-cp36-cp36m-linux_aarch64.whl
```

Link for 2.20 (works):
```
wget https://developer.download.nvidia.com/compute/redist/jp/v50/pytorch/torch-1.12.0a0+2c916ef.nv22.3-cp38-cp38-linux_aarch64.whl
```

**Comment by CoderHam** [comment]
@1-800-BAD-CODE thanks for bringing this to our attention. We will work on rectifying the same.

**Comment by acascio11** [comment]
This should be fixed now.

**Comment by CoderHam** [comment]
@1-800-BAD-CODE please use the new URL. The follow has also been updated in the docs.

**Comment by 1-800-BAD-CODE** [comment]
Thanks, link and libtorch both work.
