### ISSUE TITLE
[Question] The way of working of sequence_end control signal in sequece batcher

### ISSUE THREAD

**Issue by jeon30c** [triton-inference-server/server#4178]
I am using python backend and sequence batcher.
The signal comes in every 20ms but in server model I delayed the process by adding sleep of 40ms, meaning that the requests are stacking in message queue more and more as time goes on.

1. I observed that as soon as I sent control signal of sequence_end to the server, the server emptied the message queue right away and finished processing the sequence. Is it right?
2. Is there any way for the server to process all left requests even after getting sequence_end signal? or any method for client to see how many requests are left in the message queue of the server?

**Comment by tanmayv25** [comment]
Did you study the sequence batching strategy from [here](https://github.com/triton-inference-server/server/blob/main/docs/architecture.md#stateful-models)?

> I observed that as soon as I sent control signal of sequence_end to the server, the server emptied the message queue right away and finished processing the sequence. Is it right?

This should not happen. sequence_end just lets the sequence batcher know that batch slot can be used for other sequences.  What is your `max_sequence_idle_microseconds`? I am guessing that it is lesser than 20ms. Upon this timeout the batch slot is cleared to be used by the other sequence. Pending requests in the queue for original sequence will be emptied as what you are observing. What do you see when you set these timeout to a larger value?


> Is there any way for the server to process all left requests even after getting sequence_end signal? or any method for client to see how many requests are left in the message queue of the server?

As described above, the server should process all the requests even after receiving the sequence_end. You can launch server in verbose mode to check what is happening using `--log-verbose=1`. The reaper thread will clean up slot if it finds no requests have arrived for that sequence even after the configured `max_sequence_idle_microseconds`

**Comment by jeon30c** [comment]
The settings are as below.
```
sequence_batching {
  max_sequence_idle_microseconds: 5000000
  direct { }
  control_input [
    {
      name: "START"
      control [
        {
          kind: CONTROL_SEQUENCE_START
          fp32_false_true: [ 0, 1 ]
        }
      ]
    },
    {
      name: "END"
      control [
        {
          kind: CONTROL_SEQUENCE_END
          fp32_false_true: [ 0, 1 ]
        }
      ]
    },
    {
      name: "CORRID"
      control [
        {
          kind: CONTROL_SEQUENCE_CORRID
          data_type: TYPE_UINT64
        }
      ]
    }
  ]
}
```

I got logging like 

```
WARNING:root:!!!!!start sequence [1.]
WARNING:root:start end: [1.], [0.], corrid [1000] !!!!
WARNING:root:start end: [0.], [0.], corrid [1000] !!!!
WARNING:root:start end: [0.], [0.], corrid [1000] !!!!
WARNING:root:start end: [0.], [0.], corrid [1000] !!!!
WARNING:root:start end: [0.], [0.], corrid [1000] !!!!
WARNING:root:start end: [0.], [0.], corrid [1000] !!!!
WARNING:root:start end: [0.], [0.], corrid [1000] !!!!
WARNING:root:start end: [0.], [0.], corrid [1000] !!!!
WARNING:root:start end: [0.], [0.], corrid [1000] !!!!
WARNING:root:start end: [0.], [0.], corrid [1000] !!!!
WARNING:root:start end: [0.], [0.], corrid [1000] !!!!
WARNING:root:start end: [0.], [0.], corrid [1000] !!!!
WARNING:root:start end: [0.], [0.], corrid [1000] !!!!
WARNING:root:start end: [0.], [0.], corrid [1000] !!!!
WARNING:root:start end: [0.], [0.], corrid [1000] !!!!
WARNING:root:start end: [0.], [0.], corrid [1000] !!!!
WARNING:root:start end: [0.], [1.], corrid [1000] !!!!
WARNING:root:!!!!!end sequence {control_end}
```

As you said, I printed out the logging using --log-verbose=1 and at the last request I got 
```
I0411 02:12:57.911216 1 grpc_server.cc:3575] Infer failed: inference request for sequence 1000 to model 'add_sub' must specify the START flag on the first request of the sequence
```
I think this is the cause of the problem though I specified the start flag as is shown in the former logs.

Additional question:
I assigned random id to each model instance and had four instances as

```
instance_group [{ 
  count: 4
  kind: KIND_CPU }]
```

But after repeating start and stop of the stream, I found triton server utilized only three out of them like 

```
WARNING:root:!!!!!start sequence [1.]
WARNING:root:start end: [1.], [0.], corrid [1000] model id 200!!!!
WARNING:root:start end: [0.], [0.], corrid [1000] model id 200!!!!
WARNING:root:start end: [0.], [0.], corrid [1000] model id 200!!!!
WARNING:root:start end: [0.], [0.], corrid [1000] model id 200!!!!
WARNING:root:start end: [0.], [1.], corrid [1000] model id 200!!!!
WARNING:root:!!!!!end sequence {control_end}

WARNING:root:!!!!!start sequence [1.]
WARNING:root:start end: [1.], [0.], corrid [1000] model id 283!!!!
WARNING:root:start end: [0.], [0.], corrid [1000] model id 283!!!!
WARNING:root:start end: [0.], [0.], corrid [1000] model id 283!!!!
WARNING:root:start end: [0.], [0.], corrid [1000] model id 283!!!!
WARNING:root:start end: [0.], [1.], corrid [1000] model id 283!!!!
WARNING:root:!!!!!end sequence {control_end}

WARNING:root:!!!!!start sequence [1.]
WARNING:root:start end: [1.], [0.], corrid [1000] model id 176!!!!
WARNING:root:start end: [0.], [0.], corrid [1000] model id 176!!!!
WARNING:root:start end: [0.], [0.], corrid [1000] model id 176!!!!
WARNING:root:start end: [0.], [0.], corrid [1000] model id 176!!!!
WARNING:root:start end: [0.], [1.], corrid [1000] model id 176!!!!
WARNING:root:!!!!!end sequence {control_end}

WARNING:root:!!!!!start sequence [1.]
WARNING:root:start end: [1.], [0.], corrid [1000] model id 200!!!!
WARNING:root:start end: [0.], [0.], corrid [1000] model id 200!!!!
WARNING:root:start end: [0.], [1.], corrid [1000] model id 200!!!!

```
Could you let me know whether it is functioning properly?

**Comment by jeon30c** [comment]
To reproduce the situation, I tried to code a sample app. During the process, I found that I was using asynchronous library such as grpc.aio.xxx. After I switched that to synchronous version as grpc.xxx, the failure disappeared.

> With an instance count set to 4, the server should be capable of handling 4 concurrent requests. If you have requests from sufficient sequences queued up in the server, you should see all 4 instances under execution.

I will check this later. Thank you.
