### ISSUE TITLE
Triton server container lockup on stop when pinned memory is too big

### ISSUE THREAD

**Issue by remib-proovstation** [triton-inference-server/server#4179]
**Description**
When launching the triton server container with `--pinned-memory-pool-byte-size=20000000000` (20g), the container takes several minutes to stop with `docker container stop`.

When using less pinned memory, the docker stops as expected.

The more pinned memory is used, the longer it takes to stop the container, 

This bug occurs only on one of our hardware setup

**Triton Information**
The bug was reproductible with images :
nvcr.io/nvidia/tritonserver:22.01-py3
nvcr.io/nvidia/tritonserver:21.09-py3

Are you using the Triton container or did you build it yourself?
I'm using the triton container

**To Reproduce**

command for reproducing the bug:
`docker run -d --gpus=1 --rm -p8001:8000 -p8002:8001 -p8003:8002 -v /model_repository/:/models nvcr.io/nvidia/tritonserver:22.01-py3 tritonserver -- model-repository=/models --model-control-mode=explicit --pinned-memory-pool-byte-size=20000000000`

then when tritonserver is launched, `docker stop NAME_OF_CONTAINER`

When using --pinned-memory-pool-byte-size=2000000000 (2g), the docker container stop quickly as expected.

**Expected behavior**
The container should quickly stop no matter the pinned-memory-pool-byte-size and the hardware ? 

Possible related issue:
https://github.com/triton-inference-server/server/issues/3738

**Comment by tanmayv25** [comment]
> This bug occurs only on one of our hardware setup (2 x NVIDIA A30, drivers 510)

Can you describe other systems you have tried? Also their respective available memories and whether delay was observed or not.  

> then when tritonserver is launched, `docker stop NAME_OF_CONTAINER`

Can you try the following step on the machine exhibitting this issue?

1.  Launch  `nvcr.io/nvidia/tritonserver:22.01-py3` in interactive mode on the machine. 
2. Start the server within the container:
  `tritonserver -- model-repository=/models --model-control-mode=explicit --pinned-memory-pool-byte-size=20000000000`
3. Issue SIGINT(cntl+c) and check if the server exits quickly?

> Possible related issue:
> https://github.com/triton-inference-server/server/issues/3738

It might be related. Do you see similar dmesg logs when the server is stuck exiting?

**Comment by remib-proovstation** [comment]
Following exchange with the nvidia team, the issue was solved by disabling IOMMU on the machine. Thanks for the support :

**Comment by hurun** [comment]
> Following exchange with the nvidia team, the issue was solved by disabling IOMMU on the machine. Thanks for the support !

Can you provide a solution or specific implementation steps

**Comment by yeahdongcn** [comment]
@remib-proovstation Just curious how you use such a big pinned memory pool. Could you explain a little bit?
