### ISSUE TITLE
Need minimum CI test set to validate customized tritonsever gpu image built using optional features

### ISSUE THREAD

**Issue by yaoyunda** [triton-inference-server/server#4183]
**Description**

There is no clear specification and way to generate a CI test set for customized tritonsever image which is built using optional features.
Almost all current existing CI tests under qa folder are failed to validate customized  tritonsever  gpu image validation

**Triton Information**
What version of Triton are you using?
r22.03

Are you using the Triton container or did you build it yourself?
Build it myself

**To Reproduce**
Steps to reproduce the behavior.
1.  build tritonserver using optional features:
./build.py --cmake-dir=./build \
        -build-dir=/mnt/citritonbuild \
	--enable-logging \
        --enable-stats \
        --enable-tracing \
        --enable-metrics \
        --enable-gpu-metrics \
	--enable-gpu \
	--filesystem=azure_storage \
	--endpoint=http \
	--endpoint=grpc \
        --repo-tag=common:r22.03 \
        --repo-tag=core:r22.03 \
        --repo-tag=backend:r22.03 \
        --repo-tag=thirdparty:r22.03 \
        --backend=ensemble \
        --backend=identity:r22.03 \
        --backend=repeat:r22.03 \
        --backend=square:r22.03 \
	--backend=onnxruntime:r22.03 \
        --backend=python:r22.03 \
        --repoagent=checksum:r22.03

2. Follow the doc to generate the test models , sdk image and qa images.
3. Run tests

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

In the build, the targeted framework is onnxruntime and python.

**Expected behavior**

A minimum CI test set and cli to run, to validate the tritonserver gpu image with above option.

**Comment by tanmayv25** [comment]
What is the error that you are seeing? You should be able to run some of our generic tests. 
You might have to tweak the tests to only include your specified backends: https://github.com/triton-inference-server/server/blob/main/qa/L0_infer/test.sh#L119

I agree some of these tests in qa require models that are not generated by the  [gen_qa_model_repository](https://github.com/triton-inference-server/server/blob/main/qa/common/gen_qa_model_repository)` script.

> In the build, the targeted framework is onnxruntime and python.
But I see that you are building most of our backends in step 1.

**Comment by yaoyunda** [comment]
@tanmayv25 , thanks.

I have some questions for you about my optional build.
 1. Are 3 sanity tests mentioned in test doc (L0_infer, L0_batcher and L0_sequence_batcher) enough for build validation test?
 
 BACKENDS="onnx" ENSEMBLES=0 EXPECTED_NUM_TESTS=37 bash -x ./test.shBACKENDS="onnx" ENSEMBLES=0 EXPECTED_NUM_TESTS=37 bash -x ./test.sh

using above command line to run, all 3 tests are passed. However replacing the "onnx" with "python" in the command line
these 3 tests are failed, here is one of errors:
E0413 04:27:10.269925 564 model_repository_manager.cc:1155] failed to load 'python_float16_float32_float32' version 1: Internal: Unable to initialize shared memory key 'triton_python_backend_shm_region_2' to requested size (67108864 bytes). If you are running Triton inside docker, use '--shm-size' flag to control the shared memory region size. Each Python backend model instance requires at least 64MBs of shared memory. Error: No such file or directory
here is the one test log:
[L0_infer_python_test_log.txt](https://github.com/triton-inference-server/server/files/8478185/L0_infer_python_test_log.txt)

**Comment by dyastremsky** [comment]
Hi @yaoyunda. Those three tests mentioned in [the test document](https://github.com/triton-inference-server/server/blob/main/docs/test.md) are meant to be a sanity check. They won't be comprehensive, so if there's other functionality that is key for you, it could be worth testing. You could look at our current tests for inspiration, but as you mentioned, not all of the models are publicly available and some tweaking may be necessary for your functionality.

If you look at the Python backend config in the command line, it is initialized with a default number of bytes for shared memory. If you don't have that much available, that is the likely source of the error. What's the shared memory region size inside your Docker container?

**Comment by tanmayv25** [comment]
@yaoyunda  See here for the details: https://github.com/triton-inference-server/python_backend#managing-shared-memory

**Comment by yaoyunda** [comment]
@tanmayv25 , 
Thanks for explain.
For the python backend test, the main error from the attached log is missing 40 files listed below, how to generate or get them?

python_float16_float32_float32
python_float32_float32_float32
python_float32_int32_int32
python_int16_int16_int16
python_int32_float16_int16
python_int32_float32_float32
python_int32_int32_int32
python_int32_int32_object
python_int32_int8_int16
python_int32_int8_int8
python_int32_object_int32
python_int32_object_object
python_int64_int64_int64
python_int8_int32_int32
python_int8_int8_int8
python_nobatch_float16_float16_float16
python_nobatch_float16_float32_float32
python_nobatch_float32_float32_float32
python_nobatch_float32_int32_int32
python_nobatch_int16_int16_int16
python_nobatch_int32_float16_int16
python_nobatch_int32_float32_float32
python_nobatch_int32_int32_int32
python_nobatch_int32_int32_object
python_nobatch_int32_int8_int16
python_nobatch_int32_int8_int8
python_nobatch_int32_object_int32
python_nobatch_int32_object_object
python_nobatch_int64_int64_int64
python_nobatch_int8_int32_int32
python_nobatch_int8_int8_int8
python_nobatch_object_int32_int32
python_nobatch_object_int32_object
python_nobatch_object_object_int32
python_nobatch_object_object_object
python_object_int32_int32
python_object_int32_object
python_object_object_int32
python_object_object_object

**Comment by yaoyunda** [comment]
@tanmayv25 , I figured out how to run python sanity check for L0_infer, need to use docker run with --shm-size=4g --ulimit memlock=-1, 1g is not enough. please ignore my previous comment for model file generation.

**Comment by tanmayv25** [comment]
Just adding it here anyways. The test script should generate the python models on its own. 
https://github.com/triton-inference-server/server/blob/main/qa/L0_infer/test.sh#L153-L211

**Comment by yaoyunda** [comment]
For 2 other sanity tests , to run "BACKENDS="python" ENSEMBLES=0 EXPECTED_NUM_TESTS=37 bash -x ./test.sh" for Python backend is still not working. unable to figure out why: here are the logs.
[L0_batcher_python_test_log.txt](https://github.com/triton-inference-server/server/files/8498757/L0_batcher_python_test_log.txt)
[L0_sequence_batcher_python_test_log.txt](https://github.com/triton-inference-server/server/files/8498758/L0_sequence_batcher_python_test_log.txt)

**Comment by tanmayv25** [comment]
L0_batcher and L0_sequence_batcher doesn't include the support for python backend. 
https://github.com/triton-inference-server/server/blob/main/qa/L0_batcher/test.sh#L102
https://github.com/triton-inference-server/server/blob/main/qa/L0_sequence_batcher/sequence_batcher_test.py#L55

Most likely we don't generate these models. @Tabrizian  Do you know why we don't include python backend in these tests?

@yaoyunda You might be interested in python backend specific tests here: https://github.com/triton-inference-server/server/tree/main/qa/L0_backend_python

**Comment by Tabrizian** [comment]
@tanmayv25 It has not been prioritized yet. There is a ticket for it in the backlog.

**Comment by tanmayv25** [comment]
@yaoyunda I don't see any new issues being posted by you for past few weeks. Does that mean you were able to get minimum CI test coverage for your use case?

**Comment by yaoyunda** [comment]
@tanmayv25 , thanks for keeping on this subject, I would like to know what are needed from existing L0_xxx tests for a health tritonserver build with only onnx backend. could you provide me a initial subset?

**Comment by tanmayv25** [comment]
A quick search of onnx in the qa directory would show what all tests are supported by the backend. Some of the important tests that you must run are:

- L0_batch_input
- L0_batcher - along with shared memory and cuda shared memory versions.
- L0_compute_capabiltiy
- L0_custom_ops
- L0_dyna_implicit_state
- L0_dyna_sequence_batcher
- L0_implicit_state
- L0_inffer
- L0_inffer_reshape
- L0_inffer_variable
- L0_large_payload
- L0_lifecycle
- L0_model_config
- L0_multi_server
- L0_output_name
- L0_sequence_batcher
- L0_server_status
- L0_warmup

These tests should provide you more than sufficient coverage.

**Comment by tanmayv25** [comment]
I am going to close the issue as the original ask looks like to be answered. Please open new issues if you have any other problems/questions.
