### ISSUE TITLE
Will you submit the min-image for history triton?

### ISSUE THREAD

**Issue by lhy2749** [triton-inference-server/server#4184]
**Is your feature request related to a problem? Please describe.**
On our server, the nvidia-driver version is 450, and we can't upgrade it yet. It means we can only use triton-20.09, but it seems I can‘t use compose.py to build images becase of `nvcr.io/nvidia/tritonserver:20.09-py3-min not found`. Is there any way I can solve this problem?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tanmayv25** [comment]
20.09 is a very old release. Our build process was different back then. See this for build instruction for the release: https://github.com/triton-inference-server/server/blob/r20.09/docs/build.rst

You might still be able to use newer version of triton using [cuda-compat.](https://docs.nvidia.com/deploy/cuda-compatibility/index.html#forward-compatibility-title).

**Comment by lhy2749** [comment]
> 20.09 is a very old release. Our build process was different back then. See this for build instruction for the release: https://github.com/triton-inference-server/server/blob/r20.09/docs/build.rst
> 
> You might still be able to use newer version of triton using [cuda-compat.](https://docs.nvidia.com/deploy/cuda-compatibility/index.html#forward-compatibility-title).

Thank you for your advice. But I found a new problem, My operation is as follows:
run `docker run --gpus '"device=2"' -it --name triton-update -v ***:/models nvcr.io/nvidia/tritonserver:21.09-py3 bash`(drive version 450.80.02, RTX2080Ti), the error exception follows:

ERROR: This container was built for NVIDIA Driver Release 470.57 or later, but
       version 450.80.02 was detected and compatibility mode is UNAVAILABLE.

       [[Forward compatibility was attempted on non supported HW (CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE) cuInit()=804]]


Then use `apt-get install -y cuda-compat-11-5`, and
"""
LD_LIBRARY_PATH=/usr/local/cuda/compat/lib.real:$LD_LIBRARY_PATH tritonserver --model-repository /models/
"""
got:
W0413 02:17:07.419788 473 metrics.cc:274] Cannot get CUDA device count, GPU metrics will not be available
I0413 02:17:07.712304 473 libtorch.cc:1030] TRITONBACKEND_Initialize: pytorch
I0413 02:17:07.712369 473 libtorch.cc:1040] Triton TRITONBACKEND API version: 1.5
I0413 02:17:07.712384 473 libtorch.cc:1046] 'pytorch' TRITONBACKEND API version: 1.5
2022-04-13 02:17:07.876601: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
I0413 02:17:07.923359 473 tensorflow.cc:2170] TRITONBACKEND_Initialize: tensorflow
I0413 02:17:07.923454 473 tensorflow.cc:2180] Triton TRITONBACKEND API version: 1.5
I0413 02:17:07.923526 473 tensorflow.cc:2186] 'tensorflow' TRITONBACKEND API version: 1.5
I0413 02:17:07.923603 473 tensorflow.cc:2210] backend configuration:
{}
I0413 02:17:07.926568 473 onnxruntime.cc:1997] TRITONBACKEND_Initialize: onnxruntime
I0413 02:17:07.926599 473 onnxruntime.cc:2007] Triton TRITONBACKEND API version: 1.5
I0413 02:17:07.926613 473 onnxruntime.cc:2013] 'onnxruntime' TRITONBACKEND API version: 1.5
I0413 02:17:07.950440 473 openvino.cc:1193] TRITONBACKEND_Initialize: openvino
I0413 02:17:07.950485 473 openvino.cc:1203] Triton TRITONBACKEND API version: 1.5
I0413 02:17:07.950498 473 openvino.cc:1209] 'openvino' TRITONBACKEND API version: 1.5
W0413 02:17:07.950528 473 pinned_memory_manager.cc:236] Unable to allocate pinned system memory, pinned memory pool will not be available: forward compatibility was attempted on non supported HW
E0413 02:17:07.950600 473 server.cc:197] Failed to initialize CUDA memory manager: unable to get number of CUDA devices: forward compatibility was attempted on non supported HW
W0413 02:17:07.950615 473 server.cc:204] failed to enable peer access for some device pairs
E0413 02:17:07.951795 473 model_repository_manager.cc:1890] Poll failed for model directory 'simbert': unable to get number of CUDA devices: forward compatibility was attempted on non supported HW
I0413 02:17:07.951885 473 server.cc:519]


Could you please tell me what should i do?

**Comment by lhy2749** [comment]
I found it.

Release 21.09 is based on [NVIDIA CUDA 11.4.2](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html), which requires [NVIDIA Driver](http://www.nvidia.com/Download/index.aspx?lang=en-us) release 470 or later. However, if you are running on Data Center GPUs (formerly Tesla), for example, T4, you may use NVIDIA driver release 418.40 (or later R418), 440.[3](https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html#fnsrc_3)3 (or later R440), 450.51 (or later R450), or 460.27 (or later R460).
The CUDA driver's compatibility package only supports particular drivers. 3

It seems My device not be supported.
