### ISSUE TITLE
model config is unavaible to client if model is not loaded by the server

### ISSUE THREAD

**Issue by QMassoz** [triton-inference-server/server#4187]
**Description**
The following code
```
with httpclient.InferenceServerClient("localhost:8000") as client:
    model_config = client.get_model_config('my_model')
``` 
fails and throws 
```
tritonclient.utils.InferenceServerException: Request for unknown model: 'my_model' is not found
``` 
when triton inference server is launched with ```--model-control-mode explicit``` and 'my_model' is not loaded by the server (it does exist in model repository). Only after 'my_model' is loaded using ```client.load_model('my_model')``` that the model configuration becomes available.

**Triton Information**
Triton version: 22.03
Docker: nvcr.io/nvidia/tritonserver:22.03-pyt-python-py3
Model backend: python

**To Reproduce**
- Download [get_model_config_bug.tar.gz](https://github.com/triton-inference-server/server/files/8450695/get_model_config_bug.tar.gz)
- Run triton server via ```./run_server.sh```
- Run client via ```pipenv run python test_client.py```

The model is a simple add_sub model using the python backend. The line of interest is 44 in test_client.py.

**Expected behavior**
The triton server should be able to provide to the client the model configuration even if this model is not loaded.

Workarounds exist but are not ideal:
(1) ```client.load_model('my_model')``` to load the model with the configuration file in the model_repository given to the server (which may spin an instance on all GPUs when we may want to load only on one GPU) or 
(2) load and parse ourselves the configuration file in the model_repository accessible to the client (which may be a copy of the one given to the server in some setup), but json.loads is not enough to parse config.pbtxt as this is not json standard (and we do not have autofill functionality).

**Comment by GuanLuo** [comment]
Triton doesn't provide the config (model metadata) unless the model is loaded and ready for inference.
