### ISSUE TITLE
[request] Able to dynamically load ensembles without polling for model dependencies

### ISSUE THREAD

**Issue by darintay** [triton-inference-server/server#4193]
**Is your feature request related to a problem? Please describe.**
The process for dynamically loading an ensemble is cumbersome, and different from all(?) other model types.
You currently have to:
- Invoke ModelLoad for each model used by the ensemble
- Poll the server until it reports each one is ready
- Invoke ModelLoad for the ensemble model

For other model types the inferencer doesn't need to know what kind of model it is using, you can just load it and start inferencing. I could transparently replace a TF model with an ONNX equivalent and the callers wouldn't need to change; I cannot transparently replace it with an ensemble because of the loading differences.

**Describe the solution you'd like**
I'd like to see ModelLoad implicitly load the models in the ensemble if they're not yet loaded, instead of error'ing.

**Describe alternatives you've considered**
I'd also be happy if ModelLoad allowed an ensemble whose models aren't yet in the ready state, and the model only reports 'ready' when its submodels are also 'ready'.

While it doesn't quite fix the substitutability problem, it's a fair bit closer and gets rid of the need to poll-wait in middle of the load process.

I assume there is already some existing code that does something like this during startup if you aren't doing dynamic loading, since it seems to handle the ordering dependencies implicitly just fine.

**Comment by tanmayv25** [comment]
> I'd like to see ModelLoad implicitly load the models in the ensemble if they're not yet loaded, instead of error'ing.

It should be able to load all the composing model of an ensemble. We even have a test case for it: https://github.com/triton-inference-server/server/blob/main/qa/L0_lifecycle/lifecycle_test.py#L1567-L1578

just loading the ensemble model loads the composing models. Can you describe your setup and what error you are seeing?

**Comment by darintay** [comment]
Must have a been a bug on my end, and jumped to the conclusion that it wasn't supported.

Trying again now with a simple test case and it seems to pretty clearly work.  That's great to see!

My bad and thanks for the quick response!
