### ISSUE TITLE
UNAVAILABLE: Invalid argument: model 'keypoints_pose_0', tensor 'input.1': the model expects 4 dimensions (shape [1,3,224,224]) but the model configuration specifies 4 dimensions (shape [1,3,224,244])

### ISSUE THREAD

**Issue by sperezs95** [triton-inference-server/server#4194]
**Description**
I'm trying to serve the NVIDIA human pose estimation model described here: https://github.com/NVIDIA-AI-IOT/trt_pose, specifically I'm using the ONNX conversion of the model shown in this other link: https:/ /github.com/NVIDIA-AI-IOT/deepstream_pose_estimation

I have downloaded the "pose_estimation.onnx" file, placed it in my newt models directory and wrote the following config file:

platform: "onnxruntime_onnx"
max_batch_size : 0
input [
  {
    name: "input.1"
    data_type: TYPE_FP32
    dims: [ 1, 3, 224, 244 ]
  }
]

output [
  {
    name: "heatmap"
    data_type: TYPE_FP32
    dims: [ 1, 18, 56, 56 ]
  },
    {
    name: "part_affinity_fields"
    data_type: TYPE_FP32
    dims: [ 1, 42, 56, 56 ]
  }
]

instance_group {
  count: 1
  gpus: 0
  kind: KIND_GPU
}

My directory looks like this:

![image](https://user-images.githubusercontent.com/75050569/162546084-d169fb05-2958-4d92-9c6d-090e130b5727.png)

When starting tritonserver the following error message is thrown:

![image](https://user-images.githubusercontent.com/75050569/162546118-4e16fd1d-29f5-4b92-9fe3-43ffcfda8e1f.png)

**Triton Information**
I'm running triton inside the container "nvcr.io/nvidia/deepstream-l4t:6.0-triton" in conjunction with the triton file for jetpack 4.6:

![image](https://user-images.githubusercontent.com/75050569/162546163-7ff6fd78-36fa-4e82-8b71-6a174df524d7.png)
![image](https://user-images.githubusercontent.com/75050569/162546390-6295b48f-6af9-4af0-9e0d-660f6da0a8c9.png)

**To Reproduce**
I simply unzipped the supplied file inside the container and run:

TRITON_SERVER_DIR=/triton-server
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$TRITON_SERVER_DIR/lib
export PATH=$PATH:$TRITON_SERVER_DIR/bin
tritonserver --model-repository=/models --backend-directory=/triton-server/backends

These are the characteristics of my jetson nano:

![image](https://user-images.githubusercontent.com/75050569/162546523-8a1ccdea-e358-4dad-83f3-b69b6c8de56d.png)

**Expected behavior**
I would like to know why this conflict exists with the tensor input form and what I can do to solve it.
Thank you very much and I look forward to any help you can give me...

**Comment by tanmayv25** [comment]
The error message is self-explanatory. Your model expects `input.1` with shape `[1, 3, 224, 224 ]` but your mode config describes the shape for the tensor as: `[1, 3, 224, 244]`

> what I can do to solve it.

Just use the following config:

```
platform: "onnxruntime_onnx"
max_batch_size : 0
input [
{
name: "input.1"
data_type: TYPE_FP32
dims: [ 1, 3, 224, 224 ]
}
]

output [
{
name: "heatmap"
data_type: TYPE_FP32
dims: [ 1, 18, 56, 56 ]
},
{
name: "part_affinity_fields"
data_type: TYPE_FP32
dims: [ 1, 42, 56, 56 ]
}
]

instance_group {
count: 1
gpus: 0
kind: KIND_GPU
}
```

You can also use auto-complete config feature described here: https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#auto-generated-model-configuration

**Comment by sperezs95** [comment]
> The error message is self-explanatory. Your model expects `input.1` with shape `[1, 3, 224, 224 ]` but your mode config describes the shape for the tensor as: `[1, 3, 224, 244]`
> 
> > what I can do to solve it.
> > You can use the following config:
> 
> ```
> platform: "onnxruntime_onnx"
> max_batch_size : 0
> input [
> {
> name: "input.1"
> data_type: TYPE_FP32
> dims: [ 1, 3, 224, 224 ]
> }
> ]
> 
> output [
> {
> name: "heatmap"
> data_type: TYPE_FP32
> dims: [ 1, 18, 56, 56 ]
> },
> {
> name: "part_affinity_fields"
> data_type: TYPE_FP32
> dims: [ 1, 42, 56, 56 ]
> }
> ]
> 
> instance_group {
> count: 1
> gpus: 0
> kind: KIND_GPU
> }
> ```
> 
> You can also use auto-complete config feature described here: https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#auto-generated-model-configuration

Thank you for your answer, it seems that my whole problem was a typing error, thank you very much for your time and help.

I'm going to try the auto-complete feature.
