### ISSUE TITLE
tritonserver ensemble SEGV in nvidia::inferenceserver::RateLimiter::EnqueuePayload 

### ISSUE THREAD

**Issue by dfisk** [triton-inference-server/server#4199]
Greetings, 

This issue is wrt.

NVIDIA Release 22.03 (build 33743047)
Triton Server Version 2.20.0

I have developed an ensemble example from scratch that combines XGBoost(1), Tensorflow(1), and Scikit-Learn(2) framework models, along with multiplexer(1) and combiner(1) python models using the tensorflow2, fil and python backends.
 
The server initializes properly inference to each of the (6) models succeed. However, the ensemble model that uses all 6 of these models exposes a SEGV in the server:
 
```
I0409 20:15:58.652373 1141 rate_limiter.cc:135] Should not print this
--Type <RET> for more, q to quit, c to continue without paging--

Thread 93 "tritonserver" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f9564ffd000 (LWP 1303)]
__GI___pthread_mutex_lock (mutex=0x38) at ../nptl/pthread_mutex_lock.c:67
67      ../nptl/pthread_mutex_lock.c: No such file or directory.

(gdb) bt
#0  __GI___pthread_mutex_lock (mutex=0x38) at ../nptl/pthread_mutex_lock.c:67
#1  0x00007f975a4ce900 in nvidia::inferenceserver::RateLimiter::EnqueuePayload(nvidia::inferenceserver::TritonModel const*, std::shared_ptr<nvidia::inferenceserver::Payload>) () from /opt/tritonserver/bin/../lib/libtritonserver.so
#2  0x00007f975a3cc0ab in nvidia::inferenceserver::DynamicBatchScheduler::Enqueue(std::unique_ptr<nvidia::inferenceserver::InferenceRequest, std::default_delete<nvidia::inferenceserver::InferenceRequest> >&) () from /opt/tritonserver/bin/../lib/libtritonserver.so
#3  0x00007f975a416001 in nvidia::inferenceserver::InferenceRequest::Run(std::unique_ptr<nvidia::inferenceserver::InferenceRequest, std::default_delete<nvidia::inferenceserver::InferenceRequest> >&) () from /opt/tritonserver/bin/../lib/libtritonserver.so
#4  0x00007f975a4bb2d8 in nvidia::inferenceserver::InferenceServer::InferAsync(std::unique_ptr<nvidia::inferenceserver::InferenceRequest, std::default_delete<nvidia::inferenceserver::InferenceRequest> >&) () from /opt/tritonserver/bin/../lib/libtritonserver.so
#5  0x00007f975a4e31bd in TRITONSERVER_ServerInferAsync () from /opt/tritonserver/bin/../lib/libtritonserver.so
#6  0x0000562c5cf32644 in nvidia::inferenceserver::HTTPAPIServer::HandleInfer(evhtp_request*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#7  0x0000562c5cf33185 in nvidia::inferenceserver::HTTPAPIServer::Handle(evhtp_request*) ()
#8  0x0000562c5d118dc5 in htp.request_parse_fini_ ()
#9  0x0000562c5d11dae6 in htparser_run ()
#10 0x0000562c5d11b9fe in htp.connection_readcb_ ()
#11 0x0000562c5d1029b0 in bufferevent_run_deferred_callbacks_locked ()
#12 0x0000562c5d10a4d0 in event_process_active_single_queue.isra ()
#13 0x0000562c5d10af1f in event_base_loop ()
#14 0x0000562c5d11f852 in _evthr_loop ()
#15 0x00007f975a2a9609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#16 0x00007f9759b17163 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

```

The model directory is available from this public GCS bucket for reproduction:
`gs://dfisk-model-test/triton-ensemble-example`

I am also attaching the client test scripts. 

To reproduce: pull the tritonserver image from [NGC 22.03](nvcr.io/nvidia/tritonserver:22.03-py3) and run the container built from the [fil_backend](https://github.com/triton-inference-server/fil_backend) with:
```
$ docker run \
  --gpus=all \
  --rm \
  -p 8000:8000 \
  -p 8001:8001 \
  -p 8002:8002 \
   --shm-size=8G \
   --ulimit memlock=-1 \
  triton_fil \
  tritonserver \
  --model-repository=gs://dfisk-model-test/triton-ensemble-example
```

After editing the attached scripts to point to your server, try each of:
`combine_01.py  mux.py  sci_1.py  sci_2.py  tf_01.py  xgb_01.py  ensemble_01.py`
[triton-ensemble-example-test-scripts.zip](https://github.com/triton-inference-server/server/files/8459884/triton-ensemble-example-test-scripts.zip)

In my testing all but ensemble work correct with the subject SEGV exposed by ensemble_01.py

I am in the process of building a debug tritonserver with this version to possibly assist with the fix. I am also looking at adding some rate limiter configuration to ensure the sub-system is initialized; I am otherwise not using the rate limiter in this configuration but the crash appears to be in that sub-system. 

Thanks for your assistance!

**Comment by CoderHam** [comment]
@dfisk thanks for the repro. Marking this as a bug.

**Comment by dfisk** [comment]
The error was 'backend: "python" ' in the ensemble config.pbtxt; this was not not caught by the server startup validation checks, is an error in configuration, and resulted in the SEGV.  Thanks!
