### ISSUE TITLE
python backend:  BLS triton_python_backend_utils support url arguments

### ISSUE THREAD

**Issue by zhaohb** [triton-inference-server/server#4201]
From the documentation I see that I can use python Backend BLS mode in this way：
```shell
import triton_python_backend_utils as pb_utils


class TritonPythonModel:
  ...
    def execute(self, requests):
      ...
      # Create an InferenceRequest object. `model_name`,
      # `requested_output_names`, and `inputs` are the required arguments and
      # must be provided when constructing an InferenceRequest object. Make sure
      # to replace `inputs` argument with a list of `pb_utils.Tensor` objects.
      inference_request = pb_utils.InferenceRequest(
          model_name='model_name',
          requested_output_names=['REQUESTED_OUTPUT_1', 'REQUESTED_OUTPUT_2'],
          inputs=[<pb_utils.Tensor object>])

      # `pb_utils.InferenceRequest` supports request_id, correlation_id, and model
      # version in addition to the arguments described above. These arguments
      # are optional. An example containing all the arguments:
      # inference_request = pb_utils.InferenceRequest(model_name='model_name',
      #   requested_output_names=['REQUESTED_OUTPUT_1', 'REQUESTED_OUTPUT_2'],
      #   inputs=[<list of pb_utils.Tensor objects>],
      #   request_id="1", correlation_id=4, model_version=1, flags=0)
     ......
```

As you can see, pb_utils does not support url parameters, so the BLS can only access other models that exist locally, not models that reside on other servers. How can we resolve this situation?

thank you very much.

**Comment by Tabrizian** [comment]
Correct. BLS can only be used with models that are loaded in the current instance of Tritonserver. If you want to execute requests on a remote Triton instance, you can install the `tritonclient` and send requests to remote triton servers using the Python client.

**Comment by zhaohb** [comment]
@Tabrizian do we have plan to support this feature？

**Comment by zhaohb** [comment]
@Tabrizian Thank you very much, I am already using tritonclient, but I am not sure how this is different from doing preprocessing in flask, what are the advantages of Python Backend？
