### ISSUE TITLE
Batching by any axis

### ISSUE THREAD

**Issue by greenberd09** [triton-inference-server/server#4203]
**Is your feature request related to a problem? Please describe.**
I am using optimized gpt-2 in onnx format from [this](https://github.com/microsoft/onnxruntime/tree/master/onnxruntime/python/tools/transformers)
There is a problem with batching here, as some model inputs collect a batch along the 2nd dimension.
This has to do with previously computed keys and values ​​that can be used to prevent those values ​​from being recalculated([describe](https://huggingface.co/docs/transformers/model_doc/gpt2#:~:text=The%20model%20can,on%20its%20usage)).
The model from hugginface returns separated keys and values ​​as output, which increases the number of values, in this case output shape: 
**[-1(batch), num_attention_heads(constant), -1, head_size(constant)]**
Optimized onnx model collects the keys and values ​​into one tensor so that the input and result are one value of the form
**[2, -1(batch), num_attention_heads(constant), -1, head_size(constant)]**, where first dim is keys, second is values
This creates great convenience when working with the model.

**Describe the solution you'd like**
The server has already implemented convenient functionality for [ragged batching](https://github.com/triton-inference-server/server/blob/main/docs/ragged_batching.md), it will be convenient, along with the activation of receiving a ragged batching, also to set the axis for batching in input and output parameters configuration of models. For example, "axis_batching = 0, 1, ..."

**Describe alternatives you've considered**
Unfortunately, I didn't find any alternative solutions for such shape input and output model.

**Additional context**
N/A

**Comment by CoderHam** [comment]
Triton does support or have plans to support batching from an arbitrary axis. But we will make a note of your request and prioritize this request accordingly

**Comment by greenberd09** [comment]
@CoderHam 
Indeed, triton provides [tools](https://github.com/triton-inference-server/server/blob/main/docs/ragged_batching.md) for adapting batching to non-standard inputs. But as I understand it only works with input, this doesnt change batching behavior for output, does it?
It would be cool to know if there is an alternative server-side solution, as I may not understand correctly how batching works.
Also thanks for the feedback. I would really like to have a way to use batching for input and output on an arbitrary axis.

**Comment by CoderHam** [comment]
@GuanLuo can you clarify the same? In my understanding Ragged batching is not the same as Batching by any axis.

**Comment by GuanLuo** [comment]
> Ragged batching is not the same as Batching by any axis.

That is correct, ragged batching is a way to allow batching inputs that have different shape (i.e. batching inputs of shape [1, 4] and shape [1, 2]), however it still rely on the fact that batch dimension is the outer most dimension so that the data of each input is compact. Batching by any axis is a different and harder problem to solve as the data of inputs will be interleaving in the batched form.

**Comment by CoderHam** [comment]
@greenberd09 I have marked this as an enhancement for now but we have not prioritized this and there is no timeline/commitment on the support.

**Comment by greenberd09** [comment]
@CoderHam @GuanLuo thanks, i got all answers i need
than i'll close this issue
