### ISSUE TITLE
Can Triton improve QPS by increasing CPU utilization?

### ISSUE THREAD

**Issue by lhy2749** [triton-inference-server/server#4206]
**Is your feature request related to a problem? Please describe.**

I know Triton can use `instance_group` in `config.pbtxt` loads multiple identical models. But I found that this only changes the memory utilization, while the CPU utilization is the same (observed by `docker stats`). Are there any commands or parameters that enable Triton to increase CPU utilization?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by CoderHam** [comment]
@lhy2749 can you try to use the numa optimzation? https://github.com/triton-inference-server/server/blob/main/docs/optimization.md#numa-optimization

It is possible that the CPU utilization of specific cores are 100 but not all cores are being used.

**Comment by lhy2749** [comment]
@BenoitWang 你好，我并没有尝试numa优化。我发现triton的CPU使用率浮动在一个区间，上下限并不大还是可以接受
