### ISSUE TITLE
[FEATURE REQUEST] Support types supported by TensorRT

### ISSUE THREAD

**Issue by hyperfraise** [triton-inference-server/server#4220]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when I see that my TensorRT model can take as inputs FP16 or INT8, but not when I put it in a Triton inference server.

**Describe the solution you'd like**
We should be able to specify `TYPE_FP16` or `TYPE_INT8` in the `config.pbtxt` file when using "tensorr_plan" backend.

**Describe alternatives you've considered**
The alternative is converting eveyrthing to fp32, but this is very costly, and thus greatly reduces the benefit of using Triton in the first place. If I just use TensorRT, I can already use fp16 or int8 without any conversion. Triton should propose the same thing, I think.

**Comment by dyastremsky** [comment]
You can use FP16 and INT8. See supported datatypes here: https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md

**Comment by dyastremsky** [comment]
Closing because this feature exists. If you have further questions related to this ticket, feel free to reopen.

**Comment by hyperfraise** [comment]
@dyastremsky I think there is a misunderstanding. in face `TYPE_FP16` and `TYPE_INT8` are not supported datatypes when using "tensorr_plan" backend. Would you please reopen this ?

**Comment by hyperfraise** [comment]
I'll provide a code snippet to illustrate what I mean.

**Comment by hyperfraise** [comment]
Hey. I got confused by [another issue](https://github.com/triton-inference-server/server/issues/2377) in which I understood that we should always specify TYPE_FP32 when using "tesnorrt_plan" no matter what the type of the model input is, but you're right. Thanks.
