### ISSUE TITLE
Serverside Postprocessing

### ISSUE THREAD

**Issue by Naegionn** [triton-inference-server/server#4221]
Hey,
I want to use triton in a way where it should serve multiple different models. For example object detection and segmentation models.
The client should not have to worry about postprocessing for each model but instead there would be some python function registered with the model (onnx) to be called as a server side postprocessing step. This would for example convert the segementation output  and the bounding boxes into polygons which would be then past on to the client. So the client does only need a functionality to handle polygons instead of having to account for all of the different models and outputs.

Is something like this possible without having to fall back to the python backend completely?

Thanks

**Comment by dyastremsky** [comment]
You can use [ensemble models](https://github.com/triton-inference-server/server/blob/main/docs/architecture.md#ensemble-models) or the Python backend's [Business Logic Scripting](https://github.com/triton-inference-server/python_backend#business-logic-scripting). Those are often used for pre- and post-processing of models.
