### ISSUE TITLE
[Question]The performance of triton-server itself

### ISSUE THREAD

**Issue by zbh0323** [triton-inference-server/server#4225]
Excuse me, have you evaluated the cpu and memory resources occupied by triton-server itself? Is there any official data to corroborate it?

**Comment by CoderHam** [comment]
@zbh0323 are you referring to the CPU and memory resources taken by triton when no models are loaded / running or when there are inferences being run and models / respective frameworks have been loaded by Triton?

**Comment by zbh0323** [comment]
> @zbh0323 are you referring to the CPU and memory resources taken by triton when no models are loaded / running or when there are inferences being run and models / respective frameworks have been loaded by Triton?

Yes, I want to know the resources occupied by triton-server itself whether there is a model running or not

**Comment by zbh0323** [comment]
I want to use this to judge whether I should arrange multiple models together and run them in a triton server, or deploy multiple triton servers, each of which corresponds to a model service.> @zbh0323 are you referring to the CPU and memory resources taken by triton when no models are loaded / running or when there are inferences being run and models / respective frameworks have been loaded by Triton?

**Comment by zbh0323** [comment]
> @zbh0323 are you referring to the CPU and memory resources taken by triton when no models are loaded / running or when there are inferences being run and models / respective frameworks have been loaded by Triton?

I want to use this to judge whether I should arrange multiple models together and run them in a triton server, or deploy multiple triton servers, each of which corresponds to a model service.

**Comment by dyastremsky** [comment]
To do so, you can run Triton with an empty model folder. Use nvidia-smi or top, depending which performance metrics you'd like to get.

**Comment by zbh0323** [comment]
> 
I tried what you said and got the following result。
<img width="548" alt="image" src="https://user-images.githubusercontent.com/41530068/171116865-73bff24f-094c-460c-8801-f0c8bf882423.png">

**Comment by dyastremsky** [comment]
Thank you for trying it and sharing the memory usage results. I'll close this ticket. Please reopen it if you would like to follow up on anything.
