### ISSUE TITLE
Test L0_backend_python is coupled with AWS S3

### ISSUE THREAD

**Issue by yaoyunda** [triton-inference-server/server#4231]
**Description**
Need to build and tritonserver and  run the test L0_backend_python in Azure GPU VM
The test is going to fail with error:

aws: error: the following arguments are required: value
+ BUCKET_URL=s3://triton-bucket-
+ aws s3 rm s3://triton-bucket- --recursive --include '*'
fatal error: Unable to locate credentials
+ true
+ aws s3 mb s3://triton-bucket-
make_bucket failed: s3://triton-bucket- Unable to locate credentials

**Triton Information**
What version of Triton are you using?
r22.03

Are you using the Triton container or did you build it yourself?
build by myself

**To Reproduce**
Steps to reproduce the behavior.
Followed the build and test doc to build server , test sdk and qa images, then start the qa container;
run the test as:
PYTHON_BACKEND_REPO_TAG=r22.03 DTRITON_BACKEND_REPO_TAG=r22.03 TRITON_BACKEND_REPO_TAG=r22.03 TRITON_COMMON_REPO_TAG=r22.03 TRITON_CORE_REPO_TAG=r22.03 bash -x ./test.sh > output_log.txt
the test log is attached below.
[output_log.txt](https://github.com/triton-inference-server/server/files/8499279/output_log.txt)

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**
This test could be passed without using any execution environment or provide option with Azure.
Ideally, a dummy execution environment without credential check.

**Comment by yaoyunda** [comment]
build tritonserver using optional features:
./build.py --cmake-dir=./build
-build-dir=/mnt/citritonbuild
--enable-logging
--enable-stats
--enable-tracing
--enable-metrics
--enable-gpu-metrics
--enable-gpu
--filesystem=azure_storage
--endpoint=http
--endpoint=grpc
--repo-tag=common:r22.03
--repo-tag=core:r22.03
--repo-tag=backend:r22.03
--repo-tag=thirdparty:r22.03
--backend=ensemble
--backend=identity:r22.03
--backend=repeat:r22.03
--backend=square:r22.03
--backend=onnxruntime:r22.03
--backend=python:r22.03
--repoagent=checksum:r22.03

**Comment by CoderHam** [comment]
@yaoyunda you can disable the env test if you have build without S3 cloud storage support. This would be as simple as commenting this section under the test.sh script

```
  (cd env && bash -ex test.sh)
  if [ $? -ne 0 ]; then
    RET=1
  fi
```
