### ISSUE TITLE
Clean and Concise documentation

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [triton-inference-server/server#4245]
Dear all,

Thanks for Triton. This is more like a "call for action". Without clean and concise documentation, using Triton in the right way is very hard if not impossible.

Currently, the doc seems to have been very overlooked. I cannot see detailed and explained examples, you have to jump around multiple reports to understand how to (maybe) implement what you are looking for. 

For example, I've been reading for two hours now, how can I serve my model in PyTorch? Is there an up to date doc piece showing me **all** the steps to get things done? Configuration examples for common usages? Examples for different tasks with best practices? How the hell do I send stuff to the model? 

Thanks!

Cheers,

Francesco

**Comment by dyastremsky** [comment]
Hi Francesco, have you used the [quick start guide](https://github.com/triton-inference-server/server/blob/main/docs/quickstart.md) yet? That's a good place to start from for a vanilla model. You can adapt it using the links in our main README to your specific use case. If you want more concrete code, you can also look in our `qa` folder for specific examples associated with the backends/feature you're writing for even more specific usage (with specific configs, code to send/receive data, etc.). For example, for PyTorch models using shared weights, [this test](https://github.com/triton-inference-server/server/tree/main/qa/L0_libtorch_shared_weights).

Triton supports a massive number of use cases, across deep learning frameworks, features, and architectures. Documenting an exact full walkthrough for each one seems untenable. Luckily, our users do often post walkthroughs online for specific use cases, so that may be worth searching as well. I'll tag @dzier for awareness, but keep in mind that we put a lot of time into documentation and work with users to get their feedback on it, so a general "call to action" to document better doesn't really go beyond what we work to do everyday for our open-source project.

**Comment by FrancescoSaverioZuppichini** [comment]
Hi @dyastremsky, thanks for your reply. I hope you realize your answer proves my point. Of course, I've read them and they are just very quick raw examples that are not really useful if you want to go beyond copy & paste your examples. If you believe that the documentation is up to good open-source standards, then feel free to close the issue. 

Try to put yourself in the shoes of somebody who wants to learn how to use your software, the documentation doesn't help a lot here. I am happy to help you with end-end examples, but you first have to recognize the issue and help me (and everybody) out :)

Thanks!

**Comment by dyastremsky** [comment]
I've filed this issue in our documentation to investigate further. Right now, my understanding is that you want an end-to-end example of how to deploy Triton to serve a PyTorch model that isn't as end-to-end as the NVIDIA [end-to-end deep learning examples linked in the README](https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/LanguageModeling), only covering the Triton steps. But not as simple as our quick start guide.

If you want something else, please feel free to clarify.

Note that assuming you're using the default backends like most users (recommended), the framework you use doesn't matter. The table of links covering configs, features, etc. in the README will apply to PyTorch as much as anything else. Any additional PyTorch-specific options would be in the [PyTorch backend repo README](https://github.com/triton-inference-server/pytorch_backend).

**Comment by FrancescoSaverioZuppichini** [comment]
More or less, IMHO (and with all due respect) the documentation is so fragmented and with missing parts that is virtually impossible to create something end to end. 

A good rule of thumb to evaluate the quality of the doc is to try to act as a new user and write down how much it takes to get the information required to build a complete product and not just download a who knows if update example. What do you think?

Thanks. 

P.S. I've had already visited all the links you have sent me, if I wasn't able to get something up and running in two hours then I believe  we can help each other and make the learning curve smoother

**Comment by dyastremsky** [comment]
Thank you for your feedback, Francesco. Closing this ticket out, as this feedback has been logged into our ongoing documentation work.

**Comment by FrancescoSaverioZuppichini** [comment]
Thank you a lot @dyastremsky

**Comment by FrancescoSaverioZuppichini** [comment]
hey @dyastremsky , I hope to do something useful for the community by raising this up again. After talking with multiple people on LinkedIn, it's clear that `triton` is not used by most people due to the terrible state of the documentation. It works only with the black-box examples.

I don't know if Nvidia really believe in open source or this is an internal tool open sourced for the PR, but `triton` it's very very (if not impossible) to use.

**Comment by dyastremsky** [comment]
Francesco, we just did a massive documentation overhaul this month on top of ongoing documentation updates (both fixes and released with every new feature). We brought in folks from other teams to restructure the main README as well. We added more end-to-end guides. We support many users from start-ups of all sorts to the largest organizations in the world. We have high schoolers tinkering with projects on Triton, PhDs using it for medical research, to organizations building on it for hundreds of millions of customers in real-time. We work very hard to provide the best to our users.

I'm sorry that you feel that Triton is impossible to develop with. I don't know what you're struggling with specifically, and you're welcome to open issues to ask questions from our developers. If you think documentation can be improved, feel free to open pull requests to improve it. An initiative to "do better" unfortunately does not give us direction to your ask. We already have plenty of people working on this and doing our best.

**Comment by jbkyang-nvi** [comment]
@FrancescoSaverioZuppichini it would maybe help if you could provide a list of questions that you struggled to answer via the documentation? Maybe a step by step of how _you're_ trying to set things up, and what _you think_ you need to configure and how the documentation lacks explanation? 
As the project develops, we have added more features and documentation with these features. It makes sense it might lack some "overall picture" you might be seeking and where you can find all the features. It think it will help if you specify, at least for your use case, the specific roadblocks for you in developing with Triton.

**Comment by FrancescoSaverioZuppichini** [comment]
<img width="497" alt="image" src="https://user-images.githubusercontent.com/15908060/201303738-4b92dfd7-4d2d-448e-8590-a99e774ff50f.png">
