### ISSUE TITLE
torchscript model don't use Dynamic Batching

### ISSUE THREAD

**Issue by kelisiya** [triton-inference-server/server#4247]
**Description**
Torchscript model don't use Dynamic Batching
**Triton Information**
What version of Triton are you using?
22.03
Are you using the Triton container or did you build it yourself?
Triton container
**To Reproduce**
Steps to reproduce the behavior.
1. torch.jit.trace('model.pt')
2. triton server load this model  and config use Dynamic Batching
3. use async client as input (1,3,h,w) or (B,3,h,w) can work, but I can't synthesize the batch correctly in the server

When I make many (1,3,H,W) requests to a client, it doesn't seem to use dynamic batch successfully. I always see Batch=1. At the same time I think it is wrong to apply for a client for every request. If it's a sample for resnet50 I'd like to see a sample that includes testing Dynamic Batching, but neither using http async nor changing config can use this mechanism

**Comment by Tabrizian** [comment]
Have you tried increasing the `max_queue_delay_microseconds` parameter described here? https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#delayed-batching

If you want to use dynamic batching you need to make sure that the `max_batch_size` field of your model configuration is larger than 1. Also, you need to turn on the dynamic batching setting of the model. You can also take a look at the test below to see how dynamic batches are created: https://github.com/triton-inference-server/server/blob/main/qa/L0_batcher/batcher_test.py#L548

**Comment by kelisiya** [comment]
> Have you tried increasing the `max_queue_delay_microseconds` parameter described here? https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#delayed-batching
> 
> If you want to use dynamic batching you need to make sure that the `max_batch_size` field of your model configuration is larger than 1. Also, you need to turn on the dynamic batching setting of the model. You can also take a look at the test below to see how dynamic batches are created: https://github.com/triton-inference-server/server/blob/main/qa/L0_batcher/batcher_test.py#L548

I will try to use batcher_test to test my model  , and I make sure use max_batch_size and turn on the dynamic batching settin

**Comment by Tabrizian** [comment]
Closing this issue.
