### ISSUE TITLE
Can Triton support TensorFlow1.10.0?

### ISSUE THREAD

**Issue by hliunim** [triton-inference-server/server#4249]
As we all know, TensorFlow1.10.0 is an earlier version. Is it not supported to convert to onnx model using tf2onnx？
![image](https://user-images.githubusercontent.com/19989312/163942934-a2c8e507-8df4-49fa-9946-9f4383f12be4.png)
So can triton support TensorFlow1.10? If yes, what is the specific implementation method？Thank you

**Comment by Tabrizian** [comment]
> As we all know, TensorFlow1.10.0 is an earlier version. Is it not supported to convert to onnx model using tf2onnx？
I think this is mainly a question for the Tensorflow and ONNX teams. 

> So can triton support TensorFlow1.10? If yes, what is the specific implementation method？

There is not any released version of Triton that uses TF 1.10 (See[ DL Framework support matrix](https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html) for the TF version used by prior Triton releases). Your best bet would be following the build instructions described here: https://github.com/triton-inference-server/tensorflow_backend#build-the-tensorflow-backend-with-custom-tensorflow
