### ISSUE TITLE
Can you tell me the meaning of overhead in perf_analyzer report

### ISSUE THREAD

**Issue by MistSun-Chen** [triton-inference-server/server#4250]
I tried to use the onnx version of resnet50 to test the impact of batch.
Here is the result
set batch = 128 and instance= 1 In GTX 1080 Ti
```bash
*** Measurement Settings ***
  Batch size: 128
  Using "time_windows" mode for stabilization
  Measurement window: 5000 msec
  Latency limit: 0 msec
  Concurrency limit: 3 concurrent requests
  Using synchronous calls for inference
  Stabilizing using average latency

Request concurrency: 1
  Client: 
    Request count: 15
    Throughput: 384 infer/sec
    Avg latency: 342044 usec (standard deviation 1536 usec)
    p50 latency: 341886 usec
    p90 latency: 344325 usec
    p95 latency: 344325 usec
    p99 latency: 344455 usec
    Avg HTTP time: 341827 usec (send/recv 94020 usec + response wait 247807 usec)
  Server: 
    Inference count: 2304
    Execution count: 18
    Successful request count: 18
    Avg request latency: 235797 usec (overhead 233900 usec + queue 57 usec + compute input 101 usec + compute infer 1739 usec + compute output 0 usec)

Request concurrency: 2
  Client: 
    Request count: 21
    Throughput: 537.6 infer/sec
    Avg latency: 471866 usec (standard deviation 297 usec)
    p50 latency: 471862 usec
    p90 latency: 472281 usec
    p95 latency: 472293 usec
    p99 latency: 472513 usec
    Avg HTTP time: 471802 usec (send/recv 93943 usec + response wait 377859 usec)
  Server: 
    Inference count: 3200
    Execution count: 25
    Successful request count: 25
    Avg request latency: 365965 usec (overhead 234055 usec + queue 130069 usec + compute input 100 usec + compute infer 1741 usec + compute output 0 usec)

Request concurrency: 3
  Client: 
    Request count: 22
    Throughput: 563.2 infer/sec
    Avg latency: 707565 usec (standard deviation 404 usec)
    p50 latency: 707511 usec
    p90 latency: 708082 usec
    p95 latency: 708131 usec
    p99 latency: 708586 usec
    Avg HTTP time: 707581 usec (send/recv 95910 usec + response wait 611671 usec)
  Server: 
    Inference count: 3200
    Execution count: 25
    Successful request count: 25
    Avg request latency: 599813 usec (overhead 234017 usec + queue 363955 usec + compute input 100 usec + compute infer 1741 usec + compute output 0 usec)

Inferences/Second vs. Client Average Batch Latency
Concurrency: 1, throughput: 384 infer/sec, latency 342044 usec
Concurrency: 2, throughput: 537.6 infer/sec, latency 471866 usec
Concurrency: 3, throughput: 563.2 infer/sec, latency 707565 usec
```
Obviously, the most time-consuming part is overhead！
Can you tell me the composition of overhead and its relationship with batch inference？

**Comment by dyastremsky** [comment]
Thanks for your question! Overhead is the time spent in the endpoint that can't be correctly captured in the send/receive time with the way the GRPC and HTTP libraries are structured. These values are quite high, but they should be independent of Triton.

You can also run perf_analyzer through CAPI to avoid the HTTP/GRPC overhead via the instructions here: https://github.com/triton-inference-server/server/blob/main/docs/perf_analyzer.md#benchmarking-triton-directly-via-c-api

**Comment by Tabrizian** [comment]
We have filed an internal ticket to improve the Perf Analyzer docs to explain `overhead`.

**Comment by MistSun-Chen** [comment]
Below are my tests using the onnx version of the resnet50 model.
In 1 gpu 1080Ti instance = 1,request concurrency = 2, batch in [2,4,8,16,32,64,128,256]

batch | overhead(ms) | queue(ms) | compute_input(ms) | compute_infer(ms) | compute_output(ms) | avg_infer_latency(ms) | throughput(req/second) | mem(MiB)
-- | -- | -- | -- | -- | -- | -- | -- | --
2 | 5.073 | 7.195 | 0.146 | 4.9 | 0.004 | 17.318 | 197.6 | 1164
4 | 10.041 | 8.667 | 0.126 | 3.209 | 0.003 | 22.046 | 299.2 | 1292
8 | 19.471 | 14.189 | 0.117 | 2.657 | 0.002 | 36.436 | 360 | 1420
16 | 33.651 | 21.283 | 0.111 | 2.127 | 0.001 | 57.173 | 444.8 | 1676
32 | 62.064 | 36.775 | 0.108 | 1.891 | 0.001 | 100.839 | 499.2 | 2188
64 | 120.132 | 65.503 | 0.101 | 1.803 | 0 | 187.539 | 524.8 | 3212
128 | 234.055 | 130.069 | 0.1 | 1.741 | 0 | 365.965 | 537.6 | 5260
256 | 494.165 | 288.481 | 0.099 | 1.837 | 0 | 784.582 | 512 | 9610

Since overhead is not included in the inference time, let's look at the remaining inference time.
The following is the result of the integration from the above table.
batch | avg_infer_latency_without_overhead(ms) | latency_(input+infer+output)(ms)
-- | -- | --
2 | 12.245 | 5.05
4 | 12.005 | 3.338
8 | 16.965 | 2.776
16 | 23.522 | 2.239
32 | 38.775 | 2
64 | 67.407 | 1.904
128 | 131.91 | 1.841
256 | 290.417 | 1.936

In my thinking, as the batch increases, the transfer time between the CPU image data and the GPU should increase, and the computation scale should also increase.
Based on this test report, I have a few questions.

* Although increasing batches will increase GPU computing efficiency, the general trend of response time per request should be an increase.However, in the perf_analyzer report, regardless of the overhead and queue_wait time, the final time of compute_infer +comput_input+comput_output decreases as the batch increases. Why?
* According to question 1, if the inference time of each request decreases, why does the queue waiting time increase instead? Logically speaking, if the network inference time decreases, the queue waiting time should be reduced.
* I noticed that the throughput unit is (req/second). In the table, when batch=256, throughput=512, does this mean that it can process 512 inference requests per second with batch=256? Can you think that 256*512 = 131,072 images of size 3 * 224*224 can be processed per second at this time? According to this calculation formula, the throughput when batch=256 should be 537.6 * 128=68,812.8. Does this mean that regardless of the video memory limit, the system throughput will always increase as the batch increases?
* Finally, I am currently learning the model deployment work, can you tell me the impact of batch on throughput and latency respectively. In the case of pursuing the highest throughput possible, how much batch should be used is more appropriate.

**Comment by dyastremsky** [comment]
Thanks for being so detailed. For your first three questions, I'm pretty sure the statistics are per request. Your times get more efficient per request because you're sending batches. Each request needs to wait longer because they're waiting to be batched, and it's possible processing a batch takes longer. Your 512 throughput is 512 requests per second (see the header).

As for your fourth question, it's model-specific, which is why the perf analyzer and model analyzer exist. It also depends on your needs. There will be a tradeoff between latency and throughput, so hopefully the numbers provided by the perf analyzer and model analyzer can help you figure out what is best for your model and use case.
