### ISSUE TITLE
openvino 2022.01 support

### ISSUE THREAD

**Issue by charlesmelby** [triton-inference-server/server#4262]

**Comment by Tabrizian** [comment]
cc @tanmayv25

**Comment by tanmayv25** [comment]
@charlesmelby ORT 1.11.0 supports openvino 2022.01. However, we are still using ORT 1.10.0 in our containers.
Even though we don't support OV 2022.01, you may still be able to build openVINO backend with OV 2022.01 using our build.py.

Read here for more information and caveats: https://github.com/triton-inference-server/server/blob/main/build.py#L50-L100

You can try something like:
```
TRITON_VERSION_MAP = {
    '2.22.0dev': (
        '22.05dev',  # triton container
        '22.03',  # upstream container
        '1.10.0',  # ORT
        '2021.4.582',  # ORT OpenVINO
        (('SPECIFIC', 'cdb9bec')),  # Standalone OpenVINO
        '2.2.9')  # DCGM version
}
```
You would have to launch the server with : `--backend-config=openvino,version=cdb9bec`. 

If you can wait, we will add official support for ORT 1.11.0 and OV 2022.01 in next few releases.

**Comment by charlesmelby** [comment]
@tanmayv25 
Thanks for the info! I'll give that a try and see how it goes.

**Comment by tanmayv25** [comment]
Closing the issue for now because there is nothing much to update.  We will move to ov2022 as soon as the ORT version we use support ov2022. In the meantime I think you can build your own ov backend with ov2022. See here for more information. 
https://github.com/triton-inference-server/server/issues/4486#issuecomment-1150262673

**Comment by charlesmelby** [comment]
@tanmayv25 
Ok. I did manage to get the build working, thanks for your help.
