### ISSUE TITLE
Load model parallelly

### ISSUE THREAD

**Issue by hexisyztem** [triton-inference-server/server#4264]
Current situation: During the initialization phase, models are loaded in parallel - `ModelInstanceState()` function, which makes initialization phase slowly and resources are not used efficiently.

Suggested solution: During the initialization phase, load models in parallel.

**Comment by Tabrizian** [comment]
Thanks for your feature request. We do have an internal ticket related to this but currently there is no plans to fix this.

cc @GuanLuo @msalehiNV

**Comment by dyastremsky** [comment]
Thanks for this request. As an update, models are now loaded in parallel. See this [pull request](https://github.com/triton-inference-server/core/pull/165) for details.
