### ISSUE TITLE
Example in Python to create a pipeline with Gst-nvinferserver

### ISSUE THREAD

**Issue by micuentadecasa** [triton-inference-server/server#4266]
**Is your feature request related to a problem? Please describe.**
The problem is that I haven't found any example of using Gst-nvinferserver in Python

**Describe the solution you'd like**
I would like to be able to add/remove pipelines in Python with GST, these pipelines can be a source RTSP that is sent for processing to the Triton Server and the output sent to a RTSP sink

**Describe alternatives you've considered**
No alternatives considered

**Additional context**
I think that a sample with this options can be really helpful for other users to create Video Analytics apps.

**Comment by rmccorm4** [comment]
Hi @micuentadecasa , 

Have you asked on the Deepstream forum: https://forums.developer.nvidia.com/c/accelerated-computing/intelligent-video-analytics/deepstream-sdk/15?

**Comment by micuentadecasa** [comment]
Hi @rmccorm4 ,

I think this is just what I was looking for, from this example I can start.

Regards.
