### ISSUE TITLE
 Abnormal gpu memory usage

### ISSUE THREAD

**Issue by zhaotyer** [triton-inference-server/server#4275]
**Description**

The same model has significantly higher gpu memory usage in the r21.06 image than in the r22.03 image

**Triton Information**
What version of Triton are you using?
r21.06
r22.03

Are you using the Triton container or did you build it yourself?
Triton container

**To Reproduce**
Steps to reproduce the behavior.

docker run -it --shm-size=5G --runtime=nvidia -v /mnt/disk2/xuyongda/DLIE/:/workspace --name test_triton -p7000:8000 -p7001:8001 -p7002:8002 nvcr.io/nvidia/tritonserver:21.06-py3 bash

tritonserver --model-repository=/workspace/fire_smoke_detection/
r21.06 image occupies gpu memory
![微信图片_1](https://user-images.githubusercontent.com/89376832/165015470-7c1651ba-7f05-46bd-8478-7af55404eb84.png)

r22.03 image occupies gpu memory
![微信图片_2](https://user-images.githubusercontent.com/89376832/165015477-138f8b9d-0536-4018-9d6b-867afed1ff00.png)

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
ensemble config.pbtxt

name: "dev_ensemble"
platform: "ensemble"

input [
  {
    name: "IMAGE_BINARY"
    data_type: TYPE_STRING
    dims: [ 1 ]
  },
  {
    name: "IMAGE_DESC"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]
output [
  {
    name: "RESULT"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]

ensemble_scheduling {
  step [
    {
      model_name: "fire_smoke_pre"
      model_version: -1
      input_map {
        key: "IMAGE"
        value: "IMAGE_BINARY"
      }
      input_map {
        key: "JSON"
        value: "IMAGE_DESC"
      }
      output_map {
        key: "IMAGE_TENSOR"
        value: "preprocessed_image"
      }
      output_map {
        key: "IMAGE_SIZE"
        value: "preprocessed_size"
      }
      output_map {
        key: "TENSOR_SIZE"
        value: "tensor_size"
      }
    },
    {
      model_name: "fire_smoke"
      model_version: -1
      input_map {
        key: "images"
        value: "preprocessed_image"
      }
      output_map {
        key: "output"
        value: "infer_result"
      }
    },
    {
      model_name: "fire_smoke_post"
      model_version: -1
      input_map {
        key: "INFER_RESULT"
        value: "infer_result"
      }
      input_map {
        key: "tensor_shape"
        value: "tensor_size"
      }
      input_map {
        key: "image_shape"
        value: "preprocessed_size"
      }
      output_map {
        key: "JSON_OUTPUT"
        value: "RESULT"
      }
    }
  ]
}

fire_smoke config.pbtxt

name: "fire_smoke"
platform: "onnxruntime_onnx"
max_batch_size:32

input [
  {
    name: "images"
    data_type: TYPE_FP32
    dims: [ 3, -1, -1]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [-1,7 ]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU
	gpus:[0]
  }
]

model_warmup [
  {
    name: "warmup"
    batch_size: 1
    inputs {
      key: "images"
      value: {                                                                      
            data_type: TYPE_FP32                                                      
            dims: [3, 384, 640]                                                  
            zero_data: true                                                           
      }
    }
  }
]

dynamic_batching {
    preferred_batch_size: [ 2,4, 6,8 ]
  }

**Expected behavior**

1.The reason for this problem in r21.06
2. What changes have been made in subsequent versions to fix this bug

**Comment by dyastremsky** [comment]
Thank you for providing detailed reproduction steps. Version 21.06 is from almost a year ago. We've made many changes since then to improve the server further, and they likely cumulatively resulted in the decline in memory usage. As an example, some backends now allow weight sharing.

We recommend you use the latest versions of Triton, if possible. It wouldn't be the best use of our time to look at why specific models use more memory on previous versions of Triton.
