### ISSUE TITLE
Use custom integer data for warmup

### ISSUE THREAD

**Issue by masguit42** [triton-inference-server/server#4285]
I've made warmup block in `config.pbtxt`:
```
model_warmup {
    name: "first_warmup"
    batch_size: 16
    inputs: [
        {
            key: "data"
            value: {
                data_type: TYPE_FP32
                dims: 12800
                random_data: true
            }
        },
        {
            key: "data_size"
            value: {
                data_type: TYPE_INT32
                dims: 1
                input_data_file: "audio_size"
            }
        }
    ]
}

```
what's the correct way to create such file for `data_size` variable?
I'm stucked.

I've tried this way:

```
import numpy as np
from tritonclient.utils import serialize_byte_tensor
serialized = serialize_byte_tensor(np.array([12800], dtype=object))
with open("./warmup/audio_size", "wb") as fh:
    fh.write(serialized)
```

**Comment by tanmayv25** [comment]
`serialize_byte_tensor` is a utility for TYPE_STRING tensors. 
From what I am looking at:

```
value: {
                data_type: TYPE_INT32
                dims: 1
                input_data_file: "audio_size"
            }
```
It appears the audio_size should be a binary file with size of 4 bytes representing a INT32. See here for more information: https://github.com/triton-inference-server/common/blob/main/protobuf/model_config.proto#L1637-L1643

**Comment by tanmayv25** [comment]
Closing the issue because of the lack of activity.

**Comment by l4zyf9x** [comment]
@tanmayv25 As you mentioned `serialize_byte_tensor` is a utility for TYPE_STRING tensors. So where is utility for INT32, FLOAT32 and BOOL?

**Comment by wangyunxiaa** [comment]
> @tanmayv25 As you mentioned `serialize_byte_tensor` is a utility for TYPE_STRING tensors. So where is utility for INT32, FLOAT32 and BOOL?
I have the same question, can anyone have a reply?
