### ISSUE TITLE
How to connect Triton client library to my C++ client project?  

### ISSUE THREAD

**Issue by InfiniteLife** [triton-inference-server/server#4286]
I've installed Triton client using this:
`
$ pip install tritonclient[all]`

Does it install C++ client binaries or I need to build them from the sources?

And how to connect it to my project? is there anything available like Cmake package search:
`find_package(Triton REQUIRED)`

System is Ubuntu 20.04.

**Comment by MHS-Gautam** [comment]
Hi @InfiniteLife , were you able to figure out the CmakeLists setup to run the Triton client library for your project? I am facing a similar issue. After providing the required paths for CMAKE_PREFIX_PATH, I was able to get the find_package(TritonClient) working but when I try to link grpcclient and httpclient I get linker error stating cannot find library? Also, when I provide absolute path to the static library, I get the error libhttpclient_static.a(http_client.cc.o): undefined reference to symbol 'deflate'?
Have you seen this? Could you please help me out with the target_link_libraries setup? Thanks
