### ISSUE TITLE
Questions about performance test results

### ISSUE THREAD

**Issue by liu1032015185** [triton-inference-server/server#4297]
Hi,
I have some question about Performance Analyzer,
1、Does the number of **concurrency**  refer to the number of threads?
2、Why doesn't the throughput increase any more， The delay doesn't exceed one second immediately until I increase the concurrency to several times？Shouldn't it be blocked there. The delay is more than one second right away？
3、what's Performance Analyzer's input?
4、There are multiple instances in one server docker. Is each instance a process?

Thanks!

**Comment by tanmayv25** [comment]
Closing because of the lack of activity. Feel to reach out if any of your questions are still not answered.
