### ISSUE TITLE
Run tritonserver on Windows10 but it exited without any error

### ISSUE THREAD

**Issue by huangrunqian** [triton-inference-server/server#4299]
I tried to run a tritonserver on my PC with my backend and models, and I got a problem that the tritonserver.exe exited without any error and I don't know why.

tritonserver version: r22.02
command: `tritonserver.exe --backend-directory backends --model-repository models/my_models --log-info true --log-warning true --log-error true --log-verbose 1 --exit-timeout-secs 10`
directories:
  models/
        |------  my_models/
        |------------|---------  model-a/
        |------------|-------------|----------  config.pbtxt
        |------------|-------------|----------  1/
        |------------|-------------|-----------|---------  model.mdl
  backends/
        |------  backend.ini
        |------  logger.properties
        |------  mybackend/
        |-------------|---------- triton_mybackend.dll

log:

I0528 07:33:00.351000 10996 C:\triton\server-r22.02\src\core\model_config_utils.cc:667] Server side auto-completed config: name: "model-a"
input {
  name: "RPC_METHOD"
  data_type: TYPE_STRING
  dims: -1
}
input {
  name: "INFER_INPUT"
  data_type: TYPE_STRING
  dims: -1
}
output {
  name: "INFER_OUTPUT"
  data_type: TYPE_STRING
  dims: -1
}
instance_group {
  count: 48
  kind: KIND_CPU
}
sequence_batching {
  max_sequence_idle_microseconds: 300000000
  control_input {
    name: "START"
    control {
      int32_false_true: 0
      int32_false_true: 1
    }
  }
  control_input {
    name: "READY"
    control {
      kind: CONTROL_SEQUENCE_READY
      int32_false_true: 0
      int32_false_true: 1
    }
  }
  control_input {
    name: "END"
    control {
      kind: CONTROL_SEQUENCE_END
      int32_false_true: 0
      int32_false_true: 1
    }
  }
  control_input {
    name: "CORRID"
    control {
      kind: CONTROL_SEQUENCE_CORRID
      data_type: TYPE_UINT64
    }
  }
  oldest {
    max_candidate_sequences: 1024
  }
}
parameters {
  key: "authorization"
  value {
    string_value: "Your JWT"
  }
}
backend: "mybackend"
model_transaction_policy {
  decoupled: true
}

I0528 07:33:00.367000 10996 C:\triton\server-r22.02\src\core\model_repository_manager.cc:700] AsyncLoad() 'model-a'
I0528 07:33:00.367000 10996 C:\triton\server-r22.02\src\core\model_repository_manager.cc:939] TriggerNextAction() 'model-a' version 1: 1
I0528 07:33:00.383000 10996 C:\triton\server-r22.02\src\core\model_repository_manager.cc:975] Load() 'model-a' version 1
I0528 07:33:00.386000 10996 C:\triton\server-r22.02\src\core\model_repository_manager.cc:994] loading: model-a:1
I0528 07:33:00.495000 10996 C:\triton\server-r22.02\src\core\model_repository_manager.cc:1052] CreateModel() 'model-a' version 1
I0528 07:33:00.495000 10996 C:\triton\server-r22.02\src\core\shared_library.cc:108] OpenLibraryHandle: backends/mybackend/triton_mybackend.dll
I0528 07:33:00.495000 10996 C:\triton\server-r22.02\src\core\shared_library.cc:62] SetLibraryDirectory: path = backends/mybackend
I0528 07:33:00.495000 10996 C:\triton\server-r22.02\src\core\shared_library.cc:118] OpenLibraryHandle: path = backends/mybackend/triton_mybackend.dll
I0528 07:33:00.511000 10996 C:\triton\server-r22.02\src\core\shared_library.cc:86] ResetLibraryDirectory
I0528 07:33:00.511000 10996 C:\triton\server-r22.02\src\core\shared_library.cc:62] SetLibraryDirectory: path = backends/mybackend

And it just exited. Can anyone help me out? Thanks in advance.

**Comment by nv-kmcgill53** [comment]
Hi @huangrunqian, from the look of your output, it appears as though you are providing your own custom backend. Is your backend making use of the `TRITONBACKEND_ModelInitialize` api and doing any logging? Also, is there any more information from stdout, which you may have missed? Thanks.

**Comment by huangrunqian** [comment]
I found out that it was caused by wrong ran location, so the backend couldn't find a necessary file it need to read. Thanks anyway and I'm closing this issue then. :)
