### ISSUE TITLE
"no module named tensorflow" when running Triton server w/ python backend

### ISSUE THREAD

**Issue by klappec-bsci** [triton-inference-server/server#4302]
Triton 22.03-py3
also triton 22.03-tf2-py3

have a model file that tries to "import tensorflow" at the top. 
Importing torch doesn't work either.

I find this strange as there is an example file with 'import torch' at the top for python backend examples.

I am clearly doing something wrong but I cannot figure out what.

My configuration file is setup with backend:"python"

The docker run command is sudo docker run --gpus="all" -v /home/ec2-user/models:/models nvcr.io/nvidia/tritonserver:22.03-py3 tritonserver --model-repository=/models

Full output:

=============================
== Triton Inference Server ==
=============================

NVIDIA Release 22.03 (build 33743047)
Triton Server Version 2.20.0

Copyright (c) 2018-2022, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

NOTE: CUDA Forward Compatibility mode ENABLED.
  Using CUDA 11.6 driver version 510.47.03 with kernel driver version 450.119.01.
  See https://docs.nvidia.com/deploy/cuda-compatibility/ for details.

I0428 17:24:42.864992 1 libtorch.cc:1309] TRITONBACKEND_Initialize: pytorch
I0428 17:24:42.865076 1 libtorch.cc:1319] Triton TRITONBACKEND API version: 1.8
I0428 17:24:42.865082 1 libtorch.cc:1325] 'pytorch' TRITONBACKEND API version: 1.8
2022-04-28 17:24:43.039039: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2022-04-28 17:24:43.077390: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
I0428 17:24:43.077458 1 tensorflow.cc:2176] TRITONBACKEND_Initialize: tensorflow
I0428 17:24:43.077481 1 tensorflow.cc:2186] Triton TRITONBACKEND API version: 1.8
I0428 17:24:43.077489 1 tensorflow.cc:2192] 'tensorflow' TRITONBACKEND API version: 1.8
I0428 17:24:43.077497 1 tensorflow.cc:2216] backend configuration:
{}
I0428 17:24:43.078864 1 onnxruntime.cc:2319] TRITONBACKEND_Initialize: onnxruntime
I0428 17:24:43.078885 1 onnxruntime.cc:2329] Triton TRITONBACKEND API version: 1.8
I0428 17:24:43.078893 1 onnxruntime.cc:2335] 'onnxruntime' TRITONBACKEND API version: 1.8
I0428 17:24:43.078899 1 onnxruntime.cc:2365] backend configuration:
{}
I0428 17:24:43.095987 1 openvino.cc:1207] TRITONBACKEND_Initialize: openvino
I0428 17:24:43.096008 1 openvino.cc:1217] Triton TRITONBACKEND API version: 1.8
I0428 17:24:43.096015 1 openvino.cc:1223] 'openvino' TRITONBACKEND API version: 1.8
I0428 17:24:43.261741 1 pinned_memory_manager.cc:240] Pinned memory pool is created at '0x7f21c8000000' with size 268435456
I0428 17:24:43.262171 1 cuda_memory_manager.cc:105] CUDA memory pool is created on device 0 with size 67108864
I0428 17:24:43.263983 1 model_repository_manager.cc:997] loading: cutedge:1
I0428 17:24:43.367255 1 python.cc:1903] TRITONBACKEND_ModelInstanceInitialize: cutedge (GPU device 0)
0428 17:24:45.387375 87 pb_stub.cc:369] Failed to initialize Python stub: ModuleNotFoundError: No module named 'torch'

At:
  /models/cutedge/1/model.py(3): <module>
  <frozen importlib._bootstrap>(219): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(848): exec_module
  <frozen importlib._bootstrap>(686): _load_unlocked
  <frozen importlib._bootstrap>(975): _find_and_load_unlocked
  <frozen importlib._bootstrap>(991): _find_and_load

E0428 17:24:45.389030 1 model_repository_manager.cc:1155] failed to load 'cutedge' version 1: Internal: ModuleNotFoundError: No module named 'torch'

At:
  /models/cutedge/1/model.py(3): <module>
  <frozen importlib._bootstrap>(219): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(848): exec_module
  <frozen importlib._bootstrap>(686): _load_unlocked
  <frozen importlib._bootstrap>(975): _find_and_load_unlocked
  <frozen importlib._bootstrap>(991): _find_and_load

I0428 17:24:45.389216 1 server.cc:524]
+------------------+------+
| Repository Agent | Path |
+------------------+------+
+------------------+------+

I0428 17:24:45.389409 1 server.cc:551]
+-------------+-------------------------------------------------------------------------+--------+
| Backend     | Path                                                                    | Config |
+-------------+-------------------------------------------------------------------------+--------+
| pytorch     | /opt/tritonserver/backends/pytorch/libtriton_pytorch.so                 | {}     |
| tensorflow  | /opt/tritonserver/backends/tensorflow1/libtriton_tensorflow1.so         | {}     |
| onnxruntime | /opt/tritonserver/backends/onnxruntime/libtriton_onnxruntime.so         | {}     |
| openvino    | /opt/tritonserver/backends/openvino_2021_4/libtriton_openvino_2021_4.so | {}     |
+-------------+-------------------------------------------------------------------------+--------+

I0428 17:24:45.389474 1 server.cc:594]
+---------+---------+---------------------------------------------------------------------+
| Model   | Version | Status                                                              |
+---------+---------+---------------------------------------------------------------------+
| cutedge | 1       | UNAVAILABLE: Internal: ModuleNotFoundError: No module named 'torch' |
|         |         |                                                                     |
|         |         | At:                                                                 |
|         |         |   /models/cutedge/1/model.py(3): <module>                           |
|         |         |   <frozen importlib._bootstrap>(219): _call_with_frames_removed     |
|         |         |   <frozen importlib._bootstrap_external>(848): exec_module          |
|         |         |   <frozen importlib._bootstrap>(686): _load_unlocked                |
|         |         |   <frozen importlib._bootstrap>(975): _find_and_load_unlocked       |
|         |         |   <frozen importlib._bootstrap>(991): _find_and_load                |
+---------+---------+---------------------------------------------------------------------+

**Comment by Tabrizian** [comment]
Tensorflow and Pytorch packages are not installed by default in the Triton container. The dependencies for the examples are included in the documentation of Python backend: https://github.com/triton-inference-server/python_backend#addsubnet-in-pytorch.

**Comment by klappec-bsci** [comment]
Thank you so much Tabrizian , I got it figured out now!
