### ISSUE TITLE
[Question] Semantic Segmentation : Add an argmax layer

### ISSUE THREAD

**Issue by joihn** [triton-inference-server/server#4321]
I have a **semantic segmentation** model, outputing **confidence score** for **each class**. 
Is there a way to add an (efficient GPU powered ) **argmax layer** to the model using Triton ? 

Apparently there support for classification argmaxing [extension_classification](https://github.com/triton-inference-server/server/blob/main/docs/protocol/extension_classification.md)  but not for segmentation

**Comment by joihn** [comment]
One naive workaround would be to create a very small "argmaxer" model in ONNX and then create a model with both model, but not sure how the performance would be affected, will test.

**Comment by rmccorm4** [comment]
Hi @joihn ,

I believe the classification extension may do what you're looking for if you add the `{ "classification": 1 }` parameter to the config for the output corresponding to confidence scores (assuming it is a separate output). If it's not a separate output, then I think you would need to separately postprocess the results, or modify your model to postprocess similarly or separate the output.

i.e.
```
output [
  {
    name: "segmentation_map"
    data_type: TYPE_FP32
    dims: [ 3, 28, 28 ]  // just example output dimensions for images
    label_filename: "labels.txt"
  },
  {
    name: "confidence_scores"
    data_type: TYPE_FP32
    dims: [ 10 ]  // example number of classes 
    parameters: { "classification": 1 }  // top-1 classification of flattened output -> argmax
  }
]
```

You could also look into Triton's ensemble model feature to append a postprocessing step to the pipeline, though this would likely be slower than modifying your model to do something internally.

**Comment by joihn** [comment]
Modifying the ONNX model to add an argmax is confirmed to be faster than a model ensemble, thanks for your help
