### ISSUE TITLE
Docs link error

### ISSUE THREAD

**Issue by future-xy** [triton-inference-server/server#4335]
The link in https://github.com/triton-inference-server/server/blob/main/docs/model_repository.md to Auto-Generated Model Configuration section doesn't work because this section is actually in another doc but the current link points to the local address: 
https://github.com/triton-inference-server/server/blob/cfe3b657d7c3852ded8eb22d41bfdcc6348b4279/docs/model_repository.md?plain=1#L76-L80

**Comment by rmccorm4** [comment]
Hi @future-xy ,

Thanks for reporting this. I'll submit a PR to fix the link.
