### ISSUE TITLE
Python backend stub compilation fails because of TRITONSERVER_TYPE_BF16

### ISSUE THREAD

**Issue by janjagusch** [triton-inference-server/server#4340]
**Description**

This question refers to the [python_backend repository](https://github.com/triton-inference-server/python_backend), but as there is no issue tracker in there, I'm going to open it here instead.

I'm trying to create a custom Python backend stub, as described [here](https://github.com/triton-inference-server/python_backend#1-building-custom-python-backend-stub), using  `nvcr.io/nvidia/tritonserver:22.04-py3` as a compilation base image. When executing `make triton-python-backend-stub`, I get the following error:

```
# Truncated for readability.
-- extracting... done
[ 14%] No update step for 'boostorg'
[ 17%] No patch step for 'boostorg'
[ 20%] Performing configure step for 'boostorg'
[ 23%] No build step for 'boostorg'
[ 26%] No install step for 'boostorg'
[ 29%] Completed 'boostorg'
[ 29%] Built target boostorg
[ 32%] Building CXX object _deps/repo-common-build/CMakeFiles/triton-common-async-work-queue.dir/src/async_work_queue.cc.o
[ 35%] Building CXX object _deps/repo-common-build/CMakeFiles/triton-common-async-work-queue.dir/src/error.cc.o
[ 38%] Linking CXX static library libtritonasyncworkqueue.a
[ 38%] Built target triton-common-async-work-queue
[ 41%] Building CXX object _deps/repo-backend-build/CMakeFiles/triton-backend-utils.dir/src/backend_common.cc.o
[ 44%] Building CXX object _deps/repo-backend-build/CMakeFiles/triton-backend-utils.dir/src/backend_input_collector.cc.o
[ 47%] Building CXX object _deps/repo-backend-build/CMakeFiles/triton-backend-utils.dir/src/backend_memory.cc.o
[ 50%] Building CXX object _deps/repo-backend-build/CMakeFiles/triton-backend-utils.dir/src/backend_model_instance.cc.o
[ 52%] Building CXX object _deps/repo-backend-build/CMakeFiles/triton-backend-utils.dir/src/backend_model.cc.o
[ 55%] Building CXX object _deps/repo-backend-build/CMakeFiles/triton-backend-utils.dir/src/backend_output_responder.cc.o
[ 58%] Linking CXX static library libtritonbackendutils.a
[ 58%] Built target triton-backend-utils
[ 61%] Building CXX object CMakeFiles/triton-python-backend-stub.dir/src/pb_stub_utils.cc.o
/opt/tritonserver/python_backend/src/pb_stub_utils.cc: In function 'pybind11::dtype triton::backend::python::triton_to_pybind_dtype(TRITONSERVER_DataType)':
/opt/tritonserver/python_backend/src/pb_stub_utils.cc:127:10: error: enumeration value 'TRITONSERVER_TYPE_BF16' not handled in switch [-Werror=switch]
  127 |   switch (data_type) {
      |          ^
cc1plus: all warnings being treated as errors
make[3]: *** [CMakeFiles/triton-python-backend-stub.dir/build.make:76: CMakeFiles/triton-python-backend-stub.dir/src/pb_stub_utils.cc.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:261: CMakeFiles/triton-python-backend-stub.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:268: CMakeFiles/triton-python-backend-stub.dir/rule] Error 2
make: *** [Makefile:195: triton-python-backend-stub] Error 2
```

The error makes sense to me, as `TRITONSERVER_TYPE_BF16` is indeed not handled inside the [switch command in the triton_to_pybind_dtype function on branch r22.04](https://github.com/triton-inference-server/python_backend/blob/f3ba41c55380632ba7c464db188515b942d3ba00/src/pb_stub_utils.cc#L127-L171). It's only handled inside [the same switch command on the main branch, where it raises an error](https://github.com/triton-inference-server/python_backend/blob/c37a358e7ade0debad125c87b88fd55e6be53c35/src/pb_stub_utils.cc#L169-L170).

So, my question is about where this `TRITONSERVER_TYPE_BF16` is coming from, what it means, and how I can change it to something else, such that the stub compilation succeeds. I tried digging through the source code, [but couldn't find any other references to TRITONSERVER_TYPE_BF16](https://github.com/triton-inference-server/python_backend/search?q=TRITONSERVER_TYPE_BF16).

**Triton Information**

As I said, I'm using `nvcr.io/nvidia/tritonserver:22.04-py3` as a compilation base image. Since you need to have conda, cmake, and other libraries installed to compile the backend stub, I'm using the following Dockerfile:

```
ARG TRITON_VERSION="22.04"

FROM quay.io/condaforge/mambaforge:4.11.0-0 AS mambaforge

FROM nvcr.io/nvidia/tritonserver:${TRITON_VERSION}-py3

COPY --from=mambaforge /opt/conda /opt/conda
COPY --from=mambaforge /root/.bashrc /root/.bashrc

WORKDIR /root

# Update the CUDA Linux GPG Repository Key, see: https://developer.nvidia.com/blog/updating-the-cuda-linux-gpg-repository-key/
RUN apt-key del 7fa2af80 && \
    wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.0-1_all.deb && \
    dpkg -i cuda-keyring_1.0-1_all.deb

# Install system dependencies.
# Make sure latest version of cmake gets installed, see: https://askubuntu.com/a/865294
RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null && \
    apt-add-repository "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main" && \
    apt-get update && apt-get -y install cmake rapidjson-dev libarchive-dev zlib1g-dev
```

**To Reproduce**

1. Build the Docker image from above.
2. Start a container with an interactive terminal.
3. Run the following commands:

```
mamba install --yes python=3.9 numpy
git clone https://github.com/triton-inference-server/python_backend -b "r${NVIDIA_TRITON_SERVER_VERSION}"

pushd python_backend
mkdir build && cd build
cmake -DTRITON_ENABLE_GPU=ON -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/install ..
make triton-python-backend-stub
```

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**

I would expect the `make triton-python-backend-stub` command to succeed and to produce a `triton_python_backend_stub` file.

**Comment by rmccorm4** [comment]
Hi @janjagusch ,

Can you try adding the following cmake build args to your command to set the [dependent repos](https://github.com/triton-inference-server/python_backend/blob/main/CMakeLists.txt) to r22.04 branch as well?
```
cmake -DTRITON_ENABLE_GPU=ON -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/install \
  -D TRITON_BACKEND_REPO_TAG=r22.04 \
  -D TRITON_COMMON_REPO_TAG=r22.04 \
  -D TRITON_CORE_REPO_TAG=r22.04  \
  ..
```

**Comment by janjagusch** [comment]
> Hi @janjagusch ,
> 
> Can you try adding the following cmake build args to your command to set the [dependent repos](https://github.com/triton-inference-server/python_backend/blob/main/CMakeLists.txt) to r22.04 branch as well?
> 
> ```
> cmake -DTRITON_ENABLE_GPU=ON -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/install \
>   -D TRITON_BACKEND_REPO_TAG=r22.04 \
>   -D TRITON_COMMON_REPO_TAG=r22.04 \
>   -D TRITON_CORE_REPO_TAG=r22.04  \
>   ..
> ```

Thanks, @rmccorm4, this indeed solves the issues. Should we add the changes to the documentation [here](https://github.com/triton-inference-server/python_backend#1-building-custom-python-backend-stub)?

Also, I'm still facing problems when trying to run the Python backend stub inside my Triton server, but I'll open a separate issue for that.
