### ISSUE TITLE
Can ensemble model support to handle multiple inference requests simultaneously?

### ISSUE THREAD

**Issue by qbh1002** [triton-inference-server/server#4341]
Ensemble model seems not support to process multiple inference requests simultaneously. When I configured instance_group in ensemble model config, the triton server started failed, and the log showed instance group should not be specified for ensemble 'ensemble xxx'.

**Comment by qbh1002** [comment]
Ensemble model seems not support to process multiple inference requests. When I configured instance_group in ensemble model config, the triton server starts failed, and the log shows instance group should not be specified for ensemble 'ensemble xxx'.

**Comment by rmccorm4** [comment]
Hi @qbh1002 ,

I just added a note on this to our docs here: https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#ensemble-model-instance-groups

Let me know if this answers your question.

**Comment by qbh1002** [comment]
Hi @rmccorm4 ,

I specified instance_group in every model config file, and it worked for me. Thank you very much.

**Comment by rmccorm4** [comment]
> @rmccorm4 actually the link has been broken, can you share the new link where it has been mentioned as current updated docs don't have info about "multiple instances of ensemble model" or how to deploy them

Fixed the link.
