### ISSUE TITLE
Accept JSON files as configuration files

### ISSUE THREAD

**Issue by issamemari** [triton-inference-server/server#4352]
**Is your feature request related to a problem? Please describe.**

Model configuration files in my environment are generated dynamically using Ansible as they contain some variables that depend on the target host machine.

An Ansible playbook generates the configuration for a model and sends a request to Triton's HTTP endpoint `v2/repository/models/${MODEL_NAME}/load` to update the configuration of the model by providing the configuration in JSON format in the body of the request.

Next, the Ansible playbook has to convert the JSON configuration to pbtxt format in order to save it to `config.pbtxt`. That is not easy to do in Ansible and I had to write a Python script that does the conversion.

It would be nice to avoid having to do the conversion by making Triton accept a JSON file as a model config file. Since Triton supports JSON configuration via its HTTP API, it only makes sense for it to support JSON files as config files as well.

**Describe the solution you'd like**

Triton accepts a JSON file as a model config file.

**Comment by nv-kmcgill53** [comment]
Thank you for your request, we have added this to our roadmap. At this time there is no timeline on the release of this feature.

**Comment by GuanLuo** [comment]
It appears that you are generating the model config in your application, I wonder what is the difficulty of generating it as protobuf string v.s. as JSON string? Our test [here](https://github.com/triton-inference-server/server/blob/main/qa/L0_lifecycle/lifecycle_test.py#L2197-L2199) generate the protobuf string directly and thus don't need to consider the conversion from JSON to protobuf
