### ISSUE TITLE
[Feature Request] Add load_model api to BLS triton_python_backend_utils

### ISSUE THREAD

**Issue by dumbPy** [triton-inference-server/server#4366]
**Is your feature request related to a problem? Please describe.**
loading ensemble model takes care of loading the constituent models.  
Business Logic Scripting is a good flexible alternative to implementing ensemble models, but the caveat is that we need the load the constituent models separately.
Since kserve doesn't support ensemble models (mainly due to model placement issue #4118 ) it would be easier to implement them with BLS, if the model.py can call load model on other models

**Describe the solution you'd like**
Add `load_model` api to `triton_python_backend_utils`

**Describe alternatives you've considered**
Since #4118 is unsolved for kserve, this is the alternative to it.

**Additional context**
If we can load model from BLS, We can ship ensemble models as BLS models like,
```
models
└── M1
    ├── 1
    │   └── model.py
    ├── config.pbtxt
    ├── M11
    │   ├── 1
    │   │   └── model.dali
    │   └── config.pbtxt
    ├── M12
    │   ├── 1
    │   │   └── model.onnx
    │   └── config.pbtxt
    └── M13
        ├── 1
        │   └── model.py
        └── config.pbtxt
```
and on loading the model M1, we can create the symlinks for the constituent models M11,M12,M13 and should be able to call load on them internally with this feature request.
```
models
├── M1
│   ├── 1
│   │   └── model.py
│   ├── config.pbtxt
│   ├── M11
│   │   ├── 1
│   │   │   └── model.dali
│   │   └── config.pbtxt
│   ├── M12
│   │   ├── 1
│   │   │   └── model.onnx
│   │   └── config.pbtxt
│   └── M13
│       ├── 1
│       │   └── model.py
│       └── config.pbtxt
├── M11 -> M1/M11
├── M12 -> M1/M12
└── M13 -> M1/M13
```
effectively making BLS a complete alternative to ensemble.  

Current state is that we need to call load_model on M11, M12 and M13 from client, individually, after loading M1

**Comment by nv-kmcgill53** [comment]
@CoderHam @Tabrizian Is this something we would like to put on our roadmap?

**Comment by CoderHam** [comment]
This looks like a useful enhancement. @Tabrizian can you file a ticket for this so we can help decide a priority for this?

**Comment by Tabrizian** [comment]
Filed a ticket for this issue.

**Comment by zbh0323** [comment]
Now we also meet this problem and have this demand. Has this been realized? If not, when will it happen? @Tabrizian @CoderHam

**Comment by krishung5** [comment]
@jadhosn It's 23.07, please see here: https://github.com/triton-inference-server/python_backend/tree/main?tab=readme-ov-file#model-loading-api
