### ISSUE TITLE
Triton Server build with Docker fails

### ISSUE THREAD

**Issue by antonlukyanov** [triton-inference-server/server#4371]
**Description**
Trying to build Triton Inference Server with Docker. Build fails with message: "make install failed". Build logs are attached: [build_log.txt](https://github.com/triton-inference-server/server/files/8679051/build_log.txt)

**Triton Information**
Building on branch r22.04 (commit `c049b389b411707de035a31e341ecdfbf532cbe2`).

**To Reproduce**
Using the following script to build Triton.
```bash
mkdir -p $HOME/tmp
cd $HOME/tmp

if [ ! -d "tritonserver" ]; then
    git clone https://github.com/triton-inference-server/server.git tritonserver
fi

build_type='Release'
tag='r22.04'
cd tritonserver
git checkout $tag

python3 build.py \
    --cmake-dir=$HOME/tmp/tritonserver/build \
    --build-dir=/tmp/citritonbuild \
    --enable-logging \
    --enable-stats \
    --enable-tracing \
    --enable-metrics \
    --enable-gpu-metrics \
    --enable-gpu \
    --endpoint=http \
    --repo-tag=common:$tag \
    --repo-tag=core:$tag \
    --repo-tag=backend:$tag \
    --repo-tag=thirdparty:$tag \
    --backend=ensemble \
    --backend=tensorrt \
    --backend=identity \
    --backend=repeat \
    --backend=square \
    --backend=onnxruntime \
    --backend=pytorch \
    --backend=tensorflow1 \
    --backend=tensorflow2 \
    --backend=openvino \
    --backend=python \
    --backend=dali \
    --backend=fil \
    --repoagent=checksum \
    --build-type=$build_type
```

build.py is modified as follows to overcome this problem: https://forums.developer.nvidia.com/t/invalid-public-key-for-cuda-apt-repository/212901/27

```diff
diff --git a/build.py b/build.py
index 8867daaf..e017a342 100755
--- a/build.py
+++ b/build.py
@@ -759,6 +759,9 @@ ENV DCGM_VERSION {}
 RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin && \
     mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600 && \
     apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub && \
+    apt-key del 7fa2af80 && \
+    wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.0-1_all.deb && \
+        dpkg -i cuda-keyring_1.0-1_all.deb && \
     add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /" && \
     apt-get update && apt-get install -y datacenter-gpu-manager=1:{}
 '''.format(dcgm_version, dcgm_version)
```

By looking at log looks like the problem is still the same:

```
#11 9.248 W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
#11 9.248 E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease' is not signed.
```

Python version is 3.9.12.

**Expected behavior**
Building Triton with Docker succeeds.

**Comment by mc-nv** [comment]
Hi @antonlukyanov ,

This is know issue for `r22.04` and would be fixed in future releases. 

Please make sure that you made appropriate changes for all given files.

Below quote from [Release 2.21.0 corresponding to NGC container 22.04](https://github.com/triton-inference-server/server/releases/edit/v2.21.0) release page is refer customers to [commit](https://github.com/triton-inference-server/server/commit/270b9db032c96631c60957083766f4746c5d240b) and places which needs to be upated. 
> * To best ensure the security and reliability of our RPM and Debian package repositories, NVIDIA is updating and rotating the signing keys used by the `apt`, `dnf/yum`, and `zypper` package managers beginning April 27, 2022.
> Triton r22.04 and prior release branches have not updated these repository signing keys. Due to this users should expect package management errors when attempting to access or install packages from CUDA repositories.
> Please follow these [recommendations](https://developer.nvidia.com/blog/updating-the-cuda-linux-gpg-repository-key/) to mitigate the issue.
> Please update your branches prior to building to include the updated signing key(s). These changes are captured in this [commit](https://github.com/triton-inference-server/server/commit/270b9db032c96631c60957083766f4746c5d240b).

**Comment by antonlukyanov** [comment]
Hi @mc-nv! Thanks for the info and quick response.

**Comment by BrandonBocheng** [comment]
Hello, I just simulate the Triton building process by following the url:https://github.com/triton-inference-server/server/blob/main/docs/build.md#building-triton-with-docker

But when I run the build.py using the default argument, there is an error shown in my terminal which is attached as picture. Can anyone give me the hints to solve it? Thanks a lot.
![Screenshot from 2022-05-13 16-26-03](https://user-images.githubusercontent.com/42810939/168243003-b6224ecb-3363-44ea-936d-b5fb2cfbcf2c.png)

**Comment by antonlukyanov** [comment]
Hi @BrandonBocheng, you need to install docker package for Python before running the script:
```
pip3 install docker
```

**Comment by antonlukyanov** [comment]
@mc-nv Still Triton debug build fails with an error:

```
CMake Error at /usr/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find GTest (missing: GTEST_LIBRARY GTEST_MAIN_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.21/Modules/FindGTest.cmake:255 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  test/CMakeLists.txt:32 (find_package)
```

Release build succeeds.
Building debug version it with the following script:

```bash
mkdir -p $HOME/tmp
cd $HOME/tmp

if [ ! -d "tritonserver" ]; then
    git clone https://github.com/triton-inference-server/server.git tritonserver
fi

build_type='Debug'
tag='r22.04'
cd tritonserver
git checkout $tag
git cherry-pick --no-commit 270b9db032c96631c60957083766f4746c5d240b

~/.pyenv/shims/python3 build.py \
    --cmake-dir=$HOME/tmp/tritonserver/build \
    --build-dir=/tmp/citritonbuild \
    --enable-logging \
    --enable-stats \
    --enable-tracing \
    --enable-metrics \
    --enable-gpu-metrics \
    --enable-gpu \
    --endpoint=http \
    --repo-tag=common:$tag \
    --repo-tag=core:$tag \
    --repo-tag=backend:$tag \
    --repo-tag=thirdparty:$tag \
    --backend=ensemble \
    --backend=tensorrt \
    --backend=identity \
    --backend=repeat \
    --backend=square \
    --backend=onnxruntime \
    --backend=pytorch \
    --backend=tensorflow1 \
    --backend=tensorflow2 \
    --backend=openvino \
    --backend=python \
    --repoagent=checksum \
    --build-type=$build_type
```

**Comment by mc-nv** [comment]
The issue here is that the `--cmake-dir` flag is used to point to the directory which doesn't contain `CMakeLists.txt` file for Triton server [[build.py#L1602](https://github.com/triton-inference-server/server/blob/r22.04/build.py#L1602)]. 

Please adjust the `--cmake-dir=<repo-folder-path>/build` flag reference.

**Comment by BrandonBocheng** [comment]
Hi, @antonlukyanov 

> Hi @BrandonBocheng, you need to install docker package for Python before running the script:
> 
> ```
> pip3 install docker
> ```

Hi, @antonlukyanov , thanks for ur reply. This problem has been solved but there is another problem appear. I have already cd to the server/ folder and run **./build.py --cmake-dir ./ --build-dir ./build**, another problem appear which is shown in the attachment. BTW, I have already installed the gnutls-bin and close the sslVerify for this repo. Wish to get the reply, thx
![Screenshot from 2022-05-17 14-52-41](https://user-images.githubusercontent.com/42810939/168748801-c28b3332-e8ab-4ef2-b177-adb880b92718.png)

**Comment by antonlukyanov** [comment]
> The issue here is that the `--cmake-dir` flag is used to point to the directory which doesn't contain `CMakeLists.txt` file for Triton server [[build.py#L1602](https://github.com/triton-inference-server/server/blob/r22.04/build.py#L1602)].
> 
> Please adjust the `--cmake-dir=<repo-folder-path>/build` flag reference.

@mc-nv Thanks a lot for the hint! It worked.

**Comment by antonlukyanov** [comment]
@BrandonBocheng It looks like that the problem is in installation of git in your system. I think you should check it and manually try to clone the repo which is cloned with error.
