### ISSUE TITLE
docker run not working

### ISSUE THREAD

**Issue by riyaj8888** [triton-inference-server/server#4376]
when i am trying to run this command 

$ docker run   --rm -p8000:8000 -p8001:8001 -p8002:8002 -v/full/path/to/docs/examples/model_repository:/models nvcr.io/nvidia/tritonserver:<xx.yy>-py3 tritonserver --model-repository=/models

i am getting following error
"I0513 16:41:33.294949 1 server.cc:247] No server context available. Exiting immediately.
error: creating server: Internal - failed to stat file C:/Program Files/Git/models"

I m using triton 22.04 version ,cuda 11.3

**Comment by nv-kmcgill53** [comment]
Hi @riyaj8888, can you please re-ask your question using our [issue template](https://github.com/triton-inference-server/server/blob/main/.github/ISSUE_TEMPLATE/bug_report.md)? This will help us attend to your issue. Thanks!

**Comment by riyaj8888** [comment]
Description A clear and concise description of what the bug is.

## Triton Information What version of Triton are you using? --> 22.04/20.06

### Are you using the Triton container or did you build it yourself? --> using triton container



### Expected behavior A clear and concise description of what you expected to happen.--> wanted to use triton server client for response.

![smi](https://user-images.githubusercontent.com/29457825/168414152-fe480025-3b9d-4e5b-bfc2-e7431379b629.PNG)

**Comment by riyaj8888** [comment]
docker run --rm -p8000:8000 -p8001:8001 -p8002:8002 -v/full/path/to/docs/examples/model_repository:/models nvcr.io/nvidia/tritonserver:<xx.yy>-py3 tritonserver --model-repository=/models

i am getting following error for cpu 

"I0513 16:41:33.294949 1 server.cc:247] No server context available. Exiting immediately.
error: creating server: Internal - failed to stat file C:/Program Files/Git/models"

**Comment by riyaj8888** [comment]
`=============================
== Triton Inference Server ==
=============================

NVIDIA Release 22.04 (build 36821869)
Triton Server Version 2.21.0

Copyright (c) 2018-2022, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use the NVIDIA Container Toolkit to start this container with GPU support; see
   https://docs.nvidia.com/datacenter/cloud-native/ .

WARNING: [Torch-TensorRT] - Unable to read CUDA capable devices. Return status: 35
I0514 06:46:17.160618 1 libtorch.cc:1381] TRITONBACKEND_Initialize: pytorch
I0514 06:46:17.160778 1 libtorch.cc:1391] Triton TRITONBACKEND API version: 1.9
I0514 06:46:17.160785 1 libtorch.cc:1397] 'pytorch' TRITONBACKEND API version: 1.9
2022-05-14 06:46:17.342908: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
I0514 06:46:17.380100 1 tensorflow.cc:2181] TRITONBACKEND_Initialize: tensorflow
I0514 06:46:17.380165 1 tensorflow.cc:2191] Triton TRITONBACKEND API version: 1.9
I0514 06:46:17.380175 1 tensorflow.cc:2197] 'tensorflow' TRITONBACKEND API version: 1.9
I0514 06:46:17.380180 1 tensorflow.cc:2221] backend configuration:
{}
I0514 06:46:17.381736 1 onnxruntime.cc:2400] TRITONBACKEND_Initialize: onnxruntime
I0514 06:46:17.381822 1 onnxruntime.cc:2410] Triton TRITONBACKEND API version: 1.9
I0514 06:46:17.381829 1 onnxruntime.cc:2416] 'onnxruntime' TRITONBACKEND API version: 1.9
I0514 06:46:17.381833 1 onnxruntime.cc:2446] backend configuration:
{}
I0514 06:46:17.400167 1 openvino.cc:1207] TRITONBACKEND_Initialize: openvino
I0514 06:46:17.400227 1 openvino.cc:1217] Triton TRITONBACKEND API version: 1.9
I0514 06:46:17.400234 1 openvino.cc:1223] 'openvino' TRITONBACKEND API version: 1.9
W0514 06:46:17.400262 1 pinned_memory_manager.cc:236] Unable to allocate pinned system memory, pinned memory pool will not be available: CUDA driver version is insufficient for CUDA runtime version
I0514 06:46:17.400283 1 cuda_memory_manager.cc:115] CUDA memory pool disabled
I0514 06:46:17.400544 1 tritonserver.cc:2123]
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Option                           | Value
                                                                                           |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| server_id                        | triton
                                                                                           |
| server_version                   | 2.21.0
                                                                                           |
| server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_policy model_configuration system_shared_memory cuda_shared_memory binary_tensor_data statistics trace |
| model_repository_path[0]         | C:/Program Files/Git/models
                                                                                           |
| model_control_mode               | MODE_NONE
                                                                                          |
| strict_model_config              | 1
                                                                                          |
| rate_limit                       | OFF
                                                                                          |
| pinned_memory_pool_byte_size     | 268435456
                                                                                          |
| response_cache_byte_size         | 0
                                                                                          |
| min_supported_compute_capability | 6.0
                                                                                          |
| strict_readiness                 | 1
                                                                                          |
| exit_timeout                     | 30
                                                                                          |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

I0514 06:46:17.400579 1 server.cc:247] No server context available. Exiting immediately.
error: creating server: Internal - failed to stat file C:/Program Files/Git/models
`

**Comment by Tabrizian** [comment]
The error you have shared means that the path you specified cannot be found by the server. Also, I don't think the Linux containers can be used on Windows. You need to download the windows build from the release page: https://github.com/triton-inference-server/server/releases/tag/v2.23.0 Or build the docker yourself.

**Comment by jabuarab** [comment]
For Windows users using Git Bash who arrived here: Git bash  add "C:/Program Files/Git" to your paths when using docker and some other commands, check this issue for more details:[https://stackoverflow.com/questions/48427366/docker-build-command-add-c-program-files-git-to-the-path-passed-as-build-argu](url)
