### ISSUE TITLE
GPG Keys Expired For Apt Packages

### ISSUE THREAD

**Issue by ddukek22** [triton-inference-server/server#4380]
**Description**
We observed this error due to the gpg keys that are baked into the base image here https://github.com/triton-inference-server/server/blob/v2.17.0/Dockerfile.sdk#L79-L95 becoming stale. I noticed that the image hasn't been rebuilt and made available in NGC since December.

Do you currently have a lifecycle over which these images are supported with security patches etc?

```
#12 8.926 Reading package lists...
#12 9.781 W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
#12 9.781 E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease' is not signed.
```

**Triton Information**
What version of Triton are you using?
2.17 - ngc container version 21.12

Are you using the Triton container or did you build it yourself?
I'm using the triton container pulled from NGC

**To Reproduce**
Steps to reproduce the behavior.
Use the container from NGC as the base image, and then try to update apt packages.

**Expected behavior**
I'm able to run apt update when building on top of the base image.

**Comment by ddukek22** [comment]
Great thanks for the reply @rmccorm4 . In my case for triton version 2.17 as described in this issue adding

```
RUN apt-key del 7fa2af80 && wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.0-1_all.deb && dpkg -i cuda-keyring_1.0-1_all.deb
```

To the top of my Dockerfile when I am using the triton image as a base image solves the problem.

**Comment by alxmamaev** [comment]
Il already tied many times. But this patch is not working.

How I can fix it?
```
RUN apt-key del 7fa2af80
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/$(uname -m)/3bf863cc.pub
```


My error:
```
W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease: At least one invalid signature was encountered.
E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease' is not signed.
W: GPG error: http://security.ubuntu.com/ubuntu focal-security InRelease: At least one invalid signature was encountered.
E: The repository 'http://security.ubuntu.com/ubuntu focal-security InRelease' is not signed.
W: GPG error: http://archive.ubuntu.com/ubuntu focal InRelease: At least one invalid signature was encountered.
E: The repository 'http://archive.ubuntu.com/ubuntu focal InRelease' is not signed.
W: GPG error: http://archive.ubuntu.com/ubuntu focal-updates InRelease: At least one invalid signature was encountered.
E: The repository 'http://archive.ubuntu.com/ubuntu focal-updates InRelease' is not signed.
W: GPG error: http://archive.ubuntu.com/ubuntu focal-backports InRelease: At least one invalid signature was encountered.
E: The repository 'http://archive.ubuntu.com/ubuntu focal-backports InRelease' is not signed.
```
