### ISSUE TITLE
Request specifies invalid shape for input 'images' for yolov5x6_tensorrt. Error details: model expected the shape of dimension 0 to be between 1 and 1 but received 32

### ISSUE THREAD

**Issue by InfiniteLife** [triton-inference-server/server#4384]
I think my issue is related to this: https://github.com/triton-inference-server/server/issues/3032

```
err = grpc_client_->Infer(
            &result, options, inputs, outputs, headers_);
```

returns error:
`request specifies invalid shape for input 'images' for yolov5x6_tensorrt. Error details: model expected the shape of dimension 0 to be between 1 and 1 but received 32`

`Input` was created with shape `32x3x768x1280` 

Here is input config:
```
name: "yolov5x6_tensorrt"
platform: "tensorrt_plan"
max_batch_size : 128
input [
  {
    name: "images"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 768, 1280 ]
  }
]
```
Model was successfully loaded into Triton server.

Im using `22.03` container version.

Follow up question, if I create input of batch size 32 but fill it with amount of samples using `AppendRaw` less than 32, would it matter?

**Comment by InfiniteLife** [comment]
If I run server configuration with `--strict-model-config=false` parameter, I get error:
`UNAVAILABLE: Internal: autofill failed for model 'yolov5x6_tensorrt': configuration specified max-batch 128 but TensorRT engine only supports max-batch 1`
so I guess it's the same issue I linked above - Triton Server wont check if tensorrt model actually supports batching if `max_batch_size > 0`

**Comment by Tabrizian** [comment]
The issue is with your model. Looks like the TRT model is not generated properly to support variable first dimension. Please refer to the issue below for guidance: https://github.com/triton-inference-server/server/issues/4445
