### ISSUE TITLE
Why is an extra 1 added to the first element of the result of model  simple_squence?

### ISSUE THREAD

**Issue by ccnankai** [triton-inference-server/server#4386]
Hi,
I followed the quick start tutorial, ran simple_http_sequence_stream_infer_client.py and got the result as follows:
1. I don't understand why an extra 1 is added to the result in the first row, shouldn't it be [0, 100, 20]?Why insert an element at the head of the array？

values=[11,7,5,3,2,0,1]
inputs :    https://github.com/triton-inference-server/client/blob/9668a9fc1bd7e2fe84b2fe77dd3211756b6c3ef7/src/python/examples/simple_http_sequence_sync_infer_client.py#L140

![1652789826(1)](https://user-images.githubusercontent.com/33537489/168808856-fcf8648d-67ae-4e88-be70-0b1dbce79d5e.png)

2.  https://github.com/triton-inference-server/client/blob/9668a9fc1bd7e2fe84b2fe77dd3211756b6c3ef7/src/python/examples/simple_http_sequence_sync_infer_client.py#L130
Why is there an integer type sequenceID and a string type sequenceID, what is the difference?

**Comment by krishung5** [comment]
Hi @ccnankai, sorry for the late response. For the first question, it is the design of the [sequence model](https://github.com/triton-inference-server/server/blob/main/src/test/sequence/src/sequence.cc) we are using for this example. You can refer to the description [here](https://github.com/triton-inference-server/server/blob/main/src/test/sequence/src/sequence.cc#L36-L57) to see the more details of this model. All the handling and the validation set in the client script are based on the model behavior. For the second question, the reason we are using sequenceID and stringID is just for demonstration. From [here](https://github.com/triton-inference-server/client/blob/main/src/python/examples/simple_http_sequence_sync_infer_client.py#L114) you can see that if the flag is set, we will be using `simple_string_dyna_sequence` mode for inference, which requires string type sequeneID.

**Comment by ccnankai** [comment]
Understood，Thank you very much.
