### ISSUE TITLE
[Question] perf_analyzer, "Server Compute Input" meaning

### ISSUE THREAD

**Issue by joihn** [triton-inference-server/server#4389]
I'm using the perf_analyzer [tool ](https://github.com/triton-inference-server/server/blob/main/docs/perf_analyzer.md), which output (among other things) a column `Server Compute Input`

What is it exactly ? Why does the input needs to be "computed" ? is it simply the transfer from CPU memory to GPU ?

**Comment by krishung5** [comment]
Hi @joihn, transferring tensors to GPU is part of `Server Compute Input` duration but not necessarily all of it. `Server Compute Input` is a cumulative duration for preparing input tensor data as required. Please refer to this [doc](https://github.com/triton-inference-server/server/blob/main/docs/protocol/extension_statistics.md#statistics-response-json-object) to see statistics extension for Triton.

**Comment by joihn** [comment]
thanks
