### ISSUE TITLE
python backend example for BERT like architecture

### ISSUE THREAD

**Issue by riyaj8888** [triton-inference-server/server#4391]
can you provide pre-processing and post-processing logic for BERT like model in python backend examples.
because examples you provided [https://github.com/triton-inference-server/python_backend/tree/main/examples](url) here are not useful at all.

i want the input to be text input and output should be returned from model.plan (tensorrt model) .

where and what changes should be done to achieve this

**Comment by krishung5** [comment]
Hi @riyaj8888, the pre-processing and post-processing logic should be able to be implemented using [ensemble models](https://github.com/triton-inference-server/server/blob/main/docs/architecture.md#ensemble-models). We also have an [pre-processing example](https://github.com/triton-inference-server/python_backend/blob/main/examples/preprocessing/README.md) using python backend. This should be a good starting point.

**Comment by Tabrizian** [comment]
Closing due to in-activity. Using the examples that Kris pointed out, you should be able to design your own pipeline for pre/post processing.
