### ISSUE TITLE
Dynamically passing model parameters in inference request

### ISSUE THREAD

**Issue by Revist** [triton-inference-server/server#4400]
**Is your feature request related to a problem? Please describe.**
I have a model which has some internal parameters for inference e.g. crop size - the model takes crops of image, inferences on them and assembles final inference output. 

**Describe the solution you'd like**
I would like to dynamically pass a parameter crop size during the inference request. 

I use dynamic batching with ragged inputs. i.e. now I send images of different sizes one by one and dynamic batcher assembles them into one input batch. If I add the parameter "crop size" as a second input I would like dynamic batcher to assemble requests with crop size = 100 into one batch and send them to inference while requests with crop size = 200 are assembled into another batch and sent to inference separately. I.e I would like to have a grouping of requests based on specific configuration so that when I run inference on a batch I have only one unique value of my parameter crop size. Is there an easy way to achieve that?

**Describe alternatives you've considered**
I could introduce a model "model_gather" which receives all requests and creates these batches for every unique configuration and sends them to "the_actual_model" already grouped. It seems, however, that there ought to be much simpler way of doing things as changing configurations is pretty common.

**Additional context**
As crop size can have many values I cannot create a separate model version for every value.

**Comment by krishung5** [comment]
@tanmayv25 @GuanLuo Is this some feature we would like to add in the future?

**Comment by tanmayv25** [comment]
Your exact ask is difficult to implement within Triton core but we do have something similar for supporting [shape tensors](https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#exe_shape_tensors) in TensorRT, which is similar to your `crop_size`. Generally, Triton core avoids reading a tensor data to make batching decisions.
This is how it currently works:
1. As soon as a request with different shape value is encountered, we will push whatever dynamic batch we have to the backend for execution.
2. The second request with different shape value will mark the beginning of a new batch.

So, in your case if the requests are like following:
R1(crop_size=100), R2(crop_size=100), R3(crop_size=200), R4(crop_size=100), R5(crop_size=100), R6(crop_size=200).

The executed batches would be:
R1 + R2, R3, R4 + R5, R6.

This logic can be made available but is not what you are asking for. What you want is:
R1+R2+R4+R5,  R3+R6.

This can quickly lead to a request build up on the batcher side. What if there are several requests with all different batch size? After the timeout all will try to get a model instance for execution and affect the latency of one another which can lead to large tail latency.

I believe your exact ask is very user_specific and the work around you proposed with the custom backend to collect the requests and execute them on the model is what I would suggest.

**Comment by tanmayv25** [comment]
Closing because of the lack of activity for more than 14 days. Feel free to reach out to engage in further discussion. Currently, we would advice the work around that you have proposed as the proper solution to your problem.
