### ISSUE TITLE
L0_https Client Example Hangs 

### ISSUE THREAD

**Issue by eanmikale** [triton-inference-server/server#4402]
**Description**
The test script hangs with onnx and tensorflow backends. 
**Triton Information**

Jetpack 4.6 version. 

Are you using the Triton container or did you build it yourself?

Source 

**To Reproduce**
Steps to reproduce the behavior.

 v5.7                                                                  server.log                                                                             
| server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_policy model_configuration system_s>
| model_repository_path[0]         | /home/xxxxxxx/server/docs/examples/model_repository/                                                            >
| model_control_mode               | MODE_NONE                                                                                                                >
| strict_model_config              | 0                                                                                                                        >
| rate_limit                       | OFF                                                                                                                      >
| pinned_memory_pool_byte_size     | 268435456                                                                                                                >
| cuda_memory_pool_byte_size{0}    | 67108864                                                                                                                 >
| response_cache_byte_size         | 0                                                                                                                        >
| min_supported_compute_capability | 5.3                                                                                                                      >
| strict_readiness                 | 1                                                                                                                        >
| exit_timeout                     | 30                                                                                                                       >
+----------------------------------+-------------------------------------------------------------------------------------------------------------------------->

I0518 23:28:16.057774 21401 grpc_server.cc:4325] === GRPC KeepAlive Options ===
I0518 23:28:16.057819 21401 grpc_server.cc:4326] keepalive_time_ms: 7200000
I0518 23:28:16.057845 21401 grpc_server.cc:4328] keepalive_timeout_ms: 20000
I0518 23:28:16.057870 21401 grpc_server.cc:4330] keepalive_permit_without_calls: 0
I0518 23:28:16.057896 21401 grpc_server.cc:4332] http2_max_pings_without_data: 2
I0518 23:28:16.057920 21401 grpc_server.cc:4334] http2_min_recv_ping_interval_without_data_ms: 300000
I0518 23:28:16.057944 21401 grpc_server.cc:4337] http2_max_ping_strikes: 2
I0518 23:28:16.057968 21401 grpc_server.cc:4339] ==============================
E0518 18:28:16.060696302   21401 server_chttp2.cc:40]        {"created":"@1652916496.060257044","description":"No address added out of total 1 resolved","file>
Signal (11) received.
 0# 0x000000557152C900 in /home/xxxxxxx/Downloads/bin/tritonserver
 1# __kernel_rt_sigreturn in linux-vdso.so.1
 2# 0x000000557180D02C in /home/infiniteaiengine/Downloads/bin/tritonserver
 3# 0x000000557160A968 in /home/infiniteaiengine/Downloads/bin/tritonserver
 4# 0x0000005571612C80 in /home/infiniteaiengine/Downloads/bin/tritonserver
 5# 0x0000005571620A10 in /home/infiniteaiengine/Downloads/bin/tritonserver
 6# 0x0000007FA6757E94 in /usr/lib/aarch64-linux-gnu/libstdc++.so.6
 7# 0x0000007FA6B02088 in /lib/aarch64-linux-gnu/libpthread.so.0

Here is the command: sudo bash -x test.sh REPO_VERSION=1

Any insight into why this hangs would be awesome.

**Comment by CoderHam** [comment]
Which version of Triton are you using for your build? The L0_https needs to be patched with the --backend-directory arg to launch on Jetson correctly. Refer to the Jetson usage guide: [jetson.md](https://github.com/triton-inference-server/server/blob/main/docs/jetson.md)

**Comment by eanmikale** [comment]
Thanks, I'm using the Jetpack 4.6 Version. Here is the patched command inside the test.sh file. 

SERVER_ARGS="--repoagent-directory=/home/xxxxxxxxxxxxx/Downloads/qa/checksum_repository_agent/ --model-repository=/home/xxxxxxxxxxxxxx/server/docs/examples/model_repository/ --backend-directory=/home/xxxxxxxxxxxxxxxx/Downloads/backends/ --backend-config=onnxruntime,enable-global-threadpool=0 --backend-config=onnxruntime,intra_op_thread_count=0 --backend-config=onnxruntime,inter_op_thread_count=0 --backend-config=tensorflow,enable-global-threadpool=0 --backend-config=tensorflow,intra_op_thread_count=0 --backend-config=tensorflow,inter_op_thread_count=0 --log-verbose=1 --strict-model-config=false"

Let me know if you get something different. Thanks again.

**Comment by eanmikale** [comment]
Now, getting a no module named tritonclient.http error.  See here: 

 File "/home/xxxxxxxxxxxxx/Downloads/python/simple_http_infer_client.py", line 33, in <module>
    import tritonclient.http as httpclient
ImportError: No module named tritonclient.http
test.sh: line 107: /home/infiniteaiengine/Downloads/bin/simple_http_infer_client: cannot execute binary file: Exec format error
Traceback (most recent call last):
  File "/home/xxxxxxxxxxxxxxxxxxxx/Downloads/python/simple_http_infer_client.py", line 33, in <module>
    import tritonclient.http as httpclient
ImportError: No module named tritonclient.http
test.sh: line 120: /home/infiniteaiengine/Downloads/bin/simple_http_infer_client: cannot execute binary file: Exec format error
Traceback (most recent call last):
  File "/home/xxxxxxxxxxxxxx/Downloads/python/simple_http_infer_client.py", line 33, in <module>
    import tritonclient.http as httpclient
ImportError: No module named tritonclient.http

***
*** Expected test failure
***
test.sh: line 136: /home/xxxxxxxxxxxxx/Downloads/bin/simple_http_infer_client: cannot execute binary file: Exec format error

***
*** Expected test failure
***
Traceback (most recent call last):
  File "/home/xxxxxxxxxxxxxxxx/Downloads/python/simple_http_infer_client.py", line 33, in <module>
    import tritonclient.http as httpclient
ImportError: No module named tritonclient.http

***
*** Expected test failure
***
test.sh: line 154: /home/xxxxxxxxxxxxxxxxxxxxx/Downloads/bin/simple_http_infer_client: cannot execute binary file: Exec format error

***
*** Expected test failure
***
test.sh: line 165:  2990 Segmentation fault      (core dumped) LD_PRELOAD=$SERVER_LD_PRELOAD $SERVER $SERVER_ARGS > $SERVER_LOG 2>&1


However, I did install the related client for the Jetson 4.6.1 version. 

Even after installing the wheel, I am unable to import in Python3, and there is little documentation online for the fix.

**Comment by eanmikale** [comment]
If I enter the import tritonclient.http as httpclient command in the Python3 interpreter, it imports successfully, however, when the actual code runs, it does not take, even after updating the cache??? Any assistance is appreciated.

**Comment by eanmikale** [comment]
I have been able to solve this issue. I had to combine the server script and the client script, creating a new script, in order to get it to run, due to the openssl settings. It was arduous. it seems there were steps in the openssl certificate creation for the client, that was contained in the server. You can close the ticket. 



Regards, 

EM






---- On Thu, 19 May 2022 19:52:29 -0500 Hemant Jain ***@***.***> wrote ----





Which version of Triton are you using for your build? The L0_https needs to be patched with the --backend-directory arg to launch on Jetson correctly. Refer to the Jetson usage guide: https://github.com/triton-inference-server/server/blob/main/docs/jetson.md

**Comment by GuanLuo** [comment]
Glad to know that you have resolved the issue, do you mind to share how to resolve the SSL issue if it is okay for you, so that other may check it out if they encounter similar issue?

Closing the ticket as the issue has been resolved
