### ISSUE TITLE
how to deploy stateful model without implicit state management

### ISSUE THREAD

**Issue by murphypei** [triton-inference-server/server#4415]
For some reasons of driver, I must use the **triton20.09** which dose't seem to support **Implicit State Management** feature:
```
[libprotobuf ERROR /workspace/builddir/grpc-repo/src/grpc/third_party/protobuf/src/google/protobuf/text_format.cc:317] Error parsing text-format inference.ModelConfig: 17:11: Message type "inference.ModelSequenceBatching" has no field named "state".
```
Can you guys give me any advice? Any suggestions are very welcome, thanks.

**Comment by dyastremsky** [comment]
Triton 20.09 is over a year and a half old, quite likely before implicit state management was added. If so, you'll need a more recent version of Triton to use this feature.
