### ISSUE TITLE
config.pbtxt format in Python Protobuf text_format

### ISSUE THREAD

**Issue by JesseEisen** [triton-inference-server/server#4421]
**Question**

I just try the use below Python code to generate a config.pbtxt file's content

```python
text_format.PrintMessage(
                self.model_pbtxt, f,use_short_repeated_primitives=True
)
```

But the  **repeated**  message field like `input` and `output` are not show in the format like json list.

```python
...
input {
   .....
}
input {
  .....
}
```

These format content can parsed by text_format, but the format looks weird. So i am confused, Is there any suggestions or tools to generate the configuration like the example model repository?  just like:

```python
input: [
   { .... },
   { .... }
]
```

Or this can only generated by template or some string format trick?  Waiting for your response. 

Thanks

**Comment by nv-kmcgill53** [comment]
Hi @JesseEisen, config.pbtxt is a protobuf text file which has different syntax than json. [Here is an example](https://github.com/triton-inference-server/server/blob/main/qa/L0_model_config/autofill_noplatform_success/tensorflow_savedmodel/empty_config/expected) of a configuration file which has multiple inputs and outputs. You can see the `input` and `output` fields are repeated as expected. 

> Is there any suggestions or tools to generate the configuration like the example model repository?

A quick way to do this might be to load the model in triton and, once the model is loaded, call the `/v2/models/<model_name>/versions/<model_version_number>/config` endpoint which will return the model configuration in json form.

**Comment by JesseEisen** [comment]
Hi, thank you for reply.

I just saw the example you provided,it's in the same format as what i saved. That means the protobuffer's `text_format` generates those format as default. My confusion is the format provided in this repo： `docs/examples` is more pretty than generated😅.

And you say can load the model in server side and use `config` api to fetch the config generated by triton. So is there a convenient way to hot replace the model or load a new model repo uploaded by RESTFUL api? I looked for the quick started reference, find the `upload` api seems can only update an existed model. 

If can do hot reload existed model or load new model repo in server side, means i don't need to restart the sever each time.

**Comment by nv-kmcgill53** [comment]
>  So is there a convenient way to hot replace the model or load a new model repo uploaded by RESTFUL api?

You are probably interested in our [client repository](https://github.com/triton-inference-server/client#client-library-apis) which has a couple of different pre-built clients which you can use to interact with Triton. [Here is a python example](https://github.com/triton-inference-server/client/blob/main/src/python/examples/simple_http_model_control.py) where we load and unload models, but there are many more in the [examples directory](https://github.com/triton-inference-server/client/tree/main/src/python/examples).

**Comment by JesseEisen** [comment]
Thanks， i will checkout the client repo's examples.
