### ISSUE TITLE
Triton inference is slow then normal pytorch model on GPU,     http_server.cc:1226] HTTP: unable to provide 'OUTPUT__0' in GPU, will use CPU

### ISSUE THREAD

**Issue by bhupendrasalesken** [triton-inference-server/server#4430]
**Description**
triton inference is slow, though the model is loaded on GPU still the inference time is very slow 

**Triton Information**
21.05

Are you using the Triton container or did you build it yourself?
Trion container 

I am  getting these logs , though the inference is running and running correctly but as it is using CPU, it's very slow.

```
I0524 13:06:57.818420 1 libtorch.cc:1087] model multiqa_pr, instance multiqa_pr_0_1, executing 1 requests
I0524 13:06:57.818433 1 libtorch.cc:504] TRITONBACKEND_ModelExecute: Running multiqa_pr_0_1 with 1 requests
I0524 13:06:58.631790 1 infer_response.cc:165] add response output: output: OUTPUT__0, type: FP32, shape: [64,256,384]
I0524 13:06:58.631863 1 http_server.cc:1226] HTTP: unable to provide 'OUTPUT__0' in GPU, will use CPU
I0524 13:06:58.631896 1 http_server.cc:1246] HTTP using buffer for: 'OUTPUT__0', size: 25165824, addr: 0x7fb4f1fff040
I0524 13:06:58.861857 1 infer_response.cc:165] add response output: output: OUTPUT__1, type: FP32, shape: [64,384]
I0524 13:06:58.861898 1 http_server.cc:1226] HTTP: unable to provide 'OUTPUT__1' in GPU, will use CPU
I0524 13:06:58.861907 1 http_server.cc:1246] HTTP using buffer for: 'OUTPUT__1', size: 98304, addr: 0x7fb40e4f1b80
I0524 13:07:01.856685 1 http_server.cc:1261] HTTP release: size 25165824, addr 0x7fb4f1fff040
I0524 13:07:01.858047 1 http_server.cc:1261] HTTP release: size 98304, addr 0x7fb40e4f1b80
```

can you please let me know if something is wrong, model is loaded on GPU but inference time is slow , it seems it's using CPU

the following is my model config file

```
name: "multiqa_pr"
platform: "pytorch_libtorch"
max_batch_size: 64
input [
  {
    name: "INPUT__0"
    data_type: TYPE_INT32
    dims: [256]
  },
  {
    name: "INPUT__1"
    data_type: TYPE_INT32
    dims: [256 ]
  },
    {
    name: "INPUT__2"
    data_type: TYPE_INT32
    dims: [256 ]
  }
]
output [
  {
    name: "OUTPUT__0"
    data_type: TYPE_FP32
    dims: [ 256, 768 ]
  },
  {
    name: "OUTPUT__1"
    data_type: TYPE_FP32
    dims: [768 ]
  }
]
dynamic_batching {
    preferred_batch_size: [ 4, 8,16, 32, 64 ]
  }
instance_group [
    {
      count: 2
      kind: KIND_GPU
      gpus: [ 0 ]
    }
    ]
```

Thanks

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**
this should be executed under 400ms but overall time taken is more then 6s.

**Comment by bhupendrasalesken** [comment]
I found the solution as well 

eariler I was using :
```
output0 = tritonhttpclient.InferRequestedOutput("OUTPUT__0",  binary_data=False)
output1 = tritonhttpclient.InferRequestedOutput("OUTPUT__1",  binary_data=False)
```

but when I use 
```

output0 = tritonhttpclient.InferRequestedOutput("OUTPUT__0")
output1 = tritonhttpclient.InferRequestedOutput("OUTPUT__1")
```

It's finished under  244ms. Though not sure why :-| ?

**Comment by bhupendrasalesken** [comment]
it wasn't the warmup time , I tried it for a few times the time was still the same.

**Comment by dongteng** [comment]
> I found the solution as well
> 
> eariler I was using :
> 
> ```
> output0 = tritonhttpclient.InferRequestedOutput("OUTPUT__0",  binary_data=False)
> output1 = tritonhttpclient.InferRequestedOutput("OUTPUT__1",  binary_data=False)
> ```
> 
> but when I use
> 
> ```
> 
> output0 = tritonhttpclient.InferRequestedOutput("OUTPUT__0")
> output1 = tritonhttpclient.InferRequestedOutput("OUTPUT__1")
> ```
> 
> It's finished under 244ms. Though not sure why :-| ?
> 
> logs are still same ...

e ...in fact when i use
`output0 = tritonhttpclient.InferRequestedOutput("OUTPUT__0")
output1 = tritonhttpclient.InferRequestedOutput("OUTPUT__1")`
it will give an error
`2023-12-22 09:35:49,020] ERROR in app: Exception on /triton/v1/intent/recognition_batch [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "client_flask.py", line 203, in get_intent_similarity_batch
    batch_similarities = smtc.intent_model_infer_batch(model_name=model_name, model_version=model_version, query=query, candidates=batch_candidates)
  File "client_flask.py", line 96, in intent_model_infer_batch
    results = self.triton_client.infer(
  File "/usr/local/lib/python3.8/dist-packages/tritonclient/http/__init__.py", line 1420, in infer
    return InferResult(response, self._verbose)
  File "/usr/local/lib/python3.8/dist-packages/tritonclient/http/__init__.py", line 1974, in __init__
    self._result = json.loads(content)
rapidjson.JSONDecodeError: Parse error at offset 116: Invalid value.
`
I wonder why?Hope your answer

**Comment by romanvelichkin** [comment]
> I found the solution as well
> 
> eariler I was using :
> 
> ```
> output0 = tritonhttpclient.InferRequestedOutput("OUTPUT__0",  binary_data=False)
> output1 = tritonhttpclient.InferRequestedOutput("OUTPUT__1",  binary_data=False)
> ```
> 
> but when I use
> 
> ```
> 
> output0 = tritonhttpclient.InferRequestedOutput("OUTPUT__0")
> output1 = tritonhttpclient.InferRequestedOutput("OUTPUT__1")
> ```
> 
> It's finished under 244ms. Though not sure why :-| ?
> 
> logs are still same ...

Wow, you saved my time! I was trying to understand why inference on Triton is so slow. It worked for me too. 
Triton Server version: nvcr.io/nvidia/tritonserver:24.04-py3
