### ISSUE TITLE
run ci test fail

### ISSUE THREAD

**Issue by LucQueen** [triton-inference-server/server#4433]
I run test.sh in /server/qa/L0_backend_python/, and I meet this error. how can i fix it? thanks. 

======================================================================
ERROR: test_init_args (__main__.PythonTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./python_test.py", line 49, in setUp
    self._shm_leak_detector = shm_util.ShmLeakDetector()
  File "/workspace/qa/L0_backend_python/../common/shm_util.py", line 383, in __init__
    import triton_shm_monitor
ModuleNotFoundError: No module named 'triton_shm_monitor'

**Comment by nv-kmcgill53** [comment]
Hi @LucQueen, would you please provide more information about your issue following our [bug report template](https://github.com/triton-inference-server/server/blob/main/.github/ISSUE_TEMPLATE/bug_report.md)? This will help us in assisting you. Namely, the Triton information and the steps to reproduce will be helpful.

**Comment by Tabrizian** [comment]
You need to compile the `triton_shm_monitor` and place the produced artifact in the qa/common/shm_util.py. You can look at the QA container to see how you can build the triton_shm_monitor: https://github.com/triton-inference-server/server/blob/27018e614614cb9720e34aec8d5bdafdcdc4857f/Dockerfile.QA#L180-L186

**Comment by LucQueen** [comment]
thank you
