### ISSUE TITLE
WSL2 CUDA SHM support

### ISSUE THREAD

**Issue by bartengine27** [triton-inference-server/server#4436]
**Description**
Starting the Triton Server r22.04 docker and executing the simple_grpc_cudashm_client results in:

`
0 + 1 = 0  
0 + 1 = 0  
error: incorrect sum
`

The output of simple_grpc_infer_client looks correct:

`
0 + 1 = 1  
0 - 1 = -1  
1 + 1 = 2  
1 - 1 = 0  
2 + 1 = 3 ...
`

**Triton Information**
r22.04

Are you using the Triton container or did you build it yourself?

container

**To Reproduce**
Start the r22.04 container on WSL2 with:

`
sudo docker run --gpus all --rm --shm-size=1g --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 -p8000:8000 -p8001:8001 -p8002:8002 -v$(pwd)/docs/examples/model_repository:/models nvcr.io/nvidia/tritonserver:22.04-py3 tritonserver --model-repository=/models --strict-model-config=false --grpc-infer-allocation-pool-size=16 --log-verbose 1  
`

Download the client as documented on [clients](https://github.com/triton-inference-server/client), in this particular case, [clients tar](https://github.com/triton-inference-server/server/releases/download/v2.21.0/v2.21.0_ubuntu2004.clients.tar.gz). Extract the tar on WSL2, cd to bin and execute:

`
./simple_grpc_cudashm_client  
`

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

Models were downloaded with docs/examples/fetch_models.sh, all models, except simple were removed from the file system after the download.

**Expected behavior**

simple_grpc_cudashm_client And  simple_grpc_infer_client should have similar outputs.

**Comment by Tabrizian** [comment]
CUDA Shared memory is not supported on Windows yet.

**Comment by bartengine27** [comment]
Hi @Tabrizian 

  Thanks for the feedback!

  Not supported as in an WSL2 limitation or a Triton limitation?

Thanks,
Bart

**Comment by gunflame530** [comment]
@Tabrizian Hi
Is CUDA shared memory supported on Windows in the latest version of Triton?

**Comment by dyastremsky** [comment]
It is not.

From the [release notes, under "Windows Support"](https://github.com/triton-inference-server/server/releases):
`System and CUDA shared memory are not supported.`
