### ISSUE TITLE
[Question] Reducing payload size

### ISSUE THREAD

**Issue by austinmw** [triton-inference-server/server#4443]
Hi, I'm using Triton on SageMaker, and I have a payload size limit of 5MiB. This prevents me from sending high-res individual images, or large batches of medium size images.

I'd like to understand if there's a more optimized way to form my payload to reduce it's size. Maybe I could use jpeg compression or change my model somehow to support TYPE_FP16 input type? The fact that I'm just sending the payload batch as a list of FP32 arrays seems very large and inefficient (this is what the SageMaker Triton example demonstrated).

Here's my current way of forming a payload:

```python
import tritonclient.http as httpclient
import numpy as np
from PIL import Image


# Example of sending a batch of 4 640x640 images
sample_batch_size = 4
width = 640
height = 640

# Create a batch
def get_sample_image():
    image_path = './sample.jpg'
    img = Image.open(image_path).convert('RGB')
    img = img.resize((width, height))    
    img = np.transpose(img, (2, 0, 1))
    img = np.stack([img]*sample_batch_size, axis=0)
    return img.tolist()


# convert inference request into a binary format
def _get_sample_image_binary(input_name: str, output_names: list):
    inputs = []
    outputs = []
    inputs.append(httpclient.InferInput(input_name, [sample_batch_size, 3, height, width], 'FP16'))
    #input_data = np.array(get_sample_image(), dtype=np.float32)
    
    input_data = np.array(get_sample_image(), dtype=np.float16)
    
    inputs[0].set_data_from_numpy(input_data, binary_data=True)
    
    for output_name in output_names:
        outputs.append(httpclient.InferRequestedOutput(output_name, binary_data=True))

    request_body, header_length = httpclient.InferenceServerClient.generate_request_body(
        inputs, outputs=outputs
    )
    return request_body, header_length


def get_sample_image_binary_trt():
    return _get_sample_image_binary('input', ['dets', 'labels'])


request_body, header_length = get_sample_image_binary_trt()


# Sending the payload to the server
response = runtime_sm_client.invoke_endpoint(
    EndpointName=endpoint_name,
    ContentType="application/vnd.sagemaker-triton.binary+json;json-header-size={}".format(
        header_length
    ),
    Body=request_body,
)
```

Any suggestions for fitting larger payloads would be greatly appreciated!

**Comment by austinmw** [comment]
After reading more docs, I think I need to use Triton ensemble with DALI preprocessing.

**Comment by GuanLuo** [comment]
The payload size depends on the input tensor that the model is expecting, so yes you may create an ensemble so that you can send compressed input to workaround the payload size limit and then perform the preprocess within Triton to restore the input tensor. Another way is to send the request in smaller batch size.

**Comment by Glucosquidic** [comment]
> Hi, I'm using Triton on SageMaker, and I have a payload size limit of 5MiB. This prevents me from sending high-res individual images, or large batches of medium size images.
> 
> I'd like to understand if there's a more optimized way to form my payload to reduce it's size. Maybe I could use jpeg compression or change my model somehow to support TYPE_FP16 input type? The fact that I'm just sending the payload batch as a list of FP32 arrays seems very large and inefficient (this is what the SageMaker Triton example demonstrated).
> 
> Here's my current way of forming a payload:
> 
> ```python
> import tritonclient.http as httpclient
> import numpy as np
> from PIL import Image
> 
> 
> # Example of sending a batch of 4 640x640 images
> sample_batch_size = 4
> width = 640
> height = 640
> 
> # Create a batch
> def get_sample_image():
>     image_path = './sample.jpg'
>     img = Image.open(image_path).convert('RGB')
>     img = img.resize((width, height))    
>     img = np.transpose(img, (2, 0, 1))
>     img = np.stack([img]*sample_batch_size, axis=0)
>     return img.tolist()
> 
> 
> # convert inference request into a binary format
> def _get_sample_image_binary(input_name: str, output_names: list):
>     inputs = []
>     outputs = []
>     inputs.append(httpclient.InferInput(input_name, [sample_batch_size, 3, height, width], 'FP16'))
>     #input_data = np.array(get_sample_image(), dtype=np.float32)
>     
>     input_data = np.array(get_sample_image(), dtype=np.float16)
>     
>     inputs[0].set_data_from_numpy(input_data, binary_data=True)
>     
>     for output_name in output_names:
>         outputs.append(httpclient.InferRequestedOutput(output_name, binary_data=True))
> 
>     request_body, header_length = httpclient.InferenceServerClient.generate_request_body(
>         inputs, outputs=outputs
>     )
>     return request_body, header_length
> 
> 
> def get_sample_image_binary_trt():
>     return _get_sample_image_binary('input', ['dets', 'labels'])
> 
> 
> request_body, header_length = get_sample_image_binary_trt()
> 
> 
> # Sending the payload to the server
> response = runtime_sm_client.invoke_endpoint(
>     EndpointName=endpoint_name,
>     ContentType="application/vnd.sagemaker-triton.binary+json;json-header-size={}".format(
>         header_length
>     ),
>     Body=request_body,
> )
> ```
> 
> Any suggestions for fitting larger payloads would be greatly appreciated!



> After reading more docs, I think I need to use Triton ensemble with DALI preprocessing to send a UINT8 JPEG.

Hi. This is a longshot, but do you have any references to provide regarding incorporating DALI into an AWS-managed Triton Server image? Did you simply add an entry point script to the endpoint? I am currently running into a similar issue that you faced, a 37KB image results in a 4MB payload.
