### ISSUE TITLE
Tritonclient cushm on multi-gpu server

### ISSUE THREAD

**Issue by haritsahm** [triton-inference-server/server#4448]
I have used tritonclient with grpc+cushm for a single gpu server, now i'm planning to scale the server with multiple gpus. When creating the [create_shared_memory_region](https://github.com/triton-inference-server/client/blob/efd1cbe0cca60e750aed395c78b3ee5c90139add/src/python/library/tritonclient/utils/cuda_shared_memory/__init__.py#L97), I have to set the `device_id`. If I have multiple system running tritonclient, do I have to set manually the `device_id` on each tritonclient? Is there a way to use cushm without setting the `device_id`?

**Comment by GuanLuo** [comment]
You will need to set the device ID, in multi-GPU environment, it is used to identify which physical device the CUDA shared memory region is located in.

What is the reason that you don't / can't set the device ID? To use CUDA shared memory, I believe the client should know the characteristic of the shared memory which includes the device ID.

**Comment by haritsahm** [comment]
Ah I see, so I have to manually set the device Id. I set the `device_id` to 0 by default, but when I have multiple gpus then I have to set each client to the appropriate device id. I hope that it could automatically set the device id when I wanted to scale or replicate my app to use tritonclient/tritonserver without setting the device id.
