### ISSUE TITLE
Question: support complex model out data struct (List[Dict[str, Tensor]])?

### ISSUE THREAD

**Issue by Phelan164** [triton-inference-server/server#4452]
**Is your feature request related to a problem? Please describe.**

I am trying to make model keypoints detection from Detectron2 running on the Triton server.
The issue is: output of model is quite complex `List[Dict[str, Tensor]]`

Does the Triton inference server support that?
If yes, any example to make config.pbtxt for this case?

**Comment by Phelan164** [comment]
@dyastremsky 
>Which backend is this for?
it is pytorch backend (platform: "pytorch_libtorch")

**Comment by dyastremsky** [comment]
The PyTorch backend supports having up to one input that is a dictionary of tensors, see here: https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#special-conventions-for-pytorch-backend

You'll need to update the output of the model itself unless you write a custom backend. The workaround offered here would be a good starting point for converting a list to individual outputs: https://github.com/triton-inference-server/server/issues/4432#issuecomment-1138882128. However, your case will be more complicated, as we currently only support 0-1 inputs that are dictionaries of strings to tensors.

I'll close this ticket. Please reopen it if you would like to follow up.
