### ISSUE TITLE
"POST v2/repository/models/${MODEL_NAME}/load" failed on 22.05 but works fine on 21.08

### ISSUE THREAD

**Issue by NonStatic2014** [triton-inference-server/server#4453]
**Description**
I used triton to create a service locally with command below: 

```
tritonserver --model-repository=/host/models/ --strict-model-config=false --model-control-mode "explicit" --load-model fashion --load-model densenet --load-model bidaf-9
```

Both 22.05 and 21.08 can load the model.

Then i try to unload the model "fashion" with 

```
curl -X POST http://127.0.0.1:8000/v2/repository/models/fashion/unload -v
```

Both 22.05 and 21.08 can unload the model. Using `curl -X POST http://127.0.0.1:8000/v2/repository/index -v` verified.

Then try to load the fashion mode back with below json. It works fine on 21.08 but failed on 22.05.

```
curl -X POST -d @"fashion_load.json" http://127.0.0.1:8000/v2/repository/models/fashion/load -v
```

```json
{
  "parameters": {
    "config": {
      "name": "fashion",
      "versions": [
        1
      ],
      "platform": "tensorflow_savedmodel",
      "inputs": [{
          "name": "Conv1_input",
          "datatype": "FP32",
          "shape": [
            -1,
            28,
            28,
            1
          ]
        }
      ],
      "outputs": [{
          "name": "Dense",
          "datatype": "FP32",
          "shape": [
            -1,
            10
          ]
        }
      ]
    },
    "file": "1/saved_model.pb"
  }
}

```

The error message is

```
{"error":"attempt to access JSON non-string as string"}
```

I also tried if load the model without the json payload, since the file name is default name, it can be loaded and scoring can work.

**Triton Information**
triton image: 22.05
triton version: 2.22.0

Are you using the Triton container or did you build it yourself? -> container

**To Reproduce**
See above

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**
22.05 can load the model as what we see on 21.08.

**Comment by NonStatic2014** [comment]
Would you mind update below documents to mention which triton version or triton image version we should use?
* https://github.com/triton-inference-server/server/blob/main/docs/model_management.md
* https://github.com/triton-inference-server/server/blob/main/docs/protocol/extension_model_repository.md

I'm also looking for a real sample like what I mentioned the issue in the second link above. That will be very helpful for the first time user. Thanks!

**Comment by NonStatic2014** [comment]
The `test coverage` is using triton sdk. Do we have any sample using REST API directly?

**Comment by GuanLuo** [comment]
Not yet, but the [comment ](https://github.com/triton-inference-server/server/issues/4453#issuecomment-1144095626)I mentioned earlier should help with the issue that you are facing. Can you verify it?

**Comment by NonStatic2014** [comment]
Thank you @GuanLuo ! Update the config can make it through in the latest image.

Moving forward, can we add something like "new from 22.01" in the first line of the doc?

![image](https://user-images.githubusercontent.com/9442504/172269919-4bcc1470-0f86-4681-a3fa-c991239317d9.png)

**Comment by zengqingfu1442** [comment]
I still come across the same error message on triton 2.39.0. I use postman to launch the post requst,
![image](https://github.com/triton-inference-server/server/assets/14928378/b8a05783-61f9-48cd-ad07-be807719f5de)

**Comment by zengqingfu1442** [comment]
> Note that for "config", the value should be a string as described [here](https://github.com/triton-inference-server/server/blob/main/docs/protocol/extension_model_repository.md#load), can you double quote the actual configuration (may need to escape `"` within the config as well), i.e. `"config" : "{...}"`
> 
> Another note is that the feature to provide config via load API is available since 22.03, and it is optional. So the above load invocation in 21.08 is actually loading the model with pre-existing model config (the request body is ignored), the equivalent in 22.05 is simply invoking the API with empty request body

I tried to double quote the actual configuration but still failed with another error:

![image](https://github.com/triton-inference-server/server/assets/14928378/601f35ca-5b49-4644-b3ef-b34c531d5a58)

**Comment by Manikandan-t** [comment]
Hi @zengqingfu1442 Try with Escaping double quotes of config json similar to this
![Screenshot from 2024-01-23 13-46-11](https://github.com/triton-inference-server/server/assets/82821281/f11cc3a6-abfd-4634-912d-88dcde9668bf)

**Comment by zengqingfu1442** [comment]
> Hi @zengqingfu1442 Try with Escaping double quotes of config json similar to this ![Screenshot from 2024-01-23 13-46-11](https://private-user-images.githubusercontent.com/82821281/298908212-f11cc3a6-abfd-4634-912d-88dcde9668bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMDg0MTUsIm5iZiI6MTcxMTAwODExNSwicGF0aCI6Ii84MjgyMTI4MS8yOTg5MDgyMTItZjExY2MzYTYtYWJmZC00NjM0LTkxMmQtODhkY2RlOTY2OGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDA4MDE1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyNzJlMWE0ZjFlMzZkMTVjYmY0Y2JiMWM1NzdmZGEyZWVjOTIyYTMwZTIwMWI2MWUzZjBlNTQyNjQyNjY2MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N-0w6wHkZmn25NFGpmMnZGRteTUenFlyA95nnFLEQYQ)

Thanks a lot.
