### ISSUE TITLE
run ci test fail

### ISSUE THREAD

**Issue by LucQueen** [triton-inference-server/server#4480]
when I run qa test follow with https://github.com/triton-inference-server/server/blob/main/docs/test.md

docker run --gpus=all -it --rm -v/tmp:/data/inferenceserver tritonserver_qa
cd /opt/tritonserver/qa/L0_libtorch_nvfuser
bash -x ./test.sh 22.04

and I got the error about can not find 

cp: cannot stat '/data/inferenceserver/22.04/libtorch_model_store/resnet50_libtorch': No such file or directory

can someone tell me the reason, thank you very much!

**Comment by dyastremsky** [comment]
We'll likely need to update that documentation. Some tests require internal models that we have not made public, and I believe resnet50_libtorch is one such model. As a result, the QA can be helpful in validating your builds, but not all of the tests can be run by users.
