### ISSUE TITLE
how to debug the model file when use python backend

### ISSUE THREAD

**Issue by yuxianmin** [triton-inference-server/server#4481]
I want to debug whether the code logic in model.py is correct, and I need to output some variables in it, which cannot be displayed on the console after printing. Is there any way to debug? thanks

**Comment by yuxianmin** [comment]
oh, this solves it,  thanks!

**Comment by Jackiexiao** [comment]
FYI: If you want to print japanese/chinese character, you should set  `export PYTHONIOENCODING=UTF-8 `

**Comment by LiberiFatali** [comment]
> Have you tried using `print('Your Error Message', flush=True)`?

I tried this. It doesn't work. Any other recommendation (such as proper logging class)?

**Comment by LiberiFatali** [comment]
Ok, we can use logger like this:  https://github.com/triton-inference-server/server/blob/main/qa/python_models/identity_fp32_logging/model.py

**Comment by TheCodeWrangler** [comment]
If i have call a function which contains log messages using python logging is there a way to have those logs show up in triton python backend?

Any way to set a logging context in the model.py file for triton which results in python's logging  to be routed to that logger?
