### ISSUE TITLE
openvino backend 2022

### ISSUE THREAD

**Issue by wanduoz** [triton-inference-server/server#4486]
I build triton server with docker. The version of tritonserver is 2.20.0. I want to add ov2022 backend into tritonserver so that I can use models converted by ov2022 runtime. I find ov2021 backend at /opt/tritonserver/backends directory.
![image](https://user-images.githubusercontent.com/33130310/172558141-1ca50954-577a-4535-9def-c5eb791f5b65.png)

Can I add ov2022 backend and how? I find an issue about same question but I don't want to build container from scratch. Can I compile backend inside container and simply copy fold to /opt/tritonserver/backends directory? 

The last question is when the official triton container with ov2022 backend supported release?

**Comment by tanmayv25** [comment]
@wanduoz  looks like you already have encountered my response from 
https://github.com/triton-inference-server/server/issues/4262.

 > I find an issue about same question but I don't want to build container from scratch. Can I compile backend inside container and simply copy fold to /opt/tritonserver/backends directory?
 
 You can definitely build your own openvino backend with 2022 version using cmake. Use [TRITON_BUILD_OPENVINO_COMMIT_SHA](https://github.com/triton-inference-server/openvino_backend/blob/main/CMakeLists.txt#L48)  to provide the commit sha of ov2022. 
 
  We don't support ov2022 yet so you may run into problems. 
  
 > The last question is when the official triton container with ov2022 backend supported release?
 
 Because of the issue described [here](https://github.com/triton-inference-server/server/blob/main/build.py#L67-L70) we need to match openvino versions in standalone and ONNXRuntime variant. Apparently, the general ONNXRT version does not yet support ov2022. See [here](https://github.com/triton-inference-server/server/pull/4169#issuecomment-1108874518) for more details. 
 
 We will move to the latest versions on OV as soon as it is supported in the version of ONNXRT that we use. Unfortunately it is not supported in ONNXRT 1.11.0.

**Comment by wanduoz** [comment]
OK, there are some network problems in my computer and I would rather focus on tensorrt. Thank you!

**Comment by tanmayv25** [comment]
Closing the ticket for now. Keep an eye out for release notes on when we move to OV 2022

**Comment by zhaohb** [comment]
@tanmayv25  I am compile openvino 2022.1 , this is my command:
```shell
 cmake -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/install -DTRITON_BUILD_OPENVINO_COMMIT_SHA=ad1c879a03de10635e12261ffbf2a1663bcd0189 -DTRITON_BUILD_CONTAINER_VERSION=22.05 ..
```
output:
```shell
...
#14 12.54 -- Looking for CL_VERSION_1_0
#14 12.58 -- Looking for CL_VERSION_1_0 - not found
#14 12.58 -- Could NOT find OpenCL (missing: OpenCL_LIBRARY OpenCL_INCLUDE_DIR)
#14 12.66 -- Register template_plugin to be built in build-modules/template_plugin
#14 12.69 CMake Warning at model-optimizer/CMakeLists.txt:5 (message):
#14 12.69   Please enable IE & nGraph Python API (ie_api and
#14 12.69   offline_transformations_api) targets to enable Model Optimizer target
#14 12.69
#14 12.69
#14 12.72 CMake Warning at cmake/developer_package/shellcheck/shellcheck.cmake:11 (message):
#14 12.72   shellcheck tool is not found
#14 12.72 Call Stack (most recent call first):
#14 12.72   scripts/CMakeLists.txt:9 (ie_shellcheck_process)
#14 12.72
#14 12.72
#14 12.77 -- Configuring done
#14 13.60 -- Generating done
#14 13.63 CMake Warning:
#14 13.63   Manually-specified variables were not used by the project:
#14 13.63
#14 13.63     ENABLE_DLIA
#14 13.63     ENABLE_INTEL_MYRIAD
#14 13.63     ENABLE_VALIDATION_SET
#14 13.63     NGRAPH_DEPRECATED_ENABLE
#14 13.63     NGRAPH_ONNX_IMPORT_ENABLE
#14 13.63
#14 13.63
#14 13.63 -- Build files have been written to: /workspace/openvino/build
#14 13.67 ls: cannot access '/workspace/openvino/temp/opencv_4*': No such file or directory
------
executor failed running [/bin/sh -c /bin/bash -c 'cmake         -DCMAKE_BUILD_TYPE=${OPENVINO_BUILD_TYPE}         -DCMAKE_INSTALL_PREFIX=/workspace/install         -DENABLE_VPU=OFF         -DENABLE_CLDNN=OFF         -DTHREADING=OMP         -DENABLE_GNA=OFF         -DENABLE_DLIA=OFF         -DENABLE_TESTS=OFF         -DENABLE_INTEL_MYRIAD=OFF         -DENABLE_VALIDATION_SET=OFF         -DNGRAPH_ONNX_IMPORT_ENABLE=OFF         -DNGRAPH_DEPRECATED_ENABLE=FALSE         .. &&     TEMPCV_DIR=/workspace/openvino/temp/opencv_4* &&     OPENCV_DIRS=$(ls -d -1 ${TEMPCV_DIR}) &&     export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${OPENCV_DIRS[0]}/opencv/lib &&     make -j$(nproc) install']: exit code: 2
make[2]: *** [CMakeFiles/ov_target.dir/build.make:74: openvino/lib/openvino.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:174: CMakeFiles/ov_target.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
...
```

how to fix that? thank you.

**Comment by tanmayv25** [comment]
Looks like the path of opencv_4* has changed in the commit that you are trying to use. 
You can look for the opencv_* path in your build and change the path here:
https://github.com/triton-inference-server/openvino_backend/blob/main/tools/gen_openvino_dockerfile.py#L178

FYI: we will soon move the openvino version to 2022.1

**Comment by zhaohb** [comment]
@tanmayv25 I'm very glad to hear this news. But when will ov 2022.1 be released, 22.07?

**Comment by tanmayv25** [comment]
@zhaohb  Unfortunately, no. We don't have timeline as of yet, but with ORT 1.12.0, we can move to OV 2022.1

**Comment by zhaohb** [comment]
@tanmayv25 A bit disappointed. 
I think just setting TRITON_BUILD_OPENVINO_COMMIT_SHA to 2022.1 does not seem to guarantee that OV 2022.1 can be used, the interfaces in openvino_backend should also use the 2022.1 api. right?
Another question: Is there an interdependence between openVino backend and onnxruntime backend?
if I want let triton support ov 2022.1, what I need to do？
thank you very much.

**Comment by tanmayv25** [comment]
> I think just setting TRITON_BUILD_OPENVINO_COMMIT_SHA to 2022.1 does not seem to guarantee that OV 2022.1 can be used, the interfaces in openvino_backend should also use the 2022.1 api. right?

We had been able to build internally with the 2022.1 OV in the past. I think TRITON_BUILD_OPENVINO_COMMIT_SHA=f2f281e60b20
This was well after their release. I don't think they should have modified API after OV 2022.1 release.

**Comment by zhaohb** [comment]
@tanmayv25 Yes, openvino 2022.1 is compatible with some 2021.4 api, but the add_extension api is not compatible. The implementation of the custom operator of openvino 2022.1 has been modified. using the old interface, the custom operator cannot be successfully loaded. So now I am updating the API of openIvno backend with ov 2022.1.
