### ISSUE TITLE
Is there a good solution for video streaming? For example, RTSP and RTMP

### ISSUE THREAD

**Issue by yangyangyang0110** [triton-inference-server/server#4487]
Hello, 

For video streaming, how should this c/s architecture program transmit data, and where should the decoder be placed?

@tanmayv25

**Comment by tanmayv25** [comment]
[Nvidia DeepStream](https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_Quickstart.html#deepstream-triton-inference-server-usage-guidelines) is indeed our recommendation for video streaming workloads. Let us know if you have any question.

**Comment by yangyangyang0110** [comment]
thank, you,
