### ISSUE TITLE
Triton server stops while making Async request from multiple threads

### ISSUE THREAD

**Issue by InfiniteLife** [triton-inference-server/server#4491]
Whenever I make inference request from 2 threads with `AsyncInfer`, after like 16-20 requests I get error from client:

```
Socket closed

Inference unsuccessful Connection reset by peer
inference  failed with error: Connection reset by peer
Segmentation fault (core dumped)
```

and Triton server is also closes:

```
terminate called after throwing an instance of 'c10::ValueError'
  what():  Specified device cuda:0 does not match device of data cuda:-2
Exception raised from make_tensor at /opt/pytorch/pytorch/build/aten/src/ATen/Functions.cpp:24 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x6c (0x7f9954f71ecc in /opt/tritonserver/backends/pytorch/libc10.so)
frame #1: <unknown function> + 0xa7474f (0x7f998c74b74f in /opt/tritonserver/backends/pytorch/libtorch_cpu.so)
frame #2: <unknown function> + 0x1c787 (0x7f9995ba5787 in /opt/tritonserver/backends/pytorch/libtriton_pytorch.so)
frame #3: <unknown function> + 0x20386 (0x7f9995ba9386 in /opt/tritonserver/backends/pytorch/libtriton_pytorch.so)
frame #4: TRITONBACKEND_ModelInstanceExecute + 0x38a (0x7f9995bab4aa in /opt/tritonserver/backends/pytorch/libtriton_pytorch.so)
frame #5: <unknown function> + 0x31207a (0x7f9997aed07a in /opt/tritonserver/bin/../lib/libtritonserver.so)
frame #6: <unknown function> + 0x312797 (0x7f9997aed797 in /opt/tritonserver/bin/../lib/libtritonserver.so)
frame #7: <unknown function> + 0x1a5221 (0x7f9997980221 in /opt/tritonserver/bin/../lib/libtritonserver.so)
frame #8: <unknown function> + 0x30c607 (0x7f9997ae7607 in /opt/tritonserver/bin/../lib/libtritonserver.so)
frame #9: <unknown function> + 0xd6de4 (0x7f9997331de4 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #10: <unknown function> + 0x8609 (0x7f99977ae609 in /usr/lib/x86_64-linux-gnu/libpthread.so.0)
frame #11: clone + 0x43 (0x7f999701c163 in /usr/lib/x86_64-linux-gnu/libc.so.6)

Signal (6) received.
 0# 0x000055DC36B10549 in tritonserver
 1# 0x00007F9996F400C0 in /usr/lib/x86_64-linux-gnu/libc.so.6
 2# gsignal in /usr/lib/x86_64-linux-gnu/libc.so.6
 3# abort in /usr/lib/x86_64-linux-gnu/libc.so.6
 4# 0x00007F99972F9911 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 5# 0x00007F999730538C in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 6# 0x00007F99973053F7 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 7# 0x00007F99973056A9 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 8# 0x00007F998C74B78F in /opt/tritonserver/backends/pytorch/libtorch_cpu.so
 9# 0x00007F9995BA5787 in /opt/tritonserver/backends/pytorch/libtriton_pytorch.so
10# 0x00007F9995BA9386 in /opt/tritonserver/backends/pytorch/libtriton_pytorch.so
11# TRITONBACKEND_ModelInstanceExecute in /opt/tritonserver/backends/pytorch/libtriton_pytorch.so
12# 0x00007F9997AED07A in /opt/tritonserver/bin/../lib/libtritonserver.so
13# 0x00007F9997AED797 in /opt/tritonserver/bin/../lib/libtritonserver.so
14# 0x00007F9997980221 in /opt/tritonserver/bin/../lib/libtritonserver.so
15# 0x00007F9997AE7607 in /opt/tritonserver/bin/../lib/libtritonserver.so
16# 0x00007F9997331DE4 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
17# 0x00007F99977AE609 in /usr/lib/x86_64-linux-gnu/libpthread.so.0
18# clone in /usr/lib/x86_64-linux-gnu/libc.so.6

Signal (11) received.
 0# 0x000055DC36B10549 in tritonserver
 1# 0x00007F9996F400C0 in /usr/lib/x86_64-linux-gnu/libc.so.6
 2# abort in /usr/lib/x86_64-linux-gnu/libc.so.6
 3# 0x00007F99972F9911 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 4# 0x00007F999730538C in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 5# 0x00007F99973053F7 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 6# 0x00007F99973056A9 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 7# 0x00007F998C74B78F in /opt/tritonserver/backends/pytorch/libtorch_cpu.so
 8# 0x00007F9995BA5787 in /opt/tritonserver/backends/pytorch/libtriton_pytorch.so
 9# 0x00007F9995BA9386 in /opt/tritonserver/backends/pytorch/libtriton_pytorch.so
10# TRITONBACKEND_ModelInstanceExecute in /opt/tritonserver/backends/pytorch/libtriton_pytorch.so
11# 0x00007F9997AED07A in /opt/tritonserver/bin/../lib/libtritonserver.so
12# 0x00007F9997AED797 in /opt/tritonserver/bin/../lib/libtritonserver.so
13# 0x00007F9997980221 in /opt/tritonserver/bin/../lib/libtritonserver.so
14# 0x00007F9997AE7607 in /opt/tritonserver/bin/../lib/libtritonserver.so
15# 0x00007F9997331DE4 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
16# 0x00007F99977AE609 in /usr/lib/x86_64-linux-gnu/libpthread.so.0
17# clone in /usr/lib/x86_64-linux-gnu/libc.so.6
```

It works fine if I make inference request from one thread.
Model that is supposed to make inference is torchscript with `max_batch_size 128`, placed on 2 GPUs.

**Comment by tanmayv25** [comment]
@InfiniteLife  What is the version of Triton that you are using?
We fixed pytorch backend to use tensor device instead of model device in 22.02. 

> Specified device cuda:0 does not match device of data cuda:-2

With the error message it looks like an issue with gpu device indexing. I am not sure what cuda:-2 maps to though.

> Model that is supposed to make inference is torchscript with max_batch_size 128, placed on 2 GPUs.

Does that mean an instance of the model on both the GPUs? Can you try with a single GPU and let us know if you run into similar error?

**Comment by InfiniteLife** [comment]
I think I found reason related to error.

I was creating input with shape **128x3x256x256**, where **128** is also max_batch_size of torchscript model:

`tc::Error err = tc::InferInput::Create(&input_images, input_names[0], input_images_size, input_datatype[0]);`

But I was filling this input with `AppendRaw()` only partially, adding like from 3 to 20 input samples, whereas inference on Triton side happened on batch size of 128 anyways(seen that in log). I do not know what is in that memory that was not initialized by my code, that was causing the error. But Im not sure that it is uninitialized memory that caused error, because it was working with 1 thread, but was failing with 2 threads? May be it is big batch size(Im going to check that feeding dummy input), so I want to feel safe scaling up inference and not worry it is big batch size(tops 9 Gb of gpu memory were used out of 24 gb).

**Comment by InfiniteLife** [comment]
Im doing the same with Tensorrt model, creating fixed input size(32), because my trt model only support fixed batch dimension, but I do not always have enough data to fill batch dimension, so I fill input only partially. But trt model never behaved this way.

**Comment by InfiniteLife** [comment]
No, I was wrong, error isnt gone. Triton server keeps crashing.

**Comment by tanmayv25** [comment]
@InfiniteLife  Is it possible for you to share your model and detailed reproduction steps so that we can triage the issue on our side?

**Comment by InfiniteLife** [comment]
I just found the error. Took me way too much time to do it for a simple mistake on my side as this. Occasionally from 1 of the camera sources after previous network processing I received  0 data to do inference, it only happened in mutli-thread environment because that camera source only got in the processing pull if there were enough workers(debugging setup).

So because of this I was passing vector shape into `tc::InferInput::Create()` with data `0,3,256,256`. Input was successfully created(I am checking returned error state) and `std::vector<std::vector<uint8_t>>` with all vectors of size `0` were passed to `AppendRaw()`. And `AsyncInfer()` have been made, all returned error objects are good at this point. And when Torchscript actually was getting to work, it crashed Triton server with C10 exception.

This behavior was so weird that I was checking all the complicated stuff, but I guess I learnt a lot while was looking for this bug. But eventually it was just silly mistake, me forgetting to check data shape. 

Thank you for replies! Will close issue now.
