### ISSUE TITLE
Multiple models in Triton

### ISSUE THREAD

**Issue by Pelps12** [triton-inference-server/server#4502]
Is it possible to have models that pass their output to another model without have to do two separate API requests?

**Comment by tanmayv25** [comment]
Yes. Read about ensemble model executions here: https://github.com/triton-inference-server/server/blob/main/docs/architecture.md#ensemble-models

**Comment by Pelps12** [comment]
Is it possible to do business level scripting with tensorflow?

**Comment by tanmayv25** [comment]
You can write a custom backend that can issue inferences to tensorflow models loaded in Triton. 
We are working on an example and will share soon.
