### ISSUE TITLE
Warm up by sending multiple requests

### ISSUE THREAD

**Issue by hanwgyu** [triton-inference-server/server#4503]
Currently, there isn't an option for setting the request count of warm up.

Even after setting warm up, there is a spike when a new server starts.
I think the server needs to receive requests multiple times to warm up enough. 

<img width="1890" alt="eebea755-1829-47ca-b1fe-e6e26c92f9f1" src="https://user-images.githubusercontent.com/22293149/172804454-c567d4cc-07d3-439d-9e2b-8487d417eca9.png">

Is there a way to do it?

**Comment by hanwgyu** [comment]
+) Without dynamic batching, it worked well with only 1 request warm up.

But, when I applied dynamic batching,  warm up doesn't work well as above.

**Comment by hanwgyu** [comment]
@dyastremsky I tried with batch_size 1 and also maximum value 50 but it was same.
I guess It needs multiple requests for each batch_size.

**Comment by dyastremsky** [comment]
Looking at the [code](https://github.com/triton-inference-server/core/blob/main/src/backend_model_instance.cc#L433-L435), the batch size corresponds with the number of requests sent. So modifying batch_size would be the correct way to do it. However, each request is identical.

Are you sure the spike you're seeing isn't the server waiting for more requests to batch them before responding? Have you tried configuring some of the dynamic batcher options like batch delay? https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#dynamic-batcher

(CC'ing @Tabrizian, in case there's something unique to the dynamic batcher that he's more familiar with.)

**Comment by GuanLuo** [comment]
Please take a look at https://github.com/triton-inference-server/server/pull/4501 for usage of the new "count" field
