### ISSUE TITLE
AttributeError: 'python backend utils.Inference Request' object has no attribute 'as_numpy'

### ISSUE THREAD

**Issue by ArunMathewML** [triton-inference-server/server#4506]
AttributeError: 'python backend utils.Inference Request' object has no attribute 'as_numpy'

**Comment by Tabrizian** [comment]
Inference Request object doesn't have `as_numpy` method. Only pb_utils.Tensor object has `as_numpy`. Follow the quick start and Python backend documentation for more info: https://github.com/triton-inference-server/python_backend#quick-start
