### ISSUE TITLE
On custom config and accessing other models config on python backend

### ISSUE THREAD

**Issue by NotAnyMike** [triton-inference-server/server#4508]
I have few questions on the same topic: How to access configs from python backend

1. How can I get the info on the configuration of the models loaded in the server from the initialise function of a python backend model? I especially need to access other models' config, I know some information can be retrieved using tritonclient.grpc for example but I don't know if that is the best way of doing it while models initialise as well. 

2. I was also looking into the service_pb2 (from tritonclient.grpc import service_pb2) to see if I was able to find something useful but I was not able to find the source code, can you point me where can I find it?

3. I was considering using some custom fields in the parameters key of the config.pbtxt file, but the only way to do it is in the form 
 
```
    {
      key: "custom_key",
      value: {string_value: "custom value"}
    },
```
is there a less cumbersome way of adding custom config? which supports other types apart from `string_value` (e.g. lists of int)?

**Comment by Tabrizian** [comment]
1. You can access the model configuration using the `args['model_config']` parameter of the initialize function.
2. That is the GRPC protobuf and is not the model configuration protobofu. For model configuration protobuf, you need to import  `tritonclient.grpc import model_config_pb2`. You can also refer to [the model config protobuf](https://github.com/triton-inference-server/common/blob/main/protobuf/model_config.proto) for list of all supported parameters.
3. Unfortunately, that is the only way for specifying custom model configuration fields for now. You can workaround this by converting the string to your other type. (e.g. specifying a comma delimited list string for supporting lists of int).

**Comment by fran6co** [comment]
@Tabrizian is there a way to access another model config inside the `model.py`? For example I have a tensorrt model that I'm going to use inside a python backed model and I want to access the inputs and outputs of that model from inside python
