### ISSUE TITLE
perf_analyzer and perf_client don't have 'x' permission after pip install tritonclient(2.22.3)

### ISSUE THREAD

**Issue by EmmaQiaoCh** [triton-inference-server/server#4511]
**Description**
After pip install tritonclient[all], found /usr/local/bin/perf_analyzer and /usr/local/bin/perf_client don't have execute permission

**Triton Information**
tritonclient[all] version is 2.22.3

Are you using the Triton container or did you build it yourself?
I use the triton container, image is nvcr.io/nvidia/tritonserver:22.05-py3

**To Reproduce**
Steps to reproduce the behavior.
Pull and launch the triton image, then in the container execute: pip install tritonclient[all]
After that, when execute perf_analyzer, meet this error: /usr/local/bin/perf_analyzer: Permission denied
and ls the file permission:
-rw-r--r-- 1 root root 12974760 Jun 14 02:04 perf_analyzer
-rw-r--r-- 1 root root 12974760 Jun 14 02:04 perf_client
BTW, when uninstall tritonclient and re-install it with the version 2.22.0, no this permission issue.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**
After install tritonclient, the binary should have 'x' permission

**Comment by Tabrizian** [comment]
Hi @EmmaQiaoCh, Thanks for bringing this to our attention. I was able to reproduce this issue. I have filed a ticket to investigate this.

**Comment by Tabrizian** [comment]
@mattaltberg @EmmaQiaoCh This has been fixed in 2.22.4 patch. Let us know if you are still facing this issue.
