### ISSUE TITLE
add param for pytorch backend to specific get_method other than forward

### ISSUE THREAD

**Issue by Jackiexiao** [triton-inference-server/server#4513]
sometimes we want to use different "forward" function for a torchscript model

**Describe the solution you'd like**

in config.pbtxt, add pytorch option to change default get_method `forward` to other method

**Additional context**

Related code

https://github.com/triton-inference-server/pytorch_backend/blob/df900ce3d3c03e7f34ce1e9518c09cc2bad520a5/src/libtorch.cc#L690-L691

which is 
```
  const torch::jit::Method& method = torch_model_->get_method("forward");
  const auto& schema = method.function().getSchema();
  const std::vector<c10::Argument>& arguments = schema.arguments();
```

**Comment by Tabrizian** [comment]
@Jackiexiao Can you elaborate more on your use-case? Why not rename the function that performs inference to `forward`?

**Comment by Jackiexiao** [comment]
I have multi function in one model, sometimes I want intermediate result, sometimes I get result from one function, do some postprocessing to send to another function.

any other way to deal with it is to split one complex model to multi model, each has a `forward` function. but if we could just change parameter to decide which function we want to use in pytorch backend, it would be more convenient

**Comment by Jackiexiao** [comment]
it could help, but using python backend also means some performance penalty

**Comment by Jackiexiao** [comment]
I have rethink about it, this FR is not important, if I want to use another function instead of `forward`, just rename `forward` function, or split one complex model to multi model, each has a `forward` function.
