### ISSUE TITLE
How to use java client api  transfer  images and texts  to python backend?

### ISSUE THREAD

**Issue by wanghaohw** [triton-inference-server/server#4516]
Please give me an example.

**Comment by dyastremsky** [comment]
You'd run Triton server as you always do. There's no difference for the Python backend if using a specific client API, as loading it with the correct model config takes care of backend specifics.

Assuming you're referring to the Java API contributed by the Alibaba Cloud PAI Team, it includes a minimal example in the documentation plus [these three](https://github.com/triton-inference-server/client/tree/r21.09/src/java). The API is pretty minimal, so looking through the code could also be helpful. If your question is about adapting the code to images and text specifically, you can use the BYTES datatype found in [the DataType class](https://github.com/triton-inference-server/client/blob/r21.09/src/java/src/main/java/triton/client/pojo/DataType.java). You can set the data using [this function](https://github.com/triton-inference-server/client/blob/r21.09/src/java/src/main/java/triton/client/InferInput.java#L288-L301). For images, you'd need to read it and turn it into bytes (or a matrix of values) the same way you did when training the model.
