### ISSUE TITLE
Tritonserver hanging on startup

### ISSUE THREAD

**Issue by skiman6010** [triton-inference-server/server#4517]
**Description**
After building the tritonserver from source from either the r22.06 or r22.05 branch, the `tritonserver` command hangs with no verbose messages on start. Interestingly enough, if I ask it to load a model that does not exist with `--load-model=`, it will print an error on startup, but if the model does exist or if I do not specify one, it hangs.

**Triton Information**
NVIDIA Release 22.05 (build <unknown>)
Triton Server Version 2.22.0

OR 

NVIDIA Release 22.06 (build <unknown>)
Triton Server Version 2.23.0

Are you using the Triton container or did you build it yourself?

Built it myself from the build docs with the command

`python3 ./build.py -v  --backend onnxruntime --backend openvino`

**To Reproduce**
Steps to reproduce the behavior.

Open a shell in the built container and run `tritonserver --model-repository=/triton_home/models/triton/triton_repository --model-control-mode=explicit`

After that, the command will hang with no output or exit.

**Expected behavior**
The tritonserver to run or error out.

**Comment by GuanLuo** [comment]
I think by default the `build.py` will not enable many Triton features (including logging), so no logging may be mistaken as "hanging"? Can you try to build with `--enable-logging` (and other features that you want to enable) or to send a [health request](https://github.com/kserve/kserve/blob/master/docs/predict-api/v2/required_api.md#httprest) to verify if the server is running.

**Comment by skiman6010** [comment]
You are completely correct. I enabled logging, grpc, metrics, http as well and now everything is functioning correctly. Thank you for the help! I will close this issue, but I would also like to suggest rewriting the [docs/build.md](https://github.com/triton-inference-server/server/blob/main/docs/build.md) to be more clear about these feature flags.
