### ISSUE TITLE
what is raw_mug_data?

### ISSUE THREAD

**Issue by lhy2749** [triton-inference-server/server#4533]
how could i load or build `L0_warmup/raw_mug_data` with python?

**Comment by dyastremsky** [comment]
Raw_mug_data is the input data file expected by the inception_v3_graphdef model. If you look into how inception v3 expects images (or the specific model used in the QA test, if we have it publicly available), that may give more insight into how it's encoded or decoded. However, it's just an example we use for our testing. Your image input would be based on your model and workflow.

**Comment by Tabrizian** [comment]
Closing doing due in-activity.
