### ISSUE TITLE
Questions regarding the Rate Limiter

### ISSUE THREAD

**Issue by mhbassel** [triton-inference-server/server#4548]
Hello everyone! 

I have some pretty basic questions please regarding the rate limiter. Taking the example from the docs:
```
instance_group [
    {
      count: 1
      kind: KIND_GPU
      gpus: [ 0, 1, 2 ]
      rate_limiter {
        resources [
          {
            name: "R1"
            count: 4
          },
          {
            name: "R2"
            global: True
            count: 2
          }
        ]
        priority: 2
      }
    }
  ]
  ```
As mentioned in the docs about resources `count field refers to the number of copies of the resource that the model instance in the group requires to run`: 
* so this means each model instance needs 4 resources, correct? but how are those resources exactly measured?
* and are they the amount of GPU memory allocated (only from the 3 given GPUs) for each model instance? 

This might be very basic, but I just want to know how to set their values.

I will appreciate any help and thank you in advance

**Comment by dyastremsky** [comment]
Great question. A resource is determined by you (it's arbitrary, e.g. GPU memory). The scheduler has no concept of what the resource means or how to measure it; it just abides by the constraints you set. So it makes sure enough resources are available before scheduling a model.

A good explanation of this is available in this GitHub issue here: https://github.com/triton-inference-server/server/issues/3942#issuecomment-1043120144

**Comment by mhbassel** [comment]
Thank you very much for your quick reply.
Ok most of the steps are clear, but just to elaborate with numbers, lets say the maximum memory usage (i.e. the max load caused by one model I assume) in step 4. was 1G, so the 'count' in R1 should be equal 1, but then where should I set the total per device R1 value as mentioned in step 6.?

And I assume that these recourses settings in my config.pbtxt are only valid on my machine, on which I am configuring the triton server, and they might not work if I run the server with these configs on another machine, right?

**Comment by dyastremsky** [comment]
Any time. For your first question, I believe it'll be taken care of by default unless you choose to override the resources to set different constraints per device in the command line. You'd likely want to do this, as the default resources may not be the same as those you'd prefer to specify.

From https://github.com/triton-inference-server/server/blob/main/docs/rate_limiter.md#resources:

```
By default, the available resource copies are per-device and resource requirements for a model instance are enforced against corresponding resources associated with the device where the model instance runs. The --rate-limit-resource allows users to provide different resource copies to different devices. Rate limiter can also handle global resources. Instead of creating resource copies per-device, a global resource will have a single copy all across the system.
...
For tritonserver, running on a two device machine, invoked with --rate-limit-resource=R1:10 --rate-limit-resource=R2:5:0 --rate-limit-resource=R2:8:1 --rate-limit-resource=R3:2 , available resource copies are...
```
The resource settings would work on any machine, but they would not be "correct" for a machine if that machine has different resource availability. For example, if you're basing resource constraints on a machine with 4GB of GPU versus one with 16GB of GPU, you'd probably want to set different resource constraints. You'd probably be able to get away with just changing the command line overrides for the device (in this case, setting the resource corresponding GPU memory to a value 4x larger, if that fits your goals), but there might be situations where that'd not be ideal.

**Comment by mhbassel** [comment]
Thanks so much for your detailed answer, I really appreciate it!

I have just two more questions please, In the link you provided, it says:
```
For example, assume three loaded model instances A, B and C each specifying the following
resource requirements for a single device:
A: [R1: 4, R2: 4]
B: [R2: 5, R3: 10, R4: 5]
C: [R1: 1, R3: 7, R4: 2]
etc
```
Speaking about the model config of B: Is the reason of having multiple resources R2, R3 and R4 is to avoid the contention in case a model instance of A is using the whole R2, then it will use another one? And why each resource of them has a different count on one single device, in the steps above if the model load on that single device was e.g. 5GB, we set the count for R2 to e.g. 5, but why R3 is 10 in this case?

`a global resource will have a single copy all across the system.` does this mean it is independent of the devices I define in the config and it relays on all the resources I have on the system?

My apology for asking too many questions! :sweat_smile:

**Comment by dyastremsky** [comment]
There are many ways you could use the rate limiter. The point of having multiple resources is to allow you to set multiple constraints. It won't use a different resource. If you're out of R2, then no models that need R2 will be scheduled. Say you use R2 to represent GPU memory... perhaps you have a model that you're running on CPU, so it doesn't need R2 and that constraint doesn't apply to it (and can therefore be scheduled).

A global resource applies that constraint to the server as a whole. If your server is running with multiple devices (e.g. GPUs), then that constraint is applied across all devices. Again, these resources do not correlate with any specific resource on your system, it's just a constraint used for scheduling. It's up to you to assign them meaning.

**Comment by mhbassel** [comment]
Got it, everything is clear now! 
I really appreciate your help David and many thanks for your time.
