### ISSUE TITLE
Auto-Generated Model Configuraton with label file

### ISSUE THREAD

**Issue by Phelan164** [triton-inference-server/server#4571]
From [this](https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#minimal-model-configuration) Triton server could automatically generate [Minimal Model Configuration](https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#minimal-model-configuration) and `label_filename` not generated

I want to add the `label_filename` to  the generated model configuration or the Triton server could support that

**Comment by rmccorm4** [comment]
Hi @Phelan164,

Thanks for opening this issue. CC @nv-kmcgill53 @kthui who I believe are looking into this issue or something similar.

**Comment by nv-kmcgill53** [comment]
@rmccorm4 is correct, this issue is currently being worked on.

**Comment by kthui** [comment]
Hi @Phelan164, can you try building the server from the latest main branch, does the issue still persist?

**Comment by Phelan164** [comment]
@kthui thanks for your suggestion, I will try to build from the latest main branch.
just 1 question: Triton server automatically generates model configuration with `label_filename`. How the triton server detect that file (example predefined file name `label.txt` put in model folder, etc)  ?

**Comment by kthui** [comment]
@Phelan164 I do not think triton will automatically find a label file as far as I know. It will just fill an empty `label_filename: ""` if not specified. It is best to just set the `label_filename` in the config.

**Comment by Phelan164** [comment]
@kthui thanks for your anwser but have 1 problem with "set the `label_filename` in the config" 
To set `label_filename` we need to set in `output` and the `output` required `name`, `data_type`, `dims` so we have to specify all like example 
```
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ 1000 ]
    label_filename: "imagenet_labels.txt"
  }
]
```
So it mean that there is no automatically generated model configuration.
Another, `dims` need to be specified in this case `1000`, could not `-1` when run with `--strict-model-config=false`

**Comment by kthui** [comment]
@Phelan164 you need to provide `name` for the backend to associate them: 
```
output [
  {
    name: "output"
    label_filename: "imagenet_labels.txt"
  }
]
```
 `data_type` and `dims` could probably be inferred.
