### ISSUE TITLE
Will warmup been done when we start the server with --model-control-mode=explicit

### ISSUE THREAD

**Issue by lfxx** [triton-inference-server/server#4584]
**Is your feature request related to a problem? Please describe.**
I start the server with --model-control-mode=explicit,and no models will be loaded at start.I use client.py to load some target models later.I want to know if the warmup will been done at the same time or i need to do warmup in client.py by sending a request to the server.Thanks!

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rmccorm4** [comment]
Hi @lfxx ,

The warmup requests specified in `config.pbtxt` should be run by the server when the model is loaded, regardless of `--model-control-mode` you use.

You should be able to see the warmup requests in the verbose server output `--log-verbose=1`.
