### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by KingCSer** [triton-inference-server/server#4585]
What part of time does the request time consist of？
![1657010166414](https://user-images.githubusercontent.com/48956659/177315923-8fd0be7c-39ff-4152-944b-b8231fd7c76c.jpg)

**Comment by rmccorm4** [comment]
Hi @KingCSer ,

As the description implies, the request time is the lifetime of the inference. 

So the start is currently captured right before [running inference](https://github.com/triton-inference-server/core/blob/6a984dd747df4b0cc1782f63169a16ef9eb1ea7c/src/server.cc#L499) in `InferenceServer::InferAsync`, and the end is captured when `InferenceRequest::ReportStatistics` or similar is called, at the end of inference, before sending back the response.
