### ISSUE TITLE
Autoscale instances

### ISSUE THREAD

**Issue by manhtd98** [triton-inference-server/server#4597]
I have  2 model with difference traffic requests. 1 models have more request and need to scale but second model don't need.
How can i only scale instances instead of scale triton pod ?

**Comment by nv-kmcgill53** [comment]
Hi @manhtd98, Model instances are generated at model load time through from the Model Configuration. If you would like to scale the number of model instances at runtime, then you will have to update the model_config.pbtxt file and re-load the model. If however you would like to know the optimal number of instances before starting triton, you may use the [Model Analyzer Tool](https://github.com/triton-inference-server/model_analyzer) to determine what a good number of instances for your model should be.

For further reading, please see:
- [Model configuration](https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#instance-groups)
- {Model Management](https://github.com/triton-inference-server/server/blob/main/docs/model_management.md)

**Comment by MouseSun846** [comment]
> I have 2 model with difference traffic requests. 1 models have more request and need to scale but second model don't need. How can i only scale instances instead of scale triton pod ?

Hello, may I ask what solution you will ultimately adopt to achieve elastic scaling of the model?
