### ISSUE TITLE
MT-NLG - Are we ever getting access to the 530 B parameters trained model?

### ISSUE THREAD

**Issue by renanmb** [triton-inference-server/server#4600]
Just following up on the [Using DeepSpeed and Megatron to Train Megatron-Turing NLG 530B, the World’s Largest and Most Powerful Generative Language Model](https://forums.developer.nvidia.com/t/using-deepspeed-and-megatron-to-train-megatron-turing-nlg-530b-the-world-s-largest-and-most-powerful-generative-language-model/191746)

It has been while.

The MT-NLG framework on NGC is awesome, however it would be awesome to get the full model at NGC. A tremendous Head Start.

**Comment by rmccorm4** [comment]
Hi @renanmb ,

I'm going to close this out as it's not a Triton specific issue. However, I have reached out to some folks regarding this question. If I get a response, I will update this issue.
