### ISSUE TITLE
Get unexpected deadlock with ensemble model

### ISSUE THREAD

**Issue by yichi170** [triton-inference-server/server#4617]
### Description
I have an ensemble model which includes a preprocessing model (using Python backend and only resizing the image) and a TensorRT model (export from TAO toolkit training with cv_samples/faster_rcnn).

This is the config.pbtxt of the ensemble model:
```
name: "ensemble_faster_rcnn"
platform: "ensemble"
max_batch_size: 4
input [
    {
        name: "INPUT_ENSEMBLE"
	data_type: TYPE_UINT8
	dims: [ -1 ]
    }
]
output [
    {
	name: "OUTPUT_ENSEMBLE"
	data_type: TYPE_FP32
	dims: [ 1, 100, 7 ]
    },
    {
        name: "OUTPUT_ENSEMBLE_1"
        data_type: TYPE_FP32
        dims: [ 1, 1, 1 ]
    }
]

ensemble_scheduling {
    step [
        {
            model_name: "preprocessing_faster_rcnn"
            model_version: -1
            input_map {
                key: "INPUT_PREPROC"
                value: "INPUT_ENSEMBLE"
            }
            output_map {
                key: "OUTPUT_PREPROC"
                value: "preprocessed_image"
            }
        },
        {
            model_name: "faster_rcnn_tao"
            model_version: -1
            input_map {
                key: "input_image"
                value: "preprocessed_image"
            }
            output_map {
                key: "NMS"
                value: "OUTPUT_ENSEMBLE"
            }
            output_map {
                key: "NMS_1"
                value: "OUTPUT_ENSEMBLE_1"
            }
        }
    ]
}
```
and this is the config.pbtxt of the preprocessing model:
```
name: "preprocessing_faster_rcnn"
backend: "python"
max_batch_size: 4
input [
    {
        name: "INPUT_PREPROC"
        data_type: TYPE_UINT8
        dims: [ -1 ]
    }
]
output [
    {
        name: "OUTPUT_PREPROC"
        data_type: TYPE_FP32
        dims: [ 3, 384, 1248 ]
    }
]

instance_group [{ kind: KIND_CPU }]
```
this is the config.pbtxt of the inference model:
```
name: "faster_rcnn_tao"
platform: "tensorrt_plan"
max_batch_size: 4
input [
  {
    name: "input_image"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 384, 1248 ]
  }
]
output [
  {
    name: "NMS"
    data_type: TYPE_FP32
    dims: [ 1, 100, 7 ]
  },
  {
    name: "NMS_1"
    data_type: TYPE_FP32
    dims: [ 1, 1, 1 ]
  }
]

```
It can infer correctly without preprocessing, so I think the problem may happen in config.pbtxt of the ensemble model or preprocessing model. Issue #4260 refers that **models don't generate the output tensors promised** will report the error, so I checked my preprocessing output and its shape is (1, 3, 384, 1248)
### Informations:
- Server is running on docker (nvcr.io/nvidia/tao/triton-apps:22.02-py3)
- Preprocessing model uses [python_backend](https://github.com/triton-inference-server/python_backend)
- The inference model is training with the TAO toolkit and cv_samples_v1.4.0/faster_rcnn
### Question:
Is there anything I can check to solve the "unexpected deadlock, at least one output is not set while no more ensemble steps can be made"?

**Comment by Tabrizian** [comment]
Hi @yichi170. The error usually happens when the model is not returning the outputs it is supposed to return. Please make sure that your Python model is providing the correct names for the output tensors.

**Comment by yichi170** [comment]
Thanks a lot. I really provide the wrong name for the output tensor. I misspelled the output tensor name.
