### ISSUE TITLE
Can I stop execution?

### ISSUE THREAD

**Issue by hyunwoongko** [triton-inference-server/server#4618]
Hello. I have a question about triton inference server.
When timeout occurs, can I stop previous execution for next execution?

**Comment by Tabrizian** [comment]
You cannot cancel individual requests when they are put in the queue. However, you can set the [default_timeout_microseconds ](https://github.com/triton-inference-server/common/blob/38452b707e66eeb590188c9440d257ca3b68f35a/protobuf/model_config.proto#L1075) config parameter to reject a request if it has spent too much time in the queue.
