### ISSUE TITLE
[question] Versioning for ensemble models

### ISSUE THREAD

**Issue by denisov-vlad** [triton-inference-server/server#4627]
Hi!

I have ensemble model with "tokenize" and "predict" steps:

```
inference/
  1/
  2/
  config.pbtxt

tokenize/
  1/
  2/
  config.pbtxt

model/
  1/
  2/
  config.pbtxt
```

There is 2 versions of different models. Version policy:

```
version_policy: { all { }}
```

But in the inference (=ensemble) model we need to specify version at the model level, not version. Here is the part from `inference/config.pbtxt`:

```
...
ensemble_scheduling {
    step [
        {
            model_name: "tokenize"
            model_version: -1
            input_map {
            key: "TEXT"
            value: "TEXT"
        }
...
```

Is it possible to set the different versions for different ensemble models?

**Comment by krishung5** [comment]
Hi @denisov-vlad, as long as the ensemble model has the same set of steps, all versions of the same ensemble act the same, so the versioning of the ensemble itself doesn't really matter. If you want to set the different versions for different ensemble models, you will need have different ensemble models and specify the steps differently.

**Comment by denisov-vlad** [comment]
Thanks!
