### ISSUE TITLE
[question] Adding timeout options for both client and server with a custom backend and stateful batching

### ISSUE THREAD

**Issue by jamied157** [triton-inference-server/server#4629]
I'm interested in adding some good timeout behaviour for a deployment where we use a custom backend for triton that uses a stateful batcher. I'm using the [stateful backend](https://github.com/triton-inference-server/stateful_backend/tree/5cb23b3105eef9208503a5d9160cdad74fadcb7d) as a reference. 

 - When timing out on the client side, I can see we use the `stream_timeout` option (as is done [here](https://github.com/triton-inference-server/stateful_backend/blob/5cb23b3105eef9208503a5d9160cdad74fadcb7d/client/simple_grpc_sequence_stateful_stream_infer_client.cc#L244)) but it's not clear how this interacts with the server. If I terminate the stream via the timeout on the client side, does that cause any code to run on the server side? 
 - In the stateful batcher example, it looks like there's a separate timer for each [stream](https://github.com/triton-inference-server/stateful_backend/blob/a651fcb1e434026e600db3b022c00fd15800fd10/src/onnx_model_runner.cc#L1024) that evicts the stream from the server when it times out. Similar to before, does this interact with the client in some way? Can we send an error message to the client when this happens.

In general any advice on managing clients and their states in a robust way would be appreciated, we'd really like to avoid any instance where a client is taking up a slot on the server but has already timed out (or the client is waiting for a response from the server that has already timed out its slot).

**Comment by krishung5** [comment]
Hi @jamied157, I believe when timing out on the client side, the client just stop streaming itself and fail the inference on itself, the server side does not get triggered any timeout mechanism. Same for the server side, I think when server timing out, the client side will just lose connection to the server and have a failing inference.
For the timeout mechanism for both server and client side, maybe @tanmayv25 or @GuanLuo can chime in and provide more context on it?

**Comment by Tabrizian** [comment]
> When timing out on the client side, I can see we use the stream_timeout option (as is done [here](https://github.com/triton-inference-server/stateful_backend/blob/5cb23b3105eef9208503a5d9160cdad74fadcb7d/client/simple_grpc_sequence_stateful_stream_infer_client.cc#L244)) but it's not clear how this interacts with the server. If I terminate the stream via the timeout on the client side, does that cause any code to run on the server side?

I think it will terminate the GRPC stream and will close the connection to the server side. (CC @tanmayv25).

>In the stateful batcher example, it looks like there's a separate timer for each [stream](https://github.com/triton-inference-server/stateful_backend/blob/a651fcb1e434026e600db3b022c00fd15800fd10/src/onnx_model_runner.cc#L1024) that evicts the stream from the server when it times out. Similar to before, does this interact with the client in some way? Can we send an error message to the client when this happens.

I think this is mainly for deleting the storage associated with the correlation IDs stored in the backend. I don't think it does interact with the client. This is mainly for removing the storage when the `max_sequence_idle_microseconds` has elapsed.

You might also be interested in the implicit state management API for the backends: https://github.com/triton-inference-server/core/blob/main/include/triton/core/tritonbackend.h#L689-L758

Currently, only TensorRT and ONNX backends implement this API but you can incorporate this into your own custom backends too. Using implicit state management, the state tensors will be internally handled by Triton core and you don't need store them in your backend.

**Comment by jamied157** [comment]
> I think it will terminate the GRPC stream and will close the connection to the server side.

So just to clarify this, if I have some state associated with a correlation id that times out on the client side - it's up to me to make sure that state is discarded on the server to avoid having a memory leak and that should be run on a separate timer (as in that example above). I don't see any interface between the Triton core and the backend that allows the core to inform the backend that a certain correlation ID can be discarded.

The internal state management does look good, I assume this will correctly clean up state tensors when the grpc stream is terminated then?

**Comment by Tabrizian** [comment]
> So just to clarify this, if I have some state associated with a correlation id that times out on the client side - it's up to me to make sure that state is discarded on the server to avoid having a memory leak and that should be run on a separate timer (as in that example above). I don't see any interface between the Triton core and the backend that allows the core to inform the backend that a certain correlation ID can be discarded.

Exactly. That is why the stateful backend has that internal timer to discard the states when the sequence batcher times out.

> The internal state management does look good, I assume this will correctly clean up state tensors when the grpc stream is terminated then?

Yes, implicit state management correctly cleans up the state tensors. The cleanup is not performed when the grpc stream is closed but when new sequences are scheduled to run which will clean up the old states.

**Comment by jamied157** [comment]
Great, thanks for your help - that's all I need to know for now.

**Comment by rakib-hasan** [comment]
Thanks, Iman. What you said about the stateful backend is correct. The internal timer is there only to cleanup the states for timed-out sequences.

**Comment by rizwanishaq** [comment]
when max_sequence_idle_microseconds happens, how we can catch this inside the python_backend in sequenc_batching, as I have that correlation id, in memory, and want to remove from the python_backend side, after max_sequence_idle_microsencods, any way to do this?
