### ISSUE TITLE
onnxruntime tensorrt  is faster then triton server tensorrt  

### ISSUE THREAD

**Issue by liroda** [triton-inference-server/server#4637]
I have a onnx model , the onnx input is float32 [-1,80]

first I test in onnxruntime 
onnxruntime.InferenceSession(onnfile,providers=[('TensorrtExecutionProvider', {"trt_engine_cache_enable": "true","trt_fp16_enable":"true"})])

Linux Ubuntu 18.04 :
ONNX Runtime installed from (pip ):
ONNX Runtime version 1.10.0 :
Python version:
CUDA version 11.4.2:
cuDNN version 8.2.4 

triton server  config.pbtxt
optimization { execution_accelerators {
  gpu_execution_accelerator : [ {
    name : "tensorrt"
    parameters { key: "precision_mode" value: "FP16" }
    parameters { key: "trt_engine_cache_enable" value: "1" }
    parameters { key: "trt_engine_cache_path" value: "/opt/tritonserver" }
    }]
}}
model_warmup [
{
    name : "model"
    batch_size: 1
    inputs {
        key: "input1"
        value: {
            data_type: TYPE_FP32
            dims: [2,80]
            random_data: true
        }
    }
},
{
    name : "model"
    batch_size: 1
    inputs {
        key: "input1"
        value: {
            data_type: TYPE_FP32
            dims: [2600,80]
            random_data: true
        }
    }

the input is like this
input1 = (-1 + 2*np.random.random((xlen,80))).astype(np.float32)

when the xlen is 2000
the onnxruntime cost is 0.0238
the tritonsever cost is 0.23 

the triton sever is 22.03 

I do not know why ？

**Comment by Lzhang-hub** [comment]
Hi, did you resolve it? I have the same result, can you give some advices, thanks.
