### ISSUE TITLE
How to get predict_proba as inference output of pytorch model?

### ISSUE THREAD

**Issue by jimduden6804** [triton-inference-server/server#4646]
We built a model which I can call like this to get the probability of classification.
```
some_example_feature_vec = np.array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]).reshape(1,-1)
pt_tensor = torch.from_numpy(some_example_feature_vec)
loaded_model.predict_proba(pt_tensor.double())
>> tensor([[0.4331,` 0.5669]], dtype=torch.float64, grad_fn=<ExpBackward0>)
```

We export the model like:
```
torch.jit.script(torch_model).save("my_model.pt")
```
Now we configure triton for the export of this model
```
name: "mymodel"
platform: "pytorch_libtorch"
max_batch_size: 8
input [
  {
    name: "float_input"
    data_type: TYPE_FP64
    dims: [ 15 ]
  }
]
output [
  {
    name: "output_class"
    data_type: TYPE_INT64
    dims: [ 1 ]
  }
]
```

If we call the model this way, it uses the predict() function to generate a binary output. 
We would like to call the predict_proba() function instead, giving us the probabillities for all classes instead.
Is that possible? 

p.s. the original model is a sklearn logreg model, but the onnx runtime does not support our output as described [here](https://github.com/triton-inference-server/onnxruntime_backend/issues/94)

Best regards,
Jim

**Comment by krishung5** [comment]
Hi @jimduden6804, I think you would need to generate a model that only runs the `predict_proba()` function. AFAIK, we cannot choose which function to be used for a model in Trition.
CC @Tabrizian

**Comment by jimduden6804** [comment]
Thanks for the advice.
Too bad that it can't be configured but at least it is something we can work around 

I will leave this open for a few days in case a different idea comes up
