### ISSUE TITLE
TRTIS 19.10 does notfind GPUs | failed call to cuInit: UNKNOWN ERROR (303)

### ISSUE THREAD

**Issue by rounakskm** [triton-inference-server/server#4655]
Hello,
The machine is a Dell G7 laptop with  RTX 2060 GPU

I have installed Nvidia-driver = 470.129.06
CUDA Toolkit 10.1.243

`nvcc --version`

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

I am trying to run TRTIS 19.10 using docker compose:

trtis:
    image: nvcr.io/nvidia/tensorrtserver:19.10-py3
    volumes:
      - /home/ronny/Desktop/models:/models
    ports:
      - 8000:8000
    command: ["trtserver", "--model-store=/models", "--strict-model-config=false"]
    shm_size: 1g
    ulimits:
      memlock: -1
      stack: 67108864
    networks:
      - trtis_network 

And I get the following error:

trtis_1                 | 
trtis_1                 | ===============================
trtis_1                 | == TensorRT Inference Server ==
trtis_1                 | ===============================
trtis_1                 | 
trtis_1                 | NVIDIA Release 19.10 (build 8266503)
trtis_1                 | 
trtis_1                 | Copyright (c) 2018-2019, NVIDIA CORPORATION.  All rights reserved.
trtis_1                 | 
trtis_1                 | Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.
trtis_1                 | NVIDIA modifications are covered by the license terms that apply to the underlying
trtis_1                 | project or file.
trtis_1                 | 
trtis_1                 | WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
trtis_1                 |    Use 'nvidia-docker run' to start this container; see
trtis_1                 |    https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker .
trtis_1                 | 
trtis_1                 | I0715 21:00:37.983607 1 server.cc:110] Initializing TensorRT Inference Server
trtis_1                 | 2022-07-15 21:00:37.992418: I tensorflow/cc/saved_model/reader.cc:31] Reading SavedModel from: /models/strut_detection/1/model.savedmodel
trtis_1                 | 2022-07-15 21:00:38.019944: I tensorflow/cc/saved_model/reader.cc:54] Reading meta graph with tags { serve }
trtis_1                 | 2022-07-15 21:00:38.086357: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2199995000 Hz
trtis_1                 | 2022-07-15 21:00:38.087280: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x555d21ca5eb0 executing computations on platform Host. Devices:
trtis_1                 | 2022-07-15 21:00:38.087309: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
trtis_1                 | 2022-07-15 21:00:38.087533: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/tensorrtserver/lib:/usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
trtis_1                 | 2022-07-15 21:00:38.087544: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)
trtis_1                 | 2022-07-15 21:00:38.087556: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] no NVIDIA GPU device is present: /dev/nvidia0 does not exist

How do I resolve this,why is TRTIS failing to find any GPUs?

Thanks

**Comment by rounakskm** [comment]
Upon using nvidia-docker to run TRTIS stand alone I get

`nvidia-docker run --name trtis --network trtis_network --rm --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 -p 8000:8000 -v $(pwd)/models:/models "nvcr.io/nvidia/tensorrtserver:19.10-py3" trtserver --model-store=/models`

===============================
== TensorRT Inference Server ==
===============================

NVIDIA Release 19.10 (build 8266503)

Copyright (c) 2018-2019, NVIDIA CORPORATION.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.
NVIDIA modifications are covered by the license terms that apply to the underlying
project or file.

I0715 21:27:08.984014 1 metrics.cc:160] found 1 GPUs supporting NVML metrics
I0715 21:27:08.989635 1 metrics.cc:169]   GPU 0: NVIDIA GeForce RTX 2060
I0715 21:27:08.989905 1 server.cc:110] Initializing TensorRT Inference Server
I0715 21:27:09.028865 1 main.cc:455] Starting endpoints, 'inference:0' listening on
I0715 21:27:09.030339 1 grpc_server.cc:1800] Started GRPCService at 0.0.0.0:8001
I0715 21:27:09.030371 1 http_server.cc:1205] Starting HTTPService at 0.0.0.0:8000
I0715 21:27:09.072579 1 http_server.cc:1220] Starting Metrics Service at 0.0.0.0:8002
W0715 21:27:10.990593 1 metrics.cc:235] failed to get power limit for GPU 0, NVML_ERROR 3
W0715 21:27:12.993096 1 metrics.cc:235] failed to get power limit for GPU 0, NVML_ERROR 3
W0715 21:27:14.995228 1 metrics.cc:235] failed to get power limit for GPU 0, NVML_ERROR 3

**Comment by krishung5** [comment]
Hi @rounakskm, from the second logging you provide, it looks like your GPU doesn't report metrics. If you don't care about metrics, you can use the `--allow-metrics=false` flag to turn them off, and then you won't see the warning messages (the lines with a 'W' at the beginning).
Besides, TRTIS 19.10 is a very old version of Triton. Maybe you can use a more up-to-date version? You can find all the information including the driver requirements in our [release notes](https://docs.nvidia.com/deeplearning/triton-inference-server/release-notes/).

**Comment by rounakskm** [comment]
Okay, my major concern is that I am unable to run it using docker-compose. It is pretty important for my project. Sadly updating it is not an option for me. But TRTIS 19.10 works fine on all EC2 instances flawlessly.
I am trying to run it on a fresh PC with Ubuntu and having these issues

Running using docker-compose leads to 
WARNING: The NVIDIA Driver was not detected. GPU functionality will not be available. I will try to update browser and try

**Comment by rounakskm** [comment]
Okay, my major concern is that I am unable to run it using docker-compose. It is pretty important for my project. Sadly updating it is not an option for me. But TRTIS 19.10 works fine on all EC2 instances flawlessly.
I am trying to run it on a fresh PC with Ubuntu and having these issues

Running using docker-compose leads to 
WARNING: The NVIDIA Driver was not detected. GPU functionality will not be available. But the appropriate driver is installed and it works with nvidia-docker but not with docker-compose

**Comment by kthui** [comment]
Hi @rounakskm, can you try running `nvidia-smi` inside a docker container and see if it works?
You can run it by `sudo docker run --rm --gpus all nvidia/cuda:11.0.3-base-ubuntu20.04 nvidia-smi`.

**Comment by Tabrizian** [comment]
Closing due to in-activity.
