### ISSUE TITLE
The cc_model_filenames does not work

### ISSUE THREAD

**Issue by parichehrvn** [triton-inference-server/server#4657]
**Description**
I want to load a TensorRT model, but whatever value I set to the cc_model_filenames parameter, the model is loaded successfully.

**Triton Information**
22.05-py3

Are you using the Triton container or did you build it yourself?
Triton container

**To Reproduce**
- Train a TAO Retinanet model
- Export TAO Retinanet model
- Convert the model to generate model.plan file
- Load the plan file using Triton

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
- model: TAO Retinanet
- Config file:
```
name: "TAO_OD_RETINANET_RESNET18"
platform: "tensorrt_plan"
default_model_filename: "model.plan"
max_batch_size: 2
input [
  {
    name: "Input"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 416, 416 ]
  }
]
output [
  {
    name: "NMS"
    data_type: TYPE_FP32
    dims: [ 1, 200, 7 ]
  },
  {
    name: "NMS_1"
    data_type: TYPE_FP32
    dims: [ 1, 1, 1 ]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]

cc_model_filenames [
  {
    key: "8.6"
    value: "model.plan"
  }
]
```

**Expected behavior**
I expect that if I change the key or value in this parameter, the model will not load.

**Comment by kthui** [comment]
Thanks for submitting your request.
Hi @tanmayv25, should the model fail to load by setting incorrect `cc_model_filenames` parameter?

**Comment by tanmayv25** [comment]
@parichehrvn Providing cc_model_filenames means that on a device with a specific compute capability, triton should use the provided plan file, See here for more information: https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#cuda-compute-capability

If you are providing a cc_model_filename with key that does not match the cc of the device where the model is being loaded the provided cc_model_filename will be essentially be ignored. It only takes an effect when you are loading the model on the device with matching compute capability. 

Now the question is when would the model load fail: If you are loading the model device with cc 8.6 and the provided filename in value does not exist or was not compiled for cc 8.6. There might be other failures but the above two cases just highlights when model loading can fail.

**Comment by parichehrvn** [comment]
As far as I understand, the min_supported_compute_capability is 6.0. I generated a model on a device with compute capability 7.5 and used the following config file:
```
name: "TAO_OD_RETINANET_RESNET18"
platform: "tensorrt_plan"
default_model_filename: "model.plan"
max_batch_size: 2
input [
  {
    name: "Input"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 416, 416 ]
  }
]
output [
  {
    name: "NMS"
    data_type: TYPE_FP32
    dims: [ 1, 200, 7 ]
  },
  {
    name: "NMS_1"
    data_type: TYPE_FP32
    dims: [ 1, 1, 1 ]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [ 0 ]
  }
]

cc_model_filenames [
  {
    key: "7.5"
    value: "model.plan"
  }
]
```
but got the following error:
`The engine plan file is generated on an incompatible device, expecting compute 8.6 got compute 7.5, please rebuild.`

**Comment by tanmayv25** [comment]
> I generated a model on a device with compute capability 6.1 

Based on the error message, I don't think this statement is accurate. Can you double-check? Looks like model.plan was generated on 8.6 cc and the model.plan is being loaded on device with cc 7.5. 

Can you share ouptut of `nvidia-smi` on the system where you are generating the plan file and where you are running tritonserver?

**Comment by parichehrvn** [comment]
Sorry, I checked again.
The model.plan was generated on 7.5 cc and is being loaded on device with 8.6 cc.
The following is my config.pbtxt file. And again I got this error:

**`The engine plan file is generated on an incompatible device, expecting compute 8.6 got compute 7.5, please rebuild.`**

```
name: "TAO_OD_RETINANET_RESNET18"
platform: "tensorrt_plan"
max_batch_size: 2
input [
  {
    name: "Input"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 416, 416 ]
  }
]
output [
  {
    name: "NMS"
    data_type: TYPE_FP32
    dims: [ 1, 200, 7 ]
  },
  {
    name: "NMS_1"
    data_type: TYPE_FP32
    dims: [ 1, 1, 1 ]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [ 0 ]
  }
]

cc_model_filenames [
  {
    key: "7.5"
    value: "model.plan"
  }
]
```

**Comment by tanmayv25** [comment]
> The model.plan was generated on 7.5 cc and is being loaded on device with 8.6 cc.

This is not supported. You need to create an engine on a device with 7.5 cc to be able to run on device with 7.5 cc.
TensorRT has some device specific optimization and running engines across different device cc is not supported.
See the response here: https://github.com/NVIDIA/TensorRT/issues/1562#issuecomment-983281368

**Comment by parichehrvn** [comment]
In this case, should we deploy Triton server as multi GPU, where  each GPU is specific to one model?

**Comment by tanmayv25** [comment]
A better way of thinking is that a TensorRT model is specific to a particular GPU, not the other way around. 

Assuming you want to deploy Triton on a multi-GPU setup with A100 and T4 GPUs. You can create two TensorRT plan files for both the GPUs. The model repository should look like:

```
model-repository
       | -------- Resnet50
                      | -------- config.pbtxt
                      | -------- 1
                                 | -------- resnet50_T4.plan
                                 | -------- resnet50_A100.plan
```

And the config.pbtxt should contain :

```
cc_model_filenames [
  {
    key: "7.5"
    value: "resnet50_T4.plan"
  },
  {
    key: "8.0"
    value: "resnet50_A100.plan"
  }
]
```

When loading Resnet50 on T4, triton will use resnet50_T4.plan file and on A100, triton will use resnet50_A100.plan.

**Comment by serser** [comment]
what about the configuration for A30, I tried with key 8.0/8.6, both don't work
