### ISSUE TITLE
exec /opt/nvidia/nvidia_entrypoint.sh: exec format error

### ISSUE THREAD

**Issue by manhtd98** [triton-inference-server/server#4659]
When deploy on AWS i got this errror. When pull origin tritonserver containers all thing oke, but i just add customer layout to install pytorch and got this happend. 
Anyone know why?

**Comment by manhtd98** [comment]
when i try :
```
command: ["/bin/sh", "-c"]
          args: [ "/opt/tritonserver/bin/tritonserver  --allow-gpu-metrics=false \
          --strict-model-config=false --model-store={{ .Values.image.modelRepositoryPath }}"] 
```

```
exec /bin/sh: exec format error
```

**Comment by manhtd98** [comment]
here is dockerfile:
```
FROM nvcr.io/nvidia/tritonserver:22.05-py3
RUN pip install protobuf==3.20.0 loguru nanoid yacs boto3 
RUN pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116
RUN pip install opencv-python-headless
COPY lib/ /opt/lib/
```
local run okey but on serve i got that error

**Comment by kthui** [comment]
Hi @manhtd98, `exec /bin/sh: exec format error` seems to be errors with your script file. If it works locally, but not on AWS. It is better for you to contact AWS for assistance.

If you later found this issue to be triton specific, please feel free to reopen the issue.
