### ISSUE TITLE
I am new to triton inference. I am looking for documents related to A/B testing but couldn't find them so far. If someone here is already used this feature, please let me the details.

### ISSUE THREAD

**Issue by mail2surie** [triton-inference-server/server#4660]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kthui** [comment]
Hi @mail2surie, Triton Inference Server is for model inference and it does not interact with humans directly like a search engine would do, so A/B testing does not apply to triton.
