### ISSUE TITLE
The average latency of the fp16 bert demo trt.engine with dynamic batch size is up to 2s

### ISSUE THREAD

**Issue by helenHlz** [triton-inference-server/server#4667]
**Description**

We deploy a bert demo fp16 tensorrt engine by using triton server on a v100-32G gpu.
There is a custom performance test client that calculates latency metrics and a website captures information from the metrics port. 

The latency indicators we observed for various experiments are listed below.
#### max_batch_size is 4 and max_queue_delay_microseconds is 1 
It can be seen that the data of the client and the website are very close. The average latency is about 2s, mainly contributed by the queue latency, followed by the input latency.
```
Duration:           500
Average Latency:    1947427μs
P50:                1931263μs
P90:                3518463μs
P95:                3710975μs
P99:                3864575μs
P99.9:              3921919μs
Maximum Latency:    5156863μs
Request sent:    50000
Error rate:    0.0
QPS:                100
```
![image](https://user-images.githubusercontent.com/23006115/179733748-55b235b0-45d2-47f1-9294-b034508badd0.png)
![image](https://user-images.githubusercontent.com/23006115/179733781-2dc4e103-07bf-4dde-b555-52fc8daa000c.png)
![image](https://user-images.githubusercontent.com/23006115/179733818-4eeedcaa-049d-4c82-b964-d141a6a95850.png)
![image](https://user-images.githubusercontent.com/23006115/179733868-4c278bbe-8638-4fd7-ab3e-2e77660710bd.png)
![image](https://user-images.githubusercontent.com/23006115/179733930-46fb117d-d15f-4da1-bf80-48bf7f21f461.png)

#### max_batch_size is 3 and max_queue_delay_microseconds is 1 
If we set max_batch_size to 3, this experiment is executed with a fixed batch size is 1. But the latency results seems more plausible.
```
Duration:           500
Average Latency:    3678μs
P50:                3287μs
P90:                4851μs
P95:                5615μs
P99:                7735μs
P99.9:              13527μs
Maximum Latency:    97919μs
Request sent:    50000
Error rate:    0.0
QPS:                100
```
![image](https://user-images.githubusercontent.com/23006115/179735153-bcedfcdc-961a-4a57-b399-9c572ef1e0bb.png)
![image](https://user-images.githubusercontent.com/23006115/179735225-1ad8aa6b-8049-4bb3-ae5e-db7e1b71eb6d.png)
![image](https://user-images.githubusercontent.com/23006115/179735268-0abd0221-fd77-4946-9d81-dfc3fb52e80d.png)

#### max_batch_size is 4 and max_queue_delay_microseconds is 10
From the model_configuration document, the queue latency is only related to **max_queue_delay_microseconds** parameter. The n we changed this parameter to 10. The latency results are similar to the first experiment. The max_queue_delay_microseconds seems doesn't work.

```
Duration:           500
Average Latency:    2006327μs
P50:                2007039μs
P90:                3598335μs
P95:                3799039μs
P99:                3956735μs
P99.9:              4147199μs
Maximum Latency:    4796415μs
Request sent:    200000
Error rate:    0.0
QPS:                400 
   
 Duration:           500
Average Latency:    2004766μs
P50:                2012159μs
P90:                3588095μs
P95:                3782655μs
P99:                3946495μs
P99.9:              4020223μs
Maximum Latency:    4190207μs
Request sent:    250000
Error rate:    0.0
QPS:                500
```
![image](https://user-images.githubusercontent.com/23006115/179738428-05c8c632-5556-4fe4-8604-5b40fceac4b1.png)
![image](https://user-images.githubusercontent.com/23006115/179738454-2dcf82ed-64a6-4016-bf70-0bdd830aa914.png)
![image](https://user-images.githubusercontent.com/23006115/179738502-5b3e9673-6f50-4d18-ac99-75699720b509.png)
![image](https://user-images.githubusercontent.com/23006115/179738556-f953fe83-3722-4db6-827f-8aef3b87d58b.png)
![image](https://user-images.githubusercontent.com/23006115/179738653-34761a8c-e517-4f26-8ebb-46022a6370d9.png)

**Triton Information**
What version of Triton are you using?
20.09 

Are you using the Triton container or did you build it yourself?
custom docker image based on the Triton container 

**To Reproduce**
Steps to reproduce the behavior.

We upload the engine we use to the google drive. You can download from here. https://drive.google.com/drive/folders/1l-Iu8ScSaPboDAnBb_tNOiLOVI9RGAag?usp=sharing
You can use other testing tools to reproduce the results.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

You can get the engine from this link. https://github.com/NVIDIA/TensorRT/tree/release/7.1/demo/BERT 

```
name: "squad-bert"
platform: "tensorrt_plan"
max_batch_size: 4
dynamic_batching {
    max_queue_delay_microseconds: 1
}
input [
  {
    name: "input_ids"
    data_type: TYPE_INT32
    dims: [128]
  },
  {
    name: "input_mask"
    data_type: TYPE_INT32
    dims: [128]
  },
  {
    name: "segment_ids"
    data_type: TYPE_INT32
    dims: [128]
  }
]
output [
  {
    name: "cls_squad_logits"
    data_type: TYPE_FP32
    dims: [128,2,1,1]
  }
]
version_policy: {
  specific {
    versions:  [1]
  }
}
instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]
```

**Expected behavior**
The server can works in dynamic batch size mode. But the latency increases too much than the experiment with fixed batch size. 

- How to optimize this latency? 
- Is there something wrong with the model configuration file?
- Why doesn't the max_queue_delay_microseconds parameter have any effect on the queue latency?

**Comment by kthui** [comment]
Hi @helenHlz, from my understanding, when the batch size increases, latency could increase, as the server could wait for requests to be inferred as a batch.
CC @GuanLuo

For latency optimization, you can use the [Triton Model Analyzer](https://github.com/triton-inference-server/model_analyzer#triton-model-analyzer), it can automatically find the optimal settings for Dynamic Batching base on your model and use case.

**Comment by helenHlz** [comment]
> Hi @helenHlz, from my understanding, when the batch size increases, latency could increase, as the server could wait for requests to be inferred as a batch. CC @GuanLuo
> 
> For latency optimization, you can use the [Triton Model Analyzer](https://github.com/triton-inference-server/model_analyzer#triton-model-analyzer), it can automatically find the optimal settings for Dynamic Batching base on your model and use case.

The 20.09 version is too old to use the model analyzer. We will try it after upgrading the version. 
We still hope someone can answer this queue latency problem.

**Comment by kthui** [comment]
Sorry for missing this part. If I understand the experiment correctly, from your graphs, it seems like both setups have reached a dynamic batch size of 4. Then, the `max_queue_delay_microseconds` is not effective when a maximum size (or preferred size) batch can be created ([link to doc](https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#delayed-batching)). Maybe you can try increasing the `max_batch_size` and see if `max_queue_delay_microseconds` is capping the delay, to ensure this is the reason.

**Comment by helenHlz** [comment]
> Sorry for missing this part. If I understand the experiment correctly, from your graphs, it seems like both setups have reached a dynamic batch size of 4. Then, the `max_queue_delay_microseconds` is not effective when a maximum size (or preferred size) batch can be created ([link to doc](https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#delayed-batching)). Maybe you can try increasing the `max_batch_size` and see if `max_queue_delay_microseconds` is capping the delay, to ensure this is the reason.

After we upgraded the version, the dynamic batching works as expected. Thx.
