### ISSUE TITLE
Questions for asynchronous Triton deployment

### ISSUE THREAD

**Issue by BastianGit** [triton-inference-server/server#4669]
I would like to do parallel inference with two different models using Triton. To do this I use the non-blocking async_infer() function and append all requests in a list. After, I wait for the response of all requests before continuing in the code. However, I have several questions regarding the implementation:

1. I notice there is a gevent.sleep(0.01) in the _init_ of the http request code. This sleep takes 10ms which is quite a long time! Is it possible to use gevent.sleep(0) and are there any disadvantages to it?
2. Why does the inference not start immediately after receiving an async request? My inference only starts at the moment I ask for a response for this specific request id.
3. By default asking for a response from a specific request id is blocking, the "request_id.get_result()" function. However, if I set the parameter blocking=False, would I be able to keep looping through my request id's and get the first response that is ready? (i.e the first model that is done with inference)

**Comment by kthui** [comment]
Hi @BastianGit, seems like you are trying to stream the infer requests. You can check out the [GRPC Options](https://github.com/triton-inference-server/client#grpc-options) which has build-in [streaming](https://github.com/triton-inference-server/client/blob/main/src/python/library/tritonclient/grpc/__init__.py#L1462) capability.

**Comment by tanmayv25** [comment]
@BastianGit You should definitely give the asyncio versions a try. For standard httpclient, we use geventhttpclient lib to communicate with the server. There are some serious issues when using the async versions of the function calls. 
It uses co-operative mutli-tasking with greenlets.

1. gevent.sleep(0.01) is used to release the control back to the network thread to start sending the request. I think gevent.sleep(0) didn't transfer the control properly and the main greenlet kept the control.
2. This was supposed to be resolved by gevent.sleep(0.01). Can you try with gevent.sleep(1) just to be sure?
3.  You can read about the blocking behavior here: https://github.com/triton-inference-server/client/blob/main/src/python/library/tritonhttpclient/__init__.py
```
Greenlet.get(block=True, timeout=None) → [object](https://docs.python.org/3/library/functions.html#object)[[source]](http://www.gevent.org/_modules/gevent/greenlet.html#Greenlet.get)

    Return the result the greenlet has returned or re-raise the exception it has raised.

    If block is False, raise [gevent.Timeout](http://www.gevent.org/api/gevent.timeout.html#gevent.Timeout) if the greenlet is still alive. If block is True, unschedule the current greenlet until the result is available or the timeout expires. In the latter case, [gevent.Timeout](http://www.gevent.org/api/gevent.timeout.html#gevent.Timeout) is raised.
```

There are issues with the async operations using geventhttpclient lib. You should definitely try the new asyncio version which is based on aiohttp as @kthui has pointed.
