### ISSUE TITLE
What is the difference between `Plattform` and `Backend`

### ISSUE THREAD

**Issue by NikeNano** [triton-inference-server/server#4672]
**Description**
After reading about the [triton sever](https://github.com/triton-inference-server/backend#backends) I don't fully understand the difference between the `backend` and `platform` parameter. They seem to represent the same thing but use slightly different tags. One example form the docs are: 

```
For TensorRT, 'backend' must be set to tensorrt or 'platform' must be set to tensorrt_plan.
```
Why should the users set one or the other? Are one legacy and one is the recommended? Are there any differences at all? Why are there multiple ways to set the same thing?

**Triton Information**

**To Reproduce**

**Expected behavior**

Did not know where to post, let me know if this is the wrong place and where I can move it. Thanks for the help!

**Comment by Tabrizian** [comment]
The `platform` field is the legacy field and the `backend` field is the new convention. There is not any different in terms of functionality at all. Specifying `platform: tensorrt_plan` or `backend: tensorrt` would lead to the same backend being used.

**Comment by NikeNano** [comment]
Great, would it make sens to add this to the docs @Tabrizian? I would be happy to make a PR for it.

**Comment by krishung5** [comment]
Closing this issue as the PR has been merged. Thanks again for your contribution.
