### ISSUE TITLE
Optional usage of shared memory for python backend

### ISSUE THREAD

**Issue by farzanehnakhaee70** [triton-inference-server/server#4675]
**Is your feature request related to a problem? Please describe.**
If we want to deploy a model ensemble with multiple numbers of python_backend, we should increase the shm_size. However, increasing the shm_size is not implemented in SageMaker. If this feature would be optional, it resolves the issue with deploying a model inside sagemaker triton inference server.

**Describe the solution you'd like**
Optional usage of shm for python_backend.

**Comment by Tabrizian** [comment]
It is not possible to make Python backend shared memory usage optional. Shared memory is required for proper execution of Python backend. You can adjust the shared memory usage of Python backend using the instructions provided here: https://github.com/triton-inference-server/python_backend#managing-shared-memory

I think it makes more sense to ask SageMaker to provide APIs for adjusting the shared memory size.

**Comment by farzanehnakhaee70** [comment]
Thanks for your reply @Tabrizian. Exactly you are right.
