### ISSUE TITLE
How can I run an uninterrupted thread in python backend?

### ISSUE THREAD

**Issue by piekey1994** [triton-inference-server/server#4678]
**Description**
I created a new python thread in the initialize function. This thread is responsible for regularly updating a hot word list. However, I found that after the initialize function is finished, the python thread is no longer running. This phenomenon also occurs in the execute function. How can I run an uninterrupted thread in python backend?

**Triton Information**
21.11

Are you using the Triton container or did you build it yourself?
Triton container

**Comment by kthui** [comment]
Just a guess, can you try creating the thread as a class/static variable and see if it works:
```
...
class TritonPythonModel:
    threads = None          # class variable
    def initialize(self, args):
        TritonPythonModel.threads = initialize_the_thread
        ...
    def execute(self, requests):
        ...
    def finalize(self):
        ...
```

**Comment by Tabrizian** [comment]
There was a bug in Python backend before the 22.05/22.06 release which I think is related to the issue you are seeing. The problem was that the GIL lock was acquired as soon as you returned from the execute function and as a result the other threads never got a chance to execute. Could you please repeat your experiment with the latest version of Triton to see whether you still see this issue?

**Comment by piekey1994** [comment]
> Just a guess, can you try creating the thread as a class/static variable and see if it works:
> 
> ```
> ...
> class TritonPythonModel:
>     threads = None          # class variable
>     def initialize(self, args):
>         TritonPythonModel.threads = initialize_the_thread
>         ...
>     def execute(self, requests):
>         ...
>     def finalize(self):
>         ...
> ```

Unfortunately, this method doesn't seem to work

**Comment by piekey1994** [comment]
> There was a bug in Python backend before the 22.05/22.06 release which I think is related to the issue you are seeing. The problem was that the GIL lock was acquired as soon as you returned from the execute function and as a result the other threads never got a chance to execute. Could you please repeat your experiment with the latest version of Triton to see whether you still see this issue?

In this version of 22.06, the multithreaded code can run successfully.
