### ISSUE TITLE
TensorRT Optimization in ConfigMap

### ISSUE THREAD

**Issue by NikeNano** [triton-inference-server/server#4683]
What is the difference between setting:

```
optimization { execution_accelerators {
  gpu_execution_accelerator : [ {
    name : "tensorrt"
    parameters { key: "precision_mode" value: "FP16" }}]
}}

```

Versus using:

```
trtexec
```

before similar to how it is done python_backend preprocessing example. If done as a separate step will the start up be significantly lower than when utilizing tensorrt compare to through the config? Are the same speed expected?

Thanks for the help!

**Comment by kthui** [comment]
Hi @tanmayv25 @GuanLuo, would there be a speed difference by using the different configs?

**Comment by GuanLuo** [comment]
The TensorRT optimization in model config is used for other backends to perform online conversion if the underlying frameworks support it (i.e. ORT-TRT, TF-TRT) whereas trtexec will generate a TensorRT engine file at the end and being loaded via TensorRT backend.

In the online approach, even it ease the user to generate TRT engine in the cost of startup time, the speed may not match exactly as the conversion could be done differently from trtexec.

**Comment by NikeNano** [comment]
Thanks!
