### ISSUE TITLE
Failed to load tensorflow model: Not loaded: No model version was found

### ISSUE THREAD

**Issue by alvint4** [triton-inference-server/server#4697]
**Description**
I am trying to load a tensorflow model as a startup model but the status show Not loaded: No model version was found even though I've specified the model version folder.

**Triton Information**
What version of Triton are you using?
21.10
Are you using the Triton container or did you build it yourself?

**To Reproduce**
Steps to reproduce the behavior.
1. Build the image:
docker run -it -p8000:8000 -p8001:8001 -p8002:8002 -v /path/to/models:/models  nvcr.io/nvidia/tritonserver:21.10-py3

2. Start triton server:
tritonserver --strict-model-config=false --model-repository=/models/triton --log-verbose=50 --log-info=true --log-warning=true --log-error=true --http-port=8000 --grpc-port=8001 --metrics-port=8002 --model-control-mode=explicit --grpc-use-ssl=false --allow-http=true --allow-grpc=true --load-model=/models/triton/MyModel

Here is MyModel format layout:
```
MyModel/
   1/
       model.savedmodel/
              variables/
                       variables.data-00000-of-00002
              saved_model.pb
              modelSchema.json
```
**Expected behavior**
Triton successfully loads the model.

**Comment by rmccorm4** [comment]
Hi @alvint4 ,

The argument to `--load-model` should just be the model name, you don't need to point to a specific model repository because model names should be unique even across multiple model repositories.

Try `--load-model=MyModel` instead.
