### ISSUE TITLE
Python backend initialize 'model_repository' arg breaking change

### ISSUE THREAD

**Issue by HarmitMinhas96** [triton-inference-server/server#4703]
**Description**

I am upgrading triton from 21.05 to 22.06 and it seems that the python backend now receives the current models `model.py` path instead of the current models folder as it previously did. This is a breaking change for all currently deployed models that use the python backend and relied on this. Are there any tips for handling this? 

I also don't see this mentioned in the release notes or any other issues, not sure if I missed it somewhere. Is there any reason a new arg wasn't just added to `args` instead of changing the expected value of an existing arg?

**Comment by dotieuthien** [comment]
I have the same issue

**Comment by erfaneshrati** [comment]
i think this PR can solve this issue:
https://github.com/triton-inference-server/python_backend/pull/180

**Comment by Tabrizian** [comment]
Hi @HarmitMinhas96, Sorry about this breaking change. I think this was a mistake on our and we will fix it for 22.08 release. Thanks for bringing this to our attention.

**Comment by HarmitMinhas96** [comment]
np, thank you!

**Comment by krishung5** [comment]
Closing this issue as the PR https://github.com/triton-inference-server/python_backend/pull/180 has been merged in.
