### ISSUE TITLE
[Question] About perf_analyzer request rate

### ISSUE THREAD

**Issue by SeungsuBaek** [triton-inference-server/server#4711]
Hi!

I have a question about perf_analyzer and tritonserver's trace.json.

---
SERVER
```
$ tritonserver --model-repository=/triton_dev/models --trace-file /triton_dev/experiments/trace/trace.json --trace-level TIMESTAMPS --trace-rate 1
```
---
CLIENT
```
$ perf_analyzer -b 1 -m resnet --request-rate-range 50:50 --sync --request-distribution constant
```

I wanted to see if the request comes to the server according to the request rate set by the perf_analyzer. So after using these commands, I checked trace.json and drew a graph of how many requests per second arrived.

Below graph is the result of that.
( { "name": "**http recv start**", "ns":  123456789} ) // only use this information in trace.json.

![image](https://user-images.githubusercontent.com/76544552/181723897-627da891-bc6a-49b2-8ac7-312f2ab3cc85.png)

My question is that **why is the request rate measured higher than the perf_analyzer's value for about 3 seconds?**

**Comment by GuanLuo** [comment]
@tanmayv25 @matthewkotila @Tabrizian ^^^

**Comment by tanmayv25** [comment]
There appears to be a bug. PA generates a schedule for requests to follow. Most likely the initial few requests have missed their scheduled time and get sent together. @matthewkotila  Can you create a bug to fix this issue?

**Comment by tgerdesnv** [comment]
Hi @SeungsuBaek, there have been some fixes around request rate scheduling over the last few months. I tried to reproduce this issue and everything appears to be working correctly now. Let me know if you are still seeing this issue.

**Comment by SeungsuBaek** [comment]
@tgerdesnv Thanks you so much!!!
