### ISSUE TITLE
Customize response when using raw binary request.

### ISSUE THREAD

**Issue by N78750469** [triton-inference-server/server#4722]
**Is your feature request related to a problem? Please describe.**
When using [raw binary request](https://github.com/triton-inference-server/server/blob/main/docs/protocol/extension_binary_data.md#raw-binary-request), the response will include tensors after the metadata response which prevents deserializing the response (the tensor will consist of the string length so the response format will be like this METADATA_RESPONSE|STRING_LENTGH|JSON_RESULTS). 

**Describe the solution you'd like**
I want to include the model results in the metadata response so I can deserialize it without further parsing the output.
as an example: use ```response.json()``` directly. 

**Describe alternatives you've considered**
Split the response string using the delimiter \x00, and deserialize the last string.

**Additional context**
I am using BLS for post-processing and returning a JSON string.

**Comment by tanmayv25** [comment]
Possibly duplicated by https://github.com/triton-inference-server/server/issues/4404.

There are many ways to encode/decode bytes data. For performance considerations we represent the byte/string tensor elements as `<str_lenght><str_content>` throughout Triton clients and server. Building a nested json response object with tensor data on server side is little heavy. We would recommend using such parsing to be conducted on client side.

Have you seen [deserialize_bytes_tensors](https://github.com/triton-inference-server/client/blob/main/src/python/library/tritonclient/utils/__init__.py#L246) utility?

**Comment by N78750469** [comment]
@tanmayv25 Thanks for the quick response. I did check that, but ultimately I would like to avoid any parsing on the client side, do you have any suggestions in this regard? also, is it possible to disable the metadata response? so I would only receive the model output.

**Comment by tanmayv25** [comment]
> also, is it possible to disable the metadata response? so I would only receive the model output.

This is not possible currently. We can return the response as raw binary without any metadata but it would only support very limited use cases.
```
1. Only has 1 output
2. If the output data type is non-BYTE, the number of variable size dimensions is at most 1. If the data type is BYTE, the shape must be [1]. The supported data types can be found [here](https://github.com/kserve/kserve/blob/master/docs/predict-api/v2/required_api.md#tensor-data-types)
```

**Comment by N78750469** [comment]
So it is not possible in the case of batches, anyway thank you for the clarification, I will use what is provided.
