### ISSUE TITLE
Question complex output with different shape for every sample - Token classification 

### ISSUE THREAD

**Issue by shaked571** [triton-inference-server/server#4726]
I have a pytorch model that do token classification (NER to be specific). 
For every sentence (which has different number of tokens) I predict the labels. 
But the **amount of entities I exatrct for each sentence is diffrent**
For example for a batch of 2 sentence the prediction may be:
```
[
 [{'entity': 'A',  'start': 4, 'end': 11}],
 [{'entity': 'B',  'start': 17, 'end': 22}, {'entity': 'A',  'start': 34, 'end': 38}]
]
```
Where for the sentence I found one entity, and for the second sentence I have found two.

Is there anyway to have this kind of output? 
I saw triton for pt backend supports dict only for input, but is there any workaround?

I prefer not to move the logic to the client side because it is written in a different programming language (Java) and I wish not to implement the logic there.

I thought to have a String output and concatente so it would look like
The config:
```
...
output [
  {
    name: "OUTPUT"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
[
``` 
 The output:
```
[ 
 'A___4___11',
 'B___17___22$$$A___34___38'
]
```
But I thought there might be a different way

**Comment by tanmayv25** [comment]
Can you break the output like:
```
output [
  {
    name: "ENTITY"
    data_type: TYPE_STRING
    dims: [ -1 ]
  },
  {
    name: "START"
    data_type: TYPE_INT32
    dims: [ -1 ]
  },
  {
    name: "END"
    data_type: TYPE_INT32
    dims: [ -1 ]
  }
]
```
The tensor will look like:
```
[
 {"entity": ["a"], {"start": [4]}, {"end":[11]}},
 {"entity": ["b", "a"], {"start": [17, 34]}, {"end":[22, 38]}},
]
```

?

**Comment by shaked571** [comment]
Ohh, I  didn't realize the shape of each tensor is dynamic!

I thought that if I do 
```
  {
    name: "START"
    data_type: TYPE_INT32
    dims: [ -1 ]
  }
```
 Start can be whatever length I wish, but have to be consistent throughout the batch (i.e., if the first sentence had Start in size 2, the second sentence also has to be in the size of 2 ).
I will give it a try now!
