### ISSUE TITLE
enh: Trace to capture the child models invoked from BLS

### ISSUE THREAD

**Issue by brightsparc** [triton-inference-server/server#4731]
**Is your feature request related to a problem? Please describe.**
I have created a BLS "router" model that executes sync/async inferences on one (or more in the case of traffic mirroring) models and returns the results in a similar way to an ensemble model which has a fixed set of steps.  

When inspecting the [trace](https://github.com/triton-inference-server/server/blob/main/docs/trace.md) summary I only see the BLS `titanic_ensemble_router` model.

```
Summary for titanic_ensemble_router (1): trace count = 10
HTTP infer request (avg): 2263.9625us
	Receive (avg): 6.1543us
	Send (avg): 5.8us
	Overhead (avg): 117.7us

	Handler (avg): 2134.3082us
		Overhead (avg): 7.9622us
		Queue (avg): 71.6958us
		Compute (avg): 2054.6502us
			Input (avg): 17.5376us
			Infer (avg): 1979.4167us
			Output (avg): 57.6959us
```

And none of the child models like I do when I have an ensemble:

```
Summary for titanic_ensemble (2): trace count = 10
HTTP infer request (avg): 750.5334us
	Receive (avg): 12.0917us
	Send (avg): 4.4915us
	Overhead (avg): 71.6753us

	Handler (avg): 662.2749us
Summary for titanic_ensemble_preprocess (2): trace count = 10
	Handler (avg): 264.6375us
		Overhead (avg): 53.129us
		Queue (avg): 73.5293us
		Compute (avg): 137.9792us
			Input (avg): 19.3083us
			Infer (avg): 114.7541us
			Output (avg): 3.9168us
Summary for titanic_ensemble_predict (2): trace count = 10
	Handler (avg): 260.0915us
		Overhead (avg): 40.4247us
		Queue (avg): 67.0252us
		Compute (avg): 152.6416us
			Input (avg): 11.4749us
			Infer (avg): 135.1542us
			Output (avg): 6.0125us
Summary for titanic_ensemble_postprocess (2): trace count = 10
	Handler (avg): 147.3834us
		Overhead (avg): 42.1375us
		Queue (avg): 63.142us
		Compute (avg): 42.1039us
			Input (avg): 6.4249us
			Infer (avg): 31.1334us
			Output (avg): 4.5456us
```

**Describe the solution you'd like**
I would like the [tracer](https://github.com/triton-inference-server/server/blob/main/src/tracer.cc#L327-L384) to capture the child activity such that I could record which actual `model_name` and `model_version` was invoked at runtime, given this will be dynamic based on input

Ideally I would like this to be hooked in as part of the infer_request [Exec](https://github.com/triton-inference-server/python_backend/blob/main/src/infer_request.cc#L353) method which captures the BLS as the `parent_id`.

**Describe alternatives you've considered**
I have considered adding specific `output` configuration for the model name and version metadata, but would prefer not to have to change the contract to be any different than the downstream model config. 

One other nice to have capability would be pass additional contextual parameters to the KServing API input which I could use for ensuring session affinity on the model selection based on some unique hash for a given user.  This request has previously been raised and closed as issue  #2486

**Additional context**
The context is to support dynamic A/B Testing in Triton with multiple models instead of moving this hire up the stack at the networking layer.

**Comment by tanmayv25** [comment]
cc @Tabrizian

**Comment by oandreeva-nv** [comment]
This feature will be supported starting from 23.08 release
