### ISSUE TITLE
Perf_analyzer json file error on unspecified optional tensors.

### ISSUE THREAD

**Issue by Vozf** [triton-inference-server/server#4734]
22.05 container
I have a model with optional tensor inputs. I try to run perf_analyzer with json with unspecified optional inputs and I get the error
```
error: failed to create concurrency manager: missing tensor ... ( Location stream id: 0, step id: 0)
```
Perf_analyzer shouldn't require optional arguments

**Comment by Tabrizian** [comment]
This has been fixed and will be available for the 22.08 release. https://github.com/triton-inference-server/client/pull/127
