### ISSUE TITLE
Real time inference using Triton C APIs for multiple models

### ISSUE THREAD

**Issue by shekhardw** [triton-inference-server/server#4754]
**Is your feature request related to a problem? Please describe.**
We have a need to do inference using multiple models on same data. Data is streamed and real time performance is critical.
Data is fed into the models using a GXF tensor.

**Describe the solution you'd like**
1- A working example of inference with multiple models in parallel with no memory copy per model using Triton C APIs (same input memory is shared per model inference instance)
2- An example with GXF Tensor will be great. 

**Describe alternatives you've considered**
- Created a sample solution using Triton C APIs, but with each incoming frame the memory allocation on GPU was increasing. 
- Created a sample solution using onnxruntime

**Additional context**
Are Triton C APIs suitable for concurrent inference on multiple models in real time?

**Comment by Tabrizian** [comment]
Hi @shekhardw, we do have an example for using Triton C-API in the [simple.cc](https://github.com/triton-inference-server/server/blob/a3e96fa1d46b7a0c98280558b133f613a3c09d1a/src/simple.cc) file. This example reused some of the structs like `TRITONSERVER_InferenceRequest` object which you might be interested in.

**Comment by Tabrizian** [comment]
Closing due to in-activity.
