### ISSUE TITLE
Run server with public IP !

### ISSUE THREAD

**Issue by lktinh2018** [triton-inference-server/server#4763]
Hello all,

I can run triton server with localhost and I can request to triton server with localhost.
But I cannot request triton server with public IP.
I use port fowarding feature on router.
Device: windows 10.

Should I enable special feature or something else ?
Please help me !
Really thanks for your support.

**Comment by alxmamaev** [comment]
@lktinh2018  No, you actually need just open ports on your host machine. Probably you did not change the address from localhost to real IP on your client app.

**Comment by lktinh2018** [comment]
> @lktinh2018 No, you actually need just open ports on your host machine. Probably you did not change the address from localhost to real IP on your client app.

I configured some server before successful with same way.
But I don't know why I cannot request with triton server now.
I checked https://www.yougetsignal.com/tools/open-ports/ and it's provide my port open correctly.

**Comment by alxmamaev** [comment]
@lktinh2018  Did you checked 8000 and 8001 port?

**Comment by lktinh2018** [comment]
Sorry I can run succesful now.
I dont know why I cannot request from same device with public IP.
I use other device and request.

**Comment by alxmamaev** [comment]
Probably you may kinda firewall or something router which rejects your request.
Btw, nice that you have success!

**Comment by alxmamaev** [comment]
@lktinh2018 Probably you may kinda firewall or something router which rejects your request.
Btw, nice that you have success!

**Comment by lktinh2018** [comment]
Really thanks for your support!

**Comment by dyastremsky** [comment]
Thanks @alxmamaev for getting this resolved! I'll close out this ticket.

If you have other questions around this issue, let me know and we can reopen the ticket.
