### ISSUE TITLE
Unexpected inference output 'model_output', allowed outputs are: logits

### ISSUE THREAD

**Issue by Vinayaks117** [triton-inference-server/server#4767]
**Description**
When I try to deploy a "distillbert-base-uncased" (fine-tuned on SST-2 which is used for Sentiment Analysis) on Triton inference server then I am getting following error.

**Error details**

E0815 07:00:04.655657 90 model_repository_manager.cc:1348] failed to load 'sts' version 1: Invalid argument: unexpected inference output 'model_output', allowed outputs are: logits

**Triton Information**
Triton Server Version 2.22.0
NVIDIA Release 22.05

Using Triton container: 
'007439368137.dkr.ecr.us-east-2.amazonaws.com/sagemaker-tritonserver:21.08-py3'
'007439368137.dkr.ecr.us-east-2.amazonaws.com/sagemaker-tritonserver:22.05-py3'

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Ensemble model configuration file**
name: "ensemble_model"
max_batch_size: 0 
platform: "ensemble"

input [
{
    name: "TEXT"
    data_type: TYPE_STRING
    dims: [ -1 ] 
}
]

output {
    name: "score"
    data_type: TYPE_FP32
    dims: [-1, 2] 
}

ensemble_scheduling {
    step [
        {
            model_name: "tokenizer"
            model_version: -1
            input_map {
            key: "TEXT"
            value: "TEXT"
        }
        output_map [
            {
                key: "input_ids"
                value: "input_ids"
            },
            {
                key: "attention_mask"
                value: "attention_mask"
            }
        ]
        },
        {
            model_name: "sts"
            model_version: -1
			input_map [
				{
					key: "input_ids"
					value: "input_ids"
				},
				{
					key: "attention_mask"
					value: "attention_mask"
				}
			]
			output_map {
					key: "model_output"
					value: "score"
				}
        }
    ]
}

**NLP model configuration file**

name: "sts"
platform: "onnxruntime_onnx"
backend: "onnxruntime"
default_model_filename: "distilbert-base-uncased-finetuned-sst-2-english.onnx"
max_batch_size: 0
input [
  {
    name: "input_ids"
    data_type: TYPE_INT64
    dims: [-1, -1]
  },
{
    name: "attention_mask"
    data_type: TYPE_INT64
    dims: [-1, -1]
  }
]
output [
  {
    name: "model_output"
    data_type: TYPE_FP32
    dims: [-1, 2]
  }
]

instance_group [
    {
      count: 1
      kind: KIND_GPU
    }
]

**Tokenizer configuration file**

name: "tokenizer"
max_batch_size: 0
backend: "python"

input [
{
    name: "TEXT"
    data_type: TYPE_STRING
    dims: [ -1 ]
}
]

output [
{
    name: "input_ids"
    data_type: TYPE_INT64
    dims: [-1, -1]
},
{
    name: "attention_mask"
    data_type: TYPE_INT64
    dims: [-1, -1]
}
]

instance_group [
    {
      count: 1
      kind: KIND_GPU
    }
]

**Expected behavior**
Need to load the STS-2 model on Triton inference server. Basically, it receive a string, send it to the tokenizer, get the output from the tokenizer and pass it as input of the model, return the model output.

I'm not able to load the model due to above error. Kindly request you to help me on this issue.

Thanks a lot.

**Comment by dyastremsky** [comment]
It looks like your sts model has an output called "logits," not "model_output." If so, the config should use the output name "logits".

**Comment by alxmamaev** [comment]
Hi @Vinayaks117 , onyx files have a output nodes names, probably your model output node name is `logits`

You can check real model outputs names using https://netron.app

**Comment by Vinayaks117** [comment]
It works as expected. Thanks a lot @alxmamaev @dyastremsky for your help and it motivates me to explore the Nvidia triton more.

**Comment by Vinayaks117** [comment]
Hi @alxmamaev @dyastremsky 

Greetings!!

I have introduced postprocessing step which accepts the predictions from "distilbert-base-uncased-finetuned-sst-2-english" model as logits and return a string which is final score.

**Postprocessing model configuration file**

name: "postprocessing"
backend: "python"
max_batch_size: 0
input [
  {
    name: "logits"
    data_type: TYPE_FP32
    dims: [-1, 6]
  }
]
output [
  {
    name: "score"
    data_type: TYPE_STRING
    dims: [-1]
  }
]

instance_group [
    {
      count: 1
      kind: KIND_CPU
    }
]

So I'm getting a following error in postprocessing model script.
Failed to process the request(s) for model 'postprocessing_0', message: RuntimeError: Could not infer dtype of c_python_backend_utils.Tensor


` def execute(self, requests) -> "List[List[pb_utils.Tensor]]":
        """
        Parse and tokenize each request
        :param requests: 1 or more requests received by Triton server.
        :return: text as input tensors
        """
        responses = []
        # for loop for batch requests (disabled in our case)
        for request in requests:
            # binary data typed back to string
            data_input = pb_utils.get_input_tensor_by_name(request, "logits")
            
            print("data_input:", data_input)
            print("data_input type:", type(data_input))
            
            logits = torch.as_tensor(data_input) ## Error is coming from this line
            print("logits:", logits)`

**Comment by dyastremsky** [comment]
You need to use `.as_numpy()` on data_input to convert it into Numpy format before calling `torch.as_tensor(data_input)`.

**Comment by Vinayaks117** [comment]
Thanks for your reply. Any idea on how to enable logs in "sagemaker-tritonserver:22.05-py3" container because python print statements are not printing anything in cloudwatch logs.

**Comment by dyastremsky** [comment]
It sounds like you're asking about adding print statements in your client rather than Triton logs, so that'd be fully dependent on your code. 

Server logs always output to the console (unless redirected). Print statements in your client will print wherever you are running your client, not in the server.

If there are questions about how print statements work in SageMaker and CloudWatch, that'd be beyond the scope of Triton and would be better directed to their teams and documentation.

**Comment by Tabrizian** [comment]
You need to add `print('Your message', flush=True)` to make sure the prints by the Python model get printed to the output.

**Comment by Vinayaks117** [comment]
Thanks @Tabrizian

Making progress, I'm trying to return following prediction_list as string but getting a following error.

prediction_list  = [[('Profanity', 0.055326663), ('Race', 0.051294506), ('LGBTQ', 0.08058877), ('Religion', 0.07207184), ('Politics', 0.058775462), ('Violence', 0.8665062)]]

0818 17:44:10.945814 127 pb_stub.cc:749] Failed to process the request(s) for model 'postprocessing_0', message: TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. c_python_backend_utils.Tensor(arg0: str, arg1: numpy.ndarray)

I fixed above error by converting prediction_list  to numpy.ndarray then getting a following error.

Failed to process the request(s) for model 'postprocessing_0', message: TritonModelException: NumPy dtype is not supported.

End objective to return final predictions with it's labels in string format which I mentioned config file.
output [
{
name: "score"
data_type: TYPE_STRING
dims: [-1]
}

Please help me on this issue. Thanks
