### ISSUE TITLE
Issues with implicit state management

### ISSUE THREAD

**Issue by alecgunny** [triton-inference-server/server#4775]
**Description**
I'm trying to convert some of my code from explicit to implicit state control, but am running into issues with the API. My config looks like

```proto
name: "snapshotter"
platform: "onnxruntime_onnx"
input {
  name: "stream"
  data_type: TYPE_FP32
  dims: 1
  dims: 2
  dims: 16
}
output {
  name: "x_snapshot"
  data_type: TYPE_FP32
  dims: 8
  dims: 2
  dims: 32
}
instance_group {
  count: 1
  kind: KIND_CPU
}
sequence_batching {
  max_sequence_idle_microseconds: 10000000
  direct {
  }
  state {
    input_name: "input_snapshot"
    output_name: "output_snapshot"
    data_type: TYPE_FP32
    dims: 1
    dims: 2
    dims: 32
    initial_state {
      data_type: TYPE_FP32
      dims: 1
      dims: 2
      dims: 32
      zero_data: true
      name: "snapshot"
    }
  }
}
```
where `input_snapshot` and `output_snapshot` are the tensor names in the corresponding ONNX binary. Some example client code looks like
```python
import time
from threading import Event

import numpy as np
from tritonclient import grpc as triton

event = Event()

def callback(result, error):
    if error is not None:
        print(f"Failed: {error}")
    else:
        print(result.as_numpy("x_snapshot"))
    event.set()


x = np.arange(32).reshape(1, 2, 16).astype("float32")
input = triton.InferInput(
    name="stream",
    datatype="FP32",
    shape=(1, 2, 16)
)
input.set_data_from_numpy(x)

client = triton.InferenceServerClient("localhost:8001")
with client:
    client.start_stream(callback=callback)
    client.async_stream_infer(
        model_name="snapshotter",
        model_version="1",
        inputs=[input],
        sequence_start=True,
        sequence_id=1001,
    )

while not event.is_set():
    time.sleep(1e-3)
```

But the printed response is:
```
Failed: onnx runtime error 1: Failed to find input name in the mapping: input_snapshot
```

**Triton Information**
Triton NGC container 22.07-py3
Client version 2.24.0, installed via pip

**To Reproduce**
See client script above. I can provide the model onnx binary as well if necessary, but hoping that there's something obvious in the config/client code that I'm missing.

**Expected behavior**
A size `(8, 2, 32)` array is printed from the callback, corresponding to `x_snapshot` output of the model.

**Comment by dyastremsky** [comment]
I haven't seen that format for "dims" before, so it might be helpful to see whether using the [more standard one in our examples ](https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md) makes a difference.

Does this model run successfully directly in ONNX Runtime? The error is occurring in ONNX Runtime, not Triton, so that'd be the first place to check. Triton does additional validation, but it's possible it missed something that ONNX Runtime expects from the model.

**Comment by alecgunny** [comment]
That's the format for `dims` that gets written when you build the config programmatically in Python and then save it as a string to a text file. You can check this with any old config by doing something like:

```python
from google.protobuf import text_format
from tritonclient.grpc.model_config_pb2 import ModelConfig

config = ModelConfig()
with open("/path/to/config", "r") as f:
    text_format.Merge(f.read(), config)

with open("/path/to/config", "w") as f:
    f.write(str(config))
```
I tend to write my configs using protobuf's python bindings, so this is typically how they look, but I've never had a problem with it before.

I haven't checked running with onnxruntime directly yet, I'll give that a go and get back to you.

**Comment by alecgunny** [comment]
Ah ok this was indeed an error with tensor naming on my end, apologies and appreciate your responsiveness
