### ISSUE TITLE
Python backend bug when using model load api to reload model in explicit mode

### ISSUE THREAD

**Issue by SaratM34** [triton-inference-server/server#4783]
**Description**
I have a found a bug when using the model load api to re-load an already loaded python backend model in explicit mode. To explain the scenario, We have a model which is already being loaded and running by Triton. We have a new version of the model which we would like Triton to load. So when triton is currently running and serving the model, we deleted the same model from model repository  and copied the new version of the model. If we call the load API `/v2/repository/models/<model_name>/load` it will start re-loading the model. The bug here is that triton is not using the conda environment of the new version of the model. it continues to use the conda environment of old model hence resulting is failed model re-load in case there are newer dependencies in the conda environment for newer version. 

**Triton Information**
What version of Triton are you using?
r22.07

Are you using the Triton container or did you build it yourself?
Triton Container

**To Reproduce**
Steps to reproduce the behavior.
Its easy to reproduce the issue, create two versions of same python backend model. one with an additional python dependency i.e both versions just only differ in conda environments (provided example model.py and requirements.txt below for each version). use triton to load one version of the model and when triton is successfully loaded the model and running, remove the model from model repository and copy the other version which has an additonal dependency and call the model reload api. it will fail saying module not found error(for example, in the below case it will fail to re-load with pandas module not found error).

**Version 1 - model.py**
```
import triton_python_backend_utils as pb_utils
 
import numpy as np
 
 class TritonPythonModel:
    def initialize(self, args):
    	pass
    def execute(self, requests):
    	pass
    def finalize(self):
        pass
```

version 1 - requirements.txt
```
numpy
```

**Version 2 - model.py**
```
import triton_python_backend_utils as pb_utils
 
import numpy as np
import pandas as pd
 
 class TritonPythonModel:
    def initialize(self, args):
    	pass
    def execute(self, requests):
    	pass
    def finalize(self):
        pass
```

version 2 - requirements.txt
```
numpy
pandas
```

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
python backend

**Expected behavior**
when reloading an model it should reload conda environment too

**Comment by dyastremsky** [comment]
Thanks for reporting the above. I've filed a ticket to investigate.

You might want to try using unload before calling load again in case that fixes the above in the short-term. We'll look into what's going wrong for reloading.

**Comment by SaratM34** [comment]
@dyastremsky thanks for looking into it. You are right that we can unload and load again but in our case the model continuously takes traffic and if we unload, the service will be unavailable and will result in failed requests during the time it's loaded again.

**Comment by dyastremsky** [comment]
Any time, and thank you for clarifying. That makes sense.

**Comment by SaratM34** [comment]
Hi @dyastremsky, Just wanted to follow up on this to see if there is any update.

**Comment by dyastremsky** [comment]
Thanks for checking in. No update yet. When there is a corresponding pull request, this GitHub issue should be updated as well.

**Comment by SaratM34** [comment]
Hi @dyastremsky Just wanted to follow up on this. I know this issue will be updated whenever there is an update, since its been too long just wanted to follow up.

**Comment by dyastremsky** [comment]
Hi Sarat. Thanks for following up! This bug was assigned and prioritized recently, so it'll likely receive updates soon (after the holidays). Apologies for delay, and we appreciate your patience as we work through the queue.

**Comment by SaratM34** [comment]
Hi @dyastremsky Thanks so much for the update.

**Comment by SaratM34** [comment]
Hi @dyastremsky I did some debugging again today and found that Triton is able to load the conda env tar file only if there is a change in the conda tar file **name**. If there are some changes to the conda env and if we create conda tar file with same name as previous conda tar file, Triton is not loading the conda env. So I think while reloading Triton is not checking the tar diff instead just checking the conda tar file name to decide to load conda env or not .

**Comment by dyastremsky** [comment]
Thanks for debugging and looking into it! That helps quite a bit.

**Comment by tanmayv25** [comment]
@SaratM34 I was unable to reproduce the bug with our latest release.  For me the second variant loaded just fine. 

```

root@5c3e4cd826b5:/opt/tritonserver# curl -v -X POST localhost:8000/v2/repository/models/model/load

      Trying 127.0.0.1:8000...
    TCP_NODELAY set
    Connected to localhost (127.0.0.1) port 8000 (#0)
    > POST /v2/repository/models/model/load HTTP/1.1
    > Host: localhost:8000
    > User-Agent: curl/7.68.0
    > Accept: /
    > 
    I0126 23:39:49.221431 2557 model_lifecycle.cc:459] loading: model:1
    I0126 23:39:49.223118 2557 python_be.cc:1505] Using Python execution env /opt/tritonserver/numpy_env.tar.gz
    I0126 23:39:50.589814 2557 python_be.cc:1858] TRITONBACKEND_ModelInstanceInitialize: model (GPU device 0)
    I0126 23:39:50.793921 2557 model_lifecycle.cc:694] successfully loaded 'model' version 1
    Mark bundle as not supporting multiuse
    < HTTP/1.1 200 OK
    < Content-Type: application/json
    < Content-Length: 0
    < 
    Connection #0 to host localhost left intact
    root@5c3e4cd826b5:/opt/tritonserver# cp -r model2/model mdel-store//
    root@5c3e4cd826b5:/opt/tritonserver# curl -v -X POST localhost:8000/v2/repository/models/model/load
      Trying 127.0.0.1:8000...
    TCP_NODELAY set
    Connected to localhost (127.0.0.1) port 8000 (#0)
    > POST /v2/repository/models/model/load HTTP/1.1
    > Host: localhost:8000
    > User-Agent: curl/7.68.0
    > Accept: /
    > 
    I0126 23:40:14.170013 2557 model_lifecycle.cc:459] loading: model:1
    I0126 23:40:14.171297 2557 python_be.cc:1505] Using Python execution env /opt/tritonserver/numpy_pd_env.tar.gz
    I0126 23:40:20.705702 2557 python_be.cc:1858] TRITONBACKEND_ModelInstanceInitialize: model (GPU device 0)
    I0126 23:40:21.085093 2557 model_lifecycle.cc:694] successfully loaded 'model' version 1
    Mark bundle as not supporting multiuse
    < HTTP/1.1 200 OK
    < Content-Type: application/json
    < Content-Length: 0
    < 
    Connection #0 to host localhost left intact
    root@5c3e4cd826b5:/opt/tritonserver# I0126 23:40:22.274018 2557 model_lifecycle.cc:579] successfully unloaded 'model' version 1

```

Can you verify that your second model variant's config.pbtxt is pointing to the correct EXECUTION_ENV_PATH.

**Comment by SaratM34** [comment]
Hi @tanmayv25 , thanks for looking into this. The issue happens if the conda pack tar file has same name in both versions. since you have used two different conda pack tar names (numpy_env.tar.gz, numpy_pd_env.tar.gz) it is able to load correctly.

**Comment by tanmayv25** [comment]
Thanks for clarifying this. Can you share the config.pbtxt to make sure we got it right?

**Comment by SaratM34** [comment]
Below are the config.pbtxt for both version
* Version 1
```name: "modelA"
backend: "python"
max_batch_size: 8

input [
  {
    name: "INPUT0"
    data_type: TYPE_STRING
    dims:  [1]

  }
]

output [
  {
    name: "OUTPUT0"
    data_type: TYPE_STRING
    dims: [1]
  }
]

parameters: {
  key: "EXECUTION_ENV_PATH",
  value: {string_value: "/model_repository/modelA/condaenv.tar.gz"}
}
```
* Version 2
```
name: "modelB"
backend: "python"
max_batch_size: 8

input [
  {
    name: "INPUT0"
    data_type: TYPE_STRING
    dims:  [1]

  }
]

output [
  {
    name: "OUTPUT0"
    data_type: TYPE_STRING
    dims: [1]
  }
]

parameters: {
  key: "EXECUTION_ENV_PATH",
  value: {string_value: "/model_repository/modelB/condaenv.tar.gz"}
}

```
If conda file name is same as previous version Triton might be assuming there is no change in conda env. it might be intended to make model reload faster but i think it needs to check diff in conda env instead of name.
