### ISSUE TITLE
Images Downloaded Location? 

### ISSUE THREAD

**Issue by eanmikale** [triton-inference-server/server#4795]
**Description**
Where are files stores that are downloaded during an inference request? Or are they downloaded at all? Thank you.

**Comment by rmccorm4** [comment]
Hi @eanmikale ,

Triton should not be downloading anything by default during an inference request. 

If your underlying model/backend does some kind of downloading, then the ultimate file path would be determined by the model/backend, likely relative to the model repository location if using relative file paths.

**Comment by eanmikale** [comment]
Ryan,Thank you. When we make a curl request there is a download that happens. To our knowledge, our ONNX backend does not store imaging data. As we roll out medical applications it was paramount for liability concerns and privacy that patient data not be stored on the server or by our company. This seems to be the case and is easily explainable to interested parties. We can close this thread. Thank you!  ---- On Mon, 22 Aug 2022 16:12:05 -0500  ***@***.***  wrote ----
Hi @eanmikale ,
Triton should not be downloading anything by default during an inference request.
If your underlying model/backend does some kind of downloading, then the ultimate file path would be determined by the model/backend, likely relative to the model repository location if using relative file paths.
