### ISSUE TITLE
What should I do when backend_input_collector return need_cuda_input_sync of True value?

### ISSUE THREAD

**Issue by frankxyy** [triton-inference-server/server#4796]
I am developing a customized backend using c++. After calling the backend util function ``backend_input_collector.Finalized()``，I got the returned variable need_cuda_input_sync of value True. In the customed backend official examples，the code are all for backends running on cpu. As you can see in the demo code:
![image](https://user-images.githubusercontent.com/6971044/185780510-547204db-3d0f-4fb8-898f-3e1d54892181.png)

This customized backend is orchestrated after a model on gpu in an outer ensemble model and  I need to fetch buffer from gpu. So what should I do when I received the need_cuda_input_sync variable of True value？

More to add:
If I ignore this need_cuda_input_sync flag and continue the logic，when the server is concurrently called, the server will run into a core dump issue as below:
![7d7999c71903e519d936c0edf6fe85bb](https://user-images.githubusercontent.com/6971044/185780450-a5e6fd89-1dea-4edf-b6f8-a16215397118.png)

**Comment by rmccorm4** [comment]
Hi @frankxyy ,

As the comment points out, you'll need to synchronize the CUDA stream/event if `collector.Finalize()` returns true.

Taking a look at some other backends that do this may be useful, such as ONNXRuntime: https://github.com/triton-inference-server/onnxruntime_backend/blob/main/src/onnxruntime.cc#L2034

CC @tanmayv25

**Comment by frankxyy** [comment]
Thanks a lot, I get it. Another question I am wondering is that how can I manage the pinned memory pool？ So far as i can see from the backend util functions, it seems that a new length of memory will be allocated whenever the `collector.processTensor` function is called.

**Comment by tanmayv25** [comment]
You can take a look at [--pinned-memory-pool-byte-size](https://github.com/triton-inference-server/server/blob/main/src/main.cc#L586-L594).

**Comment by frankxyy** [comment]
Thanks a lot. I missed it before.

**Comment by rmccorm4** [comment]
Closing as this seems resolved, please open a new issue for any new questions.
