### ISSUE TITLE
Multiple instances on the same GPU

### ISSUE THREAD

**Issue by alxmamaev** [triton-inference-server/server#4799]
How triton operates with multiple instances on the same GPU? 
Does using MPS may help increase GPU utilisation?

**Comment by rmccorm4** [comment]
Hi @alxmamaev ,

> How triton operates with multiple instances on the same GPU?

See this doc: https://github.com/triton-inference-server/server/blob/main/docs/architecture.md#concurrent-model-execution

> How triton operates with multiple instances on the same GPU?
> Does using MPS may help increase GPU utilisation?

Please see these responses to similar questions: 
- https://github.com/triton-inference-server/server/issues/1061#issuecomment-579388235
- https://github.com/triton-inference-server/server/issues/366#issuecomment-501478714
