### ISSUE TITLE
If I open the log verbose in python http client, will time cost increase?

### ISSUE THREAD

**Issue by zhanghaoie** [triton-inference-server/server#4808]

**Comment by rmccorm4** [comment]
Hi @zhanghaoie ,

For the clients, setting `verbose=True` will generally print every request/response pair which could impact performance. Verbose mode is usually meant for debugging purposes.

**Comment by zhanghaoie** [comment]
Thank you very much for your reply. I have a triton inference server with nvida 21.07 which deploy on k8s with four docker instances, I have used the python backend, but after running two weeks one instance won't accept any requests．I have print the log in the python code, it shows no requests have received any more. There is no enough information to verify where the problem is, do you have any idea to display more information for debugging without hurt performance as the service is now online.   Until now there is only one instance has this problem.
