### ISSUE TITLE
triton_python_backend_utils's api document?

### ISSUE THREAD

**Issue by Jackiexiao** [triton-inference-server/server#4813]
is there any complete triton_python_backend_utils's api document?

I know there is 
- https://github.com/triton-inference-server/python_backend
- https://github.com/triton-inference-server/python_backend/blob/main/src/resources/triton_python_backend_utils.py

but none of them provide a detail and complete instruction about triton_python_backend_utils's api (maybe combind them both and we get one?)

for example, you can't find `pb_utils.Tensor.from_dlpack()` in `triton_python_backend_utils.py`; you can't find `pb_utils.serialize_byte_tensor()` and python_backend README

**Comment by rmccorm4** [comment]
Hi @Jackiexiao ,

I believe you're correct that the Python Backend README is the best documentation aside from looking at the code function definitions/comments directly as of today. 

CC @Tabrizian
