### ISSUE TITLE
Wrong behaviour of ensemble unloading using HTTP API

### ISSUE THREAD

**Issue by alxmamaev** [triton-inference-server/server#4828]
I have two models:
**Model A** - an ensemble of model B and preprocessing
**Model B** - the predictor model

**Model A** version policy for **model B** is `-1`, which means, that all time I want to use the latest version of model B in the pipeline. 

**Model B** version policy is `-1` too.

Triton server running in **explicit_mode**.

So I have my separate process worker which searches for a new model's versions and uploaded them into `model_repository`, when all model is uploaded, the worker restarts all updated models, in my case it just a **Model B**, because in fact **Model A** was not changed (config.pbtxt is not updated). For restart method `/load` from HTTP API is used.

**What happens next:**
* Triton unload **model B**
* Triton unload **model A** because **model B** is not available 
* Triton load new available version **model B**
*and that's all...*

**What i was expect**:
After the new version of **model B** is loaded, **model A** should load back.

**Comment by nv-kmcgill53** [comment]
cc @tanmayv25

**Comment by GuanLuo** [comment]
What is the Triton version that you use? And from the activities that you posted, are you unloading model B explicitly first? Or you call `load` directly and let Triton perform (re-)load?

**Comment by alxmamaev** [comment]
@GuanLuo Im using `nvcr.io/nvidia/tritonserver:22.07-pyt-python-py3`

Hm....
Probably yeah.  I should just remove the `unload` method. My fault. 
```python
    def restart_model(self, model_name: str) -> bool:
        response = requests.post(
            self.__triton_endpoint + f"/v2/repository/models/{model_name}/unload"
        )
        response = requests.post(
            self.__triton_endpoint + f"/v2/repository/models/{model_name}/load"
        )

        if not response.ok:
            raise ModelRestartError(model_name)
            
```

**Comment by alxmamaev** [comment]
Removed calling `/unload` everything works as expected. 

Thank you
