### ISSUE TITLE
README.md steps not working for me

### ISSUE THREAD

**Issue by jesuino** [triton-inference-server/server#4829]
**Description**
In README in "Serve a Model in 3 Easy Steps" section the step 3 fails for me with the following output:

```
root@localhost:/workspace# /workspace/install/bin/image_client -m densenet_onnx -c 3 -s INCEPTION /workspace/images/mug.jpg
expecting input to have 3 dimensions, model 'densenet_onnx' input has 4
```
From wireshark I can see that the request was not even sent, looks like it validates the request using a GET request to the model configuration.

I also tried with the other sample model, but looks like the image is not sent. This is the result I have:

```
root@localhost:/workspace# /workspace/install/bin/image_client -m inception_graphdef -c 3 -s INCEPTION /workspace/images/mug.jpg
expecting 1 input, got 0
```

Using wireshark I got the JSON sent, see [2]

**Triton Information**

The same from README

**To Reproduce**

Follow the steps from README

**Expected behavior**
Have the inference result

[1] 

```
{
   "name":"inception_graphdef",
   "platform":"tensorflow_graphdef",
   "backend":"tensorflow",
   "version_policy":{
      "latest":{
         "num_versions":1
      }
   },
   "max_batch_size":0,
   "input":[
      
   ],
   "output":[
      
   ],
   "batch_input":[
      
   ],
   "batch_output":[
      
   ],
   "optimization":{
      "priority":"PRIORITY_DEFAULT",
      "input_pinned_memory":{
         "enable":true
      },
      "output_pinned_memory":{
         "enable":true
      },
      "gather_kernel_buffer_threshold":0,
      "eager_batching":false
   },
   "instance_group":[
      {
         "name":"inception_graphdef",
         "kind":"KIND_CPU",
         "count":2,
         "gpus":[
            
         ],
         "secondary_devices":[
            
         ],
         "profile":[
            
         ],
         "passive":false,
         "host_policy":""
      }
   ],
   "default_model_filename":"model.graphdef",
   "cc_model_filenames":{
      
   },
   "metric_tags":{
      
   },
   "parameters":{
      
   },
   "model_warmup":[
      
   ]
}
```

**Comment by krishung5** [comment]
Hi @jesuino, I went through all the steps described in the README ["Serve a Model in 3 Easy Steps" section](https://github.com/triton-inference-server/server#serve-a-model-in-3-easy-steps) and was not able to reproduce this issue. From the JSON you got from wireshark, it seems like the model configuration is different from the one we provide [here](https://github.com/triton-inference-server/server/blob/main/docs/examples/model_repository/inception_graphdef/config.pbtxt). Could you confirm that the config files for the models are correct? Could you also provide the full server log by running server with flag `--log-verbose=1`?

**Comment by krishung5** [comment]
Thanks for confirming, @rnwang04. I followed the exact same commands you shared but still could not reproduce this issue. Filed a ticket for the team to investigate this further.

**Comment by dyastremsky** [comment]
Closing this issue and related ticket due to inactivity. The README has also been updated in the last year, so please let us know if you are still seeing this issue.
