### ISSUE TITLE
Is there any sort of C++ equivalent of the Python BLS in Triton?

### ISSUE THREAD

**Issue by avickars** [triton-inference-server/server#4838]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Just checking here if there is any sort of equivalent to the python backend's BLS in C/C++ on Triton?  We have a very complex pipeline that is currently working as a BLS, but we are experience significant performance issues that as of right now (still investigating a bit) appear to be the result bringing in python classes to keep track of objects as they flow through our pipeline.

**Comment by nv-kmcgill53** [comment]
Hi @avickars We have this implemented and here is an [example](https://github.com/triton-inference-server/backend/tree/main/examples/backends/bls).
