### ISSUE TITLE
Under high load, stateful batcher queues small batches

### ISSUE THREAD

**Issue by jamied157** [triton-inference-server/server#4841]
**Description**
I'm using a custom C++ backend to the Triton Server that runs using the stateful batcher with the oldest strategy. When testing this under a high load:

- num_clients : ~500
- max_batch_size : 64
- max_candidate_sequences: 128
- no queue_delay

We initially see quite good behaviour from the batcher (large batches, queued instantly one after the other). Eventually however, the batcher stops queueing requests and then starts queueing very small batches. It does eventually pick up again but performance never really reaches the same as the beginning. 

This might not help too much but we see this behaviour at the start (with TRITONBACKEND_ModelInstanceExecute running one after the other, this is batch size 64):
![Screenshot 2022-09-02 at 10 33 58](https://user-images.githubusercontent.com/16978470/188110648-42c34045-4a44-4190-a2a6-5123b4bc6df5.png)

Then as time goes on these stop and when we pick up again, batches are much smaller and have gaps:
![Screenshot 2022-09-02 at 10 35 47](https://user-images.githubusercontent.com/16978470/188110968-059831d9-d03d-4abb-ae54-1e172738dcfa.png)

It does eventually go back to batch_size 64 but then quickly drops off once more.

I'm wary that this behaviour is consistent with clients not spawning quickly enough to saturate the server, however increasing the number of clients to a large degree doesn't seem to help here at all.

Another point of interest is that eventually calls to `TRITONBACKEND_RequestRelease` end up being very slow (30ms), could this point at whatever the bottleneck on the server is? (EDIT: interestingly this seems to get worse over time, I can get 1000ms waiting for this call to finish, whereas the quickest requests will take <0.01ms)

If you have any tips on trying to understand what the state of the queue on the server is or what is going on in the grpc layer that would be appreciated as I'm that's where my suspicions lie. It could very well be some way we're not using the TRITONBACKEND api correctly but I think I'm following the instructions [here](https://github.com/triton-inference-server/backend/blob/main/README.md#decoupled-responses) correctly

**Triton Information**
What version of Triton are you using? 22.02

Are you using the Triton container or did you build it yourself?
We build triton ourselves however I think we see similar behaviour with the container (but haven't tried this much).

**To Reproduce**
I can't share the code we are running but depending on where you think the issue is I can try and simplify so I can share (although this might be some work). 

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
I've mentioned some of this above but to be clear:

- stateful batcher, oldest strategy
- num_clients: ~500
- custom c++ backend
- GRPC bidirectional streaming mode
- decoupled model

Thanks!

**Comment by tanmayv25** [comment]
@jamied157  Thanks for sharing your analysis. Can you share what is the length of your sequences on average? 
While releasing requests, [CompleteAndNext](https://github.com/triton-inference-server/core/blob/main/src/sequence_batch_scheduler.cc#L1564) function gets called to initiate a next request in the sequence.

It does have logic to keep retrying scheduling the next request till the seq slot is available. My guess is that more and more requests are waiting for their enqueuing their next request into the dynamic batcher. 
Can you try shorter sequences and share your feedback?

**Comment by tanmayv25** [comment]
@jamied157  Were you able to resolve the issue? If yes, then can you share your learning? I am going to close the ticket as there has been no response for last 14 days..

**Comment by jamied157** [comment]
Sorry for the late response on this, we did manage to resolve this. We were setting the `max_sequence_idle_microseconds` parameter in our config to a very large value (10^17) when we reduced this to something more reasonable, the bad behaviour went away. Not sure why this was the case though!
