### ISSUE TITLE
Ensemble scheduler parallel

### ISSUE THREAD

**Issue by manhtd98** [triton-inference-server/server#4845]
In ensemble use a step pipeline. But in many situations, we want to execute models parallel and concatenate the result, Did we plan to release it?
Old:
```
model1 - model2 - model3
```
New
```
model1  -----
                    |---- model3
model2  -----
```

**Comment by dyastremsky** [comment]
This is currently supported by ensemble models. For example, in [this](https://github.com/triton-inference-server/server/blob/main/docs/architecture.md#ensemble-models) example, the segmentation and classification models will both run once their input "preprocessed_image" is collected.

**Comment by manhtd98** [comment]
okey. i got it. thanks you for that
