### ISSUE TITLE
Question with client with cuda shared memory

### ISSUE THREAD

**Issue by avickars** [triton-inference-server/server#4850]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Small question here pertaining to using a client with cuda shared memory...I can see we register the memory handles with the Triton server, so I'm wondering if the Triton server is on the same node as the client (i.e. localhost) will it make a copy of the input when the request is made or will it simply access the same memory as the client?

Any clarification is greatly appreciated!

**Comment by Tabrizian** [comment]
Hi @avickars, It will access that mapped memory location. It will not make a copy of the data.

**Comment by avickars** [comment]
much appreciated, thank you!
