### ISSUE TITLE
how could I know the default value of model_config.proto

### ISSUE THREAD

**Issue by Jackiexiao** [triton-inference-server/server#4854]
this is a new baby question, how could I know the default value of every params in model_config.proto? I read through user document, but some of the default value is missing. or maybe I should read the source code?

https://github.com/triton-inference-server/common/blob/main/protobuf/model_config.proto

**Comment by dyastremsky** [comment]
Which default values are you looking for? The comments should have most of them. If they're missing, you could also try Googling "Triton <Param Name>" to find the documentation on them. If they're missing though, it's good to know to update the comments. You're welcome to fill out a Contributing License Agreement (CLA) and submit a PR for them as well. :)

**Comment by Jackiexiao** [comment]
oh thx, my mistake, you are right, I mistakenly thought that the proto files elsewhere were Triton's
