### ISSUE TITLE
strange coredump in libtritonserver.so

### ISSUE THREAD

**Issue by frankxyy** [triton-inference-server/server#4855]
I add one line of log in backend_model_instance.cc of triton core project. Like this below:
![image](https://user-images.githubusercontent.com/6971044/189088474-7e8959e9-5d11-4787-9042-45ab3ab0d032.png)

Then I build the triton core project and get libtritonserver.so. Then the server with the newly built libtritonserver.so meet coredump error when receiving a request to an ensemble model containing a bls model in the whole pipeline. However, If I request another ensemble model without a bls model，the coredump error will not happen. 

The coredump file analysis is as below. It seem that it has no relation with the position of code added.
![image](https://user-images.githubusercontent.com/6971044/189087290-21dd557b-3202-4bf3-8215-72abd607fba8.png)

What is the reason?

**Comment by krishung5** [comment]
Hi @frankxyy, does the ensemble model containing a bls model that you are running works with the original libtritonserver.so? Could you also share the the version of Triton you're using, and other [issue template](https://github.com/triton-inference-server/server/blob/main/.github/ISSUE_TEMPLATE/bug_report.md) information. Besides, building Triton with debug flag`-DCMAKE_BUILD_TYPE=Debug` may give us more information about the core dump.

**Comment by frankxyy** [comment]
hi @krishung5 ，the libtritonserver.so is built by myself after adding the one line of logging. The version of Triton is 22.07

**Comment by frankxyy** [comment]
I think i may find the reason. The original code of triton core in rate_limiter.cc，the `instance_index` variable is not initialized, which may cause the dequeueing of payload undefined. After setting a rarely large value, the core dump issue does not happen.

![image](https://user-images.githubusercontent.com/6971044/189515646-db6d5509-1aae-4f60-bc10-013c86695837.png)

**Comment by frankxyy** [comment]
Hello, how is the processing progress of this issue? Do I make the correct investigation?

**Comment by krishung5** [comment]
Hi @frankxyy, since the issue only occurs when using the modified `libtritonserver.so`, I think it would make more sense to investigate the part with new changes. One thing on the top off my head is that, when building the new core project, are you using the corresponding repo tag, 22.07 in your case, for other repos? Also, is adding that line of log the only changes you made to `backend_model_instance.cc`? There is some code [missing](https://github.com/triton-inference-server/core/blob/main/src/backend_model_instance.cc#L669-L684) from the screenshot you shared.
Besides, just a reminder that changing the value of `instance_index` will possibly affect the logic after that.

**Comment by frankxyy** [comment]
Hi @krishung5，I checked my code and confirm that all the depended projects are all set with repo tag 22.07， and the only change I made to the triton core project is adding the log.  

Maybe i didn't express clearly in my last post and you didn't get what I really want to discuss about. I will try to express deeper now. What I really want to ask is about the robustness of the logic in `RateLimiter::DequeuePayload` function.  As the `instance_index` in the original code is declared but not defined, the following logic after the declaration of variable `instance_index` may run into coredump error in some circumstances. For example, if the `instance_index` is instantialized with value 0. If in https://github.com/triton-inference-server/core/blob/main/src/rate_limiter.cc#L186 , variable `empty` gets false, then the program will run into the if

**Comment by krishung5** [comment]
I see. Thanks for the further explanation, @frankxyy. I have filed ticket DLIS-4165 for us to further investigate this.
cc @tanmayv25

**Comment by frankxyy** [comment]
Hello @krishung5 , I want to know about the progress of the investigation of this issue. Thank you a lot!

**Comment by tanmayv25** [comment]
@frankxyy  Looks like you are onto something. An unitialized instance_index poses a risk that a random instance_index might actually be less than the number of instances available.
For N model instances the chances of seeing this error is: `N / 65535` 

I am assuming that is why we don't see this error that often. I will raise a PR to fix the issue.
