### ISSUE TITLE
question about the priority in ratelimiter

### ISSUE THREAD

**Issue by sydnash** [triton-inference-server/server#4856]
**Description**

`Priority serves as a weighting value to be used for prioritizing across all the instances of all the models. An instance with priority 2 will be given 1/2 the number of scheduling chances as an instance with priority 1.`

The document of [Rate Limiter Configuration: priority](https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#priority) says that the rate limit priority config is control instance's priority across all models. But in the core code, i only found a priority_queue in the ModelContext, it look like that the rate limit priority only control the instance priority in the same model.
<img width="792" alt="image" src="https://user-images.githubusercontent.com/5484932/189116237-647c649f-a6bd-4492-9174-ecefbd93627d.png">

could some one give me some information about the implementation of the global priority control of model instance cross all models.

**Comment by krishung5** [comment]
CC @tanmayv25

**Comment by tanmayv25** [comment]
@sydnash `avbl_instances_` are the instances that are available for the model. All model instances from different models goes through a global priority_queue called staged_instances_. This is how global priority is maintained across all models.

**Comment by sydnash** [comment]
thanks, I got it.

**Comment by sydnash** [comment]
I understand, thanks for your reply.
