### ISSUE TITLE
too many open files

### ISSUE THREAD

**Issue by wdongdongde** [triton-inference-server/server#4880]
**Description**
after running few days, there are so many tcp connection,and finally stop accepting requests.
<img width="244" alt="image" src="https://user-images.githubusercontent.com/44493076/190049694-c6a0e7e9-5506-4fdc-a236-e2fcb98f7cd4.png">

<img width="527" alt="image" src="https://user-images.githubusercontent.com/44493076/190049459-796e0f51-e1e9-494b-a631-85cfc836f64c.png">

**Triton Information**
What version of Triton are you using?

<img width="528" alt="image" src="https://user-images.githubusercontent.com/44493076/190049743-68e65e7d-1e53-4222-b314-659d63750d2b.png">

there are three python backend models and one pytorch model

**To Reproduce**
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**

**Comment by kthui** [comment]
Hi @wdongdongde, I have filed a ticket for us to investigate further.

In the meantime, can you provide us with more information:
- Which OS (and version) are you using?
- Are you connecting to the server using HTTP or GRPC or both?
- Can you try with our later release (`docker pull nvcr.io/nvidia/tritonserver:22.08-py3`) and see if you still experience the same problem?

**Comment by tanmayv25** [comment]
@wdongdongde Please provide detailed steps for reproducing the issue. There are no details in the issue that you have filed.

**Comment by jbkyang-nvi** [comment]
@wdongdongde can you provide a small reproducible example for the client?

**Comment by jbkyang-nvi** [comment]
Closing ticket because of inactivity. @wdongdongde please reopen with more information if you would like us to look at it

**Comment by wdongdongde** [comment]
it is the caused by nginx , not triton
