### ISSUE TITLE
image_client.py does not get enough responses from server

### ISSUE THREAD

**Issue by sydat2701** [triton-inference-server/server#4881]
Hi guys, 
I have tried triton server with faster_rcnn model. And I have converted my model to ONNX runtime and checked that it returns the right results after converting (each includes bounding boxes, labels and scores. Ex, **[array([[ 67.68038,  72.15044,  85.44873, 102.64761],
       [ 66.53554, 131.09807,  83.9924 , 161.73106]], dtype=float32), array([1, 1], dtype=int64), array([0.83638126, 0.7957209 ], dtype=float32)]**). But client (image_client) does not receive enough those results. It only contains a score in output response likes **[[b'0.832606:0']]** when I print the response from server. My config file and response received from server can be seen below. Someone can help me? Thank for your help!

--------------------------------------response received from server (printed as dict) --------------------------------------
{'_result': {'id': '1', 'model_name': 'faster_rnn', 'model_version': '1', 'outputs': [{'name': '3177', 'datatype': 'BYTES', 'shape': [1, 1], 'parameters': {'binary_data_size': 14}}]}, '_output_name_to_buffer_map': {'3177': 0}, '_buffer': bytearray(b'\n\x00\x00\x000.832606:0')}

------------------------------------config file------------------------------------------------------
name: "faster_rnn"
platform: "onnxruntime_onnx"
max_batch_size : 4
input [
  {
    name: "input"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, -1, -1 ]
  }
]
output [
  {
    name: "boxes"
    data_type: TYPE_FP32
    dims: [ -1, 4 ]
  },
  {
    name: "labels"
    data_type: TYPE_INT64
    dims: [ -1, 1 ]
  },
  {
    name: "scores"
    data_type: TYPE_FP32
    dims: [ -1, 1 ]
  },
],

/* I tried changing name "labels", "boxes", etc. to "3177", "3178", etc. but the results were still the same  */

**Comment by kthui** [comment]
Hi @sydat2701, can you retrieve the model configuration from the server after the model is loaded? This might explain why there is a "3177" output.
The configuration can be retrieved via HTTP with a utility like "curl": `$ curl localhost:8000/v2/models/<model name>/config`. In your case, it might be `$ curl localhost:8000/v2/models/faster_rnn/config`

CC @tanmayv25 @GuanLuo

**Comment by sydat2701** [comment]
> Hi @sydat2701, can you retrieve the model configuration from the server after the model is loaded? This might explain why there is a "3177" output. The configuration can be retrieved via HTTP with a utility like "curl": `$ curl localhost:8000/v2/models/<model name>/config`. In your case, it might be `$ curl localhost:8000/v2/models/faster_rnn/config`
> 
> CC @tanmayv25 @GuanLuo

Thank kthui, this is model configuration I retrieved by your suggestion. I change my current conf file to this but the response was still the same.

_{"name":"faster_rnn","platform":"onnxruntime_onnx","backend":"onnxruntime","version_policy":{"latest":{"num_versions":1}},"max_batch_size":4,"input":[{"name":"input","data_type":"TYPE_FP32","format":"FORMAT_NONE","dims":[3,256,256],"is_shape_tensor":false,"allow_ragged_batch":false,"optional":false}],"output":[{"name":"3177","data_type":"TYPE_FP32","dims":[1],"reshape":{"shape":[]},"label_filename":"","is_shape_tensor":false},{"name":"3178","data_type":"TYPE_INT64","dims":[1],"reshape":{"shape":[]},"label_filename":"","is_shape_tensor":false},{"name":"output","data_type":"TYPE_FP32","dims":[4],"label_filename":"","is_shape_tensor":false}],"batch_input":[],"batch_output":[],"optimization":{"priority":"PRIORITY_DEFAULT","input_pinned_memory":{"enable":true},"output_pinned_memory":{"enable":true},"gather_kernel_buffer_threshold":0,"eager_batching":false},"dynamic_batching":{"preferred_batch_size":[4],"max_queue_delay_microseconds":0,"preserve_ordering":false,"priority_levels":0,"default_priority_level":0,"priority_queue_policy":{}},"instance_group":[{"name":"faster_rnn","kind":"KIND_GPU","count":1,"gpus":[0],"secondary_devices":[],"profile":[],"passive":false,"host_policy":""}],"default_model_filename":"model.onnx","cc_model_filenames":{},"metric_tags":{},"parameters":{},"model_warmup":[]}_

**Comment by kthui** [comment]
Can you check if the config file is named correctly and placed at the right location? The model repository should have the layout in [this doc](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/model_repository.md#repository-layout). One way to quickly check that is to remove the config file, and start the server. Then, retrieve the model configuration from the server, and check if it remains the same before the config file is removed. If they are the same, then the config file is being ignored and might simply due to it being named incorrectly or placed at the wrong location.
