### ISSUE TITLE
Splitting a batch of images into small batches for different instances.

### ISSUE THREAD

**Issue by sandesha-hegde** [triton-inference-server/server#4888]
**Is your feature request related to a problem? Please describe.**
If I have a multiple model instances but sending single request with batch of images are not splitting into smaller batches for multiple instances instead it gets processed by single instance itself.

**Describe the solution you'd like**
If I send a request of batch of 8 images and I have two model instance, it should divide into two batches of 4 and should distribute among two instances and gets processed parallely.

**Describe alternatives you've considered**
For now splitting batches into smaller batches in client side and sending multiple request using threads.
**Additional context**
Please let me if the feature is already exist.

**Comment by jbkyang-nvi** [comment]
Hi, this feature currently does not exist. You can maybe split the batched requests to smaller chunks in the client(since you know how many instances exist). If too many requests are sent, Triton can batch them together to optimize
