### ISSUE TITLE
Parameter CPU_THREADS_NUM setting bug in openvino_backend

### ISSUE THREAD

**Issue by handoku** [triton-inference-server/server#4899]
**Description**

Parameter `CPU_THREADS_NUM` setting doesn't work well in practice.
Set `CPU_THREADS_NUM` = `any reasonable value` will result in only one cpu-core being used to do openvino inference
```
parameters: {
key: "CPU_THREADS_NUM"
value: {
string_value:"8"
}
}
```
![image](https://user-images.githubusercontent.com/16758743/191234715-7f71bb8d-9c91-4e65-bc48-980d8cfec499.png)

Remove `CPU_THREADS_NUM` setting , then 4 (why 4?) cpu-cores will be busy.
![image](https://user-images.githubusercontent.com/16758743/191234527-8c0063c1-6259-415d-8ea1-ee4ea56e07a6.png)

**Triton Information**
What version of Triton are you using?
Are you using the Triton container or did you build it yourself?

ngc image `tritonserver:2208-py3`

**To Reproduce**
Steps to reproduce the behavior.

Put this  [test_model](https://drive.google.com/file/d/1tVLnJUGeY3ugoSu_JjT7xugoS7PKoioP/view?usp=sharing) under model_repository, start tritonserver, and send request through perf_client.
```bash
./perf_client -m test_model --percentile=95 --concurrency-range 8 -i grpc -u localhost:8001
```

**Comment by rmccorm4** [comment]
@kthui can you take a look?

**Comment by handoku** [comment]
seems like the effect of `auto` value of `CPU_THROUGHPUT_STREAMS` parameter;
after set `CPU_THROUGHPUT_STREAMS` = `1`, all things seem right. 

thus, Im closing this issue.

**Comment by hyrmec** [comment]
I ran into a similar issue.
But I noticed something interesting:
when running the container locally - excellent performance, 
but if I run k8s in production - openvino backend does not use all available resources, it uses 1 core.

**Comment by handoku** [comment]
> @handoku Hello! I ran into a similar issue. But I noticed something interesting: when running the container locally - excellent performance, but if I run k8s in production - openvino backend does not use all available resources, it uses 1 core.
> 
> ngc image: tritonserver:23.07-py3
> 
> Experimented with different settings: INFERENCE_NUM_THREADS = 1,2,3,4,5 NUM_STREAM = AUTO, NUMA

try setting NUM_STREAM=1

**Comment by hyrmec** [comment]
UNAVAILABLE state: Invalid argument: expected the parameter 'NUM_STREAMS' to be either AUTO/NUMA, got 1;

**Comment by handoku** [comment]
@hyrmec do you have tried just remove NUM_STREAMS setting? I havn't using openvino backend for a long time. I am not aware of what difference that OVI v2.0 brought. Maybe you can ask  intel [there](https://github.com/openvinotoolkit/openvino/issues) for help
