### ISSUE TITLE
Broken metrics link in the backend example

### ISSUE THREAD

**Issue by taneem-ibrahim** [triton-inference-server/server#4904]
**Description**
The metrics[ link](https://github.com/triton-inference-server/server/blob/main/docs/metrics.md) is broken (HTTP 404) in the backend example [readme](https://github.com/triton-inference-server/backend/tree/main/examples#recommended-triton-backend).

**Triton Information**
What version of Triton are you using?
N/A
Are you using the Triton container or did you build it yourself?
N/A
**To Reproduce**
N/A

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**
The link should be accessible.

**Comment by rmccorm4** [comment]
Hi @taneem-ibrahim,

Thanks for pointing this out. We recently had a doc restructure on the server repo and will need to update links in other repos accordingly. I'll take a look at these backend links this week.
