### ISSUE TITLE
module 'triton_python_backend_utils' has no attribute 'Logger'

### ISSUE THREAD

**Issue by vkotturu** [triton-inference-server/server#4908]
**Description**
I want to add logging to debug my code so i followed https://github.com/triton-inference-server/python_backend#logging.
But i get the error: 
     module 'triton_python_backend_utils' has no attribute 'Logger'

**Triton Information**
What version of Triton are you using? nvcr.io/nvidia/tritonserver:22.07-py3

Are you using the Triton container or did you build it yourself? Triton container

**To Reproduce**
Steps to reproduce the behavior. 

import triton_python_backend_utils as pb_utils
logger = pb_utils.Logger

**Expected behavior**
Get logging

**Comment by jbkyang-nvi** [comment]
Hello @vkotturu where are you adding the logging? Can you share the model.py you are using?

**Comment by krishung5** [comment]
Hi @vkotturu, the logger support is scheduled for the 22.09 release, which is coming soon. To use the logger right now, you need to compile Python backend from source.

**Comment by vkotturu** [comment]
Understood, thanks.
