### ISSUE TITLE
Bytes/String Datatype golang grpc client example

### ISSUE THREAD

**Issue by safehumeng** [triton-inference-server/server#4916]
use Python with http:
        input_array = np.array([sentence.encode('UTF-8')], dtype=object)
        input_array = input_array.reshape(-1, 1)
        inputs = [httpclient.InferInput(input_name, input_array.shape, input_dtype)]
        inputs[0].set_data_from_numpy(input_array)
Can you provide an example for golang with grpc

**Comment by jbkyang-nvi** [comment]
We don't have full support of Go right now. We do have one example of go here: https://github.com/triton-inference-server/client/blob/main/src/grpc_generated/go/grpc_simple_client.go

**Comment by deadspacewii** [comment]
please，how many times can we have a go client, we are waiting

**Comment by jbkyang-nvi** [comment]
@deadspacewii we do have a go client. However it is not fully fledged. If you would like, please contribute to the repo for the go client. It is currently in the backlog for us now

**Comment by safehumeng** [comment]
> ```
> 	inferInputs := []*triton.ModelInferRequest_InferInputTensor{
> 		&triton.ModelInferRequest_InferInputTensor{
> 			Name:     "INPUT0",
> 			Datatype: "BYTES",
> 			Shape: []int64{1},
> 			Contents: &triton.InferTensorContents{
> 				ByteContents: [][]byte{[]byte(yourInput)},
> 			},
> 		},
> 	}
> ```
> 
> This is an example as to how you would send a string as bytes to the server

thanks! I just write an example to parse string as bytes:
  // Serialize the strings into a "raw" buffer. The first 4-bytes are
  // the length of the string length. Next are the actual string
  // characters. There is *not* a null-terminator on the string.
func Preprocess(inputStrList[]string, batchSize int) []byte {

	var inputStrBytes []byte
	// Temp variable to hold our converted int64 -> []byte
	bs := make([]byte, 4)
	for b := 0; b < batchSize; b++ {
		inputStr := inputStrList[b]
		strBytes := []byte(inputStr)
		strCap := len(inputStr)
		binary.LittleEndian.PutUint32(bs, uint32(strCap))
		fmt.Println(inputStrBytes)
		inputStrBytes = append(inputStrBytes, bs...)
		fmt.Println(inputStrBytes)
		for i := 0; i < strCap; i++ {
			inputStrBytes = append(inputStrBytes, strBytes[i])
		}
	}
	return inputStrBytes
}

**Comment by safehumeng** [comment]
> We don't have full support of Go right now. We do have one example of go here: https://github.com/triton-inference-server/client/blob/main/src/grpc_generated/go/grpc_simple_client.go
> 
> If you create an example of object and not just int32 you are welcome to contribute to the repo!



> We don't have full support of Go right now. We do have one example of go here: https://github.com/triton-inference-server/client/blob/main/src/grpc_generated/go/grpc_simple_client.go
> 
> If you create an example of object and not just int32 you are welcome to contribute to the repo!

I make a merge request:
https://github.com/triton-inference-server/client/pull/171
please review it
