### ISSUE TITLE
[Tensorflow Backend] | [Segfault, intermittent] | Unloading model on GPU results in a segfault i.e. tritonserver crashes

### ISSUE THREAD

**Issue by nskool** [triton-inference-server/server#4924]
**Description**
1. A TF model  on GPU, with platform `tensorflow_savedmodel` and config.pbtxt as below can be loaded successfully. However, when 'unloaded', the model sometimes segfaults. 
2. In successful cases, the control reaches dynamic_batch_scheduler, line 424:
```
I0926 05:03:17.456410 1 dynamic_batch_scheduler.cc:424] Stopping dynamic-batcher thread for llSh...
I0926 05:03:17.456567 1 model_lifecycle.cc:578] successfully unloaded '7891' version 1
```
3. In segfault case, the control terminates before that
```
I0926 05:49:43.401011 1 backend_model_instance.cc:765] Starting backend thread for model_0 at nice 0 on device 3...
I0926 05:49:43.401346 1 model_lifecycle.cc:693] successfully loaded 'model' version 1
I0926 05:49:43.401352 1 dynamic_batch_scheduler.cc:281] Starting dynamic-batcher thread for model at nice 0...
I0926 05:49:45.850504 1 http_server.cc:3369] HTTP request: 2 /v2/repository/models/model/unload
I0926 05:49:45.850761 1 backend_model_instance.cc:788] Stopping backend thread for model_0...
I0926 05:49:45.850836 1 tensorflow.cc:2729] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0926 05:49:45.850943 1 backend_model_instance.cc:788] Stopping backend thread for model_0...
I0926 05:49:45.851018 1 tensorflow.cc:2729] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0926 05:49:45.851094 1 backend_model_instance.cc:788] Stopping backend thread for model_0...
I0926 05:49:45.851168 1 tensorflow.cc:2729] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0926 05:49:45.851220 1 backend_model_instance.cc:788] Stopping backend thread for model_0...
I0926 05:49:45.851287 1 tensorflow.cc:2729] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0926 05:49:45.851331 1 tensorflow.cc:2668] TRITONBACKEND_ModelFinalize: delete model state
Signal (11) received.
 0# 0x00005599374ADD79 in tritonserver
 1# 0x00007FCE8F740090 in /usr/lib/x86_64-linux-gnu/libc.so.6
 2# 0x00007FCE8F8889D3 in /usr/lib/x86_64-linux-gnu/libc.so.6
 3# std::basic_streambuf<char, std::char_traits<char> >::xsputn(char const*, long) in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 4# std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long) in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 5# 0x00007FCE901F6578 in /opt/tritonserver/bin/../lib/libtritonserver.so
 6# 0x00007FCE8FB31DE4 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 7# 0x00007FCE905DE609 in /usr/lib/x86_64-linux-gnu/libpthread.so.0
 8# clone in /usr/lib/x86_64-linux-gnu/libc.so.6
```

```
name: "model"
platform: "tensorflow_savedmodel"
max_batch_size: 64
input {
    name: "input_1"
    data_type: TYPE_FP32
    format: FORMAT_NHWC
    dims: [224, 224, 3]
}
output {
    name: "probs"
    data_type: TYPE_FP32
    dims: 1000
}
default_model_filename: "model"
instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]
```

**Triton Information**
What version of Triton are you using? 22.08 (can be reproduced with 22.07 as well)

Are you using the Triton container or did you build it yourself? Used the triton container, as well as did a custom build with just tensorflow backend

**To Reproduce**
1. Download the model [link](https://torchserve.s3.amazonaws.com/tar_gz_files/tritonserver/model.tar.gz) and untar it to any location e.g. `/opt/ml/models/7891`, directory structure is shared below:
```
(venv) ubuntu@ip-172-31-44-91:/opt/ml/models/7891$ tree
.
└── model
    ├── 1
    │   └── model
    │       ├── assets
    │       ├── saved_model.pb
    │       └── variables
    │           ├── variables.data-00000-of-00002
    │           ├── variables.data-00001-of-00002
    │           └── variables.index
    └── config.pbtxt

5 directories, 5 files
```
2. Run triton server as (change the `tritonserver:latest` image to 22.07 or 22.08 image as necessary):
```
 docker run --gpus all -v /opt/ml/models:/opt/ml/models --rm -p8000:8000 -p8001:8001 -p8002:8002 -p8080:8080 tritonserver:latest tritonserver --allow-sagemaker=false --allow-grpc=false --allow-http=true --allow-metrics=false --model-control-mode=explicit --model-repository=/opt/ml/models/7891 --sagemaker-port=8080 --log-verbose true 
```
3. Load the model using REST API: `curl -w "%{http_code}" -X POST http://0.0.0.0:8000/v2/repository/models/model/load`. Note that model name is `model`. This returns 200
4. Unload the model as: `curl -w "%{http_code}" -X POST http://0.0.0.0:8000/v2/repository/models/model/unload`. This *may* succeed, however, if you load-unload a few times, you may hit the segfault issue. Note that even during the segfault, the http response code is 200. However, the tritonserver crashes.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**
1. Unload should be successful at all times.

**Comment by dyastremsky** [comment]
Thank you for your detailed bug report, Nikhil. We have filed a ticket to investigate.

**Comment by tanmayv25** [comment]
I have been able to reproduce the issue. It appears to be coming from one of the verbose log in `BatcherThread()` function.
Most likely there should be no segfault if you drop `--log-verbose true`.

We are working on the fix.

**Comment by Lingkar** [comment]
I think I got the same issue with the ONNX Runtime, occasionally when unloading models. Correct?
`
I1027 09:37:21.248069 1 model_lifecycle.cc:578] successfully unloaded 'CIFAR10ResNet' version 3
 0# 0x000056206E4721E9 in tritonserver
 1# 0x00007F1026420090 in /lib/x86_64-linux-gnu/libc.so.6
 2# 0x00007F1026CE6DEF in /opt/tritonserver/bin/../lib/libtritonserver.so
 3# 0x00007F1026D3D791 in /opt/tritonserver/bin/../lib/libtritonserver.so
 4# 0x00007F1026E006C0 in /opt/tritonserver/bin/../lib/libtritonserver.so
 5# TRITONSERVER_ServerInferAsync in /opt/tritonserver/bin/../lib/libtritonserver.so
 6# 0x000056206E4A0964 in tritonserver
 7# 0x000056206E4A12E5 in tritonserver
 8# 0x00007F1026811DE4 in /lib/x86_64-linux-gnu/libstdc++.so.6
 9# 0x00007F1027B8C609 in /lib/x86_64-linux-gnu/libpthread.so.0
10# clone in /lib/x86_64-linux-gnu/libc.so.6`

@tanmayv25 Just tried out with --log-verbose true, but get the following error:
`0# 0x000055BEACFDA1E9 in tritonserver
 1# 0x00007F3E61453090 in /lib/x86_64-linux-gnu/libc.so.6
 2# 0x00007F3E6159B9C5 in /lib/x86_64-linux-gnu/libc.so.6
 3# std::basic_streambuf<char, std::char_traits<char> >::xsputn(char const*, long) in /lib/x86_64-linux-gnu/libstdc++.so.6
 4# std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long) in /lib/x86_64-linux-gnu/libstdc++.so.6
 5# 0x00007F3E61D1AC38 in /opt/tritonserver/bin/../lib/libtritonserver.so
 6# 0x00007F3E61844DE4 in /lib/x86_64-linux-gnu/libstdc++.so.6
 7# 0x00007F3E62BBF609 in /lib/x86_64-linux-gnu/libpthread.so.0
 8# clone in /lib/x86_64-linux-gnu/libc.so.6`

**Triton information**
nvcr.io/nvidia/tritonserver:22.09-py3

**Comment by tanmayv25** [comment]
@Lingkar you have to drop that cli option hence disabling the verbose logging. Yes, the verbose log statement that emits the segfault is a part of core triton and all backends will suffer from the segfault.
