### ISSUE TITLE
tritonclient with pycuda integration

### ISSUE THREAD

**Issue by haritsahm** [triton-inference-server/server#4930]
**Is your feature request related to a problem? Please describe.**
When using cudashm, tritonclient only support reading/writing data using numpy. Is there a way to utilize pycuda pagelocked memory or pycuda GPUArray instead of numpy as the input/output to tritonclient?  I think there is a way to utilize pycuda with the raw cudaIPC handle but I think it would be great if the method is provided here.

**Describe the solution you'd like**
- When using grpc with cudashm, `set_shared_memory_region` can handle both numpy and pycuda's pagelocked/gpuarray.
- When retrieving the output with cudashm, a method `cudashm.get_content_from_device` to get data from shared memory to pycuda's pagelocked/gpuarray.

**Comment by nv-kmcgill53** [comment]
@tanmayv25  Is this something which we want to file a ticket for?

**Comment by jbkyang-nvi** [comment]
@haritsahm what is the use case here? Can you explain a bit why you would prefer to use pycuda pagelocked memory or pycuda GPUArray instead of using numpy? Are you using CUDA on the client side as well?

**Comment by 111qqz** [comment]
Any updates? I also encountered the same problem.
My use case is that the input data is already on the GPU.
If set_shared_memory_region can only receive numpy data, there will be additional data copies of gpu->cpu, cpu->gpu

> @haritsahm what is the use case here? Can you explain a bit why you would prefer to use pycuda pagelocked memory or pycuda GPUArray instead of using numpy? Are you using CUDA on the client side as well?

**Comment by haritsahm** [comment]
@111qqz I decided to use numpy for now. The main reason I opened the issue is the same as you, I tried to avoid to additional gpu-cpu copies because the data is inside gpu device

**Comment by 111qqz** [comment]
> @111qqz I decided to use numpy for now. The main reason I opened the issue is the same as you, I tried to avoid to additional gpu-cpu copies because the data is inside gpu device

I did some research and found that there is a set_shared_memory_region_from_dlpack in the latest triton client code that meets my needs. I've verified that this function works and everything seems to work. You can refer to  [set_shared_memory_region_from_dlpack](https://github.com/triton-inference-server/client/blob/main/src/python/library/tritonclient/utils/cuda_shared_memory/__init__.py#L326)

**Comment by haritsahm** [comment]
@111qqz thank you for the information, I'll try it later
