### ISSUE TITLE
Failed to process the request(s) for model '***', message: error: unpack_from requires a buffer of at least 578635587 bytes for unpacking 578486289 bytes at offset 149298 (actual buffer size is 242891) At:   /opt/tritonserver/backends/python/triton_python_backend_utils.py(116): deserialize_bytes_tensor

### ISSUE THREAD

**Issue by wdongdongde** [triton-inference-server/server#4931]
**Description**
Failed to process the request(s) for model '***', message: error: unpack_from requires a buffer of at least 578635587 bytes for unpacking 578486289 bytes at offset 149298 (actual buffer size is 242891)
At:
  /opt/tritonserver/backends/python/triton_python_backend_utils.py(116): deserialize_bytes_tensor

**Triton Information**
What version of Triton are you using?
nvcr.io/nvidia/tritonserver:22.05-py3

Are you using the Triton container or did you build it yourself?
container

**To Reproduce**

a python backend model, which use prophet to predict time series, on one machine, the container can use 5 cpus
use java client to request, when the request is up to 60/s, the logs occur this error and another -timeout
![image](https://user-images.githubusercontent.com/44493076/192757661-e73f319e-e98c-4b08-9027-18529ffdfb5c.png)

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
model config is:
name: "prophet"
backend: "python"
max_batch_size: 0
input [
    {
    name: "POINT_NUM"
    data_type: TYPE_UINT32
    dims: [ 1 ]
  }
]

input [
    {
    name: "TYPE"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]

input [
    {
    name: "INTERVAL"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]

input [
  {
    name: "TIMESERIES"
    data_type: TYPE_STRING
    dims: [-1, 2]
  }
  ]

  input [
    {
    name: "NOW_TIME"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]

  input [
    {
    name: "PARAMS"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]

  input [
    {
    name: "META"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]

output[
{
    name: "CODE"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]

parameters: {
  key: "EXECUTION_ENV_PATH",
  value: {string_value: "$$TRITON_MODEL_DIRECTORY/prophetProject.tar.gz"}
}

instance_group [
{
  count: 1
  kind: KIND_CPU
}
]

**Comment by dyastremsky** [comment]
Thanks for your detailed request. Which Java client are you using here? How are you starting it?

This looks to be an issue with string serialization/deserialization. Can you provide reproduction instructions? If you'd rather not share your model/script, we'd need a sample model and script, plus commands you are using to run it.

**Comment by oandreeva-nv** [comment]
Closing due to the lack of activity. @wdongdongde feel free to follow up if this issue is still relevant and we will re-open this thread.
