### ISSUE TITLE
Deploy triton model on multiple nodes

### ISSUE THREAD

**Issue by BDHU** [triton-inference-server/server#4936]
I'm following the example provided in this [post](https://developer.nvidia.com/blog/deploying-gpt-j-and-t5-with-fastertransformer-and-triton-inference-server/?nvid=nv-int-txtad-393407-vt27#cid=an01_nv-int-txtad_en-us). I'm able to deploy the model on 4 GPUs in a single node. I want to test the performance when deploy the model onto 2 nodes, each with 4 GPUs (8 GPUs in total). I'm not able to find many resources explaining deploying models on multiple nodes. Any help would be appreciated!

**Comment by dyastremsky** [comment]
Thank you for your question. Triton only supports multi-node inference via the Faster Transformer backend. You can find a deployment guide and its resources in that repository: https://github.com/triton-inference-server/fastertransformer_backend

I see some questions discussing GPT-J there, so hopefully that should help with your use case! Good luck.
