### ISSUE TITLE
Simultaneous execution and dynamic batching

### ISSUE THREAD

**Issue by avaAdam** [triton-inference-server/server#4940]
Hi!

Can someone point me to more documentation on simultaneous execution and dynamic batching? 

Does simultaneous execution refer to the instance groups configuration? 

It also seems like converting models from Tf2 to TensorRT has lost support for dynamic batching.

**Comment by dyastremsky** [comment]
Dynamic batching: https://github.com/triton-inference-server/server/blob/main/docs/user_guide/model_configuration.md#dynamic-batcher

What do you mean by simultaneous execution? Did you read that somewhere? It sounds like you are talking about instance groups. More information here: https://github.com/triton-inference-server/server/blob/3589c2c72d249392809fe9ae3de8057fe0437135/docs/user_guide/architecture.md#concurrent-model-execution

Dynamic batching should be fine for TensorRT models. It's a scheduling mechanism within Triton, so it only has to do with the model insofar as your model needing to be able to support batching. The batch dimension is the first dimension, so your model needs to be able to handle requests batched on the first dimension.

**Comment by avaAdam** [comment]
Thank you for replying so fast!

We did run some tests with instance groups. We did not see a change in latency or throughput. Please let me know what config/specs/logs/etc that you may need. I am happy to provide them.

**Comment by dyastremsky** [comment]
Have you tried running [perf_analyzer](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/perf_analyzer.md) with your configurations? Adding instance groups is typically useful when you have requests queued up not being served (i.e. high queue time). If one model instance is serving all your models as soon as they come in, then you shouldn't see a latency or throughput change.

You could also run `nvidia-smi` to check GPU utilization and memory usage. And you could check CPU usage as well. If any of the values are closer to 100%, that could slow things down, but it doesn't sound like that's the case if your latency and throughput are the same.

If one model instance is enough to handle all your requests, then adding more won't do anything. Then you'd look at things like model-specific/backend-specific optimizations, dynamic batching (latency vs throughput tradeoff), using the C-API, using shared memory, etc.

**Comment by avaAdam** [comment]
thank you! I will try your suggestions! I think that wraps up this question nicely.
