### ISSUE TITLE
 Failed to create environment directory for '/tmp/python_env_QNQ3ug/5'

### ISSUE THREAD

**Issue by wdongdongde** [triton-inference-server/server#4955]
**Description**
<img width="1233" alt="image" src="https://user-images.githubusercontent.com/44493076/194701622-c3c80793-2874-4eff-bfc4-522d05496e63.png">

**Triton Information**
What version of Triton are you using? 22.05-py3

Are you using the Triton container or did you build it yourself? container

**To Reproduce**
Steps to reproduce the behavior.

![image](https://user-images.githubusercontent.com/44493076/194701671-79df04e0-bb08-4250-a3d8-6ed344d74f98.png)

![image](https://user-images.githubusercontent.com/44493076/194701715-5251a933-91da-473e-abc0-8f5c4c496500.png)

when use multiple versions the error occured

**Comment by wdongdongde** [comment]
yes, when using single version of the model, the problem will not occur.  I do not know how to use absolute path when the model repository is in aws s3.

If i do not use my own python env, there is no problem even using multi versions model. the full command is: 

docker run --env AWS_ACCESS_KEY_ID=* --env AWS_DEFAULT_REGION=us-west-1 --env AWS_SECRET_ACCESS_KEY=* --cpus=5 --rm -dit -p8000:8000 -p8001:8001 -p8002:8002  --shm-size 1g nvcr.io/nvidia/tritonserver:22.05-py3 tritonserver --model-control-mode poll --repository-poll-secs 60 --log-info true --log-warning true --log-error true --model-repository=s3://*

**Comment by krishung5** [comment]
Thanks for the clarification. Filed a ticket for further investigation.

**Comment by wdongdongde** [comment]
there is a problem in the python environment

**Comment by ukey7240** [comment]
How was this problem solved?

**Comment by katerinamerkulova** [comment]
@ukey7240 In short, when using conda-pack with Python >= 3.10, it's essential to add flags `--ignore-missing-files --exclude lib/python3.1`. Otherwise, you may encounter issues with archiving or unarchiving. For more details, check out [this issue](https://github.com/conda/conda-pack/issues/244#issuecomment-1361094094).
