### ISSUE TITLE
Unable to load custom YOLOX model with CPU only mode - failed to stat file

### ISSUE THREAD

**Issue by daocunyang** [triton-inference-server/server#4957]
Hi, I'm trying to use Triton (server version `2.26.0`) for my custom YOLOX model using CPU (no GPU) on my Macbook Pro.

I'm using the following command:
`docker run -it --rm -p8000:8000 -p8001:8001 -p8002:8002 -v /Users/Darren/Desktop/Development/Nvidia/Triton/model_repository:/models nvcr.io/nvidia/tritonserver:22.09-py3 tritonserver --model-repository=/models` 

And Triton failed to load the model, with the following error:
`E1010 00:39:51.711103 1 model_lifecycle.cc:596] failed to load 'yolox_onnx' version 1: Internal: failed to stat file /models/yolox_onnx/1/model.onnx`

Can anyone help understand this error? I tried searching for it but haven't found any related info. Thanks in advance.

**Comment by dyastremsky** [comment]
The error is saying that it's not finding a file at /models/yolox_onnx/1/model.onnx, where it expects to find your ONNX model. It could be worthwhile to `docker run -it... bash` to check to see if the file exists there in your container.

**Comment by daocunyang** [comment]
> The error is saying that it's not finding a file at /models/yolox_onnx/1/model.onnx, where it expects to find your ONNX model. It could be worthwhile to `docker run -it... bash` to check to see if the file exists there in your container.

Thanks for helping. I got it resolved. :)
