### ISSUE TITLE
The results returned by the interface can be customized

### ISSUE THREAD

**Issue by yinghaodang** [triton-inference-server/server#4971]
Using Triton, I got a result 
res = requests.post(url="http://localhost:8000/v2/models/ensemble/versions/1/infer", json=request_data).json()
res is like : 
{'model_name':` 'ensemble', 'model_version': '1', 'parameters': {'sequence_id': 0, 'sequence_start': False, 'sequence_end': False}, 'outputs': [{'name': 'OUTPUT', 'datatype': 'BYTES', 'shape': [1, 5], 'data': ['193.82896423339844', '110.80839538574219', '564.7279052734375', '581.59423828125', `'0.8453381061553955']}]}

how can I change the result return ?
I don't want the reference return 'model_name' , 'model_version'...

**Comment by krishung5** [comment]
Hi @yinghaodang, unfortunately we don't support customizing the inference result for now. It seems like you are using Python script. If so, maybe it would be helpful to just get the fields you want from the result which is in json format after calling `.json()` method.
