### ISSUE TITLE
Unable to Launch container ImagePull Back Off Issue

### ISSUE THREAD

**Issue by swapnil-lader** [triton-inference-server/server#4977]
**Description**
I am using the GKE marketplace UI config to launch the triton server pod but it's unable to pull tritonserver-21:12 as I checked in the repository of GC it's not available as our last deployment models were deployed in the same configuration I would like to know if was there any specific reason the version was removed from the repo.

**Triton Information**
I am using 2.17 according to configuration and in terms of triton server version its gcr.io/nvidia-ngc-public/tritonserver:21.12-py3

Are you using the Triton container or did you build it yourself?

I am using the triton container as per following the article https://github.com/triton-inference-server/server/tree/main/deploy/gke-marketplace-app

**To Reproduce**
1 .export PROJECT_ID=<your GCP project ID>
2 .export ZONE=<GCP zone of your choice>
3. export REGION=<GCP region of your choice>
4. export DEPLOYMENT_NAME=<GKE cluster name, triton-gke for example>

5. gcloud beta container clusters create ${DEPLOYMENT_NAME} \
--addons=HorizontalPodAutoscaling,HttpLoadBalancing,Istio \
--machine-type=n1-standard-8 \
--node-locations=${ZONE} \
--zone=${ZONE} \
--subnetwork=default \
--scopes cloud-platform \
--num-nodes 1 \
--project ${PROJECT_ID}

 add GPU node pools, user can modify number of node based on workloads
6. gcloud container node-pools create accel \
  --project ${PROJECT_ID} \
  --zone ${ZONE} \
  --cluster ${DEPLOYMENT_NAME} \
  --num-nodes 2 \
  --accelerator type=nvidia-tesla-t4,count=1 \
  --enable-autoscaling --min-nodes 2 --max-nodes 3 \
  --machine-type n1-standard-4 \
  --disk-size=100 \
  --scopes cloud-platform \
  --verbosity error

 so that you can run kubectl locally to the cluster
7. gcloud container clusters get-credentials ${DEPLOYMENT_NAME} --project ${PROJECT_ID} --zone ${ZONE}  

deploy NVIDIA device plugin for GKE to prepare GPU nodes for driver install
8. kubectl apply -f https://raw.githubusercontent.com/GoogleCloudPlatform/container-engine-accelerators/master/nvidia-driver-installer/cos/daemonset-preloaded.yaml

 make sure you can run kubectl locally to access the cluster
9. kubectl create clusterrolebinding cluster-admin-binding --clusterrole cluster-admin --user "$(gcloud config get-value account)"

enable stackdriver custom metrics adaptor
10. kubectl apply -f https://raw.githubusercontent.com/GoogleCloudPlatform/k8s-stackdriver/master/custom-metrics-stackdriver-adapter/deploy/production/adapter.yaml

11. Deploy container using GKE triton service with configuration 2.17 provide bucket path. Launch the application

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

name: "ankle_strap"
platform: "tensorflow_savedmodel"
max_batch_size: 16
input [
  {
    name: "input"
    data_type: TYPE_FP32
    format: FORMAT_NHWC
    dims: [ 299, 299, 3 ]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ 3 ]
    label_filename: "labels.txt"
  }
]
instance_group [
  {
    count: 1
    gpus: [1]
  }
]
dynamic_batching {
      preferred_batch_size: [ 16 ]
      max_queue_delay_microseconds: 100
    }

**Expected behavior**
The pods launched without any issues earlier without having any ImagePullBack off Error.

**Comment by krishung5** [comment]
Hi @swapnil-lader, apart from `21.12`, are you able to pull other versions of Triton? Could you also share the full error log which contains the `ImagePullBack off Error` you mentioned?

**Comment by swapnil-lader** [comment]
After changing the version to 22.09-py3 I am unable to access my GCS client the triton server is failing with CRASHLOOP BACKOFF Error. 
Copyright (c) 2018-2022, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

NOTE: CUDA Forward Compatibility mode ENABLED.
  Using CUDA 11.8 driver version 520.61.03 with kernel driver version 450.172.01.
  See https://docs.nvidia.com/deploy/cuda-compatibility/ for details.

Warning: '--strict-model-config' has been deprecated! Please use '--disable-auto-complete-config' instead.
I1017 09:45:40.864867 1 pinned_memory_manager.cc:240] Pinned memory pool is created at '0x7fd764000000' with size 268435456
I1017 09:45:40.866326 1 cuda_memory_manager.cc:105] CUDA memory pool is created on device 0 with size 67108864
I1017 09:45:40.866345 1 cuda_memory_manager.cc:105] CUDA memory pool is created on device 1 with size 67108864
W1017 09:45:41.077429 1 server.cc:218] failed to enable peer access for some device pairs
I1017 09:45:41.077477 1 filesystem.cc:2257] TRITON_CLOUD_CREDENTIAL_PATH environment variable is not set, reading from environment variables
I1017 09:45:41.077491 1 filesystem.cc:2335] Using credential    for path  gs://cax-collection-models-all/beta-launch-models
I1017 09:45:41.077668 1 filesystem.cc:2257] TRITON_CLOUD_CREDENTIAL_PATH environment variable is not set, reading from environment variables
I1017 09:45:41.077689 1 filesystem.cc:2335] Using credential    for path  gs://cax-collection-models-all/beta-launch-models
I1017 09:45:41.098649 1 metrics.cc:864] Collecting metrics for GPU 0: Tesla T4
I1017 09:45:41.098684 1 metrics.cc:864] Collecting metrics for GPU 1: Tesla T4
I1017 09:45:41.099243 1 metrics.cc:757] Collecting CPU metrics
I1017 09:45:41.099455 1 tritonserver.cc:2264] 
+----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Option                           | Value                                                                                                                                                                                                |
+----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| server_id                        | triton                                                                                                                                                                                               |
| server_version                   | 2.26.0                                                                                                                                                                                               |
| server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_policy model_configuration system_shared_memory cuda_shared_memory binary_tensor_data statistics trace logging |
| model_repository_path[0]         | gs://cax-collection-models-all/beta-launch-models                                                                                                                                                    |
| model_control_mode               | MODE_EXPLICIT                                                                                                                                                                                        |
| strict_model_config              | 0                                                                                                                                                                                                    |
| rate_limit                       | OFF                                                                                                                                                                                                  |
| pinned_memory_pool_byte_size     | 268435456                                                                                                                                                                                            |
| cuda_memory_pool_byte_size{0}    | 67108864                                                                                                                                                                                             |
| cuda_memory_pool_byte_size{1}    | 67108864                                                                                                                                                                                             |
| response_cache_byte_size         | 0                                                                                                                                                                                                    |
| min_supported_compute_capability | 6.0                                                                                                                                                                                                  |
| strict_readiness                 | 1                                                                                                                                                                                                    |
| exit_timeout                     | 30                                                                                                                                                                                                   |
+----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

I1017 09:45:41.099477 1 server.cc:261] No server context available. Exiting immediately.
error: creating server: Internal - Unable to create GCS client. Check account credentials.



Updated Yaml file :

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  name: triton-inference-server
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: triton-inference-server
      release: triton-inference-server-1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        app: triton-inference-server
        release: triton-inference-server-1
    spec:
      containers:
      - args:
        - tritonserver
        - --model-store=gs://cax-collection-models-all/beta-launch-models
        - --strict-model-config=false
        - --log-verbose=1
        - --allow-gpu-metrics=true
        - --model-control-mode=explicit
        env:
        - name: LD_PRELOAD
        image: gcr.io/nvidia-ngc-public/tritonserver:22.09-py3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 60
          httpGet:
            path: /v2/health/live
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: triton-inference-server
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        - containerPort: 8001
          name: grpc
          protocol: TCP
        - containerPort: 8002
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 60
          httpGet:
            path: /v2/health/ready
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            nvidia.com/gpu: "2"
        securityContext:
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

**Comment by kthui** [comment]
Hi @swapnil-lader, from you log above, it looks like there is a problem with the GCS credential. Can you check if `GOOGLE_APPLICATION_CREDENTIALS` environment variable is set and points to the GCS credential json file?

**Comment by swapnil-lader** [comment]
> Hi @swapnil-lader, from you log above, it looks like there is a problem with the GCS credential. Can you check if `GOOGLE_APPLICATION_CREDENTIALS` environment variable is set and points to the GCS credential json file?

Yes got fixed thanks , I would still like to know why the older version of tritonserver is removed from the repo

**Comment by tanmayv25** [comment]
@mengdong  Do you know the reason of removing the older version of tritonserver from GKE marketplace?
