### ISSUE TITLE
Question: Triton server scaling when too many models

### ISSUE THREAD

**Issue by ibreschi** [triton-inference-server/server#4978]
I would like to use Triton for this use-case:

* Use the Model Control Mode EXPLICIT feature to load dynamically models.
* let Kubernetes auto scale when the gpu memory runs low
* Make that each instance serves different models

If I understand it correctly all the scaled instances of Triton use the same Model repository, is my use case feasible?

**Comment by dyastremsky** [comment]
Yes, that sounds feasible.

**Comment by ibreschi** [comment]
Do you have any advice on how to do so? 

It seems that to implement such use case I would need to manually route my requests to the autoscaled Triton instances. If this is the case I would need to keep track in the client what model is loaded on which instance, which is not optimal.

**Comment by dyastremsky** [comment]
There are many different system designs you could use with Kubernetes. If you need more detailed help, typically you'd want to go through [NVIDIA AI Enterprise software suite](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nvidia.com%2Fen-us%2Fdata-center%2Fproducts%2Fai-enterprise%2F&data=05%7C01%7Cdyastremsky%40nvidia.com%7C1d086a67d2d348a0f2b308daa187fe1a%7C43083d15727340c1b7db39efd9ccc17a%7C0%7C0%7C637999902701351836%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=isQzPPkMV5bG%2BaAZk4wtJPQmLxH%2B3PP971if%2FO5yxKs%3D&reserved=0). We also have [Triton's Management Service](https://developer.nvidia.com/tms-early-access), which was just released early access, that could help with a lot of these concerns.

[Here's a blog post](https://developer.nvidia.com/blog/deploying-nvidia-triton-at-scale-with-mig-and-kubernetes/) about using Triton with Kubernetes that may also be helpful. Hopefully, some of those resources will be helpful and/or provide ideas for a design that works for you.

**Comment by ibreschi** [comment]
Many thanks @dyastremsky for your reply. I'm very eager to try the new Management Service.

**Comment by dyastremsky** [comment]
My pleasure! Good luck.
