### ISSUE TITLE
Build error on windows

### ISSUE THREAD

**Issue by RandySheriffH** [triton-inference-server/server#4979]
**Description**
When buiilding on windows with non-docker, have multiple errors reported.

**Triton Information**
Tested on latest main and r22.03

Are you using the Triton container or did you build it yourself?
I am not with container

**To Reproduce**
Just follow build steps for non-docker windows.

**Expected behavior**
Build error:
"C:\triton\client\build\cc-clients\_deps\repo-common-src\include\triton/common/triton_json.h(641,35): error C2039: 'GetO
bjectA': is not a member of 'rapidjson::GenericValue<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::Cr
tAllocator>>' [C:\triton\client\build\cc-clients\library\http-client-library.vcxproj] [C:\triton\client\build\cc-client
s.vcxproj]"

-------------------------------------------------------
Some update - there actually a few other build errors too:

C:\issue\triton_ut2\build\triton_client-prefix\src\triton_client-build\cc-clients\_deps\repo-common-src\include\triton/
common/triton_json.h(595,1): error C2530: 'm': references must be initialized [C:\issue\triton_ut2\build\triton_client-
prefix\src\triton_client-build\cc-clients\library\http-client-library.vcxproj] [C:\issue\triton_ut2\build\triton_client
-prefix\src\triton_client-build\cc-clients.vcxproj] [C:\issue\triton_ut2\build\triton_client.vcxproj]

C:\issue\triton_ut2\build\triton_client-prefix\src\triton_client\src\c++\library\http_client.cc(1645,53): error C2589:
'(': illegal token on right side of '::' [C:\issue\triton_ut2\build\triton_client-prefix\src\triton_client-build\cc-cli
ents\library\http-client-library.vcxproj] [C:\issue\triton_ut2\build\triton_client-prefix\src\triton_client-build\cc-cl
ients.vcxproj] [C:\issue\triton_ut2\build\triton_client.vcxproj]

**Comment by krishung5** [comment]
Hi @RandySheriffH, could you share the command you run to build Triton on windows and the full log which contains the build error you encountered?

**Comment by Zzephaniahh** [comment]
# Issue with RapidJSON conflicting with Windows + Additional Windows Build Issues.

I'm facing the same issue with a Docker windows build. I have edited the docker file to get it to pass the build phase.


## DockerFile Changes:

### 1. 
I changed ```ARG BASE_IMAGE=mcr.microsoft.com/dotnet/framework/sdk:4.8``` to ```ARG BASE_IMAGE=mcr.microsoft.com/dotnet/framework/sdk:4.8-20190709-windowsservercore-ltsc2019``` to enable me to use choco install correctly. Otherwise the build failed to find the choco packages. 

### 2. 
I changed the command ```RUN git clone --single-branch --depth=1 -b 2022.04.12 https://github.com/microsoft/vcpkg.git``` to ```RUN git clone --single-branch --depth=1 https://github.com/microsoft/vcpkg.git``` because it's no longer possible to build zlib via that version of vcpkg. That version pulls from [zlib-1.2.12](https://www.zlib.net/zlib-1.2.12.tar.gz) which is now a dead link (404 page).

After these changes the DockerFile Dockerfile.win10.min will complete the command ```$ docker build -t win10-py3-min -f Dockerfile.win10.min .```

Then  I run the command above, which results in the RapidJSON issues. I don't believe I need RapidJSON as I intend to use the gRPC endpoint, so if there's a temporary solution involving not building that portion of Triton it will fix things for me.

Let me know if I can provide any more information or test anything on my end.

## OS and Configuration:
Windows Server 2019 
Downloaded and placed locally zips for:
```TENSORRT VERSION 8.2.2.1```
```CUDNN VERSION 8.3.2.44```



## RapidJSON Errors:
```PS C:\Users\Administrator\Downloads\server-2.24.0\server-2.24.0> python build.py --no-container-pull --image=base,win10-py3-min --enable-logging --enable-stats --enable-tracing --enable-gpu --endpoint=grpc --endpoint=http --backend=ensemble --backend=tensorrt --backend=onnxruntime --backend=openvino
Building Triton Inference Server
platform windows
machine amd64
version 2.24.0
build dir C:\Users\Administrator\Downloads\server-2.24.0\server-2.24.0\build
install dir None
cmake dir None
default repo-tag: r22.07
container version 22.07
upstream container version 22.07
endpoint "grpc"
endpoint "http"
backend "ensemble" at tag/branch "r22.07"
backend "tensorrt" at tag/branch "r22.07"
backend "onnxruntime" at tag/branch "r22.07"
backend "openvino" at tag/branch "r22.07"
image "base": "win10-py3-min"
component "common" at tag/branch "r22.07"
component "core" at tag/branch "r22.07"
component "backend" at tag/branch "r22.07"
component "thirdparty" at tag/branch "r22.07"
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

[2022-10-20T12:37:17.983189800Z][docker-credential-desktop][W] Windows version might not be up-to-date: The system cannot find the file specified.
Sending build context to Docker daemon  1.593GB
Step 1/12 : ARG TRITON_VERSION=2.24.0
Step 2/12 : ARG TRITON_CONTAINER_VERSION=22.07
Step 3/12 : ARG BASE_IMAGE=win10-py3-min
Step 4/12 : FROM ${BASE_IMAGE}
 ---> fac1888e4469
Step 5/12 : ARG TRITON_VERSION
 ---> Using cache
 ---> 0ce0c94551af
Step 6/12 : ARG TRITON_CONTAINER_VERSION
 ---> Using cache
 ---> b922e70d1470
Step 7/12 : SHELL ["cmd", "/S", "/C"]
 ---> Using cache
 ---> d0d45d4c7b58
Step 8/12 : ENV TRITON_SERVER_VERSION ${TRITON_VERSION}
 ---> Using cache
 ---> 1af2373643f8
Step 9/12 : ENV NVIDIA_TRITON_SERVER_VERSION ${TRITON_CONTAINER_VERSION}
 ---> Using cache
 ---> e3b8fdb48bf4
Step 10/12 : WORKDIR /workspace
 ---> Using cache
 ---> 961df595df34
Step 11/12 : RUN rmdir /S/Q * || exit 0
 ---> Using cache
 ---> 9f6854b76787
Step 12/12 : COPY . .
 ---> Using cache
 ---> 8e6b8245de37
Successfully built 8e6b8245de37
Successfully tagged tritonserver_buildbase:latest
tritonserver_buildbase
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.8.5
** Copyright (c) 2020 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.



    Directory: C:\tmp\tritonbuild\tritonserver


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       10/20/2022   5:37 AM                build
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.17763.
-- The C compiler identification is MSVC 19.28.29337.0
-- The CXX compiler identification is MSVC 19.28.29337.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/BuildTools/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/BuildTools/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Using MSVC as compiler, default target on Windows 10. If the target system is not Windows 10, please update _WIN32_WINNT to corresponding value
.
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    TRT_VERSION


-- Build files have been written to: C:/tmp/tritonbuild/tritonserver/build
Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

     4>C:\tmp\tritonbuild\tritonserver\build\triton-server\_deps\repo-common-src\include\triton/common/triton_json.h(639,35): error C2039: 'Ge
       tObjectA': is not a member of 'rapidjson::GenericValue<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>>'
       [C:\tmp\tritonbuild\tritonserver\build\triton-server\grpc-endpoint-library.vcxproj] [C:\tmp\tritonbuild\tritonserver\build\triton-serve
       r.vcxproj]
     4>C:\tmp\tritonbuild\tritonserver\build\triton-server\_deps\repo-common-src\include\triton/common/triton_json.h(639,1): error C2530: 'm':
        references must be initialized [C:\tmp\tritonbuild\tritonserver\build\triton-server\grpc-endpoint-library.vcxproj] [C:\tmp\tritonbuild
       \tritonserver\build\triton-server.vcxproj]
     4>C:\tmp\tritonbuild\tritonserver\build\triton-server\_deps\repo-common-src\include\triton/common/triton_json.h(639,1): error C3531: 'm':
        a symbol whose type contains 'auto' must have an initializer [C:\tmp\tritonbuild\tritonserver\build\triton-server\grpc-endpoint-librar
       y.vcxproj] [C:\tmp\tritonbuild\tritonserver\build\triton-server.vcxproj]
     4>C:\tmp\tritonbuild\tritonserver\build\triton-server\_deps\repo-common-src\include\triton/common/triton_json.h(639,26): error C2143: syn
       tax error: missing ';' before ':' [C:\tmp\tritonbuild\tritonserver\build\triton-server\grpc-endpoint-library.vcxproj] [C:\tmp\tritonbui
       ld\tritonserver\build\triton-server.vcxproj]
     4>C:\tmp\tritonbuild\tritonserver\build\triton-server\_deps\repo-common-src\include\triton/common/triton_json.h(639,46): error C2143: syn
       tax error: missing ';' before ')' [C:\tmp\tritonbuild\tritonserver\build\triton-server\grpc-endpoint-library.vcxproj] [C:\tmp\tritonbui
       ld\tritonserver\build\triton-server.vcxproj]
     4>C:\tmp\tritonbuild\tritonserver\build\triton-server\_deps\repo-common-src\include\triton/common/triton_json.h(639,35): error C2039: 'Ge
       tObjectA': is not a member of 'rapidjson::GenericValue<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>>'
       [C:\tmp\tritonbuild\tritonserver\build\triton-server\http-endpoint-library.vcxproj] [C:\tmp\tritonbuild\tritonserver\build\triton-serve
       r.vcxproj]
     4>C:\tmp\tritonbuild\tritonserver\build\triton-server\_deps\repo-common-src\include\triton/common/triton_json.h(639,1): error C2530: 'm':
        references must be initialized [C:\tmp\tritonbuild\tritonserver\build\triton-server\http-endpoint-library.vcxproj] [C:\tmp\tritonbuild
       \tritonserver\build\triton-server.vcxproj]
     4>C:\tmp\tritonbuild\tritonserver\build\triton-server\_deps\repo-common-src\include\triton/common/triton_json.h(639,1): error C3531: 'm':
        a symbol whose type contains 'auto' must have an initializer [C:\tmp\tritonbuild\tritonserver\build\triton-server\http-endpoint-librar
       y.vcxproj] [C:\tmp\tritonbuild\tritonserver\build\triton-server.vcxproj]
     4>C:\tmp\tritonbuild\tritonserver\build\triton-server\_deps\repo-common-src\include\triton/common/triton_json.h(639,26): error C2143: syn
       tax error: missing ';' before ':' [C:\tmp\tritonbuild\tritonserver\build\triton-server\http-endpoint-library.vcxproj] [C:\tmp\tritonbui
       ld\tritonserver\build\triton-server.vcxproj]
     4>C:\tmp\tritonbuild\tritonserver\build\triton-server\_deps\repo-common-src\include\triton/common/triton_json.h(639,46): error C2143: syn
       tax error: missing ';' before ')' [C:\tmp\tritonbuild\tritonserver\build\triton-server\http-endpoint-library.vcxproj] [C:\tmp\tritonbui
       ld\tritonserver\build\triton-server.vcxproj]
     4>C:\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(238,5): error MSB8066: Custom build for 'C:\tmp\tritonbuild\tritons
       erver\build\CMakeFiles\7f609d9584e81f23d01b87584a282d0c\triton-server-mkdir.rule;C:\tmp\tritonbuild\tritonserver\build\CMakeFiles\7f609
       d9584e81f23d01b87584a282d0c\triton-server-download.rule;C:\tmp\tritonbuild\tritonserver\build\CMakeFiles\7f609d9584e81f23d01b87584a282d
       0c\triton-server-update.rule;C:\tmp\tritonbuild\tritonserver\build\CMakeFiles\7f609d9584e81f23d01b87584a282d0c\triton-server-patch.rule
       ;C:\tmp\tritonbuild\tritonserver\build\CMakeFiles\7f609d9584e81f23d01b87584a282d0c\triton-server-configure.rule;C:\tmp\tritonbuild\trit
       onserver\build\CMakeFiles\7f609d9584e81f23d01b87584a282d0c\triton-server-build.rule;C:\tmp\tritonbuild\tritonserver\build\CMakeFiles\7f
       609d9584e81f23d01b87584a282d0c\triton-server-install.rule;C:\tmp\tritonbuild\tritonserver\build\CMakeFiles\3b5d0c60e916ec60bb602caadc70
       fcc6\triton-server-complete.rule;C:\tmp\tritonbuild\tritonserver\build\CMakeFiles\1590503793072e1a82a724f76a3d5ab1\triton-server.rule'
       exited with code 1. [C:\tmp\tritonbuild\tritonserver\build\triton-server.vcxproj]```

**Comment by dyastremsky** [comment]
We merged a few fixes that should resolve the above issues. Would you be able to run a build off the (latest) main branch and confirm whether it succeeds on your end?

**Comment by RandySheriffH** [comment]
@dyastremsky: thanks! Mind copying me all related commits here?

**Comment by dyastremsky** [comment]
Sure.

https://github.com/triton-inference-server/common/pull/78
https://github.com/triton-inference-server/client/pull/192
https://github.com/triton-inference-server/core/pull/141

**Comment by sh524shin** [comment]
windows , no docker, build
error: build failed

I try to build triton in windows without docker.
Installed dependencies according to dockerfile.win10.min
unfortunately, I found below error Message. 


MSBUILD : error MSB1009: Project file does not exist
switch: install.vcxproj

E:\triton\server>python build.py -v --no-container-build --build-dir=build --enable-all

===========================================================
Building Triton Inference Server
platform windows
machine amd64
version 2.29.0dev
build dir build
install dir build\opt\tritonserver
cmake dir E:\triton\server
default repo-tag: main
container version 22.12dev
upstream container version 22.10
endpoint "http"
endpoint "grpc"
backend "ensemble" at tag/branch "main"
backend "identity" at tag/branch "main"
backend "square" at tag/branch "main"
backend "repeat" at tag/branch "main"
backend "onnxruntime" at tag/branch "main"
backend "openvino" at tag/branch "main"
backend "tensorrt" at tag/branch "main"
repoagent "checksum" at tag/branch "main"
component "common" at tag/branch "main"
component "core" at tag/branch "main"
component "backend" at tag/branch "main"
component "thirdparty" at tag/branch "main"
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

새로운 크로스 플랫폼 PowerShell 사용 https://aka.ms/pscore6

디버그:   18+  >>>> New-Item -EV Err -EA Stop -ItemType Directory -Force -Path build\tritonserver\build


    디렉터리: E:\triton\server\build\build\tritonserver


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----      2022-11-24   오전 4:09                build
디버그:   19+  >>>> Set-Location -EV Err -EA Stop build\tritonserver\build
디버그:   20+  >>>> cmake "-DTRT_VERSION=${env:TRT_VERSION}" "-DCMAKE_TOOLCHAIN_FILE=${env:CMAKE_TOOLCHAIN_FILE}"
"-DVCPKG_TARGET_TRIPLET=${env:VCPKG_TARGET_TRIPLET}" "-DCMAKE_BUILD_TYPE=Release"
"-DCMAKE_INSTALL_PREFIX:PATH=build\tritonserver\install" "-DTRITON_VERSION:STRING=2.29.0dev"
"-DTRITON_COMMON_REPO_TAG:STRING=main" "-DTRITON_CORE_REPO_TAG:STRING=main" "-DTRITON_BACKEND_REPO_TAG:STRING=main"
"-DTRITON_THIRD_PARTY_REPO_TAG:STRING=main" "-DTRITON_ENABLE_LOGGING:BOOL=ON" "-DTRITON_ENABLE_STATS:BOOL=ON"
"-DTRITON_ENABLE_METRICS:BOOL=OFF" "-DTRITON_ENABLE_METRICS_GPU:BOOL=OFF" "-DTRITON_ENABLE_METRICS_CPU:BOOL=OFF"
"-DTRITON_ENABLE_TRACING:BOOL=ON" "-DTRITON_ENABLE_NVTX:BOOL=OFF" "-DTRITON_ENABLE_GPU:BOOL=ON"
"-DTRITON_MIN_COMPUTE_CAPABILITY=6.0" "-DTRITON_ENABLE_MALI_GPU:BOOL=OFF" "-DTRITON_ENABLE_GRPC:BOOL=ON"
"-DTRITON_ENABLE_HTTP:BOOL=ON" "-DTRITON_ENABLE_SAGEMAKER:BOOL=OFF" "-DTRITON_ENABLE_VERTEX_AI:BOOL=OFF"
"-DTRITON_ENABLE_GCS:BOOL=OFF" "-DTRITON_ENABLE_S3:BOOL=OFF" "-DTRITON_ENABLE_AZURE_STORAGE:BOOL=OFF"
"-DTRITON_ENABLE_ENSEMBLE:BOOL=ON" "-DTRITON_ENABLE_TENSORRT:BOOL=ON" E:\triton\server
-- The C compiler identification is MSVC 19.29.30147.0
-- The CXX compiler identification is MSVC 19.29.30147.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: E:/triton/BuildTools/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: E:/triton/BuildTools/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Using MSVC as compiler, default target on Windows 10. If the target system is not Windows 10, please update _WIN32_WINNT to corresponding value.
-- Configuring done
-- Generating done
-- Build files have been written to: E:/triton/server/build/build/tritonserver/build
디버그:   21+ if ( >>>> $LASTEXITCODE -ne 0) {
디버그:   25+  >>>> msbuild.exe -m:16  -p:Configuration=Release install.vcxproj
.NET Framework용 Microsoft (R) Build Engine 버전 16.11.2+f32259642
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: 프로젝트 파일이 없습니다.
스위치: install.vcxproj
디버그:   26+ if ( >>>> $LASTEXITCODE -ne 0) {
디버그:   27+    >>>> Write-Output "exited with status code $LASTEXITCODE";
exited with status code 1
디버그:   28+    >>>> ExitWithCode 1;
디버그:    6+ function ExitWithCode($exitcode)  >>>> {
디버그:    7+      >>>> $host.SetShouldExit($exitcode)
디버그:    8+      >>>> exit $exitcode

**Comment by dyastremsky** [comment]
@sh524shin I believe you may need to run your "vcvarsall.bat" file (with the appropriate system architecture as an argument e.g. amd64).

If you need follow up, please create a new issue. I don't think your error is related to this one.

**Comment by sh524shin** [comment]
I got it , I will create a new issue.

**Comment by RandySheriffH** [comment]
@dyastremsky: windows builds are good now, thanks a lot!
Closing the issue.
