### ISSUE TITLE
Can not run the demo example : Request for unknown model: 'densenet_onnx' is not found

### ISSUE THREAD

**Issue by qin53027** [triton-inference-server/server#4980]
**Description**

Hi, 

My system is x86 with RTX2080ti with a brand new Ubuntu 20.04 installed.

I just did git clone and run an example per following three steps. 

When I run the step 3, it gives me the error:

error: failed to get model metadata: Request for unknown model: 'densenet_onnx' is not found
error: failed to get model config: Request for unknown model: 'densenet_onnx' is not found

But the densenet_onnx model is in /server/docs/example/model_repository where I run the step 2 and step3 in two seperate terminal.

Can you please advise how to resolve this error?

 Thanks
Jimmy

==========================================
https://github.com/triton-inference-server/server#readme

# Step 1: Create the example model repository 
git clone -b r22.09 https://github.com/triton-inference-server/server.git
cd server/docs/examples
./fetch_models.sh

# Step 2: Launch triton from the NGC Triton container
docker run --gpus=1 --rm --net=host -v ${PWD}/model_repository:/models nvcr.io/nvidia/tritonserver:22.09-py3 tritonserver --model-repository=/models

# Step 3: Sending an Inference Request 
# In a separate console, launch the image_client example from the NGC Triton SDK container
docker run -it --rm --net=host nvcr.io/nvidia/tritonserver:22.09-py3-sdk
/workspace/install/bin/image_client -m densenet_onnx -c 3 -s INCEPTION /workspace/images/mug.jpg

**Triton Information**

Used the 22.09 container 

Are you using the Triton container or did you build it yourself?
Yes

**To Reproduce**
Very easy: just follow the above three steps

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**

# Inference should return the following
Image '/workspace/images/mug.jpg':
    15.346230 (504) = COFFEE MUG
    13.224326 (968) = CUP
    10.422965 (505) = COFFEEPOT

**Comment by krishung5** [comment]
Hi @qin53027, is the model `densenet_onnx` loaded when sending an infer request using the SDK container? Could you share the full server log?

**Comment by qin53027** [comment]
Following are the step2 log
jiande@jiande-Zephyrus-S-GX531GXR-GX531GXR:~$ docker run -it --rm --net=host nvcr.io/nvidia/tritonserver:22.09-py3-sdk

=================================
== Triton Inference Server SDK ==
=================================

NVIDIA Release 22.09 (build 44909149)

Copyright (c) 2018-2022, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use the NVIDIA Container Toolkit to start this container with GPU support; see
   https://docs.nvidia.com/datacenter/cloud-native/ .

root@jiande-Zephyrus-S-GX531GXR-GX531GXR:/workspace# /workspace/install/bin/image_client -m densenet_onnx -c 3 -s INCEPTION /workspace/images/mug.jpg
error: failed to get model metadata: Request for unknown model: 'densenet_onnx' is not found
error: failed to get model config: Request for unknown model: 'densenet_onnx' is not found
expecting 1 input, got 0
root@jiande-Zephyrus-S-GX531GXR-GX531GXR:/workspace#

**Comment by qin53027** [comment]
[step2.log](https://github.com/triton-inference-server/server/files/9780624/step2.log)
[step3.log](https://github.com/triton-inference-server/server/files/9780626/step3.log)

**Comment by qin53027** [comment]
Sorry, I have attached the step2.log and step3.log. 

Thanks for the help

**Comment by qin53027** [comment]
Also all the models are fetched: 
***@***.***:~/program/server/docs/examples/model_repository$
ls
densenet_onnx       simple                simple_int8
inception_graphdef  simple_dyna_sequence  simple_sequence
model_repository    simple_identity       simple_string
[…](https://github.com/triton-inference-server/server/issues/4980#)

**Comment by krishung5** [comment]
From the log you share:
```
I1013 20:50:47.261699 1 server.cc:633] 
+-------+---------+--------+
| Model | Version | Status |
+-------+---------+--------+
+-------+---------+--------+
```
The models are not loaded to the server.
I suspect that the model repository is not mounted correctly to the docker. Are you running the `docker run` command under the path `~/program/server/docs/examples`? Can you try to change the `${PWD}` part of the command `docker run --gpus=1 --rm --net=host -v ${PWD}/model_repository:/models nvcr.io/nvidia/tritonserver:22.09-py3 tritonserver --model-repository=/models` to the absolute path and see if it works?

**Comment by qin53027** [comment]
Hi Chris,

Thanks so much for your help.

If I run the steps under: ~/program/server/docs/examples, then I can see models except that the docker run with error and exit the container:

error: creating server: Internal - failed to load all models

But if run the docker run under: ~/program/server/docs/examples/model_repository, then it does not load the model as you indicated but it does not exit the docker. Here is the last several lines of messages when run step2:

I1013 22:38:07.906264 1 http_server.cc:181] Started Metrics Service at 0.0.0.0:8002
W1013 22:38:08.844761 1 metrics.cc:603] Unable to get power limit for GPU 0. Status:Success, value:0.000000
W1013 22:38:09.845568 1 metrics.cc:603] Unable to get power limit for GPU 0. Status:Success, value:0.000000
W1013 22:38:10.848103 1 metrics.cc:603] Unable to get power limit for GPU 0. Status:Success, value:0.000000

Thanks
Jimmy


run steps in : ~/program/server/docs/examples
step2.log
==============================================
I1013 22:27:59.409518 1 server.cc:633] 
+----------------------+---------+--------+
| Model                | Version | Status |
+----------------------+---------+--------+
| densenet_onnx        | 1       | READY  |
| inception_graphdef   | 1       | READY  |
| simple               | 1       | READY  |
| simple_dyna_sequence | 1       | READY  |
| simple_identity      | 1       | READY  |
| simple_int8          | 1       | READY  |
| simple_sequence      | 1       | READY  |
| simple_string        | 1       | READY  |
+----------------------+---------+--------+

----------------------------------------------------------------------------------------------------------------------------------------------------------+
| server_id                        | triton                                                                                                                                                                                               |
| server_version                   | 2.26.0                                                                                                                                                                                               |
| server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_policy model_configuration system_shared_memory cuda_shared_memory binary_tensor_data statistics trace logging |
| model_repository_path[0]         | /models                                                                                                                                                                                              |
| model_control_mode               | MODE_NONE                                                                                                                                                                                            |
| strict_model_config              | 0                                                                                                                                                                                                    |
| rate_limit                       | OFF                                                                                                                                                                                                  |
| pinned_memory_pool_byte_size     | 268435456                                                                                                                                                                                            |
| cuda_memory_pool_byte_size{0}    | 67108864                                                                                                                                                                                             |
| response_cache_byte_size         | 0                                                                                                                                                                                                    |
| min_supported_compute_capability | 6.0                                                                                                                                                                                                  |
| strict_readiness                 | 1                                                                                                                                                                                                    |
| exit_timeout                     | 30                                                                                                                                                                                                   |
+----------------------------------+--------------------------------------------


I1013 22:34:28.477537 1 model_lifecycle.cc:578] successfully unloaded 'densenet_onnx' version 1
I1013 22:34:29.469815 1 server.cc:302] Timeout 29: Found 0 live models and 0 in-flight non-inference requests
W1013 22:34:29.471473 1 metrics.cc:603] Unable to get power limit for GPU 0. Status:Success, value:0.000000
error: creating server: Internal - failed to load all models
W1013 22:34:30.495548 1 metrics.cc:603] Unable to get power limit for GPU 0. Status:Success, value:0.000000

**Comment by krishung5** [comment]
Thanks for trying. So it seems like in the previous approach, the model repository is not mounted.
Can you run `docker run --gpus=1 --rm --net=host -v ${PWD}/model_repository:/models nvcr.io/nvidia/tritonserver:22.09-py3 tritonserver --model-repository=/models --log-verbose=1` under the correct path so that the models are able to be loaded, and share us the full server log? With `--log-verbose=1` we can get more information from the log.

**Comment by qin53027** [comment]
Hi Kris,

Attached is the full log fro the step2.

Thanks
Jimmy

[step2.log](https://github.com/triton-inference-server/server/files/9781154/step2.log)

**Comment by krishung5** [comment]
From the log:
```
I1013 23:02:25.986055 1 model_config_utils.cc:1074] Could not infer supported backend, so attempting autofill of custom backend.
E1013 23:02:25.986092 1 model_repository_manager.cc:996] Poll failed for model directory 'model_repository': Invalid model name: Could not determine backend for model 'model_repository'
```
Besides, from the reply [here](https://github.com/triton-inference-server/server/issues/4980#issuecomment-1278163917), It seems like there is a `model_repository` directory under `${PWD}/model_repository`. Could you remove the extra directory and run it again?

**Comment by qin53027** [comment]
Hi  Kris,

After I removed the model_repository inside the model_repository, now step2 and step3 run are very good.

Image '/workspace/images/mug.jpg':
    15.349562 (504) = COFFEE MUG
    13.227464 (968) = CUP
    10.424891 (505) = COFFEEPOT
root@jiande-Zephyrus-S-GX531GXR-GX531GXR:/workspace# 

I really appreciate your great help!!

Jimmy

**Comment by qin53027** [comment]
Close this issue
