### ISSUE TITLE
Docker build fail on windows 

### ISSUE THREAD

**Issue by RandySheriffH** [triton-inference-server/server#4981]
**Description**
Build docker image failed on "Dockerfile.win10.min"

**Triton Information**
main 

**To Reproduce**
`docker build -t win10-py3-min2 -f Dockerfile.win10.min .`

Got:

**Step 21/61** : RUN vcpkg.exe install openssl:x64-windows openssl-windows:x64-windows rapidjson:x64-windows re2:x64-windows boost-interprocess:x64-windows boost-stacktrace:x64-windows zlib:x64-windows pthread:x64-windows b64:x64-windows
 ---> Running in 4e03abdf511e
Computing installation plan...
A suitable version of cmake was not found (required v3.22.2). Downloading portable cmake v3.22.2...
Downloading cmake...
  https://github.com/Kitware/CMake/releases/download/v3.22.2/cmake-3.22.2-windows-i386.zip -> C:\vcpkg\downloads\cmake-3.22.2-windows-i386.zip
Extracting cmake...
A suitable version of 7zip_msi was not found (required v21.7.0). Downloading portable 7zip_msi v21.7.0...
Downloading 7zip_msi...
  https://www.7-zip.org/a/7z2107-x64.msi -> C:\vcpkg\downloads\7z2107-x64.msi
Extracting 7zip_msi...
The following packages will be built and installed:
    b64[core]:x64-windows -> 2.0.0.1
  * boost-array[core]:x64-windows -> 1.78.0
  * boost-assert[core]:x64-windows -> 1.78.0
  * boost-build[core]:x64-windows -> 1.78.0#1
  * boost-config[core]:x64-windows -> 1.78.0
  * boost-container[core]:x64-windows -> 1.78.0
  * boost-container-hash[core]:x64-windows -> 1.78.0
  * boost-core[core]:x64-windows -> 1.78.0
  * boost-detail[core]:x64-windows -> 1.78.0
  * boost-integer[core]:x64-windows -> 1.78.0
    boost-interprocess[core]:x64-windows -> 1.78.0
  * boost-intrusive[core]:x64-windows -> 1.78.0
  * boost-modular-build-helper[core]:x64-windows -> 1.78.0#3
  * boost-move[core]:x64-windows -> 1.78.0
  * boost-predef[core]:x64-windows -> 1.78.0
  * boost-preprocessor[core]:x64-windows -> 1.78.0
  * boost-smart-ptr[core]:x64-windows -> 1.78.0
    boost-stacktrace[core]:x64-windows -> 1.78.0
  * boost-static-assert[core]:x64-windows -> 1.78.0
  * boost-throw-exception[core]:x64-windows -> 1.78.0
  * boost-tuple[core]:x64-windows -> 1.78.0
  * boost-type-traits[core]:x64-windows -> 1.78.0
  * boost-uninstall[core]:x64-windows -> 1.78.0
  * boost-unordered[core]:x64-windows -> 1.78.0
  * boost-vcpkg-helpers[core]:x64-windows -> 1.78.0#1
  * boost-winapi[core]:x64-windows -> 1.78.0
    openssl[core]:x64-windows -> 3.0.2#2
    openssl-windows[core]:x64-windows -> 1.1.1h#2
    pthread[core]:x64-windows -> 3.0.0#1
  * pthreads[core]:x64-windows -> 3.0.0#10
    rapidjson[core]:x64-windows -> 2020-09-14#2
    re2[core]:x64-windows -> 2021-11-01
  * vcpkg-cmake[core]:x64-windows -> 2022-04-07
  * vcpkg-cmake-config[core]:x64-windows -> 2022-02-06
    zlib[core]:x64-windows -> 1.2.12
Additional packages (*) will be modified to complete this operation.
**Error: in triplet x64-windows: Unable to find a valid Visual Studio instance**
Could not locate a complete Visual Studio instance
The following paths were examined for Visual Studio instances:
    C:\Program Files (x86)\Microsoft Visual Studio\2022\TestAgent\VC\Auxiliary/Build\vcvarsall.bat
    C:\BuildTools\VC\Auxiliary/Build\vcvarsall.bat
The command 'cmd /S /C vcpkg.exe install openssl:x64-windows openssl-windows:x64-windows rapidjson:x64-windows re2:x64-windows boost-interprocess:x64-windows boost-stacktrace:x64-windows zlib:x64-windows pthread:x64-windows b64:x64-windows' returned a non-zero code: 1

**Comment by krishung5** [comment]
@mc-nv Have you seen something similar before? @RandySheriffH Is Visual Studio already installed on your machine? It seems like the issue may have something to do with some environment setting on VS.

**Comment by RandySheriffH** [comment]
@krishung5 : that's not my machine, the error is in container when building the image. For sure there is vs since the base image is dotnet. Your team build image out it right no?

**Comment by RandySheriffH** [comment]
@krishung5 : the error is from container when trying to build the image, vs should already be there since the base image is dotnet.

**Comment by kthui** [comment]
Hi @RandySheriffH, I was not able to replicate the issue on our CI machine, following the steps outlined in the [documentation](https://github.com/triton-inference-server/server/blob/main/docs/customization_guide/build.md#windows-10-min-image). Can you share more details on how to reproduce?

CC @tanmayv25 @GuanLuo, in case you have some insight into this issue.

**Comment by RandySheriffH** [comment]
We wouldn't be talking If you see this in your CI. ;-)

**Comment by tanmayv25** [comment]
Some similar issues are being discussed here: https://github.com/microsoft/vcpkg/issues/22074
I wonder why the containerized build run into issues on different machines.

**Comment by krishung5** [comment]
@RandySheriffH Could you try the Dockerfile changes in the above PR and see if the same issue still exists?

**Comment by krishung5** [comment]
Closing this issue as Microsoft team has verified the build.

**Comment by RandySheriffH** [comment]
@krishung5: I didn't verify building by docker.

**Comment by krishung5** [comment]
@RandySheriffH Might be some misunderstanding, sorry about that. Re-open this issue for verifying. FYI the above changes are merged into main. Please let me know if you are still seeing the same issue for docker build. Thanks!
cc @Christina-Young-NVIDIA
