### ISSUE TITLE
gRPC client generated python files are really old

### ISSUE THREAD

**Issue by omidb** [triton-inference-server/server#4984]
**Is your feature request related to a problem? Please describe.**
This is a blocking issue for us.
gRPC-generated files are old and incompatible with many other libraries (tested for Python). As has been mentioned [here](https://github.com/triton-inference-server/client/blob/main/src/python/library/requirements/requirements_grpc.txt): 

> Restrict maximum version due to breaking protobuf 4.21.0 changes
> (see https://github.com/protocolbuffers/protobuf/issues/10051)
> TODO: Update to be compatible with 4.0 release (DLIS-3809)
> protobuf>=3.5.0,<3.20
> There is memory leak in later Python GRPC (1.43.0 to be specific),
> use known working version until the memory leak is resolved in the future
> (see https://github.com/grpc/grpc/issues/28513)
> grpcio==1.41.0
> numpy>=1.19.1
> python-rapidjson>=0.9.1

**Describe the solution you'd like**
We can do two things: Release the client with two different Protoc support: version 3 and version 4. Or we can just increase the version to the latest.

**Describe alternatives you've considered**
Using HTTP or gRPC but not using the triton-client package which is not ideal as there are many nice optimizations in the package.

**Comment by kthui** [comment]
Hi @omidb, we have a ticket to increase the protobuf version. I have added your request into the ticket.

**Comment by omidb** [comment]
@kthui thanks

**Comment by kaancfidan** [comment]
This is also a blocking issue for us, and the supported Python version is 3.8, which is very old right now.

**Comment by jbkyang-nvi** [comment]
fixed with ^
