### ISSUE TITLE
tritonclient.utils.InferenceServerException: [StatusCode.UNAVAILABLE] Connection reset by peer

### ISSUE THREAD

**Issue by 1994sugar** [triton-inference-server/server#4985]
My tritonserver container version is 21.12, when I use grpc client it happen this error. How can I fix it?

**Comment by kthui** [comment]
Hi @1994sugar, container version 21.12 is really old. Would you be able to use a newer release, such as 22.09?

**Comment by 1994sugar** [comment]
My server CUDA version is 11.3.1，Can I upgrade？

**Comment by 1994sugar** [comment]
Grpc connection reset

**Comment by 1994sugar** [comment]
> What is your error?
Grpc connection reset

**Comment by 1994sugar** [comment]
> My server CUDA version is 11.3.1，Can I upgrade？

My server CUDA version is 11.3.1，Can I upgrade？

**Comment by 1994sugar** [comment]
> Hi @1994sugar, container version 21.12 is really old. Would you be able to use a newer release, such as 22.09?


My server CUDA version is 11.3.1，Can I upgrade triton version to fix this bug？
