### ISSUE TITLE
ModelInfer RPC doesn't support models with decoupled transaction policy

### ISSUE THREAD

**Issue by thrmotta** [triton-inference-server/server#4994]
**Description**
Attempting to run preprocess and postprocess methods during a triton inference call via the model.py file but ever since I updated the pbtxt to use the following policy, I keep getting "ModelInfer RPC doesn't support models with decoupled transaction policy" error.
```
model_transaction_policy {
  decoupled: True
}
```
While debugging I never even manage to get inside the model.py calls. On the deep call that actually results on error, I can see the following error_string():
`'{"created":"@1666128982.930892800","description":"Error received from peer ipv4:127.0.0.1:8001","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"ModelInfer RPC doesn\'t support models with decoupled transaction policy","grpc_status":12}'`
The error derives from the following call:
````
results = self.triton_client.infer(
            model_name=self.FLAGS.model,
            inputs=self.inputs,
            outputs=self.outputs,
            client_timeout=self.FLAGS.client_timeout,
        )
````

Inputs are set as
````
self.inputs.append(
            grpcclient.InferInput(
                self.model_config.config.input[0].name,
                self.input_shape,
                self.datatype,
            ),
        )
````

Outputs as:
````
self.outputs.append(
            grpcclient.InferRequestedOutput(
                self.model_config.config.output[0].name,
            ),
        )
````
datatype is FP32 and input_shape is [1, 1280, 1280, 3]        
**Triton Information**
22.09-py3
grpcio                       1.47.0
grpcio-tools                 1.47.0
tritonclient                 2.26.0
Python 3.8.10
Are you using the Triton container or did you build it yourself? Using Triton container

**To Reproduce**
I'm using Windows 10 with WSL2/Ubuntu22.02 on Visual Studio Code. Once the server is runing, I run a client similar to https://github.com/isarsoft/yolov4-triton-tensorrt/blob/master/clients/python/client.py with the following parameters: 
["--mode", "image", "--input", "/data/IMG_3360.JPG", "--width", "1280", "--height", "1280", "--model", "yolox_m_coco", "-o", "/data/triton_output.jpg", "--model-info", True],

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
Built a yolox_m_coco tensorrt model from a pretrained yolox_m file. Pbtxt is as follows:
```
name: "yolox_m_coco"
platform: "tensorrt_plan"
model_transaction_policy {
  decoupled: True
}
max_batch_size : 0
input [
  {
    name: "input_1"
    data_type: TYPE_FP32
    dims: [ 1, 1280, 1280, 3  ]
	reshape { shape: [ 1, 1280, 1280, 3 ] }
  }
]
output [
  {
    name: "outputs_fp32"
    data_type: TYPE_FP32
    dims: [ -1, -1, 85 ]
  }   
]
```
**Expected behavior**
Expected to be able to use preprocess and postprocess custom operations directly ON Triton Inference Server

**Comment by kthui** [comment]
@tanmayv25 Is this a supported use-case?

**Comment by Tabrizian** [comment]
The tensorrt backend doesn't support decoupled transaction policy. TRT backend will send a single response for every request. The error you are seeing is because you need to use `stream_async_infer` interface of the Python models for the [decoupled models](https://github.com/triton-inference-server/client/blob/main/src/python/examples/simple_grpc_sequence_stream_infer_client.py).

**Comment by tanmayv25** [comment]
I would advice to remove:
```
model_transaction_policy {
  decoupled: True
}
```

This is because TensorRT models generate exactly one set of output for one set of inputs. Also, Iman's comment is accurate. ModelInfer only supports such use cases. When your model can generate multiple(or none) responses for a single input then you'd need to use `decoupled: true` and `async_stream_infer`.
For more information, please read this document:
https://github.com/triton-inference-server/server/blob/main/docs/user_guide/decoupled_models.md

**Comment by thrmotta** [comment]
I started using `model_transaction_policy ` as a way to apply preprocessing and postprocessing steps to an inference via Triton. Is it possible to apply both steps without using `model_transaction_policy` ?

The only method I've found was to create a model_ensemble with one pbtxt file for each step, and each having a unique implementation of TritonPythonModel on model.py. Is there a more recommended way to do this? Perhaps one where just a single model.py is used?

**Comment by tanmayv25** [comment]
I don't think you can use `decoupled_transaction_policy` in such a manner. The specification reflects the characteristics of models on whether they can return multiple(or no) responses or not. A TensorRT model produces exactly one response per request. 

If you have to add additional logic before and after TensorRT model execution, `decoupled_transaction_policy` will not help. And you are right! The recommendation is then to use an ensemble pipeline where pre- and post- process happens in their own backend. This is especially useful for cases where you need a high throughput. The pre-process step of one request will overlap with the inference of other and post-process of another. These pipelined execution allows these steps to happen concurrently.

You can use the python_backend models as you described : ease of development. But if you want to achieve better performance, I would advice using C++ backend.
