### ISSUE TITLE
How to properly use dynamic input shape with Triton?

### ISSUE THREAD

**Issue by thrmotta** [triton-inference-server/server#4995]
**Description**
I'm building an ensemble pbtxt where the first step is to apply preprocessing (custom TritonPythonModel implementation) to images of any size, so they get resized to match the second step object detection model size, but I've been unable to make this work.

I know pbtxt works with dynamic input shape as follows: `dims: [ -1, -1, 3 ]`, but when passing an input image to `set_data_from_numpy`, so they can be inferred on a client application, it will yield and error stating that -1 shape is different from whatever actual size the image has, such as: `got unexpected numpy array shape [1080, 1920, 3], expected [-1, -1, 3]`

Here's a snippet of some of the steps done along the way:
```
self.input_shape = list(self.model_config.config.input[0].dims)
self.inputs.append(
            grpcclient.InferInput(
                self.model_config.config.input[0].name,
                self.input_shape,
                self.datatype,
            ),
        )
input_image = image.utils.load_img(
        str(FLAGS.input),
        color_mode="rgb",
    )   
 self.inputs[0].set_data_from_numpy(input_image )       
 results = self.triton_client.infer(
            model_name=self.FLAGS.model,
            inputs=self.inputs,
            outputs=self.outputs,
            client_timeout=self.FLAGS.client_timeout,
        )
```
**Triton Information**
What version of Triton are you using?  22.09-py3

Are you using the Triton container or did you build it yourself? Using container

**To Reproduce**
Create a pbtxt with variable size dims, such as `dims: [ -1, -1, 3 ]`, start the triton server and attempt to make an inference with an image of any size.

Describe the models (framework, inputs, outputs):
The following is the ensemble pbtxt model I've built so far
```
name: "ensemble_yolox_m_coco"
platform: "ensemble"
max_batch_size: 0
input [
  {
    name: "input"
    data_type: TYPE_UINT8
    dims: [ -1, -1, 3 ]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ -1, 6 ]
  }   
]
ensemble_scheduling {
  step [
    {
      model_name: "preprocess"
      model_version: -1
      input_map {
        key: "INPUT_0"
        value: "input"
      }
      output_map {
        key: "OUTPUT_0"
        value: "preprocessed_image"
      }
    },
    {
      model_name: "yolox_m_coco"
      model_version: -1
      input_map {
        key: "input_1"
        value: "preprocessed_image"
      }
      output_map {
        key: "outputs_fp32"
        value: "detected_image"
      }
    },
    {
      model_name: "postprocess"
      model_version: -1
      input_map {
        key: "INPUT_0"
        value: "detected_image"
      }
      output_map {
        key: "OUTPUT_0"
        value: "output"
      }
    }
  ]
}
```

Preprocess step is as follows:
```
name: "preprocess"
backend: "python"
max_batch_size: 0 
input [
  {
    name: "INPUT_0"
    data_type: TYPE_UINT8
    dims: [ -1, -1, 3 ]
  }
]
 
output [
{
    name: "OUTPUT_0"
    data_type: TYPE_FP32
    dims: [ 1, 1280, 1280, 3 ]
}
]

instance_group [{ kind: KIND_CPU }]
```
**Expected behavior**
Images of any size would be accepted and resized when needed during the preprocessing step.

**Comment by kthui** [comment]
Thanks for sharing this issue. I have filed a ticket for us to investigate further.

**Comment by thrmotta** [comment]
As a feedback, the only way I managed to use dynamic sized images was to have as input to the pbptxt a TYPE_STRING, which actually represents a byte array, as follows:
```
name: "preprocess"
backend: "python"
max_batch_size: 0
input [
  {
    name: "INPUT_0"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]

output [
{
    name: "OUTPUT_0"
    data_type: TYPE_FP32
    dims: [ 1, 1280, 1280, 3 ]
}
]

instance_group [{ kind: KIND_CPU }]
```

By preprocessing the input image to be of type bytes, I'm successfully able to pass images of any size to my custom model.py, decode it and resize to the size needed. 

The image is cast to bytes with:
```
    np_bytes = BytesIO()
    np.save(np_bytes, numpy_image, allow_pickle=True)
    np_bytes = np_bytes.getvalue()

```

And decoded back with:
```
    load_bytes = BytesIO(bytes_image)
    image_frame = np.load(load_bytes, allow_pickle=True)
```

Let me know if there is a way to achieve this without having to cast the image to bytes first.

**Comment by GuanLuo** [comment]
When you create a inference input, you should pass in the actual tensor shape instead of config shape, i.e. in below `self.input_shape = list(self.model_config.config.input[0].dims)` sets input_shape to `[-1, -1, 3]` which doesn't reflect the shape of your `input_image`. Instead, please try `self.input_shape = input_image.shape`
```
grpcclient.InferInput(
                self.model_config.config.input[0].name,
                self.input_shape,
                self.datatype,
            ),
```

**Comment by thrmotta** [comment]
That works as long as the input images remains with the same size, but what if images are arriving with different dimensions? Is it ok to replace `InferInput `everytime an input image dimension changes? Is there a slowdown in doing so? Or is it better to configure multiple `InferInput `and just use the one with appropriate dimensions?

I didn't time the executions yet, but working with bytes as input works for images of all sizes without having to change `InferInput`, although there is the overhead of converting images to bytes and back again inside model.py. On the other hand, working with a pbtxt with `dims: [ -1, -1, 3  ]` and setting `InferInput`, if the shapes differs from the input image shape, right before calling `infer()`, also works for images of variable sizes.

Is there a more recommended way to proceed with this?

**Comment by GuanLuo** [comment]
>Is it ok to replace InferInput everytime an input image dimension changes? Is there a slowdown in doing so? Or is it better to configure multiple InferInput and just use the one with appropriate dimensions?

Either way is fine, `InferInput` has two parts: data and meta data, data will always need to be updated when different image is given, and the meta data part should be lightweight so there shouldn't be significant overhead to manipulate `InferInput` objects. Note that `InferInput` does provide `set_shape` function to change the shape for this particular reason.
