### ISSUE TITLE
UnicodeEncodeError when using python backend to encode utf-8

### ISSUE THREAD

**Issue by DianYe2333** [triton-inference-server/server#4996]
**Description**
UnicodeEncodeError :'ascii' codec can;t encode characters，when i want to print chinese in the class TritonPythonModel.

**Triton Information**

**Comment by krishung5** [comment]
To print Chinese, you may need to set `export PYTHONIOENCODING=UTF-8`.  Related issue: https://github.com/triton-inference-server/server/issues/4708

**Comment by krishung5** [comment]
Closing this issue as the question has been addressed.
