### ISSUE TITLE
How do I know that Triton's return is over?

### ISSUE THREAD

**Issue by NoWait126** [triton-inference-server/server#4999]
**Is your feature request related to a problem? Please describe.**
I am using the streaming interface of Triton2.22. The interaction between my client and the server is: a client request, the server may have multiple streaming responses.  Is there an end mark in Triton's return? How do I know that Triton's return is over?  I only found `RequestStatus()`, but this interface cannot identify whether the transmission has ended or not.

**Comment by kthui** [comment]
Hi @NoWait126, when you get the expected number of response(s) back for the corresponding request, Triton's return is over for the request. Would this work for your use-case?

CC @tanmayv25 @Tabrizian

**Comment by NoWait126** [comment]
Hi @kthui ，for a request, I don't know how many times it will return, it's a streaming return. I have set `TRITONSERVER_RESPONSE_COMPLETE_FINAL` as 1 in server when response is over, how can I know response is over in `cpp` client?

**Comment by kthui** [comment]
> for a request, I don't know how many times it will return, it's a streaming return. I have set TRITONSERVER_RESPONSE_COMPLETE_FINAL as 1 in server when response is over, how can I know response is over in cpp client?

@tanmayv25 do we currently have a way to support this use-case?

**Comment by tanmayv25** [comment]
Unfortunately we don't have a mechanism to forward the response characteristics (response flags) to the clients yet. 
It is in our backlog though. Please follow the below for updates:
duplicate issue: https://github.com/triton-inference-server/server/issues/4541
