### ISSUE TITLE
Can I use Triton server for inference on GPU AWS graviton instances

### ISSUE THREAD

**Issue by joemaliszewski** [triton-inference-server/server#5001]
Is there a dockerfile for deploying Triton server on graviton instances on aws. 

Will it be cheaper?
Will performance be worse or better than a standard GPU instance?
Do I need to use the version for Nvidia Jetson because graviton is based on arm?

**Comment by joemal1234** [comment]
https://aws.amazon.com/blogs/aws/new-amazon-ec2-g5g-instances-powered-by-aws-graviton2-processors-and-nvidia-t4g-tensor-core-gpus/

These are the instances, will triton server work with this?

Any answer yes or no will be really appreciated

**Comment by kthui** [comment]
We have ARM64 architecture based containers: https://catalog.ngc.nvidia.com/orgs/nvidia/containers/tritonserver/tags
Feel free to give it a try.

CC @tanmayv25 @GuanLuo In case you have some insights into ARM64 deployment on AWS.

**Comment by tanmayv25** [comment]
I don't know about ARM64 deployment on AWS. But in theory our ARM64 based containers should work. You might not be able to use our Nvidia Jetson release as it is based on Jetpack.

**Comment by dyastremsky** [comment]
Closing issue due to lack of activitity. If you need further support, please let us know and we can reopen the issue.
