### ISSUE TITLE
Why does TensorRT engine only supports max-batch 1

### ISSUE THREAD

**Issue by TRINHHOANGANH** [triton-inference-server/server#5013]
**Description**
Hi Nvidia,
I have question about  TensorRT engine and triton server . 
When i run triton server with command:

docker run --gpus=1 --rm -p8000:8000 -p8001:8001 -p8002:8002 -v/home/aitraining/workspace/anhth57/Vehicle_tensorRT_K8s/module/triton-yolov5/deloy/models:/models -v/home/aitraining/workspace/anhth57/Vehicle_tensorRT_K8s/module/triton-yolov5/deloy/plugins:/plugins --env LD_PRELOAD=/plugins/libmyplugins.so nvcr.io/nvidia/tritonserver:22.04-py3 tritonserver –model-repository=/models

Then, I put my engine in triton server's models directory and wrote my config.pbtxt. When I load model it always failed because of max_batch_size
![image](https://user-images.githubusercontent.com/83366198/197913960-c2b0605e-7d41-4a91-820a-4c254c28b461.png)

**My config.pbtxt**
`name: "yolov5_infer"
platform: "tensorrt_plan"
max_batch_size: 8
version_policy{
    latest: {
        num_versions: 1
    }
    }
input: [
    {
        name: "data"
        data_type: TYPE_FP32
        format: FORMAT_NONE
        dims: [3, 640, 640]
        is_shape_tensor: false
    }
]
output: [
    {
        name: "prob",
        data_type: TYPE_FP32
        dims: [ 6001, 1, 1 ]
        is_shape_tensor: false
    }
]
instance_group: [
    {
        name: "yolov5_infer"
        kind: KIND_GPU
        count: 1
        gpus: [ 0 ]
    }
]
dynamic_batching {
    preferred_batch_size: [ 1, 4 ]
    max_queue_delay_microseconds: 100 
}`

**Triton Information**
The version of Triton container is: nvcr.io/nvidia/tensorrt:22.04-py3

**Comment by GuanLuo** [comment]
That means the engine is created with max shape 1 for the batch dimension, you can use [polygraphy](https://github.com/NVIDIA/TensorRT/tree/main/tools/Polygraphy) to examine your model. Config can't overwrite the model properties but just a reflection of it, so if you want to have max batch size different than 1, you need to generate your model in the desired way.

If polygraphy does report the engine support > 1, then it will likely be a bug in auto-complete logic. In this case, you may also try the latest release of Triton container to see if it has been fixed.

**Comment by TRINHHOANGANH** [comment]
@GuanLuo Thanks for your guide. I fixed this error

**Comment by mnuriyumusak** [comment]
@TRINHHOANGANH hi can you please share how did you exactly solve this issue?
