### ISSUE TITLE
22.09 Logger still unavailable in python_backend

### ISSUE THREAD

**Issue by akuma12** [triton-inference-server/server#5025]
**Description**
Even after updating to the r22.09 Triton Docker image, I still get the error `AttributeError: module 'triton_python_backend_utils' has no attribute 'Logger'` when trying to use `pb_utils.Logger` in my python_backend code.

I also tried compiling the python_backend from source, and building a new Triton image using build.py from the r22.09 branch, with no luck either way. I see the new code in the r22.09 branch of the python_backend repo, but I'm still unable to get it to work properly.

**Triton Information**
What version of Triton are you using?
22.09

Are you using the Triton container or did you build it yourself?
Both

**To Reproduce**
In a python_backend model, access `pb_utils.Logger`.

**Expected behavior**
I should get the results depicted in the python_backend README: https://github.com/triton-inference-server/python_backend#logging

**Comment by tanmayv25** [comment]
@akuma12  We test the logger in our CI see: https://github.com/triton-inference-server/server/tree/main/qa/L0_backend_python/logging
The respective model is here: https://github.com/triton-inference-server/server/blob/main/qa/python_models/identity_fp32_logging/model.py

There might be something wrong with your setup. Can you share your model repository?

**Comment by akuma12** [comment]
@tanmayv25 Ah ha! The docs didn't indicate that `logger = pb_utils.Logger` had to be in one of the class methods (initialize, execute, or finalize). I had `logger = pb_utils.Logger` declared outside of the `TritonPythonModel` class (like I would for a normal python logger).

Thank you for those examples, that fixed the issue!
