### ISSUE TITLE
async_infer GRPC result mapping

### ISSUE THREAD

**Issue by manhtd98** [triton-inference-server/server#5034]
I send multi requests with grpc.async_infer. 
As the tutorials, i send the result to user_data list. How i can map input and user_data :
```
def callback(user_data, result, error):
            if error:
                logger.info(error)
                user_data.append(error)
            else:
                user_data.append(result)

async_requests.append(
                self.triton_client.async_infer(
                    model_name=self.model_name,
                    inputs=input_tensor_grpc,
                    outputs=outputs,
                    callback=partial(callback, user_data),
                    client_timeout=self.time_out,
                )
            )
```

**Comment by tanmayv25** [comment]
You can use [optional request id ](https://github.com/triton-inference-server/client/blob/main/src/python/library/tritonclient/grpc/__init__.py#L1473-L1476) with your async_infer call. The corresponding result object will carry the same id.

Does that answer your question?

**Comment by manhtd98** [comment]
Yeah thanks you for that.
