### ISSUE TITLE
Ragged batching support for PyTorch backend

### ISSUE THREAD

**Issue by kpedro88** [triton-inference-server/server#5050]
**Is your feature request related to a problem? Please describe.**

Other ML backends support ragged batching, while PyTorch does not.

**Describe the solution you'd like**

Support for ragged batching in the PyTorch backend.

**Describe alternatives you've considered**

Some PyTorch models can be converted to ONNX, but not all.

**Additional context**

As noted in https://github.com/triton-inference-server/server/issues/2158#issuecomment-875974766, PyTorch previously had no universal, native support for ragged tensors. However, as of March 2022, this support has been added: https://pytorch.org/docs/master/nested.html. While it is still in a prototype state, it would be useful to start integrating it into the Triton backend, at least to understand if any important functionality is missing.

**Comment by kpedro88** [comment]
The initial use case motivating this issue is a bit esoteric: we have a PyTorch (non-NestedTensor) model that gets converted to ONNX for inference. Not all PyTorch operations are supported in ONNX, so the added operations to reshape the input from ragged batching (which comes in as a flat array from Triton) are slowing down inference substantially. We think this performance hit could be mitigated by staying in PyTorch (and modifying this model to use NestedTensors).

But more generally, it would be good to support this feature in Triton now that PyTorch has integrated it centrally.

**Comment by Tabrizian** [comment]
Thanks for sharing more background on this feature request. I have filed an internal feature request for this.

CC @msalehiNV

**Comment by kpedro88** [comment]
Addressed by https://github.com/triton-inference-server/pytorch_backend/pull/95
