### ISSUE TITLE
Stable-diffusion Example Inference Error due to Triton Server side's triton version update

### ISSUE THREAD

**Issue by tangkangqi** [triton-inference-server/server#5055]
**Description**
Follow the StableDiffusion github README.md steps https://github.com/triton-inference-server/server/tree/main/docs/examples/stable_diffusion,  after running server/model convert/client in docker, then run client.py will fail with log: Stub process is unhealthy.  

Checked triton sever log shows very slower iteration (even comparing with running native .pkl model) and end up with "Stub process is unhealthy and it will be restarted. "

![image](https://user-images.githubusercontent.com/53213125/200901212-8239d552-6903-47db-aea1-8f3f9fd9d56b.png)

**Triton Information**
2.25.0

using Triton container: 
server: nvcr.io/nvidia/tritonserver:22.08-py3

**To Reproduce**
Follow the StableDiffusion github README.md steps https://github.com/triton-inference-server/server/tree/main/docs/examples/stable_diffusion,  after running server/model convert/client in docker, then run client.py will fail with log: Stub process is unhealthy.  

**Expected behavior**
It should successfully generated image in less than 3 seconds.

**Comment by rmccorm4** [comment]
CC @tanayvarshney

**Comment by Tabrizian** [comment]
We have an internal ticket for this.
