### ISSUE TITLE
Problems with installation of python_backend from source

### ISSUE THREAD

**Issue by ethanfa** [triton-inference-server/server#5063]
**Description**
I tried to install the python_backend from the source on a Vagrant VM of Ubuntu 20.04 for CPUs.
I can load the dockers and work with them perfectly on the same Vagrant VM.

**Triton Information**
What version of Triton are you using?
I am using the latest version (22.11)

Are you using the Triton container or did you build it yourself?
- I am trying to build from the source. The Docker version works perfectly.

**To Reproduce**
Steps to reproduce the behavior.
I followed the steps described here:
[https://github.com/triton-inference-server/python_backend](url)
```
$ pip3 install numpy
$ sudo apt-get install rapidjson-dev libarchive-dev zlib1g-dev -y
$ git clone https://github.com/triton-inference-server/python_backend
$ cd python_backend
$ mkdir build
$ cd build
$ cmake -DTRITON_ENABLE_GPU=OFF -DTRITON_BACKEND_REPO_TAG=22.11 -DTRITON_COMMON_REPO_TAG=22.11 -DTRITON_CORE_REPO_TAG=22.11 -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/install ..
```

(CMake version: 3.24.1)

**Expected behavior**
I was expecting a proper installation of python_backend.
[CMakeOutput.log](https://github.com/triton-inference-server/server/files/9981183/CMakeOutput.log)

**Error Message**
[ 11%] Performing download step (git clone) for 'repo-common-populate'
Cloning into 'repo-common-src'...
fatal: invalid reference: 22.11
CMake Error at repo-common-subbuild/repo-common-populate-prefix/tmp/repo-common-populate-gitclone.cmake:49 (message):
  Failed to checkout tag: '22.11'

make[2]: *** [CMakeFiles/repo-common-populate.dir/build.make:102: repo-common-populate-prefix/src/repo-common-populate-stamp/repo-common-populate-download] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/repo-common-populate.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

CMake Error at /usr/share/cmake-3.24/Modules/FetchContent.cmake:1601 (message):
  Build step for repo-common failed: 2
Call Stack (most recent call first):
  /usr/share/cmake-3.24/Modules/FetchContent.cmake:1741:EVAL:2 (__FetchContent_directPopulate)
  /usr/share/cmake-3.24/Modules/FetchContent.cmake:1741 (cmake_language)
  /usr/share/cmake-3.24/Modules/FetchContent.cmake:1955 (FetchContent_Populate)
  CMakeLists.txt:72 (FetchContent_MakeAvailable)

-- Configuring incomplete, errors occurred!
See also "/home/vagrant/python_backend/build/CMakeFiles/CMakeOutput.log".
[CMakeOutput.log](https://github.com/triton-inference-server/server/files/9981138/CMakeOutput.log)

**Comment by Tabrizian** [comment]
@ethanfa You should use r22.11 version instead of 22.11. Also, the latest released version is r22.10.

**Comment by ethanfa** [comment]
Thank you @Tabrizian!
