### ISSUE TITLE
When i use 3060 gpu,can not load model

### ISSUE THREAD

**Issue by xs818818** [triton-inference-server/server#5064]
docker run --gpus="device=0" --name server --rm  --shm-size=32g --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 -p 8000:8000 -p 8001:8001 -p 8002:8002 -v /home/xs/AI/tensorrt-deploy/models:/models  nvcr.io/nvidia/tritonserver:22.07-py3 tritonserver --model-repository=/models  --grpc-infer-allocation-pool-size=16 --log-verbose 1

I1110 14:00:09.525177 1 server.cc:260] Waiting for in-flight requests to complete.
I1110 14:00:09.525187 1 server.cc:276] Timeout 30: Found 0 model versions that have in-flight inferences
I1110 14:00:09.525194 1 model_repository_manager.cc:1230] unloading: cap:1
I1110 14:00:09.525255 1 server.cc:291] All models are stopped, unloading models
I1110 14:00:09.525265 1 server.cc:298] Timeout 30: Found 1 live models and 0 in-flight non-inference requests
I1110 14:00:09.525430 1 tensorrt.cc:5625] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I1110 14:00:09.527726 1 tensorrt.cc:5564] TRITONBACKEND_ModelFinalize: delete model state
I1110 14:00:09.541430 1 model_repository_manager.cc:1335] successfully unloaded 'cap' version 1
I1110 14:00:10.525390 1 server.cc:298] Timeout 29: Found 0 live models and 0 in-flight non-inference requests
error: creating server: Internal - failed to load all models

NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7

**Comment by xs818818** [comment]
[log.txt](https://github.com/triton-inference-server/server/files/9989948/log.txt)

**Comment by xs818818** [comment]
Can you help me how to get a correct logs

**Comment by Tabrizian** [comment]
This is the error. You need to remove this directory from your model repository or move the models to a directory that jupyter notebook checkpoints do not exist.
```
E1111 11:47:24.162917 1 model_repository_manager.cc:2071] Poll failed for model directory '.ipynb_checkpoints': unexpected platform type '' for .ipynb_checkpoints

```

**Comment by xs818818** [comment]
Thank you,i success
