### ISSUE TITLE
mobilenet based model deploy success, but run fail

### ISSUE THREAD

**Issue by cszhz** [triton-inference-server/server#5069]
**Description**
I deployed a mobilenet based model(tensorflow_savedmodel) in triton server, deployment is success, but client invoke fail.

I attempted perf_analyzer and wrote a httpclient, both them does not work.
perf_analyzer -m mobilenet --shape image:224,224,3 --shape true_image_shape:3 --shape Predictions:834

error message:
root@ip-172-31-5-214:/models/mobilenet# perf_analyzer -m mobilenet --shape image:224,224,3 --shape true_image_shape:3 --shape Predictions:834
*** Measurement Settings ***
  Batch size: 1
  Using "time_windows" mode for stabilization
  Measurement window: 5000 msec
  Using synchronous calls for inference
  Stabilizing using average latency

Request concurrency: 1
Failed to maintain requested inference load. Worker thread(s) failed to generate concurrent requests.
Thread [0] had error: 2 root error(s) found.
  (0) Invalid argument: Expected size[0] in [0, 224], but got 1936311936
	 [[{{node map/Slice}}]]
	 [[MobilenetV1/Predictions/Reshape_1/_313]]
  (1) Invalid argument: Expected size[0] in [0, 224], but got 1936311936
	 [[{{node map/Slice}}]]
0 successful operations.
0 derived errors ignored.

--------------------------------------------------------------------------------------------
config.pbtxt
name: "mobilenet"
platform: "tensorflow_savedmodel"
max_batch_size: 1
input [
  {
    name: "image"
    data_type: TYPE_UINT8
    dims: [-1, -1, 3]
    format: FORMAT_NHWC
  },
  {
    name: "true_image_shape"
    data_type: TYPE_INT32
    dims: [ 3]
  }
]
output [
  {
    name: "Predictions"
    data_type: TYPE_FP32
    dims: [832]
  }
]
------------------------------------------------------------------------------

**Triton Information**
What version of Triton are you using?
22.04

Are you using the Triton container or did you build it yourself?
Triton container

**To Reproduce**
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**

**Comment by Tabrizian** [comment]
The error is coming from the model. Does the model work with synthetic data or it can only work with real input data? If it only works with real input data, you can specify it in Perf Analyzer using the guide below:

https://github.com/triton-inference-server/server/blob/main/docs/user_guide/perf_analyzer.md#real-input-data

**Comment by cszhz** [comment]
Thank you for your quick response.
This model can run with your solution by adding 
--input-data sample.json

however when I tried with triton http client, it still raise the same error.
Not sure how to deal with this situation via triton http client.

**Comment by jbkyang-nvi** [comment]
Sorry for the slow response. Can you share your http client?
