### ISSUE TITLE
Provide an API to access configpb.txt programmatically to know which models are configured to run on Triton

### ISSUE THREAD

**Issue by dhawalkp** [triton-inference-server/server#5074]
**Is your feature request related to a problem? Please describe.**
Provide an API to access configpb.txt programmatically to know which models are configured to run on Triton.
Reading a configpb.txt is painful. Instead, it would help to access the same data structure that triton core creates in memory by reading this file. This is particularly helpful to those users who are extending triton inference server to run on Cloud like Amazon SageMaker.
**Describe the solution you'd like**
Provide an API to access configpb.txt programmatically to know which models are configured to run on Triton

**Describe alternatives you've considered**
N/A
**Additional context**
NA

**Comment by dyastremsky** [comment]
Hi Dhawalkumar! Great questions. It looks like there are two separate questions here.

In terms of getting the config of a specific model via GRPC or HTTP, please see [the model configuration extension](https://github.com/triton-inference-server/server/blob/main/docs/protocol/extension_model_configuration.md#model-configuration-extension).

To get all models from Triton via GRPC or HTTP, you can use [the model repository extension](https://github.com/triton-inference-server/server/blob/main/docs/protocol/extension_model_repository.md#index)

If you were looking for something else, please let us know.

**Comment by dhawalkp** [comment]
hi @dyastremsky - Thanks for the pointers! I was actually asking for a public method in cc code that developers can call to get access to the datastructure in-memory rather then making call to http/grpc endpoint(s). For e.g. a developer who is extending the Triton inference server code can easily call this method to access this datastructure to know which models are configured and its state (loaded/unloaded) w/o calling grpc/http method.

**Comment by dyastremsky** [comment]
Any time! Thank you for clarifying. I've filed a ticket to look into this feature request.

**Comment by GuanLuo** [comment]
Are you referring to an Triton core API to retrieve the model config? Have you looked into [`TRITONSERVER_ServerModelConfig`](https://github.com/triton-inference-server/core/blob/main/include/triton/core/tritonserver.h#L2125-L2142) for retrieval and [`TRITONSERVER_MessageSerializeToJson`](https://github.com/triton-inference-server/core/blob/main/include/triton/core/tritonserver.h#L606-L618) for serializing it to JSON? The JSON returned should be able to be parsed into corresponding protobuf message if you want to operate on protobuf format.

**Comment by Tabrizian** [comment]
Closing due to in-activity.
