### ISSUE TITLE
triton server can not start if docker run with specified cpusets using docker run -cpuset-cpus

### ISSUE THREAD

**Issue by aluminumbox** [triton-inference-server/server#5077]
**Description**
Triton server can run use docker run, but fails if use docker run --cupusets

**Triton Information**
nvcr.io/nvidia/tritonserver:22.03-py3

**To Reproduce**

Triton server can start if we simply use docker run --runtime=nvidia --shm-size=1g. But when we specifiy cpu with --cpuset-cpus="0-12". It hangs or fails.

When it hangs, the log shows that it is loading model, but the cpu usage is 0% and the log just stops there.
When it fails , the log shows that 

`E1114 10:33:03.419637 61 model_repository_manager.cc:1234] failed to load 'decoder' version 1: Internal: onnx runtime error 1: /workspace/onnxruntime/onnxruntime/core/platform/posix/env.cc:183 onnxruntime::{anonymous}::PosixThread::PosixThread(const char*, int, unsigned int (*)(int, Eigen::ThreadPoolInterface*), Eigen::ThreadPoolInterface*, const onnxruntime::ThreadOptions&) pthread_setaffinity_np failed, error code: 2 error msg: No such file or directory`

**Expected behavior**

We expect triton server starts correctly even when we specify the cpusets, because this is necessary for production deployment.
It seems that this problem is due to onnxruntime try to bind each thread to logical core, but the logical core might not be all assigned to the container.

`https://github.com/microsoft/onnxruntime/issues/8313`

**Comment by 1215thebqtic** [comment]
Hi, is this problem solved? or I still can't specify the cpuset?

**Comment by yuekaizhang** [comment]
FYI, setting the global thread pool (https://github.com/triton-inference-server/onnxruntime_backend#thread-pools) may help.
