### ISSUE TITLE
getting incorrect output shape

### ISSUE THREAD

**Issue by albertoperdomo2** [triton-inference-server/server#5079]
**Description**
First of all, **I'm not sure if this is a bug or a misunderstanding but I haven't been able to found a solution anywhere else.**

I have set up Triton Inference Server using docker and everything was smooth. I'm serving an instance/custom version of the *mobilenet_sdd* that my team developed in Tensorflow. The issue I'm facing is that using the Python client, I'm getting a response that doesn't seem to be aligned with the configuration for the model given to the server. 

For this particular model, the configuration file looks something like this:
```
name: "my_model"
platform: "tensorflow_savedmodel"
max_batch_size: 0
input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [ 300, 300, 3 ]
    format: FORMAT_NHWC
  }
]
output [
  {
    name: "predictions"
    data_type: TYPE_FP32
    dims: [ 1917, 17 ]
    label_filename: "labels.txt"
  }
]
```

So, I'm expecting an output shaped `[1917, 17]`. However, I'm getting a bytes array that's shaped `[1, 3]`. I tried to interpret the buffer [numpy.frombuffer](https://numpy.org/doc/stable/reference/generated/numpy.frombuffer.html)  using `numpy.float32` but I doesn't get anything close to what I'm expecting. 

The model itself shouldn't be the problem because it's been working in prod for some time and it's been heavily tested. 

For example, after getting the responses from the `triton_client.infer()` calls, and getting the responses *as_numpy*, I end up with something like:
```
[[b'6.252468:9676' b'6.248357:8707' b'6.226352:10645']]
```

As I said, I'm pretty sure that there is a concept misunderstanding rather than a bug itself. 

**Triton Information**
What version of Triton are you using?
2.26.0

Are you using the Triton container or did you build it yourself?
I'm using the docker container. 

**To Reproduce**
Steps to reproduce the behaviour.

This can't be reproduced since it is a proprietary model, but as said, I think I just need some context on how the server itself works.

**Expected behavior**
I expect the model responses to be shaped as I specified in the configuration file.

**Comment by albertoperdomo2** [comment]
Additionally, `max_batch_size: 0` is overwritten to 4.

**Comment by GuanLuo** [comment]
The output looks like you have requested the use of [classification extension](https://github.com/triton-inference-server/server/blob/main/docs/protocol/extension_classification.md#classification-extension) rather than directly returning the model output, can you check your client code to see if this is set for the request?

@nv-kmcgill53 @tanayvarshney for auto-complete question

**Comment by nv-kmcgill53** [comment]
Hi @albertoperdomo2,

>Additionally, I have just checked that max_batch_size: 0 is overwritten to 4.
Due to the way the model configuration is loaded, Triton cannot distinguish between a config with `max_batch_size: 0` and a config with a `max_batch_size` which is omitted. As a workaround you can disable autocomplete by using the `--disable-auto-complete-config` command line flag.

Are you able to post the model configuration of the model once loaded? This can be done by either running Triton with the `--log-verbose=1` command line option set and inspecting the log file or by requesting the config for the model using `curl`
`curl -X GET http://localhost:8000/v2/models/<model_name>/versions/<version_number>/config`.  

This will help us understand better what autocomplete is doing. Thanks!

**Comment by albertoperdomo2** [comment]
@nv-kmcgill53 I tried disabling autocomplete but then it gave me another error (I'll post it later). The model config is the following: 

```
curl localhost:8000/v2/models/mobilenet_ssd/config | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1101  100  1101    0     0   537k      0 --:--:-- --:--:-- --:--:--  537k
{
  "name": "my_model",
  "platform": "tensorflow_savedmodel",
  "backend": "tensorflow",
  "version_policy": {
    "latest": {
      "num_versions": 1
    }
  },
  "max_batch_size": 4,
  "input": [
    {
      "name": "input_1",
      "data_type": "TYPE_FP32",
      "format": "FORMAT_NHWC",
      "dims": [
        300,
        300,
        3
      ],
      "is_shape_tensor": false,
      "allow_ragged_batch": false,
      "optional": false
    }
  ],
  "output": [
    {
      "name": "predictions",
      "data_type": "TYPE_FP32",
      "dims": [
        1917,
        17
      ],
      "label_filename": "",
      "is_shape_tensor": false
    }
  ],
  "batch_input": [],
  "batch_output": [],
  "optimization": {
    "priority": "PRIORITY_DEFAULT",
    "input_pinned_memory": {
      "enable": true
    },
    "output_pinned_memory": {
      "enable": true
    },
    "gather_kernel_buffer_threshold": 0,
    "eager_batching": false
  },
  "dynamic_batching": {
    "preferred_batch_size": [
      4
    ],
    "max_queue_delay_microseconds": 0,
    "preserve_ordering": false,
    "priority_levels": 0,
    "default_priority_level": 0,
    "priority_queue_policy": {}
  },
  "instance_group": [
    {
      "name": "mobilenet_ssd",
      "kind": "KIND_GPU",
      "count": 1,
      "gpus": [
        0,
        1
      ],
      "secondary_devices": [],
      "profile": [],
      "passive": false,
      "host_policy": ""
    }
  ],
  "default_model_filename": "model.savedmodel",
  "cc_model_filenames": {},
  "metric_tags": {},
  "parameters": {},
  "model_warmup": []
}
```

Theoretically, if I set `max_batch_size` to 0, I'm telling Triton that my model doesn't supports batching, right? I think the error I got was something in the line of Triton complaining about batching not being enabled for a model that supports it (even though it doesn't).

**Comment by albertoperdomo2** [comment]
@GuanLuo That makes sense. I took [this client](https://github.com/triton-inference-server/client/blob/main/src/python/examples/image_client.py) as an example. I'm not sure where classification is enabled.

**Comment by albertoperdomo2** [comment]
@nv-kmcgill53 completing my previous reply, the issue I face is the following: I already tried disabling autocomplete of the config, but in that case I got the following error: 
```
E1116 09:23:32.805326 1 model_lifecycle.cc:596] failed to load 'my_model' version 1: Invalid argument: model 'my_model', tensor 'input_1': the model expects 4 dimensions (shape [-1,300,300,3]) but the model configuration specifies 3 dimensions (shape [300,300,3])
```

But the format is set to `FORMAT_NHWC` and I thought that the N was set automatically based on the batch size. If I explicitly set the input dims to `[-1, 300, 300, 3]` I get more errors down the road regarding the size of the input.

**Comment by albertoperdomo2** [comment]
> @GuanLuo That makes sense. I took [this client](https://github.com/triton-inference-server/client/blob/main/src/python/examples/image_client.py) as an example. I'm not sure where classification is enabled.

I have managed to find the issue for the response part. I was passing the number of classes to the output object so I guess that's what triggered the classification. Thank you so much!
