### ISSUE TITLE
Question about the "python_backend"

### ISSUE THREAD

**Issue by ethanfa** [triton-inference-server/server#5081]
**Description**
This is a question, not a bug.
I have a model that converts audio files to their transcripts.
The underlying model is PyTorch and TF, and I want to use the python_backend for its deployment.
The input is the path of the audio file (string), and the output is a JSON file (another string), which can be the path to the resulting JSON file or the JSON text itself (string).

Is the following setting correct for the "config.pbtxt" file?

```
name: "my_Audio_to_Text"
backend: "python"

input [
  {
    name: "INPUT0"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]
output [
  {
    name: "OUTPUT0"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]

instance_group [{ kind: KIND_GPU }]
```

Thank you very much.

**Comment by Tabrizian** [comment]
Hi @ethanfa, yes, the model configuration looks correct to me for the use case you are describing.
