### ISSUE TITLE
Is there any way to check if the model is now used by another client ? Then my client will not unload this model 

### ISSUE THREAD

**Issue by Oldpan** [triton-inference-server/server#5097]
In my situation, a triton model is used by multiple users.
And when one user load this model, another user will not need to load this model again. But when one user will not use this model, the user will try unload this model (the model mabey currently used by another user).
Is there a way user can tell the model is used by another user so he will not send unload order, and make sure the last user do the unload order ( and the first user do the load model).
Thanks~
By the way I use r22.06

**Comment by dyastremsky** [comment]
There is no dynamic way to "mark" models. You could use load models with metadata: https://github.com/triton-inference-server/server/issues/439#issuecomment-509759401

You could then get the model metadata via the API, or even reload the model to update the metadata: https://github.com/triton-inference-server/server/blob/main/docs/protocol/extension_model_repository.md

However, you can't do anything like this where you're not unloading/reloading the model and you're making changes to a model without doing so or assigning ownership of the model.

**Comment by Oldpan** [comment]
Thanks! 
I figured out a way(a simple judge method) to solve this but need some time to perfect this way.
Client can send identify-key value to triton to let triton know which client using this model. 
But like new and delete in C++, sometimes the model will not be unloaded when a client didn't send unload order to triton(when client be killed or core dump happens).
