### ISSUE TITLE
Want to install specific version of TensorRT in Triton server

### ISSUE THREAD

**Issue by hamidriasat** [triton-inference-server/server#5100]
Need help to install specific version of TensorRT in triton server. 
In my case its TensorRT [v8.4.3.1](https://github.com/NVIDIA/TensorRT/tree/release/8.4) with cuda-11.6.x + cuDNN-8.4

As per [support matrix](https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html) no triton server supports this TensorRT version.

I have tried two different ways but both failed for me

- Inside triton [docker container](https://github.com/triton-inference-server/server/tree/r22.08) I tried installing it with Pip but that way it's only accessible to python interpreter not to triton server.   
- [Building With Docker](https://github.com/triton-inference-server/server/blob/main/docs/customization_guide/build.md#building-with-specific-github-branches) only works with triton [TensorRT Backend](https://github.com/triton-inference-server/tensorrt_backend) releases which does not support my required version as mentioned earlier

Any assistance is greatly appreciated.

**Comment by dyastremsky** [comment]
The Triton container builds against the TensorRT version in the same container release. If you want to use a different version of TensorRT, you will need to build Triton against the version that you are using. You may also need to modify Triton code if the TensorRT APIs used are different in other versions.

You might be able to do so by just [build the TensorRT backend ](https://github.com/triton-inference-server/tensorrt_backend) in a container/environment with the right version of TensorRT and put it in the `/opt/tritonserver/backends/tensorrt` directory. With that approach, you'd have to explore the different ways of [updating TensorRT in your container](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#downloading), like you are now. Looking at the container files, I suspect apt-get might be the best approach.

@tanmayv25 Do you know if there is a way to specify the TensorRT version when using the build.py script?

**Comment by tanmayv25** [comment]
There is no way of specifying TensorRT version via build.py.  TensorRT is picked from the installation. You can use the TRT tar ball installation method.

**Comment by hamidriasat** [comment]
Thanks for your reply @dyastremsky and @tanmayv25.
Inside the triton docker container [tar installation](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing-tar) is easy and works fine.
