### ISSUE TITLE
Multi instances's performance is slightly low. [pytorch_backend]

### ISSUE THREAD

**Issue by SeungsuBaek** [triton-inference-server/server#5108]
Hi.

I found that the multi instances's performance is slightly low.
My environment and experiment results is below.

**Machine Information**
```
GPU : TITAN RTX * 3ea
OS : ubuntu 18.04
Triton with pytorch_backend : r22.08
```

**Model config**
```
name: "resnet101"
platform: "pytorch_libtorch"
max_batch_size: 32

instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [ 0 ] or [ 0, 1 ]
  }
]

input [
  {
    name: "INPUT__0"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [3, 224, 224]
  }
]

output [
  {
    name: "OUTPUT__0"
    data_type: TYPE_FP32
    dims: [1000]
    label_filename: "resnet_labels.txt"
  }
]

version_policy: { specific: {versions: [1]}}
```

**perf_analyzer results ( Single Instance gpu: [ 0 ] )**
```
*** Measurement Settings ***
  Batch size: 1
  Using "time_windows" mode for stabilization
  Measurement window: 30000 msec
  Latency limit: 0 msec
  Request Rate limit: 200 requests per seconds
  Using uniform distribution on request generation
  Using asynchronous calls for inference
  Stabilizing using average latency

Request Rate: 200 inference requests per seconds
  Client:
    Request count: 3245
    Delayed Request Count: 537
    Throughput: 90.1381 infer/sec
    Avg latency: 9909994 usec (standard deviation 10169 usec)
    p50 latency: 9906561 usec
    p90 latency: 17777911 usec
    p95 latency: 18744365 usec
    p99 latency: 19588592 usec
    Avg HTTP time: 9908353 usec (send/recv 2162 usec + response wait 9906191 usec)
  Server:
    Inference count: 3245
    Execution count: 3245
    Successful request count: 3245
    Avg request latency: 9893671 usec (overhead 27 usec + queue 9882592 usec + compute input 191 usec + compute infer 10823 usec + compute output 37 usec)

Inferences/Second vs. Client Average Batch Latency
Request Rate: 200, throughput: 90.1381 infer/sec, latency 9909994 usec
```

**perf_analyzer results ( Multi Instance gpu: [ 0, 1 ] )**
```
*** Measurement Settings ***
  Batch size: 1
  Using "time_windows" mode for stabilization
  Measurement window: 30000 msec
  Latency limit: 0 msec
  Request Rate limit: 200 requests per seconds
  Using uniform distribution on request generation
  Using asynchronous calls for inference
  Stabilizing using average latency

Request Rate: 200 inference requests per seconds
  Client:
    Request count: 6230
    Delayed Request Count: 5593
    Throughput: 173.054 infer/sec
    Avg latency: 1381404 usec (standard deviation 19187 usec)
    p50 latency: 1344601 usec
    p90 latency: 2542631 usec
    p95 latency: 2859819 usec
    p99 latency: 3037915 usec
    Avg HTTP time: 1381659 usec (send/recv 536 usec + response wait 1381123 usec)
  Server:
    Inference count: 6231
    Execution count: 6231
    Successful request count: 6231
    Avg request latency: 1359799 usec (overhead 26 usec + queue 1348261 usec + compute input 172 usec + compute infer 11301 usec + compute output 39 usec)

Inferences/Second vs. Client Average Batch Latency
Request Rate: 200, throughput: 173.054 infer/sec, latency 1381404 usec
```

---

Although the performance gap between single and multi-instance is slight, i think that the performance has to be twice when using two instances. When I use three instances the throughput of perf_analyzer's results is 253.442 infer / sec. That means if I add an instance on another GPU, their performance drops about 8~10 infer / sec compared to a single instance.

Why does this happen?

Is it because of request queue contention for two instances? or something other contention that I can not realize?

Thanks for reading.

**Comment by dyastremsky** [comment]
This is a known issue due to an issue in PyTorch. Listed under 21.08 Release Notes, Known Issues: https://docs.nvidia.com/deeplearning/triton-inference-server/release-notes/rel_21-08.html#rel_21-08

> Running a PyTorch TorchScript model using the PyTorch backend, where multiple instances of a model are configured can lead to a slowdown in model execution due to the following PyTorch issue: https://github.com/pytorch/pytorch/issues/27902.

The amount of speedup on multiple instances will also vary. While there are shared resources (e.g. scheduler), it's also going to depend a lot on your system environment and the frameworks used. For example, if one instance of your model is already using most of your GPU, there's going to be a slowdown as you increase the number of instances. Glancing at your time breakdown, I actually see a decrease in the time for each request but an increase in send/recv time, so it looks like this may be HTTP-related.

I don't know that you'd face the same issue running Triton server, since I believe perf_analyzer only uses one client for all the requests and that could result in a slowdown. (CC: @tgerdesnv)

**Comment by tgerdesnv** [comment]
Perf Analyzer uses a different client for each thread. I don't expect that to be related to your issue.

Am I reading it correctly that you are telling perf analyzer to send 200 inferences/second to a server with 3 instances, and you are getting 253 inferences/second back? Or did you increase the request rate for the 3-instance test?

**Comment by SeungsuBaek** [comment]
@tgerdesnv 

Sorry for my poor explanation.

This is my client side command when server has one or two instances of resnet101 model.
If server has two instances of resnet101, one of instances is in gpu0 and another is in gpu1.
```
perf_analyzer -b 1 -m resnet101 --request-rate-range 200:200 -a 
```

The command when server has three instances of resnet101 model.
Instances are in gpu0, gpu1, gpu2 respectively.
```
perf_analyzer -b 1 -m resnet101 --request-rate-range 300:300 -a 
```


single instance of resnet101 (gpu0) -> throughput ~90 infer/sec
double instances of resnet101 (gpu0, gpu1) -> throughput ~173 infer/sec
triple instances of resnet101 (gpu0, gpu1, gpu2) -> throughput ~253 infer/sec

In this situation, multi instances show slightly low performance.
When we use single instance of resnet101, we can get ~90 infer / sec.
Then if we use double or triple instances of resnet101, we have to get ~180 infer/sec, ~270 infer/sec, respectively.

But the results is slightly low.
Since each instance uses a different gpu, the gpu resource contention may not be occured.

So i just wonder why it is happen.

**Comment by tgerdesnv** [comment]
Understood. They don't share GPU resources but they do share the network for receiving and responding to requests. I suspect @dyastremsky was on the right track with this statement:

>Glancing at your time breakdown, I actually see a decrease in the time for each request but an increase in send/recv time, so it looks like this may be HTTP-related.

**Comment by SeungsuBaek** [comment]
@tgerdesnv 

Thanks for your answer.

The reason why I asked this question is that i want to use multiple models parallelly in one Triton server.

However, i have found that the more models there are, the more unintended contention will occur. [MY SYSTEM HAS 32 CORE]

Is there a number of models recommended by Triton depending on the system? I think the more models there are, the more CPU Bottleneck gets.

**Comment by tgerdesnv** [comment]
Please also note that if you are running perf analyzer on the same machine as Triton, then they are competing for CPU resources. That can impact your results, even for models running on the GPU.

As for "how many instances should I use?", that is a question best answered by [Model Analyzer](https://github.com/triton-inference-server/model_analyzer). It is a wrapper around Perf Analyzer that will run multiple experiments to find the best configuration under any constraints you give it (such as a maximum latency budget).

**Comment by SeungsuBaek** [comment]
Thanks.

It is helpful to me.
