### ISSUE TITLE
Bump up curl version for compatibility for Linux 

### ISSUE THREAD

**Issue by RandySheriffH** [triton-inference-server/server#5114]
When building trition client on ubuntu, the curl [version ](https://github.com/triton-inference-server/third_party/blob/58681094de8f4f1fe1535c4f0e8b95f28a769073/CMakeLists.txt#L84) is overly aged to be compatible with openssl 3.x which is now ubiquitous on linux systems. Specifically, curl-7_66_0 brings linker issues for two missing symbols when the system are with openssl.3.x:

- SSL_get_geer_certificate
- EVP_PKEY_id

You need at least curl-7_82_0, where the linker issues are properly [addressed](https://github.com/curl/curl/blob/64db5c575d9c5536bd273a890f50777ad1ca7c13/lib/vtls/openssl.c#L173).
Or - at least make curl tag to be **configurable**.

**Comment by kthui** [comment]
Hi @RandySheriffH, thanks for reporting this issue. I have filed a ticket for us to investigate further.

**Comment by RandySheriffH** [comment]
@kthui: the change looks good thanks! But it's virtually a version upgrade for curl.
