### ISSUE TITLE
Error while nginx proxy

### ISSUE THREAD

**Issue by AndreWanga** [triton-inference-server/server#5116]
**Description**
When I use nginx to proxy triton server, there would be GOAWAY and Socket Close error when I got result

**Triton Information**
2.24.0

Are you using the Triton container or did you build it yourself?
yes
**To Reproduce**
1. nginx config (the nginx version I use is 1.20.2 )
events {
    work_connections 10000;
    multi_accept on;
    accept_mutex on;
    use epoll;
}
http {
    client_max_body_size 4000M;
    grpc_read_timeout 400ms;
    grpc_send_timeout 400ms;
    grpc_buffer_size 100M;
    grpc_next_upstream error timeout http_502 http_504;
    grpc_next_upstream_tries 2;
    underscores_in_headers on;
    
    upstream infer {
        server XX.XX.XX.XX:8001 fail_timeout=10s max_fails=10;
        server XX.XX.XX.XX:8002 fail_timeout=10s max_fails=10;
    }
    server {
        listen 8000 http2;
        location /inference.GRPCInferenceService/ModelInfer {
            grpc_pass grpc://infer;
        }
    }
}
2. start triton server
tritonserver --model-control-mode=poll --strict-model-config=false --model-repository=xx
3. use python triton client async_infer function for query
Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
NER(bert) tensorrt plan FP32
**Expected behavior**
No GOAWAY and Socket Close when I use nginx to proxy

**Comment by dyastremsky** [comment]
Does this work without nginx? Is inference successful in the latest container (Triton 22.10)?

If the answer to both is no, we'll need exact repro steps including a model that reproduces this error. That way we can we reproduce the bug and investigate it.

It sounds like there's an assumption that the issue is nginx, but we have not seen this error in nginx yet. It's quite possible that something is going wrong during the async_infer call (e.g. passing incorrect input data) that's closing the socket prematurely, so please test this outside of nginx if you can.

**Comment by AndreWanga** [comment]
> Does this work without nginx? Is inference successful in the latest container (Triton 22.10)?
> 
> If the answer to both is no, we'll need exact repro steps including a model that reproduces this error. That way we can we reproduce the bug and investigate it.
> 
> It sounds like there's an assumption that the issue is nginx, but we have not seen this error in nginx yet. It's quite possible that something is going wrong during the async_infer call (e.g. passing incorrect input data) that's closing the socket prematurely, so please test this outside of nginx if you can.

There is no GOAWAY and Socket Close Error when I use async_infer call without nginx. Actually when using nginx, not 100%  requests have these error, maybe 1% ~ 10% requests have. However the triton client just can connect one triton server, but we have multi triton servers like a cluster. If the Nginx have some issues with triton server, how can I do load balance via a better way?

**Comment by dyastremsky** [comment]
Nginx can be used to load balance with Triton.

Please provide exact repro steps (including a model e.g. a toy model, commands used, and client script) that causes this issue. We'll need to be able to reproduce the bug to investigate it.

**Comment by AndreWanga** [comment]
> Nginx can be used to load balance with Triton.
> 
> Please provide exact repro steps (including a model e.g. a toy model, commands used, and client script) that causes this issue. We'll need to be able to reproduce the bug to investigate it.
[files.zip](https://github.com/triton-inference-server/server/files/10109943/files.zip)
Here are the files I use. After start nginx and tritonserver with my config file and model.plan. Please change the url in py file to your own and run it.
By the way, the version of TRT I use is 8.4.1.5 and the version of Triton server is 2.24.0

**Comment by AndreWanga** [comment]
> Nginx can be used to load balance with Triton.
> 
> Please provide exact repro steps (including a model e.g. a toy model, commands used, and client script) that causes this issue. We'll need to be able to reproduce the bug to investigate it.

[files.zip](https://github.com/triton-inference-server/server/files/10109984/files.zip)
Here is the file I use. After starting nginx and triton server with my config and .plan file, please change the url of .py file to your own and run it, and you shall see the error.
By the way, the version of triton is 2.24.0 the version of trt is 8.4.1.5

**Comment by dyastremsky** [comment]
Thanks for the reproduction steps. We've filed a ticket to investigate this error.

**Comment by AndreWanga** [comment]
> Thanks for the reproduction steps. We've filed a ticket to investigate this error.

You are welcome ^_^

**Comment by AndreWanga** [comment]
> Thanks for the reproduction steps. We've filed a ticket to investigate this error.

Here is a good news I want to tell you. Haproxy can proxy triton server by using grpc perfectly, and maybe the Nginx has some promblems with proxing grpc

**Comment by dyastremsky** [comment]
Interesting, thank you for finding a fix and updating me! I'll keep this issue open for now in case we find a root cause of the NGINX error.

**Comment by dyastremsky** [comment]
It's possible that the timeout was set too low on the NGINX config. Perhaps 1-10% of the requests take too long and therefore the socket closes?

It seems like this error is specific to this configuration and you've found a good solution. If the above fixes the error and/or you're happy with using Haproxy, I'll close out this ticket.

**Comment by AndreWanga** [comment]
> It's possible that the timeout was set too low on the NGINX config. Perhaps 1-10% of the requests take too long and therefore the socket closes?
> 
> It seems like this error is specific to this configuration and you've found a good solution. If the above fixes the error and/or you're happy with using Haproxy, I'll close out this ticket.

Thanks for you keeping concern about my issue. I try haproxy for one week, the grpc proxy goes well. However the health check for triton server container goes wrong. Because if you running docker container, the port you mapping is always listening, so the tcp check of haproxy think the triton server is alive, but actually the triton server inside container is down. So the issue now became how to do health check for triton server by using gprc directly insead of using tcp check.

**Comment by AndreWanga** [comment]
> It's possible that the timeout was set too low on the NGINX config. Perhaps 1-10% of the requests take too long and therefore the socket closes?
> 
> It seems like this error is specific to this configuration and you've found a good solution. If the above fixes the error and/or you're happy with using Haproxy, I'll close out this ticket.

Actually I try the nginx timeout config many times, no matter how big the number I set, the socket close error will always came out. And as you know, the triton server's throughput is large, it has dinamic batch advantage. Therefore 150 users to triton server is pice of cake. The response AVG is below 10ms.

**Comment by AndreWanga** [comment]
> It's possible that the timeout was set too low on the NGINX config. Perhaps 1-10% of the requests take too long and therefore the socket closes?
> 
> It seems like this error is specific to this configuration and you've found a good solution. If the above fixes the error and/or you're happy with using Haproxy, I'll close out this ticket.

Actually I try the nginx timeout config many times, no matter how big the number I set, the socket close error will always came out. As you know, the triton server's throughput is large, and it has dynamic batch size advantage. Therefore 150 users to triton server is piece of cake. The max response time is below 10ms.

**Comment by AndreWanga** [comment]
> 

Wow! That's great! Thanks for your investigating. I'll close this issue. Glad to talk with you!

**Comment by ken-kuro** [comment]
@AndreWanga Sorry to bring this up again, but could you please share the config of HA Proxy that you used to proxy the infer request?
