### ISSUE TITLE
CPU consumtion much higher when using Triton server + aws inferentia vs aws inferentia alone

### ISSUE THREAD

**Issue by saraRaris** [triton-inference-server/server#5121]
**Description**
I wanted to compare running a model using Triton sever with inferentia vs running a model directly on inferentia + custom and basic grpc server. Inference time did not differ from both set up but I saw a huge difference in CPU usage:
- ~30% for Triton + inferentia
- ~10% for inferentia + basic grpc server
![Screenshot from 2022-12-01 12-15-08](https://user-images.githubusercontent.com/20050415/205039347-7d972d97-2df8-4035-bd2f-b43f917236e8.png)
![Screenshot from 2022-12-01 12-15-41](https://user-images.githubusercontent.com/20050415/205039354-0c81d92a-ce6d-4154-b831-13b0b2374f4c.png)

**Triton Information**
 I'm using tritonserver:22.10-py3

**Question**
I take Triton is much more complex that my basic grpc sever and also comes with more features but wanted to check if this is expected behaviour. Also, this would have an impact on the number of requests that can be processed by the server at the same time. Is there any way to improve this?

**Comment by dyastremsky** [comment]
There are a lot of variables here. Which backends are you using? How large are your models and how are they configured (e.g. CPU-only, multiple instances, etc.). Are you measuring while idle or processing requests?

Triton is likely going to use more CPU than a basic GRPC server. Triton provides performance gains and optimization options for many models and backends, so the number of requests you can process would be higher than a simple server in many cases (even given the additional CPU usage). It depends on your use case.

**Comment by rmccorm4** [comment]
To add onto this, you may want to try disabling any features of Triton you're not using for this comparison. For example, Triton will track various statistics and metrics over an HTTP server in addition to the GRPC server you're inferencing on. If using `polling` mode for the model repository, Triton may be doing some work there every few seconds and you may prefer `explicit` mode instead if you don't expect model changes on the fly. There are many options to configure.

I would take a look at `tritonserver -h` and go through any options you don't need and disable them.

One example:
```
tritonserver --allow-http false --allow-metrics false ...
```

**Comment by saraRaris** [comment]
This was useful, thank you for your answers.
