### ISSUE TITLE
Does triton support kv_cache?

### ISSUE THREAD

**Issue by jike-algorithm-zhangxiao** [triton-inference-server/server#5124]
In transformer decoder, pytorch implemention always cache the key and value to reduce computation.
Does triton support?
I want to use triton to deploy whisper, found not use kv-cache, the speed is slowly.

**Comment by dyastremsky** [comment]
We do have implementing a generic cache on our roadmap, though I don't know if that's what you're looking for. If the framework can handle it, then you can do so in Triton.

If the framework and model do not support it, then your best bet would be using [Implicit State Management](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/architecture.md#implicit-state-management) feature, which is available for the ONNX Runtime and TensorRT backends. It may also be worthwhile to look at the [FasterTransformer backend for Triton](https://github.com/triton-inference-server/fastertransformer_backend), as I believe they worked through some similar questions in building it.

**Comment by jike-algorithm-zhangxiao** [comment]
thanks
