### ISSUE TITLE
NvFuser is disabled

### ISSUE THREAD

**Issue by clementruhm** [triton-inference-server/server#5128]
**Description**
Following https://github.com/triton-inference-server/pytorch_backend#parameters, I edited my config for the model to have:
```
name: "convertor"
platform: "pytorch_libtorch"
max_batch_size: 16
dynamic_batching {
  max_queue_delay_microseconds: 100000
  preserve_ordering: true
}
parameters: {
  key: "INFERENCE_MODE"
    value: {string_value: "true"}
}
parameters: {
  key: "ENABLE_NVFUSER"
    value: {string_value: "true"}
}
...
```

I see:
```
I1203 11:36:18.813575 254 model_lifecycle.cc:459] loading: convertor:1
I1203 11:36:18.814144 254 libtorch.cc:2034] TRITONBACKEND_ModelInitialize: convertor (version 1)
I1203 11:36:18.814923 254 libtorch.cc:313] Optimized execution is enabled for model instance 'convertor'
I1203 11:36:18.814939 254 libtorch.cc:332] Cache Cleaning is disabled for model instance 'convertor'
I1203 11:36:18.814947 254 libtorch.cc:349] Inference Mode is enabled for model instance 'convertor'
W1203 11:36:18.814959 254 libtorch.cc:454] NvFuser is disabled for model instance 'convertor'
I1203 11:36:18.814997 254 libtorch.cc:2078] TRITONBACKEND_ModelInstanceInitialize: convertor (GPU device 0)
```
So despite config I can see that NvFuser is still disabled. However later on, I can see warnings:

```
[W cuda_graph_fuser.h:17] Warning: RegisterCudaFuseGraph::registerPass() is deprecated. Please use torch::jit::fuser::cuda::setEnabled(). (function registerPass)
```

So does the fuser work? Is the configuration correct?  I tried to put both inference mode and enable nvfuser into a single parameters{} but it complains about multiple "key".

**Triton Information**
22.11

Are you using the Triton container or did you build it yourself?
container

**Expected behavior**
"NvFuser is enabled for model instance 'convertor'"

**Comment by rmccorm4** [comment]
Hi @clementruhm ,

I looked into this issue and NVFuser should now be re-enabled as of the above commits. You will likely see this change reflected in the 23.01 tritonserver release, assuming no issues arise.

**Comment by SeungsuBaek** [comment]
Hi. 

I have a question about NVFUSER with pytorch_backend.

I run a tritonserver that has resnet101 * 10 on device 0.
In this situation, compute infer time is increasing regardless of sharing gpu device.

So, i saw the profiling results with nsight system.
I saw many of pthread_mutex_lock when thread calls nvfuser operation.

Can you tell me about the reason of calling many of pthread_mutex_lock?

I think that these locks make my triton server worse.

```
I1207 12:28:49.572072 7471 libtorch.cc:313] Optimized execution is enabled for model instance 'resnet101-1'
I1207 12:28:49.572087 7471 libtorch.cc:332] Cache Cleaning is disabled for model instance 'resnet101-1'
I1207 12:28:49.572095 7471 libtorch.cc:349] Inference Mode is disabled for model instance 'resnet101-1'
I1207 12:28:49.572105 7471 libtorch.cc:444] NvFuser is not specified for model instance 'resnet101-1'
```


I added ENABLE_NVFUSER false in my model configuration and solved the problem.
But i'm still wonder why many of locks are called by each of model instance's thread.

**Comment by SeungsuBaek** [comment]
Hi.

I have a question about NVFUSER with pytorch_backend.

I run a tritonserver that has resnet101 * 10 on device 0.
In this situation, compute infer time is increasing regardless of sharing gpu device.

So, i check the profiling results by nsight system.
I saw many of pthread_mutex_lock when thread calls nvfuser operation.

Can you tell me about the reason of calling many of pthread_mutex_lock?

I think that these locks make my triton server worse.

I1207 12:28:49.572072 7471 libtorch.cc:313] Optimized execution is enabled for model instance 'resnet101-1'
I1207 12:28:49.572087 7471 libtorch.cc:332] Cache Cleaning is disabled for model instance 'resnet101-1'
I1207 12:28:49.572095 7471 libtorch.cc:349] Inference Mode is disabled for model instance 'resnet101-1'
I1207 12:28:49.572105 7471 libtorch.cc:444] NvFuser is not specified for model instance 'resnet101-1'
I added ENABLE_NVFUSER false in my model configuration and solved the problem.
But i'm still wonder why many of locks are called by each of model instance's thread.
