### ISSUE TITLE
[Question] Is it possible to disable model concurrency ? 

### ISSUE THREAD

**Issue by MatthieuTPHR** [triton-inference-server/server#5134]
Hello ! 

I am currently serving multiple models, each of which requires about 80-90% of the GPU Throughput.
I notice that when I send requests to all models one model at a time I get a much better latency than when sending them in parallel. 
I haven't found a way to disable model concurrency and to enforce a single queue for all models on the same instance. 

Is it possible to group multiple models into a single queue  so that each requests is processed without concurrency ?

**Comment by GuanLuo** [comment]
You may find [rate limiter](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/rate_limiter.md#using-rate-limiter) fitting your need, you can define an abstract resource that is shared among the models to limit model concurrency.

**Comment by MatthieuTPHR** [comment]
Ok thank you very much !!
