### ISSUE TITLE
how to add lib and header into different c++ project

### ISSUE THREAD

**Issue by MrHoang1999** [triton-inference-server/server#5145]
I want to add Lib into my project. How to add lib
I am newbie. Thanks .

**Comment by rmccorm4** [comment]
Hi @MrHoang1999 ,

I would look into using CMake and referencing how some of the Triton repos interact with each other. For example, you'll see most repos pull in Triton core/common library dependencies like [this](https://github.com/triton-inference-server/developer_tools/blob/main/server/CMakeLists.txt#L39-L63).

Another example would be the [simple application example](https://github.com/triton-inference-server/server/blob/ce4e008e053cfcefc935ea146dc81f8bdf3109a7/src/simple.cc) we have, which is built [here](https://github.com/triton-inference-server/server/blob/ce4e008e053cfcefc935ea146dc81f8bdf3109a7/src/CMakeLists.txt#L645-L707).
