### ISSUE TITLE
how to keep model output on gpu in python-backend?

### ISSUE THREAD

**Issue by jike-algorithm-zhangxiao** [triton-inference-server/server#5146]
I wanna use bls model in python backend, which ensemble model1 and model1 and some logic process
 How can i keep model1's output on gpu and make some output as model2's input?

I have add some config such as parameters: { key: "FORCE_CPU_ONLY_INPUT_TENSORS" value: {string_value:"no"}}

And also i wonder if i put some model1's output on gpu, can this value directly been used as model2's input? 
or just they also need copy?

**Comment by rmccorm4** [comment]
Hi @jike-algorithm-zhangxiao ,

I believe using [dlpack](https://github.com/triton-inference-server/python_backend#interoperability-and-gpu-support) in the Python backend model is what you'll be looking for to keep tensors in GPU memory.

**Comment by jike-algorithm-zhangxiao** [comment]
great!
