### ISSUE TITLE
[Question] about NVFUSER with pytorch backend

### ISSUE THREAD

**Issue by SeungsuBaek** [triton-inference-server/server#5147]
Hi.

I have a question about NVFUSER with pytorch_backend.

I run a tritonserver that has resnet101 * 10 on device 0 and did not write ENABLE_NVFUSER option in model configuration.
In this situation, compute infer time is increasing regardless of sharing gpu device and cpu resource.

So, i check the profiling results by nsight system.
I saw many of pthread_mutex_lock when thread calls nvfuser operation.

Can you tell me about the reason of calling many of pthread_mutex_lock?

I think that these locks make my triton server worse.

I added ENABLE_NVFUSER false in my model configuration and solved the problem.
But i'm still wonder why many of locks are called by each of model instance's thread.

Version of triton : r22.08

**Comment by GuanLuo** [comment]
I think nvfuser is disable in 22.08 release due to some framework issues. @rmccorm4 ^^

Can you share more detail? Are the lock from PyTorch framework? If so, the issue should be raised in PyTorch repository.

**Comment by SeungsuBaek** [comment]
Yes. I had saw that issue and wrote this.

The bottleneck can be seen in forward function of pytorch jit module.

As you mentioned, this issue should be raised in PyTorch repo.

Thanks for reply.
