### ISSUE TITLE
Change model namespacing to allow Triton to re-use model names across different model repos

### ISSUE THREAD

**Issue by nskool** [triton-inference-server/server#5150]
**Is your feature request related to a problem? Please describe.**
Currently, if model names repeat across multiple repositories (e.g., in multiple ensemble setup where each ensemble resides in its own repository), one runs into the following error:
```
... failed to poll model `add_sub_1`: not unique across all model repositories
```

**Describe the solution you'd like**
1. While it's noted that Triton uses model names as unique identifies of a model and that in a flat namespace, all model names must be unique. However, it'll be useful to have Triton look for add_sub_1 first within the model repo in which it's called by ensemble proper, and then in a global namespace.
2. I.e. customers can just clone their ensemble model and re-use the existing model names instead of making them unique. 

**Describe alternatives you've considered**
1. Offline renaming of model names to make them unique, however, some customers may prefer to not do this as it's added maintenance

**Additional context**

**Comment by dzier** [comment]
@nskool This looks to be a bug. We have filed a ticket internally with the team to track and investigate

**Comment by nskool** [comment]
@GuanLuo Thank you for the fix. I tested the fix and currently works as expected! To enable it in SageMaker, we need to provide cmdline arg in entrypoint - I've created a PR for that, can you take a look - https://github.com/triton-inference-server/server/pull/5540

**Comment by nskool** [comment]
Closing this as it's fixed and merged, thank you again!
