### ISSUE TITLE
Detecting abrupt stream closing in C++ client library

### ISSUE THREAD

**Issue by git-bruh** [triton-inference-server/server#5154]
**Description**
Not exactly a bug, but I needed some clarifications regarding the C++ triton client API.

**Triton Information**
What version of Triton are you using?
21.08

Are you using the Triton container or did you build it yourself?
Container

**To Reproduce**

Pseudocode-ish example

```c
InferenceServerGrpcClient::Create(&triton_client, url_, /*verbose*/ false);
triton_client->StartStream([&](tc::InferResult *result) {
   if (detect_end_of_stream(result)) atomic_global_bool.set(thread_done);
}
```

Here, the constructor for the inference server client internally creates a new thread that constantly receives data from the server https://github.com/triton-inference-server/client/blob/main/src/c%2B%2B/library/grpc_client.cc#L1530

Now the callback is invoked by the thread on receiving data, and the callback knows that it's finished by identifying that the recived data corresponds to the end of a stream.

However, in the case that the server crashes for some reason, the thread simply exits without any indication whatsoever (`// End loop if Read() returns false`)

In my case, the callback sets a global boolean that the main thread polls to know when the data is ready to be used. But if the server abrubtly dies, the client library doesn't inform that the thread has actually exited, which leads to a deadlock since the callback doesn't get called.

So am I missing something obvious or should there be something like a `FinishCallback` invoked here? https://github.com/triton-inference-server/client/blob/main/src/c%2B%2B/library/grpc_client.cc#L1573

**Expected behavior**
The library should have some mechanism to communicate connection disruption

**Comment by rmccorm4** [comment]
CC @tanmayv25 @jbkyang-nvi do you know how the C++ client library currently handles an unexpected closed stream as described above?

**Comment by jbkyang-nvi** [comment]
From my brief search it seems that Triton uses [ClientReaderWriter](https://grpc.github.io/grpc/cpp/classgrpc_1_1_client_reader_writer.html) which is a blocking call. Maybe you can call 
(isServerLive)[https://github.com/triton-inference-server/client/blob/main/src/c%2B%2B/library/grpc_client.h#L158] in your callback?

**Comment by git-bruh** [comment]
I think you misunderstood, let me clarify a bit more. My code is pretty much adapted from this example code, so it should give a clear idea.

Firstly, for feeding the data, `AsyncStreamInfer` is called repeatedly:

https://github.com/NVIDIA/DeepLearningExamples/blob/master/Kaldi/SpeechRecognition/kaldi-asr-client/asr_client_imp.cc#L194

Any failure here due to the server crashing will immediately be propogated by the library as an error: https://github.com/triton-inference-server/client/blob/main/src/c%2B%2B/library/grpc_client.cc#L1334

Now, in the `AsyncStreamTransfer` thread, where the client library communicates with the server for getting inferences, there is no attempt made to propogate a closed stream back to the user via some sort of `OnFinishCallback` (Considering the async nature of the api)

https://github.com/triton-inference-server/client/blob/main/src/c%2B%2B/library/grpc_client.cc#L1272
https://github.com/triton-inference-server/client/blob/main/src/c%2B%2B/library/grpc_client.cc#L1534

So, say the client library gets successful responses 5 times and invokes the callback that many times. However, say it is only the 6th callback that would satisfy the `end_of_stream` criteria:

https://github.com/NVIDIA/DeepLearningExamples/blob/master/Kaldi/SpeechRecognition/kaldi-asr-client/asr_client_imp.cc#L57

If the server dies in between, then the 6th call may never be executed, leading to a deadlock in the user code.

The thread indicates that it's work is finished only when `end_of_stream` evaluates to true:

https://github.com/NVIDIA/DeepLearningExamples/blob/master/Kaldi/SpeechRecognition/kaldi-asr-client/asr_client_imp.cc#L104 (Basically the user code itself launches multiple triton clients, and `n_in_flight` represents all the clients that haven't finished yet. So whenever a client detects that the async streamer thread has finished and the callback won't be called anymore, it decrements the variable which is polled here until it becomes 0: https://github.com/NVIDIA/DeepLearningExamples/blob/master/Kaldi/SpeechRecognition/kaldi-asr-client/asr_client_imp.cc#L199)

Now if there was something like a FinishCallback that the async thread used to communicate that it's exiting, the code could be something like this:

```c
 triton_client->SetOnFinishCallback(...) {
  if (client_did_not_indicate_success_already) {
    set_error_somewhere();
    n_in_flight--;
  }
```

This would ensure that `n_in_flight` is never left un-decremented by a given thread.

**Comment by jbkyang-nvi** [comment]
The client does not such a functionality. Like I said [ClientReaderWriter](https://grpc.github.io/grpc/cpp/classgrpc_1_1_client_reader_writer.html) does not have API that calls "isFinished" even though we can close it through `Finish()`. 
It seems like `IsServerLive` is something you can call to break out of the loop (as a part of the callback), or you can set a [timeout](https://github.com/triton-inference-server/client/blob/main/src/c%2B%2B/library/common.h#L209-L217) on the AsyncStreamInfer() request to stop the deadlock

**Comment by git-bruh** [comment]
Alright, thanks!
