### ISSUE TITLE
tritonserver: unrecognized option '--cloud-credentials=path/to/creds/.json'

### ISSUE THREAD

**Issue by Yuvraj2300** [triton-inference-server/server#5155]
**Description**
Unable to provider credentials for connecting to GCP storage. Providing parameter --cloud-credentials' throws the following error :
```
tritonserver: unrecognized option '--cloud-credentials='--cloud-credentials=path/to/creds/.json'
Usage: tritonserver [options]
  --help
	Print usage
.
.
.
```

**Triton Information**
What version of Triton are you using?
**nvcr.io/nvidia/tritonserver:22.11-py3** 

Are you using the Triton container or did you build it yourself?
Using the Triton Container.

**To Reproduce**
Steps to reproduce the behavior.:
run the following command :
docker run --rm -p8000:8000 -p8001:8001 -p8002:8002 nvcr.io/nvidia/tritonserver:22.11-py3 tritonserver --model-repository=gs://my-bucket/model_repository --cloud-credentials=path/to/creds/.json

**Expected behavior**
The Triton server must connect to the GCS bucket and start up

**Comment by Yuvraj2300** [comment]
Never mind, I'm setting TRITON_CLOUD_CREDENTIAL_PATH variable for container. It's working fine.

**Comment by okyspace** [comment]
May I know where to get the info to set TRITON_CLOUD_CREDENTIAL_PATH ?
