### ISSUE TITLE
archive_write_data_block() failed with error code = -20, error message is Write failed for model.py (ensemble model deployment on triton)

### ISSUE THREAD

**Issue by anshudaur** [triton-inference-server/server#5156]
**Description**
Deploying an onnx model as an ensemble with python backend on triton , gives below error 

archive_write_data_block() failed with error code = -20, error message is Write failed for model.py (ensemble model deployment on triton)

**Triton Information**
What version of Triton are you using? 22.07

Are you using the Triton container or did you build it yourself? Triton container

**To Reproduce**
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

onnx exported model : and the error I get is rand for either preprocessing and  postprocessing . If I delete __pycache__ files created while starting triton script, then only one of the script works. 

config : 

backend: "python"

input [
  {
    name: "IMAGE_BYTES"
    data_type: TYPE_STRING
    dims: [1]
  }
]

output [
  {
    name: "images"
    data_type: TYPE_FP32
    dims: [1, 3, 640, 640]
  },
  {
    name: "image_shape"
    data_type: TYPE_INT32
    dims: [2]
  }
]
instance_group [
    {
      count: 1
      kind: KIND_GPU
    }
  ]
parameters: {
  key: "EXECUTION_ENV_PATH",
  value: {string_value: "$$TRITON_MODEL_DIRECTORY/pyenv.tar.gz"}
}

**Expected behavior**

The errors occurs when the number of models increases, for this I also increase shm-size to 2gb

Onnx Models loading with ready status on triton

Thank you!

**Comment by nv-kmcgill53** [comment]
Hi @anshudaur, are you able to provide us with the output from triton when the error occurs as well as the full command to run tritonserver (i.e. `$tritonserver --model-repository=....`)? Also depending on the number of models you are loading, you may want to increase the shm-size to something larger such as 10gb. This is the value we test with.

**Comment by anshudaur** [comment]
@nv-kmcgill53 Thank you :)  Increasing shared memory size and rebuilding the environment worked for me .
