### ISSUE TITLE
[Question]Why triton inference server uses different gpu devices when inference?

### ISSUE THREAD

**Issue by uitae** [triton-inference-server/server#5157]
I tested some image classification examples with example model(densenet_onnx, inception_graphdef) of model repository(https://github.com/triton-inference-server/server/tree/main/docs/examples/model_repository) and also some image classification models such as resnet, alexnet, ... with $ /workspace/install/bin/image_client.

What I'm curious about is that when I run 4 times through image client for the interference of the model with 4 gpus, I checked that 4 times were fairly divided into gpu devices like device 0->2->1->3. I just use image client when the image client was finished and print the output. just use command image_client and enter and again. So I think this is not about scheduling because there is no object in scheduling queue. I just take 1 inference again and again. I don't know why the triton inference server take inferences to different gpus. Is it about model instance? And Can I take inference specific models to specific gpu? for example model1 and model2 at device 0 and model3 at device 1?

**Comment by nv-kmcgill53** [comment]
Hi @uitae,

>Can I take inference specific models to specific gpu? 

[Here](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/model_configuration.md#multiple-model-instances) you can read about how you can configure your model to have multiple instances and how you can specify which GPUs you would like your instances to run on. 

The reason subsequent requests go to different GPUs is Triton, by default, will round robin requests to the different model instances. So if there is one instance on each GPU, then you will see requests be executed as you saw.
