### ISSUE TITLE
Question: Order of responses for the same request for decoupled models.

### ISSUE THREAD

**Issue by lenards-speechmatics** [triton-inference-server/server#5159]
I understand that in general there is no guaranteed order of responses for decoupled models. Responses of different requests can come out of order, and we do observe that behavior.

In some experiments we also observed that the responses for any given request came in the order of the backend sending them. Is this guaranteed?

Is there any guarantee for the order of responses for the same request?

**Comment by nv-kmcgill53** [comment]
CC @Tabrizian

**Comment by Tabrizian** [comment]
For a single request the responses will be delivered in the same order that they are received from the backend assuming that you are using the [gRPC streaming clients](https://github.com/triton-inference-server/client/blob/main/src/python/examples/simple_grpc_sequence_stream_infer_client.py).

**Comment by lenards-speechmatics** [comment]
Yes, we are using the gRPC streaming clients.

> same order that they are received from the backend

Just to clarify, is this the same order as the backend sends them?

**Comment by Tabrizian** [comment]
Exactly.

**Comment by lenards-speechmatics** [comment]
Thank you, this answers my question.

It was not clear for me from reading these:
* https://github.com/triton-inference-server/server/blob/dfc6f196c1cbc191f4d3e6b0ae7d0e55e9de3fab/docs/user_guide/decoupled_models.md
* https://github.com/triton-inference-server/backend/blob/35f50359d3bcd23b9c9f17a31e4074879db7b948/README.md#decoupled-responses
* https://github.com/triton-inference-server/common/blob/5313d0be99204c89ab696023534043f2ba535868/protobuf/model_config.proto#L1712-L1717.

Consider updating some of these documentations to include this information.
