### ISSUE TITLE
How can I make this scenario with image_client? 

### ISSUE THREAD

**Issue by uitae** [triton-inference-server/server#5162]
![image](https://user-images.githubusercontent.com/65074073/207251714-c894cf6c-e3b1-434d-b25e-9d5adf0446b9.png)

How can I make this scenario with image_client?
Can image_client used for parallel inference? Then how? Or is there any client execution for make that scenario?
Thank you

**Comment by nv-kmcgill53** [comment]
Hi @uitae, If you are looking for a quick demonstration of observing concurrent execution with multiple model instances, I would suggest wrapping the image_client example in a shell script which is called in quick succession. Observe, with the [Metrics endpoint](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/metrics.md), that multiple instances of the model have requests routed to them.

If you are looking to modify the image_client to induce this behavior, I would suggest referencing one of our other examples, [simple_http_async_infer_client.cc](https://github.com/triton-inference-server/client/blob/main/src/c%2B%2B/examples/simple_http_async_infer_client.cc), to help you. 

@jbkyang-nvi Do you know of any other client examples which would show this behavior?

**Comment by jbkyang-nvi** [comment]
Another thing to note is that the parallel part is configured as a part of the model configuration. You can read up more about this in the [optimization using model instances readme](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/optimization.md#model-instances). This is also noted from the original readme:

> Triton provides a [model configuration option called instance-group](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/model_configuration.md#instance-groups) that allows each model to specify how many parallel executions of that model should be allowed.

the inception_graphdef model provided does not have this enabled.
