### ISSUE TITLE
problem about  daemonts  svclb-tritoninferenceserve

### ISSUE THREAD

**Issue by liujie1008cn** [triton-inference-server/server#5163]
1) I install tritoninferenceserver with helm install, accoriding to "https://catalog.ngc.nvidia.com/orgs/nvidia/helm-charts/tritoninferenceserver".
2) The tritoninferenceserver cann't run normally  under k8s cluster, so I uninstall tritoninferenceserver.
3) we found the daemonset svclb-tritoninferenceserve is existed, it can cause other problems.

the daemonsets are stilled existed after using " kubectl delete daemonset svclb-tritoninferenceserve".

How can I delete the daemonset svclb-tritoninferenceserve?

**Comment by jbkyang-nvi** [comment]
Hi, sorry for the slow response. Did you follow the cleanup instructions on helm? https://catalog.ngc.nvidia.com/orgs/nvidia/helm-charts/tritoninferenceserver
