### ISSUE TITLE
[Question] Is there a way to specify a different filename depending on the GPU ? 

### ISSUE THREAD

**Issue by MatthieuTPHR** [triton-inference-server/server#5164]
I have seen it is possible to select different models based on the Cuda Arch, unless I am mistaken that would not work for TensorRT models as they are compiled per GPU and not per Cuda Arch. 

Hence, I am wondering if it is possible to select different model files depending on the GPU type rather than the Cuda Arch?

**Comment by rmccorm4** [comment]
Hi @MatthieuTPHR ,

Currently you can only map filenames based on Compute Capability as you pointed out. Here's an example: https://github.com/triton-inference-server/server/issues/4657#issuecomment-1210051741

If you have 2 A100s for example, it should be OK if both TRT models were generated on the same GPU. If you have 2 different GPUs with the same compute capability on the same system such as a T4 and an RTX 2080 (both CC 7.5), then I don't think this would work.

However, if the GPUs are at fixed indexes (ex: T4 is GPU 0, and RTX 2080 is GPU 1), you could create two model directories with different `config.pbtxt` and specify which GPU each model would get if you wanted to share the same tritonserver container.

You could also create separate tritonserver containers with isolated GPUs (`docker run --gpus "device=0"`, `docker run --gpus "device=1"`, ...) and deploy that way as well. Or make use of CUDA_VISIBLE_DEVICES similarly.

**Comment by MatthieuTPHR** [comment]
Thank you ! In my case it would be different GPUs on different instances. I was asking this so I don't need to build a model repository per GPU type and duplicate config files across folders / buckets.
