### ISSUE TITLE
[Question] Is it possible to add custom information in a model config ? 

### ISSUE THREAD

**Issue by MatthieuTPHR** [triton-inference-server/server#5165]
Most of the TensorRT models we shipped need to have dynamic input size within a range defined at compilation time. 

I am wondering if it is possible to specify this range in the config so that the triton client has access to it ? 

More globally is it possible to add other custom infos in the model config that the client could then access ?

**Comment by rmccorm4** [comment]
Hi @MatthieuTPHR ,

You should be able to define some arbitrary metadata as KV pairs in a model's `config.pbtxt` with the [parameters](https://github.com/triton-inference-server/server/blob/2fa2ceb6b4d30e45304b703abcaeec39981380ce/qa/custom_models/custom_sequence_int32/config.pbtxt#L68-L73) field.

You can then get the model config on the client-side calling [triton_client.get_model_config(model_name)](https://github.com/triton-inference-server/client/blob/4bb65af5c8affadeee954e358ebead72717aebe2/src/python/examples/simple_grpc_health_metadata.py#L100-L101) and parse as needed.

**Comment by MatthieuTPHR** [comment]
Ok thank you very much !
