### ISSUE TITLE
Fatal error - No such file or directory when building custom PyTorch backend

### ISSUE THREAD

**Issue by mhbassel** [triton-inference-server/server#5167]
Hello! Does anyone know how to solve this please? 

**Error**
```
[  3%] Building NVCC (Device) object _deps/repo-backend-build/CMakeFiles/kernel-library-new.dir/src/kernel-library-new_generated_kernel.cu.o
[  7%] Linking CXX static library libkernel-library-new.a
[  7%] Built target kernel-library-new
[ 11%] Building CXX object _deps/repo-common-build/CMakeFiles/triton-common-async-work-queue.dir/src/async_work_queue.cc.o
[ 15%] Building CXX object _deps/repo-common-build/CMakeFiles/triton-common-async-work-queue.dir/src/error.cc.o
[ 19%] Building CXX object _deps/repo-common-build/CMakeFiles/triton-common-async-work-queue.dir/src/thread_pool.cc.o
[ 23%] Linking CXX static library libtritonasyncworkqueue.a
[ 23%] Built target triton-common-async-work-queue
[ 26%] Building CXX object _deps/repo-core-build/CMakeFiles/triton-core-serverstub.dir/src/tritonserver_stub.cc.o
[ 30%] Linking CXX shared library libtritonserver.so
[ 30%] Built target triton-core-serverstub
[ 34%] Building CXX object _deps/repo-backend-build/CMakeFiles/triton-backend-utils.dir/src/backend_common.cc.o
[ 38%] Building CXX object _deps/repo-backend-build/CMakeFiles/triton-backend-utils.dir/src/backend_input_collector.cc.o
[ 42%] Building CXX object _deps/repo-backend-build/CMakeFiles/triton-backend-utils.dir/src/backend_memory.cc.o
[ 46%] Building CXX object _deps/repo-backend-build/CMakeFiles/triton-backend-utils.dir/src/backend_model_instance.cc.o
[ 50%] Building CXX object _deps/repo-backend-build/CMakeFiles/triton-backend-utils.dir/src/backend_model.cc.o
[ 53%] Building CXX object _deps/repo-backend-build/CMakeFiles/triton-backend-utils.dir/src/backend_output_responder.cc.o
[ 57%] Linking CXX static library libtritonbackendutils.a
[ 57%] Built target triton-backend-utils
[ 61%] Building CXX object CMakeFiles/triton-pytorch-backend.dir/src/libtorch.cc.o
In file included from /media/ssdraid/training/triton/pytorch_backend/build/pytorch/torch/csrc/jit/codegen/cuda/interface.h:3,
                 from /media/ssdraid/training/triton/pytorch_backend/src/libtorch_utils.h:36,
                 from /media/ssdraid/training/triton/pytorch_backend/src/libtorch.cc:29:
/media/ssdraid/training/triton/pytorch_backend/build/pytorch/c10/macros/Export.h:44:10: fatal error: c10/macros/cmake_macros.h: No such file or directory
   44 | #include <c10/macros/cmake_macros.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/triton-pytorch-backend.dir/build.make:76: CMakeFiles/triton-pytorch-backend.dir/src/libtorch.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:149: CMakeFiles/triton-pytorch-backend.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Backend Information**
nvcr.io/nvidia/pytorch: 22.08-py3

**To Reproduce**
I followed the steps in: https://github.com/triton-inference-server/pytorch_backend

But when I run this command, I get the above error:
```
$ cmake -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/install -DTRITON_PYTORCH_INCLUDE_PATHS="pytorch;pytorch/torch/csrc/api/include;vision/torchvision" -DTRITON_PYTORCH_LIB_PATHS="libs" ..
$ make install
```
The paths and their counterparts on the backend container: (I copied them to my local)
`pytorch: /opt/pytorch/pytorch`
`pytorch/torch/csrc/api/include:  /opt/pytorch/pytorch/torch/csrc/api/include`
`vision/torchvision: /opt/pytorch/vision/torchvision`
`libs: /usr/local/lib`

Maybe I copied the wrong paths from the container?

Any help will be appreciated!
Thanks.

**Comment by nv-kmcgill53** [comment]
Hi @mhbassel, I see you are attempting to compile the pytorch backend with an older, 22.08, container. By default your command:
>$ cmake -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/install -DTRITON_PYTORCH_INCLUDE_PATHS="pytorch;pytorch/torch/csrc/api/include;vision/torchvision" -DTRITON_PYTORCH_LIB_PATHS="libs"

will pull down the `main` branch of the required triton dependencies: `backend`, `core`, and `common`. Can you please try recompiling using the specified branches?

```
$ cmake -DTRITON_BACKEND_REPO_TAG=r22.08 -DTRITON_CORE_REPO_TAG=r22.08 -DTRITON_COMMON_REPO_TAG=r22.08 -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/install -DTRITON_PYTORCH_INCLUDE_PATHS="pytorch;pytorch/torch/csrc/api/include;vision/torchvision" -DTRITON_PYTORCH_LIB_PATHS="libs" ..
```

**Comment by mhbassel** [comment]
Hi @nv-kmcgill53 thank you for your reply!

Unfortunately it didn't work either, I got the same error.
I also tried to compile using Docker image (as I did with the TF backend) but got other kind of errors.

**Comment by mhbassel** [comment]
@nv-kmcgill53 I am sorry for tagging, but I am pretty stuck and I can't continue without finishing this step. I tried with different versions and paths and nothing worked. I am not sure how to fix it!

would you be kind and try it too to see if the problem is only on my side?

**Comment by mhbassel** [comment]
Ok I tried the Docker image approach and seems it worked, there was an error though but it has been ignored during the `make install` step. Anyway I got another error when running the Triton server, I opened an [issue](https://github.com/triton-inference-server/server/issues/5232) for it.

**Comment by nv-kmcgill53** [comment]
Sorry for missing this, I am glad you were able to find a solution. Is the compiling error you mention here the same as in #5232?

**Comment by mhbassel** [comment]
Hi nv-kmcgill53 no worries. Yep it is the same.

**Comment by mhbassel** [comment]
I will close this issue since the Docker approach worked.
