### ISSUE TITLE
Python client getting significantly less performance than perf_client tool

### ISSUE THREAD

**Issue by adamdickin** [triton-inference-server/server#5168]
Im getting significantly different results using python vs what the perf_client says.  

Triton Version: 22.09
Model: Yolo5 tensorrt model

Output from perf_client
```
./perf_client -m yolov5 -u 127.0.0.1:8000 -i http --concurrency-range 1
*** Measurement Settings ***
  Batch size: 1
  Using "time_windows" mode for stabilization
  Measurement window: 5000 msec
  Using synchronous calls for inference
  Stabilizing using average latency

Request concurrency: 1
  Client:
    Request count: 2219
    Throughput: 123.27 infer/sec
    Avg latency: 8106 usec (standard deviation 1784 usec)
    p50 latency: 7852 usec
    p90 latency: 9277 usec
    p95 latency: 10384 usec
    p99 latency: 13675 usec
    Avg HTTP time: 8095 usec (send/recv 1643 usec + response wait 6452 usec)
  Server:
    Inference count: 16133
    Execution count: 16133
    Successful request count: 16133
    Avg request latency: 6912 usec (overhead 89 usec + queue 120 usec + compute input 2084 usec + compute infer 4049 usec + compute output 568 usec)

Inferences/Second vs. Client Average Batch Latency
Concurrency: 1, throughput: 123.27 infer/sec, latency 8106 usec
```

From reading the above it says I should be able to do 123 infer/sec which is ~8ms per inference.

When i use the triton client in python I get significantly worse results.  Ive put the `triton_client.infer` request into a for loop in order to get the average time of the inference request.

```
        total_n = 0
        totalTimes = 100
        inputs, outputs, model_name, model_version = requestGenerator(image_data, 'data', 'prob', 'FP32', FLAGS)
        for i in range(totalTimes):

            t0 = time.time()

            response = triton_client.infer(FLAGS.model_name,
                                           inputs,
                                           model_version=FLAGS.model_version,
                                           outputs=outputs,
                                           request_compression_algorithm=None,
                                           response_compression_algorithm=None)

            t1 = time.time()
            total_n += t1 - t0

        print("total time: " + str(total_n) + "Average: " + str(total_n/totalTimes))
```

I get the following results `total time: 6.172801971435547Average: 0.061728019714355466`.  So with python it is taking on average ~60 ms per inference vs the perf_client which takes ~8ms.  Anyone have any ideas on whats possibly causing the difference in time?

Additional Notes:
- On the triton server I have checked that the verbose logs are the same between the perf_client and python.  i can also clearly see that there is significantly more inference requests per second when running the perf_client based on the timestamps.

**Comment by nv-kmcgill53** [comment]
CC: @jbkyang-nvi

**Comment by adamdickin** [comment]
Ive debugged this a bit further and have narrowed down the issue to something with Windows.

If I run my same python client code inside a docker container then I get the expected inference timings of ~10ms.  For some reason running this python code on my windows machine takes significantly longer.

Im going to look into my network adapters and windows firewall to see if there is something else slowing it down.

**Comment by nv-kmcgill53** [comment]
@adamdickin What is the current environment you are using to run? Is this running tritonserver and client natively on Windows/container on Windows/WSL for either of them, etc?

**Comment by jbkyang-nvi** [comment]
Another thing to note is that the perf analyzer's stats are when the model throughput/latency has stabilized. Its pretty model dependent when that is but that might also be a factor.

**Comment by adamdickin** [comment]
Machine OS: Windows 10

Triton Inference Server 22.09: Running in a docker container using Windows/WSL.
Perf_Client: Running in another docker container.  

I have ran the python client natively on my windows machine and inside the docker container im using to run the perf_client.  Running the exact same python client inside the docker container is ~5x faster.

Timings inside Docker container for 100 requests.
`total time: 1.456446886062622Average: 0.01456446886062622`

Timings on Native Windows for 100 requests
`total time: 6.247209072113037Average: 0.06247209072113037`

**Comment by krishung5** [comment]
It's highly possible that the performance hit you are seeing in the Python client is expected. Python client is built on Python modules which requires unavoidable extra data copies. On the other hand, perf client is built on our C++ library which includes some optimization for preventing extra data copies from the request tensors.

**Comment by adamdickin** [comment]
Ive tested this on a new machine and it does not suffer from this problem.  I'm not sure whats misconfigured with my current machine so I dont think this question is valid anymore.  

Additionally if I wrap the triton calls with another server that stays constantly connected I can resolve this issue as well.  Its the initial connection that is causing the slowdown, not triton.  

Thank you for all your help.
