### ISSUE TITLE
Supports of group instance count

### ISSUE THREAD

**Issue by huochaitiantang** [triton-inference-server/server#5170]
Now, the tritonserver supports setting `group instance count` in the config file `config.pbtxt`.
Is there any way to specify `group instance count` while starting the tritonserver? 

Thanks!

**Comment by nv-kmcgill53** [comment]
Hi @huochaitiantang, currently there is no way to specify the instance group count on the command line when starting tritonserver. What is your use case for wanting this feature? This will help us understand why this feature is needed.

**Comment by huochaitiantang** [comment]
Thanks for reply!

We have mulitple machines that share the same readonly file system where triton model locates.

We want to start triton model with different paramters (eg, instance group) on different machines.

At least, we wish the `config.pbtxt` could be specified, instead of being hardcoded by https://github.com/triton-inference-server/core/blob/0ce6aa959cf424832d33aac3d66a1c6de9096581/src/constants.h#L73

Furthermore, we suggest that the runtime related config (eg, instance group) should not be placed in the `config.pbtxt`, which could ensure that the model directory is readonly.

**Comment by dyastremsky** [comment]
Triton does support that. You can pass the config in JSON format via the [model load API](https://github.com/triton-inference-server/server/blob/main/docs/protocol/extension_model_repository.md#load). That will also allow you to specify different configurations across different machines.
