### ISSUE TITLE
Question about basic sequence stream example

### ISSUE THREAD

**Issue by LVCSRer** [triton-inference-server/server#5191]
I'm struggling figuring out how to develop sequence stream example.

I have experienced with kaldi example. I could make python client with mic streaming with [notebook code](https://github.com/NVIDIA/DeepLearningExamples/tree/master/Kaldi/SpeechRecognition/notebooks) that is deprecated, with referring to python client for [grpc sequence stream infer example](https://github.com/triton-inference-server/client/blob/main/src/python/examples/simple_grpc_sequence_stream_infer_client.py) 

Now I want to develop other streaming audio application something like speech enhancement or online speaker diarization, however for making model which can serve sequence input, it is very hard to find proper example. 

As a first step, I want to figure out most basic sequence stream example which can serve [grpc sequence stream infer example](https://github.com/triton-inference-server/client/blob/main/src/python/examples/simple_grpc_sequence_stream_infer_client.py). I investigated below two options, but could not find where to start.

1. Deep learning framework backend
As I know, above client example is served by [simple sequence model](https://github.com/triton-inference-server/server/tree/main/docs/examples/model_repository/simple_sequence), then how can I write TF python code for making this graphdef model? What I cannot find is how should manipulate internal state between adjacent chunk.

2. Python backend
I referred to [Stateful Model](https://github.com/triton-inference-server/python_backend#using-bls-with-stateful-models) section of python backend document, but there are no examples applied this. Though I applied TRITONSERVER_REQUEST_FLAG_SEQUENCE_START flag to InferenceRequest, the second request failed with "... must specify the START flag on the first request of the sequence"
It would be very helpful if actual example with above flag applied can be provided.

**Comment by LVCSRer** [comment]
Oh.. I found [this repository](https://github.com/triton-inference-server/server/tree/main/qa/common) contains examples regarding the fist question.

**Comment by LVCSRer** [comment]
OK. Now I found answers for first question. 
https://github.com/triton-inference-server/server/blob/main/qa/common/gen_qa_sequence_models.py

**Comment by krishung5** [comment]
Hi @LVCSRer, I don't think the `gen_qa_sequence_models.py` script is used to generate the simple sequence model in the example given that the [different behavior](https://github.com/triton-inference-server/server/blob/main/qa/common/gen_qa_sequence_models.py#L210-L216) when the model supports batching, however, I think `gen_qa_sequence_models.py` is still a great reference for creating sequence models. The behavior of the [python model](https://github.com/triton-inference-server/server/blob/main/qa/python_models/sequence_int32/model.py#L49) is derived from the script `gen_qa_sequence_models.py` where the output is the accumulated value of the inputs so I think they are the same. For your second question, unfortunately we don't have any end-to-end example for that, but you can refer to this [test case](https://github.com/triton-inference-server/server/blob/main/qa/python_models/bls/model.py#L97) to see how to apply the `TRITONSERVER_REQUEST_FLAG_SEQUENCE_START` flag.

**Comment by LVCSRer** [comment]
I found the reason of "... must specify the START flag on the first request of the sequence" error. 
I didn't set max_sequence_idle_microseconds value while I run the program with debug mode. After I set max_sequence_idle_microseconds large enough, sequence batcher can process second request.
