### ISSUE TITLE
Serve a Model in 3 Easy Steps is erro

### ISSUE THREAD

**Issue by 827346462** [triton-inference-server/server#5197]
i run Steps
# Step 1: Create the example model repository 
git clone -b r22.12 https://github.com/triton-inference-server/server.git
cd server/docs/examples
./fetch_models.sh

# Step 2: Launch triton from the NGC Triton container
docker run --gpus=1 --rm --net=host -v ${PWD}/model_repository:/models nvcr.io/nvidia/tritonserver:22.07-py3 tritonserver --model-repository=/models

# Step 3: Sending an Inference Request 
# In a separate console, launch the image_client example from the NGC Triton SDK container
docker run -it --rm --net=host nvcr.io/nvidia/tritonserver:22.12-py3-sdk
/workspace/install/bin/image_client -m densenet_onnx -c 3 -s INCEPTION /workspace/images/mug.jpg

step1 is sucessul.
steo2 👍
i run:
docker run --rm --net=host -v /data/LX/server/docs/examples/model_repository:/models nvcr.io/nvidia/tritonserver:22.07-py3 tritonserver --model-repository=/models

it is show:
![image](https://user-images.githubusercontent.com/50097546/209529855-11e6f814-c362-4ed8-848c-6f01bb278ef8.png)

i run:
docker run -it --rm --net=host nvcr.io/nvidia/tritonserver:22.12-py3-sdk
/workspace/install/bin/image_client -m densenet_onnx -c 3 -s INCEPTION /workspace/images/mug.jpg

it is erro:
![image](https://user-images.githubusercontent.com/50097546/209530679-cb8ec1f8-d10f-4dff-b56c-52abe18a94b3.png)

and
docker run --gpus=1 --rm --net=host -v /data/LX/server/docs/examples/model_repository:/models nvcr.io/nvidia/tritonserver:22.07-py3 tritonserver --model-repository=/models

it erro:
![image](https://user-images.githubusercontent.com/50097546/209530870-6f04feca-1aab-4913-95a0-f6a382c50fab.png)
 logs:
NVIDIA Release 22.07 (build 41737377)
Triton Server Version 2.24.0

Copyright (c) 2018-2022, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

WARNING: CUDA Minor Version Compatibility mode ENABLED.
  Using driver version 510.47.03 which has support for CUDA 11.6.  This container
  was built with CUDA 11.7 and will be run in Minor Version Compatibility mode.
  CUDA Forward Compatibility is preferred over Minor Version Compatibility for use
  with this container but was unavailable:
  [[Forward compatibility was attempted on non supported HW (CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE) cuInit()=804]]
  See https://docs.nvidia.com/deploy/cuda-compatibility/ for details.

I1226 09:18:37.004516 1 pinned_memory_manager.cc:240] Pinned memory pool is created at '0x7f7cb0000000' with size 268435456
I1226 09:18:37.004754 1 cuda_memory_manager.cc:105] CUDA memory pool is created on device 0 with size 67108864
I1226 09:18:37.006067 1 model_repository_manager.cc:1206] loading: densenet_onnx:1
I1226 09:18:37.006097 1 model_repository_manager.cc:1206] loading: inception_graphdef:1
I1226 09:18:37.007280 1 onnxruntime.cc:2458] TRITONBACKEND_Initialize: onnxruntime
I1226 09:18:37.007299 1 onnxruntime.cc:2468] Triton TRITONBACKEND API version: 1.10
I1226 09:18:37.007307 1 onnxruntime.cc:2474] 'onnxruntime' TRITONBACKEND API version: 1.10
I1226 09:18:37.007311 1 onnxruntime.cc:2504] backend configuration:
{"cmdline":{"auto-complete-config":"true","min-compute-capability":"6.000000","backend-directory":"/opt/tritonserver/backends","default-max-batch-size":"4"}}
I1226 09:18:37.016632 1 onnxruntime.cc:2560] TRITONBACKEND_ModelInitialize: densenet_onnx (version 1)
2022-12-26 09:18:38.547429: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
I1226 09:18:38.579449 1 tensorflow.cc:2531] TRITONBACKEND_Initialize: tensorflow
I1226 09:18:38.579474 1 tensorflow.cc:2541] Triton TRITONBACKEND API version: 1.10
I1226 09:18:38.579477 1 tensorflow.cc:2547] 'tensorflow' TRITONBACKEND API version: 1.10
I1226 09:18:38.579479 1 tensorflow.cc:2571] backend configuration:
{"cmdline":{"auto-complete-config":"true","min-compute-capability":"6.000000","backend-directory":"/opt/tritonserver/backends","default-max-batch-size":"4"}}
I1226 09:18:38.579511 1 onnxruntime.cc:2603] TRITONBACKEND_ModelInstanceInitialize: densenet_onnx (GPU device 0)
I1226 09:18:38.606514 1 onnxruntime.cc:2637] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I1226 09:18:38.606523 1 tensorflow.cc:2637] TRITONBACKEND_ModelInitialize: inception_graphdef (version 1)
I1226 09:18:38.606569 1 onnxruntime.cc:2583] TRITONBACKEND_ModelFinalize: delete model state
E1226 09:18:38.606589 1 model_repository_manager.cc:1355] failed to load 'densenet_onnx' version 1: Internal: unable to create stream: the provided PTX was compiled with an unsupported toolchain.
I1226 09:18:38.607227 1 tensorflow.cc:2686] TRITONBACKEND_ModelInstanceInitialize: inception_graphdef (GPU device 0)
I1226 09:18:38.854281 1 tensorflow.cc:2724] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I1226 09:18:38.854336 1 tensorflow.cc:2663] TRITONBACKEND_ModelFinalize: delete model state
E1226 09:18:38.854355 1 model_repository_manager.cc:1355] failed to load 'inception_graphdef' version 1: Internal: unable to create stream: the provided PTX was compiled with an unsupported toolchain.
I1226 09:18:38.854425 1 server.cc:559] 
+------------------+------+
| Repository Agent | Path |
+------------------+------+
+------------------+------+

I1226 09:18:38.854478 1 server.cc:586] 
+-------------+-----------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Backend     | Path                                                            | Config                                                                                                                                                        |
+-------------+-----------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------+
| onnxruntime | /opt/tritonserver/backends/onnxruntime/libtriton_onnxruntime.so | {"cmdline":{"auto-complete-config":"true","min-compute-capability":"6.000000","backend-directory":"/opt/tritonserver/backends","default-max-batch-size":"4"}} |
| tensorflow  | /opt/tritonserver/backends/tensorflow1/libtriton_tensorflow1.so | {"cmdline":{"auto-complete-config":"true","min-compute-capability":"6.000000","backend-directory":"/opt/tritonserver/backends","default-max-batch-size":"4"}} |
+-------------+-----------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------+

I1226 09:18:38.854515 1 server.cc:629] 
+--------------------+---------+--------------------------------------------------------------------------------------------------------------+
| Model              | Version | Status                                                                                                       |
+--------------------+---------+--------------------------------------------------------------------------------------------------------------+
| densenet_onnx      | 1       | UNAVAILABLE: Internal: unable to create stream: the provided PTX was compiled with an unsupported toolchain. |
| inception_graphdef | 1       | UNAVAILABLE: Internal: unable to create stream: the provided PTX was compiled with an unsupported toolchain. |
+--------------------+---------+--------------------------------------------------------------------------------------------------------------+

I1226 09:18:38.885321 1 metrics.cc:650] Collecting metrics for GPU 0: NVIDIA GeForce RTX 3090
I1226 09:18:38.885580 1 tritonserver.cc:2176]

**Comment by krishung5** [comment]
Hi @827346462, it seems like you are using r22.12 branch but the NGC Triton container is 22.07. That's probably why you are seeing the `UNAVAILABLE: Internal: unable to create stream: the provided PTX was compiled with an unsupported toolchain` error. Can you try again with `nvcr.io/nvidia/tritonserver:22.12-py3`?

**Comment by 827346462** [comment]
> 

yeah, I began "docker run --gpus=1 --rm --net=host -v /data/LX/server/docs/examples/model_repository:/models nvcr.io/nvidia/tritonserver:22.12-py3 tritonserver --model-repository=/models"

it is erro:
=============================
== Triton Inference Server ==
=============================

NVIDIA Release 22.12 (build 50109463)
Triton Server Version 2.29.0

Copyright (c) 2018-2022, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

WARNING: CUDA Minor Version Compatibility mode ENABLED.
  Using driver version 510.47.03 which has support for CUDA 11.6.  This container
  was built with CUDA 11.8 and will be run in Minor Version Compatibility mode.
  CUDA Forward Compatibility is preferred over Minor Version Compatibility for use
  with this container but was unavailable:
  [[Forward compatibility was attempted on non supported HW (CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE) cuInit()=804]]
  See https://docs.nvidia.com/deploy/cuda-compatibility/ for details.

I1228 01:49:00.889141 1 pinned_memory_manager.cc:240] Pinned memory pool is created at '0x7f4d4e000000' with size 268435456
I1228 01:49:00.889378 1 cuda_memory_manager.cc:105] CUDA memory pool is created on device 0 with size 67108864
I1228 01:49:00.890442 1 model_lifecycle.cc:459] loading: densenet_onnx:1
I1228 01:49:00.890465 1 model_lifecycle.cc:459] loading: inception_graphdef:1
I1228 01:49:00.891603 1 onnxruntime.cc:2459] TRITONBACKEND_Initialize: onnxruntime
I1228 01:49:00.891622 1 onnxruntime.cc:2469] Triton TRITONBACKEND API version: 1.10
I1228 01:49:00.891627 1 onnxruntime.cc:2475] 'onnxruntime' TRITONBACKEND API version: 1.10
I1228 01:49:00.891629 1 onnxruntime.cc:2505] backend configuration:
{"cmdline":{"auto-complete-config":"true","min-compute-capability":"6.000000","backend-directory":"/opt/tritonserver/backends","default-max-batch-size":"4"}}
2022-12-28 01:49:01.115449: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I1228 01:49:01.152191 1 tensorflow.cc:2536] TRITONBACKEND_Initialize: tensorflow
I1228 01:49:01.152222 1 tensorflow.cc:2546] Triton TRITONBACKEND API version: 1.10
I1228 01:49:01.152225 1 tensorflow.cc:2552] 'tensorflow' TRITONBACKEND API version: 1.10
I1228 01:49:01.152228 1 tensorflow.cc:2576] backend configuration:
{"cmdline":{"auto-complete-config":"true","min-compute-capability":"6.000000","backend-directory":"/opt/tritonserver/backends","default-max-batch-size":"4"}}
I1228 01:49:01.152258 1 onnxruntime.cc:2563] TRITONBACKEND_ModelInitialize: densenet_onnx (version 1)
I1228 01:49:02.615429 1 tensorflow.cc:2642] TRITONBACKEND_ModelInitialize: inception_graphdef (version 1)
I1228 01:49:02.615752 1 tensorflow.cc:2668] TRITONBACKEND_ModelFinalize: delete model state
I1228 01:49:02.615754 1 onnxruntime.cc:2606] TRITONBACKEND_ModelInstanceInitialize: densenet_onnx (GPU device 0)
E1228 01:49:02.615769 1 model_lifecycle.cc:597] failed to load 'inception_graphdef' version 1: Not found: model configuration is not provided for model 'inception_graphdef'
I1228 01:49:02.636808 1 onnxruntime.cc:2640] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I1228 01:49:02.636848 1 onnxruntime.cc:2586] TRITONBACKEND_ModelFinalize: delete model state
E1228 01:49:02.636864 1 model_lifecycle.cc:597] failed to load 'densenet_onnx' version 1: Internal: unable to create stream: the provided PTX was compiled with an unsupported toolchain.
I1228 01:49:02.636930 1 server.cc:563] 
+------------------+------+
| Repository Agent | Path |
+------------------+------+
+------------------+------+

I1228 01:49:02.636970 1 server.cc:590] 
+-------------+-----------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Backend     | Path                                                            | Config                                                                                                                                                        |
+-------------+-----------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------+
| onnxruntime | /opt/tritonserver/backends/onnxruntime/libtriton_onnxruntime.so | {"cmdline":{"auto-complete-config":"true","min-compute-capability":"6.000000","backend-directory":"/opt/tritonserver/backends","default-max-batch-size":"4"}} |
| tensorflow  | /opt/tritonserver/backends/tensorflow2/libtriton_tensorflow2.so | {"cmdline":{"auto-complete-config":"true","min-compute-capability":"6.000000","backend-directory":"/opt/tritonserver/backends","default-max-batch-size":"4"}} |
+-------------+-----------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------+

I1228 01:49:02.636996 1 server.cc:633] 
+--------------------+---------+--------------------------------------------------------------------------------------------------------------+
| Model              | Version | Status                                                                                                       |
+--------------------+---------+--------------------------------------------------------------------------------------------------------------+
| densenet_onnx      | 1       | UNAVAILABLE: Internal: unable to create stream: the provided PTX was compiled with an unsupported toolchain. |
| inception_graphdef | 1       | UNAVAILABLE: Not found: model configuration is not provided for model 'inception_graphdef'                   |
+--------------------+---------+--------------------------------------------------------------------------------------------------------------+

I1228 01:49:02.665641 1 metrics.cc:864] Collecting metrics for GPU 0: NVIDIA GeForce RTX 3090
I1228 01:49:02.665956 1 metrics.cc:757] Collecting CPU metrics
I1228 01:49:02.666104 1 tritonserver.cc:2264] 
+----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Option                           | Value                                                                                                                                                                                                |
+----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| server_id                        | triton                                                                                                                                                                                               |
| server_version                   | 2.29.0                                                                                                                                                                                               |
| server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_policy model_configuration system_shared_memory cuda_shared_memory binary_tensor_data statistics trace logging |
| model_repository_path[0]         | /models                                                                                                                                                                                              |
| model_control_mode               | MODE_NONE                                                                                                                                                                                            |
| strict_model_config              | 0                                                                                                                                                                                                    |
| rate_limit                       | OFF                                                                                                                                                                                                  |
| pinned_memory_pool_byte_size     | 268435456                                                                                                                                                                                            |
| cuda_memory_pool_byte_size{0}    | 67108864                                                                                                                                                                                             |
| response_cache_byte_size         | 0                                                                                                                                                                                                    |
| min_supported_compute_capability | 6.0                                                                                                                                                                                                  |
| strict_readiness                 | 1                                                                                                                                                                                                    |
| exit_timeout                     | 30                                                                                                                                                                                                   |
+----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

I1228 01:49:02.666110 1 server.cc:264] Waiting for in-flight requests to complete.
I1228 01:49:02.666116 1 server.cc:280] Timeout 30: Found 0 model versions that have in-flight inferences
I1228 01:49:02.666121 1 server.cc:295] All models are stopped, unloading models
I1228 01:49:02.666124 1 server.cc:302] Timeout 30: Found 0 live models and 0 in-flight non-inference requests
error: creating server: Internal - failed to load all models

**Comment by krishung5** [comment]
I was wondering if the model repository is modified? Could you confirm that the model repository being used is the one that contains the changes from running `./fetch_models.sh`? It seems like in your step 2 when running `docker run --gpus=1 --rm --net=host -v ${PWD}/model_repository:/models nvcr.io/nvidia/tritonserver:22.07-py3 tritonserver --model-repository=/models` the models were loaded successfully. Is `/data/LX/server/docs/examples/model_repository` same path as `{PWD}/model_repository`?

**Comment by 827346462** [comment]
> I was wondering if the model repository is modified? Could you confirm that the model repository being used is the one that contains the changes from running ? It seems like in your step 2 when running the models were loaded successfully. Is same path as ?`./fetch_models.sh``docker run --gpus=1 --rm --net=host -v ${PWD}/model_repository:/models nvcr.io/nvidia/tritonserver:22.07-py3 tritonserver --model-repository=/models``/data/LX/server/docs/examples/model_repository``{PWD}/model_repository`

**Comment by 827346462** [comment]
> > I was wondering if the model repository is modified? Could you confirm that the model repository being used is the one that contains the changes from running ? It seems like in your step 2 when running the models were loaded successfully. Is same path as ?`` ./fetch_models.sh``docker run --gpus=1 --rm --net=host -v ${PWD}/model_repository:/models nvcr.io/nvidia/tritonserver:22.07-py3 tritonserver --model-repository=/models``/data/LX/server/docs/examples/model_repository``{PWD}/model_repository ``

this path is same
i ran fetch_models.sh , tree as:
![image](https://user-images.githubusercontent.com/50097546/209895232-6800bb81-1814-4c16-9427-17992aa4b784.png)
