### ISSUE TITLE
GRPC client and decoupled mode - detecting last response of an infer request

### ISSUE THREAD

**Issue by amircodota** [triton-inference-server/server#5198]
Hi,

I'm using the grpc client to send streaming infer requests to a decoupled fastertransformer backend.

For each infer request, I'm getting a stream of responses, which is great.
However, I could not find a way to detect when a request is "done", meaning the server will not be sending any more responses for it.

I think the server does mark it, by setting the TRITONSERVER_ResponseCompleteFlag flag. But I could not find a way where the client knows about it, in the api.

Anything I missed?

**Comment by krishung5** [comment]
Unfortunately it's not possible to determine the last response on the client side for now. Please see the duplicate issue: https://github.com/triton-inference-server/server/issues/5160
