### ISSUE TITLE
[Question] Is it possible to load a separate TRT model from the initialize function of a BLS model ? 

### ISSUE THREAD

**Issue by MatthieuTPHR** [triton-inference-server/server#5201]
Hello, 

I was wondering if it was possible to load a separate TRT model from the initialise function of a python backend BLS model ? 

My motivation is that my BLS model relies on 7 other models that I would want to be loaded automatically when I load the BLS model. 

From the answer to this [question](https://github.com/triton-inference-server/server/issues/5165) I posted a couple weeks back I think this could be done by adding a parameter to the config of the BLS model and checking for it when loading it. However that makes it impractical to roll-out new versions of the BLS model that might call new TRT models. 

I have looked inside the `triton_python_backend_utils.py` but could not find any loading function, hence my question above. 

Thank you for your help !

**Comment by krishung5** [comment]
Hi @MatthieuTPHR, thanks for your question. Unfortunately there isn't any function to let you load models from the initialize function of python model.

**Comment by MatthieuTPHR** [comment]
Thank you for your quick answer !
