### ISSUE TITLE
[question] How to make sure that dynamic batching works making concurrent requests?

### ISSUE THREAD

**Issue by katerinafrid** [triton-inference-server/server#5205]
**Description**
I want to make concurrent requests to the model served on triton. I enabled dynamic batching, but I can't understand if it actually works. 
So I have a couple of questions:
1) Dynamic batching is able to create a batch from entries of any shape, doesn't it? Or it requires entries to have the same shape even if the model accepts a list of entries with different shapes? 
2) How can I be sure from logs that batches of requests were created? For example, I have the following list of logs and I don't get if it indicates dynamic batching.
<img width="1358" alt="Screenshot 2022-12-28 at 21 53 06" src="https://user-images.githubusercontent.com/16782648/209865347-8703a373-a224-4782-ae7e-94bc174da1cc.png">
3) How can I send concurrent requests in an application? For example, I have a FastApi application and use a client to make requests to triton:

`
triton_client = http_client.InferenceServerClient(url=url, verbose=False, concurrency=1000)`

`

How can I handle concurrent requests without using the following template? :

```
async_requests = []
results = []
for i in range(len(data)):
    # Asynchronous inference call.
    async_requests.append(
        triton_client.async_infer(
            model_name='model',
            model_version='1',
            inputs=[input_0[I], input_1[I]],
            outputs=[output[I]]))
for async_request in async_requests:
    results.append(async_request.get_result())
```

I can't collect all requests from the users at the beginning and then process them. 
4) Is it possible to test the concurrent requests using ThreadPoolExecutor? The following code gives me an error src/gevent/_gevent_c_greenlet_primitives.pxd in gevent._gevent_c_greenlet_primitives._greenlet_switch()

error: cannot switch to a different thread (which happens to have exited)

`
```
def make_triton_direct_async_request(data):
    req =  triton_client.async_infer(
            model_name='nlu_model',
            model_version='1',
            inputs=[data[0], data[1]],
            outputs=[data[2]])
    return req

def get_triton_direct_async_result(req):
    return np.asarray(req.get_result().as_numpy('OUTPUT__0'), dtype=np.float32)

results = []
MODEL_URL = 'http://127.0.0.1:8000/v2/models/nlu_model/versions/1/infer'
with ThreadPoolExecutor(max_workers=2) as pool:
    async_requests = list(tqdm(pool.map(make_triton_direct_async_request, triton_input_data)))
    results = list(tqdm(pool.map(get_triton_direct_async_result, async_requests)))
```

`
``
**Triton Information**
What version of Triton are you using?
Ubuntu 20.04
triton server 2.21.0
ngc container 22.04
nvidia driver 510
cuda 11.6

**To Reproduce**
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
Model config:
```
backend: "python"
max_batch_size: 32

input [
  {
    name: "INPUT__0"
    data_type: TYPE_INT64
    dims: [ -1]
  },
{
    name: "INPUT__1"
    data_type: TYPE_INT64
    dims: [ -1]
  }
]
output [
  {
    name: "OUTPUT__0"
    data_type: TYPE_FP32
    dims: [3, -1]
  }
]

instance_group [
    {
      count: 1
      kind: KIND_GPU
    }
]

dynamic_batching {
    preferred_batch_size: [2, 4, 8, 16, 32]
    max_queue_delay_microseconds: 200
}
```

**Expected behavior**
Support concurrent requests from a connected API and dynamic batching.

**Comment by katerinafrid** [comment]
any suggestions?

**Comment by kthui** [comment]
Hi @katerinafrid, thanks for your questions:
1. Dynamic batching is able to create a batch from entries of any shape, doesn't it? Or it requires entries to have the same shape even if the model accepts a list of entries with different shapes?
    - It depends. At the minimum, the model must support batching so that a batch of entries can be inferenced. There is an example which the model accepts a dynamic shape (a string) with > 0 max batch size [here](https://github.com/triton-inference-server/server/blob/main/docs/examples/model_repository/simple_identity/config.pbtxt).
    - CC @GuanLuo @tanmayv25 for more clarification on the behavior when dynamic batching inputs of different shapes.
2. How can I be sure from logs that batches of requests were created? For example, I have the following list of logs and I don't get if it indicates dynamic batching.
    - Can you try starting the server with flag `--log-verbose=2`, which should print more information?
    - If you want to be sure, you can also check in the Python model to see if `len(requests) > 1` during execute, see an example python backend [here](https://github.com/triton-inference-server/python_backend/blob/main/examples/add_sub/model.py#L75). If `>1`, it indicates batching.
3. How can I send concurrent requests in an application? I can't collect all requests from the users at the beginning and then process them.
    - You can pass in whatever request(s) that are currently available, and let the dynamic batching to group the request(s) into batch(s). You can read more about dynamic batching [here](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/model_configuration.md#scheduling-and-batching), and you might also want to config [delayed batching](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/model_configuration.md#delayed-batching) so you can get a more optimized batch size.
    - You might also want to check out the [Model Analyzer](https://github.com/triton-inference-server/model_analyzer#triton-model-analyzer) which can help you better understand the compute and memory requirement of models on a given hardware setup.
4. Is it possible to test the concurrent requests using ThreadPoolExecutor?
    - Unfortunately, the gevent http library used by the Python http client is not thread safe. To send concurrent request, you will have to initialize a http client for each thread, and never share a http client across threads. If this is not feasible, you can also try the grpc client, or the async io version of the http/grpc client.

**Comment by rohitgr7** [comment]
hey @kthui !

> You can pass in whatever request(s) that are currently available, and let the dynamic batching to group the request(s) into batch(s).

I am actually stuck on this part.

My config:
```
name: "onnx_dynamic_batching"
platform: "onnxruntime_onnx"
max_batch_size: 32
dynamic_batching { 
  preferred_batch_size: [ 4, 8, 16, 32 ] 
  max_queue_delay_microseconds: 3000000
}

input [
  {
    name: "INPUT0"
    data_type: TYPE_INT32
    dims: [ 256 ]
  }
]
input [
  {
    name: "INPUT1"
    data_type: TYPE_INT32
    dims: [ 256 ]
  }
]
output [
  {
    name: "OUTPUT0"
    data_type: TYPE_FP32
    dims: [ 28 ]
  }
]
```

My inference client requesting the server:
```py
with tritonhttpclient.InferenceServerClient(url=url, verbose=False) as client:
    # Encode the data using tokenizer
    inputs = tokenizer(text, return_tensors="pt", max_length=256, padding='max_length')
    input_ids = np.array(inputs['input_ids'], dtype=np.int32)
    attention_mask = np.array(inputs['attention_mask'], dtype=np.int32)
    
    # Define input config
    inputs = [
        tritonhttpclient.InferInput(input_name[0], input_ids.shape, input_dtype[0]),
        tritonhttpclient.InferInput(input_name[1], attention_mask.shape, input_dtype[1]),
    ]
    
    # Attach input
    inputs[0].set_data_from_numpy(input_ids)
    inputs[1].set_data_from_numpy(attention_mask)
    
    # Define output config
    outputs = [
        tritonhttpclient.InferRequestedOutput(output_name[0]),
    ]
    
    # Hit triton server
    n_requests = 4
    responses = []
    for i in range(n_requests):
        responses.append(client.async_infer(model_name, model_version=model_version, inputs=inputs, outputs=outputs))
    tock = time.time()
```

each individual request with batch_size=1 takes around 0.15 sec, and here I am sending 4 requests async. Now I'd expect them to batch internally and process all of them under 3 sec, but in total it's taking around 12 sec i.e. 3 sec for each request. I am not sure what am I doing wrong here. Can you help?

**Comment by tanmayv25** [comment]
@rohitgr7 Can you launch Triton with `--log-verbose=1` and share the entire log from the server side? It will help us identifying what's happening.

**Comment by tanmayv25** [comment]
@rohitgr7 What do you mean by context manager didn't work with gRPC?

**Comment by rohitgr7** [comment]
@tanmayv25 

this didn't work for me:
```py
with tritongrpcclient.InferenceServerClient(url=url, verbose=False):
    ...
```

**Comment by tanmayv25** [comment]
I think you meant:

```
with tritongrpcclient.InferenceServerClient(url=url, verbose=False) as client:
    ...
```
This is strange. I think gRPC is pushing towards asyncio support. You can also look at our [asyncio based client libraries](https://github.com/triton-inference-server/client#python-asyncio-support-beta-1).
Example [here](https://github.com/triton-inference-server/client/blob/main/src/python/examples/simple_grpc_aio_infer_client.py).

**Comment by Tabrizian** [comment]
Closing due to in-activity.

**Comment by jturner116** [comment]
@tanmayv25 there is some weird behavior with grpc clients as context managers.

```Python
import tritonclient.grpc.aio as grpcclient
```
Does not work as a context manager, but the normal import does. Is that intended? Makes sense to me now but was not super intuitive before.

Thanks!

**Comment by cceyda** [comment]
For people searching like me the short answer is:
1-  when launching the server  use `--log-verbose 2 --log-file triton_logs.log`
2- grep the logs with `tail -f triton_logs.log|grep --line-buffered executing` to check if requests are being grouped.
You should see something like:
`I0517 11:41:01.923802 98 tensorrt.cc:334] model bert-base, instance bert-base_0_1, executing 4 requests`
