### ISSUE TITLE
Input_memories in libtorch backend

### ISSUE THREAD

**Issue by yuekaizhang** [triton-inference-server/server#5208]
https://github.com/triton-inference-server/pytorch_backend/blob/main/src/libtorch.cc#L1722 
The variable input_memories here seem to be useless. I was wondering the usuage of it if I am wrong. Thank you.

**Comment by krishung5** [comment]
Hi @yuekaizhang, thanks for the catch! You are right that the `input_memories` variable is unused. It was used previously but got slipped from a later cleanup.
