### ISSUE TITLE
AttributeError: 'InferenceServerClient' object has no attribute '_pool'

### ISSUE THREAD

**Issue by ltm920716** [triton-inference-server/server#5216]
hello,
here is a error info:
AttributeError: 'InferenceServerClient' object has no attribute '_pool'

below is the source code
# pip install tritonclient[all]

import tritonclient.http as httpclient
import numpy as np

# Setting up client
client = httpclient.InferenceServerClient(url="http://...")

image = np.random.randn(1, 3, 244, 244)
inputs = httpclient.InferInput("INPUT__0", [1, 3, 244, 244], datatype="FP32")
inputs.set_data_from_numpy(image, binary_data=True)

outputs = httpclient.InferRequestedOutput("OUTPUT__0", binary_data=True)

results = client.infer(model_name="sr_test", inputs=[inputs], outputs=[outputs])
inference_output = results.as_numpy('OUTPUT__0')
print(inference_output.shape)

**Comment by rmccorm4** [comment]
Hi @ltm920716 ,

I expect you probably should've received another error first:
> tritonclient.utils.InferenceServerException: url should not include the scheme

From this line you shared: 
```
client = httpclient.InferenceServerClient(url="http://...")
```
The url should not include the `http://` or `https://` at the beginning as seen [here](https://github.com/triton-inference-server/client/blob/bedbb132c2c08a8e22e817018ab364c0d70a5c53/src/python/library/tritonclient/http/__init__.py#L204-L205).

If you remove the `http://` part from the url, you shouldn't see this error.

CC @jbkyang-nvi if we want to add some simple logic/check that `self._pool` and `self._client_stub` have been initialized before calling their respective [cleanup functions](https://github.com/triton-inference-server/client/blob/bedbb132c2c08a8e22e817018ab364c0d70a5c53/src/python/library/tritonclient/http/__init__.py#L234-L235) so the error messages are more clear.
