### ISSUE TITLE
/v2/repository/index api is very slowly

### ISSUE THREAD

**Issue by zjq1996518** [triton-inference-server/server#5221]
**Description**
We've deployed more than 30 models on triton. When I call the API /v2/repository/index it's very slow to respond, about 20 seconds or more. But sometimes it is very fast and only takes about 500ms, this behavior is random, sometimes fast and sometimes slow.

**Triton Information**
triton version: 22.07、22.08、22.12

**Comment by kthui** [comment]
Thanks for reporting the issue. I have filed a ticket for us to investigate further.

**Comment by zjq1996518** [comment]
Thank you for your reply

> Thanks for reporting the issue. I have filed a ticket for us to investigate further.

Thank you for your reply.

**Comment by kthui** [comment]
Hi @zjq1996518, I did a test by deploying 900+ models, and calling the `/v2/repository/index` API takes less than 5ms on average over 1000 API calls. I am wondering if you are calling the API locally (i.e. localhost) or over the internet?

**Comment by kthui** [comment]
Due to lack of activity, I am closing this issue assuming you already have a fix and no longer require any help, but please feel free to re-open it if that is not the case.

**Comment by zjq1996518** [comment]
> Due to lack of activity, I am closing this issue assuming you already have a fix and no longer require any help, but please feel free to re-open it if that is not the case.

sorry, My github didn't remind me and I guess it's my server network problem, but I tried curl -X POST -w ' %{time_connect}:%{time_starttransfer}:%{time_total} ' -o /dev/null -s http://192.168.3.245:8100/v2/repository/index commands, and the average response time was 4s, but the average response time of curl -X POST -w ' %{time_connect}:%{time_starttransfer}:%{time_total} ' -o /dev/null -s http://192.168.3.245:8100/v2/models/line_ox commands was only 700us, the line_ox is my model name.
It doesn't look like a network problem.
