### ISSUE TITLE
[Question] Tips on sending gRPC requests from .NET

### ISSUE THREAD

**Issue by jturner116** [triton-inference-server/server#5225]
Do you have any suggestions on the best way to serve gRPC requests from .NET? I am trying to replicate requests sent from the python grpcclient, but I'm having trouble printing them/figuring out how they are generated. I've considered using IronPython to just send requests using the tritonclient, but it would be nice to send them from native .NET. 

Thanks for your responsiveness to issues and for the great documentation! 
Jonah

**Comment by kthui** [comment]
@tanmayv25 @jbkyang-nvi Can you provide some suggestions on sending gRPC requests from .NET?

**Comment by jturner116** [comment]
@tanmayv25 Hi! I have been reading more and think I have a better idea now. I should be able to create a custom python backend to preprocess a byte string sent in a gRPC request from .NET? Would it be possible to send a batch of byte strings to a python backend? Thanks for your help!

**Comment by tanmayv25** [comment]
@jturner116  Unfortunately, I don't possess sufficient knowledge about .NET to comment with certainty. But you should be able to send a batch of byte string from your .NET client to the triton service hosting a python backend model for pre-process.

For the client developement, please look at :
https://learn.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-7.0&tabs=visual-studio#create-the-grpc-client-in-a-net-console-app

We have our service proto described here:
https://github.com/triton-inference-server/common/blob/main/protobuf/grpc_service.proto

You can definitely look at our python client library implementation for example:
https://github.com/triton-inference-server/client/blob/main/src/python/library/tritonclient/grpc/__init__.py

**Comment by jturner116** [comment]
@tanmayv25 Thank you for the advice, sir! When using the [Binary Tensor Data Extension](https://github.com/triton-inference-server/server/blob/main/docs/protocol/extension_binary_data.md), there are no changes required in the model config or in a custom backend to support this type? The binary data is transformed into Triton types before being passed to a model?
Thank you for your help !!

**Comment by tanmayv25** [comment]
@jturner116  Binary Tensor Data Extension is only supported on HTTP protocol.  And yes, using the extension doesn't require any changes in model config or in custom backend.  The data format is handled in HTTP frontend of Triton. The backend will see the bytes as provided by the user within the binary blob.

**Comment by jturner116** [comment]
Thank you sir, I really appreciate your help :) Marking as closed
