### ISSUE TITLE
Triton server restarts after polling a new model from GCS

### ISSUE THREAD

**Issue by RobMin** [triton-inference-server/server#5231]
**Description**
Triton restarts with 137 error code after a new model is polled from gcs, after restart all the models are served without issues.
CPU memory usage stays at about 4gb +- 0.5gb (Checked with both metrics provided by triton and kubernetes, ~26gb available)
GPU memory usage stays at about 3gb +- 1gb (Checked with both metrics provided by triton and kubernetes, ~15gb available)
Logs with `--log-verbose=1` [logs.txt](https://github.com/triton-inference-server/server/files/10381590/logs.txt)

**Triton Information**
Triton image version: `nvcr.io/nvidia/tritonserver:22.12-py3`
nvidia-smi output:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.141.03   Driver Version: 470.141.03   CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   66C    P0    30W /  70W |   3071MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```
Triton run command:
```
tritonserver \
          --model-repository=gs://<models-gs-url-path> \
          --allow-metrics=true \
          --allow-gpu-metrics=true \
          --allow-cpu-metrics=true \
          --model-control-mode=poll \
          --repository-poll-secs=60 \
          --log-verbose=1
```

**To Reproduce**
I am able to reproduce it by deploying triton in kube with few bert/distil-bert models with `platform: "onnxruntime_onnx"`.
The sample config file of the models that ate causing the issue:
```
name: "<my-model-name>"
platform: "onnxruntime_onnx"
max_batch_size: 0
input [
  {
    name: "input_ids"
    data_type: TYPE_INT64
    dims: [ -1, -1 ]
  },
  {
    name: "attention_mask"
    data_type: TYPE_INT64
    dims: [ -1, -1 ]
  }
]
output [
  {
    name: "logits"
    data_type: TYPE_FP32
    dims: [ -1, 2 ]
  }
]
```

**Expected behavior**
I expect the deployed models list to update without forcing the triton server to restart.

**Comment by RobMin** [comment]
We found out that it is restarting with T4 GPUs and not restarting with A100 GPUs.

**Comment by kthui** [comment]
Hi @RobMin, could you try adding `--strict-readiness=false` flags when starting the server? This will allow the server to report ready when it is actively loading/unloading models.

**Comment by kthui** [comment]
Alternatively, you could also health check on `/v2/health/live` Triton API from Kubernetes if not setting `--strict-readiness=false`. Please let us know if the config change can resolve your issue or not, so we can follow-up.

**Comment by RobMin** [comment]
Thank you @kthui ! Adding `--strict-readiness=false` fixed the issue!

**Comment by kthui** [comment]
Thanks for confirming!
