### ISSUE TITLE
[Bug] Triton Server crashes and becomes unavailable for a few seconds before restarting

### ISSUE THREAD

**Issue by MatthieuTPHR** [triton-inference-server/server#5234]
**Description**
_A clear and concise description of what the bug is._
I am running Triton Inference Server with multiple models (Torchscript, Torch-TensorRT, BLS) with Flask and 15 workers in front as client. 
Sometimes, randomly,  the Triton Inference Server becomes unavailable for a short period of time (a few seconds) and returns `StatusCode.UNAVAILABLE` making all requests fail during that time. 

```
File /usr/local/lib/python3.8/dist-packages/tritonclient/grpc/__init__.py, line 62, in raise_error_grpc   \
 raise get_error_grpc(rpc_error) from Nonetritonclient.utils.InferenceServerException: \
 [StatusCode.UNAVAILABLE] Socket closed
```

Followed by: 

```
File /usr/local/lib/python3.8/dist-packages/tritonclient/grpc/__init__.py, line 62, in raise_error_grpc   \
 raise get_error_grpc(rpc_error) from Nonetritonclient.utils.InferenceServerException: \
 [StatusCode.UNAVAILABLE] failed to connect to all addresses; \
 last error: UNKNOWN: ipv4:PRIVATE_IP:8001: Failed to connect to remote host: Connection refused
```

It seems like the server crashes for some reasons and then restarts.
Logs on datadog show that there are still some RAM available. 
The models don't use the full GPU memory, only 13Gb out of 24Gb (A10g). 

**Triton Information**
_What version of Triton are you using?_ 22.09

_Are you using the Triton container or did you build it yourself?_ I am using the triton container with pytorch1.12 installed on top of it. 

**To Reproduce**
_Steps to reproduce the behavior._ I am unable to reproduce this issue. 

_Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well)._
I am unfortunately unable to disclose this information publicly. 

**Expected behavior**
_A clear and concise description of what you expected to happen._

I am wondering if this is due to the queue being too long ? 

Have you ever faced this issue or something similar ?

**Comment by tanmayv25** [comment]
Can you run the server in verbose mode(--log-verbose=1)? And share the logs when the server crashes?

**Comment by muskaangupt** [comment]
Hi @MatthieuTPHR I am currently facing the same issue, can you please provide the solution for the same?
#highpriority

**Comment by MatthieuTPHR** [comment]
Our issue was that we had a tensor with a dim of 0 (usually after a cropping operation). You can use this function to test: 

```
def is_contiguous_c_order(tensor):
    strides = tensor.stride()
    ndim = len(tensor.shape)
    dims = tensor.shape

    calculated_stride = 1
    is_contiguous_c_order = True

    for i in range(1, ndim + 1):
        if dims[-i] == 1:
            continue  # Ignore dimensions of size 1

        if strides[-i] != calculated_stride:
            is_contiguous_c_order = False
            break

        calculated_stride *= dims[-i]

    return is_contiguous_c_order
```
