### ISSUE TITLE
Triton per model resource distribution monitoring

### ISSUE THREAD

**Issue by ZhilnikovaMargarita** [triton-inference-server/server#5239]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ZhilnikovaMargarita** [comment]
Hello!
We are using Triton Inference Server on Nvidia A100, and we want to know the best way to monitor the distribution of consumed memory and resource utilization by TRITON MODELS , if it's possible.
We tried to use Model Analyzer Metrics, but its report doesn't show consumed memory PER MODEL.
Please, help us, friend!

**Comment by dyastremsky** [comment]
Triton Model Analyzer should show the GPU memory used per model. It should be in the report in the table ([example](https://github.com/triton-inference-server/model_analyzer/blob/main/examples/offline_summary.pdf)). You can also get this information yourself by running Triton server, checking GPU memory usage (e.g. nvidia-smi), then loading the model and seeing what the GPU memory usage is to calculate the difference.

If you are looking for something else, let me know.

**Comment by ZhilnikovaMargarita** [comment]
Thank you @dyastremsky, but this method works only locally, if I understand correctly.
So, does there exist a way to monitor the GPU Utilization per model for plotting graphs online, in Grafana, for example?

I currently have several models deployed with Triton Server (ensembles based on both  python and trt backend) and I'm looking for a way to monitor the online GPU Utilization per model.

**Comment by dyastremsky** [comment]
GPU metrics are provided through the metrics endpoint, but they are per GPU: https://github.com/triton-inference-server/server/blob/main/docs/user_guide/metrics.md#gpu-metrics

If you want to know how much GPU memory a model takes with a given configuration, running it with Model Analyzer or nvidia-smi is the best route. That should let you know how much memory that model needs when loaded/running. GPU utilization can't be differentiated by model, given that utilization isn't additive.
