### ISSUE TITLE
Using PyTorch 2.0 for the PyTorch Backend

### ISSUE THREAD

**Issue by CoderHam** [triton-inference-server/server#5240]
Hi wonderful devs of Triton! 

**Is your feature request related to a problem? Please describe.**
Is there a plan to move to using PyTorch 2.0 for the PyTorch Backend?

According to https://pytorch.org/get-started/pytorch-2.0, it brings a host of benefits which may translate to better inference performance.

**Comment by dyastremsky** [comment]
Hi Hemant! 😄 Great suggestion. I've filed an enhancement request to look into using PyTorch 2.0.

**Comment by mikelam92** [comment]
Hi @dyastremsky is there a timeline on this?

**Comment by dyastremsky** [comment]
23.02 had a pre-release. We haven't released a timeline for the official release. You can try running any PyTorch 2.0 models through the backend. If they don't yet work, feel free to share with us.

You can also try running the PyTorch 2.0 models with the Python backend, assuming torch>=2.0 is installed.

**Comment by dyastremsky** [comment]
Triton doesn't compile models. Your models should already be trained and saved before loading to run inference on Triton.

If you create the model to work with PyTorch 2.0, you can try running it in the PyTorch or Python backends.

**Comment by lminer** [comment]
How would we go about serializing a model that has been compiled by torch dynamo? You can't use torchscript.

**Comment by dyastremsky** [comment]
Quick clarification: seeing that the NGC PyTorch container does not yet support PyTorch 2.0, and we'll support it once that does. However, since `torch.compile` is not supported via torchscript, you'd still need to use the Python backend then.

You can run these models via the Python backend. As long as you install PyTorch 2.0 in the Python backend.

CC: @Tabrizian

**Comment by lminer** [comment]
Are you sure torch 2.0 isn't supported yet? According to the support matrix (https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html) it's supported in 23.03, which appears to be an official release, but maybe I'm missing something.

**Comment by dyastremsky** [comment]
23.03 has a pre-release of PyTorch 2.0. It's likely going to be a couple of releases before PyTorch 2.0 is shipped with the latest CUDA. You're welcome to try your models to see if they work well with the pre-release.

For your case, if you're not using torchscript, so you'll need to use the Python backend either way.

**Comment by dverheijden** [comment]
> seeing that the NGC PyTorch container does not yet support PyTorch 2.0, and we'll support it once that does (...)

Will PyTorch 2.0 be supported as a backend or as a custom python backend trick? AFAIK, [we cannot save the new `torch.compile` models](https://pytorch.org/get-started/pytorch-2.0/#serialization). As such, a PyTorch backend would have to compile the model at runtime with the compilation configuration, which would require a proto extension right?

**Comment by dyastremsky** [comment]
That's correct. As mentioned above, `torch.compile` will be supported via the Python backend. The same is true for other PyTorch 2.0 features that are Python-only and not supported via the torchscript C++ route yet. Everything else will continue to be supported in the PyTorch backend. More support may be added to the PyTorch backend in the future, depending on what PyTorch makes available in the future.

There are no official performance benchmarks on PyTorch 1.0 vs 2.0 models running on Triton.

**Comment by vadimkantorov** [comment]
Second that either proper PyTorch 2.0 / torch.compile backend support and examples of setting it up with existing Python backend (until then) is a scenario that needs to be addressed / elaborated on in the docs: https://github.com/triton-inference-server/backend#where-can-i-find-all-the-backends-that-are-available-for-triton

**Comment by Tabrizian** [comment]
@kthui made some enhancements to the existing PyTorch backend to support PyTorch 2.0. This should be included in the 24.01 release. Please give it a try and let us know if you have any feedback:

https://github.com/triton-inference-server/pytorch_backend#pytorch-20-backend-experimental

**Comment by 631068264** [comment]
@Tabrizian Hi  , I want to use PyTorch 2.0 for PyTorch backend. But I don't know how to do that .  Can you add some example  and Performance comparison between the same model using TorchScript and torch.compile.

**Comment by ToanLyHoa** [comment]
@631068264 hi, did you find any Pytorch 2.0 - Pytorch backend examples for triton inference server, I cannot find it.

**Comment by 631068264** [comment]
Already given up  @ToanLyHoa

**Comment by ToanLyHoa** [comment]
So you use torch script backend instead @631068264?

**Comment by ToanLyHoa** [comment]
@631068264  
I saw this https://github.com/triton-inference-server/server/issues/8300, you may have a look at this. Triton is going to release a new backend for PyTorch 2.x, so it’s understandable that they don’t provide examples for an unstable feature.

**Comment by 631068264** [comment]
@ToanLyHoa I don't know .  But  this repo official maintainers  are too lazy to reply the issue.
