### ISSUE TITLE
Traces. OpenTelemetry

### ISSUE THREAD

**Issue by luismarquezgft** [triton-inference-server/server#5242]
**Is your feature request related to a problem? Please describe.**
Trace information is stored in files. Developers need to create an additional application to process those traces and send them to a storage and analysis platform. This makes product adoption complex because traces are a must. Sooner or later you will need them in Production environments.

The proposal is to add support for OpenTelemetry, which would be responsible for gathering metrics, logs and traces and sending them to a processing backend like Jaeger, Dynatrace or similar. Most trace platforms are adding support for OpenTelemetry, and **it would make Triton stand out in terms of Observability**. To sum up, work once and be compatible with many observability management platforms.

**Describe the solution you'd like**
Be able to connect Triton instances to OpenTelemetry agents or proxies, 

**Describe alternatives you've considered**
Manual coding. Read the trace files, process them, send them to the platform, delete those files that are processed... many hours of coding, a new set of processes to be maintained, code that has to be updated every time log format is updated or enriched.

**Additional context**

**Comment by Tabrizian** [comment]
Thanks for your feature request @luismarquezgft. @oandreeva-nv added Otel support for in the 23.04 release. Please let us know if you have any feedback/comments. https://github.com/triton-inference-server/server/blob/fd5ac9eba8b50880ba69051552283cc617523e9f/docs/user_guide/trace.md#opentelemetry-trace-support
