### ISSUE TITLE
Issue with system shared memory and OpenCL (failed reading shared memory buffer with clEnqueueWriteBuffer )

### ISSUE THREAD

**Issue by YoelBerger** [triton-inference-server/server#5248]
**Description**
I am writing a new backend for a new device that uses OpenCL (2.0) interface.
When working without system-shared memory there is no issue, but when using with system shared-memory I received an error of "bad address - Errno 14" from calling clEnqueueWriteBuffer (Upload to device memory).
After some investigation I found the root cause:
The shared memory manager maps the shared memory with "mmap" with only PROT_WRITE and without PROT_READ:
https://github.com/triton-inference-server/server/blob/main/src/shared_memory_manager.cc#L153

When it mapped with PROT_WRITE  and without PROT_READ there is no problem reading it in C++ code, but clEnqueueWriteBuffer failed to work.
When I added the PROT_READ flag too it works.

Is it possible to add the PROT_READ too?

**Triton Information**
Using custom build of triton based on r22.12 and Ubuntu 18.04.
(The accelerator vendor of the device I working on only supports ubuntu 18.04 right now).

**Comment by Tabrizian** [comment]
I've added `PROT_READ` to the `shared_memoory_manager`. Let us know if you are still seeing this issue.
