### ISSUE TITLE
Setup Triton server with build.py Error at setting up libonnxruntime.so

### ISSUE THREAD

**Issue by jvemuls1** [triton-inference-server/server#5253]
I am trying to build Triton server from build.py with r22.08 for RTX A2000 gpu with a requriment for minimal tritonserver with should support  these backends dali, tensorrt, ensemble, pytorch, and onnxruntime. Enabled with gpu support and inference requests using grpc. 
Sys os: Ubuntu 20.08

Command I tried:

sudo python3 build.py --enable-logging --enable-stats --enable-tracing --enable-metrics --enable-gpu-metrics  --enable-gpu --endpoint grpc --backend ensemble --backend tensorrt  --backend onnxruntime --backend pytorch --backend=python --backend=dali
Building Triton Inference Server
platform linux
machine x86_64
version 2.30.0dev
build dir /home/sreekanth/source_code/tycoai-services/ai/acvs-tycoai-triton-server-cpu/server/build
install dir None
cmake dir None
default repo-tag: main
container version 23.01dev
upstream container version 22.12
endpoint "grpc"
backend "ensemble" at tag/branch "main"
backend "tensorrt" at tag/branch "main"
backend "onnxruntime" at tag/branch "main"
backend "pytorch" at tag/branch "main"
backend "python" at tag/branch "main"
backend "dali" at tag/branch "main"
component "common" at tag/branch "main"
component "core" at tag/branch "main"
component "backend" at tag/branch "main"
component "thirdparty" at tag/branch "main"Building Triton Inference Server
platform linux
machine x86_64
version 2.25.0
build dir /home/sreekanth/source_code/tycoai-services/ai/acvs-tycoai-triton-server-cpu/server/build
install dir None
cmake dir None
default repo-tag: r22.08
container version 22.08
upstream container version 22.08
endpoint "grpc"
backend "ensemble" at tag/branch "r22.08"
backend "tensorrt" at tag/branch "r22.08"
backend "onnxruntime" at tag/branch "r22.08"
backend "pytorch" at tag/branch "r22.08"
backend "python" at tag/branch "r22.08"
backend "dali" at tag/branch "r22.08"
component "common" at tag/branch "r22.08"
component "core" at tag/branch "r22.08"
component "backend" at tag/branch "r22.08"
component "thirdparty" at tag/branch "r22.08"

My Gpu Details:
at Jan 14 16:47:16 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA RTX A200...  On   | 00000000:9E:00.0 Off |                  Off |
| 30%   42C    P8    13W /  70W |    118MiB / 12282MiB |      0%      Default |
|                               |                      |                  N/A |

Error Details:
[ 69%] Building CXX object CMakeFiles/onnxruntime_providers.dir/workspace/onnxruntime/onnxruntime/core/providers/cpu/math/cumsum.cc.o
make[2]: *** [CMakeFiles/onnxruntime_providers_cuda.dir/build.make:1390: CMakeFiles/onnxruntime_providers_cuda.dir/workspace/onnxruntime/onnxruntime/core/providers/cuda/math/topk_impl.cu.o] Error 255
make[2]: *** Waiting for unfinished jobs....
/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

[ 69%] Building CXX object CMakeFiles/onnxruntime_providers.dir/workspace/onnxruntime/onnxruntime/core/providers/cpu/math/det.cc.o
/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [CMakeFiles/onnxruntime_providers.dir/build.make:118: CMakeFiles/onnxruntime_providers.dir/workspace/onnxruntime/onnxruntime/core/providers/cpu/activation/activations.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

[ 69%] Building CXX object CMakeFiles/onnxruntime_providers.dir/workspace/onnxruntime/onnxruntime/core/providers/cpu/math/einsum.cc.o
/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [CMakeFiles/onnxruntime_providers.dir/build.make:146: CMakeFiles/onnxruntime_providers.dir/workspace/onnxruntime/onnxruntime/core/providers/cpu/controlflow/loop.cc.o] Error 1
/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [CMakeFiles/onnxruntime_providers.dir/build.make:244: CMakeFiles/onnxruntime_providers.dir/workspace/onnxruntime/onnxruntime/core/providers/cpu/cpu_provider_shared.cc.o] Error 1
/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/bin/bash: line 1: 32812 Killed                  cicc --c++14 --gnu_version=90400 --diag_error default_stream_launch --display_error_number --orig_src_file_name "/workspace/onnxruntime/onnxruntime/contrib_ops/cuda/bert/attention_impl.cu" --orig_src_path_name "/workspace/onnxruntime/onnxruntime/contrib_ops/cuda/bert/attention_impl.cu" --allow_managed --relaxed_constexpr --diag_suppress=bad_friend_decl --diag_suppress=unsigned_compare_with_zero --diag_suppress=expr_has_no_effect -arch compute_80 -m64 --no-version-ident -ftz=0 -prec_div=1 -prec_sqrt=1 -fmad=1 --include_file_name "tmpxft_000070b0_00000000-3_attention_impl.fatbin.c" -tused --module_id_file_name "/tmp/tmpxft_000070b0_00000000-4_attention_impl.module_id" --gen_c_file_name "/tmp/tmpxft_000070b0_00000000-7_attention_impl.compute_80.cudafe1.c" --stub_file_name "/tmp/tmpxft_000070b0_00000000-7_attention_impl.compute_80.cudafe1.stub.c" --gen_device_file_name "/tmp/tmpxft_000070b0_00000000-7_attention_impl.compute_80.cudafe1.gpu" "/tmp/tmpxft_000070b0_00000000-18_attention_impl.compute_80.cpp1.ii" -o "/tmp/tmpxft_000070b0_00000000-7_attention_impl.compute_80.ptx" > /tmp/tmpxft_000070b0_00000000-28_1c09510_stdout 2> /tmp/tmpxft_000070b0_00000000-28_1c09510_stderr
/bin/bash: line 1: 31226 Killed                  cicc --c++14 --gnu_version=90400 --diag_error default_stream_launch --display_error_number --orig_src_file_name "/workspace/onnxruntime/onnxruntime/core/providers/cuda/math/binary_elementwise_ops_impl.cu" --orig_src_path_name "/workspace/onnxruntime/onnxruntime/core/providers/cuda/math/binary_elementwise_ops_impl.cu" --allow_managed --relaxed_constexpr --diag_suppress=bad_friend_decl --diag_suppress=unsigned_compare_with_zero --diag_suppress=expr_has_no_effect -arch compute_80 -m64 --no-version-ident -ftz=0 -prec_div=1 -prec_sqrt=1 -fmad=1 --include_file_name "tmpxft_0000422f_00000000-3_binary_elementwise_ops_impl.fatbin.c" -tused --module_id_file_name "/tmp/tmpxft_0000422f_00000000-4_binary_elementwise_ops_impl.module_id" --gen_c_file_name "/tmp/tmpxft_0000422f_00000000-7_binary_elementwise_ops_impl.compute_80.cudafe1.c" --stub_file_name "/tmp/tmpxft_0000422f_00000000-7_binary_elementwise_ops_impl.compute_80.cudafe1.stub.c" --gen_device_file_name "/tmp/tmpxft_0000422f_00000000-7_binary_elementwise_ops_impl.compute_80.cudafe1.gpu" "/tmp/tmpxft_0000422f_00000000-18_binary_elementwise_ops_impl.compute_80.cpp1.ii" -o "/tmp/tmpxft_0000422f_00000000-7_binary_elementwise_ops_impl.compute_80.ptx" > /tmp/tmpxft_0000422f_00000000-28_219be40_stdout 2> /tmp/tmpxft_0000422f_00000000-28_219be40_stderr
/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

make[2]: *** [CMakeFiles/onnxruntime_providers_cuda.dir/build.make:2348: CMakeFiles/onnxruntime_providers_cuda.dir/workspace/onnxruntime/onnxruntime/contrib_ops/cuda/bert/attention_impl.cu.o] Error 255
/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

make[1]: *** [CMakeFiles/Makefile2:1755: CMakeFiles/onnxruntime_providers.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

/workspace/onnxruntime/onnxruntime/gsl/gsl-lite.hpp(1959): warning #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed

make[2]: *** [CMakeFiles/onnxruntime_providers_cuda.dir/build.make:1300: CMakeFiles/onnxruntime_providers_cuda.dir/workspace/onnxruntime/onnxruntime/core/providers/cuda/math/binary_elementwise_ops_impl.cu.o] Error 255
make[1]: *** [CMakeFiles/Makefile2:1841: CMakeFiles/onnxruntime_providers_cuda.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
Traceback (most recent call last):
  File "/workspace/onnxruntime/tools/ci_build/build.py", line 2744, in <module>
    sys.exit(main())
  File "/workspace/onnxruntime/tools/ci_build/build.py", line 2663, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/workspace/onnxruntime/tools/ci_build/build.py", line 1301, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/workspace/onnxruntime/tools/ci_build/build.py", line 714, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/workspace/onnxruntime/tools/python/util/run.py", line 49, in run
    completed_process = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/cmake', '--build', '/workspace/build/Release', '--config', 'Release', '--', '-j40']' returned non-zero exit status 2.
The command '/bin/sh -c ./build.sh ${COMMON_BUILD_ARGS} --update --build --use_cuda --cuda_home "/usr/local/cuda" --cudnn_home "/usr/local/cudnn-8.5/cuda" --use_tensorrt --tensorrt_home "/usr/src/tensorrt" --use_openvino CPU_FP32' returned a non-zero code: 1
make[2]: *** [CMakeFiles/ort_target.dir/build.make:74: onnxruntime/lib/libonnxruntime.so] Error 1
make[2]: Leaving directory '/tmp/tritonbuild/onnxruntime/build'
make[1]: *** [CMakeFiles/Makefile2:147: CMakeFiles/ort_target.dir/all] Error 2
make[1]: Leaving directory '/tmp/tritonbuild/onnxruntime/build'
make: *** [Makefile:136: all] Error 2
error: build failed

**Comment by jvemuls1** [comment]
Hello anyone knows this issue

**Comment by SirMomster** [comment]
Same issue here, if I find it myself I will post an update.

**Comment by GuanLuo** [comment]
I saw this in your log `c++: fatal error: Killed signal terminated program cc1plus`, are you running out of memory?

**Comment by SirMomster** [comment]
Hey,

First let me clarify, I had the same issue as you did building onnxruntime in a docker container. The issue you are having seems related to mine, but as I don't have a Triton server, so I can't test for you. 

How I got to your issues is by looking for: `[CMakeFiles/onnxruntime_providers_cuda.dir/build.make:1390: CMakeFiles/onnxruntime_providers_cuda.dir/workspace/onnxruntime/onnxruntime/core/providers/cuda/math/topk_impl.cu.o] Error 255`

Which was also the cause of my problems, for some reason the onnxruntime doesn't want to build using the regular steps. And I also ended up with the random errors and stuff exactly like your logs.

I fixed it with the following, however again I run locally in docker. I post my full docker container setup here. But I mimicked the Azure CI/CD (from the onnxruntime repository) pipelines and used the `build.py` scripts instead of the .sh files for installing the onnxruntime.

For me, this works considerably better than the build.sh did, Ninja also made the build go faster and to me for some reason seemed more stable. I'm uncertain, but if you could build `Triton Inference Server` without onnxruntime and install it manually using the steps in my container.

```Docker
FROM nvidia/cuda:11.6.1-cudnn8-devel-ubuntu20.04

ENV DEBIAN_FRONTEND=noninteractive

ENV ONNXRUNTIME_VERSION=1.13.1
ENV NUM_JOBS=10
ENV CMAKE_VERSION=3.25.1
ENV ONNX_CUDA_VERSION=11.6
ENV CUDA_ARCHITECTURES=86

RUN apt update -y \
        && apt install -y --no-install-recommends \
        build-essential \
        wget \
        zip \
        cmake \
        ninja-build \
        python3-dev \
        ca-certificates \
        g++ \
        python3-numpy \
        gcc \
        make \
        git \
        python3-setuptools \
        python3-wheel \
        python3-packaging \
        python3-pip \
        aria2 \
        unzip && \
        rm -rf /var/lib/apt/lists/*

# Install required CMAKE version
RUN aria2c -q -d /tmp -o cmake-${CMAKE_VERSION}-linux-x86_64.tar.gz https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-linux-x86_64.tar.gz \
    && tar -zxf /tmp/cmake-${CMAKE_VERSION}-linux-x86_64.tar.gz --strip=1 -C /usr && rm -rf ./tmp/*

RUN cd /tmp  && \
    git clone --recursive --branch v${ONNXRUNTIME_VERSION} https://github.com/Microsoft/onnxruntime && \
    cd /tmp/onnxruntime && \
    python3 ./tools/ci_build/build.py \
    --build_dir /build \
    --cmake_generator Ninja \
    --config RelWithDebInfo \
    --update \
    --build \
    --skip_submodule_sync \
    --build_shared_lib \
    --parallel \
    --enable_onnx_tests \
    --use_cuda \
    --cuda_version=${ONNX_CUDA_VERSION} \
    --cuda_home=/usr/local/cuda-${ONNX_CUDA_VERSION} \
    --cudnn_home=/usr/local/cuda-${ONNX_CUDA_VERSION} \
    --enable_cuda_profiling \
    --cmake_extra_defines CMAKE_CUDA_ARCHITECTURES=${CUDA_ARCHITECTURES} && \
    cd /build/RelWithDebInfo && ninja install \
    && rm -rf ./tmp/*

ENV LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/build/RelWithDebInfo/lib
ENV PATH=${PATH}:/usr/local/include/onnxruntime

RUN ldconfig
```

I hope this at least helps a bit for you or helps us find a better solution to your (our) problem. Furthermore, I also tested other CUDA versions and most seem to work fine using the above steps.
