### ISSUE TITLE
E0116 09:33:42.589212 1 model_repository_manager.cc:1002] Poll failed for model directory 'pytorch_classifier': Invalid model name: Could not determine backend for model 'pytorch_classifier' with no backend in model configuration. Expected model name of the form 'model.<backend_name>'.

### ISSUE THREAD

**Issue by Jayharer** [triton-inference-server/server#5255]
**Description**
I have created pytorch model, & deploying on triton server

**Triton Information**
TRITON_IMAGE = 'nvcr.io/nvidia/tritonserver:22.12-py3'

Are you using the Triton container or did you build it yourself?
by using container

**To Reproduce**
name: "pytorch_classifier"
backend: "pytorch"
max_batch_size: 0
input [                                 
 {  
    name: "input__0"
    data_type: TYPE_FP32
    dims: [ 1, 4 ]                    
  } 
]
output [
 {
    name: "output__0"
    data_type: TYPE_FP32
    dims: [ 1 ]
  }
]
instance_group [{ kind: KIND_CPU }]

**Comment by dyastremsky** [comment]
Thanks for answering this question, Victor! Correcting the backend should resolve the issue.
