### ISSUE TITLE
Guidance for model instaces and gpu count

### ISSUE THREAD

**Issue by azsh1725** [triton-inference-server/server#5271]
Hello! 

Could you, please, explain is it correct that with an increase in the model instances, I can expect an increase in RPS from the model in triton? And increasing the number of GPUs also affects the RPS of the model? Is there any guidance on how best to use these parameters to get the best performance in triton?

**Comment by Tabrizian** [comment]
Hi @azsh1725, increasing the number of GPUs should increase the model throughput in most scenarios. For determining the optimal instance count and dynamic batching setting for your model, we recommend using [Model Analyzer](https://github.com/triton-inference-server/model_analyzer). It will automatically try many different configurations to find the best model configuration.

**Comment by azsh1725** [comment]
@Tabrizian thank you for you response, i'll try it.

**Comment by azsh1725** [comment]
Is it possible to test the server (for example with 22.01 version) with different version of the analyzer (for example with 22.12 version), or it is recommended to use the same versions for server and analyzer?

**Comment by azsh1725** [comment]
Okay, if I understood correctly, then the model analyzer is a container similar to a Triton that runs different models inside itself and tests their performance, right? Therefore, it is better to use the version of the analyzer identical to the Triton version.

**Comment by Tabrizian** [comment]
It is recommended to use the same version of Model Analyzer and Triton Server.
