### ISSUE TITLE
Every other sequence_id is set to zero using pytorch backend with stateful TS model.

### ISSUE THREAD

**Issue by acinnes** [triton-inference-server/server#5276]
**Description**

I'm trying to host stateful TS models directly in Triton using the pytorch backend, so that internal state can stay on the GPU and not be transmitted back and forth to the client. 

I've created a trivial version of a model that will initialize and track updates to internal state for multiple active sequences of inference requests, using the start/end/corr_id control inputs supplied by Triton. I have a simple test script that submits multiple concurrent inference sequences, using either the http or grpc tritonclient. Triton is configured to build batches from the sequences using the sequence batcher.

This works, except that by the time the inputs reach my model, roughly every other inference request has its sequence_id (corr_id) reset to zero. This is obviously broken for any actual use.

**Triton Information**
I'm currently testing with Triton 22.12, pulled directly from NGC.

**To Reproduce**

Load test model from the attached model_test.zip in Triton:
- docker run -it --rm -p8000:8000 -p8001:8001 -p8002:8002 -v$(realpath model_test):/models nvcr.io/nvidia/tritonserver:22.12-pyt-python-py3 tritonserver --model-repository=/models

You can update the TS model if you wish as follows:
- python stateful_model.py --head_output_path stateful.test.ts
- cp stateful.test.ts model_test/stateful_test/1/model.pt 

Run test script on same host (edit to switch from http to grpc):
- python test_stateful_model.py

The model prints out the control inputs for each (dynamically batched) inference request it receives from Triton. It will also print warnings if it encounters sequences in an unexpected state, such as end of a sequence it isn't currently tracking, or a non-starting request from a sequence it hasn't seen before.

The test script is submitting 16 concurrent sequences, of 4 inference requests each. The sequence IDs start at 1000 and go up to 1015.

**Expected behavior**

The model should be receiving batches where every sequence_id is a different number from range(1000, 1016), allowing the model to reference the correct state variables for that sequence. There should be no requests where sequence_id is zero (since the test script always supplies a non-zero value to the tritonclient object). There should be no warnings about sequence inputs being received in an unexpected state.

**Actual (incorrect) behaviour**

When I run this locally, I get output like this
```code
[8, 127, 15552]
 1000     1     0
    0     1     0
 1001     1     0
    0     1     0
 1002     1     0
    0     1     0
 1003     1     0
    0     1     0
[ CPUIntType{8,3} ]
[7, 127, 15552]
 1008     1     0
    0     1     0
 1010     1     0
    0     1     0
 1009     1     0
    0     1     0
 1012     1     0
[ CPUIntType{7,3} ]
...
[6, 127, 15552]
 1010     0     0
    0     0     0
 1011     0     0
    0     0     0
 1012     0     0
    0     0     0
[ CPUIntType{6,3} ]
** id 1011 is missing from state_map; initializing
** id 1012 is missing from state_map; initializing
...
[7, 127, 15552]
 1008     0     1
    0     0     1
 1009     0     1
    0     0     1
 1010     0     1
    0     0     1
 1011     0     1
[ CPUIntType{7,3} ]
** id 0 is missing from state_map; initializing
** id 0 wasn't in state_map at seq_end
** id 0 wasn't in state_map at seq_end
```

If I run triton with `--log-verbose=1`, I see that it receives the individual inference requests with correct sequence_id values, so the corruption of some of the ids appears to be occurring somewhere inside the sequence/dynamic batchers or the pytorch backend.

**Attachments**

[model_test_script.zip](https://github.com/triton-inference-server/server/files/10500581/model_test_script.zip)
This contains the source code for the trivial stateful TS model, and the python test script to submit async sequences of dummy data.

[model_test.zip](https://github.com/triton-inference-server/server/files/10500570/model_test.zip)
This contains the model repo for hosting the stateful test model in Triton using the pytorch backend.

**Comment by dyastremsky** [comment]
Thank you for your detailed report and reproduction steps. We've filed a ticket to investigate.

**Comment by kthui** [comment]
PyTorch does not support uint64 https://pytorch.org/docs/stable/tensors.html#data-types. The "corr_ids__3" in the config is using "TYPE_UINT64", and there is a missing validation that allows the config to slide through. Could you change the data type to "TYPE_INT64"? I have tested that it worked:
```
[10, 127, 15552]
 1000     1     0
 1001     1     0
 1002     1     0
 1003     1     0
 1004     1     0
 1005     1     0
 1006     1     0
 1007     1     0
 1008     1     0
 1009     1     0
[ CPULongType{10,3} ]
[6, 127, 15552]
 1010     1     0
 1011     1     0
 1012     1     0
 1013     1     0
 1014     1     0
 1015     1     0
[ CPULongType{6,3} ]
[9, 127, 15552]
```
