### ISSUE TITLE
[Question]About Data collection and Data send back

### ISSUE THREAD

**Issue by FlyTOmeLight** [triton-inference-server/server#5283]
My tritonserver version is 22.10.
I would like to know is there any good way for tritonserver to collect inference input images and inference results into files or logs? We want to get these data and then do training.
Hope to get your help~
Thanks!

**Comment by rmccorm4** [comment]
Hi @FlyTOmeLight ,

For a simple built-in solution, you may be interested in the [Tracing API](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/trace.md), specifically the `TENSOR_QUEUE_INPUT` and `TENSOR_BACKEND_OUTPUT` fields I believe for logging the inputs/results.

For anything more complex, I think you'd want to try a custom [python_backend](https://github.com/triton-inference-server/python_backend) model (pre/postprocess) that does the custom logic you're looking for (logging, saving, etc.) through an [Ensemble](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/trace.md) or [BLS](https://github.com/triton-inference-server/python_backend/blob/main/README.md#business-logic-scripting).
