### ISSUE TITLE
[Question] Is there a way to send raw string as input to triton server?

### ISSUE THREAD

**Issue by InCogNiTo124** [triton-inference-server/server#5286]
Hello,

we're deploying some LLM models and we cannot figure out how to send raw strings. This is what I've been doing so far:

<details>
<summary>request.json</summary>

```json
{
    "id": "test",
    "inputs": [
    {
        "name": "B64_ENC",
        "datatype": "STRING",
        "shape": [1, 4],
        "data": ["abcd"]
    }
    ]
}
```

</details>

<details>
<summary>modeldir/custom/config.pbtxt</summary>

```pbtxt
backend: "python"
max_batch_size: 64
default_model_filename: "decode.py"
input [
  {
    name: "B64_ENC"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]
output [
  {
    name: "B64_DEC"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]

dynamic_batching {
}

instance_group [
    {
      count: 1
      kind: KIND_CPU
    }
  ]
```
</details>

<details>

<summary>modeldir/custom/1/decode.py</summary>

```python
import triton_python_backend_utils as pb_utils
import json

class TritonPythonModel:
    def initialize(self, args):
        self.model_config = json.loads(args["model_config"])

    def execute(self, requests):
        return list(self.process(request) for request in requests)

    def process(self, request):
        in_0 = pb_utils.get_input_tensor_by_name(request, "B64_ENC")
        print(in_0)
        print(dir(in_0))
        return str(reversed(in_0))
```

</details>

<details>
<summary>curl command</summary>

```shell
$ curl -X POST --data-binary @request_str.json  localhost:8000/v2/models/custom/versions/1/infer
{"error":"invalid datatype for input B64_ENC"}
```

</details>

The error is `{"error":"invalid datatype for input B64_ENC"}`

**Comment by dyastremsky** [comment]
What do you mean by a raw string? If you're looking at sending binary data, there is an extension for that [here](https://github.com/triton-inference-server/server/blob/main/docs/protocol/extension_binary_data.md).

Triton internally represents strings/bytes tensor elements as `<str_length><str_content>` for performance reasons, so you may not get much speedup from using binary or byte data if that's the motivation.

If you're simply looking at how to pass string data into a model, some of the tests in the QA folder like [this one](https://github.com/triton-inference-server/server/tree/main/qa/L0_string_io) and [this one](https://github.com/triton-inference-server/server/tree/main/qa/L0_nullchar_string) could be helpful references.

**Comment by InCogNiTo124** [comment]
thank you @dyastremsky.

unfortunately, the data extension is no use for us as we cannot control how the requests are sent to us (we are using [GCP Vertex AI](https://cloud.google.com/vertex-ai)). We found it weird that there is no string support for inputs, and encoding the bytes as a json array felt silly.

Thank you for the links to the examples. I'll be closing this.
