### ISSUE TITLE
how to build "xx.yy-py3-min" for base image "ubuntu:20.04"?

### ISSUE THREAD

**Issue by monsterlyg** [triton-inference-server/server#5291]
[NGC](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/tritonserver) has provided "xx.yy-py3-min" image for source-build. but i want to know whether the image size can be cut to a smalller one. And I want to know which packages(there may be a dockerfile or a package list) should be installed from  "ubuntu:20.04" to "xx.yy-py3-min".

**Comment by dyastremsky** [comment]
We provide the smallest image possible that can be used for all build cases. If you don't need every option, it's possible building your own py3-min container will result in a smaller container. We don't have documentation on this, as the py3-min container is supposed to have everything needed for building.

If you want to build your own, you should be able to use Ubuntu with the [correct CUDA version ](https://docs.nvidia.com/deeplearning/triton-inference-server/release-notes/rel_20-03.html) and then look at what goes into [the buildbase container](https://github.com/triton-inference-server/server/blob/9385a07d3240587165b14432b729354e6c26ce3e/build.py#L814-L918). That should be a good reference for everything you need.
