### ISSUE TITLE
Include Python protobuf files in install folder 

### ISSUE THREAD

**Issue by jamied157** [triton-inference-server/server#5292]
**Is your feature request related to a problem? Please describe.**
In my use case I build the triton server from source using build.py. It would be useful for us to use the Python protobuf files that are generated in the common repo: https://github.com/triton-inference-server/common/tree/main/protobuf (with the TRITON_COMMON_ENABLE_PROTOBUF_PYTHON) 

For some reason these files don't get generated in the build, even though the .pb.h files are generated for cpp.

**Describe the solution you'd like**
As well as the cpp files, the _pb2.py files generated by `protoc` are installed as part of the build process.

**Describe alternatives you've considered**
I could git clone the common repo directly and try to build from there, however I don't have protoc installed directly (it gets pulled in by the triton build process) so would prefer this solution.

**Comment by dyastremsky** [comment]
Thanks for this request. @Tabrizian, is there a way to generate the protobuf files from build.py? If not, I can create a feature request.

**Comment by Tabrizian** [comment]
Hi @jamied157, the protobufs are included in the client builds in the SDK container. When you install the client, you can access them from the `tritonclient` module:

```
from tritonclient.grpc import service_pb2_grpc
from tritonclient.grpc import service_pb2
```

**Comment by jamied157** [comment]
Ah excellent, I wasn't aware - I think this works for us, thanks
