### ISSUE TITLE
Triton onnxruntime backend serving having different result compared to the native python inference on a resnet18 model.

### ISSUE THREAD

**Issue by lxztju** [triton-inference-server/server#5300]
**Description**
Triton onnxruntime backend serving having different result compared to the native python inference on a resnet18 model.

**Triton Information**
triton  23.01 docker image.

**To Reproduce**

onnx_path: https://github.com/onnx/models/raw/main/vision/classification/resnet/model/resnet18-v1-7.onnx

[reproduce.zip](https://github.com/triton-inference-server/server/files/10568461/reproduce.zip)

The results of some images have small differences, but others have large differences. For example, In the reproduce.zip, the difference of demo.jpg is unacceptable. 

I am confused by this problem. Did I make a mistake somewhere？Hope you can help me.

**Comment by julienripoche** [comment]
Hi, do you have similar issues while directly running your ONNX model throught the `onnxruntime` package outside of Triton Server ?

**Comment by julienripoche** [comment]
In your demo you don't use the same image for the prediction in python onnxruntime and triton onnxruntime.
In one case you use :
```
imgpath = './workspace/demo.jpg'
```
In the other you use :
```
pred, score = predict('./workspace/test.jpg')
```
Might this be the reason of such big difference ?

**Comment by julienripoche** [comment]
Well I got the same result in both cases using `./workspace/demo.jpg`.

```sh
$ python python_infer.py
702 0.12024764
```

```sh
$ python triton_client.py 
702 0.12024763971567154
```

**Comment by lxztju** [comment]
> Well I got the same result in both cases using `./workspace/demo.jpg`.
> 
> ```shell
> $ python python_infer.py
> 702 0.12024764
> ```
> 
> ```shell
> $ python triton_client.py 
> 702 0.12024763971567154
> ```

Thanks for your work, I will check where I make mistake.

**Comment by lxztju** [comment]
I find the answer of this problem.
