### ISSUE TITLE
[TRT] | Complete error not propagated to the http server 

### ISSUE THREAD

**Issue by nskool** [triton-inference-server/server#5304]
**Description**

**Triton Information**
Reproducible with 22.07/22.10/22.12

**To Reproduce**
1. Use the TRT model as described in this notebook - https://github.com/aws/amazon-sagemaker-examples/blob/main/sagemaker-triton/resnet50/triton_resnet50.ipynb.
2. The model may be run locally or on SageMaker.
3. When a large instance count is used, or several such TRT models are loaded, at some point Triton server fails with the error:
```
ModelError: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received client error (400) from primary with message "{"error":"load failed for model '495cff3d03904752de92203d58f75f33': version 1 is at UNAVAILABLE state: Internal: unable to create TensorRT context;\n"}".
```
Only the error string `Internal: unable to create TensorRT context` is propagated to the http server 'response' buffer.
4. In the logs, we can see the following error:
```
I0125 20:05:23.645607 87 [logging.cc:49](http://logging.cc:49/)] [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 1459, GPU 22254 (MiB)
E0125 20:05:23.696285 87 [logging.cc:43](http://logging.cc:43/)] 1: [defaultAllocator.cpp::allocate::20] Error Code 1: Cuda Runtime (out of memory)
W0125 20:05:23.696333 87 [logging.cc:46](http://logging.cc:46/)] Requested amount of GPU memory (513802240 bytes) could not be allocated. There may not be enough free memory for allocation to succeed.
E0125 20:05:23.720471 87 [logging.cc:43](http://logging.cc:43/)] 2: [executionContext.cpp::ExecutionContext::409] Error Code 2: OutOfMemory (no further information)
I0125 20:05:23.720523 87 [tensorrt.cc:298](http://tensorrt.cc:298/)] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0125 20:05:23.720547 87 [tensorrt.cc:237](http://tensorrt.cc:237/)] TRITONBACKEND_ModelFinalize: delete model state
E0125 20:05:23.720584 87 model_lifecycle.cc:597] failed to load '495cff3d03904752de92203d58f75f33' version 1: Internal: unable to create TensorRT context
I0125 20:05:23.720695 87 model_repository_manager.cc:1409] Model repository unregistered: /opt/ml/models/495cff3d03904752de92203d58f75f33/model
```
5. It appears that only the error generated at `model_lifecycle.cc` bubbles up to the http layer, whereas the remainder of the error is logged/lost.
6. The SageMaker front-end relies on parsing the error buffer returned from the Triton core to recognize an OOM separately and rethrow a 507 - https://github.com/triton-inference-server/server/blob/main/src/sagemaker_server.cc#L767.
7. The string `OutOfMemory` can be caught since it's on the of the strings that the parser looks for, however since the complete error message does not reach the SM-Triton frontend, instead of re-throwing a 507, only a 400 is returned.

**Expected behavior**
The entire error from the `tensorrt.cc` backend layer should propagate to the SM-Triton frontend.

**Comment by dyastremsky** [comment]
Thanks for the detailed report, Nikhil. We've filed a ticket to investigate.

**Comment by kthui** [comment]
Hi @nskool, the error returned to the client will be enhanced from
```
load failed for model '495cff3d03904752de92203d58f75f33': version 1 is at UNAVAILABLE state: Internal: unable to create TensorRT context
```
to
```
load failed for model '495cff3d03904752de92203d58f75f33': version 1 is at UNAVAILABLE state: Internal: unable to create TensorRT context: 2: [executionContext.cpp::ExecutionContext::409] Error Code 2: OutOfMemory (no further information)
```
based on the provided error log.

The issue will be auto-closed when the PR is merged, but please feel free to let us know if you experience any further issue.
