### ISSUE TITLE
Document how expected model inputs tensor gets an extra dimension (of -1 items) and how to deal with it

### ISSUE THREAD

**Issue by mirekphd** [triton-inference-server/server#5319]
**Is your feature request related to a problem? Please describe.**

Despite model config file specifying that the inputs array is only a one-dimensional (here: with 238 elements), like this (here: all parameters from the `input` key, as returned by `get_model_config`, whereas the config file specified only the minimum, i.e. `data_type`, `dims` and `name`):
```
  'input': [{'allow_ragged_batch': False,
             'data_type': 'TYPE_FP32',
             'dims': [238],
             'format': 'FORMAT_NONE',
             'is_shape_tensor': False,
             'name': 'input__0',
             'optional': False}],
```

 when making an HTTP or GRPC request with `tritonclient` we get an `StatusCode.INVALID_ARGUMENT` error, stating that the expected model inputs tensor needs an extra dimension (of -1 items):
`InferenceServerException: [StatusCode.INVALID_ARGUMENT] [request id: <id_unknown>] unexpected shape for input 'input__0' for model 'some_model'. Expected [-1, 238], got [238]`

* Similar information is returned by the server when using the `get_model_metadata` method:
```
{'inputs': [{'datatype': 'FP32', 'name': 'input__0', 'shape': [-1, 238]}],
 'name': 'some_model',
 'outputs': [{'datatype': 'FP32', 'name': 'output__0', 'shape': [-1, 2]}],
 'platform': 'fil',
 'versions': ['1']}
```

**Describe the solution you'd like**
Please document - both in the code (error messages) and the docs pages, the reason(s), i.e. design purpose and parameters settings triggering this extra dimension being added to expected inputs and recommended way(s) to deal with the problem when the user fails to obtain correct response from the server.

**Describe alternatives you've considered**
I know how to make things worse: to add yet another expected dimension we can change the config to:
```
  'input': [{'allow_ragged_batch': False,
             'data_type': 'TYPE_FP32',
             'dims': [-1, 238],
             'format': 'FORMAT_NONE',
             'is_shape_tensor': False,
             'name': 'input__0',
             'optional': False}],
```
which leads to this error message:
```
InferenceServerException: [StatusCode.INVALID_ARGUMENT] [request id: <id_unknown>] unexpected shape for input 'input__0' for model 'some_model'. Expected [-1,-1,238], got [238]
```

**Additional context**
Using latest containerized version of the server (`nvcr.io/nvidia/tritonserver:23.01-py3`) and the latest client from PyPI (`tritonclient` version 2.30.0).

**Comment by rmccorm4** [comment]
Hi @mirekphd ,

Can you share your full model `config.pbtxt`? Is is possible you have a non-zero max_batch_size set? This may introduce an implicit batch dimension. You can try setting `max_batch_size: 0` if you want to keep the batch dimension explicit in each input.

If there is still an issue with a `max_batch_size` of zero, you may need to pad a batch dimension of 1 across all inputs (the batch size should be the same across all inputs in a request).

**Comment by mirekphd** [comment]
Hi @rmccorm4,

You were spot on in your diagnosis - the relevant parameter `max_batch_size` is set to a positive value ('max_batch_size': 1024), which apparently turns on batching and introduces an expectation of another dimension. I wish it were more explicitly documented, ideally in that error message, e.g. when dimensions list differs by a -1 in the 1st position, you could augment that error message with a sentence like "Note that setting non-zero `max_batch_size` requires extra dimension to be provided in each input." I think it would help many people understand the reasons for this error.

But in my case the change of `max_batch_size` from 0 to a non-zero value was a workaround for a more serious problem. When I initially set it to 0 (and input data was supplied correctly to the inference engine), it caused a memory segmentation fault in the `libtriton_fil.so` library each time `tritonserver` received a request from `tritonclient`. I think I should open a separate issue to help you reproduce and fix it.

**Comment by rmccorm4** [comment]
Hi @mirekphd, 

> I wish it were more explicitly documented, ideally in that error message, e.g. when supplied input data is missing -1 at the 1st position (dimensions list element), you could augment that error message

I think that's some great feedback. What do you think of something like this?
```
root@rmccormick-dt:/workspace# perf_analyzer -m double --shape INPUT0:1
...

Request concurrency: 1
Failed to maintain requested inference load. Worker thread(s) failed to generate concurrent requests.
Thread [0] had error: [request id: <id_unknown>] unexpected shape for input 'INPUT0' for model 'double'. Expected [-1,-1,-1], got [1,1]. NOTE: Setting a non-zero max_batch_size in the model config will require a batch dimension to be prepended to each input shape. If you want to specify the full shape including the batch dim in your input dims config, try setting max_batch_size to zero. See the model configuration docs for more info on max_batch_size.
```

> But in my case the change of max_batch_size from 0 to a non-zero value was a workaround for a more serious problem. When I initially set it to 0 (and input data was supplied correctly to the inference engine), it caused a memory segmentation fault in the libtriton_fil.so library each time tritonserver received a request from tritonclient. I think I should open a separate issue to help you reproduce and fix it.

Yes please open a separate issue with a reproducing model and detailed steps on how to reproduce it :pray:

**Comment by mirekphd** [comment]
Hi @rmccorm4,

Thank you for addressing the batch dimension documentation issue so quickly! So here is the promised bug report for the root cause of this issue - the segfault in `libtriton_fil.so`: https://github.com/triton-inference-server/server/issues/5332
