### ISSUE TITLE
How do i set labels for my Triton Model?

### ISSUE THREAD

**Issue by RosterMouch** [triton-inference-server/server#5322]
As the title mentioned,how do i set the labels for my Yolov5 custom trained model?
Here is my protobuf config.pbtxt:
```protobuf
output[
  {
    name: "output0",
    data_type: TYPE_FP16
    dims: [ 25200,9 ],
    label_filename: "labels.txt"
  }
]
```
And triton logs show model is ready to roll:
```ascii
+-------------+---------+--------+
| Model       | Version | Status |
+-------------+---------+--------+
| action_onnx | 1       | READY  |
```
And here is the python client code:
```python
inputs = [grpcclient.InferInput('images', img.shape, 'FP16')] 
    inputs[0].set_data_from_numpy(img) 
    result = triton_client.infer( 
    'action_trt', 
    inputs, 
    request_id=str('1'),
    model_version='1', 
    outputs=outputs) 
    output_array = result.as_numpy('output0')
    print(output_array)
```
It returns a array that is that contains a lots of data but not the label.
So how should i do,the project is close to ddl and i need a hot rush,plz!!!

**Comment by RosterMouch** [comment]
Recorrect the model status as below,both onnx and TensorRT engine work.
But i don`t know why label doesn`t work correctly.
```ascii
+-------------+---------+--------+
| Model       | Version | Status |
+-------------+---------+--------+
| action_onnx | 1       | READY  |
| action_trt  | 1       | READY  |
+-------------+---------+--------+
```

**Comment by GuanLuo** [comment]
Did you request to receive classification output instead of raw output (i.e. actual tensor)? Ref: [request classification on output](https://github.com/triton-inference-server/client/blob/r23.01/src/python/examples/image_client.py#L219)

**Comment by RosterMouch** [comment]
> Did you request to receive classification output instead of raw output (i.e. actual tensor)? Ref: [request classification on output](https://github.com/triton-inference-server/client/blob/r23.01/src/python/examples/image_client.py#L219)

after i set the class_count,it returns an error like this:
```
class result not available for output due to unsupported type 'FP16'
```
So should i recorrect my config file and reboot Triton?

**Comment by RosterMouch** [comment]
Close since no longer response from contributors

**Comment by xiong-qiao** [comment]
Hi I got the same error when requesting to receive classification output instead of raw output with a FP16 model. Does this mean the classification label output is only supported for FP32?

**Comment by GuanLuo** [comment]
Sorry for missing the reply, classification extension doesn't currently support FP16 as it is not primitive type in C++, you will have to add casting layer into FP32 (or other primitive types) for the extension to work properly.
