### ISSUE TITLE
/v2/repository/index api is very slowly

### ISSUE THREAD

**Issue by zjq1996518** [triton-inference-server/server#5325]
#5221 I found that my triton started to slow down after running for three days. Before that, triton was rebuilt with a new version, which was very fast three days ago.

**Comment by rmccorm4** [comment]
CC @kthui

**Comment by kthui** [comment]
> sorry, My github didn't remind me and I guess it's my server network problem, but I tried curl -X POST -w ' %{time_connect}:%{time_starttransfer}:%{time_total} ' -o /dev/null -s http://192.168.3.245:8100/v2/repository/index commands, and the average response time was 4s, but the average response time of curl -X POST -w ' %{time_connect}:%{time_starttransfer}:%{time_total} ' -o /dev/null -s http://192.168.3.245:8100/v2/models/line_ox commands was only 700us, the line_ox is my model name.
It doesn't look like a network problem.

No worries. I will test again after the server is started for 3 days.

**Comment by zjq1996518** [comment]
> > sorry, My github didn't remind me and I guess it's my server network problem, but I tried curl -X POST -w ' %{time_connect}:%{time_starttransfer}:%{time_total} ' -o /dev/null -s http://192.168.3.245:8100/v2/repository/index commands, and the average response time was 4s, but the average response time of curl -X POST -w ' %{time_connect}:%{time_starttransfer}:%{time_total} ' -o /dev/null -s http://192.168.3.245:8100/v2/models/line_ox commands was only 700us, the line_ox is my model name.
> > It doesn't look like a network problem.
> 
> No worries. I will test again after the server is started for 3 days.
Thanks!

**Comment by kthui** [comment]
Hi @zjq1996518, could you confirm the following setup is similar to yours:
- Start the server with 30 - 40 models (maybe some empty Python models that outputs the inputs).
- Do some casual inferences to the models over a course of 3 days.
- Does not load/unload any models.
- Check the API response time 3 days later.

**Comment by zjq1996518** [comment]
> Hi @zjq1996518, could you confirm the following setup is similar to yours:
> 
> * Start the server with 30 - 40 models (maybe some empty Python models that outputs the inputs).
> * Do some casual inferences to the models over a course of 3 days.
> * Does not load/unload any models.
> * Check the API response time 3 days later.

I will call/v2/models/{model_name}/ready every 1.5 seconds to check whether the loaded model is alive.
Some models have been loaded, and some models have not been loaded.
If the loaded models are deactivated for some reason, I will call v2/repository/models/{model_name}/load to reload these models.
Our triton is deployed in k8s in the form of DaemonSet.
When the request is slow, I try to restart the pod, and the call speed will not get faster, but it will get faster after a period of time.

**Comment by kthui** [comment]
Thanks for the info @zjq1996518. Just some follow-up questions: 
 - How frequent are the models being loaded/unloaded?
 - Are the 30 models always the same set of models, or do they get replaced with some other new models via load/unload (while keeping the total number to ~30 models)?

**Comment by GuanLuo** [comment]
> When the request is slow, I try to restart the pod, and the call speed will not get faster, but it will get faster after a period of time.

If the issue persists even after restarting the pod, it feels like something outside of the application (Triton). Are you able to observe similar slowdown in a local environment?

That being said, note that the index API does poll the model repository, assuming your model storage is on cloud, it may contribute to the latency as well if there is connection slowdown with your cloud storage. And the model metadata API only operate within Triton.

**Comment by zjq1996518** [comment]
>

**Comment by zjq1996518** [comment]
> Thanks for the info @zjq1996518. Just some follow-up questions:
> 
> * How frequent are the models being loaded/unloaded?
> * Are the 30 models always the same set of models, or do they get replaced with some other new models via load/unload (while keeping the total number to ~30 models)?

Although based on the above mechanism, the frequency of model loading/unloading is very low. Unless there is model debugging, a certain model may have 20-30 times of loading and unloading.
In the debugging process, generally python backend, there will be n times of loading and unloading.
But after my observation, if the index api is fast, loading and unloading will not slow it down.

@Guoluo reminded me that my model is deployed in MinIO, and my triton configuration is s3:// https://host:port/models Could it be the problem of MinIO?

**Comment by GuanLuo** [comment]
> Could it be the problem of MinIO?

This can be verified on your end, you can compare the storage latency between normal case and when the slow down is observed.

**Comment by zjq1996518** [comment]
> > Could it be the problem of MinIO?
> 
> This can be verified on your end, you can compare the storage latency between normal case and when the slow down is observed.
Thank you very much. We finally found that MinIo's list object is slow and the api is slow. We will investigate the reason why MinIo is slow.

**Comment by kthui** [comment]
> Thank you very much. We finally found that MinIo's list object is slow and the api is slow. We will investigate the reason why MinIo is slow.

Thanks for updating. I will close the issue, but please feel free to re-open if there is something we can help.
