### ISSUE TITLE
Memory segmentation fault in `libtriton_fil.so` for an xgboost model

### ISSUE THREAD

**Issue by mirekphd** [triton-inference-server/server#5332]
**Description**
Trying to send a properly formed request (even an array full of zeroes) from `tritonclient` to either a GRPC or REST port of `tritonserver` (serving an xgboost binary classification model) causes segfault in `/opt/tritonserver/backends/fil/libtriton_fil.so`.

**Triton Information**
* Triton Server Version: 2.30.0 (NVIDIA Release 23.01 (build 52277748))
* `tritonclient` package version: 2.30.0
* using officially containerized server `nvcr.io/nvidia/tritonserver:23.01-py3` and official linux wheel of the latest `tritonclient` package installed with `pip` from PyPI.

**To Reproduce**
I've prepared a fully reproducible setup that triggers the error every time consisting of two publicly available docker containers (one from NVIDIA, one mine), two bash scripts and a python script. All you need is a Linux system (this was tested on Ubuntu 22.04), and docker (no python required on the host). It targets the gRPC endpoint, but can be easily adapted to REST.

1. Clone the repo:
`$ cd /tmp && git clone https://github.com/mirekphd/tis-dbg-20230207.git`

2. Open the first Linux terminal, and start `tritonserver` script that should start the server container and load the test model from the current folder on the host:
```
$  cd /tmp/tis-dbg-20230207 && ./start-tritonserver.sh
=============================
== Triton Inference Server ==
=============================

NVIDIA Release 23.01 (build 52277748)
Triton Server Version 2.30.0
[..]
+----------------------+---------+--------+
| Model                | Version | Status |
+----------------------+---------+--------+
| ks_clf_xgb_model_cpu | 1       | READY  |
+----------------------+---------+--------+
[..]
I0208 09:16:56.274128 1 grpc_server.cc:4819] Started GRPCInferenceService at 0.0.0.0:8001
I0208 09:16:56.274361 1 http_server.cc:3477] Started HTTPService at 0.0.0.0:8000
I0208 09:16:56.316739 1 http_server.cc:184] Started Metrics Service at 0.0.0.0:8002
```

3. Open another terminal and run the `tritonclient` bash script that runs a python script that sends a test request to `tritonserver` started in point 2. The bash script will first need to pull a custom docker container with python 3.9 and `tritonclient`:
`$ cd /tmp/tis-dbg-20230207 && ./run-tritonclient-test.sh`

Note: If the client failed to connect to the server (returning `Failed to connect to remote host: Connection refused` error), you may need to change server IP address in the python script to the value currently used by the server (and displayed by the test script). For example, if you get the connection error message and see that `"IPAddress": "172.17.0.3"`, edit `tritonclient-script.py` and change `triton_host = '172.17.0.2'` to `triton_host = '172.17.0.3'` and re-run the test.

4. Server error message reporting the segmentation fault, complete with stack trace should appear in the first terminal, which displays `docker logs` from the `tritonserver` container:
```
Signal (11) received.
 0# 0x000055AEF32C0459 in tritonserver
 1# 0x00007FCE1AE99090 in /lib/x86_64-linux-gnu/libc.so.6
 2# 0x00007FCE1AFE1733 in /lib/x86_64-linux-gnu/libc.so.6
 3# treelite::gtil::Predict(treelite::Model const*, float const*, unsigned long, float*, int, bool) in /opt/tritonserver/backends/fil/libtriton_fil.so
 4# triton::backend::fil::TreeliteModel::predict(triton::backend::rapids::Buffer<float>&, triton::backend::rapids::Buffer<float const> const&, unsigned long, bool) const in /opt/tritonserver/backends/fil/libtriton_fil.so
 5# triton::backend::fil::RapidsModel::predict(triton::backend::rapids::Batch&) const in /opt/tritonserver/backends/fil/libtriton_fil.so
 6# auto* triton::backend::rapids::triton_api::execute<triton::backend::rapids::TritonModelState<triton::backend::fil::RapidsSharedState>, triton::backend::rapids::ModelInstanceState<triton::backend::fil::RapidsModel, triton::backend::fil::RapidsSharedState> >(TRITONBACKEND_ModelInstance*, TRITONBACKEND_Request**, unsigned long) in /opt/tritonserver/backends/fil/libtriton_fil.so
 7# 0x00007FCE1B74F49A in /opt/tritonserver/bin/../lib/libtritonserver.so
 8# 0x00007FCE1B74FE07 in /opt/tritonserver/bin/../lib/libtritonserver.so
 9# 0x00007FCE1B823D81 in /opt/tritonserver/bin/../lib/libtritonserver.so
10# 0x00007FCE1B749987 in /opt/tritonserver/bin/../lib/libtritonserver.so
11# 0x00007FCE1B28ADE4 in /lib/x86_64-linux-gnu/libstdc++.so.6
12# 0x00007FCE1C602609 in /lib/x86_64-linux-gnu/libpthread.so.0
13# clone in /lib/x86_64-linux-gnu/libc.so.6

```

**Expected behavior**
The test request should succeed and probability predictions from the model should be returned by both gRPC and HTTP/REST APIs.

**Comment by rmccorm4** [comment]
@wphicks can you help check if this is a FIL backend specific issue?

**Comment by wphicks** [comment]
Thanks for reporting this, @mirekphd. Currently, the FIL backend does not support a max_batch_size of 0. I've created three issues based on that:

https://github.com/triton-inference-server/fil_backend/issues/336
https://github.com/triton-inference-server/fil_backend/issues/337
https://github.com/triton-inference-server/fil_backend/issues/338

Supporting a max_batch_size of 0 may not be super high priority, but we definitely want to eliminate the segfault and make sure that this behavior is clearly documented. Thanks for all the good info!

**Comment by mirekphd** [comment]
Thank you for taking over the issue! But since are you have determined that the problem is caused / restricted to `max_batch_size` of 0, could you please specify what need to be modified / done to obtain correct prediction in this test setup? I've tried increasing to 1, but that does not generate prediction either, resulting in this error message:

**Comment by mirekphd** [comment]
Thank you @wphicks for your help! I was suspecting the incorrect input array dimensions were to blame (as confirmed by your [fix here](https://github.com/mirekphd/tis-dbg-20230207/pull/1/commits/84a54a78ba92e9742b109ca6bef2abb584bed180#diff-4c7666a4af232c7ffb5bcfcacb9121823b1d4d217f26b39ff333a88e3054353dL68-L69)), but arguably the above error message would be more helpful without the *less* or equal sign, which suggests the user passed *too much* of something (data, dimensions) rather than actually too *little*. Ideally if Triton spoke plain English to me, like "The input array received is missing one extra dimension needed for batching (required even in the special case of batch size of 1)".

The [FAQ notebook](https://nbviewer.org/github/triton-inference-server/fil_backend/blob/main/notebooks/faq/FAQs.ipynb) is fantastic!

**Comment by wphicks** [comment]
Yep, I agree that the error message here could be substantially improved. I'll have a little chat with the Triton core team and see what their thoughts are on the best way to make that happen.

Glad the notebook is helpful! :smile:
