### ISSUE TITLE
dynamic batch not work

### ISSUE THREAD

**Issue by hnsywangxin** [triton-inference-server/server#5334]
when  I used dynamic batch, The result is an error：failed to split the output tensor 'output' in responses: expected batch size of atleast 2 in model output, got 1
 
<img width="1516" alt="image" src="https://user-images.githubusercontent.com/18531174/217523644-e4afa80e-af78-4b80-b21f-8b5cf046d89d.png">

if I used concurrency=1, the result is right,as shown below：
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/18531174/217523740-2207ee1e-49a3-4cd5-ae22-b9cfacc2711c.png">
From the tips，the order of batch and channel is reversed, but I don't know how to change the order
my code as shown below:
<img width="995" alt="image" src="https://user-images.githubusercontent.com/18531174/217524303-5ef50938-b207-4ab1-9b12-fb2c338aa9f2.png">

my config file as shown below:
<img width="419" alt="image" src="https://user-images.githubusercontent.com/18531174/217524413-d6ea8d92-ea4c-4978-9767-3c440ace2280.png">
I hope to get answers from everyone， thank you very much

**Comment by dyastremsky** [comment]
It looks like the way you're manually batching your inputs and outputs is the cause of the error. See [this code](https://github.com/triton-inference-server/server/blob/2296270ab5c9b22abd7b37f2edbd8348734ac0c0/qa/L0_libtorch_shared_weights/libtorch_shared_weights_test.py#L52-L66) for an example of how to do it.

Also note that the dynamic batching portion is actually unrelated to this code. The dynamic batcher takes the requests you send < max_batch_size and batches them for you on the server scheduling side, so you don't need to do anything for that. For example, if the max_batch_size is 8 and you send three requests of size 2, 2, and 4 in the specified time window, the batcher will dynamically batch them into one request of size 8 for efficiency then return the results appropiately (to the requests corresponding to the 2, 2, and 4 sizes).

**Comment by hnsywangxin** [comment]
> It looks like the way you're manually batching your inputs and outputs is the cause of the error. See [this code](https://github.com/triton-inference-server/server/blob/2296270ab5c9b22abd7b37f2edbd8348734ac0c0/qa/L0_libtorch_shared_weights/libtorch_shared_weights_test.py#L52-L66) for an example of how to do it.
> 
> Also note that the dynamic batching portion is actually unrelated to this code. The dynamic batcher takes the requests you send < max_batch_size and batches them for you on the server scheduling side, so you don't need to do anything for that. For example, if the max_batch_size is 8 and you send three requests of size 2, 2, and 4 in the specified time window, the batcher will dynamically batch them into one request of size 8 for efficiency then return the results appropiately (to the requests corresponding to the 2, 2, and 4 sizes).

thank you @dyastremsky , you are right, I am manually batching my inputs and outputs，I want to test the efficiency of dynamic batch，I used your code ，but the error is same, I thank the reason is that my model output  tensor batch dim is axes=1 not axes=0,but triton need batch axes=0 , the error is:
my code is:
`triton_client = httpclient.InferenceServerClient(url='127.0.0.1:8000', concurrency=4)
    image, w, h = load_image(content_path)
    print("input: ", w, h)

    input_datas = []
    async_requests = []
    now = time.time()
    for i in range(4):
        input_datas.append(image)
        inputs = [httpclient.InferInput('input', image.shape, 'FP32')]
        inputs[0].set_data_from_numpy(image, binary_data=True)
        async_requests.append(
            triton_client.async_infer(model_name="tidiness",
                                      inputs=inputs, model_version="1"))
    for async_request in async_requests:
         result = async_request.get_result()
         print(result.get_response())
`
Thank you again

**Comment by dyastremsky** [comment]
My pleasure. That's correct... Triton can only batch on the first axis (axis 0). Thanks for taking the time to update me and share your results.

**Comment by hnsywangxin** [comment]
@dyastremsky So I can only change the batch dimension of the model？my onnx model output shape is : `{output [dtype=int64, shape=(1, 'batch', 'height', 'width')]}`
Can you give me some good advice?
Thank you very much!

**Comment by hnsywangxin** [comment]
I have solved it , my onnx convert code exists bug,
