### ISSUE TITLE
Perf_client reporting different requests per second depending on network

### ISSUE THREAD

**Issue by ricard-borras-veriff** [triton-inference-server/server#5335]
**Description**
When running perf_client on a corporate server, I get very different requests per second measurements if I run it from home or my office.

**Triton Information**
22.12

**Are you using the Triton container or did you build it yourself?**

Triton container

**To Reproduce**

Deploy a onnx model on a corporate server and spin up a docker container in dev machine:

`docker run -it --rm --net=host nvcr.io/nvidia/tritonserver:22.12-py3-sdk
`
In the docker machine run:

`perf_client -u https://<server_url> -m <model_name> --concurrency-range 10 --measurement-interval 30000 --async -v --percentile 95`

**Expected behavior**

Requests per second should be the same when I run this from home or from the office, but I get 10 requests / second when running from the office and 1 request / second when running from home

I am aware of other [similiar issue](https://github.com/triton-inference-server/server/issues/3599), but raising concurrency as exposed there does not help

Thanks!

**Comment by rmccorm4** [comment]
Hi @ricard-borras-veriff,

Going off of this example result from perf_analyzer via HTTP:
```
Request concurrency: 1
  Client: 
    Request count: 31877
    Throughput: 1770.14 infer/sec
    Avg latency: 563 usec (standard deviation 260 usec)
    p50 latency: 541 usec
    p90 latency: 702 usec
    p95 latency: 773 usec
    p99 latency: 933 usec
    Avg HTTP time: 556 usec (send/recv 101 usec + response wait 455 usec)
  Server: 
    Inference count: 31878
    Execution count: 31878
    Successful request count: 31878
    Avg request latency: 250 usec (overhead 9 usec + queue 23 usec + compute input 15 usec + compute infer 162 usec + compute output 41 usec)

Inferences/Second vs. Client Average Batch Latency
Concurrency: 1, throughput: 1770.14 infer/sec, latency 563 usec
```

If sending requests to a Triton server over the network via HTTP/GRPC, perf analyzer results will include network overhead in the overall throughput and latency results at the bottom, as they are end-to-end calculations from the client perspective:
```
  Client: 
    Request count: 31877
    Throughput: 1770.14 infer/sec    <----
    Avg latency: 563 usec (standard deviation 260 usec)     <----
    ...
Inferences/Second vs. Client Average Batch Latency
Concurrency: 1, throughput: 1770.14 infer/sec, latency 563 usec   <----
```

If you wanted to compare the server-side latency only when sending requests from different clients, you should only be looking at this line:
```
  Server:
    Avg request latency: 250 usec (overhead 9 usec + queue 23 usec + compute input 15 usec + compute infer 162 usec + compute output 41 usec)
```
And furthermore, the `compute` related stats in the breakdown would be the most expected to remain consistent regardless of where the requests are coming from. The overhead and queue times can vary based on rate of requests coming in, which could be affected by differences in network communication.

**Comment by ricard-borras-veriff** [comment]
Hi @rmccorm4 ,

thanks for the clarification, got it!
