### ISSUE TITLE
pytorch(torchscript) custom classes

### ISSUE THREAD

**Issue by kjtaed** [triton-inference-server/server#5337]
There is a way to use pytorch custom operations in Triton.
https://github.com/triton-inference-server/server/blob/main/docs/user_guide/custom_operations.md

I couldn't find a way to use pytorch custom classes in Triton.
Is there a way?

I wanna use libth_transformer.so(FasterTransformer).

$ LD_PRELOAD=/opt/fastertransformer/lib/libth_transformer.so tritonserver --model-repository=/models
tritonserver: symbol lookup error: /opt/fastertransformer/lib/libth_transformer.so: undefined symbol: PyInstanceMethod_Type

**Comment by guptap11** [comment]
@kjtaed hey, I am running into a similar issue , can you share some insight on resolution ?

**Comment by zjd1988** [comment]
@guptap11 @kjtaed Have you guys solved this problem？

**Comment by zjd1988** [comment]
@guptap11 @kjtaed my solution， and verified
![企业微信截图_17143521806546](https://github.com/triton-inference-server/server/assets/7134030/bb156c40-dc6d-4e8e-9676-b76ea4ace498)
