### ISSUE TITLE
Need for help! Is that my configuration wrong?

### ISSUE THREAD

**Issue by RosterMouch** [triton-inference-server/server#5338]
I have set the labels of my yolov5 tensorrt model like this :
```toml
output[
  {
    name: "output0",
    data_type: TYPE_FP32
    dims: [ 25200,9 ]
    label_filename: "labels.txt"
  }
]
```
My labels.txt content:
```
LISTENING
PLAYING
SLEEPING
YAWN

```
And i write my Python client code like this:
```python
    grpcclient.InferRequestedOutput('output0',class_count=4), 
    ]
    inputs = [grpcclient.InferInput('images', img.shape, 'FP32')] 
    inputs[0].set_data_from_numpy(img) 
    result = triton_client.infer( 
    'action_onnx', 
    inputs, 
    request_id=str('1'),
    model_version='', 
    outputs=outputs) 
    output_array = result.as_numpy('output0')
    print(output_array)
```
But it returns a Numpy array like this:
```python
[b'680.980896:226010' b'657.414368:224994' b'654.781250:225830'
 b'652.398132:225174']
```
So what the hack is that?Is my configuration wrong or this issuse is caused by yolov5?

**Comment by rmccorm4** [comment]
Hi @RosterMouch, the configuration here seems to be mismatched with the labels. For starters, the classification/label_filename feature expect a flat array in the output where each index indicates a probability, and it will simply map the index of each probability to the index of each label in the label file. More description here: https://github.com/triton-inference-server/server/issues/1501#issuecomment-635569951

It looks like you've defined an output of shape `[25200, 9]`, which I'm inferring means there are either 25200 labels or 9 labels, and there should be some extra step that flattens this array in the final output, or similar. Unless you are using explicit batching (`max_batch_size: 0`) and the 25200 is actually the batch size, but it doesn't appear so from the example above.

If we were to assume there are supposed to be 9 labels, Triton would roughly expect an output of shape `[9]` or `[batch_size, 9]`, and that your labels file would also contain 9 lines/labels to map to. Your label example above only has 4 labels, which doesn't align with the output shape.

CC @GuanLuo to correct me if this is wrong

**Comment by RosterMouch** [comment]
> Hi @RosterMouch, the configuration here seems to be mismatched with the labels. For starters, the classification/label_filename feature expect a flat array in the output where each index indicates a probability, and it will simply map the index of each probability to the index of each label in the label file. More description here: [#1501 (comment)](https://github.com/triton-inference-server/server/issues/1501#issuecomment-635569951)
> 
> It looks like you've defined an output of shape `[25200, 9]`, which I'm inferring means there are either 25200 labels or 9 labels, and there should be some extra step that flattens this array in the final output, or similar. Unless you are using explicit batching (`max_batch_size: 0`) and the 25200 is actually the batch size, but it doesn't appear so from the example above.
> 
> If we were to assume there are supposed to be 9 labels, Triton would roughly expect an output of shape `[9]` or `[batch_size, 9]`, and that your labels file would also contain 9 lines/labels to map to. Your label example above only has 4 labels, which doesn't align with the output shape.
> 
> CC @GuanLuo to correct me if this is wrong

Hi sir@rmccorm4,sorry late for this replying cause i`m writing my paper this days,i`m searching a lots of NVIDIA document yet.
Yeah,the output size `[25200,9]` is speicified by Yolo team,it is possbile like you said it`s to to be flatten it or something else and i thinking i need this pipeline for that,cause in my real experiment there just 4 classes need to be detect,i also post this issuse to Yolo community but they still not replied.
I`m trying using torch.hub component to load my INT8 quantizationed TensorRT model and use Python FastAPI framwork to make a AI inference service.so i gave up the "Triton Solution" after my match finished.
Thanks a lot for replying me sir,hug you.😊

RosterMouch

**Comment by RosterMouch** [comment]
Close this issue due to no longer need for help.
