### ISSUE TITLE
OpenVINO Backend 2022.3 support

### ISSUE THREAD

**Issue by riZZZhik** [triton-inference-server/server#5343]
Hello,

Currently [triton-inference-server/openvino_backend](https://github.com/triton-inference-server/openvino_backend) is based on OpenVINO 2022.01
When will official Triton Container support 2022.3 or later OV backend?

Based on Changelog ([2022.02](https://github.com/openvinotoolkit/openvino/releases/tag/2022.2.0), [2022.03](https://github.com/openvinotoolkit/openvino/releases/tag/2022.3.0)) I assume that update won't cause any issues

Thanks!

**Comment by nv-kmcgill53** [comment]
cc: @Christina-Young-NVIDIA @dzier

**Comment by riZZZhik** [comment]
Any updates about this issue?

**Comment by GuanLuo** [comment]
@tanmayv25 can you estimate this effort?

**Comment by tanmayv25** [comment]
The standalone openvino version in OV backend is dependent upon the version of openvino released in ORT version being shipped with Triton. See here for more information: https://github.com/triton-inference-server/server/blob/main/build.py#L64-L67

The actual update is not expected to be a lot of work.

**Comment by tanmayv25** [comment]
@pranavsharma  Does the latest onnxruntime release in Triton ORT  v1.14.1 support openvio 2022.3 ? If yes, then we can try upgrading the openvino version in Triton.

**Comment by pranavsharma** [comment]
> @pranavsharma Does the latest onnxruntime release in Triton ORT v1.14.1 support openvio 2022.3 ? If yes, then we can try upgrading the openvino version in Triton.

yes. https://onnxruntime.ai/docs/execution-providers/OpenVINO-ExecutionProvider.html#requirements

**Comment by siyuch-fdu** [comment]
We also need the 2022.3 version of openvino_backend, and hope that the official version can be implemented as soon as possible, thank you very much!

**Comment by nv-kmcgill53** [comment]
CC: @nnshah1

**Comment by nikolsky** [comment]
It would be great to see this feature in the future releases.
We have to use OpenVINO Model Server instead of Triton without it.

**Comment by pranavsharma** [comment]
The latest version of ORT uses 2023. Does that work? See https://onnxruntime.ai/docs/execution-providers/OpenVINO-ExecutionProvider.html#requirements

**Comment by riZZZhik** [comment]
@pranavsharma it supports OpenVINO 2023, but uses the one that is installed in triton server \
Currently it is 2022.1 as in https://github.com/triton-inference-server/openvino_backend

**Comment by nnshah1** [comment]
Quick update - the team is currently investigating the upgrade.

**Comment by riZZZhik** [comment]
@kthui Thanks! ❤️❤️❤️
