### ISSUE TITLE
Unable to connect to the triton service!

### ISSUE THREAD

**Issue by hh123445** [triton-inference-server/server#5346]
**Description**
I used the steps in the Quickstart document to test whether the triton sample program can run normally, but found that I could not connect to the triton service.

**Triton Information**
I use Docker to install triton, and the installed image version is 22.02. The installation command is as follows:
`sudo docker pull nvcr.io/nvidia/tritonserver:22.02-py3`

**To Reproduce**
After installing triton, I ran the following command according to the steps in the Quickstart document:
`./fetch_models.sh`
`sudo docker run --gpus=1 --rm -p8000:8000 -p8001:8001 -p8002:8002 -v/mypath/docs/examples/model_repository:/models nvcr.io/nvidia/tritonserver:22.02-py3 tritonserver --model-repository=/models`

The service program starts normally
![image](https://user-images.githubusercontent.com/90760124/218292392-e610a947-c292-4b83-a700-ec6ef1640009.png)
![image](https://user-images.githubusercontent.com/90760124/218292406-c6b68fff-75cd-4909-b00e-f18e2fad70f5.png)

But I encountered a problem when trying to connect to the triton service from another terminal
`curl -v localhost:8000/v2/health/ready`
![image](https://user-images.githubusercontent.com/90760124/218292474-e164da92-2d05-4fa6-a2fc-a234b5f446f2.png)

**Expected behavior**
It is mentioned in the Quickstart document that the following results should be displayed for the correct connection.
![image](https://user-images.githubusercontent.com/90760124/218292493-664b2778-6624-4e1f-8f2b-3090b34508ce.png)

**Comment by dyastremsky** [comment]
Thanks for catching this! It looks like you need to add a `--net=host` flag to the server container so that your SDK container can communicate with it.

The full Docker run command for the server:
`sudo docker run --gpus=1 --rm -p8000:8000 -p8001:8001 -p8002:8002 -v/mypath/docs/examples/model_repository:/models --net=host nvcr.io/nvidia/tritonserver:22.02-py3 tritonserver --model-repository=/models`

**Comment by hh123445** [comment]
> 感谢您抓住这个！看起来您需要`--net=host`向服务器容器添加一个标志，以便您的 SDK 容器可以与其通信。
> 
> 服务器的完整 Docker 运行命令： `sudo docker run --gpus=1 --rm -p8000:8000 -p8001:8001 -p8002:8002 -v/mypath/docs/examples/model_repository:/models --net=host nvcr.io/nvidia/tritonserver:22.02-py3 tritonserver --model-repository=/models`

It can be used normally. Thank you very much!
