### ISSUE TITLE
slow when I use  triton torchscript model to infer

### ISSUE THREAD

**Issue by stabling** [triton-inference-server/server#5352]
I have a problem.When I only use torchscript model to infer, only use 0.6s.But I use triton to infer,infer time is 30s.It is too slow when I use triton,can you help me get the reason of this?

**Comment by nv-kmcgill53** [comment]
Hi @stabling, we will need more information in order to help you. Please use the [Issue Template](https://github.com/triton-inference-server/server/blob/main/.github/ISSUE_TEMPLATE/bug_report.md) to fill out your request. Thanks!
