### ISSUE TITLE
How to get the dependencies between backends using BLS

### ISSUE THREAD

**Issue by AlexXi19** [triton-inference-server/server#5356]
I have a few python backends that use BLS and call other backends via `triton_python_backend_utils`. Is there a way to get the model dependency information from this?

**Comment by nv-kmcgill53** [comment]
Hi @AlexXi19, I would like further clarification of this question. Is your question asking whether you can get the models which the BLS calls, or the dependency of the models called?

The former is not possible unless BLS is logging what model it's calling. The latter would be the model configuration of the model called; normal models have just the one model while ensemble models have the dependencies listed in the config.

**Comment by AlexXi19** [comment]
Both? I guess it's not possible, the best solution to this might be to parse the python backend to see which other backend it calls. Thanks for answering!
