### ISSUE TITLE
Missing default tag (`latest`) in `nvcr.io/nvidia/tritonserver` container

### ISSUE THREAD

**Issue by mirekphd** [triton-inference-server/server#5359]
**Is your feature request related to a problem? Please describe.**
It is not possible to create future-proof (auto-updating) containerized setups. Trying to pull the `tritonserver` docker image without explicitly stating the tag results in an error:
```
$ docker pull nvcr.io/nvidia/tritonserver
Using default tag: latest
Error response from daemon: manifest for nvcr.io/nvidia/tritonserver:latest not found: manifest unknown: manifest unknown
```

**Describe the solution you'd like**
Please add default tag (`latest`) to your `nvcr.io/nvidia/tritonserver` container.

**Comment by nv-kmcgill53** [comment]
CC: @mc-nv

**Comment by Tabrizian** [comment]
We don't release the latest tag in Triton NGC containers. You should use the respective release version in your tag.
