### ISSUE TITLE
Customize-triton-container using compose.py failed

### ISSUE THREAD

**Issue by leemengwei** [triton-inference-server/server#5364]
**Description**
Customization build failed using compose.py

**Triton Information**
23.01. 
Git clone master (today).

I'm trying to build a custom container with compose.py

**To Reproduce**
I'm following https://github.com/triton-inference-server/server/blob/main/docs/customization_guide/compose.md#customize-triton-container
1. git clone https://github.com/triton-inference-server/server.git
2. python3 compose.py --backend tensorrt --backend python --container-version 23.01  (I've prune the dangling images with 'docker system prune' every time before I try to build to avoid possible cache problem)

**Expected behavior**
Docker build should be successful.
Yet instead it shows:
![image](https://user-images.githubusercontent.com/17986725/218915414-8ef95f9d-a6d2-4ded-882d-6ce95a54977c.png)

Meanwhile, I'm not sure if the compose methods suits me for my purpose of 'Using latest triton server version with previous version of some-backend?' I guess `python3 compose.py --backend python --backend tensorrt  --image min,nvcr.io/nvidia/tritonserver:23.01-py3-min --image full,nvcr.io/nvidia/tritonserver:22.02-py3` will fufill my purpose? Yet what if I want newest server(23.01) with python-backend form 22.01 and tensorrt-backend form 22.02 ?

**Comment by nv-kmcgill53** [comment]
Hi @leemengwei, I was unable to reproduce this issue on my machine using the [r23.01](https://github.com/triton-inference-server/server/tree/r23.01) branch of triton, invoking `python3 compose.py --backend tensorrt --backend python --container-version 23.01`. The HTTP code 100 is interesting as it wants the request to continue requesting. Is this consistent behavior?

>Yet what if I want newest server(23.01) with python-backend form 22.01 and tensorrt-backend form 22.02 ?

In general we don't suggest this as Triton only guarantees compatibility for the versions within a single release. We don't require backwards compatibility and, as such, ask that users use the same versions across all triton components. If you would like the newer features of recent releases, upgrade everything to the newest version.

**Comment by leemengwei** [comment]
@nv-kmcgill53 
Thanks for reply. 
>Is this consistent behavior?
Yes, tried again on my PC and other devices including a x86 GPU server and an arm jetson-NX, neither make it through. It can't be network restriction as I've tried using proxy.
Finally I get it throught with modifying how dockerfile.compose was formed. I modified build.py:
```
def install_dcgm_libraries(dcgm_version, target_machine):
    if dcgm_version == '':
        fail(
            'unable to determine default repo-tag, DCGM version not known for {}'
            .format(FLAGS.version))
        return ''
    else:
        if target_machine == 'aarch64':
            return '''
ENV DCGM_VERSION {}
# Install DCGM. Steps from https://developer.nvidia.com/dcgm#Downloads
RUN wget -O /tmp/cuda-keyring.deb \
    https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/sbsa/cuda-keyring_1.0-1_all.deb \
    && apt install /tmp/cuda-keyring.deb && rm /tmp/cuda-keyring.deb && \
    apt-get update && apt-get install -y datacenter-gpu-manager=1:{}
'''.format(dcgm_version, dcgm_version)
        else:
            return '''
ENV DCGM_VERSION {}
# Install DCGM. Steps from https://developer.nvidia.com/dcgm#Downloads
RUN wget -O /tmp/cuda-keyring.deb \
    https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.0-1_all.deb \
    && apt install /tmp/cuda-keyring.deb && rm /tmp/cuda-keyring.deb && \
    apt-get update && apt-get install -y datacenter-gpu-manager=1:{}
'''.format(dcgm_version, dcgm_version)
```

> If you would like the newer features of recent releases, upgrade everything to the newest version
However I think it would be more thoughtful to take backwards compatibility into consideration under scope of TRTIS (though I know it will brings amount of complexity with it), as users may serve dozens of their models with, say,  tensorrt backend of a specific version), converting them all over again just sounds painful to me :.(
