### ISSUE TITLE
Dumping Logs of Triton Inference Server for tools like Grafana Loki

### ISSUE THREAD

**Issue by ApoorveK** [triton-inference-server/server#5369]
**Description**
Is there any way to dump the logs of triton inference server container, which can be used for observability tools like Grafana Loki (or any other tool) , when the container being started in log-verbose mode (apart from default metrics which can be accessed through default 8002 port of container)

**Triton Information**
22.10

Are you using the Triton container or did you build it yourself?
Following dockerfile:
```
FROM tritonserver:latest
RUN apt-get update -y
RUN pip install tensorflow==2.7.0
RUN pip install transformers==2.11.0
RUN pip install tritonclient
RUN pip install tritonclient[all]
RUN pip install soundfile
# RUN pip install torch
RUN pip install pydub
RUN pip install pandas
RUN apt-get install libsndfile1 -y
RUN apt install ffmpeg -y

ENV PYTHONIOENCODING=utf-8
```

**To Reproduce**
Starting the Triton container in normal way, 
```
docker run --shm-size=2g --gpus all --rm --name trialtts -p8003:8000 -p8004:8001 -p8005:8002 \
-v $(pwd)/model_repo_triton:/models customtritonimage:latest tritonserver \
--model-repository=/models --model-control-mode=poll --log-verbose=3 --log-info=1 --log-warning=1 --log-error=1
```
and using 8002 port with prometheus, which later being exposed to grafana

Models used: Default models from examples

**Comment by kthui** [comment]
cc @GuanLuo @tanmayv25

**Comment by ApoorveK** [comment]
@tanmayv25 Actually i am planning to include some of these third party tools inside Triton docker images (so that directly these logs as an exposed port for Triton Container) maybe you can suggest some of these 3rd party tools for the same use case

**Comment by dyastremsky** [comment]
It depends on your use case and needs. We don't actively use, monitor, or test them ourselves, so we can't provide any endorsements of specific 3rd party tools. Since the original question was answered, I'm going to close out this issue.

If you'd like to get a sense of what other Triton users use for extending logging, you may want to start a discussion in the Discussions tab.
