### ISSUE TITLE
Unable to create S3 filesystem client. Check account credentials. 

### ISSUE THREAD

**Issue by okyspace** [triton-inference-server/server#5371]
**Description**
When starting Triton container in k8s, got this error: 
"unable to create S3 filesystem client. Check account credentials. "
1. The credentials are correct as they are used to access the S3 using minio client. 
2. AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_DEFAULT_REGION are in the environment. 

**Triton Information**
What version of Triton are you using? 22.12-py3

Are you using the Triton container or did you build it yourself? From Triton. 

**To Reproduce**
Steps to reproduce the behavior.
Start triton using k8s_onprem helm chart. 

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well). 
NA.

**Expected behavior**
Able to connect to S3.

**Comment by nv-kmcgill53** [comment]
cc: @kthui

**Comment by JochemTSR** [comment]
The error message `Unable to create S3 filesystem client. Check account credentials` can be a bit misleading, apparently. For me to the issue was that I incorrectly configured the custom CA certificate I use to  authenticate my local S3 instance, so a https connection could not me made. 

It might be worth checking if your S3 is even reachable from inside the container (e.g. through `wget`) to rule out such issues.

**Comment by GuanLuo** [comment]
@kthui do you know if that is related to the other similar S3 issues?

**Comment by okyspace** [comment]
Thanks @JochemTSR, I have tested with a non http route to my s3 and it works. 
May I know how to properly mount the cert to make https work?

I have tried 
1. adding to /etc/ssl/certs/cert.crt and export REQUESTS_CA_BUNDLE=/etc/ssl/certs/cert.crt
2. adding cert to /usr/share/local/ca-certificates and done update-ca-certificates, the result show 1 cert added. And export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt. 

Both methods did not work. Able to advise? Thanks

**Comment by okyspace** [comment]
Tested again and SN2 works.
