### ISSUE TITLE
Documentation for creating small versions of Triton Docker images is not sufficient

### ISSUE THREAD

**Issue by ApoorveK** [triton-inference-server/server#5376]
**Description**
Currently, if you try to build docker images from source, the minimum size which you can get is 8.81 GB (with tf2, onnx-runtime, python backend)
 
**Triton Information**
22.10

**Are you using the Triton container or did you build it yourself?**
Version builded from source

Can we decrease the Triton Docker image size, if we can then what is actual process. There is some documentation available which helps in making custom Triton docker image, but not specifically for making a smaller alternative.

**Comment by krishung5** [comment]
Hi @ApoorveK, could you elaborate more on the meaning of "smaller alternative"?

**Comment by ApoorveK** [comment]
@krishung5 smaller alternatives here referred to smaller version of Triton Docker images (around 3-4 gb or even lesser) if it's possible, because these images can't be used on some memory restricted hardwares (when the custom Triton images have even more size due to use-case specific dependencies).

**Comment by kthui** [comment]
CC @GuanLuo @tanmayv25 for any thought on reducing the custom build docker image size.

**Comment by tanmayv25** [comment]
@ApoorveK If you don't require GPU support, you can build Triton without cuda support. See here:
https://github.com/triton-inference-server/server/blob/main/docs/customization_guide/build.md#cpu-only-build

It should give you sufficiently small image 3-4 GB. Unfortunately, the cuda bits occupy large portions of our container image size.

**Comment by Jackiexiao** [comment]
if you build triton without gpu with only onnx + python, image size can reduce to around 400MB

**Comment by tanmayv25** [comment]
Closing the issue as we already document how to create minimal containers.
