### ISSUE TITLE
Enabling triton client to build with minial set to rid needless dependencies such as zlib and re2

### ISSUE THREAD

**Issue by RandySheriffH** [triton-inference-server/server#5378]
Thanks to triton we announced a preview feature for onnxruntime on azure:
https://pypi.org/project/onnxruntime-azure/
However, on windows triton client introduced external library dependencies on zlib and re2, which complicated deployment even when we are not utilizing compression and regex matching.
Hence, is it possible for the triton client to provide some build options (e.g. only include the thinnest core functions only) to make it fully standalone?
Or - could the triton client static-link to zlib and re2 as part of its binary (by a build option)?

**Comment by nv-kmcgill53** [comment]
CC: @jbkyang-nvi

**Comment by jbkyang-nvi** [comment]
Hi @RandySheriffH how are you building the client? RE2 should be a dependency for the server. We use zlib for the httpclient though. If you want to not include it, you can turn `TRITON_ENABLE_CC_HTTP` to off.

**Comment by RandySheriffH** [comment]
@jbkyang-nvi : re2 is also a dep for client as I can tell after build triton into our product, and "TRITON_ENABLE_CC_HTTP" is exactly what we need to build with ... can zlib be statically linked somehow?

**Comment by jbkyang-nvi** [comment]
@RandySheriffH Do you need grpc? It looks like RE2 is a dependency for GRPC and we cannot remove it from our client build. We can work on disabling Zlib though

**Comment by RandySheriffH** [comment]
> @RandySheriffH Do you need grpc? It looks like RE2 is a dependency for GRPC and we cannot remove it from our client build. We can work on disabling Zlib though

Thanks for asking - so far we don't need that.

**Comment by RandySheriffH** [comment]
I don't think https://github.com/triton-inference-server/client/pull/156 solve the problem.

**Comment by pranavsharma** [comment]
We're using triton_client in ORT to talk to AzureML's Triton server. Expecting users of ORT to install zlib is quite an annoyance. Can we link with zlib statically or in the worst case provide an option to disable usage of zlib in the triton client build?

**Comment by jbkyang-nvi** [comment]
@RandySheriffH @pranavsharma  we're working on this. Can you try this PR? You just need to add -DTRITON_ZLIB_USE_STATIC_LIBS=ON when you build. The problem is that zlib is needed as a part of how we use curl. 
We currently cannot need to use the static version of zlib `libz.a` in the build but the linking is controlled by [curl](https://github.com/curl/curl/blob/master/CMakeLists.txt#L503-L520). 

I have tested that if the build container itself does not include `libz.so`, curl will link the static library and the examples will work. 
Something like:
```
cmake -DCMAKE_INSTALL_PREFIX=/workspace/install           
-DTRITON_VERSION=`cat /workspace/TRITON_VERSION`          
-DTRITON_ENABLE_CC_HTTP=ON 
-DTRITON_ENABLE_CC_GRPC=OFF           
-DTRITON_ENABLE_PYTHON_HTTP=ON 
-DTRITON_ENABLE_PYTHON_GRPC=OFF          
 -DTRITON_ZLIB_USE_STATIC_LIBS=ON /workspace/client
 ... other cmake params```

**Comment by pranavsharma** [comment]
Thanks! We'll try and get back to you.

**Comment by RandySheriffH** [comment]
Testing with a unit test program ... one question - where the static zlib.lib is fetched to local? 
If remember correctly, triton relies on vcpkg to download all the deps, there the zlib downloaded is a dll.

**Comment by RandySheriffH** [comment]
@jbkyang-nvi , seems dep on zlib still there:
![image](https://user-images.githubusercontent.com/48490400/236336417-4fffb0c6-b9a6-4891-9b02-29563f4628bb.png)
Do u have a chance to test windows?

**Comment by RandySheriffH** [comment]
maybe for windows, zlib-static needs to be installed by vcpkg?

**Comment by jbkyang-nvi** [comment]
@RandySheriffH thanks for getting back so fast. On Linux, I simply removed `/usr/lib/x86_64-linux-gnu/libz.so` from the path and the curl build succeeded by using `/usr/lib/x86_64-linux-gnu/libz.a`. I have not tested on an actual Windows machine yet however I was assuming it would work similarly.

[This article](https://devblogs.microsoft.com/cppblog/vcpkg-updates-static-linking-is-now-available/) suggests that static libraries are available with `-DVCPKG_TARGET_TRIPLET=x86-windows-static`. Will do more testing tomorrow to see if that helps

**Comment by RandySheriffH** [comment]
@jbkyang-nvi, it might not that consistent among windows and linux since for windows triton client installed deps by vcpkg, and link to installed deps by looking into vcpkg's package pool; for linux the search most likely occurs to /usr/lib, /usr/local/lib, or ~/local/...

**Comment by jbkyang-nvi** [comment]
@RandySheriffH the article linked above suggests that the static keyword on the triplets when building 
```
cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static
 -DCMAKE_TOOLCHAIN_FILE='/vcpkg/scripts/buildsystems/vcpkg.cmake' 
-DCMAKE_INSTALL_PREFIX=install
 -DTRITON_ENABLE_CC_GRPC=OFF 
-DTRITON_ENABLE_PYTHON_GRPC=OFF
 -DTRITON_ENABLE_GPU=OFF
-DTRITON_ENABLE_EXAMPLES=ON
 -DTRITON_ENABLE_TESTS=ON 
 -DTRITON_INCLUDE_ZLIB_IN_BUILD=OFF
```
note: I made a typo on the comment above. The flag is: TRITON_INCLUDE_ZLIB_IN_BUILD

**Comment by RandySheriffH** [comment]
@jbkyang-nvi : then do I need to install all vcpkg packages as static?

**Comment by RandySheriffH** [comment]
![image](https://user-images.githubusercontent.com/48490400/236357120-d7531359-051c-496e-a9ff-067a001d196e.png)

**Comment by RandySheriffH** [comment]
@jbkyang-nvi :above is the link error I got with suggested flags. 
In https://github.com/triton-inference-server/client/pull/309, there is no code change to if-def-out zlib calls?

**Comment by RandySheriffH** [comment]
FYI. here the code change to be made in c++ code:
https://github.com/triton-inference-server/client/pull/312

**Comment by jbkyang-nvi** [comment]
@RandySheriffH the changes in #309 is basically hiding changes in https://github.com/triton-inference-server/client/pull/156. It should not change how the client is built fundamentally since Triton has built without explicitly needing to link to zlib before.

`deflateInit2` should be included through the curl library

**Comment by RandySheriffH** [comment]
"deflateInit2 should be included through the curl library"
--no it's from zlib

**Comment by jbkyang-nvi** [comment]
> "deflateInit2 should be included through the curl library" --no it's from zlib

Correct. There are two places that zlib is included (from the linux build). One from curl and one from the include. Not sure why the windows build is different. 

Thanks for your input. Working on merging the two PRs together.

**Comment by jbkyang-nvi** [comment]
@RandySheriffH  https://github.com/triton-inference-server/client/pull/309 should be good to go. Can you confirm?

**Comment by RandySheriffH** [comment]
@jbkyang-nvi : it works! Now with -DTRITON_ENABLE_ZLIB=OFF the zlib dependency is gone.
