### ISSUE TITLE
Set the input data  takes so many time

### ISSUE THREAD

**Issue by 1124676457** [triton-inference-server/server#5386]
# Set the input data
        self.inputs[0].set_data_from_numpy(batched_image_data)
when i use the tritonclient.grpc, set the input data takes me so many time; about 25ms, this makes my reasoning speed extremely slow

**Comment by 1124676457** [comment]
@sublee @dougn @benfred @brightsparc please cat this

**Comment by kthui** [comment]
Hi, if this is a bug, can you please fill out a complete [bug report](https://github.com/triton-inference-server/server/issues/new?assignees=&labels=&template=bug_report.md&title=). If this is an enhancement, can you please fill out a complete [feature request](https://github.com/triton-inference-server/server/issues/new?assignees=&labels=&template=feature_request.md&title=)? We are not able to provide any assistance based on subjective descriptions.
