### ISSUE TITLE
Long queue time when preprocessing using the python backend

### ISSUE THREAD

**Issue by knwng** [triton-inference-server/server#5421]
Hi I'm using Triton to serve a swin transformer v2 model. Since there's some custom logic in the preprocessor, I use a python backend to run the python script, as following:
```python
import numpy as np
import json
import io

import triton_python_backend_utils as pb_utils

from PIL import Image
import torchvision.transforms as transforms
import torchvision.transforms.functional as F


class CropAndResize(object):
    def __init__(self, target_size=224):
        self.target_size = target_size

    def __call__(self, x):
        w, h = x.size
        x = F.center_crop(x, max(w, h))
        x = F.resize(x, self.target_size,
                     interpolation=transforms.InterpolationMode.BICUBIC)
        return x


class TritonPythonModel:
    def initialize(self, args):
        self.transform = transforms.Compose([
            CropAndResize(256),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                 std=[0.229, 0.224, 0.225])
        ])

        self.model_config = model_config = json.loads(args['model_config'])

        output0_config = pb_utils.get_output_config_by_name(
            model_config, "OUTPUT")

        self.output0_dtype = pb_utils.triton_string_to_numpy(
            output0_config['data_type'])

    def execute(self, requests):
        output0_dtype = self.output0_dtype
        responses = []

        for request in requests:
            in_0 = pb_utils.get_input_tensor_by_name(request, "INPUT")

            def image_loader(image_name):
                image = self.transform(image_name)
                # expand the dimension to nchw
                image = image.unsqueeze(0)
                return image

            img = in_0.as_numpy()

            image = Image.open(io.BytesIO(img.tobytes()))
            img_out = image_loader(image)
            img_out = np.array(img_out)

            out_tensor_0 = pb_utils.Tensor("OUTPUT",
                                           img_out.astype(output0_dtype))

            inference_response = pb_utils.InferenceResponse(
                output_tensors=[out_tensor_0])
            responses.append(inference_response)

        return responses

    def finalize(self):
        print('Cleaning up...')
```

The config.pbtxt is:
```protobuf
name: "preprocess"
backend: "python"
max_batch_size: 256
input [
{
    name: "INPUT"
    data_type: TYPE_UINT8
    dims: [ -1 ]
}
]

output [
{
    name: "OUTPUT"
    data_type: TYPE_FP32
    dims: [ 3, 256, 256 ]
}
]

instance_group [
    {
        count: 6
        kind: KIND_CPU
    }
]

version_policy: { all { }}
```

Then I use the perf_analyzer with 8 concurrencies to benchmark the service and the result is:
throughput: 12.3304 infer/sec, latency 637534 usec

The detailed latency:
Avg request latency: 634407 usec (overhead 23 usec + queue 153589 usec + compute input 542 usec + compute infer 479778 usec + compute output 475 usec)

You can see that the queue time(153589 usec) is quite long. And I noticed that during serving, the cpu occupation was extremely high(almost all the 96 logic cores are fully utilized). How can I optimize this? Thank you!

**Comment by knwng** [comment]
Hi @kthui, thx for the advice! I'll try the model analyzer and come back with a report.

Here's another update:

I've created a gunicorn + Flask server with the same preprocessing logic:
```python
import io
import json
import base64

import numpy as np
from PIL import Image
from flask import Flask, request, jsonify
import torchvision.transforms as transforms
import torchvision.transforms.functional as F

app = Flask(__name__)


class CropAndResize(object):
    def __init__(self, target_size=224):
        self.target_size = target_size

    def __call__(self, x):
        w, h = x.size
        x = F.center_crop(x, max(w, h))
        x = F.resize(x, self.target_size,
                     interpolation=transforms.InterpolationMode.BICUBIC)
        return x


transform = transforms.Compose([
    CropAndResize(256),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225])
])


def pil_process(data):
    img = Image.open(data)
    if len(img.size) == 2:
        img = img.convert("RGB")
    if img.mode != "RGB":
        img = img.convert("RGB")
    img = np.array(img)
    return img


@app.route('/', methods=["POST", "GET"])
def process():
    req = json.loads(request.data)

    def image_loader(image_name):
        image = transform(image_name)
        # expand the dimension to nchw
        image = image.unsqueeze(0)
        return image

    image = Image.open(io.BytesIO(base64.b64decode(req['data'])))
    img_out = image_loader(image)
    img_out = np.array(img_out)

    return jsonify({
        'result': img_out.tolist(),
    })
```

I saved the above script to file preprocess_server.py and started the server by `gunicorn --workers 6 --threads 80 --bind 127.0.0.1:8080 preprocess_server:app`. Then I invoked it using a thread pool with max_workers=20, which resulted in approxmately 36 QPS, 3 times the QPS achived by the triton server.

**Comment by dyastremsky** [comment]
Wouldn't a more equivalent comparison be to set the perf_analyzer concurrency value to >= 80? You can also increase throughput at the cost of latency by [setting a max batch delay](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/model_configuration.md#delayed-batching). I don't know how gunicorn does things, but you can also play around with different kinds of shared memory (e.g. `--shared-memory system` in perf_analyzer), using GPU instead of CPU, and changing the protocol used for communicating with perf_analyzer to C API if it's not currently. Some of these options are configurable in Model Analyzer if you use that to find the best configuration for your needs.

**Comment by knwng** [comment]
> Wouldn't a more equivalent comparison be to set the perf_analyzer concurrency value to >= 80?

Hi @dyastremsky , I tried to set the perf_analyzer concurrency to >=80, like 100, but the performance didn't change. Here's a report of one of the best configurations generated by model analyzer:
https://drive.google.com/file/d/1B8eIfzB7P20okqfmwPoyIRdML7t7chG6/view?usp=sharing

**Comment by knwng** [comment]
Hi, I just got another observation. Previously I did the benchmark on a [AMD EPYC 7643 CPU](https://www.amd.com/en/product/10926), where the QPS of gunicorn server was about 36 while the QPS of triton server was 12. But today I benchmarked on a [Intel Xeon Gold 5218 CPU](https://ark.intel.com/content/www/us/en/ark/products/192444/intel-xeon-gold-5218-processor-22m-cache-2-30-ghz.html), and the gunicorn's QPS was about 55 while triton's QPS was 44, which was much more close.

So I'm wondering are there some optimizations only available to Intel CPU? Do you have benchmark on AMD CPU? Thank you!

**Comment by Tabrizian** [comment]
@knwng I see that you are using pytorch in your Python model. Since PyTorch spawns many different threads it can lead to poor performance when multiple instances of the Python backend is created. Can you try setting the the torch thread count to 1 to see if it improves the performance?

```
torch.set_num_threads(1)
```

**Comment by knwng** [comment]
Hi @Tabrizian, I tried your method and it worked like a charm. Thx!
