### ISSUE TITLE
Python BLS script fails to load additional models on sagemaker

### ISSUE THREAD

**Issue by andompesta** [triton-inference-server/server#5452]
**Description**
BLS models are a great alternative to ensemble models, however they fail on sagemaker as only the BLS script is loaded by triton.
Running the [async_bls example](https://github.com/triton-inference-server/python_backend/tree/main/examples/bls) locally, you can clearly see that all the 3 models are loaded:

```bash
I0306 11:23:08.896491 1 model_lifecycle.cc:459] loading: bls_async:1
I0306 11:23:08.896527 1 model_lifecycle.cc:459] loading: pytorch:1
I0306 11:23:08.896555 1 model_lifecycle.cc:459] loading: add_sub:1
...

I0306 11:23:26.828626 1 server.cc:633] 
+-----------+---------+--------+
| Model     | Version | Status |
+-----------+---------+--------+
| add_sub   | 1       | READY  |
| bls_async | 1       | READY  |
| pytorch   | 1       | READY  |
+-----------+---------+--------+
```

However, when deploying a custom sagemaker endpoints, triton loads only the BLS script and fails at request-time as the 2 other models are not present:

```
I0306 11:47:58.517433 55 model_lifecycle.cc:459] loading: bls_async:1
...
I0306 11:48:00.336709 55 server.cc:633] 
| Model     | Version | Status |
+-----------+---------+--------+
| bls_async | 1       | READY  |
+-----------+---------+--------+
```

I suspect the  problem is related to the [load_model](https://github.com/triton-inference-server/server/blob/dfa151e7444e1ffdba9c66c8e9e9039c54b70027/docker/sagemaker/serve#L120) option in the sagemaker endpoint.

P.S. to run the example you need to create a conda environment with pytorch.

**Triton Information**
I use the provided triton container on AWS: `746233611703.dkr.ecr.eu-central-1.amazonaws.com/sagemaker-tritonserver:22.10-py3`

**To Reproduce**
1. I used the [async_bls example](https://github.com/triton-inference-server/python_backend/tree/main/examples/bls). So you can easily reproduce this error on sagemaker by building the appropriate model_repository artefact. Note that, in order to run the experiment you also need to create a conda environment containing pytorch.
2. create model with image: `746233611703.dkr.ecr.eu-central-1.amazonaws.com/sagemaker-tritonserver:22.10-py3` and environment variable `SAGEMAKER_TRITON_DEFAULT_MODEL_NAME= bls_async `
3.  endpoint configuration: `Instance type =  ml.m4.xlarge`, `insatnce count = 1` and `variant name = variant-name-1`

**Expected behavior**
I expect sagemaker endpoint to load all models used by the BLS script.

**Comment by GuanLuo** [comment]
On a less related note: there is the polling mode difference between when running SageMaker endpoint and when running the BLS example that SM load only the requested model (`EXPLICIT`) and the example poll and load all visible models at startup (`NONE`).

One major difference between ensemble and BLS is that: the BLS logic is isolated from Triton so Triton can't check what models are required by the BLS and load them if not yet available. In C++ BLS, the WAR is to let the BLS itself to call load API to make sure it has everything it needs. But for Python BLS, we must expose such API binding first, @Tabrizian have we expose load / unload API to Python backend yet? Although in hindsight, exposing all APIs to BLS is not safe, we may want to revisit this to see if we can implement it in a more controlled setting (only allow operation within the same model repo?).

That being said, we will mark this as enhancement (exposing model control API to Python backend).

CC @nskool on SageMaker is involved.

**Comment by Tabrizian** [comment]
@GuanLuo The API is not exposed to the Python models yet.

**Comment by nskool** [comment]
Seconding @GuanLuo's point and @Tabrizian - would be great to have load/unload exposed in python API!

@andompesta - Since SageMaker runs in explicit mode, currently there's a hack-ish way to run BLS on SageMaker - https://github.com/aws/amazon-sagemaker-examples/blob/main/sagemaker-triton/business_logic_scripting/stable_diffusion/sm-triton-bls-stablediff.ipynb. 
(Search for `preload_model_argument`)

This will not work in Multi-Model Endpoint mode currently though.

**Comment by andompesta** [comment]
@nskool thanks that works for me for the moment !

**Comment by GuanLuo** [comment]
Closing the issue as the SM example provides the WAR, the Python backend enhancement is being tracked by this issue https://github.com/triton-inference-server/server/issues/4366
