### ISSUE TITLE
Feature Request: More flexible model interactions

### ISSUE THREAD

**Issue by jamied157** [triton-inference-server/server#5454]
**Is your feature request related to a problem? Please describe.**
For some of the ML models I use, the way I want to interact with them is more than just using a `forward` method, I sometimes want to do a relatively inexpensive state modification for a particular connection and this doesn't need to be batched.

**Describe the solution you'd like**
Certain methods to PyTorch models can be exposed by the server so I can do more complex interactions with the model that aren't batched.

**Describe alternatives you've considered**
I could try and make a single complex `forward` method to the model that handles all possible requests but that would mean that a slots in the batch would be wasted with these smaller requests to the model.

I could also try and send the state back to the client side on each request and modify it there, this would make the model stateless which would simplify things. However some of these states are quite large and it's nice to keep all the logic in Pytorch rather than putting it in the client code.

**Comment by GuanLuo** [comment]
Hi @jamied157, are you using Triton Torch backend? If so, I think there is similar feature request here https://github.com/triton-inference-server/server/issues/5209 . We have tracked it but it hasn't been planned, and you can also refer to the latest comment in the issue if you are interested in contributing as well.

**Comment by jamied157** [comment]
Yep looks like this is a duplicate of that issue, thanks!

**Comment by GuanLuo** [comment]
I will keep the linked issue as it has been associated with an internal ticket, marking this issue duplicate and close it
