### ISSUE TITLE
triton inference latency increases rapidly if the interval of inference request is more than 1 second.

### ISSUE THREAD

**Issue by liwenhust8282** [triton-inference-server/server#5459]
**Description**
Compared with the interval 0.1s, triton inference latency increases rapidly if you set the inference interval to 1 second.

**Triton Information**
What version of Triton are you using?
| server_version                   | 2.29.0                                                                                                     |
| server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_policy model_configu |
|                                  | ration system_shared_memory cuda_shared_memory binary_tensor_data statistics trace logging                 

Are you using the Triton container or did you build it yourself?
use triton container tritonserver:22.12-py3

**To Reproduce**
Steps to reproduce the behavior.
1, docker run tritonserver:22.12-py3 with trace (--trace-file=/tmp/trace.json --ace-rate=10 --trace-level=MAX)
2, send inference requests from client with interval 0.1s continually. send one inference request synchronously, sleep 0.1s, send one inference request synchronously again, sleep 0.1s, send one inference request ...
3, analyze trace1.json using trace_summary.py
4, send inference requests from client with interval 1s continually. send one inference request synchronously, sleep 1s, send one inference request synchronously again, sleep 1s, send on inference request ...
5, analyze trace2.json using trace_summary.py
6, compare the result
![image](https://user-images.githubusercontent.com/49625669/223300895-f5966c7d-6d9a-417b-a856-8db4588f6f05.png)
you can find that the latency increased more than 60%, from 10ms to 17ms.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
models: densenet_onnx
configuration file:
name: "densenet_onnx"
platform: "onnxruntime_onnx"
max_batch_size : 0
input [
  {
    name: "data_0"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 224, 224 ]
    reshape { shape: [ 1, 3, 224, 224 ] }
  }
]
output [
  {
    name: "fc6_1"
    data_type: TYPE_FP32
    dims: [ 1000 ]
    reshape { shape: [ 1, 1000, 1, 1 ] }
    label_filename: "densenet_labels.txt"
  }
]

**Expected behavior**
the inference latency is mostly the same with different inference interval.

**Comment by rmccorm4** [comment]
Hi @liwenhust8282,

Are you restarting the server or reloading the model between your two runs? The first few requests will generally be slower due to a warmup period. Since the first test has `trace count = 29`, the first few slow requests would be hidden away better in the average, vs. the second test only having `trace count = 9`, the slow requests would impact the average more significantly. You may want to try warming up the models first, or verifying some of the individual traces rather than the average.

**Comment by liwenhust8282** [comment]
Thanks a lot for your suggestion.
1, I had modified the model configure, add model_warmup  property which avoid the effect of the first few request. 
2, And I do more performance test again. the result is almost the same. Compared with fast request, the latency of slow request increased about than 60%, from 10ms to 16ms. 
trace result listed in detail.
![image](https://user-images.githubusercontent.com/49625669/223986661-40e254dd-6a5b-4c2d-8b1c-c6ceac148063.png)
 

name: "densenet_onnx"
platform: "onnxruntime_onnx"
max_batch_size : 0
model_warmup  [
  {
    name: "random_input"
    batch_size: 1
    inputs: {
      key: "data_0"
      value: {
        data_type: TYPE_FP32
        dims: [3, 224, 224]
        random_data: true
      }
    }
  }
]
input [
  {
    name: "data_0"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 224, 224 ]
    reshape { shape: [ 1, 3, 224, 224 ] }
  }
]
output [
  {
    name: "fc6_1"
    data_type: TYPE_FP32
    dims: [ 1000 ]
    reshape { shape: [ 1, 1000, 1, 1 ] }
    label_filename: "densenet_labels.txt"
  }
]
> Hi @liwenhust8282,
> 
> Are you restarting the server or reloading the model between your two runs? The first few requests will generally be slower due to a warmup period. Since the first test has `trace count = 29`, the first few slow requests would be hidden away better in the average, vs. the second test only having `trace count = 9`, the slow requests would impact the average more significantly. You may want to try warming up the models first, or verifying some of the individual traces rather than the average.

**Comment by GuanLuo** [comment]
This may be related to the power setting of the GPU (and CPU?). @tanmayv25 do you happen to have the command to control GPU / CPU clock to eliminate this factor?

**Comment by liwenhust8282** [comment]
> This may be related to the power setting of the GPU (and CPU?). @tanmayv25 do you happen to have the command to control GPU / CPU clock to eliminate this factor?

thanks a lot for your advice. 
using the command jetson_clocks, I disabled the DVFS governor and locks the clocks to their maximum. And then I eliminate this factor.
