### ISSUE TITLE
Is dynamic batch use in ensemble model ? can i create a data pineline in triton API? 

### ISSUE THREAD

**Issue by trand2k** [triton-inference-server/server#5464]
Is dynamic batch use in ensemble model ? can i create a data pineline in triton API?

**Comment by GuanLuo** [comment]
> Is dynamic batch use in ensemble model?

Dynamic batching may be used in part of the ensemble. Ensemble model describes a model pipeline, it prepare the tensors for model execution and execute the models when it is ready. So ensemble itself doesn't perform any kind of dynamic batching, however, if the inner model has dynamic batcher specified, then the execution of the model will be dynamic batched.

> can i create a data pineline in triton API?

You can specify the data pipeline in the ensemble's config (`ensemble_scheduling`), once it is set and the ensemble is ready, the data pipeline will be run when you send the request to the ensemble.
