### ISSUE TITLE
ensemble model transfer a context

### ISSUE THREAD

**Issue by solaim** [triton-inference-server/server#5465]
**Is your feature request related to a problem? Please describe.**
I used ensemble pipeline, there are pre-process、tensorrt-model and post-process, in post-process I need raw image height and width,  actually in pre-process, I received raw image data, so I could provide the raw image height and width if there is a context, but not now. 

**Describe the solution you'd like**
Add an optional context.

**Comment by solaim** [comment]
For object detection case, nms does in post-process. nms needs raw image height and width, but thers is no properties to transfer these data. Context is a tool that is used to share request-scoped data across API layers or processes in a program.

**Comment by GuanLuo** [comment]
You can always mark the data needed to execute the model as the model input, so `nms` will accept two additional inputs for raw image height and width, then if the two data are generated by the pre-process model, then you can expose them to be the additional outputs of the pre-process model, which then you can provide corresponding mapping in your ensemble configuration.

I am not sure how context is used but the similar concept should be able to be applied to passing various objects between models.

**Comment by solaim** [comment]
Thanks, work well.
