### ISSUE TITLE
How to deploy a model whose size exceeds the memory of a single gpu

### ISSUE THREAD

**Issue by WangYizhang01** [triton-inference-server/server#5466]
**Description**
I am adding a large model in model_repository whose size exceeds the video memory of a single gpu. Then when using docker to start triton, the error 'UNAVAILABLE: Internal: onnx runtime error 6: Exception during initialization: /workspace/onnxruntime/onnxruntime/core/framework/bfc_arena.cc:331 void* onnxruntime::BFCArena::AllocateRawInternal(size_t, bool) Failed to allocate memory for requested buffer of size 314572800' is reported. I would like to know how to deploy such a large model. Is it possible to configure Triton to automatically split the model？

**Triton Information**
What version of Triton are you using?
tritonserver:21.10-py3
Are you using the Triton container or did you build it yourself?
the Triton container
**To Reproduce**
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
The model is GPT2 created by transformers, I modified some parameters:
```python
from pathlib import Path
import transformers
from transformers import GPT2Config, GPT2Tokenizer, GPT2Model
from transformers.onnx import FeaturesManager


num_attention_heads = 40
num_layers = 40
hidden_size = 5120

configuration = GPT2Config( 
                    n_embd=hidden_size,
                    n_layer=num_layers,
                    n_head=num_attention_heads
                )

tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
model = GPT2Model(configuration)
```
Then I convert the model to onnx using transformers.onnx:
```python
feature = 'sequence-classification'

model_kind, model_onnx_config = FeaturesManager.check_supported_model_or_raise(model, feature=feature)
onnx_config = model_onnx_config(model.config)
onnx_inputs, onnx_outputs = transformers.onnx.export(
        preprocessor=tokenizer,
        model=model,
        config=onnx_config,
        opset=13,
        output=Path("gpt2.onnx")
)
```

The file config.pbtxt as follow:
```text
name: "gpt2"
platform: "onnxruntime_onnx"
max_batch_size : 0
input [
  {
    name: "input_ids"
    data_type: TYPE_INT64
    dims: [ -1, -1 ]
  },
  {
    name: "attention_mask"
    data_type: TYPE_INT64
    dims: [ -1, -1 ]
  }
]
output [
  {
    name: "logits"
    data_type: TYPE_FP32
    dims: [ -1, -1, -1 ]
  }
]
```

**Expected behavior**

**Comment by GuanLuo** [comment]
Unfortunately Triton doesn't have the capability to split the model, it is largely relied on the underlying machine learning frameworks. As an example, FasterTransformer allows splitting and deploying the model on multiple GPU, you will need to check with the framework of the model to see if it is feasible and how to configure your model to utilize the feature.

Other than that, if you don't have to deploy the model on GPU (which you still have access to other Triton features), you may specify KIND_CPU in instance_group setting to deploy the model in system memory. However, it will have the same concern that the deployment depends on the size of memory available.
