### ISSUE TITLE
Questions about the "--disable-auto-complete-config" flag

### ISSUE THREAD

**Issue by jackylu0124** [triton-inference-server/server#5473]
**Description**
I have a quick question after going over this page ([https://github.com/triton-inference-server/server/blob/main/docs/user_guide/model_configuration.md](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/model_configuration.md)):

If I don't run `tritonserver` with the `--disable-auto-complete-config` flag, would the settings in the auto-generated model configuration files based on the ONNX models I provide override the settings in the configuraion files (the `config.pbtxt` files) I create in the model repository? Thanks!

**Triton Information**
I am using the `nvcr.io/nvidia/tritonserver:23.01-py3` Docker container.

**Comment by GuanLuo** [comment]
@nv-kmcgill53 @tanmayv25 

IIRC, auto-complete will only set the field that is not specified in the existing config files, it should not overwrite the existing setting. If the existing setting doesn't match the actual model, a proper error should be returned at a later stage (validation stage)

**Comment by nv-kmcgill53** [comment]
@GuanLuo is correct; however, in looking over [this code](https://github.com/triton-inference-server/onnxruntime_backend/blob/main/src/onnxruntime.cc#L642-L740) I see `AutocompleteConfig()` exiting early if, at a minimum, the inputs and outputs are defined. If they are defined we will not autocomplete other fields such as `max_batch_size` etc. This is something we will want to fix in the future.

**Comment by jackylu0124** [comment]
@GuanLuo @nv-kmcgill53 I see, thanks a lot for the explanation! So to make sure I understand this correctly, the current behavior is that if the inputs and outputs are defined, then only the specified fields will be used and the unspecified fields that are left out will not be auto-completed; and in the future, when inputs and outputs are defined, the left out unspecified fields will be auto-completed by Triton, is that correct? Thanks again!

**Comment by nv-kmcgill53** [comment]
>the current behavior is that if the inputs and outputs are defined, then only the specified fields will be used and the unspecified fields that are left out will not be auto-completed; 

As of now, yes this is correct.

>in the future, when inputs and outputs are defined, the left out unspecified fields will be auto-completed by Triton,

Ideally, yes. Just to clarify, there is no timeline on when this change will happen.

**Comment by GuanLuo** [comment]
Also note that the auto-complete functionality is provided by the backend of the model, so the behavior can vary from backend to backend (i.e. PyTorch backend can't auto-complete many fields because the model doesn't contain such metadata).
