### ISSUE TITLE
How to build a tritonserver image based on centos7, which is now based on ubuntu, and the current build.py does not support it;

### ISSUE THREAD

**Issue by ltdo111** [triton-inference-server/server#5478]
How to build a tritonserver image based on centos7, which is now based on ubuntu, and the current build.py does not support it;

**Comment by ltdo111** [comment]
I tried it, but it failed to build an image through source code compilation on mac os m1;

based on this latest issue, https://github.com/triton-inference-server/server/issues/5485

**Comment by dyastremsky** [comment]
Closing due to 5485 being opened, so we can shift conversation there to avoid duplication.

**Comment by ltdo111** [comment]
Hi, I have encountered a new problem of cmake compilation in the centos image, as shown below:
 
![image](https://user-images.githubusercontent.com/17394163/224491140-c729c4ee-082b-4e0f-a1d1-1d6fa4e1fde6.png)


How can I solve this problem?
