### ISSUE TITLE
Triton support for Red Hat Enterprise Linux

### ISSUE THREAD

**Issue by luismarquezgft** [triton-inference-server/server#5516]
**Description**
The  NVIDIA Repo uses Ubuntu to build Triton's images. References to Ubuntu and Windows support are present in the documentation.

- The question is if Triton is OFFICIALLY supported when running in RHEL images (custom container)?
- If yes, are there any special conditions that apply?

**Triton Information**
What version of Triton are you using? Latest.

Are you using the Triton container or did you build it yourself?
N/A

**To Reproduce**
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**

**Comment by Tabrizian** [comment]
> The question is if Triton is OFFICIALLY supported when running in RHEL images (custom container)?

No, Triton is not officially supported when running in RHEL images.
