### ISSUE TITLE
Citation of Triton inference server

### ISSUE THREAD

**Issue by niqbal996** [triton-inference-server/server#5518]
**Is your feature request related to a problem? Please describe.**
Could you add a citation link to your Github repo? (.cff file or bibtex) I want to cite it for our research publication and do not know who to put in the authors. I checked the issues but could not find anything relevant. 

**Describe the solution you'd like**
Github has a feature of adding a cff file. I think that would be the easiest. 

**Describe alternatives you've considered**
This is a bibtex I came up with. 
@misc{triton,
  author = {John Doe?},
  title = {Triton Inference Server},
  year = {2023},
  publisher = {NVIDIA},
  version= {x},
  journal = {GitHub repository},
  howpublished = {\url{https://github.com/triton-inference-server/server}},
  commit = {6aa17924c7ef47f4e24053459fcabbc501f646f2}
}

**Comment by dyastremsky** [comment]
Thank you for your research and citation, Naeem. Really appreciate the high-impact research produced by the German Research Center for Artificial Intelligence. Tagging a couple of folks who can advise how to proceed.

CC: @dzier @Christina-Young-NVIDIA

**Comment by rmccorm4** [comment]
@niqbal996 Let us know if this enables your citation now 🙂
