### ISSUE TITLE
TRITONBACKEND_ModelInstanceInitialize: xxx (CPU device 0)

### ISSUE THREAD

**Issue by AlanFokCo** [triton-inference-server/server#5524]
When I run triton-server in the docker environment `nvcr.io/nvidia/tritonserver:2202-py3`, but I don't use gpu.
My Program block in `onnxruntime.cc:2443] TRITONBACKEND_ModelInstanceInitialize:xxx (CPU device 0)`.
And I use strace to check this process, it has blocked in `futex(0x55eb28df73a0, FUTEX_WAIT, 2147483648, NULL`.
What can I do to solve this problem.

**Comment by dyastremsky** [comment]
Please provide full reproduction steps and logs. You can use the bug report issue template to make sure to include all information (sample model, model config, system architecture, commands run, etc.) we'd need to reproduce your issue.

Once received, we can file a ticket to investigate.
