### ISSUE TITLE
error using grpc

### ISSUE THREAD

**Issue by okyspace** [triton-inference-server/server#5543]
**Description**

Hi I am trying to do a grpc call to an application deployed in my openshift. But I keep getting error `DNS resolution failed for service https://<route url to the service>`. 
I have tried pinging the hostname and it can be resolved. and successfully pinged. Any advice?
I have exposed the grpc. 

**Triton Information**
What version of Triton are you using?
23.02-py3

Are you using the Triton container or did you build it yourself?
Triton Container.

**To Reproduce**
Steps to reproduce the behavior.
I have followed this medium. https://medium.com/@furcifer/deploying-triton-inference-server-in-5-minutes-67aa09a84ca6
```
triton_client = grpcclient.InferenceServerClient(
        url='https://<route url to the service>',
        verbose=True)

results = triton_client.infer(model_name=model_name,
                                inputs=inputs,
                                outputs=outputs,
                                headers={'test': '1'})
```

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
Using a pytorch model, but this should not be the cause of the issue. 

**Expected behavior**
Successful inference done using grpc.

**Comment by jbkyang-nvi** [comment]
Have you tried using localhost (deploying both server and client to the same machine) and see if works?

**Comment by merlinarer** [comment]
have you sole it? I met the same issue

**Comment by merlinarer** [comment]
> **Description** A clear and concise description of what the bug is.
> 
> Hi I am trying to do a grpc call to an application deployed in my openshift. But I keep getting error `DNS resolution failed for service https://<route url to the service>`. I have tried pinging the hostname and it can be resolved. and successfully pinged. Any advice? I have exposed the grpc.
> 
> **Triton Information** What version of Triton are you using? 23.02-py3
> 
> Are you using the Triton container or did you build it yourself? Triton Container.
> 
> **To Reproduce** Steps to reproduce the behavior. I have followed this medium. https://medium.com/@furcifer/deploying-triton-inference-server-in-5-minutes-67aa09a84ca6
> 
> ```
> triton_client = grpcclient.InferenceServerClient(
>         url='https://<route url to the service>',
>         verbose=True)
> 
> results = triton_client.infer(model_name=model_name,
>                                 inputs=inputs,
>                                 outputs=outputs,
>                                 headers={'test': '1'})
> ```
> 
> Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well). Using a pytorch model, but this should not be the cause of the issue.
> 
> **Expected behavior** A clear and concise description of what you expected to happen. Successful inference done using grpc.
have you sole it? I met the same issue

**Comment by merlinarer** [comment]
> **Description** A clear and concise description of what the bug is.
> 
> Hi I am trying to do a grpc call to an application deployed in my openshift. But I keep getting error `DNS resolution failed for service https://<route url to the service>`. I have tried pinging the hostname and it can be resolved. and successfully pinged. Any advice? I have exposed the grpc.
> 
> **Triton Information** What version of Triton are you using? 23.02-py3
> 
> Are you using the Triton container or did you build it yourself? Triton Container.
> 
> **To Reproduce** Steps to reproduce the behavior. I have followed this medium. https://medium.com/@furcifer/deploying-triton-inference-server-in-5-minutes-67aa09a84ca6
> 
> ```
> triton_client = grpcclient.InferenceServerClient(
>         url='https://<route url to the service>',
>         verbose=True)
> 
> results = triton_client.infer(model_name=model_name,
>                                 inputs=inputs,
>                                 outputs=outputs,
>                                 headers={'test': '1'})
> ```
> 
> Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well). Using a pytorch model, but this should not be the cause of the issue.
> 
> **Expected behavior** A clear and concise description of what you expected to happen. Successful inference done using grpc.
have you sole it? I met the same issue

**Comment by okyspace** [comment]
Yes I did. I used a cert with specific hostname instead of a wild card, maybe you want to share a bit more on your setup?
