### ISSUE TITLE
Serving python libraries using Triton Inference Server

### ISSUE THREAD

**Issue by arch1902** [triton-inference-server/server#5552]
Is there a way to serve models available as Python libraries using Triton Inference Server?
For example, 
```python
import easyocr

reader = easyocr.Reader(['en'], gpu=True) # loading the model to GPU
result = reader.readtext('card.jpg') # inference request
```
Can this easyocr model be served using Triton ?

**Comment by Tabrizian** [comment]
Yes, please take a look at the Python backend documentation: https://github.com/triton-inference-server/python_backend#quick-start

You might also be interested in this section of the docs: https://github.com/triton-inference-server/python_backend#managing-python-runtime-and-libraries
