### ISSUE TITLE
custom backend [undefined symbol] 

### ISSUE THREAD

**Issue by dhanushSB96** [triton-inference-server/server#5561]
I have a custom backend and I'm trying to launch the triton server with a model.
It fails to load the model as I run into error 
Not found: unable to load shared library: /.../libtriton_custom_backend.so: undefined symbol: _ZN6xxx6IoDescC1Ev
I've made sure to include the target directories in CMakeLists.txt so that it can be available in the .so file. I'm not sure why it isn't recognizing it.
Can you suggest where I should be looking at?

**Comment by GuanLuo** [comment]
Is this symbol from another library that your backend is dynamically linked to? If so, you should make sure the library can be found via `LD_LIBRARY_PATH`. Otherwise, if the symbol is defined in the backend, the source file may be missing from the CMake instructions.

**Comment by dhanushSB96** [comment]
It is dynamically linked and echo $LD_LIBRARY_PATH shows the directory where its present. Should I be making any changes to the CMake file?

**Comment by TianyuLee** [comment]
I have a similar problem and i fix it by adding library path to target_link_libraries

**Comment by dhanushSB96** [comment]
@TianyuLee Thank you, adding path to target_link_libraries solved the issue
