### ISSUE TITLE
Can I add model instances without restarting the triton server?

### ISSUE THREAD

**Issue by JasonChao-yue** [triton-inference-server/server#5565]
When the client performs model inference requests, the latency will initially increase as the number of request paths increases, but the count set in the initial model configuration file is small

Can you increase model instances to reduce latency without restarting the triton server, or is there any other way to reduce latency?

Thank you and salute

**Comment by dyastremsky** [comment]
Yes. Update the model config. If you're in POLL mode, the changes will happen automatically. If you're in EXPLICIT mode (recommended for production deployments), you'll need to send a request to reload the model.

**Comment by JasonChao-yue** [comment]
> Yes. Update the model config. If you're in POLL mode, the changes will happen automatically. If you're in EXPLICIT mode (recommended for production deployments), you'll need to send a request to reload the model.

Thank you for your reply
