### ISSUE TITLE
Error when run multiple triton server process in one machine

### ISSUE THREAD

**Issue by frankxyy** [triton-inference-server/server#5573]
The error is like:
<img width="1379" alt="image" src="https://user-images.githubusercontent.com/6971044/228767231-76abb281-ff9f-4fa8-b4ed-5d03ea7819ba.png">
![Uploading image.png…]()

I suspect this may due to the communication between triton main processes and python model processes when launching multiple triton servers on the same machine.

**Comment by dyastremsky** [comment]
That's correct. I don't think you can run multiple servers if you are running with the Python backend in each, given the way its stubs work.

CC: @Tabrizian in case he can speak more about whether the above is possible.

**Comment by Tabrizian** [comment]
This is actually possible. Please take a look at the documentation below:

https://github.com/triton-inference-server/python_backend#running-multiple-instances-of-triton-server

**Comment by oandreeva-nv** [comment]
Closing due to the lack of activity. @frankxyy feel free to re-open/tag me for any further questions
