### ISSUE TITLE
Serve tf-trt converted model return error: NodeDef mentions attr 'max_batch_size' not in Op: name=TRTEngineOp

### ISSUE THREAD

**Issue by biaochen** [triton-inference-server/server#5583]
**Description**
Serving a tf-trt optimized model return error: Invalid argument: NodeDef mentions attr 'max_batch_size' not in Op: name=TRTEngineOp

**Triton Information**
What version of Triton are you using?
_nvcr.io/nvidia/tritonserver:22.07-py3_

Are you using the Triton container or did you build it yourself?
Use official image: _nvcr.io/nvidia/tritonserver:22.07-py3_

**To Reproduce**
Steps to reproduce the behavior.
I want to use tf-trt to optimize a tf2 model, and then serve with triton. But fail to serve the optimized tf-trt model. Following is the process:

1. following this tutorial (https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html#introduction), create a tf-trt optimized model
I use image _nvcr.io/nvidia/tensorflow:22.07-tf2-py3_ to run the code, and successfully created native model and converted model:
```
models/
├── native_saved_model
│   ├── assets
│   ├── keras_metadata.pb
│   ├── saved_model.pb
│   └── variables
│       ├── variables.data-00000-of-00001
│       └── variables.index
└── tftrt_saved_model
    ├── assets
    │   └── trt-serialized-engine.TRTEngineOp_000_000
    ├── saved_model.pb
    └── variables
        ├── variables.data-00000-of-00001
        └── variables.index
```

2. copy the native and converted model to a repos, and create the dir structure as triton wants:
```
├── mnist
│   ├── 1
│   │   └── model.savedmodel
│   │       ├── assets
│   │       ├── keras_metadata.pb
│   │       ├── saved_model.pb
│   │       └── variables
│   │           ├── variables.data-00000-of-00001
│   │           └── variables.index
│   └── config.pbtxt
└── mnist_trt
    ├── 1
    │   └── model.savedmodel
    │       ├── assets
    │       │   └── trt-serialized-engine.TRTEngineOp_000_000
    │       ├── saved_model.pb
    │       └── variables
    │           ├── variables.data-00000-of-00001
    │           └── variables.index
    └── config.pbtxt
```
the native model is copied under mnist/1/model.savedmodel, with config.pbtxt like this:
```
name: "mnist"
platform: "tensorflow_savedmodel"
max_batch_size : 0
```

the converted model is copied under mnist_trt/1/model.savedmodel, with config.pbtxt the same as above.

3. start the triton server within container _nvcr.io/nvidia/tritonserver:22.07-py3_, the log shows both models are loaded successfully.

4. try to infer. The client code likes this:
```
import tensorflow as tf
import numpy as np
import tritonclient.http as httpclient

# Setting up client
url = 'SERVER_IP:8000'
triton_client = httpclient.InferenceServerClient(url=url)
input1_shape = [1, 28, 28]
input1 = httpclient.InferInput("flatten_input", input1_shape, datatype="FP32")
input1_data = np.arange(1*28*28).reshape(1,28,28).astype(np.float32)
print('input1_data: ', input1_data)
input1.set_data_from_numpy(input1_data, binary_data=False)

test_output = httpclient.InferRequestedOutput("dense_1", binary_data=False, class_count=10)

# Querying the server
model_name="mnist"
results = triton_client.infer(model_name=model_name, inputs=[input1], outputs=[test_output])
print(results.as_numpy('dense_1'))
```
If the model_name is mnist, the infer succeeds, and print the predict result.
```
[['9575.137695:3' '9021.530273:2' '5957.917969:7' '-416.794525:5'
'-6797.246582:9' '-8895.693359:1' '-9928.074219:0' '-15507.916016:8'
'-22406.882812:6' '-29679.443359:4']]
```
However, after changing model_name to mnist_trt, the call fails, with error message: 
```
tritonclient.utils.InferenceServerException: NodeDef mentions attr 'max_batch_size' not in Op<name=TRTEngineOp; signature=in_tensor: -> out_tensor:; attr=serialized_segment:string; attr=segment_func:func,default=[]; attr=InT:list(type),min=1,allowed=[DT_INT8, DT_HALF, DT_FLOAT, DT_INT32]; attr=OutT:list(type),min=1,allowed=[DT_INT8, DT_HALF, DT_FLOAT, DT_INT32]; attr=max_cached_engines_count:int,default=1; attr=workspace_size_bytes:int; attr=precision_mode:string,allowed=["FP32", "FP16", "INT8"]; attr=calibration_data:string,default=""; attr=use_calibration:bool,default=true; attr=input_shapes:list(shape),default=[]; attr=output_shapes:list(shape),default=[]; attr=segment_funcdef_name:string,default=""; attr=cached_engine_batches:list(int),default=[],min=0; attr=fixed_input_size:bool,default=true; attr=static_engine:bool,default=true>; NodeDef: {{node TRTEngineOp_000_000}}. (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
[[PartitionedCall/PartitionedCall/TRTEngineOp_000_000]]
```
I guess maybe it's a version issue?

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
framework: tf2
model configuration: 
```
name: "mnist_trt"
platform: "tensorflow_savedmodel"
```

**Expected behavior**
The infer should succeed.

**Comment by rmccorm4** [comment]
Hi @biaochen,

Thanks for raising this detailed issue.

1. Did you include `max_batch_size: 0` in your `mnist_trt` config.pbtxt as well?
2. Are you able to run this [example](https://github.com/tensorflow/tensorrt/tree/master/tftrt/triton)?
3. Are you able to run inference on the `mnist_trt` model outside of Triton? (TF APIs / TF python script, etc.)

If none of these help narrow down the issue, I suggest raising the issue in the TF-TRT repo, as this sounds like a TF-TRT issue more than a Triton issue: https://github.com/tensorflow/tensorrt/issues

**Comment by biaochen** [comment]
1. whether or not include ```max_batch_size: 0```, the result is the same;
2. yes, the same error appears;
3. I'd load the converted model, but summary fails, seems it's not a standard tf2 saved model:
```
>>> model = tf.keras.models.load_model('resnet50_saved_model_TFTRT_FP32')
WARNING:tensorflow:SavedModel saved prior to TF 2.5 detected when loading Keras model. Please ensure that you are saving the model with model.save() or tf.keras.models.save_model(), *NOT* tf.saved_model.save(). To confirm, there should be a file named "keras_metadata.pb" in the SavedModel directory.
>>> model.summary()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: '_UserObject' object has no attribute 'summary'
>>> type(model)
<class 'tensorflow.python.saved_model.load.Loader._recreate_base_user_object.<locals>._UserObject'>
```

Thanks for your kind help, I'll ask tf-trt experts.
