### ISSUE TITLE
 Batch between model in ensemble model

### ISSUE THREAD

**Issue by ThaiLe189** [triton-inference-server/server#5586]
**Is your feature request related to a problem? Please describe.**
Batch between model in ensemble model
**Describe the solution you’d like**
I have a ensemble config of 2 child models are in the Appendix:

```
name: “ensemble_model”
platform: “ensemble”
max_batch_size : 8
input [
  {
      name: “IMAGE”
      data_type: TYPE_UINT8
      dims: [ -1, -1, -1]
  }
]
input [
  {
      name: “CUTINFO”
      data_type: TYPE_INT32
      dims: [ -1, 4 ]
  }
]
output [
  {
    name: “dense”
    data_type: TYPE_FP32
    dims: [ -1, 1 ]
  }
]
ensemble_scheduling {
  step [
    {
      model_name: “preprocess”
      model_version: -1
      input_map {
        key: “IMAGE”
        value: “IMAGE”
      }
        input_map {
        key: “CUTINFO”
        value: “CUTINFO”
      }
      output_map {
        key: “OUTPUT_0”
        value: “preprocessed_image”
      }
    },
    {
      model_name: “skinoops”
      model_version: -1
      input_map {
        key: “input_1"
        value: “preprocessed_image”
      }
      output_map {
        key: “dense”
        value: “dense”
      }
    }
  ]
}
```

**Describe alternatives you’ve considered**
Have anyway to set model skinoops receive as batch?
For example: after run over model preprocess, the output is 1000 image and the skinoops model will be receive sequence 20 image
Our preprocess model is for cutting the input image into many small images then feed to the second model. A problem is that the preprocess model can produce as many as 1000 images, which will not fit in the VRAM in 1 batch for the second model. Is there a way to make the second model process the output of the first model a few images at a time? For example: first model produces 1000 images, second model processes 20 images at a time util all 1000 images are processed.

**Appendix**
preprocess model:

```
name: "preprocess"
backend: "python"
max_batch_size: 0
input [
    {
        name: "IMAGE"
        data_type: TYPE_UINT8
        dims: [ -1, -1, -1]
    }
]

input [
    {
        name: "CUTINFO"
        data_type: TYPE_INT32
        dims: [ -1, 4 ]
    }
]

output [
    {
        name: "OUTPUT_0"
        data_type: TYPE_FP32
        dims: [ -1, 256, 256, 3 ]
    }
]
instance_group [{ kind: KIND_CPU }] 
```

skinoops model:

```
name: "skinoops"
platform: "tensorflow_savedmodel"
max_batch_size: 0
input [
  {
    name: "input_1"
    data_type: TYPE_FP32
    dims: [ -1, 256, 256, 3 ]
  }
]
output [
  {
    name: "dense"
    data_type: TYPE_FP32
    dims: [ -1, 1 ]
  }
]
```

Thank!

**Comment by rmccorm4** [comment]
Hi @ThaiLe189,

For custom scheduling/processing logic between models in a pipeline, I think BLS would better suit this case: https://github.com/triton-inference-server/python_backend/tree/main#business-logic-scripting. It is likely not possible or much more difficult to achieve some branching logic like this within the ensemble by itself.
