### ISSUE TITLE
throughput of perf analyzer 

### ISSUE THREAD

**Issue by uitae** [triton-inference-server/server#5587]
![image](https://user-images.githubusercontent.com/65074073/229680222-d1b6dac7-89e0-4670-b146-451fd0d8833b.png)

I expected throughput of N concurrent inference is less than N multiply of 1 concurrent inference.
But that wasn't really the case. Is this possible? Why did this happen?

**Comment by rmccorm4** [comment]
Can you elaborate on the question here? I don't understand.

It looks like your throughput is scaling pretty linearly for concurrency 1:4, which is expected if the model is sufficiently fast or there are sufficient resources to schedule/execute all of the requests concurrently (instance count, CPU/GPU, etc.)

At a certain concurrency threshold your throughput would likely plateau or degrade as you approach the resource limitations.

**Comment by uitae** [comment]
I was wondering why if this might show a larger execution speed increase than a linear increase.

I thought the maximum throughput of concurrency of 4 would be a little less than 4 times the throughput of the concurrency of 1, but it was actually more than 5 times larger, so I asked if I could know why.

Thank you for your answer

**Comment by rmccorm4** [comment]
Hi @uitae, I'm not sure there's an easy generic or exact answer to that question. I can share some rough ideas though.

If there is other significant other work happening on the same system, this could attribute to variance. However, assuming the system is relatively idle other than this test - sometimes there can be variance in system clock speeds (CPU and GPU) based on the rate of incoming requests. If you lock your CPU and GPU clock speeds, you should get more consistent results. Similarly, making sure there is no other heavy processes running will help with consistency too.

There could be spikes in network latency based on your network, system configuration, etc. - comparing HTTP vs GRPC, or making sure there is nothing heavy slowing down the network during the test, or testing in C API mode can help with consistency as well in this regard.

Some models, backends, frameworks, etc. also have certain warmup periods. It's possible the concurrency=1 had some portion spent warming up the server/models/etc. - doing an additional perf analyzer run before the actual test may provide more consistent results as well.
