### ISSUE TITLE
Question about the dynamic batcher and multi-instance model

### ISSUE THREAD

**Issue by 32nguyen** [triton-inference-server/server#5590]
Hi, 

Can multi-instance model be used without dynamic batching? such as with tensorRT but max-batch-size = 0. 

thanks.

**Comment by dyastremsky** [comment]
Sure, dynamic batching is always optional. More information about TRT in the dynamic batchre documentation [here.](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/model_configuration.md#default-max-batch-size-and-dynamic-batcher)
