### ISSUE TITLE
Trouble starting Triton with 3 ONNX models loaded

### ISSUE THREAD

**Issue by abryant710** [triton-inference-server/server#5602]
**Description**

Triton server is failing to start based on `config.pbtxt` file format.

[triton_error.log](https://github.com/triton-inference-server/server/files/11165511/triton_error.log)

**Triton Information**

23.01

Are you using the Triton container or did you build it yourself?

Container

**To Reproduce**
Steps to reproduce the behavior.

Start Triton at the root with the following command:

`docker run --name $(CONTAINER_NAME) --gpus all -p 8000:8000 -p 8001:8001 -p 8002:8002 -v $(shell pwd)$(MODEL_DIR):/models $(DOCKER_IMAGE) tritonserver --model-repository=/models`

Please also refer to the directory structure in the attached file.

[dir_structure.txt](https://github.com/triton-inference-server/server/files/11165477/dir_structure.txt)

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using
 an ensemble include the model configuration file for that as well).

Please refer to the attached. Also using gender_googlenet and emotion-ferplus-8 from the ONNX model zoo.

[age_googlenet_config.pbtxt.txt](https://github.com/triton-inference-server/server/files/11165476/age_googlenet_config.pbtxt.txt)

**Expected behavior**
Triton to start successfully and allow inferencing with the models.

**Comment by abryant710** [comment]
I have also tested this with nvcr.io/nvidia/tritonserver:23.03-py3 and have the same results

**Comment by abryant710** [comment]
I have made some updates to the directory structure and am now seeing a different error. Please can you provide some assistance with the configuration file requirements?

[dir_structure.txt](https://github.com/triton-inference-server/server/files/11165752/dir_structure.txt)
[triton_error.log](https://github.com/triton-inference-server/server/files/11165753/triton_error.log)
[age_googlenet_config.pbtxt.txt](https://github.com/triton-inference-server/server/files/11165757/age_googlenet_config.pbtxt.txt)

**Comment by rmccorm4** [comment]
Hi @abryant710,

Overall, I'd refer to the [docs on max_batch_size](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/model_configuration.md#maximum-batch-size) which goes into more detail on the difference between:

```
max_batch_size: 10
input [
  {
    name: "input"
    data_type: TYPE_FP32
    # Since max_batch_size > 0, the batch dimension is implicitly -1 and shouldn't be included here
    dims: [3, 224, 224]
  }
]
```
and
```
max_batch_size: 0
input [
  {
    name: "input"
    data_type: TYPE_FP32
    # Since max_batch_size == 0, the batch dimension must be explicitly included in the dims here
    dims: [-1, 3, 224, 224]
  }
]
```

---

For your first error:
> [libprotobuf ERROR /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo/src/grpc/third_party/protobuf/src/google/protobuf/text_format.cc:335] Error parsing text-format inference.ModelConfig: 2:17: Message type "inference.ModelConfig" has no field named "model_repository".

As stated, `model_repository` is not a valid/expected field in the model config. It looks like you've already removed it in your latest comment.

For your next error:

> E0406 02:29:08.373735 1 model_lifecycle.cc:597] failed to load 'gender_googlenet' version 1: Invalid argument: model 'gender_googlenet', tensor 'input': for the model to support batching the shape should have at least 1 dimension and the first dimension must be -1; but shape expected by the model is [1,3,224,224]

This relates to the `max_batch_size` behavior described above. In short, if your model supports batching and has a dynamic batch dimension, you can specify a `max_batch_size` > 0 such as `max_batch_size: 10` as you have - but that means you should not include the batch dimension in your input or output `dims`, so it should look something like:
```
max_batch_size: 10
input [
  {
    name: "input"
    data_type: TYPE_FP32
    # Since max_batch_size > 0, the batch dimension is implicitly -1 and shouldn't be included here
    # The full shape is implicitly [-1, 3, 224, 224]
    dims: [3, 224, 224]
  }
]
output [
  {
    name: "loss3/loss3_Y"
    data_type: TYPE_FP32
    # Since max_batch_size > 0, the batch dimension is implicitly -1 and shouldn't be included here.
    # The full shape is impicitly [-1, 8]
    dims: [8]
  }
]
```

---

Lastly, for a quickstart / trying out Triton perspective, I recommend reading up on Triton's Autocomplete Config feature: https://github.com/triton-inference-server/server/blob/main/docs/user_guide/model_configuration.md#auto-generated-model-configuration.

For ONNX models (and some other supported frameworks described in the doc), the model config can be completely inferred from the model file. So you can remove the config file completely, or remove the I/O components and let Triton fill in the blanks at model load time. You can then query the full model config that Triton generated: `curl localhost:8000/v2/models/age_googlenet/config`.

Hope the docs and some experimenting with the above will help.

**Comment by abryant710** [comment]
@rmccorm4 thanks for the reply. The information you've provided has been very helpful. You can see the output of `curl localhost:8000/v2/models/gender_googlenet/config` in the attached file.

[gender_googlenet.json.txt](https://github.com/triton-inference-server/server/files/11194719/gender_googlenet.json.txt)

From that I've derived the following configuration file for the model:

[gender_googlenet_config.pbtxt.txt](https://github.com/triton-inference-server/server/files/11194722/gender_googlenet_config.pbtxt.txt)

When I try to trigger a basic inferencing request I get the following error:

```bash
docker run -it --rm --net=host nvcr.io/nvidia/tritonserver:23.03-py3-sdk

=================================
== Triton Inference Server SDK ==
=================================

NVIDIA Release 23.03 (build 56086600)

Copyright (c) 2018-2023, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use the NVIDIA Container Toolkit to start this container with GPU support; see
   https://docs.nvidia.com/datacenter/cloud-native/ .

root@docker-desktop:/workspace# /workspace/install/bin/image_client -m gender_googlenet /workspace/images/mug.jpg
expecting input to have 3 dimensions, model 'gender_googlenet' input has 4
root@docker-desktop:/workspace# /workspace/install/bin/image_client -m gender_googlenet -c 3 -s INCEPTION /workspace/images/mug.jpg
expecting input to have 3 dimensions, model 'gender_googlenet' input has 4
```

Does this mean that the model is not compatible with Triton? Or does image_client need to be adapted to support this particular ONNX model? I'd appreciate you help on this.

**Comment by abryant710** [comment]
I have resolved this issue by mapping the dimensions from 4 to 3 successfully
