### ISSUE TITLE
Question about how dynamic batching works

### ISSUE THREAD

**Issue by pjh4993** [triton-inference-server/server#5603]
Thanks for your great works. 

Currently, I'm preparing the deployment of the object detection model in TRIS.
The model consists of a preprocessor and an inference model, each with a Python backend and a TensorRT backend. 
The preprocessor at Python backend loads images from disk and does some preprocessing, while the inference model in TensorRT backend runs actual inference to detect objects. 
For more information, please check attached configuration.

I found some strange results while analyzing TRIS configuration with perf_analyzer and comparing it with custom logs from the Python backend.
In python handler I checked number of request they've got and print them. The printed logs are shown as follows.

```
I0406 03:23:48.270120 1773750 model.py:86] (1, 1) request execute
I0406 03:23:48.281884 1773750 model.py:86] (1, 1) request execute
I0406 03:23:48.283971 1773750 model.py:86] (1, 1) request execute
I0406 03:23:48.303864 1773750 model.py:86] (1, 1) request execute
I0406 03:23:48.316535 1773750 model.py:86] (1, 1) request execute
I0406 03:23:48.329439 1773750 model.py:86] (1, 1) request execute
I0406 03:23:48.342474 1773750 model.py:86] (1, 1) request execute
I0406 03:23:48.394277 1773750 model.py:86] (1, 1) request execute
....
```

It looks like no dynamic batching are not occurs.
However, perf_analyzer shows different results.
```
Request concurrency: 64
  Client:
    Request count: 6999
    Throughput: 97.1996 infer/sec
    p50 latency: 659537 usec
    p90 latency: 891660 usec
    p95 latency: 932373 usec
    p99 latency: 1138880 usec
    Avg HTTP time: 649396 usec (send/recv 3431 usec + response wait 645965 usec)
  Server:
    Inference count: 22065
    Execution count: 22065
    Successful request count: 22065
    Avg request latency: 1127384 usec (overhead 0 usec + queue 258617 usec + compute 872029 usec)

  Composing models:
  nd_json_preprocess, version:
      Inference count: 22065
      Execution count: 1113
      Successful request count: 22065
      Avg request latency: 1086692 usec (overhead 253 usec + queue 244366 usec + compute input 195 usec + compute infer 805777 usec + compute output 36099 usec)

  nd_trt, version:
      Inference count: 22097
      Execution count: 4781
      Successful request count: 22097
      Avg request latency: 54453 usec (overhead 10246 usec + queue 14251 usec + compute input 14191 usec + compute infer 14712 usec + compute output 1052 usec)
```
Based on what I understand, inference count describes how many requests have been inserted into queue, whereas execution count describes how often the model runs.
As the number of inferences and executions shows a huge difference, which means dynamic bathing occurs now.

But printed logs of python backend show the model runs single request at a time.
I am extremely confused about these two results showing different meanings.
Am I wrong? How can this happen if I'm not?

[model configuration and log files](https://drive.google.com/drive/folders/1i1z_Dpzag9SaPSCmEV9QKooTxa6Ju8Kz?usp=sharing)

**Comment by rmccorm4** [comment]
Hi @pjh4993,

For the python backend in particular (a special case), I believe it does not actually support batching nor compute the requests in batches as described in similar tickets: https://github.com/triton-inference-server/server/issues/3286. I believe internally it sends batches as lists of individual requests, which can be seen from some logging:
```python
def execute(self, requests):
  print("NUM REQUESTS:", len(requests), flush=True)
  for request in requests:
    # ...
    print("INPUT SHAPE:", my_input.shape)
```

A random sample of outputs from `perf_analyzer -m my_model --shape INPUT0:7,3 --concurrency 4:
```
NUM REQUESTS: 1
INPUT SHAPE: (1, 7, 3)

NUM REQUESTS: 3
INPUT SHAPE: (1, 7, 3)
INPUT SHAPE: (1, 7, 3)
INPUT SHAPE: (1, 7, 3)

NUM REQUESTS: 1
INPUT SHAPE: (1, 7, 3)

NUM REQUESTS: 1
INPUT SHAPE: (1, 7, 3)

NUM REQUESTS: 2
INPUT SHAPE: (1, 7, 3)
INPUT SHAPE: (1, 7, 3)
```

So currently it reports stats for each request in the batch individually.

@Tabrizian could probably share more details on this current behavior, or correct me if I'm wrong.

**Comment by pjh4993** [comment]
I figured out @rmccorm4  is right. Previously, I had some misunderstanding about requests sent to Python's backend's execute function. Now I have clear view thanks to @rmccorm4.
