### ISSUE TITLE
How to use golang's ModelStreamInfer interface

### ISSUE THREAD

**Issue by lywyue** [triton-inference-server/server#5608]
When I use c++, I can correctly call the streaming grpc interface to access the triton service, but when using golang, the streaming service request fails

// Submit inference request to server
	modelInferResponse, err := client.ModelStreamInfer(ctx)
	if err != nil {
		log.Fatalf("Error processing InferRequest: %v", err)
	}
	if err := modelInferResponse.Send(&modelInferRequest); err != nil {
		log.Fatalf("modelInferRequest send failed %v", err)
	}
	if r, err := modelInferResponse.Recv(); err != nil {
		log.Fatalf("modelInferRequest Recv failed %v", err)
		return nil
	} else {
		return r
	}

**Comment by rmccorm4** [comment]
Hi @lywyue,

Can you share a more log with the actual errors you're getting, the type of model, the tritonserver command, etc.?

Also, if you can share a minimal reproducible example, including relevant model, config, etc. that will help as well.

**Comment by lywyue** [comment]
The backend is a streaming model, so http requests cannot be used here, and the received error is modelInferRequest Recv failed rpc error: code = DeadlineExceeded desc = Deadline Exceeded,
I found that c++ can pass InferOptions options(model_name);
   options.model_version_ = "1";
   options.request_id_ = "101";
   options.sequence_start_ = false;
   options.sequence_end_ = false;
But golang can't find the interface

**Comment by lywyue** [comment]
Maybe I should handle the structure separately, I saw the processing logic in grpc_client.cc， Thank

**Comment by lywyue** [comment]
I added these parameters 
modelInferRequest.Parameters = make(map[string]*triton.InferParameter)
modelInferRequest.Parameters["sequence_start"] = &triton.InferParameter{ParameterChoice: &triton.InferParameter_BoolParam{BoolParam: false}}
modelInferRequest.Parameters["sequence_end"] = &triton.InferParameter{ParameterChoice: &triton.InferParameter_BoolParam{BoolParam: false}},
 but the receiving after sending the data still exits after reaching the timeout period, and the server does not see the parsing incoming parameters parsing log for

**Comment by lywyue** [comment]
I solve it
