### ISSUE TITLE
Implicit State Management in Pytorch

### ISSUE THREAD

**Issue by jamied157** [triton-inference-server/server#5609]
**Is your feature request related to a problem? Please describe.**
Implicit state management is a really useful feature for us, it avoids a lot of the issues around syncing up the internal state of the model with triton's state. It would be useful to port this feature to the Pytorch backend.

This is potentially something I could look into implementing so it would be good to discuss specifics of how this might work. The onnxruntime implementation seems quite straightforward: https://github.com/triton-inference-server/onnxruntime_backend/blob/main/src/onnxruntime.cc#L143 so I could look into copying that.

**Describe the solution you'd like**
A similar feature to the ones in onnxruntime and tensorRT

**Describe alternatives you've considered**
Managing the state internally, but that has a bunch of difficulties.

**Comment by krishung5** [comment]
@Tabrizian Would this be some feasible enhancement for Pytorch backend?

**Comment by jamied157** [comment]
I've made a PR for this feature now, is anyone able to review it?

**Comment by Tabrizian** [comment]
Sorry, I missed this message. Thanks for your contribution! I can definitely help with reviewing/testing this PR.

**Comment by dyastremsky** [comment]
Closing issue, as discussion is happening in the pull request.
