### ISSUE TITLE
CMake Error at /usr/share/cmake-3.25/Modules/ExternalProject.cmake:3115 (message):   No download info given for 'triton-server' and its source directory:

### ISSUE THREAD

**Issue by huyhoang18112k2** [triton-inference-server/server#5645]
Describe the bug
when i run the build.py
cmake fails with the following errors:

**Triton Information**
2.33.0dev

Are you using the Triton container or did you build it yourself?
I'm building Triton container via Docker

CMake Error at /usr/share/cmake-3.25/Modules/ExternalProject.cmake:3115 (message):
  No download info given for 'triton-server' and its source directory:

   /workspace/src

  is not an existing non-empty directory.  Please specify one of:

   * SOURCE_DIR with an existing non-empty directory
   * DOWNLOAD_COMMAND
   * URL
   * GIT_REPOSITORY
   * SVN_REPOSITORY
   * HG_REPOSITORY
   * CVS_REPOSITORY and CVS_MODULE
Call Stack (most recent call first):
  /usr/share/cmake-3.25/Modules/ExternalProject.cmake:4185 (_ep_add_download_command)
  CMakeLists.txt:186 (ExternalProject_Add)

**Comment by kthui** [comment]
Hi @huyhoang18112k2, can you provide the command you used to run the `build.py`?

**Comment by tanmayv25** [comment]
Closing because of the lack of activity. Please share requested information for further assistance.
