### ISSUE TITLE
How does windows11 compile triton locally?

### ISSUE THREAD

**Issue by tuobaye11** [triton-inference-server/server#5647]
How does windows11 compile triton locally？

Could you make a tutorial？

**Comment by tuobaye11** [comment]
I mean: how does windows11 build triton locally？

**Comment by kthui** [comment]
It would be similar to [building for Windows 10](https://github.com/triton-inference-server/server/blob/main/docs/customization_guide/build.md#building-for-windows-10). Did you run into any issue when following the steps on Windows 11?

**Comment by tanmayv25** [comment]
closing the issue because of the lack of activity.
