### ISSUE TITLE
Best practice for an input pair <I_1, I,2>^0, ..., <I_1, I,2>^N

### ISSUE THREAD

**Issue by shaked571** [triton-inference-server/server#5648]
Hi, 
I have a text classficitaion model (with 3 classes). My business logic consists of 2 parts`Part A and  Part B` when in the in the post processing I apply another Binaric model that its input is the 2 predictions `Part A^` `and Part B^` and classify it to a Binaric 

So the flow is:
[Part A, PartB] -> Model_1(Part A), Model_1(Part B) -> Model2 (Model_1(Part A), Model_1(Part B))

How should I write the config in Triton to support such a scenario? I know I should use the ensemble, but it seem that ifI create 2 models, it would load 2 instances of Model_1 and I don't think it is neccesry.

P.S
It is similar in some way to a siamese network in a sense I wish to foe each sample 2 different inputs to the same model

Any help would be appreciated

**Comment by kthui** [comment]
Hi, I think ensemble will re-use "Model_1" if it is the same model for part A and B, so it will only be loaded once.

> it would load 2 instances of Model_1

I wonder if you mean the [Instance Groups](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/model_configuration.md#instance-groups) setting on Triton? In this case, you could change the config to load the desired number of instances you want.

**Comment by tanmayv25** [comment]
closing because of the lack of activity. Please reach out if you still have some questions.
