### ISSUE TITLE
Unable to run Onnx model converted databricks/dolly-v1-6b (GPT-J)

### ISSUE THREAD

**Issue by msinha251** [triton-inference-server/server#5661]
**Description**
I am trying to run an Onnx model converted from [databricks/dolly-v1-6b (GPT-J)](https://huggingface.co/databricks/dolly-v1-6b) on Triton Server for inferencing. But Getting below error:

```
| dolly_v1_6b_onnx | 1       | UNAVAILABLE: Internal: onnx runtime error 6: Exception during initialization: /workspace/onnxruntime/onnxruntime/core/framework/bfc_arena.cc:368 void* onnxruntime::BFCArena::AllocateRawInternal(size_t, bool, onnxruntime::Stream*, bool, onnxruntime::WaitNotificationFn) 
Failed to allocate memory for requested buffer of size 268435456 |
....
....
....
I0419 14:01:47.068125 1 server.cc:284] Waiting for in-flight requests to complete.
I0419 14:01:47.068131 1 server.cc:300] Timeout 30: Found 0 model versions that have in-flight inferences
I0419 14:01:47.068135 1 server.cc:315] All models are stopped, unloading models
I0419 14:01:47.068138 1 server.cc:322] Timeout 30: Found 0 live models and 0 in-flight non-inference requests
error: creating server: Internal - failed to load all models
```

I am using EC2 GPU Instance (g5.48xlarge) with 1000 gb storage space.

**Triton Information**
What version of Triton are you using?
23.03-py3

Are you using the Triton container or did you build it yourself?
Using Triton Docker container.

**To Reproduce**
Steps to reproduce the behavior.
1. Cloned https://github.com/triton-inference-server/server.git
2. Converted databricks/dolly-v1-6b model to Onnx using command:
    > python -m transformers.onnx --model=databricks/dolly-v1-6b --atol=5e-5 dolly-v1-6b-onnx/
3. Created required model_repository structure and moved all files from above created `dolly-v1-6b-onnx/` to `model_repository/dolly_v1_6b_onnx/1`
4. Created config.pbtxt:
```
name: "dolly_v1_6b_onnx"
platform: "onnxruntime_onnx"
max_batch_size: 0
input [
  {
    name: "input_ids"
    data_type: TYPE_INT64
    dims: [ -1, -1 ]
  },
  {
    name: "attention_mask"
    data_type: TYPE_INT64
    dims: [ -1, -1 ]
  }
]
output [
  {
    name: "output_0"
    data_type: TYPE_FP32
    dims: [ -1, -1, 50403 ]
  }
]
instance_group [
  {
    kind: KIND_GPU
    gpus: [0]
    count: 1
  },
  {
    kind: KIND_GPU
    gpus: [1]
    count: 1
  },
  {
    kind: KIND_GPU
    gpus: [2]
    count: 1
  }
  ,
  {
    kind: KIND_GPU
    gpus: [3]
    count: 1
  }
]
```
5. Run docker container:
    > docker run --gpus=all --rm --shm-size=16g --ulimit memlock=-1 --ulimit stack=67108864 -p 8000:8000 -p 8001:8001 -p 8002:8002 -v /home/ubuntu/server/local-hf/model_repository:/models nvcr.io/nvidia/tritonserver:23.03-py3 tritonserver --model-repository=/models --cuda-memory-pool-byte-size=0:25769803776 --cuda-memory-pool-byte-size=1:25769803776 --cuda-memory-pool-byte-size=2:25769803776 --cuda-memory-pool-byte-size=3:25769803776

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
I am able to run the converted onnx model with below script:
```
import numpy as np
import onnxruntime as ort

model_path = "./local-hf/model_repository/dolly_v1_6b_onnx/1/model.onnx"
input_ids = np.array([[16594,   257,  6126,   284, 10400,   360,  5098,    11, 27140,    44,   422, 16092, 397, 23706]]).astype(np.int64)
attention_mask = np.ones_like(input_ids).astype(np.int64)

input_dict = {
    "input_ids": input_ids,
    "attention_mask": attention_mask
}

session = ort.InferenceSession(model_path)
input_names = [input.name for input in session.get_inputs()]
output_name = session.get_outputs()[0].name

input_feed = {name: input_dict[name] for name in input_names}

result = session.run([output_name], input_feed)
print(result)
```

**Expected behavior**
Docker container should run without any failure.

**Comment by kthui** [comment]
Hi @msinha251, I was able to replicate the `Failed to allocate memory for requested buffer of size 268435456` error, but if I reduce the `--cuda-memory-pool-byte-size` (i.e. `--cuda-memory-pool-byte-size=0:15769803776 --cuda-memory-pool-byte-size=1:15769803776 --cuda-memory-pool-byte-size=2:15769803776 --cuda-memory-pool-byte-size=3:15769803776`), the error went away.

There were two config errors (i.e. `UNAVAILABLE: Invalid argument: unexpected inference output 'output_0', allowed outputs are: last_hidden_state`) after fixing the memory error. I was able to address the config errors by updating the `config.pbtxt` output to:
```
output [
  {
    name: "last_hidden_state"
    data_type: TYPE_FP32
    dims: [ -1, -1, -1 ]
  }
]
```
and the model loaded successfully
```
+------------------+---------+--------+
| Model            | Version | Status |
+------------------+---------+--------+
| dolly_v1_6b_onnx | 1       | READY  |
+------------------+---------+--------+
```

**Comment by msinha251** [comment]
Thanks @kthui for checking on this.

I have also tried with 15769803776, but unfortunately It still errored out. I have also tried restarting my instance, but no luck.
Do you have any more suggestions ?  

Docker run command:
`docker run --gpus=all --rm --shm-size=16g --ulimit memlock=-1 --ulimit stack=67108864 -p 8000:8000 -p 8001:8001 -p 8002:8002 -v /home/ubuntu/server/local-hf/model_repository:/models nvcr.io/nvidia/tritonserver:23.03-py3 tritonserver --model-repository=/models --cuda-memory-pool-byte-size=0:15769803776 --cuda-memory-pool-byte-size=1:15769803776 --cuda-memory-pool-byte-size=2:15769803776 --cuda-memory-pool-byte-size=3:15769803776`


Error:
`| dolly_v1_6b_onnx | 1       | UNAVAILABLE: Internal: onnx runtime error 6: Exception during initialization: /workspace/onnxruntime/onnxruntime/core/framework/bfc_arena.cc:368 void* onnxruntime::BFCArena::AllocateRawInternal(size_t, bool, onnxruntime::Stream*, bool, onnxruntime::WaitNotificationFn) Failed to allocate memory for requested buffer of size 268435456 |`

**Comment by kthui** [comment]
Hi @msinha251, can you try reduce the size further, or even remove the four `--cuda-memory-pool-byte-size` flags? My replication was not on AWS, so we could be running on hardware with slightly different capability.

**Comment by msinha251** [comment]
Hi @kthui I have tried couple of combinations, but still it's same. I have also reduced the gpu's and also increased the gpu's. but it's same:

error:
`| dolly_v1_6b_onnx | 1       | UNAVAILABLE: Internal: onnx runtime error 6: Exception during initialization: /workspace/onnxruntime/onnxruntime/core/framework/bfc_arena.cc:368 void* onnxruntime::BFCArena::AllocateRawInternal(size_t, bool, onnxruntime::Stream*, bool, onnxruntime::WaitNotificationFn) Failed to allocate memory for requested buffer of size 268435456 |`

Do you have any recommandation for troubleshooting it further ?

Thanks

**Comment by kthui** [comment]
Hi msinha251, the cluster I ran on has 4 GPUs and each has about 45GB of memory. I hope this helps.

**Comment by tanmayv25** [comment]
Closing the issue because of the lack of activity. Please reach out if you are still running into problems.
