### ISSUE TITLE
cmake failed！ 

### ISSUE THREAD

**Issue by ltdo111** [triton-inference-server/server#5676]
**Description**
When I compile triton in buildbase container using cmake,  occurred error！
such as blow : 
![image](https://user-images.githubusercontent.com/17394163/233527904-4e8fffa5-901c-4f35-a8c5-32fe0909c77f.png)

![image](https://user-images.githubusercontent.com/17394163/233529098-b00bb84c-aa60-4090-a1ac-faefff4a9c23.png)

**Triton Information**
the main. repo 

Are you using the Triton container or did you build it yourself?
build it by myself

**To Reproduce**
**step 1: generate build script**
```
python3 build.py --target-machine=x86_64 --enable-logging --enable-stats --enable-tracing --endpoint=grpc --endpoint=http --repo-tag=common:main --repo-tag=core:main --repo-tag=backend:main --repo-tag=thirdparty:main --backend=ensemble --backend=onnxruntime:main --backend=python:main   --build-type=Debug  --dryrun
```

**step2: docker build  the buildbase image** 
```Generate a build folder, enter the folder, and execute the following command
If it is an arm host, you need to execute docker pull --platform=x86_64 ubuntu:20.04 to pull down the x86 base image (skip the x86 host)
docker build -t tritonserver_buildbase -f ./Dockerfile.buildbase .
Generate a base image
```

**step3: Mount the native code and run the build container generated by step2, and execute sh +x cmake_build**
**mount cmd** docker run -it  -v /Users/bofeng/tl/server:/workspace -v  /Users/bofeng/tl/server/tritonbuild:/tmp/tritonbuild 86779b6f609f /bin/bash
container internal files： 
![image](https://user-images.githubusercontent.com/17394163/233528905-6fe09706-281d-465f-80c3-06bebeb51b99.png)
As you can see, I moved the cmake_build script from the build folder to the project root

**Expected behavior**
**segement 1**
[ 17%] Performing configure step for 'libevhtp'
cd /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/libevhtp/src/libevhtp-build && /usr/bin/cmake "-GUnix Makefiles" -C/tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/libevhtp/tmp/libevhtp-cache-Debug.cmake /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp
loading initial cache file /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/libevhtp/tmp/libevhtp-cache-Debug.cmake
Re-run cmake no build system arguments
CMake Warning (dev) at /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (ONIGURUMA)
  does not match the name of the calling package (Oniguruma).  This can lead
  to problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/FindOniguruma.cmake:26 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/options.cmake:8 (find_package)
  CMakeLists.txt:11 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find ONIGURUMA (missing: ONIGURUMA_LIBRARY ONIGURUMA_INCLUDE_DIR) 
CMake Warning (dev) at /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (LIBEVENT)
  does not match the name of the calling package (Libevent).  This can lead
  to problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/FindLibevent.cmake:33 (find_package_handle_standard_args)
  CMakeLists.txt:62 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find LIBEVENT (missing: LIBEVENT_LIBRARIES LIBEVENT_INCLUDE_DIR) 

-- EVHTP_VERSION            :  1.2.18
-- EVHTP_DISABLE_SSL        :  ON
-- EVHTP_DISABLE_EVTHR      :  OFF
-- EVHTP_DISABLE_REGEX      :  ON
-- EVHTP_BUILD_SHARED       :  
-- EVHTP_USE_JEMALLOC       :  
-- EVHTP_USE_TCMALLOC       :  

-- CMAKE_BUILD_TYPE         : Debug
-- CMAKE_INSTALL_PREFIX     : /tmp/tritonbuild/tritonserver/build/third-party/libevhtp
-- CMAKE_BINARY_DIR         : /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/libevhtp/src/libevhtp-build
-- CMAKE_CURRENT_BINARY_DIR : /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/libevhtp/src/libevhtp-build
-- CMAKE_CURRENT_SOURCE_DIR : /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp
-- PROJECT_BINARY_DIR       : /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/libevhtp/src/libevhtp-build
-- PROJECT_SOURCE_DIR       : /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp
-- CMAKE_MODULE_PATH        : /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/cmake
-- CMAKE_SYSTEM_NAME        : Linux
-- CMAKE_SYSTEM_VERSION     : 5.15.49-linuxkit
-- CMAKE_C_COMPILER         : /usr/bin/cc
-- CMAKE_AR                 : /usr/bin/ar
-- CMAKE_RANLIB             : /usr/bin/ranlib
-- CFLAGS                   :   
                              -g

-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/LIBEVENT_INCLUDE_DIR
   used as include directory in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp
LIBEVENT_CORE
    linked by target "evhtp" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp
    linked by target "test_extensive" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "test_proxy" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "test_basic" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "test_vhost" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "test_client" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "test_query" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "test_perf" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "example_request_fini" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "example_chunked" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "example_pause" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "example_vhost" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "example_basic" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
LIBEVENT_EXTRA
    linked by target "evhtp" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp
    linked by target "evhtp" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp
    linked by target "test_extensive" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "test_extensive" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "test_proxy" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "test_proxy" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "test_basic" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "test_basic" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "test_vhost" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "test_vhost" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "test_client" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "test_client" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "test_query" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "test_query" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "test_perf" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "test_perf" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "example_request_fini" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "example_request_fini" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "example_chunked" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "example_chunked" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "example_pause" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "example_pause" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "example_vhost" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "example_vhost" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "example_basic" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "example_basic" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
LIBEVENT_LIBRARY
    linked by target "evhtp" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp
    linked by target "test_extensive" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "test_proxy" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "test_basic" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "test_vhost" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "test_client" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "test_query" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "test_perf" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "example_request_fini" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "example_chunked" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "example_pause" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "example_vhost" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "example_basic" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
LIBEVENT_THREAD
    linked by target "evhtp" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp
    linked by target "test_extensive" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "test_proxy" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "test_basic" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "test_vhost" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "test_client" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "test_query" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "test_perf" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "example_request_fini" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "example_chunked" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "example_pause" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "example_vhost" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples
    linked by target "example_basic" in directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/examples

CMake Error in CMakeLists.txt:
  Target "evhtp" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "/tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/LIBEVENT_INCLUDE_DIR-NOTFOUND"

  which is prefixed in the source directory.
  
  
  **segement 2: **
  make[4]: Leaving directory '/tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/curl/src/curl-build'
/usr/bin/cmake -E cmake_progress_start /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/curl/src/curl-build/CMakeFiles 0
make  -f CMakeFiles/Makefile2 preinstall
make[4]: Entering directory '/tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/curl/src/curl-build'
make[4]: Nothing to be done for 'preinstall'.
make[4]: Leaving directory '/tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/curl/src/curl-build'
Install the project...
/usr/bin/cmake -P cmake_install.cmake
-- Install configuration: "Debug"
-- Up-to-date: /tmp/tritonbuild/tritonserver/build/third-party/curl/lib/libcurl-d.a
-- Up-to-date: /tmp/tritonbuild/tritonserver/build/third-party/curl/bin/curl-config
-- Up-to-date: /tmp/tritonbuild/tritonserver/build/third-party/curl/lib/pkgconfig/libcurl.pc
-- Up-to-date: /tmp/tritonbuild/tritonserver/build/third-party/curl/include/curl
-- Up-to-date: /tmp/tritonbuild/tritonserver/build/third-party/curl/include/curl/curl.h
-- Up-to-date: /tmp/tritonbuild/tritonserver/build/third-party/curl/include/curl/curlver.h
-- Up-to-date: /tmp/tritonbuild/tritonserver/build/third-party/curl/include/curl/easy.h
-- Up-to-date: /tmp/tritonbuild/tritonserver/build/third-party/curl/include/curl/header.h
-- Up-to-date: /tmp/tritonbuild/tritonserver/build/third-party/curl/include/curl/mprintf.h
-- Up-to-date: /tmp/tritonbuild/tritonserver/build/third-party/curl/include/curl/multi.h
-- Up-to-date: /tmp/tritonbuild/tritonserver/build/third-party/curl/include/curl/options.h
-- Up-to-date: /tmp/tritonbuild/tritonserver/build/third-party/curl/include/curl/stdcheaders.h
-- Up-to-date: /tmp/tritonbuild/tritonserver/build/third-party/curl/include/curl/system.h
-- Up-to-date: /tmp/tritonbuild/tritonserver/build/third-party/curl/include/curl/typecheck-gcc.h
-- Up-to-date: /tmp/tritonbuild/tritonserver/build/third-party/curl/include/curl/urlapi.h
-- Up-to-date: /tmp/tritonbuild/tritonserver/build/third-party/curl/include/curl/websockets.h
-- Up-to-date: /tmp/tritonbuild/tritonserver/build/third-party/curl/lib/cmake/CURL/CURLTargets.cmake
-- Up-to-date: /tmp/tritonbuild/tritonserver/build/third-party/curl/lib/cmake/CURL/CURLTargets-debug.cmake
-- Up-to-date: /tmp/tritonbuild/tritonserver/build/third-party/curl/lib/cmake/CURL/CURLConfigVersion.cmake
-- Up-to-date: /tmp/tritonbuild/tritonserver/build/third-party/curl/lib/cmake/CURL/CURLConfig.cmake
make[3]: Leaving directory '/tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/curl/src/curl-build'
cd /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/curl/src/curl-build && /usr/bin/cmake -E touch /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/curl/src/curl-stamp/curl-install
[ 27%] Completed 'curl'
cd /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build && /usr/bin/cmake -E make_directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/CMakeFiles
cd /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build && /usr/bin/cmake -E touch /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/CMakeFiles/curl-complete
cd /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build && /usr/bin/cmake -E touch /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/curl/src/curl-stamp/curl-done
make[2]: Leaving directory '/tmp/tritonbuild/tritonserver/build'
[ 28%] Built target curl

install_src: removing /tmp/tritonbuild/tritonserver/build/third-party-src/grpc_1.48.0/.git
install_src: removing /tmp/tritonbuild/tritonserver/build/third-party-src/grpc_1.48.0/.github
install_src: removing /tmp/tritonbuild/tritonserver/build/third-party-src/grpc_1.48.0/third_party/abseil-cpp/.github
install_src: removing /tmp/tritonbuild/tritonserver/build/third-party-src/grpc_1.48.0/third_party/benchmark/.github
install_src: removing /tmp/tritonbuild/tritonserver/build/third-party-src/grpc_1.48.0/third_party/bloaty/.github
install_src: removing /tmp/tritonbuild/tritonserver/build/third-party-src/grpc_1.48.0/third_party/bloaty/third_party/abseil-cpp/.github
install_src: removing /tmp/tritonbuild/tritonserver/build/third-party-src/grpc_1.48.0/third_party/bloaty/third_party/protobuf/.github
install_src: removing /tmp/tritonbuild/tritonserver/build/third-party-src/grpc_1.48.0/third_party/boringssl/.git
install_src: removing /tmp/tritonbuild/tritonserver/build/third-party-src/grpc_1.48.0/third_party/boringssl/.github
install_src: removing /tmp/tritonbuild/tritonserver/build/third-party-src/grpc_1.48.0/third_party/boringssl-with-bazel/.github
install_src: removing /tmp/tritonbuild/tritonserver/build/third-party-src/grpc_1.48.0/third_party/googleapis/.github
install_src: removing /tmp/tritonbuild/tritonserver/build/third-party-src/grpc_1.48.0/third_party/googletest/.github
install_src: removing /tmp/tritonbuild/tritonserver/build/third-party-src/grpc_1.48.0/third_party/libuv/.github
install_src: removing /tmp/tritonbuild/tritonserver/build/third-party-src/grpc_1.48.0/third_party/opencensus-proto/.github
install_src: removing /tmp/tritonbuild/tritonserver/build/third-party-src/grpc_1.48.0/third_party/opentelemetry/.github
install_src: removing /tmp/tritonbuild/tritonserver/build/third-party-src/grpc_1.48.0/third_party/protobuf/.github
install_src: removing /tmp/tritonbuild/tritonserver/build/third-party-src/grpc_1.48.0/third_party/re2/.github
install_src: removing /tmp/tritonbuild/tritonserver/build/third-party-src/grpc_1.48.0/third_party/upb/.github
cd /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo/src/grpc && /usr/bin/cmake -E touch /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo/src/grpc-repo-stamp/grpc-repo-patch
[ 30%] No configure step for 'grpc-repo'
cd /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo/src/grpc-repo-build && /usr/bin/cmake -E echo_append
cd /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo/src/grpc-repo-build && /usr/bin/cmake -E touch /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo/src/grpc-repo-stamp/grpc-repo-configure
[ 30%] No build step for 'grpc-repo'
cd /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo/src/grpc-repo-build && /usr/bin/cmake -E echo_append
cd /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo/src/grpc-repo-build && /usr/bin/cmake -E touch /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo/src/grpc-repo-stamp/grpc-repo-build
[ 30%] No install step for 'grpc-repo'
cd /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo/src/grpc-repo-build && /usr/bin/cmake -E echo_append
cd /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo/src/grpc-repo-build && /usr/bin/cmake -E touch /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo/src/grpc-repo-stamp/grpc-repo-install
[ 30%] No test step for 'grpc-repo'
cd /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo/src/grpc-repo-build && /usr/bin/cmake -E echo_append
cd /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo/src/grpc-repo-build && /usr/bin/cmake -E touch /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo/src/grpc-repo-stamp/grpc-repo-test
[ 31%] Completed 'grpc-repo'
cd /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build && /usr/bin/cmake -E make_directory /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/CMakeFiles
cd /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build && /usr/bin/cmake -E touch /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/CMakeFiles/grpc-repo-complete
cd /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build && /usr/bin/cmake -E touch /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo/src/grpc-repo-stamp/grpc-repo-done
make[2]: Leaving directory '/tmp/tritonbuild/tritonserver/build'
[ 34%] Built target grpc-repo
make[1]: Leaving directory '/tmp/tritonbuild/tritonserver/build'
make: *** [Makefile:136: all] Error 2

**Comment by ltdo111** [comment]
![image](https://user-images.githubusercontent.com/17394163/233555431-6673b03f-21e0-45e3-bae5-3ac0becc58b1.png)


cd /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/libevhtp/src/libevhtp-build && /usr/bin/cmake "-GUnix Makefiles" -C/tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/libevhtp/tmp/libevhtp-cache-Debug.cmake /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp
loading initial cache file /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/libevhtp/tmp/libevhtp-cache-Debug.cmake
Re-run cmake no build system arguments
CMake Warning (dev) at /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (ONIGURUMA)
  does not match the name of the calling package (Oniguruma).  This can lead
  to problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/FindOniguruma.cmake:26 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/options.cmake:8 (find_package)
  CMakeLists.txt:11 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find ONIGURUMA (missing: ONIGURUMA_LIBRARY ONIGURUMA_INCLUDE_DIR) 
CMake Warning (dev) at /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (LIBEVENT)
  does not match the name of the calling package (Libevent).  This can lead
  to problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/FindLibevent.cmake:33 (find_package_handle_standard_args)
  CMakeLists.txt:62 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find LIBEVENT (missing: LIBEVENT_LIBRARIES LIBEVENT_INCLUDE_DIR) 

-- EVHTP_VERSION            :  1.2.18
-- EVHTP_DISABLE_SSL        :  ON
-- EVHTP_DISABLE_EVTHR      :  OFF
-- EVHTP_DISABLE_REGEX      :  ON
-- EVHTP_BUILD_SHARED       :  
-- EVHTP_USE_JEMALLOC       :  
-- EVHTP_USE_TCMALLOC       :  

-- CMAKE_BUILD_TYPE         : Debug
-- CMAKE_INSTALL_PREFIX     : /tmp/tritonbuild/tritonserver/build/third-party/libevhtp
-- CMAKE_BINARY_DIR         : /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/libevhtp/src/libevhtp-build
-- CMAKE_CURRENT_BINARY_DIR : /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/libevhtp/src/libevhtp-build
-- CMAKE_CURRENT_SOURCE_DIR : /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp
-- PROJECT_BINARY_DIR       : /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/libevhtp/src/libevhtp-build
-- PROJECT_SOURCE_DIR       : /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp
-- CMAKE_MODULE_PATH        : /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/cmake
-- CMAKE_SYSTEM_NAME        : Linux
-- CMAKE_SYSTEM_VERSION     : 5.15.49-linuxkit
-- CMAKE_C_COMPILER         : /usr/bin/cc
-- CMAKE_AR                 : /usr/bin/ar
-- CMAKE_RANLIB             : /usr/bin/ranlib
-- CFLAGS                   :   
                              -g

-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/LIBEVENT_INCLUDE_DIR

**Comment by ltdo111** [comment]
**main information**
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-src/libevhtp/libevhtp/LIBEVENT_INCLUDE_DIR

**Comment by ltdo111** [comment]
--build-type=Debug   perform to make a debug version

**Comment by ltdo111** [comment]
_deps/repo-third-party-build/libevhtp/src/libevhtp-build/CMakeCache.txt 

![image](https://user-images.githubusercontent.com/17394163/233567973-b8961d61-3d9d-41de-9850-c5c9d0fbe198.png)

all be NOTFOUND ， how to solve it；

**Comment by ltdo111** [comment]
![image](https://user-images.githubusercontent.com/17394163/233627647-450993c3-e242-41fb-b4b5-cc7e5dea4156.png)

**Comment by kthui** [comment]
Hi @ltdo111, `build.py` is capable of building all the images automatically, without the `--dryrun` flag, which the manual step of invoking docker command for generating the docker buildbase image will not be necessary. I think it is possible that some of the dependency library is lost between the manual steps. Would you be able to try the steps outlined on the [building with docker](https://github.com/triton-inference-server/server/blob/main/docs/customization_guide/build.md#building-with-docker) documentation?

**Comment by ltdo111** [comment]
@kthui thank you, sir!
I know what you want to express, what I mean by manual execution is to clearly understand the whole construction process;
First of all, I mapped the third-party library downloaded during project compilation to the local by mounting and running docker -v. I don’t know if the problem of cmake failed is caused by local mounting? The reason for mounting is to stop downloading third-party dependent libraries in the future;

Secondly, I am wondering if I have already downloaded the third-party libraries that cmake depends on, will it speed up when compiling the project again? Because the operation of downloading third-party libraries is missing;

Finally, there is another problem, that is, the grpc-repo code base is too large, about 2G, is there any way to speed up the compilation speed?

**Comment by ltdo111** [comment]
I found the problem, because I mounted the tritonbuild directory to run locally

**Comment by oandreeva-nv** [comment]
@ltdo111 May I ask if you need any further assistance or I can close this issue?

**Comment by mujahiddh** [comment]
I am facing a similar issue, i posted details [here](https://github.com/triton-inference-server/server/issues/6654) will really appreciate any help on this
