### ISSUE TITLE
how can i get a C++backends

### ISSUE THREAD

**Issue by prz30** [triton-inference-server/server#5679]
Sorry, I want to know, how can I get a C++ backends, I can use this backends to perform some pre-processing or post-processing operations based on C++, is there any official C++ backends?

**Comment by kthui** [comment]
Hi @prz30, you can write your own backend if you are going to use C++. There is a [FAQ](https://github.com/triton-inference-server/backend#how-can-i-develop-my-own-triton-backend) and [tutorial](https://github.com/triton-inference-server/backend/blob/main/examples/README.md) for developing you own backend.

**Comment by tanmayv25** [comment]
Closing because of the lack of activity. 
FYI: All of the triton backends are written in C++.
