### ISSUE TITLE
Alternatives to increasing shared memory

### ISSUE THREAD

**Issue by jerome-ai** [triton-inference-server/server#5681]
I'm unable to complete inference between I've run out of shared memory:

> tritonclient.utils.InferenceServerException: Failed to increase the shared memory pool size for key 'triton_python_backend_shm_region_2' to 67108864 bytes. If you are running Triton inside docker, use '--shm-size' flag to control the shared memory region size. Error: No space left on device

Unfortunately, the environment in which I'm running the image (Fargate) [does not support](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_linuxparameters:~:text=parameter%20isn%27t%20supported.-,sharedMemorySize,-The%20value%20for) using that flag.

Are there any alternate methods available for increasing this memory pool?

**Comment by kthui** [comment]
Hi @jerome-ai, the shared memory size available inside the container is controlled by docker. I think you might have to raise an issue with AWS if they are restricting the shared memory size.

**Comment by jerome-ai** [comment]
Thanks! That was my fear. However, I noticed several memory options available at server start time:

```bash
$> tritonserver --help
...
  --pinned-memory-pool-byte-size <integer> ...
  --cuda-memory-pool-byte-size <<integer>:<integer>> ...
  --response-cache-byte-size <integer> ...
...
```

There also seem to be some client-side methods ([this](https://github.com/triton-inference-server/client/blob/94a78d1c803522c9c34a9ae1b4127676934a0344/src/python/library/tritonclient/http/__init__.py#L1016-L1022) and related) that pertain to memory.

For each, I've read their documentation to the best of my ability. I was hoping there was something I missed, or misinterpreted, that would allow me shared memory control within the Triton-sphere.
