### ISSUE TITLE
With ensemble mode submodel can run in different gpus, like pipeline parallelism

### ISSUE THREAD

**Issue by Oldpan** [triton-inference-server/server#5683]
Now Triton supports ensemble mode but does not support submodel running on different GPUs. For example, if I have an LLM and split it into many small models, can I put some of the models on the first GPU and the other part on the second GPU, then run these models like a pipeline? Is this function achievable?

**Comment by kthui** [comment]
Hi @Oldpan, each model under an ensemble model is a Triton model, which I think you can control which model will run on which GPU by the [instance group](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/model_configuration.md#instance-groups) settings of the model.

**Comment by Oldpan** [comment]
@kthui Thanks, I'll try this out and see if it can be implemented.
