### ISSUE TITLE
Docs for Parameters Support by Triton Backends

### ISSUE THREAD

**Issue by ankit-db** [triton-inference-server/server#5688]
**Is your feature request related to a problem? Please describe.**
I don't see anywhere where all the parameters that are supported in a Triton model configuration are documented in a single place. I see them supported in various different places for particular backends. Is it possible to have good docs?

**Describe the solution you'd like**
A docs page that documents all the parameters that are supported and for which backends

**Describe alternatives you've considered**
The status quo is the alternative and it is not great

**Additional context**

**Comment by oandreeva-nv** [comment]
Thanks for proposing this!

Anyone can develop a Triton backend, so it isn't possible for us to know about all available backends and their parameters. The Triton project does provide a [set of supported backends](https://github.com/triton-inference-server/backend#where-can-i-find-all-the-backends-that-are-available-for-triton) that are tested and updated with each Triton release. We recommend to refer to each backend's README for the most up-to-date information, including backend-specific parameters to configure a Triton model instance. 

Considering the nature of active development and contributions from the Triton Server community, it may happen, that the unified document page may diverge from what is described in backends' README and introduce an undesirable confusion among users.

I'll open a ticket for the team to discuss a potential solution, meanwhile feel free to create a PR or describe a potential solution in more details.

**Comment by ankit-db** [comment]
@oandreeva-nv I totally understand this concern - are there no parameters that Triton expects in general?

**Comment by oandreeva-nv** [comment]
Sure, please refer to  "Writing a Model Configuration [[Overview](https://github.com/triton-inference-server/server/blob/main/docs/README.md#model-configuration) || [Details](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/model_configuration.md)]" part of User Documentation.

Additionally, you can also check out our tutorials: [Model Deployment](https://github.com/triton-inference-server/tutorials/tree/main/Conceptual_Guide/Part_1-model_deployment#model-configuration)

Let me know if this is what you were looking for.
