### ISSUE TITLE
Output response Parsing Error

### ISSUE THREAD

**Issue by deepkshikha** [triton-inference-server/server#5690]
I am using Triton on Vertex. Where I have pre-processing, ml model and post processing. The response I am getting is as below

{"model_name":"ensemble_model","model_version":"1","parameters":{"sequence_id":0,"sequence_start":false,"sequence_end":false},"outputs":[{"name":"output_0","datatype":"UINT8","shape":[17],"parameters":{"binary_data_size":17}}]}
troy bilt starter
 
 
Below is the code snippet after ml-model and post-processing.
 
            corrected_query_numpy = np.fromstring(corrected_query, dtype='uint8')
            corrected_query_tensor=pb_utils.Tensor("output_0",corrected_query_numpy)
            inference_response = pb_utils.InferenceResponse(output_tensors=[corrected_query_tensor])
            responses.append(inference_response)
            return(responses)
 
My question here is:
Instead of entire response can we only pass final output i.e. troy bilt starter??

**Comment by tanmayv25** [comment]
closing because of the lack of activity. please provide the requested information if still seeing an issue.
