### ISSUE TITLE
protobuf version used

### ISSUE THREAD

**Issue by vovachernin** [triton-inference-server/server#5693]
Hi!
I trying to compile with triton client  c++ protobuf sources to my project but i have grpc_service.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
what branch /tag used latest protobuf version ?
Thanks

**Comment by oandreeva-nv** [comment]
Hi @vovachernin, we are build protobuf project from grpc-repo, which is protobuf 3.19.4.0, but we apply a patch that is available in 3.20.0, to resolve a linking issue on Windows. You can find more information on this here: https://github.com/triton-inference-server/third_party/blob/main/CMakeLists.txt#L135

**Comment by vovachernin** [comment]
hi! what tag version of triton client source contain protobuf [Protocol Buffers v20.0] and later?
what last version of protobuf is supported and compiled with triton client?
thank you

**Comment by oandreeva-nv** [comment]
I believe the latest protobuf version we support is 3.19.4.0.

Could you please provide more information regarding your issue? You can follow the process outlined [here](https://github.com/triton-inference-server/server#reporting-problems-asking-questions). 

This will help us in reproducing your issue.

**Comment by tanmayv25** [comment]
Closing the issue because of the lack of activity. Please provide the above info if still seeing an issue.
