### ISSUE TITLE
Support instance group of type 'MODEL' in pytorch backend

### ISSUE THREAD

**Issue by NadavShmayo** [triton-inference-server/server#5694]
**Is your feature request related to a problem? Please describe.**
I have a large model from the transformers python library which doesn't fit a single GPU and I want to run it using Triton.
I've already compiled the model to TorchScript format so it partitions the model across 2 different GPUs, and when I load the model in a Python environment using torch.jit.load it works as expected, partitioning the model across the 2 GPUs.
When I try to load the compiled model in Triton using the Pytorch backend, it tries to allocate the whole model to a single GPU, causing the model to fail loading as CUDA runs out of memory.

**Describe the solution you'd like**
Allow to use instance group of type 'MODEL' in the Pytorch backend, so if a model is defined with the 'MODEL' instance group type, the Pytorch backend won't select the device for the model, and will simply load the model as is.

**Describe alternatives you've considered**
There are not many alternatives available, as ONNX doesn't allow multi GPU runs as far as I know.

**Additional context**
I believe that in order to solve this problem, there should be another case in the code for loading the model in the Pytorch backend, which specifically refers to the 'MODEL' instance group type.
In pseudo-code:
```
if instance_group_type == 'MODEL':
    model = torch.jit.load(model_path)
else:
    model = torch.jit.load(model_path, device=device)
```

**Comment by tanmayv25** [comment]
> I've already compiled the model to TorchScript format so it partitions the model across 2 different GPUs, and when I load the model in a Python environment using torch.jit.load it works as expected, partitioning the model across the 2 GPUs. 

This looks like an important feature. It would need an update to the LoadModel call [here](https://github.com/triton-inference-server/pytorch_backend/blob/33c0bc49a9450b5465bf2001cf7d8f6734d5f23d/src/libtorch.cc#L601).

**Comment by NadavShmayo** [comment]
> Indeed. I talked offline with @krishung5 about this. It seems like it would help resolve this bug too: #5685

Good to hear!
Is there any possibility this feature could be merged before the next version release?

**Comment by NadavShmayo** [comment]
Hey, any updates regarding this issue?

**Comment by NadavShmayo** [comment]
> Hi @NadavShmayo, this is currently on our roadmap and is in progress. Regarding
> 
> > I've already compiled the model to TorchScript format so it partitions the model across 2 different GPUs
> 
> I was wondering if you are using `nn.DataParallel` to split the model across multiple GPUs or just simply using `to(device)` inside the model?

Hi, sorry for the late response.
Frankly, I don't really know how the model is being parallelized across GPU, I just use the transformers python library and when loading the model I pass the `device_map='auto'` parameter, which does the GPU mapping for me.
