### ISSUE TITLE
Accessing model_config of ensemble config.pbtxt

### ISSUE THREAD

**Issue by joshanderson-kw** [triton-inference-server/server#5703]
Hello!

Is it possible to access the model config for an ensemble model, within a python model that is in that ensemble?

For example, I have an ensemble model, A, with a config.pbtxt and some custom parameters, and another python model, B, that is a part of ensemble A. Can I access the custom parameters defined in the model config for A inside of python model B? Such as something like `ensemble_model_config = json.loads(args['ensemble_model_config'])`

Thank you in advance.

**Comment by oandreeva-nv** [comment]
If I understand correctly, you have a model repository similar to this:
```
model_repository/
|-- ensemble_model_A
|   |-- 1
|   `-- config.pbtxt
|-- model_B
|   |-- 1
|   |   `-- model.py
|   `-- config.pbtxt
```
Unfortunately, I don't think that configuration parameters defined in model A's config can be accessed from model_B, especially in python backend (cc @Tabrizian correct me if I am wrong).

As a workaround, I believe it is possible to write a custom python parser to extract parameters, provided a location of config file.

**Comment by Tabrizian** [comment]
It is not possible to use the Python Backend APIs to access the model configuration of another model but you can install triton Python client in your Python backend model to retrieve the model configuration of another model.

**Comment by joshanderson-kw** [comment]
Thank you for the quick responses! I think those should work as workarounds.
