### ISSUE TITLE
Concurrent inferences get mixed up when preprocessing python model runs torch operations on GPU

### ISSUE THREAD

**Issue by eliottsegard** [triton-inference-server/server#5733]
**Description**
Sometimes the detections from one request will show up in another when multiple client are making concurrent requests.

**Triton Information**
We are using a single tritonserver (v22.07) instance on a single GPU, running an ensemble model made up of 3 sub models (preprocessing/detector/postprocessing). We want the pre and post processing to run on GPU and to pass the tensor from one model to the next without making unnecessary copies.  

Are you using the Triton container or did you build it yourself?
We are using the Triton container

**To Reproduce**

Overview of the models:
```
    preprocessing (Python backend)

        receive image as array

        convert to torch tensor, send to GPU using .to("cuda") and runs some basic operations on it

        convert to pbutil tensor using pb_utils.Tensor.from_dlpack(to_dlpack(torch_tensor))

    detection (TRT backend)

        runs inference

    postprocessing (Python backend)

        get results as pb_utils tensor on GPU

        convert to torch tensor using from_dlpack(input_tensor.to_dlpack())

        run NMS

        get results as array with out.detach().cpu().numpy()
```

**Observations:**
- The problem has been narrowed down to the preprocessing model, specifically in the get_image_from_input_tensor method: the problem only appears when we put the pytorch image tensor on GPU. pytorch_image_tensor.to("cuda") (and if we don’t send the tensor to GPU the performance hit is too big to find this an acceptable solution)
- This is very similar to a previous bug we had when running the same three models in a single python script. In that case, the problem was caused by a lack of synchronization between cuda streams and the bug was resolved by using a torch.cuda.stream() context manager to force all cuda operations to happen on the same stream. But in the case of Triton, we (apparently) can't directly chose which stream each model will use.

 
**Attempted fixes:**
- Using torch.cuda.synchronize() after the pytorch_image_tensor.to("cuda") operation in an attempt to wait until all kernel operations on all streams had ended 
- Using torch.cuda.current_stream().synchronize() 
- Using with torch.cuda.stream_context(torch.cuda.default_stream()): to run the .to("cuda") in an attempt to have that operation be in the same stream as the TRT engine
- Using torch.cuda.synchronize() twice in the preprocessing: 
          -once after creating pytorch tensor, sending to gpu and running operations on it but before calling .contiguous() on it
          -another time after instantiating the pb_utils.InferenceResponse  
While this reduced the number of errors greatly (~1000 errors to ~1 error for 5 concurrent clients making 1000 requests each) some errors still remain.

**preprocessing config.pbtxt:**
```
name: "detection-preprocessing"
default_model_filename: "detection_preprocessor.py"
backend: "python"
max_batch_size: 128

input [
    {
        name: "PREPROCESSING_INPUT"
        data_type: TYPE_FP32
        dims: [-1, -1, 3]
    }
]

output [
    {
        name: "PREPROCESSING_OUTPUT"
        data_type: TYPE_FP32
        dims: [3, -1, -1]
    }
]

instance_group [{ kind: KIND_GPU }]
parameters: [
    {key: "FORCE_CPU_ONLY_INPUT_TENSORS" value: {string_value:"no"}},
    {key: "logging_level" value: {string_value: "INFO"}}
]
```
**detector config.pbtxt:**
```
name: "yolov7-core220"
platform: "tensorrt_plan"
max_batch_size: 1

input [
    {
        name: "images"
        data_type: TYPE_FP32
        dims: [3, 480, 640]
    }
]

output [
    {
        name: "output"
        data_type: TYPE_FP32
        dims: [18900, 17]
    }
]
```

**postprocessing config.pbtxt:**
```
name: "detection-postprocessing"
default_model_filename: "detection_postprocessor.py"
backend: "python"
max_batch_size: 128

input [
    {
        name: "POSTPROCESSING_INPUT"
        data_type: TYPE_FP32
        dims: [-1, -1]
    }
]

output [
    {
        name: "POSTPROCESSING_OUTPUT_BOX"
        data_type: TYPE_FP32
        dims: [-1, 4]
    },
    {
        name: "POSTPROCESSING_OUTPUT_SCORE"
        data_type: TYPE_FP32
        dims: [-1, 1]
    },
    {
        name: "POSTPROCESSING_OUTPUT_LABEL"
        data_type: TYPE_FP32
        dims: [-1, 1]
    },
    {
        name: "POSTPROCESSING_OUTPUT_LABEL_STR"
        data_type: TYPE_STRING
        dims: [-1, 1]
    }
]

instance_group [{ kind: KIND_GPU }]
parameters: [
    {key: "FORCE_CPU_ONLY_INPUT_TENSORS" value: {string_value:"no"}},
    {key: "iou_threshold" value: {string_value: "0.5"}},
    {key: "logging_level" value: {string_value: "INFO"}}
]
```
**ensemble model config.pbtxt**
```
name: "yolov7-inference-model-core"
platform: "ensemble"
max_batch_size: 1

input [
    {
        name: "PREPROCESSING_INPUT"
        data_type: TYPE_STRING
        dims: [1]
    }
]
output [
    {
        name: "POSTPROCESSING_OUTPUT_BOX"
        data_type: TYPE_FP32
        dims: [-1, 4]
    },
    {
        name: "POSTPROCESSING_OUTPUT_SCORE"
        data_type: TYPE_FP32
        dims: [-1, 1]
    },
    {
        name: "POSTPROCESSING_OUTPUT_LABEL"
        data_type: TYPE_FP32
        dims: [-1, 1]
    },
    {
        name: "POSTPROCESSING_OUTPUT_LABEL_STR"
        data_type: TYPE_STRING
        dims: [-1, 1]
    }
]

ensemble_scheduling {
    step [
        {
            model_name: "detection-preprocessing-redis"
            model_version: -1
            input_map {
                key: "PREPROCESSING_INPUT"
                value: "PREPROCESSING_INPUT"
            }
            output_map {
                key: "PREPROCESSING_OUTPUT"
                value: "PREPROCESSING_OUTPUT"
            }
        },
        {
            model_name: "yolov7-core220"
            model_version: -1
            input_map {
                key: "images"
                value: "PREPROCESSING_OUTPUT"
            }
            output_map {
                key: "output"
                value: "output"
            }
        },
        {
            model_name: "detection-postprocessing"
            model_version: -1
            input_map {
                key: "POSTPROCESSING_INPUT"
                value: "output"
            }
            output_map {
                key: "POSTPROCESSING_OUTPUT_BOX"
                value: "POSTPROCESSING_OUTPUT_BOX"
            }
            output_map {
                key: "POSTPROCESSING_OUTPUT_SCORE"
                value: "POSTPROCESSING_OUTPUT_SCORE"
            }
            output_map {
                key: "POSTPROCESSING_OUTPUT_LABEL"
                value: "POSTPROCESSING_OUTPUT_LABEL"
            }
            output_map {
                key: "POSTPROCESSING_OUTPUT_LABEL_STR"
                value: "POSTPROCESSING_OUTPUT_LABEL_STR"
            }
        }
    ]
}
```

**Comment by Tabrizian** [comment]
Thanks for filing a detailed bug report. I was wondering whether adding `torch.synchronize` fixed the issue or you are still seeing this issue even after adding the synchronization?

**Comment by eliottsegard** [comment]
When we use torch.cuda.synchronize twice (once before calling `.contiguous()` on the torch tensor and once after instanciating the `pb_utils.InferenceResponse`)  we are seeing a drastic improvement but some mixup still remain.

I don't really have any insights about why synchronizing in theses specific places helps and I don't know how to fix the remaining errors.

**Comment by Tabrizian** [comment]
This looks like a bug. Could you please share a minimal reproducer example so that we can look into it?

**Comment by eliottsegard** [comment]
[minimal_preprocessing.py.txt](https://github.com/triton-inference-server/server/files/11431265/minimal_preprocessing.py.txt)
[minimal_preprocessing_config.pbtxt.txt](https://github.com/triton-inference-server/server/files/11431284/minimal_preprocessing_config.pbtxt.txt)
[minimal_ensemble_config.pbtxt.txt](https://github.com/triton-inference-server/server/files/11431292/minimal_ensemble_config.pbtxt.txt)

Here is the preprocessing I use with it's configuration file and a config file for the ensemble model that contains 2 models: 
- the preprocessing using the python backend
- the detection model using TRT backend (any TRT engine would probably work here, we happen to use yolov7)

The models run in tritonserver 22.07 using the default container (with pytorch installed using pip)

to make the inferences and check for errors, I use a python script that uses 2 or more threads to simulate multiple clients making concurrent inference requests. After each request, I compare the output to the result I expect. Running this with 2 clients making 1000 inferences each and when not using any synchronization, I usually see about 100 errors or more. With the synchronization it might be harder to see errors but you start to see them when using more threads.

**Comment by eliottsegard** [comment]
Here is the script I use to make the concurrent requests and count mixups:
[debug_triton_mixup_bug.py.txt](https://github.com/triton-inference-server/server/files/11431521/debug_triton_mixup_bug.py.txt)

Note that the mixups only happen when using more than one client or when using a single client but with the `async_infer` method.

**Comment by oandreeva-nv** [comment]
Hi @eliottsegard , may I ask you to try the following and see if it fixes an issue. In your preprocessing model, instead of using `pb_utils.Tensor.from_dlpack(to_dlpack(torch_tensor))`, try pb_utils.Tensor.from_dlpack(torch_tensor.__dlpack__(stream=1))?

**Comment by eliottsegard** [comment]
Hello! Thanks for the idea, sadly it does not help. 

When checking with nsight, I can see that the preprocessing operations do run on the default stream but the TRT engine is on a different one.

**Comment by Tabrizian** [comment]
@eliottsegard Could you please share the ONNX version of the TRT model as well? I've been working on modifying your reproducer to work with something similar that you're doing here but I haven't been able to repro it yet. Here is my model repository and client.py.

[model_repository.zip](https://github.com/triton-inference-server/server/files/11465811/model_repository.zip)
![labrador](https://github.com/triton-inference-server/server/assets/10105175/f4900dcb-0746-4116-8d60-a2a4c760d418)
![mug](https://github.com/triton-inference-server/server/assets/10105175/915a6a04-2914-452b-b0fb-a0235b8e33ec)

I ran two clients with the arguments below:

```
 python3 client.py --image 640px-YellowLabradorLooking.jpg --valid-str 'LABRADOR RETRIEVER'
 python3 client.py --image mug.jpg --valid-str "COFFEE MUG"
```

The clients have been returning correct results after running for about 15 minutes.

```
# Copyright (c) 2021, NVIDIA CORPORATION. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#  * Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#  * Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#  * Neither the name of NVIDIA CORPORATION nor the names of its
#    contributors may be used to endorse or promote products derived
#    from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ``AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
# OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import os, sys
import numpy as np
import json
import tritongrpcclient
import argparse


def load_image(img_path: str):
    """
    Loads an encoded image as an array of bytes.
    
    """
    return np.fromfile(img_path, dtype='uint8')


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--model_name",
                        type=str,
                        required=False,
                        default="ensemble_python_resnet50",
                        help="Model name")
    parser.add_argument("--image",
                        type=str,
                        required=True,
                        help="Path to the image")
    parser.add_argument("--valid-str",
                        type=str,
                        required=True,
                        help="Path to the image")
    parser.add_argument("--url",
                        type=str,
                        required=False,
                        default="localhost:8001",
                        help="Inference server URL. Default is localhost:8001.")
    parser.add_argument('-v',
                        "--verbose",
                        action="store_true",
                        required=False,
                        default=False,
                        help='Enable verbose output')
    parser.add_argument(
        "--label_file",
        type=str,
        default="./model_repository/resnet50_trt/labels.txt",
        help="Path to the file with text representation of available labels")
    args = parser.parse_args()

    try:
        triton_client = tritongrpcclient.InferenceServerClient(
            url=args.url, verbose=args.verbose)
    except Exception as e:
        print("channel creation failed: " + str(e))
        sys.exit(1)

    with open(args.label_file) as f:
        labels_dict = {idx: line.strip() for idx, line in enumerate(f)}

    inputs = []
    outputs = []
    input_name = "INPUT"
    output_name = "OUTPUT"
    image_data = load_image(args.image)
    image_data = np.expand_dims(image_data, axis=0)

    inputs.append(
        tritongrpcclient.InferInput(input_name, image_data.shape, "UINT8"))
    outputs.append(tritongrpcclient.InferRequestedOutput(output_name))

    inputs[0].set_data_from_numpy(image_data)
    while True:
        results = triton_client.infer(model_name=args.model_name,
                                      inputs=inputs,
                                      outputs=outputs)

        output0_data = results.as_numpy(output_name)
        maxs = np.argmax(output0_data, axis=1)
        print("Result is class: {}".format(labels_dict[maxs[0]]))
        if labels_dict[maxs[0]] != args.valid_str:
            sys.exit(0)

```

To generate the TRT model you can refer to the third step of the tutorial below:

https://github.com/triton-inference-server/python_backend/tree/main/examples/preprocessing

**Comment by eliottsegard** [comment]
Hello, thanks for coming back to me ! I have shared the .onnx with you by email. 

I was able to reproduce the problem using your test client with my preprocessing and model. 

On the other hand I wasn't yet able to reproduce it with the engine from the example you sent, but I think that's because I have not yet reproduced the same setup in the preprocessing.

**Comment by oandreeva-nv** [comment]
I've noticed that pytorch tensor is converted the following way:
` pb_utils.Tensor.from_dlpack("PREPROCESSING_OUTPUT", pytorch_tensor.__dlpack__())`
Note, by calling `pytorch_tensor.__dlpack__()` `stream=None` is used by default and  pytorch will skip synchronization: https://github.com/pytorch/pytorch/blob/main/torch/_tensor.py#L1343

Unfortunately, `__dlpack__(stream=1)`, where `stream=1` indicates default stream, won't work at the moment due to the following issue on pytorch side: https://github.com/pytorch/pytorch/pull/101318

**Comment by zhukai242** [comment]
how to solve this problem，i have also this 
@eliottsegard 
@oandreeva-nv

**Comment by Tabrizian** [comment]
@eliottsegard Thanks I can confirm that I've received the email.

**Comment by Tabrizian** [comment]
I was able to reproduce the issue.

**Comment by eliottsegard** [comment]
Thank you! 

I have been trying to apply this fix to my own python_backend (by building a custom backend based off your branch) but then it causes tritonserver to hang while loading the models. 

Is there anything I should know in order to make this work ?

**Comment by eliottsegard** [comment]
Thank you ! It fixes the issue for me too :smiley:
