### ISSUE TITLE
ONNX instances on same device are not running concurrently

### ISSUE THREAD

**Issue by Yashupadhyay13** [triton-inference-server/server#5736]
**Description**
i am creating 16 onnx model isntances on a single device , but dont see any performance improvement, seems like the inference is happening sequentially.

**Triton Information**
What version of Triton are you using?

using triton container tag : 23.02-py3

config.pbtxt
name: "model"
backend: "onnxruntime"
dynamic_batching {
}
parameters: {
  key: "INFERENCE_MODE"
    value: {string_value: "true"}
}
parameters: {
  key: "ENABLE_NVFUSER"
    value: {string_value: "true"}
}

instance_group [
    {
      count: 16
      kind: KIND_GPU
    }
]

input [
  {
    name: "input1"
    data_type: TYPE_INT64
    dims:[-1]
  }
]
output [
  {
    name: "out1"
    data_type: TYPE_FP32
    dims: [ -1]
  }
]
output [
  {
    name: "out2"
    data_type: TYPE_INT64
    dims: [ -1 ]
  }
]

how can i make the inference happen concurrently?

**Comment by GuanLuo** [comment]
How many requests are you sending concurrently? And is the GPU already fully utilized with low instance count?

**Comment by Yashupadhyay13** [comment]
@GuanLuo i am currently have about 16 instances of onnx model, i tried with 2, 4, 8 concurrent requests and time almost doubles when moving from 2 to 4 and 4 to 8. the GPU is not fully utilized, usinga 32gb v100.

**Comment by Yashupadhyay13** [comment]
@GuanLuo 
here are the memory utilization for 4 onnx and  8onnx instances 
![4onnx](https://user-images.githubusercontent.com/56575822/236764869-9b1fff01-3e32-415d-9e54-c18e7ecc5206.png)

![8onnx](https://user-images.githubusercontent.com/56575822/236764914-e60ffef3-b2d5-47c8-b340-0327a393532b.png)
p 99 latency with concurrency of 8  for 4 onnx instances is 1.88697 seconds and for 8 onnx instances is 1.9764 seconds

**Comment by Yashupadhyay13** [comment]
here are the memory utilization for 4 onnx and 8onnx instances
![4onnx](https://user-images.githubusercontent.com/56575822/236766352-4d98ce54-9be3-4466-8d81-61787bd6ac3d.png)
![8onnx](https://user-images.githubusercontent.com/56575822/236766417-783798e2-4c90-48fd-99f9-0c17032139ca.png)

p 99 latency with concurrency of 8 for 4 onnx instances is 1.88697 seconds and for 8 onnx instances is 1.9764 seconds

**Comment by GuanLuo** [comment]
Can you run `nvidia-smi` to get the number while you are sending the inference request? It will show some % for GPU-Util to show how busy the GPU is in addition to the memory usage.

Another thing that I want to check is that are you using perf analyzer to generate the concurrent requests? PA is handy tool that it will report the latency breakdown which may point out which part of the pipeline is the bottleneck.

**Comment by Yashupadhyay13** [comment]
![4_11_may](https://github.com/triton-inference-server/server/assets/56575822/0f14a50b-2e3c-420a-b4e9-92e1e64179b5)
nvidia smi of 4 instance inference

Perf analyzer output for 14 instances 

Inferences/Second vs. Client p95 Batch Latency 
Concurrency: 2, throughput: 24.439 infer/sec, latency 85852 usec 
Concurrency: 4, throughput: 25.8282 infer/sec, latency 212386 usec 
Concurrency: 6, throughput: 25.9394 infer/sec, latency 313485 usec 
Concurrency: 8, throughput: 25.884 infer/sec, latency 381231 usec 
Concurrency: 10, throughput: 26.1049 infer/sec, latency 461368 usec 
Concurrency: 12, throughput: 25.9399 infer/sec, latency 541262 usec 
Concurrency: 14, throughput: 25.8837 infer/sec, latency 621790 usec 
Concurrency: 16, throughput: 26.0503 infer/sec, latency 698420 usec 


Perf analyzer output for 14 instances 

Inferences/Second vs. Client p95 Batch Latency 

Concurrency: 2, throughput: 24.1053 infer/sec, latency 88544 usec 
Concurrency: 4, throughput: 25.3283 infer/sec, latency 219680 usec 
Concurrency: 6, throughput: 25.7728 infer/sec, latency 330513 usec 
Concurrency: 8, throughput: 26.1061 infer/sec, latency 470780 usec 
Concurrency: 10, throughput: 26.2177 infer/sec, latency 575474 usec 
Concurrency: 12, throughput: 25.8835 infer/sec, latency 713210 usec 
Concurrency: 14, throughput: 26.1052 infer/sec, latency 845827 usec 
Concurrency: 16, throughput: 25.9951 infer/sec, latency 936835 usec
