### ISSUE TITLE
Where can I find the information about the values for various platforms such as onnx and tensorflow 

### ISSUE THREAD

**Issue by frandoLin** [triton-inference-server/server#5741]
When I review the documentation below, the only information I found is about the backend. Where can I know about the values for the platform in the configuration file?
![image](https://user-images.githubusercontent.com/41569547/236364488-31a093ec-3ff6-4ad3-982e-983fc3354e81.png)

**Comment by GuanLuo** [comment]
`platform` is a backend-specific flag to distinguish different implementation within the backend. An example is for TensorFlow backend, you will specify `platform` to be either `tensorflow_graphdef` or `tensorflow_savedmodel`. But for most of the backends, `platform` field is not currently in used and doesn't need to be specified.
