### ISSUE TITLE
An error occurred while making inference requests for tritonserver

### ISSUE THREAD

**Issue by JasonChao-yue** [triton-inference-server/server#5749]
After starting Trionserver normally, the model was successfully loaded and the client was used for inference requests. The original model successfully requested inference, but the following error occurred when using my own generated model for inference.
tritonserver version : 23.23.04-py
gpu driver version: 313:23525.105.1713:23 
cuda version: 11.5

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "client.py", line 40, in image_get
    results = triton_client.infer(model_name=model,
  File "/usr/local/lib/python3.8/dist-packages/tritonclient/grpc/__init__.py", line 1469, in infer
    raise_error_grpc(rpc_error)
  File "/usr/local/lib/python3.8/dist-packages/tritonclient/grpc/__init__.py", line 75, in raise_error_grpc
    raise get_error_grpc(rpc_error) from None
tritonclient.utils.InferenceServerException: [StatusCode.UNAVAILABLE] Socket operation on non-socket

**Comment by JasonChao-yue** [comment]
> @JasonChao-yue Can you share the server side verbose logs? `tritonserver --log-verbose=1 ....`
The following are the startup logs of the tritonserver, with the lowest end containing the logs displayed on the server after the client makes a GRPC inference request.

`m@m-ThinkStation-P350:~$ docker run --gpus=0 -it --rm -p8000:8000 -p8001:8001 -p8002:8002 -v /home/m/Triton/server/docs/examples/model_repository:/models nvcr.io/nvidia/tritonserver:22.06-py3 tritonserver --model-repository=/models --log-verbose=1
=============================
== Triton Inference Server ==
=============================
NVIDIA Release 22.06 (build 39726160)
Triton Server Version 2.23.0
Copyright (c) 2018-2022, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license
I0511 01:22:36.649652 1 pinned_memory_manager.cc:240] Pinned memory pool is created at '0x7f1b84000000' with size 268435456
I0511 01:22:36.649823 1 cuda_memory_manager.cc:105] CUDA memory pool is created on device 0 with size 67108864
I0511 01:22:36.650465 1 model_config_utils.cc:645] Server side auto-completed config: name: "test_tensorrt"
platform: "tensorrt_plan"
max_batch_size: 1
input {
  name: "images"
  data_type: TYPE_FP32
  dims: 3
  dims: 640
  dims: 640
}
output {
  name: "output0"
  data_type: TYPE_FP32
  dims: 25200
  dims: 7
  label_filename: "firesmoke5.txt"
}
instance_group {
  count: 3
  kind: KIND_GPU
}
default_model_filename: "model.plan"
backend: "tensorrt"
I0511 01:22:36.650601 1 model_repository_manager.cc:1191] loading: test_tensorrt:1
I0511 01:22:36.751101 1 backend_model.cc:292] Adding default backend config setting: default-max-batch-size,4
I0511 01:22:36.751160 1 shared_library.cc:108] OpenLibraryHandle: /opt/tritonserver/backends/tensorrt/libtriton_tensorrt.so
I0511 01:22:36.776044 1 tensorrt.cc:5312] TRITONBACKEND_Initialize: tensorrt
I0511 01:22:36.776062 1 tensorrt.cc:5322] Triton TRITONBACKEND API version: 1.10
I0511 01:22:36.776066 1 tensorrt.cc:5328] 'tensorrt' TRITONBACKEND API version: 1.10
I0511 01:22:36.776068 1 tensorrt.cc:5351] Registering TensorRT Plugins
I0511 01:22:36.776076 1 logging.cc:52] Registered plugin creator - ::BatchTilePlugin_TRT version 1
I0511 01:22:36.776079 1 logging.cc:52] Registered plugin creator - ::BatchedNMS_TRT version 1
I0511 01:22:36.776082 1 logging.cc:52] Registered plugin creator - ::BatchedNMSDynamic_TRT version 1
I0511 01:22:36.776085 1 logging.cc:52] Registered plugin creator - ::CoordConvAC version 1
I0511 01:22:36.776088 1 logging.cc:52] Registered plugin creator - ::CropAndResize version 1
I0511 01:22:36.776092 1 logging.cc:52] Registered plugin creator - ::CropAndResizeDynamic version 1
I0511 01:22:36.776095 1 logging.cc:52] Registered plugin creator - ::DecodeBbox3DPlugin version 1
I0511 01:22:36.776098 1 logging.cc:52] Registered plugin creator - ::DetectionLayer_TRT version 1
I0511 01:22:36.776101 1 logging.cc:52] Registered plugin creator - ::EfficientNMS_TRT version 1
I0511 01:22:36.776105 1 logging.cc:52] Registered plugin creator - ::EfficientNMS_ONNX_TRT version 1
I0511 01:22:36.776110 1 logging.cc:52] Registered plugin creator - ::EfficientNMS_Explicit_TF_TRT version 1
I0511 01:22:36.776114 1 logging.cc:52] Registered plugin creator - ::EfficientNMS_Implicit_TF_TRT version 1
I0511 01:22:36.776120 1 logging.cc:52] Registered plugin creator - ::FlattenConcat_TRT version 1
I0511 01:22:36.776124 1 logging.cc:52] Registered plugin creator - ::GenerateDetection_TRT version 1
I0511 01:22:36.776128 1 logging.cc:52] Registered plugin creator - ::GridAnchor_TRT version 1
I0511 01:22:36.776131 1 logging.cc:52] Registered plugin creator - ::GridAnchorRect_TRT version 1
I0511 01:22:36.776137 1 logging.cc:52] Registered plugin creator - ::InstanceNormalization_TRT version 1
I0511 01:22:36.776141 1 logging.cc:52] Registered plugin creator - ::LReLU_TRT version 1
I0511 01:22:36.776144 1 logging.cc:52] Registered plugin creator - ::MultilevelCropAndResize_TRT version 1
I0511 01:22:36.776148 1 logging.cc:52] Registered plugin creator - ::MultilevelProposeROI_TRT version 1
I0511 01:22:36.776151 1 logging.cc:52] Registered plugin creator - ::DMHA version 1
I0511 01:22:36.776155 1 logging.cc:52] Registered plugin creator - ::NMS_TRT version 1
I0511 01:22:36.776159 1 logging.cc:52] Registered plugin creator - ::NMSDynamic_TRT version 1
I0511 01:22:36.776162 1 logging.cc:52] Registered plugin creator - ::Normalize_TRT version 1
I0511 01:22:36.776166 1 logging.cc:52] Registered plugin creator - ::PillarScatterPlugin version 1
I0511 01:22:36.776171 1 logging.cc:52] Registered plugin creator - ::PriorBox_TRT version 1
I0511 01:22:36.776175 1 logging.cc:52] Registered plugin creator - ::ProposalLayer_TRT version 1
I0511 01:22:36.776178 1 logging.cc:52] Registered plugin creator - ::Proposal version 1
I0511 01:22:36.776181 1 logging.cc:52] Registered plugin creator - ::ProposalDynamic version 1
I0511 01:22:36.776185 1 logging.cc:52] Registered plugin creator - ::PyramidROIAlign_TRT version 1
I0511 01:22:36.776189 1 logging.cc:52] Registered plugin creator - ::Region_TRT version 1
I0511 01:22:36.776192 1 logging.cc:52] Registered plugin creator - ::Reorg_TRT version 1
I0511 01:22:36.776195 1 logging.cc:52] Registered plugin creator - ::ResizeNearest_TRT version 1
I0511 01:22:36.776200 1 logging.cc:52] Registered plugin creator - ::RPROI_TRT version 1
I0511 01:22:36.776203 1 logging.cc:52] Registered plugin creator - ::ScatterND version 1
I0511 01:22:36.776206 1 logging.cc:52] Registered plugin creator - ::SpecialSlice_TRT version 1
I0511 01:22:36.776210 1 logging.cc:52] Registered plugin creator - ::Split version 1
I0511 01:22:36.776214 1 logging.cc:52] Registered plugin creator - ::VoxelGeneratorPlugin version 1
I0511 01:22:36.776217 1 tensorrt.cc:5371] backend configuration:
{"cmdline":{"auto-complete-config":"false","min-compute-capability":"6.000000","backend-directory":"/opt/tritonserver/backends","default-max-batch-size":"4"}}
I0511 01:22:36.776234 1 tensorrt.cc:5423] TRITONBACKEND_ModelInitialize: test_tensorrt (version 1)
I0511 01:22:36.776718 1 model_config_utils.cc:1617] ModelConfig 64-bit fields:
I0511 01:22:36.776724 1 model_config_utils.cc:1619] 	ModelConfig::dynamic_batching::default_queue_policy::default_timeout_microseconds
I0511 01:22:36.776728 1 model_config_utils.cc:1619] 	ModelConfig::dynamic_batching::max_queue_delay_microseconds
I0511 01:22:36.776730 1 model_config_utils.cc:1619] 	ModelConfig::dynamic_batching::priority_queue_policy::value::default_timeout_microseconds
I0511 01:22:36.776733 1 model_config_utils.cc:1619] 	ModelConfig::ensemble_scheduling::step::model_version
I0511 01:22:36.776735 1 model_config_utils.cc:1619] 	ModelConfig::input::dims
I0511 01:22:36.776738 1 model_config_utils.cc:1619] 	ModelConfig::input::reshape::shape
I0511 01:22:36.776740 1 model_config_utils.cc:1619] 	ModelConfig::instance_group::secondary_devices::device_id
I0511 01:22:36.776744 1 model_config_utils.cc:1619] 	ModelConfig::model_warmup::inputs::value::dims
I0511 01:22:36.776746 1 model_config_utils.cc:1619] 	ModelConfig::optimization::cuda::graph_spec::graph_lower_bound::input::value::dim
I0511 01:22:36.776748 1 model_config_utils.cc:1619] 	ModelConfig::optimization::cuda::graph_spec::input::value::dim
I0511 01:22:36.776751 1 model_config_utils.cc:1619] 	ModelConfig::output::dims
I0511 01:22:36.776753 1 model_config_utils.cc:1619] 	ModelConfig::output::reshape::shape
I0511 01:22:36.776756 1 model_config_utils.cc:1619] 	ModelConfig::sequence_batching::direct::max_queue_delay_microseconds
I0511 01:22:36.776757 1 model_config_utils.cc:1619] 	ModelConfig::sequence_batching::max_sequence_idle_microseconds
I0511 01:22:36.776760 1 model_config_utils.cc:1619] 	ModelConfig::sequence_batching::oldest::max_queue_delay_microseconds
I0511 01:22:36.776762 1 model_config_utils.cc:1619] 	ModelConfig::sequence_batching::state::dims
I0511 01:22:36.776764 1 model_config_utils.cc:1619] 	ModelConfig::sequence_batching::state::initial_state::dims
I0511 01:22:36.776766 1 model_config_utils.cc:1619] 	ModelConfig::version_policy::specific::versions
I0511 01:22:36.776827 1 tensorrt.cc:439] model configuration:
{
    "name": "test_tensorrt",
    "platform": "tensorrt_plan",
    "backend": "tensorrt",
    "version_policy": {
        "latest": {
            "num_versions": 1
        }
    },
    "max_batch_size": 1,
    "input": [
        {
            "name": "images",
            "data_type": "TYPE_FP32",
            "format": "FORMAT_NONE",
            "dims": [
                3,
                640,
                640
            ],
            "is_shape_tensor": false,
            "allow_ragged_batch": false,
            "optional": false
        }
    ],
    "output": [
        {
            "name": "output0",
            "data_type": "TYPE_FP32",
            "dims": [
                25200,
                7
            ],
            "label_filename": "firesmoke5.txt",
            "is_shape_tensor": false
        }
    ],
    "batch_input": [],
    "batch_output": [],
    "optimization": {
        "priority": "PRIORITY_DEFAULT",
        "input_pinned_memory": {
            "enable": true
        },
        "output_pinned_memory": {
            "enable": true
        },
        "gather_kernel_buffer_threshold": 0,
        "eager_batching": false
    },
    "instance_group": [
        {
            "name": "test_tensorrt_0",
            "kind": "KIND_GPU",
            "count": 3,
            "gpus": [
                0
            ],
            "secondary_devices": [],
            "profile": [],
            "passive": false,
            "host_policy": ""
        }
    ],
    "default_model_filename": "model.plan",
    "cc_model_filenames": {},
    "metric_tags": {},
    "parameters": {},
    "model_warmup": []
}
I0511 01:22:36.776989 1 tensorrt.cc:5472] TRITONBACKEND_ModelInstanceInitialize: test_tensorrt_0_0 (GPU device 0)
I0511 01:22:36.777182 1 backend_model_instance.cc:105] Creating instance test_tensorrt_0_0 on GPU 0 (8.6) using artifact 'model.plan'
I0511 01:22:36.800700 1 tensorrt.cc:1500] Zero copy optimization is disabled
I0511 01:22:37.084397 1 logging.cc:49] [MemUsageChange] Init CUDA: CPU +466, GPU +0, now: CPU 490, GPU 894 (MiB)
I0511 01:22:37.141633 1 logging.cc:49] Loaded engine size: 93 MiB
I0511 01:22:37.639219 1 logging.cc:52] Using cublasLt as a tactic source
I0511 01:22:37.639283 1 logging.cc:49] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +842, GPU +360, now: CPU 1533, GPU 1348 (MiB)
I0511 01:22:37.639343 1 logging.cc:52] Using cuDNN as a tactic source
I0511 01:22:37.722624 1 logging.cc:49] [MemUsageChange] Init cuDNN: CPU +128, GPU +60, now: CPU 1661, GPU 1408 (MiB)
I0511 01:22:37.723345 1 logging.cc:52] Deserialization required 581587 microseconds.
I0511 01:22:37.723355 1 logging.cc:49] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +90, now: CPU 0, GPU 90 (MiB)
I0511 01:22:37.726998 1 tensorrt.cc:387] Created new runtime on GPU device 0, NVDLA core -1 for test_tensorrt
I0511 01:22:37.727003 1 tensorrt.cc:394] Created new engine on GPU device 0, NVDLA core -1 for test_tensorrt
I0511 01:22:37.727337 1 logging.cc:52] Using cublasLt as a tactic source
I0511 01:22:37.727368 1 logging.cc:49] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +10, now: CPU 1473, GPU 1400 (MiB)
I0511 01:22:37.727403 1 logging.cc:52] Using cuDNN as a tactic source
I0511 01:22:37.727997 1 logging.cc:49] [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 1473, GPU 1408 (MiB)
I0511 01:22:37.728144 1 logging.cc:52] Total per-runner device persistent memory is 94232064
I0511 01:22:37.728149 1 logging.cc:52] Total per-runner host persistent memory is 237952
I0511 01:22:37.728319 1 logging.cc:52] Allocated activation device memory of size 36941824
I0511 01:22:37.728941 1 logging.cc:49] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +125, now: CPU 0, GPU 215 (MiB)
I0511 01:22:37.728954 1 tensorrt.cc:3193] Detected images as execution binding for test_tensorrt_0_0
I0511 01:22:37.728957 1 tensorrt.cc:3193] Detected output0 as execution binding for test_tensorrt_0_0
I0511 01:22:37.729087 1 tensorrt.cc:1426] Created instance test_tensorrt_0_0 on GPU 0 with stream priority 0 and optimization profile default[0];
I0511 01:22:37.729135 1 backend_model_instance.cc:732] Starting backend thread for test_tensorrt_0_0 at nice 0 on device 0...
I0511 01:22:37.729166 1 tensorrt.cc:5472] TRITONBACKEND_ModelInstanceInitialize: test_tensorrt_0_1 (GPU device 0)
I0511 01:22:37.729222 1 backend_model_instance.cc:105] Creating instance test_tensorrt_0_1 on GPU 0 (8.6) using artifact 'model.plan'
I0511 01:22:37.729269 1 tensorrt.cc:1500] Zero copy optimization is disabled
I0511 01:22:37.729542 1 logging.cc:52] Using cublasLt as a tactic source
I0511 01:22:37.729572 1 logging.cc:49] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 1473, GPU 1548 (MiB)
I0511 01:22:37.729604 1 logging.cc:52] Using cuDNN as a tactic source
I0511 01:22:37.729821 1 logging.cc:49] [MemUsageChange] Init cuDNN: CPU +1, GPU +10, now: CPU 1474, GPU 1558 (MiB)
I0511 01:22:37.729966 1 logging.cc:52] Total per-runner device persistent memory is 94232064
I0511 01:22:37.729973 1 logging.cc:52] Total per-runner host persistent memory is 237952
I0511 01:22:37.730120 1 logging.cc:52] Allocated activation device memory of size 36941824
I0511 01:22:37.730720 1 logging.cc:49] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +125, now: CPU 0, GPU 340 (MiB)
I0511 01:22:37.730730 1 tensorrt.cc:3193] Detected images as execution binding for test_tensorrt_0_1
I0511 01:22:37.730732 1 tensorrt.cc:3193] Detected output0 as execution binding for test_tensorrt_0_1
I0511 01:22:37.730828 1 tensorrt.cc:1426] Created instance test_tensorrt_0_1 on GPU 0 with stream priority 0 and optimization profile default[0];
I0511 01:22:37.730835 1 backend_model_instance.cc:332] Using already started backend thread for test_tensorrt_0_1 on device 0
I0511 01:22:37.730901 1 tensorrt.cc:5472] TRITONBACKEND_ModelInstanceInitialize: test_tensorrt_0_2 (GPU device 0)
I0511 01:22:37.730949 1 backend_model_instance.cc:105] Creating instance test_tensorrt_0_2 on GPU 0 (8.6) using artifact 'model.plan'
I0511 01:22:37.730998 1 tensorrt.cc:1500] Zero copy optimization is disabled
I0511 01:22:37.731291 1 logging.cc:52] Using cublasLt as a tactic source
I0511 01:22:37.731319 1 logging.cc:49] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +10, now: CPU 1474, GPU 1700 (MiB)
I0511 01:22:37.731350 1 logging.cc:52] Using cuDNN as a tactic source
I0511 01:22:37.731567 1 logging.cc:49] [MemUsageChange] Init cuDNN: CPU +0, GPU +10, now: CPU 1474, GPU 1710 (MiB)
I0511 01:22:37.731706 1 logging.cc:52] Total per-runner device persistent memory is 94232064
I0511 01:22:37.731712 1 logging.cc:52] Total per-runner host persistent memory is 237952
I0511 01:22:37.731858 1 logging.cc:52] Allocated activation device memory of size 36941824
I0511 01:22:37.732458 1 logging.cc:49] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +125, now: CPU 0, GPU 465 (MiB)
I0511 01:22:37.732469 1 tensorrt.cc:3193] Detected images as execution binding for test_tensorrt_0_2
I0511 01:22:37.732472 1 tensorrt.cc:3193] Detected output0 as execution binding for test_tensorrt_0_2
I0511 01:22:37.732573 1 tensorrt.cc:1426] Created instance test_tensorrt_0_2 on GPU 0 with stream priority 0 and optimization profile default[0];
I0511 01:22:37.732580 1 backend_model_instance.cc:332] Using already started backend thread for test_tensorrt_0_2 on device 0
I0511 01:22:37.732612 1 model_repository_manager.cc:1345] successfully loaded 'test_tensorrt' version 1
I0511 01:22:37.732644 1 server.cc:556] 
+------------------+------+
| Repository Agent | Path |
+------------------+------+
+------------------+------+
I0511 01:22:37.732670 1 server.cc:583] 
+----------+-----------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------+
| Backend  | Path                                                      | Config                                                                                                                          |
+----------+-----------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------+
| tensorrt | /opt/tritonserver/backends/tensorrt/libtriton_tensorrt.so | {"cmdline":{"auto-complete-config":"false","min-compute-capability":"6.000000","backend-directory":"/opt/tritonserver/backends" |
|          |                                                           | ,"default-max-batch-size":"4"}}                                                                                                 |
+----------+-----------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------+
I0511 01:22:37.732689 1 server.cc:626] 
+---------------+---------+--------+
| Model         | Version | Status |
+---------------+---------+--------+
| test_tensorrt | 1       | READY  |
+---------------+---------+--------+
I0511 01:22:37.754135 1 metrics.cc:650] Collecting metrics for GPU 0: NVIDIA GeForce RTX 3080
I0511 01:22:37.754264 1 tritonserver.cc:2159] 
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Option                           | Value                                                                                                                                                                |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| server_id                        | triton                                                                                                                                                               |
| server_version                   | 2.23.0                                                                                                                                                               |
| server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_policy model_configuration system_shared_memory cuda_shared_memory binary_tens |
|                                  | or_data statistics trace                                                                                                                                             |
| model_repository_path[0]         | /models                                                                                                                                                              |
| model_control_mode               | MODE_NONE                                                                                                                                                            |
| strict_model_config              | 1                                                                                                                                                                    |
| rate_limit                       | OFF                                                                                                                                                                  |
| pinned_memory_pool_byte_size     | 268435456                                                                                                                                                            |
| cuda_memory_pool_byte_size{0}    | 67108864                                                                                                                                                             |
| response_cache_byte_size         | 0                                                                                                                                                                    |
| min_supported_compute_capability | 6.0                                                                                                                                                                  |
| strict_readiness                 | 1                                                                                                                                                                    |
| exit_timeout                     | 30                                                                                                                                                                   |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
I0511 01:22:37.754316 1 grpc_server.cc:4531] === GRPC KeepAlive Options ===
I0511 01:22:37.754319 1 grpc_server.cc:4532] keepalive_time_ms: 7200000
I0511 01:22:37.754321 1 grpc_server.cc:4534] keepalive_timeout_ms: 20000
I0511 01:22:37.754323 1 grpc_server.cc:4536] keepalive_permit_without_calls: 0
I0511 01:22:37.754326 1 grpc_server.cc:4538] http2_max_pings_without_data: 2
I0511 01:22:37.754329 1 grpc_server.cc:4540] http2_min_recv_ping_interval_without_data_ms: 300000
I0511 01:22:37.754332 1 grpc_server.cc:4543] http2_max_ping_strikes: 2
I0511 01:22:37.754335 1 grpc_server.cc:4545] ==============================
I0511 01:22:37.754667 1 grpc_server.cc:225] Ready for RPC 'ServerLive', 0
I0511 01:22:37.754678 1 grpc_server.cc:225] Ready for RPC 'ServerReady', 0
I0511 01:22:37.754682 1 grpc_server.cc:225] Ready for RPC 'ModelReady', 0
I0511 01:22:37.754688 1 grpc_server.cc:225] Ready for RPC 'ServerMetadata', 0
I0511 01:22:37.754691 1 grpc_server.cc:225] Ready for RPC 'ModelMetadata', 0
I0511 01:22:37.754694 1 grpc_server.cc:225] Ready for RPC 'ModelConfig', 0
I0511 01:22:37.754697 1 grpc_server.cc:225] Ready for RPC 'ModelStatistics', 0
I0511 01:22:37.754701 1 grpc_server.cc:225] Ready for RPC 'Trace', 0
I0511 01:22:37.754705 1 grpc_server.cc:225] Ready for RPC 'SystemSharedMemoryStatus', 0
I0511 01:22:37.754708 1 grpc_server.cc:225] Ready for RPC 'SystemSharedMemoryRegister', 0
I0511 01:22:37.754712 1 grpc_server.cc:225] Ready for RPC 'SystemSharedMemoryUnregister', 0
I0511 01:22:37.754716 1 grpc_server.cc:225] Ready for RPC 'CudaSharedMemoryStatus', 0
I0511 01:22:37.754720 1 grpc_server.cc:225] Ready for RPC 'CudaSharedMemoryRegister', 0
I0511 01:22:37.754724 1 grpc_server.cc:225] Ready for RPC 'CudaSharedMemoryUnregister', 0
I0511 01:22:37.754728 1 grpc_server.cc:225] Ready for RPC 'RepositoryIndex', 0
I0511 01:22:37.754731 1 grpc_server.cc:225] Ready for RPC 'RepositoryModelLoad', 0
I0511 01:22:37.754735 1 grpc_server.cc:225] Ready for RPC 'RepositoryModelUnload', 0
I0511 01:22:37.754742 1 grpc_server.cc:419] Thread started for CommonHandler
I0511 01:22:37.754784 1 grpc_server.cc:3585] New request handler for ModelInferHandler, 0
I0511 01:22:37.754795 1 grpc_server.cc:2509] Thread started for ModelInferHandler
I0511 01:22:37.754881 1 grpc_server.cc:3585] New request handler for ModelInferHandler, 0
I0511 01:22:37.754957 1 grpc_server.cc:2509] Thread started for ModelInferHandler
I0511 01:22:37.755008 1 grpc_server.cc:3969] New request handler for ModelStreamInferHandler, 0
I0511 01:22:37.755069 1 grpc_server.cc:2509] Thread started for ModelStreamInferHandler
I0511 01:22:37.755079 1 grpc_server.cc:4587] Started GRPCInferenceService at 0.0.0.0:8001
I0511 01:22:37.755209 1 http_server.cc:3303] Started HTTPService at 0.0.0.0:8000
I0511 01:22:37.797088 1 http_server.cc:178] Started Metrics Service at 0.0.0.0:8002
^[[AI0511 01:23:05.634432 1 grpc_server.cc:270] Process for ServerLive, rpc_ok=1, 0 step START
I0511 01:23:05.634449 1 grpc_server.cc:225] Ready for RPC 'ServerLive', 1
I0511 01:23:05.634474 1 grpc_server.cc:270] Process for ServerLive, rpc_ok=1, 0 step COMPLETE
I0511 01:23:05.634477 1 grpc_server.cc:411] Done for ServerLive, 0
I0511 01:23:05.634793 1 grpc_server.cc:270] Process for ServerReady, rpc_ok=1, 0 step START
I0511 01:23:05.634806 1 grpc_server.cc:225] Ready for RPC 'ServerReady', 1
I0511 01:23:05.634833 1 grpc_server.cc:270] Process for ServerReady, rpc_ok=1, 0 step COMPLETE
I0511 01:23:05.634838 1 grpc_server.cc:411] Done for ServerReady, 0
I0511 01:23:05.634960 1 grpc_server.cc:270] Process for ModelReady, rpc_ok=1, 0 step START
I0511 01:23:05.634967 1 grpc_server.cc:225] Ready for RPC 'ModelReady', 1
I0511 01:23:05.634989 1 grpc_server.cc:270] Process for ModelReady, rpc_ok=1, 0 step COMPLETE
I0511 01:23:05.634992 1 grpc_server.cc:411] Done for ModelReady, 0`

Thank you for your reply！

**Comment by tanmayv25** [comment]
From the logs it seems that server didn't even receive the request.  From the backtrace it looks you were using gRPC package on the client side. The server does receive requests for ServerLive, ServerReady and ModelReady. 

If the only difference is in model.plan contents, this is hard to explain. Are you sure there are no other difference on how you are sending requests to Triton between working and non-working models?

**Comment by JasonChao-yue** [comment]
> From the logs it seems that server didn't even receive the request. From the backtrace it looks you were using gRPC package on the client side. The server does receive requests for ServerLive, ServerReady and ModelReady.
> 
> If the only difference is in model.plan contents, this is hard to explain. Are you sure there are no other difference on how you are sending requests to Triton between working and non-working models?

Do you mean that the model requested by the client to the server may not work? However, it was successful when other computers used the client to request the same server model.

**Comment by tanmayv25** [comment]
> Do you mean that the model requested by the client to the server may not work?

If the model is loaded and ready in the server, then it will work. From the verbose logs, I was pointing out that the server endpoint didn't seem to have received the request itself. Hence, it doesn't matter which model the request was generated for from the client side. Even if the client requested an inference from an invalid model, there should have been some logs emitted on the server.

This looks like more of an issue with the system network.

> However, it was successful when other computers used the client to request the same server model.

This demonstrates that issue could be related to the system network and not Triton Server itself.

**Comment by JasonChao-yue** [comment]
> > Do you mean that the model requested by the client to the server may not work?
> 
> If the model is loaded and ready in the server, then it will work. From the verbose logs, I was pointing out that the server endpoint didn't seem to have received the request itself. Hence, it doesn't matter which model the request was generated for from the client side. Even if the client requested an inference from an invalid model, there should have been some logs emitted on the server.
> 
> This looks like more of an issue with the system network.
> 
> > However, it was successful when other computers used the client to request the same server model.
> 
> This demonstrates that issue could be related to the system network and not Triton Server itself.

Thank you for your reply!

The cause of this problem has been identified. Due to the use of local direct reading of video resources in the client, it was found through investigation that some resources failed immediately after successfully reading with OpenCV for a few seconds, resulting in the occurrence of the above problem. I attempted to use the video resource that was successfully read, but the problem did not occur.
