### ISSUE TITLE
Dynamic Input Shape Handling in triton

### ISSUE THREAD

**Issue by ss756** [triton-inference-server/server#5752]
**Description**
Hi, 
   I am trying to serve a onnx model with dynamic batching and input shape. I am unable to do so because of a hard check between the config shape ([-1,3,-1,-1]) and the input image shape [1, 3, 1048, 1680]. Is there a way to bypass this check and allow inference with the below model specifications. 

**Triton Information**
Triton Version = 22.09

**To Reproduce**
![image](https://user-images.githubusercontent.com/61051785/236772725-7ec9acf4-3a33-4324-af58-02e13b935a13.png)
![image](https://user-images.githubusercontent.com/61051785/236772836-c741d947-1ae8-425c-8f51-2ad4921e6437.png)

model link - [https://drive.google.com/file/d/1ZDXz7EgN3umDvbbdxohZrFaNJzLACu2R/view?usp=share_link](url)

config file link - [https://drive.google.com/file/d/11v2QJodrcLLq-WJ_0OF5AvrqzrNMusK_/view?usp=share_link](url)

**Comment by GuanLuo** [comment]
Can you share your client code? It looks like the shape [1, 3, 1048, 1680] is not being set for your `InferInput`

**Comment by ss756** [comment]
Yeah sure here is the link to the client code - https://drive.google.com/file/d/1rI7c7TVmfxx-pt98Ih6XlEtWyHaVTEBZ/view?usp=share_link
`
import tritonclient.grpc as grpc_client
from tritonclient.utils import triton_to_np_dtype
import numpy as np
import cv2

# Define the address and port number of the Triton server
TRITON_SERVER_URL = 'localhost:8001'

# Define the name of the model on the Triton server
MODEL_NAME = 'ppocr'

# Define the version of the model to use
MODEL_VERSION = '2'

# Define the input image file path
IMAGE_FILE = './doc/imgs_en/img_12.jpg'

# Create a Triton gRPC client and connect to the server
triton_client = grpc_client.InferenceServerClient(url=TRITON_SERVER_URL, verbose=True)

# Read the input image
img = cv2.imread(IMAGE_FILE)
print("The shape of the image is", img.shape)
# Preprocess the input image
#img = cv2.resize(img, (640, 640))
#img = np.zeros((3, 48, 320), dtype=np.float32)
img = img.astype(np.float32)
img = img / 255.0
img = np.transpose(img, (2, 0, 1))
img = np.expand_dims(img, axis=0)
metadata = triton_client.get_model_metadata(model_name=MODEL_NAME, model_version=MODEL_VERSION)
model_config = triton_client.get_model_config(model_name=MODEL_NAME, model_version=MODEL_VERSION)
# Get input and output names
input_name = metadata.inputs[0].name
output_name = metadata.outputs[0].name

# Get input and output shapes
input_shape = metadata.inputs[0].shape
output_shape = metadata.outputs[0].shape
print(f"The model input shape is", input_shape)
# Create the input data for the model
input_data = grpc_client.InferInput(input_name,input_shape,  'FP32')
input_data.set_data_from_numpy(img)
#print("The input data is", input_data)
# Define the output data to be retrieved from the model
inputs = []
outputs = []
output_data = grpc_client.InferRequestedOutput(output_name)
#print("The output data is", output_data)
inputs.append(input_data)
outputs.append(output_data)
# Send the inference request to the Triton server
results = triton_client.infer(
    model_name=MODEL_NAME,
    inputs=inputs,
    outputs=outputs,
    model_version=MODEL_VERSION
)

# Retrieve the output from the model
output = results.as_numpy('output')
`

**Comment by ss756** [comment]
@GuanLuo is there a way around this problem ?

**Comment by GuanLuo** [comment]
In your client code, you have:
```
metadata = triton_client.get_model_metadata(model_name=MODEL_NAME, model_version=MODEL_VERSION)
input_shape = metadata.inputs[0].shape
# Create the input data for the model
input_data = grpc_client.InferInput(input_name,input_shape, 'FP32')
```

The shape from metadata is the generic shape, you should set `input_shape` based on the actual input that you are passing (i.e. `img.shape`)

**Comment by GuanLuo** [comment]
The error now is from the model that it couldn't run the inference successfully, are you able to run the model outside Triton? i.e. follow [ORT quickstart](https://onnxruntime.ai/docs/get-started/with-python.html#get-started-with-onnx-runtime-in-python) to send the same data (img) to the model and see if it runs succesfully

**Comment by ss756** [comment]
Yeah @GuanLuo  I was able to send the image across, had some tensor shape mismatch issues. My inference speed is not good enough for this model. Is there any materials you have in mind to improve the inference speed?

**Comment by GuanLuo** [comment]
For performance tuning, you can follow this [documentation](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/performance_tuning.md) to experiment with different configuration.
