### ISSUE TITLE
what should I do if i want to write a plugin for pulling model repository from other file system

### ISSUE THREAD

**Issue by wyoung1** [triton-inference-server/server#5781]
Hi,
I notice that in filesystem.cc in triton core only 4 file systems are supported.
If I want to write a plugin for pulling model repository from other file system, is there any  method to complete it? Such as writing an out-of-tree plugin.
Thanks!

**Comment by tanmayv25** [comment]
As you already found, the filesystem for model repository has its implementation embedded in triton core. We currently don't have a plugin interface for the filesystem, but can extend triton to do so. 
Meanwhile you can extend the Triton core implementation to support your filesystem. We encourage external contributions for this project! 
You might be able to use repository agent to pull model files from some other storage systems. See more about it here: https://github.com/triton-inference-server/server/blob/main/docs/customization_guide/repository_agents.md

**Comment by wyoung1** [comment]
Hi,@tanmayv25, thanks for your advice! But I still have some confusion. In my understanding, Trinton's pulling a model repository from remote is divided into two steps, the first step pulls the repository into the local file system, and the second step loads the models from the local file system into Triton Server. The repo agent seems to work when loading the model locally by extracting the ModelRepositoryAgents section in the config.pbtxt file. So if I want to pull a remote model repo from a new cloud storage, how does the repo agent work?
Moreover, does Triton have an API to directly load the model from cloud storage into memory without going through the local file system?
Thanks!
