### ISSUE TITLE
Reiterating the suggestion for an enhanced extension of CUDA tensors to cudashm.

### ISSUE THREAD

**Issue by muqishan** [triton-inference-server/server#5785]
In a previous discussion, I proposed an extension of the cudashm.set_shared_memory_region(shm_put_handle, [img]) function within the Python client for CUDA shared memory inference. This extension is designed to support GPU tensors from Cupy and Torch, which effectively reduces the burden on the PCI-E bus. It is my belief that in numerous industrial settings, an API that facilitates input and output of GPU tensors is of paramount importance. Yet, I am uncertain whether this suggestion has been embraced. Implementing this would provide invaluable direction for a research project that I am engaged in. The predicament of choosing between Triton and pursuing a more complex developmental path has elicited considerable distress.

I assert that the adoption of this suggestion will yield substantial benefits, primarily in enhancing efficiency and compatibility with widely-used GPU tensor libraries. Furthermore, it will foster the development of more robust and versatile applications in the field of CUDA shared memory inference.

In the realm of image processing, with the continual escalation of camera resolutions, it becomes necessary in certain situations to incorporate specific preprocessing steps within the model or execute them directly on the GPU. However, in various scenarios, such as pedestrian re-identification tasks, the extraction of appearance features is dependent on a pre-trained pedestrian detector, akin to the widely used non-maximum suppression (NMS) in object detection. This kind of workflow mandates persistent data transfer between the GPU and CPU, imposing significant demands on the PCI-E bus.

By implementing this suggestion and bolstering cudashm's capabilities to accommodate GPU tensors, we can significantly diminish the need for data transfers between the CPU and GPU. This, consequently, considerably reduces the load on the PCI-E bus. Such optimization is particularly crucial in complex workflows that involve image processing and deep learning tasks.

Given the escalating importance of efficient data handling in contemporary computer systems, I am firmly convinced that this suggestion, if adopted, will dramatically enhance the capabilities and performance of the Python client in various industrial situations. This will facilitate the development of more streamlined and efficient processes, ultimately leading to the creation of more powerful and adaptable applications in the CUDA shared memory inference field.

I humbly request that this proposal be given due consideration, as it has the potential to significantly improve the Python client's capabilities and usability, ultimately contributing to a more efficient and productive development process.

**Comment by oandreeva-nv** [comment]
I believe, Python backend already uses shared memory to communicate and transfer data from the Triton process to the model instance’s stub process. Could you please provide more specific request and specify what Python backend's implementation is currently lacking? Your feedback would be highly appreciated.

**Comment by muqishan** [comment]
I want to use Triton to complete a face recognition project for 64 cameras, but this project needs to be divided into two stages: firstly, face detection, and then face recognition. Face detection does not depend on image clarity, while face recognition relies on high-quality images. If I use a Python backend to send data, even if I'm sending data of type uint, 64 images of 1080*1920 will require about 400MB of memory. However, my PCI bus bandwidth is only 16GB/s. Even if I use CUDA shared memory to send data to the backend, it would still take about 20ms. This is something I can't accept.

Therefore, I thought of sampling the 64*1080*1920*3 matrix, such as frames[:, :, ::3, ::3]. This way, I get a 64*360*640*3 matrix. Sending this data as type uint8 to CUDA's memory only takes about 5ms, which satisfies my requirements. But when I obtain the ROI matrix from face detection, because face recognition requires high-quality images, I need to crop the ROI from the original image (64*1080*1920*3). However, the original image does not exist on CUDA.

In this situation, I can't use a Python backend to complete this task, because I don't want to send the original image to CUDA. If I don't use a backend, I will encounter the problems mentioned above.

Of course, you might think of conducting two 32-asynchronous accesses or four 16-multi-thread (process) accesses, but the total number of cameras in the project exceeds 1000, and 64 is already the smallest batch we can accept. In fact, our algorithm and model can process 64 images in less than 20ms. The only bottleneck is copying data from the CPU to the GPU.

If there's any other way that I could perform computations in a zero-copy fashion, I would be incredibly grateful. I believe this could bring significant improvements in tasks such as face recognition, pedestrian re-identification, and anti-fraud license plate recognition.
