### ISSUE TITLE
Loading ensemble reloads already loaded models

### ISSUE THREAD

**Issue by sourabh-burnwal** [triton-inference-server/server#5791]
My setting (only for model loading) looks like this: `Client -> Flask server -> Triton server`
For model loading, client sends model name to flask server and it sends a load call to Triton server. The issue is when I load all the models first, and then call to load the ensemble, it reloads all the models again, and unloads the older ones. 

This behaviour is only when I do the load call from the Flask server. I tried doing curl load without the Flask server, and couldn't reproduce it. I am not sure why this is happening, and what might be the issue. I have made sure the model versions and names are correct. Can you guys help?

Container version: 21.08
@Tabrizian @tanmayv25

**Comment by tanmayv25** [comment]
>  I tried doing curl load without the Flask server, and couldn't reproduce it.
@sourabh-burnwal  you should compare how the system architecture behaves differently when the call goes via curl vs Flask server. 
As far as Triton is concerned, it should be oblivious to the client. Is flask server somehow modifying the model repository contents?
Additionally, 21.08 version is very old. Can you try latest triton release?

**Comment by sourabh-burnwal** [comment]
> Is flask server somehow modifying the model repository contents?

Yes, I am using `--model-control-model=explicit`, and modifying model repository on the fly. So on receiving a load request at the flask server, I am modifying some fields in config.pbtxt, before sending the actual load request to Triton.

> Additionally, 21.08 version is very old. Can you try latest triton release?

This won't be possible for me to do since many of my models are on a older cuda version.

**Comment by sourabh-burnwal** [comment]
Thanks for your reply @tanmayv25! There was a bug in my code which was unloading the models. Closing the issue.
