### ISSUE TITLE
Cannot enable OpenTelemetry trace option; "unrecognized option"

### ISSUE THREAD

**Issue by kencieszykowski** [triton-inference-server/server#5794]
**Description**
We are trying to utilize the new OpenTelemetry feature of 23.04; but the pod is crashing upon startup with `unrecognized option`.  

**Triton Information**
What version of Triton are you using?
```
nvcr.io/nvidia/tritonserver:23.04-py3
```

**To Reproduce**
Steps to reproduce the behavior.

In the `containers.args` list, we have:

```
        - tritonserver
        - --disable-auto-complete-config
        - --log-verbose=0
        - --allow-gpu-metrics=true
        - --metrics-interval-ms=1000
        - '--trace-config mode=opentelemetry'
        - '--trace-config opentelemetry,url="$(DATADOG_TRACE_AGENT_HOSTNAME):8126"'
```

**Expected behavior**

I'd expect the trace-config global mode to initiate using OpenTelemetry, but instead we get a container startup error mentioning that this is an unreocgnized option.

We have essentially based it off this Helm chart [template here](https://github.com/triton-inference-server/server/blob/main/deploy/gcp/templates/deployment.yaml), where it seems like any extra args are passed in the the `container.args` list.  It's possible that this may be an issue with how the main running command is getting parsed/constructed, but any advice would be much appreciated.

**Comment by kencieszykowski** [comment]
Well; we can close this.  Came down to user error.

Due to the way k8s parses the Args list, we had success with:

```
        - --trace-config
        - mode=opentelemetry
        - --trace-config
        - opentelemetry,url="$(DATADOG_TRACE_AGENT_HOSTNAME):8126"
```

**Comment by MatthieuToulemont** [comment]
@kencieszykowski did you manage to hook it up with Datadog ?
