### ISSUE TITLE
ubuntu 20.04 GDB 10.2 debug child process occurred error；

### ISSUE THREAD

**Issue by ltdo111** [triton-inference-server/server#5804]
**Description**
I am trying to debug a subprocess started under model_repository with GDB, but it is giving me an error; 

**Triton Information**
main tag 

Are you using the Triton container or did you build it yourself?
build by my self 

**To Reproduce**
**1. pwd**
I had build tritonserver by myself ;
![image](https://github.com/triton-inference-server/server/assets/17394163/45b1192f-e5f2-407f-9af9-3f1fcb2153c9)

**2.start gdb： gdb -tui tritonserver**
* gdb -v 
![image](https://github.com/triton-inference-server/server/assets/17394163/7ebc2ac8-882d-44a2-9542-06a4e3da57ae)

* gdb -tui tritonserver
![image](https://github.com/triton-inference-server/server/assets/17394163/6d77c5b8-400c-4db8-95e4-19d6c0da3d86)

**3.set follow-fork-mode child**

**4.start the tritonserver process**
* below the cmd
start --model-repository  /workspace/tritonserver/model-repository  --backend-directory /tmp/tritonbuild/install/backends --http-port 10000  --log-verbose 1  --log-info true --log-warning true --log-error true --log-format ISO8601 --log-file ./triton.log --id tritonserver &

## Sometimes an error may occur, like the one shown below.
![image](https://github.com/triton-inference-server/server/assets/17394163/621e6991-0cf6-4422-bbee-6c5f06439f21)

## Sometimes the error shown above may not occur. Below is a relatively normal scenario, but I still can’t trigger the breakpoint
* continue 
![image](https://github.com/triton-inference-server/server/assets/17394163/451e98b2-1527-4710-b743-88b58481a6f8)

* info inferiors 
![image](https://github.com/triton-inference-server/server/assets/17394163/82371b52-1919-471d-b444-9d8de38fb594)

* info break && jump *xxxx
![image](https://github.com/triton-inference-server/server/assets/17394163/66e28c67-eb34-482f-838f-68d68c87e039)

I am capturing a breakpoint triggered by a request.
* like this： 
```shell
curl -v http://localhost:10000/v2/models/guix_roiextractor_onnx-V0/versions/1/infer -H "Content-Type: application/json" -H "Inference-Header-Content-Length: 0" -H "Input-Content-Type: application/json" -d '{"inputs":[{"name":"url","dims
":[1],"datatype":"TYPE_STRING","data":"http://xxx-xxx-b-algo.cn-shanghai-xxx-office.oss-ali.xxxx.com/293923%2Fguix%2Fdata%2Fdemo%2Fstarbucks_order.jpg"}]}' --output - 
```

* This is the location where I set the breakpoint.
![image](https://github.com/triton-inference-server/server/assets/17394163/d505ed72-17e8-4d37-b055-5b9c05e400d6)

## I have upgraded my gdb version once, but I still can't trigger the breakpoint in the child process when the request is received. Here are my possible reasons for this:
* Is it possible that Triton's child process cannot be debugged through gdb?
* Although I upgraded from version 9.1 to 10.2, is my gdb version still relatively low?
* Is it possible that I input the wrong command or missed some instructions when using gdb for debugging?

How do you normally debug sub-processes with gdb during development?  
Can you write a guide for me on this issue? I have been struggling with it for three days。

**Comment by ltdo111** [comment]
Can you help me please? Thank you very much！

**Comment by ltdo111** [comment]
I had solve this problem， by gdb attach 
Thank you ！

**Comment by krishung5** [comment]
@ltdo111 Glad it works! Closing this issue as it's resolved. Please let us know if you would like this ticket reopened for follow-up.
