### ISSUE TITLE
Tritonserver:23.04 crashes, but it wasn't with 23.03.

### ISSUE THREAD

**Issue by sagneun** [triton-inference-server/server#5809]
**Description**
I am working on a **Mac M1 Max chip** and I have deployed python model using tritonserver:23.04. also, I run it on **cpu-only system**. When I make a request to it, the below error received.
![image](https://github.com/triton-inference-server/server/assets/14901338/33fd06c2-ce93-439b-a672-ece0fb0fb862)

**Triton Information**
What version of Triton are you using?
23.04-py3

Are you using the Triton container or did you build it yourself?
using triton container

**To Reproduce**
My project is very simple.
1. This is the directory structure of my model repository:
```
.
├── Dockerfile
└── model_repository
   └── test_1
        ├── 1
        │   └── model.py
        └── config.pbtxt
```

2. The config of ```model.py``` is:
```
name: "test_1"
backend: "python"
input [
{
    name: "INPUT_0"
    data_type: TYPE_UINT8
    dims: [ -1 ]
}
]

output [
{
    name: "OUTPUT_0"
    data_type: TYPE_UINT8
    dims: [ 10, 10, 3 ]
}
]

instance_group [{ kind: KIND_CPU }]
```

3. ```model.py``` mainly includes:
```
def execute(self, requests):
    output0_dtype = self.output0_dtype

    responses = []
    for request in requests:
        in_0 = pb_utils.get_input_tensor_by_name(request, "INPUT_0") #ignore
        img_out = np.ones((10, 10, 3), dtype="uint8")

        print(img_out)

        out_tensor_0 = pb_utils.Tensor("OUTPUT_0",
                                       img_out.astype(output0_dtype))
        inference_response = pb_utils.InferenceResponse(
            output_tensors=[out_tensor_0])
        responses.append(inference_response)
    return responses
```

4. ```client.py``` is:
```
import tritonclient.http as httpclient
from tritonclient.utils import *
import sys

if __name__ == "__main__":
    try:
        triton_client = httpclient.InferenceServerClient(
            url="localhost:8000", verbose=False)
    except Exception as e:
        print("channel creation failed: " + str(e))
        sys.exit(1)

    inputs = []
    outputs = []
    input_name = "INPUT_0"
    output_name = "OUTPUT_0"
    input_data = np.array([0, 0, 0], dtype="uint8")

    inputs = [
        httpclient.InferInput("INPUT_0", input_data.shape, np_to_triton_dtype(input_data.dtype))
    ]
    outputs.append(httpclient.InferRequestedOutput(output_name))

    inputs[0].set_data_from_numpy(input_data)
    results = triton_client.infer(model_name="test_1",
                                  inputs=inputs,
                                  outputs=outputs)

    output0_data = results.as_numpy(output_name)
    print(output0_data)
```

5. ```Dockerfile``` is:
* I just add to install numpy
```
FROM nvcr.io/nvidia/tritonserver:23.04-py3
EXPOSE 8000

RUN pip install numpy

COPY --chown=triton-server:triton-server ./model_repository /models
CMD ["tritonserver", "--model-repository=/models", "--log-verbose=1", "--model-control-mode=explicit", "--load-model=*", "--disable-auto-complete-config"]
```

6. How to build docker:
```
$docker build -t test2304:0.0.1 -f Dockerfile .
```

7. Finally, I run this:
```
$docker run -it --rm -p 8000:8000 test2304:0.0.1
```

**Expected behavior**
I expected the service returns ones array that has (10, 10, 3) shape without any crash issue, as model code shows. When I tried to them equally on earlier versions (23.02-py3 and 23.03-py3), there was not any problem.
Additionally, through ```$ curl -v localhost:8000/v2/health/ready```, the server looks ok.
![image](https://github.com/triton-inference-server/server/assets/14901338/1e697efc-22f9-4dc8-92eb-a9cc6b3c4b15)

**Comment by dyastremsky** [comment]
We don't officially support Mac M1, so we can't provide guidance on this. It's great that it worked in 23.02 and 23.03. Dependencies change as well as code and we only test architectures that we support. If you need further guidance, you could try opening a discussion under Discussions in case other users can help.
