### ISSUE TITLE
python_backend dlpack: Bool type is not supported

### ISSUE THREAD

**Issue by cceyda** [triton-inference-server/server#5820]
**Description**
Using python_backend I get `"RuntimeError: Bool type is not supported by dlpack"` with the below code.
It is true that logits is of type bool. But dlpack seems to support bool at least on newer versions according to this: https://github.com/dmlc/dlpack/issues/75 & https://github.com/dmlc/dlpack/pull/114

**Triton Information**
official ngc 23.04 container

**To Reproduce**
```
logits = pb_utils.get_output_tensor_by_name(inference_response, 'logits')
logits = logits.to_dlpack()
```

**Expected behavior**
should work

**Comment by oandreeva-nv** [comment]
Bool type will be supported by dlpack in python backend starting with 23.05 release.
