### ISSUE TITLE
[Question] How does triton server use s3 as model-respoitory?

### ISSUE THREAD

**Issue by seoungbae-park** [triton-inference-server/server#5835]
How does triton load s3 objects? 

Does it download model, config etc... to anywhere in triton cache?

or does it use some aws fs ?

**Comment by dyastremsky** [comment]
S3 is treated the same as any other file source. There is some interaction in terms of polling the model repository, but when models are loaded, the config information gets loaded into Triton and the models get loaded in a backend-specific way.

Information on loading from S3 is here: https://github.com/triton-inference-server/server/blob/main/docs/user_guide/model_repository.md#s3

If you'd like the detailed code mechanics, you're welcome to look into the pieces of the code that interest you. For example, the core filesystem handling is [here.](https://github.com/triton-inference-server/core/blob/main/src/filesystem.cc)

**Comment by tsinggggg** [comment]
@dyastremsky Is it true that in case of s3(and other cloud storage solutions), Triton actually downloads the model files(both the config and model files) to a local temp folder? Thank you!


Local temp folder: https://github.com/triton-inference-server/core/blob/c6c45ffb0fbfd81255c63f9a4d7cbc23fcaf65e8/src/filesystem/implementations/local.h#L317C1-L318

Localize: https://github.com/triton-inference-server/core/blob/c6c45ffb0fbfd81255c63f9a4d7cbc23fcaf65e8/src/filesystem/implementations/s3.h#L630C15-L630C27

**Comment by tsinggggg** [comment]
@dyastremsky thanks for the response! Do you know when/if these temp dirs are removed/cleaned up? for example, when the model finishes loading, or the model is unloaded, etc..

**Comment by dyastremsky** [comment]
It looks like they persist only as long as the model is loaded: https://github.com/triton-inference-server/core/blob/c6c45ffb0fbfd81255c63f9a4d7cbc23fcaf65e8/src/backend_model.cc#L77
