### ISSUE TITLE
Onnxruntime backend `gpu_mem_limit` is not respected 

### ISSUE THREAD

**Issue by jturner116** [triton-inference-server/server#5844]
**Description**
I have tried to set `gpu_mem_limit` to cap the memory usage of a BERT model at 1500MB. In testing, I slowly incremented up `max_batch_size` to try to force an OOM once the `gpu_mem_limit` had been reached, but it just exceeded the limit and did not throw any warning/error. The memory limit I set shows up in the config from the Triton Client, but I still wonder if my config file is not correct?

**Triton Information**
nvcr.io/nvidia/tritonserver:22.10-py3   

Are you using the Triton container or did you build it yourself?
Container

**To Reproduce**
Here is my Bert config
```
name: "bert_category"
backend: "onnxruntime"
max_batch_size: 32
input [
    {
        name: 'token_type_ids'
        data_type: TYPE_INT64
        dims: [ -1]
    },
    {
        name: 'attention_mask'
        data_type: TYPE_INT64
        dims: [ -1]
    },
    {
        name: 'input_ids'
        data_type: TYPE_INT64
        dims: [ -1]
    }
]
output [
    {
        name: 'logits'
        data_type: TYPE_FP32
        dims: [465]
    }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [ 0 ]
  }
]
dynamic_batching 
  {
    preferred_batch_size: 2
  }
parameters { key: "gpu_mem_limit" value: { string_value: "1500000000" } }
```

**Expected behavior**
I expect a request to throw an error similar to the error thrown when a batch size larger than `max_batch_size` is sent. 

Thanks for your help :)

**Comment by dyastremsky** [comment]
This parameter gets passed to ONNX Runtime for execution, which [will take care of limiting the CUDA memory](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#gpu_mem_limit) for the instance. You can see this here: https://github.com/triton-inference-server/onnxruntime_backend/blob/d815e2c8e86e4ea028415e2cee927e95fde2fd90/src/onnxruntime.cc#L537-L552

Your config looks fine to me. And if you're seeing it show up in the logs, then it shouldn't be an issue with the config. Can you try increasing the batch size further and see if you get an error? To make sure it's not a difference between how you're calculating the memory usage versus how the execution context is. And try running on the latest Triton, if possible (23.04).

If the issue persists, we can try to reproduce the issue and investigate it.
