### ISSUE TITLE
Unknown performance bottleneck when using ensemble model

### ISSUE THREAD

**Issue by E-Aho** [triton-inference-server/server#5865]
Hi!

I'm running an ensemble model on Triton 22.08. The model is composed of a simple tokenizer running on a Python backend on a CPU, and an ONNX model running on a GPU instance.

I have been tweaking config options, and used to have a variant of the ensemble model running at ~350 inference/sec on production hardware. I have reverted to what I thought that version was, running on identical hardware, and now can't get even 20 rps consistently on the ensemble model, despite the tokenizer getting comfortably ~500rps and the model itself being able to run ~400rps, given the right batch sizes.

I've been trying to debug this for a week now, and have no idea what is wrong. I had it working before, and now, with seemingly the same configs, it's not even close.

I've monitored resource usage, and for some reason, the model has a humungous queue and time spent processing in the ensemble model, and very high GPU utilization when compared to it running the model by itself.

I am wondering if there are any insights into what might be causing this problem? 

I know that it is *possible* to fix this, it was working fine earlier, I just don't know what has changed since it was working earlier this week.

Config files for the models and some results from perf_analyzer are in comments below.

**Comment by E-Aho** [comment]
Perf analysis results, along with GPU utilisations obtained during test
                                                                               
### Model

```Request concurrency: 20
  Client: 
    Request count: 6048
    Throughput: 335.954 infer/sec
    Avg latency: 59469 usec (standard deviation 481 usec)
    p50 latency: 59462 usec
    p90 latency: 59789 usec
    p95 latency: 59883 usec
    p99 latency: 60104 usec
    Avg HTTP time: 0 usec (send/recv 0 usec + response wait 0 usec)
  Server: 
    Inference count: 6048
    Execution count: 605
    Successful request count: 6048
    Avg request latency: 59287 usec (overhead 104 usec + queue 28517 usec + compute input 42 usec + compute infer 30599 usec + compute output 25 usec)

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA TITAN RTX    Off  | 00000000:3B:00.0 Off |                  N/A |
| 41%   40C    P2   126W / 280W |   3825MiB / 24576MiB |     35%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
```


### Tokenizer
```
Request concurrency: 16
  Client: 
    Request count: 8473
    Throughput: 470.634 infer/sec
    Avg latency: 33980 usec (standard deviation 834 usec)
    p50 latency: 33782 usec
    p90 latency: 34516 usec
    p95 latency: 34940 usec
    p99 latency: 37700 usec
    Avg HTTP time: 0 usec (send/recv 0 usec + response wait 0 usec)
  Server: 
    Inference count: 8474
    Execution count: 8474
    Successful request count: 8474
    Avg request latency: 33846 usec (overhead 5 usec + queue 31726 usec + compute input 17 usec + compute infer 2076 usec + compute output 21 usec)

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA TITAN RTX    Off  | 00000000:3B:00.0 Off |                  N/A |
| 41%   34C    P8    15W / 280W |   3825MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
```


### Ensemble
```
Request concurrency: 5
  Client: 
    Request count: 460
    Throughput: 12.7767 infer/sec
    Avg latency: 390831 usec (standard deviation 1918 usec)
    p50 latency: 390677 usec
    p90 latency: 393388 usec
    p95 latency: 393702 usec
    p99 latency: 393998 usec
    Avg HTTP time: 390822 usec (send/recv 76 usec + response wait 390746 usec)
  Server: 
    Inference count: 460
    Execution count: 460
    Successful request count: 460
    Avg request latency: 390551 usec (overhead 132 usec + queue 192382 usec + compute 198037 usec)

  Composing models: 
  model, version: 
      Inference count: 9200
      Execution count: 184
      Successful request count: 460
      Avg request latency: 385992 usec (overhead 108 usec + queue 190262 usec + compute input 46 usec + compute infer 195550 usec + compute output 25 usec)

  tokenizer, version: 
      Inference count: 460
      Execution count: 460
      Successful request count: 460
      Avg request latency: 4541 usec (overhead 6 usec + queue 2120 usec + compute input 16 usec + compute infer 2370 usec + compute output 28 usec)



+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA TITAN RTX    Off  | 00000000:3B:00.0 Off |                  N/A |
| 41%   63C    P2   197W / 280W |   3249MiB / 24576MiB |     58%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

```

Note the suddenly very high power usage by the GPU in the ensemble

**Comment by E-Aho** [comment]
### Configs

**Tokenizer**

```
name: "tokenizer"
backend: "python"
max_batch_size: 8
input [
  {
    name: "text"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]
output [
   {
    name: "tokens"
    data_type: TYPE_INT32
    dims: [ 192 ]
  }
]

instance_group [
    {
        name: "tokenizer"
        kind: KIND_CPU
    }
]

parameters: {
  key: "EXECUTION_ENV_PATH",
  value: {string_value: "$$TRITON_MODEL_DIRECTORY/env/tokenizer-env.tar.gz"}
}

default_model_filename: "tokenizer.py"```


**Model**

```
name: "model"
backend: "onnxruntime"
version_policy: {
    latest: {
        num_versions: 1
    }
}


max_batch_size: 512

input [
    {
        name: "tokens"
        data_type: TYPE_INT32
        dims: [ 192 ]
    }
]
output [
    {
        name: "output"
        data_type: TYPE_FP32
        dims: [ 10 ]
    }
]

dynamic_batching {
    max_queue_delay_microseconds: 50000
    preserve_ordering: false
    priority_levels: 0
    default_priority_level: 0
    default_queue_policy: {
       default_timeout_microseconds: 300000
       max_queue_size: 10000
    }

}


optimization {
  priority: PRIORITY_DEFAULT
  input_pinned_memory: {
    enable: true
  }
  output_pinned_memory: {
    enable: true
  }
  execution_accelerators {
    gpu_execution_accelerator {
      name: "tensorrt"
      parameters {
        key: "max_workspace_size_bytes"
        value: "4294967296"
      }
      parameters {
        key: "precision_mode"
        value: "FP32"
      }
    }
  }
}

instance_group [
    {
        name: "model"
        kind: KIND_GPU
        count: 1
        gpus: [ 0 ]
    }
]

model_warmup [
{
    name : "zero warmup"
    batch_size: 1
    inputs {
        key: "tokens"
        value: {
            data_type: TYPE_INT32
            dims: 192
            zero_data: true
        }
    }
}]

default_model_filename: "model.onnx"
```

**Ensemble**
```name: "ensemble"
platform: "ensemble"
max_batch_size: 0
input [
  {
    name: "text"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]
output [
    {
        name: "output"
        data_type: TYPE_FP32
        dims: [ 10 ]
    }
]
ensemble_scheduling {
  step [
    {
      model_name: "tokenizer"
      model_version: -1
      input_map {
        key: "text"
        value: "text"
      }
      output_map [
          {
            key: "tokens"
            value: "tokens"
          }
      ]
    },
    {
      model_name: "model"
      model_version: -1
      input_map {
        key: "tokens"
        value: "tokens"
      }
      output_map [
       {
          key: "output"
          value: "output"
       }
      ]
    }
  ]
}```

**Comment by Tabrizian** [comment]
@E-Aho Given that it looks like tokenizer is faster than the model, maybe the onnx model doesn't provide better performance when the batch size is large? Have you tried lowering the `max_batch_size` for the ONNX model? [Model Analyzer](https://github.com/triton-inference-server/model_analyzer) can also help you find the optimum max_batch_size for your model.

**Comment by E-Aho** [comment]
Hi @Tabrizian

Yes, that batch size was the optimal batch size found during a lot of runs with Model Analyzer (running the ONNX model independently, not in ensemble).

As said, with the 8 batch size for the tokenizer and 512 for the ONNX model, the ensemble model was earlier able to run at ~350rps, whereas now, with seemingly no changes, the ensemble struggles to get 20rps.

I'm going to continue to investigate, but my current thoughts are the issue is either:

1) An issue with how the requests are batched/moved between the models
2) An issue with hardware/resource competition between models.

The part that is confusing me the most is why this is suddenly an issue whereas before it was fine. 

Are there any things to consider when running one model on CPU and one model on GPU?

**Comment by Tabrizian** [comment]
Hi @E-Aho, please feel free to share if you've managed to find the bottleneck. It might be helpful for other people running into the same issue.

**Comment by ChowXu** [comment]
Hi @E-Aho & @Tabrizian , is there any update on the issue? I encountered a similar issue recently.
