### ISSUE TITLE
multi-gpu error

### ISSUE THREAD

**Issue by Goddard** [triton-inference-server/server#5870]
Using riva quickstart 11 with triton server.  

When I execute triton server using the additional riva features I am getting this error.
https://pastebin.ubuntu.com/p/PZtjYpwxps/

This only occurs with multile gpus.  Works fine with 1.  Pretty sure it isn't an issue with not enough memory.  All GPUs are the same and have 16 gigs of memory.  Also asking about it on the forum - https://forums.developer.nvidia.com/t/multiple-gpu-error/254579/4

**Comment by rmccorm4** [comment]
Hi @Goddard,

The issues shared in your pastebin log look specific to code in the RIVA service. I don't think there's anything Triton-specific there. Looks like someone has responded to your forum post, so I will let the conversation go there and close this issue for now. If there turn out to be Triton-specific issues, feel free to open a new issue / reference this one.
