### ISSUE TITLE
[Question] Can not infer model because of batch in  client  request smaller than batch config in server

### ISSUE THREAD

**Issue by phamkhactu** [triton-inference-server/server#5879]
I've set config: ```max_batch_size=16``` in ensemble(Triton server), I send batch=8  from client to server.
I get error:
```
request specifies invalid shape for input 'input' for ocr. Error details: model expected the shape of dimension 0 to be between 16 and 16 but received 8
``` 
From [solving issue](https://github.com/triton-inference-server/server/issues/3527#issuecomment-962213150), I understand that Triton can handle dynamic batch as long as batch from client in range: [0:16]. But in my case, batch =8.

Here is my configs in ensemble:
```
name: "ensemble_model_ocr"
platform: "ensemble"
max_batch_size: 16
input [
  {
    name: "IMAGE"
    data_type: TYPE_FP32
    dims: [ 3, 32 , 128 ]
  }
]
output [
  {
    name: "OUTPUT_TEXT"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]
ensemble_scheduling {
  step [
    {
      model_name: "ocr"
      model_version: -1
      input_map {
        key: "input"
        value: "IMAGE"
      }
      output_map {
        key: "output"
        value: "output_pred"
      }
    },
    {
      model_name: "ocr_postprocess"
      model_version: -1
      input_map {
        key: "ocr_pred"
        value: "output_pred"
      }
      output_map {
        key: "text"
        value: "OUTPUT_TEXT"
      }
    }
  ]
}
```
OCR config:
```
name: "ocr"
platform: "tensorrt_plan"
max_batch_size: 16
input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [  3, 32, 128 ]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ 26,95 ]
  }
]
```
Thank you

**Comment by jturner116** [comment]
Hey pham haha. If you try including `dynamic_batching` in either or both, would it work?
```
dynamic_batching 
  {
    preferred_batch_size: 8
  }
  ```

**Comment by rmccorm4** [comment]
Hi @phamkhactu,

Does your OCR model support actually batching? The error appears to indicate the model expects a fixed batch size of 16. In TensorRT terms I think that translates to the [Optimization Profile] (https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Core/OptimizationProfile.html) having something like this:
```
min_shape = [16, 3, 32, 128]
opt_shape = [16, 3, 32, 128]
max_shape = [16, 3, 32, 128]
```
Instead of something like this:
```
min_shape = [1, 3, 32, 128]
opt_shape = [8, 3, 32, 128]
max_shape = [16, 3, 32, 128]
```
If your model should support batching, I would verify the model correctness like above.

If your model doesn't support batching, you should set `max_batch_size=0` and set full explicit shapes something like this in your Triton `config.pbtxt`:
```
name: "ocr"
platform: "tensorrt_plan"
max_batch_size: 0
input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [  16, 3, 32, 128 ]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ 16, 26,95 ]
  }
]
```

**Comment by phamkhactu** [comment]
Hi @rmccorm4 @jturner116,
I've found that this error come from explicit batch when convert model(tf, torch,..) to onnx.
So I've fixed issue.
Thank you.
