### ISSUE TITLE
How to interpret perf_analyzer results

### ISSUE THREAD

**Issue by benhgm** [triton-inference-server/server#5886]
**Description**
Hi everyone, I'd like to clarify how to interpret the results given by the perf_analyzer tool.

I see that there are two main metrics give at the end of each analysis:
- throughput (infer/sec)
- latency (usec)

I am interested to know what the throughput results mean for different batch sizes, concurrency levels and number of model instances.

For example, for an image classification model, if the analysis gives me a throughput of 300 infer/sec, using a batch size of 8 and 2 model instances, does this mean that my model inference speed is 300 inferences * 8 images * 2 models = 4800 frames of data per second?

Otherwise, what is the correct way of interpreting the results?

**Comment by dyastremsky** [comment]
I think this is just on the request level. So, on average, 300 inferences are happening per second. And the average latency would be the average latency for a single request.

CC: @matthewkotila for awareness.

**Comment by dyastremsky** [comment]
The [documentation](https://github.com/triton-inference-server/client/blob/main/src/c++/perf_analyzer/docs/measurements_metrics.md#metrics) also indicates the latency and throughput measures are per request and provide additional details.

**Comment by TheConstant3** [comment]
> The [documentation](https://github.com/triton-inference-server/client/blob/main/src/c++/perf_analyzer/docs/measurements_metrics.md#metrics) also indicates the latency and throughput measures are per request and provide additional details.

Hi!
If the throughput measures are per request, why do I have a decrease in throughput as the number of model instances increases?
<img width="969" alt="Снимок экрана 2023-12-20 в 11 46 58" src="https://github.com/triton-inference-server/server/assets/46416203/4796109b-76a4-49d3-bf94-668eb0dc50c9">

**Comment by quanqigu** [comment]
@dyastremsky if batch size is 4 and throughput is 400, does this means it actually inference 400*4 frame per second?
