### ISSUE TITLE
Triton server produces inconsistent results 

### ISSUE THREAD

**Issue by phamkhactu** [triton-inference-server/server#5891]
Thanks for excellent repo.

I've tested my model with Triton, but I've encountered problems:  inconsistent results **with same input** during inference phase.

Here is my procedure:
- I convert my model to ```trtexec``` with dynamic input model:
```
trtexec --onnx=qat_enn_space_not_fintune_86_dynamic_batch.onnx --int8 --minShapes=input:1x3x32x128 --optShapes=input:8x3x32x128 --maxShapes=input:16x3x32x128 --saveEngine=model_dynamic.plan
``` 
My config:
```
name: "ocr"
platform: "tensorrt_plan"
max_batch_size: 8
input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [  3, 32, 128 ]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ 26,95 ]
  }
]
version_policy: { specific: { versions: [2]}}
instance_group [
    {
      count: 2
      kind: KIND_GPU
      gpus: [ 0, 1 ]
    }
  ]
```

- I have 24  images cropped from original image as input.
![image](https://github.com/triton-inference-server/server/assets/42369268/f4f672d8-e541-48fc-8712-f5a258c564dd)

- I separate my test case to 4 phases:
+) phase 1: get 0th image to 15th image (batch_size=16)
+) phase 2: get 16th image to 24th image (batch_size=8)
+) phase 3: get 8th image to 24th image (batch_size=16)
+) phase 4: get 0th image to 8th image (batch_size=8)

Here is my code:
```
print("*"*50)
print("Case1:")
ocr_imgs = img_processed[0:16]
input_ocr = httpclient.InferInput("IMAGE",shape=ocr_imgs.shape ,  datatype="FP32")
input_ocr.set_data_from_numpy(ocr_imgs, binary_data=True)

ocr_results = client.infer(model_name="ensemble_model_ocr",  inputs=[input_ocr], outputs=[output_text])
texts = ocr_results.as_numpy("OUTPUT_TEXT")
print(texts)

print("*"*50)
print("Case2:")
ocr_imgs = img_processed[16:]
input_ocr = httpclient.InferInput("IMAGE",shape=ocr_imgs.shape ,  datatype="FP32")
input_ocr.set_data_from_numpy(ocr_imgs, binary_data=True)

ocr_results = client.infer(model_name="ensemble_model_ocr",  inputs=[input_ocr], outputs=[output_text])
texts = ocr_results.as_numpy("OUTPUT_TEXT")
print(texts)


print("*"*50)
print("Case3:")
ocr_imgs = img_processed[8:]
input_ocr = httpclient.InferInput("IMAGE",shape=ocr_imgs.shape ,  datatype="FP32")
input_ocr.set_data_from_numpy(ocr_imgs, binary_data=True)

ocr_results = client.infer(model_name="ensemble_model_ocr",  inputs=[input_ocr], outputs=[output_text])
texts = ocr_results.as_numpy("OUTPUT_TEXT")
print(texts)

print("*"*50)
print("Case4:")
ocr_imgs = img_processed[0:8]
input_ocr = httpclient.InferInput("IMAGE",shape=ocr_imgs.shape ,  datatype="FP32")
input_ocr.set_data_from_numpy(ocr_imgs, binary_data=True)

ocr_results = client.infer(model_name="ensemble_model_ocr",  inputs=[input_ocr], outputs=[output_text])
texts = ocr_results.as_numpy("OUTPUT_TEXT")
print(texts)
```

**Here is my Result. I see that the inconsistent outputs with same input. (I see that results only truth if using max_batch_size=16)**
```
Case1:
[b'614874.667' b'1193340.990' b'4.001' b'1193337.121' b'614875.706' b'4'
 b'16.512' b'11933415590' b'614891.601' b'3' b'4.059' b'1193345.253'
 b'614889.853' b'2' b'15.754' b'1193340.990']
**************************************************
Case2:
[b'C{;*_d' b'S \\*' b'#' b']Uf@&+' b']<#x^/V(>_"4{`]=H'
 b' #\\Ew]~(*[*qW^S=' b's#^=#9^^]R]/?=x%{$z@[,[<]B'
 b' d!`\\;L$\\]"_]xq=]T@]=[*']
**************************************************
Case3:
[b'614891.601' b'3' b'4.059' b'1193345.253' b'614889.853' b'2' b'15.754'
 b'1193340.990' b'614874.687' b'1' b'Yim)' b'X(m)' b'TT' b'Sim' b'Toadd'
 b'So']
**************************************************
Case4:
[b']wo "*!lx;=]@Q,IK=/' b'[{R' b'J#F^)' b'}:#|#j(#' b'qx~/=JXX#^z[):'
 b'$[' b'q&,ju*ft(\\#I#e**V^###+^ ({' b'[@]>?\\{b_|&@*`<>">']
```
Thank you.

**Comment by casperroo** [comment]
Hi, 
I had the same problem. It is due to float operations sequence:

See this issue:  https://github.com/triton-inference-server/server/issues/5640

**Comment by phamkhactu** [comment]
> Hi, I had the same problem. It is due to float operations sequence:
> 
> See this issue: #5640

Hi @casperroo,
I've read your issue and [doc](https://github.com/triton-inference-server/python_backend/tree/main#pytorch-determinism).
But I think  in my case, these differences are large enough for changing my result. How do you solve it ??

**Comment by casperroo** [comment]
> 
Hi,

I didn't solve it. In my case the small differences didn't matter - I was just wondering it this is expected. And it turned it was.
TF has a determinism option and that was added in https://github.com/triton-inference-server/python_backend/pull/233 
Only now I have have realized that your case is completely different (wasn't reading carefully enough for the first time). Sorry.

**Comment by phamkhactu** [comment]
> > 
> 
> Hi,
> 
> I didn't solve it. In my case the small differences didn't matter - I was just wondering it this is expected. And it turned it was. TF has a determinism option and that was added in [triton-inference-server/python_backend#233](https://github.com/triton-inference-server/python_backend/pull/233) Only now I have have realized that your case is completely different (wasn't reading carefully enough for the first time). Sorry.

yeah, You are well come!
Thank you very much for your sharing.

**Comment by rmccorm4** [comment]
Hi @phamkhactu,

Can you try verifying your model outputs in these cases outside of Triton? From your client script, I suspect it may not be specific to Triton. Tools like [Polygraphy](https://github.com/NVIDIA/TensorRT/tree/main/tools/Polygraphy) or a simple ONNRT/TRT Python API script may help quickly verify some outputs.

**Comment by phamkhactu** [comment]
> Hi @phamkhactu,
> 
> Can you try verifying your model outputs in these cases outside of Triton? From your client script, I suspect it may not be specific to Triton. Tools like [Polygraphy](https://github.com/NVIDIA/TensorRT/tree/main/tools/Polygraphy) or a simple ONNRT/TRT Python API script may help quickly verify some outputs.

Hi @rmccorm4,

I found that it come from version Tensorrt in Triton sever.  With same model ```.onnx``` I've used 2 version trtexec to convert.
- With version tensorrt 8.4.2.4(Triton 22.08) : Cause issue above
- With version tensorrt 8.5.3.1(Triton 23.03) : not cause

**Comment by rmccorm4** [comment]
Hi @phamkhactu, this sounds like a TensorRT version then. I would post in https://github.com/NVIDIA/TensorRT/issues if your model conversion is producing bad results across versions. Though it if works in the latest version (23.05 at this time), then that may be the proposed solution.

**Comment by phamkhactu** [comment]
@rmccorm4 thank you very much
