### ISSUE TITLE
Python version used in backend updated to 3.10?

### ISSUE THREAD

**Issue by sandeshan** [triton-inference-server/server#5895]
Hello,

I'm upgrading our team's Triton services, which are currently running version 23.02, to the latest version 23.05. According to the the python backend [docs](https://github.com/triton-inference-server/python_backend#managing-python-runtime-and-libraries), the version used in the official images is python3.8, but after updating our service to use the new version (tritonserver:23.05-py3), the python executable  (`/usr/bin/python3`) is clearly using python3.10. This change has broken how we consume our custom python packages as we have only building for python3.8.

I also found some references in the repo that talk about python3.10 now being used, [example](https://github.com/triton-inference-server/server/pull/5775) but there are no mentions of python3.10 in the docs itself.

Is this change intended and official? If so, the docs need to be updated to reflect that. And what is the best way to check the version of python that is included in the container images?

**Comment by Tabrizian** [comment]
Hi @sandeshan, sorry that you're running into this issue. For 23.05 we've upgraded the base image to Ubuntu 22.04 which means that it would use Python 3.10. I've updated to the documentation to reflect the same. If you want to keep using Python 3.8, you would need to compile a custom Python backend stub.

**Comment by sandeshan** [comment]
Thanks for confirming @Tabrizian. I'm currently working on upgrading our python packages to build for 3.10, so that should unblock me.
