### ISSUE TITLE
how to serve thousands of models in python backend?

### ISSUE THREAD

**Issue by Jack47** [triton-inference-server/server#5902]
**Is your feature request related to a problem? Please describe.**
we are working on serving thousands stable diffusion models by using python backend. their inference logics are the same so we are using one Python  model.py code as a model definition.  We want to load/unload model's weight on the fly, but currently load/unload models api provided by triton is used to load different models, it's too heavy for us: 

1. currently it's time consuming to initialize a `new python backend model`(>=5s)
2. the model.py is same for these thousands sd models.

**Describe the solution you'd like**
any ways to easily extend the python backend to add custom operations? such as user defined load/unload_weights. 

**Describe alternatives you've considered**
provide ways to share states between different models under same backend?
 1. easily reuse one model.py to represent thousands of sd models
 2. share initialized pytorch models to short the initialize of triton model definition

**Additional context**
In triton, there are PythonBackend, Model, Model Instance defintions, how can we better leverage these abstractions to serving thousands of sd models which are using same pytorch code as model definitions?

**Comment by nv-kmcgill53** [comment]
Hi @Jack47, What you described is the correct understanding of Triton's architecture. If there are new weights to be loaded then Triton sees this as a new model which will go through the model loading lifecycle. As a clarification, Model Instances are copies of the same model (read weights), so you can target the same model with your request but be agnostic to the instance which it executes on. 

The way I am currently reading your request is that your team specifically wants to route requests to different _models_, i.e. `modelA` and `modelB`. Both `modelA` and `modelB` will have the same `model.py` file associated with them but they will be executing against different weights.  For more clarification, if you were to use the HTTP endpoint, would your two requests look like the following?
```
POST /v2/models/modelA/1/infer
POST /v2/models/modelB/1/infer
```

As it sounds like you have the need to just manipulate the directory structure of the model repository, you could write a [repository agent](https://github.com/triton-inference-server/server/blob/main/docs/customization_guide/repository_agents.md) to load the common `model.py` file when any one of the SD models is being loaded. See the [API here](https://github.com/triton-inference-server/core/blob/main/include/triton/core/tritonrepoagent.h#L388-L413). 

CC @GuanLuo @Tabrizian  for any clarifications or additions.

**Comment by nv-kmcgill53** [comment]
Are you able to speak to this behavior @Tabrizian?

**Comment by Tabrizian** [comment]
Hi @Jack47 / @sunieee, thank you for your interest in Python backend!

I was wondering how are you using the same Python model for all your model deployments?

Do you have a single Python model that loads all the weights for these models and you have many instances of this "single Python model"?

**Comment by Jack47** [comment]
we use same Python model because we are serving stable diffusion models, all the inference workflow are the same. we are changing the weights on the fly according to incoming request.

**Comment by tristan279** [comment]
Hi, also interested in this usecase!! I want to be able to have a 'base model' (one tar file). in the specific models, ui want to do a change to that model (e.g. add a Linear). But i want it to be fast, so preferably i don't want to load the base model in each instance, but i want to access it from shared cuda memory

**Comment by Tabrizian** [comment]
We recently added support for Python-based backends which could be applicable to your use-case. Please take a look at the documentation and let us know if you have any feedbacks: https://github.com/triton-inference-server/backend/blob/main/docs/python_based_backends.md
