### ISSUE TITLE
Provide server configuration through file

### ISSUE THREAD

**Issue by janjagusch** [triton-inference-server/server#5906]
**Is your feature request related to a problem? Please describe.**
Whenever I change the server configuration for Triton, I have to adjust the entry point script, which requires releasing a new image. For example, let's assume I want to change the log level from '_info_' to '_warning_'.

```sh
tritonserver \
  --log-info true
```

Would need to become

```
tritonserver \
  --log-warning true
```

I want to make such changes without releasing a new image version. Instead, I want to configure this through my Kubernetes deployment.

**Describe the solution you'd like**
I want to provide Triton server config through a file. My entry point would look something like this:

```
tritonserver \
  --config-file ./config.toml
```

My config file could look like this:

```toml
[logging]
info = false
warning = true
```

This would allow me to pass my config as a config map and mount it as a volume into my deployment.

**Describe alternatives you've considered**

One way to accomplish this is to make everything configurable through environment variables and then define these variables inside my deployment.

```
tritonserver \
  --log-info ${TRITON_LOG_INFO} \
  --log-warning ${TRITON_LOG_WARNING}
```

However, doing this exhaustively for all possible arguments takes time and effort.

Another solution would be to provide the entry point script as a config map and mount it into my deployment. But I feel like only providing the config would be cleaner.

**Comment by yeahdongcn** [comment]
https://github.com/triton-inference-server/server/pull/5582

Maybe this is what you are looking for?

**Comment by janjagusch** [comment]
> #5582
> 
> Maybe this is what you are looking for?

True, that's actually a pretty nice solution. I didn't think of that, thanks!
