### ISSUE TITLE
gRPC version mismatch between the Triton client and DeepStream

### ISSUE THREAD

**Issue by beomsik-park98** [triton-inference-server/server#5918]
Hi,

My application utilizes both the Triton client library and DeepStream for their respective purposes.
However, there is a discrepancy in the gRPC versions they employ, with one using v1.48.0 and the other using v1.38.0.
Consequently, this causes an error during the compilation process.

Is there an effective approach to integrating these two libraries within a single program?

Note: I'm using c++ Triton client library.

**Comment by nv-kmcgill53** [comment]
CC: @jbkyang-nvi

**Comment by jbkyang-nvi** [comment]
Can you update the deepstream library? If not. I you can fork the [third_party repo](https://github.com/triton-inference-server/third_party/blob/main/CMakeLists.txt#L117), and change these lines in the client cmake list:
https://github.com/triton-inference-server/client/blob/main/CMakeLists.txt#L66-L69 to your forked branch.

**Comment by beomsik-park98** [comment]
Thank you. I'll try it.
