### ISSUE TITLE
Triton server returns Request Timeout error after a few hours of continuous inference

### ISSUE THREAD

**Issue by sourabh-burnwal** [triton-inference-server/server#5920]
After a few hours (8-12) of continuous inference, Triton server becomes unresponsive to the requests. 

After it happens, inference requests on http and grpc endpoints return Request Timeout error. Checking the `index` of the server returns Triton health OK, and models healthy. I tried to unload/load the models and this was also working. Only the inference endpoints becomes stale. My ensemble consists of 7 python backend CPU models, 1 python backend GPU model, and 4 TensorRT backend models. The ensemble consists of 4 instances of each model. I have started 40 clients in 40 different threads, and sending the requests simultaneously. Can anyone help me what might be causing this?

Thanks!

**Comment by nv-kmcgill53** [comment]
Hi @sourabh-burnwal, to better assist you, can you please fill out our [issue template](https://github.com/triton-inference-server/server/blob/main/.github/ISSUE_TEMPLATE/bug_report.md). When filling out the steps to reproduce, can you also provide any logs during the time where the server became unresponsive? Thanks!

**Comment by sourabh-burnwal** [comment]
Somehow the behaviour changed in the subsequent stress tests. Thanks for replying @nv-kmcgill53. Closing this issue for now. If I face this issue again, will raise an issue in aforementioned format with logs.
