### ISSUE TITLE
How the aio stream client gets the response

### ISSUE THREAD

**Issue by WackyGem** [triton-inference-server/server#5929]
I have written my triton-server client based on the following [simple_grpc_aio_sequence_stream_infer_client.py](https://github.com/triton-inference-server/client/blob/main/src/python/examples/simple_grpc_aio_sequence_stream_infer_client.py), but I am not getting any response, so I would like to ask how to modify the code.

```python

import asyncio
import logging
import multiprocessing as mp
import time
import random
from typing import List

import numpy as np
import tritonclient.grpc.aio as grpcclient

from queue import Empty

from tritonclient.utils import np_to_triton_dtype

from nargabot.chatservice.model_protocol import InferArgs


def prepare_tensor(name, data):
    t = grpcclient.InferInput(
        name, data.shape, np_to_triton_dtype(data.dtype))
    t.set_data_from_numpy(data)
    return t


async def async_stream_yield(datas: List[InferArgs], task_ids, seq_id):
    count = 1
    for data, task_id in zip(datas, task_ids):
        prompt_arr = np.array([[data.prompt]]).astype(object)
        output_len_arr = np.ones_like([[data.prompt]]).astype(np.uint32) * data.output_len
        bad_word_list_arr = np.array([[""]]).astype(object)
        stop_word_list_arr = np.array([[""]]).astype(object)
        top_k_arr = (data.top_k * np.ones([prompt_arr.shape[0], 1])).astype(np.uint32)
        top_p_arr = data.top_p * np.ones([prompt_arr.shape[0], 1]).astype(np.float32)
        search_rate_arr = data.search_rate * np.ones([prompt_arr.shape[0], 1]).astype(np.float32)
        temperature_arr = data.temperature * np.ones([prompt_arr.shape[0], 1]).astype(np.float32)
        len_penalty_arr = data.len_penalty * np.ones([prompt_arr.shape[0], 1]).astype(np.float32)
        repetition_penalty_arr = data.repetition_penalty * np.ones([prompt_arr.shape[0], 1]).astype(np.float32)
        random_seed_arr = data.random_seed * np.ones([prompt_arr.shape[0], 1]).astype(np.uint64)
        inputs = [
            prepare_tensor("INPUT_0", prompt_arr),
            prepare_tensor("INPUT_1", output_len_arr),
            prepare_tensor("INPUT_2", bad_word_list_arr),
            prepare_tensor("INPUT_3", stop_word_list_arr),
            prepare_tensor("runtime_top_k", top_k_arr),
            prepare_tensor("runtime_top_p", top_p_arr),
            prepare_tensor("beam_search_diversity_rate", search_rate_arr),
            prepare_tensor("temperature", temperature_arr),
            prepare_tensor("len_penalty", len_penalty_arr),
            prepare_tensor("repetition_penalty", repetition_penalty_arr),
            prepare_tensor("random_seed", random_seed_arr),
        ]
        outputs = [grpcclient.InferRequestedOutput('OUTPUT_0'), grpcclient.InferRequestedOutput('sequence_length')]
        yield {
            "model_name": "ensemble",
            "inputs": inputs,
            "outputs": outputs,
            "request_id": task_id,
            "sequence_id": seq_id,
            "sequence_start": (count == 1),
            "sequence_end": (count == len(datas))
        }
        count = count + 1


class BatchWorker:

    def __init__(self,
                 data_queue: mp.Queue,
                 result_queue: mp.Queue,
                 batch_size: int = 8,
                 max_delay: float = 0.1,
                 ready_event: mp.Event = None
                 ) -> None:
        self.data_queue = data_queue
        self.result_queue = result_queue
        self.batch_size = batch_size
        self.max_delay = max_delay
        self.logger = logging.getLogger('Infer-Batch-Worker')
        if ready_event:
            ready_event.set()

    def callback(self, result, error):
        print("effect")
        if error:
            self.result_queue.put(error)
        else:
            self.result_queue.put(result.get_response(as_json=True))

    async def run(self):
        self.logger.info('Worker started!')

        async def async_request_iterator():
            while True:
                data, task_ids = [], []
                # since = time.time()
                for i in range(self.batch_size):
                    try:
                        d = self.data_queue.get(block=True, timeout=self.max_delay)

                        task_ids.append(d[0])
                        data.append(d[1])
                        self.logger.info('get one new task')
                    except Empty:
                        pass
                    # if time.time() - since >= self.max_delay:
                    #     break
                if len(data) == 0:
                    continue
                async for request in async_stream_yield(data, task_ids, random.randint(1000, 2000)):
                    print("before - go")
                    yield request

        try:
            async with grpcclient.InferenceServerClient(url="localhost:8001", verbose=False) as triton_client:
                response_iterator = triton_client.stream_infer(
                    inputs_iterator=async_request_iterator()
                )
                async for response in response_iterator:
                    result, error = response
                    print("result")
                    self.callback(result, error)
        except Exception as error:
            print(error)

    @classmethod
    def start(cls,
              data_queue: mp.Queue,
              result_queue: mp.Queue,
              batch_size: int = 8,
              max_delay: float = 0.1,
              ready_event: mp.Event = None
              ):
        w = cls(data_queue, result_queue, batch_size, max_delay, ready_event)
        asyncio.run(w.run())

```

I want to consume the data in the `data_queue`  to send requests to triton-server, and the triton-server logs are working fine, but I can't get the response in the client's `response_iterator` .

Version:
server_version  =  2.33.0
tritonclient = 2.33.0

**Comment by WackyGem** [comment]
> Hello,WackyGem, did you solve this problem, triton how did you achieve streaming output, tks!

Hello, @mistoFENG  , I make it works。 The key to streaming output is `Decoupled mode`, which you can set in this [use case file](https://github.com/triton-inference-server/fastertransformer_backend/blob/main/all_models/gpt/fastertransformer/config.pbtxt). 
```json
model_transaction_policy {
  decoupled: True
}
```
( If use FasterTranstransformer same as me)

**Comment by mistoFENG** [comment]
> > Hello,WackyGem, did you solve this problem, triton how did you achieve streaming output, tks!
> 
> Hello, @mistoFENG , I make it works. The key to streaming output is [`Decoupled mode`](https://github.com/triton-inference-server/fastertransformer_backend/blob/main/docs/gpt_guide.md#decoupled-mode), which you can set in this [use case file](https://github.com/triton-inference-server/fastertransformer_backend/blob/main/all_models/gpt/fastertransformer/config.pbtxt).
> 
> ```shell
> model_transaction_policy {
>   decoupled: True
> }
> ```
> 
> If you use [fastertransformer_backend](https://github.com/triton-inference-server/fastertransformer_backend/tree/main)

Thanks for your reply, I am now working on the streaming output of triton + fastertransformer, I put decoupled=True, But I run `python3 tools/issue_request.py tools/requests/sample_request_stream.json`  report an error:
``` Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "issue_request.py", line 110, in stream_consumer
    result = queue.get()
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 116, in get
    return _ForkingPickler.loads(res)
TypeError: __init__() missing 1 required positional argument: 'msg'
 ```
I would like to know how to use your above script, tks!

**Comment by mistoFENG** [comment]
> > Hello,WackyGem, did you solve this problem, triton how did you achieve streaming output, tks!
> 
> Hello, @mistoFENG , I make it works. The key to streaming output is [`Decoupled mode`](https://github.com/triton-inference-server/fastertransformer_backend/blob/main/docs/gpt_guide.md#decoupled-mode), which you can set in this [use case file](https://github.com/triton-inference-server/fastertransformer_backend/blob/main/all_models/gpt/fastertransformer/config.pbtxt).
> 
> ```shell
> model_transaction_policy {
>   decoupled: True
> }
> ```
> 
> If you use [fastertransformer_backend](https://github.com/triton-inference-server/fastertransformer_backend/tree/main)

Thanks for your reply, I am now working on the streaming output of triton + fastertransformer, Could you tell me how to use your above script, for example, what is the form of the input parameter? thks!

**Comment by WackyGem** [comment]
> > > Hello,WackyGem, did you solve this problem, triton how did you achieve streaming output, tks!
> > 
> > 
> > Hello, @mistoFENG , I make it works. The key to streaming output is [`Decoupled mode`](https://github.com/triton-inference-server/fastertransformer_backend/blob/main/docs/gpt_guide.md#decoupled-mode), which you can set in this [use case file](https://github.com/triton-inference-server/fastertransformer_backend/blob/main/all_models/gpt/fastertransformer/config.pbtxt).
> > ```shell
> > model_transaction_policy {
> >   decoupled: True
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If you use [fastertransformer_backend](https://github.com/triton-inference-server/fastertransformer_backend/tree/main)
> 
> Thanks for your reply, I am now working on the streaming output of triton + fastertransformer, Could you tell me how to use your above script, for example, what is the form of the input parameter? thks!

Hello, @mistoFENG, [This guide](https://github.com/triton-inference-server/fastertransformer_backend/blob/main/docs/gpt_guide.md) may contain all parameter you want. In my case , the `InferArgs` also like 
```python
@dataclass
class InferArgs:
    prompt: str
    output_len: int
    bad_word_list: list = field(default_factory=lambda: [""])
    stop_word_list: list = field(default_factory=lambda: [""])
    top_k: float = 40
    top_p: float = 0.7
    search_rate: float = 0.0
    temperature: float = 0.75
    len_penalty: int = 0.8
    repetition_penalty: float = 1.3
    random_seed: int = random.randint(0, 100)
```
I've pointed out  all the information I've referenced ，Good Luck！
