### ISSUE TITLE
version `GLIBCXX_3.4.30' not found (required by /opt/tritonserver/backends/python/triton_python_backend_stub

### ISSUE THREAD

**Issue by Lzhang-hub** [triton-inference-server/server#5933]
**Description**
When use custom-execution according:
https://github.com/triton-inference-server/python_backend#creating-custom-execution-environments
get the error:
![image](https://github.com/triton-inference-server/server/assets/57925599/ff63312d-2404-4655-b951-309fd8f3f073)

**Triton Information**
tritonserver in ngc container nvcr.io/nvidia/tritonserver:23.05-py3

**Comment by krishung5** [comment]
Hi @Lzhang-hub, I was wondering if the `triton_python_backend_stub` is compiled in the same Triton 23.05 container or if it's compiled in other OS/environment?

**Comment by Lzhang-hub** [comment]
> Hi @Lzhang-hub, I was wondering if the `triton_python_backend_stub` is compiled in the same Triton 23.05 container or if it's compiled in other OS/environment?

It is compiled in the host environment, which host is same as Triton 23.05 container use. I will try to package the conda environment inside the Triton container, Thanks for your reply.

**Comment by Lzhang-hub** [comment]
@krishung5  I have tried package the conda env in triton container，but get the same error

**Comment by krishung5** [comment]
Which conda version are you using? Could you also try to install `libstdcxx-ng=12`, something like `conda install -c conda-forge libstdcxx-ng=12 -y`?
@Tabrizian I believe we were seeing some similar issue before, and upgrading the conda version and installing  `libstdcxx-ng=12` resolved the issue. I was wondering if this is something we would need to document?

**Comment by Lzhang-hub** [comment]
@krishung5  Thank you very much, I upgraded conda version, and run `conda install -c conda-forge libstdcxx-ng=12 -y`. It can be work fine.

**Comment by oandreeva-nv** [comment]
@Lzhang-hub I am closing this issue, since it seems to be resolved. If you still have questions, feel free to tag me and I will re-open.

**Comment by dsgibbons** [comment]
I needed this fix too. It would be nice to see it documented formally somewhere.

**Comment by oandreeva-nv** [comment]
@krishung5 @Tabrizian do you think we can add a note on this issue in our docs?

**Comment by krishung5** [comment]
Updated the documentation: https://github.com/triton-inference-server/server/issues/5933

**Comment by simonrmonk** [comment]
This did not work for me. Tried with 23.05 and 23.06.

**Comment by Jackiexiao** [comment]
I think we should add to document

**Comment by shixianc** [comment]
This does not work for me. I'm on 23.10

**Comment by rmurray01** [comment]
@shixianc I just had this problem as well and found that I misunderstood the instructions above. Hopefully this solves your issue too.

I initially ran `conda install -c conda-forge libstdcxx-ng=12 -y` from my main OS environment, and then ran `conda create --name [name] python=3.10`, which resulted in getting the GLIBCXX_3.4.30 not found error when running Triton. I finally noticed during the environment create that it says, "The following NEW packages will be INSTALLED" and lists `libstdcxx-ng-11.2.0-h1234567_1`. So the environment setup is downgrading the libstdcxx version and undoing this suggested fix.

After creating the environment, I re-ran `conda install -c conda-forge libstdcxx-ng=12 -y` from within the new environment, and now `conda pack` is exporting the correct library files.

**Comment by shixianc** [comment]
> @shixianc I just had this problem as well and found that I misunderstood the instructions above. Hopefully this solves your issue too.
> 
> I initially ran `conda install -c conda-forge libstdcxx-ng=12 -y` from my main OS environment, and then ran `conda create --name [name] python=3.10`, which resulted in getting the GLIBCXX_3.4.30 not found error when running Triton. I finally noticed during the environment create that it says, "The following NEW packages will be INSTALLED" and lists `libstdcxx-ng-11.2.0-h1234567_1`. So the environment setup is downgrading the libstdcxx version and undoing this suggested fix.
> 
> I re-ran `conda install -c conda-forge libstdcxx-ng=12 -y` from within the new environment, and now `conda pack` is exporting the correct library files.

Thanks for the reply! I just figured out earlier, wish the documentation could add this detail too (for people does not have deep understanding of how conda works)
