### ISSUE TITLE
Questions about loading models

### ISSUE THREAD

**Issue by de1star** [triton-inference-server/server#5940]
Hi, triton team!
I found two things:    
Firstly, when using Model Repository Extension '/v2/repository/models/{model_name}/load' to load a model, triton server's readiness will be False (which was checked by using '/v2/health/ready').
Secondly, inference time of other models might dramatically increased during loading a model.   
Are these two things consistent with expectations?

**Comment by krishung5** [comment]
Hi @de1star,
The `server ready` health API indicates whether all the models are ready for inference. Therefore, it is expected to see the readiness status as false while loading a model. To check if the server is alive, you can use the `/v2/health/live`. For more information, please refer to the following link: https://github.com/kserve/kserve/blob/master/docs/predict-api/v2/required_api.md#health

For your second question, I was wondering if both models are utilizing the GPU. If the model loading process involves significant GPU operations, it could potentially interfere with the inference of another model, especially if they are both using the same GPU.

**Comment by Jack47** [comment]
@krishung5 thanks for quick reply, according to your reply, do you means we can use model level health api to determine whether current model is loaded and ready to serving incoming request?

**Comment by krishung5** [comment]
Yes, you can use `v2/models/${MODEL_NAME}[/versions/${MODEL_VERSION}]/ready` to get the readiness of specified model.
