### ISSUE TITLE
InferenceRequestNew cost time will slowly increase with the number of model reloads

### ISSUE THREAD

**Issue by echoonly** [triton-inference-server/server#5944]
**Description**
I am using Triton Inference Server for real-time inference services, implemented using C++ language and directly calling C-API functions from the core. The backend is TensorRT, and multiple models are concurrently accessed, with each model reloading a new version every few minutes.

Then I used a time profiling tool to measure the time consumed by various C-API functions and found that after the service is started, the time consumed by the `TRITONSERVER_InferenceRequestNew` function increases slowly with time. 

The average time was below 10us when just starting, but after one day, the time increased to 100us, and after one week, it rose to more than 2ms. If I suspend all model updates, then the time consumed for this function stops increasing and remains at the current level. If I suspend model updates at the beginning of the service, the time consumed by this function will remain below 10us. 

I have tested with both T4 and A10, they encountered the same issue.

**Triton Information**
The version of Triton used is 2.27.0, running in the 22.10 container.

**To Reproduce**
I think it’s unlikely that this issue is specific to a particular model. I have tested numerous models and as long as they are reloaded at a relatively high frequency, the problem can be replicated.

**Expected behavior**
The time cost by the TRITONSERVER_InferenceRequestNew function should not be affected by reloads.

**Comment by rmccorm4** [comment]
Hi @echoonly, we have made some recent changes and improvements to the model lifecycle / model repository manager code in the past few releases, one possibly related change would be the recent parallel model loading changes.

Can you try the latest release (23.05) and see if this issue is still observed?

CC @kthui

**Comment by echoonly** [comment]
Hi @rmccorm4 , thanks for your replay. 
I also noticed that the latest release note mentioned improvements in multi-model loading optimization. However, The container version 23.05 uses gcc 11.9 and glibc 2.35, which caused many compilation errors in my service code.

I would like to know if there is a way to build the latest Triton code in the 22.10 container, that is, if the latest Triton code can be compiled and run using gcc 9.4 and glibc 2.31 in the 22.10 container.

If possible, I will try the latest version to see if it still has this problem.

**Comment by echoonly** [comment]
hi，Is there any progress on this? Or any suggestions that can be tried?

**Comment by echoonly** [comment]
> 
It will not stop increasing. I have observed that it can increase up to around 5ms, and the P999 line goes beyond 50ms. At that point, I had to restart the service because it was impacting the overall performance. I suspect that if I didn’t restart, the latency would continue to increase. 

Another observation is that as the RequestNew latency increases, the infer latency decreases slightly. This includes the total time for invoking SetResponseCallback, ServerInferAsync, and completed.get(). I reached this conclusion because after restarting, the infer latency was longer compared to before the restart.

**Comment by rmccorm4** [comment]
@kthui do either the ModelMap or VersionMap grow unbounded if constantly adding new versions? I didn't see a place where items are removed from these maps on unload at a quick glance. Maybe these are growing and slowing down the [GetModel](https://github.com/triton-inference-server/core/blob/4215fdcd8173c4d2c8e4f079a1415149ba25d47f/src/model_lifecycle.cc#L329-L337) call (searching the maps) made when [creating a new request](https://github.com/triton-inference-server/core/blob/4215fdcd8173c4d2c8e4f079a1415149ba25d47f/src/tritonserver.cc#L1572)?

**Comment by rmccorm4** [comment]
@echoonly instead of constantly appending new versions to the model repository, is it feasible to instead update the same model version files in place? (re-use the same version for each update)

I believe Triton will internally handle the model update with "zero downtime", finishing any inflight requests on the current model and routing new requests to the updated model, even within the same version. Guan or Jacky may correct me if I'm wrong here.

If this works for you, then this should theoretically remove the slowdown over time, as the size of the model/version map should stay relatively the same rather than growing with each new version.

**Comment by echoonly** [comment]
@rmccorm4  Thank you for your analysis of the issue. The current observations seem to align with your analysis. 

If trtion supports updating the model using the same version number as you mentioned, I would be willing to try it out and provide feedback. However, I am unsure of the process to update the model with the same version number. 

Currently, the update process involves creating a directory with a version number +1 to store the new version, and then calling ServerLoadModel to load the new model. If the new model is placed within the directory of the old version number, the ServerLoadModel function does not trigger reload process. 

If there is a method to make it work, please let me know or provide documentation.  thx again.

**Comment by echoonly** [comment]
> I believe if you modify an existing model version and call ServerLoadModel on it, Triton should detect the changed file timestamps and initiate a reload. Let me know if you're seeing otherwise.

It works. Putting the new model in the old directory and call ServerLoadModel can  indeed trigger reload, and after running for several hours, the RequestNew function still takes less than 20us, which is about the same as when the service starts. Although the solution is a bit tricky, it does solve my problem, thank you very much.
