### ISSUE TITLE
need InferenceRequest  and InferenceResponse definitions to better test user codes

### ISSUE THREAD

**Issue by Jack47** [triton-inference-server/server#5947]
**Is your feature request related to a problem? Please describe.**
currently I'm working on adding ut and integration tests for my triton inference server using python backend. I can't find the definitions for InferenceRequest and InferenceResponse definitions,

**Describe the solution you'd like**

let people use this server side definitions

**Describe alternatives you've considered**

**Additional context**

**Comment by krishung5** [comment]
Hi @Jack47, you can refer to our [examples](https://github.com/triton-inference-server/python_backend/tree/main/examples) to see how to interact with both `InferenceRequest ` and `InferenceResponse`. If you're interested, you can learn more about these objects in [InferRequest.h](https://github.com/triton-inference-server/python_backend/blob/main/src/infer_request.h) and [InferResponse.h](https://github.com/triton-inference-server/python_backend/blob/main/src/infer_response.h).
