### ISSUE TITLE
boost::interprocess::lock_exception

### ISSUE THREAD

**Issue by zengqi0730** [triton-inference-server/server#5949]
**Description**
Using Python backend to test my python model file, but error occurs

**Triton Information**
both
nvcr.io/nvidia/tritonserver:23.02-py3
and
nvcr.io/nvidia/tritonserver:23.04-py3

Are you using the Triton container or did you build it yourself?
docker pull the image from NGC , i didn't build it by myself.
**To Reproduce**
OS: Ubuntu22.04
My model file: [https://drive.google.com/drive/folders/1puUq2-nFMWemYMbUAcbcIf1w3cXKCbBD?usp=drive_link](url)
![2023-06-14_16-32-41](https://github.com/triton-inference-server/server/assets/25789275/e98c51ec-c6cd-446c-bdab-8afdbb449618)

1. start container commond:
`docker run --gpus all --rm -it -v ${PWD}/model_test:/models --shm-size=1g --net host nvcr.io/nvidia/tritonserver:23.04-py3 bash`

2. start tritonserver:
`tritonserver --model-repository=/models`

3. send a single http request:
`python test_client.py`
I will get the expected value like:{"model_name":"test","model_version":"1","outputs":[{"name":"OUTPUT0","datatype":"FP32","shape":[1,3],"data":[0.30000001192092898,0.20000000298023225,0.5]}]}

4. Using multithreading to simulate stress testing
`python press.py`
I will get response like :('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')),or
HTTPConnectionPool(host='0.0.0.0', port=8000): Max retries exceeded with url: /v2/models/test/infer (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7dd2f46cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))

At the server terminal, Error message appears！
`terminate called after throwing an instance of 'boost::interprocess::lock_exception'
terminate called recursively
  what():  boost::interprocess::lock_exception
Signal (6) received.
Signal (6) received.
 0# 0x000055BE5479E959 in tritonserver
 1# 0x00007F35941BB090 in /usr/lib/x86_64-linux-gnu/libc.so.6
 2# gsignal in /usr/lib/x86_64-linux-gnu/libc.so.6
 3# abort in /usr/lib/x86_64-linux-gnu/libc.so.6
 4# 0x00007F3594574911 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 5# 0x00007F359458038C in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 6# 0x00007F359457F369 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 7# __gxx_personality_v0 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 8# 0x00007F359437ABEF in /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
 9# _Unwind_RaiseException in /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
10# __cxa_throw in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
11# 0x00007F35886696F1 in /opt/tritonserver/backends/python/libtriton_python.so
12# 0x00007F35886B7C55 in /opt/tritonserver/backends/python/libtriton_python.so
13# 0x00007F35886866B8 in /opt/tritonserver/backends/python/libtriton_python.so
14# 0x00007F358868ADB6 in /opt/tritonserver/backends/python/libtriton_python.so
15# 0x00007F35945ACDE4 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
16# 0x00007F35946C0609 in /usr/lib/x86_64-linux-gnu/libpthread.so.0
17# clone in /usr/lib/x86_64-linux-gnu/libc.so.6

Aborted (core dumped)
`

**Expected behavior**
I want to know how to solve the problem?

**Comment by krishung5** [comment]
Hi @zengqi0730, thanks for providing the steps to reproduce! I was able to reproduce the issue using 23.05 as well. Filed a ticket for the team to investigate. CC @Tabrizian

**Comment by krishung5** [comment]
Hi @zengqi0730, instead of reusing the output tensor and `InferenceResponse` object for every request in the model script, can you  try to create an output tensor and `InferenceResponse` for each request and see if the error still occurs?
Some like this:
```
def execute(self, requests):
        ...
        for i in range(request_num):
            out_tensor_0 = pb_utils.Tensor("OUTPUT0",
                                       out_0.astype(output0_dtype))
            inference_response = pb_utils.InferenceResponse(
                output_tensors=[out_tensor_0])
            responses.append(inference_response)

        return responses
```
In general usage, it is recommended to create the output tensor and `InferenceResponse` per request. It would be helpful if you could provide us with the specific use case or scenario where you intend to reuse these objects, so that we can better understand and prioritize any necessary enhancements.
