### ISSUE TITLE
The performance of the model is greatly affected by the request distribution

### ISSUE THREAD

**Issue by zhaohb** [triton-inference-server/server#5957]
Now I have a model where the received requests are not uniform, which can be understood as poisson distribution, tp99 is an important indicator in our scenario, but test found that the distribution of requests has a big impact on tp99, here is one of my tests:
```shell
./perf_analyzer -a -b 256 -u localhost:6602 -i gRPC -m model_trt --percentile 99 --stability-percentage 50 --request-rate-range 50:100:10
output：
Inferences/Second vs. Client p99 Batch Latency
Request Rate: 50, throughput: 12800 infer/sec, latency 10864 usec
Request Rate: 60, throughput: 15360 infer/sec, latency 10300 usec
Request Rate: 70, throughput: 17920 infer/sec, latency 8759 usec
Request Rate: 80, throughput: 20480 infer/sec, latency 7647 usec
Request Rate: 90, throughput: 23040 infer/sec, latency 7770 usec
Request Rate: 100, throughput: 25600 infer/sec, latency 6779 usec

./perf_analyzer -a -b 256 -u localhost:6602 -i gRPC -m model_trt --percentile 99 --stability-percentage 50  --request-distribution poisson --request-rate-range 50:100:10
output：
Inferences/Second vs. Client p99 Batch Latency
Request Rate: 50, throughput: 13824 infer/sec, latency 24276 usec
Request Rate: 60, throughput: 16537.6 infer/sec, latency 27982 usec
Request Rate: 70, throughput: 18380.8 infer/sec, latency 24621 usec
Request Rate: 80, throughput: 20121.6 infer/sec, latency 23875 usec
Request Rate: 90, throughput: 22937.6 infer/sec, latency 28090 usec
Request Rate: 100, throughput: 25651.2 infer/sec, latency 31787 usec
```
My model is a trt model. When the request rate is 100, the uniformly distributed tp99 is 6.8ms and the poisson distribution is 31.7ms, which is 4.6 times of the uniformly distributed one.I have to reduce the number of requests per node.

How to fix it？

**Comment by kthui** [comment]
Hi zhaohb, could you share the `config.pbtxt` of the model? It might provide some hints on the latency numbers.

**Comment by zhaohb** [comment]
@kthui  In the config.pbtxt file, I know we can use the delay parameter to control the time interval of request merging. I set max batch to 256 default , and the performance will be better when I set max batch to 1024:
```shell
Inferences/Second vs. Client p99 Batch Latency
Request Rate: 50, throughput: 13875.2 infer/sec, latency 24086 usec
Request Rate: 60, throughput: 16486.4 infer/sec, latency 22795 usec
Request Rate: 70, throughput: 18380.8 infer/sec, latency 17034 usec
Request Rate: 80, throughput: 20224 infer/sec, latency 17783 usec
Request Rate: 90, throughput: 22937.6 infer/sec, latency 19059 usec
Request Rate: 100, throughput: 25651.2 infer/sec, latency 21554 usec
```
tp99 dropped a lot,  which shows that merging requests can improve performance, but there is still a 3.1x performance difference.

**Comment by zhaohb** [comment]
I then modify the max_queue_delay_microseconds parameter,which was set to 100 by default,but now it is increased to 1000, max batch is still 1024, the test results are as follows:
```shell
Inferences/Second vs. Client p99 Batch Latency
Request Rate: 50, throughput: 13875.2 infer/sec, latency 16427 usec
Request Rate: 60, throughput: 16537.6 infer/sec, latency 16770 usec
Request Rate: 70, throughput: 18380.8 infer/sec, latency 16961 usec
Request Rate: 80, throughput: 20172.8 infer/sec, latency 18014 usec
Request Rate: 90, throughput: 22937.6 infer/sec, latency 21403 usec
Request Rate: 100, throughput: 25651.2 infer/sec, latency 21504 usec
```
It can be seen that increasing delay can improve the performance when the request rate is relatively small, but has no effect when the requets rate is large, which is in line with the expectation, and the overall performance is still far from that when the poisson is not added.

Is there a better way？

**Comment by zhaohb** [comment]
@kthui  this is my config file:
```pbtxt
name: "model_trt"
platform: "tensorrt_plan"
max_batch_size: 1024
input {
  name: "input1"
  data_type: TYPE_INT32
  dims: 1
}
...
input {
  name: "input70"
  data_type: TYPE_FP32
  dims: 1
  dims: 192
}
output {
  name: "output1"
  data_type: TYPE_FP32
  dims: 1
}
...
output {
  name: "output6"
  data_type: TYPE_FP32
  dims: 1
}
instance_group {
  count: 1
  kind: KIND_GPU
}
default_model_filename: "model_22.08.1024.plan"
dynamic_batching {
  preferred_batch_size: [256, 512]
  max_queue_delay_microseconds: 1000
}
optimization {
  cuda {
    busy_wait_events: true
    output_copy_stream: true
  }
}
```

**Comment by Tabrizian** [comment]
Hi @zhaohb, could you please share the latency breakdown that is returned by Perf Analyzer when the distribution is Poisson and constant?

**Comment by zhaohb** [comment]
The only difference is that the queue time for poisson becomes about 1-2 ms, which is still very short, so I don't think this will affect latency too much.

**Comment by Tabrizian** [comment]
I see that your model supports dynamic batching. One thing that might be happening here is that when you use Poisson distribution there might be fewer instances where dynamic batching can be leveraged due to the changes in the request arrival rate. Do you see the same difference in latency if you disable dynamic batching in your model?

cc @tgerdesnv @matthewkotila for viz

**Comment by zhaohb** [comment]
@Tabrizian Yes, I think so too. Dynamic batching can consolidate requests to reduce variations in request arrival rates.
We can only use dynamic batching on our business, so there is no case for testing static batching.
Poisson requests are more consistent with our business requests, so we want to minimize the impact of the poisson distribution on tp99 in a dynamic batching situation.
thank you very much.

**Comment by zhaohb** [comment]
hello everyone , any suggestions?

**Comment by dyastremsky** [comment]
Does this occur outside of Triton? If you are seeing the same behavior on the framework they are using, then it would be framework-related.

More likely, this has to do with optimizations Triton is making to make their model faster. However, there is only so much Triton can do. As far as I know, we do not have official guidance on requests following a Poisson distribution. Perf analyzer allows this option, so I'm assuming Model Analyzer does as well. You can use [Model Analyzer](https://github.com/triton-inference-server/model_analyzer) to model your situation and sweep through possible configurations (e.g. different batch sizes) to see expected latency.

If the above fails to accomplish the expected latency, the hardware capabilities may be insufficient for your expected performance. Run fewer models on the hardware or try running the model with more/better GPUs (assuming you're running GPUs).

From @Tabrizian:

```
Adding to what David mentioned, you could also take a look at the inference request trace to access the latency breakdown of each inference request:
https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/user_guide/trace.html

Another issue that might be happening here is that sometimes the GPU/CPU p-state can greatly affect the latency of the requests. Is it possible to try pinning the GPU/CPU clocks and repeat these experiments to see whether they still observe any gaps between the two experiments?```

**Comment by zhaohb** [comment]
@dyastremsky  Thank you for your reply. 
I wonder if triton can do some optimization for poisson distribution requests.
Now all optimization methods are aimed at uniform requests, but most of the requests are poisson distribution in actual use, so I think triton can do some targeted optimization.
Even though I found the best configuration using model analyzer,  I think the poisson distribution still degrades performance in this case.

thank you very much.

**Comment by dyastremsky** [comment]
Any time. Happy Model Analyzer helped you find the best configuration!

If you have any optimizations you would recommend for Poisson distributions, please let us know. This is also an open-source project, so feel free to contribute. Thanks!
