### ISSUE TITLE
[Question] How does Triton run ensemble models ? 

### ISSUE THREAD

**Issue by MatthieuTPHR** [triton-inference-server/server#5970]
Let's say I have two requests in the queue of an ensemble model comprised of 3 models A,B,C that are executed sequentially A->B->C. 

Does Triton wait for the first request to exit from C to start processing the second request with A or does it only wait for the first request to exit A to start processing the second request with A ? 

First case: 
```
Req 1 : A
Req 1 : B
Req 1 : C
Req 2: A
Req 2 : B
Req 2 : C
```
Second case: 
```
Req 1: A
Req 1: B
Req 2: A
Req 1: C
Req 2: B
Req 2: C
```

I would assume the second case can be more efficient in certain cases, for instance if A is image decoding and C is image encoding and B is an image -> image model (e.g. segmentation)

**Comment by david-macleod** [comment]
The second case is correct, it execute Req 1 for model A as soon as  Req 1 is complete, potentially executing in parallel with Req 1 for model B
