### ISSUE TITLE
how to set the ensemble_scheduling when do  inference of difference outputs

### ISSUE THREAD

**Issue by diandianliu** [triton-inference-server/server#5996]
I have three models: a face detection model, a post-processing backend for detection, and a face feature extraction model. In the scenario where the post-processing backend detects multiple faces,each face as a  face feature extraction  input. How to configure an ensemble model to pass multiple post-processing outputs as inputs to the face feature extraction.

**Comment by oandreeva-nv** [comment]
@diandianliu Thank you for your question. One way to do that, is if your post-processing model produces multiple outputs, each representing a face, you can specify them as inputs to your face feature extraction model in the `config.pbtxt` file.
Something like:
```
ensemble_scheduling {
  step [
    {
      model_name: "face_detection_model"
      model_version: -1
      input_map {...}
      output_map {... }
    },
    {
      model_name: " post_processing"
      model_version: -1
      input_map {
        key: "input_0"
        value: "some_value"
      }
      output_map {
        key: "IMAGE_1"
        value: "image_1"
      },
      output_map {
        key: "IMAGE_2"
        value: "image_2"
      }
    },
    {
      model_name: " face feature extraction"
      model_version: -1
      input_map {
        key: "IMAGE_1"
        value: "image_1"
      }
      input_map {
        key: "IMAGE_2"
        value: "image_2"
      }
      output_map {...}
    }
]
}
```
More on Ensemble models can be found [here](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/architecture.md#ensemble-models) and [this guide](https://github.com/triton-inference-server/tutorials/tree/main/Conceptual_Guide/Part_5-Model_Ensembles) explores the concept of ensembles with a running example.

If your  " post_processing" model does not provide multiple outputs, you can explore [BLS approach](https://github.com/triton-inference-server/python_backend#business-logic-scripting)

**Comment by diandianliu** [comment]
@oandreeva-nv Thank for your answer, I still have some question, The  face number of post_processing  model outputs is not fixed and  face feature extraction  model only have one input(only input one face at a time if batch is one). Should I combine multiple face into one batch as  face feature extraction input?

**Comment by oandreeva-nv** [comment]
> The face number of post_processing model outputs is not fixed
I am not sure I fully understand. Does your model have a random number of outputs?

Unfortunately, I am not aware of the requirements of your system and final goal, so I am not in the position to provide recommendations for the implementation.

**Comment by diandianliu** [comment]
My system is  client send a preprocess's image to  ensemble model ,expect get all faces' featrue  in the image.

if the image only have one face, face_detect_post will get one face, it can successful work, but if the image have more than one face, how to send multi faces form face_detect_post to face_feature?(face_feature model input one face  once if batch equal 1)


config.pbtxt:  
platform:"ensemble"
max_batch_size : 0
input [
    {
        name: "ENSEMBLE_INPUT0"
        data_type: TYPE_UINT8 
        dims: [-1]
       
    }
]
output [
    {
        name: "ENSEMBLE_OUTPUT0"
        data_type: TYPE_STRING
        dims: [ -1 ]
    }
]
ensemble_scheduling {
  step [
    {
      model_name: "face_detect"
      model_version: 1
      input_map: {
        key: "INPUT0"
        value: "ENSEMBLE_INPUT0"
      }
      output_map: {
        key: "OUTPUT0"
        value: "face_detect_post_input0"
      }
    },
    {
      model_name: "face_detect_post"
      model_version: 1
      input_map: {
        key: "INPUT0"
        value: "face_detect_post_input0"
      }
      output_map: {
        key: "OUTPUT0"
        value: "feature_input0"
      }
    },
    {
      model_name: "face_feature"
      model_version: 1
      input_map: {
        key: "INPUT0"
        value: "feature_input0"
      }
      output_map: {
        key: "OUTPUT0"
        value: "ENSEMBLE_OUTPUT0"
      }
    }
  ]
}

**Comment by oandreeva-nv** [comment]
I believe [BLS approach](https://github.com/triton-inference-server/python_backend#business-logic-scripting) would be more suitable for this case than ensemble. You can implement custom logic - in your case post-process output of `face_detect_post`, e.g. split this output into multiple inputs for the next model.

**Comment by diandianliu** [comment]
Thanks
