### ISSUE TITLE
 UNAVAILABLE: Internal: failed to load model 'yolov5': PytorchStreamReader failed locating file constants.pkl: file not found 

### ISSUE THREAD

**Issue by xyh15864643181** [triton-inference-server/server#5997]
![image](https://github.com/triton-inference-server/server/assets/62532042/f8e23aa3-d804-4165-87bb-9f9f4a5567be)

![image](https://github.com/triton-inference-server/server/assets/62532042/29f120c2-8d5a-42b9-bfd6-170673e36862)

I uploaded the model in triton format as .pt and there was an error!

May I ask the big guy who has encountered this problem, trouble to solve it?

**Comment by oandreeva-nv** [comment]
Hi @xyh15864643181 , sorry to see that you are running into this issue. Could you please verify that your model works outside of triton? Based on the logs you've provided, it seems like the model expects `constants.pkl` file, but wasn't able to find it. Similar issues were discussed [here](https://stackoverflow.com/questions/67644548/cannot-export-yolov5-model-using-export),  [here](https://discuss.pytorch.org/t/pytorchstreamreader-failed-locating-file-constants-pkl-file-not-found/169884) and [here](https://github.com/zhiqwang/yolov5-rt-stack/issues/142)

**Comment by xyh15864643181** [comment]
I would like to ask, do you mean the content shown in the figure below by "constant"?
![image](https://github.com/triton-inference-server/server/assets/62532042/133e0792-d95a-4622-8360-9e4031fe0d97)


根据提供的链接，执行文章内的代码
“python /workspace/yolov5-master/export.py --weights /workspace/yolov5-master/runs/train/exp2/weights/best.pt --img 640 --batch 1”
得到的模型文件为best.torchscript，triton没有此格式的文件呀，正常的后缀名应该是.pt，请问triton上传pytorch的权重模型，即以后缀名为.pt的模型，如何上传到triton仓库中，有案例文档吗？
![image](https://github.com/triton-inference-server/server/assets/62532042/63816076-9bbb-4a05-b58c-e6a328fa12c5)

**Comment by xyh15864643181** [comment]
> Hi @xyh15864643181 , sorry to see that you are running into this issue. Could you please verify that your model works outside of triton? Based on the logs you've provided, it seems like the model expects `constants.pkl` file, but wasn't able to find it. Similar issues were discussed [here](https://stackoverflow.com/questions/67644548/cannot-export-yolov5-model-using-export), [here](https://discuss.pytorch.org/t/pytorchstreamreader-failed-locating-file-constants-pkl-file-not-found/169884) and [here](https://github.com/zhiqwang/yolov5-rt-stack/issues/142)

Please take a look at the reply above

**Comment by xyh15864643181** [comment]
[oandreeva-nv](https://github.com/oandreeva-nv) Please take a look at the reply above

**Comment by xyh15864643181** [comment]
HI @oandreeva-nv Please take a look at the reply above

**Comment by xyh15864643181** [comment]
@oandreeva-nv  This model was generated during yolov5 training. I also took into account whether the model was damaged. After testing, it was found that the model had no problems, and reasoning could be realized under yolov5

**Comment by xyh15864643181** [comment]
@oandreeva-nv  Is there any problem between the above errors and the CUDA version number? The CUDA version number in the container of the yolov5 training model is 11.1, the CUDA version number in the triton-server container is 11.6, and the pytorch in both containers is 1.8.1+cu111. And I found something online that supports compatibility
![image](https://github.com/triton-inference-server/server/assets/62532042/7672c857-6dcd-41d9-a895-1ffd563745ad)

**Comment by oandreeva-nv** [comment]
Did you follow steps listed here: https://pytorch.org/tutorials/advanced/cpp_export.html#converting-to-torch-script-via-tracing
after your model was fully trained?

**Comment by Tabrizian** [comment]
Closing, due to in-activity.
