### ISSUE TITLE
How can i identify the model instances in the instance group ?

### ISSUE THREAD

**Issue by eunbin079** [triton-inference-server/server#6008]
Hello, I'm a developer who wants use Triton Inference Server. 

## Background
In our project, there is a restriction that we should create as many clients as the number of model instances, and that model instances and clients **should make a 1:1 TCP connection**.
**we use gRPC communication, the request needs to be well distributed(1:1) to the model instance only once in the beginning**

![Triton Inference Server](https://github.com/triton-inference-server/server/assets/50285785/fdd86db0-16cd-4e4d-bf33-bbadffa4b295)

in logical aspect,
![instance group](https://github.com/triton-inference-server/server/assets/50285785/478a83fe-1fe1-4433-a7cb-fb189a2eedcc)

To solve this restriction, I would like to check some Triton function.

### 1. When client request inference, specify the Model Instance uuid(or name ?)
- The client somehow knows the uuid or name of the Model Instance and pass uuid when requesting inference.
- In other words, I wonder if **Triton is providing the client API as below**
```
import tritonclient.http as httpclient


 # set Triton Inference Server
triton_server_url = "http://localhost:8000"
triton_client = httpclient.InferenceServerClient(url=triton_server_url)
 

# Set the name of the model instance group to call
model_group_name = "my_model_group"

# Set the name of the model instance to call
model_instance_name = "my_model_instance"

 
# Reasoning Request Data Settings
input_data = {

    "input": [...]

}


# Send Inference Request
response = triton_client.infer(model_instance_name, model_instance_group=model_group_name, input_data=input_data)
```

### 2. Modify the Triton Scheduling logic.

- When Triton receives a request and decides which instance to hand over the request to, it assigns a model instance that does not process the request
- In the figure below, when a new client comes in, it should be assigned to model instance number 3.
![instance group](https://github.com/triton-inference-server/server/assets/50285785/f14c6c41-fc97-4dbc-946c-fc972449cae4)

- **I wonder what scheduling algorithms are available and if there is a way to customize them (I cannot find some document ..).**
- For your information, we are a stateful model, so we need to have a Sequence Batter inside.

### 3. Distribute the same 4 models with 4 different model names
- Instead of deploying four identical models with instance_group.count = 4, it is simply a way to create four models with different names.
- I think it's the simplest way to identify the model. If this happens, I wonder if you have any concerns.

---

Thank you for reading the long issue. 
If you have any questions or opinions, please feel free to comment.
Waiting your comment.
Thank you.

**Comment by oandreeva-nv** [comment]
1. Currently, there is no support for this, model name and its version is the only fields that the client may use to direct the request destination.

2.  is the opposite of the batching assumption that we hold when designing the scheduler: the model execution is usually the major contributor of the latency, to provide better throughput, we fill the batch slots of individual instances first to make sure an instance is fully utilization for each execution. In the case you describe, it can be the case that each instance is handling only one sequence and cause longer queue time for pending sequences. However, if each of your client only sends one sequence at a time, then you can limit your instances to have only 1 batch slot (set max_batch_size: 1), then this "round robin" behavior will be enforced

3. It is the easiest as everything is in-place. Only thing to note is that the assignment will be done outside Triton, either the client or intermediate service needs to provide the name (and/or version) of the model "assigned" to the specific client.

Thanks to @GuanLuo for this response.

**Comment by Tabrizian** [comment]
Closing, feel free to open a new GitHub issue if you have additional questions.
