### ISSUE TITLE
[QST] when/where to exactly load the pytorch mode?

### ISSUE THREAD

**Issue by wbo4958** [triton-inference-server/server#6029]
Hello experts,

Recently, I am reading triton-inference-server code, but I really can't find where/when to exactly load the model. 

For example, I have a pytorch model under model-repository/resnet18/1/model.pt and corresponding config.pbtxt, the command `tritonserver --model-repository=model-repository --backend-directory=xx` can deploy the model.

I would like to know when pytorch loads the resnet18/1/model.pt into the CPU memory? I searched pytorch backends but I can't find anything. Would you be able to help me find out where the source code is? Thx in advance.

**Comment by nnshah1** [comment]
Please take a look at the LoadModel method:

https://github.com/triton-inference-server/pytorch_backend/blob/f3d03d975efa7e2360fc51f0a8e77fa89c888d61/src/libtorch.cc#L251

[pytorch_backend/src/libtorch.cc at f3d03d975efa7e2360fc51f0a8e77fa89c888d61 · triton-inference-server/pytorch_backend](https://github.com/triton-inference-server/pytorch_backend/blob/f3d03d975efa7e2360fc51f0a8e77fa89c888d61/src/libtorch.cc#L262)

**Comment by wbo4958** [comment]
amazing, that's what I'm looking for. Thx for your help.
