### ISSUE TITLE
How to convert an image into the input required by the model in Java

### ISSUE THREAD

**Issue by faquir-sun** [triton-inference-server/server#6036]
the input sent to the model is an image. How can I convert the image to uint8 format required by the model and get the actual shape information of the image, I saw that the similar operation in the demo is:

InferTensorContents.Builder input0_data = InferTensorContents.newBuilder();
input0_data.addAllUintContents(Iterable<? extends Integer> values)

**Comment by nnshah1** [comment]
In order to load and convert a jpeg image into an RGB tensor you'll need to use the JAVA image APIs from:

```
javax.imageio.ImageIO
```
