### ISSUE TITLE
CPU & GPU metrics are not present in Grafana dashboard.json

### ISSUE THREAD

**Issue by yeahdongcn** [triton-inference-server/server#6047]
**Is your feature request related to a problem? Please describe.**
I'm using `deploy/k8s-onprem` to deploy Triton on K8s and importing `dashboard.json` to Grafana to view the metrics. According to [docs](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/), there are some extra metrics been collected for CPU & GPU, but they are not present in the dashboard. So I consider this issue as a feature request. I would like to see these metrics visually in Grafana.

**Describe the solution you'd like**
Extend the `dashboard.json` to have more widgets.

**Describe alternatives you've considered**
If these metrics are not suitable to be added to the dashboard, please provide a best practice in viewing these data.

**Additional context**
- I also searched around and didn't find any other `dashboard.json` that contains `nv_cpu_utilization` or  `nv_gpu_utilization`.
- `dashboard.json` in other deployment methods also doesn't have CPU & GPU widgets.

**Comment by Tabrizian** [comment]
@yeahdongcn Would you be interested in contributing this feature?

cc @nealvaidya who originally added `k8s-onprem` example.

**Comment by yeahdongcn** [comment]
<img width="1239" alt="Screenshot 2023-07-25 at 14 25 18" src="https://github.com/triton-inference-server/server/assets/2831050/b915c139-89be-4fbb-84ed-f9c90a09481d">
@Tabrizian I've added more panels for displaying CPU & GPU metrics. Could you please take a look before I send out PR? Thanks.
