### ISSUE TITLE
Delay in grpc communication stage

### ISSUE THREAD

**Issue by sarperkilic** [triton-inference-server/server#6050]
Hi,

I am using triton inference server to deploy my onnx model and at the same device I am using gRPC client to send inference request.

I wonder how can I calculate delay during the transferring data from CPU to GPU memory.

I am using curl localhost:8002/metrics but I wonder is there anything else I can calculate this delay?

I just want to see how much delay I have during using gRPC to send inference request to the server.

Thanks

**Comment by Tabrizian** [comment]
Hi @sarperkilic, you can use `metrics` endpoint to the accumulated statistics. You can also use tracing to get per request tracing information: https://github.com/triton-inference-server/server/blob/main/docs/user_guide/trace.md
