### ISSUE TITLE
pb_utils InferenceRequest not working

### ISSUE THREAD

**Issue by amey-matroid** [triton-inference-server/server#6058]
**Description**
`pb_utils` seems to throw an error on using `InferenceRequest` when I upgrade triton version to `23.04` from `22.04`

```
"load failed for model 'my_model': version 1 is at UNAVAILABLE state: Internal: AttributeError: module 'triton_python_backend_utils' has no attribute 'InferenceRequest'
```

**Triton Information**
What version of Triton are you using?
`23.04`

Are you using the Triton container or did you build it yourself?
I built it myself

**To Reproduce**
```
import triton_python_backend_utils as pb_utils

infer_request = pb_utils.InferenceRequest(
        model_name=model_name,
        requested_output_names=[output_tensor_name],
        inputs=inputs,
    )
```

**Expected behavior**
I expect it to not throw an error as it did earlier

**Comment by Tabrizian** [comment]
Yes, there were some changes between 22.04 and 23.04 that caused most of the `pb_utils` object to be only available after the `initialize` has been called. So, if you try to use `pb_utils.InferenceRequest` before initialize you're going to run into this issue.

We have a ticket to fix that but it has not been prioritized yet.

**Comment by amey-matroid** [comment]
I see, thanks for the update. For now, I have removed `pb_utils.InferenceRequest` from the function signature and that suppresses the issue. I am able to use it in the `execute` function which suffices for now.
