### ISSUE TITLE
Does ensemble involve GPU->CPU->GPU data movement?

### ISSUE THREAD

**Issue by flexwang** [triton-inference-server/server#6060]
Let's say if we have two models on GPU and make it a DAG using ensemble. Will the output of the first model be moved to CPU first and then to GPU for the second model to consume, or is it a direct GPU-to-GPU data movement?

**Comment by Tabrizian** [comment]
If both the models are operating on GPU and are able to work with GPU inputs, there wouldn't be any CPU data movements.

**Comment by flexwang** [comment]
@Tabrizian thanks. 

What if part of the ensemble is a python backend? Then there has to be CPU data movement because at least you have to do something like `pb_utils.get_input_tensor_by_name(request, "hidden_state")`

**Comment by OminousBlackCat** [comment]
I'm also curious about when we allocate a python model to GPU(which means the `instance_group['kind'] = KIND_GPU` ), how the python code running at GPU?  Is there are some GPU->CPU->GPU data movement?

**Comment by Tabrizian** [comment]
@flexwang Sorry for the delayed response, if the Python model has `parameters: { key: "FORCE_CPU_ONLY_INPUT_TENSORS" value: {string_value:"no"}}`, the input tensors won't be moved to CPU.

@OminousBlackCat Python backend behaviour doesn't change based on the `kind` value. It is up to your model to move it to the appropriate GPU. There is an example for how this can be achieved here: https://github.com/triton-inference-server/python_backend/tree/main/examples/instance_kind
