### ISSUE TITLE
change the setRetryCnt to >= 0 in InferenceServerClient.java

### ISSUE THREAD

**Issue by rohitrahul-wynk** [triton-inference-server/server#6066]
**Description**
This issue is related to the triton server client library. Currently the setRetryCnt function expects the retryCnt to be > 0. It should rather be set to >=0. As In some of the scenarios, we do not want to retry the request in case it fails.

[  public void setRetryCnt(int retryCnt)](https://github.com/triton-inference-server/client/blob/b6f35bb8ea642dc604e06ab52099967569995f76/src/java/src/main/java/triton/client/InferenceServerClient.java#L245C15-L245C26)

**Issue**
When we set the retryCnt > 0, the client keeps retrying requests. The requests generally fail in peak traffic hours, when this happens client starts sending more requests to the server, essentially doubling / tripling the load, which causes service outage in peak hours.

**Comment by Tabrizian** [comment]
cc @jbkyang-nvi
