### ISSUE TITLE
How to implement self.client.load_model(self.model_name) and self.client.unload_model(self.model_name) in Java?

### ISSUE THREAD

**Issue by michaelwechner** [triton-inference-server/server#6069]
I have the triton client running successfully, but I was told, that in Python one can load and unload the model:

self.client.load_model(self.model_name)
self.client.unload_model(self.model_name)

Is this also possible in Java? If so, how?

Thanks

Michael

**Comment by Tabrizian** [comment]
In the Java HTTP client, it looks like it is not currently possible to load/unload models: https://github.com/triton-inference-server/client/tree/main/src/java

However, for gRPC you should be able to load/unload models.

There is an example for java gRPC client here: https://github.com/triton-inference-server/client/blob/main/src/grpc_generated/java/examples/src/main/java/clients/SimpleJavaClient.java

**Comment by michaelwechner** [comment]
Thanks for your feedback!
