### ISSUE TITLE
The triton inference process time is too slow when deployed across nodes

### ISSUE THREAD

**Issue by xyh15864643181** [triton-inference-server/server#6093]
When triton's server and client containers are deployed on the same host, the time from client to inference request is about 1 second!
66/5000
However, when triton's server and client containers are deployed on two different servers, the time from the inference request to the inference request is about 15 seconds!
If you can ping the ip address, there is no network delay, except that the client sends a request to use the ip+ port mapped from the server container to the host. How can I configure and modify the ip+ port? Can you give me a solution to the problem? Thank you

**Comment by jbkyang-nvi** [comment]
Maybe @kthui ?

**Comment by kthui** [comment]
Hi @xyh15864643181, if you start the Triton server with `tritonserver --help`, it will print a list of options that contain the flags to modify the default IP address and port. For example: 
```
  --http-address <string>
        The address for the http server to bind to. Default is
        0.0.0.0
  --http-port <integer>
        The port for the server to listen on for HTTP requests.
        Default is 8000.
```
