### ISSUE TITLE
tritonclient protobuf version

### ISSUE THREAD

**Issue by weidezhang** [triton-inference-server/server#6095]
**Is your feature request related to a problem? Please describe.**

currently tritonclient has lower version of protobuf ==3.20.x which is incompatible with latest version grpcio-tools (protobuf >=4.21.x)

**Describe the solution you'd like**

please upgrade protobuf version 

**Describe alternatives you've considered**

n/a

**Additional context**

**Comment by jbkyang-nvi** [comment]
Thanks for your request. I have filed a ticket

**Comment by jbkyang-nvi** [comment]
fixed with ^
