### ISSUE TITLE
how to deploy stable diffusion webui  for many submodel?

### ISSUE THREAD

**Issue by foocker** [triton-inference-server/server#6111]
such as lora , dreambooth form peft,  controlnet which has many sub model, such as depth, canny...。
how to deploy all these models in a triton server, maybe four 3090ti in one server.  maybe 8 3090ti in k8s.
[sd-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui)

maybe one project can do a good teaching example(which contains many feature from trironserver)

**Comment by jbkyang-nvi** [comment]
Hi @foocker maybe you can find this video helpful for deploying stable diffusion on Triton: https://www.youtube.com/watch?v=JgP2WgNIq_w

**Comment by foocker** [comment]
> Hi @foocker maybe you can find this helpful for deploying stable diffusion on Triton: [blog](https://medium.com/nvidia-ai/how-to-deploy-almost-any-hugging-face-model-on-nvidia-triton-inference-server-with-an-8ee7ec0e6fc4) [youtube](https://www.youtube.com/watch?v=JgP2WgNIq_w)

the blog need upgrad. i have deploy the sd on triton. but it's not webui, which contain lora, face, resolution, and so on, many many sub model. it's best with ui, the inference is on triton. can concurrence,, high performence. trt8.6.1(vae, unet, decoder) i have done, but in triton, i have failed.

**Comment by jbkyang-nvi** [comment]
What is your specific problem with Triton you're facing?

**Comment by jbkyang-nvi** [comment]
For these specific applications, Triton does not provide a README or a specific example. If you have a more specific question with what you have tried, and what doesn't work we might be able to help you

**Comment by foocker** [comment]
> For these specific applications, Triton does not provide a README or a specific example. If you have a more specific question with what you have tried, and what doesn't work we might be able to help you

i  need read the all sub doc  and do it by myself. i have specific question.but it's better read the all sub docs. maybe after that it will not  be a question. so, for saving time, i asked the question, a complex example, which contain many content of the docs, if that, i only read the examlple. i mean, it can save time.  any way, thx.

**Comment by foocker** [comment]
hi, i mean this: [Stable-Diffusion-WebUI-TensorRT](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT)
