### ISSUE TITLE
There is a core dumped when I use  Shared memory in Multi threads

### ISSUE THREAD

**Issue by busishengui** [triton-inference-server/server#6114]
**Description**
There is a Triton server core dumped when I use  Shared memory in Multi threads
**Triton Information**
What version of Triton are you using?
21.12
Are you using the Triton container or did you build it yourself?
build it myself
**To Reproduce**
Steps to reproduce the behavior.

`std::string encoder_input_shm_key = "/encoder_input" + std::to_string(thread_idx_);
    int encoder_shm_fd_ip = thread_idx_* 100 +2;
    void* encoder_input_shm;
    size_t encoder_input_byte_size = feats.size() * sizeof(float) + 2 * sizeof(int64_t);
    tc::CreateSharedMemoryRegion(encoder_input_shm_key, encoder_input_byte_size, &encoder_shm_fd_ip);
    tc::MapSharedMemory(
          encoder_shm_fd_ip, 0, encoder_input_byte_size, (void**)&encoder_input_shm);

    tc::CloseSharedMemory(encoder_shm_fd_ip);
    // Timer asa;
    memcpy(encoder_input_shm, feats.data(), feats.size() * sizeof(float));
    memcpy(encoder_input_shm + feats.size() * sizeof(float), &chunk_lens_, sizeof(int64_t));
    memcpy(encoder_input_shm + feats.size() * sizeof(float) + sizeof(int64_t), &required_cache_size, sizeof(int64_t));
    // LOG(INFO) << "memcpy cost time is " << asa.Elapsed();
    std::string shm_input_name = "encoder_input" + std::to_string(thread_idx_);
    client->RegisterSystemSharedMemory(
          shm_input_name, encoder_input_shm_key, encoder_input_byte_size);
    encoder_input_ptr->SetSharedMemory(shm_input_name,  feats.size() * sizeof(float), 0);
    chunk_lens_ptr->SetSharedMemory(shm_input_name, sizeof(int64_t), feats.size() * sizeof(float));
    required_cache_size_ptr->SetSharedMemory(shm_input_name, sizeof(int64_t), feats.size() * sizeof(float) + sizeof(int64_t));

    std::vector<tc::InferInput*> encoder_input_list = {encoder_input_ptr.get(),
                                                       chunk_lens_ptr.get(),
                                                       required_cache_size_ptr.get()};
    tc::InferRequestedOutput* encoder_output;
    tc::InferRequestedOutput::Create(&encoder_output, "output");
    std::shared_ptr<tc::InferRequestedOutput> encoder_output_ptr;
    encoder_output_ptr.reset(encoder_output);
    std::string encoder_output_shm_key = "/encoder_output" + std::to_string(thread_idx_);
    int encoder_shm_fd_op = thread_idx_* 100 +100;
    float* encoder_output_shm;
    size_t encoder_output_byte_size = sizeof(float) * chunk_size * attention_dim_;
    tc::CreateSharedMemoryRegion(encoder_output_shm_key, encoder_output_byte_size, &encoder_shm_fd_op);
    tc::MapSharedMemory(
          encoder_shm_fd_op, 0, encoder_output_byte_size, (void**)&encoder_output_shm);
    tc::CloseSharedMemory(encoder_shm_fd_op);
    std::string shm_output_name = "encoder_output" + std::to_string(thread_idx_);
    client->RegisterSystemSharedMemory(shm_output_name, encoder_output_shm_key, encoder_output_byte_size);
    encoder_output_ptr->SetSharedMemory(
          shm_output_name, encoder_output_byte_size, 0 /* offset */);
    std::vector<const tc::InferRequestedOutput*> encoder_outputs = {encoder_output_ptr.get()};
    tc::InferResult* encoder_results;
    tc::InferOptions encoder_options("encoder_model");
    encoder_options.sequence_id_ = thread_idx_ + 10086;
    encoder_options.sequence_start_ = !start_ ? true : false;
    // LOG(INFO)<< "encoder_options.sequence_id_: "<<encoder_options.sequence_id_;
    // LOG(INFO)<< "sequence_start_: "<<encoder_options.sequence_start_;
    encoder_options.sequence_end_ = state == DecodeState::kEndFeats ? true : false;
    encoder_options.request_id_ = std::to_string(thread_idx_);
    // encoder_options.sequence_end_ = false;
    // LOG(INFO)<< "state: "<<state;
    if (encoder_options.sequence_start_ == true)
    {
        LOG(INFO) << "it is a sequence_id_: "<< encoder_options.sequence_id_<<" start";
    }
    if (encoder_options.sequence_end_ == true)
    {
        LOG(INFO) << "it is a sequence_id_: "<< encoder_options.sequence_id_<<" end";
    }
    // LOG(INFO)<< "encoder_options.sequence_end_ : "<<encoder_options.sequence_end_ ;
    client->Infer(
        &encoder_results, encoder_options, encoder_input_list, encoder_outputs, http_headers, tc::Parameters(),
        request_compression_algorithm, response_compression_algorithm);`
**Expected behavior**
 0# nvidia::inferenceserver::(anonymous namespace)::ErrorSignalHandler(int) at signal.cc:?
 1# 0x00007F42A0F88280 in /lib64/libc.so.6
 2# 0x00007F42A10AD2E0 in /lib64/libc.so.6
 3# 0x00007F4296E89FBF in /lib64/libcuda.so.1
 4# 0x00007F4296D0E130 in /lib64/libcuda.so.1
 5# 0x00007F4296D0D9B3 in /lib64/libcuda.so.1
 6# 0x00007F4296C0DFA2 in /lib64/libcuda.so.1
 7# 0x00007F4296C0FAFF in /lib64/libcuda.so.1
 8# cuMemcpyHtoDAsync_v2 in /lib64/libcuda.so.1
 9# 0x00007F42957932F9 in /usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudart.so.11.0
10# 0x00007F42957689DD in /usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudart.so.11.0
11# cudaMemcpyAsync in /usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudart.so.11.0
12# 0x00007F41B46021CF in /data/nfs_rt26/kailong/GPU_test/server/lib/libonnxruntime_providers_cuda.so
13# 0x00007F42960B1470 in /data/nfs_rt26/kailong/GPU_test/server/lib/libonnxruntime.so.1.8.1
14# 0x00007F42960B1E04 in /data/nfs_rt26/kailong/GPU_test/server/lib/libonnxruntime.so.1.8.1
15# 0x00007F429612CDF3 in /data/nfs_rt26/kailong/GPU_test/server/lib/libonnxruntime.so.1.8.1
16# 0x00007F429612D5C6 in /data/nfs_rt26/kailong/GPU_test/server/lib/libonnxruntime.so.1.8.1
17# 0x00007F4295B22E1E in /data/nfs_rt26/kailong/GPU_test/server/lib/libonnxruntime.so.1.8.1
18# 0x00007F4295B0979C in /data/nfs_rt26/kailong/GPU_test/server/lib/libonnxruntime.so.1.8.1
19# 0x00007F42967F16EA in /data/nfs_rt26/kailong/GPU_test/server/onnx_build/onnxruntime/build/install/backends/onnxruntime/libtriton_onnxruntime.so
20# 0x00007F42967F513A in /data/nfs_rt26/kailong/GPU_test/server/onnx_build/onnxruntime/build/install/backends/onnxruntime/libtriton_onnxruntime.so
21# TRITONBACKEND_ModelInstanceExecute in /data/nfs_rt26/kailong/GPU_test/server/onnx_build/onnxruntime/build/install/backends/onnxruntime/libtriton_onnxruntime.so
22# 0x00007F42A31D34F0 in /data/nfs_rt26/kailong/GPU_test/server/lib/libtritonserver.so
23# 0x00007F42A31D3B3D in /data/nfs_rt26/kailong/GPU_test/server/lib/libtritonserver.so
24# 0x00007F42A30A7691 in /data/nfs_rt26/kailong/GPU_test/server/lib/libtritonserver.so
25# 0x00007F42A31CE1C9 in /data/nfs_rt26/kailong/GPU_test/server/lib/libtritonserver.so
26# 0x00007F42A18F1F6F in /data/nfs_rt26/kailong/GPU_test/server/lib/libstdc++.so.6
27# 0x00007F42A29C3DD5 in /lib64/libpthread.so.0
28# clone in /lib64/libc.so.6

Segmentation fault (core dumped)

**Comment by jbkyang-nvi** [comment]
Can you try using 23.07? This is a branch from almost 2 year ago

**Comment by busishengui** [comment]
> 

Sorry, My machine only has cuda11.4 and cannot be changed

**Comment by dyastremsky** [comment]
Unfortunately, it would not make sense for us to look at a bug from >1.5 years ago. It's likely this bug has been fixed, and any fixes would only be applied going forward. You may want to look at building the server and ORT backend [with Debug symbols](https://github.com/triton-inference-server/server/blob/main/docs/customization_guide/build.md#building-with-debug-symbols) to get a more detailed backtrace.

If you are able to provide full steps for a reproduction and would like further support, please look into NVIDIA AI Enterprise support [here](https://www.nvidia.com/en-us/data-center/products/ai-enterprise/).
