### ISSUE TITLE
Python backend: unpacked conda env - when will it be released?

### ISSUE THREAD

**Issue by enricorotundo** [triton-inference-server/server#6115]
The [python backend](https://github.com/triton-inference-server/python_backend)'s readme says: "_[...] Python backend also supports unpacked conda execution environments, given it points to an activation script to setup the conda environment. [...]_". I'm using the docker `nvcr.io/nvidia/tritonserver:23.xx-py3` images and I've realized this feature has not been released yet. Is that the case? When would you plan on releasing that?

I'm currently dealing with a 2.7G `py38.tar.gz` env and `python_be.cc` takes _at least_ 1 minute to unpack/read on a fairly powerful machine. What would be the expected loading time boost?

**Comment by jbkyang-nvi** [comment]
I believe [r23.07](https://github.com/triton-inference-server/python_backend/tree/r23.07) image is released today (7/27 at 2PM PST). [nvcr.io/nvidia/tritonserver:23.07-py3](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/tritonserver/tags).

**Comment by yeahdongcn** [comment]
["python_backend"](https://github.com/triton-inference-server/python_backend) supports [unpacked Conda execution environment](https://github.com/triton-inference-server/python_backend/tree/r23.07#creating-custom-execution-environments).

**Comment by yeahdongcn** [comment]
> ["python_backend"](https://github.com/triton-inference-server/python_backend) supports [unpacked Conda execution environment](https://github.com/triton-inference-server/python_backend/tree/r23.07#creating-custom-execution-environments).

Question: Where to set the conda activation script location in a Python model?

**Comment by enricorotundo** [comment]
I think that readme needs more details. It points out to use `$path_to_conda_pack/lib/python<your.python.version>/site-packages/conda_pack/scripts/posix/activate` but it's not 100% clear whether that value should go into `parameters. EXECUTION_ENV_PATH.string_value` model config, or somewhere else.
Furthermore, that `conda_pack/scripts/posix/activate` script is available only if you install conda-pack into your inference conda env, which is not expected since I'd normally install conda-pack only on my "base" environment.

**Comment by enricorotundo** [comment]
> I believe [r23.07](https://github.com/triton-inference-server/python_backend/tree/r23.07) image is released today (7/27 at 2PM PST). [nvcr.io/nvidia/tritonserver:23.07-py3](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/tritonserver/tags).

Cool thanks @jbkyang-nvi !

> Please let us know if it works.

Actually I'll need to use it on Sagemaker so I need them to support it too (https://github.com/aws/deep-learning-containers/blob/master/available_images.md#nvidia-triton-inference-containers-sm-support-only) 😃

**Comment by jbkyang-nvi** [comment]
> Question: Where to set the conda activation script location in a Python model?

@yeahdongcn, @enricorotundo. Unfortunately there's no great way to activate the environment without the conda-pack provided activation script, therefore the more straightforward way is to conda-pack your conda environment, unpack the environment, and add the unpacked path to `EXECUTION_ENV_PATH`.

The activate script should be in the `bin` folder. You shouldn't need to add the `activate` script path to `config.pbtxt` at all, sorry about the confusion.
