### ISSUE TITLE
model config feature instance_group does not load model in specific gpu

### ISSUE THREAD

**Issue by TanvirHundredOne** [triton-inference-server/server#6124]
I am trying to build an ensemble model where specific models will be loaded in specific gpu. I am trying to do that `instance_group` key in `config.pbtxt` . But all the models seem to load in the first gpu of the gpus I am assigning to nvidia-triton docker container.

here are the config files of 2 models and the ensemble models

**ensemble->config.pbtxt**
```
name: "ensemble_model"
platform: "ensemble"
max_batch_size: 256

input [
{
    name:"raw_image"
    data_type:TYPE_FP32
    dims: [-1, -1, -1]
}
]
output [
{
    name:"doc_class"
    data_type:TYPE_STRING
    dims: [-1, -1]
}
]

ensemble_scheduling {
    step [
        {
        model_name: "alignment"
        model_version: -1
        input_map {
            key: "input_image"
            value: "raw_image"
        }
        output_map {
            key: "aligned_image"
            value: "preprocessed_image"
        }
        },
        {
        model_name: "doc_classification"
        model_version: -1
        input_map {
            key: "aligned_image"
            value: "preprocessed_image"
        }
        output_map {
            key: "doc_type"
            value: "doc_class"
        }
        }
    ]
}
```

**alignment-->config.pbtxt**
```
backend: "python"
max_batch_size: 256 

input [
{
    name:"input_image"
    data_type:TYPE_FP32
    dims: [-1, -1, -1]
}
]

output [
{
    name:"aligned_image"
    data_type:TYPE_FP32
    dims: [-1, -1, -1]
}
]

instance_group [
{
    count: 1
    kind: KIND_GPU
    gpus: [ 1 ]
}
]
```

**doc_classification->config.pbtxt**
```
backend: "python"
max_batch_size: 0 

input [
{
    name:"aligned_image"
    data_type:TYPE_FP32
    dims: [-1, -1, -1]
}
]

output [
{
    name:"doc_type"
    data_type:TYPE_STRING
    dims: [-1, -1]
}
]
instance_group [
{
    count: 1
    kind: KIND_GPU
    gpus: [ 0 ]
}
]
```

nvidia-triton docker container run command:
`docker run --env CUDA_VISIBLE_DEVICES=1,2 --gpus=all -it --shm-size=20g --rm -p8000:8000 -p8001:8001 -p8002:8002 -v /path-to-models/models:/trained_models/ -v ${PWD}/model_repository:/models nvcr.io/nvidia/tritonserver:23.05-py3 bash`

triton-server command:
`tritonserver --model-repository=/models`

Here is the Gpu utilization
![image](https://github.com/triton-inference-server/server/assets/35261471/b361fae9-79c6-4aa0-ab60-eea01735160c)

**Comment by dyastremsky** [comment]
Thank you for reporting this behavior.

@GuanLuo, does the above look like a bug? If so, I can open a ticket.

**Comment by fpeyre** [comment]
We observe the same behaviour on our side.

We are running triton on kubernetes. We assign 2 GPU to our pod
We have two models and we want to force each model to be loaded on a different GPU.
In order to do that, we are using the `instance_group` parameters

```
# Model 1

instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [0]
  }
]

# Model 2

instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [1]
  }
]
```

We are seing the following logs

```
#Model 1
2023-08-08T23:23:50Z I 104 python_be.cc:2076] TRITONBACKEND_ModelInstanceInitialize: instance initialization successful model_1(device 0)
2023-08-08T23:23:50Z I 104 backend_model_instance.cc:806] Starting backend thread for model_1at nice 0 on device 0...
2023-08-08T23:23:50Z I 104 dynamic_batch_scheduler.cc:292] Starting dynamic-batcher thread for model_1 at nice 0...
2023-08-08T23:23:50Z I 104 model_lifecycle.cc:815] successfully loaded 'model_1'

#Model 2
2023-08-08T23:26:41Z I 104 python_be.cc:2076] TRITONBACKEND_ModelInstanceInitialize: instance initialization successful model_2 (device 1)
2023-08-08T23:26:41Z I 104 backend_model_instance.cc:806] Starting backend thread for model_2 at nice 0 on device 1...
2023-08-08T23:26:41Z I 104 dynamic_batch_scheduler.cc:292] Starting dynamic-batcher thread for model_2 at nice 0...
2023-08-08T23:26:41Z I 104 model_lifecycle.cc:815] successfully loaded 'model_2'
```
which indicate that each model is loaded on a different device

However, when we run a nvidia-smi inside our pod, our models are only loaded on our GPU 0

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100 80G...  On   | 00000000:17:00.0 Off |                    0 |
| N/A   37C    P0    72W / 300W |  62518MiB / 81920MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A100 80G...  On   | 00000000:CA:00.0 Off |                    0 |
| N/A   35C    P0    75W / 300W |    912MiB / 81920MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
```

**Comment by dyastremsky** [comment]
Thank you for reporting your issue as well. We have filed a ticket (DLIS-5275) to investigate this.

**Comment by tanmayv25** [comment]
I see that you are using python backend. In this case it should be the model.py developer responsibility to respect the `model_instance_device_id` provided to the model in initialize call. 
If the model.py initialize function is ignoring the device specification, then default device(GPU 0) will be used. See the documentation on the fields provided by triton to model instance initialize here: https://github.com/triton-inference-server/python_backend/tree/main#initialize

See example here: https://github.com/triton-inference-server/python_backend/tree/main/examples/instance_kind

**Comment by dyastremsky** [comment]
Thanks for that correction, Tanmay. I missed that this is happening in a Python model in the ensemble.

Since this is expected behavior and Tanmay answered the question, I'm going to close out this ticket. If you need this ticket reopened for follow-up, please let us know.
