### ISSUE TITLE
Invalid curl library directory set by triton client and third-party CMakeLists.txt for 32-bit build

### ISSUE THREAD

**Issue by skottmckay** [triton-inference-server/server#6134]
**Description**
CMakeLists.txt assumes only a 64-bit build is being done with CentOS and hardcodes the curl library directory to 'lib64'. For a 32-bit build this is invalid.

https://github.com/triton-inference-server/client/blob/f7c45d382639f31a5162666034fae7852681f082/CMakeLists.txt#L76-L87
https://github.com/triton-inference-server/third_party/blob/de22dfb0509180c6c382edb24318bc49a13fd9aa/CMakeLists.txt#L71-L78

**Triton Information**
Version: r23..05 but problem exists on `main`.

Are you using the Triton container or did you build it yourself?  Building from source

**To Reproduce**
Using cibuildwheel to build 32 and 64-bit python wheels of onnxruntime-extensions. Setup it non-trivial as it involves external projects and curl not being installed at the system level. 

**Expected behavior**
Check that it is a 64-bit build before setting CURL_LIB_DIR to 'lib64'. 

e.g. adding a check for the size of a void pointer is one option
```
    if(DISTRO STREQUAL "CentOS Linux" AND CMAKE_SIZEOF_VOID_P EQUAL 8)
      set (CURL_LIB_DIR "lib64")
    endif()
```

**Comment by dyastremsky** [comment]
We don't officially support 32-bit or CentOS officially. See the build documentation [here](https://github.com/triton-inference-server/server/blob/main/docs/customization_guide/build.md). If we add support for these architectures, we will take a look then. If you are able, using the Docker containers for running Triton could be a good route to take.
