### ISSUE TITLE
API to get queue_size for a model for loadbalance

### ISSUE THREAD

**Issue by sfc-gh-zhwang** [triton-inference-server/server#6136]
We are deploying multiple triton instance for inferencing. Does triton provide an API to report the queue size of a certain model, so that we can use this information for load balancing?

Right now, I only found triton support reject a request if queue size is above some limit, but this doesn't really fit our need.

**Comment by dyastremsky** [comment]
No, we are tracking this enhancement request here: https://github.com/triton-inference-server/server/issues/5927
