### ISSUE TITLE
support for BLS between CPU and GPU models

### ISSUE THREAD

**Issue by rajsrujan77** [triton-inference-server/server#6137]
We were earlier using python_backend version r21.08.
In the pipeline we were able to send BLS calls from CPU model to a GPU model without any issue.

As we want to use the new python_backend feature like async BLS calls, we tried building newer python_backend version r22.12.

There we are getting an issue to send BLS calls from CPU model to a GPU model.

![image](https://github.com/triton-inference-server/server/assets/13798104/c453fa10-7507-4bd0-ab75-dc597b2e476b)

Is the data copy between CPU and GPU models not allowed in the newer versions? 

Issue is we don't want to use GPU for python backend models as these do not share the cuda context and starts consuming a lot of GPU mem, hence we need them on CPU.

**Comment by Tabrizian** [comment]
I believe the 21.08 version didn't have GPU tensor support and would move all the tensors to CPU. Are you compiling Python backend with `-DTRITON_ENABLE_GPU=OFF`? @krishung5 also recently added support for `preferred_memory` in BLS if you would like to keep all the tensors on CPU.

**Comment by rajsrujan77** [comment]
> I believe the 21.08 version didn't have GPU tensor support and would move all the tensors to CPU. Are you compiling Python backend with `-DTRITON_ENABLE_GPU=OFF`? @krishung5 also recently added support for `preferred_memory` in BLS if you would like to keep all the tensors on CPU.

@Tabrizian We have 2 kinds of models in our ensemble, one where the python backend is on CPU and we use BLS to an other GPU model. And the other is a python backend model which requires GPU. 

So, when we built the python_backend with `-DTRITON_ENABLE_GPU=OFF` we couldn't load the python backend model that uses GPU. And when we built the pythn backend with `-DTRITON_ENABLE_GPU=ON` we were facing the above issue I mentioned while calling a GPU model from a CPU model using BLS.

**Comment by rajsrujan77** [comment]
> Are you sure there are GPUs visible to Triton inside your container (e.g. passing the `--gpus all` flag)?
> 
> @Tabrizian, do you know the answer to the above? Do you have to do anything beyond specifying KIND_GPU/KIND-CPU in the individual model configs?

Yes @dyastremsky we have GPU access to the container.

**Comment by rajsrujan77** [comment]
We have converted all our models and python backend processes to newer version. As suggested by @Tabrizian we are now able to use `preferred_memory` flag for using BLS between CPU and GPU models.

Thanks for the support. Closing the issue.
