### ISSUE TITLE
Multi model load fails with Below Error : error: creating server: Internal - failed to load all models

### ISSUE THREAD

**Issue by hasnainkothawala** [triton-inference-server/server#6160]
**Description**
I am trying to load a few models using Triton Server on Kubeflow. The models load and come in READY state however within a few seconds the triton starts destroying and unloading the modes with below error.
**Multi-model load fails with Below Error : error: creating server: Internal - failed to load all models (stack trace attached)**

**Triton Information**
nvcr.io/nvidia/tritonserver:21.09-py3

**infrastructure**
AWS EKS G4dn.xlarge servers.

Are you using the Triton container or did you build it yourself?
I am using the triton server.

**To Reproduce**
Deployment files attached.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
Attached are the config files

**Expected behavior**
I am expecting both the models to load and infer as Triton promised multimodel deployments. 

 **Note** 
When both the models are deployed individually, they load well and I was able to run a performance test which also went well.

**I would really appreciate if someone could help since I have been struggling with this for a while.**

**Below is the deployment file**
![image](https://github.com/triton-inference-server/server/assets/46241927/49fa4605-722c-4c86-9967-a1aacb98bc37)

   
   **Below is the error - detailed error logs attached.** 
 `  
 I0808 10:39:15.107221 1 model_repository_manager.cc:547] BackendStates()
I0808 10:39:15.107265 1 server.cc:589]
+--------------------------------+---------+--------+
| Model                          | Version | Status |
+--------------------------------+---------+--------+
| detectron-service              | 1       | READY  |
| qa-roberta-base-squad2-service | 1       | READY  |
+--------------------------------+---------+--------+

I0808 10:39:17.109388 1 server.cc:264] Timeout 28: Found 1 live models and 0 in-flight non-inference requests
I0808 10:39:17.109395 1 server.cc:271] qa-roberta-base-squad2-service v1: UNLOADING
I0808 10:39:17.767647 1 python.cc:1775] TRITONBACKEND_ModelFinalize: delete model state
I0808 10:39:17.767680 1 triton_backend_manager.cc:101] unloading backend python
I0808 10:39:17.767685 1 python.cc:1732] TRITONBACKEND_Finalize: Start

error: creating server: Internal - failed to load all models
`

**Below is the CUDA details on the instance:**
![image](https://github.com/triton-inference-server/server/assets/46241927/87e1fa00-ba2e-4c79-88b5-9bf94665c9e2)

      
[config_detectron.txt](https://github.com/triton-inference-server/server/files/12290429/config_detectron.txt)
[config_qa.txt](https://github.com/triton-inference-server/server/files/12290434/config_qa.txt)
[deployment.txt](https://github.com/triton-inference-server/server/files/12290487/deployment.txt)
[error_logs.txt](https://github.com/triton-inference-server/server/files/12290507/error_logs.txt)

**Comment by rmccorm4** [comment]
Hi @hasnainkothawala,

Judging from your error logs, it looks like you have some extra directories in your model repository that are not actually model directories:
```
E0808 10:37:28.578765 1 model_repository_manager.cc:1890] Poll failed for model directory '_od': unexpected platform type  for _od
...
E0808 10:37:28.579221 1 model_repository_manager.cc:1890] Poll failed for model directory '_qa': unexpected platform type  for _qa
```

So I'm guessing that Triton is seeing a model repository that looks something like this:
```
models/
--- detectron-service/
--- qa-roberta-base-squad2-service/
--- _qa/  # <--- not a model dir
--- _od/  # <--- not a model dir
```

If this is the case, you'll need to move these folders outside of your `models/` model repository as they are not valid triton models. This could be moving them up out of the `models/` dir completely, or down into one of the model dirs, depending on what you need to do. Another alternative I believe you can do is in `--model-control-mode explicit`, Triton won't verify all of the directories in the model repository up front, so you can let Triton ignore them and then explicitly load your specific models with the model load APIs.

**Comment by hasnainkothawala** [comment]
Thank you so much @rmccorm4 , I am not sure where those dirs are coming from since they are not in my bucket which is weird.

However I ended up passing the following to the server  and it worked, 

`--exit-on-error=false --strict-readiness=false`

**Comment by rmccorm4** [comment]
Happy to help, I'll go ahead and close this issue then.
