### ISSUE TITLE
triton warmup treats one string input as two strings 

### ISSUE THREAD

**Issue by weidezhang** [triton-inference-server/server#6161]
**Description**
During the triton server warmup, I am using a single text input in the warmup configuration, however, triton server fails to load the model since it thinks there are 2 strings input.  The error shows as the following: 
```
| sentence | 1       | UNAVAILABLE: Invalid argument: failed to run warmup sample 'text_12': unexpected number of string elements 2 for inference input 'inputs', expecting 1; unexpected number of string elements 2 for inference input 'inputs', expecting 1; unexpected number of string elements 2 for inference input 'inputs', expecting 1; unexpected number of string elements 2 for inference input 'inputs', expecting 1; unexpected number of string elements 2 for inference input 'inputs', expecti
```

The string contains some special characters(utf-8 valid characters), if i remove the special character, the warmup works. 

"(a) The person is with another person not the accused's spouse; ", (this works) 
"(a) The person is with another person not the accused�~@~Ys spouse; " (this doesn't work) 

So, my question is why the special characters makes triton thinks it is two strings and if there is any rules i need to remove those special characters ? I already validate those special characters, they are in deed valid utf-8 strings.  In the original pdf. those
```
 '�~@~Y' corresponds to " '  "
```

**Triton Information**
23.05 

Are you using the Triton container or did you build it yourself?
build it myself with tensorflow2 backend 

**To Reproduce**
Steps to reproduce the behavior.
The model I'm using is : 
https://tfhub.dev/google/universal-sentence-encoder-multilingual/3

The config.pbtxt is as follows and I also attached the "text_12.bin" for warmup. 

[text_12.zip](https://github.com/triton-inference-server/server/files/12292599/text_12.zip)
```
name: "sentence"
platform: "tensorflow_savedmodel"
max_batch_size: 64

input [
    {
        name: "inputs"
        data_type: TYPE_STRING
        dims: [-1]
        allow_ragged_batch: true
    }
]
output [
    {
        name: "outputs"
        data_type: TYPE_FP32
        dims: [512]
    }
]
dynamic_batching {
  preferred_batch_size: [1, 2, 4, 8, 16, 32, 64]
  max_queue_delay_microseconds: 30000
}
optimization {
  graph { level: 1 }
}
response_cache {
  enable: true
}
model_warmup [
{
    name : "text_12"
    batch_size: 64
    inputs {
        key: "inputs"
        value: {
            data_type: TYPE_STRING
            dims: [1]
            input_data_file: "text_12.bin"  //the file contains the 4 byte length followed by string bytes 
        }
    }
}
]
```

**Expected behavior**
warmup for single string should input as single string, not 2.

**Comment by rmccorm4** [comment]
Hi @weidezhang,

Based on this:

> "(a) The person is with another person not the accused's spouse; ", (this works)
> "(a) The person is with another person not the accused�~@~Ys spouse; " (this doesn't work)

I'm suspecting that the UTF-8 characters may be multiple bytes, and therefore maybe your calculated total byte size does not match for the UTF-8 character case? Can you try confirming that?

**Comment by weidezhang** [comment]
yes, it is the byte length issue. thx

**Comment by fighterhit** [comment]
Hi @rmccorm4 , I also encountered this problem, but I used `serialize_byte_tensor` in tritonclient according to the  https://github.com/triton-inference-server/server/issues/3844#issuecomment-1021734020 .
```
import numpy as np
from tritonclient.utils import serialize_byte_tensor
from tritonclient.utils import np_to_triton_dtype
with open("my.pkl", "rb") as f:
    data_seq = pickle.load(f)

with open("state_bytes.bin", "ab") as fh:
    for index, data in enumerate(data_seq):
        state_bytes = msgpack.packb(data)
        serialized = serialize_byte_tensor(
            np.array([[state_bytes]], dtype=np.object_)
        )

        fh.write(serialized.item())
```

```
name: "mymodel"
backend: "python"
max_batch_size: 64
input [
  {
        name: "state_bytes"
        data_type: TYPE_STRING
        dims: [ 1 ]
  }
]

output [
  {
    name: "action_bytes"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]


instance_group [
    {
        count: 10
        kind: KIND_CPU
    }
]

sequence_batching {
  max_sequence_idle_microseconds: 30000000
  oldest {
    max_candidate_sequences: 128
    preferred_batch_size: [2]
    max_queue_delay_microseconds: 1000
  }
}

model_warmup [
  {
    name: "warmup_request",
    batch_size: 1,
    count: 100,
    inputs: {
      key: "state_bytes",
      value: {
        data_type: TYPE_STRING,
        dims: [ 1 ],
        input_data_file: "state_bytes.bin"
      }
    }
  }
]
```

```
| mymodel | 1       | UNAVAILABLE: Invalid argument: [request id: <id_unknown>] unexpected number of string elements 2 for inference input 'state_bytes' for model 'mymodel', expecting 1 |
```
