### ISSUE TITLE
Nested submodels can not be traced ?

### ISSUE THREAD

**Issue by monsterlyg** [triton-inference-server/server#6175]
I am tracing a model-repository which contains multi-models but I found the nested sub-ensemble models which are not scheduled in the top parent ensemble model were not traced. Is it a supported feature ?

**Comment by rmccorm4** [comment]
CC @oandreeva-nv for references on recent work.

**Comment by oandreeva-nv** [comment]
Hi @monsterlyg , could you please provide more information, i.e. what version of Triton you are using, what tracing mode you are using, what is the structure of your model, what you expect to see and what you are currently seeing.

**Comment by oandreeva-nv** [comment]
We've added nested spans support in 23.07 version for tracing with OpenTelemetry mode: https://github.com/triton-inference-server/server/blob/main/docs/user_guide/trace.md#opentelemetry-trace-support. If this is something, you haven't tried, I encourage you to check it out and see if this solves your issue.

**Comment by monsterlyg** [comment]
I'll take a try.



---Original---
From: "Olga ***@***.***&gt;
Date: Sat, Aug 12, 2023 03:34 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [triton-inference-server/server] Nested submodels cat not betraced ? (Issue #6175)




 
We've added nested spans support in 23.07 version for tracing with OpenTelemetry mode: https://github.com/triton-inference-server/server/blob/main/docs/user_guide/trace.md#opentelemetry-trace-support. If this is something, you haven't tried, I encourage you to check it out and see if this solves your issue.

**Comment by monsterlyg** [comment]
22.12 with TIMESTAMP. The structure is like:
ensemble
- - modelA
- - modelB
- - - - modelH
- - - - modelJ
- - modelC
model.A,B,C are the child models of the&nbsp; ensemble model and model.H,J are the child models of.model B. I've found that only ABC and the ensemble have tracing info in the trace file. Of course all nodes are expected.&nbsp;

---Original---
From: "Olga ***@***.***&gt;
Date: Sat, Aug 12, 2023 03:01 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [triton-inference-server/server] Nested submodels cat not betraced ? (Issue #6175)




 
Hi @monsterlyg , could you please provide more information, i.e. what version of Triton you are using, what tracing mode you are using, what is the structure of your model, what you expect to see and what you are currently seeing.

**Comment by monsterlyg** [comment]
> We've added nested spans support in 23.07 version for tracing with OpenTelemetry mode: https://github.com/triton-inference-server/server/blob/main/docs/user_guide/trace.md#opentelemetry-trace-support. If this is something, you haven't tried, I encourage you to check it out and see if this solves your issue.

I am not sure whether I use OpenTelemetry successfully with error:
```
[Error] File: /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/opentelemetry-cpp/src/opentelemetry-cpp/exporters/otlp/src/otlp_http,Body:t.Content-Type: text/plain] Export failed, Status:400, Header:    Content-Length: 0
[Error] File: /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/opentelemetry-cpp/src/opentelemetry-cpp/exporters/otlp/src/otlp_http_exporter.cc:107 [OTLP HTTP Client] ERROR: Export 1 trace span(s) error: 1
```
The triton was launched with:
```
tritonserver --model-repository=./ \
--http-port=5104 \
--metrics-port=5105 \
--grpc-port=5106 \
--trace-config mode=opentelemetry \
--trace-config opentelemetry,resource=service.name=tritonserver \
--trace-config opentelemetry,url=http://localhost:5104/v1/traces \
--trace-config triton,file=/ssd2/lyg/files/trace_files/ottrace.json \
--trace-config triton,log-frequency=50 \
--trace-config rate=100 \
--trace-config level=TIMESTAMPS \
--trace-config count=100 
```

**Comment by oandreeva-nv** [comment]
It seems like Triton is trying to export collected traces, but it can't. May I ask if you've set up a collector on `localhost:5104/v1/traces` ? For a debugging purposes, you can try to run Jaeger docker container, as shown [here](https://opentelemetry.io/docs/instrumentation/cpp/exporters/#jaeger)

**Comment by oandreeva-nv** [comment]
I also recommend to set up a different port for opentelemetry exporter. I believe, now you have Triton's http port and port set up for OpenTelemetry's exporter matching `--trace-config opentelemetry,url=http://localhost:5104/v1/traces `

**Comment by monsterlyg** [comment]
> It seems like Triton is trying to export collected traces, but it can't. May I ask if you've set up a collector on `localhost:5104/v1/traces` ? For a debugging purposes, you can try to run Jaeger docker container, as shown [here](https://opentelemetry.io/docs/instrumentation/cpp/exporters/#jaeger).
> 
> 22.12 container is a little bit old, I recommend trying both tracing APIs with newer versions.
> 
> `--trace-config opentelemetry,log-frequency=50` - is not going to work, `log-frequency` is only valid for Triton Trace API
In fact, I switched to r23.07 container in this experiment. I have no experience on using OpenTelemetry before and usually triton runs on the remote server. So it may be difficult to visualize the tracing info in a browser through jaeger. And I have no idea about how to "set up a collector".  So what it should be like if anything runs correctly with OpenTelemetry mode, can you share an example ?

**Comment by oandreeva-nv** [comment]
@monsterlyg May I ask you to try Triton Trace API in 23.07 version and see if your issue persists?

For OpenTelemetry, you can run [Jaeger](https://www.jaegertracing.io/docs/1.6/) docker container, that will be your collector and visualization tool. Simply run:
```
docker run -d --name jaeger -e COLLECTOR_OTLP_ENABLED=true -p 16686:16686  -p 4318:4318   jaegertracing/all-in-one:latest
```
More on Jaeger's Docker image you can find [here](https://www.jaegertracing.io/docs/1.6/getting-started/#all-in-one-docker-image). And access the UI in `http://localhost:16686/`. Note, the above command will expect traces to be exported to `localhost:4310/v1/traces`, which is a default url for `trace-config opentelemetry,url` . 

Now you can start your Triton server instance with:
```
tritonserver --model-repository=./ \
--http-port=5104 \
--metrics-port=5105 \
--grpc-port=5106 \
--trace-config mode=opentelemetry \
--trace-config opentelemetry,resource=service.name=tritonserver \
--trace-config rate=100 \
--trace-config level=TIMESTAMPS \
--trace-config count=100 
```
and send requests. Jaeger's UI located at `http://localhost:16686/` is quite straightforward, it will look like [this](https://www.jaegertracing.io/docs/1.6/#traces-view). Pick `tritonserver` under `Service` drop down menu and you should be able to see traces. Note Service name was specified by `--trace-config opentelemetry,resource=service.name=tritonserver` option.

**Comment by monsterlyg** [comment]
@oandreeva-nv It runs well. Thanks.

**Comment by oandreeva-nv** [comment]
@monsterlyg Happy to hear. I will close this issue then. Feel free to reach out here if you have any other questions, we can always re-open the closed issue.
