### ISSUE TITLE
A conformance test suite is required for testing the custom backend

### ISSUE THREAD

**Issue by yeahdongcn** [triton-inference-server/server#6178]
**Is your feature request related to a problem? Please describe.**
I'm adding a new backend for Triton using backend API and the backend skeleton is copied from [recommended](https://github.com/triton-inference-server/backend/tree/main/examples/backends/recommended). AFAIK, I need to test all sorts of input/output combinations and supported parameters for configuring models. But I'm not confident to deliver this backend since I don't know whether the above tests are enough.

**Describe the solution you'd like**
A conformance test suite is required for testing the custom backend.

**Describe alternatives you've considered**
As an alternative, a checklist of all test cases would be acceptable.

**Additional context**
N/A

**Comment by yeahdongcn** [comment]
@dyastremsky Any ideas?

**Comment by dyastremsky** [comment]
This has previously been investigated [in 772](https://github.com/triton-inference-server/server/issues/772) and [4779](https://github.com/triton-inference-server/server/issues/4779), with the latter still being open with an associated feature request. The request has not yet been prioritized. In regards to testing until then, you may want to use the tests in server/qa as a reference for how we do a lot of the testing (e.g. L0_backend_identity).

I'm going to close this as a duplicate to keep the conversation in the issue tracking this. Please feel free to comment in 4779.

CC: @nnshah1 @Christina-Young-NVIDIA @tanmayv25 for awareness for task prioritization.

**Comment by yeahdongcn** [comment]
Thanks for letting me know about the previous discussions.
