### ISSUE TITLE
How do I add multiple operators to the same triton server when I use TensorRT.

### ISSUE THREAD

**Issue by HeyMrYu** [triton-inference-server/server#6183]
How do I add multiple operators to the same triton server when I use TensorRT.

**Comment by dyastremsky** [comment]
The operators are part of creating the model. That wouldn't have to do with Triton. Triton will load the model as is.

If you mean you would like to use custom operators/plugins, you can use the backend config flag with the plugins option. The documentation with an example is in the TensorRT backend repository README [here](https://github.com/triton-inference-server/tensorrt_backend#command-line-options).
