### ISSUE TITLE
dynamic_batching  not working

### ISSUE THREAD

**Issue by jiuweisu** [triton-inference-server/server#6196]
triton server_version: 2.26.0 
i use python backend, but data not batched,and i got this problem :
```
Traceback (most recent call last):
  File "client_string.py", line 23, in <module>
    results = triton_client.infer(model_name='xverse_model1',
  File "/usr/local/lib/python3.8/dist-packages/tritonclient/http/__init__.py", line 1486, in infer
    _raise_if_error(response)
  File "/usr/local/lib/python3.8/dist-packages/tritonclient/http/__init__.py", line 65, in _raise_if_error
    raise error
tritonclient.utils.InferenceServerException: [request id: <id_unknown>] unexpected shape for input 'INPUT0' for model 'xverse_model1'. Expected [-1,-1], got [1]

```
if i delete the config`  max_batch_size: 8`, the problem can be solved. but i don't know whether dynamic_batching working.
if i send two request , the message "execute=============== " will be printed twice

![image](https://github.com/triton-inference-server/server/assets/84340727/86b1a451-7da3-4eef-8111-f7d56e344590)

config.pbtxt:
```
input [
  {
    name: "INPUT0" 
    data_type: TYPE_STRING 
    dims: [1 ] 
  }
]
output [
  {
    name: "OUTPUT0"
    data_type: TYPE_STRING
    dims: [1 ]
  }
]

  instance_group [
    {
      count: 1
      kind: KIND_GPU
      gpus: [ 0]
    }
  ]

 max_batch_size: 8

dynamic_batching {
    max_queue_delay_microseconds: 10000
}
```

**Comment by OminousBlackCat** [comment]
if the max_batch_size is larger than zero, the client must extend the dimension of input shape. In your case, set the max_batch_size to 8, you need to extend your client infer input. Specifically, the shape of the 'INPUT0' need to be [batch_size, 1], the batch_size can be any interger smaller than 8.

**Comment by jiuweisu** [comment]
thank you，this can solve my problem
