### ISSUE TITLE
Used opentelemetry-ccp version can crash triton

### ISSUE THREAD

**Issue by valkum** [triton-inference-server/server#6202]
**Description**
The used version (based on the thrid-party-src files 1.8.3) can crash triton if the OTel exporter timeouts. See https://github.com/open-telemetry/opentelemetry-cpp/issues/2191

**Triton Information**
2.34

We use the container.

**To Reproduce**
Block traffic to the OTLP endpoint of your OTel collector/ingestion point via a firewall.
Observe the following:
```
[Error] File: /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/opentelemetry-cpp/src/opentelemetry-cpp/exporters/otlp/src/otlp_http_client.cc:213 [OTLP HTTP Client] Session state: connection failed.Timeout was reached
[Error] File: /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/opentelemetry-cpp/src/opentelemetry-cpp/exporters/otlp/src/otlp_http_exporter.cc:107 [OTLP HTTP Client] ERROR: Export 1 trace span(s) error: 1
I0815 20:22:02.593456 1 infer_handler.cc:636] Process for ModelInferHandler, rpc_ok=1, 0 step 1
I0815 20:22:02.593479 1 infer_handler.h:1018] Done for ModelInferHandler, 0
[Error] File: /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/opentelemetry-cpp/src/opentelemetry-cpp/exporters/otlp/src/otlp_http_exporter.cc:107 [OTLP HTTP Client] ERROR: Export 1 trace span(s) error: 1
Signal (11) received.
[Error] File: /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/opentelemetry-cpp/src/opentelemetry-cpp/exporters/otlp/src/otlp_http_client.cc:213 [OTLP HTTP Client] Session state: connection failed.Timeout was reached
```
And triton crashing.

**Expected behavior**
This should not crash triton.

**Comment by nv-kmcgill53** [comment]
Hi @valkum, Thank you for filing this issue. Are you able to reproduce this using our latest 23.07 release (v2.36.0)?

**Comment by valkum** [comment]
I looked up the used `opentelemetry-cpp` version using the 23.07/2.36 container. I assume the crash we observed with 2.34 will not be fixed with upgrading to 2.36.  I will try to see if I can reproduce this issue locally using 23.07 and will report back.

**Comment by oandreeva-nv** [comment]
Thanks @valkum for reporting this. We will upgrade `opentelemetry-cpp` version to pick up this bug fix.

**Comment by oandreeva-nv** [comment]
The `opentelemetry-cpp` version was upgraded to v1.11.0 : https://github.com/triton-inference-server/third_party/pull/46
Expect changes to be picked up in 23.09 release.
