### ISSUE TITLE
Scale each component model with difference number instance  in ensemble model

### ISSUE THREAD

**Issue by linhld0811** [triton-inference-server/server#6207]
I had written done service ASR using tritonserver with ensemble backend with 3 component model: 
- extract feature - EF (using python backend - stateless style) 
- acousetic model - AM (using onnx backend - statefull style)
- language model - LM (using python backend - stateless style)
I wonder that is the tritonserver support scale each of above component with difference size to optimize performance of my service (for example 1  instance EF with batchsize 64 and 1  instance AM with batchsize 64 and 4 instance LM with batchsize 16)?
Addition, in the third component, can I write python backend with style statefull and manage state by myself?

**Comment by nv-kmcgill53** [comment]
Hi, @linhld0811,

> I wonder that is the tritonserver support scale each of above component with difference size to optimize performance of my service (for example 1 instance EF with batchsize 64 and 1 instance AM with batchsize 64 and 4 instance LM with batchsize 16)?

To understand the optimal configuration of your component models, this work will have to be done offline with the [model_analyzer tool](https://github.com/triton-inference-server/model_analyzer#triton-model-analyzer). You are able to scale your component models manually via updating the model config but Triton will not do so automatically.

> Addition, in the third component, can I write python backend with style statefull and manage state by myself?
CC: @Tabrizian
