### ISSUE TITLE
BLS backend crashing on reading input tensor from deepstream pipeline

### ISSUE THREAD

**Issue by dilip814** [triton-inference-server/server#6208]
**Description**
BLS backend crashing on reading input tensor from deepstream pipeline, input tensor is in GPU memory 
**Triton Information**
What version of Triton are you using?
23.04

Are you using the Triton container or did you build it yourself?
Triton pre-built container
**To Reproduce**
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
![Untitled Diagram-Page-5 drawio](https://github.com/triton-inference-server/server/assets/92431673/36215d43-497d-4d62-92df-f73dae6b8d1b)

I have built C++ BLS backend and BLS works fine if I use python application with grpc call for inferencing but if I use deepstream app do so, It is getting crashed.

I see input tensor memory is different in both the scenario, in case of python app, I am getting memory type 0 for input tensor which indicates CPU but if I use deepstream app then getting memory type 2 for input tensor which indicates GPU memory.

How can I access input image (tensor) from GPU memory into BLS model. below is my pipeline structure into triton-server.
**Expected behavior**

**Comment by nv-kmcgill53** [comment]
Possible related: https://github.com/triton-inference-server/server/issues/6179

**Comment by dilip814** [comment]
It was crashing due to input tensor was in GPU memory so added cuda stream copy to read from GPU memory fix the issue
