### ISSUE TITLE
How can I measure the overall throughtput of my system

### ISSUE THREAD

**Issue by wxthu** [triton-inference-server/server#6211]
For example, I wanna deploy two resnet50 models and two VGG16 models in one GPU and then send requests to all these 4 models in the frequency of 20 times per second. How can I measure the overall throughput for the whole system ? Could you give some demo code?

**Comment by rmccorm4** [comment]
Hi @wxthu,

If you have a specific scenario you want to test, I recommend checking out [Perf Analyzer](https://github.com/triton-inference-server/client/blob/main/src/c++/perf_analyzer/README.md).

If you want to let a tool automatically iterate through different configurations to see what config gets the optimal throughput/latency/etc., I would check out [Model Analyzer](https://github.com/triton-inference-server/model_analyzer).

If these help, please go ahead and close this issue.

**Comment by wxthu** [comment]
> Hi @wxthu,
> 
> If you have a specific scenario you want to test, I recommend checking out [Perf Analyzer](https://github.com/triton-inference-server/client/blob/main/src/c++/perf_analyzer/README.md).
> 
> If you want to let a tool automatically iterate through different configurations to see what config gets the optimal throughput/latency/etc., I would check out [Model Analyzer](https://github.com/triton-inference-server/model_analyzer).
> 
> If these help, please go ahead and close this issue.

I mean how can I feed request into multiple models simultaneously e.g multi-process and get the overall throughput either that of individual model or that of the whole system
