### ISSUE TITLE
ODDITY, resuming when not paused

### ISSUE THREAD

**Issue by codedoves** [triton-inference-server/server#6216]
[ERROR] evhtp.c:3101 ODDITY, resuming when not paused?!? :: (errno: Connection reset by peer)
[ERROR] evhtp.c:3101 ODDITY, resuming when not paused?!? :: (errno: Connection reset by peer)
[ERROR] evhtp.c:3101 ODDITY, resuming when not paused?!? :: (errno: Connection reset by peer)
[ERROR] evhtp.c:3101 ODDITY, resuming when not paused?!? :: (errno: Connection reset by peer)

 how to solve the problem ？？？

**Comment by krishung5** [comment]
Hi @codedoves, can you please fill out a [bug report](https://github.com/triton-inference-server/server/blob/main/.github/ISSUE_TEMPLATE/bug_report.md) so that we can better understand the issue here?

**Comment by krishung5** [comment]
Closing this as it's duplicated: https://github.com/triton-inference-server/server/issues/6229
