### ISSUE TITLE
pthon backend inference_request.exec() stuck

### ISSUE THREAD

**Issue by ycqjm718** [triton-inference-server/server#6236]
Operating system： CentOS 7.9.2009
Triton inference sever image version： 23.07-py3

![1693193812921](https://github.com/triton-inference-server/server/assets/50256476/bee1dc75-8230-45c3-8ccb-f700bab77def)
python backend question:
The program stops running at the box after sending the request.

![1703193972452](https://github.com/triton-inference-server/server/assets/50256476/1b879b7d-e437-43c0-b8db-8b12d296a0ab)

There is no problem entering parameters.
Log as follow：
![1713276258256](https://github.com/triton-inference-server/server/assets/50256476/026d8b35-9cc1-46ef-9e56-a332cabb68a4)

**Comment by kthui** [comment]
Hi @ycqjm718, can you elaborate on what `inference_request.exec()` does? Are there any modifications to the `pb_utils.InferenceRequest()`?

**Comment by ycqjm718** [comment]
It is used to call the model and get the inference result; I didn't change it.
I can use 'inference_request.exec()' in BLS mode, whether it can't be used in a single model

**Comment by ycqjm718** [comment]
> It is used to call the model and get the inference result; I didn't change it.
I can use 'inference_request.exec()' in BLS mode, whether it can't be used in a single model

**Comment by kthui** [comment]
On a single model, I think you will have to explicitly compute/provide the inference result. For example: 
```
        # Every Python backend must iterate through list of requests and create
        # an instance of pb_utils.InferenceResponse class for each of them.
        # Reusing the same pb_utils.InferenceResponse object for multiple
        # requests may result in segmentation faults. You should avoid storing
        # any of the input Tensors in the class attributes as they will be
        # overridden in subsequent inference requests. You can make a copy of
        # the underlying NumPy array and store it if it is required.
        for request in requests:
            # Perform inference on the request and append it to responses
            # list...
```
Reference: https://github.com/triton-inference-server/python_backend#usage

**Comment by ycqjm718** [comment]
@kthui ，Thank you very much for your answer

**Comment by hangben123** [comment]
@ycqjm718 Using bls reasoning will not cause the stuck problem mentioned above? can you explain it
