### ISSUE TITLE
PyTorch model stucks

### ISSUE THREAD

**Issue by SneakyBerry** [triton-inference-server/server#6239]
**Description**
PyTorch model stops responding when 2 or more concurrent requests came to it and increases GPU utilisation up to 100%.
![telegram-cloud-photo-size-2-5406851835953795311-y](https://github.com/triton-inference-server/server/assets/49777945/6d7641ce-53da-40b9-9b98-6f39576ae2e9)

Logs on shutdown:
```
triton_server  | Signal (15) received.
triton_server  | I0820 08:11:48.828863 1 server.cc:305] Waiting for in-flight requests to complete.
triton_server  | I0820 08:11:48.828889 1 server.cc:321] Timeout 30: Found 2 model versions that have in-flight inferences
triton_server  | I0820 08:11:48.828893 1 server.cc:325] Model 'ensemble' (version 1) has 71 in-flight inferences
triton_server  | I0820 08:11:48.828895 1 server.cc:325] Model 'module_1' (version 1) has 35 in-flight inferences
triton_server  | I0820 08:11:49.828972 1 server.cc:321] Timeout 29: Found 2 model versions that have in-flight inferences
triton_server  | I0820 08:11:49.828989 1 server.cc:325] Model 'ensemble' (version 1) has 71 in-flight inferences
triton_server  | I0820 08:11:49.828992 1 server.cc:325] Model 'module_1' (version 1) has 35 in-flight inferences
triton_server  | I0820 08:11:50.829068 1 server.cc:321] Timeout 28: Found 2 model versions that have in-flight inferences
triton_server  | I0820 08:11:50.829084 1 server.cc:325] Model 'ensemble' (version 1) has 71 in-flight inferences
triton_server  | I0820 08:11:50.829087 1 server.cc:325] Model 'module_1' (version 1) has 35 in-flight inferences
triton_server  | I0820 08:11:51.829166 1 server.cc:321] Timeout 27: Found 2 model versions that have in-flight inferences
triton_server  | I0820 08:11:51.829184 1 server.cc:325] Model 'ensemble' (version 1) has 71 in-flight inferences
triton_server  | I0820 08:11:51.829187 1 server.cc:325] Model 'module_1' (version 1) has 35 in-flight inferences
triton_server  | I0820 08:11:52.829266 1 server.cc:321] Timeout 26: Found 2 model versions that have in-flight inferences
triton_server  | I0820 08:11:52.829283 1 server.cc:325] Model 'ensemble' (version 1) has 71 in-flight inferences
triton_server  | I0820 08:11:52.829286 1 server.cc:325] Model 'module_1' (version 1) has 35 in-flight inferences
```

**Triton Information**
Triton server in docker with tag `23.07-py3`

**To Reproduce**
Use PyTorch model with count >1 and call it asynchronously.

**Expected behavior**
Everything is working without stuck issues.

**Comment by kthui** [comment]
Thanks for reporting the issue. I have filed a ticket for us to investigate further. DLIS-5299

**Comment by kthui** [comment]
Hi @SneakyBerry , can you do a quick check to see if the issue is addressed in 23.08? https://catalog.ngc.nvidia.com/orgs/nvidia/containers/tritonserver/tags

**Comment by kthui** [comment]
If I understand correctly, the PyTorch model did not stop responding on 23.07, and the issue is about worsen performance on 23.08 after upgrading from 23.07?

**Comment by SneakyBerry** [comment]
Behaviour of pytorch model (stuck spontaneously) didn't changed on 23.08 and overall performance on 23.08 degraded compared to 23.07 about 25%

**Comment by kthui** [comment]
Let us focus on the 23.07 and 23.08 stuck spontaneously problem on this issue. Can you open another issue for the degraded performance, if you would like it followed up?

For the PyTorch backend stuck spontaneously problem, can you share a minimum reproduction? It would be best to have a minimum TorchScript model with config.pbtxt, and share how inference(s) are called by the client.

**Comment by SneakyBerry** [comment]
Here is reproduction. It raises an error because of outputs on "success" but stuck is reproducing.

https://drive.google.com/file/d/1XHuaFU5HGW-RtXi3oqffMVie64SqtcQK/view?usp=sharing

**Comment by SneakyBerry** [comment]
Sorry, my fault. It isn't reproduces. I will do more research in our environment and maybe open another issue. Thanks!
