### ISSUE TITLE
are there methods to switch the pbconfig.txt between a local development environment and a server？

### ISSUE THREAD

**Issue by syuta-sugawara** [triton-inference-server/server#6258]
**Is your feature request related to a problem? Please describe.**
i want to run a machine learning model using GPU.
when using GPU, we should write pbconfig.txt like below.

```
instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]
```
however, when we make kind KIND_GPU, a machine learning model does not run in a local development.

**Describe the solution you'd like**

is threre any solution?
For example,there are methods to switch the pbconfig.txt between a local development environment and a server？

**Comment by dyastremsky** [comment]
There is not such a method. I am not exactly sure of your use case.

If you want your model to use GPU when available, else CPU, you can use [KIND_AUTO](https://github.com/triton-inference-server/common/blob/a2de06f4c80b2c7b15469fa4d36e5f6445382bad/protobuf/model_config.proto#L151). Alternatively, you can [supply the model config via the load API](https://github.com/triton-inference-server/server/blob/main/docs/protocol/extension_model_repository.md#load).

**Comment by syuta-sugawara** [comment]
@dyastremsky 
thanks!

I read the following statement.
> This instance group represents instances that can run on either CPU or GPU. If all GPUs listed in 'gpus' are available then
> instances will be created on GPU(s), otherwise instances will be created on CPU.
https://github.com/triton-inference-server/common/blob/a2de06f4c80b2c7b15469fa4d36e5f6445382bad/protobuf/model_config.proto#L153

i have a question.
Is it necessary to write  'gpus' ？
ex
```
instance_group [
  {
    kind: KIND_AUTO
    count: 1
    gpus: [0] 
  }
```

do not i need to write 'gpus'?
```
instance_group [
  {
    kind: KIND_AUTO
    count: 1
  }
```

**Comment by dyastremsky** [comment]
Please see this section of the model configuration documentation: https://github.com/triton-inference-server/server/blob/main/docs/user_guide/model_configuration.md#multiple-model-instances.

Your first config will only place one copy of the model on GPU 0. The second config will place one copy of the model on every GPU visible to Triton server.
