### ISSUE TITLE
Python model inference for a period of time card owner

### ISSUE THREAD

**Issue by hangben123** [triton-inference-server/server#6259]
**Description**
My Python backups were working normally at the beginning, but after providing services for a while, they got stuck. My Python backups are of the BLS type

**Triton Information**
Build it yourself, triton version is 23.03

**To Reproduce**

python mody.py 

 async def execute(self, requests):
        responses = []

        for request in requests:
            page_info = PageInfo()
            page_info.set_info(pb_utils.get_input_tensor_by_name(request, "eventfields"))

            inference_request = pb_utils.InferenceRequest(
                model_name='domtext_2_prompt-v1',
                requested_output_names=['query'],
                inputs=[pb_utils.get_input_tensor_by_name(request, "eventfields")])
            
            inference_response = inference_request.exec()
            output_list = []
           
            if inference_response.has_error():
                raise pb_utils.TritonModelException(
                    inference_response.error().message())
            else:
                response_page = pb_utils.get_output_tensor_by_name(inference_response, 'query').as_numpy()

            promt_string = bytes(response_page[0]).decode('utf-8')

            # pb_utils.Tensor("query", np.asarray(promt_string, dtype=np.bytes_))
            query = pb_utils.Tensor("query", np.array([promt_string], dtype=np.object_))

           
            inference_response_awaits = []
            models = ["item-bert", "item_category-bert", "service_category-bert"]
            # models = ['item-bert']
            output_dict = {
                            'item-bert': ['result'],
                            'item_category-bert': ['pred_label', 'pred_label_score'],
                            'service_category-bert': ['pred_label', 'pred_label_score']
                           }

           
            for model_name in models:
                # Create inference request object
                infer_request = pb_utils.InferenceRequest(
                    model_name=model_name,
                    requested_output_names=output_dict[model_name],
                    inputs=[query],
                )

               
                inference_response_awaits.append(infer_request.async_exec())

            inference_responses = await asyncio.gather(*inference_response_awaits)

            for infer_response in inference_responses:
                # Make sure that the inference response doesn't have an error.
                # If it has an error and you can't proceed with your model
                # execution you can raise an exception.
                if infer_response.has_error():
                    raise pb_utils.TritonModelException(
                        infer_response.error().message()
                    )

            res_list = []
            page_info.append_infer_res("1", get_list(inference_responses[0], "result")[0], "Item")
            page_info.append_infer_res(get_list(inference_responses[1], "pred_label_score")[0],
                                       get_list(inference_responses[1], "pred_label")[0], "ItemCategory")
            page_info.append_infer_res(get_list(inference_responses[2], "pred_label_score")[0],
                                       get_list(inference_responses[2], "pred_label")[0], "ServicesCategory")

            uumPromt = get_list(inference_responses[0], "result")[0]
            if uumPromt == "":
                uumPromt = promt_string
            uumPromt = uumPromt.replace(" ", "")
            inference_request = pb_utils.InferenceRequest(
                model_name='intent_inference',
                requested_output_names=['preds'],
                inputs=[pb_utils.Tensor("text", np.array([uumPromt], dtype=np.object_))])
            inference_response = inference_request.exec()

            uumData_ = pb_utils.get_output_tensor_by_name(inference_response, 'preds').as_numpy()
            uumData_ = bytes(uumData_[0]).decode('utf-8')
           
            logger.info("uumData_" + uumData_)
            uumData = json.loads(uumData_)
            page_info.append_infer_res("1", uumData[0]["ner"], "Ner")
            page_info.append_infer_res("1", uumData[0]["intent"], "Intent")

            result_ = {}
            # page_info_ = json.dumps(page_info.__dict__)
            page_info.ExtMap["prompt"] = promt_string
            result_["toCloud"] = page_info.__dict__
            result = json.dumps(result_)
            output1 = pb_utils.Tensor("result", np.asarray(result, dtype=np.object_))
            
            inference_response = pb_utils.InferenceResponse(
                output_tensors=[output1]
            )

            responses.append(inference_response)

        return responses

after multiple repeated requests, request the card owner again

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**

Able to execute inference services normally

**Comment by kthui** [comment]
Hi @hangben123, can you provide a trace on where it got stuck?

**Comment by hangben123** [comment]
card owner's log：

I0901 06:41:18.972081 29 infer_handler.cc:636] Process for ModelInferHandler, rpc_ok=1, 0 step 0
I0901 06:41:18.972130 29 infer_handler.cc:629] New request handler for ModelInferHandler, 0
I0901 06:41:18.972214 29 infer_request.cc:751] [request id: <id_unknown>] prepared: [0x0x7f7855ec9e90] request id: , model: page_bls, requested version: 1, actual version: 1, flags: 0x0, correlation id: 0, batch size: 0, priority: 0, timeout (us): 0
original inputs:
[0x0x7f7855eca3c8] input: eventfields, type: BYTES, original shape: [1], batch + shape: [1], shape: [1]
override inputs:
inputs:
[0x0x7f7855eca3c8] input: eventfields, type: BYTES, original shape: [1], batch + shape: [1], shape: [1]
original requested outputs:
result
requested outputs:
result

log of normal reasoning：

I0901 06:48:57.689372 21 http_server.cc:3448] HTTP request: 2 /v2/models/green_ai_bls/versions/1/infer
I0901 06:48:57.689463 21 infer_request.cc:751] [request id: <id_unknown>] prepared: [0x0x7f8024011b00] request id: , model: green_ai_bls, requested version: 1, actual version: 1, flags: 0x0, correlation id: 0, batch size: 0, priority: 0, timeout (us): 0
original inputs:
[0x0x7f802400f488] input: eventfields, type: BYTES, original shape: [1], batch + shape: [1], shape: [1]
override inputs:
inputs:
[0x0x7f802400f488] input: eventfields, type: BYTES, original shape: [1], batch + shape: [1], shape: [1]
original requested outputs:
requested outputs:
result

I0901 06:48:57.689562 21 python_be.cc:1244] model green_ai_bls, instance green_ai_bls_0_1, executing 1 requests
I0901 06:48:57.691898 21 python_be.cc:2230] TRITONBACKEND_ModelInstanceExecute: model instance name green_ai_bls_0_1 released 1 requests



By comparison, we can see that the current code is stuck in infer_request.cc:751
At present, the request has been processed by the triton sever and is waiting for the processing to be completed, but it has not entered the processing reasoning function that calls python backends. The existing logs only know that the card owner is stuck at a certain point in the middle

**Comment by hangben123** [comment]
@kthui   Can you help me take a look?

**Comment by hangben123** [comment]
@kthui   Can you help me take a look?

**Comment by hangben123** [comment]
@kthui   Can you help me take a look?

**Comment by kthui** [comment]
Can you try `--log-verbose=2`? This should print more logs from the server core.
