### ISSUE TITLE
python backends  study

### ISSUE THREAD

**Issue by hangben123** [triton-inference-server/server#6260]
https://github.com/triton-inference-server/python_backend#running-multiple-instances-of-triton-server

What does this mean in this document，Do you mean different models？

tritonserver --model-repository=/models --backend-config=python,shm-region-prefix-name=prefix1

This instruction cannot be run twice in a container，I want to know what you mean by this

Running Multiple Instances of Triton Server
Python backend uses shared memory to transfer requests to the stub process. When running multiple instances of Triton Server on the same machine that use Python models, there would be shared memory region name conflicts that can result in segmentation faults or hangs. In order to avoid this issue, you need to specify different shm-region-prefix-name using the --backend-config flag.

# Triton instance 1
tritonserver --model-repository=/models --backend-config=python,shm-region-prefix-name=prefix1

# Triton instance 2
tritonserver --model-repository=/models --backend-config=python,shm-region-prefix-name=prefix2
Note that the hangs would only occur if the /dev/shm is shared between the two instances of the server. If you run the servers in different containers that don't share this location, you don't need to specify shm-region-prefix-name.

**Comment by kthui** [comment]
Hi @hangben123, it means there should not be multiple Triton Servers running on the same machine that use Python models.

@Tabrizian do you think we should remove the word "Instances" to avoid confusion with "model instances"?

**Comment by hangben123** [comment]
yes，i still have some questions ，tritonserver --model-repository=/models --backend-config=python,shm-region-prefix-name=prefix1 ，

The phenomenon is that multiple python models are running in my docker, and I can’t reason. I don’t know if it’s because of memory sharing. I want to try this method, but the above can’t run

**Comment by hangben123** [comment]
![image](https://github.com/triton-inference-server/server/assets/127070080/6e827534-59a4-47b4-b16e-ac9d2a8e6b54)

**Comment by hangben123** [comment]
If I need to run multiple python models in one container like in the documentation, but I can't specify the name of the python shared memory at the same time

**Comment by Tabrizian** [comment]
You can run multiple Python models in one container. Only if you are running multiple Triton Servers that run Python models you would need to specify different shared memory region prefix.

**Comment by pharmapsychotic** [comment]
When you specify `--backend-config=python,shm-region-prefix-name=prefix1` that applies to all Python backends correct? So if you have multiple Python backends with the same tritonserver instance they will each try and use the same `shm-region-prefix-name` and fail. Is there a way to specify multiple prefix names somehow?
