### ISSUE TITLE
client c++ example

### ISSUE THREAD

**Issue by wxthu** [triton-inference-server/server#6263]
**Description**

I noticed in the official client c++ examples  that when I need to initialize the inputs, I always have to call **_AppendRaw_** to cast the data type to **_uint8_**. Does this mean that when my input is of float type, I need to overload the interface?
![image](https://github.com/triton-inference-server/server/assets/73052387/484552ea-16fc-42cf-9cc5-bbbffba039d1)

**Comment by fpetrini15** [comment]
cc @tanmayv25 @jbkyang-nvi

**Comment by jbkyang-nvi** [comment]
If you see [here](https://github.com/triton-inference-server/client/blob/main/src/c%2B%2B/examples/simple_grpc_infer_client.cc#L258-L262) you can do an `interpret cast` on your input data
