### ISSUE TITLE
for  bls mode, can all model(onnx, pt) write with py. and only using bls（model.py） to pipeline the input and output for server/client ？

### ISSUE THREAD

**Issue by foocker** [triton-inference-server/server#6266]
```
xxxx/
├── 1
│   ├── cache
│   ├── client.py
│   ├── examples
│   ├── inference.py
│   ├── model.py
│   ├── onnx_weights
│   ├── __pycache__
│   ├── results
│   └── src
└── config.pbtxt
```
all inference is python, execute only do get_input_tensor_by_name and InferenceResponse. but i meet :

```
+-----------+---------+----------------------------------------------------------------------------+
| Model     | Version | Status                                                                     |
+-----------+---------+----------------------------------------------------------------------------+
| xxxx| 1       | UNAVAILABLE: Internal: AssertionError: <EMPTY MESSAGE>                     |
|           |         |                                                                            |
|           |         | At:                                                                        |
|           |         |   /models/./xxxx/1/src/fxx/xxx.py(80): __init__                  |
|           |         |   /models/./xxxx/1/src/fxx/xxxxxxxxxxx.py(90): __init__ |
|           |         |   /models/./xxxx/1/src/utils/croper.py(12): __init__                  |
|           |         |   /models/./xxxx/1/src/utils/preprocess.py(60): __init__              |
|           |         |   /models/./xxxx/1/model.py(29): initialize                           |
+-----------+---------+----------------------------------------------------------------------------+
```
free(): invalid pointer
E0905 04:41:18.923154 1042 model_lifecycle.cc:626] failed to load 'xxxx' version 1: Internal: AssertionError: <EMPTY MESSAGE>

path is right. failed to load 'xxxx' version 1: Internal: Stub process 'xxxx_0' is not healthy
Inconsistency detected by ld.so: dl-version.c: 204: _dl_check_map_versions: Assertion `needed != NULL' failed!
received metadata size exceeds hard limit。 

### for the question from title , the answer is: yes.

**Comment by fpetrini15** [comment]
Hello @foocker is it possible for you to share the full error log and the model config?

**Comment by foocker** [comment]
> Hello @foocker is it possible for you to share the full error log and the model config?

i have make it right. but i meet: received metadata size exceeds hard limit(value length 7104610 vs. 16384).  as my station, i will translate a video which is transform to bytes.

**Comment by fpetrini15** [comment]
Hello @foocker.

1. I believe the hard limit for tensor size when using grpc is 2GB. If your output is larger than this limit, you must use the http endpoint.
2. I am not sure what your particular use-case for this characteristic is, however, you may want to take a look at [Triton decoupled mode](https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/user_guide/decoupled_models.html) which can send multiple or zero responses per request.

**Comment by foocker** [comment]
> Hello @foocker.
> 
>     1. I believe the hard limit for tensor size when using grpc is 2GB. If your output is larger than this limit, you must use the http endpoint.
> 
>     2. I am not sure what your particular use-case for this characteristic is, however, you may want to take a look at [Triton decoupled mode](https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/user_guide/decoupled_models.html) which can send multiple or zero responses per request.

thx. for 1. maybe using stream to put the generated video to some url?  i will try http.  
by the way, if the onnx model is not dynamic batch when export from *.pt. it can do dynamic batch in triton?

**Comment by fpetrini15** [comment]
A precondition of using dynamic batching in Triton is that the model supports batching: see [here](https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/examples/jetson/concurrency_and_dynamic_batching/README.html#demonstration-case-2-dynamic-batching). In terms of improving performance for your specific configuration I would recommend using our [model analyzer](https://github.com/triton-inference-server/model_analyzer) tool.

**Comment by foocker** [comment]
> 
1. batching i see. there are many sub model, almost supports batching, but some are not. this lead to all deploy do not supports batching... 
2. for loop and complex bls. such as contain ensemble and for loop and more than 4 sub module, it can't use model analyzer.
