### ISSUE TITLE
Unexplained stuck and failure of concurrent executions

### ISSUE THREAD

**Issue by wxthu** [triton-inference-server/server#6269]
**Description**
I sent multiple requests to two different models consecutively, and after each round of requests, I retrieved the inference results. The expected behavior was that both models would run in parallel during each round of inference. However, in reality, except for the first round, both models executed sequentially. 
![image](https://github.com/triton-inference-server/server/assets/73052387/cd71fd9a-2b27-4f78-92ba-7870a12fb8ff)

![image](https://github.com/triton-inference-server/server/assets/73052387/232915b8-c0f5-4e5f-8b22-bf355b4195a8)

As you can see, if I sent and received requests like this:
![image](https://github.com/triton-inference-server/server/assets/73052387/05b458a6-daa1-4d83-ba54-805070607e2f)

As you can see, there is a significant delay between the first and second rounds of inference, as if it's waiting for a semaphore
![image](https://github.com/triton-inference-server/server/assets/73052387/374a0ffc-d170-46cc-b51e-88823a8dd2b5)

When I conducted tests using the C++ API, both of the aforementioned issues still persisted
All the related files are **[HERE](https://github.com/wxthu/debug_triton_server/tree/sync_issue)**
I am looking forward to your reply and thanks so much!

**Triton Information**
r23.07 ,Triton container
NVIDIA Nsight Systems version 2023.3.1.92-233133147223v0

**Comment by fpetrini15** [comment]
Hello @wxthu, thank you for reporting an issue.

I took a look at your source files and am wondering if your bottleneck is a result of [setting your `concurrency` parameter for your client to 1](https://github.com/wxthu/debug_triton_server/blob/01294583db3652b1d923b347246a06ff6251417b/my_custom_http_async_infer_client.py#L83C55-L83C80). I believe setting a concurrency of 1 is limiting the number of possible in-flight requests: see [here](https://github.com/triton-inference-server/client/blob/8ecca2037a7c6791d4203bbc99afc138d6e28af2/src/python/library/tritonclient/http/_client.py#L1490-L1497). Can you try increasing your concurrency parameter and seeing if it resolves the issue?

**Comment by wxthu** [comment]
> Hello @wxthu, thank you for reporting an issue.
> 
> I took a look at your source files and am wondering if your bottleneck is a result of [setting your `concurrency` parameter for your client to 1](https://github.com/wxthu/debug_triton_server/blob/01294583db3652b1d923b347246a06ff6251417b/my_custom_http_async_infer_client.py#L83C55-L83C80). I believe setting a concurrency of 1 is limiting the number of possible in-flight requests: see [here](https://github.com/triton-inference-server/client/blob/8ecca2037a7c6791d4203bbc99afc138d6e28af2/src/python/library/tritonclient/http/_client.py#L1490-L1497). Can you try increasing your concurrency parameter and seeing if it resolves the issue?

Are you saying that this **concurrency** parameter is intended for the server, not the client?

**Comment by wxthu** [comment]
> Hello @wxthu, thank you for reporting an issue.
> 
> I took a look at your source files and am wondering if your bottleneck is a result of [setting your `concurrency` parameter for your client to 1](https://github.com/wxthu/debug_triton_server/blob/01294583db3652b1d923b347246a06ff6251417b/my_custom_http_async_infer_client.py#L83C55-L83C80). I believe setting a concurrency of 1 is limiting the number of possible in-flight requests: see [here](https://github.com/triton-inference-server/client/blob/8ecca2037a7c6791d4203bbc99afc138d6e28af2/src/python/library/tritonclient/http/_client.py#L1490-L1497). Can you try increasing your concurrency parameter and seeing if it resolves the issue?

It really works but there is still long stuck ... I donot understand @fpetrini15

**Comment by fpetrini15** [comment]
[Context for the concurrency parameter](https://github.com/geventhttpclient/geventhttpclient#high-concurrency). What is your current value for concurrency? The description I linked states that if the number of in-flight requests exceeds your value of concurrency, the server will block. Your screenshot makes it seem like you set the concurrency equal to 2.

Since this is an optimization issue, it may also be worthwhile to check out our [optimizations page](https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/user_guide/optimization.html) and run your configuration through our [model analyzer](https://github.com/triton-inference-server/model_analyzer).

**Comment by wxthu** [comment]
Maybe I misunderstood the meaning of **_concurrency_**, I originally thought this parameter was related to the model, indicating the number of requests for this model that the server receives simultaneously. But it is not?

**Comment by wxthu** [comment]
However, no matter how I adjust this parameter **_concurrency_**, there always seems to be a mysterious stuck during the inference process, as if it's waiting on a semaphore.（threading communication） @fpetrini15

**Comment by fpetrini15** [comment]
Concurrency refers to the number of reusable connections the client establishes with the server for the purpose of executing inferences. Is it possible that these large delays are coming from your model.py? In any event, I would still recommend running your configuration through our model analyzer.

**Comment by wxthu** [comment]
Certainly, this is a reasonable modification because, as my script shows, I simply transformed the official example code into a multi-task version, so there shouldn't be major issues.

**Comment by fpetrini15** [comment]
If you modify your script to execute inferences on one of our [simple python models](https://github.com/triton-inference-server/server/tree/main/qa/python_models), do you still observe performance issues?

**Comment by wxthu** [comment]
if I execute inferences on these simple python models, no stuck happened .. @fpetrini15

**Comment by fpetrini15** [comment]
If the simple models do not get stuck, then it seems the delay is not coming from your script, but rather is coming from your model implementation. Outside of Triton, how long does it take for your model to return an inference?

**Comment by wxthu** [comment]
> If the simple models do not get stuck, then it seems the delay is not coming from your script, but rather is coming from your model implementation. Outside of Triton, how long does it take for your model to return an inference?

The pure inference time is the same as that of Trition, but no stuck

**Comment by fpetrini15** [comment]
Apologies for the late reply. I see you have taken down your test repo mentioned above, can you remind me what backend you are using?

**Comment by wxthu** [comment]
> Apologies for the late reply. I see you have taken down your test repo mentioned above, can you remind me what backend you are using?

TensorRT @fpetrini15

**Comment by fpetrini15** [comment]
cc @GuanLuo or @tanmayv25 is there something outside the bounds of this thread that I am missing that could cause the partial utilization observed above?

@wxthu Can you provide a minimum reproducible example for us to investigate?

**Comment by dyastremsky** [comment]
Closing ticket due to inactivity. If you would like to reopen it, let us know.
