### ISSUE TITLE
HTTP Load API with config passed as part of parameter fails when config contains execution env path for python backend

### ISSUE THREAD

**Issue by risheek11** [triton-inference-server/server#6271]
**Description**
While using the load API
`POST http://<host>:8000/v2/repository/models/deberta/load`
with body containing parameters with config as shown below
```{
  "parameters": {
    "config": "{
      "name": "deberta",
      "backend": "python",
      "input": [
        {
          "name": "question__2",
          "data_type": "TYPE_STRING",
          "dims": [
            -1
          ]
        },
        {
          "name": "context__3",
          "data_type": "TYPE_STRING",
          "dims": [
            -1
          ]
        }
      ],
      "output": [
        {
          "name": "output__1",
          "data_type": "TYPE_STRING",
          "dims": [
            -1
          ]
        }
      ],
      "instance_group": [
        {
          "count": 1,
          "kind": "KIND_GPU",
          "gpus": [
            1
          ]
        }
      ],
      "parameters": {
        "key": "EXECUTION_ENV_PATH",
        "value": {
          "string_value": "$$TRITON_MODEL_DIRECTORY/venk_blooom.tar.gz"
        }
      }
    }"
  }
}
```
We encounter an error
`E0906 09:39:02.018562 1 model_repository_manager.cc:1004] Poll failed for model directory 'bloom_qa': Invalid config override: (parameters[0].value): invalid value "EXECUTION_ENV_PATH" for type type.googleapis.com/inference.ModelParameter
`

**Triton Information**
tritonserver:23.02-py3 using Triton container.

**To Reproduce**
Running the docker container
`docker run --gpus=all --shm-size=2g -it -p8000:8000 -p8001:8001 -p8002:8002 -v $(pwd)/model_repository:/models nvcr.io/nvidia/tritonserver:23.02-py3 tritonserver --model-repository=/models --model-control-mode=explicit --log-verbose=3
`
Contents in model repository
```
├── bloom_qa
│   ├── 1
│   │   ├── config.json
│   │   ├── model.py
│   │   ├── pytorch_model.bin
│   │   ├── special_tokens_map.json
│   │   ├── tokenizer_config.json
│   │   ├── tokenizer.json
│   │   └── training_args.bin
│   ├── config.pbtxt
│   └── venk_blooom.tar.gz
└── deberta
    ├── 1
    │   ├── config.json
    │   ├── model.py
    │   ├── pytorch_model_16.bin
    │   ├── pytorch_model.bin
    │   ├── special_tokens_map.json
    │   ├── tokenizer_config.json
    │   ├── tokenizer.json
    │   └── training_args.bin
    ├── config.pbtxt
    └── venk_blooom.tar.gz
```
Note:  venk_blooom.tar.gz is our custom execution env, created using conda pack.

The config.pbtxt is similar to the config mentioned in the above request body.

model.py for the deberta model
```
import json
import logging

import numpy as np
import torch
import os
import triton_python_backend_utils as pb_utils
from transformers import AutoTokenizer, AutoModelForQuestionAnswering

logger = logging.getLogger("tensor_model")


class TritonPythonModel:

    def initialize(self, args):

        model_config = json.loads(args["model_config"])
        output1_config = pb_utils.get_output_config_by_name(model_config, "output__1")

        os.environ['CUDA_VISIBLE_DEVICES'] = str(json.loads(args['model_instance_device_id']))

        # Convert Triton types to numpy types
        self.output1_dtype = pb_utils.triton_string_to_numpy(
            output1_config["data_type"]
        )

        # Load tokenizer
        path: str = os.path.join(args["model_repository"], args["model_version"])
        self.tokenizer = AutoTokenizer.from_pretrained(path)

        # Load Model
        self.model = AutoModelForQuestionAnswering.from_pretrained(path, load_in_8bit=True)

    def execute(self, requests):
        responses = []

        for request in requests:
            # Code commented for shortening.
            pass
        return responses

    def finalize(self):
        print("Cleaning up...")
```
**Expected behavior**
When we try to load the model specified above using the HTTP API we get the error as specified above.
Upon sending the request we expect Triton to load the model with the config passed in the POST request.

**Comment by risheek11** [comment]
Hello @fpetrini15  @Tabrizian the associated string value does resolve to the correct path.
This can be verified when I load the model through the API without passing any parameters in the request body.
In this case the model will be loaded by using the config.pbtxt in the model repository.

```
name: "deberta"
backend: "python"
input [
    {
        name: "question__2"
        data_type: TYPE_STRING
        dims: [-1]
    },
    {
        name: "context__3"
        data_type: TYPE_STRING
        dims: [-1]
    }
]
output [
    {
        name: "output__1"
        data_type: TYPE_STRING
        dims: [-1]
    }
]

parameters: {
  key: "EXECUTION_ENV_PATH",
  value: {string_value: "$$TRITON_MODEL_DIRECTORY/venk_blooom.tar.gz"}
}

instance_group [
    {
    count: 1
    kind: KIND_GPU
    gpus: [0]
    }
]

```

**Comment by Tabrizian** [comment]
This looks like a bug. I'll file a ticket for further investigation.

**Comment by Manikandan-t** [comment]
Hi @risheek11 The reason for E0906 09:39:02.018562 1 model_repository_manager.cc:1004] Poll failed for model directory 'bloom_qa': Invalid config override: (parameters[0].value): invalid value "EXECUTION_ENV_PATH" for type type.googleapis.com/inference.ModelParameter is due to the syntax for the EXECUTION_ENV_PATH differs when you specify in config.pbxt and using the config json in Triton Model Load API. It should be like this

"parameters": {
        "EXECUTION_ENV_PATH": {
            "string_value": "/data/envs/my-service/my-env.tar.gz"
        }
    }
    
    
![Screenshot from 2024-01-23 13-46-11](https://github.com/triton-inference-server/server/assets/82821281/0e227d45-9e23-4291-be42-4ddc5af4358d)

**Comment by dyastremsky** [comment]
Thank you for providing a fix, Manikandan!

Risheek, please let us know if that does not resolve the issue you are seeing.
