### ISSUE TITLE
onnxruntime-gpu doesnt work with CUDA-12 and triton defaults to using CPUExecutionProvider

### ISSUE THREAD

**Issue by amey-matroid** [triton-inference-server/server#6272]
**Description**
I recently made a switch to 2.36.0 from 2.21.0 and noticed that some of my models have slowed down noticeably. I ran perf analyzer on the models in the 2 different versions and noticed that the newer version is able to atleast be on par with the previous version and sometimes does even better. 

Is there any change in the default config over the last couple of iterations that might be slowing down the inference in real time utilization.

**Triton Information**
What version of Triton are you using? 2.36.0

Are you using the Triton container or did you build it yourself? Built it myself

**To Reproduce**

**Expected behavior**
Expect the model to perform as well or better than before

**Comment by fpetrini15** [comment]
Hello @amey-matroid, thank you for submitting an issue.

That is a significant version upgrade, so many changes have been made Triton since 2.21.0, but none that should negatively impact performance. Can you share more details such as your model config, the statistics you collected, and steps to reproduce your experiments?

**Comment by amey-matroid** [comment]
I narrowed it down further to this [issue](https://github.com/microsoft/onnxruntime/issues/11092). My model uses onnxruntime but fails to use the CUDAExecutionProvider. I am using CUDA 12 (upgrading from CUDA 11.6) The issue doesnt seem to concretely describe the best way to proceed. Do you have any recommendations?

**Comment by SunnyGhj** [comment]
I have the same question

**Comment by fpetrini15** [comment]
Seems like many threads have been opened regarding a compatibility issue between ORT and CUDA 12 that are currently being worked on. The ORT team would have more information in this regard. In the meantime, is possible to install a version of CUDA < 12 or use Triton v2.35.0?

**Comment by amey-matroid** [comment]
Yup, ORT does not support `CUDA-12` natively. I solved the issue my building a wheel from source. Its a few extra steps but works with triton `2.36.0` (to be more accurate, works with `CUDA-12`).

Adding the steps here for anybody else having the same issue:
```
git clone --recursive https://github.com/Microsoft/onnxruntime
cd onnxruntime
./build.sh --config RelWithDebInfo --build_wheel --use_cuda --parallel --allow_running_as_root --skip_tests
```
This will generate a wheel which can be installed using pip - `python3 -m pip install *.whl`. I skipped the tests because they needed some more dependencies which are not necessary if all you care about is getting a working `onnxruntime-gpu`.

**Comment by amey-matroid** [comment]
Closing the issue as this is not necessary a triton issue but would be helpful if this can be documented somewhere in the official documention.

**Comment by taotao707** [comment]
A wonderful answer

**Comment by Dinxin** [comment]
@amey-matroid How can I find the generated .whl file?

**Comment by amey-matroid** [comment]
> @amey-matroid How can I find the generated .whl file?

If you follow the steps mentioned in https://github.com/triton-inference-server/server/issues/6272#issuecomment-1716898068, it will generate the `.whl` file in your directory. You can then install it using `pip` as mentioned in the same comment.
