### ISSUE TITLE
Dynamic Batching Deployment with non-batched input data

### ISSUE THREAD

**Issue by sarperkilic** [triton-inference-server/server#6288]
**Description**

Hi,

I am deploying my model with dynamic batching feature.
My config file is as below:

```

name: "model_1"
backend: "python"
max_batch_size : 512

input [
  {
    name: "input_1"  
    data_type: TYPE_FP32
    dims: [3, 256, 256 ]
  },
  {
    name: "input_2"
    data_type: TYPE_INT64
    dims: [ 4 ]
  },

]

output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [3, 1110, 1920]  
  }
]

instance_group [
    {
      count: 1
      kind: KIND_GPU
    }
  ]

dynamic_batching {
}
```

My problem is:

input_1 is batched data, data shape is like
[25, 3, 256, 256]

but input_2 is non_batched data, data shape is 
[4]

I cannot send an inference request without batching input_2 data to the same batch size as input_1.
For example, if my batch size is set to 25, I have to apply the below operations on input_2 to send an inference request, 

input_2= input_2[np.newaxis]
input_2= np.repeat(input_2, 25, axis=0)  

How can I send inference request to the server without batching input data?

Thanks.

**Comment by oandreeva-nv** [comment]
I am not sure if this is possible without the aforementioned transformations. Maybe @Tabrizian can provide more information.

**Comment by Tabrizian** [comment]
It is not possible to combine batch and non-batched data together. Please take a look at the ragged batching documentation to see if it could be useful for your use-case:

https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/user_guide/ragged_batching.html
