### ISSUE TITLE
Custom GPU Temperature Metric

### ISSUE THREAD

**Issue by fzehracetin** [triton-inference-server/server#6300]
Hello,

We want to monitor `GPU Temperature` metric for our Triton Server. I wonder if there is any custom GPU metric implementation that we can check out or any ideas how we can collect this metric. 

Triton Server Version: 23.08

Thanks

**Comment by oandreeva-nv** [comment]
I believe Triton currently does not collect this metric. In regards to custom metrics, Triton [exposes](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/metrics.md#custom-metrics) a C API to allow users and backends to register and collect custom metrics with the existing Triton metrics endpoint. However, these metrics will be associated with a model. I think that GPU Temperature is not exactly `per model` metric and it is better to monitor it separately to avoid any impact on latency and throughput of your model. 

Triton collects GPU metrics through the use of [DCGM](https://developer.nvidia.com/dcgm). Here is a blog post on [Monitoring GPUs in Kubernetes with DCGM](https://developer.nvidia.com/blog/monitoring-gpus-in-kubernetes-with-dcgm/), hopefully this can help you.
