### ISSUE TITLE
Failed to initialize Python stub for auto-complete: ModuleNotFoundError: No module named 'onnxruntime' with conda environment in Triton r22.12

### ISSUE THREAD

**Issue by jFkd1** [triton-inference-server/server#6302]
**Description**
I have a model that requires Cuda=11.8, python >= 3.9, and onnxruntime=1.15.1. However, onnxruntime does not work with Cuda 12 that's shipped with triton image r23.08, and r22.12 has python=3.8 which is too low. 

I have tried using a custom python execution environment with conda python=3.10 for r22.12, created with conda pack. For some reason, I am getting a "module not found" error when running the server with the conda environment. 

**Triton Information**
What version of Triton are you using?
r22.12. 

Are you using the Triton container or did you build it yourself?
I used `nvidia-docker run nvcr.io/nvidia/tritonserver:22.12-py3` and ran `tritonserver` within the container.

**To Reproduce**
Steps to reproduce the behavior.
1. Create any conda environment with python=3.10: `conda create -n myenv python=3.10`
2. Run `export PYTHONNOUSERSITE=True`
3. Install requirements.txt with pip install:
```
--extra-index-url https://download.pytorch.org/whl/cu118

gfpgan==1.3.8
gradio==3.40.1
insightface==0.7.3
numpy==1.24.3
onnx==1.14.0
onnxruntime==1.15.1
onnxruntime-gpu==1.15.1
opencv-python==4.8.0.74
pillow==10.0.0
protobuf==4.23.4
psutil==5.9.5
realesrgan==0.3.0
tensorflow==2.13.0
tqdm==4.65.0
conda-pack
```
4. conda pack this environment and put it in the model folder. 
5. Run docker and start the server r22.12. 
6. Encounter said error.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
Model config.pbtxt:

```
name: "model_a"
backend: "python"

input [
  {
    name: "source_image_path"
    data_type: TYPE_STRING
    dims: [ -1 ]
  },
  {
    name: "target_image_path"
    data_type: TYPE_STRING
    dims: [ -1 ]
  },
  {
    name: "output_image_path"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]

output [
  {
    name: "output_image"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]

parameters: { 
  key: "EXECUTION_ENV_PATH", 
  value: {string_value: "/path/to/myenv.tar.gz"}
}
```

**Expected behavior**
Server starts without error.

**Comment by jFkd1** [comment]
I tried building a custom python backend with r23.08, but I am getting this error: 

```
python_backend/src/pb_memory.cc:324:27: error: ‘CU_POINTER_ATTRIBUTE_RANGE_START_ADDR’ was not declared in this scope  
           &start_address, CU_POINTER_ATTRIBUTE_RANGE_START_ADDR,                                                                                                                     │
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                      │
python_backend/src/pb_memory.cc:324:27: note: suggested alternative: ‘CU_POINTER_ATTRIBUTE_BUFFER_ID’                                         │
           &start_address, CU_POINTER_ATTRIBUTE_RANGE_START_ADDR,                                                                                                                     │
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                      │
                           CU_POINTER_ATTRIBUTE_BUFFER_ID                                                                                                                             │
CMakeFiles/triton-python-backend.dir/build.make:285: recipe for target 'CMakeFiles/triton-python-backend.dir/src/pb_memory.cc.o' failed                                               │
make[2]: *** [CMakeFiles/triton-python-backend.dir/src/pb_memory.cc.o] Error 1                                                                                                        │
CMakeFiles/Makefile2:334: recipe for target 'CMakeFiles/triton-python-backend.dir/all' failed                                                                                         │
make[1]: *** [CMakeFiles/triton-python-backend.dir/all] Error 2                                                                                                                       │
Makefile:135: recipe for target 'all' failed                                                                                                                                          │
make: *** [all] Error 2
```

**Comment by oandreeva-nv** [comment]
Could you please provide your steps for building custom python backend? Meanwhile, maybe @Tabrizian can provide some guidance.

**Comment by jFkd1** [comment]
hi @oandreeva-nv, of course please see the steps below: 

I pretty much followed the instructions here: https://github.com/triton-inference-server/python_backend#building-from-source. 

1. I intended to create a python backend with version 3.10, so I`git clone https://github.com/triton-inference-server/python_backend -b r23.08`
2. ran 
```
mkdir build
cd build
cmake -DTRITON_ENABLE_GPU=ON -DTRITON_BACKEND_REPO_TAG=r23.08 -DTRITON_COMMON_REPO_TAG=r23.08 -DTRITON_CORE_REPO_TAG=r23.08 -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/install ..
make install
```

And during make install, I encountered the error mentioned in https://github.com/triton-inference-server/server/issues/6302#issuecomment-1716604976.

**Comment by Tabrizian** [comment]
@jFkd1 For the build error, what is the environment that you're trying to build in? I suggest using the Triton published container to make sure that you have all the dependencies required. Also, if the issue is only with ORT, you could just create a Python environment without compiling a separate stub process. In the conda environment you can install the CUDA version that's required by ORT using `conda`.

**Comment by jFkd1** [comment]
@Tabrizian the python stub is just built with ubuntu 22.04 LTS with CUDA 11.7. 

I have tried using a custom conda environment with the right CUDA version, but it looks like the issue is with the cudnn version. Is there a way to solve the issue without having to rebuild cudnn or ORT?

**Comment by Tabrizian** [comment]
> I have tried using a custom conda environment with the right CUDA version, but it looks like the issue is with the cudnn version. Is there a way to solve the issue without having to rebuild cudnn or ORT?

Can you share the error that you run into when trying the custom conda env? Note that in your conda env you need to install the CUDA from conda-forge that satisfies the ORT requirements and make sure that ORT is able to operate in that conda env.

**Comment by dyastremsky** [comment]
Closing ticket due to inactivity. If you would like to reopen it, let us know.
