### ISSUE TITLE
wsl2 or native Linux?

### ISSUE THREAD

**Issue by nyck33** [triton-inference-server/server#6310]
I posted here too: https://github.com/nv-morpheus/Morpheus/issues/1194 but can you be clear whether it's easiest to use Native Linux or if WSL2 will suffice?  Many people use WSL2 now but I find that I'm having to go back to dual boot because at least for Cuda programming, not everything was supported in WSL2.

**Comment by oandreeva-nv** [comment]
Hi @nyck33, I would recommend to pick based on your current needs. Some Triton's features are currently not supported on Windows, for example tracing with OpenTelemetry. In terms of `easiest`, you can easily `pull` our Linux based containers from [NGC](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/tritonserver). Please, keep in mind we also provide steps on how to [build Triton on Windows](https://github.com/triton-inference-server/server/blob/main/docs/customization_guide/build.md#windows-and-docker) using docker container as well.

**Comment by nyck33** [comment]
@oandreeva-nv I pulled down a Triton container and ran some Morpheus examples but they seemed to be pulling in data from sources which were prepared demo data files, not using any telemetry to write to those first?  Even the Dfp example required running a script to get the duo and azure jsons.  Are there versions of containers that have telemetry collecting scripts that run on say any system in which I run that version of the Triton container?  I'd imagine in this scenario that there would be some command line arguments that would have passed to either run the telemetry collecting script or not.

**Comment by oandreeva-nv** [comment]
Hi @nyck33, I am unfamiliar with Morpheus, unfortunately, but if you would like to enable tracing, please refer to the documentation for [traces](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/trace.md#triton-server-trace) and for [metrics](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/metrics.md#metrics).
