### ISSUE TITLE
Does triton support model_warmup for ensemble?

### ISSUE THREAD

**Issue by l4zyf9x** [triton-inference-server/server#6326]
I am in a situation where I have a lot of sub-model. Each model needs to warm up on variants of length input like 128, 256, 384, 512,... So, I came up with the idea warm-up ensemble once instead of adding a warm-up code for each sub-model.
But when I added warm-up code for ensemble and started the triton container I got those message errors:

```
I0919 08:38:34.326394 2748084 pinned_memory_manager.cc:240] Pinned memory pool is created at '0x7ff8f6000000' with size 268435456
I0919 08:38:34.326856 2748084 cuda_memory_manager.cc:105] CUDA memory pool is created on device 0 with size 67108864
E0919 08:38:34.331212 2748084 model_repository_manager.cc:1002] Poll failed for model directory 'full_pipeline': model_warmup can not be specified for ensemble 'full_pipeline'
I0919 08:38:34.332918 2748084 model_lifecycle.cc:459] loading: model_1:1
I0919 08:38:34.332964 2748084 model_lifecycle.cc:459] loading: model_2:1
I0919 08:38:34.332995 2748084 model_lifecycle.cc:459] loading: model_3:1
I0919 08:38:34.333026 2748084 model_lifecycle.cc:459] loading: model_4:1
I0919 08:38:34.333080 2748084 model_lifecycle.cc:459] loading: model_5:1
...
```

I guess `model_warmup can not be specified for ensemble` means model_warmup is not an option for ensemble. Do you guys have a plan to support this?

I could still stay at the option of adding a warm-up code for each model. But it is really frustrating when there is a change in the input shape, and I have to create a warm-up parameter again for each module instead of creating only one for ensemble pipeline.

**Comment by oandreeva-nv** [comment]
I believe warm up is not supported for ensembles at the moment (cc @GuanLuo will correct me if I am wrong).
Feel free to file a feature request, if this is something you would like Triton to have.

**Comment by SangbumChoi** [comment]
@oandreeva-nv is there any plan to make this ensemble warmup function?

**Comment by oandreeva-nv** [comment]
@SangbumChoi , may I ask you to file a feature request, if this is something you would like Triton to have.
