### ISSUE TITLE
How to compute the completed requests within a time interval when using httpclient.async_infer ?

### ISSUE THREAD

**Issue by monsterlyg** [triton-inference-server/server#6328]
I need to know how many requests can be processed per second. And I want to keep a stable request rate. So I meant to use httpclient.async_infer, the requests are processed asynchronously. But how can I know how many requests are indeedy inferred with a time interval ?

**Comment by oandreeva-nv** [comment]
I would suggest to explore [Perfomance Analyzer](https://github.com/triton-inference-server/client/blob/main/src/c++/perf_analyzer/README.md#triton-performance-analyzer) : [Quick Start](https://github.com/triton-inference-server/client/blob/main/src/c%2B%2B/perf_analyzer/docs/quick_start.md)
