### ISSUE TITLE
Triton server unloads model automatically after the model is loaded successfully

### ISSUE THREAD

**Issue by MarouaneMja** [triton-inference-server/server#6329]
**Description**
The triton server unloaded all my models automatically after I started triton inference server in container.
Normal condition after starting the server
![image](https://github.com/triton-inference-server/server/assets/59453891/829aab97-d10a-4334-932e-2652c66fa75f)

**Triton Information**
triton 2.15.0
Nvidia driver 470.199.02

Are you using the Triton container or did you build it yourself?
I am using triton container

**To Reproduce**
The model is a yolov7-seg, sorry I can't share specification about the model. I am using a onnx backend. 

**Expected behavior**
Trion should not unload the model after the model is loaded successfully.

**Comment by oandreeva-nv** [comment]
Hi @MarouaneMja , v 2.15.0 is quite old. May I ask you to try one of the recent releases, e.g. 23.08 ([v2.37.0](https://github.com/triton-inference-server/server/tree/v2.37.0)?

**Comment by MarouaneMja** [comment]
Hi @oandreeva-nv , thank you for your response, I found a workaround for this problem. For now, I will close this comment.
