### ISSUE TITLE
Example ensemble models cannot get loaded

### ISSUE THREAD

**Issue by vadimkantorov** [triton-inference-server/server#6338]
I have a slightly modified example ensemble model:

`models/pipeline/config.pbtxt`:
```pbtxt
name: "pipeline"
max_batch_size: 0
platform: "ensemble"

input [
  {
    name: "pipeline_input"
    data_type: TYPE_UINT8
    dims: [ -1 ]
  }
]

output [
  {
    name: "pipeline_output"
    data_type: TYPE_UINT8
    dims: [ -1 ]
  }
]

ensemble_scheduling {
  step [
    {
      model_name: "modelA"
      model_version: -1
      input_map {
        key: "INPUT0"
        value: "pipeline_input"
      }
      output_map {
        key: "OUTPUT0"
        value: "modelA_output"
      }
    },
    {
      model_name: "modelB"
      model_version: -1
      input_map {
        key: "INPUT0"
        value: "modelA_output"
      }
      output_map {
        key: "OUTPUT0"
        value: "pipeline_output"
      }
    }
  ]
}
```

and an empty dir `models/pipeline/1/`

I'm getting an error `E0921 00:26:07.620347 12886 model_repository_manager.cc:1307] Poll failed for model directory 'pipeline': unexpected platform type 'ensemble' for pipeline` which further triggers server termination

I have a custom-built `tritonserver`, not sure if this is related

**Comment by vadimkantorov** [comment]
So I had to add `--extra-core-cmake-arg=TRITON_ENABLE_ENSEMBLE=ON` to the compilation command. It's a bit strange that `ensemble` building isn't available as a `build.py` frontend switch

**Comment by dyastremsky** [comment]
Thank you for finding and sharing the solution, Vadim! I think the frontend is the same as other backends, you can add the flag --backend=ensemble. See the [documentation here](https://github.com/triton-inference-server/server/blob/main/docs/customization_guide/build.md#build-triton-server) for more details.

**Comment by vadimkantorov** [comment]
So in practice, one would need both `--backend=python --backend=ensemble` during the build

**Comment by dyastremsky** [comment]
Yes, exactly. Assuming your ensemble model uses Python models, you will need both flags.
