### ISSUE TITLE
Found a possible security concern

### ISSUE THREAD

**Issue by psmoros** [triton-inference-server/server#6342]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@l1k3beef) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by dyastremsky** [comment]
Thank you for your suggestion, Pavlos! We have added a [security policy](https://github.com/triton-inference-server/server/security/policy). Please feel free to share the potential issue via the channels outlined there.
