### ISSUE TITLE
Why tutorials/Quick_Deploy/vLLM the vllm_output.outputs text result always has "b'"？

### ISSUE THREAD

**Issue by activezhao** [triton-inference-server/server#6354]
I use the README.md below to deploy a vLLM model in Triton.
`https://github.com/triton-inference-server/tutorials/blob/main/Quick_Deploy/vLLM/README.md`

I use "model.py" to test, however, I found that every time the result returned contains b'. 
`https://github.com/triton-inference-server/tutorials/blob/main/Quick_Deploy/vLLM/model_repository/vllm/1/model.py`

vllm_output.outputs: [CompletionOutput(index=0, text="\n    b'    for i = 1 to length(arr) -", token_ids=[13, 1678, 289, 29915, 1678, 363, 474, 353, 29871, 29896, 304, 3309, 29898, 2749, 29897, 448], cumulative_logprob=-0.2058177888393402, logprobs={}, finish_reason=length)]

In fact, I want to get the pure string result, what should I do? Thank you.

**Comment by dyastremsky** [comment]
If the b'<text>' is what you need to get rid of, you can modify model.py [after this line](https://github.com/triton-inference-server/tutorials/blob/main/Quick_Deploy/vLLM/model_repository/vllm/1/model.py#L144-L146) to truncate the string to only the parts you want, e.g. remove the first 2 characters and last character from the prompt.

I'd have to look at the code closely, but I'd guess there is some bytes conversion happening that's responsible for prepending and appending those characters. You can manipulate the response string to only have the text you want at that line.

**Comment by activezhao** [comment]
> If the b'' is what you need to get rid of, you can modify model.py [after this line](https://github.com/triton-inference-server/tutorials/blob/main/Quick_Deploy/vLLM/model_repository/vllm/1/model.py#L144-L146) to truncate the string to only the parts you want, e.g. remove the first 2 characters and last character from the prompt.
> 
> I'd have to look at the code closely, but I'd guess there is some bytes conversion happening that's responsible for prepending and appending those characters. You can manipulate the response string to only have the text you want at that line.

@dyastremsky OK, thank u, I have cut the text to avoid the b', and I also think it is caused by byte conversion.

**Comment by dyastremsky** [comment]
Fantastic! We also just pushed a pull request to fix this issue: https://github.com/triton-inference-server/tutorials/pull/57. You should see a regular string when using the tutorial from the main branch.

**Comment by activezhao** [comment]
> Fantastic! We also just pushed a pull request to fix this issue: [triton-inference-server/tutorials#57](https://github.com/triton-inference-server/tutorials/pull/57). You should see a regular string when using the tutorial from the main branch.

@dyastremsky Cool, I will just try it, thanks.
