### ISSUE TITLE
 use a docker image to build triton without container?

### ISSUE THREAD

**Issue by LuLu2kANG** [triton-inference-server/server#6356]
**Description**

pull r23.09

build with --no-container-build

got error: 

manifest for nvcr.io/nvidia/tritonserver:23.09-py3-min not found: manifest unknown: manifest unknown
CMakeFiles/ort_target.dir/build.make:72: recipe for target 'onnxruntime/lib/libonnxruntime.so' failed

what ???

**Comment by dyastremsky** [comment]
Quoting Tanmay: "It can get little confusing. --no-container-build would mean triton is not built over docker container. The individual backends(like onnxruntime backend in this case), however are not invoked by that setting."

More information here: https://github.com/triton-inference-server/server/issues/4742#issuecomment-1206742282
