### ISSUE TITLE
How to forcefully evict a slot in a stateful backend 

### ISSUE THREAD

**Issue by eunbin079** [triton-inference-server/server#6374]
### env
- r.22.12 version python backend
- stateful model
- grpc streaming protocol between client and server

### question
I want to know How to forcefully evict a slot in a stateful backend 

I know that following two situations, the slot identified by sequence_id in the statful model is cleared.
- request does not come for more than `max_sequence_idle_microseconds`
- request's `sequence_end == true`

In my case, **I need to set `max_sequence_idle_microseconds` for several hours.**
In this case, if the client dies abnormally for some reason (ex. power off), the triton model will not be able to use slot before old request (client already died) complete or `max_sequence_idle_microseconds` exceed (several hours)

**So I wonder if the following methods are possible.**
- a way to empty all the slots from the outside when the client dies abnormally. (Even if don't know the sequence_id)
- custom slot queue use LRU algorithm(when new request comming, clear old request even if `sequence_end = true` is not recieved).
- triton notice client connection closed and clear slot... 

thank you

**Comment by tanmayv25** [comment]
@eunbin079 We have added handling [request cancellation](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/request_cancellation.md#request-cancellation) in Triton recently. The feature should be available in our 23.10 release.
With these changes, if a gRPC client exits or calls stop_stream(cancel_requests=True), the server will receive a cancellation notification and Triton will cancel the pending requests  freeing up the slot.

Please give the feature a try and let us know your feedback.
