### ISSUE TITLE
Support for float type parameter in inference requests

### ISSUE THREAD

**Issue by wemoveon2** [triton-inference-server/server#6382]
**Is your feature request related to a problem? Please describe.**

Currently, when we need to pass a float we'd have to pass it as a string or rescale it into an integer and then scale it back into a float in the model files.

**Describe the solution you'd like**

Would like for `InferParameter` to support `double_param` as a custom parameter
https://github.com/triton-inference-server/common/blob/468eb216b01b375b83590b1e206d1c8cf4160b38/protobuf/grpc_service.proto#L470-L476

**Describe alternatives you've considered**

Currently converting to a string and then converting it back before it's used, which isn't ideal.

**Additional context**

**Comment by tanmayv25** [comment]
@wemoveon2  Great catch! We will support this!

**Comment by wemoveon2** [comment]
Hey, any updates? is this feature planned for a release?

**Comment by fpetrini15** [comment]
Hello @wemoveon2, unfortunately we had to prioritize other urgent items over the last few releases. This feature is not currently planned for a release, but I hope to have an update for you soon! When I do, I'll link you to the corresponding PR.

**Comment by fpetrini15** [comment]
Hello @wemoveon2, I have merged the [PRs](https://github.com/triton-inference-server/server/pull/6755) relating to this request. Double type parameters will be supported in the 23.02 release!

**Comment by wemoveon2** [comment]
> Hello @wemoveon2, I have merged the [PRs](https://github.com/triton-inference-server/server/pull/6755) relating to this request. Double type parameters will be supported in the 23.02 release!

much appreciated, thanks for the work!
