### ISSUE TITLE
Triton C++ in Explicit Control Mode loads Pytorch Backend at start

### ISSUE THREAD

**Issue by nathanjacobiOXOS** [triton-inference-server/server#6386]
**Description**
Pytorch 1.3 backend is loaded at start regardless of settings and models in the model repository. There is no call to load Pytorch present. The only settings listed are for tensorflow2, and not even tensorflow2 backend gets loaded at startup.

```
std::vector<std::tuple<const char*, const char*, const char*>> backendConfig_ = {{"tensorflow", "version", "2"}};
```

More specifically, it gets loaded when TRITONSERVER_ServerNew is called

**Triton Information**
Triton version 2.35.0
C++ API
Custom build, using an OS image that uses JetPack 5.1.1-b56 as the base, with some other changes. CUDA 11.4 is still in use. Backends pulled from tritonserver2.35.0-jetpack5.1.2.tgz directly

**To Reproduce**
Launch a instance of the triton server using the C++ API with explicit control mode, and do not load any models. Pytorch backend will load at startup

**Expected behavior**
Not load pytorch backend without request.

**Comment by krishung5** [comment]
Hi @nathanjacobiOXOS, thanks for reporting this. There was a PyTorch bug with simultaneous loading of PyTorch and TF models, so it loaded PyTorch backend as a persistent backend before starting to load any models to avoid this issue. This change is reverted in the latest version. Please try with Triton version 2.38.0.

**Comment by nathanjacobiOXOS** [comment]
Hi @krishung5, thank you for the quick response, does 2.38.0 have a jetson jetpack support version? I have been using 2.35.0 since it is the latest release with JP5 support

**Comment by krishung5** [comment]
@nathanjacobiOXOS Unfortunately, 2.38.0 doesn't have jetpack support. If you're using custom build, you could refer to the [PR](https://github.com/triton-inference-server/core/pull/264) to see how to cooperate the changes to your build to avoid loading Pytorch Backend at start.

**Comment by nathanjacobiOXOS** [comment]
Hi @krishung5 unfortunately we're using the precompiled .so library contained in the jetpack tarball provided with the 2.35 release. Our temporary solution has been removing the pytorch backend from backend directory and avoiding using pytorch models. Closing this issue.
