### ISSUE TITLE
Using torch with tritonclient.grpc cause Exception when exiting python program

### ISSUE THREAD

**Issue by khoalu** [triton-inference-server/server#6390]
**Description**
Import torch before import `tritongrpcclient` result in Exception when exiting python program.

**Triton Information**
Docker image: nvcr.io/nvidia/tritonserver:23.08-py3

**To Reproduce**
Follow the step in [python_backend preprocessing example](https://github.com/triton-inference-server/python_backend/blob/main/examples/preprocessing/README.md).

At the final step, instead of running `client.py` inside docker, I run it using my conda environment.

Add `import torch` right before `import tritongrpcclient` in `client.py`.

Output of `client.py`:
```
{a bunch of tensor value here}
[504]
Result is class: COFFEE MUG
Exception ignored in: <function InferenceServerClient.__del__ at 0x7f2f1547e7a0>
Traceback (most recent call last):
  File "/media/ocr/external/khoala2/temp/torch2trt/env/lib/python3.10/site-packages/tritonclient/grpc/_client.py", line 238, in __del__
  File "/media/ocr/external/khoala2/temp/torch2trt/env/lib/python3.10/site-packages/tritonclient/grpc/_client.py", line 246, in close
  File "/media/ocr/external/khoala2/temp/torch2trt/env/lib/python3.10/site-packages/grpc/_channel.py", line 2102, in close
  File "/media/ocr/external/khoala2/temp/torch2trt/env/lib/python3.10/site-packages/grpc/_channel.py", line 2083, in _close
AttributeError: 'NoneType' object has no attribute 'StatusCode'
```

Change all instances of `tritongrpcclient` to `tritonclient.grpc` causes the same error.
Change all instances of `tritongrpcclient` to `tritonclient.http` and the "Exception ignored ... " part goes away.

**Expected behavior**

No exception should be made when using tritonclient.grpc.

**Additional Information**
Related python packages:
```
triton==2.0.0
tritonclient==2.38.0.69485441
grpcio==1.59.0
torch==2.0.1
```

**Comment by GuanLuo** [comment]
@jbkyang-nvi ^^^

**Comment by jbkyang-nvi** [comment]
Hi @khoalu,  can you try with 23.09 and if that doesn't work, send me instructions of how you are producing your conda environment? Its working for me in my conda environment with python3.10

**Comment by khoalu** [comment]
Thank you for the advice. I will try and report back asap.

**Comment by khoalu** [comment]
The problem is in my conda environment

My current environment does not work for both 23.08 and 23.09

I create a new conda environment with
```
conda create --name new_env python=3.10
conda activate new_env
pip install tritonclient[all]
pip install torch
```

And it works fine for both 23.08 and 23.09

**Comment by ZJU-lishuang** [comment]
I have the same problem.
torch 2.* lead to the problem.
torch 1.12.0 is no problem.

**Comment by DZADSL72-00558** [comment]
same here... Not able to resovle
