### ISSUE TITLE
How to write a config file for my ensemble model?

### ISSUE THREAD

**Issue by Le-Bao-181003** [triton-inference-server/server#6391]
I'm using two models, a classifier and a segmentation model, for ship detection. Currently, the input image is passed through the classifier model, and then I receive two results: a positive number for images with ships and a negative number for images without ships. Here, I only want the images that return positive results to go through the segmentation model.

So, with this requirement, can I write a config file or should I use a different platform for inference and serving the model with these specifications?

If someone knows of a platform, please suggest it to me!

Thanks!

**Comment by GuanLuo** [comment]
Ensemble doesn't support selection logic. You may use [business logic scripting](https://github.com/triton-inference-server/python_backend#business-logic-scripting) from Triton Python backend to implement your specific data workflow.
