### ISSUE TITLE
build triton-server r22.12 without docker error in found Protobuf

### ISSUE THREAD

**Issue by veridone** [triton-inference-server/server#6393]
**Description**
I use `./build.py -v --no-container-build --build-dir=`pwd`/build --enable-all` or cmake comes the error
`
CMake Error at /ssd1/github/server1/build/_deps/repo-core-build/triton-core/_deps/repo-common-src/protobuf/CMakeLists.txt:30 (find_package):
  Could not find a package configuration file provided by "Protobuf" with any
  of the following names:

    ProtobufConfig.cmake
    protobuf-config.cmake

  Add the installation prefix of "Protobuf" to CMAKE_PREFIX_PATH or set
  "Protobuf_DIR" to a directory containing one of the above files.  If
  "Protobuf" provides a separate development package or SDK, be sure it has
  been installed.
`
**Triton Information**
Triton r22.12
build Triton without container in Centos7

**Comment by mokeyish** [comment]
I also build failed.
https://github.com/triton-inference-server/server/issues/5594

**Comment by dyastremsky** [comment]
Unfortunately, we do not officially support Centos7, so we do not build or test with it. If you can run an official Linux Docker container, that may be easier.

If you would like support for Debian 11, please start a discussion in the Discussions tab and you may get support from other users of Debian 11.

**Comment by ZhouMengLei1999** [comment]
I encountered the same problem as you, but found out the cause of the problem. It was because Triton server was getting third_party/protobuf with a lib library path of build/hird-party/protobuf/lib64, while Triton core wrote the PATH as build/hird-party/protobuf/lib in its CMakeLists.txt. Therefore, I solved this problem by copying lib64 to lib

**Comment by ZhouMengLei1999** [comment]
@mokeyish @veridone @dyastremsky You can refer to my answer above :)
