### ISSUE TITLE
How to get the time each inference of server cost?

### ISSUE THREAD

**Issue by tengerye** [triton-inference-server/server#6414]
Hi, I would like to measure the time of server cost for each request, transmitting time exclusively because the input has very different sizes. Does triton has such feature?

**Comment by tanmayv25** [comment]
Please take a look at our tracing tool [here](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/trace.md).
Additionally, we added [opentelemetry](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/trace.md#opentelemetry-trace-support) support here.
