### ISSUE TITLE
Triton Server Does Not Display Loaded Models in Model Status Table

### ISSUE THREAD

**Issue by helloxjade** [triton-inference-server/server#6418]
**Description**
I am using Triton Server, and I am trying to load a model named "text_detection." I have confirmed that the model has been successfully loaded in the following ways:

Retrieving model index information using the following command:

`curl -X POST  http://ip:8000/v2/repository/index
[{"name":"densenet_onnx"},{"name":"my_model"},{"name":"text_detection","version":"1","state":"READY"},{"name":"text_recognition"}]`
In the response, I see relevant information about the "text_detection" model, including its status as "READY."

I can confirm that the model has been loaded based on the logs, where I see relevant log messages indicating that the model has been loaded. However, the model status table displayed in the logs does not show any information about the loaded models.

`I1012 01:17:48.317907 1 grpc_server.cc:2451] Started GRPCInferenceService at 0.0.0.0:8001
I1012 01:17:48.318179 1 http_server.cc:3558] Started HTTPService at 0.0.0.0:8000
I1012 01:17:48.359879 1 http_server.cc:187] Started Metrics Service at 0.0.0.0:8002
I1012 01:26:44.159169 1 model_lifecycle.cc:462] loading: text_detection:1
I1012 01:26:44.163014 1 onnxruntime.cc:2514] TRITONBACKEND_Initialize: onnxruntime
I1012 01:26:44.163066 1 onnxruntime.cc:2524] Triton TRITONBACKEND API version: 1.15
I1012 01:26:44.163086 1 onnxruntime.cc:2530] 'onnxruntime' TRITONBACKEND API version: 1.15
I1012 01:26:44.163114 1 onnxruntime.cc:2560] backend configuration:
{"cmdline":{"auto-complete-config":"true","backend-directory":"/opt/tritonserver/backends","min-compute-capability":"6.000000","default-max-batch-size":"4"}}
I1012 01:26:44.206889 1 onnxruntime.cc:2625] TRITONBACKEND_ModelInitialize: text_detection (version 1)
I1012 01:26:44.208228 1 onnxruntime.cc:692] skipping model configuration auto-complete for 'text_detection': inputs and outputs already specified
I1012 01:26:44.214944 1 onnxruntime.cc:2690] TRITONBACKEND_ModelInstanceInitialize: text_detection_0 (GPU device 0)
2023-10-12 01:26:44.448251633 [W:onnxruntime:, session_state.cc:1169 VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-10-12 01:26:44.448283589 [W:onnxruntime:, session_state.cc:1171 VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
`
I1012 01:17:48.290943 1 server.cc:674] 
+-------+---------+--------+
| Model | Version | Status |
+-------+---------+--------+
+-------+---------+--------+

**Triton Information**

NVIDIA Release 23.08 (build 66820947)
Triton Server Version 2.37.0

using k8s  deploy 

**To Reproduce**
1、--model-control-mode=explicit
2、    curl -X POST -H "Content-Type: application/json"   -d '{"model_name": "text_detection", "model_version": "1"}'   http://ip:8000/v2/repository/models/load

**Expected behavior**
 expect Triton Server to display information about the loaded models in the model status table in the logs. Specifically, I would like to see the model "text_detection" listed in the table along with its version and status.

**Comment by tanmayv25** [comment]
The model status table is only printed once when Triton is launching. So it would only print the models that were loaded at the launch time. Since you are launching server in explicit mode, no models are loaded at the launch time hence the table is empty. 

When you issue request to load model, the model gets loaded but at this point we don't print the table on the server side as you observed. The reason behind this is that it for a system where model are frequently loaded/unloaded, this would quickly lead to a lot of server logs. Imagine 100s of models. Currently, the server does print whether the model was loaded or unloaded - just not the entire status table. The user can still query the status of the model they are interested in using the model control API. 

We may consider adding verbose logging if you can explain the use case for printing the Model Status Table with each model load/unload.

**Comment by helloxjade** [comment]
I initially assumed that all model loading successes or failures would be displayed in the model status table. So, when I didn't see it initially, I thought there might be an issue with my own model loading and unloading. If you could clarify this point in the documentation, it might save us some troubleshooting time. Of course, having it displayed in the table would also be more obvious, as logs can sometimes be harder to read.

**Comment by dyastremsky** [comment]
Thank you for the suggestion. Note that the table is itself a log. So it cannot be updated, only a new table can be printed.

Explicit mode is meant to be used as the production mode, so we really want to limit anything that affects performance there, including logging (unless verbose logging is explicitly enabled). If we eventually have a visual interface or similar, we can look into updating it via logs. Thank you again for the feedback!
