### ISSUE TITLE
Not able to use s3 model repository polling and checksum repository agent together

### ISSUE THREAD

**Issue by Vanish1011** [triton-inference-server/server#6420]
Original question completed - separate issue (https://github.com/triton-inference-server/server/issues/6346#issuecomment-1757469895) with regards to interaction between s3 model repository and checksum repository agent to be filed separately (@Vanish1011).

_Originally posted by @nnshah1 in https://github.com/triton-inference-server/server/issues/6346#issuecomment-1757708278_

**Comment by Vanish1011** [comment]
**Description**
when i was try to use s3 to poll models(doc example:simple) and using the checksum project to verify file's MD5 value, it report some wrongs. But, i was successful to use checksum project to vertiy models(doc example:simple) by the local poll way ( use docker -e  /local/path/models :  /models/) , I wonder if  can't use the checksum project simultaneously when use s3  to pull the model?  Because the models can load successfully when I do not use the checksum agent.

**Triton Information**

Triton docker mirror nvcr.io/nvidia/tritonserver:21.09-py3 

**To Reproduce**

docker run --rm -it    -p 8000:8000 -p 8001:8001 -p 8002:8002  -v ${HOME}/repoagents:/opt/tritonserver/repoagents  
-e AWS_ACCESS_KEY_ID=admin123  -e AWS_SECRET_ACCESS_KEY=admin123  nvcr.io/nvidia/tritonserver:21.09-py3 tritonserver --model-store=s3:// minio ip (s3 api)  :9000/models  --model-control-mode=poll --repository-poll-secs=3 --exit-on-error=false  


models dir include : simple model

simple tree: 
simple
├── 1
│   └── model.graphdef
├── 1.txt
└── config.pbtxt

1 directory, 3 files

This model file can be loaded locally ( when i don't use checksum repository agent ,Can also be loaded via s3)

**Expected behavior**

i want to use my custome repository agent( Now I just tested it by using checksum) when i try to poll models via s3.



**Errors report**

=============================
== Triton Inference Server ==
=============================

NVIDIA Release 21.09 (build 27443074)

Copyright (c) 2018-2021, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use Docker with NVIDIA Container Toolkit to start this container; see
   https://github.com/NVIDIA/nvidia-docker.

I1012 02:27:46.829681 1 libtorch.cc:1030] TRITONBACKEND_Initialize: pytorch
I1012 02:27:46.829803 1 libtorch.cc:1040] Triton TRITONBACKEND API version: 1.5
I1012 02:27:46.829809 1 libtorch.cc:1046] 'pytorch' TRITONBACKEND API version: 1.5
2023-10-12 02:27:46.937034: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
I1012 02:27:46.983417 1 tensorflow.cc:2170] TRITONBACKEND_Initialize: tensorflow
I1012 02:27:46.983862 1 tensorflow.cc:2180] Triton TRITONBACKEND API version: 1.5
I1012 02:27:46.983888 1 tensorflow.cc:2186] 'tensorflow' TRITONBACKEND API version: 1.5
I1012 02:27:46.983893 1 tensorflow.cc:2210] backend configuration:
{}
I1012 02:27:46.985622 1 onnxruntime.cc:1997] TRITONBACKEND_Initialize: onnxruntime
I1012 02:27:46.985896 1 onnxruntime.cc:2007] Triton TRITONBACKEND API version: 1.5
I1012 02:27:46.986183 1 onnxruntime.cc:2013] 'onnxruntime' TRITONBACKEND API version: 1.5
I1012 02:27:47.005419 1 openvino.cc:1193] TRITONBACKEND_Initialize: openvino
I1012 02:27:47.005961 1 openvino.cc:1203] Triton TRITONBACKEND API version: 1.5
I1012 02:27:47.005982 1 openvino.cc:1209] 'openvino' TRITONBACKEND API version: 1.5
W1012 02:27:47.006102 1 pinned_memory_manager.cc:236] Unable to allocate pinned system memory, pinned memory pool will not be available: CUDA driver version is insufficient for CUDA runtime version
I1012 02:27:47.006123 1 cuda_memory_manager.cc:115] CUDA memory pool disabled
E1012 02:27:47.038279 1 model_repository_manager.cc:1890] Poll failed for model directory 'simple': Unsupported filesystem: 1
I1012 02:27:47.038321 1 server.cc:519] 
+------------------+------+
| Repository Agent | Path |
+------------------+------+
+------------------+------+

I1012 02:27:47.038349 1 server.cc:546] 
+-------------+-----------------------------------------------------------------+--------+
| Backend     | Path                                                            | Config |
+-------------+-----------------------------------------------------------------+--------+
| pytorch     | /opt/tritonserver/backends/pytorch/libtriton_pytorch.so         | {}     |
| tensorflow  | /opt/tritonserver/backends/tensorflow1/libtriton_tensorflow1.so | {}     |
| onnxruntime | /opt/tritonserver/backends/onnxruntime/libtriton_onnxruntime.so | {}     |
| openvino    | /opt/tritonserver/backends/openvino/libtriton_openvino.so       | {}     |
+-------------+-----------------------------------------------------------------+--------+

I1012 02:27:47.038362 1 server.cc:589] 
+-------+---------+--------+
| Model | Version | Status |
+-------+---------+--------+
+-------+---------+--------+

I1012 02:27:47.038447 1 tritonserver.cc:1836] 
+----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
| Option                           | Value                                                                                                                                      |
+----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
| server_id                        | triton                                                                                                                                     |
| server_version                   | 2.14.0                                                                                                                                     |
| server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_policy model_configuration system_shared_memory cuda |
|                                  | _shared_memory binary_tensor_data statistics                                                                                               |
| model_repository_path[0]         | s3://172.17.0.2:9000/models                                                                                                                |
| model_control_mode               | MODE_POLL                                                                                                                                  |
| strict_model_config              | 1                                                                                                                                          |
| rate_limit                       | OFF                                                                                                                                        |
| pinned_memory_pool_byte_size     | 268435456                                                                                                                                  |
| min_supported_compute_capability | 6.0                                                                                                                                        |
| strict_readiness                 | 1                                                                                                                                          |
| exit_timeout                     | 30                                                                                                                                         |
+----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+

E1012 02:27:47.038479 1 tritonserver.cc:1845] Internal: failed to load all models
I1012 02:27:47.039579 1 grpc_server.cc:4111] Started GRPCInferenceService at 0.0.0.0:8001
I1012 02:27:47.039757 1 http_server.cc:2803] Started HTTPService at 0.0.0.0:8000
I1012 02:27:47.084134 1 http_server.cc:162] Started Metrics Service at 0.0.0.0:8002
E1012 02:27:47.111562 1 model_repository_manager.cc:1890] Poll failed for model directory 'simple': Unsupported filesystem: 1
E1012 02:27:50.153426 1 model_repository_manager.cc:1890] Poll failed for model directory 'simple': Unsupported filesystem: 1

**Comment by Vanish1011** [comment]
@nnshah1

**Comment by Vanish1011** [comment]
i found the problem is that when i add model_repository_agents param in the model_config file <config.pbtxt> ,It's going to be wrong when i try to use poll model by s3 

And error information (simple is my model file,and it worked successfully when i try to load models locally):

E1020 13:03:55.743062 1 model_repository_manager.cc:1890] Poll failed for model directory 'simple': Unsupported filesystem: 1

**Comment by Vanish1011** [comment]
plz ,help me , bro @nnshah1

**Comment by Vanish1011** [comment]
if the repository agent (repoagent) support to poll model files via s3? or just for local models ? @nnshah1

**Comment by nnshah1** [comment]
@Vanish1011 

The checksum agent only supports local files and not remote files:

https://github.com/triton-inference-server/checksum_repository_agent/blob/b3741602dfeb21ff69aff121ea8d675c2463fbe6/src/checksum.cc#L205 

This is why when you enable checksum you will get an error during the polling as polled models will be checked by repo agents.
