### ISSUE TITLE
Compress image inside Deepstream before sending it to Triton

### ISSUE THREAD

**Issue by thangdt277** [triton-inference-server/server#6446]
My problem is limited to bandwidth. So, i want to encode image like nvjpeg or turbo-jpeg  before sending it to Triton Inference Server. Main pipeline is using Deepstream to process live stream from camera. Does anyone have experience with this?

**Comment by jbkyang-nvi** [comment]
Hi, could you set up the processing in the client? Another way to do this is you can create an ensemble model that does this. This is a better question in the [discussions](https://github.com/triton-inference-server/server/discussions) and not issues category.
