### ISSUE TITLE
About use perf_analyzer

### ISSUE THREAD

**Issue by ShiMinghao0208** [triton-inference-server/server#6462]
**Description**

Triton can be use，but when I want test perf_analyzer, its reported an error
`perf_analyzer: error while loading shared libraries: libcudart.so.12: cannot open shared object file: No such file or directory`

**Triton Information**
What version of Triton are you using?
My container is _tritonserver:21.08-py3_；Cuda version is 11.4

Are you using the Triton container or did you build it yourself?
I didnt build it, just install other python dependency
**To Reproduce**
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**

**Comment by ShiMinghao0208** [comment]
Maybe the tritonclient version？I install tritonclient by pip.
 I need to install a right version of the tritonclient corresponding to cuda？

**Comment by dyastremsky** [comment]
Yes, that's correct. The easiest approach would be to use the matching sdk container e.g. 21.08-py3-sdk. You can then use that perf_analyzer to analyze your model.

I also highly recommend using a more recent container like 23.09, if you can. Your container is over two years old.

**Comment by ShiMinghao0208** [comment]
> Yes, that's correct. The easiest approach would be to use the matching sdk container e.g. 21.08-py3-sdk. You can then use that perf_analyzer to analyze your model.
> 
> I also highly recommend using a more recent container like 23.09, if you can. Your container is over two years old.

I try to use 21.08-py3-sdk,but Its mistakes are even stranger. The tritonserver command not working
![image](https://github.com/triton-inference-server/server/assets/53176521/85e28188-cc3e-468e-a12a-55550faddb79)

**Comment by ShiMinghao0208** [comment]
> Yes, that's correct. The easiest approach would be to use the matching sdk container e.g. 21.08-py3-sdk. You can then use that perf_analyzer to analyze your model.
> 
> I also highly recommend using a more recent container like 23.09, if you can. Your container is over two years old.

Include model-analyzer，I think it's the version error
![608d049907b96854ffa57f75c92eb82](https://github.com/triton-inference-server/server/assets/53176521/ab0e4f36-e8dd-438a-be47-fb9dd176501a)
then I use -v to get the log：
`tritonserver: unrecognized option '--metrics-interval-ms'
Usage: tritonserver [options]
  --help
	Print usage
  --log-verbose <integer>
	Set verbose logging level. Zero (0) disables verbose logging
	and values >= 1 enable verbose logging.
  --log-info <boolean>
	Enable/disable info-level logging.
  --log-warning <boolean>
	Enable/disable warning-level logging.
  --log-error <boolean>
	Enable/disable error-level logging.
  --id <string>
	Identifier for this server.
  --model-store <string>
	Equivalent to --model-repository.
  --model-repository <string>
	Path to model repository directory. It may be specified
	multiple times to add multiple model repositories. Note that if a model
	is not unique across all model repositories at any time, the model
	will not be available.
  --exit-on-error <boolean>
	Exit the inference server if an error occurs during
	initialization.
  --strict-model-config <boolean>
	If true model configuration files must be provided and all
	required configuration settings must be specified. If false the model
	configuration may be absent or only partially specified and the
	server will attempt to derive the missing required configuration.
  --strict-readiness <boolean>
	If true /v2/health/ready endpoint indicates ready if the
	server is responsive and all models are available. If false
	/v2/health/ready endpoint indicates ready if server is responsive even if
	some/all models are unavailable.
  --allow-http <boolean>
	Allow the server to listen for HTTP requests.
  --http-port <integer>
	The port for the server to listen on for HTTP requests.
  --http-thread-count <integer>
	Number of threads handling HTTP requests.
  --allow-grpc <boolean>
	Allow the server to listen for GRPC requests.
  --grpc-port <integer>
	The port for the server to listen on for GRPC requests.
  --grpc-infer-allocation-pool-size <integer>
	The maximum number of inference request/response objects
	that remain allocated for reuse. As long as the number of in-flight
	requests doesn't exceed this value there will be no
	allocation/deallocation of request/response objects.
  --grpc-use-ssl <boolean>
	Use SSL authentication for GRPC requests. Default is false.
  --grpc-use-ssl-mutual <boolean>
	Use mututal SSL authentication for GRPC requests. Default is
	false.
  --grpc-server-cert <string>
	File holding PEM-encoded server certificate. Ignored unless
	--grpc-use-ssl is true.
  --grpc-server-key <string>
	File holding PEM-encoded server key. Ignored unless
	--grpc-use-ssl is true.
  --grpc-root-cert <string>
	File holding PEM-encoded root certificate. Ignore unless
	--grpc-use-ssl is false.
  --grpc-infer-response-compression-level <string>
	The compression level to be used while returning the infer
	response to the peer. Allowed values are none, low, medium and high.
	By default, compression level is selected as none.
  --grpc-keepalive-time <integer>
	The period (in milliseconds) after which a keepalive ping is
	sent on the transport. Default is 7200000 (2 hours).
  --grpc-keepalive-timeout <integer>
	The period (in milliseconds) the sender of the keepalive
	ping waits for an acknowledgement. If it does not receive an
	acknowledgment within this time, it will close the connection. Default is
	20000 (20 seconds).
  --grpc-keepalive-permit-without-calls <boolean>
	Allows keepalive pings to be sent even if there are no calls
	in flight (0 : false; 1 : true). Default is 0 (false).
  --grpc-http2-max-pings-without-data <integer>
	The maximum number of pings that can be sent when there is
	no data/header frame to be sent. gRPC Core will not continue sending
	pings if we run over the limit. Setting it to 0 allows sending pings
	without such a restriction. Default is 2.
  --grpc-http2-min-recv-ping-interval-without-data <integer>
	If there are no data/header frames being sent on the
	transport, this channel argument on the server side controls the minimum
	time (in milliseconds) that gRPC Core would expect between receiving
	successive pings. If the time between successive pings is less than
	this time, then the ping will be considered a bad ping from the peer.
	Such a ping counts as a ‘ping strike’. Default is 300000 (5
	minutes).
  --grpc-http2-max-ping-strikes <integer>
	Maximum number of bad pings that the server will tolerate
	before sending an HTTP2 GOAWAY frame and closing the transport.
	Setting it to 0 allows the server to accept any number of bad pings.
	Default is 2.
  --allow-sagemaker <boolean>
	Allow the server to listen for Sagemaker requests. Default
	is false.
  --sagemaker-port <integer>
	The port for the server to listen on for Sagemaker requests.
	Default is 8080.
  --sagemaker-safe-port-range <<integer>-<integer>>
	Set the allowed port range for endpoints other than the
	SageMaker endpoints.
  --sagemaker-thread-count <integer>
	Number of threads handling Sagemaker requests. Default is 8.
  --allow-metrics <boolean>
	Allow the server to provide prometheus metrics.
  --allow-gpu-metrics <boolean>
	Allow the server to provide GPU metrics. Ignored unless
	--allow-metrics is true.
  --metrics-port <integer>
	The port reporting prometheus metrics.
  --trace-file <string>
	Set the file where trace output will be saved.
  --trace-level <string>
	Set the trace level. OFF to disable tracing, MIN for minimal
	tracing, MAX for maximal tracing. Default is OFF.
  --trace-rate <integer>
	Set the trace sampling rate. Default is 1000.
  --model-control-mode <string>
	Specify the mode for model management. Options are "none",
	"poll" and "explicit". The default is "none". For "none", the server
	will load all models in the model repository(s) at startup and will
	not make any changes to the load models after that. For "poll", the
	server will poll the model repository(s) to detect changes and will
	load/unload models based on those changes. The poll rate is
	controlled by 'repository-poll-secs'. For "explicit", model load and unload
	is initiated by using the model control APIs, and only models
	specified with --load-model will be loaded at startup.
  --repository-poll-secs <integer>
	Interval in seconds between each poll of the model
	repository to check for changes. Valid only when --model-control-mode=poll is
	specified.
  --load-model <string>
	Name of the model to be loaded on server startup. It may be
	specified multiple times to add multiple models. Note that this
	option will only take affect if --model-control-mode=explicit is true.
  --pinned-memory-pool-byte-size <integer>
	The total byte size that can be allocated as pinned system
	memory. If GPU support is enabled, the server will allocate pinned
	system memory to accelerate data transfer between host and devices
	until it exceeds the specified byte size. If 'numa-node' is configured
	via --host-policy, the pinned system memory of the pool size will be
	allocated on each numa node. This option will not affect the
	allocation conducted by the backend frameworks. Default is 256 MB.
  --cuda-memory-pool-byte-size <<integer>:<integer>>
	The total byte size that can be allocated as CUDA memory for
	the GPU device. If GPU support is enabled, the server will allocate
	CUDA memory to minimize data transfer between host and devices
	until it exceeds the specified byte size. This option will not affect
	the allocation conducted by the backend frameworks. The argument
	should be 2 integers separated by colons in the format <GPU device
	ID>:<pool byte size>. This option can be used multiple times, but only
	once per GPU device. Subsequent uses will overwrite previous uses for
	the same GPU device. Default is 64 MB.
  --min-supported-compute-capability <float>
	The minimum supported CUDA compute capability. GPUs that
	don't support this compute capability will not be used by the server.
  --exit-timeout-secs <integer>
	Timeout (in seconds) when exiting to wait for in-flight
	inferences to finish. After the timeout expires the server exits even if
	inferences are still in flight.
  --backend-directory <string>
	The global directory searched for backend shared libraries.
	Default is '/opt/tritonserver/backends'.
  --repoagent-directory <string>
	The global directory searched for repository agent shared
	libraries. Default is '/opt/tritonserver/repoagents'.
  --buffer-manager-thread-count <integer>
	The number of threads used to accelerate copies and other
	operations required to manage input and output tensor contents.
	Default is 0.
  --backend-config <<string>,<string>=<string>>
	Specify a backend-specific configuration setting. The format
	of this flag is --backend-config=<backend_name>,<setting>=<value>.
	Where <backend_name> is the name of the backend, such as 'tensorrt'.
  --host-policy <<string>,<string>=<string>>
	Specify a host policy setting associated with a policy name.
	The format of this flag is
	--host-policy=<policy_name>,<setting>=<value>.Currently supported settings are 'numa-node', 'cpu-cores'.
	Note that 'numa-node' setting will affect pinned memory pool behavior,
	see --pinned-memory-pool for more detail.
`
So I really hope can have a table of references to CUDA、model-analyzer、perf-analyzer and Triton server versions or other triton's tools. Then we can pip the  corresponding version.
And， because of my lower version of cuda driver，I cant try 23.09(I think)

**Comment by dyastremsky** [comment]
That exists. For example, for 21.08, it would be under the [21.08 release notes page.](https://docs.nvidia.com/deeplearning/triton-inference-server/release-notes/rel_21-08.html#rel_21-08)

Yeah, it looks like you're missing versions here. Hopefully, that helps. We cannot provide much support on versions beyond a certain age. It would be good to check if you can upgrade your CUDA driver so that you can try out a newer version of Triton.

**Comment by ShiMinghao0208** [comment]
> That exists. For example, for 21.08, it would be under the [21.08 release notes page.](https://docs.nvidia.com/deeplearning/triton-inference-server/release-notes/rel_21-08.html#rel_21-08)
> 
> Yeah, it looks like you're missing versions here. Hopefully, that helps. We cannot provide much support on versions a couple of years old. It would be good to check if you can upgrade your CUDA driver so that you can try out a newer version of Triton.

Emmmm,the release notes I have already seen it. I mean the tools version include model-analyzer、perf-analyzer and so on.
And the 21.08-sdk version, I try to use but it even can not recognize the tritonserver command. Can u check my error above？
I think if I know the right tool‘s version，I can install by myself，pip、tar or .whl and so on

**Comment by dyastremsky** [comment]
The versions of model analyzer and perf analyzer are the same as the server, 21.08 in your case. You cannot get them via Pip.

The sdk container only has the clients, not Triton server. You would need to start Triton server in the 21.08 container. You can use Docker's port flags (e.g. -p 8000:8000) to expose ports or use your host network (e.g. --net=host). You can do the same in your sdk container so that the client and server are able to communicate between the two containers.

Unfortunately, I'm not going to be able to help you much more than that. I think you're right that it's a version mismatch. So using the server and sdk containers of the same version should fix the issue. If it's more than that, it'd be hard to know with how the code and behavior has changed in the last two years. And if there is a bug, it was likely patched (and any new patches would only be applied to releases going forward).

**Comment by ShiMinghao0208** [comment]
> The versions of model analyzer and perf analyzer are the same as the server, 21.08 in your case. You cannot get them via Pip.
> 
> The sdk container only has the clients, not Triton server. You would need to start Triton server in the 21.08 container. You can use Docker's port flags (e.g. -p 8000:8000) to expose ports or use your host network (e.g. --net=host). You can do the same in your sdk container so that the client and server are able to communicate between the two containers.
> 
> Unfortunately, that's as far as I think we can go here. I think you're right that it's a version mismatch. So using the server and sdk containers of the same version should fix the issue. If it's more than that, it'd be hard to know with how the code and behavior has changed in the last two years. And if there is a bug, it was likely patched (and any new patches would only be applied to releases going forward).

Okay, I know it. So the preferred plan it's a 21.08 triton container for my triton server and the other one 21.08-sdk container that I can use perf-analyzer or model-analyzer?
