### ISSUE TITLE
Dynamic Batch is not working for yolov7

### ISSUE THREAD

**Issue by KaranBhuva22** [triton-inference-server/server#6498]
I have been working on deploying yolov7 in triton however even after configuring below parameters dynamic batching is not working.

> {
    "name": "yolo",
    "platform": "tensorrt_plan",
    "backend": "tensorrt",
    "max_batch_size": 4,
    "input": [
        {
            "name": "images",
            "data_type": "TYPE_FP32",
            "dims": [
                3,
                1280,
                1280
            ],
            "is_shape_tensor": false
        }
    ],
    "output": [
        {
            "name": "num_dets",
            "data_type": "TYPE_INT32",
            "dims": [
                1
            ],
            "is_shape_tensor": false
        },
        {
            "name": "det_boxes",
            "data_type": "TYPE_FP32",
            "dims": [
                500,
                4
            ],
            "is_shape_tensor": false
        },
        {
            "name": "det_scores",
            "data_type": "TYPE_FP32",
            "dims": [
                500
            ],
            "is_shape_tensor": false
        },
        {
            "name": "det_classes",
            "data_type": "TYPE_INT32",
            "dims": [
                500
            ],
            "is_shape_tensor": false
        }
    ],
    "batch_input": [],
    "batch_output": [],
    "optimization": {
        "priority": "PRIORITY_DEFAULT",
        "input_pinned_memory": {
            "enable": true
        },
        "output_pinned_memory": {
            "enable": true
        },
        "gather_kernel_buffer_threshold": 0,
        "eager_batching": false
    },
    "dynamic_batching": {
        "preferred_batch_size": [
            4
        ],
        "max_queue_delay_microseconds": 100,
        "preserve_ordering": false,
        "priority_levels": 0,
        "default_priority_level": 0,
        "priority_queue_policy": {}
    },
    "instance_group": [
        {
            "name": "yolo",
            "kind": "KIND_GPU",
            "count": 1,
            "gpus": [
                0
            ],
            "secondary_devices": [],
            "profile": [],
            "passive": false,
            "host_policy": ""
        }
    ]
}

At server side when I execute` print(client.get_inference_statistics())`, I get a batch size of 1 every time. I increased `max_queue_delay_microseconds` but batch_size remains 1 only.

I double-checked whether the model supports batching by using a static batch size of 2, and it works well!

**Comment by SeibertronSS** [comment]
I think the problem is that your max_queue_delay_microseconds is set too small. Microseconds is 10^-6 seconds.

**Comment by KaranBhuva22** [comment]
> I think the problem is that your max_queue_delay_microseconds is set too small. Microseconds is 10^-6 seconds.

I have tried that out by increasing max_queue_deplay_microseconds however i didn't see any changes. 

See below logs during inference, batch size is 1 only.

> I1031 12:43:33.914605 1 infer_request.cc:710] prepared: [0x0x7f32e00010f0] request id: , model: yolo, requested version: -1, actual version: 1, flags: 0x0, correlation id: 0, **batch size: 1**, priority: 0, timeout (us): 0
original inputs:
[0x0x7f32e0001428] input: images, type: FP32, original shape: [1,3,1280,1280], batch + shape: [1,3,1280,1280], shape: [3,1280,1280]
override inputs:
inputs:
[0x0x7f32e0001428] input: images, type: FP32, original shape: [1,3,1280,1280], batch + shape: [1,3,1280,1280], shape: [3,1280,1280]
original requested outputs:
det_boxes
det_classes
det_scores
num_dets
requested outputs:
det_boxes
det_classes
det_scores
num_dets

**Comment by SeibertronSS** [comment]
What is the value of your max_queue_delay_microseconds setting?

**Comment by KaranBhuva22** [comment]
Updated value of max_queue_delay_microseconds is 5000000.

**Comment by KaranBhuva22** [comment]
> > I think the problem is that your max_queue_delay_microseconds is set too small. Microseconds is 10^-6 seconds.
> 
> I have tried that out by increasing max_queue_deplay_microseconds however i didn't see any changes.
> 
> See below logs during inference, batch size is 1 only.
> 
> > I1031 12:43:33.914605 1 infer_request.cc:710] prepared: [0x0x7f32e00010f0] request id: , model: yolo, requested version: -1, actual version: 1, flags: 0x0, correlation id: 0, **batch size: 1**, priority: 0, timeout (us): 0
> > original inputs:
> > [0x0x7f32e0001428] input: images, type: FP32, original shape: [1,3,1280,1280], batch + shape: [1,3,1280,1280], shape: [3,1280,1280]
> > override inputs:
> > inputs:
> > [0x0x7f32e0001428] input: images, type: FP32, original shape: [1,3,1280,1280], batch + shape: [1,3,1280,1280], shape: [3,1280,1280]
> > original requested outputs:
> > det_boxes
> > det_classes
> > det_scores
> > num_dets
> > requested outputs:
> > det_boxes
> > det_classes
> > det_scores
> > num_dets

However when i check `triton_client.get_inference_statistics()`  after updating max_queue_delay_microseconds to 5000000, I can see below stats:

> model_stats {
  name: "yolo"
  version: "1"
  last_inference: 1698755743120
  inference_count: 511
  execution_count: 92
  inference_stats {
    success {
      count: 511
      ns: 1007872853826
    }
    fail {
    }
    queue {
      count: 511
      ns: 897712542265
    }
    compute_input {
      count: 511
      ns: 25522642272
    }
    compute_infer {
      count: 511
      ns: 83982725638
    }
    compute_output {
      count: 511
      ns: 47162225
    }
    cache_hit {
    }
    cache_miss {
    }
  }
  batch_stats {
    batch_size: 1
    compute_input {
      count: 10
      ns: 116854001
    }
    compute_infer {
      count: 10
      ns: 425655302
    }
    compute_output {
      count: 10
      ns: 783274
    }
  }
  batch_stats {
    batch_size: 2
    compute_input {
      count: 6
      ns: 85441348
    }
    compute_infer {
      count: 6
      ns: 329436982
    }
    compute_output {
      count: 6
      ns: 281306
    }
  }
  batch_stats {
    batch_size: 3
    compute_input {
      count: 9
      ns: 187203425
    }
    compute_infer {
      count: 9
      ns: 716602650
    }
    compute_output {
      count: 9
      ns: 1667033
    }
  }


I'm not sure if dynamic batch is working or not because I see batch sizes greater than 1 in 'triton_client.get_inference_statistics()' but only 1 in inference logs as I stated above!

**Comment by llFireHawkll** [comment]
Hi @KaranBhuva22 Did you solve this issue? Can you please help me?
