### ISSUE TITLE
How to pass int or string list parameter  use Generate Extension?

### ISSUE THREAD

**Issue by supercocoa** [triton-inference-server/server#6508]
**Description**
How to pass int or string list parameter  use Generate Extension?

**Triton Information**
What version of Triton are you using?
23.10-vllm-python-py3

Are you using the Triton container or did you build it yourself?
docker container

**To Reproduce**
Steps to reproduce the behavior.
use vllm backend  triton generate extention format for test:
``` bash
> curl -X POST localhost:8000/v2/models/vllm_model/generate -d '{"text_input": "What is triton inference server?", "parameters": {"stream": false, "temperature": "0.1", "top_p": "0.95", "max_tokens": 256, "stop_token_ids": [151643,151644,151645]}}'
> {"error":"Converting keyword: 'parameters': parameter 'stop_token_ids' has invalid type. It should be either 'int', 'bool', or 'string'."}
```

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
use vllm and qwen-7b-chat model

**Expected behavior**
success generate

**Comment by nnshah1** [comment]
Unfortunately the parameters schema only supports scaler types. However the model config also supports an optional tensor called "sampling_parameters" by which you can pass a full JSON string with the values, something like:

> curl -X POST localhost:8000/v2/models/vllm_model/generate -d '{"text_input": "What is triton inference server?", "sampling_parameters": "{\"stream\": false, \"temperature\": \"0.1\", \"top_p\": \"0.95\", \"max_tokens\": 256, \"stop_token_ids\": [151643,151644,151645]}}"

Note: my escaping may be off - but the basic idea is to embed the full sampling parameters as a JSON string within the "sampling_parameters" key

**Comment by vadimkantorov** [comment]
Btw, could anyone advice how do I enabled `generate` extension at build time? There is `--enable-logging` argument, but no `--enable-generate` for r23.12

```
 cd server && python ./build.py -v --no-container-build --enable-logging --enable-generate --enable-stats --enable-tracing --build-dir="$PWD/build" --backend python --backend=ensemble --extra-core-cmake-arg=TRITON_ENABLE_GRPC=OFF --extra-core-cmake-arg=TRITON_ENABLE_HTTP=ON  --extra-core-cmake-arg=TRITON_ENABLE_ENSEMBLE=ON
  shell: /usr/bin/bash -e {0}
usage: build.py [-h] [-q | -v] [--dryrun] [--no-container-build]
                [--no-container-interactive] [--no-container-pull]
                [--container-memory CONTAINER_MEMORY]
                [--target-platform TARGET_PLATFORM]
                [--target-machine TARGET_MACHINE] [--build-id BUILD_ID]
                [--build-sha BUILD_SHA] [--build-dir BUILD_DIR]
                [--install-dir INSTALL_DIR] [--cmake-dir CMAKE_DIR]
                [--tmp-dir TMP_DIR] [--library-paths LIBRARY_PATHS]
                [--build-type BUILD_TYPE] [-j BUILD_PARALLEL]
                [--github-organization GITHUB_ORGANIZATION]
                [--version VERSION] [--container-version CONTAINER_VERSION]
                [--upstream-container-version UPSTREAM_CONTAINER_VERSION]
                [--container-prebuild-command CONTAINER_PREBUILD_COMMAND]
                [--no-container-source] [--image IMAGE] [--enable-all]
                [--enable-logging] [--enable-stats] [--enable-metrics]
                [--enable-gpu-metrics] [--enable-cpu-metrics]
                [--enable-tracing] [--enable-nvtx] [--enable-gpu]
                [--enable-mali-gpu]
                [--min-compute-capability MIN_COMPUTE_CAPABILITY]
                [--endpoint ENDPOINT] [--filesystem FILESYSTEM]
                [--no-core-build] [--backend BACKEND] [--repo-tag REPO_TAG]
                [--repoagent REPOAGENT] [--cache CACHE] [--no-force-clone]
                [--extra-core-cmake-arg EXTRA_CORE_CMAKE_ARG]
                [--override-core-cmake-arg OVERRIDE_CORE_CMAKE_ARG]
                [--extra-backend-cmake-arg EXTRA_BACKEND_CMAKE_ARG]
                [--override-backend-cmake-arg OVERRIDE_BACKEND_CMAKE_ARG]
build.py: error: unrecognized arguments: --enable-generate
```

**Comment by dyastremsky** [comment]
Hi Vadim! Sorry for the late reply, but would you be able to open a new issue if this is still an issue? Generate might be automatically included in the build with HTTP, but if you are not finding that, then please open an issue and we can get you an answer.

Closing since the original issue was resolved.
