### ISSUE TITLE
Use multiple GPUs memory to load a large model not fit into single GPU?

### ISSUE THREAD

**Issue by pbxqdown** [triton-inference-server/server#6519]
I have a 3090(24GB memory) and a 3080(10GB memory) GPU. I'm not able to load a large model(e.g. contains 13b parameters, usually requires 26GB memory) into triton because single GPU doesn't have enough memory to hold entire model. I'm wondering whether there is a way to combine 3090 and 3080's memory so they together(24G+10G) can load the large model into memory.

Sorry if the question looks naive , still newbie to inference world😅

**Comment by dyastremsky** [comment]
Most of the backends presently handle single-GPU models. The [TRT-LLM backend](https://github.com/triton-inference-server/tensorrtllm_backend) is for the multi-GPU use case. You can find documentation for running it as well as an issues tab for TRT-LLM-specific questions in the TRT-LLM repository.

Alternatively, you can write a custom backend to load a multi-GPU model.

**Comment by pbxqdown** [comment]
@dyastremsky thanks! i‘m using vLLM-fasttransformer backend as it is out-of-the box solution. I have too few deep learning experience to customize on my own...

**Comment by dyastremsky** [comment]
Any time! That should work fine. From this [vLLM backend documentation](https://github.com/triton-inference-server/vllm_backend#using-the-vllm-backend): `For multi-GPU support, EngineArgs like tensor_parallel_size can be specified in [model.json](https://github.com/triton-inference-server/vllm_backend/blob/main/samples/model_repository/vllm_model/1/model.json).`

That approach should work. You can verify with `nvidia-smi`. If you have any issues, let us know.
