### ISSUE TITLE
Exception: expecting input to have 3 dimensions, model 'densenet_onnx' input has 4

### ISSUE THREAD

**Issue by mahesh11T** [triton-inference-server/server#6529]
python /workspace/client/src/python/examples/image_client.py  image_filename=/workspace/images/mug.jpg -m densenet_onnx -b=0 -s=INCEPTION -v

![image](https://github.com/triton-inference-server/server/assets/107621428/e83138a0-5c77-46da-b1d7-b235eed769d2)

```py
    if len(input_metadata.shape) != expected_input_dims:
        raise Exception(
            "expecting input to have {} dimensions, model '{}' input has {}".format(
                expected_input_dims, model_metadata.name, len(input_metadata.shape)
            )
        )
```
line 116 in image_client.py is expecting (3,2..x, 2.3xx) shape, but its getting (1,3,2.x,2.x) , y is this happening?

**Comment by Yobol** [comment]
Hi. You can modify 'max_batch_size param' in config.pbtxt of densenet_onnx. Default value is 0. It must be more than 0. [https://github.com/triton-inference-server/server/blob/main/docs/examples/model_repository/densenet_onnx/config.pbtxt](https://github.com/triton-inference-server/server/blob/main/docs/examples/model_repository/densenet_onnx/config.pbtxt)

**Comment by mahesh11T** [comment]
> Hi. You can modify 'max_batch_size param' in config.pbtxt of densenet_onnx. Default value is 0. It must be more than 0. https://github.com/triton-inference-server/server/blob/main/docs/examples/model_repository/densenet_onnx/config.pbtxt

I had set it to 1 itself and it was giving this error.

**Comment by Yobol** [comment]
I encountered this error yesterday. I solve it because I found config.pbtxt was missing.

**Comment by mahesh11T** [comment]
> I encountered this error yesterday. I solve it because I found config.pbtxt was missing.

oh ok, can you look into this issue? https://github.com/triton-inference-server/server/issues/6547
