### ISSUE TITLE
How do I propagate intermediate results in an integration model?

### ISSUE THREAD

**Issue by callmezhangchenchenokay** [triton-inference-server/server#6537]
Because of this problem
https://github.com/triton-inference-server/tensorrtllm_backend/issues/71

How do I propagate intermediate results in an integration model?

I want to get the output of the first model

I tried to use the output of the first model directly as the input in the third model, but it didn't work

<img width="1507" alt="image" src="https://github.com/triton-inference-server/server/assets/146302419/35d1b64c-5a48-4f19-a2f8-ed60745cfaf7">

**Comment by oandreeva-nv** [comment]
Did the solution provided in https://github.com/triton-inference-server/tensorrtllm_backend/issues/71 worked for your case?

**Comment by callmezhangchenchenokay** [comment]
Thanks for your reply! 
At the bottom of this solution is my comment that the problem has been solved

**Comment by callmezhangchenchenokay** [comment]
Sorry to interrupt again! 
 
The solution mentioned above requires model_transaction_policy to be set to True, 
Can only be used if stream = False, 
 
However, this problem occurs when stream = True
<img width="1055" alt="image" src="https://github.com/triton-inference-server/server/assets/146302419/b16fc516-03a3-4f57-9bd0-2ffea8f4d836">

So there needs to be a way to export REQUEST_INPUT_LEN from stream =True, model_transaction_policy =True
