### ISSUE TITLE
When using stateful models, the dims of the initial_state is ignored

### ISSUE THREAD

**Issue by grzywada** [triton-inference-server/server#6538]
**Description**

The [docs](https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/user_guide/architecture.html#state-initialization) for stateful models describe a dims field on initial_state. Supposedly this dims can be used to override a variable dimension in state, as referenced by the note in the docs "in the example above variable dimensions in the state description are converted to fixed size dimensions." But in reality this dims value seems to be ignored by the code and has no apparent effect. If you specify a variable dimension in state, that dimension value will always be 1.
The relevant code is [here](https://github.com/triton-inference-server/core/blob/main/src/sequence_state.cc#L112). I would expect the code to read dims from the initial_state object and use it to override any variable dimensions in state_config, but the code does not read initial_state.dims at any point.
Indeed there appears to be only one code reference to initial_state.dims throughout the codebase [here](https://github.com/search?q=repo%3Atriton-inference-server%2Fcore+initial_state.dims&type=code).
The example in the doc with initial_state: { ... dims: [ 1 ] ... } happens to work because 1 is Triton's default value for every variable-sized dimension in the starting request. If the example was changed to 2 instead of 1 the bug manifests.

**Triton Information**

Reproduced in tritonserver v23.09, and seems to be present in the latest version of the code.

**To Reproduce**

Take any stateful model whose dims have a variable number of dimensions and whose initial_state is specified. Set the initial state's dimension corresponding to the state's variable number of dimensions to be any non-1 value. That value is ignored.

**Expected behavior**

The initial_state.dims fixed dimensions should override the state's variable dimensions.

**Comment by nnshah1** [comment]
@grzywada Thank you for the observation and detailed note. During our testing and recent enhancements we also found the same issue and have begun working on a fix:

https://github.com/triton-inference-server/core/pull/270 

@Tabrizian Are there additional considerations here before merge?

**Comment by Tabrizian** [comment]
@nnshah1 It is just additional testing that is needed. Otherwise, it should be good to merge.

**Comment by Tabrizian** [comment]
The fix has been merged. Let us know if you still run into issues.
