### ISSUE TITLE
src/nvOCDR.cpp:664:23: error: 'mParam' was not declared in this scope

### ISSUE THREAD

**Issue by mahesh11T** [triton-inference-server/server#6547]
while bulding the docker file i found no error in running the following line, make -j8 inside triton folder, but nvocdr was not found error happening, so again i ran this make command and its failing.?
https://github.com/NVIDIA-AI-IOT/NVIDIA-Optical-Character-Detection-and-Recognition-Solution/blob/main/triton/README.md

![image](https://github.com/triton-inference-server/server/assets/107621428/8c1c9ea9-a5c8-4e18-ab98-7cbc9c11abbc)
![image](https://github.com/triton-inference-server/server/assets/107621428/30d22be8-dad0-41e2-8c0e-606968a92ab8)

**Comment by dyastremsky** [comment]
Please open an issue in [the source repository](https://github.com/NVIDIA-AI-IOT/NVIDIA-Optical-Character-Detection-and-Recognition-Solution). That is were the Dockerfile is located. The team maintaining that repository should hopefully be able to help.
