### ISSUE TITLE
Unable to connect to server  when `curl -v localhost:8000/v2/health/ready`

### ISSUE THREAD

**Issue by xx-xxx** [triton-inference-server/server#6560]
`curl -v localhost:8000/v2/health/ready`
Unable to connect to server
The error is as follows

* Trying 127.0.0.1:8000...
* connect to 127.0.0.1 port 8000 failed: Connection refused
* Trying [::1]:8000...
* connect to ::1 port 8000 failed: Connection refused
* Failed to connect to localhost port 8000 after 0 ms: Couldn't connect to server
* Closing connection 0
curl: (7) Failed to connect to localhost port 8000 after 0 ms: Couldn't connect to server

What went wrong

But the server is already running

I1110 07:21:40.271901 1 server.cc:662]
+----------------------+---------+--------+
| Model                | Version | Status |
+----------------------+---------+--------+
| densenet_onnx        | 1       | READY  |
| inception_graphdef   | 1       | READY  |
| simple               | 1       | READY  |
| simple_dyna_sequence | 1       | READY  |
| simple_identity      | 1       | READY  |
| simple_int8          | 1       | READY  |
| simple_sequence      | 1       | READY  |
| simple_string        | 1       | READY  |
+----------------------+---------+--------+
I1110 07:21:40.275966 1 grpc_server.cc:2513] Started GRPCInferenceService at 0.0.0.0:8001
I1110 07:21:40.276272 1 http_server.cc:3620] Started HTTPService at 0.0.0.0:8000
I1110 07:21:40.319154 1 http_server.cc:187] Started Metrics Service at 0.0.0.0:8002

**Comment by dyastremsky** [comment]
Wherever you are running curl, can it access the server endpoint? For example, are you in the same container or does the Triton server container expose the port (including `-p8000:8000` in the Docker run command)? If you are using two containers, does the client container use the host network (including `--net=host` in the Docker run command)? This seems like a networking issue, so you want to make sure your ports are set up correctly.

**Comment by xx-xxx** [comment]
> Wherever you are running curl, can it access the server endpoint? For example, are you in the same container or does the Triton server container expose the port (including `-p8000:8000` in the Docker run command)? If you are using two containers, does the client container use the host network (including `--net=host` in the Docker run command)? This seems like a networking issue, so you want to make sure your ports are set up correctly.

yeah! expose the port (including -p8000:8000 in the Docker run command)?  I use ‘-p8000:8000’ in Docker run command  it's successful！ thank you very much!

**Comment by owlnikita** [comment]
what if i don't use containers, but the error still exists?

**Comment by catcity217** [comment]
GET http://localhost:8000/health

**Comment by catcity217** [comment]
GET http://localhost:8000/health

**Comment by catcity217** [comment]
![Image](https://github.com/user-attachments/assets/38683351-4bab-4025-ac48-d65cbb31b441)

**Comment by catcity217** [comment]
![Image](https://github.com/user-attachments/assets/5a29a139-3d7b-4301-9654-20881e8a8d5c)

**Comment by catcity217** [comment]
https://github.com/triton-inference-server/server/issues/6560#issuecomment-3873516178

**Comment by NaniToka** [comment]
GET curl http://127.0.0.1:8000/health
