### ISSUE TITLE
How to send a request when enabled dynamic batch and batchsize > 1

### ISSUE THREAD

**Issue by MKMQ99** [triton-inference-server/server#6567]
I  start a triton server by following config:
```
name: "internlm"
backend: "python"
max_batch_size: 8

input [
  {
    name: "prompt"
    data_type: TYPE_STRING
    dims: [-1]
    allow_ragged_batch: true
  }
]
output [
  {
    name: "generated_text"
    data_type: TYPE_STRING
    dims: [-1]
  }
]
instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [5]
  }
]
dynamic_batching {
  priority_levels: 9
  default_priority_level: 9
  max_queue_delay_microseconds: 300
}
```
then I use python API to send request:
```
from tritonclient.utils import *
import tritonclient.http as httpclient
import time
import numpy as np
tm1 = time.perf_counter()
with httpclient.InferenceServerClient(url="localhost:38000", verbose=False, concurrency=32) as client:
    input_text =["Where is Uruguay?"] 
    text_obj = np.array(input_text, dtype="object")
    inputs = [
        httpclient.InferInput("prompt", text_obj.shape, np_to_triton_dtype(text_obj.dtype)).set_data_from_numpy(text_obj),
    ]
    outputs = [
        httpclient.InferRequestedOutput("generated_text"),
    ]
    n_requests = 1
    responses = []
    for i in range(n_requests):
        responses.append(client.async_infer('internlm', model_version='1', inputs=inputs, outputs=outputs, priority=4))
        
for r in responses: 
    result = r.get_result()
    content = result.as_numpy('generated_text')
    print(content)
    
tm2 = time.perf_counter()
print(f'Total time elapsed: {tm2-tm1:0.2f} seconds')
```
but it errors
![WXWorkCapture_16998715727680](https://github.com/triton-inference-server/server/assets/45583406/cac5ad85-3a54-4e73-b6aa-e943f326c22f)

so I change the shape of  input_text 

```
    input_text =[["Where is Uruguay?"]]   
```

but still error
![WXWorkCapture_16998711883277](https://github.com/triton-inference-server/server/assets/45583406/030cf6a7-98ec-4143-9ba4-ab7003864120)

Is there a way to solve this problem, or how to send a request when triton enabled dynamic batch and batchsize > 1?

**Comment by krishung5** [comment]
Hi @MKMQ99, from the log it seems like the error comes from the Python model at line 45 and is not related to the batch size. Could you check if the `decode` attribute is called by a correct object?

**Comment by MKMQ99** [comment]
> Hi @MKMQ99, from the log it seems like the error comes from the Python model at line 45 and is not related to the batch size. Could you check if the `decode` attribute is called by a correct object?

sorry, I cleaned some remark, So the error actually comes from the code:
`responses.append(client.async_infer('internlm', model_version='1', inputs=inputs, outputs=outputs, priority=4))`
`decode` Presumably encapsulated in the python API. It doesn't seem like it can be changed. Am I using the API the wrong way?Or is there something wrong with my triton configuration?

**Comment by MKMQ99** [comment]
There is something wrong in model.py when using python backend. It's fixed now.
