### ISSUE TITLE
segmentation fault on /generate_stream when the client closes the connection

### ISSUE THREAD

**Issue by anxietymonger** [triton-inference-server/server#6576]
If the client tries to close the connection when the server is still generating, the server will crash on segmentation fault. 100% reproducible.

**Comment by nnshah1** [comment]
Fixed in this commit and will be released in 23.12

https://github.com/triton-inference-server/server/commit/b876a90fe92d0e36621bdb66f2cc522665473222

**Comment by tanmayv25** [comment]
Closing the issue as the bug was resolved.
