### ISSUE TITLE
Llama-2-7b-chat-hf on vLLM not loading

### ISSUE THREAD

**Issue by vecorro** [triton-inference-server/server#6578]
**Description**
Following instructions from the [vLLM backend](https://github.com/triton-inference-server/vllm_backend/tree/main/samples/model_repository) and some adjustments it is no possible to load the model from `meta-llama/Llama-2-7b-chat-hf` into vLLM for inference. The model gets properly downloaded from HF but after the download concludes, I get the following errors:

```
Downloading (\u2026)of-00002.safetensors: 100%|##################################################################################################################################################################| 9.98G/9.98G [01:27<00:00, 114MB/s]
INFO 11-15 02:58:48 llm_engine.py:205] # GPU blocks: 2361, # CPU blocks: 512
I1115 02:58:49.477216 1 pb_stub.cc:325] Failed to initialize Python stub: TypeError: 'NoneType' object is not subscriptable

At:
  /opt/tritonserver/backends/vllm/model.py(75): initialize

E1115 02:58:51.162611 1 backend_model.cc:634] ERROR: Failed to create instance: TypeError: 'NoneType' object is not subscriptable

At:
  /opt/tritonserver/backends/vllm/model.py(75): initialize

E1115 02:58:51.162838 1 model_lifecycle.cc:621] failed to load 'vllm_model' version 1: Internal: TypeError: 'NoneType' object is not subscriptable

At:
  /opt/tritonserver/backends/vllm/model.py(75): initialize

I1115 02:58:51.162889 1 model_lifecycle.cc:756] failed to load 'vllm_model'
I1115 02:58:51.163199 1 server.cc:592] 

```

**Triton Information**
What version of Triton are you using?

`nvcr.io/nvidia/tritonserver:23.10-vllm-python-py3`

Are you using the Triton container or did you build it yourself?

I'm using an NGC container without modification

**To Reproduce**
Steps to reproduce the behavior.

Here the dir structure
```
.
└── model_repository
    └── vllm_model
        ├── 1
        │   └── model.json
        └── config.pbtxt

```

The config.pbtxt file contents is:
```
backend: "vllm"

instance_group [
  {
    count: 1
    kind: KIND_MODEL
  }
]

model_transaction_policy {
  decoupled: True
}

max_batch_size: 0

input [
  {
    name: "PROMPT"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]

output [
  {
    name: "generated_text"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }

```

I'm attaching the JSON config file. The container gets executed by

`docker run --env HUGGING_FACE_HUB_TOKEN=$HUGGING_FACE_HUB_TOKEN --gpus all -it --net=host --rm -p 8001:8001 --shm-size=1G --ulimit memlock=-1 --ulimit stack=67108864 -v ${PWD}:/work -w /work nvcr.io/nvidia/tritonserver:23.10-vllm-python-py3
 tritonserver --model-store ./model_repository`

**Expected behavior**
vLLM serving the Llama 2 chat LLM. I'd also expect to be able to run vLLM emulating the OpenAI compatible API to use vLLM as a drop-in replacement of ChatGPT. 

```
python -m vllm.entrypoints.openai.api_server \
    --model facebook/opt-125m
```

Thank you!

[model.json](https://github.com/triton-inference-server/server/files/13359631/model.json)

**Comment by nnshah1** [comment]
we have updated the model to use "text_input" as input instead of PROMPT and "text_output" for output instead of "generated_text". This is to help normalize between different backends (TRT-LLM and vLLM).

https://github.com/triton-inference-server/vllm_backend/blob/0e5b209f879e637705eab6e8d6c3c73451968bf1/src/model.py#L46 

You can also remove these sections from your config and they will be auto populated.

Can you give that a try?

**Comment by vecorro** [comment]
Thanks @nnshah1. I retried bu got the same errors:

The `config.pbtxt` file content is now
```
backend: "vllm"

instance_group [
  {
    count: 1
    kind: KIND_MODEL
  }
]

model_transaction_policy {
  decoupled: True
}

max_batch_size: 0

```

Notice that this entry:
`model_transaction_policy {
  decoupled: True
}`

is necessary, otherwise Triton would complain as well and throw an exception. 

Here the new error message which looks very similar to the previous one:


```
Downloading (\u2026)of-00002.safetensors: 100%|######################################################################################################################################################################################| 9.98G/9.98G [01:48<00:00, 92.3MB/s]
INFO 11-15 14:36:52 llm_engine.py:205] # GPU blocks: 2361, # CPU blocks: 512
I1115 14:36:53.663659 1 pb_stub.cc:325] Failed to initialize Python stub: TypeError: 'NoneType' object is not subscriptable

At:
  /opt/tritonserver/backends/vllm/model.py(75): initialize

E1115 14:36:55.517609 1 backend_model.cc:634] ERROR: Failed to create instance: TypeError: 'NoneType' object is not subscriptable

At:
  /opt/tritonserver/backends/vllm/model.py(75): initialize

E1115 14:36:55.517864 1 model_lifecycle.cc:621] failed to load 'vllm_model' version 1: Internal: TypeError: 'NoneType' object is not subscriptable

At:
  /opt/tritonserver/backends/vllm/model.py(75): initialize

I1115 14:36:55.517924 1 model_lifecycle.cc:756] failed to load 'vllm_model'
I1115 14:36:55.518310 1 server.cc:592] 
```

**Comment by nnshah1** [comment]
Apologies again, I realized the auto complete features is coming in our next release. For 23.10 you will still need to have the input and outputs explicitly in the model config (but with updated names)

https://github.com/triton-inference-server/vllm_backend/blob/r23.10/samples/model_repository/vllm_model/config.pbtxt

**Comment by vecorro** [comment]
Thanks, not it works. The `config.pbtxt` file content is:

`config.pbtxt:`
```
# Note: The vLLM backend uses the following input and output names.
# Any change here needs to also be made in model.py
input [
  {
    name: "text_input"
    data_type: TYPE_STRING
    dims: [ 1 ]
  },
  {
    name: "stream"
    data_type: TYPE_BOOL
    dims: [ 1 ]
  },
  {
    name: "sampling_parameters"
    data_type: TYPE_STRING
    dims: [ 1 ]
    optional: true
  }
]

output [
  {
    name: "text_output"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]
```
