### ISSUE TITLE
Fail to run triton server with  GPU on Jetson Orin AGX 16G: GPU instances not supported

### ISSUE THREAD

**Issue by skymizerFuji** [triton-inference-server/server#6588]
Follow up #6570, I have followed instruction [here](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/jetson.md) to setup env for Jetson

**Description**
 
When I run the command
```
cd tritonserver/bin
./tritonserver --model-repository ~/model_repository/ --backend-directory=~/tritonserver/backends/ --log-verbose 1
```
I got an error
```
...
E1116 03:33:53.875492 17251 model_lifecycle.cc:626] failed to load 'Llama-2-7b-chat-hf' version 1: Internal: GPU instances not supported
```

This is my config.pbtxt
```
name: "Llama-2-7b-chat-hf"
backend: "python"
input [
  {
    name: "prompt"
    data_type: TYPE_STRING
    dims: [1]
  }
]
output [
  {
    name: "generated_text"
    data_type: TYPE_STRING
    dims: [1]
  }
]
instance_group [
  {
    kind: KIND_GPU
  }
]
```
Note: When I change KIND_GPU to KIND_CPU, the triton server can be launched successfully, but it won't use GPU. 

Triton ver: 2.35.0
JetPack: 5.1.1
Using pre-build bin: [tritonserver2.35.0-jetpack5.1.2.tgz](https://github.com/triton-inference-server/server/releases)

**To Reproduce**

create a model_repository
```
model_repository
|____Llama-2-7b-chat-hf
| |____config.pbtxt
| |____1
| | |____model.py
```

`model.py`
```
class TritonPythonModel:
    pass
```
`config.pbtxt`: as listed above

Download and extract the triton server [tarfile]((https://github.com/triton-inference-server/server/releases)
Then run the command
```
cd tritonserver/bin
./tritonserver --model-repository ~/model_repository/ --backend-directory=~/tritonserver/backends/ --log-verbose 1
```

**Comment by krishung5** [comment]
Hi @skymizerFuji, for Jetson, the Python backend does not support GPU Tensors. Please see the limitation in the [documentation](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/jetson.md).
