### ISSUE TITLE
TRITON_AWS_MOUNT_DIRECTORY is not working

### ISSUE THREAD

**Issue by tuanavu** [triton-inference-server/server#6624]
**Description**
Typically, when deploying in Kubernetes (k8s) with the model_repo located in S3, the model is downloaded into a k8s pod and mounted to a temporary directory, namely `/tmp/folderXXX`. However, there are additional supporting files in the model_repo that I need to reference, such as `embedding_tables/` and `hps_tf_trion.json`.

![Screen Shot 2023-11-21 at 2 53 41 PM](https://github.com/triton-inference-server/server/assets/6547031/3ff7abdc-3d7c-4dfd-b4f9-ccf71d8e8ba3)

To accommodate this, I aim to employ `TRITON_AWS_MOUNT_DIRECTORY` based on [this model_repo guide](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/model_repository.md#s3) to set a specific folder with an exact path in the pod for model_repo that I can reference to. In my `deployment.yaml file`,I have incorporated information to generate a temporary mount folder `/tmp/models`, and set the environment variable `TRITON_AWS_MOUNT_DIRECTORY= /tmp/models`. Despite these changes, upon initiating the deployment, the model continues to be pulled to `/tmp/folderXXX` instead of `/tmp/models`. Here's the relevant excerpt from the `deployment.yaml`:

```bash
containers:
      - name: triton
        imagePullPolicy: IfNotPresent
        image: {{triton_image}}
        volumeMounts:
        - name: model-repo
          mountPath: /tmp/models
env:
        - name: TRITON_AWS_MOUNT_DIRECTORY
          value: /tmp/models
```

**Triton Information**
- `nvcr.io/nvidia/merlin/merlin-tensorflow:23.02`
- `nvcr.io/nvidia/merlin/merlin-tensorflow:23.09`

Are you using the Triton container or did you build it yourself?
- Utilized an existing Triton container

**To Reproduce**
- Create a `deployment.yaml` with the above information to add mount path for and `TRITON_AWS_MOUNT_DIRECTORY` env.
- Start the deployment.
- SSH into the pod to verify the location where the model files have been downloaded.

**Comment by kthui** [comment]
Hi @tuanavu, can you try replicate the issue on a Triton container from [NGC](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/tritonserver/tags) (i.e. 23.10-py3)? This can help use eliminate any issue from k8s.

cc @oandreeva-nv on `TRITON_AWS_MOUNT_DIRECTORY` issue

**Comment by oandreeva-nv** [comment]
Agree with @kthui, setting a specific folder is quite recent feature, so please make sure that containers you are using have the latest version of Triton. 

Verified our CI, tests are green for this feature and logs show that models are loaded to specified location. 

I am not 100% familiar with merlin's workload, but maybe you can try to explicitly export the env variable? link to how we do it in our tests: https://github.com/triton-inference-server/server/blob/main/qa/L0_storage_S3/test.sh#L296

**Comment by yingcanw** [comment]
This question has been replied in [HugeCTR's slack channel](https://hugectr.slack.com/archives/C063BG59HR6/p1700791114755139?thread_ts=1700629070.693999&cid=C063BG59HR6). If @kthui have further feedback on this issue, it will continue to be discussed in the slack channel.

**Comment by markthill** [comment]
I had the same issue using the triton server container version 23.08.  Switched to 23.10 and it works.

**Comment by tuanavu** [comment]
Thank you for confirming the issue. Confirmed that I am able to reproduce @markthill's steps of using Triton version 23.10 and setting `TRITON_AWS_MOUNT_DIRECTORY=/tmp/models`, it did successfully download the S3 objects to the specific folder.

However, instead of putting all the S3 objects directly in that folder, it created another temporary sub-folder like `/tmp/models/folderXXX`, which defeat the purpose of getting a specific path to reference to. cc @oandreeva-nv, @kthui

**Comment by kthui** [comment]
Hi @tuanavu, can you file a separate [feature request](https://github.com/triton-inference-server/server/issues/new/choose) if you would like follow up on having a deterministic S3 sub-folder path (i.e. not having `folderXXX` on the path)?

**Comment by oandreeva-nv** [comment]
Hi @tuanavu , regarding Merlin specific issues, could you please reach out to Merlin GitHub: https://github.com/NVIDIA-Merlin/Merlin and ask them? We don't have any information regarding when Merlin will support `TRITON_AWS_MOUNT_DIRECTORY` env variable. 

Regarding ` defeat the purpose of getting a specific path to reference to`, you can specify any directory, not only `/tmp/...`. That can help if you want to use external mount drive for example and download S3 directory there. If you still would like to have a control over `folderXXX` pattern, please file a feature request as @kthui kindly mentioned.

**Comment by tuanavu** [comment]
Thanks guys, I believe @markthill has already filed a feature request here: https://github.com/triton-inference-server/server/issues/6644. Will add some more details and follow this.
