### ISSUE TITLE
[WARNING] Perf Analyzer was not able to keep up with the desired request rate. 

### ISSUE THREAD

**Issue by ZhanqiuHu** [triton-inference-server/server#6637]
I was using Perf Analyzer to profile a recommendation system on the Triton Inference Server. As I increased the request rate, I got the following error
```[WARNING] Perf Analyzer was not able to keep up with the desired request rate. ```

What does this mean, what is the cause of this, and how can I fix the issue?

Thanks!

**Comment by matthewkotila** [comment]
It means the request rate was too high and given your system (likely CPU-bound), Perf Analyzer was unable to send requests quickly enough to match the specified request rate. You could try running on a system with a faster CPU/more cores.

**Comment by ZhanqiuHu** [comment]
Hi @kthui!
The warning message says 
```
Avg send request rate: 361.97 infer/sec
[WARNING] Perf Analyzer was not able to keep up with the desired request rate. 96.49% of the requests were delayed. 
Throughput: 361.97 infer/sec
```

I tried to look up `DELAY_PCT_THRESHOLD` but couldn't find anything. What is it and how do I use it?

Thanks!

**Comment by oandreeva-nv** [comment]
@ZhanqiuHu, I'm closing this issue due to in-activity. 
If you still have any questions, feel free to reach out and I will re-open this issue
