### ISSUE TITLE
[Question] What became of image_preprocess.cc? Is there a modern equivalent?

### ISSUE THREAD

**Issue by mvpel** [triton-inference-server/server#6652]
Hi folks,

After a number of years, we're finally tasked to upgrade our Triton server from v20.11. Our workflows are using the image_preprocess backend to do a 1/255 scaling and image resizing. However, this code appears to have vanished from the src/custom path in the server repository at version 20.10. Is there a modern equivalent for a later version of Triton?

Alternatively, is there a way to use the existing v20 .so with the newer version of Triton? I seem to recall a change in the API which precluded that, but perhaps I'm mistaken.

Thanks for any recommendations you can offer.

I'm also in need of an elementwise average backend, so if anyone out there knows of such a beast I'd appreciate a referral. This may be a good candidate for use with the Python backend, come to think of it.

**Comment by kthui** [comment]
Hi @mvpel, are you referring to https://github.com/triton-inference-server/server/blob/r20.11/src/backends/custom/custom_backend.h custom backend implementation? We refactored the project into multiple repositories, and added a lot more new features along the way. I think the closest code to the one back in 2020 would be here https://github.com/triton-inference-server/backend/tree/main/examples

cc @GuanLuo @tanmayv25 for recommendations on upgrading from r20.11.

**Comment by mvpel** [comment]
Excellent, thanks for the pointer, I'll check it out!

**Comment by tanmayv25** [comment]
@mvpel you might want to take a look at the [dali backend](https://github.com/triton-inference-server/dali_backend) for image processing. 
You can take a look on the example here: https://github.com/triton-inference-server/dali_backend/tree/main/docs/examples/inception_ensemble

**Comment by mvpel** [comment]
> @mvpel you might want to take a look at the [dali backend](https://github.com/triton-inference-server/dali_backend) for image processing. You can take a look on the example here: https://github.com/triton-inference-server/dali_backend/tree/main/docs/examples/inception_ensemble

Thanks for pointing me in that direction, I had no idea what DALI even was. I'll see what I can figure out.

**Comment by Bobo-y** [comment]
@mvpel https://github.com/triton-inference-server/server/issues/6715, I refer recommended , I want to reszize + norm img, but only can return char datatype img now.

**Comment by mvpel** [comment]
> @mvpel you might want to take a look at the [dali backend](https://github.com/triton-inference-server/dali_backend) for image processing. You can take a look on the example here: https://github.com/triton-inference-server/dali_backend/tree/main/docs/examples/inception_ensemble

Thanks again for the reference, I think the following will do what I need for the 1/255 normalization of RGB:

```
import nvidia.dali as dali
from nvidia.dali.plugin.triton import autoserialize
import nvidia.dali.types as types

@dali.plugin.triton.autoserialize
@dali.pipeline_def(batch_size=256, num_threads=4, device_id=0, output_dtype=types.FLOAT32, output_ndim=[3])
def one255_pipe():
    images = dali.fn.external_source(device="cpu", name="DALI_INPUT_0")
    images = dali.fn.decoders.image(images, device="cpu")
    images = images / nvidia.dali.types.Constant(np.float32([255.0, 255.0, 255.0]))
    return images
```
Based on the example I found, this should do what I need for the 0-255 => 0.0-1.0 transformation. It looks like I may not actually need the resizing piece of it upon closer inspection of the old ensemble workflow.
