### ISSUE TITLE
Using a Torchscript Model with Tuple as Output Type

### ISSUE THREAD

**Issue by guzman109** [triton-inference-server/server#6657]
### Discussed in https://github.com/triton-inference-server/server/discussions/6656

<div type='discussions-op-text'>

<sup>Originally posted by **guzman109** December  4, 2023</sup>
I'm trying load yolov5 as a torchscript model. I see that the output of the torchscript model ( I got using their export.py) has an output of type Tuple. I see that Triton supports Tuples for torchscript models but so far I only see for inputs. Does it work for output as well? Also, what should my `config.pbtxt` look like for the output?

P.S.  I am experimenting with using the torchscript model only. I know it works fine with other backends like ONNX.</div>

**Comment by fpetrini15** [comment]
Hello @guzman109, thank you for submitting an issue. AFAIK Triton does not support tuples as inputs. When you say it does, are you referring to [this](https://github.com/triton-inference-server/server/issues/2025#issuecomment-697961419) thread?

I found [this](https://hackernoon.com/deploy-computer-vision-models-with-triton-inference-server) succinct tutorial regarding deploying yolov5 in Triton, which includes an example config.pbtxt.

**Comment by guzman109** [comment]
@fpetrini15 Sorry, I meant dictionary and not a tuple (https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/user_guide/model_configuration.html)

I'm specifically asking if Triton supports the OUTPUT of torchscript's tuple type. This is the type that I am getting as output from the torchscript version of yolov5 I exported. I'm wondering if I can load the model without having to create a wrapper or change the code in the yolov5 repository.  

Thank you for the example, but that is using TensorRT only.

**Comment by fpetrini15** [comment]
I see, sorry for the confusion.

The way we handle a dictionary of inputs does not extend to outputs, nor are tuple-type outputs supported. This question has come up in the past but has not yet been prioritized. Please see [here](https://github.com/triton-inference-server/server/issues/2846#issuecomment-844487265) for more context and a possible workaround.

**Comment by guzman109** [comment]
Thank you so much for you help and responses. I will use another backend then for this model.
