### ISSUE TITLE
How to handle requests concurrently with one model instance？

### ISSUE THREAD

**Issue by eeeeeunjung** [triton-inference-server/server#6681]
class TritonPythonModel:
    def execute(self, requests):
        ...
        
My execute function will take a long time to execute, so I want this function can be executed concurrently.
because of certain reasons，I need to set instance_group count to 1，and handle requests concurrently.
The current situation is that each request will execute serially.
I tried max_batch_size. When there are few requests, the requests will not form a batch. When the delay time is set too long, it will cause the request to wait too long, which is not suitable for me.
I just want to simply run a simple TritonPythonModel deployed on the cpu. Like fastapi, the execute function is executed immediately when the request comes, and it is not serial but can be concurrent.
Please tell me how to do

**Comment by SunnyGhj** [comment]
The execution of a model instance is always serial and concurrency cannot be achieved.

**Comment by oandreeva-nv** [comment]
I'll close this issue for now. If there are any other questions, feel free to reach out and we will re-open this issue
