### ISSUE TITLE
Interval-Based OpenTelemetry Tracing in Triton Server

### ISSUE THREAD

**Issue by teith** [triton-inference-server/server#6693]
**Is your feature request related to a problem? Please describe.**
I'm exploring Triton Inference Server's integration with OpenTelemetry for tracing. I'm interested in whether Triton can emit OpenTelemetry traces at regular intervals or under specific conditions, instead of for every request. This would be beneficial for efficient performance monitoring without the overhead of continuous detailed tracing.

**Describe the solution you'd like**
I'd like an option in Triton to configure OpenTelemetry trace emission at set intervals or based on certain triggers, rather than per-request.

**Describe alternatives you've considered**
I considered manually retrieving trace files through Nginx at specific times, but this approach seems inefficient and less practical.

**Additional context**
Interval-based or conditional tracing would offer a balanced approach between gathering detailed performance data and managing system overhead, optimizing the monitoring and debugging process.

**Comment by denti** [comment]
+1

**Comment by oandreeva-nv** [comment]
Hi @teith , you can specify rate at which you want to collect traces: https://github.com/triton-inference-server/server/blob/main/docs/user_guide/trace.md#global-settings

For example,  `tritonserver --trace-config mode=opentelemetry --trace-config rate=100 ` will only trace every 100th inference request.

**Comment by teith** [comment]
Hi, @oandreeva-nv!
Thanks for your response. I was actually looking for a way to send groups of 100 traces in one file to a webhook, not just every 100th trace. This would help manage the tracing data better and reduce system load.

**Comment by oandreeva-nv** [comment]
I see, thanks for clarification. [I've created a ticket for this feature: 5943]

**Comment by oandreeva-nv** [comment]
I'll close this issue, since this feature is currently targeted to 24.02 release and currently on master. Relevant PR: https://github.com/triton-inference-server/server/pull/6842

**Comment by oandreeva-nv** [comment]
Relevant docs: https://github.com/triton-inference-server/server/blob/main/docs/user_guide/trace.md#opentelemetry-trace-support
