### ISSUE TITLE
model analyzer collect no gpu metrics

### ISSUE THREAD

**Issue by kobecai** [triton-inference-server/server#6694]
**Description**
model analyzer collect no gpu metrics

**Triton Information**
using official Triton container: nvcr.io/nvidia/tritonserver:22.05-py3-sdk
Using CUDA 11.8 driver version 520.61.05 with kernel driver version 470.199.02.

**To Reproduce**
1. start container 
docker run -it --privileged=true --gpus all \
       -v /var/run/docker.sock:/var/run/docker.sock \
       -v /data/models:/data/models \
      --net=host  nvcr.io/nvidia/tritonserver:22.05-py3-sdk 
2. start analyze 
model-analyzer profile \
    --model-repository=/data/models \
    --profile-models=my_model --triton-launch-mode=docker \
    --override-output-model-repository \
    --output-model-repository-path=/data/models/profile \
    --triton-http-endpoint=localhost:9020\
   --triton-grpc-endpoint=localhost:9021\
    --triton-metrics-url=http://localhost:9022 \
    --triton-output-path=/workspace/triton_log\
    --run-config-profile-models-concurrently-enable

3. get output
[Model Analyzer] Running perf_analyzer failed with exit status 1 : *** Measurement Settings ***
  Batch size: 1
  Using "count_windows" mode for stabilization
  Minimum number of samples in each window: 50
  Using synchronous calls for inference
  Stabilizing using average latency

[Model Analyzer] WARNING: GPU output field "gpu_used_memory", has no data
[Model Analyzer] WARNING: GPU output field "gpu_utilization", has no data
[Model Analyzer] WARNING: GPU output field "gpu_power_usage", has no data
[Model Analyzer] WARNING: Server output field "gpu_used_memory", has no data
[Model Analyzer] WARNING: Server output field "gpu_utilization", has no data
[Model Analyzer] WARNING: Server output field "gpu_power_usage", has no data

**Expected behavior**
It should have the metrics above

**Comment by oandreeva-nv** [comment]
Hi @kobecai , thanks for reporting this! May I ask you to try one of the latest versions of Triton? 22.05 is quite old. Meanwhile, I'm CC'ing @debermudez in case he can  suggest  something else.

**Comment by debermudez** [comment]
Hi @kobecai, gpu metric gathering was added to PA/MA in 22.09. Upgrading to at least this version should remove your issue. That said, 22.09 is still a rather old release and you will see many more features and support using 23.10+.

**Comment by oandreeva-nv** [comment]
Closing per solution provided above. Feel free to reach out with any questions.
