### ISSUE TITLE
tritonclient.utils.InferenceServerException: The parameter datatype "<class 'float'>" for key "speed" is not supported.

### ISSUE THREAD

**Issue by Jackiexiao** [triton-inference-server/server#6709]
**Description**
parameter should support float?

**Triton Information**
23.10-py3

**To Reproduce**
in client.py 
```
response = triton_client.infer(
  FLAGS.model_name,
  inputs,
  outputs=outputs,
  parameters={'speaker': ‘baker', 'speed': 1.0},
)
```
Error:
```
tritonclient.utils.InferenceServerException: 
The parameter datatype "<class 'float'>" for key "speed" is not supported.
```
when I change to `'speed': 1` (int), it works fine

**Expected behavior**
but according to 
- https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/protocol/extension_parameters.html
- https://kserve.github.io/website/0.10/modelserving/data_plane/v2_protocol/#parameters

```
$parameters =
{
  $parameter, ...
}

$parameter = $string : $string | $number | $boolean
```

I think datatype "<class 'float'>" for key "speed" should support?  since float is also number

**Comment by oandreeva-nv** [comment]
Hi @Jackiexiao , `float` is currently not supported, it is on our roadmap and this issue: https://github.com/triton-inference-server/server/issues/6382 is tracking it.

I will close this issue as a duplicate, feel free to reach out in the original thread (i.e. issue 6382)

**Comment by fpetrini15** [comment]
Hello @Jackiexiao, I have merged the [PRs](https://github.com/triton-inference-server/server/pull/6755) relating to the linked request. Double type parameters will be supported in the 23.02 release!

**Comment by Jackiexiao** [comment]
thx, I guess you mean  24.02 release

**Comment by fpetrini15** [comment]
I did, thank you for the correction. I've modified the original comment to prevent confusion.
