### ISSUE TITLE
Triton Server Crash with Signal (11)

### ISSUE THREAD

**Issue by rainyfly** [triton-inference-server/server#6723]
**Triton Information**
What version of Triton are you using?
r23.10
Are you using the Triton container or did you build it yourself?
I build it myself in centos.
**To Reproduce**
We use python backend and decoupled mode to supply service for users. And the tritonserver crashs for several times with signal 11. The core dump file shows the stack as follows:
![image](https://github.com/triton-inference-server/server/assets/22424850/7aaf4f08-a368-4e1e-b824-15df4cc561c3)

I have no idea how to reproduce this segment fault, it seems that it happens after running a long time or suddenly happens sometimes.

**Expected behavior**
I also want a stable tritonserver.

**Comment by tanmayv25** [comment]
Please follow the comments in #6720.
