### ISSUE TITLE
c++ client using http not working

### ISSUE THREAD

**Issue by GuangfuWang** [triton-inference-server/server#6729]
**Description**
I use the c++ client with http enabled (i use the client library compiled from source). the inference task can run without crashes, but the problem is that it cannot output right results. in most cases, the inference client will get randoms data or simply zeros. I confirm that when using a python client requesting the same server will work as expected.

I have been debugging for days, but cannot figure out why it is not work for c++ clients.

**Triton Information**
Building from source with the most recent main branch.

Are you using the Triton container or did you build it yourself?
yes.

**To Reproduce**
the code snippet for inference:

`#include <fstream>
#include "trt_deploy.h"
#include "util.h"
#include "http_client.h"

namespace helmet
{
#define FAIL_IF_ERR(X, MSG)                                        \
  {                                                                \
    tc::Error err = (X);                                           \
    if (!err.IsOk()) {                                             \
      std::cerr << "error: " << (MSG) << ": " << err << std::endl; \
    }                                                              \
  }

bool enable_trt_log = false;

TrtDeploy::TrtDeploy(SharedRef<Config> &config): options(config->MODEL_NAME)
{
	m_config = config;
	m_im_shape = {static_cast<float>(m_config->TARGET_SIZE[0]),
				  static_cast<float>(m_config->TARGET_SIZE[1])};
	m_scale_factor = {1.0f, 1.0f};
	options.model_version_ = config->MODEL_VERSION;
	options.client_timeout_ = client_timeout;
	m_headers = tc::Headers();
	m_url = config->SERVER_URL+":"+std::to_string(config->SERVER_PORT);
	m_infer_res = nullptr;
}

TrtDeploy::~TrtDeploy() = default;

void TrtDeploy::Infer(cv::Mat &img, SharedRef<TrtResults> &result)
{
	if (!INIT_FLAG) {
		Init();
		INIT_FLAG = true;
	}

	//preprocess the image using cpu.
	cv::resize(img, img, cv::Size(m_config->TARGET_SIZE[1], m_config->TARGET_SIZE[0]));
	cv::cvtColor(img, img, cv::COLOR_BGR2RGB);
	img.convertTo(img, CV_32FC3);
	cv::multiply(img, m_mul, img);
	cv::add(img, m_subtract, img);

	InferResults(img, result);
}

void TrtDeploy::Init()
{
	if (!m_postprocessor) {
		m_postprocessor = createSharedRef<Postprocessor>(m_config);
	}
	const auto ori_w = m_config->TARGET_SIZE[1];
	const auto ori_h = m_config->TARGET_SIZE[0];
	// normalization constant, should be 1.0/255.0;
	const auto normalizer = 0.00392157f;
	const float coe_1 = normalizer / m_config->N_STD[0];
	const float coe_2 = normalizer / m_config->N_STD[1];
	const float coe_3 = normalizer / m_config->N_STD[2];
	const float off_1 = -m_config->N_MEAN[0] / m_config->N_STD[0];
	const float off_2 = -m_config->N_MEAN[1] / m_config->N_STD[1];
	const float off_3 = -m_config->N_MEAN[2] / m_config->N_STD[2];
	m_mul = cv::Mat(ori_h, ori_w, CV_32FC3,
					cv::Scalar(coe_1, coe_2, coe_3));
	m_subtract = cv::Mat(ori_h, ori_w, CV_32FC3,
						 cv::Scalar(off_1, off_2, off_3));

	if (img_data.empty())img_data.resize(3 * ori_h * ori_w * sizeof(float), 0);
	if(channels.empty()){
		size_t pos = 0;
		for (auto i = 0; i < 3; ++i) {
			channels.emplace_back(
				ori_h, ori_w, CV_32FC1, &(img_data[pos]));
			pos += channels.back().total() *
				channels.back().elemSize();
		}
	}
	ssl_options.verify_peer = verify_peer;
	ssl_options.verify_host = verify_host;
	ssl_options.ca_info = ca_certs;
	ssl_options.cert = cert_file;
	ssl_options.key = keyfile;
	FAIL_IF_ERR(
		tc::InferenceServerHttpClient::Create(&m_client,
											  m_url, verbose),
		"unable to create http client")
}

void TrtDeploy::InferResults(cv::Mat &img, SharedRef<TrtResults> &res)
{
	res->Clear();
	auto status = ValidStatus(res);
	if (!status)return;

	cv::split(img, channels);
	AppendData();

	options.request_id_ = std::to_string(request_cnt);
	request_cnt++;
	if (request_cnt % INT_MAX == 0)request_cnt = 0;

	auto outputs = CreateInferOutputs();

	FAIL_IF_ERR(
		m_client->Infer(
			&m_infer_res, options, inputs, outputs, m_headers, tc::Parameters(),
			m_request_com, m_respond_com),
		"unable to run model")

	std::shared_ptr<tc::InferResult> results_ptr(m_infer_res);
	ProcessResults(results_ptr, res);
	PrintLogs(results_ptr);
}

void TrtDeploy::Postprocessing(const SharedRef<TrtResults> &res, cv::Mat &img, int &alarm)
{
	m_postprocessor->Run(res, img, alarm);
}
bool TrtDeploy::ValidStatus(SharedRef<TrtResults> &res)
{
	bool live;
	FAIL_IF_ERR(
		m_client->IsServerLive(&live, m_headers),
		"unable to get server liveness")
	bool ready;
	FAIL_IF_ERR(
		m_client->IsServerReady(&ready, m_headers), "server is not ready")
	bool model_ready;
	FAIL_IF_ERR(
		m_client->IsModelReady(
			&model_ready, m_config->MODEL_NAME, m_config->MODEL_VERSION, m_headers),
		"unable to get model readiness")
	if (live && !ready) {
		std::cerr << "error: server is not ready" << std::endl;
		res->Set({"SERVER_STOP", {1.0f}});
		return false;
	}
	else if (!live && !ready) {
		std::cerr << "error: server is not live" << std::endl;
		res->Set({"SERVER_STOP", {2.0f}});
		return false;
	}
	else if (!model_ready) {
		std::cerr << "error: model is not ready" << std::endl;
		res->Set({"SERVER_STOP", {3.0f}});
		return false;
	}
	return true;
}
void TrtDeploy::PrintLogs(std::shared_ptr<tc::InferResult> &res)
{
	if (!res->RequestStatus().IsOk()) {
		std::cerr << "inference  failed with error: " << res->RequestStatus()
				  << std::endl;
	}
	// Get full response
	if (enable_trt_log) {
		std::cout << res->DebugString() << std::endl;
		tc::InferStat infer_stat;
		m_client->ClientInferStat(&infer_stat);
		std::cout << "======Client Statistics======" << std::endl;
		std::cout << "completed_request_count " << infer_stat.completed_request_count
				  << std::endl;
		std::cout << "cumulative_total_request_time_ns "
				  << infer_stat.cumulative_total_request_time_ns << std::endl;
		std::cout << "cumulative_send_time_ns " << infer_stat.cumulative_send_time_ns
				  << std::endl;
		std::cout << "cumulative_receive_time_ns "
				  << infer_stat.cumulative_receive_time_ns << std::endl;

		std::string model_stat;
		FAIL_IF_ERR(
			m_client->ModelInferenceStatistics(&model_stat, m_config->MODEL_NAME),
			"unable to get model statistics")
		std::cout << "=======Model Statistics======" << std::endl;
		std::cout << model_stat << std::endl;
	}
}
void TrtDeploy::ProcessResults(std::shared_ptr<tc::InferResult> &res_ptr, SharedRef<TrtResults> &res)
{
	float *outputData;
	size_t outputByteSize;
	for (auto &outputName : m_config->OUTPUT_NAMES) {
		std::vector<float> infer_result;
		res_ptr->RawData(
			outputName, (const uint8_t **)&outputData, &outputByteSize);
		infer_result = std::vector<float>(outputByteSize / sizeof(float));
		std::memcpy(infer_result.data(), outputData, outputByteSize);
		res->Set({outputName, infer_result});
	}
}
std::vector<const tc::InferRequestedOutput *> TrtDeploy::CreateInferOutputs()
{
	std::vector<const tc::InferRequestedOutput *> outputs;
	for (const auto &output_name : m_config->OUTPUT_NAMES) {
		tc::InferRequestedOutput *output;
		auto err = tc::InferRequestedOutput::Create(&output, output_name);
		if (!err.IsOk()) {
			std::cerr << "unable to get output: " << err << std::endl;
		}
		else
			outputs.push_back(output);
	}
	return outputs;
}
void TrtDeploy::InitInputs()
{
	int w = m_config->TARGET_SIZE[1];
	int h = m_config->TARGET_SIZE[0];
	if(inputs.empty()||inputs[0]== nullptr){
		inputs = {nullptr, nullptr, nullptr};
	}
	if(inputs[0]== nullptr){
		FAIL_IF_ERR(
			tc::InferInput::Create(&inputs[0],
								   m_config->INPUT_NAME[0],
								   {1, 2}, "FP32"),
			"unable to get image shape")
	}
	if(inputs[1]== nullptr){
		FAIL_IF_ERR(
			tc::InferInput::Create(&inputs[1],
								   m_config->INPUT_NAME[1],
								   {1, 3, h, w}, "FP32"),
			"unable to get image data")
	}
	if(inputs[2]== nullptr){
		FAIL_IF_ERR(
			tc::InferInput::Create(&inputs[2],
								   m_config->INPUT_NAME[2],
								   {1, 2}, "FP32"),
			"unable to get image scale factor")
	}
}
void TrtDeploy::AppendData()
{
	if (inputs.empty()||inputs[0]== nullptr) {
		InitInputs();
	} else {
		inputs[0]->Reset();
		inputs[1]->Reset();
		inputs[2]->Reset();
	}

	FAIL_IF_ERR(
		inputs[0]->AppendRaw(
			reinterpret_cast<uint8_t *>(&m_im_shape[0]),
			2 * sizeof(float)),
		"unable to set data for INPUT0")
	FAIL_IF_ERR(
		inputs[1]->AppendRaw(
			img_data.data(),
			3 * sizeof(float) * m_config->TARGET_SIZE[0] * m_config->TARGET_SIZE[1]),
		"unable to set data for INPUT1")
	FAIL_IF_ERR(
		inputs[2]->AppendRaw(
			reinterpret_cast<uint8_t *>(&m_scale_factor[0]),
			2 * sizeof(float)),
		"unable to set data for INPUT2")
}

}
`

**Expected behavior**
any help will highly appreciated!

**Comment by Tabrizian** [comment]
Please file a minimally reproducible issue so that we can help you. I would double check the inputs to make sure that they are the same as Python clients and also make sure that the inputs are in scope (i.e., not deallocated) when executing inference.

**Comment by GuangfuWang** [comment]
> Please file a minimally reproducible issue so that we can help you. I would double check the inputs to make sure that they are the same as Python clients and also make sure that the inputs are in scope (i.e., not deallocated) when executing inference.

Huge thanks for your reply, it turns out that the error is induced by my preprocessing mistake( i change the channel order twice: brg->rgb->bgr), this can be verified by setting http data to non-binary format and using mock tools.

again thank you!
