### ISSUE TITLE
rapidjson.JSONDecodeError: Parse error at offset 116: Invalid value. 

### ISSUE THREAD

**Issue by dongteng** [triton-inference-server/server#6735]
**Description**
I have an onnx mode for m3e_large . Then I use nvcr.io/nvidia/tensorrt:22.12-py3 convert this onnx to model.plan

`
trtexec --onnx=model.onnx \
        --saveEngine=model.plan \
        --verbose \
        --fp16 \
        --minShapes=input_ids:1x1,attention_mask:1x1,token_type_ids:1x1 \
        --maxShapes=input_ids:16x64,attention_mask:16x64,token_type_ids:16x64 \
        --optShapes=input_ids:16x64,attention_mask:16x64,token_type_ids:16x64\
        --workspace=10000\
        --useCudaGraph \
`
Then i use this model.plan in triton,this is my config.pbtxt
`
name: "sbert_base_chinese_nli"
platform: "onnxruntime_onnx"
max_batch_size: 16
input [
  {
    name: "input_ids"
    data_type: TYPE_INT64
    dims: [ 64 ]
  },
  {
    name: "attention_mask"
    data_type: TYPE_INT64
    dims: [ 64 ]
  },
  {
    name: "token_type_ids"
    data_type: TYPE_INT64
    dims: [ 64 ]
  }

]
output [
  {
    name: "output_0"
    data_type: TYPE_FP32
    dims: [-1,-1]
  },
  {
    name: "output_1"
    data_type: TYPE_FP32
    dims: [1024]
  }

]
version_policy: { all { }}

triton loaded it successful,but when i requesi, it gave an error :
![image](https://github.com/triton-inference-server/server/assets/84452216/1c764369-6be0-4bd0-9f3d-9b32a0a7a03d)

when i request
`
curl -v -X POST -H "Content-Type: application/json" -d '{
  "inputs": [
    {"name": "input_ids", "shape": [1, 64], "datatype": "INT32", "data": [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]},
    {"name": "attention_mask", "shape": [1, 64], "datatype": "INT32", "data": [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]},
    {"name": "token_type_ids", "shape": [1, 64], "datatype": "INT32", "data": [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]}
  ],
  "outputs": [
    {"name": "output_0", "datatype": "FP32", "binary_data": true},
    {"name": "output_1", "datatype": "FP32", "binary_data": true}
  ]
}' http://172.17.0.4:8000/v2/models/m3e/infer 
`
it give
`
< HTTP/1.1 200 OK
< Content-Type: application/json
< Content-Length: 116
<
* Connection #0 to host 172.17.0.4 left intact
{"model_name":"m3e","model_version":"1","outputs":[{"name":"output_0","datatype":"FP32","shape":[1,64,1024],"data":[
`

I find this back is incomplete.I  wonder the reason for the error. Hope your reply.Thanks!

`
**Triton Information**
nvcr.io/nvidia/triton22.12-py3

Are you using the Triton container or did you build it yourself?
nvcr.io/nvidia/triton22.12-py3
**To Reproduce**
Steps to reproduce the behavior.

**Comment by Tabrizian** [comment]
I believe we fixed a similar issue a while ago. Could you please try with the latest version and let us know if you still run into this issue?

**Comment by dongteng** [comment]
> I believe we fixed a similar issue a while ago. Could you please try with the latest version and let us know if you still run into this issue?

Thanks
