### ISSUE TITLE
boost library cannot download

### ISSUE THREAD

**Issue by bltcn** [triton-inference-server/server#6756]
boost library site is offline. So I can't build r22.12. What can I deal with it?

**Comment by uguisu** [comment]
Hello, may be you can try to download boost package from: https://sourceforge.net/projects/boost/files/boost/

**Comment by Tabrizian** [comment]
This has been fixed here: https://github.com/triton-inference-server/server/pull/6775

Let us know if you still run into issues after picking up this fix.
