### ISSUE TITLE
The size of restfulapi response is too big, triton server is oom-killed by kernel.But why does triton continue to apply memory without considering memory limits?

### ISSUE THREAD

**Issue by cannon0102** [triton-inference-server/server#6766]
# **Description**
The size of RestfulAPI response is too large, triton server is oom-killed by k8s(linux kernel).But why does tritonserver continue to apply memory without considering memory limits?Triton server is deployed with method of k8s container.I wonder how to let triton server to stop appling memory, and  at the same time it can reply to client with the message which describe the size of current  request is too large and it demands more memory.

# **Triton Information**
image:  nvcr.io/nvidia/tritonserver:23.05-py3

Are you using the Triton container or did you build it yourself?
Use Triton container to deploy services directly.

# **To Reproduce**

- **k8s container settings**
```YAML
     containers:
        - name: triton-inference-server
          image: nvcr.io/nvidia/tritonserver:23.05-py3
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /models
              name: models
            - mountPath: /logs
              name: logs

          resources:
            limits:
              cpu: "4"
              memory: 2Gi
              aliyun.com/gpu-mem: 2 #GiB
          args: ["tritonserver", "--model-repository=/models", "--allow-http=true", "--allow-http=true", "--http-port=8080", "--grpc-port=9000", "--log-verbose=2", "--allow-metrics=true", "--metrics-port=8002", "--log-file=/logs/triton-inference-server.log"]

          ports:
            - containerPort: 8080
              name: http
            - containerPort: 9000
              name: grpc
            - containerPort: 8002
              name: metrics
          livenessProbe:
            initialDelaySeconds: 15
            failureThreshold: 3
            periodSeconds: 10
            httpGet:
              path: /v2/health/live
              port: http
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
            httpGet:
              path: /v2/health/ready
              port: http
```

- **Model/request settings**
   - model:
      - model framework: tensorflow 2.0/keras
      - model name: yolov3

    - input/output data
        - batchsize: 2
        - input
            - input1 shape: [2,416,416,3]
        - output
            - output1 shape: [2, 52, 52, 3, 85]
            - output2 shape: [2, 26, 26, 3, 85]
            - output3 shape: [2, 13, 13, 3, 85]

- **Client request/response information**
```shell

curl -H "Content-Type: application/json" "http://172.16.1.216:44511/v2/models/yolov3_tf/infer" --data-binary @./input.json -vv
*   Trying 172.16.1.216:44511...
* TCP_NODELAY set
* Connected to 172.16.1.216 (172.16.1.216) port 44511 (#0)
> POST /v2/models/yolov3_tf/infer HTTP/1.1
> Host: 172.16.1.216:44511
> User-Agent: curl/7.68.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 45670012
> Expect: 100-continue
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 100 Continue
* We are completely uploaded and fine
* Empty reply from server
* Connection #0 to host 172.16.1.216 left intact
curl: (52) Empty reply from server
```

- **Server Information**
- k8s信息
![img_v3_026p_8906b854-4fa3-45c1-a262-a8a4ab9b51dg](https://github.com/triton-inference-server/server/assets/152941001/cd1168b6-d5fc-4492-a8f1-1bfecb790652)

- pod所在宿主机syslog信息(/var/log/syslog)
```log
Jan  5 11:14:10 node-gpu kernel: [169753.877501] Tasks state (memory values in pages):
Jan  5 11:14:10 node-gpu kernel: [169753.877501] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
Jan  5 11:14:10 node-gpu kernel: [169753.877503] [1457048] 65535 1457048      255        1    28672        0          -998 pause
Jan  5 11:14:10 node-gpu kernel: [169753.877505] [1913998]     0 1913998  5869194   612925  7913472        0          -997 tritonserver
Jan  5 11:14:10 node-gpu kernel: [169753.877506] oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=cri-containerd-58a94d6c4fd8be30a09feefb97689808a74c627d023cc8c109ddad0def1f4803.scope,mems_allowed=0,oom_memcg=/kubepods.slice/kubepods-pod7caca731_5462_41bf_a402_3f44af7a5c23.slice,task_memcg=/kubepods.slice/kubepods-pod7caca731_5462_41bf_a402_3f44af7a5c23.slice/cri-containerd-58a94d6c4fd8be30a09feefb97689808a74c627d023cc8c109ddad0def1f4803.scope,task=tritonserver,pid=1913998,uid=0
Jan  5 11:14:10 node-gpu kernel: [169753.878185] Memory cgroup out of memory: Killed process 1913998 (tritonserver) total-vm:23476776kB, anon-rss:1267404kB, file-rss:389672kB, shmem-rss:794624kB, UID:0 pgtables:7728kB oom_score_adj:-997
```

# **Expected behavior**
- Expect Happen
1. Tritonserver stop to apply memory with considering memory limits
2. Tritonserver respond to cient with the status code 502 and error message which says the size of current  request is too large and it demands more memory.
3.  Tritonserver service can't be killed by k8s because of memory growth.

**Comment by Tabrizian** [comment]
It is not possible for Triton to query the remaining memory before allocating buffers. Memory allocations could come from many different places in Triton (including frameworks) and Triton doesn't have control over this. You might need to do some offline experiments to make sure your model is able to work properly using the memory constraints that you've specified.
