### ISSUE TITLE
Need clarification on configuring stub-timeout-seconds

### ISSUE THREAD

**Issue by ahujaparas** [triton-inference-server/server#6770]
[Here](https://github.com/triton-inference-server/python_backend?tab=readme-ov-file#managing-shared-memory) it mentions about setting up `stub-timeout-seconds` but I am not able to understand the impact. 

If the above timeout is configured as 10 secs and for more than 10 seconds, multiple inference requests were queued up at one of the five models that I have as part of ensemble model, what impact will it have on the complete system?

**Comment by Tabrizian** [comment]
@ahujaparas I believe in the recent versions this parameter has no impact. This parameter used to be a value that determined how long the stub process can take to load the model but there were some changes made to no longer require this. In any case, I don't think this parameter affects the actual inference times or queuing of the requests. Could you please confirm whether this is what you're observing?

**Comment by paras-oai** [comment]
@Tabrizian What am I observing is if my queue-size is more than 12, the stub process is intermittently getting crashed with no error logs whatsoever. I am not able to figure out what is that variable that is playing a role here? How could I deterministically point out the factor which is causing this behaviour?

**Comment by Tabrizian** [comment]
@paras-oai It looks like a different issue. Could you file a different Github issue with reproducing introductions?
