### ISSUE TITLE
[question] Can a model with larger max_batch_size used before a model with small max_batch_size  in ensemble model?

### ISSUE THREAD

**Issue by SunXuan90** [triton-inference-server/server#6776]
I have two python models, and a tensorrt model.

The first one queries database, and returns encoded messages. I wish the requests to be batched and sent in a single query to save time, so I set the max_batch_size to 128. 

Then the second python model processes the messages from query, and creates numpy arrays. It's not a simple conversion like base64 encode, the message are actually some rules, and images are created from them. Each message has to be processed separately and cannot be batched, 

The third model, which is tensorrt classification model, takes the numpy arrays and classify them. The max_batch_size is limited to 32 because of GPU memory, which is smaller than the first python model.

Can I use these models in a ensemble model? How to set the max_batch_size of the outer ensemble model? If I set 128 to the outer ensemble model, will the second and third model work?

Sorry I can't share the code here, thank you!

**Comment by Tabrizian** [comment]
Yes, you can use these models in an ensemble model. Ensemble allows models with different batch sizes to be used together. As long as the max batch size of the outer ensemble model is less than or equal to the minimum of the max batch size of the composing models you should be fine.
