### ISSUE TITLE
Error with tensor's localization when using BLS and multiple GPUs

### ISSUE THREAD

**Issue by kbegiedza** [triton-inference-server/server#6783]
**Description**

In k8s cluster I have with multiple GPUs and a single Triton server's pod.
Some of requests fails with `Internal` status and error below:

```
Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument tensors in method wrapper_CUDA_cat)
```

Is there any method I should use while using multiple GPUs and BLS with sub-requests?
My model is stateless.

Multiple server replicas could do the trick, but I'm worried about performance and proper load balancing.

**Triton Information**

While using container: `nvcr.io/nvidia/tritonserver:23.02-py3`

**To Reproduce**

Run Triton Server with multiple GPUs with BLS model using `dl_pack` and multiple models hosted in the same container.

**Expected behavior**

Triton should 'pin' all following sub-requests to concrete gpu.

**Comment by kbegiedza** [comment]
@Tabrizian Do you have any idea (or potential performance diff), how can I solve this ?

**Comment by Tabrizian** [comment]
Do you use PyTorch in your Python models? You might need to make sure that the tensors are on the correct device before passing them to the PyTorch model. You could also use preferred_memory in Python backend BLS if you want Triton to take of this for you: https://github.com/triton-inference-server/python_backend#business-logic-scripting

**Comment by kbegiedza** [comment]
Thank you @Tabrizian for pointing this out!

I've solved it by adjusting my PyTorch model, not works like a charm
