### ISSUE TITLE
Thread [0] had error: Unable to parse 'data': Shape does not match true shape of 'data' field  

### ISSUE THREAD

**Issue by ZhanqiuHu** [triton-inference-server/server#6791]
Hi! I was getting the following model when using the perf_analyzer:
```
 Successfully read data for 1 stream/streams with 1 step/steps.
*** Measurement Settings ***
  Batch size: 1
  Service Kind: Triton
  Using "time_windows" mode for stabilization
  Measurement window: 5000 msec
  Using synchronous calls for inference
  Stabilizing using average latency

Request concurrency: 1
Failed to maintain requested inference load. Worker thread(s) failed to generate concurrent requests.
Thread [0] had error: Unable to parse 'data': Shape does not match true shape of 'data' field
```

The model I was profiling takes in a tensor of shape [-1, 1] and dtype int32, and the command I was running is 
```
perf_analyzer -m ${model_repository} -u localhost:8000 \
                    --input-data=${input_data_file} \
                    --shape=candidate_ids:${batch_size},1 \
                    --input-tensor-format=json \
```

For `batch_size=1`, I used the following json input file, and the perf_analyzer works without error. 
```
{
    "data": [
        {
            "candidate_ids": {
                "content": [
                    2694396
                ],
                "shape": [
                    1,
                    1
                ]
            }
        }
    ]
}
```

However, when I tested `batch_size=1` and used this json input file, the perf_analyzer gave me the error above. 
```
{
    "data": [
        {
            "candidate_ids": {
                "content": [
                    2001675,
                    2767196
                ],
                "shape": [
                    2,
                    1
                ]
            }
        }
    ]
}
```

The format of the input data files looks correct to me, and I'm not sure what is causing this error and how to fix it. 

Thanks!

**Comment by tgerdesnv** [comment]
I assume that you meant to say that you tried a batch_size of 2 for the error case?

Also, what version of Triton/Perf Analyzer are you using?

**Comment by tgerdesnv** [comment]
My brief attempt to reproduce was not successful (no error was thrown and it ran fine).

Can you confirm that you are NOT telling perf analyzer to change the batch size via the `-b` option?

I'm noticing that the error you are hitting is inside of some JSON parsing logic in triton. I'm curious if you see the same (or similar) error if you remove `--input-tensor-format=json` from the command line.

Note: my understanding is that if you specify the shape in the input json file, that you do not also need to pass the `--shape` option on the command line. It is fine to do so, just not necessary. I do not expect that this a cause of the problem.

**Comment by ZhanqiuHu** [comment]
Hi, Thanks for the reply! 

"I assume that you meant to say that you tried a batch_size of 2 for the error case?" Yes, sorry for the typo. 

I'm using the Merlin Tensorflow 23-08 container, and `perf_analyzer --version` outputs `Perf Analyzer Version 2.37.0.9383150 (commit unknown) `.

I'm not changing the batch size with `-b` option. 

Initially I didn't use the `--input-tensor-format=json` flag, but then it gives me this error:
```
free(): invalid pointer
/usr/bin/bash: line 87: 903411 Aborted                 (core dumped) perf_analyzer -m ${model_repository} -u localhost:8000 --input-data=/workspace/${input_data_file} --shape=candidate_ids:${batch_size},1 --request-rate-range=100:200:10 --request-distribution=poisson -f $output_file
```

**Comment by ZhanqiuHu** [comment]
I tried using the lastest docker image instead and it seems to fix the problem for me! Thanks!
