### ISSUE TITLE
about C++ backend only gpu

### ISSUE THREAD

**Issue by lzcchl** [triton-inference-server/server#6793]
hello, I have reviewed some materials, but there may be some omissions. Regarding a C++backend Ensemble pipeline model, how to ensure that the data flow always stays on the GPU device.

For Python backend, I see that there is a parameter "FORCE-CPU-ONLY-INPUT-TENSORS" that can be set, just like https://github.com/triton-inference-server/server/issues/6060 As mentioned in the middle, but for C++backend, I couldn't find a similar parameter to set. Is there any?

I made some simple attempts and tests myself, and the results surprised me. This is an example of cuda rgb2bgr, and the content of config.pbtxt is as follows:

    backend: "cudargb2bgr"
    max_batch_size: 8
    input [
      {
        name: "input_tensors"
        data_type: TYPE_UINT8
        dims: [224, 224, 3]
      }
    ]

    output [
      {
        name: "output_tensors"
        data_type: TYPE_UINT8
         dims: [224, 224, 3]
          }
    ]

    instance_group [
      {
        kind: KIND_GPU
      }
    ]

    dynamic_batching {
        max_queue_delay_microseconds: 1000000
    }

Then in C++backend, I developed the code based on the example "recommended" in the Triton backend, which is derived from: https://github.com/triton-inference-server/backend/tree/r23.12/examples/backends/recommended

I have modified some parts to access GPU data, such as the location marked as change below:

    ModelInstanceState* instance_state;
    RETURN_IF_ERROR(TRITONBACKEND_ModelInstanceState(
        instance, reinterpret_cast<void**>(&instance_state)));
    ModelState* model_state = instance_state->StateForModel();

    int kind = instance_state->Kind();
    auto name = instance_state->Name();
    int deviceId = instance_state->DeviceId();
    auto cudaStream = instance_state->CudaStream();
    LOG_MESSAGE(TRITONSERVER_LOG_INFO, std::string("Kind: " + std::to_string(kind)).c_str());
    LOG_MESSAGE(TRITONSERVER_LOG_INFO, std::string("Name: " + name).c_str());
    LOG_MESSAGE(TRITONSERVER_LOG_INFO, std::string("DeviceId: " + std::to_string(deviceId)).c_str());
    if (cudaStream)
      LOG_MESSAGE(TRITONSERVER_LOG_INFO, std::string("CudaStream: 1").c_str());
    else
      LOG_MESSAGE(TRITONSERVER_LOG_INFO, std::string("CudaStream: 0").c_str());

    std::vector<TRITONBACKEND_Response*> responses;
    responses.reserve(request_count);
    for (uint32_t r = 0; r < request_count; ++r) {
      TRITONBACKEND_Request* request = requests[r];
      TRITONBACKEND_Response* response;
      RETURN_IF_ERROR(TRITONBACKEND_ResponseNew(&response, request));
      responses.push_back(response);
    }
    
    // change
    BackendInputCollector collector(
        requests, request_count, &responses, model_state->TritonMemoryManager(),
        model_state->EnablePinnedInput() /* pinned_enabled */, instance_state->CudaStream() /* stream*/);
        
    // change
    std::vector<std::pair<TRITONSERVER_MemoryType, int64_t>> allowed_input_types =
        {{TRITONSERVER_MEMORY_GPU, deviceId}};

    const char* input_buffer;
    size_t input_buffer_byte_size;
    TRITONSERVER_MemoryType input_buffer_memory_type;
    int64_t input_buffer_memory_type_id;

    RESPOND_ALL_AND_SET_NULL_IF_ERROR(
        responses, request_count,
        collector.ProcessTensor(
            model_state->InputTensorName().c_str(), nullptr /* existing_buffer */,
            0 /* existing_buffer_byte_size */, allowed_input_types, &input_buffer,
            &input_buffer_byte_size, &input_buffer_memory_type,
            &input_buffer_memory_type_id));

    LOG_MESSAGE(TRITONSERVER_LOG_INFO, std::string("input_buffer_memory_type: " + std::to_string(input_buffer_memory_type)).c_str());
    LOG_MESSAGE(TRITONSERVER_LOG_INFO, std::string("input_buffer_memory_type_id: " + std::to_string(input_buffer_memory_type_id)).c_str());

    const bool need_cuda_input_sync = collector.Finalize();
    if (need_cuda_input_sync) {
      // change
      cudaStreamSynchronize(instance_state->CudaStream());
      LOG_MESSAGE(
          TRITONSERVER_LOG_ERROR,
          "'recommended' backend: unexpected CUDA sync required by collector");
    }

    uint64_t compute_start_ns = 0;
    SET_TIMESTAMP(compute_start_ns);

    bool supports_first_dim_batching;
    RESPOND_ALL_AND_SET_NULL_IF_ERROR(
        responses, request_count,
        model_state->SupportsFirstDimBatching(&supports_first_dim_batching));

    size_t total_batch_size = 0;
    if (!supports_first_dim_batching) {
      total_batch_size = request_count;
    } 
    else {
      for (uint32_t r = 0; r < request_count; ++r) {
        auto& request = requests[r];
        TRITONBACKEND_Input* input = nullptr;
        LOG_IF_ERROR(
            TRITONBACKEND_RequestInputByIndex(request, 0 /* index */, &input),
            "failed getting request input");
        if (input != nullptr) {
          const int64_t* shape = nullptr;
          LOG_IF_ERROR(
              TRITONBACKEND_InputProperties(
                  input, nullptr, nullptr, &shape, nullptr, nullptr, nullptr),
              "failed getting input properties");
          if (shape != nullptr) {
            total_batch_size += shape[0];
          }
        }
      }
    }
    std::cout << "total_batch_size: " << total_batch_size << std::endl;

    std::vector<int64_t> nb_shape_vec = model_state->TensorNonBatchShape();
    int height = (int)nb_shape_vec[0];
    int width = (int)nb_shape_vec[1];
    // int channel = (int)nb_shape_vec[2];
    int64_t nb_shape = 1;
    for (const auto& tmp : nb_shape_vec)
    {
      // std::cout << tmp << std::endl;
      nb_shape *= tmp;
    }

    size_t dataSize = nb_shape * sizeof(uint8_t);
    uint8_t *output_buffer_gpuptr = NULL;
    cudaMalloc((void**)&output_buffer_gpuptr, dataSize * total_batch_size);
    //cuda kernel
    RGBToBGR_infer(input_buffer, output_buffer_gpuptr, width, height);

    const char* output_buffer = (const char*)output_buffer_gpuptr;
    TRITONSERVER_MemoryType output_buffer_memory_type = input_buffer_memory_type;
    int64_t output_buffer_memory_type_id = input_buffer_memory_type_id;

It can be seen that I used the "ProcessTensor" function of the "BackendInputCollector collector" and set the "TRITONSERVER-MemoryType" to "TRITONSERVER-MEMORY_GPU" to retrieve data from the GPU. When "need_cuda_input_sync" is true, I called "cudaStreamSynchronize (instance_state ->CudaStream())" for data synchronization. Therefore, in my client code, I hope to pass in cudashm, which is also data from the GPU device. I believe that now my C++backend is a GPU only operation that does not require CPU ->GPU ->CPU.

Then, when using the client, I enabled tritonz server and tested passing in cudashm, shm, and numpy with grpc. All three types of data were able to run successfully, and the printed log was also consistent, as shown below:

    I0116 02:57:48.914467 1 cudargb2bgr.cc:514] Kind: 2
    I0116 02:57:48.914485 1 cudargb2bgr.cc:515] Name: allgpu_cudaRgb2bgr_0_0
    I0116 02:57:48.914490 1 cudargb2bgr.cc:516] DeviceId: 0
    I0116 02:57:48.914495 1 cudargb2bgr.cc:518] CudaStream: 1
    I0116 02:57:48.917459 1 cudargb2bgr.cc:607] input_buffer_memory_type: 2
    I0116 02:57:48.917473 1 cudargb2bgr.cc:608] input_buffer_memory_type_id: 0

This makes me very puzzled. The success of cudashm is expected, but for shm, numpy with grpc, I think the call should fail, but in reality it succeeded. Does this indicate that there is still a CPU ->GPU silently executing behind the scenes? Is there a way to forcibly disable implicit CPU ->GPU calls for C++backend? If data is transmitted on different devices, an error must be reported, at least a message will notify me.

Or how can I monitor whether my data has undergone CPU ->GPU or GPU ->CPU?

**Comment by nv-kmcgill53** [comment]
CC: @GuanLuo

**Comment by dyastremsky** [comment]
Pinging: @GuanLuo @rmccorm4

**Comment by GuanLuo** [comment]
You are correct that the input collector will implicitly perform data transfer to meet the `allowed_input_types` expectation. If you want to enforce that the execution can only perform if the input data is already in specific memory type, then you have to perform the data examination on your own (i.e. calling `TRITONBACKEND_InputBuffer` to get memory type)

**Comment by lzcchl** [comment]
What I understand is that Triton will automatically perform implicit conversions when it needs them, but not when it doesn't.

**Comment by lzcchl** [comment]
> You are correct that the input collector will implicitly perform data transfer to meet the `allowed_input_types` expectation. If you want to enforce that the execution can only perform if the input data is already in specific memory type, then you have to perform the data examination on your own (i.e. calling `TRITONBACKEND_InputBuffer` to get memory type)

What I understand is that Triton will automatically perform implicit conversions when it needs them, but not when it doesn't.
