### ISSUE TITLE
Explanation of downloadable NGC containers

### ISSUE THREAD

**Issue by lzcchl** [triton-inference-server/server#6806]
In https://catalog.ngc.nvidia.com/orgs/nvidia/containers/tritonserver, 
The overview contain:
    The xx.yy-py3 image contains the Triton inference server with support for Tensorflow, PyTorch, TensorRT, ONNX and OpenVINO models.
    The xx.yy-py3-sdk image contains Python and C++ client libraries, client examples, and the Model Analyzer.
    The xx.yy-py3-min image is used as the base for creating custom Triton server containers as described in [Customize Triton Container].
    The xx.yy-pyt-python-py3 image contains the Triton Inference Server with support for PyTorch and Python backends only.
    The xx.yy-tf2-python-py3 image contains the Triton Inference Server with support for TensorFlow 2.x and Python backends only.

but the tags:
   23.12-py3-igpu-sdk-------------------------------No explanation provided
   23.12-py3-igpu------------------------------------No explanation provided
   23.12-py3------------------------------------------Exist
    23.12-vllm-python-py3----------------------------No explanation provided
    23.12-trtllm-python-py3--------------------------No explanation provided
    23.12-tf2-python-py3-----------------------------Exist
    23.12-pyt-python-py3----------------------------Exist
    23.12-py3-sdk-------------------------------------Exist
    23.12-py3-min------------------------------------Exist

**Comment by nv-kmcgill53** [comment]
Hi @lzcchl, you can find our explanation of the additional containers below:
- **23.12-py3-igpu**: This container is built for the Jetson or Integrated GPU class of NVIDIA devices. This equates to our [jetson tar ball](https://github.com/triton-inference-server/server/releases/tag/v2.41.0) which we release on our github release page. It contains the same supported backends between the 23.12-py3-igpu container and the tar-ball: TensorRT, Tensorflow, Pytorch, and Onnxruntime
- **23.12-py3-igpu-sdk**:  This container is built for the Jetson or Integrated GPU class of NVIDIA devices. This equates to our [jetson tar ball](https://github.com/triton-inference-server/server/releases/tag/v2.41.0) which we release on our github release page. It contains the Python and C++ client libraries, client examples, perf_analyzer, and model analyzer
- **23.12-vllm-python-py3**: This container contains tritonserver and support for the [vllm backend](https://github.com/triton-inference-server/vllm_backend). The reason for this separation is container size.
- **23.12-trtllm-python-py3**: This container contains tritonserver and support for the [trtllm backend](https://github.com/triton-inference-server/tensorrtllm_backend) which only includes TRT 9.x which is not compatible with the [tensorrt_backend](https://github.com/triton-inference-server/tensorrt_backend). tensorrt_backend, as of 23.12 is currently compatible with TensorRT 8.6.x. The reason for this backend separation is both for container size and backend compatibility. 

Hopefully this explanation helps!

**Comment by lzcchl** [comment]
thank you very much
