### ISSUE TITLE
What is triton's data privacy policy?

### ISSUE THREAD

**Issue by sperezs95** [triton-inference-server/server#6809]
Hello everyone, 

I am recently working on a computer vision project where images are sensitive data, I have been doing some searching but have not found an official document that specifies the way **Nvidia collects or stores data from the Triton Inference Server SDK** . 

If anyone could provide me with a **link to these documents** I would be very grateful.

Thank you so much!

**Comment by nv-kmcgill53** [comment]
It largely depends on where you are running Triton and what type of logging you have enabled. In our most verbose logging setting, `--log-verbose=2` we will print all the request metadata to the log. We do _not_ recommend logging verbosely in production. Likewise, if the client is also logging verbosely, then the requests and responses will be logged out as well.

In general we have [Secure Deployment Considerations](https://github.com/triton-inference-server/server/blob/main/docs/customization_guide/deploy.md) which you might find helpful as well.

CC: @jbkyang-nvi @GuanLuo

**Comment by sperezs95** [comment]
> Depende en gran medida de dónde esté ejecutando Triton y qué tipo de registro haya habilitado. En nuestra configuración de registro más detallada, `--log-verbose=2`imprimiremos todos los metadatos de la solicitud en el registro. No _recomendamos_ iniciar sesión detalladamente en producción. Del mismo modo, si el cliente también inicia sesión detalladamente, las solicitudes y respuestas también se cerrarán.
> 
> En general, tenemos [consideraciones de implementación segura](https://github.com/triton-inference-server/server/blob/main/docs/customization_guide/deploy.md) que también pueden resultarle útiles.
> 
> CC:@jbkyang-nvi @GuanLuo

nv-kmcgill53 Thank you very much for your time, 

Instead of the metadata of the requests and the type of the logging, I am interested if Triton Inference Server sends any part of the input and/or output tensors to Nvidia. Do you know where I can find information about this? 

As for the execution environment, I am thinking of mounting it on AWS EC2.

**Comment by jbkyang-nvi** [comment]
> It largely depends on where you are running Triton and what type of logging you have enabled. In our most verbose logging setting, `--log-verbose=2` we will print all the request metadata to the log. We do _not_ recommend logging verbosely in production. Likewise, if the client is also logging verbosely, then the requests and responses will be logged out as well.

Hi @sperezs95 . The library does not send data to Nvidia servers or databases, if that's what you are asking. Triton should work if it is not connected to the WWW, as long as there are connections between the server and the client.

**Comment by jbkyang-nvi** [comment]
There's a user agreement here: https://www.nvidia.com/en-us/data-center/products/nvidia-ai-enterprise/eula/ which states 
Nvidia tracks the DL numbers of the containers I believe. However:

> 12.2 Customer Ownership. Subject to the rights of NVIDIA and its suppliers in AI Products, Customer holds all rights, title and interest in and to Customer’s services, applications and Derivative Samples and Derivative Models Customer develops as permitted in the Agreement including their respective Intellectual Property Rights.

I think might be good to ask the legal/security team to contact [enterprisesupport@nvidia.com](mailto:enterprisesupport@nvidia.com) directly

**Comment by sperezs95** [comment]
> There's a user agreement here: https://www.nvidia.com/en-us/data-center/products/nvidia-ai-enterprise/eula/ which states Nvidia tracks the DL numbers of the containers I believe. However:
> 
> > 12.2 Customer Ownership. Subject to the rights of NVIDIA and its suppliers in AI Products, Customer holds all rights, title and interest in and to Customer’s services, applications and Derivative Samples and Derivative Models Customer develops as permitted in the Agreement including their respective Intellectual Property Rights.
> 
> I think might be good to ask the legal/security team to contact [enterprisesupport@nvidia.com](mailto:enterprisesupport@nvidia.com) directly

Thank you very much for the response, I will take your suggestions into account. greetings!

**Comment by Nima-Nilchian** [comment]
Hi,
I'm using Nvidia Nemotron model deployed on triton inference server on an on-premise server, isn't the inference server locally on my server or it sends data to external resources?

**Comment by jbkyang-nvi** [comment]
> Hi, I'm using Nvidia Nemotron model deployed on triton inference server on an on-premise server, isn't the inference server locally on my server or it sends data to external resources?

the server can send data to your designated client. What do you mean "external resources"? You can do inference within your server, and not connect to the web at all.
