### ISSUE TITLE
Does the metrics support visualization UI ?

### ISSUE THREAD

**Issue by lzcchl** [triton-inference-server/server#6812]
Just like the dashboard of a car, does triton metrics support similar functions so that we can have a beautiful UI page to see real-time information? I think this is a very cool thing.

**Comment by nv-kmcgill53** [comment]
Triton provides the [metrics api](https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/user_guide/metrics.html) to allow an application to pull data. From there it's up to the pulling application to process the metrics, say a UI application. Tritonserver itself doesn't provide any of this UI functionality and is left up to the user to provide the front end they would like. Also consider the [tracing api](https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/user_guide/trace.html) to get the raw trace data from requests on the server. Again, tritonserver itself doesn't provide a UI for this data.
