### ISSUE TITLE
Latency in model_lifecycle::GetModel() when serving an object detection model in ONNX format

### ISSUE THREAD

**Issue by langong347** [triton-inference-server/server#6843]
**Description**
I deployed an YOLOv8 model in ONNX format on Triton. The total latency is 260ms for a single request but the `model_lifecycle.GetModel()` step alone takes 160ms.

**Triton Information**
22.12

**Are you using the Triton container or did you build it yourself?**
I use Triton through KServe. Image is prebuilt.

**To Reproduce**
Since this is not an open project, I am not able to share the exact commands to repro.

Here is my deployment setup:
- Single GPU (T4)
- Single model instance
- No dynamic batching (i.e., default scheduler)
- ONNX model with dynamic batch, height and width dimensions
- Log verbosity: 2

Serving a single request: (the two lines marked with arrows contain the step in question)
```
I0126 19:18:44.778893 1 http_server.cc:3372] HTTP request: 2 /v2/models/object-detectron/infer
I0126 19:18:44.778939 1 model_lifecycle.cc:327] GetModel() 'object-detectron' version -1
-> I0126 19:18:44.778952 1 model_lifecycle.cc:327] GetModel() 'object-detectron' version -1
-> I0126 19:18:44.933820 1 infer_request.cc:729] [request id: 7a9fc358-fb3b-4fe4-ab02-32dd933e7e6b] prepared: [0x0x7fe498016740] request id: 7a9fc358-fb3b-4fe4-ab02-32dd933e7e6b, model: object-detectron, requested version: -1, actual version: 1, flags: 0x0, correlation id: 0, batch size: 1, priority: 0, timeout (us): 0
original inputs:
[0x0x7fe498016a28] input: images, type: FP32, original shape: [1,3,800,608], batch + shape: [1,3,800,608], shape: [3,800,608]
override inputs:
inputs:
[0x0x7fe498016a28] input: images, type: FP32, original shape: [1,3,800,608], batch + shape: [1,3,800,608], shape: [3,800,608]
original requested outputs:
requested outputs:
output0

I0126 19:18:44.933964 1 onnxruntime.cc:2672] model object-detectron, instance object-detectron, executing 1 requests
I0126 19:18:44.933997 1 onnxruntime.cc:1469] TRITONBACKEND_ModelExecute: Running object-detectron with 1 requests
2024-01-26 19:18:44.935946356 [I:onnxruntime:, sequential_executor.cc:176 Execute] Begin execution
I0126 19:18:44.968048 1 infer_response.cc:167] add response output: output: output0, type: FP32, shape: [1,7,9975]
I0126 19:18:44.968072 1 http_server.cc:1118] HTTP using buffer for: 'output0', size: 279300, addr: 0x7fe42f3a0dc0
I0126 19:18:45.009047 1 http_server.cc:1192] HTTP release: size 279300, addr 0x7fe42f3a0dc0
```

**Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).**

Model source code: Ultralytics/YOLOv8, written in PyTorch

`config.pbtxt`
```
platform: "onnxruntime_onnx"
max_batch_size: 256
input {
  name: "images"
  data_type: TYPE_FP32
  dims: 3
  dims: -1
  dims: -1
}
output {
  name: "output0"
  data_type: TYPE_FP32
  dims: -1
  dims: -1
}
default_model_filename: "model.onnx"
backend: "onnxruntime"
```

**Expected behavior**
Latency of `model_lifecycle().GetModel` step should be within 1ms. Total latency for a single request should be close to 50ms.

**Comment by jbkyang-nvi** [comment]
Is it possible to run with a later version of Triton? The version you are running is more than a year old. Our latest version is `23.12`
@GuanLuo for core related `GetModel()` calls.

**Comment by langong347** [comment]
Hi @jbkyang-nvi  @GuanLuo I have upgraded to `23.12` but the latency hasn't improved much:

- Total latency: `240ms` - `250ms`
- `model_lifecycle.GetModel`: `120ms` - `130ms`

Here is log output for one request (look for lines starting with an `->`):

```
I0129 15:20:09.115029 1 http_server.cc:4505] HTTP request: 2 /v2/models/object-detectron/infer
I0129 15:20:09.115080 1 model_lifecycle.cc:328] GetModel() 'object-detectron' version -1
-> I0129 15:20:09.115098 1 model_lifecycle.cc:328] GetModel() 'object-detectron' version -1
-> I0129 15:20:09.241864 1 infer_request.cc:131] [request id: d18db4e8-7af5-4c8f-b711-c241ba041904] Setting state from INITIALIZED to INITIALIZED
I0129 15:20:09.241884 1 infer_request.cc:893] [request id: d18db4e8-7af5-4c8f-b711-c241ba041904] prepared: [0x0x7f45a8007bb0] request id: d18db4e8-7af5-4c8f-b711-c241ba041904, model: object-detectron, requested version: -1, actual version: 1, flags: 0x0, correlation id: 0, batch size: 1, priority: 0, timeout (us): 0
original inputs:
[0x0x7f45a8006518] input: images, type: FP32, original shape: [1,3,800,608], batch + shape: [1,3,800,608], shape: [3,800,608]
override inputs:
inputs:
[0x0x7f45a8006518] input: images, type: FP32, original shape: [1,3,800,608], batch + shape: [1,3,800,608], shape: [3,800,608]
original requested outputs:
requested outputs:
output0

I0129 15:20:09.241894 1 infer_request.cc:131] [request id: d18db4e8-7af5-4c8f-b711-c241ba041904] Setting state from INITIALIZED to PENDING
I0129 15:20:09.241947 1 infer_request.cc:131] [request id: d18db4e8-7af5-4c8f-b711-c241ba041904] Setting state from PENDING to EXECUTING
I0129 15:20:09.241980 1 onnxruntime.cc:2868] model object-detectron, instance object-detectron_0, executing 1 requests
I0129 15:20:09.241992 1 onnxruntime.cc:1597] TRITONBACKEND_ModelExecute: Running object-detectron_0 with 1 requests
2024-01-29 15:20:09.243593175 [V:onnxruntime:, sequential_executor.cc:534 ExecuteThePlan] Number of streams: 2
2024-01-29 15:20:09.243669098 [V:onnxruntime:, sequential_executor.cc:184 SessionScope] Begin execution
2024-01-29 15:20:09.244018955 [V:onnxruntime:, sequential_executor.cc:518 ExecuteKernel] stream 0 launch kernel with idx 0
2024-01-29 15:20:09.244055398 [V:onnxruntime:, stream_execution_context.cc:171 RecycleNodeInputs] ort value 3 released

# Omit repetitive output from onnxruntime

2024-01-29 15:20:09.257517626 [V:onnxruntime:, stream_execution_context.cc:171 RecycleNodeInputs] ort value 523 released
2024-01-29 15:20:09.257522319 [V:onnxruntime:, stream_execution_context.cc:171 RecycleNodeInputs] ort value 524 released
2024-01-29 15:20:09.257524749 [V:onnxruntime:, sequential_executor.cc:518 ExecuteKernel] stream 0 launch kernel with idx 421

I0129 15:20:09.290991 1 infer_response.cc:167] add response output: output: output0, type: FP32, shape: [1,7,9975]
I0129 15:20:09.291014 1 http_server.cc:1199] HTTP using buffer for: 'output0', size: 279300, addr: 0x7f45469580e0
I0129 15:20:09.332397 1 http_server.cc:1273] HTTP release: size 279300, addr 0x7f45469580e0
I0129 15:20:09.332434 1 infer_request.cc:131] [request id: d18db4e8-7af5-4c8f-b711-c241ba041904] Setting state from EXECUTING to RELEASED
```

**Comment by langong347** [comment]
I also tried being specific about the model version but latency has not improved:

```
platform: "onnxruntime_onnx"
version_policy {
  specific {
    versions: 1
  }
}
max_batch_size: 256
input {
  name: "images"
  data_type: TYPE_FP32
  dims: 3
  dims: -1
  dims: -1
}
output {
  name: "output0"
  data_type: TYPE_FP32
  dims: -1
  dims: -1
}
default_model_filename: "model.onnx"
backend: "onnxruntime"
```

**Comment by jbkyang-nvi** [comment]
As stated here: https://github.com/triton-inference-server/server/blob/main/docs/user_guide/model_configuration.md#version-policy specifying the version shouldn't degrade the performance

**Comment by langong347** [comment]
@jbkyang-nvi @GuanLuo Do you have any updates on why there's a significant delay between `model_lifecycle::GetModel` and `infer_request.cc:131] [request id: <id_unknown>] Setting state from INITIALIZED to INITIALIZED`? I've tried both explicitly setting the model version and the default but got no improvement. My logger verbosity is currently set at the highest level `2`. Are there likely other steps executed in between which are not logged?

**Comment by GuanLuo** [comment]
Hi @langong347, one thing to be aware of is that the time spent between the logs you highlight is more than just time spent on GetModel(). The `setting state` message is printed when the request is fully prepared to be sent for inference, therefore the time spent like converting HTTP request into the format expected by Triton will also be included.

Given that the conversion time is included, it is also important to know how your HTTP request is formed. One major thing I would like to check is if you sends the tensor in JSON or utilizing the [binary data extension](https://github.com/triton-inference-server/server/blob/main/docs/protocol/extension_binary_data.md), it would be expected to have huge overhead if the tensor is sent in JSON because a serialization must take place as part of the conversion.

**Comment by langong347** [comment]
Hi @GuanLuo  thanks for your reply. You are right about the part with HTTP/JSON which was how our service was deployed previously. We have since switched to using gRPC and observed a huge improvement in latency. We may consider using the binary data extension you mentioned between service components where gRPC is not available. 

For the record, here is the relevant part of the log:

```
I0201 00:02:35.657082 1 infer_handler.h:1295] Grpc::CQ::Next() Running state_id 0
        Context step 0 id 0
                 State id 0: State step 0

I0201 00:02:35.657135 1 infer_handler.cc:696] Process for ModelInferHandler, rpc_ok=1, 0 step START
I0201 00:02:35.657160 1 infer_handler.h:1185] StateNew, 0 Step START
I0201 00:02:35.657181 1 infer_handler.cc:674] New request handler for ModelInferHandler, 0
I0201 00:02:35.657203 1 model_lifecycle.cc:328] GetModel() 'object-detectron' version -1
-> I0201 00:02:35.657225 1 model_lifecycle.cc:328] GetModel() 'object-detectron' version -1
-> I0201 00:02:35.657265 1 infer_request.cc:131] [request id: 9a6985c3-4095-4091-bacd-c0a3503e220e] Setting state from INITIALIZED to INITIALIZED
I0201 00:02:35.657278 1 infer_request.cc:893] [request id: 9a6985c3-4095-4091-bacd-c0a3503e220e] prepared: 

# omit subsequent outputs
```

Thanks again for taking a look into this issue!!

**Comment by GuanLuo** [comment]
From your latest log, the interval between the two logs is 40 us which is way better than the previous interval of 100+ ms. Given that, I assume the latency is indeed being introduced by the deserialization.

I am going to close the issue if you have no further concern.

**Comment by langong347** [comment]
Resolved. Thank you.
