### ISSUE TITLE
Bump OpenVINO version to 2023.3, issues with build.py

### ISSUE THREAD

**Issue by atobiszei** [triton-inference-server/server#6845]
I created alredy PR's that should solve this:
https://github.com/triton-inference-server/server/pull/6827
https://github.com/triton-inference-server/onnxruntime_backend/pull/234

I did check the openvino_backend by replacing the old version with composer Dockerfile but I wanted to check if that doesn't break ONNX so I tried to create the image with

`python3 ./build.py -v --backend onnxruntime:pull/234/head --backend openvino:pull/6827/head --container-version 23.12`

On ubuntu 20.04 but I got non-descriptive error:

> + cmake -DTRT_VERSION= -DCMAKE_TOOLCHAIN_FILE= -DVCPKG_TARGET_TRIPLET= -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/tmp/tritonbuild/tritonserver/install -DTRITON_VERSION:STRING=2.43.0dev -DTRITON_COMMON_REPO_TAG:STRING=r23.12 -DTRITON_CORE_REPO_TAG:STRING=r23
> .12 -DTRITON_BACKEND_REPO_TAG:STRING=r23.12 -DTRITON_THIRD_PARTY_REPO_TAG:STRING=r23.12 -DTRITON_ENABLE_LOGGING:BOOL=OFF -DTRITON_ENABLE_STATS:BOOL=OFF -DTRITON_ENABLE_METRICS:BOOL=OFF -DTRITON_ENABLE_METRICS_GPU:BOOL=OFF -DTRITON_ENABLE_METRICS_CPU:BOOL=OFF -DTRITON_EN
> ABLE_TRACING:BOOL=OFF -DTRITON_ENABLE_NVTX:BOOL=OFF -DTRITON_ENABLE_GPU:BOOL=OFF -DTRITON_MIN_COMPUTE_CAPABILITY=6.0 -DTRITON_ENABLE_MALI_GPU:BOOL=OFF -DTRITON_ENABLE_GRPC:BOOL=OFF -DTRITON_ENABLE_HTTP:BOOL=OFF -DTRITON_ENABLE_SAGEMAKER:BOOL=OFF -DTRITON_ENABLE_VERTEX_A
> I:BOOL=OFF -DTRITON_ENABLE_GCS:BOOL=OFF -DTRITON_ENABLE_S3:BOOL=OFF -DTRITON_ENABLE_AZURE_STORAGE:BOOL=OFF -DTRITON_ENABLE_ENSEMBLE:BOOL=OFF -DTRITON_ENABLE_TENSORRT:BOOL=OFF /workspace
> ...
> -- Distro Name: Ubuntu
> ESC[0mCMake Deprecation Warning at /tmp/tritonbuild/tritonserver/build/_deps/pybind11-src/CMakeLists.txt:8 (cmake_minimum_required):
>   Compatibility with CMake < 3.5 will be removed from a future version of
>   CMake.
> 
>   Update the VERSION argument <min> value or use a ...<max> suffix to tell
>   CMake that the project does not need compatibility with older versions.
> 
> ESC[0m
> -- pybind11 v2.10.0
> ESC[33mCMake Warning (dev) at /tmp/tritonbuild/tritonserver/build/_deps/pybind11-src/tools/FindPythonLibsNew.cmake:98 (find_package):
>   Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
>   are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
>   the cmake_policy command to set the policy and suppress this warning.
> 
> Call Stack (most recent call first):
>   /tmp/tritonbuild/tritonserver/build/_deps/pybind11-src/tools/pybind11Tools.cmake:50 (find_package)
>   /tmp/tritonbuild/tritonserver/build/_deps/pybind11-src/tools/pybind11Common.cmake:180 (include)
>   /tmp/tritonbuild/tritonserver/build/_deps/pybind11-src/CMakeLists.txt:200 (include)
> This warning is for project developers.  Use -Wno-dev to suppress it.
> ESC[0m
> -- Found PythonInterp: /usr/bin/python3 (found suitable version "3.10.12", minimum required is "3.6")
> -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.10.so
> -- Performing Test HAS_FLTO
> -- Performing Test HAS_FLTO - Success
> ESC[31mCMake Error at /usr/share/cmake-3.27/Modules/ExternalProject.cmake:3611 (get_property):
>   get_property could not find TARGET re2.  Perhaps it has not yet been
>   created.
> Call Stack (most recent call first):
>   /usr/share/cmake-3.27/Modules/ExternalProject.cmake:3793 (_ep_get_file_deps)
>   /usr/share/cmake-3.27/Modules/ExternalProject.cmake:4348 (_ep_add_configure_command)
>   CMakeLists.txt:212 (ExternalProject_Add)
> 
> ESC[0m
> ESC[31mCMake Error at /usr/share/cmake-3.27/Modules/ExternalProject.cmake:3616 (get_property):
>   get_property could not find TARGET re2.  Perhaps it has not yet been
>   created.
> Call Stack (most recent call first):
>   /usr/share/cmake-3.27/Modules/ExternalProject.cmake:3793 (_ep_get_file_deps)
>   /usr/share/cmake-3.27/Modules/ExternalProject.cmake:4348 (_ep_add_configure_command)
>   CMakeLists.txt:212 (ExternalProject_Add)
> 
> ESC[0m
> ESC[31mCMake Error at /usr/share/cmake-3.27/Modules/ExternalProject.cmake:1843 (get_property):
>   get_property could not find TARGET re2.  Perhaps it has not yet been
>   created.
> Call Stack (most recent call first):
>   /usr/share/cmake-3.27/Modules/ExternalProject.cmake:2155 (ExternalProject_Get_Property)
>   /usr/share/cmake-3.27/Modules/ExternalProject.cmake:3621 (_ep_get_step_stampfile)
>   /usr/share/cmake-3.27/Modules/ExternalProject.cmake:3793 (_ep_get_file_deps)
>   /usr/share/cmake-3.27/Modules/ExternalProject.cmake:4348 (_ep_add_configure_command)
>   CMakeLists.txt:212 (ExternalProject_Add)
> 
> ESC[0m
> ESC[31mCMake Error at /usr/share/cmake-3.27/Modules/ExternalProject.cmake:1845 (message):
>   External project "re2" has no stamp_dir
>     External project "re2" has no stamp_dir
> Call Stack (most recent call first):
>   /usr/share/cmake-3.27/Modules/ExternalProject.cmake:2155 (ExternalProject_Get_Property)
>   /usr/share/cmake-3.27/Modules/ExternalProject.cmake:3621 (_ep_get_step_stampfile)
>   /usr/share/cmake-3.27/Modules/ExternalProject.cmake:3793 (_ep_get_file_deps)
>   /usr/share/cmake-3.27/Modules/ExternalProject.cmake:4348 (_ep_add_configure_command)
>   CMakeLists.txt:212 (ExternalProject_Add)
> 
> ESC[0m
> -- Configuring incomplete, errors occurred!
> Building Triton Inference Server
> platform linux

I did try to use r23.12 to check if that would work but there I get different error:
`python3 ./build.py -v --backend onnxruntime --backend openvino --container-version 23.12 2>&1 | tee build_log_verbose_23.12

> ERROR: failed to solve: executor failed running [/bin/sh -c apt-get update && apt-get install -y --no-install-recommends         software-properties-common         wget         zip         ca-certificates         build-essential         curl         libcurl4-openssl-dev         libssl-dev         patchelf         python3-dev         python3-pip         git         gnupg         gnupg1]: exit code: 100
> make[2]: *** [CMakeFiles/ort_target.dir/build.make:74: onnxruntime/lib/libonnxruntime.so] Error 1
> make[2]: Leaving directory '/tmp/tritonbuild/onnxruntime/build'
> make[1]: *** [CMakeFiles/Makefile2:275: CMakeFiles/ort_target.dir/all] Error 2
> make[1]: Leaving directory '/tmp/tritonbuild/onnxruntime/build'
> make: *** [Makefile:136: all] Error 2
> Building Triton Inference Server
> platform linux
> machine x86_64
> version 2.41.0
> build dir /home/atobisze/git_repos/triton/triton_server/build
> install dir None
> cmake dir None
> default repo-tag: r23.12
> container version 23.12
> upstream container version 23.12
> backend "onnxruntime" at tag/branch "r23.12"
> backend "openvino" at tag/branch "r23.12"
> component "common" at tag/branch "r23.12"
> component "core" at tag/branch "r23.12"
> component "backend" at tag/branch "r23.12"
> component "thirdparty" at tag/branch "r23.12"
> error: build failed

**Comment by dyastremsky** [comment]
Closing due with fix in https://github.com/triton-inference-server/onnxruntime_backend/pull/238.
