### ISSUE TITLE
Add support for Oracle Cloud in deploy

### ISSUE THREAD

**Issue by bruno-garbaccio** [triton-inference-server/server#6849]
There is no documentation yet on how to deploy Triton server on Oracle Cloud via the OKE service. This documentation exists for AWS, GCP and others

Oracle Cloud is S3 compatible. Based on deploy/aws, it is possible to adapt this documentation to support Triton on OKE.

I open this feature Request before proposing a Pull Request with those changes.

**Comment by rmccorm4** [comment]
Hi @bruno-garbaccio, thanks for filing this - I left a comment on the PR.

**Comment by bruno-garbaccio** [comment]
https://github.com/triton-inference-server/server/pull/6850 is merded
