### ISSUE TITLE
can't connect to azure for reading model registry 

### ISSUE THREAD

**Issue by ksokolov-vaisto** [triton-inference-server/server#6856]
**Description**
I have built the triton for Jetpack 5.1.2 with -DTRITON_ENABLE_AZURE_STORAGE=ON
to be able to offload the model repository to azure blob storage. I have followed the instructions and provided the correct storage account name and key. When launching the server it quits immediately with the following error
```
I0201 11:37:57.308434 166336 server.cc:301] No server context available. Exiting immediately.
error: creating server: Internal - Failed to check if directory at as://my-storage-account/model-repository/model_repository_test/:401 Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
```
I tried to manually query the container using a python script to construct the headers for the auth request in the same environment. The script used the same account name and key and was able to read the container contents successfully. 

**Triton Information**
built from r23.06-update-1-jp

Are you using the Triton container or did you build it yourself?
built myself

**To Reproduce**
build the r23.06-update-1-jp with -DTRITON_ENABLE_AZURE_STORAGE=ON, try setting the model repository to reside in azure storage following the instructions.

**Comment by rmccorm4** [comment]
Hi @ksokolov-vaisto, thanks for raising this. 

@kthui are you aware of any issues with the Azure auth or missing steps here?

**Comment by ksokolov-vaisto** [comment]
> Hi @ksokolov-vaisto, thanks for raising this.
> 
> > I have followed the instructions and provided the correct storage account name and key
> 
> Can you elaborate on the exact steps you took?
> 
> CC @kthui are you aware of any issues with the Azure auth or missing steps here?

I've set AZURE_STORAGE_ACCOUNT and AZURE_STORAGE_KEY env variables with my Azure storage account name and access key, respectively.  then launched the tritonserver app with `--model-repository as://my-storage-account/model-repository/model_repository_test`

**Comment by dyastremsky** [comment]
Are you able to try to use a more recent version of Triton to see if you still see this potential bug? Do you see this on the official Jetpack release as well? What is the operating system?

**Comment by ksokolov-vaisto** [comment]
> Are you able to try to use a more recent version of Triton to see if you still see this potential bug? 

I am using Jetson AGX Xavier, running jetpack 5.1.2, I guess newer releases support the Orin family only?

> Do you see this on the official Jetpack release as well? 

not sure what you mean, if it is about the prebuilt binaries, I think they come without azure extension. Actually now reading the releases notes closer, I see that in every jetpack release there is this line
>GPU metrics, GCS storage, S3 storage and Azure storage are not supported.

Does this apply to binaries only or does it mean that it is impossible also to **build** Triton for jetpack with azure support? 

> What is the operating system?

L4T R35.4.1

**Comment by dyastremsky** [comment]
> > Are you able to try to use a more recent version of Triton to see if you still see this potential bug?
> 
> I am using Jetson AGX Xavier, running jetpack 5.1.2, I guess newer releases support the Orin family only?
> 
> > Do you see this on the official Jetpack release as well?
> 
> not sure what you mean, if it is about the prebuilt binaries, I think they come without azure extension. Actually now reading the releases notes closer, I see that in every jetpack release there is this line
> 
> > GPU metrics, GCS storage, S3 storage and Azure storage are not supported.
> 
> Does this apply to binaries only or does it mean that it is impossible also to **build** Triton for jetpack with azure support?
> 
> > What is the operating system?
> 
> L4T R35.4.1

Good find. I expect that means Triton does not support Azure storage on Jetpack even if you are building it. It would need to be developed and supported as a feature, so it likely has either been deprioritized or has hardware limitations. You are welcome to contribute it to the Jetson build though.

CC: @nv-kmcgill53 @kthui
