### ISSUE TITLE
How does Triton implement batch inference

### ISSUE THREAD

**Issue by lyc728** [triton-inference-server/server#6863]
In the [TensorRT-LLM](https://github.com/NVIDIA/TensorRT-LLM) build.py
`parser.add_argument('--max_batch_size', type=int, default=10)`

However, when Triton calls the code, `client/inflight_batcher_llm_client.py`,
it sends grpc requests at the same time, accepts them and returns them. How does it implement batch requests based on the service level? I'm guessing it's time to block, then splice the requests, and then return at the same time?

**Comment by rmccorm4** [comment]
Hi @lyc728, the TensorRT LLM backend specifically implements Inflight Batching in the backend itself, assuming it is configured to do so with something like `gpt_model_type: "inflight_fused_batching"` in the `tensorrt_llm` model's `config.pbtxt`.

What this means is that the backend maintains its own queue and executes requests in generative loops, where at each step it evaluates if any request in the batch has finished, and adds a new request if available to fill the empty batch slot.

For this case, it is generally best to let Triton just forward requests to the TRT LLM backend as quickly as possible without trying to do any special kinds of batching in the Triton core/server logic.

The `--max_batch_size` argument for building the TRT LLM engine helps to refer to the max batch of requests that could be executed at once, whether by inflight batching individual requests together, or executing a static batch given upfront.

Hope this helps.

**Comment by rmccorm4** [comment]
Some of these concepts, relevant config parameters, and relevant metrics are described in the TRT LLM backend repo as well: https://github.com/triton-inference-server/tensorrtllm_backend?tab=readme-ov-file#modify-the-model-configuration

**Comment by lyc728** [comment]
Hello, thank you for your reply. When I use triton here, I conducted a multi-threaded concurrent request here, and found that triton added inflighting batch or V1 in the configuration, and the time was almost unchanged.

**Comment by lyc728** [comment]
I also have a question when I use the triton directly (gpt type as V1). Can it play an accelerated role compared to trt-llm? Where is it embodied?

**Comment by dyastremsky** [comment]
The Triton TRT-LLM backend is a Triton backend. You can use other backends for your needs, but TRT-LLM is developed to have bleeding-edge performance for most use cases. You can also use TRT-LLM without Triton, but you lose the benefits of Triton (e.g. ease of use, ability to easily test and get performance metrics for different configurations, ability to run models with different backends/frameworks in one place, etc.)
