### ISSUE TITLE
gRPC response is cropped, where REST /generate fully sent

### ISSUE THREAD

**Issue by mkhludnev** [triton-inference-server/server#6864]
Hello, 
I use triton with vLLM model. For some reason vLLM backend prepends response with prompt. Don't know why, [asked here](https://github.com/triton-inference-server/vllm_backend/pull/31). 
As a result of RAG approach I've got really long responses. The problem is that REST /generate return long response fully, and gRPC crops long response at certain length. I'm using python gRPC client, but I witness cropping in verbose log. 
More details, excepts from configs and logs are [here](https://github.com/langchain-ai/langchain/issues/12474#issuecomment-1925914483).

**Comment by mkhludnev** [comment]
Sure. 
curl got 200 words [rest-triton.txt](https://github.com/triton-inference-server/server/files/14301464/rest-triton.txt)
gRPC takes only 20 [grpc-triton.txt](https://github.com/triton-inference-server/server/files/14301462/grpc-triton.txt)
I use [langchain module](https://github.com/langchain-ai/langchain/blob/master/libs/partners/nvidia-trt/langchain_nvidia_trt/llms.py) as a client. 
Here's the model for vllm_bacnkend
[model.json](https://github.com/triton-inference-server/server/files/14301552/model.json)
[config.pbtxt.txt](https://github.com/triton-inference-server/server/files/14301559/config.pbtxt.txt)
 
I'm trying to find a brief reproducer but it's tough to a noob like myself.

**Comment by oandreeva-nv** [comment]
Thank you! I think this should be enough for now.

**Comment by mkhludnev** [comment]
Pardon https://github.com/triton-inference-server/vllm_backend/pull/34

**Comment by oandreeva-nv** [comment]
Thanks for providing solution!
