### ISSUE TITLE
Optimizing ASR Streaming: Implementing Continuous Audio Processing for Uninterrupted Response

### ISSUE THREAD

**Issue by rizwanishaq** [triton-inference-server/server#6865]
Operate an ASR streaming server using sequence batching.
Receive audio samples every 10 milliseconds and accumulate them until a period of silence is detected.
Send gathered audio samples to the ASR model for processing.
The ASR model takes around 1 second to complete its analysis.
Aim to implement a continuous streaming mechanism.
Send a request to the ASR model.
Continue receiving and accumulating audio samples without waiting for the model's response.
Seek a solution or approach to achieve uninterrupted streaming.

**Comment by rizwanishaq** [comment]
I currently employ sequence batching, but the challenge lies in the 1-second processing period where I encounter a delay. How can I seamlessly continue receiving audio packets without interruption during this time?

**Comment by Jank14** [comment]
Hey, I am trying to do something similar. I am very new to this. Can you please help me understand how are u streaming audio to your triton inference server?Are u using websocket or something to stream it the server. Can you please help me with your solution architecture

**Comment by Jank14** [comment]
Thanks a lot for reply. Will check the above link. Majorly I wanted to check is the client file above will receive the audio stream from websocket and when the requests are accumulated the server would process them and output would be sent back to client and from there through some mechanism back to the device where the stream is generated? Sorry if I am wrong but I am new to it and just want to understand proper flow

**Comment by dyastremsky** [comment]
Why can't the model continue receiving requests while it is processing a request? What is the specific issue?

It sounds like this may not be a Triton issue. Triton can handle you continuing to send audio to it (you even have the option to use multiple sequence batcher slots), but if you are saying you want to manage traffic between your clients and asking how to do so, then that would be a design decision for your software.

**Comment by dyastremsky** [comment]
Wonderful! Thank you for updating us with your solution.
