### ISSUE TITLE
vllm-backend exclude_input_in_output flag whether prepend output with prompt

### ISSUE THREAD

**Issue by mkhludnev** [triton-inference-server/server#6866]
**Description**
vllm-backend [concatenates the prompt and the output](https://github.com/triton-inference-server/vllm_backend/pull/31/files) before responding.

1. it just seems verbose and redundant since client already have the prompt which was submitted. It especially odd with RAG-approach where prompts are so long. 
2. along side with #6864 it makes gRPC interface useless. 

**Triton Information**
Are you using the Triton container or did you build it yourself?

`nvcr.io/nvidia/tritonserver:23.11-vllm-python-py3`

**To Reproduce**
Steps to reproduce the behavior. 

1. I run Notus7b under triton+vLLM in docker 
2. `curl POST  :8000/v2/models/vllm_model/generate`
3. Then run a sample [langchain app](https://github.com/langchain-ai/langchain/blob/master/libs/partners/nvidia-trt/langchain_nvidia_trt/llms.py) which uses gRPC `:8001` and watch verbose logs
4. Actual: both responses have [prompt prepended,](https://github.com/langchain-ai/langchain/issues/12474#issuecomment-1925914483) gRPC response in verbose log is cropped  #6864 
```
backend: "vllm"

# Disabling batching in Triton, let vLLM handle the batching on its own.
max_batch_size: 0


# We need to use decoupled transaction policy for saturating
# vLLM engine for max throughtput.
model_transaction_policy {
  decoupled: True
}
# Note: The vLLM backend uses the following input and output names.
# Any change here needs to also be made in model.py
input [
  {
    name: "text_input"
    data_type: TYPE_STRING
    dims: [ 1 ]
  },
  {
    name: "stream"
    data_type: TYPE_BOOL
    dims: [ 1 ]
  },
  {
    name: "sampling_parameters"
    data_type: TYPE_STRING
    dims: [ 1 ]
    optional: true
  }
]

output [
  {
    name: "text_output"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]

# The usage of device is deferred to the vLLM engine
instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]

model.json
{
    "model":"TheBloke/notus-7B-v1-AWQ",
    "disable_log_requests": "true",
    "gpu_memory_utilization": 0.7,
    "max_model_len": 4096,
    "quantization": "awq"
}
```

**Expected behavior**
There are no prompt in vLLM response that makes  #6864 less painful.

**Comment by mkhludnev** [comment]
Considering https://github.com/triton-inference-server/server/discussions/6867 it's worth to implement `echo=False` option for vlm and trt backends.

**Comment by mkhludnev** [comment]
up https://github.com/triton-inference-server/server/discussions/6867#discussioncomment-8460209

> trt-llm backend has exclude_input_in_output flag, that controls prompt concatenation. We will add same flag to vLLM soon

**Comment by dyastremsky** [comment]
Thank you for this enhancement request! We have a ticket tracking this request.

Ref: 6137

**Comment by dyastremsky** [comment]
This has been implemented in https://github.com/triton-inference-server/vllm_backend/pull/35. Closing this issue.
