### ISSUE TITLE
 Attempt to use the C++ gRPC client to send an image to a Triton server with a YOLOv8 model

### ISSUE THREAD

**Issue by lawliet0823** [triton-inference-server/server#6870]
I am running Triton Server (including a YOLOv8 model) on a different machine (Ubuntu 20.04) using Docker. When executing the following code, I receive an error message. How should I address this issue?

Error: Inference failed: parameter keys starting with 'triton_' are reserved for Triton usage and should not be specified.

The code is being run on Ubuntu 22.04 using WSL2.

`#include <opencv2/opencv.hpp>
#include <opencv2/highgui.hpp>
#include <string>
#include "ImageClient.h"

namespace tc = triton::client;

#define FAIL_IF_ERR(X, MSG)                                              \
    {                                                                    \
        tc::Error err = (X);                                             \
        if (!err.IsOk())                                                 \
        {                                                                \
            std::cerr << "error: " << (MSG) << ": " << err << std::endl; \
            exit(1);                                                     \
        }                                                                \
    }

void clientSendImage(const cv::Mat& image)
{
    const std::string url("192.168.1.228:8001");
    const std::string model_name("TensorRT");

    std::unique_ptr<tc::InferenceServerGrpcClient> grpcClient;
    tc::Error err;

    err = tc::InferenceServerGrpcClient::Create(&grpcClient, url, false);
    if (!err.IsOk())
    {
        std::cerr << "Error creating grpc client: " << err << std::endl;
        exit(1);
    }

    tc::InferInput* input;
    const std::string input_name = "images";
    const std::vector<int64_t> input_shape = {1, 3, 640, 640}; 
    std::vector<tc::InferInput*> inputs;
    std::vector<const tc::InferRequestedOutput*> outputs;

    tc::InferOptions options(model_name);
    options.model_version_ = "1";

    err = tc::InferInput::Create(&input, input_name, input_shape, "FP32");
    if (!err.IsOk())
    {
        std::cerr << "Error: Creating input failed: " << err << std::endl;
        exit(1);
    }

    if (image.empty()) {
        std::cerr << "Error: Unable to read image! " << std::endl;
        exit(1);
    }

    cv::Mat resized_image;
    cv::resize(image, resized_image, cv::Size(640, 640));
    cv::cvtColor(resized_image, resized_image, cv::COLOR_BGR2RGB);

    std::vector<float> input_data;
    std::vector<cv::Mat> channels(3);
    cv::split(resized_image, channels);
    for (auto& ch : channels) {
        std::vector<float> img_data(ch.reshape(1, 1));
        input_data.insert(input_data.end(), img_data.begin(), img_data.end());
    }

    err = input->AppendRaw(reinterpret_cast<const uint8_t*>(input_data.data()), input_data.size() * sizeof(float));
    if (!err.IsOk()) {
        std::cerr << "Error: Setting input data failed: " << err << std::endl;
        exit(1);
    }
    inputs.push_back(input);

    tc::InferRequestedOutput* output;
    const std::string output_name = "output0";
    err = tc::InferRequestedOutput::Create(&output, output_name);
    if (!err.IsOk()) {
        std::cerr << "Error: Creating output failed: " << err << std::endl;
        exit(1);
    }
    outputs.push_back(output);

    tc::InferResult* result;
    err = grpcClient->Infer(&result, options, inputs, outputs);
    if (!err.IsOk()) {
        std::cerr << "Error: Inference failed: " << err << std::endl;
        exit(1);
    }

    delete result;
}

int main() {

    cv::Mat image = cv::imread("test.jpg");
    clientSendImage(image);

    return 0;
}`

**Comment by nnshah1** [comment]
Just to confirm - which versions of Triton / client / etc. are you using?

**Comment by lawliet0823** [comment]
The Docker environment I am using is nvcr.io/nvidia/tritonserver:23.12-py3. 
The includes and libraries for the client are sourced from v2.41.0_ubuntu2204.clients.tar.gz.

**Comment by nnshah1** [comment]
Was the issue resolved? Can you update here with the resolution (I think it could help others, and maybe there is something we can do to make the error easier to resolve)

**Comment by lawliet0823** [comment]
The issue remains unresolved. Later, I sent a request to myself on the local machine. This problem might still require official investigation.

**Comment by chinderks** [comment]
Hello! Checking to see if this issue has potentially been resolved a year later. I'm experiencing a similar issue.
