### ISSUE TITLE
Compiling Triton Inference Server

### ISSUE THREAD

**Issue by wolfgangsmdt** [triton-inference-server/server#6876]
Hello NVIDIA,

**PLEASE KINDLY READ ALL THIS THREAD BEFORE ANSWERING ME**.

I would like to compile Triton inference server on my PC (***Ubuntu 22.04, x86 machine***) and get after that the shared library (.so) so I can run it on other platforms like *raspberry*, *jetson*, *arm64*, *aarch64*, *etc*. (cross compiling)

If I am not mistaken, there is two main methods, with and without docker.
I tried both and here is my resume.

**Without docker** [here](https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/customization_guide/build.html#building-without-docker) FAILED with lacking of dependencies even if I followed the official guide [here](https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/customization_guide/build.html#building-without-docker) 

**With docker** [here](https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/customization_guide/build.html#building-with-docker) SUCCEED after running it on an enormous CPU with 64GB of RAM other wise it will not be able to compile ***it demands a lot of resources***. Is that normal?

ALL what I did is to clone and build using the `build.py` script (as the official documentation promote to) after that nothing is clear to me on how to be able to run it on other devices like raspbarry pi or jetson devices, _etc_. 

another thing [here](https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/customization_guide/build.html#building-for-jetpack-4-x) in this section of building it for jetson is not completed yet!

And [here](https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/examples/jetson/README.html) you told us developers/users to follow the installation instructions of the git repo releases [here](https://github.com/triton-inference-server/server/releases/) So where are the instructions? I am missing something?
You said as well 
> In our example, we placed the contents of downloaded release directory under `/opt/tritonserver`.

What contents? is it the extracted tar file or the content of the compiled build directory? On what platform? 

Please, could you provide me the instructions step by step on : 
1. How to compile on my PC (Ubunru 22.04 x86 machine) (cross-compile) Triton Inference Server and get the shared library.
2. How to be able to run Triton Inference Server on raspberry, jetson, etc. using the shared library compiled on my PC in question 1.

Thank you.

**Comment by kthui** [comment]
@nv-kmcgill53 @mc-nv do you know if it is possible to compile the ARM version of Triton (i.e. for raspberry, jetson, ...) on a x86 machine?

**Comment by mc-nv** [comment]
It should be possible to compile on `x86` to obtain `arm64` binaries as long as all necessary dependencies are been satisfied.

> [!Tip]
> Customer may try to use [docker QEMU emulator](https://docs.docker.com/build/building/multi-platform/#qemu) for such purpose.

**Comment by wolfgangsmdt** [comment]
Thank you for your answers @kthui and @mc-nv ,
In the build.py script there is an option for platform architecture aarch64, but the script must run on the target platform.

However, compiling on the jetson (natively) will end up saturating the RAM usage and rebooting the board. I believe it is still under development and this is the reason why this section [here](https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/customization_guide/build.html#building-for-jetpack-4-x) about compiling for jetson devices is empty.

If you have any other suggestions simpler than docker QEMU which is not 100% sure it will works I will be happy.

**Comment by kthui** [comment]
> In the build.py script there is an option for platform architecture aarch64, but the script must run on the target platform.

You can change the script if some checks are blocking you from moving forward with the build.

> compiling on the jetson (natively) will end up saturating the RAM usage and rebooting the board

We usually build it on ARM machines. If you have an Apple Silicon machine, maybe you can try it there. Otherwise, the docker QEMU emulator seems to be the way to go.

**Comment by wolfgangsmdt** [comment]
hello @kthui @mc-nv

Just to give you an update.

docker QEMU emulator was my only option and it did worked after installing all the needed dependencies and it took a lot of time to compile using 24 CPUs.

However, the backends failed. The problem is that the build.py script does not provide the arm64 backend so it failed with the error of `collect2: error: ld returned 1 exit status` which I believe for x86 and not for amr64/aarch64 architechture.

So now, I am trying to find a way to compile the backends for arm64/aarch64 architechture. If you have any suggestions feel, I will be happy.  : )

**Comment by wolfgangsmdt** [comment]
Hello @kthui and  @mc-nv 

I cannot compile triton with --enable-gpu option in docker QEMU. because there is no CUDA for arm64.
Here below is my error:
```bash
CMake Error at /usr/share/cmake-3.27/Modules/FindCUDA.cmake:883 (message):
  Specify CUDA_TOOLKIT_ROOT_DIR
Call Stack (most recent call first):
  CMakeLists.txt:6 (find_package)
```

Here below is my command to compile in docker QEMU, (_**I am compiling without docker as docker cannot run inside docker with diferent architechture, so I cannot forward the docker.sock)**_
```bash
./build.py --target-platform linux --target-machine aarch64 -j 12 --enable-logging --enable-stats --enable-metrics --enable-gpu-metrics --enable-cpu-metrics --enable-tracing --enable-nvtx --enable-gpu --enable-mali-gpu  --endpoint grpc -v --no-container-build --build-dir /home/qemu/build_triton_all/triton_onnxruntime/server/build --backend onnxruntime
```

Here below is my docker QEMU envirement:
```bash
Linux 2c1b2a62f0a8 6.5.0-18-generic #18~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Feb  7 11:40:03 UTC 2 aarch64 aarch64 aarch64 GNU/Linux
```


Thank you

**Comment by wolfgangsmdt** [comment]
Hello @kthui  @mc-nv  @dyastremsky 

Actually, you cannot compile full Triton and its backends with docker QEMU.
You cannot compile it neither on target hardware like raspberry or jetson nano device.

the problem is that it needs a lot of ressources (RAM, CPU core/threads) to compile only Triton, then for the backends you need docker to compile them see [here](https://github.com/triton-inference-server/onnxruntime_backend/blob/0825c357a226c9e4657a24895302557a211b13d8/CMakeLists.txt#L320) https://github.com/triton-inference-server/onnxruntime_backend/blob/0825c357a226c9e4657a24895302557a211b13d8/CMakeLists.txt#L320

So you need to forward the docker.sock into docker QEMU, but this is not going to work as docker.sock is for my host x86 machine, therefore, you cannot full compile Triton.

Could you please confirm me that? @kthui @dyastremsky @mc-nv 

Thank you : )

**Comment by vyrsh** [comment]
has there been any developments on this? I have a device which is similar to a jetson, with aarch64 configuration. 

I can see that section for compiling on jetson devices is still empty.
why doesn't nvidia provide a docker image for aarch64 images?
