### ISSUE TITLE
vllm backend - logit probabilities at inference

### ISSUE THREAD

**Issue by HalteroXHunter** [triton-inference-server/server#6895]
regarding the current vllm backend: https://github.com/triton-inference-server/vllm_backend/tree/main

I wanted to know if at inference there is a possibility of also getting the logit probabilities, not only the generated tokens.

for example in TRT this seems possible: https://github.com/triton-inference-server/tensorrtllm_backend#:~:text=Input%20sequence%3A%20%20%5B28524,10.556551%20%20%20%209.685863%0A%20%20%20%20%20%2019.625107%5D%5D%5D%5D

Please help :)

**Comment by dyastremsky** [comment]
No, the vLLM backend runs vLLM under the hood. So you could only do it if vLLM lets you output logit probabilities. See this vLLM thread: https://github.com/vllm-project/vllm/issues/185

**Comment by HalteroXHunter** [comment]
great, thanks!
