### ISSUE TITLE
can get the nvidia-smi information but cannot detect available GPU device.

### ISSUE THREAD

**Issue by chiehpower** [triton-inference-server/server#6903]
**Description**
Now I have a laptop, the spec is quite new. Using RTX4070, 32 GB RAM memory and has 24 CPU cores. 
When I start the Triton server, it cannot detect the GPU device. However, when I access to that container, I can check the GPU driver information (by `nvidia-smi` command).

![2024-02-22_13-43](https://github.com/triton-inference-server/server/assets/32332200/af6001b7-8447-4ff5-a9ce-e6cbdca73357)

Here is the CPU information
![2024-02-22_13-43_1](https://github.com/triton-inference-server/server/assets/32332200/39331721-d45c-484c-861a-8286fe59a058)

GPU driver version is **535.154.05**

**Triton Information**
Using **v23.02**

Are you using the Triton container or did you build it yourself?
Container.

**To Reproduce**
Cannot reproduce.

**Expected behavior**
Triton can detect the GPU device.

This problem seems to occur frequently on brand-new laptops. I'm wondering what other settings I should check and how I can resolve it. Your suggestions would be greatly appreciated.
Thank you.

**Comment by oandreeva-nv** [comment]
Please refer to [support matrix](https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html). According to support matrix, 23.02 version does not support 535 version of the driver. I belive this driver is supported in v 23.08 and later

**Comment by chiehpower** [comment]
Thank you for your information! 
Here is the log from Triton v23.08 container. Seems work fine.
![2024-02-27_14-12](https://github.com/triton-inference-server/server/assets/32332200/aedc6f52-e3d0-408c-986c-7fab4a00450f)

**Comment by chiehpower** [comment]
hi @oandreeva-nv 

After I deployed a model, but encountered this error. And then the container was dead.
![2024-02-29_08-54](https://github.com/triton-inference-server/server/assets/32332200/765f6c4d-5aab-4f0c-8830-68c7121fa48b)
