### ISSUE TITLE
Multi Instance Execution Does Not Improve Throughput for YOLOv8 Model

### ISSUE THREAD

**Issue by langong347** [triton-inference-server/server#6908]
**Description**
I use Triton through KServe to deploy YOLOv8 model with dynamic batching and multi-instance execution enabled.

I notice that using 2 model instances only marginally improves throughput. Since the triton perf analyzer is not available to me, I use `hey` to measure the latency/throughput before/after increasing the model instances and read my resource utilization from a graphana dashboard associated with my deployment framework.

A similar issue can be found here #3066.

**Triton Information**
23.12

Are you using the Triton container or did you build it yourself?
I am using Triton through KServe which provides the container.

**To Reproduce**
Deploy the ONNX model of YOLOv8 with two replicas, each contains a single T4 GPU

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
- YOLOv8 Model in ONNX format
- config.pbtxt:
```
platform: "onnxruntime_onnx"
max_batch_size: 8
input [
  {
    name: "images"
    data_type: TYPE_FP32
    dims: [ 3, -1, -1 ]
  }
]
output [
  {
    name: "output0"
    data_type: TYPE_FP32
    dims: [ -1, -1 ]
  }
]
 dynamic_batching {
 	max_queue_delay_microseconds: 20000
 }
 instance_group [
   {
     count: 2
     kind: KIND_GPU
   }
 ]
```

**Expected behavior**
Using two instances should significantly improve the throughput without impacting latency too much.

Below is a list of experiments by sending 1000 requests to my service endpoint at concurrency level  `c=1, 2, 5, 10, 20, 50` for model instance 1 and 2.

Model instance = 1
```
# c = 1
   Total:        11.3171 secs
   Slowest:      0.1655 secs
   Fastest:      0.1011 secs
   Average:      0.1132 secs
   Requests/sec: 8.8362

# c = 2
Total:        10.0818 secs
   Slowest:      0.2255 secs
   Fastest:      0.0830 secs
   Average:      0.1001 secs
   Requests/sec: 19.8377

# c = 5
 Total:        12.3119 secs
   Slowest:      0.2220 secs
   Fastest:      0.0810 secs
   Average:      0.1200 secs
   Requests/sec: 40.6112

# c = 10
 Total:        16.6449 secs
   Slowest:      0.3462 secs
   Fastest:      0.0844 secs
   Average:      0.1636 secs
   Requests/sec: 60.0786

# c = 20
 Total:        14.9312 secs
   Slowest:      0.5636 secs
   Fastest:      0.0869 secs
   Average:      0.2920 secs
   Requests/sec: 66.9737

# c = 50
 Total:        14.8280 secs
   Slowest:      1.1955 secs
   Fastest:      0.0930 secs
   Average:      0.7206 secs
   Requests/sec: 67.4398
```

Model instances = 2
```
c = 1
Total:        11.0247 secs
   Slowest:      0.1277 secs
   Fastest:      0.0989 secs
   Average:      0.1102 secs
   Requests/sec: 9.0705

c = 2
 Total:        10.8996 secs
   Slowest:      0.1914 secs
   Fastest:      0.0859 secs
   Average:      0.1087 secs
   Requests/sec: 18.3493

c = 5
 Total:        13.2817 secs
   Slowest:      0.2476 secs
   Fastest:      0.0814 secs
   Average:      0.1279 secs
   Requests/sec: 37.6459

c = 10
Total:        19.4423 secs
   Slowest:      0.5300 secs
   Fastest:      0.0837 secs
   Average:      0.1882 secs
   Requests/sec: 51.4342

c = 20
   Total:        15.9425 secs
   Slowest:      0.5783 secs
   Fastest:      0.0847 secs
   Average:      0.3078 secs
   Requests/sec: 62.7255

c = 50
   Total:        14.2107 secs
   Slowest:      1.1725 secs
   Fastest:      0.1462 secs
   Average:      0.6919 secs
   Requests/sec: 70.3695
```

I noticed that at higher concurrency levels my GPU core utilization could reach anywhere between 90 - 100%, which might have halved the performance of each model instance. I suspect enabling dynamic batching was sufficient to saturate GPU utilization making multi-instance execution unnecessary.....

Also, we may rule out issues due to GPU memory as running two instances only took 5 GB out of 16GB total for my GPU.

I want to know if my understanding is correct, and whether you have further insights into the proper usage of multi-instance execution.

Thank you.

cc @GuanLuo  @tanmayv25

**Comment by dyastremsky** [comment]
Your understanding is correct. Increasing instance count is not guaranteed to improve throughput and can even result in decreased throughput, e.g. due to GPU saturation.

Since you stated that perf analyzer is not available to you, you may also not be able to use [Model Analyzer](https://github.com/triton-inference-server/model_analyzer), but that tool is a great way to test different combinations to identify what results in maximal throughput for your model and hardware.
