### ISSUE TITLE
Persistent timeout problems with triton http client

### ISSUE THREAD

**Issue by secain** [triton-inference-server/server#6909]
**Description**

The online service is experiencing persistent timeout problems(unevenly occurring once every few minutes).

`error_msg: Traceback (most recent call last):\n File \"/home/risk-ai/comment_understand/comment_politics.py\", line 28, in post\n results, runtime = comment_processor.get_results(text)\n File \"/home/risk-ai/comment_understand/comment_process.py\", line 29, in get_results\n triton_results, runtime = self.infere_client.predict(inputs, outputs)\n File \"/home/risk-ai/server_triton.py\", line 64, in predict\n timeout=self.timeout)\n File \"/usr/local/lib/python3.6/dist-packages/tritonclient/http/_client.py\", line 1472, in infer\n query_params=query_params)\n File \"/usr/local/lib/python3.6/dist-packages/tritonclient/http/_client.py\", line 286, in _post\n headers=headers)\n File \"/usr/local/lib/python3.6/dist-packages/geventhttpclient/client.py\", line 272, in post\n return self.request(METHOD_POST, request_uri, body=body, headers=headers)\n File \"/usr/local/lib/python3.6/dist-packages/geventhttpclient/client.py\", line 254, in request\n block_size=self.block_size, method=method.upper(), headers_type=self.headers_type)\n File \"/usr/local/lib/python3.6/dist-packages/geventhttpclient/response.py\", line 292, in __init__\n super(HTTPSocketPoolResponse, self).__init__(sock, **kw)\n File \"/usr/local/lib/python3.6/dist-packages/geventhttpclient/response.py\", line 164, in __init__\n self._read_headers()\n File \"/usr/local/lib/python3.6/dist-packages/geventhttpclient/response.py\", line 184, in _read_headers\n data = self._sock.recv(self.block_size)\n File \"/usr/local/lib/python3.6/dist-packages/gevent/_socketcommon.py\", line 663, in recv\n self._wait(self._read_event)\n File \"src/gevent/_hub_primitives.py\", line 317, in gevent._gevent_c_hub_primitives.wait_on_socket\n File \"src/gevent/_hub_primitives.py\", line 322, in gevent._gevent_c_hub_primitives.wait_on_socket\n File \"src/gevent/_hub_primitives.py\", line 313, in gevent._gevent_c_hub_primitives._primitive_wait\n File \"src/gevent/_hub_primitives.py\", line 314, in gevent._gevent_c_hub_primitives._primitive_wait\n File \"src/gevent/_hub_primitives.py\", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait\n File \"src/gevent/_hub_primitives.py\", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait\n File \"src/gevent/_hub_primitives.py\", line 55, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait\n File \"src/gevent/_waiter.py\", line 154, in gevent._gevent_c_waiter.Waiter.get\n File \"src/gevent/_greenlet_primitives.py\", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch\n File \"src/gevent/_greenlet_primitives.py\", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch\n File \"src/gevent/_greenlet_primitives.py\", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch\n File \"src/gevent/_gevent_c_greenlet_primitives.pxd\", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch\nsocket.timeout: timed out\n"
`
**Triton Information**
What version of Triton are you using?
OS：
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"

Python 3.6.9
tritonclient  2.36.0

Are you using the Triton container or did you build it yourself?
container: nvcr.io/nvidia/tritonserver:22.05-py3

**To Reproduce**
Unable to reproduce this bug in the test environment, it only appears in the online environment.

**Comment by oandreeva-nv** [comment]
Hi @secain , could you please try later version of Triton? The current latest is 24.01 and you are using 22.05, which is quite a bit old.

**Comment by secain** [comment]
> Hi @secain , could you please try later version of Triton? The current latest is 24.01 and you are using 22.05, which is quite a bit old.

my cuda version may not support 24.01. And when  debugged it, i found out when this bug occurring, the `is_server_live()` methed will get timeout too. Dose this means the connection between client and model server is somehow disconnected occasionally ?(ten minutes, usually.)

**Comment by oandreeva-nv** [comment]
@, Could you possibly try 23.10 - 23.12?

**Comment by secain** [comment]
> @, Could you possibly try 23.10 - 23.12?

updated to 24.12 with Triton Server Version 2.41.0, still has the problem.
Now with triton client 2.41.1 and container nvcr.io/nvidia/tritonserver:23.12-py3

**Comment by secain** [comment]
> > @, Could you possibly try 23.10 - 23.12?
> 
> updated to 24.12 with Triton Server Version 2.41.0, still has the problem. Now with triton client 2.41.1 and container nvcr.io/nvidia/tritonserver:23.12-py3

And when I deploy the web service on the same server as the model service, this problem no longer occurs

**Comment by marcozzxx810** [comment]
We are using 24.01 and experienced this problem. We are using BLS python model which asynchronously call ONNX model. 

With log Level 1 and request id, we unable to identify the request is picked up from triton

**Comment by secain** [comment]
> We are using 24.01 and experienced this problem. We are using BLS python model which asynchronously call ONNX model.
> 
> With log Level 1 and request id, we unable to identify the request is picked up from triton

Now I'm testing grpc client, and get this:
```
Traceback (most recent call last):
  File "/home/risk-ai/comment_understand/comment_cls.py", line 28, in post
    results, runtime = comment_processor.get_results(text)
  File "/home/risk-ai/comment_understand/comment_process.py", line 29, in get_results
    triton_results, runtime = self.infere_client.predict(inputs, outputs)
  File "/home/risk-ai/server_grpc.py", line 60, in predict
    client_timeout=10
  File "/usr/local/lib/python3.6/dist-packages/tritonclient/grpc/_client.py", line 1321, in infer
    raise_error_grpc(rpc_error)
  File "/usr/local/lib/python3.6/dist-packages/tritonclient/grpc/_utils.py", line 62, in raise_error_grpc
    raise get_error_grpc(rpc_error) from None
tritonclient.utils.InferenceServerException: [StatusCode.DEADLINE_EXCEEDED] Deadline Exceeded
```

**Comment by oandreeva-nv** [comment]
Hi @secain and @marcozzxx810 , could you please share a minimal reproducer ?

**Comment by secain** [comment]
The cause of the problem can be found at [Idle connections over overlay network ends up in a broken state after 15 minutes](https://github.com/moby/moby/issues/31208)

**Comment by oandreeva-nv** [comment]
Hi @secain , thanks for referencing the cause. Have you solved an issue with Triton by using `keep alive` feature?

**Comment by secain** [comment]
> Hi @secain , thanks for referencing the cause. Have you solved an issue with Triton by using `keep alive` feature?

Hi，I konw there are some keepalive options for grpc client. But what should I do when I'm using http client to control the `keepalive`?
