### ISSUE TITLE
UnicodeError: While deploying telugu asr model with wave2vec2 processorwithlm: try to load on triton server it gives the unicode error ascii' codec can't decode byte 0xe0 in position 0 ordinal not in range(128)

### ISSUE THREAD

**Issue by Jank14** [triton-inference-server/server#6916]
I am trying to use huggingface asr model with processorlm on triton server. The model runs fine and is working correct on local as well as on docker image python repl.But when I try launching the triton server with this model get the unicode error: the unicode error ascii' codec can't decode byte 0xe0 in position 0 ordinal not in range(128) 

This is the python model file I am using to launch the server: 
```
import numpy as np
import triton_python_backend_utils as pb_utils
from transformers import AutoModelForCTC, Wav2Vec2Processor, Wav2Vec2ProcessorWithLM, pipeline
import torch
import sys
import pyctcdecode
import kenlm
import soundfile as sf
# import gradio as gr
import torch.nn.functional as F
import os
os.environ['PYTHONIOENCODING'] = 'utf-8'



class TritonPythonModel:
    def initialize(self, args):
        self.model_id = "jank14/nthtrial"
        self.device_id = "cuda" if torch.cuda.is_available() else "cpu"
        self.DECODER_TYPE = "LM" # Choose "LM" decoding or "greedy" decoding
        self.model_instance = AutoModelForCTC.from_pretrained(self.model_id)
        self.processor = Wav2Vec2ProcessorWithLM.from_pretrained(self.model_id)

    def execute(self, requests):
        responses = []
        for request in requests:
            inp = pb_utils.get_input_tensor_by_name(request, "input")
            #input_image = np.squeeze(inp.as_numpy()).transpose((2, 0, 1))
            input_tensor = self.processor(inp, return_tensors="pt", sampling_rate=16000).input_values
            with torch.no_grad():
                logits = self.model_instance(input_tensor[0]).logits
            output_str = self.processor.batch_decode(logits.numpy(),beam_width = 128,alpha = 0.5).text

            inference_response = pb_utils.InferenceResponse(
                output_tensors=[
                    pb_utils.Tensor(
                        "output", np.array(output_str)
                    )
                ]
            )
            responses.append(inference_response)
        return responses
```

**Comment by fpetrini15** [comment]
Can you please provide full reproduction steps (all commands run) and fill out the bug template below? Thank you!

--

Description
A clear and concise description of what the bug is.

Triton Information
What version of Triton are you using?

Are you using the Triton container or did you build it yourself?

To Reproduce
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

Expected behavior
A clear and concise description of what you expected to happen.

**Comment by Jank14** [comment]
Hey actually got it resolved: The issue was triton not recognising the telugu tokens so ran this in the docker container bash: 
export PYTHONIOENCODING="utf-8"
apt-get clean && apt-get update
apt-get install locales
export LC_ALL="en_US.UTF-8"
locale-gen en_US.UTF-8
Thanks

**Comment by fpetrini15** [comment]
Glad to hear you were able to resolve your issue! Thank you for posting your solution!
