### ISSUE TITLE
In TritonServer, if I use gRPC requests with timeouts set, will the request continue to execute after the timeout?

### ISSUE THREAD

**Issue by SunnyGhj** [triton-inference-server/server#6920]
Firstly, I have a question, will the request continue to execute in Triton Server after the timeout?
Secondly, I believe that if timed-out requests can be abandoned, it will save resources.

**Comment by fpetrini15** [comment]
I believe `timeout` in its current state requires `dynamic_batching` to be enabled to take effect and refers to how long Triton will allow a request to sit in its queue prior to considering it stale and evicting it. The timeout will not apply to inference requests that have begun execution. As such, the server will continue executing the inference request and will send it back to the client.

We already have a ticket open to try to extend this functionality to non-dynamic batching servers.

It seems to me that your expectation is that `timeout` refers to both queue and execution time, such that an inference request that is executing when a timeout would theoretically expire would be cancelled. Is this accurate?

**Comment by SunnyGhj** [comment]
> Hi @SunnyGhj,
> 
> I believe `timeout` in its current state requires `dynamic_batching` to be enabled to take effect and refers to how long Triton will allow a request to sit in its queue prior to considering it stale and evicting it. The timeout will not apply to inference requests that have begun execution. As such, the server will continue executing the inference request and will send it back to the client.
> 
> It seems to me that your expectation is that `timeout` refers to both queue and execution time, such that an inference request that is executing when a timeout would theoretically expire would be cancelled. Is this accurate?

Hi fpetrini15, sorry, I didn't describe the problem clearly. The timeout I'm talking about is the timeout set on the client. For example, when I use rpc requests, I can set deadline
'''
        Deadline deadline = Deadline.after(tfsTimeout, TimeUnit.MILLISECONDS);
        GRPCInferenceServiceGrpc.GRPCInferenceServiceBlockingStub stub = GRPCInferenceServiceGrpc
                .newBlockingStub(channel)
                .withDeadline(deadline);
'''

**Comment by fpetrini15** [comment]
Hi @SunnyGhj,

Thank you for clarifying!

This used to be the case with Triton, however, with the recent addition of request cancellation handling (r23.10), some backends are able to detect that the client deadline has been reached and cancel the request. See [here](https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/user_guide/request_cancellation.html#handling-in-backend) for more information and supported backends.

You can verify this by launching a server in verbose mode, setting an unrealistic value for the deadline, and sending an inference request. You should see logs align the lines of: 
```bash
I0229 01:45:59.868943 7408 infer_handler.cc:985] ModelInferHandler::InferResponseComplete, 5 step CANCELLATION_ISSUED
```

CC @kthui for accuracy or to add more detail.

**Comment by SunnyGhj** [comment]
> Hi @SunnyGhj,
> 
> Thank you for clarifying!
> 
> This used to be the case with Triton, however, with the recent addition of request cancellation handling (r23.10), some backends are able to detect that the client deadline has been reached and cancel the request. See [here](https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/user_guide/request_cancellation.html#handling-in-backend) for more information and supported backends.
> 
> You can verify this by launching a server in verbose mode, setting an unrealistic value for the deadline, and sending an inference request. You should see logs align the lines of:
> 
> ```shell
> I0229 01:45:59.868943 7408 infer_handler.cc:985] ModelInferHandler::InferResponseComplete, 5 step CANCELLATION_ISSUED
> ```
> 
> CC @kthui for accuracy or to add more detail.

Got it, thanks
