### ISSUE TITLE
Will tensorRT backend be compatible with tensorRT 9.1+ ? 

### ISSUE THREAD

**Issue by copasseron** [triton-inference-server/server#6931]
I'm trying to deploy a classifier (Hugging Face model https://huggingface.co/knowledgator/comprehend_it-base ) using Nvidia triton with the tensorRT backend. 

I've followed the steps described here : https://github.com/NVIDIA/TensorRT/tree/main/quickstart/deploy_to_triton. 

The deployment using TensorRT involves three main steps:
	1.	Export the model from Hugging Face to ONNX (Open Neural Network Exchange).
	2.	Construct the TensorRT engine.
	3.	Set up and initiate Triton with the TensorRT backend.

However, with this model is based on the DeBERTaV3-base architecture, which currently faces compatibility issues with TensorRT version 8.6 when trying to build this engine. Nvidia containers 24.01 from NGC are all with tensorRT 8.6. This has been solved with tensorRT 9.
Related issue: NVIDIA TensorRT Issue #3124. . https://github.com/NVIDIA/TensorRT/issues/3124

I've achieved to build the tensorRT engine with building a container with tensorRT 9.2, but the tensorRT for the runtime should be the same than the building one. 
However, tensorRT backend for triton only support tensorRT 8.6, I've tried removing it and installing tensorRT 9.2 in the container but faced multiple problem afterward. 

what would be my best solution here ? 

- Build a custom tensorRT backend for triton with version 9.2 ? 
- Wait for official support of tensorRT 9.1+ inside Nvidia containers ? (might take some time that I don't necessary have)
- Try to install the fix in tensorRT 8.6, and build the engine again ?

**Comment by fpetrini15** [comment]
Hello @copasseron,

@mc-nv do you know if tensorRT 9.XX is on our roadmap in the near-future?

Otherwise, if the fix is successful, I would say option 3 is your best bet.

**Comment by mc-nv** [comment]
I don't believe that the Triton will ever support natively TensorRT 9.x .
I would suggest use of Triton TensorRT LLM image which includes TRT installation version 9

**Comment by fpetrini15** [comment]
Misha's suggestion is a great alternative! Please note, if you go this route, you will need to compile the tensorRT backend in the container yourself as it only ships with the Python and Tensorrt LLM backends.

**Comment by fpetrini15** [comment]
By default, it would seem that the library path is correctly setup. Executing `(IFS=:; set -f; ls -l $LD_LIBRARY_PATH)` in the container shows that the base libraries should be symbolically linked to their corresponding version for TensorRT9.2.

It might help to purge 8.,6 from the container: `apt-get purge "libnvinfer*"`. Though, it's very possible something else breaks when you do this.

**Comment by copasseron** [comment]
Yes

the problem is mainly when I launch the tritonserver it uses the version 8.6 of tensorRT so I get this error, which is to be expected when there is a version mismatch between tensorRT engine and tensorRT runtime version : 

```
E0304 14:05:03.214759 1 logging.cc:40] 6: [runtime.cpp::deserializeCudaEngineEx::123] Error Code 6: Internal Error (TensorRT plan major version does not match runtime major version.Plan version: 9.2, runtime library version: 8.6)

```
however, if I try removing only version 8 with apt-get : 
```
RUN apt-get purge -y --auto-remove libnvinfer-bin=8.6.1.6-1+cuda12.0 \
    libnvinfer-dev=8.6.1.6-1+cuda12.0 \
    libnvinfer-dispatch-dev=8.6.1.6-1+cuda12.0 \
    libnvinfer-dispatch8=8.6.1.6-1+cuda12.0 \
    libnvinfer-headers-dev=8.6.1.6-1+cuda12.0 \
    libnvinfer-headers-plugin-dev=8.6.1.6-1+cuda12.0 \
    libnvinfer-lean-dev=8.6.1.6-1+cuda12.0 \
    libnvinfer-lean8=8.6.1.6-1+cuda12.0 \
    libnvinfer-plugin-dev=8.6.1.6-1+cuda12.0 \
    libnvinfer-plugin8=8.6.1.6-1+cuda12.0 \
    libnvinfer-vc-plugin-dev=8.6.1.6-1+cuda12.0 \
    libnvinfer-vc-plugin8=8.6.1.6-1+cuda12.0 \
    libnvinfer8=8.6.1.6-1+cuda12.0 \
    libnvonnxparsers-dev=8.6.1.6-1+cuda12.0 \
    libnvonnxparsers8=8.6.1.6-1+cuda12.0 \
    libnvparsers-dev=8.6.1.6-1+cuda12.0 \
    libnvparsers8=8.6.1.6-1+cuda12.0 \
```
I get the following error that it does not find anymore libnvinfer version 8:
```
error: creating server: Invalid argument - load failed for model 'comprehend_it': version 1 is at UNAVAILABLE state: Not found: unable to load shared library: libnvinfer.so.8: cannot open shared object file: No such file or directory;
```

**Comment by fpetrini15** [comment]
Hi @copasseron,

I tried running a python model before and after removing TRT 8.6 and there was no issue, which leads me to believe the dependency exists with the backend and not the tritonserver binary.

Running through your steps manually, I see you do not purge TRT 8.6 before your compile. Doing this, the backend compiles fine. However, if I purge TRT 8.6 before I compile I run into errors. So, I think you were building your backend against TRT 8.6 after all.

Forcing the backend to compile with TRT 9.2 requires some tweaks to the CMakeLists.txt file, namely adding hints to the following lines:
```
find_library(NVINFER_LIBRARY NAMES nvinfer HINTS "/usr/local/TensorRT-9.2.0.5/targets/x86_64-linux-gnu/lib")
find_library(NVINFER_PLUGIN_LIBRARY NAMES nvinfer_plugin HINTS "/usr/local/TensorRT-9.2.0.5/targets/x86_64-linux-gnu/lib")
```
Again, because we are operating outside of what is officially supported, you may encounter more issues, but see if this works for you.

**Comment by copasseron** [comment]
Thanks a lot @fpetrini15. 

It works now !! 

the model gives me slightly different results than directly loading it from huggingface, so I still need to figure out how much it impacts my use case. 

your help was greatly appreciated.
