### ISSUE TITLE
Dynamic batching does not work properly with python backend

### ISSUE THREAD

**Issue by Anton-Cherepkov** [triton-inference-server/server#6937]
**Description**
Dynamic batching does not work in case I send requests with different input shapes. This makes sense for onnx/tensorrt backends, however this makes no sense for python backend as the input tensors are not stacked across the batch.

**Triton Information**
_What version of Triton are you using?_ see the answer below

_Are you using the Triton container or did you build it yourself?_ Container `tritonserver_24.01`

**To Reproduce**

Here is the model description and code:
<details>
  <summary>config.pbtxt</summary>

```
name: "python_batched_service"

backend: "python"
max_batch_size: 16

dynamic_batching {
  max_queue_delay_microseconds: 500000
}

input [
  {
    name: "input_field"
    data_type: TYPE_FP32
    dims: [ -1 ]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_CPU
  }
]
```
</details>

<details>
  <summary>model.py</summary>

```python
import triton_python_backend_utils as pb_utils


class TritonPythonModel:
    def initialize(self, args):
        pass

    def execute(self, requests):
        num_requests = len(requests)
        print(f"Received a batch containing {num_requests} request(s)")

        responses = [
            pb_utils.InferenceResponse(output_tensors=[])
            for _ in range(num_requests)
        ]
        return responses

    def finalize(self):
        print("Cleaning up...")
```
</details>

<details>
  <summary>client.py</summary>

```python
import tritonclient.grpc as grpcclient
import numpy as np


triton_client = grpcclient.InferenceServerClient(
    url="localhost:8001",
    verbose=False,
)


def callback(result, error):
    if error:
        print(error)
    pass


def send_single_request(array):
    inputs = [
        grpcclient.InferInput("input_field", array.shape, "FP32")
    ]
    inputs[0].set_data_from_numpy(array)

    triton_client.async_infer(
        model_name="python_batched_service",
        inputs=inputs,
        model_version="1",
        outputs=[],
        callback=callback,
    )

def send_many_requests(input_sizes):
    for ix in range(200):
        size = input_sizes[ix % len(input_sizes)]
        array = np.random.rand(*size).astype(np.float32)
        send_single_request(array=array)


if __name__ == "__main__":
    send_many_requests(input_sizes=[
        (1, 20,),
    ])

    send_many_requests(input_sizes=[
        (1, 20,),
        (1, 40),
        (1, 60),
    ])
```
</details>

For requests coming from `send_many_requests(input_sizes=[(1, 20,),])` the dynamic batching works properly because I can see a lot of `Received a batch containing 16 request(s)` lines in the model's log.

However for requests coming from `send_many_requests(input_sizes=[(1, 20,), (1, 40), (1, 60),])` the dynamic batching does not work, because I can see only `Received a batch containing 1 request(s)` lines in the model's log.

**Expected behavior**
With the python backend I expect the dynamic batching feature to work even for inputs with different shapes, because they are not stacked afterwards.

**Comment by dyastremsky** [comment]
If you would like to batch with different-sized inputs, [ragged batching](https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/user_guide/ragged_batching.html) is available. Scheduling happens in Triton core, which is independent of the backend used, so it would not make sense to relax the scheduling requirement there.
