### ISSUE TITLE
[CMake error] Building Triton on arm64 machine using build.py

### ISSUE THREAD

**Issue by crane-sapia** [triton-inference-server/server#6947]
### Settings
I am trying to build a Triton server from `build.py` with r23.12 on an AWS EC2 instance with
- platform: Amazon Linux (Inferred).
- chip: AWS Inferentia (arm-based architecture)
- cmake version 3.22.2
-  python version 3.8

The following is the script that I use to build the server:
``` BASH
python build.py \
--enable-logging \
--enable-stats \
--enable-tracing \
--enable-metrics \
--no-container-interactive \
--endpoint=http \
--endpoint=grpc \
--endpoint=sagemaker \
--repo-tag=common:r23.12 \
--repo-tag=core:r23.12 \
--repo-tag=backend:r23.12 \
--repo-tag=thirdparty:r23.12 \
--backend=ensemble:r23.12 \
--backend=identity:r23.12 \
--backend=repeat:r23.12 \
--backend=square:r23.12 \
--backend=onnxruntime:r23.12 \
--backend=pytorch:r23.12 \
--backend=python:r23.12 \
--repoagent=checksum:r23.12
```
### Error Description
I am getting the error shown below:
<img width="984" alt="image" src="https://github.com/triton-inference-server/server/assets/144634209/03e32699-7198-4acb-96ed-a3ad6c1387bf">

Can anyone help me solve this issue?

**Comment by yinggeh** [comment]
Hi @crane-sapia. Can you try with `--image=gpu-base,nvcr.io/nvidia/tritonserver:<xx.yy>-py3-min` flag?
You can read more about [CPU-only build here](https://github.com/triton-inference-server/server/blob/main/docs/customization_guide/build.md#cpu-only-build).

**Comment by crane-sapia** [comment]
Hi @yinggeh thx for your response. The build.py file now runs successfully. However, while I was checking the docker images, I saw the following list of images. May I know which one that I can use as a base image for my sagemaker program?
<img width="670" alt="image" src="https://github.com/triton-inference-server/server/assets/144634209/ae63817b-ecdf-49f6-8e19-02548f8a0fc6">

**Comment by yinggeh** [comment]
Hi @crane-sapia. You should use the second image `tritonserver` and you can see it was just created.
`nvcr.io/nvidia/tritonserver` is downloaded from public release. Please check out [Run on CPU-Only System](https://github.com/triton-inference-server/server/blob/main/docs/getting_started/quickstart.md#run-on-cpu-only-system) for more info.

**Comment by crane-sapia** [comment]
Hi @yinggeh Thank you for your help. I will give it a try and see if it works as the docker image provided by [aws](https://github.com/aws/deep-learning-containers/blob/master/available_images.md) as shown below
<img width="1197" alt="image" src="https://github.com/triton-inference-server/server/assets/144634209/9ba71352-b651-4edb-954b-e21e7ac88890">.
