### ISSUE TITLE
Errors from tutorial : Deploying a vLLM model in Triton 

### ISSUE THREAD

**Issue by woo1976** [triton-inference-server/server#6948]
**Description**
I have followed [Triton vllm tutorial](https://github.com/triton-inference-server/tutorials/blob/main/Quick_Deploy/vLLM/README.md#deploying-a-vllm-model-in-triton) to learn about Triton. Code provided in the tutorial guide worked well up to a certain point but in the section "Using the gRPC Asyncio Client", I came across an error.

**Triton Information**
Version: `23.12`  
Images: 
   - `nvcr.io/nvidia/tritonserver:23.12-vllm-python-py3`
   - `nvcr.io/nvidia/tritonserver:23.12-py3-sdk`

Are you using the Triton container or did you build it yourself?  
  - I pulled the images from the Nvidia image repository.  I did not build them myself.

**To Reproduce**
Machine : AWS EC2 having 4 GPUs (Tesla V100-SXM2-16GB)
Nvidia driver version: 535.129.03
CUDA version: 12.2
Nvidia container toolkit version: 1.14.5

Tested model : [facebook/opt-125m](https://huggingface.co/facebook/opt-125m) as suggested in the tutorial

**Step 1: Prepared a model repository following [Tutorial_step_1](https://github.com/triton-inference-server/tutorials/blob/main/Quick_Deploy/vLLM/README.md#step-1-prepare-your-model-repository)**
   - Set up a work directory: `~/work/` on the EC2
   - Set up a model repo directory: `~/work/model_repository/vllm_model/1`
   - Downloaded `model.json` and `config.pbtxt` as suggested in the tutorial
      -  wget -P model_repository/vllm_model/1 https://raw.githubusercontent.com/triton-inference-server/vllm_backend/r23.12/samples/model_repository/vllm_model/1/model.json  
      - wget -P model_repository/vllm_model/ https://raw.githubusercontent.com/triton-inference-server/vllm_backend/r23.12/samples/model_repository/vllm_model/config.pbtxt
   - Modified `model.json` and added `tensor_parallel_size` to `model.json`. The value of `model` key is a path to model files inside a container. I had to do this due to automatic model download limitation caused by my work place's security policy. The json file looks like :  
   ```
    {
        "model": /work/model_repository/vllm_model/1/fb_model",
        "disable_log_requests": "true",
        "gpu_memory_utilization: 0.5,
        "tensor_parallel_size": 4
    }
   ```
   - Did not modify `config.pbtx`. This looks like : 
  ``` 
   backend: "vllm"

   instance_group [
      {
         count: 1
         kind: KIND_MODEL
      }
   ]
  ```
  - In the directory `~/work/model_repository/vllm_model/1` on the EC2, the sub directory `fb_model` and `model.json` exist. The `fb_model` includes all the 12 facebook model files. The sub directory is mapped into a container when doing `docker run`.   

**Step 2: Launch Triton inference server. Referred to [this](https://github.com/triton-inference-server/tutorials/blob/main/Quick_Deploy/vLLM/README.md#step-2-launch-triton-inference-server)** 
```
cd ~/work
# The docker run command in the tutorial did not work as it was on the EC2, so I modified it like the below to make it work. 
# Mapped container's 8001 port to host server's 8011 since host server's 8001 was already taken.
sudo docker run --gpus all -it --rm -p8000:8000 -p8011:8001 -p8002:8002 --shm-size=1G --ulimit memlock=-1 --ulimit stack=67108864 -v ./:/work -w /work nvcr.io/nvidia/tritonserver:23.12-vllm-python-py3 tritonserver --model-store ./model_repository
```

**Step 3: Use a Triton Client to send your first Inference request Referred to [this](https://github.com/triton-inference-server/tutorials/blob/main/Quick_Deploy/vLLM/README.md#step-3-use-a-triton-client-to-send-your-first-inference-request)** 
  - Using the Generate Endpoint. **_This worked as expected!_**
  ```
  # In another bash terminal
  cd ~/work
  sudo docker run -it --net=host -v ./:/workspace/ nvcr.io/nvidia/tritonserver:23.12-py3-sdk bash

  # Within the sdk container. ---- THIS WORKED AS EXPECTED ----
  curl -X POST localhost:8000/v2/models/vllm_model/generate -d '{"text_input": "What is Triton Inference Server?", "parameters": {"stream": false, "temperature": 0}}'
  ```
  - Using the gRPC Asyncio Client. **_THIS DID NOT WORK!_**
  ```
  # On the EC2, downloaded client.py and prompts.txt as suggested in the tutorial
  cd~/work
  wget https://raw.githubusercontent.com/triton-inference-server/vllm_backend/main/samples/client.py
  wget https://raw.githubusercontent.com/triton-inference-server/vllm_backend/main/samples/prompts.txt

 # Run the sdk container
 sudo docker run -it --net=host -v ./:/workspace/ nvcr.io/nvidia/tritonserver:23.12-py3-sdk bash

 # Within the container. 
 # Note: when starting the triton server, mapped container's 8001 port to host server's 8011 since host server's 8001 was already taken.
 python3 client.py -u localhost:8011
  ```
- The code above(`python3 client.py -u localhost:8011`) resulted in error like this : 
```
Loading inputs from `prompts.txt`...

Encountered error while processing: [request id: 0] expected number of inputs between 1 and 3 but got 4 inputs for model 'vllm_model'

Encountered error while processing: [request id: 1] expected number of inputs between 1 and 3 but got 4 inputs for model 'vllm_model'

Encountered error while processing: [request id: 2] expected number of inputs between 1 and 3 but got 4 inputs for model 'vllm_model'

Encountered error while processing: [request id: 3] expected number of inputs between 1 and 3 but got 4 inputs for model 'vllm_model'

Storing results into `results.txt`...

FAIL: vLLM example
```
- I do not know how to debug the expected number of inputs error. If there are issues in the tutorial, please fix them. Many users depend on such a tutorial. 

**Expected behavior**
As shown in the tutorial, I expect to see the code output like this : 
```
Loading inputs from `prompts.txt`...
Storing results into `results.txt`...
PASS: vLLM example
```

**Comment by oandreeva-nv** [comment]
Hi @woo1976 ,
Thanks for reporting this issue! I'll update the tutorial. 
Please note that vLLM backend is in active development, so I would like to ask you to try the following commands:
```
# On the EC2, downloaded client.py and prompts.txt as suggested in the tutorial
cd~/work
wget https://raw.githubusercontent.com/triton-inference-server/vllm_backend/r23.12/samples/client.py
wget https://raw.githubusercontent.com/triton-inference-server/vllm_backend/r23.12/samples/prompts.txt
```
The only difference is, I replaced `main` with the same branch you are using, so files should be consistent.

**Comment by woo1976** [comment]
@oandreeva-nv It worked. Thank you.

**Comment by oandreeva-nv** [comment]
Great! I'll close this issue now, feel free to reach out with any other questions
