### ISSUE TITLE
Exception serializing request - dealing with large input

### ISSUE THREAD

**Issue by mhbassel** [triton-inference-server/server#6956]
Hey everyone!

I am trying to deploy whisper model. I used to the python backend for that. We pass the audio as numpy array to Triton server, I set the `dims` in the model config to `-1` so the user can determine the input shape dynamically (whisper accepts that too).

When I try to inference a very long audio (around 24h) with shape of `1.382.393.499` (very large I know) I get this error:
```
Traceback (most recent call last):
  File "/media/ssdraid/training/triton/triton-test/whisper_client.py", line 145, in <module>
    results = triton_client.infer(
  File "/home/tensorflow/venvs/triton/lib/python3.10/site-packages/tritonclient/grpc/__init__.py", line 1322, in infer
    raise_error_grpc(rpc_error)
  File "/home/tensorflow/venvs/triton/lib/python3.10/site-packages/tritonclient/grpc/__init__.py", line 62, in raise_error_grpc
    raise get_error_grpc(rpc_error) from None
tritonclient.utils.InferenceServerException: [StatusCode.INTERNAL] Exception serializing request!
```
Can anyone help me finding a solution, please?

Thanks in advance

**Comment by yinggeh** [comment]
Hi @mhbassel,

Can you please provide full reproduction steps (all commands run) and fill out the bug template below? Thank you!
--
**Description**
A clear and concise description of what the bug is.

**Triton Information**
What version of Triton are you using?

Are you using the Triton container or did you build it yourself?

**To Reproduce**
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**
A clear and concise description of what you expected to happen.

**Comment by mhbassel** [comment]
Hi @yinggeh 

Thanks for your reply!

**Description**
I am trying to deploy whisper model. I used to the python backend for that. We pass the audio as numpy array to Triton server, I set the dims in the model config to -1 so the user can determine the input shape dynamically (whisper accepts that too).
When I try to inference a very long audio (around 24h) with shape of 1.382.393.499 (very large I know) I get this error:
```
Traceback (most recent call last):
  File "/media/ssdraid/training/triton/triton-setup/reproduce/inference/test_client.py", line 134, in <module>
    results = triton_client.infer(
  File "/home/tensorflow/venvs/triton/lib/python3.10/site-packages/tritonclient/grpc/__init__.py", line 1322, in infer
    raise_error_grpc(rpc_error)
  File "/home/tensorflow/venvs/triton/lib/python3.10/site-packages/tritonclient/grpc/__init__.py", line 62, in raise_error_grpc
    raise get_error_grpc(rpc_error) from None
tritonclient.utils.InferenceServerException: [StatusCode.INTERNAL] Exception serializing request!
```

**Triton Information**
What version of Triton are you using?
- 23.07

**Are you using the Triton container or did you build it yourself?**
- I tried with both and got the same behaviour

To Reproduce
[reproduce_example.zip](https://github.com/triton-inference-server/server/files/14518078/reproduce_example.zip)
1. Unzip `reproduce_example.zip` file
2. Go to the Docker file location and run: `docker compose -f docker-compose.yml up --build`
3. Go to `inference` folder and run: `python test_client.py`

**Describe the models**
1. It's a simple python model that returns a list of a one arbitrary string element.
2. The model accepts input of any shape of type FP32.
3. The client sends a request to infer on numpy array of shape `(1382393499,)`

**Expected behavior**
I expect to run the client script `test_client.py` successfully and get the first element of the returned list of the response.

**Comment by mhbassel** [comment]
Ok I tested a bit and found out that changing its order of magnitude by one works fine. So apparently, the gRPC protocol cannot handle such large array.
A solution would be, maybe, by adjusting the gRPC implementation to make it accept larger sizes. But I don't think if that the optimal solution is, I was thinking maybe dividing the request into chunks and sending them one by one to the triton server, and triton server should wait until it get all the chunks and then process them at once, and does the same when returning them. But I am still not sure how to implement this.

**Comment by yinggeh** [comment]
@jbkyang-nvi Any thoughts?

**Comment by mhbassel** [comment]
Hi, any updates on this?

**Comment by jbkyang-nvi** [comment]
Hello, sorry for the delay in responses. It seems like you can use the [sequence batcher](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/model_configuration.md#sequence-batcher) for stateful models or the dynamic batcher for stateless models. Read about different model configurations [here](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/architecture.md#stateful-models). 

Maybe: @tanmayv25  has more ideas

**Comment by mhbassel** [comment]
Hey @jbkyang-nvi thanks for responding! Yeah that could be a reliable solution, I will try it, also I am not expecting Triton to accept too large input sizes, there would be probably some downsides.
Therefore I will close the issue, thanks a lot!
