### ISSUE TITLE
In 24.02, TensorRT version is 8.6.1, but expected to be 8.6.3

### ISSUE THREAD

**Issue by jacob-talroo** [triton-inference-server/server#6959]
**Description**
Triton 24.02 claims to be based on 24.02 container release on NVIDIA GPU Cloud (NGC).  From https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html , it appears that the TensorFlow version has been upgraded from 2.14 to 2.15 and the TensorRT version has been upgraded from 8.6.1 to 8.6.3.

However, TF has been upgraded, but it appears that TensorRT has not.

**Triton Information**
24.02

Are you using the Triton container or did you build it yourself?  Prebuilt

**To Reproduce**
```python
import tensorrt
print(tensorrt.__version__)
assert tensorrt.Builder(tensorrt.Logger())

import tensorflow as tf
print(tf.config.list_physical_devices('GPU'))

from tensorflow.python.compiler.tensorrt import trt_convert as trt
print(trt.trt_utils._pywrap_py_utils.get_linked_tensorrt_version())
```

**Expected behavior**
I expected the TensorRT version to be 8.6.3.

**Comment by yinggeh** [comment]
@mc-nv Can you take a look?

**Comment by mc-nv** [comment]
Triton server is part of the [DeepLearning Framework](https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html) ecosystem. 

Triton base image includes installation of the TensorRT version 8.6.3 and can be verified: 
```
$ docker run --rm -it nvcr.io/nvidia/tritonserver:24.02-py3 bash -c "dpkg -l | grep tensorrt-dev"

=============================
== Triton Inference Server ==
=============================

NVIDIA Release 24.02 (build 83572450)
Triton Server Version 2.43.0

Copyright (c) 2018-2023, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use the NVIDIA Container Toolkit to start this container with GPU support; see
   https://docs.nvidia.com/datacenter/cloud-native/ .

ii  tensorrt-dev                    8.6.3.1-1+cuda12.0                      amd64        Meta package for TensorRT development libraries
```

**Comment by jacob-talroo** [comment]
Also, it is important to note that I found a slight work around to use 24.01 (8.6.1 for all builds).  This build doesn't have TF 2.15.  We are testing inference now to determine if that is an issue.

**Comment by yinggeh** [comment]
Our prebuild image does not ship with TensorRT python package. Did you manually install it? Please try to install 8.6.3 library in 24.02 container.

**Comment by jacob-talroo** [comment]
That error message was outputted when I loaded the model in Triton.

The image I have is slightly modified:

```
FROM nvcr.io/nvidia/tritonserver:24.02

RUN pip install --no-dependencies tensorflow-text==2.15.* && \
  mkdir -p /ops && \
  ln -s /usr/local/lib/python3.10/dist-packages/tensorflow_text/python/ops/ /ops/tf_text
```

It sounds like there is quite a bit of push back, so I'll rerun my build and deploy to confirm.

**Comment by jacob-talroo** [comment]
I just tried again and can _not_ reproduce.  We must have had a configuration issue with running the wrong container.  Apologies for the erroneous defect!

**Comment by yinggeh** [comment]
To build/prepare TF or TRT models, you can use the same <yy.mm> version of the corresponding NGC containers to do so:
https://catalog.ngc.nvidia.com/orgs/nvidia/containers/tensorrt/tags
https://catalog.ngc.nvidia.com/orgs/nvidia/containers/tensorflow/tags
ex: For Triton 24.02, use TRT 24.02 container to build the engine.
