### ISSUE TITLE
How does triton support the case where batch is not the first dimension?

### ISSUE THREAD

**Issue by fighterhit** [triton-inference-server/server#6969]
I noticed that the [doc](https://docs.nvidia.com/deeplearning/triton-inference-server/archives/triton_inference_server_1120/triton-inference-server-guide/docs/model_configuration.html#:~:text=The%20Triton%20Inference%20Server%20assumes%20that%20the%20batching%20occurs%20along%20a%20first%20dimension%20that%20is%20not%20listed%20in%20the%20inputs%20or%20outputs) says that trition assumes that the first dimension of the model represents the batch, so it can be ignored in the config. But how does triton support the case where batch is not the first dimension? For example, in the second dimension? e.g. (5,batch,6).

**Comment by lkomali** [comment]
To add to @tanmayv25's answer, for dynamic batching, Triton expects the first dimension to be batch size. For a simple model that uses default scheduler, the input can be any shape as long as it matches with the model metadata.
It's a general recommendation to have first dimension represent batch size.
cc: @rmccorm4
