### ISSUE TITLE
How to interperet traces for business logic scripting model(BLS). 

### ISSUE THREAD

**Issue by NikeNano** [triton-inference-server/server#6980]
**Description**
We are experiancing very low inference speed for our BLS model and try to optimize the performance. Part of this is that we added tracing to the triton server in order to better understand what we spend the time on. 

**Triton Information**

container: nvcr.io/nvidia/tritonserver:24.01-py3-sdk /bin/bash

```bash
tritonserver --model-repository=/models   --trace-config triton,file=/tmp/trace.json   --trace-config triton,log-frequency=50   --trace-config rate=1   --trace-config level=TIMESTAMPS   --trace-config count=100
```

**To Reproduce**
The config for the BLS mode is the following: 

```
backend: "python"
input [
  {
    name: "inputs"
    data_type: TYPE_UINT8
    dims: [ 1, 1024, 21960]
  }
]
output [
  {
    name: "bounding_box"
    data_type: TYPE_FP32
    dims: [ -1, 4]
  },
  {
    name: "label"
    data_type: TYPE_FP32
    dims: [ -1, 1]
    label_filename: "label_names.txt"
  },
  {
    name: "probability"
    data_type: TYPE_FP32
    dims: [ -1, 1]
  }
]
instance_group [
  {
    count: 5
    kind: KIND_CPU
  }
]
version_policy: { latest: { num_versions: 1}}
```

and the model is run as following: 

```
max_batch_size: 8
dynamic_batching {}
platform: "onnxruntime_onnx"
#optimization { execution_accelerators {
#  gpu_execution_accelerator : [ {
#    name : "tensorrt"
#    parameters { key: "precision_mode" value: "FP16" }
#    parameters { key: "max_workspace_size_bytes" value: "1073741824" }
#   } ]
#}}
input [
  {
    name: "inputs"
    data_type: TYPE_FP32
    dims: [ 1, 512, 512 ]
  }
]
output [
  {
    name: "segmentation_map"
    data_type: TYPE_FP32
    dims: [ 10, 512, 512]
  }
]
model_warmup [
{
    name : "zero sample"
    batch_size: 1
    inputs {
        key: "inputs"
        value: {
            data_type: TYPE_FP32
            dims: 1
            dims: 512
            dims: 512
            zero_data: true
        }
    }
}]
version_policy: { latest: { num_versions: 1}}

```

**Expected behavior**

We have the following trace: 

```
bls (1):
	id: 1
	REQUEST_START
		17.762us
	QUEUE_START
		123.469us
	COMPUTE_START
		29822.027us
	COMPUTE_INPUT_END
		3415627.488us
	COMPUTE_OUTPUT_START
		29.659us
	INFER_RESPONSE_COMPLETE
		10.318us
	GRPC_SEND_START
		230.306us
	COMPUTE_END
		1.526us
	GRPC_SEND_END
		35.831us
	REQUEST_END
defect-classifier (1):
	id: 2
	parent id: 1
	REQUEST_START
		11.423us
	QUEUE_START
		218.305us
	COMPUTE_START
		16.963us
	COMPUTE_INPUT_END
		131262.408us
	COMPUTE_OUTPUT_START
		14245.408us
	COMPUTE_END
		57.843us
	REQUEST_END
defect-classifier (1):
	id: 3
	parent id: 1
	REQUEST_START
		14.265us
	QUEUE_START
		196.486us
	COMPUTE_START
		17.561us
	COMPUTE_INPUT_END
		107458.203us
	COMPUTE_OUTPUT_START
		15821.712us
	COMPUTE_END
		49.24us
	REQUEST_END
     ....
  
```

I dont follow what the different groupings represent even though I read[https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/user_guide/trace.html#trace-summary-tool]. Specifically I would better like to understand: 

- What is COMPUTE_INPUT_END for the bls model? 
- What is best practice to better understand how I optimize COMPUTE_INPUT_END
- What is COMPUTE_START for the bls model? 
- Is there any recomendations around profiling of BLS models?

Thanks you! Awesome work with triton and the tools around it!

**Comment by lkomali** [comment]
cc @rmccorm4 Any thoughts?

**Comment by NikeNano** [comment]
Is there any other forum I that I should use instead @lkomali? Is there a discord or slack group? Thanks

**Comment by Tabrizian** [comment]
The duration between `COMPUTE_START` and `COMPUTE_INPUT_END` is the time it takes for the backend to process your input tensors (e.g. move them to the correct device). I think your input is quite large (21MBs) so I think it is expected that it takes sometime for the inputs to be copied.

`COMPUTE_START` is the time that your Python model starts execution.

For BLS models, you can profile them using [Perf Analyzer](https://github.com/triton-inference-server/client/blob/main/src/c++/perf_analyzer/README.md). It has a flag named `--composing-models` which would provide a latency breakdown of the inference steps. You could also try to manually time different sections of your Python code to better understand the places where the majority of the time spent.

**Comment by NikeNano** [comment]
Thanks @Tabrizian. I dont really follow on

> The duration between COMPUTE_START and COMPUTE_INPUT_END is the time it takes for the backend to process your input tensors (e.g. move them to the correct device).

So the time to move the data is `COMPUTE_INPUT_END` or the diff between `COMPUTE_INPUT_END` - `COMPUTE_START`? Are these times aggregted of I should view them as timestamps? 

Is there any optimisations related to sending large images to a BLS model for preprocessing before sending it to the model? We are considering to move it to c++ instead of python(and not doing any post or preprocessing inside triton) sacrificing consistency between training(python) and inference(then c++ and triton).

**Comment by NikeNano** [comment]
Run `pref_analyzer` with --bls-composing-models:

```
*** Measurement Settings ***
  Batch size: 1
  Service Kind: Triton
  Using "time_windows" mode for stabilization
  Measurement window: 10000 msec
  Using synchronous calls for inference
  Stabilizing using average latency

Request concurrency: 1
  Client:
    Request count: 267
    Throughput: 7.41631 infer/sec
    Avg latency: 134594 usec (standard deviation 13630 usec)
    p50 latency: 133122 usec
    p90 latency: 151233 usec
    p95 latency: 158099 usec
    p99 latency: 173065 usec
    Avg gRPC time: 134568 usec ((un)marshal request/response 2496 usec + response wait 132072 usec)
  Server:
    Inference count: 267
    Execution count: 267
    Successful request count: 267
    Avg request latency: 120016 usec (overhead 117254 usec + queue 70 usec + compute 2692 usec)

  Composing models:
  defect-classifier, version: 202403071807
      Inference count: 2940
      Execution count: 2940
      Successful request count: 2940
      Avg request latency: 2782 usec (overhead 20 usec + queue 70 usec + compute input 216 usec + compute infer 2374 usec + compute output 101 usec)

Inferences/Second vs. Client Average Batch Latency
Concurrency: 1, throughput: 7.41631 infer/sec, latency 134594 usec
```

The overhead for the bls model is: 117254us is this also equivalent is time equivalent to cpu cycles used?

**Comment by NikeNano** [comment]
As I understand from:

```
...
  Server:
    Inference count: 267
    Execution count: 267
    Successful request count: 267
    Avg request latency: 120016 usec (overhead 117254 usec + queue 70 usec + compute 2692 usec)
...
```

a majority of my compute is spent on GRPC to process the inference request, is that correct?

**Comment by Tabrizian** [comment]
> So the time to move the data is COMPUTE_INPUT_END or the diff between COMPUTE_INPUT_END - COMPUTE_START? Are these times aggregated of I should view them as timestamps?

No, it is the value printed after `COMPUTE_START` (i.e. 29822.027us for bls). 

> Is there any optimisations related to sending large images to a BLS model for preprocessing before sending it to the model? We are considering to move it to c++ instead of python(and not doing any post or preprocessing inside triton) sacrificing consistency between training(python) and inference(then c++ and triton).

Unfortunately, I can't think of any optimizations this part of the pipeline. Looks like your only option might be custom backends in C++. This would avoid data copy to shared memory which can help with the performance.

@ganeshku1 / @matthewkotila / @tgerdesnv it might be worth including the compute input / output time for BLS requests in Perf Analyzer server-side latency breakdown.

**Comment by NikeNano** [comment]
But what is COMPUTE_INPUT_END? What is the time spent on the actual computations of the backend(from grpc and from our custom code)? Also in relation to the `pref_analyzer` tool what is: 

...
  Server:
    Inference count: 267
    Execution count: 267
    Successful request count: 267
    Avg request latency: 120016 usec (overhead 117254 usec + queue 70 usec + compute 2692 usec)
...

? Maybe we could add a example to the docs to better understand the times, would be happy to add it when I understand it better. 

Thanks

**Comment by Tabrizian** [comment]
`COMPUTE_INPUT_END` marks the end of request processing. The trace summary prints out the times between each stage. For example, from `REQUEST_START` to `QUEUE_START` it has taken `17.762us` in the 'bls' model. The actual computation time is the value after `COMPUTE_INPUT_END` and before `COMPUTE_OUTPUT_START`.

> ? Maybe we could add a example to the docs to better understand the times, would be happy to add it when I understand it better.

There is some information about the `perf_analyzer` output here: https://github.com/triton-inference-server/client/blob/main/src/c%2B%2B/perf_analyzer/docs/measurements_metrics.md#how-latency-is-calculated

Let us know if you have any feedback or if it is still not clear. (cc @matthewkotila / @nv-hwoo  for viz)

**Comment by NikeNano** [comment]
Ok, thanks for the help @Tabrizian.
