### ISSUE TITLE
Use Dynamic Batching on ONNX Model Exported with Fixed Batch Dim

### ISSUE THREAD

**Issue by langong347** [triton-inference-server/server#7003]
**Description**
I use a third party library (Ultralytics) to export a YOLOv8 model to ONNX format in half precision. Due to limitation of the third party, it does not support dynamic axes and half precision export at the same time. So in `config.pbtxt` I need to set the input and output size to include the fixed batch dim. The batch dim is currently set as `1` by the third party, for example, input shape `[1, 3, 800, 800]`, output shape `[1, 7, num_anchors]`.

I wonder if setting batch dim explicitly will conflict with dynamic batching, as the latter determines the actual batch size at runtime.

My current `config.pbtxt` caused Triton to throw the error: 

```
UNAVAILABLE: Invalid argument: model 'my-yolov8-service', tensor 'images': for the model to support batching the shape should have at least 1 dimension and the first dimension must be -1; but shape expected by the model is [1,3,800,800]
```

```
name: "my-yolov8-service"
platform: "onnxruntime_onnx"
max_batch_size: 8
input [
  {
    name: "images"
    data_type: TYPE_FP16
    dims: [ 3, 800, 800 ]
  }
]
output [
  {
    name: "output0"
    data_type: TYPE_FP16
    dims: [ 7, 13125 ]
  }
]
dynamic_batching {
    max_queue_delay_microseconds: 20000
}
instance_group [
  {
    count: 2
    kind: KIND_GPU
  }
]
```

**Triton Information**
23.12

Are you using the Triton container or did you build it yourself?
KServe, prebuilt container.

**To Reproduce**
- Export the ultralytics YOLOv8 model with `half=True, format=onnx`
- Deploy the service with the Triton config file (see above)

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

Model: Ultralytics YOLOv8 model written in PyTorch

**Expected behavior**
I expect dynamic batching will work with ONNX model exported with a fixed batch dim.

**Comment by indrajit96** [comment]
CC @tanmayv25 @rmccorm4

**Comment by rmccorm4** [comment]
Hi @langong347, the underlying model itself needs to support batching in order for Triton to form batches for it. 

Since the model has a fixed batch size of 1, Triton expects the same, so it won't support dynamic batching. You can either (a) keep the model as is and change the config to set the max_batch_size to 0 and add the "1" batch dimension to the input/output shapes, or (b) keep the config as is and regenerate the ONNX model with dynamic batch dimension.

**Comment by langong347** [comment]
Thanks you @rmccorm4 ! (b) is what I've adopted since then, and it worked.

**Comment by MiqdaadIndori** [comment]
Hello @rmccorm4 , I have the same problem, I went with (a). I thought triton would automatically detect that the model does not support batching and run the inputs in a loop.
Although I see in the documentation that this is not supported. I think this is a common use case and there should be an option to enable this.
in the meantime, would BLS solve this? I think that would be the easiest way.
