### ISSUE TITLE
why concurrency multiply batch_size same in perf_analyzer but throughtput are very different

### ISSUE THREAD

**Issue by Joenhle** [triton-inference-server/server#7026]
I have a dali model and bls model, the bls model just collect input from all the request, and then async send to dali model, the await the dali response, then return little result. I use perf_analyzer to messure the performance. the concurrency multiply by batch_size are same, but the result throughput are very diffrent, i don't why. In my opinion, they should be differ a liitle cause the dynamic batcher.

first command: 
perf_analyzer -m bls --percentile=95 --concurrency-range 4:20:4 -b 8 --input-data /opt/tritonserver/test/dali_input.json --shape INPUT:245340 --measurement-interval 10000
<img width="1439" alt="企业微信截图_ed2440c0-176b-49f2-bca8-f84f1b0e49e6" src="https://github.com/triton-inference-server/server/assets/56585772/d5d108dc-4255-4589-9a3c-6eec25e9f99f">

second command:
perf_analyzer -m bls --percentile=95 --concurrency-range 32:160:32 -b 1 --input-data /opt/tritonserver/test/dali_input.json --shape INPUT:245340 --measurement-interval 10000
<img width="1406" alt="image" src="https://github.com/triton-inference-server/server/assets/56585772/987c9871-51a4-433a-aac5-e4cfd466df51">

the bls config
<img width="434" alt="image" src="https://github.com/triton-inference-server/server/assets/56585772/e325f52e-7870-41ac-a7f9-03128c7a6180">

the dali config
<img width="475" alt="image" src="https://github.com/triton-inference-server/server/assets/56585772/e7e39726-9fe0-463d-a2f0-68b92b099d64">

**Comment by rmccorm4** [comment]
Hi @Joenhle, thanks for opening the issue with such detail!

A few follow-up questions to help eliminate some factors:
1. Do you see the expected scaling in performance when querying your DALI model directly from perf analyzer? (`perf_analyzer -m my_dali_model ...`
2. Can you share your BLS model and the logic being used for gathering/scattering?

**Comment by Joenhle** [comment]
@rmccorm4 thank your reply，I have resolved the question. In the last slow version, my bls gathering logic is that construct 32 independent async requetst, each request input data's shape is [1, C, H, W]，then use asyncio.gather to wait the 32 response. Then in the latest version, i use torch.cat to concatenate the 32 torch data matually, it's shape is [32, C, H, W] and then send in one request, it's performance is better much. I don't konw why it's so a big effection gather data matually in bls, rather than hand to the dynamic bacher.

**Comment by Tabrizian** [comment]
@Joenhle this is an interesting observation. I was curious whether you're sending the BLS tensors that you are transferring are on GPU or CPU?

For GPU, if you run out of CUDA memory pool it could be that falling back to `cudaIpc` calls can hinder performance.

Also, can you share the Triton version that you're using?

**Comment by Joenhle** [comment]
@Tabrizian 1. On GPU 2. didn't run out of CUDA memory 3. triton version 2.21.0

**Comment by Tabrizian** [comment]
Could you retry your experiments on the latest version of Triton? @krishung5 had some changes in this area that should improve the performance.
