### ISSUE TITLE
TritonServer and X Server together on 1 GPU

### ISSUE THREAD

**Issue by dpai** [triton-inference-server/server#7060]
I have a question on compatibility between TritonServer and X Server on Linux.
I want to share my GPU to both do an inference using the tritonserver, as well as connect the same to the display monitor to work on the UI that will engage the DL model for inference.

I have a working version, but I am looking for any corner cases. Will there be any issue with X Server and Tritonserver working on the same GPU?

**Comment by nnshah1** [comment]
@dpai there is no general issue with using the GPU for both AI workloads and display workloads. The drivers will handle time slicing / synchronization such that they don't directly interfere with one another. Both applications will share GPU resources in terms of memory and compute but again generally speaking display pipelines and AI pipelines are relatively independent and much of the work can be done in parallel. If you are heavily taxing the GPU for your graphics (say 3D gaming) then there will be definite impact to the workloads sharing the same compute engines - but for normal simple 2d display you shouldn't face much if any impact.

Best is to use nvidia-smi on the host to see how much load (memory, compute) is being used by the display portion if you suspect issues.

**Comment by nnshah1** [comment]
@dpai let us know if you run into issues
