### ISSUE TITLE
The nvml requested operation is not available on target device when following DALI with Triton tutorial

### ISSUE THREAD

**Issue by bitchaser12** [triton-inference-server/server#7071]
**Description**
I've been trying to follow along the tutorial to use DALI with triton but I'm getting an error trying to load the dali pipeline:
I0403 19:23:22.564242 1 dali_backend.cc:164] TRITONBACKEND_ModelFinalize: delete model state
E0403 19:23:22.564288 1 model_lifecycle.cc:638] failed to load 'dali_preprocessing' version 1: Unknown: DALI Backend error: Critical error when building pipeline:
Error when constructing operator: decoders__Image encountered:
Error in thread 0: nvml error (3): The nvml re

**Triton Information**
24.03

Are you using the Triton container or did you build it yourself?
Container

**To Reproduce**
Dali pipeline:
`
from nvidia.dali import pipeline_def
import nvidia.dali.fn as fn
import nvidia.dali.types as types

@pipeline_def(batch_size=256, num_threads=4, device_id=0)
def custom_pipeline():
    # Triton will provide the input through "DALI_INPUT_0"
    images = fn.external_source(device="cpu", name="DALI_INPUT_0")
    images = fn.decoders.image(images, device="mixed", output_type=types.RGB)
    # Resize to 384x384 using bicubic interpolation
    images = fn.resize(images, resize_x=384, resize_y=384, interp_type=types.INTERP_CUBIC)
    # Normalize
    images = fn.crop_mirror_normalize(
        images,
        dtype=types.FLOAT16,
        mean=[0.485 * 255, 0.456 * 255, 0.406 * 255],
        std=[0.229 * 255, 0.224 * 255, 0.225 * 255],
        output_layout="CHW")
    return images

# Instantiate and build the pipeline
pipe = custom_pipeline()
pipe.serialize(filename="./model.dali")
`

**Expected behavior**
DALI model loads as in the tutorial

**Comment by nnshah1** [comment]
@szalpal would you be able to help triage?

**Comment by ntakouris** [comment]
open this again please :)

**Comment by nnshah1** [comment]
@ntakouris - please open a new issue if needed. Seems this was root caused to WSL specifics - and we would need to understand NVML limitations there -
