### ISSUE TITLE
Copy GPU Tensor to CPU on Python backend without using pytorch

### ISSUE THREAD

**Issue by ShuaiShao93** [triton-inference-server/server#7120]
**Is your feature request related to a problem? Please describe.**
I know we can copy GPU tensor to CPU with `torch.utils.dlpack.from_dlpack` ([link](https://github.com/triton-inference-server/server/blob/6b9da4e7d66dfca4e0b769c43a74caaca6fc784a/qa/python_models/bls_async/model.py#L48)), but we don't want to introduce torch into our deps.

**Describe the solution you'd like**
Add an API to Tensor to copy to CPU and convert to numpy.

**Comment by MatthieuToulemont** [comment]
That would be great, especially given the torch cache

**Comment by Tabrizian** [comment]
Thanks for your feature request. I've linked your issue to this ticket and will close this issue as duplicate. https://github.com/triton-inference-server/server/issues/3547

Let's keep all the comments related to this feature in that GitHub issue.
