### ISSUE TITLE
Question: Which backends automatically warm up models?

### ISSUE THREAD

**Issue by nkinnaird** [triton-inference-server/server#7161]
On the main readme I see this paragraph:

> For a few of the Backends (check [Additional Resources](https://github.com/triton-inference-server/server/blob/main/docs/README.md#resources)) 
> some or all of initialization is deferred until the first inference request is received, the benefit 
> is resource conservation but comes with the downside of the initial requests getting processed 
> slower than expected. Users can pre-"warm up" the model by instructing Triton to initialize the 
> model. 
> [Learn more](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/model_configuration.md#model-warmup).

However I am unable to determine which models automatically warm up models or not. (I'm mainly interested in TensorRT and ONNX backends.) Looking at the individual backend github pages I am also unable to find the information. I'm sure it must be there somewhere, is anyone aware of a list or know for TensorRT and ONNX backends whether they automatically warm up models or not? Thanks

**Comment by rmccorm4** [comment]
Hi @nkinnaird, most backends can incur some kind of "cold-start penalty", regardless of the details about the framework, but some may be more noticeable than others and may be use-case dependent. Regardless of this, Triton has a [Model Warmup](https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/user_guide/model_configuration.html#model-warmup) feature which you should be able to apply to any backend. You can specify some realistic batch sizes and shapes that are expected for your use case to ensure the model is properly warmed up before it is considered "ready" by the server for processing client requests.
