### ISSUE TITLE
Stub process is not healthy.

### ISSUE THREAD

**Issue by NDNM1408** [triton-inference-server/server#7186]
I want to use python backend with triton to deploy TTS model using hifigan and fastpitch. When I infer hifigan, I meet the error

tritonclient.utils.InferenceServerException: [400] Failed to process the request(s) for model instance 'hifigan_0', message: Stub process is not healthy.

This is the content of fime model.py

import json
import triton_python_backend_utils as pb_utils
from nemo.collections.tts.models import HifiGanModel
import torch

class TritonPythonModel:

    def initialize(self, args):

        self.model_config = model_config = json.loads(args['model_config'])

        output_config = pb_utils.get_output_config_by_name(
            model_config, "audio")

        # Convert Triton types to numpy types
        self.output_dtype = pb_utils.triton_string_to_numpy(
            output_config['data_type'])
        self.model = HifiGanModel.restore_from("hifigan.nemo")
        
    def execute(self, requests):

        output_dtype = self.output_dtype

        responses = []

        # Every Python backend must iterate over everyone of the requests
        # and create a pb_utils.InferenceResponse for each of them.
        for request in requests:
            input = pb_utils.get_input_tensor_by_name(request, "spec").as_numpy()
            audio = self.model.convert_spectrogram_to_audio(spec=torch.from_numpy(input))
            print(audio)
            print(audio.shape)
            out_tensor = pb_utils.Tensor("audio",
                                           audio.astype(output_dtype))
            inference_response = pb_utils.InferenceResponse(
                output_tensors=[out_tensor])
            responses.append(inference_response)

        # You should return a list of pb_utils.InferenceResponse. Length
        # of this list must match the length of `requests` list.
        return responses

    def finalize(self):
        """`finalize` is called only once when the model is being unloaded.
        Implementing `finalize` function is OPTIONAL. This function allows
        the model to perform any necessary clean ups before exit.
        """
        print('Cleaning up...')
        
Can anyone help?

**Comment by krishung5** [comment]
Hi @NDNM1408, I was wondering which Triton version are you using? Could you also provide the model config and any steps required for us to reproduce the issue?

**Comment by Tabrizian** [comment]
@victorsoda You need to compile the same branch of the repo as the server. I think the issue is that you're using the `main` branch with the 24.03` version of the server. Could you try building Python backend from `r24.03` branch and let us know if you're still running into an error?

**Comment by victorsoda** [comment]
> @victorsoda You need to compile the same branch of the repo as the server. I think the issue is that you're using the `main` branch with the 24.03`version of the server. Could you try building Python backend from`r24.03` branch and let us know if you're still running into an error?

@Tabrizian  Thanks a lot for your quick reply! I'll try it today and give you some feedback ASAP.

**Comment by sboudouk** [comment]
> @victorsoda You need to compile the same branch of the repo as the server. I think the issue is that you're using the `main` branch with the 24.03`version of the server. Could you try building Python backend from`r24.03` branch and let us know if you're still running into an error?

Just want to be sure here, is manually uprading python_backend also also needed if i'm running `nvcr.io/nvidia/tritonserver:23.07-py3` docker image ?
