### ISSUE TITLE
Query Regarding Custom Metrics For Python Backend

### ISSUE THREAD

**Issue by AniForU** [triton-inference-server/server#7204]
**Is your feature request related to a problem? Please describe.**
We are trying to use Python Backend of Triton server. We are using Model.py and writing our logic and model usage inside it. I want to know how can we use metrics in Python backend so that it can be retrieved from deployed Triton Server.

**Describe the solution you'd like**
Model.py file could accompdate something like

Import triton_python_backend_utils as pb_utils
 .....
execute()
internal_process_key = pb_utils.Metrics("key_for_prometheus")

Someprocess....

internal_process_key.inc()

**Describe alternatives you've considered**
Not yet as, could not find how this could be used

**Comment by krishung5** [comment]
Hi @AniForU, the custom metrics support in Python backend utilizes the in-process Triton C API under the hood, so you should be able to retrieve the custom metrics by any of the [metrics endpoint](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/metrics.md#metrics).
