### ISSUE TITLE
Triton Server for the model mixtral-8x7b

### ISSUE THREAD

**Issue by harievg** [triton-inference-server/server#7249]
.

**Comment by Tabrizian** [comment]
Are you asking for safe tensors support for a specific backend? It is not currently supported but you could create your custom Python-based backend that leverages safe-tensors: https://github.com/triton-inference-server/backend/blob/main/docs/python_based_backends.md#

**Comment by harievg** [comment]
Hello dear Iman,
Thanks for your mail regarding our ticket,
yes, that would be one of our secondary requirements to handle safe tensor based open-source models & and to host our own models.
But our actual primary requirements would be of scaling the inference engines which host the LLM models eg, hosting multiple instances of models.

Currently we use docker compose & containers to host the llm engines (Currently we use VLLM open-source Inference engine). But we would like to opt for proprietary.
Nvidia solutions for our DGX Nodes, so it has scalable solutions for future in case if we are buying more DGX.

I would explain a bit:
Now, since it’s a container we are scaling by ports of the host dgx machine network, eg, port 8000 to 8010 for 10 model instance & Vector DB servers. But we want to have a scalable solution by IP’s based eg:
<ip1_llm>:8000; <ip2_llm>:8000; <ip3_vecDB>:8000 … and so on.

We have a parent layer network as DGX machine Network open port of 443, there we must have to access all those ip based models inside the DGX, through 443.
Hope I do explain it short and right manner. If needed, we could arrange a video call later, but this is our Primary requirements for scaling up things. We would be even happy if Nvidia Triton has solution for this, if needed we would like to have an offer for that from Nvidia.

Thanks


Best regards,
Hari Shankar Govindasamy

EV Group
invent • innovate • implement
IT Engineer - Artificial Intelligence Services - Phone: +43 (7712) 5311 - 0,
E-Mail: ***@***.******@***.***>, Web: www.EVGroup.com<http://www.EVGroup.com>

EV Group GmbH, DI Erich Thallner Str. 1, 4782 St. Florian am Inn, Austria
Rechtsform: GmbH, Sitz: St. Florian am Inn, FN 215218y, LG Ried im Innkreis

This message and any attachments contain trade secrets, confidential or privileged information, which is intended for the named addressee(s) only. If you have received it in error, please notify the sender immediately and then delete this e-mail. Please note that unauthorized review, copying, disclosing, distributing or otherwise making use of the information is strictly prohibited. To keep in contact with you, EV Group might process your personal data. Please follow the link to the privacy policy on our webpage.

**Comment by harievg** [comment]
Hi dear Iman,
we would like to know whether you got my response just in case. And does you have any updates on this regards ticket.
If needed we not an issues to wait further but we would be happy if we got our scalability solution.

thanks


Best regards,
Hari Shankar Govindasamy

EV Group
invent • innovate • implement
IT Engineer - Artificial Intelligence Services - Phone: +43 (7712) 5311 - 0,
E-Mail: ***@***.******@***.***>, Web: www.EVGroup.com<http://www.EVGroup.com>

EV Group GmbH, DI Erich Thallner Str. 1, 4782 St. Florian am Inn, Austria
Rechtsform: GmbH, Sitz: St. Florian am Inn, FN 215218y, LG Ried im Innkreis

This message and any attachments contain trade secrets, confidential or privileged information, which is intended for the named addressee(s) only. If you have received it in error, please notify the sender immediately and then delete this e-mail. Please note that unauthorized review, copying, disclosing, distributing or otherwise making use of the information is strictly prohibited. To keep in contact with you, EV Group might process your personal data. Please follow the link to the privacy policy on our webpage.
From: Govindasamy Hari Shankar ***@***.***>
Sent: Freitag, 24. Mai 2024 09:59
To: triton-inference-server/server ***@***.***>; triton-inference-server/server ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [triton-inference-server/server] Triton Server for the model mixtral-8x7b (Issue #7249)

Hello dear Iman,
Thanks for your mail regarding our ticket,
yes, that would be one of our secondary requirements to handle safe tensor based open-source models & and to host our own models.
But our actual primary requirements would be of scaling the inference engines which host the LLM models eg, hosting multiple instances of models.

Currently we use docker compose & containers to host the llm engines (Currently we use VLLM open-source Inference engine). But we would like to opt for proprietary.
Nvidia solutions for our DGX Nodes, so it has scalable solutions for future in case if we are buying more DGX.

I would explain a bit:
Now, since it’s a container we are scaling by ports of the host dgx machine network, eg, port 8000 to 8010 for 10 model instance & Vector DB servers. But we want to have a scalable solution by IP’s based eg:
<ip1_llm>:8000; <ip2_llm>:8000; <ip3_vecDB>:8000 … and so on.

We have a parent layer network as DGX machine Network open port of 443, there we must have to access all those ip based models inside the DGX, through 443.
Hope I do explain it short and right manner. If needed, we could arrange a video call later, but this is our Primary requirements for scaling up things. We would be even happy if Nvidia Triton has solution for this, if needed we would like to have an offer for that from Nvidia.

Thanks


Best regards,
Hari Shankar Govindasamy

EV Group
invent • innovate • implement
IT Engineer - Artificial Intelligence Services - Phone: +43 (7712) 5311 - 0,
E-Mail: ***@***.******@***.***>, Web: www.EVGroup.com<http://www.EVGroup.com>


EV Group GmbH, DI Erich Thallner Str. 1, 4782 St. Florian am Inn, Austria
Rechtsform: GmbH, Sitz: St. Florian am Inn, FN 215218y, LG Ried im Innkreis

This message and any attachments contain trade secrets, confidential or privileged information, which is intended for the named addressee(s) only. If you have received it in error, please notify the sender immediately and then delete this e-mail. Please note that unauthorized review, copying, disclosing, distributing or otherwise making use of the information is strictly prohibited. To keep in contact with you, EV Group might process your personal data. Please follow the link to the privacy policy on our webpage.

**Comment by harievg** [comment]
Hello Iman,
Yes sure we can keep GH as the medium, but when there is a needed to share any of our company’s intellectual ideas or assets, I would prefer to do in Nvidia Enterprise support medium.
Yes, you got the requirements.

thanks


Best regards,
Hari Shankar Govindasamy

EV Group
invent • innovate • implement
IT Engineer - Artificial Intelligence Services - Phone: +43 (7712) 5311 - 0,
E-Mail: ***@***.******@***.***>, Web: www.EVGroup.com<http://www.EVGroup.com>

EV Group GmbH, DI Erich Thallner Str. 1, 4782 St. Florian am Inn, Austria
Rechtsform: GmbH, Sitz: St. Florian am Inn, FN 215218y, LG Ried im Innkreis

This message and any attachments contain trade secrets, confidential or privileged information, which is intended for the named addressee(s) only. If you have received it in error, please notify the sender immediately and then delete this e-mail. Please note that unauthorized review, copying, disclosing, distributing or otherwise making use of the information is strictly prohibited. To keep in contact with you, EV Group might process your personal data. Please follow the link to the privacy policy on our webpage.

**Comment by Tabrizian** [comment]
Closing due to in-activity.
