### ISSUE TITLE
docker image for triton 24.04 has incorrect CUDA version reported

### ISSUE THREAD

**Issue by stephanbertl** [triton-inference-server/server#7267]
**Description**
the docker image nvidia/tritonserver:24.04-trtllm-python-py3 should be based on CUDA 12.4.1 but nvcc reports wrong version

**Triton Information**
24.04-trtllm
[https://docs.nvidia.com/deeplearning/triton-inference-server/release-notes/rel-24-04.html](url)

**To Reproduce**
`docker run -it --gpus 0 nvidia/tritonserver:24.04-trtllm-python-py3 /bin/bash`

```
root@56fb21bff677:/opt/tritonserver# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Nov_22_10:17:15_PST_2023
Cuda compilation tools, release 12.3, V12.3.107
Build cuda_12.3.r12.3/compiler.33567101_0
```

**Expected behavior**
CUDA 12.4.1 is installed

**Comment by statiraju** [comment]
@mc-nv can you comment?

**Comment by mc-nv** [comment]
> @mc-nv can you comment?

It's correct, and reflected in release notes: 
> The TensorRT-LLM container uses nvcr.io/nvidia/pytorch:24.02-py3 as the base image.
https://github.com/triton-inference-server/server/releases/tag/v2.45.0
