### ISSUE TITLE
No 24.05-trtllm-python-py3 in NGC Repo

### ISSUE THREAD

**Issue by avianion** [triton-inference-server/server#7277]
All other images like VLLM etc are available, but not this one. What gives?

24.05-py3-min
24.05-py3-sdk
24.05-pyt-python-py3
24.05-tf2-python-py3
24.05-vllm-python-py3
24.05-py3
24.05-py3-igpu-min
24.05-py3-igpu-sdk
24.05-py3-igpu

But no 
24.05-trtllm-python-py3 ??

**Comment by krishung5** [comment]
The TRT-LLM image is out. Closing the issue.
