### ISSUE TITLE
Windows 10 docker build Error "Could not locate a complete Visual Studio instance"

### ISSUE THREAD

**Issue by jinkilee** [triton-inference-server/server#7281]
Hi, I am building tritonserver in windows 10 with docker. My host windows version is 
- Edition: Windows 10 Enterprise
- Version: 22H2
- OS build: 19045.4412

**Description**
I tried to build tag names of v2.19.0 and v2.40.0, and failed at the same point. which is...
`RUN vcpkg.exe install openssl:x64-windows openssl-windows:x64-windows rapidjson:x64-windows re2:x64-windows boost-interprocess:x64-windows boost-stacktrace:x64-windows zlib:x64-windows pthread:x64-windows b64:x64-windows
RUN vcpkg.exe integrate install`

The error is
`
$ docker build -t win10-py3-min -f Dockerfile.win10.min .
...
Step 47/49 : RUN vcpkg.exe install openssl:x64-windows openssl-windows:x64-windows rapidjson:x64-windows re2:x64-windows boost-interprocess:x64-windows boost-stacktrace:x64-windows zlib:x64-windows pthread:x64-windows b64:x64-windows
 ---> Running in 52cdbc9a5756
Computing installation plan...
The following packages will be built and installed:
    b64:x64-windows -> 2.0.0.1#2
  * boost-array:x64-windows -> 1.82.0#2
  * boost-assert:x64-windows -> 1.82.0#2
  * boost-build:x64-windows -> 1.82.0#2
  * boost-config:x64-windows -> 1.82.0#2
  * boost-container:x64-windows -> 1.82.0#2
  * boost-container-hash:x64-windows -> 1.82.0#2
  * boost-core:x64-windows -> 1.82.0#2
  * boost-describe:x64-windows -> 1.82.0#2
    boost-interprocess:x64-windows -> 1.82.0#2
  * boost-intrusive:x64-windows -> 1.82.0#2
  * boost-modular-build-helper:x64-windows -> 1.82.0#4
  * boost-move:x64-windows -> 1.82.0#2
  * boost-mp11:x64-windows -> 1.82.0#2
  * boost-predef:x64-windows -> 1.82.0#2
  * boost-preprocessor:x64-windows -> 1.82.0#2
    boost-stacktrace:x64-windows -> 1.82.0#2
  * boost-static-assert:x64-windows -> 1.82.0#2
  * boost-throw-exception:x64-windows -> 1.82.0#2
  * boost-tuple:x64-windows -> 1.82.0#2
  * boost-type-traits:x64-windows -> 1.82.0#2
  * boost-uninstall:x64-windows -> 1.82.0#2
  * boost-unordered:x64-windows -> 1.82.0#2
  * boost-vcpkg-helpers:x64-windows -> 1.82.0#2
  * boost-winapi:x64-windows -> 1.82.0#2
    openssl:x64-windows -> 3.1.1#1
    openssl-windows:x64-windows -> deprecated
    pthread:x64-windows -> 3.0.0#2
  * pthreads:x64-windows -> 3.0.0#14
    rapidjson:x64-windows -> 2023-04-27
    re2:x64-windows -> 2023-02-01
  * vcpkg-cmake:x64-windows -> 2023-05-04
  * vcpkg-cmake-config:x64-windows -> 2022-02-06#1
  * vcpkg-cmake-get-vars:x64-windows -> 2023-03-02
    zlib:x64-windows -> 1.2.13
Additional packages (*) will be modified to complete this operation.
error: in triplet x64-windows: Unable to find a valid Visual Studio instance
Could not locate a complete Visual Studio instance
The following paths were examined for Visual Studio instances:
    C:\BuildTools\VC\Auxiliary/Build\vcvarsall.bat
`

**Triton Information**
What version of Triton are you using?
v2.19.0 and v2.40.0, both version shows same error.

Are you using the Triton container or did you build it yourself?
build myself using docker container, following the build instruction(https://github.com/triton-inference-server/server/blob/v2.40.0/docs/customization_guide/build.md#building-for-windows-10)

**To Reproduce**
Steps to reproduce the behavior.
`
$ git clone -b v2.40.0 https://github.com/triton-inference-server/server.git
$ cd server
$ docker build -t win10-1 -f Dockerfile.1 .
`

**Expected behavior**

**Comment by mc-nv** [comment]
We are aware of this issue, and looking into it.

**Comment by jinkilee** [comment]
Do you have any other recommendation to run tritonserver in windows 10? I already run with linux container on docker desktop, but it is very slow when i call request from the outside of the docker. This is why i tried to build natively on windows 10.

**Comment by mhbassel** [comment]
@jinkilee I could build triton on windows without using docker, but unfortunatelyI faced this [issue](https://github.com/triton-inference-server/server/issues/7636), 
I can give you some tips, but hopefully you won't end up with the same error, so at best would be someone who could build triton with some backend and successfully tested it already so they can give us the build instruction.

**Comment by mhbassel** [comment]
Voilà! fixed it, looks like it is related to the **vcpkg** version, I used version **2024.06.15** then it worked.

**Comment by mc-nv** [comment]
> [!NOTE] 
> Please note switching version of VCPKG will change version of the dependencies which are coming with it. 

We don't use VisualStudio in our build process only `BuildTools` that are provided by Microsoft for download.
As of this writing I would suggest to install `vs_BuildTools.exe` version `17.12 preview 2` as compiler.

**Comment by mhbassel** [comment]
yes @mc-nv, but I changed the version of VCPGK_VERSION variable in windows dockerfile, the one provided by nvidia, is that what are you talking about? 
and sticking to the 2023 version will cause this error mentioned here. I have no other solution, we need a windows docker image with onnx runtime urgently, therefore!
