### ISSUE TITLE
Incorrect asset tritonserver2.35.0-jetpack5.1.2-update-2.tgz

### ISSUE THREAD

**Issue by joachimhgg** [triton-inference-server/server#7294]
**Description**
cf. this page: https://github.com/triton-inference-server/server/releases/tag/v2.35.0

Hello, the asset `tritonserver2.35.0-jetpack5.1.2-update-1.tgz` has been replaced by the `tritonserver2.35.0-jetpack5.1.2-update-2.tgz` but this asset contains the wrong wheels: `tritonserver2.35.0-jetpack5.1.2-update-2/clients/python/tritonclient-2.34.0-py3-none-manylinux2014_aarch64.whl` instead of `tritonclient-2.35.0-py3-none-manylinux2014_aarch64.whl`

In addition, the link in the Jetson Jetpack Support section dead: `... is provided in the attached tar file: [tritonserver2.35.0-jetpack5.1.2.tgz](https://github.com/triton-inference-server/server/releases/download/v2.35.0/tritonserver2.35.0-jetpack5.1.2.tgz). `

Thank you for your support!

**Comment by mc-nv** [comment]
Package has been updated with corrected version
