### ISSUE TITLE
ONNX backend with TensorRT optimizer sometimes fails to start

### ISSUE THREAD

**Issue by ShuaiShao93** [triton-inference-server/server#7296]
**Description**
The server sometimes fails to start with error. Note that this is not deterministic, so sometimes fails and sometimes works
```
error: creating server: Invalid argument - load failed for model 'sentiment_model': version 1 is at UNAVAILABLE state: Invalid argument: failed to run warmup sample 'warmup': onnx runtime error 6: /workspace/onnxruntime/onnxruntime/core/providers/cuda/cuda_call.cc:121 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*, const char*, int) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t<THRW, void, onnxruntime::common::Status> = void] /workspace/onnxruntime/onnxruntime/core/providers/cuda/cuda_call.cc:114 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*, const char*, int) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t<THRW, void, onnxruntime::common::Status> = void] CUDNN failure 4000: unrecognized error code ; GPU=0 ; hostname=b8ba6e13da2b ; file=/workspace/onnxruntime/onnxruntime/core/providers/cuda/cuda_
```

What does this mean?

**Triton Information**
What version of Triton are you using?
2.45.0

Are you using the Triton container or did you build it yourself?
Triton container

**To Reproduce**
I'm not sure how to reproduce exactly, but we have multiple bert models with ONNX backend + TensorRT optimizer, and each of them has warmup

**Expected behavior**
If everything is correct, the server should always be able to start

**Comment by Tabrizian** [comment]
Hi @ShuaiShao93, could you please share more details? For example, it would be great to share the model and configuration so that we can try to reproduce this issue on our end.

**Comment by Tabrizian** [comment]
Closing due in-activity.
