### ISSUE TITLE
Segmentation fault when multi-requsts to triton-vllm 

### ISSUE THREAD

**Issue by tricky61** [triton-inference-server/server#7332]
my env is tritonserver23.11-py3:v1，when send the request one-by-one，the server is normal.
but when the client sends multi-requests to the server, after several iteration, it will crash.
The backend model is one vllm model and one onnx model.
The Error message is below

INFO 06-07 17:13:56 metrics.py:161] Avg prompt throughput: 195.7 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.1%, CPU KV cache usage: 0.0%
INFO 06-07 17:14:02 metrics.py:161] Avg prompt throughput: 1064.4 tokens/s, Avg generation throughput: 133.1 tokens/s, Running: 3 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 3.6%, CPU KV cache usage: 0.0%
INFO 06-07 17:14:07 metrics.py:161] Avg prompt throughput: 2102.7 tokens/s, Avg generation throughput: 146.2 tokens/s, Running: 4 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.5%, CPU KV cache usage: 0.0%
Signal (11) received.
 0# 0x0000559334F1667D in /opt/tritonserver/bin/tritonserver
 1# 0x00007FA5EAD8D520 in /usr/lib/x86_64-linux-gnu/libc.so.6
 2# TRITONBACKEND_ResponseFactoryIsCancelled in /opt/tritonserver/bin/../lib/libtritonserver.so
 3# 0x00007FA5D870E1B9 in /opt/tritonserver/backends/python/libtriton_python.so
 4# 0x00007FA5D871590D in /opt/tritonserver/backends/python/libtriton_python.so
 5# 0x00007FA5EB050253 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 6# 0x00007FA5EADDFAC3 in /usr/lib/x86_64-linux-gnu/libc.so.6
 7# clone in /usr/lib/x86_64-linux-gnu/libc.so.6

**Comment by tricky61** [comment]
seems this crash has no relation with onnx model, when I depoly onnx model to another model, the triton vllm also crash

**Comment by statiraju** [comment]
[6860] created for internal tracking

**Comment by statiraju** [comment]
@tricky61 can you please provide clear steps to repro the issue.

**Comment by rmccorm4** [comment]
Hi @tricky61, it's possible that this issue has been fixed since 23.11. Can you please try to reproduce with the latest 24.05 release?

**Comment by tricky61** [comment]
> @tricky61 can you please provide clear steps to repro the issue.

I am not sure this has relation with vllm version.
First, I use the tritonserver23.11-py3:v1 image to create the environment and install vllm==0.3.2, then I start tritonserver and send request to the server by c++ with TritonGrpcClient's AsyncStreamInfer.
when I use one thread send the request one-by-one， the program ends normal.
but when I use multi-thread to send the request, the tritonserver crash with the following message:
    Signal (11) received.
 0# 0x0000558937C7067D in /opt/tritonserver/bin/tritonserver
 1# 0x00007F719F78D520 in /usr/lib/x86_64-linux-gnu/libc.so.6
 2# TRITONBACKEND_ResponseFactoryIsCancelled in /opt/tritonserver/bin/../lib/libtritonserver.so
 3# 0x00007F71983B81B9 in /opt/tritonserver/backends/python/libtriton_python.so
 4# 0x00007F71983BF90D in /opt/tritonserver/backends/python/libtriton_python.so
 5# 0x00007F719FA50253 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 6# 0x00007F719F7DFAC3 in /usr/lib/x86_64-linux-gnu/libc.so.6
 7# clone in /usr/lib/x86_64-linux-gnu/libc.so.6

./start_vllm.sh: line 11:  4756 Segmentation fault      /opt/tritonserver/bin/tritonserver --trace-file=trace.json --trace-rate=0 --trace-level=TENSORS --model-repository model_repository。

the crash happens randomly, not at the beginning, sometimes the request can ends normally. but most time it will crash. the crash message seems not happend in the vllm's inference, but in the grpc send response.

**Comment by tricky61** [comment]
> Hi @tricky61, it's possible that this issue has been fixed since 23.11. Can you please try to reproduce with the latest 24.05 release?

I change the image to tritonserver:23.11-vllm-python-py3, but crash happens again.  Does this image limit vllm version？seems the default vllm version is 0.2.1？but I installed 0.3.2. Does this matter？
I am trying the 24.05, but the cuda version is 12.4, and the vllm version should not be 0.3.2, because of the torch version confict?

**Comment by rmccorm4** [comment]
The 24.05 triton+vllm container has vllm 0.4.0 post1 per the release notes: https://docs.nvidia.com/deeplearning/triton-inference-server/release-notes/rel-24-05.html#rel-24-05

It may contain some fixes to the GRPC frontend in Triton that you have observed compared to 23.11.

**Comment by tricky61** [comment]
> The 24.05 triton+vllm container has vllm 0.4.0 post1 per the release notes: https://docs.nvidia.com/deeplearning/triton-inference-server/release-notes/rel-24-05.html#rel-24-05
> 
> It may contain some fixes to the GRPC frontend in Triton that you have observed compared to 23.11.

changed to 24.05 and it seenms normal
Thanks for your help
