### ISSUE TITLE
Triton Tensorrt-LLM 24.04 and 24.05 are very large

### ISSUE THREAD

**Issue by yaysummeriscoming** [triton-inference-server/server#7335]
**Description**

Looking at the [catalog](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/tritonserver/tags), Triton containers 24.04 and 24.05 are very large, both coming in at ~18.5GB. 24.01-3 were ~8.5GB. Why is this? Is it something to do with the containers being built on previous versions of the Triton base container?

**Comment by statiraju** [comment]
We are aware of the current concerns with container size. The team is working on this with priority

**Comment by statiraju** [comment]
@nvda-mesharma for viz

**Comment by krishung5** [comment]
Hi @yaysummeriscoming, the TRT-LLM container has different dependency stack. Some packages like pytorch are required during runtime so the image size is larger than the other Triton images. We are improving the container size along with the releases. Closing this issue as we have internal tracker for the TRT-LLM image size. Thanks for bringing this up!

**Comment by yaysummeriscoming** [comment]
@krishung5 ok thanks, removing the dependency on Pytorch would be great too
