### ISSUE TITLE
Question about the `get_response()` function in the Python API's HTTP/REST Client

### ISSUE THREAD

**Issue by jackylu0124** [triton-inference-server/server#7354]
Hey all, I have a question regarding the `get_response()` function in the Python API's HTTP/REST Client, I see that in the client script for the [pytorch](https://github.com/triton-inference-server/python_backend/blob/main/examples/pytorch/client.py) and [add_sub](https://github.com/triton-inference-server/python_backend/blob/main/examples/add_sub/client.py) examples, we have a `result = response.get_response()` call (see [https://github.com/triton-inference-server/python_backend/blob/c8b188f26a4e80c7204baaf73e27f11c33f52f57/examples/pytorch/client.py#L58](https://github.com/triton-inference-server/python_backend/blob/c8b188f26a4e80c7204baaf73e27f11c33f52f57/examples/pytorch/client.py#L58) and [https://github.com/triton-inference-server/python_backend/blob/c8b188f26a4e80c7204baaf73e27f11c33f52f57/examples/add_sub/client.py#L58](https://github.com/triton-inference-server/python_backend/blob/c8b188f26a4e80c7204baaf73e27f11c33f52f57/examples/add_sub/client.py#L58)) before we extract the outputs with `response.as_numpy("OUTPUT0")` for example.

My question is: what is the purpose of the `result = response.get_response()` call before we extract the outputs with `as_numpy()`, and whether the `result = response.get_response()` call is necessary before we extract the outputs with `as_numpy()`; because I have tried removing the `response.get_response()` call, and have tried directly extracting the outputs with `as_numpy()` right after `infer()`, and I was able to extract the expected outputs.

Thank you very much for your time and help in advance!

**Comment by Tabrizian** [comment]
Thanks for the question @jackylu0124. Calling `get_response` is not required and directly calling `as_numpy` should work.
