### ISSUE TITLE
 nvcr.io: i/o timeout - error 401

### ISSUE THREAD

**Issue by davy-blavette** [triton-inference-server/server#7356]
I try to use the image:
`nvcr.io/nvidia/tritonserver:22.12-py3`

with the docker command :

```
FROM nvcr.io/nvidia/tritonserver:22.12-py3

# Install dependencies
RUN pip install opencv-python && \
    apt-get update && \
    apt-get install -y libgl1 && \
    rm -rf /var/lib/apt/lists/*

CMD ["tritonserver", "--model-repository=/models" ]
```

`docker build -t $DOCKER_NAME .`

but I have an access problem: 401 Authorization Required

`ERROR: failed to solve: nvcr.io/nvidia/tritonserver:22.12-py3: failed to resolve source metadata for nvcr.io/nvidia/tritonserver:22.12-py3: failed to do request: Head "https://nvcr.io/v2/nvidia/tritonserver/manifests/22.12-py3": dial tcp: lookup nvcr.io: i/o timeout`

the same with docker pull nvcr.io/nvidia/tritonserver:22.09-py3

If I use api key, the same 
`docker login nvcr.io
Username: $oauthtoken
Password: nvapi-Tl8emrOqWbVLFj...
`
`Error response from daemon: Get "https://nvcr.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`

if I use ngc config set
`[Errno -2] Name or service not known`

**Comment by davy-blavette** [comment]
ok it was a dns namespace problem...thanks ^^

**Comment by Samnonstop** [comment]
> ok it was a dns namespace problem...thanks ^^

Hi, not sure if you would see this, but I'll be much obliged if you can offer some information on this.

I might have ran into the same issue, though I was calling the `docker build` command using MONAI, the error message look the same as yours while pulling another image from the `nvcr.io/nvidia` repository. I tried logging in using the api key, as well as setting up a proxy, but still got the same error.

How did you solve the dns namespace problem? I looked into the daemon.json file and nothing seemed suspicious. Thanks.

**Comment by davy-blavette** [comment]
@Samnonstop, I had corrected by checking what I had with :
```
nmcli dev show | grep DN
cat /etc/resolv.conf
```

**Comment by Samnonstop** [comment]
> [@Samnonstop](https://github.com/Samnonstop), I had corrected by checking what I had with :
> 
> ```
> nmcli dev show | grep DN
> cat /etc/resolv.conf
> ```

Thank you for the response! I checked the DNS servers and there seemed to be no problem. There might be other issues I need to check, but thanks anyway. 😊
