### ISSUE TITLE
How to use pb_utils in python backend to receive data from cudashm？

### ISSUE THREAD

**Issue by sunkenQ** [triton-inference-server/server#7357]
I want to use pb_utils with dlpack in python backend to read the data transferred via cudashm, but I couldn't find it in the documentation or sample code. I read some python backend source code, and I found that pbTensor has a code related to Share Memory. Can someone provide a python code as a reference?

**Comment by Tabrizian** [comment]
The cuda shared memory should just work with Python backend. If you want to receive the inputs directly in GPU memory, please make sure to set `FORCE_CPU_ONLY_INPUT_TENSORS` to `no`. https://github.com/triton-inference-server/python_backend?tab=readme-ov-file#input-tensor-device-placement
