### ISSUE TITLE
Unable to use GPU in custom py3-igpu Docker image with S3 filesystem support

### ISSUE THREAD

**Issue by andreas-schliebitz** [triton-inference-server/server#7421]
**Description**
I would like to compile S3 filesystem support into the `24.06-py3-igpu` Docker image on an AGX Xavier using JetPack 5.1.2. For this I would like to reproduce the standard `py3-igpu` build as published in the NGC Catalog and simply add `--filesystem s3` to the corresponding `build.py` call. My build of the `py3-igpu` image with S3 support succeeds but the resulting container is unable to use the GPU. My custom container produces the following output:

```
NVIDIA Tegra driver detected.

W0705 20:55:51.369801 1 pinned_memory_manager.cc:273] "Unable to allocate pinned system memory, pinned memory pool will not be available: CUDA driver version is insufficient for CUDA runtime version"
I0705 20:55:51.370347 1 cuda_memory_manager.cc:117] "CUDA memory pool disabled"
I0705 20:55:51.695486 1 model_lifecycle.cc:472] "loading: densenet_onnx:1"
I0705 20:55:52.098957 1 onnxruntime.cc:2899] "TRITONBACKEND_Initialize: onnxruntime"
I0705 20:55:52.099029 1 onnxruntime.cc:2909] "Triton TRITONBACKEND API version: 1.19"
I0705 20:55:52.099037 1 onnxruntime.cc:2915] "'onnxruntime' TRITONBACKEND API version: 1.19"
I0705 20:55:52.099043 1 onnxruntime.cc:2945] "backend configuration:\n{\"cmdline\":{\"auto-complete-config\":\"true\",\"backend-directory\":\"/opt/tritonserver/backends\",\"min-compute-capability\":\"5.300000\",\"default-max-batch-size\":\"4\"}}"
I0705 20:55:52.116798 1 onnxruntime.cc:3010] "TRITONBACKEND_ModelInitialize: densenet_onnx (version 1)"
I0705 20:55:52.117761 1 onnxruntime.cc:983] "skipping model configuration auto-complete for 'densenet_onnx': inputs and outputs already specified"
I0705 20:55:52.136351 1 onnxruntime.cc:3075] "TRITONBACKEND_ModelInstanceInitialize: densenet_onnx_1 (CPU device 0)"
I0705 20:55:52.136566 1 onnxruntime.cc:3075] "TRITONBACKEND_ModelInstanceInitialize: densenet_onnx_0 (CPU device 0)"
I0705 20:55:52.479762 1 model_lifecycle.cc:838] "successfully loaded 'densenet_onnx'"
I0705 20:55:52.480183 1 server.cc:604]
```

Comparing this output to the working standard `py3-igpu` image from the NGC Catalog one can clearly see that there are no CUDA warnings and the GPU is used instead of the CPU (`device 0`):

```
NVIDIA Tegra driver detected.

I0705 20:27:21.380928 1 pinned_memory_manager.cc:277] "Pinned memory pool is created at '0x205547000' with size 268435456"
I0705 20:27:21.381429 1 cuda_memory_manager.cc:107] "CUDA memory pool is created on device 0 with size 67108864"
I0705 20:27:21.386721 1 model_lifecycle.cc:472] "loading: densenet_onnx:1"
I0705 20:27:21.389650 1 onnxruntime.cc:2899] "TRITONBACKEND_Initialize: onnxruntime"
I0705 20:27:21.389721 1 onnxruntime.cc:2909] "Triton TRITONBACKEND API version: 1.19"
I0705 20:27:21.389740 1 onnxruntime.cc:2915] "'onnxruntime' TRITONBACKEND API version: 1.19"
I0705 20:27:21.389756 1 onnxruntime.cc:2945] "backend configuration:\n{\"cmdline\":{\"auto-complete-config\":\"true\",\"backend-directory\":\"/opt/tritonserver/backends\",\"min-compute-capability\":\"5.300000\",\"default-max-batch-size\":\"4\"}}"
I0705 20:27:21.408288 1 onnxruntime.cc:3010] "TRITONBACKEND_ModelInitialize: densenet_onnx (version 1)"
I0705 20:27:21.409034 1 onnxruntime.cc:983] "skipping model configuration auto-complete for 'densenet_onnx': inputs and outputs already specified"
I0705 20:27:21.409975 1 onnxruntime.cc:3075] "TRITONBACKEND_ModelInstanceInitialize: densenet_onnx_0 (GPU device 0)"
I0705 20:27:21.751393 1 model_lifecycle.cc:838] "successfully loaded 'densenet_onnx'"
I0705 20:27:21.751812 1 server.cc:604]
```

I've also noticed, that the CUDA version in the official image is 12.2:

```
root@b86ba96b2e0e:/opt/tritonserver# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Aug_15_22:08:11_PDT_2023
Cuda compilation tools, release 12.2, V12.2.140
Build cuda_12.2.r12.2/compiler.33191640_0
```

Whereas `build.py` produces an image with CUDA 12.5:

```
root@72cd43e8f048:/opt/tritonserver# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Wed_Apr_17_19:24:55_PDT_2024
Cuda compilation tools, release 12.5, V12.5.40
Build cuda_12.5.r12.5/compiler.34177558_0
```

This might be the issue but I'm unsure how to force `build.py` to use a specific CUDA version.

**Triton Information**
I'm comparing the functionality of `nvcr.io/nvidia/tritonserver:24.06-py3-igpu` with my attempt of building the same image but with S3 support enabled.

Are you using the Triton container or did you build it yourself?
I'm using the Triton container and I try to build it myself.

**To Reproduce**

To pull and start the official image (works fine, but no S3 support):

```bash
docker run -d \
	-p 8000:8000 \
	-p 8002:8002 \
	--runtime=nvidia \
	--gpus all \
	-v ./model-repository:/models \
	--name tritonserver \
	nvcr.io/nvidia/tritonserver:24.06-py3-igpu \
	tritonserver --model-repository=/models
```

Now the attempt to reproduce the image with S3 support:

```bash
TRITON_VERSION="24.06"

cd triton/server \
    && git checkout "r${TRITON_VERSION}" \
    && python3 build.py \
        --target-platform igpu \
        --filesystem s3 \
        --target-machine aarch64 \
        --enable-metrics \
        --enable-logging \
        --enable-stats \
        --enable-cpu-metrics \
	--enable-tracing \
	--enable-mali-gpu \
	--enable-nvtx \
	--enable-gpu \
        --backend onnxruntime \
        --endpoint http \
	--min-compute-capability "5.3" \
  && docker tag tritonserver:latest tritonserver:${TRITON_VERSION}-igpu-s3
```

After the custom build has finished, I use the following command to instantiate my custom `24.06-igpu-s3` image:

```bash
TRITON_VERSION="24.06"

BUCKET_NAME="<redacted>"
AWS_ACCESS_KEY_ID="<redacted>"
AWS_SECRET_ACCESS_KEY="<redacted>"

docker run -d --runtime=nvidia --gpus all \
  -p 8000:8000 \
  -p 8002:8002 \
  -e AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}" \
  -e AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}" \
  -e AWS_DEFAULT_REGION='us-east-1' \
  --name tritonserver tritonserver:${TRITON_VERSION}-igpu-s3 \
  tritonserver --model-repository=s3://https://<redacted>:443/${BUCKET_NAME}/models
```

The S3 connection works fine, but as statet above, the model inference is not run on the GPU but on the CPU.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

I use the `densenet_onnx` example for inference which also works fine: https://github.com/triton-inference-server/server/tree/main/docs/examples/model_repository/densenet_onnx

**Expected behavior**
My custom image should behave like the official image in terms of GPU inference but with S3 support added.

**Comment by andreas-schliebitz** [comment]
Another possibility that I'm eager to try is adding `--image "gpu-base,nvcr.io/nvidia/tritonserver:${TRITON_VERSION}-py3-igpu"` to the call to `build.py`. That might just transfer the CUDA setup present in the official `py3-igpu` to my custom image.

**Comment by shahizat** [comment]
Hello @andreas-schliebitz , I'm experiencing the same issue with Nvidia AGX Orin, where I'm unable to compile with S3 support. Do you have a Dockerfile that you could share with me? I would greatly appreciate your help. Thanks in advance!

**Comment by andreas-schliebitz** [comment]
Hi @shahizat, I use the following shell script to build a certain version of Triton (in this case 24.07 by default) directly from this repository:

```bash
#!/usr/bin/env bash

TRITON_VERSION="${1}"
[[ -z "${TRITON_VERSION}" ]] && TRITON_VERSION="24.07"

DOCKER_REGISTRY_URL="<your-docker-registry-url>"

IMAGE_NAME="tritonserver"
OFFICIAL_MIN_IMAGE_TAG="${TRITON_VERSION}-py3-igpu-min"
CUSTOM_IMAGE_TAG="${TRITON_VERSION}-igpu-s3"

rm -rf triton; mkdir triton && cd triton \
        && git clone https://github.com/triton-inference-server/server.git \
        && cd server \
        && git checkout "r${TRITON_VERSION}" \
        && python3 build.py \
                --target-platform igpu \
                --target-machine aarch64 \
                --filesystem s3 \
                --enable-gpu \
                --enable-mali-gpu \
                --enable-metrics \
                --enable-logging \
                --enable-stats \
                --enable-cpu-metrics \
                --enable-nvtx \
                --backend onnxruntime \
                --backend pytorch \
                --backend tensorflow \
                --backend python \
                --backend tensorrt \
                --endpoint http \
                --min-compute-capability "5.3" \
                --image "base,nvcr.io/nvidia/${IMAGE_NAME}:${OFFICIAL_MIN_IMAGE_TAG}" \
                --image "gpu-base,nvcr.io/nvidia/${IMAGE_NAME}:${OFFICIAL_MIN_IMAGE_TAG}" \
        && docker tag "${IMAGE_NAME}:latest" "${DOCKER_REGISTRY_URL}/${IMAGE_NAME}:${CUSTOM_IMAGE_TAG}" \
        && docker push "${DOCKER_REGISTRY_URL}/${IMAGE_NAME}:${CUSTOM_IMAGE_TAG}"
```
This script will build, tag and push the image into a private (or public) Docker registry. You may omit the `docker push` if you only want to use the image locally.

In my case I had to execute the build process on an `aarch64` based system. If i recall correctly, the build failed on a standard `x86_64` system. I now use a second AGX device as my build server for newer Triton versions.

I hope this helps!

**Comment by shahizat** [comment]
Hello @andreas-schliebitz, thank you for your prompt and informative reply. I tried almost the same steps, but I always encounter an issue similar to the one shown below. I thought it might be an internet problem on my end. I will proceed with troubleshooting. I am running on the Nvidia AGX Orin 64GB Dev Kit. 

```
rror: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
error: 3014 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
fatal: clone of 'https://github.com/google/boringssl.git' into submodule path '/tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo/src/grpc/third_party/boringssl-with-bazel' failed
Failed to clone 'third_party/boringssl-with-bazel' a second time, aborting
CMake Error at /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo/tmp/grpc-repo-gitclone.cmake:62 (message):
  Failed to update submodules in:
  '/tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo/src/grpc'


gmake[2]: *** [_deps/repo-third-party-build/CMakeFiles/grpc-repo.dir/build.make:99: _deps/repo-third-party-build/grpc-repo/src/grpc-repo-stamp/grpc-repo-download] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:243: _deps/repo-third-party-build/CMakeFiles/grpc-repo.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
error: build failed
```

**Comment by andreas-schliebitz** [comment]
Hi @shahizat, looking at your error message my firtst reaction was "yes, this is probably an issue on your end". Most likely network and or git related. Just for your information, yesterday I was able to build the latest 24.08 version of Triton with the script I provided.

I hope you figure out the issue soon!

**Comment by shahizat** [comment]
Hello @andreas-schliebitz, I suspect that the issue is related to my ISP and git, as I've tried building multiple times and sometimes with some success. I'm also observed that the docker image may not have NCCL pre-built? See below logs. Thanks, I'll take a look at your Docker image.  

`UNAVAILABLE: Not found: unable to load shared library: libnccl.so.2: cannot open shared object file:     `

**Comment by shahizat** [comment]
hi @andreas-schliebitz, i mentioned you here, thanks for your help https://www.hackster.io/shahizat/triton-inference-server-on-nvidia-jetson-using-k3s-and-minio-cbcfe3
