### ISSUE TITLE
COUNTER in Custom metrics has no initial value.

### ISSUE THREAD

**Issue by harjol** [triton-inference-server/server#7435]
I am using triton python backend custom metrics function. I send some customize metrics to grafana. However I found that the COUNTER value has no initial value. All COUNTER should have initial value as 0, so that we can use rate function on it.

Here is the grafana metric:
![Screen Shot 2024-07-11 at 10 48 40](https://github.com/triton-inference-server/server/assets/2950247/33b97dc2-3832-4315-9a64-8337fb99afef)
All value here start from 1 directly, no 0 initial value.

My triton version is 24.05

I built triton docker by myself.

My code for metric is:
```
for metric in couter_metrics or []:
                setattr(
                    self,
                    metric.key + "_family",
                    pb_utils.MetricFamily(name=metric.key, description=metric.key, kind=pb_utils.MetricFamily.COUNTER),
                )
                setattr(
                    self,
                    metric.key,
                    getattr(self, metric.key + "_family")
                    .Metric(labels=metric.tags if metric.tags else {})
                    .increment(metric.value),
                )
```

The custom metrics should be the same as the other COUNTER metrics, start from ZERO. Like `nv_inference_request_success`
![Screen Shot 2024-07-11 at 10 52 07](https://github.com/triton-inference-server/server/assets/2950247/20e2cb16-f7eb-421f-9155-4e241c4c9263)

**Comment by GuanLuo** [comment]
In your code snippet, you create the metric and immediately increment the count. Have you tried create the metric entries during model initialization as shown in the example?
```
def initialize(self, args):
      # Create a MetricFamily object to report the latency of the model
      # execution. The 'kind' parameter must be either 'COUNTER' or
      # 'GAUGE'.
      self.metric_family = pb_utils.MetricFamily(
          name="preprocess_latency_ns",
          description="Cumulative time spent pre-processing requests",
          kind=pb_utils.MetricFamily.COUNTER # or pb_utils.MetricFamily.GAUGE
      )

      # Create a Metric object under the MetricFamily object. The 'labels'
      # is a dictionary of key-value pairs.
      self.metric = self.metric_family.Metric(
        labels={"model" : "model_name", "version" : "1"}
      )
```

**Comment by harjol** [comment]
Thanks. But there is a triky thing:
`Metric(labels=metric.tags if metric.tags else {})`
the labels here need some input params, but initialize function cannot accept any params, so that I cannot create them in initialization phase.
Is there any solution to it?

**Comment by GuanLuo** [comment]
I think `Metric()` is needed to expose the entry in Prometheus, so at the minimum you will create it as soon as the tags are determined, and increment the counter at a later point.
