### ISSUE TITLE
[New] Discord channel for triton-inference-server, tensorrt

### ISSUE THREAD

**Issue by geraldstanje** [triton-inference-server/server#7442]
Hi,

I noticed there is no slack, discord or irc channel for tensorrt - which could offload some future tickets by discussing things in the channel - so I created one.

I hope its ok to advertise the discord channel to discuss nvidia tensorrt, tensorrt-llm, triton inference server here: https://discord.gg/hrARsZjJ

Thanks,
Gerald

**Comment by rmccorm4** [comment]
Hi @geraldstanje, thanks for sharing! 

We have the [GitHub Discussions](https://github.com/triton-inference-server/server/discussions) open to support an official means of community discussion that the team can also engage with. Do you have any feedback or requests on how that could better be used to facilitate community discussion?

CC @dzier @dyastremsky @harryskim @meleegy

**Comment by hoohooprog** [comment]
hi. invitation link is invalid

**Comment by geraldstanje** [comment]
@hoohooprog updated link: https://discord.gg/xUEggt5xqn
