### ISSUE TITLE
Not able to perform multiple inferences on my ASR model

### ISSUE THREAD

**Issue by aryan1165** [triton-inference-server/server#7443]
**Description**
I have build my triton server v 2.36.0 with ASR ensemble model which has a preprocessor (TorchScript module) and tensor RT acoustic model. When i try to perform more than 1 inference, some shapes error in matrix multiplication occurs in the pre processor. Model compose mode is polling. When i changed this mode to explicit and loaded and unload my preprocessor before each inference it worked fine. I want to get rid of loading/unloading step for each iteration as it is just overhead, my other models in the ensemble work fine without any explicit loading/unloading.

Attaching the screenshots when model compose method is set to poll, and no loading /unloading of preprocessor is done.

<img width="1311" alt="Screenshot 2024-07-14 at 6 07 04 PM" src="https://github.com/user-attachments/assets/eb732c13-b096-4a08-a6c1-53963b4738ef">
<img width="1378" alt="Screenshot 2024-07-14 at 6 07 41 PM" src="https://github.com/user-attachments/assets/6b63219d-421e-46b7-a0e1-9866c7fdde83">
<img width="203" alt="Screenshot 2024-07-14 at 6 08 28 PM" src="https://github.com/user-attachments/assets/ccd9ce4c-1d41-4200-af5d-fe0607daa2b4">
<img width="1059" alt="Screenshot 2024-07-14 at 6 09 19 PM" src="https://github.com/user-attachments/assets/43b263b4-9ef1-4809-9e3b-412c916f9950">
<img width="1178" alt="Screenshot 2024-07-14 at 6 10 42 PM" src="https://github.com/user-attachments/assets/7ca5252a-f08d-4cf2-94e2-d4395b5a7b67">

Please explain, why it happens at first place, secondly is there any other workaround than loading/unloading the preprocessor each time?

I am also attaching the preprocessor, its architecture can be viewed [here](https://netron.app/).

[preprocessor.zip](https://github.com/user-attachments/files/16225127/preprocessor.zip)

**Comment by sourabh-burnwal** [comment]
@aryan1165 can you share everything in code-snippet format rather than screenshots? I will try to reproduce this.

**Comment by aryan1165** [comment]
Hi @sourabh-burnwal, Sorry for late reply. This issue got resolved, as the issue was with Libtorch backend's config file. Added DISABLE_OPTIMIZED_EXECUTION parameter as mentioned [here](https://github.com/triton-inference-server/pytorch_backend#parameters). 

New config file had 
```parameters: {
key: "DISABLE_OPTIMIZED_EXECUTION"
    value: {
    string_value: "true"
    }
}
