### ISSUE TITLE
Metric Endpoint not working for custom backend.

### ISSUE THREAD

**Issue by Kanupriyagoyal** [triton-inference-server/server#7451]
**Description**
 Metrics can then we queried using the Triton [metrics](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/metrics.md) and [statistics](https://github.com/triton-inference-server/server/blob/main/docs/protocol/extension_statistics.md) APIs isn't working with the custom backend.All Details are coming empty. Python backend it is working able to capture the metrics
Enabled flags:
-DTRITON_ENABLE_STATS:BOOL=ON \
-DTRITON_ENABLE_CUSTOM=ON \
-DTRITON_ENABLE_METRICS:BOOL=ON \
-DTRITON_ENABLE_METRICS_GPU:BOOL=OFF \
-DTRITON_ENABLE_METRICS_CPU:BOOL=ON \

MacBook-Pro ~ % curl x.xx.xx.xx:8002/metrics
```
# HELP nv_inference_request_success Number of successful inference requests, all batch sizes
# TYPE nv_inference_request_success counter
nv_inference_request_success{model="python_model",version="1"} 1
nv_inference_request_success{model="custom_model",version="0"} 0
# HELP nv_inference_request_failure Number of failed inference requests, all batch sizes
# TYPE nv_inference_request_failure counter
nv_inference_request_failure{model="python_model",version="1"} 0
nv_inference_request_failure{model="custom_model",version="0"} 0
# HELP nv_inference_count Number of inferences performed (does not include cached requests)
# TYPE nv_inference_count counter
nv_inference_count{model="python_model",version="1"} 3
nv_inference_count{model="custom_model",version="0"} 0
```

Statistics API response :
**Python Backend:**
```
 b'{"model_stats":[{"name":"python_model","version":"1","last_inference":1721207878173,"inference_count":3,"execution_count":1,"inference_stats":{"success":{"count":1,"ns":16186454},"fail":{"count":0,"ns":0},"queue":{"count":1,"ns":754755},"compute_input":{"count":1,"ns":151817},"compute_infer":{"count":1,"ns":14908516},"compute_output":{"count":1,"ns":353099},"cache_hit":{"count":0,"ns":0},"cache_miss":{"count":0,"ns":0}},"batch_stats":[{"batch_size":3,"compute_input":{"count":1,"ns":151817},"compute_infer":{"count":1,"ns":14908516},"compute_output":{"count":1,"ns":353099}}],"memory_usage":[]}]}'
```

**Custom Backend**
```
b'{"model_stats":[{"name":"custom_model","version":"1","last_inference":0,"inference_count":0,"execution_count":0,"inference_stats":{"success":{"count":0,"ns":0},"fail":{"count":0,"ns":0},"queue":{"count":0,"ns":0},"compute_input":{"count":0,"ns":0},"compute_infer":{"count":0,"ns":0},"compute_output":{"count":0,"ns":0},"cache_hit":{"count":0,"ns":0},"cache_miss":{"count":0,"ns":0}},"batch_stats":[],"memory_usage":[]}]}
```

**Triton Information**
What version of Triton are you using?
r23.12

Are you using the Triton container or did you build it yourself?

**To Reproduce**
Steps to reproduce the behavior.
Just Build a Custom backend using https://github.com/triton-inference-server/backend/blob/r23.12/examples/README.md#minimal-triton-backend
Enable the stats and metric flags
Try to capture the metrics for the inference.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**
If flags are enabled metric and stats endpoint should work for all custom backend

**Comment by Kanupriyagoyal** [comment]
@dyastremsky It would be great if you help here.Thank you !

**Comment by dyastremsky** [comment]
I think that you may need to implement some metrics APIs call in the custom backend itself, like you can see in the other backends (e.g. [the identity backend](https://github.com/triton-inference-server/identity_backend/blob/main/src/identity.cc)). Deferring to a couple of folks on the server team: @krishung5 and @rmccorm4.

**Comment by rmccorm4** [comment]
Hi @Kanupriyagoyal, are you calling [TRITONBACKEND_ModelInstanceReportStatistics](https://github.com/triton-inference-server/backend/blob/33be4466c3319d21daf2de9594cc13ef48aab7d8/examples/backends/recommended/src/recommended.cc#L724-L728) in your custom backend?

**Comment by Kanupriyagoyal** [comment]
@rmccorm4 How identity backend model_statistics working there is no implementation of [TRITONBACKEND_ModelInstanceReportStatistics](https://github.com/triton-inference-server/backend/blob/33be4466c3319d21daf2de9594cc13ef48aab7d8/examples/backends/recommended/src/recommended.cc#L724-L728) [here](https://github.com/triton-inference-server/identity_backend/blob/main/src/identity.cc) .
i did **TRITON_ENABLE_STATS=OFF**,  but still able to get metric results:
```
PASSED : Model statistics and Got status 200 and response as b'{"model_stats":[{"name":"custom_model","version":"1","last_inference":1721795691422,"inference_count":1,"execution_count":1,"inference_stats":{"success":{"count":1,"ns":446975},"fail":{"count":0,"ns":0},"queue":{"count":1,"ns":18445983891822169118},"compute_input":{"count":1,"ns":0},"compute_infer":{"count":1,"ns":0},"compute_output":{"count":1,"ns":0},"cache_hit":{"count":0,"ns":0},"cache_miss":{"count":0,"ns":0}},"batch_stats":[{"batch_size":0,"compute_input":{"count":1,"ns":0},"compute_infer":{"count":1,"ns":0},"compute_output":{"count":1,"ns":0}}],"memory_usage":[]}]}'
```

**Comment by Kanupriyagoyal** [comment]
I have implemented [TRITONBACKEND_ModelInstanceReportStatistics](https://github.com/triton-inference-server/backend/blob/33be4466c3319d21daf2de9594cc13ef48aab7d8/examples/backends/recommended/src/recommended.cc#L724-L728) and able to get the reports. Thanks!!

Is there any example of memory usage implementation:
[TRITONBACKEND_ModelInstanceReportMemoryUsage](https://github.com/triton-inference-server/core/blob/d2abb8bbf407bdc020639bf3d6a560735d9c3255/include/triton/core/tritonbackend.h#L1304)

**Comment by krishung5** [comment]
Yes, we have `TRITONBACKEND_ModelInstanceReportMemoryUsage`  implemented in [TRT backend](https://github.com/triton-inference-server/tensorrt_backend/blob/40a2b302388a92cf0c5eb6a70839371783c35115/src/tensorrt.cc#L335) and [Onnxruntime backend](https://github.com/triton-inference-server/onnxruntime_backend/blob/373bd88f7cd8ca441443fa39099b4d2f3777049a/src/onnxruntime.cc#L3113).

**Comment by rmccorm4** [comment]
For future reference, Github's search is pretty powerful, and a query like this can help find all the Triton repo's that use or reference this API:
`org:triton-inference-server TRITONBACKEND_ModelInstanceReportMemoryUsage`

Example search [here](https://github.com/search?q=org%3Atriton-inference-server+TRITONBACKEND_ModelInstanceReportMemoryUsage&type=code).

**Comment by Kanupriyagoyal** [comment]
Thanks @rmccorm4 @krishung5 for the reference, I was able to find the implementation earlier. Forgot to update. Thanks Again !!
