### ISSUE TITLE
Build Triton and Backends On Windows

### ISSUE THREAD

**Issue by mhbassel** [triton-inference-server/server#7551]
Hello! 

I am trying to build Triton on windows and get a simple **tritonserver.exe**. But regarding the backends, e.g. TensorFlow or PyTorch, I assume I should also build them on Windows in order to have them in the Triton executable, correct?

And if so, are there any docs or repos regarding this, similar to [tensorflow_backend](https://github.com/triton-inference-server/tensorflow_backend)?
If not, how I am supposed to integrate these backends in the executable?

Much appreciated for any help!
Thanks, Mo

**Comment by mhbassel** [comment]
Hi @krishung5,
Thanks a lot for the reply! 🙏

Oh, I see. So, does that mean it's not really worth trying to build it myself on Windows? I'm guessing I'm limited to using ONNX or TensorRT, right? Also, how does Python fit into this?

Thanks again for your help!

**Comment by krishung5** [comment]
@mhbassel Python backend windows support was added in this [PR](https://github.com/triton-inference-server/python_backend/pull/294). I will update the build.md doc to include Python backend.
> So, does that mean it's not really worth trying to build it myself on Windows?

Windows support require some changes to the code and the build script. There might be some issues when building those unsupported backends on Windows.

**Comment by mhbassel** [comment]
Hey @krishung5,

So it sounds like I should stick to ONNX or TensorRT if I want to keep things smooth on Windows.
And about Python—thanks for the heads-up on that PR! I’ll definitely check out the updated docs once they’re available.

Appreciate the guidance!
Thanks again! 😄
