### ISSUE TITLE
How is the order determined for loading a model onto a specific device?

### ISSUE THREAD

**Issue by mhbassel** [triton-inference-server/server#7558]
How does Triton Server determine the order of loading models onto specific devices, such as a GPU? For instance, if there isn't enough VRAM available for all models, how does the server decide which models to load on the GPU and which ones to fall back to the CPU?

**Comment by Tabrizian** [comment]
If there isn't enough memory available the server would simply error out and exit. Currently, there is no logic for falling back to CPU memory if GPU loading fails.

**Comment by mhbassel** [comment]
Thanks @Tabrizian for your answer!

Ok clear, but What if Triton did not find enough memory to load model_2 on GPU (because model_1 is already loaded there) and instead it loaded it on the CPU (KIND_AUTO), here how the model determined that the model_1 is going to be put on GPU, why not model_2, assuming both are using KIND_AUTO?

**Comment by mhbassel** [comment]
aaaaah! I got it wrong the whole time for a year, gotta tell my team about that. 
Anyway, thanks a lot for your explanation, we will try to figure out how to prioritize them then.
