### ISSUE TITLE
Github login issue while building tritonserver without docker

### ISSUE THREAD

**Issue by ddoddii** [triton-inference-server/server#7569]
**Description**

I used the command below to build a tritonserver without docker, using r23.02 version.

```
python3 build.py --enable-logging --enable-stats --enable-tracing --enable-metrics --filesystem=gcs --filesystem=s3 --endpoint=http --endpoint=grpc --repo-tag=common:r23.02 --repo-tag=core:r23.02 --repo-tag=backend:r23.02 --repo-tag=thirdparty:r23.02 --backend=custom --backend=ensemble --backend=onnxruntime:r23.02
```

But this message popped up to login to github. I logged in using my username and github token, but the below error occurs. 

<img width="918" alt="image" src="https://github.com/user-attachments/assets/af413a92-539b-4a35-95a4-1fa7326792b7">

**Triton Information**
What version of Triton are you using?
r23.02

Are you using the Triton container or did you build it yourself?
- Error occurred while building tritonserver myself.

**To Reproduce**
Steps to reproduce the behavior.

1. git clone 

`git clone -b r23.02 --single-branch https://github.com/triton-inference-server/server.git server`

2. Run build.py

```
python3 build.py --enable-logging --enable-stats --enable-tracing --enable-metrics --filesystem=gcs --filesystem=s3 --endpoint=http --endpoint=grpc --repo-tag=common:r23.02 --repo-tag=core:r23.02 --repo-tag=backend:r23.02 --repo-tag=thirdparty:r23.02 --backend=custom --backend=ensemble --backend=onnxruntime:r23.02
```

**Expected behavior**
I cannot find the github login part in the document.

**Comment by Tabrizian** [comment]
Please remove "--backend=custom". There is no custom backend repository in Triton.
