### ISSUE TITLE
Triton server 24.08 has package versions different from announcement

### ISSUE THREAD

**Issue by dhruvmullick** [triton-inference-server/server#7581]
**Description**
As per the [announcement](https://github.com/triton-inference-server/server/releases/tag/v2.49.0) and [support matrix](https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html), triton images should have torch [2.5.0a0+872d972e41](https://github.com/pytorch/pytorch/commit/872d972e41596a9ac94dfd343f40bfc12b340a74) and TensorRT-LLM 0.12.0 

However, the nvcr.io/nvidia/tritonserver:24.08-trtllm-python-py3 image actually has: 
torch==2.4.0a0+3bcc3cddb5.nv24.7
tensorrt_llm==0.12.0.dev2024080600

There's a version inconsistency. 

**Triton Information**
nvcr.io/nvidia/tritonserver:24.08-trtllm-python-py3

Are you using the Triton container or did you build it yourself?
-> Using the official container 

**To Reproduce**
1. sudo docker pull nvcr.io/nvidia/tritonserver:24.08-trtllm-python-py3
2. sudo docker run -it nvcr.io/nvidia/tritonserver:24.08-trtllm-python-py3 bash
3. pip show tensorrt_llm
4. pip show torch

**Expected behavior**
Consistent package versions

**Comment by dhruvmullick** [comment]
Tagging @pvijayakrish

**Comment by krishung5** [comment]
Hi @dhruvmullick, the 24.08 TRT-LLM container is actually based on 24.07 dependency stacks to align with the dependencies supported by TRT-LLM. Please refer to the `Triton TRT-LLM Container Support Matrix` section in the [release note](https://github.com/triton-inference-server/server/releases/tag/v2.49.0). The torch version of 24.07 would be `2.4.0a0+3bcc3cddb5`.

**Comment by dhruvmullick** [comment]
Thank you @krishung5!
