### ISSUE TITLE
Implementing early exit in ensemble models

### ISSUE THREAD

**Issue by ash2703** [triton-inference-server/server#7589]
Possibly a duplicate of https://github.com/triton-inference-server/server/issues/3483
I have an ensemble model for an OCR service, with 2 major components the detector and recognizer with pre/post-processing scripts before and after inference completes

I am trying to find a way to somehow early exit and return response to client if no bounding boxes are detected in the detector stage to avoid wasting time in recognition pre/infer/post processing

I believe BLS is the way to go but not pretty sure how, for the moment I am raising an exception when this happens in the detector post processing python backend, but there are few other conditionals which I would like to implement and raising exceptions might not be the best way to go about it.

Looking for something where I can break the flow of the ensemble and directly skip to the last layer, or return response from an intermediate stage itself.

**Comment by ash2703** [comment]
Should I route the inference request via BLS rather than making an ensemble?

**Comment by Tabrizian** [comment]
You can return an error in ensemble and that would stop the execution of the rest of the pipeline.
