### ISSUE TITLE
When downloading, execute  ./fetch_models.sh the report

### ISSUE THREAD

**Issue by xzlinux** [triton-inference-server/server#7608]
Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/root/.wget-hsts'. HSTS will be disabled.
--2024-09-09 16:41:15--  https://contentmamluswest001.blob.core.windows.net/content/14b2744cf8d6418c87ffddc3f3127242/9502630827244d60a1214f250e3bbca7/08aed7327d694b8dbaee2c97b8d0fcba/densenet121-1.2.onnx

**Comment by oandreeva-nv** [comment]
Hi @xzlinux , Could you please clarify the issue you've encountered? Here's the template:
```
**Description**
A clear and concise description of what the bug is.

**Triton Information**
What version of Triton are you using?

Are you using the Triton container or did you build it yourself?

**To Reproduce**
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**
A clear and concise description of what you expected to happen.
```

**Comment by rmccorm4** [comment]
Hi @xzlinux, the densnet onnx model link was broken and was recently fixed here: https://github.com/triton-inference-server/server/pull/7621, please try the new link.
