### ISSUE TITLE
./fetch_models.sh - unable to resolve host address

### ISSUE THREAD

**Issue by surprisedPikachu007** [triton-inference-server/server#7630]
**Description**
when running ./fetch_models.sh in server/docs/examples, I get an error: unable to resolve host address when downloading onnx densenet model

**Triton Information**
What version of Triton are you using?
24.08-py3

Are you using the Triton container or did you build it yourself?
pulled in from NGC (nvcr.io/nvidia/tritonserver:24.08-py3)

**To Reproduce**
Clone the repo and run ./fetch_models.sh in server/docs/examples

**Temporary Solution**
replace the model link with other working link. I used [onnx model from official repo](https://github.com/onnx/models/raw/refs/heads/main/validated/vision/classification/densenet-121/model/densenet-12.onnx?download=)

**Comment by albpedmul** [comment]
This might help:This file might fix it
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
If you don't have the c compliator, install it.(gcc or clang)

**Comment by rmccorm4** [comment]
Hi @surprisedPikachu007, the broken onnx model link was recently fixed here: https://github.com/triton-inference-server/server/pull/7621. Please try the new link.
