### ISSUE TITLE
Triton ensemble LLM model (Llama 3.1 8B Instruct) returns prompt in the output

### ISSUE THREAD

**Issue by alvaroalfaro612** [triton-inference-server/server#7665]
**Description**
The model is returning the prompt again,and after that, the generated content.

**Triton Information**
24.08 container. LLM tensorRT create with tensorRT 0.12.0.

**To Reproduce**
1. `python3 test/TensorRT-LLM-0.12.0/examples/llama/convert_checkpoint.py --model_dir test/Meta-Llama-3.1-8B-Instruct/   --output_dir test/meta-chkpt --dtype bfloat16
`
2. `trtllm-build    --checkpoint_dir test/meta-chkpt/ \
				--output_dir test/llama-3.1-engine/ \
				--gemm_plugin bfloat16 \
				--max_seq_len  12288`

3. Deploy as ensemble model
4. Send http request to the model endpoint (/v2/models/ensemble/generate)
```
{
"text_input": "        <|begin_of_text|>   <|start_header_id|>system<|end_header_id|>        You are a JSON generator. Provide only an answer with just and only the requested JSON.        <|eot_id|>        <|start_header_id|>user<|end_header_id|>        What is the capital of Spain <|eot_id|>       <|start_header_id|>assistant<|end_header_id|>",
"parameters": {
"max_tokens": 50,
"bad_words":[""],
"stop_words":[""]
}
}
```

**Expected behavior**
In ·text_output", I would expect to receive only the generated text, without the prompt again. Currently, what I get: 

```
{
    "batch_index": 0,
    "context_logits": 0.0,
    "cum_log_probs": 0.0,
    "generation_logits": 0.0,
    "model_name": "ensemble",
    "model_version": "1",
    "output_log_probs": [
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0
    ],
    "sequence_end": false,
    "sequence_id": 0,
    "sequence_start": false,
    "text_output": "           system        You are a JSON generator. Provide only an answer with just and only the requested JSON.                user        What is the capital of Spain        assistant        {\n  \"capital\": \"Madrid\"\n}"
}
```

**Comment by oandreeva-nv** [comment]
Hi @alvaroalfaro612 , thanks for your question. Could you please check that `exclude_input_in_output` parameter in the `config.pbtxt`: https://github.com/triton-inference-server/tensorrtllm_backend/blob/8ffb174c0fe88e677eeed7928348e20be548f3f6/all_models/inflight_batcher_llm/tensorrt_llm/config.pbtxt#L477 
is set to `True` ?

**Comment by alvaroalfaro612** [comment]
Yes,that was the problem! Thank you very much!
