### ISSUE TITLE
Dynamic batching not working with TRT-LLM backend

### ISSUE THREAD

**Issue by ShuaiShao93** [triton-inference-server/server#7676]
**Description**
With dynamic batching enabled, and max_batch_size set to 64 for trtllm-backend, it never batches the requests even when there are requests in the queue.

**Triton Information**
What version of Triton are you using?
24.09

Are you using the Triton container or did you build it yourself?
Container

**To Reproduce**
1. Compile LLAMA3.1 8B Instruct to trt llm
2. Fill template with command
```
python3 tools/fill_template.py -i all_models/inflight_batcher_llm/tensorrt_llm/config.pbtxt triton_backend:tensorrtllm,triton_max_batch_size:64,decoupled_mode:False,max_beam_width:1,engine_dir:${ENGINE_PATH},max_tokens_in_paged_kv_cache:2560,max_attention_window_size:2560,kv_cache_free_gpu_mem_fraction:0.5,exclude_input_in_output:True,enable_kv_cache_reuse:False,batching_strategy:inflight_fused_batching,max_queue_delay_microseconds:0
```
3. Start triton with all_models/inflight_batcher_llm/ensemble
4. Use a multi-threaded client to send multiple requests in parallel
5. Check the logs, found this
```
I1002 23:45:42.282246 136 model_instance_state.cc:1115] "{\"Active Request Count\":8,\"Iteration Counter\":6189,\"Max Request Count\":8,\"Runtime CPU Memory Usage\":3060,\"Runtime GPU Memory Usage\":1427313739,\"Runtime Pinned Memory Usage\":637534388,\"Timestamp\":\"10-02-2024 23:45:42.275675\",\"Context Requests\":0,\"Generation Requests\":1,\"MicroBatch ID\":0,\"Paused Requests\":0,\"Scheduled Requests\":1,\"Total Context Tokens\":0,\"Free KV cache blocks\":25,\"Max KV cache blocks\":40,\"Tokens per KV cache block\":64,\"Used KV cache blocks\":15,\"Reused KV cache blocks\":0}"
```

**Expected behavior**
When `Active Request Count` is greater than 1, `Scheduled Requests` should also be greater than 1

**Comment by ShuaiShao93** [comment]
Ok it turns out max_tokens_in_paged_kv_cache was throttling the batch size

**Comment by xxchauncey** [comment]
hi, 
I ran into the similar problem. I used the example inflight_batching_llm config and sent grpcclient async requests but found that "Active Request Count" and "Scheduled Requests" were both always 1. It's pretty wired. Do I need to set "max_tokens_in_paged_kv_cache" or just use default value?

**Comment by xxchauncey** [comment]
ok, I may know what happened. I only let LLM generate 1 output token and it only cost 10ms to consume a request. If I increase output length, it will be normal.

> hi, I ran into the similar problem. I used the example inflight_batcher_llm config and sent 64 grpcclient async requests but found that "Active Request Count" and "Scheduled Requests" were both always 1.
> 
> That's pretty wired. I think the inflight batching is invalid since I set the batch size to 64, and I observed latencies list is like [10ms, 20ms, 30ms... 640ms, 10ms, 20ms....], which means that every request is waiting for previous one to be completed.
> 
> Btw, I set "max_tokens_in_paged_kv_cache" by default value.
> 
> Need help!
