### ISSUE TITLE
Wget onnx model fails for end-to-end example

### ISSUE THREAD

**Issue by shenj68** [triton-inference-server/server#7716]
**Description**

executing the ./fetch_models.sh script or manually using the wget command does not download the onnx model for the end-to-end example.

![image](https://github.com/user-attachments/assets/a801fda0-cdb0-45c5-8b15-68b3cf827b62)

**Triton Information**
What version of Triton are you using?
v2.50.0 (downloaded source files from release tag)

Are you using the Triton container or did you build it yourself?
built myself

**To Reproduce**
Steps to reproduce the behavior.
run ./fetch_models.sh at ~/server-2.50.0/docs/examples 
or 
follow these commands on the end-to-end example:

mkdir -p ./models/densenet_onnx/1

wget -O models/densenet_onnx/1/model.onnx
https://contentmamluswest001.blob.core.windows.net/content/14b2744cf8d6418c87ffddc3f3127242/9502630827244d60a1214f250e3bbca7/08aed7327d694b8dbaee2c97b8d0fcba/densenet121-1.2.onnx

**Expected behavior**
To download the same model used for the end-to-end example in the docs.

**Comment by rmccorm4** [comment]
Hi @shenj68, the broken onnx model link was recently fixed here: https://github.com/triton-inference-server/server/pull/7621. Please try the new link.
