### ISSUE TITLE
No content returned with OpenAI-Compatible Frontend Beta

### ISSUE THREAD

**Issue by Loc8888** [triton-inference-server/server#7724]
**Description**
I am testing the OpenAI-Compatible Frontend service (https://github.com/triton-inference-server/server/blob/main/python/openai/README.md) with a custom built TensorRT model. When I send a request to the service I get a response but there is no generated text in the content field.

**Triton Information**
Are you using the Triton container or did you build it yourself?  I am using `nvcr.io/nvidia/tritonserver:24.08-trtllm-python-py3` as the base image and installing the additional dependencies as listed in the README above.

**To Reproduce**
Start the server from within the container:
```
python3 openai_frontend/main.py \
  --model-repository /workspace/final_model \
  --tokenizer /workspace/hub/models--microsoft--phi-2/snapshots/ef382358ec9e382308935a992d908de099b64c23 \
  --backend tensorrtllm \
  --openai-port 9000
```
Send a HTTP request from another terminal:
```
curl \
  -w '\nTotal: %{time_total}s\n' \
  -s http://localhost:9000/v1/chat/completions \
  -H 'Content-Type: application/json' \
  -d '{"model": "ensemble", "messages": [{"role": "user", "content": "What is machine learning?"}]}'
```
Reponse (note the lack of text in the content field and the speed of the response):
```
{"id":"cmpl-3d5c1526-8faf-11ef-a5df-0242ac110002","choices":[{"finish_reason":"stop","index":0,"message":{"content":"","tool_calls":null,"role":"assistant","function_call":null},"logprobs":null}],"created":1729516828,"model":"ensemble","system_fingerprint":null,"object":"chat.completion","usage":null}

Total: 0.003654s
```
As a sanity check, I can get generated text if I use the Triton Server bindings in Python (https://github.com/triton-inference-server/server/blob/main/docs/customization_guide/tritonfrontend.md) using the same container:
```Python
import tritonserver
import numpy as np

# Constructing path to Model Repository
model_path = f"/workspace/final_model"

server_options = tritonserver.Options(
    server_id="ExampleServer",
    model_repository=model_path,
    log_error=True,
    log_warn=True,
    log_info=True,
    )

server = tritonserver.Server(server_options).start(wait_until_ready=True)

model = server.model("ensemble")

responses = model.infer(inputs={"text_input": [["What is machine learning?"]], \
        "return_context_logits": [[False]], \
        "return_log_probs": [[False]], \
        "max_tokens": np.array([[100]], dtype=np.int32)})

for response in responses:
    print(response.outputs['text_output'].to_bytes_array()[0].decode("utf-8"))
```
Output:
```
Machine learning is a type of artificial intelligence that allows computers to learn from data and improve their performance without being explicitly programmed. Machine learning algorithms can find patterns, make predictions, and optimize decisions based on the data they are given. Machine learning can be used for various applications, such as image recognition, natural language processing, recommendation systems, and self-driving cars.
```
From the speed of the cURL response (`0.003654s`), it appears that the service isn't waiting for the generated content. Perhaps there's an issue here https://github.com/triton-inference-server/server/blob/main/python/openai/openai_frontend/engine/triton_engine.py#L151?

**Expected behavior**
Generated text within the content field of the response instead of nothing.

**Comment by Loc8888** [comment]
I found a solution. Using `tensorrt_llm_bls` instead of `emsemble` fixed it.

**Comment by geraldstanje** [comment]
hi, does triton inference also work with openai frontend when i use python backend for triton inference server?
