### ISSUE TITLE
wget: unable to resolve host address ‘contentmamluswest001.blob.core.windows.net’

### ISSUE THREAD

**Issue by ST-q** [triton-inference-server/server#7746]
**Description**
When I run the ./fetch_models.sh script to load models, I found that the branch I'm on resolves to an unreachable address, while the main branch can correctly resolve and download the ONNX model. Why is this happening? I have try different machine like wsl2_ubuntu20.04 ,  wsl2_ubuntu24.04 , jetson orin nx_jetpack5.1.3 .  I also try different branches like r24.09 r22.12.
branches images like this 
![b01375502acdacacc0ccf9fd8e4c6dd](https://github.com/user-attachments/assets/53169206-bc51-4756-8907-b76fd8b6406b)
and main like this 
![3581c0e43310ccc4d9bc471b9c9a5b1](https://github.com/user-attachments/assets/79b8173c-6a52-4044-8f05-4f95a9789f10)

**Comment by GuanLuo** [comment]
The older release branches downloads the models from a broken link, which was recently fixed by using a different link https://github.com/triton-inference-server/server/pull/7621
