### ISSUE TITLE
ensemble logic control

### ISSUE THREAD

**Issue by xiazi-yu** [triton-inference-server/server#7749]
Here is a scenario: For vehicle license plate recognition, when there is no license plate target, I want to terminate the subsequent pipeline execution early, but I still want to be able to obtain the coordinates of the vehicle. How can this logic be handled?

**Comment by rmccorm4** [comment]
Hi @xiazi-yu, this is exactly the use case for [Business Logic Scripting (BLS)](https://github.com/triton-inference-server/python_backend?tab=readme-ov-file#business-logic-scripting), please check it out.
